### ISSUE TITLE
New XBB.1.5.57 + N:S194P sublineage with S:F456L appeared in Spain (12 sequences all from April ahead)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#10]
I mentioned this one briefly in the main pango github page : https://github.com/cov-lineages/pango-designation/issues/1949 ith @krosa1910, but it has grown further since so  a pre proposal is deserved:
 

Def muts: XBB.1.5.57 + A18333G,  N_S194P (T28853C)  >> C26681T > C1594T > Orf1a:L2620I (C8123A) >Orf1a:G934S (G3065A) > C1853T, S:F456L (T22928C)  

Gisaid Query : N_S194P, Spike_F456L

Sequences: EPI_ISL_17469836, EPI_ISL_17469840, EPI_ISL_17504402,
EPI_ISL_17504404-17504406, EPI_ISL_17505609, EPI_ISL_17505611,
EPI_ISL_17540248, EPI_ISL_17597796, EPI_ISL_17597801,

Tree:
![Schermata 2023-05-06 alle 19 39 08](https://user-images.githubusercontent.com/87669813/236638956-ef737200-bf34-4182-ae6c-d1613dc24210.png)

![Schermata 2023-05-06 alle 19 39 27](https://user-images.githubusercontent.com/87669813/236638965-b6cfc15c-7b5c-4b54-ab8a-b54982f592b7.png)

 
![Schermata 2023-05-06 alle 19 39 46](https://user-images.githubusercontent.com/87669813/236638972-b5a6ed07-5516-4f5c-9ba0-c6a79f6d7969.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_395c0_68f9e0.json?c=gt-S_456&label=id:node_5921924

Note that XBB.1.5.57 is in the pre T17124C branch of XBB.1.5 and it is likely the parental lineage of XBL

**Comment by krosa1910** [comment]
Is this the new platform to submit issues?
If so could someone help relocate my issue 1984 in the original respitory here?

**Comment by FedeGueli** [comment]
hi @krosa1910 this repo is for very small, uncertain, low priority or artefact dubious lineages or for discussions on everything is linked tona lineage/mutation spotted.

This helps to keep the designation work lighter.
Obviously if something is growing and will be highlighted by the community that will be open in the main page by the author and closed here.
It is like a two tiers system. 


Just copy and paste here the link to the issue in the main pango github. and the title..

This is for lineages with less chance to be fast designated , or without spike mutations or without already known significant mutation or alteady clear growth (for an example : a small.intetesting lineage from a very slow sequencer countr

**Comment by FedeGueli** [comment]
One more sample, from Singapore.

**Comment by FedeGueli** [comment]
No new sequences as today. ill keep this open till  next week

**Comment by FedeGueli** [comment]
Closing this for now
