### ISSUE TITLE
BF.29 or BA.5.2.1 potential chronic or saltation?

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#100]
Proposal for a sublineage of BF.29/BA.5.2.1
Earliest sequence: 27.10.2022 (Scotland)
Countries detected: Scotland

Potential chronic or saltation?

Defining Mutations:
nuc	unique	A686T, G688C, T692A, T4615C, A12759G, A13559G, C21648G, T22197C, A26786T, G27541A, C27697T, C27925A, C254T, G443A, G569A, G1018A, C5178T, T6791C, G14202A, C15108T, G17122A, G17749A, C24912T, G25145A, T25705C
nuc	homoplasies	C2700T, C4230T, C12534T, C26029A, T26171A, C28473T, C28677T, G17242A, C17766T
ORF1ab	unique	K141Y, F143I, D4165G, D4432G, V60I, E102K, T1638I, A5620T, A5829T
ORF1ab	homoplasies	T812I, T1322I, T4090I, A5660T
S	unique	T29S, L212S, T1117I, E1195K
ORF3a	homoplasies	Q213K, I260K, F105L
ORF7a	unique	A50T, L102F
ORF8	unique	T11K
N	homoplasies	P67L, T135I

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/5503f9e6-cda4-4268-88c6-79d2f0bd3f88)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/4a952e71-4a8c-4b08-be13-d5f99c2fd628)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_181f7_9a8f0.json?c=gt-S_1117

EPI_ISL_15926723, EPI_ISL_17299688, EPI_ISL_17716296

**Comment by ryhisner** [comment]
I'd be very surprised if this wasn't a single patient. One interesting aspect: the second branch was definitely created by molnupiravir treatment. 15/15 nucleotide mutations are transitions, 8/15 G->A and 5/15 C->T. There's no question about it. The second long branch, on the other hand, is a typical chronic-infection branch and has no molnupiravir signature. 

Below is my summary of the molnupiravir branch. The fact that this individual is still infected seven months later does not inspire confidence in the ability of molnupiravir to treat immunocompromised individuals or those suffering chronic infections. 
<img width="1265" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c1c3ff8c-c909-42e7-a6d4-f84442b432de">

**Comment by agamedilab** [comment]
@ryhisner do you maintain a list with all the potential molnupiravir cases?

**Comment by ryhisner** [comment]
@agamedilab, yes, I keep a list of the ones I find. I don't know how to code or do anything automated, so it's just the ones I find manually. It's well over 400 sequences now, and a number of them involve multiple sequences.

**Comment by agamedilab** [comment]
@ryhisner do you think it would be worth making a public collection e.g. on covspectrum?

**Comment by ryhisner** [comment]
I wasn't aware there was any way to make a list of actual sequences on CovSpectrum. In any case, I don't think it would be possible to include the molnupiravir-relevant information in any list, and I spend altogether too much time maintaining lists already (mainly of molnupiravir sequence and non-MOV chronic-infection/hypermutated sequences). 
Send me an email. rhisner@gmail.com
