### ISSUE TITLE
 XBB.1.16 with S:V1230A, ORF1a:S994N (nsp3_S994N), S:Q613H and S:Q675K (184 seqs, mainly in Russia, 12 countries) - > 10% in Russia in October

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1000]
**Defining Mutations:**  `XBB.1.16` > `T13518C` > `T17250G` > `T25251C(S:V1230A)` > `G3246A(ORF1a:S994N), G23401T(S:Q613H), C23585A(S:Q675K)`
**Query:** `T13518C, T17250G , G23401T`
**Earliest seq:** 2023-07-28 (`EPI_ISL_18417219`, Kovylkino, Mordovia, Russia)
**Latest seq:** 2023-10-09 (`EPI_ISL_18416738`, Saint Petersburg, Russia)
**Sampled Countries:** Russia (66: SPE/41; MOW/19; MO/2; TYU/2; SAR/1), Austria (1), China (1: ex. Russia), Kazakhstan (1), Spain (1), USA (1: FL)

<details><summary>Genomes: </summary>

`EPI_ISL_18078437, EPI_ISL_18238343-18238344, EPI_ISL_18238350, EPI_ISL_18238352, EPI_ISL_18317229, EPI_ISL_18360222, EPI_ISL_18406327, EPI_ISL_18411852, EPI_ISL_18416733, EPI_ISL_18416738-18416739, EPI_ISL_18416759, EPI_ISL_18416762, EPI_ISL_18416859, EPI_ISL_18416865, EPI_ISL_18416869, EPI_ISL_18416881, EPI_ISL_18416885-18416886, EPI_ISL_18416893, EPI_ISL_18416900, EPI_ISL_18416914, EPI_ISL_18416923, EPI_ISL_18416925, EPI_ISL_18416937, EPI_ISL_18416953-18416954, EPI_ISL_18416956, EPI_ISL_18417026, EPI_ISL_18417094, EPI_ISL_18417100-18417101, EPI_ISL_18417103, EPI_ISL_18417106, EPI_ISL_18417112-18417113, EPI_ISL_18417121, EPI_ISL_18417136, EPI_ISL_18417146, EPI_ISL_18417160-18417161, EPI_ISL_18417170, EPI_ISL_18417179, EPI_ISL_18417187, EPI_ISL_18417189, EPI_ISL_18417192, EPI_ISL_18417195, EPI_ISL_18417208, EPI_ISL_18417210, EPI_ISL_18417213, EPI_ISL_18417219-18417220, EPI_ISL_18417355, EPI_ISL_18417366, EPI_ISL_18417370, EPI_ISL_18417381, EPI_ISL_18417384-18417385, EPI_ISL_18417387, EPI_ISL_18417389, EPI_ISL_18417397, EPI_ISL_18417405, EPI_ISL_18417411, EPI_ISL_18417415, EPI_ISL_18417419, EPI_ISL_18417424, EPI_ISL_18417426, EPI_ISL_18417468, EPI_ISL_18417569, EPI_ISL_18417610`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4a4a_4bc4c0.json?f_userOrOld=uploaded%20sample&label=id:node_3261462
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3a4fd169-1db0-4b9b-ba82-dab0355c3312)

**Trivia:**
- Previously mentioned in #897 , quite a propotion from the most recent Russian batch but hard to calculate the growth.

**Comment by FedeGueli** [comment]
Ping @corneliusroemer high local prevalence in Saint Petersburg.

**Comment by FedeGueli** [comment]
Pls propose it when it reaches 100 ( if it will do that in a short time 2wks)

**Comment by FedeGueli** [comment]
@NkRMnZr please propose this one.

ping @corneliusroemer high local prevalence in Russia

**Comment by FedeGueli** [comment]
designated XBB.1.16.28 via https://github.com/cov-lineages/pango-designation/commit/2efc9a16eb53ff505b9eb17e863a3494aef59de9
