### ISSUE TITLE
XBB.1.9.1 with ORF1a:E637K (Side branch of FL.15) with S:T478R and S:Q613H (87 seqs, mainly in Russia, 11 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1001]
**Defining Mutations:** `XBB.1.9.1` > `C28846T` > `G2174A(ORF1a:E637K/nsp2_E457K)` > `C25482T` > `A2821G, C14670T, C22995G(S:T478R), T23158C(S:N532), G23401T(S:Q613H)`
**Query:** `G2174A, A2821G, C14670T`
**Earliest seq:** 2023-07-09 (`EPI_ISL_18023444`, Saint Petersburg, Russia)
**Latest seq:** 2023-10-04 (`EPI_ISL_18403129`, Ghent, Belgium)
**Sampled Countries:** Russia (37: SPE/24; TAM/9; TYU/3; MOW/1), UK (3: EN), Belgium (1), Italy (1), South Korea (1), Netherlands (1), Slovenia (1), USA (1: CA)

<details><summary>Genomes: </summary>

`EPI_ISL_18023444, EPI_ISL_18110993, EPI_ISL_18238332, EPI_ISL_18293557, EPI_ISL_18299851, EPI_ISL_18301623, EPI_ISL_18301633, EPI_ISL_18325223, EPI_ISL_18331900, EPI_ISL_18375598, EPI_ISL_18386800, EPI_ISL_18402749, EPI_ISL_18403129, EPI_ISL_18416898, EPI_ISL_18416913, EPI_ISL_18416919, EPI_ISL_18416924, EPI_ISL_18416926, EPI_ISL_18416928, EPI_ISL_18416964, EPI_ISL_18416966-18416967, EPI_ISL_18416969-18416970, EPI_ISL_18416972, EPI_ISL_18416974-18416975, EPI_ISL_18416978, EPI_ISL_18417109, EPI_ISL_18417118, EPI_ISL_18417123-18417124, EPI_ISL_18417128, EPI_ISL_18417134, EPI_ISL_18417153, EPI_ISL_18417163, EPI_ISL_18417166, EPI_ISL_18417190, EPI_ISL_18417198, EPI_ISL_18417338, EPI_ISL_18417412, EPI_ISL_18417434-18417435, EPI_ISL_18417596, EPI_ISL_18417599, EPI_ISL_18417628`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a62d_4c6c30.json?label=id:node_3338399

view from XBB.1.9.1's `C28846T` branch, the upper one with `S:F456L` is FL.15
![sc](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0c422d8a-15be-4f5a-87bd-604526807330)

details
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6abf3116-fd26-402f-8ce9-0572abef9465)

**Comment by FedeGueli** [comment]
2,5% in Russia at the end of October

**Comment by FedeGueli** [comment]
2% in St Petersburg

**Comment by FedeGueli** [comment]
Designated FL.38 via https://github.com/cov-lineages/pango-designation/commit/7f94a436c2ddd55632f4121724fb385003644cff
