### ISSUE TITLE
FY.8 (S:T572I) sublineage gained S:T478R (73 Seqs) and then S:P521Q (27) emerged in Iraq 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1002]
Credits: _first spotted and mentioned by @HynnSpylor_ 

Using Dave McNally tool for Uk samples i noticed a cluster of FY.8.
It has gained S:t478R further after S:T572I
![Schermata 2023-10-22 alle 12 03 45](https://github.com/cov-lineages/pango-designation/assets/87669813/00d5b2b1-796c-4dc4-8b89-66bf97403356)
**Defining mutation** for S:T478R: **FY.8**> T4579A, **ORF1b:P1682S** (C18511T) > **S:T478R** (C>A22995G)
**Query for T478R: C18511T,T4579A,C23277T**
Samples: **40** 
EPI_ISL_17786848, EPI_ISL_18227008, EPI_ISL_18234384,
EPI_ISL_18273708, EPI_ISL_18281328, EPI_ISL_18281399,
EPI_ISL_18281681, EPI_ISL_18286491, EPI_ISL_18290965-18290966,
EPI_ISL_18301718, EPI_ISL_18302137, EPI_ISL_18313822,
EPI_ISL_18314209, EPI_ISL_18325771, EPI_ISL_18325844,
EPI_ISL_18332437, EPI_ISL_18356075, EPI_ISL_18356085,
EPI_ISL_18392294, EPI_ISL_18392413, EPI_ISL_18398172,
EPI_ISL_18398174, EPI_ISL_18398819

And then it has been splitted in two branches: 
one with S:n148T  and the other with S:S521Q.
This last one with recent collection dates:
![Schermata 2023-10-22 alle 12 03 20](https://github.com/cov-lineages/pango-designation/assets/87669813/4971052b-2746-4db8-af15-35ebcbf43415)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c559_4f0550.json?c=userOrOld&label=id:node_3223034
**Defining mutations** for S:P521Q sublineage : **FY.8**> T4579A, ORF1b:P1682S (C18511T) > **S:T478R** (C>A22995G) >>**Orf1b:V1149L** (G16912T), **S:P521Q** (C23124A), C26681T, C29296T
**Query for S:P521Q : C18511T,T4579A,G16912T** 
Samples: **17** 
EPI_ISL_18286491, EPI_ISL_18301778, EPI_ISL_18352159,
EPI_ISL_18352189, EPI_ISL_18362363, EPI_ISL_18362379,
EPI_ISL_18373512, EPI_ISL_18373578, EPI_ISL_18373584,
EPI_ISL_18373588, EPI_ISL_18378292, EPI_ISL_18385585,
EPI_ISL_18385589, EPI_ISL_18392505, EPI_ISL_18398447,
EPI_ISL_18398501, EPI_ISL_18412501

Growth rate in Uk for 478R
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/from%3D2023-09-15%26to%3D2023-10-15/variants?nextcladePangoLineage=HK.3*&nucMutations1=C18511T%2CT4579A%2CC23277T&analysisMode=CompareToBaseline&  

 
Growth rate in Uk for S:478R + S:P521Q
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past2M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C18511T%2CT4579A%2CG16912T&analysisMode=CompareToBaseline&

Edited note that T4579A is the defining of FL.2 and linked to TRS as @oobb45729 and @ryhisner pointed before.

**Comment by HynnSpylor** [comment]
Yes I've mentioned the branch in X group.
GISAID once classified them as FY.5

**Comment by FedeGueli** [comment]
> Yes I've mentioned the branch in X group. GISAID once classified them as FY.5

Thank you @HynnSpylor !! i was recalling that it was not new but i couldnt find it! sorry i ll credit you now!.

**Comment by HynnSpylor** [comment]
Ah I just mentioned it in chat group several days ago, and forgot to submit here. Thx @FedeGueli to propose it!

**Comment by FedeGueli** [comment]
two samples from Iraq collected in August make me think it emerged in that area! cc @HynnSpylor

**Comment by FedeGueli** [comment]
Slowing down apparently. now 57

**Comment by FedeGueli** [comment]
more samples from Uk Denmark Italy

**Comment by FedeGueli** [comment]
+5 Uk, Denmark, US

**Comment by FedeGueli** [comment]
@HynnSpylor do you think i should propose this one?

**Comment by HynnSpylor** [comment]
The whole FY.8+T478R branch could be proposed as widely spread (despite it is slow now). 
Thx @FedeGueli !
> @HynnSpylor do you think i should propose this one?

**Comment by FedeGueli** [comment]
transferred to https://github.com/cov-lineages/pango-designation/issues/2391

**Comment by FedeGueli** [comment]
Designated FY.8.1 via https://github.com/cov-lineages/pango-designation/commit/37a695ae2bd98599ddd6348566bc731aa42937d2

**Comment by FedeGueli** [comment]
Sublineage with S:P521Q designated FY.8.1.1 via https://github.com/cov-lineages/pango-designation/commit/45544bcf8b080b193b9f2b3638d2fef17e78bbfe
