### ISSUE TITLE
JZ.1+Orf1a:T1822I (= PLPro_T259I),I2854T,T4311I, Orf1b:M2322T,S:K182R (24 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1004]
JZ.1+C5730T,T8826C(Orf1a:T1822I,I2854T)+ C13197T,T20432C,A22107G(Orf1a:T4311I, Orf1b:M2322T,S:K182R)

GISAID query: C13197T,T20432C,A22107G
No. of seqs: 22(USA 3(1 from UK), South Korea 1 Israel 1 Switzerland 1 Brazil 16)

First: EPI_ISL_18078910, Brazil, 2023-7-20
Latest: EPI_ISL_18401529, USA, 2023-9-29

Though time for the seqs are not very recent, but Brazil always has long delays. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice114_genome_140fb_624dd0.json?branchLabel=Spike%20mutations&label=id:node_3850502&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/18fb6c6b-639c-405c-b800-bb4d623cc63a)

**Comment by aviczhl2** [comment]
+1 Denmark

**Comment by FedeGueli** [comment]
I ve missed this one.

**Comment by FedeGueli** [comment]
One only October sample but lets wait for more Brazilian sample to be sure it is dead.

**Comment by FedeGueli** [comment]
No recent sample closing it
