### ISSUE TITLE
EG.5.1* / GK.1.1 recombinant with extra S:H49Y (England, 5 seq)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1007]
Credit to @JosetteSchoenma and @aviczhl2.

Mutations Based on XBB.1+Orf8:G8*+S:S486P: C2334T(Orf1a:A690V), G5720A(Orf1a:G1819S), C9693T(Orf1a:A3143V), C12789T(Orf1a:T4175I), A16878T, A18492G, C21707T(S:H49Y), T22609G, C22624T, G22927T(S:L455F), T22928C(S:F456L), C23280T(S:T573I), C23673T(S:S704L), A25045G, C25658T(Orf3a:T89I), C26735T, C27059T, C28005T(~Orf8:P38S~), C28519T(Orf9b:T79I), C28657T, C28810T

Query: C21707T, C28810T

Earliest sequence: 10-04 EPI_ISL_18398766
Latest sequence: 10-11 EPI_ISL_18421115
Regions detected: UK 5(England)

Breakpoint: A18492G\~G21718G

The GK.1.1 donor is same with XCZ.
GK.1.1>G12442A >C4276T, C28519T(Orf9b:T79I)> T22609G

The EG.5.1* donor could not be EG.5.1.1/HK*, EG.5.1.3/JG*, EG.5.1.6/HV* or EG.5.1.2/5/9/10.

If C21707T(S:H49Y) is inherited from EG.5.1* donor, the breakpoint should be after 21707. But there are no EG.5.1*+S:H49Y without extra mutations before 21707. And there are no GK.1.1>>T22609G with C21707T(S:H49Y) too. So C21707T should be private.

Private mutations: C21707T(S:H49Y), C28810T

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice60_genome_a57c_64ef20.json?label=id:node_3527428
![2023-10-24 (6)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/c6549d23-ae91-4027-b702-3b1e4021f6ba)

Sequences:
EPI_ISL_18392212-18392213, EPI_ISL_18398766, EPI_ISL_18403217,
EPI_ISL_18421115

**Comment by FedeGueli** [comment]
It was likely just a cluster lets it open for a while more before closing.

**Comment by FedeGueli** [comment]
C27059T now designated HK.32 could you check if may be relevant here please? not important nor urgent

**Comment by FedeGueli** [comment]
> C27059T now designated HK.32 could you check if may be relevant here please? not important nor urgent

scratch it is in the GK.1.1 side

**Comment by FedeGueli** [comment]
No new sample of this closint it for now.
