### ISSUE TITLE
GS.3/DV.7.1.2 recombinant (3 seqs, Spain/France)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1008]
This one is like XCM, but has its breakpoint between S:257 and S:368 instead of between S:152 and 157. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/926259af-7e1e-4a74-ab82-d7c3d7ed1a86)

GS.3--DV.7.1.2
Breakpoint between 22332 and 22663

Additional mutations:
A4231G,A5541G, C10376T, C15613T, C16596T

Orf1a:Q1759R,P3371S
Orf1b:H716Y

A4231G,A5541G, C10376T, C16596T from a GS.3 branch
C15613T is private

GISAID query: C15613T, C10376T,A29558G
No. of seqs: 2(Spain)

EPI_ISL_18393172, 2023-8-31
EPI_ISL_18419751, 2023-9-3

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice32_genome_e260_7233b0.json?s=hCoV-19/Spain/MC-HCUVA-60488630/2023%7CEPI_ISL_18419751%7C2023-09-03)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a4d5a9a0-59b5-4bc6-95e5-021d9c8bbe04)

[usher for GS.3-donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21a90_72d2b0.json?branchLabel=nuc%20mutations)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/95e6cf0f-4fff-46f4-afa3-5db65a1d9454)

**Comment by aviczhl2** [comment]
Oh I just recognized this one was already proposed in #973, as they are found in very different trees(this one is XBB.1-sibling the other being GS.3) I don't realize at the 1st glance. 

I'll keep this one.

**Comment by FedeGueli** [comment]
> Oh I just recognized this one was already proposed in #973, as they are found in very different trees(this one is XBB.1,XCM-sibling the other being GS.3) I don't realize at the 1st glance.
> 
> I'll keep this issue open.

Sorry i ddint get what you mean? are these the same recombinants or two very similar ones?

**Comment by aviczhl2** [comment]
> Sorry i ddint get what you mean? are these the same recombinants or two very similar ones?

The same one but found in very different places because usher changes assignments of lineages every day.

**Comment by aviczhl2** [comment]
+1 France
