### ISSUE TITLE
Another BA.2.86* sublineage with S:A475V (26 seqs in 5 countries, including Belgian hospital cluster)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1009]
Defining mutations:

BA.2.86>A6183G (ORF1a:K1973R, but without C12815T)>C22986T (S:A475V)
GISAID query: A6183G, C22986T, -T3565C, -C22978T
Earliest seq: 2023-09-18 (Netherlands- EPI_ISL_184331408)
Most recent seq: 2023-10-19 (Belgium- EPI_ISL_18429484)
Countries detected: Belgium (4), Netherlands (1)
**The 4 Belgian sequences are submitted by @kdurkin. Thanks for the work! 

Usher Tree:
![QQ截图20231024215024](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d4905b8d-63d7-47c0-b477-870455a9a7e5)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ab4b_7c3a50.json

Notice that another Spanish branch of BA.2.86.1* also gets S:A475V (has been proposed in #954)

Recently, S:A475V is increasing rapidly in some XBB* sublineages. We can monitor whether it can work well in BA.2.86*.

Genomes:
EPI_ISL_18331408, EPI_ISL_18429476-18429477, EPI_ISL_18429481, EPI_ISL_18429484

**Comment by kdurkin** [comment]
You did not give me much time to post this myself, some context for the 4 Belgian sequences are all from the same outbreak.

**Comment by HynnSpylor** [comment]
Ah sorry for that @kdurkin I just notice that you are the submitter!

**Comment by kdurkin** [comment]
no problem

**Comment by Huachuan1120** [comment]
France+1, EPI_ISL_18441084

**Comment by kdurkin** [comment]
14 additional samples from Belgian, all belong to the same healthcare centre cluster as the first 4 Belgian samples.  
EPI_ISL_18445514
EPI_ISL_18445515
EPI_ISL_18445516
EPI_ISL_18445517
EPI_ISL_18445518
EPI_ISL_18445519
EPI_ISL_18445520
EPI_ISL_18445521
EPI_ISL_18445522
EPI_ISL_18445523
EPI_ISL_18445524
EPI_ISL_18445525
EPI_ISL_18445545
EPI_ISL_18445550

**Comment by JosetteSchoenma** [comment]
Indeed. The 13 black dots all say 'Hospital cluster' on GISAID.
![Screenshot_20231030_161418_X.jpg](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/1e3a58c7-bc88-4ca7-9995-da4f8abd00cf)

**Comment by JosetteSchoenma** [comment]
I say 13, but it's indeed probably 14. EPI_ISL_18445525 has N at S:A475V and several other nucleotides.

**Comment by JosetteSchoenma** [comment]
> I did the sequencing, all 14 samples came from the same facility, a few have high Ns.

Did the ones that were found earlier also come from the same hospital? They aren't tagged 'hospital cluster' but are in the same branch. White dots. Ending in 476, 477, 481 and 484. Or were they only sequenced in the same lab?
![Screenshot_20231030_161418_X.jpg](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/d13810d4-a89c-4d75-8df7-ebe58bac2256)

**Comment by kdurkin** [comment]
> Did the ones that were found earlier also come from the same hospital?
Yes they came from the same hospital, I only became aware that they were part of a cluster after they were submitted to GISAID.

**Comment by JosetteSchoenma** [comment]
Thanks!

**Comment by Huachuan1120** [comment]
Spain+1, EPI_ISL_18450053

**Comment by Huachuan1120** [comment]
England,UK+1, EPI_ISL_18457932
Finland+1, EPI_ISL_18458444

**Comment by HynnSpylor** [comment]
The UK and Finland seq are indeed on the branch. But the Spanish seq updated yesterday is not.
Also notice that Finland seq gets S:S680F

**Comment by Huachuan1120** [comment]
Thanks to @HynnSpylor for correction!

**Comment by HynnSpylor** [comment]
One more seq in France.

**Comment by Huachuan1120** [comment]
Netherlands+1，EPI_ISL_18463265

**Comment by Huachuan1120** [comment]
Denmark+1, EPI_ISL_18472838

**Comment by kdurkin** [comment]
12 additional samples, Belgium and Spain 

9 from ULG Belgium (submitted to GISAID not yet release)

3 are form the same facility as the 18 in the "Belgian hospital cluster" and are labelled in GISAID as active surveillance 
hCoV-19/Belgium/ULG-301442/2023
hCoV-19/Belgium/ULG-301443/2023
hCoV-19/Belgium/ULG-301444/2023

4 cluster with the  "Belgian hospital cluster" but do not have a know connection, sampled in different hospital, labelled in GISAID as baseline surveillance 
hCoV-19/Belgium/ULG-301446/2023
hCoV-19/Belgium/ULG-301452/2023
hCoV-19/Belgium/ULG-301456/2023
hCoV-19/Belgium/ULG-301467/2023

Other 2 do not cluster with the "Belgian hospital cluster", sequenced as part as baseline surveillance 
hCoV-19/Belgium/ULG-301468/2023
hCoV-19/Belgium/ULG-301476/2023

2 samples from other Belgian labs
hCoV-19/Belgium/AZDelta-2343-04107/2023|EPI_ISL_18486570|2023-11-02
hCoV-19/Belgium/Jessa_11-2343-007069/2023|EPI_ISL_18486684|2023-10-29

Spanish sample
hCoV-19/Spain/CT-LabRefCat-079590328300/2023|EPI_ISL_18485651|2023-10-10
![BA 2 86](https://github.com/sars-cov-2-variants/lineage-proposals/assets/40354992/fc38be7d-4e9e-4212-95e2-a26aa6b1b574)

**Comment by Over-There-Is** [comment]
JN.4

**Comment by Over-There-Is** [comment]
USA/MD-MDH-9069/2023|EPI_ISL_18403841|2023-10-03 dropout or convergence?

**Comment by Over-There-Is** [comment]
![2023-11-12 (5)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/af38a212-c3ea-4dc4-970d-ca16f78ee86f)
@CorneliusRoemer

**Comment by FedeGueli** [comment]
Designated JN.4 via https://github.com/cov-lineages/pango-designation/commit/8c291c77c2451fdbd2c0e9a3ff6ce38ea734c66c
