### ISSUE TITLE
XBC.1.6.2 with Orf7a: Q21* Australia and Netherland， 58 seqs  

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#101]
This is basically a resubmission of my proposal 1928 in the main repository here. That proposal got shut down by @corneliusroemer but as I routinely review my old proposal I discover that it spread to more province of Australia and increase in number, so I want to give it another try here.

Mutations on top of XBC.1.6.2: G2744A->G5572T(orf1a: M1769I)->T1936C,C27454T
Inquiry: T1936C,C27454T
Sequences: EPI_ISL_17324195, EPI_ISL_17324208, EPI_ISL_17324217-17324219,
EPI_ISL_17324225, EPI_ISL_17324241, EPI_ISL_17324268,
EPI_ISL_17324276, EPI_ISL_17398298, EPI_ISL_17398341,
EPI_ISL_17398398, EPI_ISL_17398417, EPI_ISL_17463441,
EPI_ISL_17588518, EPI_ISL_17606357, EPI_ISL_17606413,
EPI_ISL_17606445-17606446, EPI_ISL_17606518, EPI_ISL_17606544,
EPI_ISL_17624130, EPI_ISL_17624134, EPI_ISL_17624136,
EPI_ISL_17624241, EPI_ISL_17656293, EPI_ISL_17656446,
EPI_ISL_17656958, EPI_ISL_17657256-17657257, EPI_ISL_17662992,
EPI_ISL_17663048-17663049, EPI_ISL_17663086, EPI_ISL_17682831,
EPI_ISL_17703832, EPI_ISL_17703837, EPI_ISL_17703846,
EPI_ISL_17703910

Earliest: EPI_ISL_17324219 2023-03-20
Latest: EPI_ISL_17703837 2023-05-16
Distribution : 1 Capital Terriroty (which is weird and questionable), 5 Victoria, 1 Tasmania, 32 South Australia.

USHER tree: I rather include a whole tree of XBC.1.6 here with submission time from 03-15- 
 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3c5fa_115820.json?f_userOrOld=uploaded%20sample&gt=ORF1ab.1769M&label=id:node_4782018&showBranchLabels=all

Australia has this bad habit of submitting a bunch of sequences together, so one could see that a lineage may disappear for a while then reappear.

**Comment by AnonymousUserUse** [comment]
Could you please write the number of sequences and the circulating country/countries in the title of the proposal? E.g. XBC.1.6.2 with Orf7a: Q21* (39 sequences, Australis). Thanks.

**Comment by krosa1910** [comment]
> Could you please write the number of sequences and the circulating country/countries in the title of the proposal? E.g. XBC.1.6.2 with Orf7a: Q21* (39 sequences, Australis). Thanks.

Yeah， I wasn't being so considerate when writing this, thanks for pointing out.

**Comment by FedeGueli** [comment]
Grown to 51 recent bathc from SA, AUs

**Comment by krosa1910** [comment]
> Grown to 51 recent batch from SA, AUs

As australia usually uploaded sequences in batches, I am not sure about its growth.

**Comment by krosa1910** [comment]
EPI_ISL_17884976 Netherland 06-08, 2023The first sequence outside Australia detected

**Comment by FedeGueli** [comment]
No new seq in the last batch. waiting for a while more before closing.

**Comment by krosa1910** [comment]
I hate this one, fk
I don't think it is even worthy of being designated as the whole XBC family including its parent XBC.1.6.2* is on a track of marginalization , yet it just periodically appeared.
The total number has increased to 82, yet it had been months since it got any where except Australia , yet it still appeared with non-negligible number with the recent Australia cluster sequencing, so I suggest it is at least spreading somewhere.

**Comment by FedeGueli** [comment]
> I hate this one, fk I don't think it is even worthy of being designated as the whole XBC family including its parent XBC.1.6.2* is on a track of marginalization , yet it just periodically appeared. The total number has increased to 82, yet it had been months since it got any where except Australia , yet it still appeared with non-negligible number with the recent Australia cluster sequencing, so I suggest it is at least spreading somewhere.

XBC is very sneaky it always appears disappears go down and up. really i cnat get exactly why (maybe accessory proteins?) but for sure it doesnt behave as the rest of variants.

**Comment by krosa1910** [comment]
Really persistent it seemed, although XBC.1.6.2* is no longer relevant and could only hide in Australia.

**Comment by FedeGueli** [comment]
XBC is a sneaky variants. i dont understand how it does. alos XBC.1.3 does the same of XBC.1.6 so it is not spike driven.

**Comment by krosa1910** [comment]
> XBC is a sneaky variants. i dont understand how it does. alos XBC.1.3 does the same of XBC.1.6 so it is not spike driven.

And that situation is ultimately worsened by Australia's massive uploads.
