### ISSUE TITLE
XBB.1.19.1 + S:L455F, S:F456L, S:K478I, ORF8:G8*, ORF1a:T2283I, ORF1a:S302F, ORF1a:P4220L, N:S80P (7)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1010]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/56744d5d-35bc-4a71-93be-3205eadc2f10)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d46d_865b40.json?c=gt-nuc_28511&gmax=29511&gmin=27511&label=id:node_3205572

First Seq: 2023-09-14
Most Recent: 2023-10-03

Gisaid Query: C7113T, G22927T, T22928C, G27915T, T28297C

EPI_ISL_18294825 EPI_ISL_18294822 EPI_ISL_18294824 EPI_ISL_18294827 EPI_ISL_18411746 OR673138.1 EPI_ISL_18387869

**Comment by Over-There-Is** [comment]
GW.5 / FL.13 Recombinant

**Comment by Over-There-Is** [comment]
T28297C=Orf9b:I5T

**Comment by Over-There-Is** [comment]
Duplicated with #855

**Comment by FedeGueli** [comment]
Thx @Over-There-Is and @Fearuncle closing it
