### ISSUE TITLE
Potential GJ.1.2* and XBB.1.41.2 Recombinant (7 seqs, Scotland, France) with a singlet, most recent sample, with S:L455S

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1011]
**Query:** `C7819G, T8119C, G16795A`
**Earliest seq:** 2023-09-02 (`EPI_ISL_18263110`, Scotland)
**Latest seq:** 2023-10-05 (`EPI_ISL_18421655`, Scotland)
**Sampled Countries:** UK (6: SC), France (1)

**Recombinant Profiles:** 
- Placement on Phylogenetic Tree: `XBB.1.41.2` > `C21772T(S:V70)` > `A28319T(N:T16S/OFR9b:L12F)` > `C1549T, C3020T(ORF1a:H919Y), C4234T, C7819G, C12754T, A12878G(ORF1a:I4205V),` _`A14023G_reversion(ORF1b:T186A_reversion)`_ > _`T1473C_reversion(ORF1a:I403T_reversion),`_ `G6536A(ORF1a:G2091S), T8119C,` _`T9724C_reversion, C16342T_reversion(ORF1b:P959S_reversion),`_ `G16795A(ORF1b:V1110I)`
- Donor A: **GJ.1.2*** with `C3020T/ORF1a:H919Y` and `C12754T` (undesignated sibling to **GJ.1.2.4** and **GJ.1.2.7**), upstream from 5' end to breakpoint.
- Donor B: **XBB.1.41.2**, downstream from breakpoint to 3' end.
- Breakpoint: Between `nuc_16795` to `nuc_20102`
- Private mutation(s): `T8119C`
- Mutation Details:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2cc8a490-bb1d-451b-950d-5130451afe68)

<details><summary>Genomes: </summary>

`EPI_ISL_18263110, EPI_ISL_18302888, EPI_ISL_18363148, EPI_ISL_18367066, EPI_ISL_18385893, EPI_ISL_18421655`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1379f_8adb40.json?label=id:node_3555179
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bd10f236-221c-4348-bef6-42efdc284998)

**Trivia:**
- A singlet got further `S:L455S` : `Scotland/CLIMB-CM7YGHDH/2023|EPI_ISL_18421655|2023-10-05`

**Comment by FedeGueli** [comment]
Most of them have S:T1788M too that is NSP3_T970M that is PLPro_T225M
