### ISSUE TITLE
EG.5.1.6/XBB.1.16.8 recombinant (56 seqs, Canada)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1013]
Likely recombinant (explaining 4 private mutations, 1 of which is a reversion)

EG.5.1.6 (or HV.1)/XBB.1.16.8 recombinant (Canada)

XBB.1.16.8 that has picked up C2334T, G5720A, C5835T from HV.1/EG.5.1.6 and reverts one of the XBB.1.16.8 sublineage

Breakpoint 7301-8200 I think

<img width="1924" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/d8fbe65c-18c2-4489-9eb6-2aee8e67951c">

<img width="1957" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/584e9851-07ea-4150-ad00-6f1c50bdcbdd">

Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7f6d_98bfc0.json?label=id:node_3253271

Some sequences:
EPI_ISL_18344174
EPI_ISL_18344545
EPI_ISL_18372033
EPI_ISL_18344967
EPI_ISL_18251326
EPI_ISL_18277858

Possible query: C2334T, G5720A, C5835T,T12730A (EDIted)

**Comment by FedeGueli** [comment]
56 now mostly Canada.

**Comment by FedeGueli** [comment]
Apparently dying off, i flagged it to check it in a couple of weeks then closing it.

**Comment by FedeGueli** [comment]
No new sequence. closing it
