### ISSUE TITLE
JR.1.1 (EG.5.1.11.1.1) sublineage with S:K356Q and ORF1a:A3061V (11 seqs in Australia, Japan, Thailand, US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1015]
Defining mutations:
JR.1.1>A27388C>C9447T (ORF1a:A3061V), A22628C (S:K356Q)
GISAID query: C9447T, A22628C, A27388C
Earliest seq: 2023-09-13 (Japan, detected in US International Airport- EPI_ISL_18295307)
Most recent seq: 2023-10-10 (NSW, Australia- EPI_ISL_18411613)
Countries detected: Australia (4), Japan (2, including 1 detected in US International Airport)

Usher Tree:
![QQ截图20231027013540](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/1d292c48-59de-4232-aa1d-5fe707dbe354)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21742_a9f310.json?c=gt-S_356

JR.1.1 (EG.5.1.11.1.1) is one of FlippeR (S:L455F+S:F456L+S:K478R) lineages. Now the branch gets S:K356Q, which is different with the popular S:K356T, can slightly increase the escape potential. 
Also, the US International Airport seq gets S:Q677H.

Genomes:
 EPI_ISL_18295307, EPI_ISL_18410942, EPI_ISL_18411613, EPI_ISL_18411657, EPI_ISL_18435046, EPI_ISL_18435384,

**Comment by aviczhl2** [comment]
+1 Thailand

**Comment by FedeGueli** [comment]
+3 CALIFORNIA, THAILAND, AUSTRALIA(QLD)

**Comment by HynnSpylor** [comment]
11 seqs now
