### ISSUE TITLE
EG.5.1.1/FLip Branch 15 ( issue #2340) sublineage  with ORF1a:T2906N, ORF1a:A4148V, ORF1a:A3571V, ORF1a:V3510I (76)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1019]
This is a sublineage of EG.5.1.1/FLip Branch 15-issue #537

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/4add5fa4-b18d-4a42-b973-4a2c9815a0bb)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20b8f_b368e0.json?c=gt-nuc_10793&gmax=11793&gmin=9793&label=id:node_3471633

First Seq: 2023-09-25
Most Recent: 2023-10-18

Gisaid Query: G10793A, C12708T, T17208C

EPI_ISL_18428629 EPI_ISL_18362082 EPI_ISL_18397275 EPI_ISL_18354968 EPI_ISL_18397540 EPI_ISL_18397532 EPI_ISL_18397352 EPI_ISL_18362042 EPI_ISL_18397428 EPI_ISL_18428518 EPI_ISL_18355029 EPI_ISL_18428547 EPI_ISL_18428565 EPI_ISL_18361857 EPI_ISL_18428583 EPI_ISL_18397408 EPI_ISL_18428521 EPI_ISL_18428577 EPI_ISL_18397348 EPI_ISL_18397463 EPI_ISL_18428531 EPI_ISL_18397308 EPI_ISL_18397371 EPI_ISL_18397250 EPI_ISL_18361924 EPI_ISL_18428550 EPI_ISL_18428739 EPI_ISL_18428719 EPI_ISL_18415930 EPI_ISL_18397446 EPI_ISL_18397524 EPI_ISL_18428689 EPI_ISL_18428709 EPI_ISL_18428753 EPI_ISL_18362056 EPI_ISL_18361967 EPI_ISL_18361928 EPI_ISL_18397456 EPI_ISL_18428541 EPI_ISL_18397366 EPI_ISL_18362012 EPI_ISL_18397326 EPI_ISL_18428548 EPI_ISL_18397602 EPI_ISL_18397623 EPI_ISL_18362004 EPI_ISL_18397553 EPI_ISL_18428704 EPI_ISL_18354976 EPI_ISL_18428686 EPI_ISL_18428627

**Comment by FedeGueli** [comment]
The parental lineage has been proposed in https://github.com/cov-lineages/pango-designation/issues/2340
