### ISSUE TITLE
GE.1 with S:T732I 47 seq. in 14 countries 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#102]
Defining mutations: GE.1 >>Orf1b:I1403V (A17674G) > S:T732I (C23757T), T24127C

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/dd9b592b-a312-480a-9ea3-baf33c685f5d)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10b0a_121170.json?c=gt-S_732&label=id:node_6989808 
samples:
EPI_ISL_17623390 EPI_ISL_17640621 EPI_ISL_17511338 EPI_ISL_17671221 EPI_ISL_17652344 EPI_ISL_17690462 EPI_ISL_17677695 EPI_ISL_17696435 EPI_ISL_17631077 OQ932732.1 
gisaid query A17674G,C23757T, T24127C
First Sequenced: 2023-04-02
Most Recent: 2023-05-02

**Comment by FedeGueli** [comment]
Too slow?? @Fearuncle  to me this could be let open for a while more. But up to you.

**Comment by FedeGueli** [comment]
Propose it once reaches 50

**Comment by FedeGueli** [comment]
Designated GE.1.3 via https://github.com/cov-lineages/pango-designation/commit/cffd0e3b3e3096c90628178666413149aef1b1bc
