### ISSUE TITLE
EG.5.1*FLip/XBB.1.16.15 singlet

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1020]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1a3bd9f2-d481-4d26-a060-e16b16c398a7)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_43804_b40560.json?label=id:node_3241858

gisaid query: A2059G, C22482T, G29227T

England/CLIMB-CM7Y8HHP/2023

**Comment by FedeGueli** [comment]
Spotted first by @nkrmnzr

**Comment by FedeGueli** [comment]
I ve looked again st this one spotted by @nkrmnzr but the flipflop 52/147/180/307/Flip/521 makes me think it is likely contamination

**Comment by FedeGueli** [comment]
Closing it CLimb didnt upload it to Gisaid it means likely they were not sure it was real.
