### ISSUE TITLE
GN.1 (XBB.1.5.73.1) with ORF1a:A2345V (nsp3_A1527V) and S:L455W (23 seqs, Spain, Peru)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1021]
**Defining Mutations:** `GN.1` > `C7299T(ORF1a:A2345V)` > `T682C` > `T22926G(S:L455W)`
**Query:** `T682C, C7299T, T22926G`
**Earliest seq:** 2023-09-20 (`EPI_ISL_18437542`, Lima, Peru)
**Latest seq:** 2023-09-27 (`EPI_ISL_18392020`, Badajoz, Spain)
**Sampled Countries:** Peru (1), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18392020, EPI_ISL_18437542`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_4f700_b45380.json?label=id:node_3574499
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/9564bec0-68d4-4d54-9167-2d02cae66bcb)

**Comment by ryhisner** [comment]
I think there are actually 16 sequences in this lineage with S:L455W. Ten of them also have S:H49L.

<img width="1486" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/eb39b247-d234-4edd-99cf-4871a51e9733">

EPI_ISL_18392020, EPI_ISL_18437542, EPI_ISL_18440190, EPI_ISL_18440194, EPI_ISL_18440201, EPI_ISL_18440206, EPI_ISL_18440212, EPI_ISL_18440215, EPI_ISL_18440218, EPI_ISL_18440220-18440223, EPI_ISL_18440226, EPI_ISL_18440248,

**Comment by FedeGueli** [comment]
> Wow I'm pretty sure when I started this proposal there were only 2 sequences. Thanks for the update @ryhisner

Yes it was two, do your query catches all of them?

@ryhisner xbb.1.5.73 /GN.1 was quite fast and it is the lineage with 28272 different from everything since Delta.

**Comment by FedeGueli** [comment]
The query catches 15

**Comment by ryhisner** [comment]
> The query catches 15

Yes, 15 is correct. I didn't catch that there was one duplicate on the Usher tree.

**Comment by FedeGueli** [comment]
lets wait the next upload from Peru before closing it.

**Comment by FedeGueli** [comment]
Likley circualting at low levels there. @corneliusroemer pls take a look at this.

**Comment by FedeGueli** [comment]
No recent sample pls let me know if something changes.
