### ISSUE TITLE
EG.5.1.6 sublineage with S:K182I and N:V246I (87 , 10 countries) with a sublineage with S:E554K (22, UK)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1022]
I was in doubt if propose this one or not but i think better highlighting it the same:

Defining mutations: **EG.5.1.6** (S:F157L)>> **Orf8:R115C** > C16092T >C4331T, C9943T, C15951T,**S:K182I** (A22107T), **N:V246I** (G29009A), C29708T

Tree:
![Schermata 2023-10-27 alle 10 15 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a699b2a9-1e3e-4221-9d94-7cc7360682e9)
![Schermata 2023-10-27 alle 10 16 09](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/12a35623-b6ce-46bb-afa2-cf33cf1ba85b)
![Schermata 2023-10-27 alle 10 16 25](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/de303279-2061-486c-b220-fd5bebeea3c6)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1e615_79c560.json?c=country&label=id:node_3435495

Query:  **C16092T,C4331T, C9943T, C15951T**
[ it is interesting to notice that many of these nucleotides are reversion to bat/pangolin viruses:
C16092T, C9943T, C15951T toward Pangolin viruses
C16092T,C4331T, C9943T, toward Yunnan BAT viruses
( maybe @ryhisner interested in this)]

Samples: **42**
Countries: **6** (Uk,France, Netherlands, Luxembourg, Ireland, US)

IDs:
EPI_ISL_18161704, EPI_ISL_18220578, EPI_ISL_18227708,
EPI_ISL_18274317, EPI_ISL_18302478, EPI_ISL_18302483,
EPI_ISL_18302526, EPI_ISL_18302579, EPI_ISL_18302587,
EPI_ISL_18302659, EPI_ISL_18315939, EPI_ISL_18316040,
EPI_ISL_18338416, EPI_ISL_18356248, EPI_ISL_18357377,
EPI_ISL_18362228, EPI_ISL_18363059, EPI_ISL_18363281,
EPI_ISL_18373378, EPI_ISL_18373591, EPI_ISL_18376143,
EPI_ISL_18385799, EPI_ISL_18387542, EPI_ISL_18392811,
EPI_ISL_18392922, EPI_ISL_18392935, EPI_ISL_18398509,
EPI_ISL_18398754, EPI_ISL_18412625, EPI_ISL_18412685,
EPI_ISL_18421153, EPI_ISL_18421158, EPI_ISL_18421196,
EPI_ISL_18421324, EPI_ISL_18421330, EPI_ISL_18421345,
EPI_ISL_18421351, EPI_ISL_18422661, EPI_ISL_18422982,
EPI_ISL_18429166, EPI_ISL_18429548-18429549

**EDITED**:
Some sequences dropped just after this proposal shows a possible sublineage carrying S:E554K that now i will include here:

Defining mutations over the parental lineage:
>> C3583T > S:E554K (G23222A) 

Gisaid query: **C3583T ,G23222A, C9943T, C4331T**

Samples : **6** 
Country : **Uk**
IDs: 
EPI_ISL_18412625, EPI_ISL_18421153, EPI_ISL_18421158,
EPI_ISL_18439941, EPI_ISL_18439945, EPI_ISL_18439952,

**Comment by FedeGueli** [comment]
> > it is interesting to notice that many of these nucleotides are reversion to bat/pangolin viruses:
> 
> This trend happens in other lineages as well.

yes of course

**Comment by FedeGueli** [comment]
Another 5 samples dropped today from Walsh and England , interestingly 3 of them have S:E554K this sublineage counts now 6 sequences on Gisaid and i am adding it to the proposal

**Comment by FedeGueli** [comment]
it doesnt seems slow : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=Hk.3*&nucMutations1=C16092T%2CC4331T%2CC9943T%2CC15951T&analysisMode=CompareToBaseline&

now 59 with 9 with 554K

**Comment by Fearuncle** [comment]
On the S:554K branch there are 4 seq. with S:523N on CLIMB
England/CLIMB-CM7YKPQ3/2023 England/CLIMB-CM7YKJMK/2023 England/CLIMB-CM7YKX69/2023 England/CLIMB-CM7YFYFZ/2023

**Comment by FedeGueli** [comment]
@corneliusroemer the 554K sublineage of this seems growing fast i would designate both. 

@aviczhl2 @ryhisner @hynnspylor @over-there-is @nkrmnzr wht do you think?

**Comment by FedeGueli** [comment]
> On the S:554K branch there are 4 seq. with S:523N on CLIMB England/CLIMB-CM7YKPQ3/2023 England/CLIMB-CM7YKJMK/2023 England/CLIMB-CM7YKX69/2023 England/CLIMB-CM7YFYFZ/2023

Now on Gisaid

**Comment by aviczhl2** [comment]
> @corneliusroemer the 554K sublineage of this seems growing fast i would designate both.
> 
> @aviczhl2 @ryhisner @HynnSpylor @Over-There-Is @NkRMnZr wht do you think?

Oh you can designate now? That's great. 

For the E554K branch I think better wait for appearance in another country.

**Comment by FedeGueli** [comment]
> > @corneliusroemer the 554K sublineage of this seems growing fast i would designate both.
> > @aviczhl2 @ryhisner @HynnSpylor @Over-There-Is @NkRMnZr wht do you think?
> 
> Oh you can designate now? That's great.
> 
> For the E554K branch I think better wait for appearance in another country.

No i cant! and dont want not to! i was asking Cornelius to designate i mistook the words!

**Comment by FedeGueli** [comment]
This slowed down as expected.

**Comment by FedeGueli** [comment]
only 4 samples from November closing it

**Comment by FedeGueli** [comment]
82/22

**Comment by FedeGueli** [comment]
Quite unbelievable but it reappeared yesterday in Queensland (first time sampled in Australia) after more than 2 months hyatus !
