### ISSUE TITLE
HK.3/(XBB.1.9.1* or XBB.1.22*) recombinant(25 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1023]
HK.3+A4624G,C6629T,T25572C(rev),C27507A(rev),T29625C(rev),C29675T

Orf1a:L2122F
Orf10:F23S(rev)

HK.3--XBB.1.9.1* or XBB.1.22*
Breakpoint between 22931 and 25571

T25572C(rev),C27507A(rev),T29625C(rev) from XBB.1.9.1* or XBB.1.22*
C29675T from a branch, a lot of candidates, cannot specify
A4624G is private mutation and C6629T from an HK.3 branch

GISAID query: A4624G,C29675T,C6629T(edited)
No. of seqs: 11(China 1 Singapore 10)

First: EPI_ISL_18409281, Sichuan, 2023-8-29
Latest: EPI_ISL_18428722, Singapore, 2023-10-16

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice12_genome_cf9a_bc4110.json?label=id:node_3480279)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9a20d212-cdcb-4063-a58b-edc68fb0bae2)

**Comment by FedeGueli** [comment]
thank you! we will see if orf10 was deleterious or advantageous

**Comment by FedeGueli** [comment]
+ 5 Singapore

**Comment by FedeGueli** [comment]
Please propose it when it hits 25

**Comment by aviczhl2** [comment]
+1 Netherlands

**Comment by aviczhl2** [comment]
A new seq from Slovenia shows that C2110T, C7764T are actually branch-specific mutations after recomb. Alter proposal and query

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/888e7d11-4e6f-454e-ae7d-4fbbdbfa5f99)

**Comment by FedeGueli** [comment]
> A4624G,C29675T,C6629T

Thanks

**Comment by FedeGueli** [comment]
it has slowed down a lot,

**Comment by FedeGueli** [comment]
+2 Singapore today 
considering its sequencing frequency i think it is slow.

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by aviczhl2** [comment]
+1 Vietnam

**Comment by FedeGueli** [comment]
No sequence came in December closing it

**Comment by aviczhl2** [comment]
+1 South Korea

**Comment by FedeGueli** [comment]
> A4624G,C29675T,C6629T

at the next one if collected in December we will reopen the issue.
