### ISSUE TITLE
XDD: EG.5.1.1*(HK)/JN.1 recombinant, 4 samples, 1 France and Spain, 2 USA New York

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1024]
Description: HK.3/JN.1 recombinant, 2 breaking points, Spike from JN.1
Private mutations: none
Breakpoint: First between nucleotide 6541 - 7842, second 25416 - 26270
One sequence from: 2023-03-29 from USA/New York
Countries circulating: USA
GISAID query: 
Former:G5720A, T13437C, 
Latter: _C6541T, A7842G, T15756A, A26275G_
Alternative by @Over-There-Is : C2334T, G11727A, -G13627A (Edited)
Sample: EPI_ISL_18440692
Nextclade:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/caef9088-426f-4d4a-b095-b3d71fbde603)
Compared to BA.2:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/fd4e5f22-08b4-4883-95b0-a6b838cfe958)
Usher tree:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/b67a2bf1-8f75-4a94-998f-b37aed50d14b)

**Comment by aviczhl2** [comment]
Inherits the Orf8/Orf9b from HK.3 and maintains the JN.1 spike.

**Comment by Over-There-Is** [comment]
I think it could be any EG.5.1.1*.

**Comment by JosetteSchoenma** [comment]
> I think it could be any EG.5.1.1*.

I looked at that, but many EG.5.1.1 have several mutations in the low nucleotide numbers that this recombinant and HK.3 do not have. I will check which ones again later.

**Comment by JPWeiland** [comment]
Wow, great spot Josette! This is DEFINITELY one to keep an eye on.

**Comment by JosetteSchoenma** [comment]
> I think it could be any EG.5.1.1*.

I rechecked and you are right. It could have been very many different EG.5.1.1 or HK that could have been one of the parents. No idea what i did to find just that one HK.3 sample. I will change the title.

**Comment by HynnSpylor** [comment]
Yes I noticed it. The EG.5* part indeed can be any EG.5.1.1*
with ORF8:G8* and T28297C are interesting

**Comment by UnusualTimes** [comment]
So a BA.2.86* with the famed XBB Orf8* Stop Codon (which imho gives it transmisibility rocket boots, but also makes it milder). Just my unprofessional opinion. Has Ryan seen this Josette ?

**Comment by aviczhl2** [comment]
> So a BA.2.86* with the famed XBB Orf8* Stop Codon (which imho gives it transmisibility rocket boots, but also makes it milder)

Any evidence? It seems that XBB.1.16(with G8stop)  is not milder than XBB.2.3(without G8stop).

https://www.thelancet.com/journals/lanwpc/article/PIIS2666-6065(23)00167-0/fulltext#:~:text=Overall%2C%20our%20preliminary%20analysis%20showed%20a%20higher%20risk%20of%20severe,hospitalisation%20across%20different%20XBB%20variants.

**Comment by UnusualTimes** [comment]
I think SATO Labs had something, i could be wrong though, I'm not particularly clever or clued up on any of this.

**Comment by jasondorjeshort** [comment]
...any evidence orf8:8* confers a growth advantage?  It's appeared repeatedly in very successful lineages, but its appearance as a non-defining XBB.1 mutation could easily be a founder effect:

https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3Axbb.1+%26+%21orf8%3A8*+%26+%21S%3A486P&variantQuery1=nextcladePangoLineage%3Axbb.1+%26+orf8%3A8*+%26+%21S%3A486P&analysisMode=CompareToBaseline&

For orf9b:i5t I couldn't find a relevant comparison, but there is modelling data suggesting it does confer an advantage.  The main XBB saltation families though are in ORF1a and (lesser) ORF1b.  And those are carried from BA.2.86 in this singlet?

**Comment by JosetteSchoenma** [comment]
> For orf9b:i5t I couldn't find a relevant comparison, but there is modelling data suggesting it does confer an advantage.  The main XBB saltation families though are in ORF1a and (lesser) ORF1b.  And those are carried from BA.2.86 in this singlet?

First half of ORF1a comes fromEG.5.1.1*, second half of ORF1a and ORF1b are from JN.1.

**Comment by corneliusroemer** [comment]
Great example of recombinants.tsv being useful - just came across this in my recent upload review and found the issue in recombinants.tsv. Thanks @aviczhl2 for maintaining!

**Comment by alurqu** [comment]
EPI_ISL_18493696 aka hCoV-19/USA/NY-NYULH-17002/2023 collected 2023-10-24 and submitted to GISAID 2023-11-10 may be a second sequence for this.

Note that the apparent 2 sequences at the tip after M:H3D are the same sequence coming from 2 different sources as they have the same EPI_ISL number. That is the first sequence reported for this recombinant.

The second sequence which I note here is just before the M:H3D step.

![Screenshot 2023-11-10 at 16-39-15 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_393d3_eaf550 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/8208bcb9-8220-4647-bfb4-7929506f5f14)

**Comment by JosetteSchoenma** [comment]
Indeed, @alurqu . The query catches them both. They look exactly the same to me, considering that this new one misses some coverage.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/3f30e4ad-62bc-4439-9c07-9ca2eb42468c)
Chances are that they both have the M as well!
The reversion (M:H3D) is not real. It is just that HK.3 does not have the M:D3H (light blue) mutation that JN.1 has, while the new sample has no coverage there. I put an BA.2.86.1* on top to show the difference.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/bdb97d9c-79d2-429b-b6ea-3306b8798c68)

**Comment by JosetteSchoenma** [comment]
There is a third one from France, which is actually an earlier one. From the 16th of October. EPI_ISL_18496788. This does not have the T13437C, which therefor turns out to be a mutation that is gained later on.
New query: C6541T, A7842G, T15756A, A26275G
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/5a7a9cbf-8005-4cad-aa4c-67e31de6c95d)

**Comment by aviczhl2** [comment]
Suggest designation. Lineages with similar importance, like HK.3, BA.2.86 and XCU are all designated at this stage.

**Comment by FedeGueli** [comment]
Ping @corneliusroemer JN.1 recombinant

**Comment by corneliusroemer** [comment]
Yep I've also seen the three, let's wait for one or two more just to be sure this isn't a coincidence - unlikely but possible.

**Comment by Over-There-Is** [comment]
Alternative query: C2334T, G11727A, -G13627A

**Comment by FedeGueli** [comment]
> Alternative query: C2334T, G11727A, -G13627A

added

**Comment by JosetteSchoenma** [comment]
A fourth one from Spain. EPI_ISL_18509506
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/25d7cf85-43f2-4b60-9734-dbe3560e94a8)

**Comment by FedeGueli** [comment]
thx @JosetteSchoenma please propose it is very likely that will be in the arena with JN.1 and XCT.1 for the leadership.

**Comment by Over-There-Is** [comment]
> Alternative query: C2334T, G11727A, -G13627A

Dated

**Comment by JosetteSchoenma** [comment]
6th. EPI_ISL_18517611 from Illinois / USA.

**Comment by FedeGueli** [comment]
> 6th. EPI_ISL_18517611 from Illinois / USA.

It appears as fast as feared

**Comment by aviczhl2** [comment]
+1 Denmark

**Comment by FedeGueli** [comment]
i would add a tracking in the open disccussion issue for BA.2.86

**Comment by JosetteSchoenma** [comment]
+1 Spain, First for Germany

**Comment by JosetteSchoenma** [comment]
+1 Spain

**Comment by JosetteSchoenma** [comment]
+1 The Netherlands, +1 Switzerland

**Comment by JosetteSchoenma** [comment]
France +2

**Comment by JosetteSchoenma** [comment]
+1 Switzerland

**Comment by aviczhl2** [comment]
@AngieHinrichs, It seems that XDD is still not on usher tree except for the first 3 seqs. 

I don't put designated lineages on recombinants.tsv as they will eventually be added in one day.
But strongly suggest to add them in to keep track on this. 

EPI_ISL_18440692, EPI_ISL_18493696, EPI_ISL_18496788,
EPI_ISL_18509506, EPI_ISL_18514951, EPI_ISL_18517611,
EPI_ISL_18518682, EPI_ISL_18525826, EPI_ISL_18526332,
EPI_ISL_18531477, EPI_ISL_18536130, EPI_ISL_18538125,
EPI_ISL_18541049, EPI_ISL_18541124, EPI_ISL_18543361,
EPI_ISL_18544896, EPI_ISL_18545103, EPI_ISL_18545399,
EPI_ISL_18545401, EPI_ISL_18545536, EPI_ISL_18549763,
EPI_ISL_18553184, EPI_ISL_18553542, EPI_ISL_18553650,
EPI_ISL_18560083, EPI_ISL_18560564, EPI_ISL_18560571,
EPI_ISL_18567628, EPI_ISL_18568506, EPI_ISL_18568533,
EPI_ISL_18569013, EPI_ISL_18569038, EPI_ISL_18569051,
EPI_ISL_18569318, EPI_ISL_18569411, EPI_ISL_18572900,

**Comment by aviczhl2** [comment]
@AngieHinrichs, I put those XDD seqs temporarily in recombinants.tsv so as to keep seqs in usher up to date.

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2!  @corneliusroemer released an update to nextclade data yesterday, including XDD, and I am running it on GISAID sequences now.  So they should no longer have extra reversions relative to their nextclade placements, and should be added to the build tomorrow (2023-12-06).
