### ISSUE TITLE
Sublineage of #791 (HK.3.1) with S:681R (20 seqs, Sweden)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1028]
HK.3.1+A29700G+T11269C+G29081T(N:T270I)+G410T(Orf1a:G49C)+G8849A,A23604G(Orf1a:V2862M,S:H681R)

GISAID query: G8849A,C23604G,T11269C
No. of seqs: 19(Sweden)

First: EPI_ISL_18443363, 2023-10-5
Latest: EPI_ISL_18443381, 2023-10-19

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3abb8_f08e60.json?gt=S.681R&label=id:node_11052842)

Usher places some of the seqs at earlier stages because they have their 410 and 29081 masked. All seqs shall be actually having 29081T and 410T. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/58496a57-f99b-4aba-8ff3-9e9042d38673)

**Comment by Fearuncle** [comment]
descendent of https://github.com/sars-cov-2-variants/lineage-proposals/issues/791

**Comment by FedeGueli** [comment]
thank you very likely a long term care outbreak judging by ages, but it could spread further outside.
