### ISSUE TITLE
GL.1+ORF1a:E940G (without S:Y144-) sublineage with ORF1a:A474V, ORF1a:P971S, ORF1a:P1497T, ORF1a:L2044I, S:N148T, S:G213E, ORF3a:T175I, ORF8:V62L (3 seq. Ireland, Sweden, Spain)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#1030]
(Edited)
Defining mutations:
GL.1 > > C26013T > A3084G, C5144T > Orf1a:A474V ( C1686T), Orf1a:P971S (C3176T), Orf1a:P1497T (C4754A), Orf1a: L2044I (C6395A) , T16974C, T17565C, C19011T, S:N148T (A22005C), S:G213E (G22200A), C25276T, Orf3a:T175I (C25916T), G26951T, C27389T, ORF8:V62L (G28077T)

Gisaid Query: C1686T, C3176T, C4754A

Samples : 3
EPI_ISL_18363180, EPI_ISL_18443303, EPI_ISL_18443682,
 077T)

 
CovSpectrum:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF1a%3AE940G%26S%3AN148T&
Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15b9c_f89ad0.json?c=gt-S_148&label=id:node_2826232
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/9dd51c22-35cb-4c55-b2aa-152ebd9da4af)

**Comment by oobb45729** [comment]
@ryhisner
Does this thing look Molnupiravir-related to you?

**Comment by oobb45729** [comment]
1 more. New in Spain.

**Comment by oobb45729** [comment]
This thing has the ORF7a-TRS mutation C27389T, likely lowering the expression of ORF7a. XAY* is the most common lineage now that probably have all full-functioning accessory proteins like WT, if you don't count ORF3c. It got rid of most mutations of Delta and BA.2 on accessory proteins through recombination. It has a new mutation ORF7a:T61S.

Remember ORF7a:H47Y, the mutation has its moments in BA.5? One recent paper (https://www.biorxiv.org/content/10.1101/2023.09.06.556547v1) claims that "H47Y mutation impairs the ability of SARS-CoV-2 ORF7a to antagonize type-I interferon (IFN-I) response". ORF7a:H47Y seems to be beneficial for BA.5, but it had faded along with BA.5.

T61S is near H47Y. Unlike H-to-Y, the effect of T-to-S is probably more subtle. Also unlike ORF7a:H47Y(C27532T), ORF7a:T61S(T27574A or C27575G) should be much more unlikely to happen. However, ORF7a:T61S has appeared in some chronic sequences, including this Deltacron https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1b%3AG814D%26M%3AI82T%26S%3AT859N%26S%3AV736I&. Therefore it's likely not a random change.

XAY does not have a tendency (yet) to lose ORF8 or to have an impaired ORF6, but it does have a tendency to lose ORF7a. We've seen XAY with large deletions on ORF7a or ORF7a-TRS changes multiple times. It also has a tendency to have deletions on nsp1 (near M85 or on 141-143). I suspect that there's a relation between nsp1 and ORF7a, as we've seen the nsp1 deletions and ORF7a deletions occur together multiple times one many lineages.

**Comment by ryhisner** [comment]
> @ryhisner Does this thing look Molnupiravir-related to you?

Sorry I started a response to this yesterday then never got back to finish it. No MOV signature here. I thought it was pretty remarkable when two sequences in this branch showed up in Ireland and Sweden, but getting a 3rd sequence from Spain really puts it on the radar. 

I agree with @oobb45729 that ORF7a:T61S isn't coincidental. It's showed up in chronics multiple times before, and as you say, it's a T->A mutation, which is I think the 3rd-rarest type of nuc mutation after C->G and T->G. 

My hypothesis, which I elaborated on recently in one section of a marathon twitter thread, is that ORF6 and ORF7a have redundant functions, at least to some extent. ORF7a deletions, TRS-destroying mutations, and frameshifts rarely show up in lineages with ORF6:D61L, which we know impairs ORF6 functioning. I think something similar is true with ORF8 and ORF9b. XBB lineages with an intact ORF8 rarely have ORF9b:I5T, which has proven so advantageous in XBB lineages with ORF8:G8*, and that can't be a coincidence. Also, Alpha had the highest ORF9b expression of any major variant and of course also had an ORF8 stop codon. 

Here's that thread in case anyone's interested. It's mostly about some lineages that I'm almost certain have large ORF7a-ORF7b-ORF8 deletions, but I had to talk about the other accessory proteins to put that in context. https://twitter.com/LongDesertTrain/status/1718769959688360206

**Comment by FedeGueli** [comment]
Sorry @oobb45729 i ve missed this one until now. thank you both for your analysis.

**Comment by oobb45729** [comment]
> > @ryhisner Does this thing look Molnupiravir-related to you?
> 
> Sorry I started a response to this yesterday then never got back to finish it. No MOV signature here. I thought it was pretty remarkable when two sequences in this branch showed up in Ireland and Sweden, but getting a 3rd sequence from Spain really puts it on the radar.
> 
> I agree with @oobb45729 that ORF7a:T61S isn't coincidental. It's showed up in chronics multiple times before, and as you say, it's a T->A mutation, which is I think the 3rd-rarest type of nuc mutation after C->G and T->G.
> 
> My hypothesis, which I elaborated on recently in one section of a marathon twitter thread, is that ORF6 and ORF7a have redundant functions, at least to some extent. ORF7a deletions, TRS-destroying mutations, and frameshifts rarely show up in lineages with ORF6:D61L, which we know impairs ORF6 functioning. I think something similar is true with ORF8 and ORF9b. XBB lineages with an intact ORF8 rarely have ORF9b:I5T, which has proven so advantageous in XBB lineages with ORF8:G8*, and that can't be a coincidence. Also, Alpha had the highest ORF9b expression of any major variant and of course also had an ORF8 stop codon.
> 
> Here's that thread in case anyone's interested. It's mostly about some lineages that I'm almost certain have large ORF7a-ORF7b-ORF8 deletions, but I had to talk about the other accessory proteins to put that in context. https://twitter.com/LongDesertTrain/status/1718769959688360206

By the way, XBC* has been gaining nuc:T27384C recently.

**Comment by oobb45729** [comment]
It may be recombined with EG.5.1.1* in Slovakia.
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1a%3AP1497T%26ORF1a%3AP971S%26ORF1a%3AA3143V&

**Comment by FedeGueli** [comment]
> It might be recombined with EG.5.1.1* in Slovakia. https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1a%3AP1497T%26ORF1a%3AP971S%26ORF1a%3AA3143V&

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9f40_f71e80.json?label=id:node_3466209
<img width="1160" alt="Screenshot 2024-01-11 alle 05 45 45" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1e70ed76-e801-4afe-8201-ab5b44604751">

Query:G407A, C3176T, C4754A,T20407C, T26609C 

Please propose directly on Pango.

**Comment by oobb45729** [comment]
> > It might be recombined with EG.5.1.1* in Slovakia. https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1a%3AP1497T%26ORF1a%3AP971S%26ORF1a%3AA3143V&
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9f40_f71e80.json?label=id:node_3466209 <img alt="Screenshot 2024-01-11 alle 05 45 45" width="1160" src="https://private-user-images.githubusercontent.com/87669813/295792237-1e70ed76-e801-4afe-8201-ab5b44604751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTQwNTksIm5iZiI6MTcwNTAxMzc1OSwicGF0aCI6Ii84NzY2OTgxMy8yOTU3OTIyMzctMWU3MGVkNzYtZTgwMS00YWZlLTgyMDEtYWI1YjQ0NjA0NzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIyNTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZmQxMGExYjY5MTBjYjE1OTY3MWQxOWU1M2YzOGYzYzllM2U2NWM5YTgyMmZiNGY5ODJhNTU3YTRlYmM4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79bq1KINqopI6sZ_Qk1tp24RmMQyx2oFeKGt25ZDnRY">
> 
> Query:G407A, C3176T, C4754A,T20407C, T26609C
> 
> Please propose directly on Pango.

The recombination was back in last September. Is it necessary if no newer sequences show up?

**Comment by FedeGueli** [comment]
> > > It might be recombined with EG.5.1.1* in Slovakia. https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=ORF1a%3AP1497T%26ORF1a%3AP971S%26ORF1a%3AA3143V&
> > 
> > 
> > https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9f40_f71e80.json?label=id:node_3466209 <img alt="Screenshot 2024-01-11 alle 05 45 45" width="1160" src="https://private-user-images.githubusercontent.com/87669813/295792237-1e70ed76-e801-4afe-8201-ab5b44604751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTQwNTksIm5iZiI6MTcwNTAxMzc1OSwicGF0aCI6Ii84NzY2OTgxMy8yOTU3OTIyMzctMWU3MGVkNzYtZTgwMS00YWZlLTgyMDEtYWI1YjQ0NjA0NzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIyNTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZmQxMGExYjY5MTBjYjE1OTY3MWQxOWU1M2YzOGYzYzllM2U2NWM5YTgyMmZiNGY5ODJhNTU3YTRlYmM4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79bq1KINqopI6sZ_Qk1tp24RmMQyx2oFeKGt25ZDnRY">
> > Query:G407A, C3176T, C4754A,T20407C, T26609C
> > Please propose directly on Pango.
> 
> The recombination was back in last September. Is it necessary if no newer sequences show up?

as you prefer, i will track it pvtly!
