### ISSUE TITLE
XDA (XBB.1.16 x HN.5) sublineage with S:L176F (37 seqs in 12 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1031]
Defining mutations:
XDA>T17664C>C22088T (S:L176F), G27952A (ORF8:C20Y)
GISAID query: T17664C, A22106C, G27952A
Earliest seq: 2023-09-21 (Scotland, UK- EPI_ISL_18367133)
Most recent seq: 2023-10-16 (France- EPI_ISL_18441133)
Countries detected: France (3), UK (2), US (1), Germany (1)

Usher Tree:
![QQ截图20231031010126](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/381d8576-4f50-48cb-a7b3-128d548e9986)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7dc6_fdcb80.json?c=gt-S_176

XDA is one of the fastest growing lineage recently. S:L176F is considered to improve all of escape potential, Spike mediated entry and hACE2 binding slightly. 
![QQ截图20231031010206](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/9e8f08df-0a40-4085-a2d9-986a91066aa4)

Genomes:
EPI_ISL_18366589, EPI_ISL_18367133, EPI_ISL_18405079, EPI_ISL_18412672, EPI_ISL_18441125, EPI_ISL_18441132-18441133, EPI_ISL_18446418

**Comment by FedeGueli** [comment]
now 24 (6 in November) with 5 more countries .

**Comment by FedeGueli** [comment]
37 now

**Comment by aviczhl2** [comment]
Designated XDA.1
