### ISSUE TITLE
BA.2.86 sublineage with S:A222V and ORF1a:V3892A (11 seqs in 7 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1032]
Defining mutations:
BA.2.86>T11940C (ORF1a:V3892A), C22227T (S:A222V)
GISAID query: T11940C, C22227T, C26681T
Earliest seq: 2023-08-28 (South Africa- EPI_ISL_18326183)
Most recent seq: 2023-10-17 (Spain- EPI_ISL_18439674)
Countries detected: UK (2), Spain (1), Sweden (1), Japan (1), South Africa (1), Australia (1)

Usher Tree: 
![QQ截图20231031011658](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/5d260084-140b-400d-a3e6-e1a449aef15e)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_634a_fe36d0.json?c=gt-nuc_1194
*Despite the low quality of South African seq, it is clear with S:A222V, ORF1a:V3892A and without ORF1a:K1973R (one of BA.2.86.1 defining mutations). Hence the South African seq is very likely on the branch.

S:A222V was successful in B.1.177*, some delta lineages and XBC* lineages. Now we can track how it works on BA.2.86*.
  
Genomes:
EPI_ISL_18326183, EPI_ISL_18406207, EPI_ISL_18411811, EPI_ISL_18432621, EPI_ISL_18439674, EPI_ISL_18439776, EPI_ISL_18444843

**Comment by Huachuan1120** [comment]
England,UK+1, EPI_ISL_18450194
Thailand+2, EPI_ISL_18449803, EPI_ISL_18449772

**Comment by Huachuan1120** [comment]
England,UK+1, EPI_ISL_18467017
