### ISSUE TITLE
GW.5.1.1 with S:∆N185, S:F186I (68 seqs , 7 countries , as of 02/11)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1034]
**Description**
**Sub-lineage of:** GW.5.1.1 (XBB.1.19.1.5.1.1)
**Earliest sequence:** 2023-9-19, Scotland — EPI_ISL_18367129
**Most recent sequence:** 2023-10-18, Scotland — EPI_ISL_18444830  
**Countries circulating:** Scotland (15), England (6)
**Number of Sequences:** 21
**GISAID Nucleotide Query:** A12586G, del22115_22117
**CovSpectrum Query:** Nextcladepangolineage:GW.5.1.1* & S:N185- & S:F186I
**Substitutions/Deletions on top of GW.5.1.1:**
**Spike:** ∆N185, F186I
**N:** D399N
**ORF1a:** L3641S
**ORF1b:** T730I
**Nucleotide:** C9985T, T11187C, A12586G, C15656T, T17442A, ∆22116-22118, G29468A

**Phylogenetic Order of Mutations:** T11187C, C15656T  (ORF1a:L3641S, ORF1b:T730I) **→** C9985T  **→**  T17442A, G29468A (N:D399N)  **→**  A12586G   **→**   ∆22116-22118 (S:∆N185, S:F186I)

**USHER Tree**
Unfortunately, all the ∆N185-F186I sequences are jumbled together in the Usher tree with sequences that lack this deletion.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/GW.5.1.1__N185del_F186I.json?c=gt-nuc_12586&gmax=13586&gmin=11586&label=id:node_3206248 

<img width="1500" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/00d12109-3a4c-49e2-a4a1-f44b4c377122">

**Evidence**
The three-nucleotide, out-of-frame deletion here (∆22116-22118) has been very successful in GE.1 (XBB.2.3.10.1), which I believe is still one of the most successful XBB.2.3* variants. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18363147, EPI_ISL_18367129, EPI_ISL_18378262,
EPI_ISL_18392719, EPI_ISL_18393039, EPI_ISL_18393046,
EPI_ISL_18398693, EPI_ISL_18420757, EPI_ISL_18421414,
EPI_ISL_18421417, EPI_ISL_18421479, EPI_ISL_18421582,
EPI_ISL_18421584, EPI_ISL_18421606, EPI_ISL_18421609,
EPI_ISL_18421612, EPI_ISL_18421627, EPI_ISL_18432871,
EPI_ISL_18432883, EPI_ISL_18444742, EPI_ISL_18444830,
</details>

**Comment by FedeGueli** [comment]
It looks fast.

**Comment by FedeGueli** [comment]
@ryhisner please propose it.

**Comment by FedeGueli** [comment]
Likely dead closing it
