### ISSUE TITLE
JG.3+Orf1a:Q1758R ( = PLPro_Q222R) ,A2098V+S:L335F(62 seqs, 5 countries) emerged in Castilla y Leon,Es (6% in November)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1038]
S:L335F appeared in EG.5.1.1 #877, and now it also appears in JG.3. 

JG.3+A5538G,C6558T(Orf1a:Q1758R,A2098V)+G22567T(S:L335F)

GISAID query: A5538G,C6558T,G22567T
No. of seqs: 10(Canada 1 France 1 Spain 8)

First: EPI_ISL_18446015, 2023-9-21, Spain
Latest: EPI_ISL_18444702. 2023-10-17, Spain

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice15_genome_1ff21_6c6d0.json?branchLabel=Spike%20mutations&label=id:node_3440967&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1bb16f53-e276-48c0-9692-64860c0d0170)

**Comment by FedeGueli** [comment]
Orf1a:Q1785R is NSP3_Q967R = PLPro_Q222R

**Comment by FedeGueli** [comment]
this is around 5% in Castilla y Leon after October 1

**Comment by aviczhl2** [comment]
32, Italy

**Comment by aviczhl2** [comment]
+1 Poland

**Comment by aviczhl2** [comment]
Share grows to 17/270=6.3% in November

**Comment by FedeGueli** [comment]
Lets wait for some data frm December to evalaute if it is making through JN.1 wave.

**Comment by FedeGueli** [comment]
It appears still local, but worth monitor it for more time here.

**Comment by FedeGueli** [comment]
likely dead closing for now
