### ISSUE TITLE
Belgian XBB.1.5.90 singlet saltation with S:R403K and S:Y453F

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1039]
Came across a singlet saltation from Belgium that's interesting because it has two ACE2 binding enhancing mutations:  S:R403K and S:Y453F: hCoV-19/Belgium/LHUB-ULB_48490687/2023|EPI_ISL_18443944|2023-10-20

<img width="635" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/f0cf56bc-b341-4cc6-b70e-8bab0924b6c4">

<img width="568" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/5a9a6e58-07c2-4fbe-bb60-7ed8869530af">

Very slight signal of recombination (saving two muts) when there's a breakpoint between 25400 and 27600, where the 3' donor could be FL.13.4.1, or just generally an ORF9b:I5T donor (explaining that mutation alone)

**Comment by ryhisner** [comment]
Also interesting in this one is the classic BA.1 reversion of S:S446G and the extremely rare S:L611F, which has only been in ~200 sequences ever. The only other time I've ever noticed that mutation was in a different XBB.1.5 from Italy from just a few weeks ago that metadata indicate had been found in two different patients. 

The Italian XBB.1.5 and this one have far too many difference to be related, but the number of mutations on they share—including the exceedingly rare S:L611F—is striking. 

Both have S:R403K, S:L611F, S:P621S, ORF9b:I5T, and ORF1a:S1372(A/C). 
<img width="1488" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6bbab87a-8269-4a97-954a-cbd4d5fef15c">

**Comment by FedeGueli** [comment]
Spotted by @asinickle too. veru good multiple eyes on these heavy mutated things.

**Comment by FedeGueli** [comment]
it seems there are two of this , EPI_ISL_18496252 in addition to the one found by Cornelius, same lab same age same sex maybe same patient ? Anyway i m closing this one. 
<img width="1169" alt="Screenshot 2024-01-03 alle 01 26 52" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/08354b54-db8d-41f5-b452-dcf0d203d9ed">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_a8bd_4a9b40.json?label=id:node_3935204

Query: C875T, A964C, A3406G,C4380G, G5008T, A7661G
