### ISSUE TITLE
FL.13 with S:K356T in China(24 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#104]
FL.13+C21904T,T6334C,C7843T+A22629C(S:K356T)
GISAID query: C21904T,T6334C,C7843T,A22629C

No. of seqs: 6 (2023.4.28-5.10, Sichuan, Shanghai, Hubei)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_277a5_18c340.json?label=id:node_6674458)
<img width="1388" alt="Screenshot 2023-05-27 at 15 25 47" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/29f832cb-6026-4d0c-b13f-c114a5c86d48">

**Comment by FedeGueli** [comment]
this keeps spreading propose it if it reaches 25 seqs

**Comment by aviczhl2** [comment]
22 seqs and in South Korea

**Comment by FedeGueli** [comment]
Please propose this one is 24 now.
