### ISSUE TITLE
HF.1.1/BA.2.86.1 recombinant from England, 2 sample

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1040]
**Description:** HF.1.1/BA.2.86.1 recombinant, 1 breaking point, Spike from HF.1.1 (XBB.1.16.13.1.1)
**Private mutation**: C26801T
**Breakpoint:** Between nucleotide 17149 and 17586 (ORF1b)
**One sequence from:** 2023-10-21 from England
**Countries circulating:** England
**GISAID query:** A6183G, G11876A, C17586T
**Sample:** EPI_ISL_18450393
**Note:** There are some HF.1 with C26801T, but since these do not have the Spike mutations D1084N and H1101Y, I am assuming the parent is a HF.1.1 and C26801T is a convergent private mutation.
Deletion S:Y144- is missing in this sample, but also in HF.1.1 with EPI_ISL_18362262 from England, for example.
2 English BA.2.86.1 would fit to be the parent. EPI_ISL_18412465 and  EPI_ISL_18444269
Nextclade:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/6d4ec0a4-5586-49d7-a47e-8fa5857388cc)
Usher:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/159f5892-81c0-4782-9e71-681012b4e76f)

**Comment by corneliusroemer** [comment]
Heh, came here to mention it and see that you've already spotted it :)

**Comment by FedeGueli** [comment]
+1 England EPI_ISL_18606378

**Comment by JosetteSchoenma** [comment]
+1 Wales EPI_ISL_18641683

**Comment by FedeGueli** [comment]
No new sample of this one closing it for now.
