### ISSUE TITLE
HV.1 with S:R452W, ORF1a:T4083M (61 seqs - 7 countries - March 19)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1044]
Making this one very short as I have to run, and I'm not sure if it's significant in any case. If it grows, I'll fill in the details. The 5 sequences come from near-opposite ends of North America. The two other S:R452W sequences that cluster with it on the Usher tree are most likely unrelated. 

**Query:** C5835T, C12513T, A18492G, C22916T

**Usher Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/HV.1_R452W.json?c=gt-nuc_12513&label=id:node_11054571

<img width="1387" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e0b7f3f7-7dec-4108-a009-51ab7b7081c0">

Genomes: EPI_ISL_18368684, EPI_ISL_18368708, EPI_ISL_18368715, EPI_ISL_18452865, EPI_ISL_18453010

**Comment by FedeGueli** [comment]
+1 Greece

**Comment by FedeGueli** [comment]
Slow closing it

**Comment by aviczhl2** [comment]
18 seqs now

**Comment by FedeGueli** [comment]
thx @aviczhl2 reopend it cause still ongoing in December,.

**Comment by aviczhl2** [comment]
Designated HV.1.10

**Comment by aviczhl2** [comment]
Seems that this is not the real HV.1.10, and S:452W is very very convergent in HV.1 

Reopen this.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/abaf1a1c-b5fd-41e9-89eb-816f89343637)


This is a summary of HV.1+S:452W, as can be seem this one is not the HV.1.10. There seems to be at least 30 separate branches of HV.1+S:452W. 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_ff5a_9e2190.json?f_userOrOld=uploaded%20sample&label=id:node_3577511

@ryhisner @FedeGueli  @corneliusroemer

**Comment by FedeGueli** [comment]
What a mess there were just two lineages and a few of sequences at the time of designation. I ve checked at that time the sequences used to designate and some of them belonged to this one. cc @corneliusroemer @angiehinrichs important.

At this point maybe more useful to open a multiple lineages issue. for HV.1 and S:l452W inclusing this one, the HV.1.10 and the NZL proposed one plus other branches with more than 3 seqs

**Comment by FedeGueli** [comment]
> What a mess there were just two lineages and a few of sequences at the time of designation. I ve checked at that time the sequences used to designate and some of them belonged to this one. cc @corneliusroemer @AngieHinrichs important.
> 
> At this point maybe more useful to open a multiple lineages issue. for HV.1 and S:l452W inclusing this one, the HV.1.10 and the NZL proposed one plus other branches with more than 3 seqs

scratch my words  i was confusing it with 450D , but still @corneliusroemer @angiehinrichs could you take a look

**Comment by FedeGueli** [comment]
> Seems that this is not the real HV.1.10, and S:452W is very very convergent in HV.1
> 
> Reopen this.
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/297942010-abaf1a1c-b5fd-41e9-89eb-816f89343637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NjY4OTAsIm5iZiI6MTcwNjU2NjU5MCwicGF0aCI6Ii8xMDQ0NTk0NC8yOTc5NDIwMTAtYWJhZjFhMWMtYjVmZC00MWU5LTg5ZWItODE2Zjg5MzQzNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDIyMTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ODJkZGUwOGU5OTk3MTdhMDMwNjg1N2RkMDRlMmJkNzljNDk3OWIyNTgyMTVhNTdlZTQ4YjgwZjJhM2FhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cw1NkLIwAd-SvBRtcBhXVmEsZEMYILhZ1ZRkjRwsKtg)
> 
> This is a summary of HV.1+S:452W, as can be seem this one is not the HV.1.10. There seems to be at least 30 separate branches of HV.1+S:452W. https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_ff5a_9e2190.json?f_userOrOld=uploaded%20sample&label=id:node_3577511
> 
> @ryhisner @FedeGueli @corneliusroemer

I  managed to look into it : HV.1.10 is not this one and has around 100 Seqs , best query i found is :  C15720T,C29784T,C22916T

**Comment by FedeGueli** [comment]
In january a few of the highly homoplasic HV.1 + 452W are still circualting: 
1)HV.1.10
2) the lineage proposed here
3) a lineage stemming out of from the politomy
4) one small lineage found by   C22916T,C7788T,T3306A : with Orf1a:E377G, Orf1a:M1014K, Orf1a:A2508V
5) one lineage that Usher shows having a intermediate step with C22916A and then A22916T so likely just a flip flop

@corneliusroemer if you want to take a look: (tree cut with just samples from January , but there are 50+ branches with 452W in HV.1)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_67132_82d7e0.json?f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
57 one sample from February

**Comment by FedeGueli** [comment]
still a couple of recent new samples lets keep it open for a while more

**Comment by FedeGueli** [comment]
no seuence in March closing it
