### ISSUE TITLE
XBB.1.5 sublineage with S:Q613H, S:H1058Y and NSP5_M17V (98 seq in 10 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#105]
XBB.1.5> T17124C> T10204C> C4993T, A10103G(Orf1a:M3280V = NSP5_M17V), C12025T> T23488C, C24734T(S:H1058Y)> G29543T> G23401T(S:Q613H)

GISAID Query: A10103G, G23401T
Earliest Sequence: 02-07 Texas, US EPI_ISL_17018910
Latest Sequence: 06-07 Ontario, Canada EPI_ISL_17789672
Regions Detected: **US** 51 (Texas 19, Florida 10, Ohio 9, Pennsylvania 4, California 2, New Mexico 2, Arizona 1, Minnesota 1, Mississippi 1, New York 1, S. Carolina 1), **Canada** 23 (Ontario 16, Quebec 5, BC 1, Saskatchewan 1), **China** 14 (Guangdong 5, Sichuan 3, Shanghai 6 [1 from HK, 2 from **Japan**, 2 from **S. Korea**], Xinjiang 2, Fujian 1, Hubei 1), **Singapore** 2(1 from China), **Austria** 1, **Norway** 1, **Spain** 1, **UK** 1

[Genome Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_10868_1eeed0.json?f_userOrOld=uploaded%20sample)

![2023-05-27 (2)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/fb2ec857-fee7-4055-92e6-2cb7c536163a)

<details><summary>Sequences:</summary>
EPI_ISL_17018910, EPI_ISL_17128466, EPI_ISL_17134670,
EPI_ISL_17147355, EPI_ISL_17180122, EPI_ISL_17240790,
EPI_ISL_17240820, EPI_ISL_17251151, EPI_ISL_17307062,
EPI_ISL_17328203, EPI_ISL_17333504, EPI_ISL_17384370,
EPI_ISL_17428843, EPI_ISL_17430630, EPI_ISL_17442452,
EPI_ISL_17466859, EPI_ISL_17478010, EPI_ISL_17486149,
EPI_ISL_17490820, EPI_ISL_17490828, EPI_ISL_17490840-17490841,
EPI_ISL_17490843, EPI_ISL_17495826-17495827, EPI_ISL_17495830,
EPI_ISL_17513804, EPI_ISL_17526677, EPI_ISL_17537178,
EPI_ISL_17537425, EPI_ISL_17537546, EPI_ISL_17543608,
EPI_ISL_17543762, EPI_ISL_17543766, EPI_ISL_17546803,
EPI_ISL_17582017, EPI_ISL_17582875, EPI_ISL_17589757,
EPI_ISL_17590587, EPI_ISL_17635248, EPI_ISL_17641720,
EPI_ISL_17645061, EPI_ISL_17645836, EPI_ISL_17648261,
EPI_ISL_17651042, EPI_ISL_17651443, EPI_ISL_17651516,
EPI_ISL_17651539, EPI_ISL_17653325, EPI_ISL_17680721,
EPI_ISL_17680723-17680724, EPI_ISL_17684163-17684164, EPI_ISL_17687653,
EPI_ISL_17690049, EPI_ISL_17693975, EPI_ISL_17693983,
EPI_ISL_17697653, EPI_ISL_17697716, EPI_ISL_17697854,
EPI_ISL_17698017, EPI_ISL_17698088, EPI_ISL_17711169,
EPI_ISL_17711499, EPI_ISL_17714292, EPI_ISL_17717370,
EPI_ISL_17718430, EPI_ISL_17722753, EPI_ISL_17722767,
EPI_ISL_17724530, EPI_ISL_17725128-17725129, EPI_ISL_17727015,
EPI_ISL_17727142, EPI_ISL_17744319, EPI_ISL_17744321-17744322,
EPI_ISL_17744333, EPI_ISL_17763572, EPI_ISL_17764393,
EPI_ISL_17765395, EPI_ISL_17775378, EPI_ISL_17775477,
EPI_ISL_17778265, EPI_ISL_17782073, EPI_ISL_17782082,
EPI_ISL_17789672, EPI_ISL_17790551, EPI_ISL_17795103,
EPI_ISL_17795530, EPI_ISL_17797681, EPI_ISL_17801945,
EPI_ISL_17809778, EPI_ISL_17810540, EPI_ISL_17811083,
EPI_ISL_17811134, OR061953.1

Sequence lost S:Q613H due to sequencing error(not including in counting): EPI_ISL_17683550</details>

**Comment by Over-There-Is** [comment]
Ontario, Canada+2

**Comment by Over-There-Is** [comment]
Usher placed Australia/NSW-ICPMR-46572/2023|EPI_ISL_17683550|05-05 on the tree, which dropped out Q613H.

![2023-05-30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/0657b779-5815-4a49-bf86-da7088c970bf)

![2023-05-30 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/4dc9619b-ab05-4985-b8d6-ba91307d8304)

**Comment by Over-There-Is** [comment]
So it should be 71 seq in 7 countries?

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation#1510

**Comment by Over-There-Is** [comment]
Singapore+1, Local Case

**Comment by Over-There-Is** [comment]
Shanghai+2, collected by Customs, travelling info not uploaded to GISAID, and not publicized yet on GenBase.

**Comment by FedeGueli** [comment]
This lineage looks interesting even if it should not be that faast being around since Feb.
Now that it has landed in Asia we will be able to compare with fast sublineages circulating there.
Please dont transfer to the main page until it has doubled its number of seqs from today.

**Comment by Over-There-Is** [comment]
Quebec+2

**Comment by Over-There-Is** [comment]
Due to my negligence, 2 Quebec sequences were counted into Ontario. There were 14 from Ontario and 2 from Quebec, and the number of sequences from Quebec become 4 now.

**Comment by Over-There-Is** [comment]
Ohio+4

**Comment by Over-There-Is** [comment]
I am not able to understand how it spread. Texas> Canada> China> Ohio?
![2023-06-03 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/92aaf47c-69ae-4892-98ca-f35d5ed434f6)

**Comment by Over-There-Is** [comment]
Ontario+1

**Comment by Over-There-Is** [comment]
Xinjiang +2(Changji)

**Comment by Over-There-Is** [comment]
New Mexico+1

**Comment by Over-There-Is** [comment]
Ohio+2

**Comment by Over-There-Is** [comment]
A GenBank sequence from Arizona is found.

**Comment by Over-There-Is** [comment]
2 Shanghai sequence from Japan

**Comment by FedeGueli** [comment]
As already stated above please propose it
