### ISSUE TITLE
#944(XBB/EG.5.1/XCM recomb)/#1049(FL.20.1+S:732,1191) recombinant (9 seqs, Germany, Spain, Switzerland)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1050]
_This tree was first described by @borisuitham_

Thanks @NkRMnZr for spotting.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/777cbf2b-7d74-452e-b979-c14f99a1f57e)

#944(XBB/EG.5.1/XCM recomb)--#1049(FL.20.1+S:732I,1191N)
Breakpoint between 19984 and 21717

Additional mutations: T17220C

GISAID query: C1387T,T3453C, T17220C
No.of seqs: 7(Germany 3 Spain 4)

First: EPI_ISL_18455079, 2023-10-8, Germany
Latest: EPI_ISL_18446890, 2023-10-24, Spain

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24b22_396b70.json?c=gt-nuc_3453&gmax=4453&gmin=2453)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d13292b1-9ed3-420a-9648-1e78991bb545)

**Comment by Over-There-Is** [comment]
19983\~21718

**Comment by Over-There-Is** [comment]
19983 is reverted in this recombinant, it's covered by #944.

**Comment by Over-There-Is** [comment]
A recombinant of recombinants of recombinants of recombinants

**Comment by Over-There-Is** [comment]
5'\~2334 undesignated XBB
3453\~13560 EG.5.1
16878\~19983 XBB.2.3
21718\~3' FL.20.1
DV.7.1 seems excluded

**Comment by FedeGueli** [comment]
Important @corneliusroemer please follow up from here the work of @Over-There-Is @aviczhl2 @NkRMnZr  i suggest a collective designation of all the bits of lineages driving to this and this one then.

**Comment by FedeGueli** [comment]
+1 Switzerland

**Comment by FedeGueli** [comment]
+1 Germany
