### ISSUE TITLE
EG.5.1.8 with S:V83T (60  seqs, mainly in New Zealand 4% prevalence there, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1052]
**Defining Mutations:** `EG.5.1.8` > `C12100G` > `C27603T` > `G21809A(S:V83T, on top of existing S:V83A/T21810C)`
**Query:** `C12100G, G21809A, C27603T`
**Earliest seq:** 2023-08-26 (`EPI_ISL_18231674`, New Zealand)
**Latest seq:** 2023-10-23 (`EPI_ISL_18459194`, New Zealand)
**Sampled Countries:** New Zealand (51), Australia (2: NSW; WA), Canada (BC/1), USA (1: UT)

<details><summary>Genomes: </summary>

`EPI_ISL_18231674, EPI_ISL_18292098, EPI_ISL_18292173, EPI_ISL_18292409, EPI_ISL_18324404, EPI_ISL_18347440, EPI_ISL_18347535, EPI_ISL_18347670, EPI_ISL_18351514, EPI_ISL_18381760, EPI_ISL_18411408, EPI_ISL_18459103, EPI_ISL_18459109, EPI_ISL_18459137, EPI_ISL_18459157, EPI_ISL_18459184, EPI_ISL_18459194, EPI_ISL_18459198, EPI_ISL_18459202, EPI_ISL_18459238, EPI_ISL_18459264, EPI_ISL_18459278, EPI_ISL_18459281, EPI_ISL_18459314, EPI_ISL_18459331, EPI_ISL_18459361, EPI_ISL_18459368, EPI_ISL_18459391, EPI_ISL_18459400, EPI_ISL_18459414-18459415, EPI_ISL_18459446, EPI_ISL_18459506, EPI_ISL_18459568-18459569, EPI_ISL_18459591, EPI_ISL_18459662, EPI_ISL_18459665-18459666, EPI_ISL_18459675, EPI_ISL_18459695, EPI_ISL_18459717, EPI_ISL_18459758-18459760, EPI_ISL_18459765, EPI_ISL_18459769, EPI_ISL_18459771, EPI_ISL_18459774, EPI_ISL_18459807, EPI_ISL_18459822, EPI_ISL_18459867, EPI_ISL_18459872, EPI_ISL_18459902, EPI_ISL_18459958`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3f3b0_46a510.json?label=id:node_3472725
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2c823e35-b168-4262-87aa-e792ac373be5)

**Trivia:**
- Modifies `S:V83A/T21810C` inherited from `BJ.1`, 5'-end donor of `XBB`
- Forms N-linked glycosylation with `S:N81`?
- Could #983 (`S:V83S`) have similar effect?

**Comment by FedeGueli** [comment]
Designated KB.3 via https://github.com/cov-lineages/pango-designation/commit/682de0ec3675554f54a6aecad02d76b7b4edfa75
