### ISSUE TITLE
EG.5.1.1/(XBB.1*+Orf9b:I5T) recombinant with additional 4-nuc,3-aa (33 seqs, 8 countries, 10 with S:494P)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1053]
EG.5.1.1+T6515C, T25496C, T25572C(rev), C25976T, C27507A(rev),A28886G,T29625C(rev)

Orf3a:I35T,S195F
N:T205A
Orf10:F23S(rev)

EG.5.1.1--XBB.1.9.1* or XBB.1.22* (or any XBB.1*+Orf9b:I5T without additional mutations after 25571.) 
Breakpoint between 22931 and 25571
 T25572C(rev), C27507A(rev),T29625C(rev) from XBB.1.9.1* or XBB.1.22*

T6515C,T25496C,C25976T,A28886G are private

This is a weird recombinant that all of its additional mutations are private and don't come from anywhere. I cannot find any hint of its donor on both sides. 

Maybe it first recombs then do a mini-saltation to get these mutations, 

GISAID query: T25496C,T6515C
No. of seqs: 18(France 8 Belgium 7 UK 1 Switzerland 1 Austria 1)

First: EPI_ISL_18075975, France, 2023-7-17
Latest: EPI_ISL_18462378, France, 2023-10-23

It also has a S:494P branch

GISAID query for S:494P: T25496C,T6515C,T23042C (8 seqs)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40933_4bd1f0.json?f_userOrOld=uploaded%20sample&label=id:node_3502310)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d70d6155-268b-46be-affa-a9f7d0d639c1)

**Comment by FedeGueli** [comment]
This keeps circualting especially in Belgium. I ve put it on closer watch

**Comment by FedeGueli** [comment]
Slowed down a lot likely suffering from JN.1 circualtion in the same countries where it was.

**Comment by aviczhl2** [comment]
30, Slovenia

**Comment by aviczhl2** [comment]
Seems dead
