### ISSUE TITLE
HN.4 (FL.1.5.1.4) + S:A1020S branch with S:I68T,S:452R, S:E554K - 17 sequences (Canada, US , Australia, New Zealand )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1054]
Defining mutations: HN.4 >  S:A1020S (G24620T) > C11962T > C14184T, T18012C, S:I68T (T21765C), S:L452R (T22917G), S:E554K (G23222A)

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_341ea_4caa80.json?c=userOrOld&label=id:node_3403999
![Schermata 2023-11-03 alle 11 40 14](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/af49926f-4a57-4256-83e9-00443074cf85)

Query:C11962T , C14184T, T18012C

Samples : 2

EPI_ISL_18456119, EPI_ISL_18459122
first collected on 2023-10-17 in Canada
Last collected on 2023-10-19 in NZL

**Comment by FedeGueli** [comment]
still 2

**Comment by Fearuncle** [comment]
New Seq in Canada EPI_ISL_18493041

**Comment by FedeGueli** [comment]
> 14 now

thx reopened this one

**Comment by FedeGueli** [comment]
15 now

**Comment by FedeGueli** [comment]
+2 Virginia and Australia

**Comment by FedeGueli** [comment]
Designated HN.4.1 via https://github.com/cov-lineages/pango-designation/commit/80be7b8e2fb7067c931800fcfe2a69f5c8c8e424
and HN.4.1.1 via https://github.com/cov-lineages/pango-designation/commit/c5c8ede2b32cb9f7b4214f8bc6aabdbbfef3d0bb
