### ISSUE TITLE
JD.1.1+Orf7b:L32F+S:E554G(46 seqs, 4 countries, 9 with S:V483F, 3% NSW)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1056]
JD.1.1+C27849T(Orf7b:L32F)+T5303C+A23223G,C29245T, C29281T(S:E554G)

GISAID query: A23223G,C29245T, C29281T
No. of seqs: 20(Australia 18, New Zealand 1 South Korea 1)

First: EPI_ISL_18324743, 2023-9-20
Latest: EPI_ISL_18461871, 2023-10-23

GISAID query for S:V483F subbranch: A23223G,C29245T, G23009T( 3 seqs)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice15_genome_430ce_6de960.json?label=id:node_3738112)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/021e842a-cd88-43fe-b34e-e14b31385680)

**Comment by aviczhl2** [comment]
+1 Greece

**Comment by FedeGueli** [comment]
This seems faster than parental lineage lets wait how fast it reaches 50 or if it slows down before getting as big as needed to be proposed.

**Comment by FedeGueli** [comment]
+1 Aus(SA)

**Comment by aviczhl2** [comment]
20/752=3% in NSW from 10-20

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
Desingated JD.1.1.4 via https://github.com/cov-lineages/pango-designation/commit/d15a7450c761c6193439cd3951d68da2c3a30e06
