### ISSUE TITLE
FL.1 with ORF1a:T2300I (nsp3_T1482I), ORF1a:K4348R (nsp10_K95R), S:T478R and S:P521T (48 seqs, 14 countries) around 3% in Russia

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1058]
**Defining Mutations:** `FL.1` > `C7164T(ORF1a:T2300I), A13308G(ORF1a:K4348R), C14877T` > `C22995G(S:T478R), C23123A(S:P521T)` > `G5917A, A26544G(M:I8V)`
**Query:** `C7164T, A13308G, C22995G`
**Earliest seq:** 2023-08-02 (`EPI_ISL_18129436`, Wisconsin, USA)
**Latest seq:** 2023-10-29 (`EPI_ISL_18464822`, Israel)
**Sampled Countries:** Russia (10), UK (5: WS/3; EN/2), Israel (4), Netherlands (3), USA (3), Switzerland (2), Denmark (1), Japan (1), Kazakhstan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18129436, EPI_ISL_18238370, EPI_ISL_18246964, EPI_ISL_18276299, EPI_ISL_18300085, EPI_ISL_18331416, EPI_ISL_18339107, EPI_ISL_18340038, EPI_ISL_18356282, EPI_ISL_18360490, EPI_ISL_18411854, EPI_ISL_18416719-18416720, EPI_ISL_18417199, EPI_ISL_18417425, EPI_ISL_18417580, EPI_ISL_18417602, EPI_ISL_18417629, EPI_ISL_18417689-18417690, EPI_ISL_18419982, EPI_ISL_18421296, EPI_ISL_18429135, EPI_ISL_18440409, EPI_ISL_18440434, EPI_ISL_18444569, EPI_ISL_18450591, EPI_ISL_18451030, EPI_ISL_18455020, EPI_ISL_18464822`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c333_739010.json?label=id:node_3418797
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/cf6a252e-e061-4980-831e-0f63c1c64fd4)

**Trivia:**
- Already seen a couple of recombinant with `XBB.2.3*` (placed at the bottom of the tree) : `Russia/PRI-RII-MH145732S/2023|EPI_ISL_18417689|2023-09-14` and `Russia/SPE-RII-MH145868S/2023|EPI_ISL_18416719|2023-10-03`

**Comment by FedeGueli** [comment]
Last Samples from Russia, Ireland, China England

**Comment by FedeGueli** [comment]
please propose it.

**Comment by FedeGueli** [comment]
Designated FL.18 via https://github.com/cov-lineages/pango-designation/commit/b89aa1c34d3cfbaebc1c67c4b0eeffa421291719
