### ISSUE TITLE
Another branch of XBB.1.16.6+S:L455F(50 seqs, 9 countries, 5 with S:T470I and S:M1229I)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1059]
XBB.1.16.6+T23986C+C29296T+C26192T(Orf3a:P267L)+G463A,G22927T(S:L455F)

GISAID query: G463A,C26192T
No. of seqs: 13(Germany 7 Austria 1 Australia 1 Finland 1 Sweden 3)

First: EPI_ISL_18343008, Germany, 2023-9-18
Latest: EPI_ISL_18465565, Sweden, 2023-10-18

GISAID query for S:T470I,M1229I branch: G463A,C26192T,C22971T (5 seqs)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice47_genome_11c3d_842900.json?label=id:node_3295129)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e98cf0aa-63f5-43a3-939a-75e5b9cd0cca)

**Comment by FedeGueli** [comment]
luckily few recent samples.

**Comment by FedeGueli** [comment]
+1 scotland

**Comment by aviczhl2** [comment]
+1 France

**Comment by aviczhl2** [comment]
32, Ireland, Canada

**Comment by FedeGueli** [comment]
> G463A,C26192T

now clearly circualting in multiple countries. propose it when  it tops 50, please.
