### ISSUE TITLE
XBB.1.5.44 with s:P631S, s:Q146P, ORF1ab:P1862S, ORF1ab:T3775A 29 seq. Mostly USA

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#106]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b9b53c07-535a-4103-ba81-8b5ae2d49118)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c0d4_2b1160.json?c=gt-nuc_11588&label=id:node_6820532
first seq 2023-04-05
Most Recent 2023-05-07
EPI_ISL_17687988 EPI_ISL_17639793 OQ977765.1 EPI_ISL_17588167 OQ871280.1 EPI_ISL_17636030 EPI_ISL_17689124 OQ932331.1 EPI_ISL_17689126 EPI_ISL_17685857 EPI_ISL_17688687 OQ977717.1 EPI_ISL_17616014 OQ932414.1 
gisaid query,
C5849T, A11588G, A21999C

**Comment by FedeGueli** [comment]
Designated HC.1 via https://github.com/cov-lineages/pango-designation/commit/c65ee84dee0514580a6cc50ac8b2301ea0dee0d6
