### ISSUE TITLE
Hongkongese FQ.1 Saltation Singlet with 17 ORF1ab Residue Substitutions and Restored ORF8

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1060]
Hong_Kong/VB23204967/2023|EPI_ISL_18466251|2023-10-27
Southern District, Hong Kong SAR, China

FQ.1> T6571C> C26537T> T378C(Orf1a:V38A), C503T(Orf1a:P80S), C629T(Orf1a:L122F), T1354C, A1818G(Orf1a:K518R), C2721T(Orf1a:A819V), G2897A(Orf1a:A878T), C3619T, A4233G(Orf1a:D1323G), C5178A(Orf1a:T1638N), A5227G, C7644T(Orf1a:A2460V), A7986T(Orf1a:Q2574L), C9073T, G9383T(Orf1a:A3040S), C10279T, G11083T(Orf1a:L3606F, masked by Usher), A12762G(Orf1a:D4166G), C17626T(Orf1b:H1387Y), C17733T, G18340A(Orf1b:V1625I), G19282A(Orf1b:D1939N), G19480A(Orf1b:G2005S), C19524T, T22729C, G23429A(S:A623T), C23763T(S:T734I), C26198T(Orf3a:T269M), G27087A(M:G189S), C27208T(Orf6:H3Y), T27504C, T27780C(Orf7b:F9L), T27889Crev, del28254(Orf8:I121fs), C28957T, A29700G
35 substitutions and 1 deletion(frameshift)

> T27889Crev strengthens the expression of ORF8 (Credit to @NkRMnZr and @ryhisner)

del28254=I\*121-122SKRTNLNV\*

FQ.1> T6571C> C26537T mainly circulates in Australia.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_2fb68_8e8790.json
![2023-11-06 (4)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/617cd69b-4bce-4843-aa5f-f1fa06f93ea1)

**Comment by Huachuan1120** [comment]
The title should be changed to FQ.1.
Also attach picture
![Uploading IMG_5829.png…]()

**Comment by Over-There-Is** [comment]
> The title should be changed to FQ.1. And attach picture！ ![IMG_5829](https://user-images.githubusercontent.com/142312996/280743406-6c9ce23a-a40f-46f8-8cc3-76ebf22679a0.png)

Thank you! It was an Typo, sorry.

**Comment by Over-There-Is** [comment]
del28254=I121S, *122K, 123R, 124T, 125N, 126V, 127*

ATC TAA ACG AAC AAA CTT AAA TGT CTG A
TCT AAA CGA ACA AAC TTA AAT GTC TGA

**Comment by ryhisner** [comment]
This is very likely an example of a sequence whose mutations were partly acquired over the course of a chronic infection and partly through molnupiravir treatment. 
<img width="966" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1e7f8087-2b22-4fa1-a9b9-0f858710f655">

**Comment by FedeGueli** [comment]
@ryhisner do you thinkit is MOV related? would you like to argument that here?

**Comment by Over-There-Is** [comment]
#BA.5# #Saltation# #TRS??#

**Comment by Over-There-Is** [comment]
"∆28254 is actually an extremely common deletion. It's one of the ways the virus increases N and ORF9b expression through creating more extended homology with the TRS-L." - By @ryhisner

**Comment by FedeGueli** [comment]
> #BA.5# #Saltation#

yeah i was waiting to see if more than one pops thx.

**Comment by FedeGueli** [comment]
Still singlet closing it for now.
