### ISSUE TITLE
Potential recombinant between XBB.1.16/XBB.2.3.5 or XBB.2.3.16  ( 12 samples , 7 countries India, China via India, Germany, England, Singapore, Australia, Russia, Japan ) with S:157S, S:184V, S:T478N, S:P521S, ORF1A:P971L

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1065]
I was not able to establish with sufficient evidences which are the donors of this recombinant,
so i let it to a further analysis putatively i establish them as **XBB.2.3.5** or **XBB.2.3.16** and [XBB.1.16 + T12538C](https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?nucMutations=T12538C&nextcladePangoLineage=XBB.1.16*&)

the point i would able to do are:
**3 Breakpoints**
10079-11749 unknown XBB lineage
BP Nr 1
11750-12730 XBB.1.16
BP Nr 2
12731-27430 XBB.2.3* 
BP. Nr.3
27431-3'end of genome XBB.1.16
Diagram: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=T12538C&nextcladePangoLineage=XBB.1.16*&nucMutations1=C2662T%2CC3177T%2CA4336G&aaMutations2=S%3AT478N&nextcladePangoLineage2=XBB.2.3*&analysisMode=CompareEquals&
![Uploading Schermata 2023-11-07 alle 15.22.48.png…]()

Note that this lineage has also C28471T as XDA but in XDA that bit is inherited by FL.1.5.1

Query : T19176C,C2662T, C3177T,

Samples: 5

IDs:
EPI_ISL_18320731, EPI_ISL_18361846, EPI_ISL_18454917,
EPI_ISL_18465473, EPI_ISL_18465478

Countries
![Schermata 2023-11-07 alle 15 24 33](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/83c91b50-91b4-4f11-86d6-affd8980182d)

Tree:
 ![Schermata 2023-11-07 alle 15 30 22](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2de4fc93-f491-42ab-97c7-4e3e62ed6f6d)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_e7a7_a49bf0.json?label=id:node_11074486

Rapid overview:
![Schermata 2023-11-07 alle 15 29 27](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/017a4565-459f-47d6-ace5-fa58881df287)

PRIVATE MUTATIONS:
C2662T, C3177T (ORF1A:P971L) , A4336G, C10078T, T19176C, C21622T, C28471T, C29272T

**Comment by aviczhl2** [comment]
I finally realized how to search GenBase metadata. Maybe we're able to get this automated. (Still gaps need filling)
  
We first get the C_AA id from usher, then append that id after https://ngdc.cncb.ac.cn/genbase/search/gb/ we can get that metadata. 

https://ngdc.cncb.ac.cn/genbase/search/gb/C_AA045546.1

 Location/Qualifiers
     source          1..29772
                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230916-3547/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 27; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-09-14"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in India"

**Comment by FedeGueli** [comment]
+1 Tasmania

**Comment by FedeGueli** [comment]
+1 Germany

**Comment by FedeGueli** [comment]
+1 Russia

**Comment by FedeGueli** [comment]
+1 Germany

**Comment by FedeGueli** [comment]
11 now +1 Japan (new Country)

**Comment by FedeGueli** [comment]
12 but no recent sample closing it.

**Comment by FedeGueli** [comment]
<img width="1173" alt="Screenshot 2024-01-31 alle 10 59 04" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/73355ae6-339d-46ca-86ec-49e727e92636">
up to 19 but the query doesn't catch the new indonesian sample
