### ISSUE TITLE
GW.5.3.1 + S:ins186:NVAHW, swiped from N:316-321 (4 seq, Netherlands, Australia, Ohio ; Jan 2)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1066]
### **Description**
**Sub-lineage of:** GW.5.3 (XBB.1.19.1.5.3)
**Earliest sequence:** 2023-9-23
**Most recent sequence:** 2023-10-3
**Continents circulating:** Oceania (1), Europe (1)
**Countries circulating:** Netherlands (1), Australia (1)
**Number of Sequences:** 2
**GISAID AA Query:** 186NVAHW, -K2T
**GISAID Nucleotide Query:** T3321C, G8015T
**CovSpectrum Query:** Nextcladepangolineage:GW.5.3* & T3321C & G8015T
**Substitutions/Deletions/Insertions on top of GW.5.3:**
**Spike:** ins186:NVAWH
**ORF1a:** V1019A, A2584S
**Nucleotide:** T3321C, G8015T, ins22120:AATGTCGCGCATTGG

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/GW.5.3_ins186_NVAHW.json?c=gt-ORF1ab_2584&label=id:node_3206666 
<img width="1340" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/acfea6f3-cdcf-4d03-9226-98dd7274bb41">

**Evidence**
This 15-nucleotide mutation is an exact match for a stretch of 15 nucleotides in nucleocapsid ranging from 29221-29235: AATGTCGCGCATTGG. Even if you chop off four nucleotides from both ends, the middle seven nucleotides (TCGCGCA) are found nowhere else in the SARS-CoV-2 genome. Coming from independent labs from different continents and sharing two mutations (T3321C, G8015T) that have never occurred together in any sequence since the beginning of the pandemic, there can be little doubt this is real. 

Incredibly, this same insertion, in the exact same location, was in an XBC.1.2.1 sequence from Denmark collected in December 2022. It seems clear there's something more than random luck involved in this one, though I have no idea what the mechanism might be. The Czech sequence looks perfectly clean. EPI_ISL_16350152

<img width="1409" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d597d6f0-a19e-46bd-a1d9-737cc5498974">

There have been four other sequences with the same 15-nuc insertion but in other parts of the genome. One, an AY.4 from the Czech Republic, looks clean, but the others have at least something that makes me unsure how genuine they are. All are singlets.

• N:ins242:NVAHW, ins28999:AATGTCGCGCATTGG – AY.4, Czech Republic, 2021-11-22, EPI_ISL_18249901

Sequence below has N’s at nucleotides at -2 and -4 positions relative to the insertion. 
• S:ins212:NVAHW, ins22198:AATGTCGCGCATTGG – BQ.1, USA, Texas, 2023-2-23, EPI_ISL_17180799

Sequence below has a frameshift in spike
• N:ins30:NVAHW, ORF9b:ins:MSRIG, ins28363:AATGTCGCGCATTGG – B.1.1.7, Italy, 2021-6-11, EPI_ISL_2922994

Sequence below has a frameshift about 80 nucs downstream of the insertion
• S:ins214:NVAHW, ins22204:AATGTCGCGCATTGG – B.1, USA, New York, 2021-3-22, EPI_ISL_2965162

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18411659, EPI_ISL_18471183
</details>

**Comment by FedeGueli** [comment]
2 sample caem in November from Ohio, since no new sequence popped up i m closing it
