### ISSUE TITLE
JY.1/XBB.1.16.24 recombinant with S:N641S and ORF1a:S2535L (44 sequences - 11 countries as 12/20)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1067]
First spotted and described by Ryan Hisner @ryhisner (edited)

Another recombinant XBB.2.3/XBB.1.16 recombinant emerging from India.

This time the recombination is quite clear with a single Breakpoint
1-23522  < JY.1
BP
25410- 3'end of genome < XBB.1.16.24

[JY.1 Donor](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2d7e5_a33d50.json?c=gt-ORF8_8&gmax=28259&gmin=27894&label=id:node_3967139)
[XBB.1.16.24 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34d30_ac30b0.json?f_userOrOld=uploaded%20sample&label=id:node_3265326): 

_Private mutations_:
T2552C, C5173T ,C7869T (**ORF1a:S2535L**), T10891C, A23484G (**S:N641S**)  

_Mutations from_ **JY.1:** C4234T, ORF1a:P1786L (C5622T), ORF1a:G2091S (G6536A),  C7303A,ORF1a:P3504L (C10776T), ORF1b:K2579R (A21203G) , S:G184V (G22113T), ,S:D253G (A22320G),  C22624T, S:P521S (C23123T),S:E654K (G23522A)

_Mutations from_ **XBB.1.16.24** : A25410G, Orf3a:E194K (G25972A), Orf8:G8* (G27915T), Orf9b:I5T (T28297C), Orf9b:N55S (A28447G), C29386T

_Diagram:_
![Schermata 2023-11-08 alle 00 24 36](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/842c7a48-5fe1-48f5-9cc8-f76a9776ef11)
https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?nucMutations=A25410G%2CG25972A%2CC7869T&nucMutations1=G27915T%2CA28447G%2CC29386T%2CA25410G%2CG25972A%2C25410G&nextcladePangoLineage1=XBB.1.16.24*&nextcladePangoLineage2=JY.1*&analysisMode=CompareEquals&

_Tree:_
![Schermata 2023-11-08 alle 00 26 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bdb0735b-fa3c-4e64-94e3-1184690a522b)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2d7e5_a33d50.json?c=gt-ORF8_8&label=id:node_3967104

_Gisaid query_: **A25410G, G25972A, C7869T**

_Samples:_ 17
First collected on 2023-09-12 in Illinois - Us
EPI_ISL_18233959, EPI_ISL_18315295, EPI_ISL_18326042,
EPI_ISL_18331958, EPI_ISL_18362750, EPI_ISL_18379967,
EPI_ISL_18379983, EPI_ISL_18421357, EPI_ISL_18438651,
EPI_ISL_18439804, EPI_ISL_18441663, EPI_ISL_18444719,
EPI_ISL_18452226, EPI_ISL_18454881, EPI_ISL_18457552,
EPI_ISL_18457741, EPI_ISL_18464696

Countries:
![Schermata 2023-11-08 alle 00 31 32](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/6aadfaba-498a-4171-bf57-3f46e12c7f99)

**Comment by FedeGueli** [comment]
+2 Denmark , Russia

**Comment by FedeGueli** [comment]
+1 England

**Comment by FedeGueli** [comment]
ping @corneliusroemer although small 6/24 samples have been collected in November , i bet this is much bigger where it emerged.

**Comment by FedeGueli** [comment]
30 now last ones from Scotland, Italy, France cc @corneliusroemer maybe this is big enough and enough spread to be designated.

**Comment by FedeGueli** [comment]
34 now mos recent sample England 11/25

**Comment by FedeGueli** [comment]
+3 France

**Comment by aviczhl2** [comment]
44 now

**Comment by FedeGueli** [comment]
I m proposing it

**Comment by FedeGueli** [comment]
Transferred to https://github.com/cov-lineages/pango-designation/issues/2420
