### ISSUE TITLE
FL.2.3+S:Q14R, L455F on N:R189L>S:F456L branch(8 seq, 3 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1068]
FL.2.3>G28839T(N:R189L)> T22928C(S:F456L)> G22927T(S:L455F)> G198A, A21603G(S:Q14R)

Subbranch of #526#branch1, potential homogenous to #818. I'm not sure if the L455F convergent or not.

Query: A21603G, G22927T, G28839T

Earliest Sequence: 09-03 Altay, Xinjiang, China EPI_ISL_18494071
Latest Sequence: 11-22 Colorado, US EPI_ISL_18656637
Regions Detected: China 6(Shanghai 5, Xinjiang 1), US 2(Colorado), Russia 1(Sankt-Peterburg)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json?label=id:node_6795306
![2023-11-11 (6)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/7b722e01-d5b1-42d3-b958-bd3659d516ff)

<details><summary>Sequences:</summary>

EPI_ISL_18465384, EPI_ISL_18475162, EPI_ISL_18487615,
EPI_ISL_18494071, EPI_ISL_18518399, EPI_ISL_18602672,
EPI_ISL_18655304, EPI_ISL_18656637
</details>

**Comment by Over-There-Is** [comment]
Be aware. Lots of duplicated sequences from China are uploaded.

**Comment by FedeGueli** [comment]
> Be awared. Lots of duplicated sequences from China are uploaded.

Thank you! but involving this specific lineage or all lineages?

**Comment by Over-There-Is** [comment]
> > Be awared. Lots of duplicated sequences from China are uploaded.
> 
> Thank you! but involving this specific lineage or all lineages?

Shanghai/SCDC-14720/2023|EPI_ISL_18481215|2023-10-17=Shanghai/SCDC-XG10-14720/2023|EPI_ISL_18475162|2023-10-17

**Comment by Over-There-Is** [comment]
Saint Petersburg +1

**Comment by Over-There-Is** [comment]
Xinjiang/XJCDCALT-141/2023|EPI_ISL_18494071|2023-09-03 Altay, Xinjiang, China without any Orf1a mutations.

**Comment by Over-There-Is** [comment]
![2023-11-11 (4)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/ce6292ab-37c1-45ab-b7ab-aedf75b80019)
Border to Russia, Kazakhstan and Mongolia

**Comment by Over-There-Is** [comment]
This branch probably circulates in Central Asia for a while. #Emerged in an undersampled area#

**Comment by FedeGueli** [comment]
+1 Xinjiang . It seems fast.

**Comment by Over-There-Is** [comment]
> A21603G, G22927T, G28839T



> +1 Xinjiang . It seems fast.

Already counted. Still 4. A Shanghai sequence is duplicated.

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1815d_76bd80.json?label=id:node_3389219
![Schermata 2023-11-17 alle 14 39 03](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/14c6b4fc-45fb-4f5c-9425-3bd444f1efe0)

**Comment by Over-There-Is** [comment]
Shanghai/SCDC-XG10-14819/2023|EPI_ISL_18518399|2023-10-16

**Comment by Over-There-Is** [comment]
No more sequence recently.

**Comment by Over-There-Is** [comment]
Shanghai +1

**Comment by FedeGueli** [comment]
It has no chance to compete but it would be nice to understnad where it is still circulating. reopened to track until the end of this year

**Comment by Over-There-Is** [comment]
Colorado US

**Comment by FedeGueli** [comment]
Closing it for now. Pls keep it checked if it will make a comeback.
