### ISSUE TITLE
HK.13.1 with S:E406Q, S:Q409E (Poland, Denmark 5 seq, Dic 9)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1069]
**Description**
**Sub-lineage of:** HK.13.1 (EG.5.1.1.13.1—has FLip)
**Earliest sequence:** 2023-10-13
**Most recent sequence:** 2023-10-13
**Continents circulating:** Europe (4)
**Countries circulating:** Poland (4)
**Number of Sequences:** 4
**GISAID Nucleotide Query:** C18166T, G22778C, C22787G
**CovSpectrum Query:** Nextcladepangolineage: HK.13* & S:E406Q & S:Q409E
**Substitutions on top of HK.13.1:**
**Spike:** E406Q, Q409E
**ORF1b:** P1567S (NSP14_P43S)
**Nucleotide:** C18166T, G22778C, C22787G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/HK.13.1__E406Q_Q409E.json?c=gt-S_409&gmax=25384&gmin=21563&label=id:node_3508421 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/HK.13.1__E406Q_Q409E.json
<img width="1452" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7e042dc8-cc4a-4bb4-b3b0-b83128d6e9bd">

**Evidence**
The mutation S:Q409E has only ever occurred in 34 sequences and S:E406Q in 783 sequences according to CovSpectrum. S:Q409E requires a C->G mutation, which is the rarest type of nucleotide mutation. S:E406Q, meanwhile requires a G->C mutation, which is the 4th-rarest type of nucleotide mutation. This branch acquired both mutations in one jump. 

Remarkably, both of these rare mutations were also acquired simultaneously by one previous sequence, an XBB.1.5.33 from Michigan, USA, collected in April 2023. EPI_ISL_17763872

<img width="1351" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c1d82d91-7fd0-42b9-b9ac-5a6cbabda08f">

As you can see from the depiction below, each mutation occurs immediately after the canonical BA.2 mutations S:D405N and S:R408S, which I feel pretty certain are extensively involved in important epistatic interactions, likely ones that have been key to the success of BA.2 and BA.5 relative to BA.1, which, despite infecting more people in a shorter amount of time than any other variant, has failed to produce any offspring lineages or successful recombinants, in stark contrast to BA.5 and especially BA.2, which has given birth to dozens of successful chronic-infection saltation variants and recombinants.

<img width="1454" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/29e2cf20-969e-46c1-8520-2e8aefdf5bf1">

I have no idea what the exact consequences of this rare combinational duo might be, but the fact that they have been acquired independently once before suggests there’s a possibility they might be doing something productive together that neither is capable of doing independently. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18474122-18474125
</details>

**Comment by oobb45729** [comment]
Could the "optimal positive charge" theory I talked about in https://github.com/cov-lineages/pango-designation/issues/1901#issuecomment-1555978995 be the reason?
More examples since that thread:
HV.1(XBB+L452R) with K444T or K444N.
D420N in XAY (which has an RBD that is less basic than most circulating lineages).
BA.2.86 is an outlier though.

**Comment by oobb45729** [comment]
By the way, E406Q and N417Y also appeared together twice, in BA.5.2+ORF1b:T1050N and BA.5.2.1.
See https://github.com/cov-lineages/pango-designation/issues/1237.

**Comment by FedeGueli** [comment]
Popped up in Denmark but likely too slow clsoing it for now
