### ISSUE TITLE
HV.1/BA.2.86.1 recombinant, 1 sample from Sweden

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1070]
**Description:** HV.1/BA.2.86.1 recombinant, 1 breaking point, Spike from BA.2.86.1
**Private mutations**: G29468A 
extra from HV.1: C1884T, C5835T and A20652G (4 samples from Sweden with these mutations)
extra from BA.2.86.1: A25360G, C28528T and G29063T (19 samples from Sweden and Finland)              
**Breakpoint:** between nucleotide 20652 and 21633 (end of ORF1b or at the very start of the Spike)
**One sequence from:** 2023-10-29 from Sweden
**Countries circulating:** Sweden
**GISAID query:** A20652G, A25360G
**Sample:** EPI_ISL_18469551
**Nextclade:**
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/0080bdf6-f916-49b6-81b5-5612ac1c5405)

**Comment by FedeGueli** [comment]
It didnt spread. closing it for now
