### ISSUE TITLE
Usher bugs on JN.1 branch.

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1072]
@AngieHinrichs, there seems to be some bugs regarding placement of JN.1

1: The decision point seems on a weird C21610T reversion branch instead of the defining S:L455S. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3e2250e8-072a-42cc-8987-c442cd403a51)

2: The tree seems full of flip-flop reversions. Even the main branch is very flip-flop. Labeled are all reversion flip-flop branches. As can be seen, almost everywhere on the tree is some form of flip-flopping. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/57bbf2a6-c9b6-46fd-bc44-9babd4026699)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice24_genome_ce5a_c32c80.json?branchLabel=back-mutations&label=id:node_4426871&showBranchLabels=all)

These bugs make the tree look quite weird under the current stage and infomation retriving very difficult.

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2, that view with the back-mutations is very helpful.  Masking 21610 in BA.2.86 as suggested by @Over-There-Is should help a lot.  I will mask reversions of these mutations in all of BA.2.86 too:
* C21711T (S:S50L)
* T22032C, C22033A, A22034G (S:F157S, S:R158G)
* G23012A (S:E484K)
* A26610G (M:T30A)

**Comment by AngieHinrichs** [comment]
Again, the benefit of branch-specific masking is that it prevents those kinds of structural problems in the tree.  But later, if there are true reversions or recombinants of BA.2.86 that legitimately remove those mutations whose reversions are masked, the drawback is that the tree will say the sequences have those mutations even though they don't.

**Comment by FedeGueli** [comment]
Thank you @AngieHinrichs

**Comment by Over-There-Is** [comment]
Gisaid and Usher have aligned insertion to codon. So the insertion has been analyzed as ins21610ATGCCGCTGTTT + T21610C.

**Comment by aviczhl2** [comment]
> Gisaid and Usher have aligned insertion to codon. So the insertion has been analyzed as ins21610ATGCCGCTGTTT + T21610C.

Yeah but that site is a hot-spot for mutation too.

 Further mutations may happen inside the insertion part and at that time usher will be unable to handle.

**Comment by Over-There-Is** [comment]
Spain/GA-SCQ_265071/2023|EPI_ISL_18400575|2023-10-02 seems having the real T21610C.
And a England branch(EPI_ISL_18392760, EPI_ISL_18412652, EPI_ISL_18450613), has ins21608TCATGCC**T**CTGT instead of ins21608TCATGCC**G**CTGT.
