### ISSUE TITLE
HK.13 + S:T22N, N481K; ORF1a:S167G, A2636S, L3829F (61 seq, 11 countries; Feb 10)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1073]
### **Description**
**Sub-lineage of:** HK.13
**Earliest sequence:** 2023-10-2
**Most recent sequence:** 2023-10-22
**Continents circulating:** Europe (3)
**Countries circulating:** Sweden (2), Denmark (1)
**Number of Sequences:** 3
**GISAID Nucleotide Query:** A764G, C21627A New better query :   **C21627A,G8171T,T13174C (Edited)**
**CovSpectrum Query:** Nextcladepangolineage:HK.13* & [3-of: A764G, G8171T, C11750T, C21627A]
**Substitutions on top of HK.13:**
**Spike:** T22N, N481K
**ORF1a:** S167G, S944L, A2636S, L3829F (NSP1_S167G, NSP3_S126L, NSP3_A1818S, NSP6_L260F)
**Nucleotide:** A764G, C3096T, G8171T, C8293T, C11750T, A11782G, T13174C, C21627A, T23005A

**Phylogenetic Order of Mutations:** C3096T (ORF1a:S944L)   **→**   C8293T, A11782G   **→**   T13174C   **→** T23005A (S:N481K)   **→**   A764G, G8171T, C11750T, C21627A (ORF1a:S167G, A2636S, L3829F, S:T22N) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/HK.13_T22N_N481K_L3829F.json?c=gt-S_22&gmax=25384&gmin=21563&label=id:node_3513138 

<img width="1446" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c7b820dc-98c6-43b1-afa9-55738b9a862b">

**Evidence**
Very small and unlikely to be widely significant, but I find the mutations interesting, so I threw this together. S:T22N adds a glycan due to the out-of-frame S:∆24-26 deletion creating a serine two residues after S:22. ORF1a:L3829F has been one of the most convergent mutations of the past two years, present in all BQ* and XBB.1.16* lineages and many others. S:N481K is of course in BA.2.86*. It’s much more common to see ORF1a:S166G, but I wonder if ORF1a:S167G has much the same effect, whatever it is. 

The last five mutations in this lineage are all non-synonymous, indicating positive selection.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18377562, EPI_ISL_18465573, EPI_ISL_18469117
</details>

**Comment by FedeGueli** [comment]
+1 denmark

**Comment by aviczhl2** [comment]
17 now

**Comment by FedeGueli** [comment]
Very big jump. Lets wait if ti spreads outside sweden as fast as there.

**Comment by olias120676** [comment]
24 now
+5 Sweden
+1 Spain
+1 Slovenia

**Comment by FedeGueli** [comment]
30 now mostly Sweden

**Comment by FedeGueli** [comment]
+1 Denmark

**Comment by FedeGueli** [comment]
There is a better query for this one:   C21627A,G8171T,T13174C

it finds 47 now.

**Comment by FedeGueli** [comment]
@ryhisner please propose this one.

**Comment by FedeGueli** [comment]
> @ryhisner please propose this one.

remainder @ryhisner

**Comment by FedeGueli** [comment]
59 now. still no samples from January. lets wait if some sequence pop up

**Comment by FedeGueli** [comment]
No sample from january closing it
