### ISSUE TITLE
EG.5.1.13+Orf1a:R135S(rev) (1314 seqs global > 30 countries，further gaining Flip+S:A288S,P1162L 42 Seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1074]
There is a large EG.5.1+G670T(Orf1a:R135S)(rev) branch. 

Orf1a:R135S was a known homoplastic reversion designated in BA.2.23  https://github.com/cov-lineages/pango-designation/issues/546, so likely to be real. 

EG.5.1+C12439T+G670T(Orf1a:R135S)(rev)

GISAID query: C12439T,C241T,-T670G, C2334T, T22930A 
No. of seqs: 790(Australia, Belgium, Brazil, Canada, Chile, Denmark, UK, France, Germany, Greece, Iceland, Israel, Ireland, Italy,
Japan, Mexico, Netherlands, New Zealand, Peru, Portugal, Romania, South Korea, Spain, Sweden, Switzerland, USA)

GISAID query for sub-branch with S:A288S,P1162L,L455F: C12439T,C241T,-T670G, C2334T, G22927T

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice62_genome_11e92_d985f0.json?label=id:node_3453406)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e6ea27ac-5685-42fd-b28a-1837e71f305b)

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c0d84a9b-7e17-49ea-9793-c4d80dfd61e8)

It is faster than baseline EG.5.1 , and about the same speed with the whole EG.5.1 family(including Flips)

**Comment by FedeGueli** [comment]
i ve tried : C12439T,C241T,-T670G,  C2334T, T22930A that gives 790

**Comment by aviczhl2** [comment]
> i ve tried : C12439T,C241T,-T670G, C2334T, T22930A that gives 790

Oh I don't notice the C12439T mutation . Thanks for pointing out .

**Comment by FedeGueli** [comment]
cc @corneliusroemer maybe you could designate this one? the existence of one reversion in a defining mutation of BA.2 should be something to keep tracked also for potential recombinations in the future.

**Comment by aviczhl2** [comment]
862, Poland

**Comment by Over-There-Is** [comment]
Shanghai/SCDC-XG11-15119/2023

**Comment by aviczhl2** [comment]
1128, China. 
There is a S:A288S,P1162L.L455F sub-branch of 21.

**Comment by aviczhl2** [comment]
1189, Luxembourg, Norway.

**Comment by aviczhl2** [comment]
1218, Finland

**Comment by aviczhl2** [comment]
The Flip sub-lineage grows to 40.

**Comment by FedeGueli** [comment]
already +2 the flip branch

**Comment by FedeGueli** [comment]
> C12439T,C241T,-T670G, C2334T, G22927T

i ve misssed to trck this sorry, great you found. propose it together with the parental big lineage.
