### ISSUE TITLE
JN.7 with S:T20A, N30G (2-nuc), ORF1a:T987I + A4576T-T4579A nuc combo (12 seq, DK; Jan 1)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1076]
### **Description**
**Sub-lineage of:** BA.2.86.1 plus S:G594S proposed in  #856 by @outpfmance
**Earliest sequence:** 2023-9-18
**Most recent sequence:** 2023-10-23
**Continents circulating:** Europe (10)
**Countries circulating:** Denmark (10)
**Number of Sequences:** 6
**GISAID Nucleotide Query:** A21620G, A21650G, A21651G
**CovSpectrum Query:** Nextcladepangolineage:BA.2.86* & [3-of: A21620G, A21650G, A21651G]
**Substitutions on top of BA.2.86.1:**
**Spike:** T20A, N30G, G594S
**ORF1a:** T987I (NSP3_T169I)
**Nucleotide:** C2455T, C3225T, A4576T, T4579A, A21620G, A21650G, A21651G, T26460C, C29546A

**Phylogenetic Order of Mutations:** A4576T, T4579A, G23342A (S:G594S)   **→**   C3225T (ORF1a:T987I), T26460C, C29546A (3’ UTR)   **→**    C2455T   **→**   A21620G (S:T20A), A21650G, A21651G (S:N30G)    

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.2.86_T20A_N30G_G594S.json?c=gt-S_30&gmax=25384&gmin=21563&label=id:node_4423053
<img width="1439" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2b1fd777-0830-427f-a1c5-4fb9dc4c6a92">

**Evidence**
Initially, I wasn’t sure if the 2-nucleotide S:N30G mutation, accompanied by S:T20A, was real or an artifact induced by the complex nature of this region of spike, with multiple mutations and the unique S:16:insMPLF insertion. But these are clearly monophyletic, and there are now 10 sequences, so I feel pretty certain it’s real. 

A number of things make this small BA.2.86.1 branch exceptionally interesting to me. First, S:N30G is a mutation that has only ever appeared in one previous sequence, a BA.5.2 from Ohio, USA, collected 2022-8-21. Furthermore, all three nucleotide mutations that form S:T20A and S:N30G are A->G mutations. 

<img width="1496" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/fe21da2a-7605-4555-8a89-0477421a6a6c">

The BA.5.2 with S:N30G, fascinatingly, had two additional A->G mutations in this region in addition to A21650G and A21651G—A21583G (synonymous) and A21792G (S:K77R). All four of these A->G mutations were simultaneously acquired, which is unlikely to be a coincidence and suggests these A->G mutations somehow function together.

<img width="1463" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0b8cc756-be48-4473-8383-7591b9314e26">

To me, these simultaneous A->G mutations in the same region—suggest a couple possibilities:

1. These mutations create a new secondary RNA structure in that G nucleotides work together to stabilize.
2. The A->G mutations foster binding by some viral or cellular protein to the spike sgmRNA inside the cell. I don’t have nearly enough knowledge of cellular molecular biology to say much of worth on this matter, so I’ll leave it to those more informed than me to comment on whether or not this is a plausible hypothesis.  

Another fascinating aspect of this branch is the A4576T-T4579A mutational duo, which it simultaneously acquired. These two synonymous nucleotide mutations frequently occur together—far more often than would be expected by chance. According to CovSpectrum, 98.3% of the 11047 sequences with A4576T also have T4579A. Conversely, 22.23% of all sequences with T4579A have A4576T. A->T and T->A are both rare nucleotide mutations, making the association between these two still more remarkable. 

What could explain this extraordinary correlation between two rare, synonymous nucleotide mutations? I don’t pretend to know the ultimate reason or whether it is adaptive, but I feel pretty confident it is a TRS-related phenomenon (TRS = transcription regulation sequence). Here is a view of these mutations adapted from Nextclade images. You can see that it forms a sequence that is a fairly good match for the TRS-L, including an impressive degree of extended homology. 

<img width="1507" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c0500e0b-e5fa-43ac-abb3-594759776996">

Further evidence that these mutations are TRS-related comes from a smaller number of sequences that have multiple additional mutations that combine to make an ever more impressive match for the TRS-L and its surrounding nucleotides. There have been >50 such sequences according to CovSpectrum. 

<img width="1458" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9764a2ed-d53a-4fad-8048-f584d08048a9">

Finally, this branch also possesses C29546A, which is in the 3’ UTR of the genome. This does not appear to be in a crucial location according to the secondary structures I’ve seen, but nevertheless, transversions in the 3’ UTR are uncommon, and this one has occurred in fewer than 2500 sequences throughout the pandemic. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18360400, EPI_ISL_18360504, EPI_ISL_18442871,
EPI_ISL_18442913, EPI_ISL_18442950, EPI_ISL_18442971,
EPI_ISL_18464562, EPI_ISL_18464624, EPI_ISL_18464651,
EPI_ISL_18494612
</details>

**Comment by FedeGueli** [comment]
Sublineage of https://github.com/sars-cov-2-variants/lineage-proposals/issues/856

**Comment by FedeGueli** [comment]
+1  still seems slow

**Comment by FedeGueli** [comment]
12 now but very slow. closingit for now
