### ISSUE TITLE
HV.1/XCR recombinant in USA(3 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1077]
XCR+T1973C(rev), C2334T,A3852G,C8016T,C13426T

Orf1a:A690V,E1196G,A2584V

T1973C(rev), C2334T,A3852G from an HV.1 branch. 
C8016T,C13426T from main XCR branch

HV.1--XCR
Breakpoint between 3853 and 5719

GISAID query: C2334T,A3852G,C8016T
No. of seqs: 2(USA-VA 1 TX 1)

EPI_ISL_18423728,USA-TX 2023-10-15
EPI_ISL_18378060, USA-VA 2023-9-23

Though it may not be much faster than XCR, I think worth noticing it as it is also a recomb of recomb of recomb. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_17428_39320.json?c=gt-ORF1ab_690&label=id:node_3662178)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/04b107e9-11ba-4b95-85f0-31050dfa1fb9)

**Comment by aviczhl2** [comment]
+1 USA-IL seq not on GISAID. 

USA/IL-RIPHL_21375_G/2023|OR792336.1|2023-10-01

**Comment by aviczhl2** [comment]
+1 WI

**Comment by aviczhl2** [comment]
+1 CT

**Comment by FedeGueli** [comment]
Still no recent ones.thx
