### ISSUE TITLE
HK.3+S:Q675H(12 seqs, 4 countries, 1.5% in Shanxi)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1080]
HK.3+C12415T+C17397A+C2395T+C26534T+G23587C(S:Q675H)

GISAID query: C2395T,C26534T,G23587C
No. of seqs: 7(China-Shanxi 4 Japan 1 USA 2)

6 on GISAID, 1 USA seqs not.  OR710705.1

4/257 of Shanxi seqs from 2023-9-1. nearby provinces have very little seqs so detected in USA and Japan before detecting in other provinces.

First: EPI_ISL_18495419, Shanxi, 2023-9-8
Latest: EPI_ISL_18495527, Shanxi, 2023-10-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_341a8_193fa0.json?label=id:node_11091709)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/25bdeba1-f612-429a-a09a-a5f90a7a1198)

**Comment by aviczhl2** [comment]
+1 Shanghai +1 South Korea

**Comment by aviczhl2** [comment]
+1 Henan

**Comment by FedeGueli** [comment]
No recent sample in December and neither in the batch from Shanxi, closing it for now
