### ISSUE TITLE
GW.5.3 mini saltation  with S:N185del / S:F186I  and S:L>I368V (6 UK, Australia)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1083]
Just spotted using the Dave McNally tool an interesting sublineage of GW.5.3 with a deletion at 185 ( same reisdue of the insertion described by @ryhisner in #1066 ) and the defining of XBB S:L368I mutated to V.

Query : C900T, T4057C, C28737T

Defining mutations:
GW.5.3 > Orf1a:I694V (A2345G) > ORF1a:S212L (C900T), T4057C, S:I368V (A22664G),N:A155V (C28737T)

Samples: EPI_ISL_18497083, EPI_ISL_18497268, EPI_ISL_18497373,
EPI_ISL_18497375, EPI_ISL_18497383

Tree:
![Schermata 2023-11-14 alle 12 26 49](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/030979f5-61e6-4ac9-8abb-54d11e3d9eec)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_49247_351d20.json?c=gt-S_368&label=id:node_3207039

**Comment by ryhisner** [comment]
I think this is at least the second time a GW.5* lineage has acquired the S:∆N185/F186I mutation. #1034 is one other example.

**Comment by FedeGueli** [comment]
> I think this is at least the second time a GW.5* lineage has acquired the S:∆N185/F186I mutation. #1034 is one other example.

Thx @ryhisner yes it is

**Comment by HynnSpylor** [comment]
One more seq in Tasmania, Australia

**Comment by FedeGueli** [comment]
no new sample coming for now.

**Comment by FedeGueli** [comment]
no new sample came. closing it
