### ISSUE TITLE
JN.1  with S:M1229I ( 34 Sequences, 5 countries, mainly Canada- 4 States) one with S:T572I

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1087]
JN.1  > S:M1229I (G25249T) 

Gisaid query: G25249T,T27810C,T3565C

Samples:
EPI_ISL_18486527, EPI_ISL_18492896, EPI_ISL_18496250,
EPI_ISL_18501461, EPI_ISL_18504052, EPI_ISL_18505281,
EPI_ISL_18505329, EPI_ISL_18505452

First sample collected in Puerto Rico on 20/10/2023

Countries : Canada (Alberta, Ontario, Saskatchewan), Puerto RIco, Belgium

Tree:
![Schermata 2023-11-16 alle 09 31 53](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/aef22e14-54ca-4646-b99e-ca7b828662d6)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2bd52_5d30f0.json?label=id:node_4439124

Query for the S:T572I branch  : G25249T,T27810C,C23277T

**Comment by FedeGueli** [comment]
+2 Alberta

**Comment by FedeGueli** [comment]
+ 5 Ontario, it doenst seem the usual canadian cluster tough looking at the age of patients involved

**Comment by FedeGueli** [comment]
Now entered some long term care home. 23 now 5 countries.

**Comment by FedeGueli** [comment]
+2 Israel

**Comment by Memorablea** [comment]
JN.1.2 https://github.com/cov-lineages/pango-designation/commit/3a8e5905e6513c6f819bd4c66226e388dd5834b1

**Comment by FedeGueli** [comment]
Desingated JN.1.2 via https://github.com/cov-lineages/pango-designation/commit/3a8e5905e6513c6f819bd4c66226e388dd5834b1
