### ISSUE TITLE
 Widespread 8-nuc/4-aa branch of GJ.1 (S:A222V, 23 seqs,  16 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#109]
Baseline variant: https://github.com/cov-lineages/pango-designation/issues/2005 

(XBB.2.3.3 >> > C19884T > Orf8:E106Q (G28209C) >Orf1a:I4205V (A12878G NSP9_I65V)

Additional mutations: 
C1549T,C2902T, A3394T, G6008A, A6948G, G29229A, C1150T, C22227T

ORF1ab | V1915I, N2228S
S | A222V
N | R319H

GISAID query: C2902T, A3394T, G6008A, A6948G, G29229A, C1150T, C22227T
No. of seqs: 11 (India 2 China 1 USA 2(1 from Spain), Switzerland 1 South Korea 1 Austria 1 Australia 3)

First seq: EPI_ISL_17720450, India ,4-15
Latest: EPI_ISL_17719397, Switzerland, 5-7

Propose this because I found the S:A222V branch is quite widespread. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c3b9_405610.json?c=gt-nuc_1150)

<img width="1406" alt="Screenshot 2023-05-29 at 09 56 39" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/562c5f60-64de-4dae-93aa-4ed9c74eecc2">

**Comment by FedeGueli** [comment]
parent designated GJ.1

**Comment by aviczhl2** [comment]
new countries are New Zealand, Italy, Singapore and Canada, so 12 countries.

**Comment by aviczhl2** [comment]
23 seqs, Trinidad& Tobago, UK, Slovenia, Norway.

**Comment by FedeGueli** [comment]
Before adding the label I want to wait some more time to see if while the philippines wave  goes down then it slows exportations too. But i think this is one of the things to be proposed.

**Comment by FedeGueli** [comment]
It got designated GJ.1.1 !! via https://github.com/cov-lineages/pango-designation/commit/1e361ded69ba708ddc8e682d9489ea52b5f062c1

**Comment by aviczhl2** [comment]
@FedeGueli Please add a milestone for this.

**Comment by aviczhl2** [comment]
@FedeGueli  It shall be GJ.1.1
