### ISSUE TITLE
XBB.1.16.2/JN.1 recombinant, 14 seqs, Australia, USA, New Zealand, Canada

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1090]
Description: XBB.1.16.2/JN.1 recombinant, 1 breaking point, Spike from JN.1
Private mutations: C583T, C12970T, G25252T
from XBB.1.16.2: A5350G, A5689G, T8014G, G8872A
from JN.1: C11747T, T21610C
Breakpoint: between nucleotide 8872 and 11042
One sequence from: 2023-10-30 from NSW, Australia
Countries circulating: Australia
GISAID query: T8014G, G8872A, G11042T (edited om 02/21)
Sample: EPI_ISL_18513949
Nextclade:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/47f3c475-4fc1-4440-93c1-1c4552ae5362)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/e4b8628b-b2d6-4cb9-ad5d-cc548c5ce82f)

**Comment by FedeGueli** [comment]
Sorry i ve missed the proposal thank you @JosetteSchoenma

**Comment by Over-There-Is** [comment]
T21610C = Artefact

**Comment by FedeGueli** [comment]
No new sample of this one for now. Closing it.

**Comment by aviczhl2** [comment]
+1 Queensland

**Comment by aviczhl2** [comment]
+1 Australia NSW

**Comment by aviczhl2** [comment]
+1 VIC

**Comment by aviczhl2** [comment]
+2 Australia. 
The query now captures an unrelated USA sample, suggest to change.

**Comment by FedeGueli** [comment]
> +2 Australia. The query now captures an unrelated USA sample, suggest to change.

yeah 8 with the old query trying to find a new one.

**Comment by FedeGueli** [comment]
new query :G11042T,C583T,-A29086T,-T17065C,G8872A

**Comment by FedeGueli** [comment]
7 with G11042T,C583T,-A29086T,-T17065C,G8872A

**Comment by aviczhl2** [comment]
+1 USA

**Comment by JosetteSchoenma** [comment]
+1 Queensland

Query: T8014G, G8872A, G11042T

All are being called XDK by Nextclade!

**Comment by JosetteSchoenma** [comment]
+1 New Zealand

**Comment by JosetteSchoenma** [comment]
+1 (Western) Australia

**Comment by JosetteSchoenma** [comment]
+1 Queensland, Australia

**Comment by aviczhl2** [comment]
+1 with S:T573I

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by aviczhl2** [comment]
Seems dead.
