### ISSUE TITLE
HK.3+S:T732I(51 seqs, 5 countries, 9% Tasmania)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1092]
HK.3+C22849T,A28877T,G28878C+ C23757T(S:T732I)

usher masks 28877 and 28878 but all 51 seqs do have the mutations. 

GISAID query: C23757T,T22849C,G22927T
No. of seqs: 51(China 1 Singapore 1 USA 2(from Spain) Australia 47)

First: EPI_ISL_18324907, Australia, 2023-9-7
Latest: EPI_ISL_18510983, Australia, 2023-11-13

7/82 in Tasmania's seqs from 11-1.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2bfb2_9773e0.json?label=id:node_3520257)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f5a91227-f3e1-4414-b719-1ffb56666efd)

**Comment by FedeGueli** [comment]
@ryhisner i think this has the double nuc in N trs you talked about many times

**Comment by aviczhl2** [comment]
Designated HK.3.9
