### ISSUE TITLE
BA.2.86.1+ C7528T with S:N>K481R and then S:V1228L spreading in Denmark (15)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1094]
This lineage was spotted first by @ryhisner , we were a bit skeptical occuring next to the deletion, it was removed from Gisaid but now new sequences are accumulating.
Defining mutations:
BA.2.86.1 > C7528T > Orf1b:R188L(G14030T)= NSP12_R197L, Orf1b:Y1247C(A17207G)=NSP13_Y324C > S:N481K>R (A23004G)
then further acquired > S:V1228L (G25244T), T28229C

Query : G14030T,A17207G,A23004G

Samples : 8
EPI_ISL_18301101, EPI_ISL_18301121, EPI_ISL_18457540,
EPI_ISL_18457555, EPI_ISL_18457566, EPI_ISL_18498685,
EPI_ISL_18498751, EPI_ISL_18498763

Tree:
![Schermata 2023-11-20 alle 10 15 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/737ad731-896d-4ddb-b325-dde45bc5af5c)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2bc3b_a88ed0.json?label=id:node_4442321

One recent sample carries Orf10:S23F it could be a recombinant with any EG.5.1 lineage but with one mutation only hard to say

**Comment by FedeGueli** [comment]
+3 denmark

**Comment by FedeGueli** [comment]
15 but still Denmark only

**Comment by FedeGueli** [comment]
it seems near dead closing for now ( i suspect it was an artifact from the start now solved)

**Comment by Fearuncle** [comment]
now 98

**Comment by FedeGueli** [comment]
> G14030T,A17207G,A23004G

i see 17, which query do you use?

**Comment by Fearuncle** [comment]
used dave's tool it went back down to 17
