### ISSUE TITLE
Many(more than 3,000) XBB.1.5 misplaced as XBB.1.22+C28297T(reversion)+T17124C on usher

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#11]
I feel these branch-specific usher misplacement issues improper to propose on either usher or pango-designation. 

However, branch-specific usher misplacements have quite some importance to be warned to others and to be fixed if they happen on popular recent lineages. 

Finally there is a place to propose this and similar issues. Thanks @FedeGueli

@AngieHinrichs 
I find many XBB.1.5 misplaced as XBB.1.22+C28297T(reversion)+T17124C, simply adding 28297 to branch-specific mask for XBB.1.22 will solve this problem I guess. 

Maybe we shall make an anti-flip-flop rule that the most recent x(x= 3 or 5?) mutations shall not be reverted? Although far-away reversions may be real, reversions of most recent mutations are almost certainly misplacements.  For recombinants they'll still be placed near one of their donaters. Without flip-flop maybe we can see them more clearly. 

https://taxonium.org/?backend=https%3A%2F%2Fapi.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22XbB.1.22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%5D&mutationTypesEnabled=%7B%22aa%22%3Atrue%2C%22nt%22%3Atrue%7D
Taxonium tree:
<img width="1661" alt="Screen Shot 2023-05-07 at 07 29 50" src="https://user-images.githubusercontent.com/10445944/236650344-31e62f10-9024-40d2-bfc4-949453bf8c44.png">

**Comment by aviczhl2** [comment]
On tree including GISAID, it actually has at least 3,874 seqs. 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice38_genome_3ce0c_710d20.json?f_userOrOld=uploaded%20sample)
<img width="1389" alt="Screen Shot 2023-05-07 at 13 51 43" src="https://user-images.githubusercontent.com/10445944/236660203-87b3ec64-9953-4827-8f32-2fa244696b1e.png">

**Comment by FedeGueli** [comment]
Hi @aviczhl2 i have highlighted this in the commit of XBB.1.22 designation. i think that what is actually XBB.1.22 is just xbb.1.5, while the two xbb.1.22.1 and xbb.1.22.2 (and another i am tracking with T26597C, T28888A,A28615G,T23018C)   are real and likely earlier branches of  XBB.1.9 tree

**Comment by FedeGueli** [comment]
> On tree including GISAID, it actually has at least 3,874 seqs. [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice38_genome_3ce0c_710d20.json?f_userOrOld=uploaded%20sample) <img alt="Screen Shot 2023-05-07 at 13 51 43" width="1389" src="https://user-images.githubusercontent.com/10445944/236660203-87b3ec64-9953-4827-8f32-2fa244696b1e.png">

it is all the actually assigined XBB.1.22 without XBB.1.22.1 and .2 and  .X.

**Comment by aviczhl2** [comment]
> Hi @aviczhl2 i have highlighted this in the commit of XBB.1.22 designation. i think that what is actually XBB.1.22 is just xbb.1.5, while the two xbb.1.22.1 and xbb.1.22.2 (and another i am tracking with T26597C, T28888A,A28615G,T23018C) are real and likely earlier branches of XBB.1.9 tree


XBB.1.22=XBB.1+28297C+S:486P,   
having 28297 reverted we get XBB.1+S:486P, which is actually XBB.1.5.

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2!  I was away last week at a conference but am getting caught up now and doing some pruning and reoptimizing today.  Hopefully this will be fixed in tomorrow's build (2023-05-10).

**Comment by FedeGueli** [comment]
> is this recurring or a true recombinant? @FedeGueli @AngieHinrichs https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4ed1_b62fa0.json?c=gt-nuc_17124&f_userOrOld=uploaded%20sample&label=id:node_6825037 ![prob](https://user-images.githubusercontent.com/125747944/258051122-61d9a824-97d6-4c83-be86-c15d05bbb1b7.png)

This could be a real recombinant cause it has also the reversion of T2935C to 2935T ( defining of FY.6). Please propose it @NkRMnZr
