### ISSUE TITLE
XBC.1 with S:T478R,S:K444T and ORF1ab:Y5648C(6 sequences,Philippines,Australia and Hong Kong)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#110]
This is a new strain in the XBC* series, belonging to the XBC.1 * line, with the defining mutation S: T478R for XBB.1.16 and the immune escape addition S: K444T. It now has 6 sequences, although the growth advantage is not as good as that of XBC.1.6 *, but it is still of concern.
![IMG_0449](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/fa9acb2e-ce30-402a-a992-6c146d659285)

Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_13687_49b3d0.json?f_userOrOld=uploaded%20sample&label=id:node_4784325

Sequences:
EPI_ISL_17245001
EPI_ISL_17689805
EPI_ISL_17244999
EPI_ISL_17719935
EPI_ISL_17683241
EPI_ISL_17682924

**Comment by FedeGueli** [comment]
I was not able to find a reliable query for the bigger lineage starting with S:K478R.


Has to be noticed that this branch has an important reversion of A28271T>A that was a defining of all BA.2 Descendants.

28271 is right in the TRS of N and Orf9b.

![Schermata 2023-05-31 alle 23 39 51](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c71156ba-3125-434a-962d-9916c1c1468a)

@ryhisner could add something on its potential effect on TRS.

**Comment by ryhisner** [comment]
A28271T is actually a Kozak sequence thing. It cause an enormous drop in Kozac-sequence favorability—the single largest drop possible in a one-nucleotide mutation, in fact. The Delta deletion at 28271 has the same effect as A28271T does on the Kozak sequence, causing a change from A to T at the -3 position. 

I only recently learned about it myself, but the Kozak sequence, which consists of the nucleotides surrounding the start codon, helps determine the likelihood of whether an mRNA will get translated into a protein by a ribosome. The taller the letter in the image below, the greater the favorability for translation. 

The likely purpose of A28271T (or ∆28271) is to increase the expression of ORF9b. ORF9b is entirely contained within N but in a different reading frame. N's start codon comes first though, so the only way ORF9b can get translated on a ribosome is if the N start codon gets skipped over, which apparently happens a certain percentage of the time. This "leaky scanning" is more likely to occur if the Kozac sequence is unfavorable. 

I think the fact that all Delta and Omicron lineages have this Kozak-sequence-lowering change is a clear indication of the importance of ORF9b. And before that Alpha had the 3-nucleotide N:D3L mutation, whose main effect was to increase ORF9b expression. Put simply, the three most consequential VOC, and the two that have dominated the globe for nearly two years, have mutations that seem clearly designed to increase ORF9b expression. I don't think the full import of this is widely understood. IMO, this is a big deal. 

<img width="1451" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a0c5a5de-87f4-4ef5-a212-5466b51a1d76">

Anyway, addressing the topic at hand, I don't think this lineage actually has a reversion at 28271. I think that part of the genome in XBC lineages is from Delta, and it should therefore have ∆28271, which, as explained above, has basically the same effect on the Kozak sequence as A28271T (A->T at -3).

**Comment by FedeGueli** [comment]
Thx very much @ryhisner great comment and great questions.

**Comment by FedeGueli** [comment]
Designated XBC.1.7 via https://github.com/cov-lineages/pango-designation/commit/ff71f8bec3979aee90e214572eaead4fb2a37a05
