### ISSUE TITLE
BA.2.86.1 sublineage with S:F456V, ORF1a:A498G   (18 seqs  , 6 countries) 

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1102]
Defining mutations: (_Edited_)
BA.2.86.1>C1758G (ORF1a:A498G),  T22928G (S:F456V)
GISAID query:   : **C1758G, T22928G** (edited)
Earliest seq: 2023-11-09 (Sweden- EPI_ISL_18522850)
Most recent seq: 2023-11-09 (Sweden- EPI_ISL_18522961)
Countries detected: Sweden (2)

Usher Tree:
![QQ截图20231121204617](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/4790a2a2-304a-4ba7-8bdb-c40c526e18be)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_dcfd_c5d650.json

Recently nearly all S:F456X mutations are S:F456L (and S:F456L takes up more than 70% of recent seqs). Now some seqs attempt to get other changes on site S:F456, including these two Swedish BA.2.86.1 seqs.
![QQ截图20231121184049](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7db49899-cd2b-4cf8-85a6-9873a68a47c1)
![QQ截图20231121184039](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/192fa2a4-1ec7-43f3-8e75-efc0e28994f5)

Genomes:
EPI_ISL_18522850, EPI_ISL_18522901

**Comment by Over-There-Is** [comment]
V and L is quite similar. Both have alkyl group.

**Comment by Over-There-Is** [comment]
Found by @Huachuan1120
Without G13091T (ORF1a:A4276S)
EPI_ISL_18544255 Catalunya, Spain

**Comment by Over-There-Is** [comment]
New query: C1758G, T22928G

**Comment by Over-There-Is** [comment]
@FedeGueli the new sequence doesn't have Orf1a:A4276S

**Comment by FedeGueli** [comment]
thx editing the proposal

**Comment by Huachuan1120** [comment]
EPI_ISL_18547134,Sweden+1
This new case has ORF1a:A4276S.
![IMG_6198](https://github.com/sars-cov-2-variants/lineage-proposals/assets/142312996/69628b91-5c1e-4bb0-8aab-011f344c3d23)

**Comment by FedeGueli** [comment]
ping  @corneliusroemer it reached 5.

**Comment by FedeGueli** [comment]
+2 Ireland, Germany

**Comment by FedeGueli** [comment]
14 sequences now 6 countries

**Comment by FedeGueli** [comment]
18 now it seems slow luckily.

**Comment by FedeGueli** [comment]
> 18 now it seems slow luckily.

But it got designated JN.12 just now! via https://github.com/cov-lineages/pango-designation/commit/80a788e11583dde621c8abb4179945c4bbc67820
