### ISSUE TITLE
HN.1 (FL.1.5.1 + S:A67S) with S:H69Y, R403K, K440R + ORF1a:E604A (12 seq, USA,Uk,Denmark Jan 16)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1107]
### **Description**
**Sub-lineage of:** HN.1 (FL.1.5.1.1 = FL.1.5.1 + S:A67S)
**Earliest sequence:** 2023-10-28, USA, Washington
**Most recent sequence:** 2023-11-4, USA, Washington
**Continents circulating:** North America (9)
**Countries circulating:** USA (5)
**Number of Sequences:** 9 (possibly only 6 as three may be duplicates)
**GISAID Nucleotide Query:** A2184C, T16866C
**CovSpectrum Query:** Nextcladepangolineage:FL.1.5.1 & [4-of: A2184C, C2650T, T16866C, C21767T, G22770A, A22881G]
**Substitutions on top of HN.1:**
**Spike:** H69Y, R403K, K440R
**ORF1a:** E604A (NSP2_E424A)
**Nucleotide:** A2184C, C2650T, T16866C, C21767T, G22770A, A22881G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/HN.1_H69Y_R403K_K440R.json?c=gt-nuc_2184&gmax=3184&gmin=1184&label=id:node_3415802 

<img width="1385" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/aa03b149-5292-4f08-ad3c-6a1d5aa8be01">

**Evidence**
Metadata indicate these are from different patients, though it’s possible three are duplicates, meaning there would be only six sequences rather than nine. These were all uploaded within the last two days. 

These are the first Omicron sequences ever to have S:A67S and S:H69Y. There have only been five previous such sequences, all from 2021. Three of those had S:D80G which, like S:V83A, is a move to a residue with a smaller side chain. 

ORF1a:E604A (NSP2_E424A) is an extremely rare mutation. According to CovSpectrum, it has only ever been in 35 sequences, 16 of which were collected between July and August 2023 from nine different XBB* lineages. 
<img width="1291" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9a032cac-1b14-4550-8bda-db7e00b60275">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18528517, EPI_ISL_18528521, EPI_ISL_18528530, EPI_ISL_18533853, EPI_ISL_18533854, EPI_ISL_18533856, EPI_ISL_18533859, EPI_ISL_18533864, EPI_ISL_18533867
</details>

**Comment by FedeGueli** [comment]
10 but it seems it was a cluster. lets check for a couple of week more

**Comment by FedeGueli** [comment]
No new sample came from this. Closing it.

**Comment by FedeGueli** [comment]
2 new samples from Uk and Denmark all of them from December, hence i reopened the issue.

**Comment by FedeGueli** [comment]
it was a cluster
