### ISSUE TITLE
GJ.1.2.6 saltation with ORF1a:A967V, ORF1a:T1168I, ORF1a:A3956S, ORF1b:S1552G, S:K97N, S:F456L and ORF8:A65V (20 seqs, USA, Canada, Netherlands)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1109]
**Defining Mutations:** `GJ.1.2.6` > `C3165T(ORF1a:A967V/nsp3_A149V), C3768T(ORF1a:T1168I/nsp3_T350I), C4777T, G12131T(ORF1a:A3956S/nsp8_A14S), A18121G(ORF1b:S1552G/nsp14_S28G), G21853T(S:K97N), T22928C(S:F456L), C26894T, C28087T(ORF8:A65V)`
**Query:** `C3165T, C4777T, T22928C`
**Earliest seq:** 2023-10-06 (`EPI_ISL_18415781`, Arizona, USA)
**Latest seq:** 2023-11-07 (`EPI_ISL_18522371`, Noord-Brabant, Netherlands)
**Sampled Countries:** USA (7: AZ/2; CO/2; UT/2; NJ), Canada (BC), Netherlands (NB)

<details><summary>Genomes: </summary>

`EPI_ISL_18415781, EPI_ISL_18425012, EPI_ISL_18453124, EPI_ISL_18469939, EPI_ISL_18498259, EPI_ISL_18498265, EPI_ISL_18507763, EPI_ISL_18522371, EPI_ISL_18533131`</details>

**Mutation Profiles:**

List of mutations on nearest phylogenetic branch
```
nuc	unique	C3165T, C4777T, A18121G, G21853T
nuc	homoplasies	C3768T, T22928C, C26894T
ORF1ab	unique	A967V, S5953G
ORF1ab	homoplasies	T1168I
S	unique	K97N
S	homoplasies	F456L
```
List of mutations to root/reference strain
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/103693f7-89d8-4a42-ae9e-379226b7d12b)

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38359_ec36c0.json?label=id%3Anode_4018162
![456L](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8d251d24-6410-4cea-87b1-9f37fadf727d)

**Trivia:**
- The _Lazy_ XBB.2.3* finally got `S:T478R` and `S:F456L`
- The saltation should also contain `G12131T(ORF1a:A3956S/nsp8_A14S)` and `C28087T(ORF8:A65V)` due to potential dropout/low-coverage from `USA/CO-CDPHE-41441538/2023|EPI_ISL_18507763|2023-10-15`

**Comment by FedeGueli** [comment]
My easy bet this comes from Philippines. we will see!

**Comment by FedeGueli** [comment]
Alternative query to exclude spike dropouts : C3165T, C4777T, A18121G ( it gives the same result but please keep it here to double check low quality sequences

**Comment by jasondorjeshort** [comment]
What's with ORF8:A65V?  This lineage has an intact ORF8, but this has evolved convergently also in multiple lineages (FU.2, JD.1.1) after the orf8 stop?  It doesn't look like it's in an overlapping frame with another protein - how is this possible?

**Comment by ryhisner** [comment]
> What's with ORF8:A65V? This lineage has an intact ORF8, but this has evolved convergently also in multiple lineages (FU.2, JD.1.1) after the orf8 stop? It doesn't look like it's in an overlapping frame with another protein - how is this possible?

I think that region of ORF8 is particularly prone to APOBEC-drive C->T mutations, particularly C28087T and C28093T. APOBEC3 disproportionately deaminates cytosines that are unpaired and on prominent stem-loops in the secondary RNA structure. It also occur much more commonly in certain nucleotide contexts. C28087T is unpaired, on a prominent stem-loop, and has a relatively good nucleotide context. I don't think ORF8:A65V or ORF8:S67F are adaptive at all; they're just located in positions in the genome that are prone to C->T mutations. 
<img width="1028" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f537ff48-e1fd-4e8b-9c12-7cd48f9ac2ef">
<img width="1126" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0e4ddcd5-4a4b-47a9-afdd-6756e081e317">

**Comment by FedeGueli** [comment]
+2 US

**Comment by FedeGueli** [comment]
13 now

**Comment by FedeGueli** [comment]
One sample only from December closing it for now.
