### ISSUE TITLE
FL.15.1.1+S:E183D(20 seqs, 3 countries, 7 wth S:K182I)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1111]
FL.15.1.1+C4438T+T9292C+C10186T,G22111T(S:E183D)

XBB has C22109G making S:Q183E, and with G22111T it further mutates to D.

GISAID query: T9292C, G22111T,T28297C
No. of seqs: 18(UK 1 New Zealand 2 Australia 15)
18 on GISAID

First: EPI_ISL_18350451, Australia, 2023-10-1
Latest: EPI_ISL_18536594, Australia, 2023-11-13

GISAID query for S:K182I subbranch: T9292C, A22107T(5 seqs)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice32_genome_427c0_13f0.json?label=id:node_3356149)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9325b36b-c52c-4756-acd2-93bdc4dea5d0)

**Comment by aviczhl2** [comment]
Designated KF.2

**Comment by FedeGueli** [comment]
KF.2 has further expanded its Branch with S:K182I already present in this tree , locally in Australia.
i further suggest designation of it. cc @corneliusroemer 
<img width="1199" alt="Screenshot 2024-01-24 alle 13 23 58" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/384b823f-0c29-4a37-8bbb-191c3c91d7bf">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_355d0_100760.json?label=id:node_3329871
