### ISSUE TITLE
FL.1.5.1 + S:Q52H + S:F157L + S:V701A(r) and 7 orfab mutations + N:A398V (1)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1112]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/67e66411-1934-40e6-a60b-451a885e1668)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_15250_1754b0.json?c=gt-S_52

Seq: 2023-11-02
EPI_ISL_18530510

I don't know the gisaid query.

**Comment by FedeGueli** [comment]
It seems to me a recombinant with EG.5.1.6

**Comment by Over-There-Is** [comment]
![2023-11-25 (4)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/31f880f4-a1e8-471b-a73d-7111481d2f19)
Contamination?
