### ISSUE TITLE
Putative JN.1 + S:R346T with C1762A, C11747T, C20629T (4 seqs, France/Sweden/Australia/Italy)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1118]
There are around 40 JN.1 that have S:R346T, but most of them are poor quality sequences with lots of XBB mixed in.

When filtering out those pretty clear artefacts, we're left with 11-12 BA.2.86 that may actually have 346T. These are shown in the screenshot, where mutations are shown with respect to BA.2.86 parent, that's why there are so few mutation markers:
<img width="2551" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/0adfc26d-8a02-4f76-b719-01be7939b495">

Interestingly, most of the 346T are within JN.1 (9 out of 11), much more concentrated than we'd expect by chance (around 1/4 of total BA.2.86 are JN.1 in GISAID).

Within JN.1, 8 out of 9 are on the JN.1 branch with C1762A (ORF1a:F499L) and C11747T. Again more concentrated than one would expect by chance (around 40% of JN.1 are on that branch).

4 out of those 8 share another mutation that's seen only once elsewhere within JN.1:  C20629T (ORF1b:H2388Y).

Thus, it looks like at least these 4 sequences form a proper monophyletic lineage that could get designated. Though the numbers are still a bit small and there's a contamination issue as evidenced by the 3/4 of BA.2.86 + 346T being likely artefacts:

```
hCoV-19/Australia/NSW-ICPMR-50850/2023|EPI_ISL_18513742|2023-11-04
hCoV-19/Sweden/D-6556154176/2023|EPI_ISL_18538246|2023-11-13
France/GES-IPP26802/2023|EPI_ISL_18540862|2023-11-06
Italy/LOM_Unimi-3855-23/2023|EPI_ISL_18510429|2023-11-06
```

GISAID query: `G22599C,C20629T,C11747T,C1762A`

It's also possible that the 8 sequences are a single event - better wait for sequence numbers to double before making a decision. Due to the way the other 4 are scattered around, they look like independent events for now, though.

On Usher, things are a bit messy:
<img width="2129" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/9469c8c1-8818-451c-b521-a91900af2ffd">
<img width="2157" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/ecfea52f-3a59-4add-9db6-7cda8c47be0c">

Here's how Nextclade arranges things with just the 346T sequences on the JN.1 branch:

<img width="2095" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/fa892083-2008-471f-aa4f-34064a781c52">

**Comment by FedeGueli** [comment]
I think this is the same of #1089 !

there i found also these other 3 Jn.1 with S:R346T : (copy&past from there):
1
G10540T, C22088T 1 seq from Belgium with S:176F

2
C21952T,G22599C,C11747T,C1762A 1 seq from France

3
this one without a specific query
![Schermata 2023-11-25 alle 16 47 25](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/46b55cbf-4708-4f5a-bcd2-40d07448a26f)

all the trees from :https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_13bf8_214840.json?c=userOrOld&label=id:node_4467536

If you have time would you like to change this in a 346T tracker fro BA.2.86??
