### ISSUE TITLE
BA.2.86.1 + C364T （ 26 seqs -11 country ） 

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1119]
I accidentally discovered it and proposed it because there are sequence related to China and it seems to be a popular branch in Hong Kong, which has also been exported to Singapore.As is well known, the evolutionary branches of BA.2.86 are very diverse and complex, and in the context of incomplete global sequencing, there must still be regions in a low prevalence state. I am proposing it now to prevent a large number of related regions from uploading this branch. However, we cannot guarantee that there will be new C364T branches in the future, as we are  concerned about the uncertainty surrounding the Covid-19 pandemic in China.

GISAID query:`C364T` correct query: C364T, A7842, C8293T, G8393A,-G11727A (edited on Jan 21 by mod)
[USHER TREE ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d096_423ae0.json?f_userOrOld=uploaded%20sample&label=id:node_5475107)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/de919e79-f266-4e6b-9bcf-072d6981c5e7)

SEQS: EPI_ISL_18366378, EPI_ISL_18473622, EPI_ISL_18495093,EPI_ISL_18536107

EPI_ISL_18495093：Local cases in Shanghai, China, with another ORF1a: Y2171F
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/33504340-b7cd-4606-b79b-3eb2519d5519)
EPI_ISL_18473622：Imported cases from Hong Kong, China，but it also have C22993T.
EPI_ISL_18366378 : from Hong Kong,China

Addendum: We still hold a skeptical attitude towards this branch, as it exists but has not grown in a wide range of lineages such as BA. 2.10.1/BA. 2.12.1/BA. 5.1. *.

If there are no new sequences of C364T branch within a month, I  will close this issue.THX.
```[tasklist]
### Tasks
- [ ] #1119
```

**Comment by Memorablea** [comment]
No new additions, temporarily closed

**Comment by Memorablea** [comment]
Denmark +2

**Comment by FedeGueli** [comment]
added a credible query : C364T, A7842, C8293T, G8393A. now this is 21

**Comment by FedeGueli** [comment]
C364T, A7842, C8293T, G8393A,-G11727A to exclude some JN.1 that have acquired the same nuc mutation

**Comment by Memorablea** [comment]
thanks

**Comment by Memorablea** [comment]
24now

**Comment by FedeGueli** [comment]
26 , it is also circualting recently in Japan . lets see if it gains some mutations there.

**Comment by FedeGueli** [comment]
closing this for now
