### ISSUE TITLE
 GJ.1 sublineage with ORF1b:V1110I, C1549T, and C7819G first detected in South Korea (124 seqs as of 2023-06-12; China, USA, Canada, Singapore, Australia, South Korea, Japan, UK, Switzerland, New Zealand, Finland, Hong Kong, Italy, Philippines)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#112]
EDITED: This is a sublineage of  GJ.1
and it is the sibling lineage of #109 

There may be a XBB.2.3.3 sublineage with ORF1a:I4205V (NSP9:I65V, A12878G), ORF1b:V1110I (NSP13:V187I, G16795A), ORF8:E106Q (G28209C), C1549T, C7819G first detected in South Korea and detected in at least 7 different countries.

As of 2023-05-29, Cov-Spectrum reports 51 good-quality (57 total) XBB.2.3.3+ORF1a:4205V+ORF1b:1110I+ORF8:106Q+1549T+7819G sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.2.3.3+%26+ORF1a%3AI4205V+%26+ORF1b%3AV1110I+%26+ORF8%3AE106Q+%26+C1549T+%26+C7819G&nextcladeQcOverallScoreTo=29&

As of 2023-05-29 there is insufficient data to determine good growth advantage relative to XBB.2.3.3 at this time.

As of 2023-05-29, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 2 3 3+ORF1a_4205V+ORF1b_1110I+ORF8_106Q+1549T+7819G](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/629ee2ed-924a-4e64-a38a-5766fd9f9c63)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/05/subtreeAuspice1_genome_CoV-Spectrum_XBB.2.3.3%2BORF1a_4205V%2BORF1b_1110I%2BORF8_106Q%2B1549T%2B7819G.json?c=gt-ORF1ab_5511&label=id%3Anode_6996120

GISAID query: A12878G, G16795A, G28209C, C1549T, C7819G

First GenBank sequence: South Korea 2023-04-13

Most Recent GenBank sequence: Fujian, China and Virginia, USA 2023-05-14

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support_XBB.2.3.3+ORF1a_4205V+ORF1b_1110I+ORF8_106Q+1549T_7819G.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/11593575/Support_XBB.2.3.3%2BORF1a_4205V%2BORF1b_1110I%2BORF8_106Q%2B1549T_7819G.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl_XBB.2.3.3+ORF1a_4205V_ORF1b_1110I+ORF8_106Q+1549T+7819G.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/11593573/gisaid-epi-isl_XBB.2.3.3%2BORF1a_4205V_ORF1b_1110I%2BORF8_106Q%2B1549T%2B7819G.txt).

**Comment by FedeGueli** [comment]
Welcome here Andrew, the parental sublineage has been already transferred to pango designation page (issue # 2005) and @aviczhl had proposed the other brach in #109   i consequently edited bith titles but very good to track them both in this repo.

**Comment by alurqu** [comment]
The parent lineage with ORF8:E106Q and ORF1a:I4205V has now been designated GJ.1.

**Comment by alurqu** [comment]
This sublineage has also now been detected in Europe (Switzerland and the UK).

**Comment by Fearuncle** [comment]
100 seq.

**Comment by FedeGueli** [comment]
124 as today please propose it @alurqu

**Comment by Fearuncle** [comment]
147

**Comment by FedeGueli** [comment]
@alurqu please open an issue on the main page

**Comment by FedeGueli** [comment]
Designated GJ.1.2
