### ISSUE TITLE
FL.1.5.2 (KC.1) with 356T, A83T, T572I (Canada-ON,Florida 29 seqs)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1123]
Interesting triple spike substitution. Only Ontario, so will need to wait for sequences from other countries but FL.1.5.2 has been performing better and better over time. No relevant S substitutions yet until this one popped up:

<img width="2072" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/1de28d52-9245-4f3c-a9c0-ff4b6e5c197f">

Potential GISAID query: `A7444G, G11115T, G21809A`

**Comment by FedeGueli** [comment]
great catch Cornelius, i was monitoring too FL.1.5.2 being likely the ,ost fit not flip not ba.2.86 spike thx for spotting!

**Comment by FedeGueli** [comment]
15 now all Ontario.

**Comment by FedeGueli** [comment]
22 seqs now all Ontario

**Comment by FedeGueli** [comment]
24 now.

**Comment by FedeGueli** [comment]
26 mainly Ontario

**Comment by FedeGueli** [comment]
27 now, with 2 sampoles from January.

**Comment by FedeGueli** [comment]
i think this should be designated 4/29 samples from January @corneliusroemer 
New tree:
<img width="1166" alt="Screenshot 2024-01-29 alle 20 04 01" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c5b51280-5c65-47e2-81de-4d47d0fc6313">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_57dd3_7f4eb0.json?label=id:node_3408190

**Comment by FedeGueli** [comment]
it was a cluster closing it now thx for the good spot.
