### ISSUE TITLE
XBB.1.16.6 with S:Q613H and ORF3a:F79L (52 seqs, mainly in UK, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1125]
**Defining Mutations:** `XBB.1.16.6` > `C8947T` > `A10861G` > `T18648C` > `G23401T(S:Q613H), T25627C(ORF3a:F79L)`
**Query:** `C8947T, T18648C, G23401T`
**Earliest seq:** 2023-08-08 (`EPI_ISL_18146728`, England, UK)
**Latest seq:** 2023-11-16 (`EPI_ISL_18553019`, Scotland, UK)
**Sampled Countries:** UK (29: SC/24; EN/4; WS), Canada (8: BC/6; NB; ON), France (3), USA (3: NY), Slovenia (2), Belgium (1), Croatia (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18146728, EPI_ISL_18248484, EPI_ISL_18273964, EPI_ISL_18362808, EPI_ISL_18379675, EPI_ISL_18379683, EPI_ISL_18396684, EPI_ISL_18402766, EPI_ISL_18407504, EPI_ISL_18420309, EPI_ISL_18429192, EPI_ISL_18431050, EPI_ISL_18431057, EPI_ISL_18431060, EPI_ISL_18431107, EPI_ISL_18447394, EPI_ISL_18452524, EPI_ISL_18452676, EPI_ISL_18492434, EPI_ISL_18493471, EPI_ISL_18494010, EPI_ISL_18505118, EPI_ISL_18514628, EPI_ISL_18548304, EPI_ISL_18552879-18552880, EPI_ISL_18552883-18552884, EPI_ISL_18552886, EPI_ISL_18552901, EPI_ISL_18552905, EPI_ISL_18552909, EPI_ISL_18552911, EPI_ISL_18552913, EPI_ISL_18552915, EPI_ISL_18552919, EPI_ISL_18552931, EPI_ISL_18552933, EPI_ISL_18552943-18552944, EPI_ISL_18552947-18552948, EPI_ISL_18552967, EPI_ISL_18552976-18552977, EPI_ISL_18553006, EPI_ISL_18553019`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6dc8_7003a0.json?f_userOrOld=uploaded%20sample&label=id:node_3290676
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8eb1a014-e8f0-42b6-bf14-6fcc43bf1766)

**Comment by FedeGueli** [comment]
Thx for spotting 613 that is quite good with 478R. Still no chance for this one. https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=C8947T%2CT18648C%2CG23401T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
one sample only from December closing it for now
