### ISSUE TITLE
GK.1.8 (XBB.1.5.70.1.8) saltation branch with S:K187I, S:A222P and ORF3a:R134H (25 seqs in 7 countries, including one further saltation branch with ORF1a:L3829F)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1127]
Defining mutations:
GK.1.8>C6401T (ORF1a: P2046S)>T20733C, A22122T (S:K187I), G22226C (S:A222P), G25793A (ORF3a:R134H)
GISAID query: T20733C, A22122T, G22226C
Earliest seq: 2023-09-19 (Brazil- EPI_ISL_18453868)
Most recent seq: 2023-11-17 (DE, US- EPI_ISL_18556136)
Countries detected: US (4), Canada (2), Brazil (2), UK (1), Sweden (1)

Usher Tree:
![联想截图_20231129203137](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/0843e64e-e0d1-4e23-8cfc-ac7880c042fb)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34dd0_729ad0.json
Notice that the 6 latest seqs are from one further saltation branch with ORF1a:G603D, ORF1a:A2033T and ORF1a:L3829F. ORF1a:L3829F (C11750T) is popular in XBB.1.16* lineages.

Genomes:
EPI_ISL_18357604, EPI_ISL_18436987, EPI_ISL_18437405, EPI_ISL_18453868, EPI_ISL_18456330, EPI_ISL_18497358, EPI_ISL_18498584, EPI_ISL_18498591, EPI_ISL_18522586, EPI_ISL_18556136

**Comment by HynnSpylor** [comment]
2 more seqs in Brazil

**Comment by HynnSpylor** [comment]
25 seqs now and it emerges in some other South American countries (Columbia, Paraguay)

**Comment by aviczhl2** [comment]
Designated GK.1.8.1
