### ISSUE TITLE
HV.1+Orf1a:W630C,A2375V,T4083M, Orf3a: L140F, S:452Q( 26 seqs, 9 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1129]
HV.1+C12513T(Orf1a:T4083M)+C7389T(Orf1a:A2375V)+C27920T+ G2155T, C25810T, G22917A(Orf1a:W630C, Orf3a:L140F, S:R452Q)

GISAID query: G2155T, C25810T, C29625T
No. of seqs: 16( UK 11 Germany 2 Belgium1 Ireland 1 Switzerland 1)

First: EPI_ISL_18420156, UK, 2023-10-8
Latest: EPI_ISL_18552871, UK, 2023-11-14

Usher places it on an HV.1.2 flip-flop reversion branch, however no seq on this branch actually has the HV.1.2 defining S:L514F.  
Shall be sub-branch of HV.1+Orf1a:T4083M branch. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_c782_7d7240.json?label=id:node_3480400)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/4d16e8e7-a5dc-470f-8993-45e0f0a10243)

**Comment by aviczhl2** [comment]
19, Sweden

**Comment by aviczhl2** [comment]
22, USA

**Comment by FedeGueli** [comment]
5/24 from december

**Comment by FedeGueli** [comment]
No new sample coming for this liley dying off.

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by aviczhl2** [comment]
+1 China

**Comment by FedeGueli** [comment]
closing this it seems dead
