### ISSUE TITLE
FE.1.1/GY.1 recombinant (7 seqs)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1130]
Breakpoint around 8200-10400, first FE.1.1 then GY.1, recombination saves 4 mutations: the reversion, and A3662G, T4579A, A8001G

GISAID query: `C25782T,A2437G, A3662G`

<img width="2143" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/71569968-d0e1-4e36-8a7f-4e864e5339e5">

<img width="1464" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/b2f2988d-bf2c-404c-a986-90c1355c2a00">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21c4e_85f210.json?branchLabel=Spike%20mutations

**Comment by FedeGueli** [comment]
+1 Lux (collected in early november so i m closing this one)
