### ISSUE TITLE
GY.1 / XBB.1.9.1 (probably FL.2) recombinant [8-11 seqs]

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1131]
Breakpoint around 22000-24000

GISAID query: `C17550T, C29353T,C21812A`

<img width="2137" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/28d2f48d-45bc-4d81-a616-9cd6e6767a93">

Given presence of the two donors in China, quite likely emerged in China

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21c4e_85f210.json?branchLabel=Spike%20mutations

**Comment by FedeGueli** [comment]
Most recent smaple is before October closing it now
