### ISSUE TITLE
EG.5/EG.10.1.1 recombinant (Lithuania, 32 seqs)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1132]
EG.5/EG.10.1 with breakpoint between 11313 and 12000

<img width="2167" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/42fad69f-5352-4785-b603-04e3f99f258a">

It's from the bigger EG.10.1 branch with G11312A, G8372T, C18175T

Recombination explains 3 reversions T335C, T8372G, A11312G and 2 mutations C2334T, C9693T

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ace6_8a8350.json?branchLabel=Spike%20mutations&label=id:node_3603660&showBranchLabels=all

Query : C2334T, C9693T,A26451T (edited)

**Comment by FedeGueli** [comment]
32 now no one recent prevalence in Lithuania in the 0, range closing it for now.
