### ISSUE TITLE
EG.5.1.1/XBB.2.3  recombinant island

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1136]
I don't have the time right now for a deep dive but here are a few interesting recombinants, at least the South Korea quintet and the US doublet:
<img width="2145" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/8abb851a-7cce-4a9b-9966-ced05942cd88">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_392a3_9b7410.json

They all have EG.5.1.1 up to mid-RBD, and XBB.2.3 downstream, with 521S and ORF8 restored

e.g. `SouthKorea/KDCA273047/2023|EPI_ISL_18539618|2023-10-23`

Too small to designate but worth monitoring

**Comment by Over-There-Is** [comment]
England/CLIMB-CM7YMQ9J/2023|EPI_ISL_18521456|2023-11-02
GE.1.5/EG.5.1.1/GE.1.5

**Comment by Over-There-Is** [comment]
New_Zealand/ZA4831/2023|EPI_ISL_18347542|2023-09-23
EG.5.1.1/GE.1
EG.5.1.1> C11779T> C15720T> C13665T (183 seq)
GE.1> T10792C> T6691A, C20594T> C2306T> C1302T, C2523T, C17550T(2 seq)
brpt: 16342\~16878
C4633T

**Comment by Over-There-Is** [comment]
South Korean Cluster
HK.3/XBB.2.3.8
HK.3+C2675T or C10834T (More likely HK.3> C10834T> T28672A)
XBB.2.3.8> T23797C> G19563A, T22579C> A29534T(Most with further > C5986T> A15005C)
Brpt: 22930\~22995

**Comment by Over-There-Is** [comment]
American Cluster(3 seq, 1 not shown on tree)
EG.5.1.1*/GJ.1.2/EG.5.1.1*
EG.5.1.1*+C218T (Most likely EG.5.1.1> C18508T> C218T, G22801T)
GJ.1.2> T16456C> A6229G> C7749T, G22365C> C29509G> A21137G, T27582C
Brpt 1: 13627\~16342
Brpt 2: 25572\~27507

**Comment by Over-There-Is** [comment]
USA/CA-HLX-STM-GNHQMDVDZ/2023
EG.5.1.1/GJ.1.2
EG.5.1.1> A21603G> C13517T> A4758C, G25767T (21 seq)
GJ.1.2> G25907T> C3177T> C22591T> G2539A> T24995C, C25614T (2 seq)
Brpt: 16342\~16878
C25613T, T26436C are private

**Comment by FedeGueli** [comment]
> South Korean Cluster 9 seq HK.3/XBB.2.3.8 HK.3+C2675T or C10834T (More likely HK.3> C10834T> T28672A) XBB.2.3.8> T23797C> G19563A, T22579C> A29534T(Most with further > C5986T> A15005C) Brpt: 22930~22995 Query: C2675T, C10834T, T23797C
One more from Singapore: 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5f5fd_174490.json?c=userOrOld&label=id:node_3465681
![Schermata 2023-12-19 alle 11 49 41](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f7fdaf49-51a6-4352-af60-027fa6644673)

**Comment by aviczhl2** [comment]
There is a new JD.1.1/Main page #2436 recombinant on this island. #1257

**Comment by Over-There-Is** [comment]
> C2334T, G22365C

the latest sequence collected on 10-31, but it has spread to Greeece.

**Comment by FedeGueli** [comment]
Closing this one almost everything is dead
