### ISSUE TITLE
EG.5.1 / XBB.1.16 / EG.5.1 recombinant island

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1137]
Found another recombinant island in Usher that's worth characterising, there's an interesting Polish cluster, and a Canada one

<img width="2143" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/4b2f8f50-7821-4814-abd2-42d261401c8b">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4cec2_9b8d50.json?label=id:node_3344023

```
Canada/SK-RRPL-664180/2023|EPI_ISL_18501595|2023-10-18
Poland/Kce-1065/2023|EPI_ISL_18508658|2023-11-10


Query for Polish cluster: C1645T, G3153A, G6759T (edited)
```

**Comment by FedeGueli** [comment]
Polish cluster is one to watch query added : C1645T, G3153A, G6759T

**Comment by Over-There-Is** [comment]
Canadian cluster 5 seq
XBB.1.16.6+A10861G(The branch with JF.1/2) / HV.1.2+C18508T(75 seq)
brpt1: 12789\~14856
brpt2: 23103\~27507
2 Saskatchewan sequences have A1065G potentially
Query: A10861G, C18508T, C23103T

**Comment by Over-There-Is** [comment]
France/OCC-HCL723001449501/2023|EPI_ISL_18545048|2023-10-23 Singlet
XBB.1.16.7/HK.3.4 17154\~18492
Private mut: C11668T

**Comment by Over-There-Is** [comment]
Japan/PG-571694/2023|EPI_ISL_18390728|2023-09-08 Singlet
XBB.1.16.7+C10189T,T12022C,T17328C,C22858T (4 seq) /EG.5.1*+(C22388T or T26972C)
more likely EG.5.1+T26972C, C28909T
brpt 1: 17328\~18492
brpt 2: 28447\~29386(28909?)

**Comment by Over-There-Is** [comment]
Polish cluster
XBB.1.16.21+C1645T,G3153A,A18675G,C19017T,T29581C,T29834C /EG.5.1*
brpt1: 14856\~16878
brpt2: 22995\~27507
G6759T, C29774T are private

**Comment by Over-There-Is** [comment]
USA/OR-OSPHL08907/2023|EPI_ISL_18256619|2023-09-04 XBB.1.16/HK.28

**Comment by Over-There-Is** [comment]
most are XBB.1.16/EG.5.1/XBB.1.16, some are XBB.1.16/EG.5.1

**Comment by Over-There-Is** [comment]
USA/TX-HMH-134279/2023|EPI_ISL_18424034|2023-09-20 Low Quality XBB.1.16*/HV.1/XBB.1.16*
USA/TX-HMH-M-131990/2023|EPI_ISL_18163947|2023-08-18 Potential Contamination

**Comment by Over-There-Is** [comment]
Singapore/R62MR29/2023|EPI_ISL_18233254|2023-08-28
XBB.1.16/EG.5.1*/XBB.1.16
XBB.1.16> T18447C> A29368G> G947A, C11345T, C24334T(1 seq)
brpt 1: 14856\~16878(16457?)
brpt 2: 22995\~27507
C12885T is private,  C16457T could be private or inherited from EG.5.1*

**Comment by FedeGueli** [comment]
@Over-There-Is please propose the ones reaching  more than 10 seqs , please crediting Cornelius.

**Comment by Over-There-Is** [comment]
> A10861G, C18508T, C23103T

9 now, Alberta, Saskatchewan, BC, Texas

**Comment by FedeGueli** [comment]
> Canadian cluster 5 seq XBB.1.16.6/HV.1.2/XBB.1.16.6 XBB.1.16.6+A10861G(The branch with JF.1/2) HV.1.2+C18508T(75 seq) brpt1: 12789~14856 brpt2: 23103~27507 2 Saskatchewan sequences have A1065G potentially Query: A10861G, C18508T, C23103T

now 24 please propose it.

**Comment by FedeGueli** [comment]
> Polish cluster is one to watch query added : C1645T, G3153A, G6759T

15 seqs likely dead
