### ISSUE TITLE
JU.1 (XBB.2.3.12.1) +S:F456L via T22930G(31 seqs, 5 countries, 0.7% Russia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1138]
JU.1+T22930G,C23707T(S:F456L)

Previously we usually see S:456L with T22930A or T22928C though. This one has T22930G.

GISAID query: T22930G,C23707T
No. of seqs: 8 (Russia 6 Crimea 1 South Korea 1)

First: EPI_ISL_18417396, Russia-Moscow, 2023-9-18
Latest: EPI_ISL_18561310, Crimea, 2023-11-1

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice17_genome_1d3b1_aabe40.json?c=gt-S_456&label=id:node_4048154)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/10f397ec-35d8-410f-97d6-b34a61fb938b)

**Comment by aviczhl2** [comment]
> Spike here is very different from circulating ones.

Yeah. If BA.2.86 infection doesn't provide enough cross-immunity maybe XBB.2.3-Flip will make an XBB come back.

**Comment by aviczhl2** [comment]
+1 China from Russia

**Comment by aviczhl2** [comment]
11/1534 in Russian and Crimea 2023.11 seqs, growing in everywhere in Russia.

**Comment by FedeGueli** [comment]
2/10 in Crimea after nov 1

**Comment by FedeGueli** [comment]
Please propose it once it gets 40 seqs

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
+1 Greece

**Comment by aviczhl2** [comment]
1/2 in 2024-1-31 Crimea batch.

**Comment by FedeGueli** [comment]
Likely it is dead closing for now, oplease reopen if it will be present in the next Crimean or Greek batches
