### ISSUE TITLE
From Malaysia/Indonesia  S:N481Y on XBB.1.31 backbone 3seqs

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#114]
This will be nothing but better to track it.

Its composite fitness score is still high:
![Schermata 2023-05-30 alle 00 27 43](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f44e3a45-ed5b-495d-88ad-96a256cf6266)

![Schermata 2023-05-30 alle 00 27 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/94321b90-3289-4870-a57c-14eba30e67ea)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e095_526910.json?label=id:node_6983430
 
XBB.1.31>> Orf1a:A1049V (C3411T) > C313T , A12103G, S:N481Y (A23003T), C27923T

Gisaid query :  A12103G, A23003T,C313T, C27923T 

Samples: 3
EPI_ISL_17681274, EPI_ISL_17696804, EPI_ISL_17719515,

**Comment by Over-There-Is** [comment]
/organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230508-604/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 33; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-05-05"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Malaysia"

**Comment by FedeGueli** [comment]
- [ ]
