### ISSUE TITLE
GW.5.3.1/FY.5.1.1 recombinant [8 seqs, Sweden/England]

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1140]
Breakpoint probably around 7k or so, would be great if someone could take a closer look.

<img width="2240" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/553f60d1-e517-4125-80bc-3ce729936632">

```
hCoV-19/England/CLIMB-CM7YRE5E/2023|EPI_ISL_18497419|2023-11-02
hCoV-19/England/CLIMB-CM7YE5ID/2023|EPI_ISL_18521509|2023-11-07
hCoV-19/Sweden/D-6381377976/2023|EPI_ISL_18538194|2023-11-08
hCoV-19/Sweden/D-6534726776/2023|EPI_ISL_18538193|2023-11-08
hCoV-19/Sweden/AB-01_SE100_23CS502989/2023|EPI_ISL_18507429|2023-11-04
```

EDITED:

Query:  A2345G, C6501A,G13313A
Samples: EPI_ISL_18497419, EPI_ISL_18507429, EPI_ISL_18521509,
EPI_ISL_18538193-18538194
Countries: Sweden , Uk

Breakpoints
5'-10041 GW.5.3.1
10042-3' FY.5.1
see : [covspectrum](https://cov-spectrum.org/explore/World/AllSamples/Past1M/variants?nucMutations=A2345G%2CC6501A%2CG13313A&nextcladePangoLineage1=GW.5.3.1*&nextcladePangoLineage2=FY.5.1*&analysisMode=CompareEquals&)
![Schermata 2023-12-03 alle 09 47 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a8ba7ee0-e48f-4af1-ada8-efd4070a06d9)

Spike from FY.5.1

**Comment by corneliusroemer** [comment]
<img width="1979" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/498efbe6-fdca-46b8-bd6f-66edc32004b2">

<img width="2147" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/b8d2a535-f7f4-42cf-9940-dbf7eba8e4a3">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16f54_b28790.json?branchLabel=Spike%20mutations&c=gt-nuc_6019,23277&gmax=24277&gmin=5019

**Comment by FedeGueli** [comment]
@corneliusroemer analysis done in the main proposal.

**Comment by FedeGueli** [comment]
8 now last two sequences from Upsala and Stockholm

**Comment by FedeGueli** [comment]
still 8 liley it is slow or dying off.

**Comment by FedeGueli** [comment]
Likely dead closing it now
