### ISSUE TITLE
EG.5.1 with ORF1a:G3278S (nsp5_G15S) and S:F490P (F>S>P) on a ORF6:D61I (D>L>I) flip-flop branch (121 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1142]
**Defining Mutations:** `EG.5.1` > _`G27382A(ORF6:D61I)`_ > `G10097A(ORF1a:G3278S)` > `T23030C(S:F490P)`
**Query:** `G10097A, A18492G, T23030C`
**Earliest seq:** 2023-06-03 (`EPI_ISL_17990815`, New Jersey, USA)
**Latest seq:** 2023-11-16 (`EPI_ISL_18555205`, Utah, USA)
**Sampled Countries:** Canada (47: ON), USA (45: NY/16; CA/6; MA/4; UT/3; CT/2; FL/2; NJ/2; NM/2; VA/2; AZ; CO; IN; OH; RI; WA), Croatia (1), Japan (1), UK (1: EN)

<details><summary>Genomes: </summary>

`EPI_ISL_17990815, EPI_ISL_18121347, EPI_ISL_18121648, EPI_ISL_18131573, EPI_ISL_18145729, EPI_ISL_18247639, EPI_ISL_18266057, EPI_ISL_18266716, EPI_ISL_18266751, EPI_ISL_18267490, EPI_ISL_18276024, EPI_ISL_18276039, EPI_ISL_18276231, EPI_ISL_18276429, EPI_ISL_18303804, EPI_ISL_18307773, EPI_ISL_18310017, EPI_ISL_18310182, EPI_ISL_18317233, EPI_ISL_18333194, EPI_ISL_18333353, EPI_ISL_18333656, EPI_ISL_18333658, EPI_ISL_18333665, EPI_ISL_18333707, EPI_ISL_18333770, EPI_ISL_18334811, EPI_ISL_18341581, EPI_ISL_18350602, EPI_ISL_18351609, EPI_ISL_18358669, EPI_ISL_18375248, EPI_ISL_18375641, EPI_ISL_18398417, EPI_ISL_18399241, EPI_ISL_18407410, EPI_ISL_18409941, EPI_ISL_18425013, EPI_ISL_18426555, EPI_ISL_18426570, EPI_ISL_18426588, EPI_ISL_18426604, EPI_ISL_18427080, EPI_ISL_18427626-18427627, EPI_ISL_18448264, EPI_ISL_18448370, EPI_ISL_18448716, EPI_ISL_18448726, EPI_ISL_18451438-18451439, EPI_ISL_18451482, EPI_ISL_18451525, EPI_ISL_18451549, EPI_ISL_18451565, EPI_ISL_18466315, EPI_ISL_18471469, EPI_ISL_18471473, EPI_ISL_18471476, EPI_ISL_18471569, EPI_ISL_18471675, EPI_ISL_18471682, EPI_ISL_18471975, EPI_ISL_18472030, EPI_ISL_18496016, EPI_ISL_18502179, EPI_ISL_18502247, EPI_ISL_18504932, EPI_ISL_18505121, EPI_ISL_18505140, EPI_ISL_18505324, EPI_ISL_18507265, EPI_ISL_18523765-18523768, EPI_ISL_18524025, EPI_ISL_18524069, EPI_ISL_18524155-18524156, EPI_ISL_18533063, EPI_ISL_18533754, EPI_ISL_18547875, EPI_ISL_18548676-18548678, EPI_ISL_18548759, EPI_ISL_18548812, EPI_ISL_18548814, EPI_ISL_18548902-18548903, EPI_ISL_18548983, EPI_ISL_18550311, EPI_ISL_18550925, EPI_ISL_18555205`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1033c_c96580.json?label=id:node_3463849
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/edbd42d8-153b-4b97-ad09-e5b4bf63e48b)

**Trivia:**
- The flip-flop ORF6:D61I/L may be artifact, but if it is real it would have 2 modified mutations, along with `S:F490P(T23030C, T23031C)`
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/9870fdd9-c8f2-4e79-85b3-20eca2d539db)

- A weird lineage that last for long enough (from June to November)

**Comment by FedeGueli** [comment]
118 now

**Comment by FedeGueli** [comment]
121 no one recent closing it
