### ISSUE TITLE
JN.1 + 2-nuc ORF1b:V1271T (358 seq, 4 continents; Dec 19)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1143]
**Description**
**Sub-lineage of:** JN.1
**Earliest sequence:** 2023-10-30, France – EPI_ISL_18510103
**Most recent sequence:** 2023-11-22, Israel – EPI_ISL_18572353
**Continents circulating:** Asia (38), Europe (5), Oceania (1), North America (1)
**Countries circulating:** Singapore (36), France (3), Israel (2), Switzerland (2), Australia (1), Canada (1)
**Number of Sequences:** 45
**GISAID Nucleotide Query:** C897A, G17278A, T17279C
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & G17278A & T17279C
**Substitutions on top of JN.1:**
**ORF1b:** V1271T (NSP13_V348T)
**Nucleotide:** G17278A, T17279C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_G17278A_T17279C.json?c=gt-ORF1ab_5672&gmax=21555&gmin=266&label=id:node_4491220

<img width="1490" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f0a6fe52-f89f-4e66-a02b-df5a58fff02a">

**Evidence**
Two-nuc mutations are rare, but this one has emerged several times independently—most recent in FL.16.3, XBB.1.16, and JG.3—which might indicate strong selection pressure. Or perhaps it’s just some unusual replication error that randomly occurs now and then. 

<img width="1390" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d49d6a90-37e0-4f4d-bd7a-879e19d91fe9">

It’s possible this is actually two separate lineages. Five of the sequences have ORF7a:T28I, also found on another branch of JN.1. Usher joins these two together and give about 40 of the 45 sequences in this lineage an ORF7a:I28T reversion. Most likely ORF7a:T28I was acquired separately by the other branch and the five sequences in this branch. The other possibility is that the 2-nuc ORF1b:A1271T was acquired twice independently. 

Curiously, two sequences on this branch have S:R683Q and one has S:P681S, both of which would abolish the FCS. Two others, from France, allegedly have S:R681P. Hard to take reversions like that seriously until you see it from multiple different labs, however. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18510103, EPI_ISL_18524417, EPI_ISL_18541866,
EPI_ISL_18541869, EPI_ISL_18544451, EPI_ISL_18544456,
EPI_ISL_18544544, EPI_ISL_18544568, EPI_ISL_18544576,
EPI_ISL_18544579, EPI_ISL_18544588, EPI_ISL_18544592,
EPI_ISL_18544610, EPI_ISL_18544689, EPI_ISL_18544691,
EPI_ISL_18544700-18544701, EPI_ISL_18544719, EPI_ISL_18544726-18544727,
EPI_ISL_18544735, EPI_ISL_18544754, EPI_ISL_18544763,
EPI_ISL_18544773, EPI_ISL_18544776, EPI_ISL_18544781,
EPI_ISL_18544783, EPI_ISL_18544794, EPI_ISL_18544804-18544805,
EPI_ISL_18544812, EPI_ISL_18544819-18544820, EPI_ISL_18544836,
EPI_ISL_18544842, EPI_ISL_18544857, EPI_ISL_18544872,
EPI_ISL_18544880-18544881, EPI_ISL_18544884, EPI_ISL_18551379,
EPI_ISL_18553476, EPI_ISL_18569059, EPI_ISL_18572344,
EPI_ISL_18572353 </details>

**Comment by FedeGueli** [comment]
54 batch uploaded from Singapore.

**Comment by FedeGueli** [comment]
193 sequences now 20% of smaples collected in December in Singapore. please propose it. cc @corneliusroemer

**Comment by FedeGueli** [comment]
270 now. (252 from Singapore)

**Comment by FedeGueli** [comment]
280 but these last 10 sequences are super interesting five  of them are caught in travellers 2 from Qatar , 1 from Japan, 1 from Australia 1 from Singapore
So  it seems expanding quickly outside Singapore.
It has been sampled also  in Scotland and NY in December

cc @corneliusroemer i pudentially suggest to designate this one,  could it be a new Orf1b:1050N?

**Comment by FedeGueli** [comment]
big upload from Singapore and Malaysia where this lineage represents 25% of sequences

**Comment by FedeGueli** [comment]
Thank you Ryan.

**Comment by FedeGueli** [comment]
@corneliusroemer this seems to have an advantage it is spreading well further . It would be interesting if as Orf1b:T1050N arose from Indonesia (likely) another beneficial NSP13 mutation would have arisen from the same area.
