### ISSUE TITLE
JN.1.1 plus S:K147N emerged in France   (59 seqs,  as of Apr 17)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1149]
I just noticed , but it was detected first by @ryhisner  a sublineage of JN.1.1 with S:K147N.
S:K147 mutated to E was defining of BA.2.75 while mutated to N appeared successfully recently  in XBB.1.16.15 , before was in BA.2.3.20/CM.8.1.1 sublineage FV.1 and earlier in BA.5's  BF.11.2, DN.1 and DJ.1.1.1.

Defining mutations:
JN.1.1 > C11747T > C9142T > S:K147N (A22003T)

Query:  A22003T,T3565C

Samples : 3
EPI_ISL_18462116, EPI_ISL_18553645, EPI_ISL_18577315,

Usher shows 4 with another from Sweden with a suspicious reversion at 11747:
![Schermata 2023-12-04 alle 19 33 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a26a485b-211e-41e2-ba45-fee3f7da7dab)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1bc8b_e14900.json?c=gt-nuc_11747&gmax=23003&gmin=2565&label=id:node_4493626

**Comment by thiolist** [comment]
The K147N mutation removes a target site for trypsin-like proteases such as HAT (Human Airway Trypsin-like protease). These proteases cleave proteins at lysine sites (K) or arginine sites (R), for almost all sequences, provided that the protease has access to the site.

If the K147 site is accessible to the protease, then the spike protein could normally be cleaved in the mucus lining the human airway (where HAT resides), affecting its shape and therefore antibody activity. In other tissues (such as muscle, where vaccines are commonly injected) it wouldn't be cleaved, therefore the "spike protein" from vaccines has a built-in difference from the natural spike protein delivered by inhalation.

The SARS-CoV-1 spike protein has been identified as a target of HAT. Presumably this also applies to SARS-CoV-2. Good review articles are available at:
https://pubmed.ncbi.nlm.nih.gov/21994442/
https://pubmed.ncbi.nlm.nih.gov/28235951/

**Comment by FedeGueli** [comment]
THX!

**Comment by FedeGueli** [comment]
+1 FR

**Comment by HynnSpylor** [comment]
One more in IL, US (the first one outside France)

**Comment by FedeGueli** [comment]
+2 Sweden

**Comment by aviczhl2** [comment]
This seems interesting. JN.1 gets Orf8:68* itself to cut down its Orf8.

**Comment by FedeGueli** [comment]
> This seems interesting. JN.1 gets Orf8:68* itself to cut down its Orf8.

good spot!!

**Comment by FedeGueli** [comment]
+1 Luxembourg +1 California

**Comment by FedeGueli** [comment]
13 now, new  Ireland, France

**Comment by FedeGueli** [comment]
17 all from France

**Comment by FedeGueli** [comment]
21, italy new country

**Comment by FedeGueli** [comment]
25 inn 7 countries

**Comment by FedeGueli** [comment]
43

**Comment by FedeGueli** [comment]
50, not fast but woidespread

**Comment by FedeGueli** [comment]
new country Ukraine

**Comment by FedeGueli** [comment]
Slow but circulating

**Comment by FedeGueli** [comment]
no seqs from April finally closing this
