### ISSUE TITLE
BA.1.17.2 mini saltation (6 seq. Italy)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#115]
Proposal for a sublineage of BA.1.17.2
Earliest sequence: 15.03.2023 (Italy)
Countries detected: Italy

Another potential mini saltation of BA.1.17 (cf. #1224, #1844). Two different originating lab, one submitting lab, two different uploads.

Defining Mutations:
nuc	unique	G11417T, T11630C, G12071A, C21219T, C22079A, C22323T, A22743G, T22917A, T22942G, C23741T, G24368C, G25266T, G27556T, A28319T, G28913T
nuc	homoplasies	T22254C, G22599C, C27389T
ORF1ab	unique	V3718F, F3789L, D3936N
S	unique	Q173K, S254F, N394S, L452Q, N460K, D936H, C1235F
S	homoplasies	I231T, R346T
ORF7a	unique	A55S
N	unique	T16S, G214C

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/ba3c7763-984a-42b1-bec7-538038b882b1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10578_59f530.json?c=gt-N_214

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/94e57643-344a-49d2-912b-1e8d733a3640)

EPI_ISL_17722060
EPI_ISL_17559150
EPI_ISL_17559167
EPI_ISL_17559165
EPI_ISL_17559166
EPI_ISL_17559168

Gisaid query: G11417T, T11630C, G12071A

**Comment by FedeGueli** [comment]
Hi @agamedilab this was spotted and proposed by @ryhisner in https://github.com/cov-lineages/pango-designation/issues/1970#issuecomment-1567437993

Then closed after @agrimaldi checked metadata were wrong and all the sequences were from a single patient.
But yesterday it popped up again and again with metadata showing different age/sex from the first patient. We are waiting info from Tigem/ @agrimaldi.

I will leave this open to allow discussion.
If this will turn to be a lineage and not a single chronic infection it will be designated from.the original issue by @ryhisner

**Comment by agrimaldi93** [comment]
Dear all,
We are currently checking with our sample provider. The Swab was collected in a different city than the previous ones, thus, it should be a different patient.
I will keep you posted as soon as I can.

**Comment by FedeGueli** [comment]
> Dear all, We are currently checking with our sample provider. The Swab was collected in a different city than the previous ones, thus, it should be a different patient. I will keep you posted as soon as I can.

Thank you very much! it would be quite a bad news.

**Comment by Sinickle** [comment]
EPI_ISL_17722060 is the sequence in question, correct? 

Spike differing from BA.1 by
Spike Q173K,  Spike I231T, Spike D253G, Spike S254F, Spike R346T, Spike N354K, Spike T376A, Spike N394S, Spike R403K, Spike V445A, Spike L452Q, Spike N460K, Spike E484T, Spike G496T, Spike A701V, Spike T791P, Spike K795T, Spike D843G, Spike I896T, Spike D936H, Spike L981S, Spike C1235F

**Comment by FedeGueli** [comment]
> EPI_ISL_17722060 is the sequence in question, correct?
> 
> Spike differing from BA.1 by Spike Q173K, Spike I231T, Spike D253G, Spike S254F, Spike R346T, Spike N354K, Spike T376A, Spike N394S, Spike R403K, Spike V445A, Spike L452Q, Spike N460K, Spike E484T, Spike G496T, Spike A701V, Spike T791P, Spike K795T, Spike D843G, Spike I896T, Spike D936H, Spike L981S, Spike C1235F

Yes it is that one and thx for highlighting gow it got quite everything we saw in one year of BA.5 plus a rid of new(or old) S2 mutations

**Comment by FedeGueli** [comment]
@Sinickle found a new sequence of this one from a different patient. uploaded on Friday but collected back in May.

**Comment by agrimaldi93** [comment]
@FedeGueli, I just checked with the sample provider. They gave us the wrong metadata again. It still is the same patient. I asked GISAID to remove all the samples from this sample provider to check all the metadata before re-upload them.
Sorry for the inconvenience.

**Comment by FedeGueli** [comment]
> @FedeGueli, I just checked with the sample provider. They gave us the wrong metadata again. It still is the same patient. I asked GISAID to remove all the samples from this sample provider to check all the metadata before re-upload them. Sorry for the inconvenience.

Thank you very much!
