### ISSUE TITLE
HK.13.2+Orf1b:T1178A, S:T250I,N:T379I(104 seqs, 13 countries, 2% Greece)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1151]
HK.13.2+A16999G,C22311T, C29409T(Orf1b:T1178A, S:T250I,N:T379I)

GISAID query: A16999G,C22311T, C29409T
No. of seqs: 15(Switzerland 1 Greece 2 UK 2 Spain 1 Germany 1 Denmark 1 USA 7)

First: EPI_ISL_18490364, Greece, 2023-9-28
Latest: EPI_ISL_18576504, USA, 2023-11-16

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice19_genome_26b1d_e86c70.json?label=id:node_3532821)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f93a570d-4bab-4f7d-adce-70ab7b9c1f6a)

**Comment by FedeGueli** [comment]
Thank you very diverse spike from the other backbones.

**Comment by aviczhl2** [comment]
25, Sweden

**Comment by FedeGueli** [comment]
most of the new samples are old, still this one of the most interesting lineages

**Comment by aviczhl2** [comment]
36, Belgium, Czech Republic

**Comment by aviczhl2** [comment]
11/578 in 12-21 Greece batch

**Comment by FedeGueli** [comment]
Let's see if it could make it through the Jn.1 wave. the recent sequences are all in the main Orf1a:4357V branch? in this case maybe worth adding it?

**Comment by aviczhl2** [comment]
> Let's see if it could make it through the Jn.1 wave. the recent sequences are all in the main Orf1a:4357V branch? in this case maybe worth adding it?

3/50 don't have that C13335T.

**Comment by FedeGueli** [comment]
> > Let's see if it could make it through the Jn.1 wave. the recent sequences are all in the main Orf1a:4357V branch? in this case maybe worth adding it?
> 
> 3/50 don't have that C13335T.

ok perfect so add it please.

**Comment by aviczhl2** [comment]
+1 China

**Comment by FedeGueli** [comment]
57 now , quite fast doubling but only 3 collected in December lets wait if some more come in the next few weeks.

**Comment by aviczhl2** [comment]
60, Australia

**Comment by FedeGueli** [comment]
> C13335T.

57/60 have the orf1a:4357V to me it should be added to the main proposal as defining.

**Comment by aviczhl2** [comment]
17/971 in Greek 2024-1-11 batch, still seqs from 2023-11 though. Now 22/843 of Greek seqs from 2023.11.

**Comment by aviczhl2** [comment]
10/514 in 2024-1-26 Greek batch

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by FedeGueli** [comment]
Designasted HK.13.2.1 via https://github.com/cov-lineages/pango-designation/commit/dc148ec8cdae9bbe64383b9a2b560861c679a63e
