### ISSUE TITLE
#466(XBB.1.16+S:K113R)/BA.2.86.1 recombinant in Japan (2 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1153]
Found by @JosetteSchoenma in #991, but worth an issue though. The two seqs are from different cities in Japan. And its XBB.1.16 donor is also interesting. 

This is the 4th non-singlet recombinant of BA.2.86*.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/73997836-ccbc-4907-a2ec-9fffe0ffcd87)

#466--BA.2.86.1
Breakpoint between 11957 and 12729

Additional mutations:
C3177T, C3587T,C3944A,C12115T, C26078T

Orf1a: P971L, H1108Y, Q1227K
Orf3a: T229I

C3177T, C3587T,C3944A from a Japanese XBB.1.16 branch under #466, with additional S:N148T. 
one of C12115T, C26078T come from a BA.2.86.1 branch, the other is private. As BA.2.86.1 has both branches , hard to decide which one is the donor and which one is private mutation.

[usher for XBB.1.16-donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ee2_ffa8b0.json?c=gt-nuc_3177,3587,3944&gmax=4177&label=id:node_3238498)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c2f980cd-c015-401d-b500-482658721b87)

GISAID query: C3944A,C12115T
No. of seqs: 2(Japan)
EPI_ISL_18505932, 2023-10-11, Kanagawa
EPI_ISL_18580656, 2023-11-15, Tokyo

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice13_genome_2919_fdf900.json?label=id:node_11165532)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d4359d37-8ead-4834-9427-611ef39c230a)

**Comment by FedeGueli** [comment]
Alt query:  C12115T, C26078T,C3587T

**Comment by FedeGueli** [comment]
Orf3a:T229I was in BN.1.3
