### ISSUE TITLE
EG.5.1/JN.1 (1)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1154]
First spotted by @corneliusroemer in #991 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b1aedd5c-7276-44f9-83cb-d358df6b0d3f)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1bc4c_b2290.json?c=gt-S_403&gmax=25384&gmin=21563&label=id:node_3493744

Gisaid Query: C7101T, C27527T, A22556G

submitted: 2023-11-19

EPI_ISL_18566568

**Comment by FedeGueli** [comment]
> Please check [#991 (comment)](https://github.com/sars-cov-2-variants/lineage-proposals/issues/991#issuecomment-1835753661) and https://github.com/sars-cov-2-variants/lineage-proposals/blob/main/recombinants.tsv

thank you @aviczhl2 missed this for some reasons, i  ve added credits letting it open for now.
