### ISSUE TITLE
JN.1.4 sublineage with ORF1b:G662S after T18453C first detected in Denmark (108 GISAID seqs as of 2024-02-11; Denmark, Belgium, Finland, Sweden, USA)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#1155]
There may be an emerging JN.1 sublineage with ORF1a:T170I (NSP1:T170I; C774T), ORF1b:G662S (NSP12:G671S; G15451A), T18453C first detected in Denmark.

If this sublineage is designated, I recommend that serious consideration be given to also designating the intermediate sublineage JN.1+ORF1a:T170I mentioned in [pre-proposal 987](https://github.com/sars-cov-2-variants/lineage-proposals/issues/987).

As of 2023-12-06, Cov-Spectrum reports 12 good-quality (13 total) JN.1+ORF1a:170I+ORF1b:662S+18453C sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AJN.1+%26+ORF1a%3AT170I+%26+ORF1b%3AG662S+%26+T18453C&nextcladeQcOverallScoreTo=29&

Growth estimates are currently unreliable due to the small number of samples. However, ORF1b:G662S has occurred in many clades and is commonly associated with an increase in relative viral fitness. The clade-specific Bloom and Neher estimates of the fitness effects of ORF1b:G662S are shown below.

As of 2023-12-06, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_JN 1+ORF1a_T170I+ORF1b_G662S+18453_zoomed-out](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/a1e66ad6-900c-4f2e-bd2f-59b54fff2476)
![UShER_JN 1+ORF1a_T170I+ORF1b_G662S+18453_zoomed-in](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/37048b10-dd1e-44ea-8fbc-424093d77474)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/12/subtreeAuspice1_genome_JN.1%2BORF1a_170I%2BORF1b_662S%2B18453C.json?c=gt-ORF1ab_5063&gmax=21555&gmin=266&label=id%3Anode_4499555

GISAID query: C18894T, T15756A, T27810C, C774T, G15451A

First GISAID sequence: Denmark 2023-10-23

Most Recent GISAID sequence: Denmark 2023-11-27

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support_JN.1_ORF1a_170I+ORF1b_662S+18453C.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/13593272/Support_JN.1_ORF1a_170I%2BORF1b_662S%2B18453C.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-JN.1_ORF1a_T170I_ORF1b_662S+18453C.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/13593269/gisaid-epi-isl-JN.1_ORF1a_T170I_ORF1b_662S%2B18453C.txt)

The clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of ORF1b:G662S, also ORF1ab:G5063S, are:

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,G5063S,2.142
20B,ORF1ab,G5063S,1.8651
20C,ORF1ab,G5063S,1.4897
20E,ORF1ab,G5063S,1.4964
20G,ORF1ab,G5063S,1.5901
20I,ORF1ab,G5063S,1.8127
21C,ORF1ab,G5063S,1.9842
21K,ORF1ab,G5063S,2.2852
21L,ORF1ab,G5063S,2.3697
22A,ORF1ab,G5063S,2.3362
22B,ORF1ab,G5063S,2.4345
22C,ORF1ab,G5063S,2.7677
22E,ORF1ab,G5063S,1.4166

ORF1b:G662S is foundational to clades not shown for which Bloom and Neher have provided data.

**Comment by FedeGueli** [comment]
big jump to 26. one to watch. ping @corneliusroemer

**Comment by alurqu** [comment]
A sequence from Belgium, EPI_ISL_18604462, has been uploaded to GISAID. This lineage has now shown international spread.

**Comment by FedeGueli** [comment]
39  now. clearly growing fast.

**Comment by FedeGueli** [comment]
62 now outside denmark

**Comment by aviczhl2** [comment]
ORF1b:G662S (NSP12:G671S; G15451A) shall be excluded from query. 

The count shall be 5116 now.

**Comment by alurqu** [comment]
I have updated the proposal title in response to designation of parental lineage as JN.1.4.

**Comment by FedeGueli** [comment]
> I have updated the proposal title in response to designation of parental lineage as JN.1.4.

Thx ! i ll do for everything else now (huge workload!)

**Comment by alurqu** [comment]
This lineage has few new samples in the last month, so it appears to have fizzled. I'm closing the issue.
