### ISSUE TITLE
JN.1 two branches

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1159]
```[tasklist]
### Tasks
- [ ] JN.1+ T4789A,C5144T（110 seqs , from Japan and Singapore）
- [x] JN.1+T18471C （971 seqs,from China,Canada,Australia and New Zealand）, **Parent of JN.1.35**
```

**Task 1**
GISAID seach `T4789A` ,`C5144T`
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/df0bcb61-835d-454e-95e9-012795c64844)
[Usher tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f549_89270.json?f_userOrOld=uploaded%20sample)
EPI_ISL_18461933, EPI_ISL_18501779-18501780, EPI_ISL_18513495,EPI_ISL_18513968, EPI_ISL_18536613, EPI_ISL_18561893,EPI_ISL_18566741, EPI_ISL_18580633, EPI_ISL_18584677,EPI_ISL_18584682, EPI_ISL_18591952, EPI_ISL_18591959,EPI_ISL_18593478

**Task 2**
Query: T18471C , C18894T, T15756A
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/0fb37293-10bc-42fc-aa22-76c7c66a9a5a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3524c_2adf50.json?label=id:node_5532951

**Comment by aviczhl2** [comment]
Is S:N417K real here?

**Comment by FedeGueli** [comment]
please remove the 417 branch is 99% artifact.

**Comment by FedeGueli** [comment]
added them to this one :https://cov-spectrum.org/collections/188?adminKey=KEAUmtGfqkqBdv12WTcQV

**Comment by Over-There-Is** [comment]
T18471C branch is also detected from a Thailand imported case.

**Comment by Memorablea** [comment]
> added them to this one :https://cov-spectrum.org/collections/188?adminKey=KEAUmtGfqkqBdv12WTcQV (key to edit)

ha?

**Comment by Memorablea** [comment]
T18471C South Korea+1 15now

**Comment by Memorablea** [comment]
BA.2.86.1 also have T18471C branch,from Denmark

**Comment by Memorablea** [comment]
add JN.1+S:F456V

**Comment by Memorablea** [comment]
add BA.2.86.1+S:S680F

**Comment by Memorablea** [comment]
@FedeGueli please add "S:456" label （or “S:680”label ？）

**Comment by FedeGueli** [comment]
> @FedeGueli please add "S:456" label （or “S:680”label ？）

please the branches defined by spike mutations propose in  separate issues.

**Comment by FedeGueli** [comment]
67 and 238 respectively

**Comment by Memorablea** [comment]
thanks

**Comment by FedeGueli** [comment]
110 /437 now

**Comment by FedeGueli** [comment]
please propose branch 2 it is around 7% in NZL

**Comment by Memorablea** [comment]
I plan to propose Branch 2. 971 now @FedeGueli

**Comment by FedeGueli** [comment]
> I plan to propose Branch 2. 971 now @FedeGueli

yes please

**Comment by aviczhl2** [comment]
JN.1.35 is designated as a sub-branch of branch 2, which means branch 2 cannot be designated now.
