### ISSUE TITLE
Fast growing DV.6+Orf1b:T1522I+S:Q613H (150 seqs, 16 countries) 

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#116]
DV.6+G23401T(S:Q613H),C18032T(Orf1b:T1522I),C6628T
GISAID query: G23401T,C18032T,C6628T

Number of seqs: 129(Australia 2 Austria 20 Belgium 1 Czech Rep 1 England 2 Finland 5 Germany 7 Hong Kong 1 Shanghai 4 Taiwan 6 Italy 1 Japan 6 Luxemburg 12 Malaysia 1 Netherlands 2 Singapore 11(1 from Malaysia) South Korea(1 from Japan) 27 USA-CA 1 USA-OH 17)

First seq: EPI_ISL_16976816, Austria, 2023-2-13
Latest: EPI_ISL_17715437, Austria, 2023-5-15

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice27_genome_25cac_587c60.json?label=id:node_7289347)

<img width="1068" alt="Screenshot 2023-05-30 at 17 12 36" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/51853585-91bc-43c0-b4be-4f4056af1aff">

<img width="1389" alt="Screenshot 2023-05-30 at 17 12 08" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d88818c7-ed8c-4816-aef7-ee754bcca261">

**Comment by aviczhl2** [comment]
A little faster than XBB.1.9.1 but a little slower than XBB.1.16
<img width="1075" alt="Screenshot 2023-05-30 at 17 15 25" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/87546603-1092-4ace-b77c-fcf90e3bd3ae">
<img width="1094" alt="Screenshot 2023-05-30 at 17 16 13" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a5dc3d06-e06c-4c3f-8054-12a2d8e4ce68">

**Comment by FedeGueli** [comment]
Interestingly this one gained also S:F486P in 3 seqs 2 of them are recent from Australia : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice27_genome_25cac_587c60.json?label=id:node_7289371

Beyond this:
In FInland two seqs appear to have recombined with XBB.1.5 (.12?) :https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_352e5_5e3940.json?f_userOrOld=uploaded%20sample&label=id:node_10205502
EPI_ISL_17699098 and EPI_ISL_17699172 losing the Orf1a part of CH.1.1 

Looking at 24 samples collected in May several stepwise evolved or saltation branches are involved:

![Schermata 2023-05-30 alle 14 02 00](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e3133f4b-2f8d-42af-80e2-f575779a2b22)

**Comment by FedeGueli** [comment]
Lets wait it stabilizes a bit (also to see if N:A173V branch could be defining or not counting  already 16/24 seqs)
If it keeps circulating in late May and early June it deserves a proposal.

**Comment by FedeGueli** [comment]
@aviczhl2 Wait but N:A173V is the defining of XBC.1.6.3 so could the top branch be a recombinant one?

**Comment by FedeGueli** [comment]
Yes likeky it would have required a mini recombinant event in N just between 64 and 376 unlikely

**Comment by aviczhl2** [comment]
Seems that N:A173V is not obviously faster than others. I'll propose the whole branch.
