### ISSUE TITLE
JN.3+N:H300Y(44 seq, 11 countries) and further S:F456V(20 seq, 5 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1160]
JN.3> C2939T(Orf1a:P892S)> C29171T(N:H300Y)> A17637G, T22928G(S:F456V), C29095T, C29253T(N:S327L)

S:F456V branch is spotted by @Huachuan1120 on 12-04.

Query: C2939T, A6183, C29171(3 dropout)
Query for S:F456V branch: A17637G, T22928G or **A17637G, C29095T, C29253T** (This one avoids to catch the recombinant- Edited / Suggested)

Earliest Sequence: 09-18 Auvergne-Rhône-Alpes, France EPI_ISL_18327129
Latest Sequence: 12-15 England, UK EPI_ISL_18688159
Regions Detected: 
France 13(ARA 6, HDF 3, Bretagne 1, IDF 1, Normandie 1, PDL 1), UK 10(Scotland 9, England 1), Germany 10(Bayern 6, Berlin 3, BW 1), Switzerland 3(Berne 2, Zürich 1), Denmark 2, Ireland 1(Kildare), Netherlands 1(Limburg);
Canada 1(Ontario), US 1(Michigan);
China 1(HK), Singapore 1

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_6c9b_389ab0.json?c=country&label=id:node_4507656
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/f269d833-1251-49e6-83b2-acef9111d01b)

<details><summary>Sequences:</summary>

EPI_ISL_18327129, EPI_ISL_18345205, EPI_ISL_18393016,
EPI_ISL_18398880, EPI_ISL_18421665, EPI_ISL_18421669,
EPI_ISL_18444789, EPI_ISL_18444795, EPI_ISL_18444860,
EPI_ISL_18444880, EPI_ISL_18493326, EPI_ISL_18510026,
EPI_ISL_18541096, EPI_ISL_18547047, EPI_ISL_18577281,
EPI_ISL_18577373, EPI_ISL_18592282, EPI_ISL_18596299,
EPI_ISL_18598210, EPI_ISL_18599846, EPI_ISL_18599863,
EPI_ISL_18606074, EPI_ISL_18605945, EPI_ISL_18619751,
EPI_ISL_18631463, EPI_ISL_18632934, EPI_ISL_18633152,
EPI_ISL_18645464, EPI_ISL_18652958, EPI_ISL_18661656,
EPI_ISL_18674685, EPI_ISL_18676345, EPI_ISL_18676927,
EPI_ISL_18680575, EPI_ISL_18688159, EPI_ISL_18688784,
EPI_ISL_18695237, EPI_ISL_18700645, EPI_ISL_18713427,
EPI_ISL_18716994, EPI_ISL_18717245, EPI_ISL_18724621,
EPI_ISL_18726821, OR981977.1

Potential recombinant with EG.5.1.3:
EPI_ISL_18705445, EPI_ISL_18724545
</details>

**Comment by Over-There-Is** [comment]
Deutcshland+2

**Comment by FedeGueli** [comment]
@corneliusroemer 456V expanding here.

**Comment by FedeGueli** [comment]
456V +1 Swi

**Comment by Over-There-Is** [comment]
Query edited to include the French sequence: C2939T, A6183, C29171

**Comment by Over-There-Is** [comment]
> 456V +1 Swi

Q677H

**Comment by Over-There-Is** [comment]
Ara, France+1

**Comment by Over-There-Is** [comment]
Earliest 2 sequences are also spotted by @hniman

**Comment by FedeGueli** [comment]
> C2939T, A6183, C29171

Thank you

**Comment by Over-There-Is** [comment]
Berlin +1

**Comment by Over-There-Is** [comment]
Bayern +1

**Comment by Over-There-Is** [comment]
Bayern +2

**Comment by FedeGueli** [comment]
propose it when 456V branch reaches 20. it seems fast

**Comment by FedeGueli** [comment]
cc @corneliusroemer apparent short doubling time

**Comment by Over-There-Is** [comment]
Ontario(Non F456V)

**Comment by Over-There-Is** [comment]
Genbank sequence OR981977 is not uploaded to GISAID yet.

**Comment by Over-There-Is** [comment]
England

**Comment by Over-There-Is** [comment]
I have noticed the Singaporean sequence, but forget to edit the issue. And now, the S:F456V branch is also recombined with EG.5.1.3*.

**Comment by FedeGueli** [comment]
the query : A17637G, C29095T, C29253T doesnt catch already th recombinant.

**Comment by Over-There-Is** [comment]
Switzerland/ZH-UZH-IMV-3ba6c30e/2023|EPI_ISL_18713427|2023-12-09 Orf8:Q18*

**Comment by Outpfmance** [comment]
A new sequences from Germany.It has 20 sequences now.
Search:A17637G, C29095T, C29253T

**Comment by Outpfmance** [comment]
@FedeGueli It’s time to propose it!

**Comment by Over-There-Is** [comment]
recombinant(2 sequences, UK 1, DE 1)
EG.5.1.3/JN.3/EG.5.1.3
Breakpoint 1: 8293\~8393
Breakpoint 2: 26833~27507
JN.3+A17637G+T22928G=S:F456V branch of this issue
EG.5.1.3 donor could be from one of several branches with C29409T(N:T379I) (but not JG.3*)
G598A should be private

Query: C1889T, G8393, A17637G

Scotland/CLIMB-CM7YRE7Y/2023|EPI_ISL_18705445|2023-12-16 Scotland, UK (with further C13620T)
Germany/BY-MVP-000023191/2023|EPI_ISL_18724545|2023-12-07 Augsburg, Bayern, Germany (with further C2937T, A6994G, C23601T, G24697A, C28775T)

**Comment by FedeGueli** [comment]
> propose it when 456V branch reaches 20. it seems fast

@Outpfmance already green light for the proposal @Over-There-Is please procede!

**Comment by FedeGueli** [comment]
Thank you.

**Comment by FedeGueli** [comment]
Designated JN.3.2 and JN.3.2.1 via https://github.com/cov-lineages/pango-designation/commit/bc21f6f06afddbc9f662caf5e71484ff92e14f77
