### ISSUE TITLE
Multiple JN.1*+S:H1058Y 2 ongoing branches as of 04/19

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1162]
JN.1+C24734T(S:H1058Y)

GISAID query for all JN.1*+S:H1058Y: C24734T,T22926C,A6183G (336 seqs)

- [x] [JN.1+S:H1058Y](https://github.com/cov-lineages/pango-designation/issues/2452), Designated JN.1.21, 93 seqs
- [x] Branch 1,JN.1+Orf3a:N119Y+S:H1058Y, Query: C24734T,T22926C,A25747T, 11 seqs, Spain,Greece, Dead
- [ ] Branch 2,JN.1.4+S:H1058Y, Query: C24734T,C774T,T18453C,-3177,-26029,-10078,-28201,-29799,-10323,-10138,-13308, 35 seqs, Italy,Sweden,USA,Luxembourg, Spain,China, Canada
- [x] Branch 3,JN.1.4 > A29799G > C27630T > C13536T > Orf1a:P1220S (C3923T) > Orf1b:1727L (C18647T) > C15588T >S:H1058Y (C24734T), Orf3a:V225I /G26065A), T27348C,Dead Query: C18647T, C15588T ,C24734T, 29 seqs, UK
- [x] Branch 4,JN.1.1+C9142T+S:H1058Y, Query:C1762A,C9142T,C24734T,Dead, 5 seqs,France, Slovenia, Spain,USA
- [x] Branch 5, JN.1.8.1+Orf1a:K1247R+S:H1058Y, Query: A4005G, G29717A,C24734T,Dead, 12 seqs, Canada
- [x] Branch 6, JN.1.9+Orf1a:K4138R+S:H1058Y, Query: G22111T,C24734T,A12678G,Dead, 8 seqs, USA, China
- [x] Branch 7, JN.1.22+S:H1058Y,Dead Query: C13019T,C24734T,C18894T, 3 seqs, USA, Ukraine
- [x] Branch 8, JN.1+A21700G+S:H1058Y,Dead, Query: A21700G,C24734T,C18894T, 3 seqs, UK, France
- [x] Branch 9, JN.1.4 ['T18453C', 'A13308G', 'C832T', 'C17134A', 'C17304T', 'C24734T'], Query: T18453C,A13308G,C24734T,Dead, 22 seqs, South Korea
- [x] Branch 10, JN.1+C25566T,A11947G,G17122T,C5986T,C24734T,C28603T, Query: C25566T,C24734T,A11947G, 4 seqs, Dead, China, South Korea
- [ ] Branch 11, KP.2+T22795G+S:H1058Y,N:T135N, Query: C24734T, T22795G, C28677A, 7 seqs, France

Doublets:

1. JN.1.4+Orf1a:P971L+S:H1058Y, Query: C24734T,C774T,C3177T, USA (dead)
2. JN.1.4+Orf3a:Q213K,S:H1058Y, Query: C24734T,C26029A,C774T, Australia (slow)

Singlets:

1. [Pango#2426](https://github.com/cov-lineages/pango-designation/issues/2426)+C28948T+S:H1058Y, Query: C28948T,C24734T,A6183G, Singapore
2. JN.1.4+C16308T+C10078T, C17634T+T21246C+S:H1058Y, Query: C17634T,T21246C,C24734T, Singapore
4. JN.1.4+Orf1a:T3150I+S:H1058Y, Query: C774T,C9714T, C24734T, Italy
5. JN.1.1+Orf1a:T2124I+S:H1058Y, Query: C6636T, C24734T,C1762A, France
6. #1148+Orf3a:D27H+S:H1058Y, Query: C24734T, C21952T ,A22600C, France
7. JN.1.1+C9142T+C12970T+S:H1058Y, Query: C24734T, C12970T,C9142T, Slovenia
8. JN.1.1+Orf3a:T24I+S:H1058Y, Query: C24734T, C25463T, C1762A, France
9. JN.1.2+Orf1b:T2488M+S:P57S,S:H1058Y, Query: C20930T,C24734T,T22926C, -11986, Canada
10. JN.1.2+Orf1b:T2488M+C11986T+S:H1058Y,Orf8:Y31*, Query: C11986T,C24734T,C20930T, Canada
11. #987 branch 1+Orf1a:Y1734F+S:H1058Y, Query: C24734T, A5466T, UK
12. JN.1+Orf1a:K3353R+S:H1058Y, Query:A10323G, C24734T, T22926C, UK

**Comment by FedeGueli** [comment]
Thx we will se if it is a local cluster or instead spreads further .

**Comment by FedeGueli** [comment]
+1 Singapore +1 Netherlands. it is clearly already spreading outside Austria.

**Comment by FedeGueli** [comment]
13, found now in California too.

**Comment by FedeGueli** [comment]
+2 Us, Ger

**Comment by FedeGueli** [comment]
+1 Netherlands

**Comment by aviczhl2** [comment]
34, Switzerland, France, Australia

**Comment by aviczhl2** [comment]
37, USA, UK

**Comment by aviczhl2** [comment]
49, Slovenia, Ireland,Canada

**Comment by FedeGueli** [comment]
pls propose it

**Comment by aviczhl2** [comment]
It is actually diversed into multiple branches.
Edit query to focus on main branch.

**Comment by aviczhl2** [comment]
68, Chile

**Comment by aviczhl2** [comment]
Re-arranged the proposal to face the convergent status. 

2 branches, 2 doublets and 9 singlets for JN.1*+S:H1058Y

**Comment by FedeGueli** [comment]
Please propose branch 1

**Comment by Memorablea** [comment]
> Please propose branch 1

I think it should be specified after #2426.

**Comment by aviczhl2** [comment]
1/20: 
Add doublet 3

**Comment by aviczhl2** [comment]
1/26:
Add branch 3

**Comment by FedeGueli** [comment]
I ve updated the issue searching for this new very recent UK branch JN.1.4 ( i guess a cluster) popped up after sustaiend stepwise evolution:

Tree:
<img width="1166" alt="Screenshot 2024-02-02 alle 10 08 50" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/40168d0c-92d0-4da7-8283-3caacfe13e85">

<img width="1168" alt="Screenshot 2024-02-02 alle 10 10 28" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c432c34d-10d9-463f-950a-68786d3e5934">


https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5e399_cb0cf0.json?label=id:node_6935725

It is defined by S:H1058Y and Orf3a:V225I 

JN.1.4 > A29799G > C27630T > C13536T > Orf1a:P1220S (C3923T) > Orf1b:1727L (C18647T) > C15588T >S:h1058Y (C24734T), Orf3a:V225I /G26065A), T27348C

**Comment by FedeGueli** [comment]
Branch 1 designated JN.1.21 via https://github.com/sars-cov-2-variants/lineage-proposals/issues/1162

**Comment by FedeGueli** [comment]
> I ve updated the issue searching for this new very recent UK branch JN.1.4 ( i guess a cluster) popped up after sustaiend stepwise evolution:
> 
> Tree: <img alt="Screenshot 2024-02-02 alle 10 08 50" width="1166" src="https://private-user-images.githubusercontent.com/87669813/301790072-40168d0c-92d0-4da7-8283-3caacfe13e85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwODAyNTcsIm5iZiI6MTcwNzA3OTk1NywicGF0aCI6Ii84NzY2OTgxMy8zMDE3OTAwNzItNDAxNjhkMGMtOTJkMC00ZGE3LTgyODMtM2NhYWNmZTEzZTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDIwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDFmMTgyMjBiMGM2MGExYWQyZWI0NjMxODUwNTk4ZDdjNTQ3NTE2ZjY0YjI3NDU2ZTdmZjMwMGJiNmVlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rpDLPBMBX962SwGxQ7B9ProLGX6VydHQ1kpr0CfKb44">
> 
> <img alt="Screenshot 2024-02-02 alle 10 10 28" width="1168" src="https://private-user-images.githubusercontent.com/87669813/301790518-c432c34d-10d9-463f-950a-68786d3e5934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwODAyNTcsIm5iZiI6MTcwNzA3OTk1NywicGF0aCI6Ii84NzY2OTgxMy8zMDE3OTA1MTgtYzQzMmMzNGQtMTBkOS00NjNmLTk1MGEtNjg3ODZkM2U1OTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDIwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyM2FlNGY3ZGI1ZDJmZjdmY2Y3YzE4YTQxMjNhMGUxNjlmMmVhMmFmYWYzNWE1MjVkOTkxMDZkOTgzNjE3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IcQ5ffKli6x_B4ixcRlut4lk-xqKDGSQ_xpJ3qykDP8">
> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5e399_cb0cf0.json?label=id:node_6935725
> 
> It is defined by S:H1058Y and Orf3a:V225I
> 
> JN.1.4 > A29799G > C27630T > C13536T > Orf1a:P1220S (C3923T) > Orf1b:1727L (C18647T) > C15588T >S:h1058Y (C24734T), Orf3a:V225I /G26065A), T27348C
> 
> Query: C18647T, C15588T ,C24734T
> 
> Samples: 16

@aviczhl2 please add to the main proposal as branch

**Comment by aviczhl2** [comment]
2/11: Add branch 4
Branch 2 becomes 24

**Comment by aviczhl2** [comment]
3/1 Add branch 6

**Comment by aviczhl2** [comment]
3/15 Add branch 8

**Comment by aviczhl2** [comment]
Add branch 9, 17 seqs from South Korea

**Comment by aviczhl2** [comment]
Most branches are dead. Close this.

**Comment by FedeGueli** [comment]
Thank you for the "multiple" effort ;)

**Comment by FedeGueli** [comment]
JN.1.21 has got a very big sublineage with Orf7b:F13del as big as 210 out of 470 , 
Query : del27792_27794,C24734T,T22926C,

**Comment by aviczhl2** [comment]
There seems to be a new branch under KP.2, reopen this

**Comment by aviczhl2** [comment]
No new seqs, close down.
