### ISSUE TITLE
Potential XDA, GW.5.1.1 (or GW.5.3.1), XDA sandwich recombinant (14 seqs, UK)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1163]
**Query**: `T24046C, C27059T` or `T8908C, A13693G, C22986T`
**Earliest seq**: 2023-12-02 (`EPI_ISL_18598919`, England)
**Latest seq**: 2023-12-02 (`EPI_ISL_18598920`, England)
**Sampled Countries**: UK (2: EN)

**Recombinant Profiles**: 
- Placement on Phylogenetic Tree: **`XDA`** > `C27059T` > `G22927T(S:L455F, C22986T(S:A475V), C22995T(S:T478I, T>K>R>I)`, _`rev_T23664C(S:rev_V701A)`_, `C24034T(S:N824N), T24046C(S:L828L), G25599T(ORF3a:W69C)`
- Donor A: `XDA`, upstream from 5' end to 1st breakpoint, downstream from 2nd bp to 3' end.
- Donor B: `GW.5.1.1` or `GW.5.3.1`, between 2 bps
- 1st Breakpoint: Between `nuc_22107/spike_182` to `nuc_22926/spike_455` if one of the donor is `GW.5.1.1`; Between `nuc_22113/spike_184` to `nuc_22926/spike_455` if one of the donor is `GW.5.3.1`
- 2nd Breakpoint: Between `nuc_24047/spike_829` to `nuc_25838/ORF3a_149`
- Private mutation(s): `ORF3a:W69C (G25599T)`
- Effectifly this would be **XDA** with `FLip` combo plus `A475V` and `T478I` at a cost of `A701V`, _OR_ **GW.5.1.1** with its ORF7ab restored plus `K182Q` and `ORF9b:I5T`
- Details of mutations:
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/69189bd7-c999-429b-b0cb-c6f3e6eea36a)

**Genomes**:
```
England/CLIMB-CM7Y89IF/2023|EPI_ISL_18598919|2023
England/CLIMB-CM7YFFCT/2023|EPI_ISL_18598920|2023
```

**UShER**:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice17_genome_test_23e00_3e3230.json?f_userOrOld=uploaded%20sample&label=id:node_3348095
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/301a8cfe-5baa-487e-8dc2-659a2a107551)

**Comment by FedeGueli** [comment]
Great catch and great deal on the paper : fast XDA got FLip 475V 478 and 554 in one shot

**Comment by aviczhl2** [comment]
Breakpoint shall be after S:182 if the donor is GW.5.1.1

**Comment by aviczhl2** [comment]
6 now

**Comment by FedeGueli** [comment]
11 now, growing fast.

**Comment by corneliusroemer** [comment]
It's an interesting one, are we sure that XDA is a parent or could a parent of XDA be a parent here? I guess XDA as parent is not too unlikely given that XDA is quite prevalent in the middle east and Indonesia (Muslim majority countries) and so is GW.5).

It has a potentially quite competitive genotype
