### ISSUE TITLE
#1086(XCT+S:S151R)/(#972(EG.5.1/DV.7.1 recomb) or its DV.7.1-donor) recombinant (3 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1165]
There seems to be a new recomb between #1086 and #972 (or https://github.com/cov-lineages/pango-designation/issues/2394) or its DV.7.1-donor.
Previously registered in #991 and now it becomes 3.

XCT+A22013C, T22849C, C25959T(rev), C27507A(rev), T27915G(rev), C28297T(rev),C29518T, T29793A

S:S151R
Orf8:*8G(rev)
Orf9b:T5I(rev)

#1086--#972 or its DV.7.1 donor
Breakpoint between 24074 and 25958.

A22013C,T22849C from the main branch of #1086 
C25959T(rev), C27507A(rev), T27915G(rev), C28297T(rev),C29518T,T29793A from #972 or its DV.7.1 donor

GISAID query: A22013C,C29518T

No. of seqs: 3( Denmark 1 Sweden 2)

First: EPI_ISL_18416021, Denmark, 2023-10-9
Latest: EPI_ISL_18598333, Sweden, 2023-11-30

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice23_genome_a62c_519160.json?label=id:node_11187064)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c4918055-a025-4262-ba29-bc172b533e35)

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by ryhisner** [comment]
S:S151R eliminates the S:N149 glycan, so that's a substantial change.

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
Thx for spotting anyway, one of the fiorst multilevel recombinants analysed.
