### ISSUE TITLE
Interesting BA.2.36 singlet saltation

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1167]
Gisaid Search:EPI_ISL_18590820 11-20,2023, Denmark
Interesting Mutations: I would put S:H245Y and S:R403S. 245Y is a remarkable rare yet marker for saltation mutation, S:R403S is close to S:R403K and I wonder if it can do stuff. P621S and A623V being close could also be interesting.
<img width="1124" alt="Screenshot 2023-12-11 at 6 04 29 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/b3847d68-07f5-4397-991a-aa6383ae38f3">

**Comment by FedeGueli** [comment]
Thank you for spotting this.
