### ISSUE TITLE
Undesignated branch of XBB.1.22.1 likely emerged in Middle-East  with S:A222V, S:T478R , S:K679R (15 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1168]
cc @corneliusroemer this has not fit to compete with Jn.1 , still coming from an undersampled area where xbb.1.22.1 emerged first it could have still some relevance to be analyzed.

Big undesignated branch:
![Schermata 2023-12-12 alle 00 25 37](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/569c69ea-891a-4b8a-8cb9-3c3bc5914159)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_5d8e1_798160.json?c=userOrOld&label=id:node_3236145

Defining mutations:
XBB.1.22.1 > Orf8:C102F (G28198T) >  ORF1a:A2637T (G8174A),T13195C > T16854C, T20625C, S:A222V (C22227T) > C17421T, S:T478R (A22995G) , S:K679R (A23598G)

Gisaid Query : C17421T, C22995G, A23598G

Samples: 13
First: GBW from Qatar EPI_ISL_18338555 | 2023-09-23
Last: Texas, EPI_ISL_18592562 | 2023-11-13
IDs : EPI_ISL_18338555, EPI_ISL_18338585, EPI_ISL_18352477,
EPI_ISL_18435118, EPI_ISL_18440430, EPI_ISL_18461106,
EPI_ISL_18491773, EPI_ISL_18491798, EPI_ISL_18511593,
EPI_ISL_18580356, EPI_ISL_18592538, EPI_ISL_18592559,
EPI_ISL_18592562

cc @hynnspylor did u notice this before?

**Comment by HynnSpylor** [comment]
One more in Sweden with S:N703K

**Comment by FedeGueli** [comment]
+1 Germany

**Comment by FedeGueli** [comment]
no new sequence tracking it pvtly
