### ISSUE TITLE
Very recent FL.4 + N:K256R sublineage blooming in China (203 seqs )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#117]
Just spotted it seems increasing its share in Chinese samples all along MAY 2023

Defining mutations: FL.4 >> N:K256R (A29040G) 

(Note that differently from FL.4.1 and FL.4.2 this is **not** in the branch with A28615G)
![Schermata 2023-05-30 alle 18 16 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8adcc8af-201c-4e0d-b5e7-0c4c4707b293)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32d9_620360.json?c=country&label=id:node_6716751

Gisaid query: G16741T, A29040G,T28297C
Samples 77

EPI_ISL_9064622, EPI_ISL_16553478, EPI_ISL_17625346,
EPI_ISL_17625376, EPI_ISL_17625396, EPI_ISL_17645431,
EPI_ISL_17645495-17645496, EPI_ISL_17645502-17645503, EPI_ISL_17652437,
EPI_ISL_17664554, EPI_ISL_17664556, EPI_ISL_17671922,
EPI_ISL_17672042, EPI_ISL_17672044, EPI_ISL_17678296,
EPI_ISL_17678328, EPI_ISL_17678353, EPI_ISL_17678432,
EPI_ISL_17683129, EPI_ISL_17684134, EPI_ISL_17684348-17684349,
EPI_ISL_17684358, EPI_ISL_17684363-17684364, EPI_ISL_17684369,
EPI_ISL_17684376-17684377, EPI_ISL_17684380, EPI_ISL_17684385-17684386,
EPI_ISL_17684389-17684391, EPI_ISL_17684393, EPI_ISL_17684463,
EPI_ISL_17689342, EPI_ISL_17689427, EPI_ISL_17689429,
EPI_ISL_17694990, EPI_ISL_17696757, EPI_ISL_17696924,
EPI_ISL_17696950, EPI_ISL_17696953, EPI_ISL_17696962,
EPI_ISL_17696966, EPI_ISL_17696980, EPI_ISL_17697978,
EPI_ISL_17698001, EPI_ISL_17698102, EPI_ISL_17703966,
EPI_ISL_17714320, EPI_ISL_17714323, EPI_ISL_17714325-17714327,
EPI_ISL_17714332, EPI_ISL_17714380, EPI_ISL_17714398,
EPI_ISL_17714401, EPI_ISL_17716662, EPI_ISL_17718354-17718355,

**Comment by FedeGueli** [comment]
New ones from Gansu Anhui Shanghai Xinjinag Yunnan and South Korea (from Thailand)

**Comment by FedeGueli** [comment]
140 seqs it seems very fast . @memorablea @over_there_is were you tracking this one?

**Comment by Memorablea** [comment]
> 140 seqs it seems very fast (edited: far from Orf1b:D54N see [here](https://cov-spectrum.org/explore/China/AllSamples/Past2M/variants?aaMutations=Orf1b%3AD54N&aaMutations1=N%3AK256R&nextcladePangoLineage1=FL.4&analysisMode=CompareToBaseline&).) @Memorablea @over_there_is were you tracking this one?

Received, we will track

**Comment by Memorablea** [comment]
Eight sequences from Shanghai.

**Comment by aviczhl2** [comment]
Many of this further gained S:V1129I

**Comment by FedeGueli** [comment]
![Schermata 2023-06-27 alle 14 25 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7c0afa90-6b56-4f3e-ad90-6dbbc53ae9fa)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice31_genome_test_5aa23_ac1b90.json?label=id:node_6680923
It appears to be the second largest branch of FL.4 :
 
![Schermata 2023-06-27 alle 14 26 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5e9b8bc4-e670-4210-b491-7af0a1bfe89c)

Ping @corneliusroemer this FL.4 branch is widespread in China  but likely will go further expanding.
Said that it is not faster than EG.5 but in that case 99% of lineages are slower than that:
https://cov-spectrum.org/explore/Asia/AllSamples/from%3D2023-05-15%26to%3D2023-06-27/variants?aaMutations=N%3A256R&aaMutations1=Orf1b%3AD54N&analysisMode=CompareToBaseline&

**Comment by Over-There-Is** [comment]
C_AA024656, C_AA024682.1

**Comment by Over-There-Is** [comment]
4 seq from 3 provinces in China, 187 now.

**Comment by Over-There-Is** [comment]
194 on GISAID now, spread to Portugal and Israel. And two Chinese sequences C_AA024656, C_AA024682.1 not uploaded to GISAID is still not counted.

**Comment by Over-There-Is** [comment]
202 on GISAID

**Comment by Over-There-Is** [comment]
203, 1 in Quebec.

**Comment by FedeGueli** [comment]
I think this should be proposed and designated
@aviczhl2 @Over-There-Is @Memorablea @hynnspylor @nkmr do u ageee?

**Comment by Memorablea** [comment]
High growth probability, worth specifying.

> I think this should be proposed and designated @aviczhl2 @Over-There-Is @Memorablea @HynnSpylor @nkmr @BorisUitham do u ageee?

**Comment by aviczhl2** [comment]
> I think this should be proposed and designated @aviczhl2 @Over-There-Is @Memorablea @HynnSpylor @nkmr @BorisUitham do u ageee?

Yes, agreed,

**Comment by Over-There-Is** [comment]
So do I.

**Comment by Over-There-Is** [comment]
@NkRMnZr

**Comment by FedeGueli** [comment]
Ok thx i will propose it now!

**Comment by FedeGueli** [comment]
FL.4.10 via https://github.com/cov-lineages/pango-designation/commit/1403582daca652ff33227de157a09b16add58a8d startig from S:V1129I spotted by @aviczhl2 : https://github.com/sars-cov-2-variants/lineage-proposals/issues/117#issuecomment-1596669039
