### ISSUE TITLE
HV.1.6.1 with S:K444N (221 seqs, mainly in Canada, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1174]
**Defining Mutations:** `HV.1.6.1` > `G22894T(S:K444N)`
**Query:** `C5646T, C11020T, G22894T` alternative better query :   **G22894T, C11020T, C23673T, C6317T** (EDITED)
**Earliest seq:** 2023-10-13 (`EPI_ISL_18427211`, Ontario, Canada)
**Latest seq:** 2023-12-03 (`EPI_ISL_18615136`, Ontario, Canada)
**Sampled Countries:** Canada (64, ON/63; BC/1), Japan (2), USA (1: NY)

<details><summary>Genomes: </summary>

`EPI_ISL_18427211, EPI_ISL_18427397, EPI_ISL_18448709, EPI_ISL_18448952-18448953, EPI_ISL_18451478, EPI_ISL_18451508, EPI_ISL_18451523, EPI_ISL_18471317, EPI_ISL_18471819, EPI_ISL_18474372, EPI_ISL_18504005, EPI_ISL_18504717, EPI_ISL_18549002-18549003, EPI_ISL_18549304, EPI_ISL_18549337, EPI_ISL_18580674, EPI_ISL_18580690, EPI_ISL_18581579-18581580, EPI_ISL_18581592, EPI_ISL_18581608, EPI_ISL_18581627-18581630, EPI_ISL_18581691, EPI_ISL_18581694, EPI_ISL_18581717, EPI_ISL_18581850, EPI_ISL_18581922, EPI_ISL_18582420, EPI_ISL_18582607, EPI_ISL_18582725, EPI_ISL_18582976, EPI_ISL_18583023, EPI_ISL_18583032, EPI_ISL_18583061, EPI_ISL_18583094, EPI_ISL_18583098, EPI_ISL_18583208, EPI_ISL_18583224, EPI_ISL_18583272, EPI_ISL_18591181, EPI_ISL_18591301, EPI_ISL_18591376, EPI_ISL_18591549, EPI_ISL_18602359, EPI_ISL_18609168, EPI_ISL_18610674, EPI_ISL_18610882, EPI_ISL_18610983, EPI_ISL_18611054, EPI_ISL_18611056, EPI_ISL_18611074, EPI_ISL_18611228, EPI_ISL_18614976, EPI_ISL_18614984, EPI_ISL_18615020, EPI_ISL_18615036, EPI_ISL_18615058, EPI_ISL_18615060, EPI_ISL_18615083, EPI_ISL_18615087, EPI_ISL_18615136, EPI_ISL_18615159`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_120e6_962830.json?f_userOrOld=uploaded%20sample&label=id:node_3423723
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d25241ce-d5b1-4fd5-b399-d2877d52ed31)

**Trivia:**
- Looks like typical Canadian cluster due to high sample density, from different labs though.
- The interesting part is a sub-branch with ORF8:W45S(G28027C) acquired further ORF8:W45*(G28027A), on top of already truncated ORF8:G8*. What is going on out there?
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ade5a853-5088-4746-ae4a-ce7f93cfcd52)

**Comment by FedeGueli** [comment]
long time we didn't see 444N spreading in this way.

**Comment by krosa1910** [comment]
Heh? S:K444N?
Somehow HV.1 reminds me of CH.1.1*. As it adopted F157L and L452R from it. Now with something in 444, I could only think the deja vu intensifies.

**Comment by FedeGueli** [comment]
> @NkRMnZr @corneliusroemer @FedeGueli This whoopingly jumped to 219 now , and Switerland had been added, I suggest possible designation for it.

propose it in the main page. yes i was tracking it too, still want to watch it outside Canada.

**Comment by FedeGueli** [comment]
i have 156 where do you get 219? @krosa1910

**Comment by krosa1910** [comment]
> i have 156 where do you get 219? @krosa1910

C5835T, T22917G,G22894T,C23673T I guess? I did not check it carefully so can be wrong.

**Comment by krosa1910** [comment]
The Tree I got.
I am not sure if this search gives a uniform tree, it is up to you to define this branch I guess?
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_9e5d_d5ad80.json?f_userOrOld=uploaded%20sample&label=id:node_1008534
<img width="1174" alt="Screenshot 2023-12-28 at 6 25 34 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/066fd591-c8b0-41fa-bc0c-a0e44c5f9710">

**Comment by FedeGueli** [comment]
> The Tree I got. I am not sure if this search gives a uniform tree, it is up to you to define this branch I guess? Still, this tree managed to pass all the four CT transitions besides S704L defined for HV.1.6.1*, so I think it is legit. I don't know how NKR would like to post it though. 

ok thank you: new query   G22894T, C11020T, C23673T, C6317T from https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_343b1_d5bff0.json?label=id:node_3558411
<img width="1163" alt="Screenshot 2023-12-28 alle 12 31 24" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d98d7542-29b0-43b6-a1b2-673c5be11753">
