### ISSUE TITLE
Weird Lineage of XBB.1.5.72* with S:K356T and S:Y266F. (45) with branch of S:T572I (36) that could be circulating at some level in Costa Rica 

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1178]
I was roaming the S:K356T and S:T572I trying to find resource for a pledged brief about those two , and I found this weird XBB.1.5.72* (sub)tree. It seems recent enough and appeared in a under-sampled area (or what i believe to be so)
Search: A22359T, A22629C,G22317T ( I have no idea why apparently some bat sequences covered mutations of XBB.1.5.72*, so I have to resort to S:G252V for this)
Search for sub-tree with S:T572I
A22359T, A22629C,G22317T,C23277T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_22d5f_b53aa0.json?f_userOrOld=uploaded%20sample&label=id:node_5391320
<img width="1358" alt="Screenshot 2023-12-14 at 2 17 11 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/394e923a-ada4-4fd2-a41b-182bd3d89bc2">

Honestly I don't expect any XBB.1.5* outside JD.1.1* to put up any resistence to JN.1*, but this got interesting enough. S:Y266F is rather rare and 356+572 combo is common and mildly successful, so deserve to be proposed.
Judging from the spread, I would think it was probably originated in Costa RIca, then it spread to US likely in its Southern Hispanic communities. It was then brought to Columbia and Spain, from Spain to Germany. 
Yeah, why would I write Puerto Rico when submitting the original statement, maybe just tired.

Edited Jan 31:
From @NkRMnZr this has also ORF9b:Q20R (A28342G)

**Comment by FedeGueli** [comment]
EPI_ISL_18621654 could be a recombinant with EG.5.1 suggesting a wider circulation or prevalence likely in Costa Rica

**Comment by krosa1910** [comment]
Gets some big uploads in Czech and Spain, this is actually more successful than I am thinking.

**Comment by krosa1910** [comment]
<img width="1174" alt="Screenshot 2023-12-21 at 4 18 40 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/b795c130-8596-4ab4-8908-b6b740007a5b">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_13e2a_402de0.json?f_userOrOld=uploaded%20sample&label=id:node_1139397

**Comment by krosa1910** [comment]
+2 in Canada, I guess it could reach 50 and I would propose it then.

**Comment by FedeGueli** [comment]
29 tot. and 23 fro the 572I branch

**Comment by krosa1910** [comment]
Second sequence in Columbia, I am more confident it did if not still does circulate in Latin America

**Comment by HynnSpylor** [comment]
38 seqs for main branch, and 30 seqs for T572I branch now

**Comment by FedeGueli** [comment]
propose it please @krosa1910

**Comment by FedeGueli** [comment]
> ORF9b:Q20R 

@ryhisner 

thx @NkRMnZr

**Comment by FedeGueli** [comment]
45736 as of today ,
@krosa1910 please propose it adding the mutation highlighted by @NkRMnZr

**Comment by krosa1910** [comment]
No update since 1/29, as in general the receding tide of XBB*, especially non EG.5.1* ones seems irreversible I think this can be the endnote for this lineage.
I think I am closing this for now.
