### ISSUE TITLE
XBB.1.9.1 with ORF1ab:T2007I, N:T166I, S:Y200C, ORF1ab:H5042Q, ORF1ab:G519S, S:K478R (seq.12) 5 countries

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#118]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b6354922-ffea-475f-9394-272bdf466e26)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/cfe4f494-cff7-488b-ab4d-273bdff35e8a)
EPI_ISL_17657166 EPI_ISL_17682885 EPI_ISL_17689132 EPI_ISL_17683629 PHEP-YYGWUKK/2023 EPI_ISL_17718870 EPI_ISL_17614765 EPI_ISL_17703980 EPI_ISL_17408992 EPI_ISL_17614857 EPI_ISL_17661231 EPI_ISL_17696738 
First seq - 2023-03-29
Most Recent - 2023-05-16
gisaid query: C15390A, T26457C
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f84a_65d0f0.json?c=gt-nuc_26457&label=id:node_6679065

**Comment by FedeGueli** [comment]
Already pre proposed here and transferred to Pango: https://github.com/cov-lineages/pango-designation/issues/2019
