### ISSUE TITLE
JN.1.4  with S:N185D emerged in NY  (118 sequences , US, Ireland as 01/17)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1180]
Defining mutations:
JN.1.4 [Orf1a:T170I (C774T)] > T18453C > S:N185D (A22115G) 

Query:C774T,T18453C,A22115G

Samples: 6 (All NY)
First sample collected on 2023-11-17 last one collected on 26/11/2023
EPI_ISL_18601499, EPI_ISL_18621722, EPI_ISL_18621757,
EPI_ISL_18621810, EPI_ISL_18621904, EPI_ISL_18621928,

Tree:
![Schermata 2023-12-15 alle 11 28 06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9487e2a7-8575-48c1-b8f0-dc68d4d31408)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_36a3e_c29000.json?c=userOrOld&label=id:node_4451488

**Comment by FedeGueli** [comment]
+3 NY , Ireland

**Comment by FedeGueli** [comment]
+2 NY

**Comment by FedeGueli** [comment]
20 now

**Comment by FedeGueli** [comment]
28 new states: California, Maryland

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/bd222b8e-9333-4c05-adaa-6eb776c476c8)
now 60

**Comment by FedeGueli** [comment]
77 now ping @corneliusroemer known fit mutation is spreading quite well , although still mainly NYC for now.

**Comment by FedeGueli** [comment]
transferred to main repo

**Comment by FedeGueli** [comment]
Designated JN.1.4.2 via https://github.com/cov-lineages/pango-designation/commit/271f9e03fbf810521bb98a56c138106dae8e12a8
