### ISSUE TITLE
BA.2.86.1 with S:S680F （22 seqs，from Nine countries）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1182]
BA.2.86.1 with S:S680F 
Country:China,Singapore,Germany,Thailand,New Zealand
GISAID seach：A7842, C23601T, C29614T
THX for @Over-There-Is 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_237bb_c59c90.json?f_userOrOld=uploaded%20sample
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/8ce6b01d-0927-4207-b122-539b2165843c)

**Comment by Memorablea** [comment]
Japan +4 15seqs now

**Comment by FedeGueli** [comment]
+1 Malaysia

**Comment by Memorablea** [comment]
Japan +1 17seqs

**Comment by Memorablea** [comment]
Thailand+1 Netherlands+1 Indonesia+3. 22seqs 9 county

**Comment by FedeGueli** [comment]
please propose it.

**Comment by Memorablea** [comment]
go github.com/cov-lineages/pango-designation/issues/2424

**Comment by Memorablea** [comment]
There doesn't seem to be much about Spike_ Research on S680F?

**Comment by FedeGueli** [comment]
Designated JN.14 via https://github.com/cov-lineages/pango-designation/commit/1cb2994e5b5c4ca2539354808d9716f2c06c8328#commitcomment-140372586
