### ISSUE TITLE
XDT : BA.2.86.4 + GK.1  recombinant (27 seqs, Ireland, UK, 8 with S:P174S)

### ISSUE THREAD

**Issue by DeepakPhuyal** [sars-cov-2-variants/lineage-proposals#1183]
**_Spotted first by @JosetteSchoenma (Edited)_**

EPI_ISL_18521215, EPI_ISL_18636413, EPI_ISL_18636423, EPI_ISL_18636425-18636426, 
5 sequences from Ireland, 
collected between Nov 13th and Dec 5th,
first one uploaded on Nov 20th and then 4 more on Dec 15th.

Breakpoint at Spike S2 between 23673 and 24378.

Private mutations: ORF1a:L446F, S:P174S

New Query by @aviczhl2 : A7842G, C1601T, A8633G, C897A  (suggested one)
Previous Queries by @JosetteSchoenma : 
T5767C, A7842G, C28005T
and
C1601T, T4654C, T7633C 
(EDITED)_

Usher tree is a bit clueless at the moment: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14949_db8910.json?label=id:node_5398024

**Comment by ryhisner** [comment]
Was looking at this one yesterday. ORF3a:I35T and ORF3a:T89I, both taken from the GK* part of this recombinant, have positive fitness values in the Bloom Lab fitness calculator.
<img width="1428" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f34062cb-0bc0-4b00-b5da-66cacd589e2e">

**Comment by aviczhl2** [comment]
EPI_ISL_18521215 was previously registered on #991 by @JosetteSchoenma .This again highlights the importance of #991.

**Comment by FedeGueli** [comment]
S:P174S was in HK.3.5 quite good.

**Comment by JosetteSchoenma** [comment]
I have been using these 2 queries since I saw that first one.

T5767C, A7842G, C28005T
and
C1601T, T4654C, T7633C

**Comment by aviczhl2** [comment]
10 seqs now.

**Comment by aviczhl2** [comment]
13 seqs now

**Comment by FedeGueli** [comment]
> 13 seqs now

I think now S:P174S could be removed from the defining cause 4 of the samples belonging to this lineage have not it:
<img width="1167" alt="Screenshot 2024-01-11 alle 10 14 16" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ab507a3d-2368-448f-89d8-45814f912da9">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2f005_fb05a0.json?label=id:node_6819599

The query finds all 13 sequences tough.

**Comment by aviczhl2** [comment]
+1 UK

**Comment by aviczhl2** [comment]
17 seqs now

**Comment by aviczhl2** [comment]
25 seqs now.

**Comment by FedeGueli** [comment]
Please propose it

**Comment by aviczhl2** [comment]
Suggest to change query to A7842G,C1601T,A8633G,C897A,  which finds 27.

**Comment by FedeGueli** [comment]
> Suggest to change query to A7842G,C1601T,A8633G,C897A, which finds 27.

Thank you! added to the issue,

**Comment by FedeGueli** [comment]
Now designated XDT via https://github.com/cov-lineages/pango-designation/commit/48ee76de3744ed1b8ddf569a992d15638f45ac7d

**Comment by Over-There-Is** [comment]
BA.2.86.4> **A8633G**> **T5767C**(UK 5, Luxembourg 2)
GK.1> C5173T, C5724T, C7858T, **T25496C**, **G29778A**> T23633C> **G27014A** (Belgium 2, France 1)
C1601T, T4654C, T7633C, C9661T, A19326G are private.

Interestingly, A19326G is also the only private mutation of XBB. But due to the breakpoint, it could not

**Comment by JosetteSchoenma** [comment]
> BA.2.86.4> **A8633G**> **T5767C**(UK 5, Luxembourg 2)
> GK.1> C5173T, C5724T, C7858T, **T25496C**, **G29778A**> T23633C> **G27014A** (Belgium 2, France 1)
> C1601T, T4654C, T7633C, C9661T, A19326G are private.
> 
> Interestingly, A19326G is also the only private mutation of XBB. But due to the breakpoint, it could not be inherited from GK.1.

@Over-There-Is I named the private mutation in the pango-designation issue.
https://github.com/cov-lineages/pango-designation/issues/2485
