### ISSUE TITLE
New EG.5.1.1-Flip lineage(78 seqs,  9 countries, 1,5% Finland, 2% Lithuania) and its sub-branch of S:G184S (19 seqs, 5 countries) displaying an insertion TTT resulting in Orf8:107F

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1186]
There is a new EG.5.1.1-Flip lineage not in #537, and seems fast growing now. 

EG.5.1.1->T14988C, A23014T->C1471T->C12823T->G25459T,G22927T(Orf3a:A23S,S:L455F), ins28214TTT?(or T or TT )

GISAID query: C12823,G25459, C1471,C29625T
No. of seqs: 58(Denmark 2 Finland 28 France 4 Lithuania 13 Netherlands 3 Sweden 8)

16/657 of Finland 12-15 batch, 11/326 of Lithuania 12-4 batch

Sub-lineage of S:G184S: >T16456C,G22112A(Orf1b:S997P,S:G184S)

GISAID query: C12823T,G22112,G25459,16456
No. of seqs: 13(Lituania 4 France 2 Netherlands 3 Sweden 4)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice110_genome_260a3_fb0a80.json?label=id:node_3442213)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ea0802ee-461a-44ab-aa85-f2fd7fbbea49)

**Comment by FedeGueli** [comment]
Many sequences of this sublineage from different countries display a weird insertion of TTT or TT in Orf8:107 , 
the ones with TT have a frameshift while the oens with TTT have Orf8:ins107F
![Schermata 2023-12-18 alle 09 50 02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a5515fb4-37f0-463a-bcbd-fbbc0a29375c)

**Comment by FedeGueli** [comment]
CovSpectrum sees the insertion in 20 out of 35 sequences with the following differences:
ins_28214:TT (10 seqs)• ins_28214:TTT (6 seqs)• ins_28214:TTTT (2 seqs)• ins_28214:T (1 seqs)• ins_28214:TTTTTN (1 seqs) 

![Schermata 2023-12-18 alle 09 59 29](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/34533e4e-41de-47aa-8074-92301856039d)

**Comment by FedeGueli** [comment]
cc @thomasppeacock @ryhisner @corneliusroemer could you take a look please?

**Comment by FedeGueli** [comment]
If i put the sequences qith the insertion on the tree they are scattered over many branches so very likely it is present in every sequence of this sublineage: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_392b3_dc40.json?c=userOrOld&label=id:node_3442857
![Schermata 2023-12-18 alle 10 17 50](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b8f3797e-c33b-4508-a076-e30b0d1727b3)

**Comment by aviczhl2** [comment]
> Many sequences of this sublineage from different countries display a weird insertion of TTT or TT in Orf8:107

As Orf8 is truncated it can be TT or T or other forms too.

**Comment by aviczhl2** [comment]
Main branch: 75, USA, Poland, 14/435 in Lithuania 12-21 batch, still 3.5%

G184S branch is 19 seqs and in USA.

**Comment by FedeGueli** [comment]
Ples propose once reaches 100. it has had very fast bumps still prefer to see a cleare pattern but it is not slow.

**Comment by aviczhl2** [comment]
78, UK for main branch

**Comment by ryhisner** [comment]
Comes right where there's already a stretch of five Ts in a row, which is usually how these things happen. I'm noticing more of these lately. There have been a few TCT insertions at S:254-255, where there are already two TCTs in a row. 
<img width="1171" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/b07ff170-335c-4652-9b5e-d48471038fea">

**Comment by ryhisner** [comment]
Ah, dang, I just realized this is the explanation for XBC's ORF1b:814D insertion (ins_25909:GAT). There are two GATs in a row there already, so this another one of those RdRp-stutter insertions. 
<img width="1116" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/8d2f4dc7-9bdb-4e31-b799-37ec96617de5">

**Comment by FedeGueli** [comment]
> Ah, dang, I just realized this is the explanation for XBC's ORF1b:814D insertion (ins_25909:GAT). There are two GATs in a row there already, so this another one of those RdRp-stutter insertions. <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/33738461/293109991-8d2f4dc7-9bdb-4e31-b799-37ec96617de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTc5NTksIm5iZiI6MTcwMzc1NzY1OSwicGF0aCI6Ii8zMzczODQ2MS8yOTMxMDk5OTEtOGQyZjRkYzctOWJkYi00ZTMxLWI3OTktMzdlYzk2NjE3ZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEwMDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMzZhZTA0OTEyYjQ3ZWNiZDY5NjFlMTgxMDMzMTRlNjUyMmFmMDIwZDUzYjM0NjAzYzQ3MGNjMWE2YTZkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kdKaiuDk764Q3vVNVkIMKOSW8GBtSSy5l3lwfVwuZUY">

Thanks Ryan please add this to the original XBC issue on Pango!

**Comment by FedeGueli** [comment]
@aviczhl2 propose itclearly still growing better letting Cornelius know about it.

**Comment by FedeGueli** [comment]
Updated prevalence after Nov 20

**Comment by FedeGueli** [comment]
please propose it.
