### ISSUE TITLE
JN.1+S:S408N(9 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1190]
JN.1+C5812T,C10833T,C21302T, C21304A, G21305A, G22785A(together with A22786C forms a 2-nuc mutation S:408R->S->N)

Orf1a:A3523V
Orf1b:P2612L, R2613S, S2614N
S:S408N

GISAID query: C5812T,C10833T,G22785A
No. of seqs: 4(USA)

First: EPI_ISL_18554172, 2023-11-5
Latest: EPI_ISL_18637289, 2023-11-28

Usher places it on a messy hyper-flip-flop branch under JN.1.1  @AngieHinrichs
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice21_genome_14328_e1780.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6fb79b65-6893-4add-b16d-a02a32e6c51a)

**Comment by FedeGueli** [comment]
Great i was tracking it too!

**Comment by FedeGueli** [comment]
Same XBB.1.22.1 preferences for JN.1

**Comment by AngieHinrichs** [comment]
It's pulled in to that branch by the old 21302,21304,21305 recurrent thing that I've needed to mask elsewhere -- I'll mask that in BA.2.86 too.

**Comment by FedeGueli** [comment]
+1 Minnesota.

**Comment by aviczhl2** [comment]
No new seqs
