### ISSUE TITLE
New EG.5.1.1 Flip lineage with N:S37P and S:Q183G (2 nucs) spreading in south-eastern Asia  (88 Seqs - 10 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1192]
I checked if anyone proposed this but i didnt find it obviously if i wrongoed smtg please let me know, but this seems  enough different to deserve a proposal and a rapid review.

Defining mutations:

EG.5.1.1 >> N:S37P (T28382C )> S:L455F (G22927T) > T12022A >P3504L ( C10776T) >S:Q183E>G (A22110G)  

Query: C10776T,A22110G, T12022A 

Countries: 8
Samples: 55 
First Singapore: 2023-09-11
Last: Malaysia 2023-12-05

IDs: EPI_ISL_18376847, EPI_ISL_18397300, EPI_ISL_18397358,
EPI_ISL_18428537, EPI_ISL_18428602, EPI_ISL_18444929,
EPI_ISL_18445009, EPI_ISL_18445153, EPI_ISL_18473484,
EPI_ISL_18473494, EPI_ISL_18473517, EPI_ISL_18473531,
EPI_ISL_18475548, EPI_ISL_18520854, EPI_ISL_18543059,
EPI_ISL_18544084, EPI_ISL_18544566, EPI_ISL_18544817,
EPI_ISL_18561683, EPI_ISL_18561890, EPI_ISL_18561900,
EPI_ISL_18561902, EPI_ISL_18562050, EPI_ISL_18562598,
EPI_ISL_18565835, EPI_ISL_18566403, EPI_ISL_18566516,
EPI_ISL_18566779, EPI_ISL_18580678, EPI_ISL_18583719,
EPI_ISL_18590058, EPI_ISL_18590278, EPI_ISL_18590315,
EPI_ISL_18590344, EPI_ISL_18590371, EPI_ISL_18591675,
EPI_ISL_18592186, EPI_ISL_18604525, EPI_ISL_18604615,
EPI_ISL_18604646, EPI_ISL_18604947, EPI_ISL_18604977,
EPI_ISL_18604979, EPI_ISL_18605044, EPI_ISL_18611436,
EPI_ISL_18611523, EPI_ISL_18611639, EPI_ISL_18611800,
EPI_ISL_18620751, EPI_ISL_18640741, EPI_ISL_18650499,
EPI_ISL_18651547, EPI_ISL_18651597, EPI_ISL_18651872-18651873,

Tree:
![Schermata 2023-12-19 alle 10 31 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d9ed6f70-9747-4607-a0a1-004a1b2a506b)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5fb73_15e6b0.json?label=id:node_3463225

**Comment by HynnSpylor** [comment]
Great catch!
but the title should be N:S37P not S:N37P

**Comment by FedeGueli** [comment]
> Great catch! but the title should be N:S37P not S:N37P

ahahah thank you!! i flipped protein and AA!

**Comment by FedeGueli** [comment]
64 now

**Comment by FedeGueli** [comment]
68, last three samples from three different australian states

**Comment by FedeGueli** [comment]
74 , please note that in Australia it reached 5 different states and New Zealand  ping @corneliusroemer

**Comment by FedeGueli** [comment]
80 now most recent sample collected in Japan in January

**Comment by FedeGueli** [comment]
83 with three samples in January from two continents

**Comment by FedeGueli** [comment]
slowing down. next to be closed
