### ISSUE TITLE
New JN.1 sublineage with S:K444R ( 6 Seqs England, Netherlands )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1194]
I was tracking since last week a sublineage of JN.1 with S:K444R, now it grew to 6 in to countries so i m proposing it.

Defining mutations:
JN.1 > G17562T > S:K444R (A22893G), C26873T

Query: A22893G, C26873T,G17562T

Samples : 6 ( Eng, Ndl)
First: Netherlands 2023-11-12
Last: England 2023-12-05

IDs:
EPI_ISL_18576850, EPI_ISL_18592137, EPI_ISL_18635523,
EPI_ISL_18640248, EPI_ISL_18640463, EPI_ISL_18641346

Tree:
![Schermata 2023-12-19 alle 12 15 46](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e93ee66a-8279-4d0b-8e2a-087ef18b38d4)
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3590f_17a760.json?c=userOrOld&label=id:node_4466420

**Comment by krosa1910** [comment]
K444R+N450D+L452M WAS a good combo in BA.2.3.20*, and I always thought it to be foreshadowing BA.2.86*, thus similar combo (changing M to R in 452) could also be good.

**Comment by FedeGueli** [comment]
cllosing this
