### ISSUE TITLE
FD.5.1 with ORF1b:Q2635R (nsp16_Q238R), ORF1a:N267S (nsp2_N87S), ORF1a:M1083I (nsp3_M265I) and S:L455F (14 seqs, USA, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1197]
**Defining Mutations:** `FD.5.1` > `T21369C, A21371G(ORF1b:Q2635R)` > `T23428C(S:V622V)` > `A1065G(ORF1a:N267S)` > `T9931C` > `G3514A(ORF1a:M1083I), C3787T` > `G23236A(S:K558K)` > `G22927T(S:L455F)`
**Query:** `A1065G, T9931C, G22927T`
**Earliest seq:** 2023-09-27 (`EPI_ISL_18394075`, California, USA)
**Latest seq:** 2023-11-25 (`EPI_ISL_18655586`, Colorado, USA)
**Sampled Countries:** USA (8: CO/6; CA; TX)

<details><summary>Genomes: </summary>

`EPI_ISL_18394075, EPI_ISL_18638060, EPI_ISL_18654918, EPI_ISL_18655586, EPI_ISL_18656139, EPI_ISL_18656876, EPI_ISL_18657211, EPI_ISL_18657301`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38848_2a2d30.json?label=id:node_3959894
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/52bba5b4-04b8-4ec9-aa17-4022026dc6d1)

---

There seems to be another cluster from Peru, which follows:
`FD.5.1` > `C4890T(ORF1a:T1542I), A8557G` > _`T26270C_rev(E:I9T_rev)`_ > `G3896A(ORF1a:V1211I), C6539T(ORF1a:H2092Y), T10135C, T10816A, A15861C(ORF1b:K798N), G22927T(S:L455F), C24058T(S:G832G)` [Query: `C4890T, G15957T, G22927T`, 2 seqs, 01/05]

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_2b611_cc7370.json?label=id:node_4000728
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e2c4ec29-60b6-4dba-b9f6-78ab97b3c076)

**Comment by FedeGueli** [comment]
10 now only 1 from December tough

**Comment by FedeGueli** [comment]
4 sequences from December coming from. 3 different places. better kept it monitored

**Comment by FedeGueli** [comment]
Dead
