### ISSUE TITLE
GK.1.1.1 (Orf9b:S50L) with ORF1b:A647S (nsp12_A656S), S:F157L and S:N450D (43 seqs, 6 countries) likely emerged in Argentina

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1199]
**Defining Mutations:** `GK.1.1.1` > `G15406T(ORF1b:A647S)` > `T8761C, C22033A(S:F157L)` > `A22910G(S:N450D)`
**Query:** `T8761C, G15406T, A22910G` _OR_ `T8761C, G15406T, C22033A` in case of the `N450D` dropout
**Earliest seq:** 2023-10-08 (`EPI_ISL_18445782`, Louisiana, USA)
**Latest seq:** 2023-12-05 (`EPI_ISL_18644941`, New York, USA)
**Sampled Countries:** USA (13: LA/6; NY/3; CA; IL; MN; NJ), Argentina (5), Switzerland (3), Austria (2), UK (1: SC)

<details><summary>Genomes: </summary>

`EPI_ISL_18445782, EPI_ISL_18445785, EPI_ISL_18485433, EPI_ISL_18486058, EPI_ISL_18497614, EPI_ISL_18529004, EPI_ISL_18545716, EPI_ISL_18546316, EPI_ISL_18547089, EPI_ISL_18596891, EPI_ISL_18600764, EPI_ISL_18606112, EPI_ISL_18608861-18608863, EPI_ISL_18622126, EPI_ISL_18622519, EPI_ISL_18644941, EPI_ISL_18654755-18654757, EPI_ISL_18654781, EPI_ISL_18654789, EPI_ISL_18656996`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13683_2d2010.json?label=id:node_3704021
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/52dced63-c134-4ec8-a719-5478ba402ee2)

**Trivia:**
- Although displayed on UShER tree as 2 sub-branches, `S:N450D` could be part of the mini-saltation together with `S:F157L`, the outliers all happened to have Ns around spike_439-520:
```
USA/LA-EVTL20440/2023|EPI_ISL_18445787|2023-10-11
USA/LA-EVTL20474/2023|EPI_ISL_18470209|2023-10-17
USA/LA-EVTL20472/2023|EPI_ISL_18470207|2023-10-18
USA/LA-EVTL20468/2023|EPI_ISL_18470206|2023-10-23
```
![out](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3ebc3f8b-d239-4574-93ac-b4cac08ac505)

**Comment by FedeGueli** [comment]
Great catch thx

**Comment by FedeGueli** [comment]
GK.1.1.1 defining is Orf9b:S50L , @ryhisner i think looked at it in depth.

**Comment by FedeGueli** [comment]
for the split already asked to Angie.

**Comment by FedeGueli** [comment]
It is very likely this emerged in Argentina

**Comment by FedeGueli** [comment]
propose when it gets 50

**Comment by aviczhl2** [comment]
57 now
