### ISSUE TITLE
XBB.1.5.15 Sublineage With S:484S, ORF1a:V3976I - 36 Sequences (USA)

### ISSUE THREAD

**Issue by plomano** [sars-cov-2-variants/lineage-proposals#12]
### **Description**
**Sublineage of:** XBB.1.5.15
**Earliest Sequence:** 2023-02-13, USA - California - EPI_ISL_17161166
**Latest Sequence:** 2023-05-08, USA - Washington - EPI_ISL_17706336
**Countries Circulating:** USA (36)
**Number of Sequences:** 36
**GISAID Query:** G15957T, G23012T, A23013C
**CovSpectrum Query:** G15957T & G23012T & A23013C

**Substitutions on Top of XBB.1.5.15:**
**Spike:** E484S
**ORF1a:** V3976
**Nucleotide:** G12191A, C442T, G15957T, G23012T

### USHER Tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_a7d6_6ef3f0.json?f_userOrOld=uploaded%20sample
![UO0002](https://user-images.githubusercontent.com/115512395/236652703-1e73da45-37f6-4b5e-9fca-cee23f019bce.jpg)

### Evidence

484S is an uncommon mutation, but it has been seen in small clusters. These sublineages typically have not been successful, however the Bloom Labs RBD Heatmaps show it increases ACE2 binding by a small amount (+0.05) and expression by a moderate amount (+0.14). While this mutation provides some escape, the increase in expression can potentially act as an evolutionary credit to add destabilizing mutations like 444* that further increase escape potential.

The downside is Omicron seems to highly prefer alanine in this position, with some limited success using arginine. Other amino acids at position 484 on an Omicron background have yet to create noticeable growth advantages.

I've posted this here since I don't believe it deserves to be posted in the main Pango designation repository, but at the same time it seems to have spread to a few different states and may be circulating at low levels in California.

<details>

EPI_ISL_17706336,

EPI_ISL_17467706,

EPI_ISL_17535352,

EPI_ISL_17642770,

EPI_ISL_17468038,

EPI_ISL_17706293,

EPI_ISL_17529837,

EPI_ISL_17514400,

EPI_ISL_17582264,

EPI_ISL_17529672,

EPI_ISL_17146965,

EPI_ISL_17643252,

EPI_ISL_17615808,

EPI_ISL_17642834,

EPI_ISL_17486460,

EPI_ISL_17430138,

EPI_ISL_17676345,

EPI_ISL_17467586,

EPI_ISL_17706021,

EPI_ISL_17651673,

EPI_ISL_17642785,

EPI_ISL_17384581,

EPI_ISL_17180394,

EPI_ISL_17467772,

EPI_ISL_17428334,

EPI_ISL_17412103,

EPI_ISL_17197160,

EPI_ISL_17582175,

EPI_ISL_17653668,

EPI_ISL_17637202,

EPI_ISL_17486900,

EPI_ISL_17161166,

EPI_ISL_17529728,

EPI_ISL_17420450,

EPI_ISL_17430067
<summary>Genomes:</summary></details>

**Comment by krosa1910** [comment]
My suggestion is that do not trust the calculator as a prediction rather than an explanation. For example, S:E484P is predicted to be "good" (at the same time of not changing binding or expression, it is the most powerful escape aa at 484 position, and is readily available after precursor E484A), but it only appeared 300 or so times, and its presence today would be virtually impossible.

**Comment by FedeGueli** [comment]
30 as today with the query you suggested. Could you find one with nuc mutations only?

**Comment by plomano** [comment]
I think G15957T, G23012T, A23013C should also catch them all, there's two I see with 484S on a different branch of XBB.1.5, but I believe they are unrelated.

**Comment by FedeGueli** [comment]
31 as today it appears very slow , due its circualtion in California that has a good sequencing intensity. if no seqs will come in   next week i ll close it

**Comment by FedeGueli** [comment]
32 as today

**Comment by FedeGueli** [comment]
I went here to close it but i found 4 more new seqs from California and Arizona. Please keep ur issue updated (36seqs)

**Comment by plomano** [comment]
> I went here to close it but i found 4 more new seqs from California and Arizona. Please keep ur issue updated (36seqs)

Sorry, will do! It seems slow but persistent.

**Comment by FedeGueli** [comment]
Luckily this one didnt grow further closing it for now.
