### ISSUE TITLE
XBB.1.9.1 sublineage with S:L179H and S:H681Y (23 seqs in South Korea)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#120]
Defining mutations: XBB.1.9.1>C1627T>G28817T (N:A182S), G18642A, T22098A (S:L179H), C23603T (S:H681Y)
GISAID query: Spike_L179H, Spike_P681Y
Earliest seq: 2023-03-29 (South Korea, EPI_ISL_17538540)
Most recent seq: 2023-05-02 (South Korea, EPI_ISL_17723243)
Countries detected: South Korea (22)

Usher tree: the only seq with S:H681Y & without S:L179H is low-coverage, as site S:179 is absent.
![QQ截图20230531233135](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/fd62053e-7130-4a8b-b245-6ef51320c7b3)
![QQ截图20230531232800](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/5be70d31-0603-4cd2-965f-a8cfef85f50f)

 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33396_7667b0.json
a well-known Spike mutation site with a rare mutation. S:P681Y samples are only 1400 since 2020, and it scattered in many lineages. S:L179H is even rarer as less than 50 seqs since 2020 (this branch accounts for near half of total)
Since it is only spread in South Korea with limited growth rate, I propose it here for tracking.

Genomes:
EPI_ISL_17528028, EPI_ISL_17538540, EPI_ISL_17563141, EPI_ISL_17563421, EPI_ISL_17647283, EPI_ISL_17691008-17691010,
EPI_ISL_17691380, EPI_ISL_17691418, EPI_ISL_17691420-17691423, EPI_ISL_17691426-17691431, EPI_ISL_17723177, EPI_ISL_17723243,

**Comment by FedeGueli** [comment]
one more sequence but it seems luckily slow.

**Comment by FedeGueli** [comment]
lets wait one more week for this one.

**Comment by HynnSpylor** [comment]
I think we can close it.
