### ISSUE TITLE
DV.7.1 / XBB.1.16 recombinant (19 seqs : Canada, California)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1200]
Breakpoint in RBD, 5' is DV.7.1, 3' is XBB.1.16
<img width="1606" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/c892566f-da7b-4950-9ac1-d4a08d226f8e">

<img width="1532" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/ac0216e5-f382-4309-bc14-79e9da62f641">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2b165_307a70.json?s=USA/CA-HLX-STM-KT4WHJEUM/2023%7CEPI_ISL_18637220%7C  
 

```
USA/CA-HLX-STM-KT4WHJEUM/2023|EPI_ISL_18637220|2023-11-08
Canada/ON-KHS-09109-v1/2023|EPI_ISL_18615089|2023-12-01
hCoV-19/Canada/ON-KHS-09290-v1/2023|EPI_ISL_18653743|2023-12-05
hCoV-19/Canada/ON-KHS-09425-v1/2023|EPI_ISL_18653838|2023-12-08
```

Query:  A28447G, C2227T,T28297C,A19886G ,-A2280C, -C10645T(edited)

**Comment by krosa1910** [comment]
Does it really appear to break exactly between FLip and T478R? That would be a surprise for how well that happened.

**Comment by krosa1910** [comment]
<img width="1130" alt="Screenshot 2023-12-21 at 3 49 02 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/1e1f2c53-f44e-45c3-a1fb-960b57f4f05b">
Do you think those earlier seqs are part of it? 
Link: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3a86c_3fa770.json?f_userOrOld=uploaded%20sample&gt=S.486P&label=id:node_1271561

**Comment by FedeGueli** [comment]
Interestingly the danish sample was proposed by @c19850727 back in August in https://github.com/sars-cov-2-variants/lineage-proposals/issues/718

**Comment by FedeGueli** [comment]
Added a query for this : A28447G, C2227T,T28297C,A19886G ,-A2280C, -C10645T

**Comment by aviczhl2** [comment]
+1 Canada. 

Shall be XBB.1.16.6 due to 23986?

**Comment by FedeGueli** [comment]
+1 Canada first from 2024

**Comment by Sinickle** [comment]
+4 from Canada today. 14 total now.

**Comment by FedeGueli** [comment]
15

**Comment by FedeGueli** [comment]
long time since last sample closing it

**Comment by DailyCovidCases** [comment]
No new seqs

**Comment by FedeGueli** [comment]
closing this
