### ISSUE TITLE
JG.3.2 sublineage defined by insertion S:212insERY (or 213RYR vs XBB ref) only [298, mostly Canada, US]

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1201]
There's a JG.3.2 sublineage in Canada that is defined by a Spike insertion S:212insERY only - there's no defining SNP compared to JG.3.2 unfortunately.

GISAID query: `ins214YRR`

It seems to be not doing too badly as it has popped up in multiple states in Canada. The location is one that's known for insertions, so not surprising.

There's nothing we can do here in terms of designation - all we can do is hope that there will be one SNP that has encompasses most of this lineage and designate that were we to designate.

It's also been sequenced in the US twice

<img width="1766" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/760695f9-f8e5-48e7-bde5-2fc11925f9a2">

Covspectrum: ins_S:212:ERY (Edited)

**Comment by ryhisner** [comment]
This is up to 77 sequences and has been found in 5 different US states and 5 different Canadian provinces. The Usher tree is a total mess though. They're scattered all over the place.

**Comment by FedeGueli** [comment]
and pls pay attention to this: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&aaInsertions1=ins_S%3A212%3AERY&analysisMode=CompareToBaseline& 
Ok biased by Canada and Minnesota high sequencing intensity but still..

**Comment by FedeGueli** [comment]
132 now , fast maybe due to canadian targeted sequencing: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&aaInsertions1=ins_S%3A212%3AERY&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
156 @corneliusroemer this should be designated

**Comment by ryhisner** [comment]
Four sequences from Manitoba, Canada, from this lineage with S:H52Y were uploaded today but with collection dates from late November. Usher apparently masks this mutation, so it doesn't show up on the tree. EPI_ISL_18822538, EPI_ISL_18822547-18822548, EPI_ISL_18822559

**Comment by FedeGueli** [comment]
181 now

**Comment by FedeGueli** [comment]
201 now

**Comment by JosetteSchoenma** [comment]
This seems to still be growing in Canada, despite JN.1 being over 90%.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/480240bc-392d-4390-84af-697d06663563)
250 now while searching GISAID with ins22204TACAGGAGG. 246 with ins214YRR.

**Comment by FedeGueli** [comment]
> This seems to still be growing in Canada, despite JN.1 being over 90%. ![image](https://private-user-images.githubusercontent.com/94831035/307580821-480240bc-392d-4390-84af-697d06663563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTQ4MDUsIm5iZiI6MTcwODg1NDUwNSwicGF0aCI6Ii85NDgzMTAzNS8zMDc1ODA4MjEtNDgwMjQwYmMtMzkyZC00MzkwLTg0YWYtNjk3ZDA2NjYzNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA5NDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NDczMDIyYzU2NmI3ODM5NWUwZmQxZmU5OGEyNDk5YzQwMzAyYjkzMzYwMWJmYzA2YTU3MzdiNmQ0YmNiZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9tD92eKUwXC0m5knm6JkQgiojq1uM_5a4Qhks6vLuGc) 250 now while searching GISAID with ins22204TACAGGAGG. 246 with ins214YRR.

Thx @JosetteSchoenma i m tracking since the start, unfortunately the insertion has no nucleotide associated with it , so pretty hard to designate. @corneliusroemer what could we do?

**Comment by FedeGueli** [comment]
@corneliusroemer @JosetteSchoenma noticed that both CovSpectrum and Nextclade read the insertion as S:V213R could be this. a way to designate it?

**Comment by FedeGueli** [comment]
254

**Comment by aviczhl2** [comment]
261 now.

**Comment by aviczhl2** [comment]
@AngieHinrichs
It seems that a lot seqs of this branch are not even categorized in JG.3.2 in usher despite all have S:N450D. There seems some bug in usher here. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3b30_d9f880.json?f_userOrOld=uploaded%20sample&label=id:node_3569723)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6348535e-2527-4241-80bf-22d520930cb1)

**Comment by AngieHinrichs** [comment]
Is it an UShER bug, or is it that sequences from Canada (and some from the US) tend to have A22910G along with so many other mutations that are shared with sequences from other countries that don't seem to have A22910G?  I will try the usual prune/re-optimize/re-place, but the large number of cases in which especially Canada seems to gain A22910G with many other different shared mutations makes me wonder if it could be an artifact, or if other countries tend to miss 22910.  I don't have time to look at alignments right now.

**Comment by aviczhl2** [comment]
> Is it an UShER bug, or is it that sequences from Canada (and some from the US) tend to have A22910G along with so many other mutations that are shared with sequences from other countries that don't seem to have A22910G? I will try the usual prune/re-optimize/re-place, but the large number of cases in which especially Canada seems to gain A22910G with many other different shared mutations makes me wonder if it could be an artifact, or if other countries tend to miss 22910. I don't have time to look at alignments right now.

They have to be after the A22910G because they also have the S:ins213RYR thing described in this repo.(not shown in usher)

**Comment by aviczhl2** [comment]
An S:A475V sub-branch of this appears. #1465.

**Comment by FedeGueli** [comment]
298 now

**Comment by DailyCovidCases** [comment]
No new seqs

**Comment by FedeGueli** [comment]
Dying or dead
