### ISSUE TITLE
Lineages with potentially large deletions masquerading as stretches of Ns

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1202]
Inspired by @cassiawag's work on large deletions in ORF7/8 often masquerading as stretches of Ns in assemblies rather than as deletions, I had a look through currently submitted sequences to see if I can find more examples.

@ryhisner has already pointed out that GW.5.1.1 seems to have a large ORF8 deletion.

I thought it might be useful to add further examples here. There's a potential for a simple tool to be written that would autodetect such suspicious stretches of Ns and be able to distinguish between amplicon dropout and deletions, e.g. by checking that the same stretch of N is observed in almost all sequences from a lineage and also from a number of labs/countries etc.

I found:
- GW.5.1.1: 27395-28246 - already known - but suspiciously identical with GE.1.2...
- GE.1.2: around 27395-28246, encompassing end of ORF6, ORF7a, ORF7b and into ORF8

I didn't expect them to have the same stretch - maybe these macro deletions are due to amplicon dropout in mostly English samples after all. Could be that there _is_ a real short indel that throws primers off in that region.

_______________
_Edited by mod_.:
Lineages spotted by community ( see comments below) :
 FW.1.1
JP.1.1
XBB.1.5.71 (50%)
EG.5.1.12

Edited : suggested query by @NkRMnZr :
>The trick is ins27384C search it in GISAID you will find all lineages with similar ORF6 stop codon and ORF7a start codon destroyer

**Comment by aviczhl2** [comment]
usher tree for FW.1.1 looks like GW.5.1.1, I guess it may have similar deletion.

**Comment by corneliusroemer** [comment]
I'm not sure Usher is helpful here as it completely ignores anything that happens in deletions/Ns. In both cases, there should be plenty of raw reads on SRA in case anyone wants to investigate what's going on - that should be the way to go.

**Comment by FedeGueli** [comment]
> usher tree for FW.1.1 looks like GW.5.1.1, I guess it may have similar deletion.

XBB.1.28 has already a frameshift at the start of ORf6

**Comment by FedeGueli** [comment]
@ryhisner found two more and going. Hope he will update here. Once updated i will add them to main text

**Comment by ryhisner** [comment]
About 50% of XBB.1.5.71 have the ORF7a-7b-8 deletion. 
**GISAID Query:** C21691T, A13953G, C281T, -del27796_27797, -G27915T, -C27807T (356 seq)
**Usher Tree:**https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/XBB.1.5.71_with_7a-7b-8_Deletion_356_seq.json?c=gt-ORF1ab_6&gmax=21555&gmin=266&label=id:node_3734774 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17275919, EPI_ISL_17328757, EPI_ISL_17344213,
EPI_ISL_17482742-17482743, EPI_ISL_17495423, EPI_ISL_17503819,
EPI_ISL_17503822, EPI_ISL_17503825, EPI_ISL_17503843,
EPI_ISL_17521521, EPI_ISL_17521597, EPI_ISL_17521638,
EPI_ISL_17521684, EPI_ISL_17521940, EPI_ISL_17535650,
EPI_ISL_17541225, EPI_ISL_17583470, EPI_ISL_17597811,
EPI_ISL_17602439, EPI_ISL_17630102, EPI_ISL_17635146,
EPI_ISL_17638065, EPI_ISL_17638566, EPI_ISL_17640093,
EPI_ISL_17640100, EPI_ISL_17640126, EPI_ISL_17640210,
EPI_ISL_17640212, EPI_ISL_17652482, EPI_ISL_17652495,
EPI_ISL_17652617, EPI_ISL_17667737, EPI_ISL_17678975,
EPI_ISL_17679012, EPI_ISL_17679034, EPI_ISL_17679058,
EPI_ISL_17679154, EPI_ISL_17679200, EPI_ISL_17679219,
EPI_ISL_17679313, EPI_ISL_17679414, EPI_ISL_17679425-17679426,
EPI_ISL_17679431-17679432, EPI_ISL_17679482, EPI_ISL_17679495,
EPI_ISL_17679548, EPI_ISL_17679564-17679565, EPI_ISL_17679623,
EPI_ISL_17679695, EPI_ISL_17679698, EPI_ISL_17679725,
EPI_ISL_17689903, EPI_ISL_17711708, EPI_ISL_17719151,
EPI_ISL_17721500, EPI_ISL_17722195, EPI_ISL_17722928,
EPI_ISL_17722939, EPI_ISL_17726162, EPI_ISL_17726423,
EPI_ISL_17728955, EPI_ISL_17728996, EPI_ISL_17729020,
EPI_ISL_17731327, EPI_ISL_17731337, EPI_ISL_17731361,
EPI_ISL_17731393, EPI_ISL_17731420, EPI_ISL_17731432,
EPI_ISL_17731443, EPI_ISL_17734970, EPI_ISL_17734982,
EPI_ISL_17734994, EPI_ISL_17735013, EPI_ISL_17743068,
EPI_ISL_17743083, EPI_ISL_17743111, EPI_ISL_17743121,
EPI_ISL_17743130, EPI_ISL_17761363, EPI_ISL_17761591,
EPI_ISL_17762447, EPI_ISL_17762470, EPI_ISL_17762488,
EPI_ISL_17766849, EPI_ISL_17780216, EPI_ISL_17780765,
EPI_ISL_17780775, EPI_ISL_17780782, EPI_ISL_17780893-17780894,
EPI_ISL_17781016, EPI_ISL_17781041, EPI_ISL_17781745,
EPI_ISL_17782323, EPI_ISL_17782865, EPI_ISL_17784488,
EPI_ISL_17785794, EPI_ISL_17786054, EPI_ISL_17786074,
EPI_ISL_17787140, EPI_ISL_17787183, EPI_ISL_17788547,
EPI_ISL_17788565, EPI_ISL_17788575, EPI_ISL_17788593,
EPI_ISL_17788607, EPI_ISL_17791774, EPI_ISL_17795926,
EPI_ISL_17795943, EPI_ISL_17795973, EPI_ISL_17797709,
EPI_ISL_17806702, EPI_ISL_17806704, EPI_ISL_17809632,
EPI_ISL_17811476, EPI_ISL_17812472, EPI_ISL_17814817,
EPI_ISL_17814821, EPI_ISL_17815103, EPI_ISL_17817716,
EPI_ISL_17817862, EPI_ISL_17820264, EPI_ISL_17820814-17820815,
EPI_ISL_17831246, EPI_ISL_17831280, EPI_ISL_17833516,
EPI_ISL_17833530, EPI_ISL_17837161, EPI_ISL_17837277,
EPI_ISL_17838514, EPI_ISL_17859227, EPI_ISL_17859241,
EPI_ISL_17859253, EPI_ISL_17859345, EPI_ISL_17859349,
EPI_ISL_17859360-17859361, EPI_ISL_17948429, EPI_ISL_17948441-17948442,
EPI_ISL_17948458, EPI_ISL_17948469, EPI_ISL_17948480,
EPI_ISL_17948487, EPI_ISL_17948490, EPI_ISL_17948518,
EPI_ISL_17948542, EPI_ISL_17948587, EPI_ISL_17948597,
EPI_ISL_17948636, EPI_ISL_17948643, EPI_ISL_17948652,
EPI_ISL_17949009, EPI_ISL_17949017, EPI_ISL_17949041-17949042,
EPI_ISL_17949053, EPI_ISL_17949071, EPI_ISL_17949077,
EPI_ISL_17949103, EPI_ISL_17949116, EPI_ISL_17949239,
EPI_ISL_17949251, EPI_ISL_17949256, EPI_ISL_17949261,
EPI_ISL_17949270, EPI_ISL_17949312, EPI_ISL_17949555,
EPI_ISL_17949558, EPI_ISL_17949589, EPI_ISL_17949613,
EPI_ISL_17949616, EPI_ISL_17949622, EPI_ISL_17949625,
EPI_ISL_17949798, EPI_ISL_17949800, EPI_ISL_17949809,
EPI_ISL_17952135, EPI_ISL_17958936, EPI_ISL_17959682,
EPI_ISL_17969381, EPI_ISL_17972245, EPI_ISL_17973563,
EPI_ISL_17975015, EPI_ISL_17975284, EPI_ISL_17975650-17975651,
EPI_ISL_17978341, EPI_ISL_17978901-17978902, EPI_ISL_17980561,
EPI_ISL_17985275, EPI_ISL_17988475, EPI_ISL_17989438,
EPI_ISL_17989440, EPI_ISL_17989446, EPI_ISL_17989453,
EPI_ISL_17989472, EPI_ISL_17989474, EPI_ISL_17989496-17989497,
EPI_ISL_17989512, EPI_ISL_17989524-17989525, EPI_ISL_17989925-17989933,
EPI_ISL_17990142, EPI_ISL_17995559, EPI_ISL_17995978,
EPI_ISL_17995997, EPI_ISL_18000668-18000669, EPI_ISL_18000672,
EPI_ISL_18000801, EPI_ISL_18008612, EPI_ISL_18010136,
EPI_ISL_18010435, EPI_ISL_18010440, EPI_ISL_18010448,
EPI_ISL_18015691, EPI_ISL_18015751, EPI_ISL_18036910,
EPI_ISL_18042134, EPI_ISL_18042201, EPI_ISL_18042252,
EPI_ISL_18042354, EPI_ISL_18043947, EPI_ISL_18044152,
EPI_ISL_18052041, EPI_ISL_18052753, EPI_ISL_18056764,
EPI_ISL_18062679, EPI_ISL_18072059, EPI_ISL_18072756,
EPI_ISL_18072809, EPI_ISL_18075549, EPI_ISL_18083478,
EPI_ISL_18094246, EPI_ISL_18094438, EPI_ISL_18094823,
EPI_ISL_18094835, EPI_ISL_18094856, EPI_ISL_18097904,
EPI_ISL_18097957, EPI_ISL_18098234, EPI_ISL_18098238,
EPI_ISL_18098325, EPI_ISL_18112439, EPI_ISL_18112442,
EPI_ISL_18112527, EPI_ISL_18112548, EPI_ISL_18112710,
EPI_ISL_18113451, EPI_ISL_18118140, EPI_ISL_18118155,
EPI_ISL_18118170, EPI_ISL_18118175, EPI_ISL_18118179,
EPI_ISL_18118183-18118184, EPI_ISL_18118192, EPI_ISL_18118208,
EPI_ISL_18118212, EPI_ISL_18118297, EPI_ISL_18118309,
EPI_ISL_18118529, EPI_ISL_18123287, EPI_ISL_18123296,
EPI_ISL_18123301, EPI_ISL_18123311, EPI_ISL_18123324,
EPI_ISL_18124195, EPI_ISL_18130011, EPI_ISL_18130329,
EPI_ISL_18134774, EPI_ISL_18135346, EPI_ISL_18139391,
EPI_ISL_18160042, EPI_ISL_18167872, EPI_ISL_18168039,
EPI_ISL_18210500, EPI_ISL_18210697-18210698, EPI_ISL_18216095,
EPI_ISL_18220503, EPI_ISL_18226748, EPI_ISL_18233654-18233656,
EPI_ISL_18233899-18233900, EPI_ISL_18234003, EPI_ISL_18234026-18234027,
EPI_ISL_18234032, EPI_ISL_18234152, EPI_ISL_18234155,
EPI_ISL_18234158, EPI_ISL_18234164, EPI_ISL_18238228,
EPI_ISL_18244368-18244369, EPI_ISL_18248605, EPI_ISL_18255132,
EPI_ISL_18256027, EPI_ISL_18257895, EPI_ISL_18264885-18264886,
EPI_ISL_18265114, EPI_ISL_18271257, EPI_ISL_18271412,
EPI_ISL_18273548-18273549, EPI_ISL_18275006, EPI_ISL_18285485,
EPI_ISL_18285605, EPI_ISL_18286492, EPI_ISL_18292038-18292039,
EPI_ISL_18300238, EPI_ISL_18301303, EPI_ISL_18308478,
EPI_ISL_18308531, EPI_ISL_18308641, EPI_ISL_18315859,
EPI_ISL_18319955, EPI_ISL_18331339, EPI_ISL_18332413,
EPI_ISL_18356153, EPI_ISL_18358181, EPI_ISL_18391239,
EPI_ISL_18419440, EPI_ISL_18425282, EPI_ISL_18429836,
EPI_ISL_18457808, EPI_ISL_18489829, EPI_ISL_18515451,
EPI_ISL_18515526, EPI_ISL_18541998, EPI_ISL_18549702,
EPI_ISL_18552812, EPI_ISL_18567527, EPI_ISL_18684066,
</details>



JP.1.1 (CH.1.1.31.1.1), which is still circulating in South Africa (3/19 sequences collected in December) and also has shown up in England and Wales this month, also has the ORF7a-7b-8 deletion. 
**GISAID Query:** G7059A, G21668A, C5183T, -G27459T, -C27807T
**Usher Tree:** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JP.1.1__7a-7b-8_Deletion.json?c=gt-nuc_21668&gmax=22668&gmin=20668&label=id:node_4351062
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17859330, EPI_ISL_18125226-18125227, EPI_ISL_18125236, EPI_ISL_18125240, EPI_ISL_18284171, EPI_ISL_18341854, EPI_ISL_18341856, EPI_ISL_18341865, EPI_ISL_18341867, EPI_ISL_18341869, EPI_ISL_18386573, EPI_ISL_18407195, EPI_ISL_18407207, EPI_ISL_18412376, EPI_ISL_18536151, EPI_ISL_18553248, EPI_ISL_18553260, EPI_ISL_18553262, EPI_ISL_18566817, EPI_ISL_18585428, EPI_ISL_18607115, EPI_ISL_18607126, EPI_ISL_18607145, EPI_ISL_18612213, EPI_ISL_18669267, EPI_ISL_18673303, EPI_ISL_18684741, EPI_ISL_18688579, EPI_ISL_18688622, EPI_ISL_18697901, EPI_ISL_18697914-18697915
</details>


There's a branch of EG.5.1, mostly in Japan, that seems to have the last half of ORF7b and ORF8 deleted. Probably about to go extinct though. The Japan sequences actually may get the deletion exactly right, but Nextclade can't read them. I recorded a bunch of info on that branch a couple months ago, but I'm not sure if I can find it again. 

I think there are a couple others as well. I'll see if I can find them.

**Comment by ryhisner** [comment]
EG.5.1.12 with something resembling an ORF7b:26-ORF8:122 deletion
**GISAID Query**: C6543T, C28311T, A16878T, C2334T, C28909T, -G27915, -G28209C, -C28146T
**Usher Tree:** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/EG.5.1.12_ORF7b-ORF8_Deletion.json?c=gt-nuc_6543&gmax=7543&gmin=5543&label=id:node_3436821
<details>
<summary>Genomes</summary>
EPI_ISL_17969765, EPI_ISL_17970318, EPI_ISL_17970508,
EPI_ISL_18047263, EPI_ISL_18047620, EPI_ISL_18067826,
EPI_ISL_18068029, EPI_ISL_18071971, EPI_ISL_18109039,
EPI_ISL_18116822, EPI_ISL_18117104, EPI_ISL_18117474,
EPI_ISL_18117732, EPI_ISL_18117877, EPI_ISL_18117946,
EPI_ISL_18124420, EPI_ISL_18137096, EPI_ISL_18139529,
EPI_ISL_18139670, EPI_ISL_18139800, EPI_ISL_18139899,
EPI_ISL_18140493, EPI_ISL_18145142, EPI_ISL_18161374,
EPI_ISL_18164977, EPI_ISL_18165914, EPI_ISL_18168559,
EPI_ISL_18208214, EPI_ISL_18209281, EPI_ISL_18209711,
EPI_ISL_18213591, EPI_ISL_18213656, EPI_ISL_18213912,
EPI_ISL_18214012, EPI_ISL_18214384, EPI_ISL_18218139,
EPI_ISL_18218318, EPI_ISL_18227051, EPI_ISL_18235855,
EPI_ISL_18235892, EPI_ISL_18235967, EPI_ISL_18236941,
EPI_ISL_18237037, EPI_ISL_18239483, EPI_ISL_18243129,
EPI_ISL_18243391, EPI_ISL_18243400, EPI_ISL_18246641,
EPI_ISL_18247763, EPI_ISL_18254845, EPI_ISL_18254962,
EPI_ISL_18259587, EPI_ISL_18260446, EPI_ISL_18261393,
EPI_ISL_18271990, EPI_ISL_18272273, EPI_ISL_18279079,
EPI_ISL_18280059, EPI_ISL_18281390, EPI_ISL_18284849,
EPI_ISL_18285198, EPI_ISL_18285348, EPI_ISL_18285410,
EPI_ISL_18293036, EPI_ISL_18293096, EPI_ISL_18293111,
EPI_ISL_18293124, EPI_ISL_18293202, EPI_ISL_18293362,
EPI_ISL_18293494, EPI_ISL_18293535, EPI_ISL_18293572,
EPI_ISL_18293575, EPI_ISL_18293704, EPI_ISL_18294156,
EPI_ISL_18300341, EPI_ISL_18300765, EPI_ISL_18305354,
EPI_ISL_18306066, EPI_ISL_18306487, EPI_ISL_18306524,
EPI_ISL_18307291, EPI_ISL_18307305, EPI_ISL_18307307,
EPI_ISL_18312392, EPI_ISL_18312430, EPI_ISL_18312516,
EPI_ISL_18312578, EPI_ISL_18312779, EPI_ISL_18313325,
EPI_ISL_18313558, EPI_ISL_18315526, EPI_ISL_18324578,
EPI_ISL_18327728, EPI_ISL_18327764, EPI_ISL_18330993,
EPI_ISL_18330999, EPI_ISL_18331041, EPI_ISL_18342031,
EPI_ISL_18346697, EPI_ISL_18346911, EPI_ISL_18347779,
EPI_ISL_18350065, EPI_ISL_18353958, EPI_ISL_18354013,
EPI_ISL_18354317, EPI_ISL_18354602, EPI_ISL_18354652,
EPI_ISL_18354746, EPI_ISL_18355156-18355157, EPI_ISL_18359797,
EPI_ISL_18359858, EPI_ISL_18361083, EPI_ISL_18361891,
EPI_ISL_18362992, EPI_ISL_18370765, EPI_ISL_18370818,
EPI_ISL_18370964, EPI_ISL_18371329, EPI_ISL_18372666,
EPI_ISL_18376281, EPI_ISL_18376406, EPI_ISL_18376973,
EPI_ISL_18382676, EPI_ISL_18384708, EPI_ISL_18385688,
EPI_ISL_18386752, EPI_ISL_18387158, EPI_ISL_18390797,
EPI_ISL_18392741, EPI_ISL_18402227, EPI_ISL_18402307,
EPI_ISL_18402549, EPI_ISL_18402590, EPI_ISL_18408832,
EPI_ISL_18410327, EPI_ISL_18411769, EPI_ISL_18413614,
EPI_ISL_18415356, EPI_ISL_18415363, EPI_ISL_18417943,
EPI_ISL_18418070, EPI_ISL_18418092, EPI_ISL_18419599,
EPI_ISL_18428833, EPI_ISL_18430423, EPI_ISL_18432559,
EPI_ISL_18432648, EPI_ISL_18432691, EPI_ISL_18432702,
EPI_ISL_18438906, EPI_ISL_18438930, EPI_ISL_18439456,
EPI_ISL_18442648, EPI_ISL_18442693, EPI_ISL_18444464,
EPI_ISL_18449219, EPI_ISL_18449240, EPI_ISL_18449280,
EPI_ISL_18454509, EPI_ISL_18466243-18466244, EPI_ISL_18488519,
EPI_ISL_18488937, EPI_ISL_18498897, EPI_ISL_18498998,
EPI_ISL_18499032, EPI_ISL_18503469, EPI_ISL_18503754,
EPI_ISL_18507084, EPI_ISL_18511618, EPI_ISL_18511650,
EPI_ISL_18512956, EPI_ISL_18520963, EPI_ISL_18522437,
EPI_ISL_18524368, EPI_ISL_18527050, EPI_ISL_18527159,
EPI_ISL_18527218, EPI_ISL_18538743, EPI_ISL_18538963,
EPI_ISL_18539184, EPI_ISL_18539459, EPI_ISL_18549781,
EPI_ISL_18556333, EPI_ISL_18556352, EPI_ISL_18556365,
EPI_ISL_18564158, EPI_ISL_18564235, EPI_ISL_18564615,
EPI_ISL_18566541, EPI_ISL_18570107, EPI_ISL_18581188,
EPI_ISL_18581354, EPI_ISL_18593263, EPI_ISL_18651685,
EPI_ISL_18666546, EPI_ISL_18667294, EPI_ISL_18687416,
</details>

Okay, so the ORF7b-ORF8 deletion is part of EG.5.1.12. Again, a lot of the Japanese sequences might get the deletion right. GISAID registers those sequences as having T27833A, T27835A, del27837_28261 in some cases, but at other times as del27831_28049, T28053C, C28054G, G28056A, del28059_28256.  

When I put one of the Japan sequences in BLAST, it looks like ∆27832-27885, ∆27896-28257. 27832 is the second nucleotide in ORF7b:26 while 28257 is the first nucleotide in the ORF8 stop codon, ORF8:122, and the last nucleotide before the core N/ORF9b core TRS (AAACGAAC). 

<img width="997" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a08159f1-2f2e-4565-a805-014276e3adca">

I think all these interpretations are more or less equivalent. ORF7b hits a stop codon pretty quickly and ORF9b/N gain a second TRS to go with the two overlapping ones they already have. In any case, this is a quickly disappearing lineage, but it might be worth documenting for the historical record.

**Comment by FedeGueli** [comment]
thank you Ryan!

**Comment by ryhisner** [comment]
There's a ~53-sequence branch of FY.1.2 with this deletion, including a 20-sequence branch with S:N481K and N:A267V that includes a recent sequence from a traveler from Columbia sequenced in the US (by Ginkgo Bozoworks, unfortunately, so bad quality). 

The S:N481K-N:A267V branch has 20 sequences, but only three of them are on GISAID, mostly from New York, USA. It seems one of the New York labs doesn't upload to GISAID. 13/20 sequences on this branch were collected in November or December. 

**Earliest sequence:** 2023-6-26 - Israel, EPI_ISL_17953535
**Most recent sequence:** 2023-12-21 - Colombia (Traveler to USA), EPI_ISL_18710009
**Continents circulating:** Asia (29), Europe (4), North America (2), South America (1)
**Countries circulating:** Israel (29), USA (2), Colombia (1—traveler to USA), England (1), Finland (1), Germany (1), Wales (1)
**Number of Sequences:** 36 (subtracting one Ginkgo Bozoworks pooled sample)
**GISAID Nucleotide Query:** G18811A, C14120T, A13947C, C4795T, A22161G, -del27795, -A21794C


**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/FY.1.2__7a-7b-8_Deletion__Usher_Tree.json?c=gt-nuc_4795&gmax=5795&gmin=3795&label=id:node_3170444

<img width="1479" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d452c716-3e7e-4ff6-836d-7d0c232d40a8">

**Wider View**
<img width="1008" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/256adfe3-a64b-4b77-9739-1099495e4f6a">

**S:N481K-N:A267V Branch (85% not on GISAID)**
<img width="1452" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/aaee786d-016d-41f3-a118-0e938a54fbf9">


**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17953535, EPI_ISL_18062570, EPI_ISL_18096858,
EPI_ISL_18096860, EPI_ISL_18096866, EPI_ISL_18097994,
EPI_ISL_18115865, EPI_ISL_18215498, EPI_ISL_18226749,
EPI_ISL_18228401, EPI_ISL_18246912, EPI_ISL_18246954,
EPI_ISL_18246975, EPI_ISL_18255382, EPI_ISL_18300242,
EPI_ISL_18313607, EPI_ISL_18313670, EPI_ISL_18330690,
EPI_ISL_18330706, EPI_ISL_18345517, EPI_ISL_18345674,
EPI_ISL_18374025, EPI_ISL_18374041, EPI_ISL_18417826,
EPI_ISL_18421210, EPI_ISL_18455048-18455049, EPI_ISL_18464854,
EPI_ISL_18519101, EPI_ISL_18560787, EPI_ISL_18561018,
EPI_ISL_18572329, EPI_ISL_18601883, EPI_ISL_18636467,
EPI_ISL_18661583, EPI_ISL_18710009
</details>

**Comment by FedeGueli** [comment]
@corneliusroemer new one , sibling of GE.1.2.1 but without 376S and the 478Rev, likely there was a common ancestor with it : https://github.com/sars-cov-2-variants/lineage-proposals/issues/1340

**Comment by FedeGueli** [comment]
@corneliusroemer @ryhisner spotted another one: JB.2 undesignated branch in South Africa
<img width="1256" alt="Screenshot 2024-01-30 alle 12 38 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3d382faf-f840-4c17-932b-005d6563c104">

**Comment by FedeGueli** [comment]
> @corneliusroemer new one , sibling of GE.1.2.1 but without 376S and the 478Rev, likely there was a common ancestor with it : #1340

Designated GE.1.2.2

**Comment by DailyCovidCases** [comment]
No new seqs

**Comment by FedeGueli** [comment]
> ins27384C

Only 12 samples so far with the large deletion in Orf7ab/8 on Jn.1 Backbone (USING THE QUERY BY @NkRMnZr )
EPI_ISL_18818052, EPI_ISL_18836042, EPI_ISL_18902167,
EPI_ISL_18910469, EPI_ISL_18931552, EPI_ISL_18932329,
EPI_ISL_18932331, EPI_ISL_18951356, EPI_ISL_18981826,
EPI_ISL_19095772, EPI_ISL_19136921, EPI_ISL_19175463,


Interestingly there are two from May both in fast lineages : 
LB.1 with S:S31del in Spain. Query: **ins27384C,t3565C,C19512T, A28993C**
and 
KP.3.2 without S:S31del in Canada. Query: **ins27384C,t3565C,G3871T,** 


cc @ryhisner did you spot any other?

**Comment by FedeGueli** [comment]
no recent lineage with it , apparently . closing this

**Comment by FedeGueli** [comment]
the new BA.3 Saltation seems to have the same pattern of GE.1.2 and GW.5.1.1 : https://github.com/cov-lineages/pango-designation/issues/2909
