### ISSUE TITLE
EG.5.1.6/XCR recombinant removed by usher(6 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1207]
I see all seqs being pruned by usher despite not having too much reversions, 2 are recently submitted but the other 3 were past seqs and still get removed.
Maybe better to highlight this recomb.
@AngieHinrichs

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/de3d0f33-b301-4d80-b1d4-25041758c132)

EG.5.1.6--XCR
Breakpoint between 18973 and 21717

Additional mutations: A1759G, C4999T, T6714C, G18972T,T25422C, 

Orf1a: V2150A
Orf1b:K1835N

C4999T, G18972T from an EG.5.1.6 branch.
A1759G,T6714C,T25422C are private mutations

GISAID query: T6714C,T25422C
No. of seq: 5(USA-CO,CA,SD)

First: EPI_ISL_18603100, CA,2023-10-4
Latest: EPI_ISL_18662544, SD, 2023-12-10

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1eca9_3d3f40.json?f_userOrOld=uploaded%20sample&label=id:node_11089666)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ca4c119e-55be-4236-a665-413f8edb5b00)

[usher for EG.5.1.6-donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1eca9_3d3f30.json?c=gt-nuc_4999,18972&gmax=19972&gmin=3999&label=id:node_3541706)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d833f094-949a-4878-96a2-a4be802f776d)

**Comment by AngieHinrichs** [comment]
> pruned by usher despite not having too much reversions

I see they don't have reversions when placed on the usher tree.  But nextclade (with data downloaded on Dec. 4th after the latest release) is placing them as 'recombinant' with 6 reversions, and nextclade's count is what I use for filtering.  I will add some exceptions for those IDs.

**Comment by aviczhl2** [comment]
> > pruned by usher despite not having too much reversions
> 
> I see they don't have reversions when placed on the usher tree. But nextclade (with data downloaded on Dec. 4th after the latest release) is placing them as 'recombinant' with 6 reversions, and nextclade's count is what I use for filtering. I will add some exceptions for those IDs.

Oh. So we shall not look at GISAID count but use nextclade reversion count? 
How to get these counts?

**Comment by FedeGueli** [comment]
Closing this for now.
