### ISSUE TITLE
XAY.1.1.1+ORF3a:L65F sublineage with S:D420N (6 seq. Italy, Luxembourg, Spain, Portugal, UK)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#121]
S:D420N and S:N460K were predicted to escape similar types of antibodies. S:D420N was growing in BA.5 but it was out-competed by S:N460K.
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/e3cfe3d5-533f-405c-abdf-f48cab21bf5c)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1*%26S%3AD420N&

Query: G22820A,C19441T

finds 6 sequences also another  one from Italy uploaded yesterday.
EPI_ISL_17470214, EPI_ISL_17615116, EPI_ISL_17633261,
EPI_ISL_17720236, EPI_ISL_17721921, EPI_ISL_17726266,

**Comment by oobb45729** [comment]
This is not the only subbranch of XAY.1.1.1 that gained S:D420N recently.
There are also three sequences with ORF1a:G519S and S:D420N in Germany (on the XAY.1.1.1+nuc:C8140T then S:T307I+ORF3a:P240S subbranch, within which there are several interesting sequences, including one with S:N460K).
![2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/81dbf03a-4668-4eb5-953d-1afec81c88df)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40d68_788ed0.json?c=gt-S_420,460&label=id:node_10210124
https://open.cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1*%26S%3AD420N&
https://open.cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1*%26S%3AN460K&

**Comment by FedeGueli** [comment]
![Schermata 2023-05-31 alle 22 32 14](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/23e4512e-f4b3-4829-8d7d-82ec9f5a6d6e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_403c9_7ad3c0.json?label=id:node_6217080

tree with the new sequence.

**Comment by HynnSpylor** [comment]
S:D420N may be a potential mutation by Cao (2023) (despite the research is based on XBB.1.5 RBD)
![Uploading QQ截图20230601120808.png…]()

**Comment by corneliusroemer** [comment]
This one also has an extra deletion S:144-

The one Italian missing the 420 has Ns there, this is an interesting lineage that could be transferred over to cov-lineages/pango-designation

**Comment by FedeGueli** [comment]
@oobb45729 please transfer this one to the main  page thx!

**Comment by FedeGueli** [comment]
> This is not the only subbranch of XAY.1.1.1 that gained S:D420N recently. There are also three sequences with ORF1a:G519S and S:D420N in Germany (on the XAY.1.1.1+nuc:C8140T then S:T307I+ORF3a:P240S subbranch, within which there are several interesting sequences, including one with S:N460K). ![2](https://user-images.githubusercontent.com/115189228/242367496-81dbf03a-4668-4eb5-953d-1afec81c88df.png) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40d68_788ed0.json?c=gt-S_420,460&label=id:node_10210124 https://open.cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1*%26S%3AD420N& https://open.cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1*%26S%3AN460K&

@oobb45729 spotted this one too please propose it , it has to be monitored.
