### ISSUE TITLE
JN.1 (BA.2.86.1.1) sublineage with 3-nuc mutation S:V445H->Q and ORF1a:T1004I (3 seqs in France, Israel) 

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1216]
Defining mutations: JN.1>C27371T (ORF6: P57L)>C3276T (ORF1a:T1004I), T22897A (S:V445H->Q)
GISAID query: C3276T, T22897A
Earliest seq: 2023-11-27 (France- EPI_ISL_18653068)
Most recent seq: 2023-12-07 (Israel- EPI_ISL_18673168)
Countries detected: France (1), Israel (1)

Usher Tree:
![联想截图_20231223002402](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/dd48d6c0-5d66-457b-9579-87707b903531)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3efe5_5ad2d0.json?c=gt-S_445

S:V445H is one of key mutations in BA.2.86* lineages with 2-nuc mutation (G22895C, T22896A). Now the branch further gets T22897A then the 3-nuc mutation S:V445H->Q appears.
![联想截图_20231223002516](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/9528e227-e3ea-488c-8b4c-9de91b396481)

Genomes:
EPI_ISL_18653068, EPI_ISL_18673168

**Comment by cvejris** [comment]
What a lovely mutation. More strikingly, XBB also had a 2nuc at the site: V445P

**Comment by FedeGueli** [comment]
+1 France
