### ISSUE TITLE
XCH.1+S:E554D(24 seq, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1219]
XCH.1+G9220A+T23662C+G23224T(S:E554D)

GISAID query: G9220A,T23662C,G23224T
No. of seqs: 22(UK 1 France 7 Italy 1 Slovenia 6 Spain 6 Sweden 1)

First: EPI_ISL_18331717, Spain, 2023-9-12
Latest: EPI_ISL_18675933, France, 2023-12-3

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice49_genome_20e63_659740.json?label=id:node_3707377)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/229330c6-49a6-4e5b-87ab-840c338f7678)

**Comment by aviczhl2** [comment]
+1 USA

**Comment by FedeGueli** [comment]
no recent smaples closing it for now.
