### ISSUE TITLE
BQ.1.24 sublineage with S:A701V (47 seqs in South Korea and Japan)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#122]
Defining mutations: BQ.1.24>G27666T (ORF7a:E91D)>G11365T>C23664T(S:A701V), C15720T
GISAID query: Spike_T240I, Spike_A701V, G11365T, G27666T
Earliest seq: 2023-02-09 (South Korea, EPI_ISL_17090276)
Most recent seq: 2023-05-14 (South Korea, EPI_ISL_17730621)
Countries detected: South Korea (20), Japan (20)

Usher tree: 
![QQ截图20230601121719](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/6c5e46c7-bd73-4e9a-ad4a-fbc17a71ff14)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_145a4_818240.json
As BQ* has been rapidly replaced by XBB* lineages, it may be the one of "last BQ* sublineages".
Despite it has a certain transmission in South Korea and Japan, its potential is limited. So I propose here for tracking.

Genomes:
EPI_ISL_17090276, EPI_ISL_17091442, EPI_ISL_17294722, EPI_ISL_17374050, EPI_ISL_17374172, EPI_ISL_17374223, EPI_ISL_17415859, EPI_ISL_17495619, EPI_ISL_17510708, EPI_ISL_17538663-17538664, EPI_ISL_17540029, EPI_ISL_17556471, EPI_ISL_17558607, EPI_ISL_17563697, EPI_ISL_17564233, EPI_ISL_17604420, EPI_ISL_17625682, EPI_ISL_17625693, EPI_ISL_17625706, EPI_ISL_17625724, EPI_ISL_17629544, EPI_ISL_17629758, EPI_ISL_17630000-17630001, EPI_ISL_17631171, EPI_ISL_17637604, EPI_ISL_17647346-17647347, EPI_ISL_17648922, EPI_ISL_17648978, EPI_ISL_17672457, EPI_ISL_17692200-17692201, EPI_ISL_17730616-17730621

Nuc query: G11365T,C15720T,G27666T

**Comment by FedeGueli** [comment]
It seems very slow closing for now.
