### ISSUE TITLE
JN.1.4 sublineage with S:N185T (9 seqs in Singapore and China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1220]
Defining mutations: JN.1.4 [C774T (ORF1a:T170I)] >T18453C>C28201T (ORF8:S103L)>C28948T>A22116C (S:N185T)
GISAID query:  C774T,T18453C,A22116C,C28201T
Earliest seq: 2023-11-22 (Singapore- EPI_ISL_18544740)
Most recent seq: 2023-12-06 (Singapore- EPI_ISL_18651154)
Countries detected: Singapore (5), China (1)

Usher Tree: (The S:K484E rev is common artefact in Singapore)
![联想截图_20231223133936](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/50ac019a-a0c5-40d6-add5-f88a18451b4a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33e9_5af200.json?c=gt-S_185

** @FedeGueli has mentioned one JN.1* branch with S:N185D in #1180 and @Doropfan proposed JN.1*+S:N185S in #1214 
JN.1* is growing fast in the whole world, particularly in Singapore. Now the JN.1+S:N185T branch is detected in Shanghai, China and we can track it for a time.

Genomes:
EPI_ISL_18544740, EPI_ISL_18604650, EPI_ISL_18605092, EPI_ISL_18651055, EPI_ISL_18651154, EPI_ISL_18672175

**Comment by FedeGueli** [comment]
Thx @HynnSpylor i ve spotted this one too! thx for proposing

**Comment by FedeGueli** [comment]
the query was wrong ( i think copy padte from V445Q ) here the correct  C774T,T18453C,A22116C,C28201T . edited in the proposal

**Comment by HynnSpylor** [comment]
> the query was wrong ( i think copy paste from V445Q ) here the correct C774T,T18453C,A22116C,C28201T . edited in the proposal

Yeah I had the typo! Thx @FedeGueli

**Comment by FedeGueli** [comment]
> > the query was wrong ( i think copy paste from V445Q ) here the correct C774T,T18453C,A22116C,C28201T . edited in the proposal
> 
> Yeah I had the typo! Thx @FedeGueli

No worries it happens all the time!

**Comment by FedeGueli** [comment]
+2 SNGP

**Comment by FedeGueli** [comment]
no recent sample closing it
