### ISSUE TITLE
Some weird Samples from Italy about possible FL.15.1.1 saltations or contamination

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1222]
Gisaid Inquiry: A22910G, C22916T,A23223C
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_25bb0_7fd230.json?f_userOrOld=uploaded%20sample&label=id:node_5413758
This is what the usher looks like
<img width="1151" alt="Screenshot 2023-12-24 at 4 56 21 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/4ee6bede-044d-4ec7-9f89-08ab6d2df6d1">
However, I don't trust the lab very well, and this is the collection of some recent samples.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2d727_800130.json?f_userOrOld=uploaded%20sample&label=id:node_5413896

**Comment by krosa1910** [comment]
<img width="1428" alt="Screenshot 2023-12-24 at 5 04 07 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/addf4720-2094-45bc-b64d-cbd4d5d7681d">
Some problems that could be about the lab's quality control.

**Comment by krosa1910** [comment]
I think it is a lab thing so I would close this issue for now.

**Comment by FedeGueli** [comment]
A22910G, C22916T,A23223C the query finds 5 from far countries would u like to check them?

**Comment by krosa1910** [comment]
<img width="1433" alt="Screenshot 2024-01-18 at 3 15 06 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/0c785ac8-c03c-4407-b326-de58947dcdeb">
It is because this search now contain a small JN.1.4* tree of 4(3 when you commented) seqs, but I think that is discussed by Ryan sometime yesterday about JN.1*+S:E554T

**Comment by FedeGueli** [comment]
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1aac3_8cfcf0.json?f_userOrOld=uploaded%20sample&label=id:node_2300633 <img alt="Screenshot 2024-01-18 at 3 15 06 PM" width="1433" src="https://private-user-images.githubusercontent.com/131021067/297655170-0c785ac8-c03c-4407-b326-de58947dcdeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjU4NzcsIm5iZiI6MTcwNTU2NTU3NywicGF0aCI6Ii8xMzEwMjEwNjcvMjk3NjU1MTcwLTBjNzg1YWM4LWMwM2MtNDQwNy1iMzI2LWRlNTg5NDdkY2RlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwODEyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGE4N2YyNWQyMWY1MjY2MzQ5NjhlODk5MzM0MjAxMTYxYTI3MmIwMGU5ZmVkMzFmODhlYjYzMDYxOThiY2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5xoAMKHP14G4g_K68j2IF3YSRso14SqKX_Rt1NlS_Pg">
> 
> <img alt="Screenshot 2024-01-18 at 3 17 02 PM" width="647" src="https://private-user-images.githubusercontent.com/131021067/297655651-2e9fe947-14fe-4a71-b99e-c46c457f87c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjU4NzcsIm5iZiI6MTcwNTU2NTU3NywicGF0aCI6Ii8xMzEwMjEwNjcvMjk3NjU1NjUxLTJlOWZlOTQ3LTE0ZmUtNGE3MS1iOTllLWM0NmM0NTdmODdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwODEyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDBhNjcyYTk1NGQ5NTA3ZDk2ZjZmNjJiZGU0N2Y4MDkzOWRlYzZhNzEzYTY2OGFlMGE2OTA0N2IzMzZkOTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8y_E36pw7pfC2oAJowJPs_lbV8-1TXD_FXONR1SwtFs">
> It is because this search now contain a small JN.1.4* tree of 4(3 when you commented) seqs, but I think that is discussed by you and Ryan sometime yesterday about JN.1*+S:E554T @FedeGueli

So i found that from here! thank you!
