### ISSUE TITLE
Possible JN.1+S:ins16MPLL likely emerged in an undersampled area(78) with a sublineage with Orf9b:R47C,N:A50V, (24 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1223]
**Note:  the insertion ins21610ATGCCGCTGCTT is present in 15 samples subdivided in more than 5 clusters on Usher it is possible thay are all the same lineage but impossible to prove or disprove:
query to track them : ins21610ATGCCGCTGCTT (**EDITED by mod**)**

There seems to be a French JN.1 branch with S:ins16MPLL instead of S:ins16MPLF.

JN.1+C28422T(Orf9b:R47C, N:A50V)+T16473C, ins21610ATGCCGCTGCTT (previous  ins21610ATGCCGCTGTTT , effectively making 
S:ins16MPLL, or S:F20L in the new Spike)

GISAID query:C28422T, ins21610ATGCCGCTGCTT (by @FedeGueli)
No. of seqs: 5(France)

First: EPI_ISL_18675808, 2023-11-28
Latest: EPI_ISL_18676085, 2023-12-8

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_30c16_801cd0.json?branchLabel=nuc%20mutations&label=id:node_6786985&showBranchLabels=all)
Note that Spike change in the insertion part is invisible in usher, it only displays T16473C for that branch.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/76d106cd-8388-4c73-8716-6ace4ebc903d)

**Comment by FedeGueli** [comment]
@aviczhl2  displayed gisaid query is unrelated, i suggest to use : ins21610ATGCCGCTGCTT and it gives 15 samples!

**Comment by aviczhl2** [comment]
> @aviczhl2 displayed gisaid query is unrelated, i suggest to use : ins21610ATGCCGCTGCTT and it gives 15 samples!

Yeah but others are distributed, only this one is grouped in a branch visible in usher.

**Comment by FedeGueli** [comment]
The query displayed seems unrelated to this one finding just three distant indian samples,
while ins21610ATGCCGCTGCTT, T14454C finds 4 of the french cluster you proposed.

but ins21610ATGCCGCTGCTT alone finds 15 and i think they are all form the same lineage splitted by Usher cause it doent see the insertion : i say this for these reasons:
1 all very recent samples,
2 all clustering by country
3 two sequences with this insertion has been caught from african travellers one from Ethiopia one from South Africa.
4 looking at samples clustering with the samples with this insertion it is easy to spot an early italian spread.

list of clusters with this mutation:

1) France with N:A50V proposed here

2) England G19999T (orf1b:V2178F)

3)Italy/England G6404T (orf1a:V2047F)

4)Italy/Poland directly from politomy with 452L 

5)

**Comment by FedeGueli** [comment]
> ins21610ATGCCGCTGCTT

yeha that makes hard the designation, but still i think they are one. thank you for spotting. please correct the query that gives unrelated samples.

**Comment by FedeGueli** [comment]
@corneliusroemer please can you take  a look? it seems quite fast thing.

**Comment by aviczhl2** [comment]
@AngieHinrichs, is there a way for usher to display mutations inside the insertion part?

**Comment by FedeGueli** [comment]
@aviczhl2 the query is wrong please check it.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs, is there a way for usher to display mutations inside the insertion part?

Currently no, this is a limitation of usher.

**Comment by aviczhl2** [comment]
+1 Spain on Orf9b:R47C branch

**Comment by aviczhl2** [comment]
28, the Orf9b branch becomes 10 and adds UK

**Comment by aviczhl2** [comment]
42, the Orf9b branch becomes 15 and adds USA

**Comment by FedeGueli** [comment]
47 now

**Comment by FedeGueli** [comment]
It seems very slow

**Comment by FedeGueli** [comment]
no sequence in March closing it
