### ISSUE TITLE
Weird JN.1/BA.1? recombinant in India (2 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1224]
There seems to be 2 seqs with weird shared mutations in the recently uploaded India samples.  Unable to detect how they are formed. Have a lot of unique mutations so may not purely contam. 

It has the BA.1-S:ins214EPE. 

Maybe they are recomb of JN.1 and something involving BA.1?

JN.1+
Reversions:
G670T(rev), G7842A(rev), T9534C(rev), T10198C(rev), T12815C(rev), T12789C(rev), T17410C(rev), T21711C(rev), A22295C(rev), A22353C(rev),T23423C(rev), T25207C(rev) 

New mutations:
T8617C, G9805A, A17532G,G20569A,C20589T, C21846T,  ins22204GAGCCAGAA, G23604A, C24559T

Orf1ab: R135S(rev),S2526N(rev), I3090T(rev), I4175T(rev),C5716R(rev), I5756M, V6769I
S: T95I, L50S(rev), N245H(rev),D264A(rev), S621P(rev), ins214EPE, R681H

GISAID query: T8617C, G9805A, A17532G 
No. of seq: 2(India)

EPI_ISL_18682687,2023-12-14
EPI_ISL_18682688,2023-12-19

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice11_genome_1cd53_8ff0e0.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ddb6d01a-a457-4acd-9bb2-48592489a863)

**Comment by aviczhl2** [comment]
Dr. Rajesh Karyakarte confirms they are real, at least for 18682688.

**Comment by karyakarte** [comment]
@Outpfmance, I discussed this issue with @aviczhl2, to take care of contamination, if any, we will be including both samples in our next sequencing run. Regarding, sequencing quality, the run was on illumina MiSeq, with 814 Ns with 96.90% @ Coverage >10X (%) & 93.97% @ Coverage > 30X (%). We will be taking our next run ASAP.

**Comment by aviczhl2** [comment]
It seems that they are artefacts confirmed by @karyakarte
