### ISSUE TITLE
Lineage of HV.1* that includes a possible subbranch with S:N450D (17 samples , 1,5% prevalence in NZL)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1225]
On an undesignated branch of HV.1
 with C4900T, G14346A
Gisaid Inquiry: G14346A,C5835T,C4900T （C4900T merely reduces sequence  EPI_ISL_18440535 questionable early sequence of EG.5.1.6* with possible contamination)
this sublineage with S:N450D seems interesting to be proposed:

Sublineage with S:N450D
Defining mutations:
HV.1 > Orf1a:t4083M (C12513T) > C4900T, G14346A > S:N450D (A22910G)
Gisaid query: G14346A,C5835T,A22910G
Samples 13
Country : New Zealand
Sequences:EPI_ISL_18670550, EPI_ISL_18670597, EPI_ISL_18670599,
EPI_ISL_18670610, EPI_ISL_18670755-18670757, EPI_ISL_18670762,
EPI_ISL_18670843, EPI_ISL_18671131, EPI_ISL_18671473-18671474,
EPI_ISL_18671589

 
Earliest Sequence: 
EPI_ISL_18531551 US, NJ 10-07
Latest Sequence: 
EPI_ISL_18670550 New Zealand 12-13
usher
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_17a99_94bb50.json?f_userOrOld=uploaded%20sample (the version without C4900T)
<img width="1179" alt="Screenshot 2023-12-25 at 4 35 03 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/326041bf-b58c-4426-be03-1707dc8d8b32
<img width="1179" alt="Screenshot 2023-12-25 at 4 38 10 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/8eda2d51-5b24-4151-a442-7e2c24240551">
">
I am more cautious with the S:N450D branch as it could be some cluster testing.

**Comment by FedeGueli** [comment]
Although it is likely a cluster the important lineage of this proposal is the S:N450D one, i would re edit to focus on that please

**Comment by krosa1910** [comment]
> Although it is likely a cluster the important lineage of this proposal is the S:N450D one, i would re edit to focus on that please

New Zealand is doing trash on gisaid uploads now it seemed. They upload nothing from Nov 16th to Nov29th, only to dump something in Nov30th and Dec 1st (the later is somehow mostly old ones), and then they wait another three weeks to dump some new sequences on Dec 22th. I hope I don't have to wait two or three more weeks to see that better monitored.

**Comment by FedeGueli** [comment]
> > Although it is likely a cluster the important lineage of this proposal is the S:N450D one, i would re edit to focus on that please
> 
> New Zealand is doing trash on gisaid uploads now it seemed. They upload nothing from Nov 16th to Nov29th, only to dump something in Nov30th and Dec 1st (the later is somehow mostly old ones), and then they wait another three weeks to dump some new sequences on Dec 22th. I hope I don't have to wait two or three more weeks to see that better monitored.

They do batch upload since last summer

**Comment by krosa1910** [comment]
It seemed another branch of HV.1*+S:N450D is designated as HV.1.11*. without info on New Zealand we may not know about this one.

**Comment by FedeGueli** [comment]
> > It seemed another branch of HV.1*+S:N450D is designated as HV.1.11*. without info on New Zealand we may not know about this one.
> 
> **HV.1.11** is `C21952T, A22910G(S:N450D)` right on HV.1 polytomy

yeha i ve checked it ! @krosa1910 maybe already aware but if you click CSV lineage file from the commit you can get the virus name then adding hCov-19/ before the name you can query ot from Gisaid and adding whtever query for a lineag you immmediately know if it belongs to it or not. (i usally take 3-4 seqs to be sure)

**Comment by krosa1910** [comment]
I was looking for transforming this into an HV.1* with S:N450D issue, but there does not seem to be any >2 seq branch besides this one and HV.1.11*, I guess I will just wait for New Zealand to do some new uploads.

**Comment by FedeGueli** [comment]
17 now only 4 in the last NZL batch

**Comment by krosa1910** [comment]
Still no N450D branch update, closing it now as the parent does not look too interesting.
