### ISSUE TITLE
JN.1.5 with FCS-destroying S:R683Q, ORF7a:T28I (sublineage of #1143) (35 seq, Mar 3)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1226]
This is a proposal for a sublineage of a proposed-but-not-designated sublineage (now JN.1.5 edited) , which is normally not something I'd do, but I think the unusual mutation here and its geographic spread warrant a separate issue. See #1143, where I first noted this S:R683Q branch.

### **Description**
**Sub-lineage of:** JN.1
**Earliest sequence:** 2023-11-20, Israel — EPI_ISL_18572344
**Most recent sequence:** 2023-12-14, Israel — EPI_ISL_18683585
**Continents circulating:** Asia (6), Europe (4), North America (1)
**Countries circulating:** Israel (6), France (3), Netherlands (1), USA (1)
**Number of Sequences:** 11
**GISAID Nucleotide Query:** C27476T, G23610A, G11727A
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [3-of: C27476T, G23610A, G11727A]
**Substitutions on top of JN.1:**
**Spike:** R683Q
**ORF7a:** T28I
**ORF1b:** V1271T
**Nucleotide:** G17278A, T17279C, G23610A, C27476T

**Phylogenetic Order of Mutations:** G17278A, T17279C (ORF1b:V1271T) **→** C27476T (ORF7a:T28I) **→** G23610A (S:R683Q) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1__1b.V1271T_7a.T28I_S.R683Q.json?c=gt-S_683&gmax=25384&gmin=21563&label=id:node_6802838 
<img width="1431" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c4df9b32-b64e-47a8-9e80-51440c5220b1">

**Evidence**
The furin cleavage site has been a mainstay of SARS-CoV-2, and its enhancement by S:P681R or S:P681H has become universal. It’s pretty shocking, therefore, to see dozens of BA.2.86* sequences with FCS-destroying mutations like S:R683Q and S:R683W. 

There are actually more than twice as many BA.2.86* sequences with S:R683W than S:R683Q, but they are much more scattered about the Usher tree. However, there are two or three smaller S:R683W branches with about five sequences that indicate that mutation is circulating as well. 

It’s striking to see this show up in the ORF1b:V1271T branch, which seems to be growing quickly. ORF1b:V1271T is a 2-nucleotide mutation that also showed up in two XBB* lineages, perhaps indicating it’s one of those advantageous mutations that is only rare because of the difficult path needed to traverse to achieve it. 

Even more intriguing is the 4-sequence branch just below this S:R683Q branch. It has three sequences that allegedly have the S:R681P reversion (_Query: C19859T,C27476T,G17278A edited_)  and one of those sequences went on to—again, allegedly—acquire S:P681S (_Query: A16953G, C23603T,C20320T edited_). I normally dismiss sequences like these as artifacts, but given the extraordinary number of mutations and diversity in and around the FCS in BA.2.86, perhaps these are real. 

**Genomes**
<details>
<summary>Genomes</summary> 
EPI_ISL_18572344, EPI_ISL_18572349, EPI_ISL_18572353, EPI_ISL_18618033, EPI_ISL_18621762, EPI_ISL_18640345, EPI_ISL_18673149, EPI_ISL_18676916, EPI_ISL_18677173, EPI_ISL_18683457, EPI_ISL_18683585
</details>

**Comment by HynnSpylor** [comment]
Yeah the S:R683X is more frequent in BA.2.86* (there are more S:R683W seqs but seems scattered, and also several R683S/L seqs). 
The S:R683Q is clear on the 2-nuc mutation (G17278A, T17279C) branch which is high prevalence in Singapore

**Comment by FedeGueli** [comment]
great catch @ryhisner i ve added two queries for the mentioned lineages belonging to the branch below this one.

**Comment by FedeGueli** [comment]
> Yeah the S:R683X is more frequent in BA.2.86* (there are more S:R683W seqs but seems scattered, and also several R683S/L seqs). The S:R683Q is clear on the 2-nuc mutation (G17278A, T17279C) branch which is high prevalence in Singapore

also high in Malaysia and Indonesia

**Comment by FedeGueli** [comment]
16 now

**Comment by FedeGueli** [comment]
30 mostly new samples coming from France and Israel

**Comment by FedeGueli** [comment]
Only one sample from February closing it
