### ISSUE TITLE
JN.1.1 Sublineage with S:K679M (68seq, Mar 26)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1227]
### **Description**
**Sub-lineage of:** JN.1.1 (BA.2.86.1.1.1)
**Earliest sequence:** 2023-10-20, Spain — EPI_ISL_18444230
**Most recent sequence:** 2023-12-12, Sweden — EPI_ISL_18626506
**Continents circulating:** Europe (17), North America (1)
**Countries circulating:** Denmark (4), France (4), Netherlands (4), Spain (2), England (1), Germany (1), Sweden (1), USA (1)
**Number of Sequences:** 18
**GISAID Nucleotide Query:** G11727A, A23598T, -G27598T
**CovSpectrum Query:** Nextcladepangolineage:JN.1.1* & S:K679M
**Substitutions on top of JN.1.1:**
**Spike:** K679M
**Nucleotide:** A23598T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.1__K679M.json?c=gt-S_679&gmax=25384&gmin=21563&label=id:node_6791430 
<img width="1305" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/bd32ed6a-605d-4aea-8755-fca81381aa5d">

**Evidence**
This is one of the many FCS and FCS-adjacent mutations that have exploded since the arrival of BA.2.86. There have been 26 sequences with S:K679M in 2023, and 22 of those are BA.2.86*, with 18 of those in this lineage. All time, there have been 51 sequences with S:679M. 

I’m not 100% convinced that all 18 of these sequences are monophyletic. They don’t have any shared mutations apart from S:K679M. However, they all are JN.1.1, and there are only four BA.2.86* sequences outside of this branch that have S:K679M, so probably most of them are related. 

<img width="1279" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e9322c49-822d-4278-88bf-73180c713d2e">

**Genomes**
<details>
<summary>Genomes</summary> 
EPI_ISL_18444230, EPI_ISL_18464539, EPI_ISL_18551653, EPI_ISL_18553541, EPI_ISL_18556844, EPI_ISL_18568384, EPI_ISL_18591011, EPI_ISL_18598846, EPI_ISL_18612622, EPI_ISL_18621403, EPI_ISL_18626506, EPI_ISL_18634514, EPI_ISL_18640452, EPI_ISL_18641445, EPI_ISL_18661682, EPI_ISL_18674653, EPI_ISL_18674677, EPI_ISL_18676433 
</details>

**Comment by FedeGueli** [comment]
Thx for proposing!

**Comment by FedeGueli** [comment]
35 now, not fast but widespread in 4 continents

**Comment by FedeGueli** [comment]
44

**Comment by FedeGueli** [comment]
it seems slow

**Comment by FedeGueli** [comment]
it has no growth closing it
