### ISSUE TITLE
JN.1.5 (ORF1b:V1271T) with C5986T, and ORF1a:P1921S first detected in Ticino, Switzerland (160 GISAID seqs as of 2024-01-24; Australia, Brunei, Canada, China, Denmark, France, Indonesia, Japan, Malaysia, Pakistan, Poland, Singapore, South Korea, Switzerland, UK, and USA; traveller from Turkey)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#1228]
There may be a JN.1.5 (ORF1b:V1271T=NSP13:V348T; G17278A, T17279C), C5986T, and ORF1a:P1921S (NSP3:P1103S; C6026T) first detected in Ticino, Switzerland. This sublineage has a proposed parent https://github.com/cov-lineages/pango-designation/issues/2419 to which this proposal adds C5986T and ORF1a:P1921S (NSP3:P1103S; C6026T). 

As of 2023-12-25, Cov-Spectrum reports 29 good-quality (42 total) JN.1+ORF1a:1921S+ORF1b:1271T+5986T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AJN.1+%26+ORF1a%3AP1921S+%26+ORF1b%3AV1271T+%26+C5986T&nextcladeQcOverallScoreTo=29&

This lineage has been reported from 4 continents and shows a possible growth advantage over its parent JN.1. While this lineage has been detected in stellar sequencing countries Canada and Signapore, the majority of the global sequences are not from these two countries so their relatively intense sequencing is not likely to be biasing the global growth advantage. The plurality of sequences for this lineage are from Malaysia, but as of 2023-12-25 there are too few sequences from Malaysia to determine a reliable growth advantage over this lineage's parent JN.1.

Checking Bloom and Neher's data https://jbloomlab.github.io/SARS2-mut-fitness/ and https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv, as shown below ORF1a:P1921S is associated with a relative growth advantage for all clades. As a novel 2-nucleotide mutation, ORF1b:V1271T has no data in the Bloom and Neher dataset.

As of 2023-12-25, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_JN 1+ORF1a_1921S+ORF1b_1271T+5986T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/d17a6f57-ad9c-4b71-a6fb-0b7c37b24cd6)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/12/subtreeAuspice1_genome_CoV-Spectrum_JN.1%2BORF1a_1921S%2BORF1b_1271T%2B5986T.json?c=gt-ORF1ab_1921&label=id%3Anode_6802619

GISAID query: G17278A, T17279C, C5986T, C6026T

First GISAID sequence: Ticino, Switzerland 2023-11-19 

Most Recent GISAID sequence: Jakarta, Indonesia 2023-12-14

A zip archive of CoV-Spectrum-derived UShER output files for these sequences is available at [Support-JN.1+ORF1a_P1921S+ORF1b_1271T+5986T.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/13768059/Support-JN.1%2BORF1a_P1921S%2BORF1b_1271T%2B5986T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-JN.1+ORF1a_P1921S+ORF1b_1271T+5986T.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/13768061/gisaid-epi-isl-JN.1%2BORF1a_P1921S%2BORF1b_1271T%2B5986T.txt)

Potential effects of the non-synonymous mutation ORF1a:P1921S on viral relative fitness
---------------------------------------------------------------------------------------

From the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations, for ORF1a:P1921S:

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,P1921S,0.45975
20B,ORF1ab,P1921S,1.1701
20C,ORF1ab,P1921S,1.0042
20E,ORF1ab,P1921S,0.9422
20G,ORF1ab,P1921S,0.42036
20I,ORF1ab,P1921S,0.78364
21C,ORF1ab,P1921S,0.46398
21I,ORF1ab,P1921S,0.57457
21J,ORF1ab,P1921S,0.85523
21K,ORF1ab,P1921S,0.82125
21L,ORF1ab,P1921S,0.75162
22A,ORF1ab,P1921S,0.89186
22B,ORF1ab,P1921S,0.83121
22C,ORF1ab,P1921S,0.53524
22D,ORF1ab,P1921S,0.58985
22E,ORF1ab,P1921S,0.84586
22F,ORF1ab,P1921S,1.1764
23A,ORF1ab,P1921S,0.75612
23B,ORF1ab,P1921S,0.057158
23D,ORF1ab,P1921S,0.78267

ORF1a:P1921S has a positive fitness effect for all clades with the strongest positive fitness effect in clades 22F, 20B, 20C, and 20E and a weak likely negligible effect in clade 23B.

As of this writing, Bloom and Neher provide no relative fitness estimates for ORF1b:V1271T. However, for some clades ORF1b:V1271L and ORF1b:V1271A are associated with positive relative fitness impacts with some of the impacts, such as ORF1b:V1271L, having significant positive relative fitness impacts such as +1.6328 in clade 22B and +1.448 in clade 22C. So mutations at ORF1b:V1271 are plausibly beneficial to viral fitness.

**Comment by FedeGueli** [comment]
i spotted this too while tracking JN.1 in Malaysia it is interesting to watch how it goes, cause the parental linegae in Singapore seemed to have advantage but Singapore is cluster/targeting sequencing prone and also high density of population could influence epi- ariants dynamics. This one seems going well in both Malayisa and Indonesia but also is the main sublineage for exportations in other continents. It still could be explained as founder effect: first to hit first to leave and spread, but still debatable. We will seee soon if its growth advantage is real. thx for spotting and proposing it.

**Comment by FedeGueli** [comment]
Please propose it on the main repo:
i am tracking a sublineage of this with S:R408G in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1150 apparently fast.

**Comment by alurqu** [comment]
> Please propose it on the main repo: i am tracking a sublineage of this with S:R408G in #1150 apparently fast Please try to short the title with a country count w/o specifying each country! thx!

Transferred to the main repo as [Proposal 2482](https://github.com/cov-lineages/pango-designation/issues/2482).

**Comment by alurqu** [comment]
Closing this issue since it has been transferred to the main repo.

**Comment by FedeGueli** [comment]
Thx!
