### ISSUE TITLE
Big FY.1 / BQ.1  recombinant hidden in the FY.1 tree (41 samples)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#123]
cc @corneliusroemer 

Spotted a clear recombinant where a BQ.1* gave its start of Orf1a to FY.1:

![Schermata 2023-06-01 alle 10 41 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/40cf4718-cc53-454a-b81d-cad1bc504ad3)
![Schermata 2023-06-01 alle 10 41 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5ff3240a-c813-4571-a66e-790c989fa740)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_8b54_8585b0.json?c=gt-nuc_2954&label=id:node_6723854

BQ.1 gave T2954C,C1931A (Orf1a:Q556K), and FY.1 got Orf1a:K47R reverted to K.

Gisaid query:
G18811A, T2954C,C1931A,  C15810T

Samples : 34 (but 38 shown on Usher)

EPI_ISL_17008219, EPI_ISL_17092881, EPI_ISL_17189521,
EPI_ISL_17212326, EPI_ISL_17232282, EPI_ISL_17285867,
EPI_ISL_17286110, EPI_ISL_17324727, EPI_ISL_17327420,
EPI_ISL_17397923, EPI_ISL_17421859, EPI_ISL_17440426,
EPI_ISL_17497844, EPI_ISL_17514351, EPI_ISL_17524403,
EPI_ISL_17564884-17564885, EPI_ISL_17615330, EPI_ISL_17655131,
EPI_ISL_17655281, EPI_ISL_17657543, EPI_ISL_17673611-17673612,
EPI_ISL_17677943, EPI_ISL_17696530, EPI_ISL_17696537,
EPI_ISL_17700078, EPI_ISL_17701199, EPI_ISL_17710678,
EPI_ISL_17710680, EPI_ISL_17710723, EPI_ISL_17710729,
EPI_ISL_17710743, EPI_ISL_17719251

**Comment by FedeGueli** [comment]
I will propose this when it reaches 50

**Comment by corneliusroemer** [comment]
I just came across this myself, also concluded it was likely a recombinant. Will designate, thanks for the analysis!

**Comment by FedeGueli** [comment]
THX Cornelius!

**Comment by FedeGueli** [comment]
XCE
