### ISSUE TITLE
Stepwise FL.5 with S:478R(#268 branch 2)+T732I(44 seqs)+Y200C (39 seqs)+G219D(13 seqs, Russia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1230]
_Branch B1 have been spotted and tracked first by @NkRMnZr in #268_ (edited)

B1: FL.5+A10103G(Orf1a:M3280V)+C8991T(Orf1a:A2909V)+A22995G(S:K478R)

GISAID query: A10103G,C8991T, C22995G
No. of seqs: 80(Australia 1 Austria 2 Canada 3 Israel 3 Japan 1 Lithuania 6 Norway 3 China 1 Slovenia 2 South Korea 1 USA 1 Russia 56)

First; EPI_ISL_17818318, Russia, 2023-4-28
Latest: EPI_ISL_18685546, Russia, 2023-11-20

B2: B1+G19480A(Orf1b:G2005S)+C25782T+T7969C, A16755G,C23757T(S:T732I)

GISAID query: T7969C, A16755G,C23757T
No. of seqs: 38

B3: B2+C26029A(Orf3a:Q213K)+A22161G(S:Y200C)

GISAID query: C26029A, A22161G, C23757T
No. of seqs: 34

B4: B3+C1204T+G22218A(S:G219D)

GISAID query:C1204T,G22218A,C26029A
No. of seq: 9(Russia)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice79_genome_ca70_a3bc70.json?label=id:node_3399225)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/39a55ec1-894c-4c22-9bc8-5a9dde58b6bc)

**Comment by FedeGueli** [comment]
> #268 still going

yeah this is a sublineage of branch 1 of #268. alsp branch 5 to a lower extent is still around

**Comment by FedeGueli** [comment]
44 sequences now still no one fro December

**Comment by aviczhl2** [comment]
Seems dead
