### ISSUE TITLE
Saltation branch of FL.5 (XBB.1.9.1.5)+S:K478R with S:Y200C, S:T732I, ORF3a:Q213K (34 seqs mainly in Russia) 

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1231]
Defining mutations:
FL.5>A10103G (ORF1a:M3280V)>C8991T (ORF1a:A2980V)>G19480A (ORF1b:G2005S), A22995G (S:K478R) >T7969C, A16755G, A22161G (S:Y200C), C23757T (S:T732I), C25782T, C26029A (ORF3a:Q213K)

GISAID query: T7969C, A16755G, A22161G
Earliest seq: 2023-08-31 (Israel- EPI_ISL_18226759)
Most recent seq: 2023-11-20 (Russia- EPI_ISL_18685862)
Countries detected: Russia (21), Lithuania (8), Slovenia (2), Israel (2), Australia (1) 

Usher Tree:
![联想截图_20231226163839](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/08bcc57d-5509-4289-95a5-c4211e0eea4c)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21dba_a8fc10.json?c=gt-S_200

A saltation branch with S:Y200C, which is mostly concentrated on FY* lineages with notable escape potential.

Genomes:
EPI_ISL_18226759, EPI_ISL_18345631, EPI_ISL_18347078, EPI_ISL_18347146, EPI_ISL_18365891, EPI_ISL_18416703, EPI_ISL_18416950, EPI_ISL_18417159, EPI_ISL_18417660, EPI_ISL_18486921, EPI_ISL_18487053, EPI_ISL_18487131, EPI_ISL_18487134, EPI_ISL_18487478, EPI_ISL_18487746, EPI_ISL_18487793, EPI_ISL_18487817, EPI_ISL_18579322, EPI_ISL_18579385-18579386, EPI_ISL_18579482, EPI_ISL_18638864, EPI_ISL_18668577, EPI_ISL_18668671, EPI_ISL_18668680, EPI_ISL_18668797, EPI_ISL_18682783, EPI_ISL_18682930, EPI_ISL_18682933, EPI_ISL_18682993, EPI_ISL_18685345, EPI_ISL_18685546, EPI_ISL_18685862, EPI_ISL_18686155

**Comment by HynnSpylor** [comment]
Oh I just found it duplicated!

**Comment by FedeGueli** [comment]
Same time same lineage! thx for spotting always good to be two spotting the same!
