### ISSUE TITLE
JN.1.1 Sublineage with 3-nuc ORF1b:E2266I (116 seq,  7 countries , March 26)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1232]
### **Description**
**Sub-lineage of:** JN.1.1 (BA.2.86.1.1.1)
**Earliest sequence:** 2023-11-6 (USA, Georgia) — EPI_ISL_18603560
**Most recent sequence:** 2023-12-12 (USA, Texas) — EPI_ISL_18690208
**Continents circulating:** North America (14), Europe (2)
**Countries circulating:** USA (14), France (1), Switzerland (1, traveler, sequenced in USA)
**Number of Sequences:** 16
**GISAID Nucleotide Query:** G20263A, A20264T, A20265T, C897A
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [3-of: G20263A, A20264T, A20265T]
**Substitutions on top of JN.1.1:**
**ORF1b:** E2266I (NSP15_E215I)
**Nucleotide:** C11747T, C13207T, G20263A, A20264T, A20265T  

**Phylogenetic Order of Mutations:**  C11747T  **→**  C13207T  **→**  G20263A, A20264T, A20265T (ORF1b:E2266I, NSP15_E215I)   

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.1__G20263A_A20264T_A20265T.json?c=gt-ORF1ab_6667&gmax=21555&gmin=266&label=id:node_6792354 
<img width="1489" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d1203d08-279b-4cd4-b921-9614a3b89947">

**Evidence**
This is an odd one. The sequences are monophyletic and come from a variety of US states and labs, including the always-reliably CDC. There is also one sequence from France. Furthermore, this 3-nuc mutation has been in about 220 previous sequences, in 41 different designated lineages, according to CovSpectrum (filtering for “good and mediocre” sequences). It first appeared in March 2020 and has reappeared intermittently since. AY.43, with 30.51% of the total, has the most sequences with this mutation, while XBB.1.5.20 is second with 19.92%. 

<img width="1178" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/adb7f583-393c-4388-9cc7-7fea44ac79f0">

Most of the time, when a 3-nucleotide mutation like this appears, there’s a TRS-like motif in the immediate region, signifying recombination was involved. Nothing comes close to resembling the TRS-L here though. There’s also no obvious repetitive pattern in the region that might induce an RdRp stutter (as with ORF3a:ins103P or N:ins238Q). 

There’s no way this evolved stepwise, particularly since A20265T is both synonymous and a rare type of nuc mutation (A->T). 

Doing a search with Theo Sanderson’s invaluable GenSplore (https://gensplore.genomium.org), I found that with this 3-nuc mutation, the 20262-20275 region in NSP15 matches 15/16 nucleotides from 26511-26526 in the region around the M start codon. The first 11 nucleotides in those stretches are a perfect match, as seen below. 

<img width="1508" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/37d82ad4-5385-4d09-9977-ac425d345f3f">

I can’t say for certain that recombination with this region is the reason for this 3-nuc mutation, but it’s the only plausible explanation I can think of. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18590733, EPI_ISL_18600220, EPI_ISL_18600749, EPI_ISL_18601657, EPI_ISL_18602420, EPI_ISL_18603560, EPI_ISL_18621792, EPI_ISL_18636471, EPI_ISL_18644990, EPI_ISL_18675412-18675413, EPI_ISL_18676475, EPI_ISL_18690208, EPI_ISL_18690977, EPI_ISL_18691165, EPI_ISL_18691867
</details>

**Comment by ryhisner** [comment]
This lineage is up to 52 sequences now. Most are still in the US, but there are 3 sequences from France, 2 from Switzerland (one a traveler to the USA), and one from Canada (Quebec). 

There's also an unrelated JN.1.5 from Singapore and an an unrelated JN.1.4 from Hawaii with the same 3-nuc mutation.

**Comment by FedeGueli** [comment]
92

**Comment by FedeGueli** [comment]
little or no growth closing it
