### ISSUE TITLE
JN.1.1 with s:211i and s:212v (>29)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1234]
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f9b7_bb74c0.json?label=id:node_6795222
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/c472eab9-4971-48d2-9945-9737b90e6c83)

First Seq: 2023-11-27
Most Recent: 2023-12-13

Gisaid query: A22194T, T22195A, T22196G, C11747T

EPI_ISL_18676068 EPI_ISL_18677092 EPI_ISL_18676039 EPI_ISL_18676363 EPI_ISL_18676823 EPI_ISL_18676840 EPI_ISL_18676824 EPI_ISL_18676106 EPI_ISL_18676147 EPI_ISL_18676223 EPI_ISL_18676141 EPI_ISL_18676265 EPI_ISL_18676140 EPI_ISL_18677194 EPI_ISL_18676224 EPI_ISL_18676129 EPI_ISL_18662411 EPI_ISL_18677189 EPI_ISL_18675961 EPI_ISL_18676040 EPI_ISL_18676059 EPI_ISL_18676476 EPI_ISL_18676073 EPI_ISL_18676058 EPI_ISL_18676189 EPI_ISL_18676084 EPI_ISL_18676022

**Comment by FedeGueli** [comment]
This is this sublineage :
![Schermata 2023-12-27 alle 08 36 54](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/91b609a5-94b2-44b1-87fb-dd854c9f8a3e)
this is usual JN.1:
![Schermata 2023-12-27 alle 08 38 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5ea4294f-56ba-47e5-8b7b-8d7f92411c96)

To me very hard to think the deletion have been replaced with an insertion. so i m prone to think it  is an artifact. 

cc @ryhisner could you take a look please?

**Comment by FedeGueli** [comment]
It would mean an insertion of three nucleotides GTA (= V Valine) at S:212

**Comment by ryhisner** [comment]
> cc @ryhisner could you take a look please?

I've seen some sequences that say they have a mutation similar to this, and it always looks to me like it's just an S:I210V mutation on top of the usual S:N211del, S:L212I. My guess is that that's what's happening here as well—together with a misread of the deletion by this French lab.

**Comment by FedeGueli** [comment]
> > cc @ryhisner could you take a look please?
> 
> I've seen some sequences that say they have a mutation similar to this, and it always looks to me like it's just an S:I210V mutation on top of the usual S:N211del, S:L212I. My guess is that that's what's happening here as well—together with a misread of the deletion by this French lab.

Thank you Ryan!

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/69aa1e55-d30a-4f4c-90e8-27ab44fb8032)

**Comment by FedeGueli** [comment]
Still only France.until it wont' be sequenced aelsewhere to me it is likely a missread of a nuc mutation. or an artifact itself. Looking at the tree you posted it seems they have trouble with indels at S:16 too. This makes me think it is a lab artifact .
