### ISSUE TITLE
FY.1.2 (XBB.1.22.1.1.2) saltation branch with S:G181V, S:K478R, S:A570V (6/9) and ORF1a:E640K, ORF1a:I1203T, ORF1a:S4135T (6/9), ORF1b:I2373V emerged in Russia (10 seqs in 5 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1235]
Defining mutations:
FY.1.2>A13947C>G2183A (ORF1a:E640K), T3873C (ORF1a:I1203T), T4888C, A20584G (ORF1b:I2373V), C18744T, C18804T, G22104T (S:G181V), A22995G (S:K478R), C23114T>(5/6 with) T12668A (ORF1a:S4135T), C23271T (S:A570V)
GISAID query: T4888C, A20584G, A22161G
Gisaid query to exclude the swedish recombinant : -C4931T, T4888C, A20584G, A22161G (EDITED)
Earliest seq: 2023-10-30 (Slovenia- EPI_ISL_18546051)
Most recent seq: 2023-12-XX (Sweden- EPI_ISL_18694386)
Countries detected: Russia (2), Slovenia (1), Sweden (1), Lithuania (1), UK (1, non-GISAID seq) 

Usher Tree:
![联想截图_20231227204803](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d14fc213-768e-4d0e-9451-d95f85ccb11f)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13b24_c18940.json?c=gt-S_181

the S:A570V is independent from BA.2.86* lineages. Moreover, the Swedish seq is very interesting as Spike shows JN.1* features (between 356-554), but it is difficult to judge whether it is a recombinant.
![联想截图_20231227204712](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/843a46fa-d947-44b2-96ce-8ae3bd02347d)

Genomes:
EPI_ISL_18546051, EPI_ISL_18638840, EPI_ISL_18685332, EPI_ISL_18694386, EPI_ISL_18694865

**Comment by FedeGueli** [comment]
i see ten with T4888C, A20584G, A22161G ! (yesterday there were 5 from Russia!)

**Comment by FedeGueli** [comment]
Got it 9 excluding the recombinant , i ve added a query to exclude it.

**Comment by FedeGueli** [comment]
10 now

**Comment by FedeGueli** [comment]
Likely dead
