### ISSUE TITLE
JN.1 Sublineage with ORF1a:Q607H, ORF1a:K3353R, ORF9b:I5T (18 seq, Canada, 03/03)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1237]
Making this a very brief one as it might be a nursing home cluster that dies out immediately. If it grows, I'll fill in the details in normal fashion.

**Phylogenetic Order of Mutations:**  T14334C   **→**   C18483T    **→**  G2086T (ORF1a:Q607H)  **→**  A10323G (ORF1a:K3353R)  **→**  A9517T, T28297C (ORF9b:I5T)  

**GISAID Nucleotide Query:** G2086T, A10323G, T28297C, -G27915T

**Usher Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_T28297C_K3353R.json?c=gt-nuc_28297&gmax=29297&gmin=27297&label=id:node_6791910
<img width="1303" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2f10db5c-e9e3-4c30-9dcb-73dbe6044cfd">

**Wider View of Usher Tree**
<img width="1491" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a6ac6dc9-c72f-466c-ab7e-b7a1e480b056">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18695983, EPI_ISL_18696011, EPI_ISL_18696069-18696070, EPI_ISL_18697125-18697126, EPI_ISL_18697423, EPI_ISL_18697436
</details>

**Comment by ryhisner** [comment]
Five more of these today from Ontario. All identical to the previous ones.

**Comment by FedeGueli** [comment]
17 now

**Comment by FedeGueli** [comment]
Likely it was just a cluster , no recent sample coming out

**Comment by FedeGueli** [comment]
18, closing it foer now
