### ISSUE TITLE
BN.1.2.3 undesignated branch with N:S37P circulating in South Korea (291 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#124]
I spotted this other big branch of BN.1.2.3 that currently goes on spreading in South Korea. 
Worth monitoring it:
Gisaid query: T25446C,T28382C
![Schermata 2023-06-01 alle 11 22 06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e893be59-b02d-4db4-9933-20fc73d67536)
![Schermata 2023-06-01 alle 11 22 28](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/32064154-fd00-47d9-8f8b-6416c4291986)

sequences : 288

Defining mutations:
BN.1.2.3 >> N:S37P (T28382C)

**Comment by ryhisner** [comment]
N:S37P is a classic cryptic-lineage mutation. It's never caught on in any major lineage, but it may only be a matter ofd time.
