### ISSUE TITLE
Main page #2378(HV.1)/JD.1.1.1 recombinant with additional S:Q218R(6 seqs, USA, 5 with S:S939F)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1240]
Main page #2378(HV.1+Orf1a:T1589I)---JD.1.1.1

Breakpoint between 18493 and 21717

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/79df2b4d-bec5-4d61-bf40-adc80a2f4c21)

Additional mutations: 
A2171G,C4423T,C8814T, A22215G, C22597T

Orf1a:K636E,A2850V
S:Q218R

C4423T,C8814T from a branch in main page #2378
C22597T from a JD.1.1.1 branch

A2171G, A22215G are private

GISAID query:A2171G,C4423T
No. of seqs: 3(USA-CA, NJ)

EPI_ISL_18621827, NJ, 2023-11-28
EPI_ISL_18703419,18703422, CA,2023-11-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice148_genome_2084f_f866a0.json?c=gt-S_218)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/cf6e2544-c576-48a9-9436-b328758829fd)

**Comment by FedeGueli** [comment]
likely dying off

**Comment by aviczhl2** [comment]
+1 CA

**Comment by FedeGueli** [comment]
no 2024 sample closing this

**Comment by aviczhl2** [comment]
+1 USA
