### ISSUE TITLE
BA.2.86.5 + ORF1b:V1553A + S:T572I (22)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1241]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/8c2a9236-9c18-4258-ae7b-7dd22a745750)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b7e2_a0430.json?c=gt-S_572&gmax=25384&gmin=21563&label=id:node_6821786

First Seq: 2023-11-20
Most Recent: 2023-12-18

Gisaid Query: C23277T, C5575T, A22151G, T23278C

England/CLIMB-CM7YMXQ6/2023 England/CLIMB-CM7YEYUA/2023 OY971293.1 EPI_ISL_18677156 EPI_ISL_18676954 OY988953.1 OY987945.1 OY874732.1 OY973886.1 OY875111.1 OY970646.1 OY969222.1 OY970489.1 OY990070.1

**Comment by FedeGueli** [comment]
i am tracking this since some weeks with C23277T, T23278C,C5575T
