### ISSUE TITLE
FW.1.1* branch with large deletions/frameshifts in Orf6/7ab/8 with Orf1a:K3353R and S:A684T  (113 seqs)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1242]
_**First spotted by @nkrmnzr**_ (Edited)

Gisaid Inquiry: A10323G,G23612A,C7119T
Earliest Sample: EPI_ISL_18248688 2023-09-03 England
Latest Sample: EPI_ISL_18688310 2023-12-18 England
It is mostly circulating in Great Britain, but samples in Denmark and US also
Tree of it
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12107_1121d0.json?f_userOrOld=uploaded%20sample
<img width="1424" alt="Screenshot 2023-12-31 at 2 03 36 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/a5a4383d-d5bf-4d97-9535-865b65b5c845">
Remember FW.1.1* gets K356T+R403K combo just like our dear JN.1*, yet it lacked F486P and it is proven that nearly all XBB without F486P does not survive well since XBB.1.5*.
Yet, 
<img width="1424" alt="Screenshot 2023-12-31 at 2 04 38 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/25048a44-e41f-4475-bdf1-90831eda31cd">
*********************

**Edited by mod:**
to fully appreaciate the relevance of this lineage better sharing also the complete tree of XBB.1.28:
<img width="1151" alt="Screenshot 2024-01-01 alle 09 23 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d3f5e2df-2a0c-4bfc-b147-42aed2f18aab">

More i think two relevant things are to be added : 
**First**: XBB.1.28 in its mayority has a frameshift in orf6b described in a comment under the original proposal:

> that the vast mayority (194/240 but further 19 miss it just cause sequencing issue, verified on Nextclade))  of XBB.1.28.1 sequences have a single nucleotide deletion **del27208_27208** corresponding to  the first nuc of the second codon of Orf6 
![Schermata 2023-08-24 alle 14 18 28](https://github.com/cov-lineages/pango-designation/assets/87669813/e914938a-72ee-452f-b8c3-7a4fe8c7bb03)
This consequently causes a frameshift 
![Schermata 2023-08-24 alle 14 19 44](https://github.com/cov-lineages/pango-designation/assets/87669813/e9f617b0-35d3-4614-9e62-35cba9ae421e)
This frameshift leads to a creation of a short new protein of just 10AA.
Its sequence is radically different from the first 11 A of the old Orf6:

OLD  Orf6:1-11 .= MFHLVDFQVTI (ATGTTTCATCTCGTTGACTTTCAGGTTACTATA)
NEW Orf6:1-11  = MFISLTFRLL*    (ATGTTCATCTCGTTGACTTTCAGGTTACTATAG)
![Schermata 2023-08-24 alle 14 24 45](https://github.com/cov-lineages/pango-designation/assets/87669813/376e20c4-d069-4361-9e3a-0daffc0b021a)..."

**Second** :this branch of FW.1.1 had the large deletion of Orf7ab and Orf8, described first by @ryhisner for GW.5.1.1, and found in FW.1.1 by @Nkrmnzr back in October along with this sublineage.

**Comment by krosa1910** [comment]
I don't think this comes from contamination as S:A684T is not altogether a very popular thing, according to cov-spectrum it appeared 83 total within last 2 months, and 64 seemed to be contained in this branch. The growth though can be bit artificial due to the Britain sequencing technique, still it is something to look at.

**Comment by FedeGueli** [comment]
Thx @krosa1910 i ve edited the proposal a bit adding credits but especially with a little talk about this lineage:
XBB.1.28 as a whole started frameshifting Orf6 in a very short 11AA protein then had a Stop Codon at Orf7a:121 then got the Orf7ab orf8 deletion, so in my view it is the shortest genome circulating.

**Comment by FedeGueli** [comment]
CC @ryhisner @aviczhl2 @nkrmnzr @hynnspylor @over-there-is @JosetteSchoenma 
 @krosa1910 :wait wait could this be a recombinant with GW.5.1.1? 
cause i m noticing that this sublineage has not the orf6:2 frameshift that was in all XBB.1.28.1 and in the branch. So the only way i see it gained it back via recombination getting the large deletion too. Both lineages have circulated in England 
<img width="545" alt="Screenshot 2024-01-01 alle 09 55 55" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/6faabe97-9011-447f-93f4-c15d3251b503">

The other thought i can have is that the large deltion messes up the sequencing and so the labs did base calling (WT) for the orf6 missreading,

cc @Thomasppeacock @corneliusroemer @angiehinrichs

**Comment by FedeGueli** [comment]
the recombimant hypotehsis seems unlikely cause GW.5.1.1 has these mutations 
C28511T,T28723C,A28768G,G29810T not present in this  FW.1.1.  so scratch that !

**Comment by FedeGueli** [comment]
It is striking the fact  that the T27205- (= Orf6:F2- > frameshift) deletion 

<img width="1085" alt="Screenshot 2024-01-01 alle 13 05 56" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/da357a4b-427a-4468-a1e0-fceeab8754bb">
bt  
is still there until the node T13728C:
<img width="1159" alt="Screenshot 2024-01-01 alle 13 03 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/99d6f5c6-0dfa-4afd-b292-b38b714e7809">
But disappears completely within the node proposed here:
![Uploading Screenshot 2024-01-01 alle 13.04.16.png…]()
Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1ac7e_27e100.json?f_userOrOld=uploaded%20sample&label=id:node_3645960
As it can be seen from Covspectrum where only 30% of FW.1.1 + T13728C has Orf6:F2-):
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=T13728C&nextcladePangoLineage=FW.1.1*&nextcladePangoLineage1=GW.5.1.1*&

No easy explanattion for it

**Comment by corneliusroemer** [comment]
Designated as FW.1.1.1 - I haven't dug into the deletion question
