### ISSUE TITLE
JQ.1 (BA.2.86.3.1) Branch with ORF1b:Y140N (new TRS-B)- 10 seqs

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1243]
Just doing a really brief issue and a temporary Usher link for now as any BA.2.86 lineage that lacks S:L455S seems destined to die. Will expand and include the usual details if it grows.

**Sub-lineage of:** JQ.1 (BA.2.86.3.1)
**Countries circulating:** Denmark (10)
**Number of Sequences:** 10
**GISAID Nucleotide Query:** C222T, A13884G, T13885A
**Substitutions on top of JQ.1:**
**ORF1a:** D1742N, A1951V
**ORF1b:** Y140N
**Nucleotide:** G5489A, C6117T, A13884G, T13885A, G24004A
**Phylogenetic Order of Mutations:** G5489A (ORF1a:D1742N) **→** C6117T, A13884G, T13885A, G24004A (ORF1a:A1951V, ORF1b:Y140N)

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27c6e_17b950.json?label=id:node_6824572
<img width="1489" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5283bff2-235c-4bea-81dd-ab6ecf600878">

Oddly, the first sequence here appeared way back on October 16. Then it vanished for a month before reappearing. Even more strange is that that October sequence had more mutations than any of the others, including S:G476S and the homoplasic (likely T cell-evading) ORF1a:P1640S, also found in all BA.2.75 sublineages. Perhaps this lineage is more prominent somewhere else on the globe and is has been imported a couple times to Denmark?

All three ORF1ab mutations here are extremely rare, occurring in 0.01% or fewer of sequences all time. 

The combination of A13884G, T13885A creates a new minimal core TRS motif here (ACGAAC). There's not much of anything in the way of extended homology in this case. 
<img width="1383" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/67946e84-3b99-45c3-afae-6c4dde66f015">

**Genomes**
<details>
<summary>Genomes</summary> 
EPI_ISL_18464682, EPI_ISL_18590799, EPI_ISL_18634372,
EPI_ISL_18634477, EPI_ISL_18680500, EPI_ISL_18680962,
EPI_ISL_18693267, EPI_ISL_18693384, EPI_ISL_18693419,
EPI_ISL_18704986
</details>

**Comment by FedeGueli** [comment]
10 now

**Comment by FedeGueli** [comment]
likely dead
