### ISSUE TITLE
KW.1 [JN.1.28  + ORF1a:P1640L (= PLPro_P77L), S:T572I]  sublineage with S:F456L (15  seqs)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1244]
<Details>
<Summary>
Original JN.1.28 Proposal
</Summary>
Defining mutations: (EDITED)
JN.1.28 (C24034T  > A29700G) > C19545T> C24370T > Orf1a:P1640L (C5184T) > S:T572I (C23277T)

Tree:
<img width="1154" alt="Screenshot 2024-03-10 alle 14 09 17" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/926dea73-ce02-4481-bba0-dec2801bbd43">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_54d3e_db02b0.json?c=userOrOld&label=id:node_6919387

First Seq: 12-12-2023
Most Recent: 12-19-2023

NEW Gisaid Query: C19545T, C24370T ,C5184T,C23277T (EDITED to include a few australian sequences without T10084A)
(former by @Fearuncle =T10084A, C5184T, T22926C)

EPI_ISL_18686290 England/CLIMB-CM7Y8QKA/2023 EPI_ISL_18700446 EPI_ISL_18685138

</Details>

Edited by Fed:
It further acquired S:F456L  (**spotted by @aviczhl2** )
Defining mutations:
KW.1 > T10084A > Orf1b:R2009K(G19493A) > S:F456L (T22928C)
Query:T10084A,G19493A,T22928C
Samples : 15  
Country : Australia (multiple states) 
IDs: EPI_ISL_18814984, EPI_ISL_18944247, EPI_ISL_18960766,
EPI_ISL_18960839, EPI_ISL_18981942, EPI_ISL_18983130,
EPI_ISL_18986999, EPI_ISL_18987002, EPI_ISL_18987039,
EPI_ISL_18987072, EPI_ISL_18987111, EPI_ISL_19000184,
EPI_ISL_19005775, EPI_ISL_19009779, EPI_ISL_19013419,
Tree:
<img width="1173" alt="Screenshot 2024-04-01 alle 01 41 35" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/11db5bde-2278-4817-b007-1f985a1543ec">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_20d0a_9f4680.json?c=gt-S_456&gmax=25384&gmin=21563&label=id:node_6933812

**Comment by FedeGueli** [comment]
Last sample came from Qatar via GBW surveillance in US airports.

**Comment by FedeGueli** [comment]
please propose it.

**Comment by FedeGueli** [comment]
propose it please

**Comment by FedeGueli** [comment]
@Fearuncle please propose it

**Comment by FedeGueli** [comment]
Parental branch now JN.1.28. Please propose it .. cc @corneliusroemer

**Comment by FedeGueli** [comment]
@Fearuncle please transfer it to the main page i ve adjusted the defining mutations uopdated the tree and the query and added a sublinegae with 456L spotted by @aviczhl2

**Comment by FedeGueli** [comment]
Designated JN.1.28.1 and KW.1 ( the latter the branch with S:T572I ) via https://github.com/cov-lineages/pango-designation/commit/d2c609bf9158ddd0f1e126581821c89ea99cac23

**Comment by FedeGueli** [comment]
KW:1 + 456L now at 15 i suggest to reop

**Comment by FedeGueli** [comment]
Designated KW.1.1 via https://github.com/cov-lineages/pango-designation/commit/81da870bafcf174f41ae9bad84b28fe00d0bc4dd
