### ISSUE TITLE
JN.1 Sublineage with S:G158V, UK, Can, France, Czech Republic (15 seq, Jan 17)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1248]
### **Description**
**Sub-lineage of:** JN.1 (BA.2.86.1.1)
**Earliest sequence:** 2023-12-14, Canada — EPI_ISL_18708663
**Most recent sequence:** 2023-12-20, Canada — EPI_ISL_18705421 & 3 others
**Continents circulating:** North America (5), Scotland (2)
**Countries circulating:** Canada (5), Scotland (2)
**Number of Sequences:** 7
**GISAID Nucleotide Query:** C22033A, A22034G, G22035T
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & G22035T
**Substitutions on top of JN.1:**
**Spike:** G158V
**Nucleotide:** G22035T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1__S.G158V__G22035T.json?c=gt-S_158&gmax=25384&gmin=21563&label=id:node_6822911 
<img width="1430" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7033d543-1e18-439c-a9db-5820aa5fe274">

**Evidence**
This makes four consecutive nucleotide mutations relative to the reference genome (and relative to BA.2). Not just a typical Canadian cluster since there are also two sequences in Scotland. All 7 sequences collected between Dec 14-20. One sequences was uploaded on December 27, and the other six were uploaded on January 1 or January 2. Could just be a random bump, but it's not impossible it could turn out to be growing rapidly. 
<img width="958" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/15e7bda0-9c3f-4f5f-9fc1-a0026660b95c">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18696550, EPI_ISL_18705364, EPI_ISL_18705421,
EPI_ISL_18708528, EPI_ISL_18708545, EPI_ISL_18708549,
EPI_ISL_18708663
</details>

**Comment by FedeGueli** [comment]
it seems slow 10 now

**Comment by FedeGueli** [comment]
15 but slow closing it for now
