### ISSUE TITLE
JN.1.4 + ORF9b:P10F (131 seq in 20 countries as Jan 31) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1254]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/e4afae85-c5e5-4acd-8e92-73f8ebdfadb7)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6d48_72e990.json?c=gt-nuc_25710&gmax=26710&gmin=24710

First Seq: 2023-11-17
Most Recent: 2023-12-21

Gisaid Query: C25710T, C28312T, T18453C

England/CLIMB-CM7YRIGM/2023 England/CLIMB-CM7YRQKO/2023b EPI_ISL_18695448 PP038769.1 EPI_ISL_18704040 EPI_ISL_18672702  EPI_ISL_18672838  EPI_ISL_18694172  EPI_ISL_18680731 EPI_ISL_18677218 EPI_ISL_18695623 EPI_ISL_18705743 England/CLIMB-CM7YJHQA/2023 EPI_ISL_18702044 EPI_ISL_18672823 England/CLIMB-CM7YJC4P/2023 EPI_ISL_18687869 EPI_ISL_18700589 EPI_ISL_18596992 England/CLIMB-CM7YR8EX/2023 England/CLIMB-CM7YK5AO/2023 EPI_ISL_18535763 EPI_ISL_18680933 England/CLIMB-CM7YFT5J/2023 England/CLIMB-CM7YR6XM/2023 EPI_ISL_18604778 EPI_ISL_18544183 EPI_ISL_18668247 England/CLIMB-CM7YGOBA/2023 England/CLIMB-CM7YK7M5/2023

**Comment by FedeGueli** [comment]
Orf9b:10F was BQ.1 XBL and in many other lineages. 
Please when referring to an issue always display the parental lineage (JN.1 , XBB.1.5 etc etc)

**Comment by FedeGueli** [comment]
This seems one of the fastest sub lineage of JN.1, recency of sequences from multile different areas makes me think this time it could be real

**Comment by Fearuncle** [comment]
new sample from Peru EPI_ISL_18723286 now making it 14 countries

**Comment by Over-There-Is** [comment]
438
