### ISSUE TITLE
New EG.5.1.6+S:L455F(25 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1255]
There seems to be a new EG.5.1.6-Flip branch growing globally.

EG.5.1.6+G2195T,C12896T, G22927C(Orf1a:D644Y, P4211S, S:L455F)

GISAID query: G2195T,C12896T, G22927C
No. of seqs: 14(Denmark 1 Singapore 1 Canada 5 Ireland 1 New Zealand 1 Sweden 2 USA 3)

First: EPI_ISL_18523070, Sweden, 2023-10-29
Latest: EPI_ISL_18717978, Ireland, 2023-12-22

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice119_genome_38e1b_74fbe0.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/fbf5abde-052b-4b92-b105-c8645db4665f)

**Comment by FedeGueli** [comment]
+1 canada

**Comment by FedeGueli** [comment]
it seems dying off

**Comment by aviczhl2** [comment]
Dead
