### ISSUE TITLE
JD.1.1/Pango#2436 (= HK.13.1+S:Q14R) recombinant (15 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1257]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6b9f4b76-a4e6-4073-871d-96923040ee61)

JD.1.1--Main page #2436(HK.13.1+S:Q14R)--JD.1.1

Breakpoint 1 between 6897 and 9692
Breakpoint 2 between 22987 and 25571

Additional mutations: C3828T, from a JD.1.1 branch
Orf1a:S1188L 

GISAID query: C6896T, C13378T, G22927C
No. of seqs: 5(Canada 3 Germany 1 France 1)

First: EPI_ISL_18570187, Germany, 2023-11-13
Latest: EPI_ISL_18717389,France, 2023-12-11

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice121_genome_301bf_75ea70.json?c=gt-S_14&gmax=25384&gmin=21563)

It is on the same recombinant island as main page #2422. 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c306c7b1-0289-48b4-a1a8-7059eb82cb1f)

**Comment by FedeGueli** [comment]
1 seq in. jan

**Comment by FedeGueli** [comment]
Last two samples from january are Canada, if it was circulating there we should have more than that, closing for now
