### ISSUE TITLE
FL.1.5.1/JN.1.1 recombinant( 26 seqs, 10 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1258]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e5ee75c9-327d-4200-9de3-33ebde24c560)

FL.1.5.1--JN.1.1
Breakpoint between 7843 and 8292

Additional mutation: G1127A, from an FL.1.5.1 branch
Orf1a: V288I

GISAID query: G3242A, C8293T,T27810C
No. of seqs: 3(France)

EPI_ISL_18716925,18717232,18717410, 2023-12-11

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_301bf_75e880.json?label=id:node_11137077)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/da12844c-7294-44c0-bf5b-c6c6f2a6a932)

**Comment by aviczhl2** [comment]
+1 France 1 Germany(env sample unsure)

**Comment by aviczhl2** [comment]
+1 Netherlands 1 USA

**Comment by FedeGueli** [comment]
still no recent sequences

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
New country Puerto Rico

**Comment by FedeGueli** [comment]
no new sequence. lets wait. abit before closing it

**Comment by aviczhl2** [comment]
+2 Chile

**Comment by aviczhl2** [comment]
26, China, UK

**Comment by FedeGueli** [comment]
Although not super recent ones worth to transfer it to main issue. Thank you!

**Comment by aviczhl2** [comment]
It seems that G3242A is convergent within JN.1, making the query no longer appropriate now, 

G1127A, G3242A, C8293T,T27810C shall be the correct query, which only gives 4 samples in 2024.1

**Comment by FedeGueli** [comment]
> It seems that G3242A is convergent within JN.1, making the query no longer appropriate now,
> 
> G1127A, G3242A, C8293T,T27810C shall be the correct query, which only gives 4 samples in 2024.1

thank you!
