### ISSUE TITLE
Sudden Emergence of FR.1+9-nuc,3-aa including Orf9b:G31R in China (48 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#126]
FR.1+C25572T+C337T+C882T(orf1a:A206V)+C14097T,C15017T(orf1b:A517V)+T28019C,C14599T,C25603T+G28374A(orf9b:G31R, N:G34E)

GISAID query: del28367_28375,T28019C,C14599T,C25603T

Note that the default for omicron is del28364_28372, and GISAID categorizes G28374A  to del28367_28375. 

No. of seqs: 42( China 40(7 provinces), Singapore 1(from Hong Kong) South Korea 1(from Hong Kong))

First seq: EPI_ISL_17645692, Sichuan, 4-1
Latest: EPI_ISL_17735959, Sichuan, 5-22

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_27786_848c90.json?label=id:node_7227896)
<img width="1400" alt="Screenshot 2023-06-01 at 18 21 31" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f7cbd8a7-92ca-476d-bf23-e421a436b0c1">

**Comment by FedeGueli** [comment]
Same mutation was in FK.1.1 , interestingly covspectrum reports it as N:G34- (G28374A)

@chaoran_chen @corneliusroemer @angiehinrichs

**Comment by Over-There-Is** [comment]
48 now, 3 from Yunnan and 1 from Fuyang, Anhui.
Additionally, all the 3 sequences collected in Shanghai are all imported cases, 2 from Singapore and 1 from Canada, so it's 48 seq in 4 countries now.

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230504-502/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 34; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-05-02"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Singapore

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230504-503/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 35; Host_sex: Female"
                     /country="China:Shanghai"
                     /collection_date="2023-05-02"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Singapore"

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230508-586/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 33; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-05-06"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Canada"

**Comment by FedeGueli** [comment]
I think this should be transferred to the main pango page: It is clearly growing and FR.1 clan is certainly one of the most important underdogs at the moment globally, better to track exactly if it is able to tune its transmissibility further with Orf9b mutations.

 .
