### ISSUE TITLE
Weird #723(XBB.1.16.11+S:K182N)/BA.2.86 recombinant with additional S:143-,145D,356T,572I (2 seqs, India)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1260]
#723(XBB.1.16.11+S:K182N)+
C4577T, C5178T, A9023G, C10279T ,C14649T, C16394T, T17556C, C22295A, T22317G(rev), C22353A,A22629C, C23277T

Other mutations (involving difference in deletions so hard to describe)
del11283_11294 to replace the del11288_11296
del21987_21992 to replace the del21992_21994

Both seqs have clear breakpoints but the breakpoints don't match. Maybe not the same recombinant? 
Need further investigation. 

One seq has the BA.2.86* S:211-, L212I while the other has the XBB* S:G213E so don't know exact about this position.
One seq has the XBB* S:L368I while the other doesn't. 

Orf1a: L1438F, T1638I, T2920A
del3673_3676 and F3677M instead of del3675_3677

Orf1b: P976L
S:V143-,Y145D,H245N, V252G(rev), A264D, K356T, T572I

#723--BA.2.86*--#723

Breakpoint 1 between S:158 and S:245, depends on the exact situation of S:211-213. 
Breakpoint 2 between S:264  and S:332. 

S:K356T, T572I and mutations on Orf1ab are private mutations.
Both seqs have S:S408R rev but that seems to be a common artefact in Indian seqs.

Likely involving some contam. Maybe shall request @karyakarte to confirm those seqs on situation for S:211-213 and S:368

GISAID query: C4577T, C5178T, A9023G
No. of seqs: 2(India)

EPI_ISL_18718926, 2023-12-22
EPI_ISL_18718933, 2023-12-24

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice17_genome_1c89b_78abe0.json?label=id:node_11139462)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ab818be3-fee0-4131-b2f6-b4a4a33fc2d6)

**Comment by FedeGueli** [comment]
In my view they are contamination, there are plenty of sequences in India in the same batch that has the same ba.2.86 245/264 pattern.

**Comment by aviczhl2** [comment]
> In my view they are contamination, there are plenty of sequences in India in the same batch that has the same ba.2.86 245/264 pattern.

If S:200-300 are untrustful, then it shall be XBB.1.16.11 saltation with S: V143-, Y145D, K356T and T572I.

**Comment by aviczhl2** [comment]
> In my view they are contamination, there are plenty of sequences in India in the same batch that has the same ba.2.86 245/264 pattern.

This batch is uploaded by @karyakarte, maybe he can offer some additional information on this contam thing.

**Comment by FedeGueli** [comment]
agree better tracking it.

**Comment by FedeGueli** [comment]
Still 2 i tend to think it is not real. lets wait a bit more.

**Comment by aviczhl2** [comment]
No new seqs
