### ISSUE TITLE
A Quite Ancient EG.5.1* lineage with Orf3a:D27H and S:E1092D involved in a recent recombination (#1154) (250 Sequences)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1261]
_Formerly mentioned by @nkrmnzr in #1048_ (Edited)

I was tracking C22916T (under T22917G it makesS:R452W ) mutation within my HV.1* sequence and I accidentally discovered a recombination of EG.5.1* with JN.1* as EPI_ISL_18566568 (see #1154), which is not uncommon considering the sheer amount of the two parent lineages. 
Yet the latter part contains some mutation I do not know S:E1092D. E and D are not too common within XBB* so it makes me interested and investigate the lineage. Indeed there seems to bury a small lineage there.
Parent: EG.5.1*
Mutations Added: EG.5.1*-》G25471C (Orf3a:D27H)-》T14835C, A24838C (S:E1092D), T28226C
Gisaid Inquiry: T14835C,A24838C,T28226C
Geographic Distribution:
Earliest Sequence: EPI_ISL_18113849 US, 2023-07-23
Latest Sequence: EPI_ISL_18708628, Canada, 2023-12-20
Geographic Distribution: North America-24 Canada, 1 Peurto Rico, 51USA ; Asia-1 Shanghai, 3 South Korea; South America-7 Ecuador Oceania-11 Australia, 5 New Zealand; Europe-1 Belgium, 4 Denmark, 44 England, 4 France, 7 Germany, 7 Greece, 15 Ireland, 5 Netherlands, 1 Portugal, 33 Scotland, 3 Spain, 4 Sweden, 1 Switzerland 
Its comparison with EG.5.1* parent:
<img width="1220" alt="Screenshot 2024-01-05 at 3 29 32 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/c48714b6-05c1-4a10-ad98-d9fc8a5c4691">

Usher：https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1b4f7_7bd2c0.json?f_userOrOld=uploaded%20sample
<img width="1252" alt="Screenshot 2024-01-05 at 3 28 15 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/fb8554d4-1d1e-47e4-8f3b-a039cb609d86">

Some of the recent sequences seem to get S:K444R, and if that is not misled by England clusters then it could give a little more vis viva to this old branch

**Comment by FedeGueli** [comment]
> parent of branch 7 of #1048

dead one luckily.

**Comment by FedeGueli** [comment]
This kind of lineages without a super fit but with a good persistance are always interesting , maybe is that orf3a:D27H pushing some different expression of putative Orf3b Orf3C and so? i sicerely dont jnow anything about that. maybe @ryhisner or @oobb45729 could check that.

**Comment by krosa1910** [comment]
> This kind of lineages without a super fit but with a good persistance are always interesting , maybe is that orf3a:D27H 8 close to the orf3a:S26L in all Delta) pushing some different expression of putative Orf3b Orf3C and so? i sicerely dont jnow anything about that. maybe @ryhisner or @oobb45729 could check that.
> 
> <img alt="Screenshot 2024-01-05 alle 11 31 09" width="574" src="https://private-user-images.githubusercontent.com/87669813/294463756-06eb9441-849a-484a-b7b4-23e3157115b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTE0NjEsIm5iZiI6MTcwNDQ1MTE2MSwicGF0aCI6Ii84NzY2OTgxMy8yOTQ0NjM3NTYtMDZlYjk0NDEtODQ5YS00ODRhLWI3YjQtMjNlMzE1NzExNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEwMzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YzkxYTlmMzQzODI4NTE1NDdhNzU1N2Y2ZDYxZjlmMTViZTNmZjg4MjVjMjNkNzc2NGY0NWNlMmY1OTcxNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PsUKCZDqARRffDvcXfePjZnaUdesssyykViyUmqtFjI">
<img width="1220" alt="Screenshot 2024-01-05 at 5 40 49 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/df1c27e2-7105-4d6a-8cc1-39d462a09f54">
Yeah, it look like quite fit to me, and also it is evident in other lineages, yet this one seems like it is the sole survivor now

**Comment by oobb45729** [comment]
> This kind of lineages without a super fit but with a good persistance are always interesting , maybe is that orf3a:D27H 8 close to the orf3a:S26L in all Delta) pushing some different expression of putative Orf3b Orf3C and so? i sicerely dont jnow anything about that. maybe @ryhisner or @oobb45729 could check that.
> <img alt="Screenshot 2024-01-05 alle 11 31 09" width="574" src="https://private-user-images.githubusercontent.com/87669813/294463756-06eb9441-849a-484a-b7b4-23e3157115b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTI0NTQsIm5iZiI6MTcwNDc5MjE1NCwicGF0aCI6Ii84NzY2OTgxMy8yOTQ0NjM3NTYtMDZlYjk0NDEtODQ5YS00ODRhLWI3YjQtMjNlMzE1NzExNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5MjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2RjZWFlMTJiNzcxOWZmMTllMGZmY2M5MDY1MTFmZTE3OGEyNTBiZjRhMjgxY2M0ZjEyYTFmNmQ1N2NhN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hb0VrHgDrLS74PZT2kIerUH24Py2C_L7cTLVAP4_iXs">

The mutation of ORF3a:D27H also results in ORF3c:Q5H. The mutation of ORF3a:S26L is also results in ORF3c:Q5*. Some Deltas further gained ORF3a:D27Y/ORF3c:Q5Y.

**Comment by FedeGueli** [comment]
> > This kind of lineages without a super fit but with a good persistance are always interesting , maybe is that orf3a:D27H 8 close to the orf3a:S26L in all Delta) pushing some different expression of putative Orf3b Orf3C and so? i sicerely dont jnow anything about that. maybe @ryhisner or @oobb45729 could check that.
> > <img alt="Screenshot 2024-01-05 alle 11 31 09" width="574" src="https://private-user-images.githubusercontent.com/87669813/294463756-06eb9441-849a-484a-b7b4-23e3157115b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTI0NTQsIm5iZiI6MTcwNDc5MjE1NCwicGF0aCI6Ii84NzY2OTgxMy8yOTQ0NjM3NTYtMDZlYjk0NDEtODQ5YS00ODRhLWI3YjQtMjNlMzE1NzExNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5MjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2RjZWFlMTJiNzcxOWZmMTllMGZmY2M5MDY1MTFmZTE3OGEyNTBiZjRhMjgxY2M0ZjEyYTFmNmQ1N2NhN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hb0VrHgDrLS74PZT2kIerUH24Py2C_L7cTLVAP4_iXs">
> 
> The mutation of ORF3a:D27H also results in ORF3c:Q5H. The mutation of ORF3a:S26L is also results in ORF3c:Q5*. Some Deltas further gained ORF3a:D27Y/ORF3c:Q5Y.

Thank you!

**Comment by krosa1910** [comment]
Mexico and Ecuador？ very weird recent lineages，lets keep watching it a bit

**Comment by krosa1910** [comment]
Weird, this one does not look too fit but seems to still move on, I would still keep it as of now.

**Comment by FedeGueli** [comment]
no 2024 sample from this closing it
