### ISSUE TITLE
JN.1 with S:V1104L parental of  SLip Branch 4 of #1253 emerged in India ( 16 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1262]
This was first described by @aviczhl2 in #1253 
India is experimenting a supposedly huge wave of JN.1 recently a lot of samples have been uploaded from there.
As in the past waves many samples have artefactual reversions hence  this lineages is splitted ( cc @angiehinrichs) in different trees, so the image below  is just indicative :
<img width="1006" alt="Screenshot 2024-01-05 alle 09 26 19" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/69a7dc11-d925-4994-82c3-e1391bb3c1c4">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice7_genome_test_3aa55_7b6bc0.json?label=id:node_6827336

Defining mutations:
JN.1> G17334T, S:V1104L (G24872T)
Query: G24872T, G17334T,C897A 

Samples: 10
, EPI_ISL_18683064, EPI_ISL_18694660,
EPI_ISL_18694669, EPI_ISL_18694672, EPI_ISL_18704304,
EPI_ISL_18704343, EPI_ISL_18704350, EPI_ISL_18718937,
EPI_ISL_18718979, EPI_ISL_18718993
plus EPI_ISL_18682687 that looks like a recombinant or contamination of this lineage with an unknown donor ( that could be also a very different one)
<img width="531" alt="Screenshot 2024-01-05 alle 12 17 07" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/577ce4c5-7329-4de8-8d32-ffe34c48da45">

**Comment by aviczhl2** [comment]
15/790=2% India from 2023-12.

**Comment by aviczhl2** [comment]
Better use G24872T, G17334T,C28958A which captures 21. Some India seqs have C897G and some has no coverage  there.

**Comment by FedeGueli** [comment]
Designated JN.1.11 via https://github.com/cov-lineages/pango-designation/commit/1e13380d904f607c60d7e52b52cab573f8a3808d
