### ISSUE TITLE
Recent EG.5.1.8 (Flip) saltation branch with four spike mutations S:Q14R, S:G184V, S:Q675H, S:D843N and a BJ.1 nuc reverted T15939T  (27 seqs, 4 continents)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1263]
Just looking at EG.5.1.8 after CDC highlighted it one of few lineages still growing in US i spotted this small saltation branch that is already being sampled in three continents.
it carries four spike mutations, two in the NTD one in the flanking sequence of FCS and one in S2 ( close to the "fusion machinery" i think but ask to @ryhisner that for sure knows better than me) at least three known to be slighty  beneficial (14,184,675).
interestingly it carries a reversion in a BJ.1 inherited nuc mutation T15939C>T

Defining mutations:
EG.5.1.8 >> C12100G > C14676A > C1549T,A6097G, C10969T, T15939T(rev) ,  Orf1b:C1796Y  (G18854A), Orf1b:D1869G (A19073G), S:Q14R (A21603G), S:G184V (G22113T),  Q675H (G23587C), S:D843N (G24089A) 

Gisaid query: C10969T, A19073G,A6097G

Samples : 13
First: Netherlands 2023-10-30
Last:  Australia 2023-12-24

IDs:
EPI_ISL_18557700, EPI_ISL_18633221, EPI_ISL_18633320,
EPI_ISL_18657114, EPI_ISL_18657158, EPI_ISL_18667192,
EPI_ISL_18667307, EPI_ISL_18674393, EPI_ISL_18684670,
EPI_ISL_18687613, EPI_ISL_18694793, EPI_ISL_18705806,
EPI_ISL_18707780

Countries: Australia, England , South Korea, Netherlands ,

Tree:
<img width="1156" alt="Screenshot 2024-01-05 alle 19 48 10" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8fbb802e-3274-4868-9e40-cb4833172f34">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_66dec_845ba0.json?c=gt-nuc_15939&gmax=16939&gmin=14939&label=id:node_3441242

**Comment by FedeGueli** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
+2 South Australia

**Comment by FedeGueli** [comment]
17 with 3 samples in january from 2 continents

**Comment by FedeGueli** [comment]
21

**Comment by FedeGueli** [comment]
+1 , new continent (North Am.)

**Comment by FedeGueli** [comment]
closing this

**Comment by aviczhl2** [comment]
+4 Australia, extends to 2024.3

**Comment by FedeGueli** [comment]
Thx @aviczhl2 ! i ve reopened it , it could find a niche to keep circulating in Australia

**Comment by FedeGueli** [comment]
27 with 2 samples from March (Tasmania)

**Comment by FedeGueli** [comment]
no new sample collected in the last month closing it
