### ISSUE TITLE
Recent KB.2 (EG.5.1.8.2) sublineage with S:H245Y  13 sequences

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1264]
KB.2 sublinegae is showing some interesting spike diversity:
while a quite big S:A475V has been already tracked by @nkrmnzr in #978 (Branch 3) 
and an interesting S:Y660H sublineage died off back in November,now we are seeing a branch defined by a mutation in a convergent residue with BA.2.86 S:H245Y:
<img width="1153" alt="Screenshot 2024-01-06 alle 00 04 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9a9118f3-cdf6-4da6-a187-5d3c6fcf0b63">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_66dec_845ba0.json?label=id:node_3441275

Defining mutation
KB.2 (S:R214H) > S:H245Y (C22295T) 
Gisaid query:  C22295T, G22203A, C14676A ,C12100G
Samples 8 ( England, US)
IDs:
EPI_ISL_18602515, EPI_ISL_18603435, EPI_ISL_18608705,
EPI_ISL_18621172, EPI_ISL_18691470, EPI_ISL_18694801,
EPI_ISL_18695439, EPI_ISL_18716142

**Comment by HynnSpylor** [comment]
Great catch and H245Y also emerged in GA.4.1 (XBB.1.17.1.4.1)

**Comment by FedeGueli** [comment]
> Great catch and H245Y also emerged in GA.4.1 (XBB.1.17.1.4.1)

thx for noting!

**Comment by FedeGueli** [comment]
11 now, last samples from Colorado.

**Comment by FedeGueli** [comment]
13 but no one from January

**Comment by FedeGueli** [comment]
dead
