### ISSUE TITLE
HK.20.1 with S:S704L in England (22 seqs, 2 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1266]
I noticed a while back a stepwise evolved HK.20.1 (Flip+S:G482R) that got S:S704L, now it is 18 and worth tracking it publicly.
Looking at the tree it is possible to spot 3/4 independent acquisition of S:S704L by HK.20.1 all very recent ( cc @angiehinrichs the tree seems solid here)

Tree: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2d1d5_9e5d10.json?c=gt-S_704&gmax=25384&gmin=21563&label=id:node_3468979
<img width="1173" alt="Screenshot 2024-01-07 alle 01 13 12" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/595a5661-ef31-4329-90a8-9231b563cce3">
Despite not being big it has already got two/three sub-branches defined by spike mutations as S:V705I on the top , or S:K444M on the bottom:
<img width="1159" alt="Screenshot 2024-01-07 alle 01 13 57" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/10eb0ad9-de29-40be-a097-23d94c7e4ce4">

Defining mutations:
HK.20.1 > > C17502T > C28214T > C19803T > T23398C > C7834T, Orf1b:I1675T(T18488C), C19290T > S:S704L (C23673T)  

Query: T18488C, C19290T ,C23673T

Samples: 19
First : England 2023-11-13
Last : England 023-12-24

IDs:
EPI_ISL_18525477, EPI_ISL_18545581, EPI_ISL_18578093,
EPI_ISL_18598905, EPI_ISL_18598931, EPI_ISL_18606211,
EPI_ISL_18641385, EPI_ISL_18652416, EPI_ISL_18688185-18688186,
EPI_ISL_18694599, EPI_ISL_18694612, EPI_ISL_18712636,
EPI_ISL_18712645, EPI_ISL_18717916, EPI_ISL_18717932,
EPI_ISL_18717942, EPI_ISL_18717965, EPI_ISL_18720990,

**Comment by Mydtlwn** [comment]
this is interesting!

**Comment by FedeGueli** [comment]
> this is interesting!

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=T18488C%2CC19290T%2CC23673T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
too slow to track
