### ISSUE TITLE
EG.5.1.3/JN.3.2.1 recombinant with S:F456V (13 seqs, 4 countries )

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1267]
There seems to be a new EG.5.1.3/JN.3+S:F456V recombinant.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2ba69ad6-ab50-448a-a6b7-24a64bccedba)

EG.5.1.3--#1160(JN.3+N:H300Y+S:F456V branch)--EG.5.1.3

Breakpoint 1 between 8294 and 8392
Breakpoint 2 between 26834 and 27506

Additional mutations: G598A

N:T379I

C29409T from an EG.5.1.3 branch, G598A is private.

GISAID query:  C1889T, G8393, T22928G (alternative query by @Over-There-Is : C1889T, G8393, A17637G edited)
No. of seqs: 2(Germany 1 UK 1)

EPI_ISL_18705445, UK, 2023-12-16
EPI_ISL_18724545, Germany, 2023-12-7

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20f8_a82db0.json?f_userOrOld=uploaded%20sample&label=id:node_11146925)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d15a1794-0b00-4d26-911f-4e327e412b97)

**Comment by Over-There-Is** [comment]
There are several branches of EG.5.1.3 with C29409T(N:T379I), or it could also be private.

**Comment by Over-There-Is** [comment]
sometimes it would be no coverage on 22928, so there is an alternative query: C1889T, G8393, A17637G

**Comment by Over-There-Is** [comment]
Scotland/CLIMB-CM7YFQ6T/2023|OY991246.1|2023-12-13, 22928 and 29625 not covered

**Comment by FedeGueli** [comment]
> > CLIMB-CM7YFQ6T
> 
> Seems not on GISAID yet. How can you check its coverage?

https://ukcovid.xyz/spike-combo-new.php?mincount=2

**Comment by Over-There-Is** [comment]
https://www.ncbi.nlm.nih.gov/nuccore/OY991246.1

**Comment by Over-There-Is** [comment]
EPI_ISL_18789987 Österreich

**Comment by Over-There-Is** [comment]
EPI_ISL_18794847 Switzerland

**Comment by aviczhl2** [comment]
> EPI_ISL_18794847 Switzerland

This one is interesting. It has a JN.1 spike instead of JN.3.2.1 spike. It also doesn't have 29409T. It also has C26833T indicating its BP 2 is different from this one. 

There are no JN.1 with A17637G so likely a recomb of this one and another JN.1/EG.5.1 recomb? XDD? 

 @ryhisner @FedeGueli @JosetteSchoenma @corneliusroemer  shall take a look at this.

**Comment by aviczhl2** [comment]
> Scotland/CLIMB-CM7YFQ6T/2023|OY991246.1|2023-12-13, 22928 and 29625 not covered

That one is still not on GISAID. It can also belong to the Switzerland 2nd-level recomb.

**Comment by FedeGueli** [comment]
Thx good analysis on that sample

**Comment by Over-There-Is** [comment]
It has 598A and 6183G but without 8293A. I think it's a contaminated sample of this recombinant and JN.1.

**Comment by Over-There-Is** [comment]
> > Scotland/CLIMB-CM7YFQ6T/2023|OY991246.1|2023-12-13, 22928 and 29625 not covered
> 
> That one is still not on GISAID. It can also belong to the Switzerland 2nd-level recomb though

I think its coverage is not enough for UK to upload it to GISAID.

**Comment by aviczhl2** [comment]
> > > Scotland/CLIMB-CM7YFQ6T/2023|OY991246.1|2023-12-13, 22928 and 29625 not covered
> > 
> > 
> > That one is still not on GISAID. It can also belong to the Switzerland 2nd-level recomb though

That seq is on usher now. It has 29625C so shall not belong to both recombs.

**Comment by Over-There-Is** [comment]
> > > > Scotland/CLIMB-CM7YFQ6T/2023|OY991246.1|2023-12-13, 22928 and 29625 not covered
> > > 
> > > 
> > > That one is still not on GISAID. It can also belong to the Switzerland 2nd-level recomb though
> 
> That seq is on usher now. It has 29625C so shall not belong to both recombs.

It has no coverage on 29625, and usher guess it as 29625C like BA.2.86.

**Comment by aviczhl2** [comment]
+2 UK

**Comment by FedeGueli** [comment]
> sometimes it would be no coverage on 22928, so there is an alternative query: C1889T, G8393, A17637G

this query catches the swiss sample with 455S and 456V unsure if just base calling of instead not same recombinant. but thx , alternative queries are always welcome here.

**Comment by FedeGueli** [comment]
Using the Dave McNally tool it seems to me there are already 7 of this one (excluding the swiss sample mentioned above):
<img width="1166" alt="Screenshot 2024-01-24 alle 11 46 20" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9193f5e6-ebb0-40f8-a3b3-c76c5de70f96">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2c7a_e4360.json?c=gt-S_455&gmax=25384&gmin=21563&label=id:node_6861116

**Comment by aviczhl2** [comment]
> C1889T, G8393, T22928G

The Scotland sample has S:455,456 missing coverage so unsure whether it belongs to the Swiss re-recomb or this recomb.

**Comment by FedeGueli** [comment]
9  now

**Comment by FedeGueli** [comment]
Pls propose once it reaches 20

**Comment by aviczhl2** [comment]
> 9 now , 10 using the Over' query

That query captures the Switzerland seq that does not belong to this recomb.

**Comment by aviczhl2** [comment]
+2 Sweden

**Comment by aviczhl2** [comment]
@AngieHinrichs, today's build seems to miss the XDD and XDS and assign them back to JN.1.1. What's the cause? Please fix that.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_6025c_303470.json?branchLabel=Spike%20mutations&f_userOrOld=uploaded%20sample&label=id:node_6951529&showBranchLabels=all

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/fa779260-bbdb-4e61-a284-0c77ac365725)

**Comment by AngieHinrichs** [comment]
#1415
