### ISSUE TITLE
Stepwise JD.1.1 with S:N148T(21 seqs, 3 countries) and D287N,N450D(13 seqs, UK)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1268]
JD.1.1+C19185T+C28603T+T16875C+A4222T, T20625C(Orf1a:K1319N)+
C10036T, A22005C, G26158A,G28621A(S:N148T,Orf3a:V256I)

GISAID query: A22005C, G26158A,G28621A
No. of seqs: 19(UK 17 Netherlands 2)

First:EPI_ISL_18525665,  UK, 2023-11-7
Latest: EPI_ISL_18708026, UK, 2023-12-19

+G22421A(S:D287N)+T6957G, A16560G,A22910G, C23086T, C29353T (Orf1a: I2231S, S:N450D)

GISAID Query: A22910G, C23086T, A16560G (13 seqs, UK)

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_70f7_ade130.json?label=id:node_3702986)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/53dca875-4c73-4fe8-9dac-c210177d989f)

**Comment by FedeGueli** [comment]
S:N450D is something going to be very beneficial in this moment. look at it without any BA.2.86/JN:
<img width="1090" alt="Screenshot 2024-01-08 alle 00 48 58" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/31bf2f6e-3884-42bc-b9c5-2bf3d17f716a">

**Comment by FedeGueli** [comment]
It seems fast, luckily could be a cluster (hope so).

**Comment by krosa1910** [comment]
Could resemble some convergence toward the fastest major clan of XBB-JG.3.2* which got its boost from N450D.
N450D could also possibly help it survive better in the soon JN.1*-dominated world.
Overall a very interesting thing to keep observing.

**Comment by FedeGueli** [comment]
also convergent 148T with GE.1.2.1

**Comment by FedeGueli** [comment]
+1 Scotland

**Comment by aviczhl2** [comment]
+1 Finland

**Comment by FedeGueli** [comment]
no new sequence closing it pls reopen it if it will resurge
