### ISSUE TITLE
Another XBB.1.9.1 sublineage with S:H146K and Orf1b:K1383R circulating in United States and other countries(45 seq)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#127]
XBB.1.9.1> C21998A(S:Q146K)> A3069G(Orf1a:D935G)> 5 nuc saltation: A2647G, C11455T, A17615G(Orf1b:K1383R), G27225A, G27870T(Orf7b:E39*)
Query: A2647G, A17615G, G27870T(edited)
Earliest Sequence: 03-15 Honolulu, Hawaii, US EPI_ISL_17617365
Latest Sequence: 05-24 Marin, California, US EPI_ISL_17965952
Regions Detected: US 38(California 23, Hawaii 7, Ohio 3, Utah 2, S. Dakota 1, Minnesota 1, Virginia 1), Japan 3(Tokyo 2, Kyoto 1), France 2(Hauts de France), Canada 1(BC)

[Genome Tree](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_34807_8f95b0.json?label=id:node_6712729)
![2023-06-02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/f8f348a0-0f31-496c-98f4-bed5d5b7f30c)

<details><summary>Sequences:</summary>
EPI_ISL_17423639, EPI_ISL_17429327, EPI_ISL_17430704,
EPI_ISL_17508607, EPI_ISL_17526647, EPI_ISL_17526975,
EPI_ISL_17536098, EPI_ISL_17536100, EPI_ISL_17538163,
EPI_ISL_17556426, EPI_ISL_17558662, EPI_ISL_17585485,
EPI_ISL_17589834, EPI_ISL_17617365, EPI_ISL_17627380,
EPI_ISL_17631972, EPI_ISL_17644269, EPI_ISL_17653477,
EPI_ISL_17677355-17677356, EPI_ISL_17688428, EPI_ISL_17690053,
EPI_ISL_17694132, EPI_ISL_17734764, EPI_ISL_17738091,
EPI_ISL_17743701, EPI_ISL_17778436, EPI_ISL_17789375,
EPI_ISL_17798164, EPI_ISL_17798167-17798169, EPI_ISL_17831761,
EPI_ISL_17846948, EPI_ISL_17847095, EPI_ISL_17860860,
EPI_ISL_17861017, EPI_ISL_17861138, EPI_ISL_17861145,
EPI_ISL_17861481, EPI_ISL_17861490, EPI_ISL_17880097,
EPI_ISL_17965952
</details>

**Comment by Over-There-Is** [comment]
Minnesota +1

**Comment by JosetteSchoenma** [comment]
I mentioned this one here. https://github.com/sars-cov-2-variants/lineage-proposals/issues/97#issuecomment-1562339077

I do not think it is growing fast anymore, but designation (after main branches) might be useful to avoid confusion with the other XBB.1.9.1 alike subbranch with ORF1b:K1383R an S:H146K from issue #2016 (FL.2).

**Comment by Over-There-Is** [comment]
Hawaii +1

**Comment by Over-There-Is** [comment]
Although a "new" sequence EPI_ISL_17759706 is found, it has been submitted for more than a month and actually duplicate to EPI_ISL_17508607.

**Comment by JosetteSchoenma** [comment]
Indeed, @Over-There-Is . It is probably only useful to designate this one, if the FL.2.3 with H146K gets designated. Just to be able to destinguish between the 2 easily.

**Comment by Over-There-Is** [comment]
One more sequence hCoV-19/USA/CA-NSYMMPHL-NSYM7420/2023|EPI_ISL_17789375|2023-05-24 can be find with query `A2647G, A17615G, G27870T`, which was uploaded yesterday.

**Comment by Over-There-Is** [comment]
But that sequence has too many dropouts.

**Comment by Over-There-Is** [comment]
25/33 of this sublineage is identified as FL.2 by GISAID.

**Comment by Over-There-Is** [comment]
4/33 of this sublineage is identified as FL.2.3 by Nextclade, and 3/30 be done so by CovSpectrum.

**Comment by FedeGueli** [comment]
No recent samples closing this one
