### ISSUE TITLE
Weird minor branch of JN.1.44 that seems to harbor   a significant branch with Orf6 deletion Orf6:22-30del (76 seqs at 04-05)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1271]
Branch of JN.1.44 (C27371T=ORF6:P57L)
>Gisaid Search: C27371T,C18894T,T15756A
First Sequence: EPI_ISL_18300149 Netherlands 2023-09-13
Last Sequence: EPI_ISL_18724122 Denmark 2023-12-25
186 total

Gisaid Search for sub-branch: C27371T,C18894T,T15756A, del27265_27291
First Sequence: EPI_ISL_18326669 France 2023-09-23 (Questionable because it disappeared for a while after initial 2)
Third Sequence: EPI_ISL_18674701 Netherlands 2023-10-27
Last Sequence: EPI_ISL_18709946  US, CA 2023-12-18
40 total

Usher Tree for parent: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3265a_c2eb70.json?f_userOrOld=uploaded%20sample

<img width="1243" alt="Screenshot 2024-01-09 at 1 41 07 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/0893cc73-2091-4864-871a-ed2eef845b9b">
Usher tree for child: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3e7d7_c32a80.json?f_userOrOld=uploaded%20sample&label=id:node_2294943

<img width="1243" alt="Screenshot 2024-01-09 at 1 41 41 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/35ca0775-8f92-4273-a337-a4b3ac80e142">

Orf6:22-30del=del27265_27291 seems to be a glitch that happened widely within gisaid sequences, as it showed in all kinds of varaints and across three continents. Yet, among the limited (95 total sequences since 08-28,2023) sequences troubled by this deletion, it seemed to favor the relatively small tree of JN.1*+orf6:P57L, so that it reached 40/186 density, more than 20% here. My intuition is somehow this glitch gets catalyzed by Orf6:P57L+JN.1* setting, but needs further discussion and check.
(PS. Apart from this the parent branch looks quite boring, it is like the 10th first sequence of JN.1* overall and very close to the initial French boom, yet it only reached 185 seqs while JN.1* itself reached like 30k, cov-spectrum is also giving it not very fast growth advantage)
(PPS. This is really unexpected discovery, I was checking a sequence mentioned by Hynn and tried to pull up a random JN.1* for comparison, yet that sequence contained this Orf6 deletion, so I studied it a bit and pull up this issue.)

**Comment by FedeGueli** [comment]
Thanks for spotting this!! i think i met the very first one while looking at orf6 mutations in the very few sequences of Jn.1 (see open discussion issue) but i thought it was completely dead while it is still around!

**Comment by ryhisner** [comment]
Yeah, nice spot. It's definitely real. ORF6 is thought by many to be the most potent accessory protein at evading innate immune responses. But this isn't the first branch to have deleted or lost much of it. And ORF6:D61L significantly limited ORF6's abilities. 

I definitely think there's redundancy in the accessory proteins, but that has always been the case. I'm not sure why there's a growing trend toward large deletions, including ones that entirely erase ORF7a, ORF7b, and ORF8. Perhaps one of the NSPs or structural proteins has gained greater innate immune-evasion powers, making the various accessory proteins less essential.

**Comment by krosa1910** [comment]
> Yeah, nice spot. It's definitely real. ORF6 is thought by many to be the most potent accessory protein at evading innate immune responses. But this isn't the first branch to have deleted or lost much of it. And ORF6:D61L significantly limited ORF6's abilities.
> 
> What's remarkable is that even just on other branches of this ORF6:P57L lineage, there's a frameshift-causing deletion and a start codon mutation in ORF6. Also a few ORF6:∆I17. Very strange. I wonder if P57L further crippled ORF6 so that it's now disposable.
> 
> I definitely think there's redundancy in the accessory proteins, but that has always been the case. I'm not sure why there's a growing trend toward large deletions, including ones that entirely erase ORF7a, ORF7b, and ORF8. Perhaps one of the NSPs or structural proteins has gained greater innate immune-evasion powers, making the various accessory proteins less essential.

Yeah, there is a few thing with a weird frameshift at position 31, and some of the sequences even combine the frameshift with the deletion to create a long and non-3-multiple deletion. It deserves some investigation.

**Comment by krosa1910** [comment]
Updated to 217 and 45 with large uploads in Sweden.

**Comment by FedeGueli** [comment]
51 now

**Comment by FedeGueli** [comment]
The parental Orf6:P57L now designated JN.1.44 , issue edited

**Comment by FedeGueli** [comment]
closing this one
