### ISSUE TITLE
JN.7 + S:T20A, S:N30G/HK.26 Recombinant (4 seq, Denmark, Jan 8)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1274]
### **Description**
**Recombinant of:** JN.7 (BA.2.86.1.7) and HK.26 (EG.5.1.1.26)
**Earliest sequence:** 2023-11-27, Denmark — EPI_ISL_18617579
**Most recent sequence:** 2023-12-18, Denmark — EPI_ISL_18721530
**Continents circulating:** Europe (4)
**Countries circulating:** Denmark (4)
**Number of Sequences:** 4
**GISAID Nucleotide Query:** A21650G, A21651G, A4576T, C25546A 
**CovSpectrum Query:** [9-of: C2334T, A4576T, G8393A, A21620G, A21650G, A21651G, C22352A, A22556G, T22896A, G23342A, C25546A, C25708T, C25572T, C29625T]
**Substitutions on top of JN.7:**
**Spike:** T20A, N30G
**Nucleotide:** T10273C, A21620G, A21650G, A21651G

**HK.26:** 1-3431
**Breakpoint 1:** 3431-4575
**JN.7:** 4576-23604
**Breakpoint 2:** 23604-23477
**HK.26:** 23478-end

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.7_N30G__EG.5.1.3_Recomb.json?c=gt-S_30&gmax=25384&gmin=21563&label=id:node_6812098 

<img width="1419" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/89a096ce-b0fc-4fdc-b223-4f8c26cc1394">

**Evidence**
This was one of my favorite branches of JN.7. It strangely had three A->G mutations early in the spike NTD, already quite a busy area in BA.2.86*, forming S:T20A and the 2-nucleotide S:N30G. But unfortunately, this JN.7 branch started on September 18 and ended on October 23 producing only 10 sequences total. 

<img width="1317" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/80b78f3e-ee1f-43cd-a657-722cebc0bdc3">

However, it lives on in modified form, having swapped its 5’ end and 3’ end for chunks of HK.26. It’s not exactly setting the river on fire. It currently sits at 4 sequences, averaging less than one per week, all in Denmark. The most recent two sequences were collected on December 18 (uploaded January 5). 

I think it’s the most interesting BA.2.86* recombinant so far, but it’s hanging on for dear life. We’ll see if it’s still alive this week when the next major Denmark upload comes. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18617579, EPI_ISL_18693230, EPI_ISL_18721514, EPI_ISL_18721530
</details>

**Comment by aviczhl2** [comment]
Seems that the middle one (Orf1a:S505F,T602I) is also unproposed.

**Comment by FedeGueli** [comment]
No new seqs closing it

**Comment by FedeGueli** [comment]
@ryhisner i ve updated  the query to get the sample you found yesterday from Philippines: A21650G, A21651G,  T10273C,C25572T , 5 samples total
