### ISSUE TITLE
GL.1+S:Y144- sublineage with ORF1a:A3392T (68 seqs , 3 countries.)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#1275]
Defining mutations: GL.1 then S:Y144- then nuc:C5239T then ORF1a:A3392T(G10439A)
Query: G10439A, C5239T (edited) 
Trees:
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/7e46a76c-bc56-4a86-af27-f595cea6b028)
![2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/d8ad39d7-07ae-4547-a9e4-09edbd26fb4b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43b23_d19640.json?c=gt-ORF1ab_3392&gmax=21555&gmin=266&label=id:node_2789186
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF1a%3AA3392T&
This subbranch has been circulating in South Korea for months.
ORF1a:A3392T is a rare nsp5 mutation, which is near ORF1a:P3395H. It has 3 nsp5 mutations now (the other one is ORF1a:Q3346K).

**Comment by FedeGueli** [comment]
Thank u OObb noticed this too, i think it has already recombined too (spotted by @ryhisner and analyzed privately  along with @aviczhl2 ) i ve added a query : G10439A, C5239T

**Comment by oobb45729** [comment]
> Thank u OObb noticed this too, i think it has already recombined too (spotted by @ryhisner and analyzed privately together with @aviczhl2 ) i ve added a query : G10439A, C5239T

Recombined with which other lineage?

**Comment by FedeGueli** [comment]
> > Thank u OObb noticed this too, i think it has already recombined too (spotted by @ryhisner and analyzed privately together with @aviczhl2 ) i ve added a query : G10439A, C5239T
> 
> Recombined with which other lineage?

with HV.1  cc @ryhisner  could i share the IDs you found here?

**Comment by FedeGueli** [comment]
No sample from February closing it and 2 only from Jan
