### ISSUE TITLE
JN.1.1 (BA.2.86.1.1.1) 16-nuc saltation seq with S:G261A, S:D264A rev, S:F456V, S:I468N, S:S477N->D, S:Y489F and 6 non-Spike aa mutations (single seq in Italy, collected in 2023-12-19)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1278]
Defining mutations:
JN.1.1>C11747T>C9142T>saltation branch 
nuc and AA mutations:
ORF1a: C4069T, C4999T, A11951T (ORF1a:N3896Y), G11954T (ORF1a:D3897Y)
ORF1b: C19951A (ORF1b:P2162T)
S: G22344C (S:G261A), A22353C rev (S:D264A rev), T22928G (S:F456V), T22965A (S:I468N), A22991G (S:S477N->D), A23028T, C23029T (S:Y489F, 2-nuc)
ORF8: C28000T (ORF8:P36L)
N: G29405A (N:E378K), G29414T, C29416A (N:A381S)

GISAID query: T22965A, A23028T, C23029T
Gisaid query (spike independent): C4069T, C4999T,C19951A (edited)

Usher Tree:
![联想截图_20240110210400](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/4cb909a3-66bc-4f93-a97f-01001f9c34e6)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40f4c_e57db0.json

**Notice that Usher does not show the S:Y489F, and clades-nextstrain suggests the frameshift in N gene
![联想截图_20240110210509](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/c3872a30-f873-497f-adbf-8aaf868db60f)
![联想截图_20240110210454](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d564de64-781e-4857-83e0-9565c87c7854)

Despite JN.1* becomes the dominant variant recently, the saltation seqs are relatively few. the seq shows 4 RBD mutations, including the 2-nuc S:S477N->D and S:Y489F, and the another choice of S:F456 (F456V). We can monitor it for a time.

Genomes:
EPI_ISL_18736029

**Comment by FedeGueli** [comment]
I have added a spike independent query: C4069T, C4999T,C19951A

**Comment by FedeGueli** [comment]
Usher masks S:489 so it is not there for this reason i think ( cc @angiehinrichs maybe if this grows better to unmaask it in this branch?)

**Comment by jbloom** [comment]
In Yunlong Cao's deep mutational scanning, site 489 is a **major** antibody escape mutation (https://jbloomlab.github.io/SARS2-RBD-escape-calc/). But at least in XBB.1.5 and BA.2, mutations at site 489 are very bad for ACE2 binding affinity (https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/). I suppose we can't rule out possibility of some epistasis that alleviates that in JN.1.

**Comment by FedeGueli** [comment]
> In Yunlong Cao's deep mutational scanning, site 489 is a **major** antibody escape mutation (https://jbloomlab.github.io/SARS2-RBD-escape-calc/).
> 
> But at least in XBB.1.5 and BA.2, mutations at site 489 are very bad for ACE2 binding affinity (https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/).
> 
> I suppose we can't rule out possibility of some epistasis that alleviates that in JN.1. But it is also possible that the mutation at site 489 will make this a low-fitness variant despite antigenic escape.

Thank you! Also being a singlet could be just a sequencing mess, but better tracking it from the start

**Comment by cvejris** [comment]
note that many of the mutations are not the (by large) most frequent C→T, T→C, G→A or A→G, so this might be a highly evolved combo that somewhat "works"

**Comment by oobb45729** [comment]
S:I468N creates a new N-glycan site.

**Comment by ryhisner** [comment]
I think most or maybe all of the mutations here are artifacts. This sequence was part of an upload from the Lombardy lab that had a tom of low-quality sequences, and there's a lot of dropout in the areas near the spike mutations here—S:459-461 and S:491-510, for example. There's also a suspicious cluster of mutations near the end of N—G20405A, G29414T, C29416A. This resembles s lot of other sequences with probable artifacts from this upload from that lab. 

Here's the Nextclade nucleotide view of the 18 sequences from this upload from that lab.
<img width="1512" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/82237037-09ab-4215-adb6-662dc8f061af">

And here's a view of the spike proteins from the same upload along with the Nextclade QC scores. 
<img width="1506" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/dae39f58-5796-442a-97da-72f238e433ba">


The following nucleotide regions are missing from the sequences: 473-653, 3483-3496, 5414-5417, 5760-5813, 6224-6393, 7188-7387, 9129-9130, 11032-11112, 11231-11252, 11405-11470, 11657-11672, 11877-11925, 11987-12243, 13339-13350, 16260-16301, 21055-21062, 21216-21304, 22938-22945, 23033-23092, 23291-23365, 23966-24097, 28135-28187, 29438-29481, 29605-29856

And here are the corresponding unknown AA: N:34-420, ORF1a:70-130, ORF1a:1073-1077, ORF1a:1717-1718, ORF1a:1832-1850, ORF1a:1987-2043, ORF1a:2308-2374, ORF1a:2955, ORF1a:3589-3616, ORF1a:3656-3663, ORF1a:3714-3735, ORF1a:3798-3803, ORF1a:3871-3887, ORF1a:3908-3993, ORF1a:4358-4362, ORF1b:931-945, ORF1b:2530-2532, ORF1b:2583-2613, ORF8:81-98, ORF9b:30-98, S:459-461, S:491-510, S:533, S:577-601, S:802-845

**Comment by ryhisner** [comment]
There's also another JN.1 sequence with a bunch of unusual spike mutations in the 18-sequence upload from this lab. I think they're all likely artifacts. 

<img width="1401" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e7734924-1f5a-4f04-b157-bec25712950b">

Here are a couple other unlikely alleged spike mutations in this upload. I would just dismiss everything from this upload. I don't think any of it can be trusted. 
<img width="1353" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2f62a8f8-b6bf-4a79-8e23-a8a2e8e2ce2b">

**Comment by Memorablea** [comment]
> There's also another JN.1 sequence with a bunch of unusual spike mutations in the 18-sequence upload from this lab. I think they're all likely artifacts.

I think so

**Comment by FedeGueli** [comment]
Dead
