### ISSUE TITLE
BN.1/XBB.1 + S:486P+ Orf8:G8* + orf9b:I5T recombinant [1 Belarus/Shanghai, 1 England, 3 Lithuania as of 2023-06-02]

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#128]
Came across this doublet of sequences from Shanghai and England, looking like they are the same recombinant:
```
hCoV-19/Shanghai/SCDC-HG-0518-887/2023|EPI_ISL_17725101|2023-05-17
hCoV-19/England/PHEC-YYEAHG9/2023|EPI_ISL_17721826|2023-05-14
```

Not sure anyone has spotted these already.

<img width="2032" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/07dfad93-5742-4af0-ac0b-28ad634ba522">

<img width="766" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/58719087-95d0-4afb-bee8-4d8b2e4959c6">

<img width="1950" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/311aef72-a2ed-48a6-a143-0dd1614d683d">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1930d_91a900.json

Gisaid query: T4744C,T7477C  (the coolest ive ever seen, edited by Fed)

**Comment by FedeGueli** [comment]
Today i have found another of the same kind , but unrelated BN.1.2.3/XBB.1+Orf8:G8*
![Schermata 2023-06-02 alle 02 25 49](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1ba271ef-0386-46e4-8d1e-f71e11dee8f2)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35594_84d460.json?c=gt-ORF1ab_47&label=id:node_7234439

**Comment by corneliusroemer** [comment]
But yours is a singlet @FedeGueli, singlets are much more boring than something discovered on opposite sides of the world ;)

**Comment by corneliusroemer** [comment]
Here's another one, now Lithuania 👀 
hCoV-19/Lithuania/MB230509-0128/2023\|EPI_ISL_17742697\|2023-05-02

**Comment by FedeGueli** [comment]
Same tree so i ll update the title

**Comment by FedeGueli** [comment]
@corneliusroemer having Orf9b:I5T and being sequenced from very far places in the globe i suggest you to propose. Set yourself the nr of sequences to be reached.

**Comment by Over-There-Is** [comment]
Belarus?!

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/HG20230518-887/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 49"
                     /country="China:Shanghai"
                     /collection_date="2023-05-17"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Belarus"

**Comment by FedeGueli** [comment]
> Belarus?!
> 
> ```
>                  /organism="Severe acute respiratory syndrome coronavirus 2"
>                  /mol_type="genomic RNA"
>                  /isolate="SARS-CoV-2/human/CHN/HG20230518-887/2023"
>                  /isolation_source="Pharyngeal swab"
>                  /host="Homo sapiens; Host_age: 49"
>                  /country="China:Shanghai"
>                  /collection_date="2023-05-17"
>                  /note="Passage_details/history: Original;
>                  Additional_host_information: Patient infected while
>                  traveling in Belarus"
> ```

thx it makes sense

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0ff6e99d-dc56-4acd-bc50-57a9baa07524)

There seems to be a side branch of this. Another BN.1/XBB recombinant locally in China.

**Comment by Over-There-Is** [comment]
24 now

**Comment by FedeGueli** [comment]
reopening this for a while. @corneliusroemer this kept circulating in Lithuania

**Comment by FedeGueli** [comment]
Designated XDH
