### ISSUE TITLE
EG.5.1.8+Orf1a:S2114F+2-nuc S:H49S in SE Asia (9 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1281]
EG.5.1.8+C12100G+C6606T(Orf1a:S2114F)+C21707T, A21708C(S:H49S)

GISAID query: C6606T, C21707T,A21708C
No. of seqs: 8( Myanmar 1 Malaysia 1 Singapore 6(1 from Thailand))

First: EPI_ISL_18361895, Singapore from Thailand, 2023-9-30
Latest: EPI_ISL_18744371, Myanmar, 2023-12-19

Note that most SE Asia countries are heavily undersampled. 
Myanmar only uploads 16 seqs collected after 2023-11. Thailand 94 but 0 are after 12-1. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice8_genome_test_37c25_ff0210.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/43d462c8-63e2-4d9f-a7f7-a0466013744e)

**Comment by FedeGueli** [comment]
No new sequence in a while.

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
No new seqs
