### ISSUE TITLE
XCT+ins28389AAG (N:ins371K)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1283]
Spotted by @ryhisner , ins28389AAG is very rare, but it seems that this mutation is widely distributed among multiple branches of XCT. 

Open a thread for discussion about possible reasons. @corneliusroemer @AngieHinrichs @FedeGueli 

Uploaded are seqs with ins28389AAG (GISAID query: ins28389AAG)

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_f112_b7c20.json?f_userOrOld=uploaded%20sample)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/15892dca-de1b-44ff-865e-75ced8c8a5de)

**Comment by FedeGueli** [comment]
Just thinking aloud and listing some data: the insertion is present in mainly two branches XCT.1  and #1086 with S:S151R . All the three lineages XCT XCT.1 and #1086 arose  in the same time frame in Germany/Austria . XCT has been involved in tracked recombinations multiple times.

**Comment by ryhisner** [comment]
This insertion is similar to a number of others that involve an RdRp stutter. There are multiple repeats of a certain sequence, and an extra one gets stuck in on rare occasions. Other examples include N:ins283Q, ORF3a:ins103P, and several insertions in the hypervariable/acidic domain of NSP3 that I can't recall off the top of my head. There are some examples in spike as well, somewhere around AA residue ~255 if I remember right.  

In this case, "AAG" is repeated three consecutive times. 
<img width="762" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c5ba4b31-611e-4e4d-ad9b-900ad9e623aa">
