### ISSUE TITLE
XBB.1.16.11 with (possible G20055A reversion,) S:A701V (45 seqs, Russia)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1284]
**Defining Mutations:** `XBB.1.16.11 (with T25496A/ORF3a:I35K)` > `C28819A` > `A23092T(S:V510V), C28789T` > _**`G20055A_reversion`**_ > `C23664T(S:A701V)`
**Query:** `C23664T, T25496A, C28789T, -A20055G`
**Earliest seq:** 2023-10-30 (`EPI_ISL_18685596`, Vologda, Russia)
**Latest seq:** 2023-12-05 (`EPI_ISL_18736924`, Vologda, Russia)
**Sampled Countries:** Russia (45: VLG)

<details><summary>Genomes: </summary>

`EPI_ISL_18685542, EPI_ISL_18685550, EPI_ISL_18685565, EPI_ISL_18685596, EPI_ISL_18685604, EPI_ISL_18685607, EPI_ISL_18685620, EPI_ISL_18685634, EPI_ISL_18685636, EPI_ISL_18685660, EPI_ISL_18685672, EPI_ISL_18685707, EPI_ISL_18685717, EPI_ISL_18736856, EPI_ISL_18736868, EPI_ISL_18736873, EPI_ISL_18736879, EPI_ISL_18736882, EPI_ISL_18736884, EPI_ISL_18736890, EPI_ISL_18736899, EPI_ISL_18736913, EPI_ISL_18736915-18736916, EPI_ISL_18736921, EPI_ISL_18736924, EPI_ISL_18736934, EPI_ISL_18736956, EPI_ISL_18736958, EPI_ISL_18736966, EPI_ISL_18736970, EPI_ISL_18736983, EPI_ISL_18736991, EPI_ISL_18737000, EPI_ISL_18737002-18737003, EPI_ISL_18737016, EPI_ISL_18737021, EPI_ISL_18737023, EPI_ISL_18737042, EPI_ISL_18737339, EPI_ISL_18737349, EPI_ISL_18737356, EPI_ISL_18737367, EPI_ISL_18737371`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12aad_dcc80.json?f_userOrOld=uploaded%20sample&label=id:node_3241348

view from `XBB.1.16.11`'s `ORF3a:I35K/T25496A` polytomy with `nuc_20055` genotype filter
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3f625c7f-bfdb-424d-955e-d4bb8ab67705)

details
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ab92ff53-7f04-494d-a3b7-dbb2369e2c29)

**Trivia:**
- XBB.1.16.11 is an ongoing and huge one (over 8k seqs, hence unable to display the full sub-tree on UShER) that has not seen any of its sub-lineages designated. One of the few lineages in circulation without much additional spike mutations.

<details><summary>Slightly downsampled XBB.1.16.11 tree</summary>

![dsp](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2627e3c5-140f-4fce-9286-ec3c9a68e544)</details>

- Digging into its destination history, it seems to be [composed by at least 2 or 3 different lineages](https://github.com/cov-lineages/pango-designation/issues/2058#issuecomment-1601812931) from the start.
- `A20055G` is introduced since `BA.2`, and it is not represented in `BA.1*`, this woluld be interesting if the reversion is not an artifact.
![G20055A_rev](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/af58e443-86be-46d6-9935-3d47fff89445)
- However, there are 3 seqs that come with `S:A701V` and `A20055G`, these seqs are all outside Vologda region, which makes the reversion skeptical:

```
Russia/SVE-RII-MH145072S/2023|EPI_ISL_18417036|2023-09-20
Russia/SAM-MH155514S/2023|EPI_ISL_18736944|2023-11-13
Russia/SPE-4469S/2023|EPI_ISL_18736268|2023-11-19
```

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
Likely dead
