### ISSUE TITLE
3 seqs of Sandwich of GL.1* (#1275) within a supposedly HV.1 unnamed division skeleton  (48+3 seqs)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1285]
Gisaid Search for the HV.1* donor of this branch: C6593T,T23198C,(-A22320G if you want not the recom ones)
Mutations added compared with HV.1*: G1696A, T4149C, C4633T, C6593T, T23198C
Earliest Sequence: EPI_ISL_18539029 South Korea 2023-11-02
Latest Sequence: EPI_ISL_18752165 South Korea 2023-12-13
Distribution is limited to South Korea now, but the thing spanned over a long time so it is likely not caused by cluster sequencing.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_d06d_10ce70.json?f_userOrOld=uploaded%20sample
<img width="1447" alt="Screenshot 2024-01-12 at 5 57 24 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/2842f72a-d25d-46df-94e2-0fbf1a02dc18">
(image of the "HV.1 parts without the 3 recombination branch)

Recombination Gisaid Search: C19220T,C22664A,A21623G
Sequence Numbers:EPI_ISL_18752070, EPI_ISL_18712197, EPI_ISL_18712007
The thing does look like a good tree although hard to tell a lot at 3 seqs.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_cddd_10a100.json?f_userOrOld=uploaded%20sample
<img width="1256" alt="Screenshot 2024-01-12 at 5 49 59 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/0425545c-a780-4ebc-9e5d-10bcbd52d40f">
Cov-spectrum listed those documented changes that are incompatible with HV.1*
C44T,A385G,G407A,C4456T (GL.1 Part 1),C6593T (seemingly private belongs to HV.1* donor),C16466T,C19220T,C19441T,G20679T,C21614T,C21618G,A21623G,C21846T,G22017T,A22029-,G22030-,T22031-,T22032-,C22033-,A22034-,T22118C,T22200G,A22320G,(GL.1 Part 2) T23198C (Seemingly private belongs to HV.1* donor)

A result I ran to compare these three seq with the results of another two searchs as C6593T,T23198C,-A22320G (48 seqs, the proposed HV.1* branch) and South Korean GL.1* as C16466T,A22320G,-C6593T
GL.1*: head-C4456T breakpoint very likely before the wildly popular C5239T (all Korean GL.1* carries it although not defining of GL.1*)
HV.1*:  G5720A-C15738T
GL.1*: C16466T-S:D253G=A22320G breakpoint very likely after T22480C, the defining EG.5.1* mutation.
HV.1*: S:D339H=G22577C-end
Whole Genomes
<img width="1447" alt="Screenshot 2024-01-12 at 6 10 03 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/bba6fa6e-004a-42b8-aab7-14cae7e4d469">
Orf1a (for first breakpoint)
[
<img width="1447" alt="Screenshot 2024-01-12 at 6 08 24 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/44c8d8a3-1303-4207-9a8a-d52b76da688f">
](url)
 Orf1b (for second breakpoint)
<img width="1447" alt="Screenshot 2024-01-12 at 6 08 43 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/e4858bd4-8777-46fb-8724-e461f8e3a222">
[](url)
S (for third breakpoint)
<img width="1447" alt="Screenshot 2024-01-12 at 6 08 50 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/005124f0-c029-4628-b076-3be861d22c81">

**Comment by krosa1910** [comment]
The GL.1* donor is described by #1275 well (it seems to be the dominant form of GL.1* in East Asia so I believe it is involved here), and Ryan and Fed seems to find this recombination before

**Comment by FedeGueli** [comment]
> The GL.1* donor is described by #1275 well (it seems to be the dominant form of GL.1* in East Asia so I believe it is involved here), and Ryan and Fed seems to find this recombination before

spottewd by @ryhisner discussed earlier with @aviczhl2 and you i think!

**Comment by FedeGueli** [comment]
No new sequence . let's wait a bit more till S.Korea uploads a new batch.

**Comment by FedeGueli** [comment]
likely dead closing it
