### ISSUE TITLE
Weird Thai singlet with 445P, 453F, 478T, 484K, 486P, Nextclade BA.2.9

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#129]
hCoV-19/Thailand/NIC_BKK_2345/2023|EPI_ISL_17661709|2023-05-03

<img width="782" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/5692e539-e0c5-4ac0-9f66-c74ccb08fd0d">

Very strange sequence, couldn't find any relatives.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer It was spotted first by Ryan on May 16 and then it was rediscovering the wheel by a bunch of us! but good to have it here i ll keep it monitored.

**Comment by FedeGueli** [comment]
No new sample closing it for now
