### ISSUE TITLE
XBB/XDP recombinant(50 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1290]
There seems to be a side branch of [XDP](https://github.com/cov-lineages/pango-designation/issues/2451), either formed by recomb of any XBB* and XDP, or via FL.15/JN.1/FL.15 sandwich recomb.

XDP+A405G,T774C(rev)

Orf1a: K47R, I170T(rev)

XBB*--XDP  (likely)
Breakpoint between 775 and 896

Or

FL.15--JN.1.4--FL.15
Breakpoint 1 between 775 and 896
Breakpoint 2 between 26834 and 27809

GISAID query: T3565C, C28846T, G27915T, A405G
No. of seqs: 4(USA)
First: EPI_ISL_18621270, 2023-11-27
Latest: EPI_ISL_18752886, 2024

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1494_201ab0.json)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6c0fb150-6fa2-4c55-b719-097b3a4860ef)

**Comment by aviczhl2** [comment]
6 seqs now. 
They have T18453C so the JN.1 donor shall be JN.1.4.

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
Dying or dead

**Comment by corneliusroemer** [comment]
Still around!

**Comment by aviczhl2** [comment]
+5 Apr/May seqs, total 50 now. 

@corneliusroemer , do you consider designate?

**Comment by aviczhl2** [comment]
Designated XEB
