### ISSUE TITLE
BA.2.86.1/FL.15.1.1 recombinant (22 seqs, 9 countries, 3 with S:A475V)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1291]
BA.2.86.1+
C7420T,T22846C,  T24378C(rev), T24990C(rev), T25207C(rev),C25416T, A26275G, C26529G(rev), T26681C(rev), T26833C(rev),G27915T, A27980G,T28297C, C28846T,A28958C(rev),T29023C

S:F939S(rev),L1143P(rev)
E:T11A
M:H3D(rev),V104A(rev)
Orf8:G8*
Orf9b:I5T
N:K229Q(rev)

BA.2.86.1--FL.15.1.1
breakpoint between 23605 and 24377

C7420T from a BA.2.86.1* branch, many candidates
T24378C(rev), T24990C(rev), T25207C(rev),C25416T, A26275G, C26529G(rev), T26681C(rev), T26833C(rev),G27915T, T28297C, C28846T,A28958C(rev) from FL.15.1.1
T29023C from a FL.15.1.1 branch
T22846C,A27980G is private

GISAID query: C28846T,C23604G,C7420T,T28297C,(edited)
No. of seqs: 5(South Korea 3 Japan 1 UK 1)

First: EPI_ISL_18598081, 2023-11-14, South Korea
Latest: EPI_ISL_18751683, 2023-12-26, South Korea

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2321f_218d90.json?label=id:node_11172443)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8456e029-5832-488f-a04a-794e606f56e3)

**Comment by aviczhl2** [comment]
+1 Singapore from Hong Kong

**Comment by Over-There-Is** [comment]
KR3 JN2(1 from Vietnam) UK1 SG1(1 from HK, China), totally 6 countries

**Comment by Over-There-Is** [comment]
https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_664cc_695f20.json?c=country&label=id:node_6829602
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/646c45b3-8d74-444f-ab6f-d7cf4fd4ccb1)

**Comment by Over-There-Is** [comment]
the most recent sequences don't have T22846C.

**Comment by Over-There-Is** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/418264c4-3c0c-47cd-a1ec-00c8b9174ce3)

**Comment by FedeGueli** [comment]
thx @Over-There-Is

**Comment by Over-There-Is** [comment]
EPI_ISL_18775734 SEA Airport, Washington, US, From Japan

**Comment by aviczhl2** [comment]
+1 Sweden

**Comment by aviczhl2** [comment]
It seems that 2 of the seqs have additional S:A475V, which is interesting.

**Comment by FedeGueli** [comment]
the most recent sample from Singapore has S:N487D
img width="520" alt="Screenshot 2024-01-21 alle 12 12 48" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fe78254e-c255-4c22-819d-21fa62b7c682">

**Comment by FedeGueli** [comment]
it seems widespread geographiclly , lets wait few days we will likely se more of this popping up.

**Comment by aviczhl2** [comment]
+1 Fujian from Taiwan
+4 Singapore

**Comment by FedeGueli** [comment]
thx @aviczhl2 please propose when. it tops 20.

**Comment by Over-There-Is** [comment]
![2024-01-24 (3)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/77d9d314-3887-4704-a47c-a410d0809196)

**Comment by Over-There-Is** [comment]
All the new sequences have C or Y on 22846.

**Comment by FedeGueli** [comment]
apparently fast: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=A27980G%2CC28846T%2CC23604G&analysisMode=CompareToBaseline&

**Comment by Over-There-Is** [comment]
Taiwan/CDC-W35453/2024|EPI_ISL_18838513|2024-01-13 27980dropout

**Comment by Over-There-Is** [comment]
> thx @aviczhl2 please propose when. it tops 20.

20 now

**Comment by Over-There-Is** [comment]
It's time to propose it.
![2024-01-31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/78db1962-f046-49d4-b79a-4f0ce4a73c8d)

**Comment by aviczhl2** [comment]
+1 Japan
+1 USA from Qatar

**Comment by FedeGueli** [comment]
Designated XDQ via https://github.com/cov-lineages/pango-designation/commit/ce9f9d0c8b16d357e72e18f706a262802447f2db
