### ISSUE TITLE
DY.1 with N1/N2 PCR-test escaping mutations(C28311T,A28330G,C29200T) together with lots of orf1ab mutations emerging in Shanghai (57 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#13]
Migrated from https://github.com/cov-lineages/pango-designation/issues/1899

I noticed that a branch of DY.1 shows quite high prevalence in Shanghai's recent sequences of 3.10-4.10(21/311). Interestingly it has the PCR-test escaping mutation C29200T (on top of the BA.5.2's C28311T and A28330G.)

sub-lineage of: DY.1
mutations on top of DY.1: C6618T,C9611T(orf1a:L3116F), C20759T(orf1b:A2431V), C2388T(orf1a:T708I),G11417T(orf1a:V3718F), T20028C,C29200T
GISAID query: T20028C,C29200T,G11417T
No. of seqs: 40 (all in Shanghai)

**Comment by FedeGueli** [comment]
It seems slower than other circualting lineages. if nothing changes i will close this down at the end of this month

**Comment by aviczhl2** [comment]
No new seqs so close down

**Comment by aviczhl2** [comment]
Jiangsu uploads 1 of this too.

**Comment by FedeGueli** [comment]
@aviczhl2 to me this should be closed for now. it is clearly dying off.  If you have other reasons to keep this open please write here back.
