### ISSUE TITLE
AY.124 singlet, ~30 spike mutations, Portugal - collected 2023-12-22

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1300]
### **EPI_ISL_18766752** 

Usher Tree Link: https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/AY.124_Delta_Portugal_2023-12-22_Usher.json?c=gt-M_19&gmax=27191&gmin=26523&label=id:node_9495887 

<img width="1383" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/08ba583a-2903-4025-9c45-4104fa47d4e1">

Despite having a lot of dropout, this Delta has 29-31 spike mutations (depending on how you count). Normally, I don't put a lot of weight in sequences labeled as being from "random surveillance" or "representative sampling" because I've seen clearly targeted sequencing—as in repeated sequencing of known chronic patients or in Canadian nursing homes—labeled that way. But Portugal is maybe the best country at labeling their sequences. In my experience, when they do targeted sequencing or non-random surveillance, they label it that way. So I tend to believe that this sequence was obtained from representative surveillance. 

Of course, that doesn't mean that this is circulating, and in all likelihood, it is not. It's almost certainly a chronic infection confined to a single individual. But if it really was obtained through random surveillance, I think that's another indication of just how widespread these very long-term chronic infections are. 

Below is my summary of the private mutations in this sequence. Private mutations were identified with the help of Usher while the dropout stats were obtained through Nextclade. 
<img width="1459" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/8cbde251-612b-42ef-8b93-32bcfdf350b4">

**Private nucleotide mutations** - (R) = Reversion
G1126T, C1812T, C2113T, C2445T, C5192T, A8452G, G8747T, G9756A, C10977T, C11020T, G11426A, G12793T, C13971T, C18647T, G21618C (R), C21648T, T21752C, C21846T, G21974T, G22100A, C22208T, C22224T, G22599A, A22600C, A22771C, T22882G, G22898A, T22907A, G22917A, C22986T, A22995C, G23012A, T23019C, A23055G, A23063T, G23417A, C23423T, C23525T, C23595T, C24138A, C24771T, C25294T, C26111T, G26529C, G26538A, A26579T, C26895T A27372G, C27638T (R), C27732T, G27762C, C28311T

Some noteworthy aspects:
**• ORF7a:A82V reversion** -  This is the single most common mutation in chronic-infection Deltas—by a long shot. It might be in 50% of them. This seems hard to square with the frequent large ORF7a deletions, stop codons, and TRS-destroying mutations that have occurred frequently over the last few years. But there are several other ORF7a mutations convergent in chronics (E22D, N43X, S81P, L96P, A105V), so it clearly is doing something in these patients. It seems likely that in some genetic and individual contexts ORF7a is disposable, while in other contexts, it performs a vital function, likely involving immune evasion.
**• 45/52 nucleotide mutations (86.5%) are non-synonymous** - This is a typically high percentage in chronic sequences like this, evidence of the positive selection at work. 
**• S:Q498R-N501Y** - This is just the 2nd Delta ever to have this combination. The other was the legendary Indonesian Delta of #437. In fact, outside of Omicron, very few the Q498Y-N501Y combo, which enormously increases ACE2 binding strength, has only ever appeared in a handful of sequences, something that has always seemed something of a mystery to me, particularly given the number of non-Omicron variants that have had S:N501Y.
**• S:K478T** reversion - This is another mutation this Delta shares with the Indonesian Delta. 
**• S:R346N** - This 2-nuc mutation is very rare and has only been seen in a few other chronic-infection sequences. It can be obtained by R->S->N or R->K->N. 
**• S:R403S** - This is another extremely rare mutation that seems only to show up in long-term, highly mutated chronic-infection sequences. 
**• ∆A372** - This should result in a glycan due to N370-S373 forming the N-(not-P)-S/T pattern. S:A372T and S:A372S  are seen in some of the most extreme chronic-infection and cryptic-wastewater sequences. S:A372T is also present in all or nearly all Bat-CoVs and in SARS-CoV-1. This was noted in a 2021 study in Cell. A:A372T greatly reduces ACE2 binding and infectivity in Calu-3 cells, though it grew similarly to D614G in Vero E6 cells. It seems S:A372T likely influences the open/closed state of the RBD; perhaps it favors the closed state and this is the cause of the reduced ACE2 affinity? Perhaps this functions in a similar way to the S371F-S373P-S375F triple-mutation in BA.2 & its descendants? I think every study I've seen has shown each of the 371-373-375 mutations—and all three collectively—to reduce infectivity in the lab. Yet these mutations seem locked in in circulating lineages. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8260498/
Kang L, He G, Sharp AK, Wang X, Brown AM, Michalak P, Weger-Lucarelli J. A selective sweep in the Spike gene has driven SARS-CoV-2 human adaptation. Cell. 2021 Aug 19;184(17):4392-4400.e4. doi: 10.1016/j.cell.2021.07.007. Epub 2021 Jul 7. PMID: 34289344; PMCID: PMC8260498.
<img width="1485" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/839762d0-f5ad-4e8d-8828-2cbde6914459">
<img width="1433" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9729c367-7c89-4d3d-bba1-1a1eb3837e45">

I've probably made some mistakes somewhere above, so feel free to point them out and I'll do my best to correct them.

EDITED: putative queries: G1126T, C1593T, C1812T or  G26529C, G26538A, A26579T

**Comment by FedeGueli** [comment]
> EDITED: putative queries: G1126T, C1593T, C1812T or G26529C, G26538A, A26579T

i have added two putative queries for this from two different area of the genome to be sure of not missing any sequence. Thx Ryan for the great analysis! 
I would add that this particular branch of AY.124 was a "portuguese one" that makes me think to chronic infection rather than import from an undersampled area ( that should have not surprised me too much considering BA.5.1 landed in Portugal first with one month of advantage vs other european countries) : https://github.com/cov-lineages/pango-designation/issues/281#issuecomment-961936817

**Comment by ujoshi4** [comment]
I don't think it can compete with Jn.1. It has way less mutations and seems to have way less coverage against prior immunity. If it is able to compete, it could be a problem, because it is set up a bit differently than omicron and can pick up novel mutations and have "fast" descendants.

**Comment by FedeGueli** [comment]
It seems dead luckily
