### ISSUE TITLE
JN.11 (BA.2.86.1+S:V1104L)with S:L455S (25 sequences 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1303]
It seems that there's another BA.2.86+S:V1104L branch likely emerged in SE Asia, with S:L455S it effectively reproduces the current fastest spike of JN.1.11.

BA.2.86.1+G24872T(S:V1104L)

GISAID query:A6183G,G24872T,-27810,-7528,-8456,-A405G
No. of seqs: 72(Australia 9 Canada 1 UK 1 France 6 Indonesia 3 Japan 6 Malaysia 1 Singapore 21(1 from Malaysia), South Korea 6 Sweden 1 USA 15(1 from UAE) China 1 Vietnam 1)

First: EPI_ISL_18499092, USA, 2023-10-3
Latest: EPI_ISL_18757342, USA, 2023-1-8

GISAID query for S:L455S branch: A6183G,G24872T,-27810,-7528,-8456,-A405G, ,-T3565C,T22926C (4 seqs, Singapore, Japan, USA)

 [usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_17994_641370.json?label=id:node_6827509)
Note that some are on other artefact branches.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/dd8046a4-6c62-48b3-8178-a128151bc162)

**Comment by FedeGueli** [comment]
+1 Thailand. great catch btw! it appears that S:V1104L is beneficial in BA.2.86
and it is predicted to be good by Bloom/Neher,
<img width="251" alt="Screenshot 2024-01-16 alle 10 49 49" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9a765164-335b-4104-ab6c-60ec3a225e37">
While Dadonaite/Bloom predicts it to affect ace2 binding.

**Comment by aviczhl2** [comment]
+1 USA airport seq on S:L455S branch , country unknown.

**Comment by aviczhl2** [comment]
Let's reopen this to track the S:L455S sub-branch

**Comment by aviczhl2** [comment]
+1 India for S:L455S branch

**Comment by aviczhl2** [comment]
There seems to be a JN.1.4/JN.11 recombinant, alter query to exclude this.

**Comment by FedeGueli** [comment]
the 455S branch seems slow

**Comment by FedeGueli** [comment]
Japan and South Korea

**Comment by aviczhl2** [comment]
+3 Thailand

**Comment by aviczhl2** [comment]
+1 China

**Comment by FedeGueli** [comment]
Slowed down lets keep this open due to Fujan sample from March for a bit more.

**Comment by aviczhl2** [comment]
20, GBW from Qatar

**Comment by aviczhl2** [comment]
Designated JN.11.1
