### ISSUE TITLE
JN.1+ORF1ab:S2242F+S:F456L+S:N960S(18 sequences, mainly in Europe)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#1304]
Sub-lineage of:JN.1
Earliest sequence: EPI_ISL_19205731,France,2024-5-28
Latest sequence: EPI_ISL_19229746,USA,2024-6-19
Countries:USA(2),France(2),Ireland(5),Spain(2)
Number of Sequences:12
GISAID query:  A24441G,C6990T,T22928C(Edited)
UShER Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1556c_5696d0.json?f_userOrOld=uploaded%20sample&label=id:node_5614567
![IMG_0039](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/55550d14-a778-4930-85ff-b96c2b999ba7)

**Comment by FedeGueli** [comment]
thx i ve added a nuc query: C13405T, T17599C, T20185C

**Comment by FedeGueli** [comment]
it looks like a cluster , lets keep it open until the end of the month

**Comment by FedeGueli** [comment]
Confirmed it was just a cluster closing it for now

**Comment by aviczhl2** [comment]
S:P812A may be a cluster, but S:N960S seems to grow large.  Query A24441G,C6990T finds 146. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/25cbbb89-0f97-4e52-b5e7-ae9a09d25fb2)

**Comment by aviczhl2** [comment]
There is an S:F456L sub-branch emerging from this.

**Comment by FedeGueli** [comment]
> There is an S:F456L sub-branch emerging from this.

Branch 111 ??

**Comment by aviczhl2** [comment]
> > There is an S:F456L sub-branch emerging from this.
> 
> Branch 111 ??

Yeah.

**Comment by Outpfmance** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1556c_5696d0.json?f_userOrOld=uploaded%20sample&label=id:node_5614567
![IMG_0039](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/55550d14-a778-4930-85ff-b96c2b999ba7)
This is a branch of the F456L, which became popular in Europe at the beginning of June, and a small portion of which also has the R346T.
I think we can reopen the issue. @FedeGueli 
Thanks @aviczhl2

**Comment by FedeGueli** [comment]
Thx @Outpfmance !

**Comment by FedeGueli** [comment]
Pls update the main text of the proposal @Outpfmance

**Comment by Outpfmance** [comment]
18 sequences now

**Comment by FedeGueli** [comment]
Pls propose it

**Comment by FedeGueli** [comment]
@Outpfmance pls propose it.

**Comment by Outpfmance** [comment]
@FedeGueli OK, I have already opened the issue, I don't know why I didn't open it last time.
https://github.com/cov-lineages/pango-designation/issues/2692

**Comment by FedeGueli** [comment]
Thanks!
