### ISSUE TITLE
JN.1.7 (S:T572I, S:E1150D) + S:Q613H cluster in Washington, USA (8 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#1305]
JN.1.7 > C7113T (ORF1ab:T2283I) > A20112C + G23401T (S:Q613H)

Nucleotide query: C7113T, A20112C, G23401T 

These sequences are identical and are thus a single cluster, but because jn.1.7 is one of the fastest branches of jn.1* and because of the success of Q613H in the first half of 2023 I think it is good to keep an eye out for spread outside the cluster. In the last half of 2023 however, Q613H lost its advantage to F456L and later L455F and L452R, so it might not have much of an effect nowadays.
On cov-spectrums latest update (15-01), there are 8 sequences of various jn.1* + q613h branches, and setting a baseline of jn.1* gives a relative advantage of 31% (-19 -- 89%) but in my opinion there are not enough sequences to know for sure.

Usher tree:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/b4dc26e9-645f-453d-8f6b-2fa10aef6baf)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a962_7bca70.json?branchLabel=nuc%20mutations&c=gt-S_613&gmax=25384&gmin=21563&label=id:node_6854182

EPI_ISL_18730784, EPI_ISL_18779048, EPI_ISL_18779051,
EPI_ISL_18779054, EPI_ISL_18779062, EPI_ISL_18779069,
EPI_ISL_18779076

**Comment by FedeGueli** [comment]
Slow or just a cluster

**Comment by FedeGueli** [comment]
no new seqs closing it
