### ISSUE TITLE
JN.1.4 with S:F32L, S:ins32:WRR (ins21657:AATGGCGGA) (3 seq, USA, NY)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1306]
### **Description**
**Sub-lineage of:** JN.1.4
**Earliest sequence:** 2023-12-27, USA, New York
**Most recent sequence:** 2023-12-27, USA, New York
**Continents circulating:** North America (2)
**Countries circulating:** USA (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** G18811A, C14120T, A13947C, C4795T, A22161G, -del27795, -A21794C
(it works also: C3619T, C25680T, C26894T, A28699T edited)
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [3-of: C3619T, C25680T, A28699T]
**Substitutions/Insertions on top of X:**
**Spike:** ins32:WRR
**Nucleotide:** C3619T, ins21657:AATGGCGGA, C25680T, C26894T, A28699T  

**Phylogenetic Order of Mutations:**  C26894T  **→**  C25680T  **→**  A28699T  **→**  C3619T, ins21657:AATGGCGGA (S:ins32:WRR) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.4_ins32_WRR.json?c=gt-nuc_3619&gmax=4619&gmin=2619&label=id:node_6850268 
<img width="1452" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/59c408d6-a763-4a18-9cef-16f1017b84bd">

**Evidence**
Probably the most unique and surprising aspect of BA.2.86 was its MPLF insertion at S:16. I can only recall one other sequence that I’ve ever seen with an insertion in that area (a chronic-infection XBB.1.5 from Canada with S:ins16:SHS + S:N17Y— EPI_ISL_17821850). It’s fairly common to see deletions in that area, particularly in chronic patients, but insertions just don’t happen. 

So I find it particularly surprising that a BA.2.86 descendant has piled on yet another insertion in that region. Only two sequences, but the fact that it happened at all is remarkable to me. 

There’s one aspect of insertions that baffles me, and perhaps someone here can explain to me whether this is a known phenomenon or if it’s unique to SARS-CoV-2 or if I’m just crazy and imagining something that doesn’t exist: guanine nucleotides seem to me hugely overrepresented in insertions. In the genome as a whole, G is underrepresented, making up <20% of all nucleotides (I calculated it at 19.6%, in the reference genome I think). Yet I think G must make up 40% or more of the nucleotides in spike insertions. I’ve seen insertions with 6/9 G’s before (ins222304:GGGGCGCGA), and one just showed up in Thailand with 8/12 (ins22204:TGGCGGCGGCGG, ins214:WRRR, EPI_ISL_18771387—might be an artifact but looks real enough). I also suspect that cytosine is overrepresented in insertions compared to its frequency in the genome (~18.4%), but I'm less certain of that.

So 4/9, or 44% G’s, as this sequence has, is pretty normal in my experience. Notably, the FCS has 5/12 G’s, so it fits the pattern as well. Image below from Spyros Lytras, https://virological.org/t/the-sarbecovirus-origin-of-sars-cov-2-s-furin-cleavage-site/536 

<img width="1113" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cb975ec8-f545-4f78-8c1f-096dfd6a6484">

So does anyone know if overrepresentation of guanine in insertions is a known thing, or if anyone has done any quantitative analysis of the nucleotide content of insertions in SARS-CoV-2?

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18779904, EPI_ISL_18779975
</details>

**Comment by FedeGueli** [comment]
Now 3 but very slow.-

**Comment by FedeGueli** [comment]
closing this
