### ISSUE TITLE
JN.1.4 mutated in one of the defining mutations  of BA.2.86 S:E>K554T (20 seqs, Indonesia, Japan, Australia,China, 12 with S:V1264L) 4% prevalence in Indonesia in January

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1307]
I don't know why but i had this one open in a tab of my pc, hence it is showing a mutation in a defining mutation of BA.2.86 and coming from 2 countries and one of them being an undersampled area and being all quite recent i propose it 

JN.1.4 > > Orf1a:K4348R ( T18453C) > A13308G > C26873T > S:E>K554T (A23223C), Orf7a:F9L (C27782A)
Query: A13308G,C26873T,C27782A
Samples: 3 (EPI_ISL_18673395, EPI_ISL_18769901, EPI_ISL_18770508) 
Countries: Indonesia , Shanghai (from Japan)

Tree:
<img width="1171" alt="Screenshot 2024-01-17 alle 18 25 54" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/eb0cad4f-60f9-4851-94de-1860fb1f1744">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_34619_7dc6a0.json?c=userOrOld&label=id:node_6860066

Addendum:
S:E554T is not present in any other SC2 sequence but it was in Pangolin viruses from Guangxi  cc @ryhisner

**Comment by ryhisner** [comment]
There have also been several JN.1 sequences with S:K554N, so this seems to either be a flexible residue or else one that's under some slight selection pressure to change.

**Comment by krosa1910** [comment]
4 Now, one added in Australia (typical Indonesian origin developments)

**Comment by FedeGueli** [comment]
Thx @krosa1910 now i know i was cjhecking https://github.com/sars-cov-2-variants/lineage-proposals/issues/1222 and found this one. And thx for pointing to the new sequence from Australia , this could have some fitness apparently judging from the countries from where it was sampled (Indonesia, China from Japan, Australia) cc @corneliusroemer

**Comment by krosa1910** [comment]
> There have also been several JN.1 sequences with S:K554N, so this seems to either be a flexible residue or else one that's under some slight selection pressure to change.

554 is one of the most convergent places in XBB*, I counted something like 20+ distinct lineages carrying it, yet I did not see a clear advantage of E554K, maybe further changing to something else could really express some advantage here.

**Comment by FedeGueli** [comment]
+3 recent samples from indonesia

**Comment by FedeGueli** [comment]
slowed down a lot.

**Comment by FedeGueli** [comment]
clsoing this

**Comment by FedeGueli** [comment]
now tracked in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1433
