### ISSUE TITLE
JF.1.1/JN.1 recombinant(3 seqs, Slovenia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1309]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d9fbafda-494e-455f-90d4-e9118e211585)

JF.1.1--JN.1--JF.1.1

Breakpoint 1 between 16343 and 17858
Breakpoint 2 between 27916 and 28296

Additional mutations: G670T(rev), C5869T,C6120T, C6664T,C18348T, A28254T

Orf1a:R135S(rev),S1952L
Orf8:I121L

G670T(rev), C5869T,C6120T, C6664T, A28254T from a Slovenia JF.1.1 branch.
C18348T from a JN.1 branch

GISAID query:C6664T,C18894T,C29386T
No. of seqs: 2(Slovenia)

EPI_ISL_18609089, 2023-12-24
EPI_ISL_18779382, 2023-12-29

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_27006_8c3820.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c8f51384-ca85-444f-9eff-9d8505b1f99f)

**Comment by FedeGueli** [comment]
Sorry i have missed this one for some reason!

**Comment by aviczhl2** [comment]
No new seqs

**Comment by aviczhl2** [comment]
+1 Slovenia

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
Thank you for tracking it
