### ISSUE TITLE
Stepwise evolved XBF got NSP6_F35L then S:L858I then N:A135V, Orf1b:T1050I, ORF1a:L2105F and finally S:P681R (seen in Delta) , 16 samples New Zealand

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#131]
XBF with S:P681R
15 samples, New Zealand. Most recent samples (12) from Nelson Marlbourough (hospital).
No sample strategy has been given, so I do not know if the samples actually came from hospitalized patients.
From that lab/hospital 0 out 10, 5 out of 13 and 6 out of 10 sequenced sample concerned this sublineage in week 18, 19 and 20 resp..
**First sample:** 2023-04-03 from Bay of Plenty
**Most recent sample:** 2023-05-17 from Nelson Marlbourough
GISAID Query: T9208A, T11075C, Spike_P681R or (T9208A, T11075C,C6578T, C16616T **edited**)
CovSpectrum Query: https://cov-spectrum.org/explore/World/AllSamples/Y2023/variants?aaMutations=S%3AP681R&nucMutations=T9208A&nextcladePangoLineage=XBF*&nextcladePangoLineage1=xbb.1.9.1*&

I find the Usher tree a bit strange. The mutations on the long branch are actually reversions and the samples shown before it are actually shown twice.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f3f0_9daea0.json?label=id:node_7318696
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/1fda339e-2016-47af-a0f2-1a2218c971e9)

**Comment by FedeGueli** [comment]
@angiehinrinchs could you take a look at this little branch with rev?

**Comment by FedeGueli** [comment]
@JosetteSchoenma relooking at the long stepwise evolution this seemed to undergo i would like to highlight the precious node before getting S:681R:
it got also N:A152V, Orf1a:L2105F and Orf1b:T1050I ( As XBC! and convergent residue to BA.5.2!)
![Schermata 2023-06-02 alle 17 10 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e61d1e7c-6a50-4c1c-b6e9-0683360a42df)

**Comment by JosetteSchoenma** [comment]
Thanks, @FedeGueli . Also for adjusting the title.

**Comment by oobb45729** [comment]
ORF1a:L2105F is near XBC's ORF1a:S2104I, XAY.1.1's ORF1a:K2108N, and the convergent ORF1a:S2103F.

**Comment by FedeGueli** [comment]
Just one virus out of 800+ seqs  uploaded today i m closing this for now.
