### ISSUE TITLE
JN.1.4* with C21302T,C21304A,G21305A triple mutation (322 seqs, 10 countries mostly Israel at 03-26)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1310]
Mutations: JN.1.4*(JN.1*+C774T/Orf1a:T170I/NSP1 T170I)+,C21302T, C21304A, G21305A
Notes: many, or even majority of the sequences gets T18453C, T1510C, C5784T(Orf1a:T1840I), C23628T or C28201T(orf8:S103L), but because those CT transitions are too common and most does not correspond with meaningful aa mutations so I ignore them.
Gisaid Inquiry:C21302T, C21304A, G21305A,C774T,T15756A
Earliest Sequence: EPI_ISL_18596536 Denmark 2023-11-20
Latest Sequence: EPI_ISL_18781263 Isarel 2024-01-08
Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_28c15_8d46a0.json?f_userOrOld=uploaded%20sample

<img width="1429" alt="Screenshot 2024-01-18 at 5 39 27 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/6ef02929-672b-4d17-ae68-2d5ac0b99e88">

nextclade result: https://clades.nextstrain.org/tree

[nextclade.csv](https://github.com/sars-cov-2-variants/lineage-proposals/files/13974789/nextclade.csv)

<img width="1429" alt="Screenshot 2024-01-18 at 5 40 26 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/e0e80b36-8bc9-4a8c-8db6-ba5bf3320883">

**Comment by corneliusroemer** [comment]
Can you list how many are Israel and other countries? This is almost entirely Israel with so-so sequence quality so I'm a bit hesitant. It jumps a bit too fast from 0 to 20% in Israel. 

<img width="2097" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/6a37ad82-e5fc-4873-bc0d-3fa02ddbaabf">

**Comment by krosa1910** [comment]
> C21302T, C21304A, G21305A,C774T,T15756A

3 Belgium, 2 Canada, 1 Denmark, 1 Netherlands, 1 USA, the rest Isareal, I would present a usher tree with manually marked series shortly after.

**Comment by krosa1910** [comment]
<img width="990" alt="Screenshot 2024-01-22 at 3 30 15 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/8c9a4d0d-58bd-4b6b-af11-e50fb3613224">
<img width="990" alt="Screenshot 2024-01-22 at 3 30 25 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/24ca1c19-8b54-484b-9c83-29862abe784d">

Yeah, this tree's quality is not so good, all the foreign sequences are clustered before the large Isareli clade, which is further characterized by the mutation T1510C, I would consider changing the proposal.

**Comment by FedeGueli** [comment]
please propose it.

**Comment by Memorablea** [comment]
The first find by @ryhisner in cov-lineages/pango-designation/issues/2426
![Uploading image.png…]()

**Comment by Memorablea** [comment]
The first find by @ryhisner in cov-lineages/pango-designation/issues/2426
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/1fe0f524-a564-4113-b291-3fe4063d26be)

**Comment by Memorablea** [comment]
The first find by @ryhisner in cov-lineages/pango-designation/issues/2426
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/1fe0f524-a564-4113-b291-3fe4063d26be)

**Comment by FedeGueli** [comment]
322 now

**Comment by FedeGueli** [comment]
Likely dead
