### ISSUE TITLE
Multiple JN.1* branches with S:H445Y (18 branches, 41 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#1311]
General Search: Spike_V445Y, Spike_L455S, Spike_L452W

Interestingly, these 6 branches all popped up independently near the end of December. 445Y is very rare, mostly because it is a 2-nuc mutation that 445H in ba.2.86* allowed. As of writing, there are only 23 445Y sequences on GISAID.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A445y&nextcladePangoLineage=jn.1*&

Downsampled global tree of all branches:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/bc06bd1e-788a-4a5b-9219-eede169e8ed9)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3939c_93d740.json?f_userOrOld=uploaded%20sample

Branch 1 (4 seq, Australia) (JN.1.4 > C28201T (ORF8:S103L) > C28948T > A19410C (ORF1b:K1981N) >C22895T (S:H445Y)):  
G22895T, A19410C, C28948T

Branch 2 (7 seq, NY+NJ USA) (JN.1 > G25647T (ORF3a:L85F) >A5053G + T23629C > C6720T (ORF1a: T2152I) > C22895T (S:H445Y)):
G22895T,  A5053G

Branch 3 (2 seq, Portugal) (JN.1 > C1909T + T18357C + C22895T (S:H445Y)): 
G22895T,  T18357C

Branch 4 (2 seq, Denmark) (JN.1 > C17766T > C556T > A10323G (ORF1a:K3353R) + C22895T (S:H445Y)): 
G22895T,  C556T, A10323G

Branch 5 (1 seq, Sweden) (JN.1.1.1 > C19263T + C22895T (S:H445Y)):
G22895T,  C9142T

Branch 6  (1 seq, Canada): (JN.1 > C26571T (M:L17F) > C17288T (ORF1b:T1274I) + C22895T (S:H445Y))
G22895T,  C17288T

Branch 7 (2 seq, South Korea): (JN.1 > C26625T > C22341T (S:A260V) + C22895T (S:H445Y)):
G22895T, C22341T, C26625T

Branch 8 (1 seq, Scotland): (JN.1 > G1322T (ORF1a:G353C) > C21727T > C27297T > T1322G (ORF1a:C353G) > C18744T > C2445T (ORF1a:T727I) > C22895T (S:H445Y)):
G22895T, C2445T, C18744T

Branch 9 (1 seq, Netherlands): (JN.1 > C24734T (S:H1058Y) > C1968T (ORF1a:T568I), T20266C, G21586T (S:L8F) > A8763G (ORF1a:D2833G) >T7348C, T7855C, C22895T (S:H445Y)):
G22895T, T7855C

Branch 10 (1 seq, Spain): (JN.1 > A23005T (S:K481N rev) > A23013C (S:K484T) > A22770G (S:K403R rev), A22942G > A22011T (S:K150I), C22895T (S:H445Y)):
G22895T, A22011T

Branch 11 (1 seq, France): (JN.1 > C1779T (ORF1a:S505F) > C13019T > C22895T (S:H445Y)):
G22895T, c1779t, C13019T

Branch 12 (1 seq, USA NY): (JN.1.4.2 > C29311T > C22895T (S:H445Y)):
G22895T, A22115G, C29311T

Branch 13 (1 seq, Italy): (JN.1.1 > T20526C > C22895T (S:H445Y), G26610A (M:A30T rev artefact?)
G22895T, T20526C

Branch 14 (1 seq, USA RI): (JN.1 > C18796T > T14619A, G18148A (ORF1b:G1561S), C18804T, C22895T (S:H445y) )

Branch 15 (2 seq, New Zealand): (JN.1 > C6629T (ORF1a:L2122F) > C19698T, C22895T (S:H445Y), G3567A (ORF1a:G1101D)

Branch 16 (1 seq, Ireland): (JN.1 > A22194T (S:N211I) > T22195A, T22196G (S:L212V) > C774T (ORF1a:T170I) > T18453C > C11003T (ORF1a:H3580Y) > C22895T (S:H445Y), C25096T

Branch 17 (1 seq, USA HI): (JN.1 > G2782T > C2488T > C14119T (ORF1b:P218S), C22895T (S:H445Y)

Branch 18 (1 seq, USA IL): JN.1 > G18674A (ORF1b:R1736K) > G21665A (S:G35S), G25690A (ORF3a:G100S), C11572T >T3616C, G4720A, C12455T (ORF1a:L4064F), G22599C (S:R346T), C22895T (S:H445Y), C27434T (ORF7a:T14I)

**Comment by FedeGueli** [comment]
edited a little typo in the mutation.

**Comment by BorisUitham** [comment]
> edited a little typo in the mutation.

Thanks, I must've copy pasted the same mutation multiple times lol.

7th branch in south korea, 2 sequences. Collected 21 and 19 december. These also have s:a260v

Wonder why this convergence is happening only now, relatively late. Perhaps the first effects of evading immunity from jn.1 wave?

**Comment by FedeGueli** [comment]
Maybe yes

**Comment by BorisUitham** [comment]
New singlet branch, scotland.

JN.1 > G1322T (ORF1a:G353C) > C21727T > C27297T > T1322G (ORF1a:C353G) > C18744T > C2445T (ORF1a:T727I) > C22895T (S:H445Y)

Im really not sure if the back and forth mutation of 1322 is real or not.

**Comment by BorisUitham** [comment]
New singlet branch Netherlands:
JN.1 > C24734T (S:H1058Y) > C1968T (ORF1a:T568I), T20266C, G21586T (S:L8F) > A8763G (ORF1a:D2833G) >T7348C, T7855C, C22895T (S:H445Y)

**Comment by BorisUitham** [comment]
New singlet branch spain: JN.1 > A23005T (S:K481N rev) > A23013C (S:K484T) > A22770G (S:K403R rev), A22942G > A22011T (S:K150I), C22895T (S:H445Y)
I would say the 484t 481n and 403r are probably artefacts

**Comment by FedeGueli** [comment]
homoplasic but slow, maybe intrahost good but not interhost?

**Comment by BorisUitham** [comment]
Indeed, I thought it would be otherwise because all these branches popped up simultaneously but it seems to be a fluke

**Comment by FedeGueli** [comment]
41 for 18 branches only one sample in february i think this is very likely deleterious inter host (but with some advantage intrahost) closing for now thanks for tracking it @BorisUitham
