### ISSUE TITLE
GE.1.2.1+Orf1a:V23I,S:M153I,,Orf10:L37F(15 seqs, Kenya, 11% prevalance)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1312]
New seqs uploaded from Kenya reveals more GE.1.2 branches. 
GE.1.2.1+G332A, G22021A,C29666T

GISAID query: G332A, G22021A,C29666T
No. of seqs: 15(Kenya)
First: EPI_ISL_18788227, 2023-11-21
Latest: EPI_ISL_18788113, 2024-1-5

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4a3d5_965600.json?label=id:node_11184214)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6e446ac9-cd0d-477b-907f-2de6a3510f43)

**Comment by FedeGueli** [comment]
Orf10 convergent with BA.5.1

**Comment by aviczhl2** [comment]
This one doesn't have S:77 though

**Comment by FedeGueli** [comment]
> This one doesn't have S:77 though

Oh thx i was thinkint S:77 was in all GE.1.2.1 . sorry

**Comment by corneliusroemer** [comment]
There's a lot of ORF6:62 flip flopping which might mess things up
<img width="1847" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/e2252df8-1339-4838-b01a-666118a14e8c">

GE.1.2.1 is really interesting, I wonder why it's only really been found in US-MN and UK other than Kenya. In particular, why in the US only in these mid west states?

**Comment by aviczhl2** [comment]
No new seqs
