### ISSUE TITLE
JN.2+Orf1a:C3059S+S:L455S(48 seqs, 6 countries) >5% in Rio de Janeiro in February

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1314]
One more BA.2.86*+S:L455S branch.

JN.2+G16221T+T9440A(Orf1a:C3059S)+T22926C(S:L455S)

GISAID query: G16221T,T9440A,T22926C
No. of seqs: 6(Brazil 4 Spain 1 France 1)

First: EPI_ISL_18676851, France, 2023-12-4
Latest: EPI_ISL_18791431, Brazil, 2024-1-13

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice175_genome_test_4d02f_b131f0.json?label=id:node_6886770)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/867553d9-1c89-4373-9bf3-920c9dedeb18)

**Comment by corneliusroemer** [comment]
455S might be acquired through intra-BA.2.86.1 recombination

Bit to small right now, let's watch

**Comment by FedeGueli** [comment]
12 now

**Comment by aviczhl2** [comment]
+3 Canada +1 USA

**Comment by FedeGueli** [comment]
33 mostly new ones from Rio de Janeiro, where its share apparently around 5% in February

**Comment by FedeGueli** [comment]
+2 Federal District Brazil

**Comment by FedeGueli** [comment]
@aviczhl2 please propose it.

**Comment by FedeGueli** [comment]
+4 Para' Brazil, maybe worth watching it a bit more, even if samples are not recent

**Comment by aviczhl2** [comment]
> +4 Para' Brazil, maybe worth watching it a bit more, even if samples are not recent

Already Proposed to main page. https://github.com/cov-lineages/pango-designation/issues/2534

**Comment by FedeGueli** [comment]
> > +4 Para' Brazil, maybe worth watching it a bit more, even if samples are not recent
> 
> Already Proposed to main page. [cov-lineages/pango-designation#2534](https://github.com/cov-lineages/pango-designation/issues/2534)

ah ok sorry didnt see that i thought you closed it for recency of samples
