### ISSUE TITLE
Relatively big JN.1 branch with Orf3a:V13L ( 1126 seqs )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1319]
There is a branch of JN.1 consisting of around 1% of JN.1 defin ed by Orf3a:V13L
It seems as fast as the fastest branch Jn.1.4 and Jn.1.5 so maybe @corneliusroemer would evaluate to designate it too.

Defining mutations:
JN.1>> G25429T Orf3a:V13L (G25429T)

Query: G25429T, T3565C , T27810C

Tree:
<img width="1156" alt="Screenshot 2024-01-21 alle 16 13 06" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5c40a23e-b4c6-4d3d-87ea-b5b4c3f9be19">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_37078_d2f1e0.json?f_userOrOld=uploaded%20sample&label=id:node_6845933

Samples: 484

IDs:
<Details>
<Summary>
Genomes
</Summary>
EPI_ISL_18403428, EPI_ISL_18472857, EPI_ISL_18489786,
EPI_ISL_18506916, EPI_ISL_18506925, EPI_ISL_18516402,
EPI_ISL_18516426, EPI_ISL_18523165, EPI_ISL_18523889,
EPI_ISL_18531791, EPI_ISL_18541750, EPI_ISL_18545440,
EPI_ISL_18546342, EPI_ISL_18549079, EPI_ISL_18549217,
EPI_ISL_18551496, EPI_ISL_18556971, EPI_ISL_18567606,
EPI_ISL_18567616, EPI_ISL_18567620, EPI_ISL_18567623,
EPI_ISL_18567627, EPI_ISL_18575307, EPI_ISL_18577826,
EPI_ISL_18577841, EPI_ISL_18577859-18577860, EPI_ISL_18577909,
EPI_ISL_18577919, EPI_ISL_18579763, EPI_ISL_18580125,
EPI_ISL_18581502, EPI_ISL_18582219, EPI_ISL_18583219,
EPI_ISL_18583294, EPI_ISL_18584247, EPI_ISL_18585376,
EPI_ISL_18590963, EPI_ISL_18593482, EPI_ISL_18600740,
EPI_ISL_18602462, EPI_ISL_18607362, EPI_ISL_18610361,
EPI_ISL_18610407, EPI_ISL_18610508, EPI_ISL_18611071,
EPI_ISL_18613002, EPI_ISL_18620704, EPI_ISL_18621657,
EPI_ISL_18621924, EPI_ISL_18621956, EPI_ISL_18624521,
EPI_ISL_18626656, EPI_ISL_18634799, EPI_ISL_18635948,
EPI_ISL_18636404, EPI_ISL_18636793, EPI_ISL_18638183,
EPI_ISL_18640611, EPI_ISL_18642235, EPI_ISL_18642240,
EPI_ISL_18642249, EPI_ISL_18643154, EPI_ISL_18643300,
EPI_ISL_18643312, EPI_ISL_18643414, EPI_ISL_18644500,
EPI_ISL_18644827, EPI_ISL_18645239, EPI_ISL_18645305,
EPI_ISL_18645420, EPI_ISL_18645692-18645693, EPI_ISL_18645767,
EPI_ISL_18647871-18647872, EPI_ISL_18647882, EPI_ISL_18647936,
EPI_ISL_18647950, EPI_ISL_18647964, EPI_ISL_18647987,
EPI_ISL_18648011, EPI_ISL_18648026, EPI_ISL_18648030,
EPI_ISL_18648051, EPI_ISL_18648115, EPI_ISL_18652656,
EPI_ISL_18652923, EPI_ISL_18653024-18653025, EPI_ISL_18654205,
EPI_ISL_18659550, EPI_ISL_18659622, EPI_ISL_18659792,
EPI_ISL_18659818, EPI_ISL_18660522, EPI_ISL_18661925,
EPI_ISL_18661936, EPI_ISL_18666662, EPI_ISL_18667261,
EPI_ISL_18669358, EPI_ISL_18669360, EPI_ISL_18669362-18669367,
EPI_ISL_18669370-18669373, EPI_ISL_18669375-18669376, EPI_ISL_18669378,
EPI_ISL_18669382, EPI_ISL_18672150, EPI_ISL_18672919,
EPI_ISL_18672928, EPI_ISL_18674702, EPI_ISL_18675054,
EPI_ISL_18675071, EPI_ISL_18675086, EPI_ISL_18675262,
EPI_ISL_18676756, EPI_ISL_18677544, EPI_ISL_18677557,
EPI_ISL_18677592, EPI_ISL_18677605, EPI_ISL_18677652,
EPI_ISL_18677828, EPI_ISL_18677876, EPI_ISL_18677932,
EPI_ISL_18680639, EPI_ISL_18680890, EPI_ISL_18682653,
EPI_ISL_18686591, EPI_ISL_18690099, EPI_ISL_18690565,
EPI_ISL_18691825, EPI_ISL_18691965, EPI_ISL_18692449,
EPI_ISL_18693816-18693817, EPI_ISL_18694563, EPI_ISL_18695342,
EPI_ISL_18695391, EPI_ISL_18695845-18695846, EPI_ISL_18695870,
EPI_ISL_18695913, EPI_ISL_18695961, EPI_ISL_18695966,
EPI_ISL_18696027, EPI_ISL_18696038, EPI_ISL_18696044,
EPI_ISL_18696214, EPI_ISL_18696219, EPI_ISL_18696319,
EPI_ISL_18696367, EPI_ISL_18696409, EPI_ISL_18696439,
EPI_ISL_18696470, EPI_ISL_18696485, EPI_ISL_18696506-18696507,
EPI_ISL_18696565-18696567, EPI_ISL_18696576-18696577, EPI_ISL_18696588,
EPI_ISL_18696628, EPI_ISL_18697062, EPI_ISL_18697237,
EPI_ISL_18697358, EPI_ISL_18697379, EPI_ISL_18697521,
EPI_ISL_18697595-18697596, EPI_ISL_18697598, EPI_ISL_18698015,
EPI_ISL_18698721, EPI_ISL_18698729, EPI_ISL_18698736,
EPI_ISL_18698855, EPI_ISL_18698878, EPI_ISL_18699152,
EPI_ISL_18701426, EPI_ISL_18701479, EPI_ISL_18701502,
EPI_ISL_18702048, EPI_ISL_18702510, EPI_ISL_18704464,
EPI_ISL_18707891, EPI_ISL_18708076, EPI_ISL_18708092,
EPI_ISL_18708703, EPI_ISL_18710569, EPI_ISL_18710624,
EPI_ISL_18710638, EPI_ISL_18710648, EPI_ISL_18710712,
EPI_ISL_18710765-18710766, EPI_ISL_18710810, EPI_ISL_18710881,
EPI_ISL_18710884, EPI_ISL_18710893-18710896, EPI_ISL_18710898,
EPI_ISL_18710990, EPI_ISL_18711022, EPI_ISL_18711083,
EPI_ISL_18711086, EPI_ISL_18711095, EPI_ISL_18711101,
EPI_ISL_18711107, EPI_ISL_18713217, EPI_ISL_18714068,
EPI_ISL_18715056, EPI_ISL_18716673, EPI_ISL_18717149,
EPI_ISL_18717479, EPI_ISL_18717531, EPI_ISL_18719063,
EPI_ISL_18721890, EPI_ISL_18721954, EPI_ISL_18722952,
EPI_ISL_18724737, EPI_ISL_18724754, EPI_ISL_18724759,
EPI_ISL_18724865, EPI_ISL_18725813, EPI_ISL_18725817,
EPI_ISL_18725822, EPI_ISL_18725831, EPI_ISL_18726118,
EPI_ISL_18726997, EPI_ISL_18727544, EPI_ISL_18728268,
EPI_ISL_18728901, EPI_ISL_18729108, EPI_ISL_18729225,
EPI_ISL_18729553, EPI_ISL_18729571, EPI_ISL_18729731,
EPI_ISL_18729751, EPI_ISL_18729766, EPI_ISL_18729778,
EPI_ISL_18729783, EPI_ISL_18729801, EPI_ISL_18729818,
EPI_ISL_18729824, EPI_ISL_18729868, EPI_ISL_18729880,
EPI_ISL_18729883, EPI_ISL_18729905, EPI_ISL_18730017,
EPI_ISL_18730117, EPI_ISL_18730226, EPI_ISL_18730246,
EPI_ISL_18730257, EPI_ISL_18730261, EPI_ISL_18730677,
EPI_ISL_18730710, EPI_ISL_18730777, EPI_ISL_18731616,
EPI_ISL_18731828, EPI_ISL_18731939, EPI_ISL_18732086-18732091,
EPI_ISL_18732093, EPI_ISL_18732137, EPI_ISL_18732148,
EPI_ISL_18732163, EPI_ISL_18732197, EPI_ISL_18732230,
EPI_ISL_18732238, EPI_ISL_18732251, EPI_ISL_18732315,
EPI_ISL_18732354, EPI_ISL_18732426, EPI_ISL_18732464,
EPI_ISL_18732472, EPI_ISL_18732497, EPI_ISL_18732578,
EPI_ISL_18732587, EPI_ISL_18732660, EPI_ISL_18732710,
EPI_ISL_18732809, EPI_ISL_18732834, EPI_ISL_18732851,
EPI_ISL_18732860, EPI_ISL_18735237, EPI_ISL_18735403,
EPI_ISL_18735470, EPI_ISL_18735982, EPI_ISL_18735984,
EPI_ISL_18735993, EPI_ISL_18736006, EPI_ISL_18739307,
EPI_ISL_18741517, EPI_ISL_18742178, EPI_ISL_18742190,
EPI_ISL_18742361, EPI_ISL_18742363, EPI_ISL_18742368,
EPI_ISL_18742373, EPI_ISL_18743177, EPI_ISL_18743191,
EPI_ISL_18743437, EPI_ISL_18743558, EPI_ISL_18743749,
EPI_ISL_18743761, EPI_ISL_18744792, EPI_ISL_18746153,
EPI_ISL_18753716, EPI_ISL_18754524, EPI_ISL_18754546,
EPI_ISL_18754685, EPI_ISL_18754693, EPI_ISL_18754796,
EPI_ISL_18755318, EPI_ISL_18755394, EPI_ISL_18756835,
EPI_ISL_18757388, EPI_ISL_18757547, EPI_ISL_18757979,
EPI_ISL_18758211, EPI_ISL_18758577, EPI_ISL_18758650,
EPI_ISL_18758653, EPI_ISL_18758660, EPI_ISL_18758665,
EPI_ISL_18760375, EPI_ISL_18762533, EPI_ISL_18762537,
EPI_ISL_18763435, EPI_ISL_18764136, EPI_ISL_18764393,
EPI_ISL_18764835, EPI_ISL_18764845, EPI_ISL_18764902,
EPI_ISL_18765068, EPI_ISL_18766331, EPI_ISL_18766335,
EPI_ISL_18766353, EPI_ISL_18766368, EPI_ISL_18766614,
EPI_ISL_18766627, EPI_ISL_18766673, EPI_ISL_18768598-18768599,
EPI_ISL_18768610, EPI_ISL_18768622, EPI_ISL_18768656,
EPI_ISL_18768683, EPI_ISL_18768686, EPI_ISL_18768744-18768746,
EPI_ISL_18768772, EPI_ISL_18768877, EPI_ISL_18769031,
EPI_ISL_18769033-18769034, EPI_ISL_18769077, EPI_ISL_18769092,
EPI_ISL_18769110, EPI_ISL_18769128, EPI_ISL_18769166,
EPI_ISL_18769180, EPI_ISL_18769182, EPI_ISL_18769188,
EPI_ISL_18769234-18769235, EPI_ISL_18769246, EPI_ISL_18769294,
EPI_ISL_18769400, EPI_ISL_18769402-18769403, EPI_ISL_18769409-18769410,
EPI_ISL_18769418, EPI_ISL_18769431, EPI_ISL_18769438-18769439,
EPI_ISL_18769442-18769453, EPI_ISL_18769466, EPI_ISL_18769549,
EPI_ISL_18770006, EPI_ISL_18771703-18771704, EPI_ISL_18771706,
EPI_ISL_18771751, EPI_ISL_18771863, EPI_ISL_18772045,
EPI_ISL_18772054, EPI_ISL_18772057, EPI_ISL_18772320,
EPI_ISL_18774303, EPI_ISL_18775596, EPI_ISL_18775814,
EPI_ISL_18775868, EPI_ISL_18776085, EPI_ISL_18777555,
EPI_ISL_18777628, EPI_ISL_18777636, EPI_ISL_18777711,
EPI_ISL_18777716, EPI_ISL_18777723, EPI_ISL_18777725,
EPI_ISL_18777728, EPI_ISL_18777733, EPI_ISL_18777738,
EPI_ISL_18777742, EPI_ISL_18777748-18777749, EPI_ISL_18777752,
EPI_ISL_18777756-18777757, EPI_ISL_18777759, EPI_ISL_18777768-18777770,
EPI_ISL_18777787, EPI_ISL_18777796, EPI_ISL_18777800,
EPI_ISL_18777809, EPI_ISL_18777817, EPI_ISL_18778442,
EPI_ISL_18778528, EPI_ISL_18779068, EPI_ISL_18779115,
EPI_ISL_18779600, EPI_ISL_18779811, EPI_ISL_18780760,
EPI_ISL_18781166, EPI_ISL_18782591, EPI_ISL_18782962,
EPI_ISL_18783898, EPI_ISL_18784405, EPI_ISL_18784410,
EPI_ISL_18785224, EPI_ISL_18785436, EPI_ISL_18787422,
EPI_ISL_18787492, EPI_ISL_18787537, EPI_ISL_18787550,
EPI_ISL_18787615, EPI_ISL_18787665, EPI_ISL_18787668,
EPI_ISL_18787925, EPI_ISL_18787935, EPI_ISL_18789856,
EPI_ISL_18789864, EPI_ISL_18789867, EPI_ISL_18790249,
EPI_ISL_18790252, EPI_ISL_18790499, EPI_ISL_18793671,
EPI_ISL_18793684, EPI_ISL_18794200, EPI_ISL_18794870,
EPI_ISL_18795726, EPI_ISL_18796655
</Details>

**Comment by corneliusroemer** [comment]
Good idea to look for big branches but this is maybe still a bit small to start cutting, let's wait a bit more to not end up with 100 JN.1s in a month ;)

**Comment by FedeGueli** [comment]
569

**Comment by FedeGueli** [comment]
> Good idea to look for big branches but this is maybe still a bit small to start cutting, let's wait a bit more to not end up with 100 JN.1s in a month ;)

thanks Cornelius just read now. agree.

**Comment by FedeGueli** [comment]
802

**Comment by krosa1910** [comment]
Yep, I can provide you with a new tree structure as it is bad to define something by one mutation.
The defining mutation would still be Orf3a:V13L=G25429T, after that the thing is nearly exclusively C19186T, then there is about 85% C18687T branch 1 and 15% C832T branch 2.
We can thus define JN.1.whatever=G25429T+C19186T as it is large enough. Branch 1 and branch 2 now does not deserve separate designation (to me) as they are just syn mutations. However, the large S2500F=C7764T can be cut out to be JN.1.what.1?
@FedeGueli @corneliusroemer 
<img width="994" alt="Screenshot 2024-03-04 at 9 35 43 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/e6cbeae4-2bd1-489e-bcee-9c7d7154fc8b">

**Comment by FedeGueli** [comment]
Designated JN.1.31.1 via https://github.com/cov-lineages/pango-designation/commit/c83781ea0cccdd11ae5fbc9899a64e0132bda289
