### ISSUE TITLE
Saltation of BQ.1.1.40 with S:S71Y, S:S112L, (S:E132Q?), S:L212I, S:D339H, S:T385I, S:Y453F, S:A653V, S:D1139Y and 4 other non-Spike mutation (11 seqs in Ontario, Canada)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#132]
Defining mutations: BQ.1.1.40>C1441T, C1441T, C23191T, G25690T(ORF3:G200C)>saltation branch

Substitutions in saltation:
Spike: S71Y, S:112L ,S:E132Q (one seq is missing S:132), S:L212I, S:D339H, S:T385I, S:Y453F, S:A653V, S:D1139Y
ORF1a: R24C, N2162S
ORF1b:M1839L 
N: A252S
<img width="689" alt="屏幕截图 2023-06-03 011535" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/8e9734a8-aa35-44f9-9a30-b7d72de5287e">

Deletions in saltation (Spike only)
del S:69-70 (del nuc 21765-21770), del S:211 (del nuc 22194-22196)
<img width="433" alt="屏幕截图 2023-06-03 005019" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/01d7d11c-138c-4a19-87cf-f02043a6def7">
<img width="442" alt="屏幕截图 2023-06-03 005130" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/177cec5a-6291-49ba-94a7-1a2e93b14817">

GISAID query: Spike_Y453F, Spike_A653V, Spike_S112L
NUCs only query: A6750G, C12241T (EDITED)
Earliest seq: 2023-05-21 (Canada, EPI_ISL_17743165)
Most recent seq: 2023-05-22 (Canada, EPI_ISL_17743168)
Countries detected: Canada (2)

Usher Tree:

<img width="900" alt="屏幕截图 2023-06-03 011212" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/948c9b9a-9d94-4bb3-8652-3ff5c4aeaa80">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13069_a178a0.json

As the neighbor seqs are collected in Jan2023, the long saltation may have evolved several months, which is quite likely associated with chronic. 
MetaData show the 2 seqs are from different patient, both are aged 70+.

However, Canada is often updated a series of seqs with same mutations. They need a further watch.

Genomes:
EPI_ISL_17743165, EPI_ISL_17743168

Double spotted at the same time by @Sinickle (great job both!)

**Comment by HynnSpylor** [comment]
2 more seqs updated today. They are from different patients but still in Ontario, Canada.

**Comment by FedeGueli** [comment]
Please propose in the main page once reaches 10

**Comment by ryhisner** [comment]
Metadata indicate all nine sequences are from different patients. The ages (8/9 70+, 3/9 90+)suggest this is likely a nursing home outbreak, which is not uncommon in Canada. I've been told that in Ontario they regularly sequence such outbreaks.

**Comment by HynnSpylor** [comment]
2 more seqs are updated today and reaches 11 (one former seq is Y453F only), still in Ontario.

So I still hesitate for submitting it to main page (unless it emerges outside Ontario).

**Comment by FedeGueli** [comment]
No Please propose it.

**Comment by Codes1985** [comment]
Hello,

We've been monitoring this issue.  We'll get in touch with our provincial counterpart in Ontario to see if there is any information that can be shared.

**Comment by FedeGueli** [comment]
> Hello,
> 
> We've been monitoring this issue. We'll get in touch with our provincial counterparts in Ontario to see if there is any information they can share.

Thank you!!

**Comment by FedeGueli** [comment]
@Codes1985 please update on https://github.com/cov-lineages/pango-designation/issues/2052 this is now transferred there.
