### ISSUE TITLE
XDN mini saltation with S:N703Y (2 Seqs , England)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1320]
Just spotted a mini saltation happened in XDN in England , 
it displays a spike mutation at S:N703 to **Y** while we have **I** in XBC , **S** in an undesignated XBB.1.5 sublineage .
**S:N703Y** instead was defining of CP.7 , a late Japanese BA.5.2 descendants.
Mutations at spike residues 701, 703, 704 and 706 have been present in several fast lineages and variants.
Please note that this saltation displays also C28269T that affects the N Kozak sequence  in position -5 , further reducing its optimization:
<img width="872" alt="Screenshot 2024-01-21 alle 19 51 10" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/73cc9140-503f-49c2-8943-abdbfc3f38f4"> cc @ryhisner 

Defining mutations:
XDN > Orf8:T87I (C28153T) >  A7864G, Orf1a:P2739L (C8481T), C15654T, A16107G,S:N703Y (A23669T), G26610A (rev, unsure if real), Orf6:L15F (A27246C), C28269T 

Query:A7864G, C8481T, C15654T

Samples 2 (England)
EPI_ISL_18763573, EPI_ISL_18782680

Tree:
<img width="1175" alt="Screenshot 2024-01-21 alle 19 53 28" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f84f01d3-9f3a-4b47-9d2b-202d6a56562f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_248af_d382a0.json?c=gt-S_703&label=id:node_6843079

**Comment by aviczhl2** [comment]
26610 is branch specific mask in BA.2.86, however XDN is JD.1 on this part, so every seq shall have that.

**Comment by FedeGueli** [comment]
no new sequences clsoing it
