### ISSUE TITLE
Relative big branch of JN.1 defined by Orf1a:S505F (982) and the Orf1a:G445V (311)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1321]
Here another putative branch of JN.1 that maybe @corneliusroemer could evaluate for branch designation.

JN.1 > Orf1a:S505F (C1779T) > C13019T > Orf1a:G445V (G1599T)

Tree:
<img width="1169" alt="Screenshot 2024-01-21 alle 23 38 21" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/48918758-c580-4469-bc77-9cb3e5253d26">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5c9f5_d9a460.json?label=id:node_6865595

Query for Orf1a:S505F : T15756A, A7842, C1779T,
Samples 982

Query for Orf1a:G445V : C13019T,G1599T, C1779T,
Samples 311

**Comment by Fearuncle** [comment]
https://github.com/cov-lineages/pango-designation/issues/2465
