### ISSUE TITLE
JN.1*  + A29086T  with S:Q677H (96 Sequences) and  a further sublineage with S:S680F （42 seqs)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1326]
**Edited by mod**
JN.1*> A29086T > G23593T(S:Q677H) 
Query:G23593T, A29086T,T3565C 
Samples: 63
IDs:EPI_ISL_18598041, EPI_ISL_18639885, EPI_ISL_18685007,
EPI_ISL_18688698, EPI_ISL_18688878, EPI_ISL_18706617-18706618,
EPI_ISL_18706622, EPI_ISL_18711912, EPI_ISL_18720952,
EPI_ISL_18732956, EPI_ISL_18733298-18733299, EPI_ISL_18740816,
EPI_ISL_18740832, EPI_ISL_18740834, EPI_ISL_18751372,
EPI_ISL_18751611, EPI_ISL_18751613, EPI_ISL_18751615,
EPI_ISL_18751618, EPI_ISL_18751681, EPI_ISL_18751780,
EPI_ISL_18751989, EPI_ISL_18792064-18792065, EPI_ISL_18793124,
EPI_ISL_18823339, EPI_ISL_18823388, EPI_ISL_18823457,
EPI_ISL_18823585, EPI_ISL_18823643, EPI_ISL_18823661,
EPI_ISL_18823670, EPI_ISL_18823716, EPI_ISL_18823745,
EPI_ISL_18823758, EPI_ISL_18823868, EPI_ISL_18823898,
EPI_ISL_18841467, EPI_ISL_18853043, EPI_ISL_18853131,
EPI_ISL_18853143, EPI_ISL_18853161, EPI_ISL_18853171,
EPI_ISL_18853181, EPI_ISL_18853195, EPI_ISL_18853197,
EPI_ISL_18853202, EPI_ISL_18853219, EPI_ISL_18853282,
EPI_ISL_18853286, EPI_ISL_18853292, EPI_ISL_18853311,
EPI_ISL_18853404, EPI_ISL_18853406, EPI_ISL_18853426,
EPI_ISL_18858430, EPI_ISL_18858434, EPI_ISL_18858445,
EPI_ISL_18858560, EPI_ISL_18860243, EPI_ISL_18869604,

Tree:
<img width="1162" alt="Screenshot 2024-02-07 alle 10 38 54" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/309f665a-bb39-4494-bc49-57067a577003">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_34002_34d1c0.json?c=gt-S_677&gmax=25384&gmin=21563&label=id:node_6903698

A sublineage has further acquired S:S680F in the FCS
Search: C23601T,T15756A,C18894T,G23593T,
Mutations Added: A29086T (a relatively large branch of JN.1*, nor sure if it is mentioned or not)->G23593T(S:Q677H) ,C23601T (S:S680F)
Samples: 29
First Sequence: EPI_ISL_18688878 Scotland 2023-11-30
Latest Sequence: EPI_ISL_18751611 South Korea 2024-01-02
Usher: 
<img width="909" alt="Screenshot 2024-01-23 at 2 39 58 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/c3019256-7d58-48ad-989f-3fffcead024c">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12c39_eb63d0.json?f_userOrOld=uploaded%20sample
Many of the sequences are actually trash as they contain too many reversions ( I hate South Korea for its trash sequences), but showing up in three countries is good enough for me, and if it is not completely an artefect, it could resemble the trend @LongDesertTrain have observed that multiple close to FCS mutations are now rising among JN.1*

**Comment by FedeGueli** [comment]
very good catch.

**Comment by FedeGueli** [comment]
please propose it

**Comment by FedeGueli** [comment]
@krosa1910 i have reorganized the proposal cause it seems that the parental branch with S:Q677H is growing.
So please propose it in the way i displayed above. Thank you

**Comment by krosa1910** [comment]
I think I would propose the Q677H branch, but the S680F also looks tempting so I would also include it.

**Comment by FedeGueli** [comment]
please propose it especially the 680F branch

**Comment by krosa1910** [comment]
108 seq and 49 for branch, I think I will propose it tomorrow (too tired today)

**Comment by krosa1910** [comment]
Transferred.

**Comment by FedeGueli** [comment]
Designated JN.1.36 via https://github.com/cov-lineages/pango-designation/commit/99bec760313aed2c5baf46ada5c6bb038226644b

**Comment by FedeGueli** [comment]
The sublineage with S:S680F designated JN.1.36.1 via https://github.com/cov-lineages/pango-designation/commit/dc9f2701f10970d700f6ef84c763995df66c77a5
