### ISSUE TITLE
JN.3 + S:L455V, ORF1a:T1168I, ORF1a:P2046L (6 seq, England, Mar 03)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1327]
Just four sequences in England right now, collection dates from Jan 1, 6, 9, 13.

JN.3  -->  A5641G   -->  C21676T  -->   C14478T  -->  C3768T, C6402T, T22925G, C28849T (ORF1a:T1168I, ORF1a:P2046L, S:L455V)

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.3_L455V.json?c=gt-S_455&gmax=25384&gmin=21563&label=id:node_6844699
<img width="1352" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a67b7a08-13cd-48e1-9e02-ba05481de7b5">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18771722, EPI_ISL_18800524, EPI_ISL_18800726, EPI_ISL_18800743
</details>

Query: C3768T, C6402T,C28849T,C14478T (Edited)

**Comment by FedeGueli** [comment]
Thx Ryan i ve added a query: C3768T, C6402T,C28849T,C14478T

**Comment by FedeGueli** [comment]
Dead
