### ISSUE TITLE
BA.5.2 saltation with S:P9L, S:Y144del, S:Q183del-G184H-N185D, S:D215G, S:Q218E, S:L244S, S:T315I, S:K356T, S:V445A, S:N450D, S:N460K, S:E484A->P, S:V486F rev, S:Q493E-S494P, S:A570V, S:T572S, S:G496R and 8 non-Spike aa mutations (singlet collected in Jan 6 2024, Indonesia)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1329]
Description:

mutations on top of BA.5.2:
Spike: P9L, Y144del, Q183del-G184H-N185D, D215G, Q218E, L244S, T315I, K356T, V445A, N450D, N460K, E484A->P, V486F (rev), Q493E-S494P, A570V, T572S, G946R

ORF1a: I1714T, T2197I, F3604L

ORF1b: Q215R, S1661I

ORF9b: G16D (rev), D89E 

N: T362I

GISAID query: C22506T, G23012C, C23277G

Usher Tree：
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10f0f_f87930.json

a BA.5.2* saltation with interesting Spike mutations, including K356T, N450D, A570V as popular in recent BA.2.86* lineages, and some really rare combo: Q493E-S494P, Q183del-G184H-N185D. 
Metadata shows the patient is a 32-year-old male.
It is a single seq now, but we can monitor it for a time.

Genomes:
EPI_ISL_18809509

**Comment by ryhisner** [comment]
It's fascinating to see how often the ORF9b:G16D reversion occurs in these chronic BA.5.2 sequences. I haven't tried to analyze it quantitatively, but it seems like about half of them have this reversion. Reminiscent of the ORF7a:A82V reversion that shows up in about half of chronic Deltas.

**Comment by FedeGueli** [comment]
no new sequence from this closing for now
