### ISSUE TITLE
BQ.1.1.40 with 10 spike mutations including Y453F - [2 patients, Ontario]

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#133]
Collected 5/21 and 5/22, both in Ontario, but with distinct patient metadata. 

**Gisaid Query**: spike_y453f,spike_t385i,spike_l452r

**Additional Spike Mutations:** 
S71Y, S112L, E132Q, Y144del, "N211del", D339H, T385i, Y453F, A653V, D1139H 

**Other mutations beyond basal BQ.1.1.40**
ORF1a: R24C, N2162S
ORF1b: M1839L
ORF3a: G100C
N: A252S

[Tree link](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/9edefe13-bb9c-4937-9e3f-e9079e802b5f)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/741950dd-4880-4a4c-a8db-f354dd458ecf)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/0f6bde47-0dce-4dc6-bc76-7b4b55a2ffd8)

**Discussion**
Due to having Y453F, this is scoring very high in binding affinity. Although there was a saltation that led to these two sequences, a lot of the mutations I list were acquired stepwise. Y144del is one of the mutations that's clearly very beneficial for BQ.1, and D339H is notable for being in BA.2.75 and XBB. T385i is notable for being on the rise globally recently. 
Other spike mutations seem to not appear to grant advantage when they show up. So overall I wouldn't say the mutational profile looks particularly bad. I am opening the issue due to it being on top of an already fit BQ spike, the fact that it has already infected a second or third patient after what appears to be 3-4 months of developing without transmission, and the possibility that with this many mutations it may be greater than the sum of its parts. 

I imagine this should be designated if it shows up outside of Ontario. 

EPI_ISL_17743168
EPI_ISL_17743165

**Comment by HynnSpylor** [comment]
Ah we coincidentally sent it out at the same time! #132
