### ISSUE TITLE
DV.7.1 saltation with 6 spike mutations - 2 patients, 4 seqs, Vigo, Spain [possibly artifact]

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#1330]
**Description:**
Three sequences are from a chronic patient, and one is from a separate patient. All sequences have substantial differences. I'll list the mutations for the separate patient, but give a query that catches all four sequences. 

Mutations on top of DV.7.1: 
Spike: N137D, L176F, Q218E, i434L, S486P, K795N

ORF1a: N1709S, M1769T, i2010T, V2324G, Y2353N, D4165N

ORF1b: R276H

ORF7a - T39i

N: P326L, V350F 

GISAID query: A5391G, C22214G, A23947T (Alternative query: G7246T,C14085T, C28744T edited)

**[Usher Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c349_febc40.json):**
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/5dbf5b71-0110-4979-81c8-5db21e86060b)

**Discussion:**
EPI_ISL_18805014 has different patient identifiers than EPI_ISL_18784438, EPI_ISL_18784385, EPI_ISL_18634703, which are all from the same patient. 
It notably doesn't match any of the three chronic sequences... it's 12 NT away from the closest sequence on the tree, EPI_ISL_18784438! If you look at the branch that links together these two sequences and separates them from the chronic patient's other two sequences, there's an interesting "pattern" though. The new patient and its closest sequence only are linked by mutations from 12758 and onwards -- and 8 of the 12 differences they have in mutations are from 7322 or before. 
...and two of the additional mutations before 7322 are in the EPI_ISL_18784385 sequence from the chronic patient. (4228 and 5571). EPI_ISL_18784385 has no mutations in this region that are NOT present in the new patient's sequence.

In other words, the new patient's sequence (collected Dec 22) could be a recombinant between more developed versions of the chronic patient's EPI_ISL_18784385 sequence (which was collected Dec 11), and a mostly current version of the patient's EPI_ISL_18784438 sequence (collected Dec 27). 

...but an issue in the theory is that the new patient's sequence also shares a unique mutation at 29250 with EPI_ISL_18784385, as well as a unique mutation with EPI_ISL_18784438 at 29321. This would mean that the mutation(s) were either coincidentally acquired independently, or there is multiple recombination breakpoints, or, what I think is the most likely, that the new patient's sequence somehow got contaminated with the chronic patient's sequences... possibly because the new patient is mislabeled and it actually is just another sequence from the chronic patient? 

I think we will need more sequences to make sense of it.

**Comment by FedeGueli** [comment]
i ve added an alternative query: G7246T,C14085T, C28744T

**Comment by FedeGueli** [comment]
no new sequence from this
