### ISSUE TITLE
JN.1.1 with 2nd ORF6 TRS (M:S136N)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1331]
**Description**
**Sub-lineage of:** JN.1.1 (BA.2.86.1.1.1)
**Earliest sequence:** 2023-11-30, Ontario, Canada — EPI_ISL_18611237
**Most recent sequence:** 2024-1-2, British Columbia, Canada — EPI_ISL_18806207
**Continents circulating:** North America (18)
**Countries circulating:** Canada (18)
**Number of Sequences:** 18
**GISAID Nucleotide Query:** C1762A, G26929A, T26930C
**CovSpectrum Query:** Nextcladepangolineage:JN.1.1* & [2-of: G26929A, T26930C]
**Substitutions on top of JN.1.1:**
**M:** S136N
**Nucleotide:** G26929A, T26930C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.1_G26929A_T26930C_2nd_ORF6_TRS.json?branchLabel=nuc%20mutations&c=gt-M_136&gmax=27191&gmin=26523&label=id:node_6861802
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/60f4364f-7366-4f77-a7bd-348f6d824a81">

**Evidence**
The first 17 sequences in this lineage were from Ontario, Canada, likely from a nursing home outbreak, which I believe is where the vast majority of Ontario clusters come from. But this is more than just a local cluster since the most recent sequence is from British Columbia, Canada, which is about 2000 miles (3300 km) from Ontario. 

M:S136N only requires one nucleotide mutation, but this lineage has two consecutive nucleotide mutations, G26929A and T26930C. The latter mutation is synonymous, but it has a purpose: it creates a full, optimal TRS (AAACGAAC). Annotated & unannotated images below. 

<img width="1449" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a1c687c3-a306-4af7-b074-79a111c109d5">
.

.
Somewhat surprisingly, the next start codon after this TRS is the ORF6 start codon, 268 nucleotides downstream. 
.

.
<img width="1120" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c87acc8f-d0f1-4d50-b3ff-6044892968ae">

I would expect this to result in a large increase in ORF6 sgmRNA production. Recent papers by Krogan Lab, Lucy Thorne, and others have emphasized the crucial role ORF6 plays in innate immune antagonism, primarily by preventing the importation of transcription factors like necessary for interferon production (like IRF3) into the nucleus. 
https://www.cell.com/cell-host-microbe/fulltext/S1931-3128(23)00328-1

Later Omicron variants like BA.5, BA.2.75, and XBB have much greater innate immune antagonism than BA.1 or BA.2, and this can partly be attributed to higher ORF6 production. So this mutation would likely increase the ability of JN.1.1 to suppress the host IFN response.
https://www.nature.com/articles/s41564-023-01588-4

16/18 sequences in this lineage also have N:P383L. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18611237, EPI_ISL_18643290, EPI_ISL_18643293,
EPI_ISL_18643296, EPI_ISL_18643324, EPI_ISL_18645403,
EPI_ISL_18645407-18645408, EPI_ISL_18645410, EPI_ISL_18645723,
EPI_ISL_18645793, EPI_ISL_18645800, EPI_ISL_18645819,
EPI_ISL_18645935, EPI_ISL_18645937, EPI_ISL_18696345,
EPI_ISL_18697057, EPI_ISL_18806207
</details>

**Comment by FedeGueli** [comment]
No recent sample closing it
