### ISSUE TITLE
JN.1 with ORF9b:L64P (229 seq)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1332]
### **Description**
**Sub-lineage of:** JN.1 (BA.2.86.1.1)
**Earliest sequence:** 2023-10-15, USA Colorado — EPI_ISL_18507641
**Most recent sequence:** 2024-1-10, USA, Iowa — EPI_ISL_18791520 + 1 more
**Continents circulating:** North America (74)
**Countries circulating:** USA (62), Canada (10), Puerto Rico (2)
**Number of Sequences:** 74
**GISAID Nucleotide Query:** C897A, T29417C, T28474C
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [2-of: T28474C, T29417C]
**Substitutions on top of JN.1:**
**ORF9b:** L64P
**Nucleotide:** T28474C, T29417C

**Phylogenetic Order of Mutations:**   T29417C   **→**  T28474C (ORF9b:L64P) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_ORF9b.L64P.json?c=gt-nuc_28474&gmax=29474&gmin=27474&label=id:node_6862367
<img width="1490" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/fdc56139-95ea-4d7e-9ead-8d74390544ff">

**Evidence**
ORF9b:L64P is a rare mutation but one that’s frequently seen in highly mutated chronic-infection sequences. So far this lineage is concentrated in the US Midwest, particularly Iowa, Minnesota, and Illinois, but there are 10 sequences from Canada (7 Alberta, 3 Ontario), two sequences from Puerto Rico, five from the US East Coast, and five from California. 

ORF9b has a solid positive fitness score on the Bloom Lab fitness mutation calculator. 
https://jbloomlab.github.io/SARS2-mut-fitness/ORF9b.html
<img width="936" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f88b16d5-4516-4ef7-963f-1a48bdc5352d">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18507641, EPI_ISL_18519478, EPI_ISL_18543933,
EPI_ISL_18543939, EPI_ISL_18592044, EPI_ISL_18592606,
EPI_ISL_18592648, EPI_ISL_18608561, EPI_ISL_18609216,
EPI_ISL_18609226, EPI_ISL_18609264, EPI_ISL_18622971,
EPI_ISL_18622992, EPI_ISL_18636473, EPI_ISL_18643383,
EPI_ISL_18647383, EPI_ISL_18647386, EPI_ISL_18647415,
EPI_ISL_18654105, EPI_ISL_18659276, EPI_ISL_18677672,
EPI_ISL_18677728, EPI_ISL_18677801, EPI_ISL_18683058,
EPI_ISL_18686459, EPI_ISL_18691307, EPI_ISL_18691728,
EPI_ISL_18699821, EPI_ISL_18699880, EPI_ISL_18699924,
EPI_ISL_18699982, EPI_ISL_18700056, EPI_ISL_18709707-18709708,
EPI_ISL_18709717, EPI_ISL_18731020, EPI_ISL_18731118,
EPI_ISL_18731135, EPI_ISL_18732512, EPI_ISL_18733901,
EPI_ISL_18735154, EPI_ISL_18742676, EPI_ISL_18742736,
EPI_ISL_18742752-18742753, EPI_ISL_18749423, EPI_ISL_18752904,
EPI_ISL_18756493, EPI_ISL_18756548, EPI_ISL_18756554,
EPI_ISL_18772859, EPI_ISL_18776092, EPI_ISL_18776163,
EPI_ISL_18779229, EPI_ISL_18779401, EPI_ISL_18779435,
EPI_ISL_18783917, EPI_ISL_18783994-18783995, EPI_ISL_18785629,
EPI_ISL_18787114, EPI_ISL_18787434-18787435, EPI_ISL_18787530,
EPI_ISL_18787726, EPI_ISL_18791515, EPI_ISL_18791520,
EPI_ISL_18791532, EPI_ISL_18797559, EPI_ISL_18803275,
EPI_ISL_18804195, EPI_ISL_18804408, EPI_ISL_18809200,
EPI_ISL_18809268
</details>

**Comment by FedeGueli** [comment]
Please propose it

**Comment by aviczhl2** [comment]
229 now.

**Comment by FedeGueli** [comment]
it seems going down, i would wait for proposing it in the wake of FLIRT dominance i don't see this to survive even if Or9b lin egaes are always very resilient.

**Comment by FedeGueli** [comment]
277 no recent one so i m closing it
