### ISSUE TITLE
HK.1 (FLip, formerly designated HK.1.1 and then retracted) cluster with S:E583D in Japan (16)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1337]
I noticed this japanese cluster of HK.1+FLip that gained S:E583D along with several AA substitutions acquired through stepwise evolution.

Defining mutations:
HK.1 > S:L455F (G22927T) > Orf1a:E972K (G3179A), N:T135N (C28677A), G29706C > C25521T > Orf1a:A516V (C1812T) , T6001A, A8302G, C13761T, Orf3a:T269M (C26198T) > Orf1b:V548I (G15109A), T28735C > S:E583D (G23311C), T27555C

Query: G15109A , G23311C
Samples: 16 All from Japan , all from January
EPI_ISL_18815057-18815059, EPI_ISL_18815061-18815062, EPI_ISL_18815064-18815073,
EPI_ISL_18815075

Tree:
<img width="1162" alt="Screenshot 2024-01-24 alle 18 37 03" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bc81cb70-f1ae-4d16-ab96-dd2f9fa79b8d">
<img width="1154" alt="Screenshot 2024-01-24 alle 18 37 18" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b49ba717-a9b6-4706-bc19-8e92a22dc59f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2f4bc_116c00.json?c=gt-S_583&gmax=25384&gmin=21563&label=id:node_3509645

**Comment by aviczhl2** [comment]
It seems that it involves a 3' recomb with non-XBB.1.9.2* XBB.1+Orf9b:I5T
