### ISSUE TITLE
JN.1 with S:Y505del (2 seq/patients, Spain) [possibly artifact?]

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#1341]
EPI_ISL_18821930
EPI_ISL_18764848

Collection dates are Dec 22 and Dec 27. They are both in Albacete Spain, but are different patients. **These are the only two sequences in the entire pandemic that have S:Y505del, but no mutation at S:504 or S:506**. 

USHER doesn't group them on the same tree, but they don't differ by enough from each other that I believe it to be strong evidence they are unrelated. 

One of the sequences also has a reversion at S:408.

**Comment by FedeGueli** [comment]
Closing for now
