### ISSUE TITLE
GK.10 sublineage with S:K356T and S:A475V (45 seq. Brazil)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#1344]
Defining mutations: GK.10 then nuc:C27131T then nuc:G4255A+nuc:T12730C+nuc:A15948G+nuc:C21057T+S:K356T(A22629C)+S:A475V(C22986T)+nuc:T23542C
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f479_372040.json?label=id:node_3786649
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/77e74523-b91e-43a2-9a2a-7e241c22149a)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70.10*%26S%3AA475V&

Query: T12730C, A15948G (edited)

**Comment by FedeGueli** [comment]
Added query: T12730C, A15948G

**Comment by FedeGueli** [comment]
Spreading fast in Paraiba and Maranao

**Comment by aviczhl2** [comment]
44 now

**Comment by FedeGueli** [comment]
one only from February

**Comment by FedeGueli** [comment]
dead
