### ISSUE TITLE
JN.1.5 + 6 aa mutations and 3 Spike mutations (E96D, F456L, S680F) (2 in Singapore)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1346]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1df760eb-9670-4f19-9450-6870341fb606)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_221ed_492d70.json?c=gt-S_96&gmax=25384&gmin=21563&label=id:node_6887657

Seq: 2024-01-15

Gisaid Query: G9904A, G15836T, G17252A, G21850T, C28332A

EPI_ISL_18806827  EPI_ISL_18806842

Mutations: 

ORF1b: C790F, R1262H
S: E96D, F456L, S680F
ORF8: T26I, T80E
N: P20H
ORF9b:P17T

**Comment by ryhisner** [comment]
ORF8:T80E is a 2-nuc mutation that often comes paired with a 3rd mutation. It's always happening behind a stop codon, so it has to be about RNA structure or RNA interactions, not the AA substitutions. 

<img width="1460" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/71279003-fcda-4270-9094-01a7209adffd">



Here are two other multi-nuc patterns that have showed up in the exact same area, again, virtually always behind a stop codon. I really don't know what's going on here. There's no TRS pattern.

<img width="1401" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ea697dcf-6d55-444b-ab9d-2b69bff93593">

**Comment by ryhisner** [comment]
The only possible hint on the ORF8:T80E/ORF8:V81I is that there are two 10-nuc stretches in the SARS-CoV-2 genome that match the A28131G-C28132A-G21834A stretch. The first is in NSP14, 17357-17566.

<img width="1048" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1721cb71-141a-49e7-8b03-9bd575b274ef">

The second is at the very beginning of ORF8, starting with the ORF8 start codon, 27894-27903. 

This stretch from 27894-27909 actually matches 15/16 nucs from 28129-28144, so it seems like a pretty likely source.

<img width="1507" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e414795e-ac9a-4e19-8cc9-f7a200fea5cd">

**Comment by FedeGueli** [comment]
> The only possible hint on the ORF8:T80E/ORF8:V81I is that there are two 10-nuc stretches in the SARS-CoV-2 genome that match the A28131G-C28132A-G21834A stretch. The first is in NSP14, 17357-17566.
> 
> <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/33738461/300202947-1721cb71-141a-49e7-8b03-9bd575b274ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODY1NzcsIm5iZiI6MTcwNjM4NjI3NywicGF0aCI6Ii8zMzczODQ2MS8zMDAyMDI5NDctMTcyMWNiNzEtMTQxYS00OWU3LThiMDMtOWJkNTc1YjI3NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIwMTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGM0MjBiMWZkMzgwMWRiMmY5NGI4ZmE3Mjc1YTFjMjczMDVlOTgwMGI3ZWY1Y2QyODE2YzU5MDA3YjZjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oxc0ukTFLE35fUik8-7wr5lwbmVNj58pMLGLQ4aWFHk">
> The second is at the very beginning of ORF8, starting with the ORF8 start codon, 27894-27903.
> 
> This stretch from 27894-27909 actually matches 15/16 nucs from 28129-28144, so it seems like a pretty likely source.
> 
> <img alt="image" width="1507" src="https://private-user-images.githubusercontent.com/33738461/300206270-e414795e-ac9a-4e19-8cc9-f7a200fea5cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODY1NzcsIm5iZiI6MTcwNjM4NjI3NywicGF0aCI6Ii8zMzczODQ2MS8zMDAyMDYyNzAtZTQxNDc5NWUtYWM5YS00ZTE5LThjYzktZjdhMjAwZmVhNWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIwMTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjEwYWI1MjJkNTIzNTZkNjcwNzZmNzU5OGVlYThkM2VkYjY4MDM0NGQxZGMzMWQxMTQwMWY5Yzk0YTM3YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hazfRIM9mTbz-xaApsbFu4hKljsvJ1Lrnmm6t_F2yKM">

Thx Ryan!
