### ISSUE TITLE
DV.7 Sublineage With S:455F, S:456L - 10 Sequences (Spain)

### ISSUE THREAD

**Issue by plomano** [sars-cov-2-variants/lineage-proposals#135]
### **Description**
**Sublineage of:** DV.7 (EDITED)
**Earliest Sequence:** 2023-05-16, Spain - Asturias - EPI_ISL_17726537
**Latest Sequence:** 2023-05-22, Spain - Asturias - EPI_ISL_17762415
**Countries Circulating:** Spain (9)
**Number of Sequences:** 9
**GISAID Query:** G22927T, T22928C, G22331A
**CovSpectrum Query:** G22927T & T22928C & G22331A

**Substitutions on Top of CH.1.1.1:**
**Spike:** L455F, F456L
**Nucleotide:** G22927T, T22928C

Complete defining mutations (**EDITED**):
DV.7 (S:L858I )>> T4036A >> C2227T, T25959C >> Orf1b:A520V >> Orf3a:A72T (G25606A)>S:L455F (G22927T) ,  F456L (T22928C)

### USHER Tree

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_130f4_a99b30.json?f_userOrOld=uploaded%20sample&showBranchLabels=all

![245222258-655250d1-f0fe-4253-afda-a14833e12b0c](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115512395/d0e7fa14-af40-4afe-9e4b-23ffb4ded6d9)

### Evidence

The 455F and 456L swap is a rare but yet recurring combination that hints at some sort of epistasis. Due to the prominence of 456L in some XBB lineages it has occurred more commonly on that background. 

This sample seems to be the first time a CH* sublineage has obtained this mutation combo. This may provide an advantage in the current immune environment, however it is hard to tell if 455F/456L will see a fitness increase on this particular background or if this will fizzle out.

<details>

EPI_ISL_17726537,

EPI_ISL_17762415

<summary>Genomes:</summary></details>

**Comment by plomano** [comment]
Up to a second one, same region.

**Comment by ryhisner** [comment]
This lineage appears to be up to nine sequences, though only six seem to be on GISAID at the moment. One of the sequences has two additional spike mutations—S:P728L and S:T1117I. I've scrubbed the duplicate sequences from the Usher tree picture below. 
<img width="1367" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/655250d1-f0fe-4253-afda-a14833e12b0c">

**Comment by plomano** [comment]
Thanks, Ryan!

I can only see 4 on CoV-Spectrum, so I updated the main post via your info, as long as you're ok with it.

**Comment by FedeGueli** [comment]
All very recent ones, Paul please propose it once gets one outside Spain without evident link to travel to Spain.

**Comment by FedeGueli** [comment]
New sample of this one uploaded today from Spain , Asturias.

@plomano i ve changed the title and the proposal cause this now belongs to DV.7

New tree:
![Schermata 2023-06-19 alle 19 12 03](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/506aff16-4d13-4847-9283-b0c98433e968)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28a51_8be30.json?label=id:node_7248199

Ping @corneliusroemer 455+456 expanding on CH.1.1 backbone.

**Comment by Sinickle** [comment]
This one scores a -1.05 on binding affinity relative to BA.2 on Nextclade.

**Comment by FedeGueli** [comment]
Very recent spanish sample from this lineage acquired further S:N354K and S:T778I lacking also S:N764K without a clear sign of being unreal.  EPI_ISL_17949962
