### ISSUE TITLE
GE.1.2.1 with S:Q1201K spreading in Uk,Ireland (56)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1351]
Just noticed that there is an Uk branch of GE.1.2.1 featuring S:Q1201K ( that is a single nuc mutation but usually for unknown reasons preceeded by another silent chang in the third nucleotide of S:1200. cc @ryhisner 

Defining mutations:

GE.1.2.1 >> C583T, Orf1b:N2328S (A20450G ) > Orf1a:A2142V (C6690T) > A1051G > C25162A, S:Q1201K ( C25163A)

Query: A1051G,C25162A, C25163A

Samples: 39 Uk, Netherlands
First collected on 2023-11-22
IDs:
EPI_ISL_18618402, EPI_ISL_18635662, EPI_ISL_18641322,
EPI_ISL_18641517, EPI_ISL_18652358, EPI_ISL_18673286,
EPI_ISL_18687966, EPI_ISL_18688141, EPI_ISL_18688543,
EPI_ISL_18688872, EPI_ISL_18694789, EPI_ISL_18694802,
EPI_ISL_18694810, EPI_ISL_18707869, EPI_ISL_18712893,
EPI_ISL_18727033, EPI_ISL_18727107, EPI_ISL_18727423,
EPI_ISL_18727430, EPI_ISL_18727710, EPI_ISL_18735453,
EPI_ISL_18735480, EPI_ISL_18735866, EPI_ISL_18754743,
EPI_ISL_18754828, EPI_ISL_18763539, EPI_ISL_18763571,
EPI_ISL_18763680, EPI_ISL_18763762, EPI_ISL_18763782,
EPI_ISL_18763862, EPI_ISL_18800657-18800658, EPI_ISL_18800661,
EPI_ISL_18801239, EPI_ISL_18815845, EPI_ISL_18824289,
EPI_ISL_18824551, EPI_ISL_18831840

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_49536_8d5c40.json?c=gt-S_1201&label=id:node_4130695
<img width="1162" alt="Screenshot 2024-01-30 alle 12 06 57" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bf929e39-c06e-441c-afab-81826ea6370d">

**Comment by JosetteSchoenma** [comment]
44 now. 1 in Ireland as well.

**Comment by FedeGueli** [comment]
54 none from March

**Comment by FedeGueli** [comment]
thx @aviczhl2 only 2 in March i m closing it
