### ISSUE TITLE
JN.1 with S:K478R + 2-nuc N:L121S (6 seq, Jan 30)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1353]
### **Description**
**Sub-lineage of:** JN.1 (BA.2.86.1.1)
**Earliest sequence:** 2023-11-24, England — EPI_ISL_18592157
**Most recent sequence:** 2024-1-15, Canada, Quebec — EPI_ISL_18839387
**Continents circulating:** Europe (4), North America (2)
**Countries circulating:** England
**Number of Sequences:** 6
**GISAID Nucleotide Query:** G18811A, C14120T, A13947C, C4795T, A22161G, -del27795, -A21794C 
**Alterantive Query** : C22995G, C28634T, T28635C (edited)
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [2-of: C28634T, T28635C]
**Substitutions on top of JN.1:**
**Spike:** K478R
**N:** L121S
**Nucleotide:** A22995G, C28634T, T28635C

**Phylogenetic Order of Mutations:**  A22995G (S:K478R) **→**  C28634T, T28635C (N:L121S) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_K478R_N.L121S.json?c=gt-N_121&gmax=29533&gmin=28274&label=id:node_6896448
<img width="1488" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2b2203d3-3d00-4609-9649-a28a16243e30">

**Evidence**
In all likelihood this is a minor branch that will go nowhere, but I'm fascinated by it because of the 2-nucleotide N:L121S mutation, which has only ever appeared in four legit previous sequences. In fact, despite C->T mutations being by far the most common and T->C mutations also being among the most common, there have only been about 80 legit sequences in the entire pandemic with either C28634T or T28635C. 

<img width="1329" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/440294f5-13a4-494e-818e-70cd065a497b">

This branch also has an oddly wide geographic spread for such a small branch, particularly since the first sequence appeared on November 24 in England, a country with good surveillance. It has appeared in England, Scotland, two distant provinces of Canada (Alberta and Quebec), and Sweden. The last four sequences were collected between January 6 and January 15. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18592157, EPI_ISL_18793850, EPI_ISL_18811003,
EPI_ISL_18817485, EPI_ISL_18832399, EPI_ISL_18839387
</details>

**Comment by FedeGueli** [comment]
@ryhisner i have added C22995G, C28634T, T28635C cause your one finds 42 samples!

**Comment by FedeGueli** [comment]
Slow closing it

**Comment by aviczhl2** [comment]
Branch with only S:478R but without the N:L121S is growing.  

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3b600d9f-3097-43ba-9837-254aabc8ccc0)

**Comment by DailyCovidCases** [comment]
No new seqs

**Comment by FedeGueli** [comment]
dead
