### ISSUE TITLE
JG.3/JN.11 or #1095 recombinant (2 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1354]
The 2 seqs are both from NY but from different NY counties and different patients(one aged 92 and the other 1), so propose it.

JG.3--JN.11 or #1095
Breakpoint between 21619 and 21710 (S:16 and S:50)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9948248c-687d-47ec-aeea-4d5fb96445a3)

No additional mutations

GISAID query: C7086T,C21711T,G24872T
No. of seqs: 2(USA-NY)

EPI_ISL_18838324, 2023-12-31
EPI_ISL_18838431, 2024-1-3

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3e8df_9f5690.json?f_userOrOld=uploaded%20sample&label=id:node_11236553)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/5892d4e3-1a50-4dd5-8472-404b7626e102)

**Comment by kevsilva** [comment]
Hi,

We detected 3 JG.3/JN.1.1 recombinants in France:
EPI_ISL_18842774
EPI_ISL_18800192
EPI_ISL_18800327

However, they have different mutations, especially in ORF1b, so I was not sure to continue in this issue or create a new one.
![Capture d’écran du 2024-01-31 12-16-06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/48321731/f876c360-7e79-42a8-8441-1bec159ab19d)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ea44_a2a9a0.json?f_userOrOld=uploaded%20sample&label=id:node_5479201)
![Capture d’écran du 2024-01-31 12-11-36](https://github.com/sars-cov-2-variants/lineage-proposals/assets/48321731/33ba2b01-777f-42f4-b111-68e7847cff83)

**Comment by FedeGueli** [comment]
> Hi,
> 
> We detected 3 JG.3/JN.1.1 recombinants in France: EPI_ISL_18842774 EPI_ISL_18800192 EPI_ISL_18800327
> 
> However, they have different mutations, especially in ORF1b, so I was not sure to continue in this issue or create a new one. ![Capture d’écran du 2024-01-31 12-16-06](https://private-user-images.githubusercontent.com/48321731/301140381-f876c360-7e79-42a8-8441-1bec159ab19d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDI0NTAsIm5iZiI6MTcwNjcwMjE1MCwicGF0aCI6Ii80ODMyMTczMS8zMDExNDAzODEtZjg3NmMzNjAtN2U3OS00MmE4LTg0NDEtMWJlYzE1OWFiMTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExNTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MzIwOTBlOTgzMzk2ZGQwMTU0ZGIyYjFiNjQ5Mzk0MzJmZDUyYzE4MTJjYzA1NjQwMmJkYjgwZWUyZjliNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._7MQHL-QMCO51mfr4oxoyAQ8qr9lw3-c79k8w8zG7xM)
> 
> [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ea44_a2a9a0.json?f_userOrOld=uploaded%20sample&label=id:node_5479201) ![Capture d’écran du 2024-01-31 12-11-36](https://private-user-images.githubusercontent.com/48321731/301140836-33ba2b01-777f-42f4-b111-68e7847cff83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDI0NTAsIm5iZiI6MTcwNjcwMjE1MCwicGF0aCI6Ii80ODMyMTczMS8zMDExNDA4MzYtMzNiYTJiMDEtNzc3Zi00MmY0LWIxMTEtNjhlNzg0N2NmZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExNTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTYwNzYxMmFmYWJjNDRmNmE2ZjNjMjUzODlhODY3YjhiOGIxODU0NDU4OWNkZTI3N2I5YTZhNDA3MWE4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiliQEQnFatIFB0LWYspwkoRKsudrdxBtIyQIiT0KI8)

Please propose it in a new issue

**Comment by aviczhl2** [comment]
> Hi,
> 
> We detected 3 JG.3/JN.1.1 recombinants in France: EPI_ISL_18842774 EPI_ISL_18800192 EPI_ISL_18800327
> 
> However, they have different mutations, especially in ORF1b, so I was not sure to continue in this issue or create a new one. ![Capture d’écran du 2024-01-31 12-16-06](https://private-user-images.githubusercontent.com/48321731/301140381-f876c360-7e79-42a8-8441-1bec159ab19d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDMyNzIsIm5iZiI6MTcwNjcwMjk3MiwicGF0aCI6Ii80ODMyMTczMS8zMDExNDAzODEtZjg3NmMzNjAtN2U3OS00MmE4LTg0NDEtMWJlYzE1OWFiMTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjcwZjk3ODAwYWNlYWEwMDM5NTE2NzNmZWE3MjlhZDhhYzM0MTlmNWQ2MTBlMWMzOWJkMmEwMzBlMWM3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3NCQtFOsGg56Js-ekcAfpQFNM_vmmHroAvPcOoaFXI)
> 
> [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ea44_a2a9a0.json?f_userOrOld=uploaded%20sample&label=id:node_5479201) ![Capture d’écran du 2024-01-31 12-11-36](https://private-user-images.githubusercontent.com/48321731/301140836-33ba2b01-777f-42f4-b111-68e7847cff83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDMyNzIsIm5iZiI6MTcwNjcwMjk3MiwicGF0aCI6Ii80ODMyMTczMS8zMDExNDA4MzYtMzNiYTJiMDEtNzc3Zi00MmY0LWIxMTEtNjhlNzg0N2NmZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMTNkOGZhYjg0N2U0NDk5MzkwOTU5MDQyODllYjdlZDk1NGViOTM4NzI4ZGFiNTA2ODhjYTAzMjJhZjI0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvPtPyBzq3e9qpkYvL9RMtS1oKf_NoUaIS8JxKKbAyg)

@AngieHinrichs, These French recombs are previously listed in recombinants.tsv but not added to the tree. 

@FedeGueli they are separate recombs from this one though.  This one is recombinant of JG.3 and JN.11, not JN.1.1.

**Comment by FedeGueli** [comment]
> > Hi,
> > We detected 3 JG.3/JN.1.1 recombinants in France: EPI_ISL_18842774 EPI_ISL_18800192 EPI_ISL_18800327
> > However, they have different mutations, especially in ORF1b, so I was not sure to continue in this issue or create a new one. ![Capture d’écran du 2024-01-31 12-16-06](https://private-user-images.githubusercontent.com/48321731/301140381-f876c360-7e79-42a8-8441-1bec159ab19d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDMyNzIsIm5iZiI6MTcwNjcwMjk3MiwicGF0aCI6Ii80ODMyMTczMS8zMDExNDAzODEtZjg3NmMzNjAtN2U3OS00MmE4LTg0NDEtMWJlYzE1OWFiMTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjcwZjk3ODAwYWNlYWEwMDM5NTE2NzNmZWE3MjlhZDhhYzM0MTlmNWQ2MTBlMWMzOWJkMmEwMzBlMWM3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3NCQtFOsGg56Js-ekcAfpQFNM_vmmHroAvPcOoaFXI)
> > [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3ea44_a2a9a0.json?f_userOrOld=uploaded%20sample&label=id:node_5479201) ![Capture d’écran du 2024-01-31 12-11-36](https://private-user-images.githubusercontent.com/48321731/301140836-33ba2b01-777f-42f4-b111-68e7847cff83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDMyNzIsIm5iZiI6MTcwNjcwMjk3MiwicGF0aCI6Ii80ODMyMTczMS8zMDExNDA4MzYtMzNiYTJiMDEtNzc3Zi00MmY0LWIxMTEtNjhlNzg0N2NmZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMTNkOGZhYjg0N2U0NDk5MzkwOTU5MDQyODllYjdlZDk1NGViOTM4NzI4ZGFiNTA2ODhjYTAzMjJhZjI0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvPtPyBzq3e9qpkYvL9RMtS1oKf_NoUaIS8JxKKbAyg)
> 
> @AngieHinrichs, These French recombs are previously listed in recombinants.tsv but not added to the tree.
> 
> @FedeGueli they are separate recombs from this one though. This one is recombinant of JG.3 and JN.11, not JN.1.1.

thank u

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs, These French recombs are previously listed in recombinants.tsv but not added to the tree.

The two EPI_ISL_1880* are in the 2024-01-30 tree. The EPI_ISL_1884* sequence has not been downloaded yet, but should be downloaded tonight and added to the tree tomorrow (2024-02-01).  https://github.com/sars-cov-2-variants/lineage-proposals/issues/1356#issuecomment-1919601854

**Comment by aviczhl2** [comment]
No new seqs
