### ISSUE TITLE
JG.3/JN.1 recombinant (7 seqs, France,USA)

### ISSUE THREAD

**Issue by kevsilva** [sars-cov-2-variants/lineage-proposals#1356]
JG.3/JN.1 recombinant from France.

Breakpoint between 12,816-13,338.
![Capture d’écran du 2024-01-31 14-17-46](https://github.com/sars-cov-2-variants/lineage-proposals/assets/48321731/4450218f-e61e-4cfb-a351-412c1c2f7076)

Three sequences:
EPI_ISL_18842774
EPI_ISL_18800192
EPI_ISL_18800327

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_49e7_a47380.json?f_userOrOld=uploaded%20sample&label=id:node_9633902)
![Capture d’écran du 2024-01-31 14-18-06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/48321731/5c46aa6c-c075-4c5f-b1cf-9f4f477e59c1)

**Comment by FedeGueli** [comment]
Putative query:C1889T, C2334T, G5720A,  C23557T,C18894T

**Comment by aviczhl2** [comment]
@AngieHinrichs, this is another recomb in recombinants.tsv that is not added in usher tree,

**Comment by AngieHinrichs** [comment]
The two EPI_ISL_1880* are in the 2024-01-30 tree.  The EPI_ISL_1884* sequence has not been downloaded yet, but should be downloaded tonight and added to the tree tomorrow (2024-02-01).

**Comment by FedeGueli** [comment]
sorry wrong issue updated.

**Comment by FedeGueli** [comment]
Likely just a cluster

**Comment by aviczhl2** [comment]
+4 USA

**Comment by FedeGueli** [comment]
if C1889T, C2334T, G5720A, C23557T,C18894T is the correct query it is very likely dead

**Comment by aviczhl2** [comment]
Is this one XDZ? @corneliusroemer

**Comment by aviczhl2** [comment]
Seems it is.

**Comment by corneliusroemer** [comment]
Sound like it yes, based on the 23577

We disagree regarding breakpoints though, I might be wrong

**Comment by FedeGueli** [comment]
XDZ via https://github.com/cov-lineages/pango-designation/commit/d734b84fe1405676518a8eac05a51977b20657e6
