### ISSUE TITLE
EG.5.1.1/JN.1.4.5 recombinant (9 seqs, Australia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1357]
One more previous singlet registered in #991 gets company.

EG.5.1.1--Pango#2426(JN.1.4+Orf8:S103L)
Breakpoint between 14890 and 15755
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/408d3757-4b61-4eb9-87bc-56569aa4d0e9)

Additional mutations:C14889T,C17766T, C28948T,G29527T
N:Q418H

C14889T from an EG.5.1.1 branch(many candidates)
C28948T from a sub-branch of Pango#2426
C17766T, G29527T are private

GISAID query: C28948T,C14889T,C18894T
No. of seqs: 3(Australia)

First:EPI_ISL_18815003, 2023-1-16
Latest: EPI_ISL_18841427, 2023-1-17

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice15_genome_test_67e04_b08540.json?label=id:node_11239796)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f71eeff8-6390-484b-a604-f0dd10ef1958)

**Comment by CaitlinSelway** [comment]
Hi @aviczhl2, to add to this post there are 5 more genomes from Australia (see names below) that are expected to have the same recombinant profile as the profile you have posted (one with some missing data). These have been uploaded to GISAID. 

hCoV-19/Australia/SA1252254/2024 (sample with missing data)
hCoV-19/Australia/SA1254671/2024
hCoV-19/Australia/SA1254675/2024
hCoV-19/Australia/SA1254672/2024
hCoV-19/Australia/SA1254685/2024

**Comment by aviczhl2** [comment]
> Hi @aviczhl2, to add to this post there are 5 more genomes from Australia (see names below) that are expected to have the same recombinant profile as the profile you have posted (one with some missing data). These have been uploaded to GISAID.
> 
> hCoV-19/Australia/SA1252254/2024 (sample with missing data) hCoV-19/Australia/SA1254671/2024 hCoV-19/Australia/SA1254675/2024 hCoV-19/Australia/SA1254672/2024 hCoV-19/Australia/SA1254685/2024

Thanks.
BTW are you sure about hCoV-19/Australia/SA1252254/2024 ?It doesn't have EG.5.1.1 signature mutations and JN.1.4 signature mutations.

**Comment by CaitlinSelway** [comment]
I don't mind if it's not counted in the numbers for this purpose. Based on nextclade (see image), it was missing data in the regions for mutations defining this new recombinant, possibly due to low sequencing depths in these regions, but had a very similar arrangement of the genome. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/84895885/8d4cd135-cb36-4d9a-aa23-30e5296ed530)

**Comment by aviczhl2** [comment]
> I don't mind if it's not counted in the numbers for this purpose. Based on nextclade (see image), it was missing data in the regions for mutations defining this new recombinant, possibly due to low sequencing depths in these regions, but had a very similar arrangement of the genome.


I think that one is a sandwich recomb of this recomb and JN.1.  It has the signature mutation 29527 for this recomb, but clearly it isn't JN.1.4 in the middle. 
It also doesn't have 14889 and 13627, which may due to its 1st BP is before 13627(and after 12815)

**Comment by FedeGueli** [comment]
i ve put it un der closer monitoring i think it will be worth a proposal soon

**Comment by FedeGueli** [comment]
<img width="1143" alt="Screenshot 2024-02-15 alle 10 03 07" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b97ba668-2f1c-4805-bbf7-590b228ffecc">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_a37d_dd08a0.json?c=userOrOld&label=id:node_6961022

There is an unrelated (in my view but help wanted) sibling of this one that has popped up in US with 2 samples : 
USA/CA-HLX-STM-7SSQDSMDZ/2024|EPI_ISL_18834967|2024-01-01
hCoV-19/USA/CA-CDC-QDX91916022/2024|EPI_ISL_18895341|2024-01-26

the previous singlet was reported in #991

**Comment by FedeGueli** [comment]
> <img alt="Screenshot 2024-02-15 alle 10 03 07" width="1143" src="https://private-user-images.githubusercontent.com/87669813/305013126-b97ba668-2f1c-4805-bbf7-590b228ffecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODgzMDksIm5iZiI6MTcwNzk4ODAwOSwicGF0aCI6Ii84NzY2OTgxMy8zMDUwMTMxMjYtYjk3YmE2NjgtMmYxYy00ODA1LWJiZjctNTkwYjIyOGZmZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA5MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZDNjMGJlODU2MzhlYTA1YzA5NTA1ZjQzNDMxZDI2YWQ2OThlZTBlZjQ3OWFjMjlhNGNlMTk3ZGVhMzIyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SiX2WC7fcXn9n4CPdIWQyKldUAy6fDvif3Kqx7denEo"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_a37d_dd08a0.json?c=userOrOld&label=id:node_6961022
> There is an unrelated (in my view but help wanted) sibling of this one that has popped up in US with 2 samples : USA/CA-HLX-STM-7SSQDSMDZ/2024|EPI_ISL_18834967|2024-01-01 hCoV-19/USA/CA-CDC-QDX91916022/2024|EPI_ISL_18895341|2024-01-26
> 
> the previous singlet was reported in #991

for sure unrelated due lacking orf8:103 so it is another JN.1.4 sublineage and another recombinant event.

**Comment by aviczhl2** [comment]
> for sure unrelated due lacking orf8:103 so it is another JN.1.4 sublineage and another recombinant event.

#1383

**Comment by aviczhl2** [comment]
Seems that one of the seqs is removed from GISAID. Now the count is 7.

**Comment by FedeGueli** [comment]
> > for sure unrelated due lacking orf8:103 so it is another JN.1.4 sublineage and another recombinant event.
> 
> #1383

thank you

**Comment by aviczhl2** [comment]
No new seqs

**Comment by aviczhl2** [comment]
1 more from Australia

**Comment by aviczhl2** [comment]
No new seqs
