### ISSUE TITLE
Another XBB.1.5 sublineage with S:L455F and S:F456L in Brazil (7 seq)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#136]
EPI_ISL_17514981
EPI_ISL_17737679
EPI_ISL_17737657
Substitutions on top of XBB.1.5: C14085T then C19488T+C6896T then A14634G+A19182G+S:L455F(G22927T)+S:F456L(T22928C)+S:P1162S(C25046T)+T28282C
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/e5b2a9d3-66d3-48aa-ac22-0ec89b24f866)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f842_b85500.json?f_userOrOld=uploaded%20sample
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3AL455F%26S%3A456L%26S%3AP1162S&
The XBB.1.5+C14085T+C19488T+C6896T subbranch is quite large. Maybe it deserves its own designation.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5*%26C14085T%26C19488T%26C6896T&

Gisaid query: A19182G, G22927T finds 7 samples (checking them now)

**Comment by FedeGueli** [comment]
T28282C is directly at P-2 in the Kozak sequence of Orf9b:
![Schermata 2023-06-04 alle 00 22 43](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bfffc753-7113-4779-b4cb-3fbaf3facd89)
![Schermata 2023-06-04 alle 00 23 02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e9b21308-beb9-428e-89be-cf75a91a08dd)

It should improve it a lot cc @ryhisner

**Comment by ryhisner** [comment]
Yes, excellent observation, Fede! T28282C occurs relatively frequently and has been most commonly seen in CM.12, a pretty successful BA.2.3.20 sublineage, over the past 6 months. 
<img width="1314" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2af56b86-314d-4e4a-a9dc-08432d7845c6">

**Comment by FedeGueli** [comment]
Two new samples of this one came today from American airport surveillance: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ca94_af3840.json?c=userOrOld&label=id:node_10393485
![Schermata 2023-06-27 alle 16 38 43](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e8e8b4c0-ca54-49e6-b16d-6d20b9ac5b86)

Both had S:G72E and S:A1078T

one of them is flagged for traveller coming from Brazil.

**Comment by FedeGueli** [comment]
@oobb45729 since 4 samples came from very recent airport surveillance and they are linked to Brazil, this suggests the prevalence there went up  somewhere. Please propose it in the main page.

**Comment by FedeGueli** [comment]
New Query:  A14634G, G22927T ,T22928C, T28282C fins 13

**Comment by FedeGueli** [comment]
Designated JD.1

**Comment by FedeGueli** [comment]
The very very original proposal with S:P1162S got designated JD.1.2.

Super well done work @oobb45729 !! from just three sequences now we have already 3 lineages designated!

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/93d23131a6c8f65b0bfc785e4f25a21b274c88e1

**Comment by AngieHinrichs** [comment]
@FedeGueli the milestone on this is JD.2 but it looks like the designated lineage was JD.1.2.  Noticed by @Over-There-Is in PR #2246.  (I would fix it but I don't have permissions to change milestones in this repo.)

**Comment by FedeGueli** [comment]
> @FedeGueli the milestone on this is JD.2 but it looks like the designated lineage was JD.1.2. Noticed by @Over-There-Is in PR #2246. (I would fix it but I don't have permissions to change milestones in this repo.)

Thank you @AngieHinrichs sorry my bad!
