### ISSUE TITLE
JN.1 + S:S680Y  in Oceania and Asia (41) with a NZL sublineage with further  S:T678I (3)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1362]
Another mutation right flanking the FCS worth keeping an eye on it as it seems highly homoplasic in JN.1 (11 trees)
Query: C23601A,T18471C
Defining mutations: 
JN.1 >> T18471C > S:S680Y (C23601A)

[USher Tree](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_641eb_ca55f0.json?c=gt-S_680&label=id:node_6893504):
<img width="1158" alt="Screenshot 2024-02-02 alle 09 29 29" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e55cdc5d-979d-4654-9725-f748f09c8267">

Countries: 
<img width="311" alt="Screenshot 2024-02-02 alle 09 30 17" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/eebd9bf0-9ca7-4271-a3a2-c1fa76381e8d">

Samples: 17
EPI_ISL_18670743, EPI_ISL_18670748, EPI_ISL_18679104,
EPI_ISL_18693763, EPI_ISL_18705838, EPI_ISL_18775805,
EPI_ISL_18787226, EPI_ISL_18792490, EPI_ISL_18792534,
EPI_ISL_18850370, EPI_ISL_18850405, EPI_ISL_18850500,
EPI_ISL_18850518, EPI_ISL_18850549, EPI_ISL_18850732,
EPI_ISL_18850828, EPI_ISL_18851125

*****************************

Edited: @HynnSpylor found a small branch of 3 sequences in NZL ( See below comments) with further FCS mutation S:T678I belonging to the proposed lineage
To track it we could use this query: C26421T,C23114T,C23595T

**Comment by Memorablea** [comment]
Good! https://github.com/cov-lineages/pango-designation/issues/2424 also is S:S680X

**Comment by FedeGueli** [comment]
+1 Shanghai ( from Thailand)

**Comment by HynnSpylor** [comment]
+3 from NZ
The NZ seqs are on N:P383S branch with small saltation- 3 nuc muatations and S:T678I, which shows T678I-N679K-S680Y-P681R combo near FCS
![联想截图_20240226141820](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/e3d6f0d0-49a9-4d55-bd0f-2c1211b60abd)

**Comment by FedeGueli** [comment]
Query for that sublineage : C26421T,C23114T,C23595T cc @HynnSpylor

**Comment by FedeGueli** [comment]
41 now

**Comment by aviczhl2** [comment]
Designated JN.1.35
