### ISSUE TITLE
JN.1 + ORF1a:S1534C (A4864G, A4865T) [11 seq, 5 countries, 2 continents]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1363]
### **Description**
**Sub-lineage of:** JN.1.1 (BA.2.86.1.1.1)
**Earliest sequence:** 2023-12-23, India, Maharashtra — EPI_ISL_18718954
**Most recent sequence:** 2024-1-12, USA, New York — EPI_ISL_18847618
**Continents circulating:** Asia (8), North America (3)
**Countries circulating:** India (5), USA (3), Malaysia (1—traveler to Singapore), Nepal (1), Singapore (1)
**Number of Sequences:** 11
**GISAID Nucleotide Query:** A4864G, A4865T, C897A
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [2-of: A4864G, A4865T]
**Substitutions on top of JN.1.1:**
**ORF1a:** S1534C (NSP3_S716C)
**Nucleotide:** A4864G, A4865T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.1__A4864G_A4865T.json?c=gt-ORF1ab_1534&gmax=21555&gmin=266&label=id:node_6876893

Most of the branches here are just artifactual reversions, so there's in reality very little diversity here.
<img width="1434" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e480e814-1f61-4195-9dbe-81c843519f8b">

**Evidence**
I don't expect this to be a significant lineage, but I want to at least register it here because there's something strange about these two nucleotide mutations. Both are rare: The synonymous A4864G has been in just 666 sequences while A4865T has been in just 88 sequences, yet 35 sequences have had both A4864G and A4865T. 

<img width="1472" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/98c2568c-4d8b-4e79-a31c-429eafd8bffc">

Furthermore, 17 of those 35 sequences also have G4868A, and these represent at least 7 independent lineages with these three mutations. G4868A is also rare, appearing in only 1169 sequences. 

<img width="1486" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f051b6bd-9ced-4da5-8d11-898b8850a0e3">

It's hard to make sense of. Is it possible that the repeat GTGT causes an RdRp stutter and makes it lay down a third GT? And could the same be happening with G4868A, only with two repeat TATA motifs causing the change? It seems very unlikely, but I can't think of any other explanation. 

Perhaps there is a strong secondary RNA structure here that any one of these mutations greatly disturbs but which the two (or three) mutations together do not alter? Or else they replace the old secondary structure with a new one that also serves the same purpose? I really don't know. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18605120, EPI_ISL_18718954, EPI_ISL_18725649-18725651, EPI_ISL_18726196, EPI_ISL_18819819, EPI_ISL_18847333, EPI_ISL_18847618, EPI_ISL_18848542, EPI_ISL_18856232
</details>

**Comment by aviczhl2** [comment]
Likely dead. However two Chinese seq under JN.1.1 also have this mutation too, seems a bit convergent.
