### ISSUE TITLE
JG.3 plus S:V1264L and  S:A352N (Triple nuc mutation previously described by Ryan Hisner) 5 seqs Poland, Ireland

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1365]
Just spotted a recent sub lineage of JG.3 still circulating in january with a 3 nuc mutation in the RBD, A352N.
This mutation could potentially result in a new Glycan if S:N354 would mutate to S or T.

Defining mutations:
JG.3 > > Orf1a:D2136N (G6671A) > C29686T > Orf3a:G18V ( G25445T) > S:V1264L (G25352T) > C2881A, T14313C, S:A352N ( T22615C, G22616A, C22617A),  N:P>L13F (C28310T)

Query : C2881A, T14313C,G25445T

Samples: 5 (Poland 4, Ireland 1)
First: 2023-12-08 Poland
Last: 2024-01-26 Poland
EPI_ISL_18663422, EPI_ISL_18705510, EPI_ISL_18755960,
EPI_ISL_18853988, EPI_ISL_18854004

Tree:
<img width="1164" alt="Screenshot 2024-02-04 alle 23 50 07" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9da08814-4af7-4d7a-8ce0-87b2d70c767f">
<img width="1168" alt="Screenshot 2024-02-04 alle 23 50 22" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/cec79b9c-ac23-4209-b3ed-266847339715">
<img width="1177" alt="Screenshot 2024-02-04 alle 23 50 44" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8dc8dd31-2935-423f-85ed-e1aab3697aa7">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5e912_11020.json?c=gt-S_352&gmax=25384&gmin=21563&label=id:node_3568668

Triple nuc mutation at S:352:
<img width="483" alt="Screenshot 2024-02-04 alle 23 51 23" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2b0c59cc-4049-411a-956f-efa628acdb47">

**Comment by ryhisner** [comment]
One of my favorite enigmatic mutations making a comeback! This one appeared several times in East Asia in 2022 then mostly vanished. At first it was a total mystery to me. 

Given that the first mutation here, T22615C, is synonymous, yet seems only ever to appear with the other two, this 3-nuc mutation must be about nucleotide sequence and not amino acid content. The two main things I look for in these cases are TRS patterns and anything that might have something to do with secondary RNA structure. This mutation seems to be a strange mix of both, but the case for secondary structure implications is strongest.  

Looking at the surrounding nucleotides, I noticed that this triple-mutation creates a near-perfect complementary palindrome. 

<img width="1489" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5a577c2d-424f-4df3-8086-2718b8753c30">

According to one of the only available full-genome secondary RNA structure predictions available, this region is single-stranded, so if that is correct, this region would be newly structured. But given that the first 6 nucleotides and the last 3 nucleotides here are already paired with other distant regions, this would perhaps cause a major rearrangement of the secondary RNA structure. This is all supposing the prediction pictured is correct, which it may well not be. And RNA structure isn't static in any case, so the whole situation is more complex. 
<img width="1507" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/302bf770-bba8-40bd-9d30-ac93ad3642f8">


There's one other notable pattern here as well. With this 3-nuc mutation, the region from 22606-22631 has 17/26 nucleotides that perfectly match the TRS-L. Half of the core TRS is off, so it seems unlikely to cause much in the way of template switches, but it's remarkable nonetheless. 

<img width="1506" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/67da20b7-4985-43fe-abf7-254a62713682">

**Comment by FedeGueli** [comment]
Thank you @ryhisner !

**Comment by FedeGueli** [comment]
dead
