### ISSUE TITLE
KD.1/KC.1 recombinant (3 seqs, Australia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1366]
There seems to be a new KD.1/KC.1 recombinant.

KC.1--KD.1--KC.1

Breakpoint 1 between 9867 and 11417
 Breakpoint 2 between 22601 and 22663

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0a129178-2278-46c7-9c15-44a7f199de30)

Additional mutations: C106T,C601T,T967C, G4280A,T4519C,G7058A, T8220C,  C22664A

C601T,G4280A,T8220C,C22664A from a KC.1 branch

C106T,T967C,T4519C,G7058A are private

GISAID query: C22664A, T8220C, C12786T

No. of seqs: 3(Australia)

EPI_ISL_18858457,18858477,18858496, 2024-1-25/26

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice105_genome_test_56686_4a720.json)

**Comment by FedeGueli** [comment]
Orf1b:Ins814D is defining of XBC

**Comment by FedeGueli** [comment]
very interesting one. thx for spotting

**Comment by Outpfmance** [comment]
This recombination is very successful, this has 490P+456L, increasing the RBD strength, while inheriting the RBD characteristics of the R346S, retaining the RBD characteristics of the XBC*, inheriting the Delta NTD+FL.1.5.2* FCS (P681R) of the XBC*, the two major killers of the Delta are reintroduced. In short, this may be the best way for DeltaCron to continue in this era.

**Comment by aviczhl2** [comment]
No new seqs
