### ISSUE TITLE
JN.1.4/EG.5 recombinant(2 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1367]
A recombinant in #991 gets company of another county in New York.

JN.1.4--EG.5

Breakpoint between 24379 and 24989

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/cf65255c-5511-419c-91a4-ece45936d0d0)

Additional mutations: C5654T, C19170T, C26885T

 C5654T, C19170T from a JN.1.4 branch
C26885T from one EG.5 branch, 

GISAID query: C26885T,C24378T,C29625T,T18453C
No. of seqs: 2(USA-NY)

EPI_ISL_18826069,2024-1-8
EPI_ISL_18858403, 2024-1-17

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice85_genome_test_56686_4a700.json?label=id:node_11254542)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/7ed5b78b-7812-43a3-bdf1-3e4765510036)

**Comment by FedeGueli** [comment]
another one with S:1143 removed and Orf3a-10 from XBB.1.9.2

**Comment by aviczhl2** [comment]
no new seqs

**Comment by FedeGueli** [comment]
Thank you
