### ISSUE TITLE
EG.5.1.1+Orf8:I9T+S:L455F(75 seqs, 7 countries, 14% Argentina )

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1369]
EG.5.1.1+T25827C+T27919C(Orf8:I9T)+G22927T(S:L455F)

GISAID query 1: T25827C,T27919C,G22927T,C2334T
GISAID query 2: T25827C, G13627A, G22927T, C2334T, -27915,-27919 (In case for missing coverage on Orf8)
No. of seqs: 61 (Argentina 44 Chile 3 Netherlands 4 Peru 2 USA 8)
44 are found by query 1 , 17 are by query 2. 

First: EPI_ISL_18422433, Argentina, 2023-8-7
Latest: EPI_ISL_18864599, Argentina, 2024-1-6

Unsure why this one grows, but it is 7/49=14% in Argentina seqs after 2024-1-1. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice46_genome_test_5c25a_194710.json?label=id:node_3465530)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3e1dde00-4fc2-4b6f-9515-e6d42140c6a2)

**Comment by FedeGueli** [comment]
+ 3 Paraguay ( i dont get well how you got the final count from the two queries)

**Comment by FedeGueli** [comment]
> > today +3 Paraguay ( i dont get well how you got the final count from the two queries)
> 
> Sum up the two queries.

ahah really?? sorry i was thinking it was more complicated ;)) (maybe i checked when they were already moved and didnt match the sum ;) )

**Comment by aviczhl2** [comment]
68, Paraguay and Uraguay

**Comment by aviczhl2** [comment]
No new seqs
