### ISSUE TITLE
XDQ+S:A475V(37 seqs, 4 countries, 17% South Korea)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1370]
It seems that the S:A475V branch of XDQ is exploding.

XDQ+C22986T(S:A475V)

GISAID query: C28846T,C7420T,C22986T
No. of seqs: 11(Sweden 1 South Korea 2 Japan 8)

First: EPI_ISL_18795907, Sweden, 2023-12-16
Latest: EPI_ISL_18860130, Japan, 2024-1-19

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_2edde_1c6cd0.json?label=id:node_6865408)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/454293f6-4422-49ce-a252-0e60065181bc)

**Comment by FedeGueli** [comment]
16 last samples from Japan

**Comment by FedeGueli** [comment]
@aviczhl2 please propose when it reaches 25

**Comment by aviczhl2** [comment]
21, Australia

**Comment by FedeGueli** [comment]
It seems fast pleas go with a proposal

**Comment by aviczhl2** [comment]
+16 South Korea today

**Comment by aviczhl2** [comment]
15/90=17% in South Korean seqs after 2024-2-1.

**Comment by FedeGueli** [comment]
Designated XDQ.1 via https://github.com/cov-lineages/pango-designation/commit/ab76d4aec4477f59eb2a4c8f4089a533226efeab
