### ISSUE TITLE
JN.1.7 plus S:R346K ( 20 seqs England)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1371]
JN.1.7 is the fastest designated lineage circulating with more than 100seqs.
hence i think useful proposing directly this cluster of JN.1.7 plus S:R364K  that emerged in England

Defining mutations:
JN.1.7 > S:R346K ( G22599A) 
Query:G22599A, G25012T, C25566T,C23277T
Samples : 7
IDs: EPI_ISL_18764191, EPI_ISL_18800746, EPI_ISL_18831935,
EPI_ISL_18842857, EPI_ISL_18860656, EPI_ISL_18860819,
EPI_ISL_18867225
Tree:
<img width="1161" alt="Screenshot 2024-02-06 alle 14 32 34" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b902774c-d16c-473c-819d-af5976607544">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4fb38_233310.json?label=id:node_6893318

Note that the top branch with the mutation K346T has been proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1343 and i think it is misplaced here: @angiehinrichs

**Comment by AngieHinrichs** [comment]
> Note that the top branch with the mutation K356T has been proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1343 and i think it is misplaced here: @AngieHinrichs

Yes, it should be separate.  I'll try to fix it, thanks @FedeGueli.

**Comment by FedeGueli** [comment]
> > Note that the top branch with the mutation K356T has been proposed in #1343 and i think it is misplaced here: @AngieHinrichs
> 
> Yes, it should be separate. I'll try to fix it, thanks @FedeGueli.

Thank you

**Comment by aviczhl2** [comment]
Designated JN.1.7.1
