### ISSUE TITLE
JN.1 x XBB.1.16.11 recombinant, 17 seqs, England

### ISSUE THREAD

**Issue by DeepakPhuyal** [sars-cov-2-variants/lineage-proposals#1375]
6 sequences as of today: EPI_ISL_18707847, EPI_ISL_18771720, EPI_ISL_18854569, EPI_ISL_18861013, EPI_ISL_18867148, EPI_ISL_18877673

First collected on Dec 21st 2023, and latest collection was on Jan 23rd 2024, all from England.

Breakpoint is somewhere between 26833 and 27810.

Basically it's an JN.1 with ORF7b and downstream donated from XBB.1.16.11, featuring ORF8:G8stop, ORF9b:I5T and ORF9b:N55S.

USHER branch is misplaced next to XDP:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/154001647/1a5aac87-4cda-46fd-b81e-f3997715bc2b)

Query: C29386T, G28085T, G26529C

**Comment by FedeGueli** [comment]
7 now

**Comment by FedeGueli** [comment]
17 but likely dead. ping me if some new samples will be uploaded
