### ISSUE TITLE
XDD+E:S68F(15 seqs, Spain, 1 with S:T572I)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1376]
XDD+T27336A+C8947T,C26447T(E:S68F)

Query: T27336A,C26447T,C6541T
No. of seqs: 14(Spain)

First: EPI_ISL_18830408,2023-12-25
Latest: EPI_ISL_18878657, 2024-1-20

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_d84c_82a8c0.json?label=id:node_6937300)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/25c502ab-36b9-4d66-8416-38739a3eca2d)

**Comment by FedeGueli** [comment]
Lets see if it is a cluster or something different

**Comment by aviczhl2** [comment]
No new seqs

**Comment by aviczhl2** [comment]
+1 with S:T572I

**Comment by aviczhl2** [comment]
It doesn't manage to grow.
