### ISSUE TITLE
JN.1.4 with ORF1ab mutations and E:P71S (3 sequences,USA)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#1377]
This branch belongs to JN.1.4, is prevalent in the United States, with E: P71S, according to studies can cause more serious disease mutations, E: P71L/S in the late evolution of HV.1 and XBB.1.16.6, the frequency of occurrence in JN.1* is not much, this occurrence should be monitored.

ORF1ab:A117T,S212L,W646L,Q1582R,K4348R
E:P71S

GISAID query(AA):NSP1_A117T,NSP1_T170I,Spike_L455S,E_P71S nuc : G614A, A5010G, C14481T
UShER tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_1b50c_b28550.json?label=id:node_6948371

Sequences:
EPI_ISL_18871976
EPI_ISL_18866003
EPI_ISL_18865997

**Comment by Outpfmance** [comment]
![IMG_2500](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/e02dfa3d-fffb-4363-abf3-f23ae0b989d1)

**Comment by FedeGueli** [comment]
@Outpfmance nuc query added : G614A, A5010G, C14481T

**Comment by Outpfmance** [comment]
It seems no new sequences.
