### ISSUE TITLE
JN.1 with S:D936N(21 sequences,Australia,New Zealand and Japan)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#1378]
Description
Sub-lineage of:JN.1
Earliest sequence:2023-12-8
Latest sequences:2024-1-22
Countries:Australia(9),Japan(3)
GISAID query: A29086T,G24368A,T22926C
Cov-spectrum: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-08-07%26to%3D2024-02-06/variants?aaMutations=S%3AD936N%2CS%3AL455S&nucMutations=A29086T&
UShER TREE: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_4a059_b6fc90.json?label=id:node_6876342
![IMG_2509](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/209f4c3d-2ebd-4d60-8c21-e5445e93aa8a)

Evidence
S: D936 is one of the important points on S2, and the mutation has H, Y, N, etc., which is considered to be a mutation caused by long-term infection. In history, B.1.619* and B.1.1.486 both had this mutation, and the situation on B.1.619 is very similar to that of the current BA.2.86*, both with (S: D936N+S: S939F) double mutation, maybe these two are related? Or is it an interaction? I think this phenomenon needs to be observed and monitored, and I am curious about the influence of D936N on the S2 control chain of BA.2* (H655Y+N764K+Q954H+N969K), especially on N969K. Will it re-change the conformation of S2?
![52c33f49ff1065b211522bffb72db7a8](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/fe508477-e178-4fa0-8d5b-80fc4370da11)

Sequences:
EPI_ISL_18814946
EPI_ISL_18858417
EPI_ISL_18705780
EPI_ISL_18841454
EPI_ISL_18657182
EPI_ISL_18667536
EPI_ISL_18711397
EPI_ISL_18711404
EPI_ISL_18841447
EPI_ISL_18872822
EPI_ISL_18872833
EPI_ISL_18884450

**Comment by Outpfmance** [comment]
EPI_ISL_18915588
A new sequence from SA

**Comment by Outpfmance** [comment]
EPI_ISL_18923562 New Zealand
A new sequence in a new country.

**Comment by Outpfmance** [comment]
EPI_ISL_18944203
A new sequence from Australia QL

**Comment by Outpfmance** [comment]
18 sequences now.

**Comment by FedeGueli** [comment]
closing this one
