### ISSUE TITLE
Large artefactual branch of S:N211I,L212V under JN.1 (2700+ seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1380]
JN.1 shall have S:211del, and now there is a very large S:N211I,L212V artefactual branch with 2700+ seqs 
@AngieHinrichs.  suggest to mask. 

Most seqs under this branch belong to JN.1.4. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_14bd6_cb8df0.json?label=id:node_6915693)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/33aff53c-e343-4d52-8317-bcfd15a00654)

**Comment by FedeGueli** [comment]
Thanks for highlighting there is this one and also a smaller one with S:T22V S:Q23*

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2 and @FedeGueli, I will mask both regions.  Should take effect in tomorrow's build (2024-02-20).
