### ISSUE TITLE
A subbranch of XDP with additional ORF1b:2163S, 88 seqs, mainly US-CA

### ISSUE THREAD

**Issue by DeepakPhuyal** [sars-cov-2-variants/lineage-proposals#1382]
Earliest collection on December 8th 2023, and most recently collected on January 29th 2024.
22 seqs from US-CA, and 1 each from US-MN and England.

Previously I thought it's an independent recombinant, but turns out it should be a sub-branch of XDP with some private mutations (and thus misplaced by USHER).

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/154001647/5ec0ca12-e36f-4f42-b2a6-22aa5ebc0f0c)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38184_dab050.json?c=gt-nuc_25928&gmax=26298&gmin=24298&label=id:node_5513887

ORF1b:I2163S (T19955G), which is a further step from one of Omicron's signature mutation, ORF1b:T2163I (C19955T).

Query: C19955G, C28846T, G27915T(edited)

Sequences: EPI_ISL_18756372, EPI_ISL_18774604, EPI_ISL_18774812, EPI_ISL_18774900, EPI_ISL_18775053, EPI_ISL_18784805, EPI_ISL_18785581, EPI_ISL_18818036, EPI_ISL_18818478, EPI_ISL_18834589, EPI_ISL_18834989, EPI_ISL_18835137, EPI_ISL_18835533, EPI_ISL_18842859, EPI_ISL_18846741, EPI_ISL_18846752, EPI_ISL_18857086-18857087, EPI_ISL_18857100, EPI_ISL_18865978, EPI_ISL_18871926, EPI_ISL_18887682, EPI_ISL_18894740, EPI_ISL_18894937

**Comment by aviczhl2** [comment]
Isn't it usher misplacement of XDP? @AngieHinrichs @FedeGueli @corneliusroemer

**Comment by DeepakPhuyal** [comment]
Yes it seems it should be a sub-branch of XDP. Sorry for the mess. I actually double checked #1177 before posting, but your USHER tree there is a bit too old.

**Comment by FedeGueli** [comment]
I think the difference is that this one has   C19955G while XDPP has C19955T

**Comment by FedeGueli** [comment]
@DeepakPhuyal due to the relevance of a achange in BA.2 defining mutation you could change this issue in a proposal of the subbranch of XDP with Orf1b:T2163S instead of I as all BA.2/BA.5

**Comment by DeepakPhuyal** [comment]
> @DeepakPhuyal due to the relevance of a achange in BA.2 defining mutation you could change this issue in a proposal of the subbranch of XDP with Orf1b:T2163S instead of I as all BA.2/BA.5

Okay I'll edite the proposal.

**Comment by DeepakPhuyal** [comment]
> @DeepakPhuyal due to the relevance of a achange in BA.2 defining mutation you could change this issue in a proposal of the subbranch of XDP with Orf1b:T2163S instead of I as all BA.2/BA.5

Okay I'll edit the proposal. Thanks!

**Comment by aviczhl2** [comment]
Still call @AngieHinrichs to fix this. This branch is placed under a different place of main XDP.

**Comment by FedeGueli** [comment]
> Still call @AngieHinrichs to fix this. This branch is placed under a different place of main XDP.

Already mailed her about it!

**Comment by AngieHinrichs** [comment]
I think this was fixed as of the 2024-02-16 tree.  This branch is now placed as XDP > C774T (ORF1ab:T170I) > T19955G (ORF1b:I2163S) > T25928C (ORF3a:I179T).

**Comment by aviczhl2** [comment]
54 seqs now.

**Comment by aviczhl2** [comment]
It seems that the tree changes and Orf3a:179T is placed after Orf1b:2163S now. 

Suggested query: C19955G, C28846T, G27915T  (70 seqs)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e00f38ed-1dcf-4a8f-8a40-d4e38b1e13b6)

**Comment by FedeGueli** [comment]
It reappeared in May, let this open for a while more

**Comment by FedeGueli** [comment]
2 only from May closing it
