### ISSUE TITLE
JN.1.4 + ORF8:S103L & ORF1a:P971L & S:T572I (107)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1384]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/fe81aefc-1eb2-4531-b35d-18d34d28e938)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ae52_f96210.json?c=gt-ORF1ab_971&gmax=21555&gmin=266&label=id:node_6944665

First Seq: 2023-12-13
Most Recent: 2024-02-02

Gisaid Query: C3177T, C11956T, C23277T, C28201T

EPI_ISL_18869524 PP204564.1 EPI_ISL_18816910 EPI_ISL_18816583 EPI_ISL_18869532 PP106760.1 PP188929.1 EPI_ISL_18817092 EPI_ISL_18874966 EPI_ISL_18874407 PP315513.1 EPI_ISL_18816361 EPI_ISL_18743391 EPI_ISL_18874339 EPI_ISL_18874728 EPI_ISL_18874456 EPI_ISL_18743529 PP318604.1 EPI_ISL_18817090 EPI_ISL_18874271 EPI_ISL_18817065 PP204683.1 EPI_ISL_18816771 PP065113.1 PP231525.1 PP231066.1 EPI_ISL_18816582 EPI_ISL_18813545 EPI_ISL_18874515 EPI_ISL_18816539 PP153260.1 EPI_ISL_18743508 PP141250.1 EPI_ISL_18743056

**Comment by FedeGueli** [comment]
Already tracked in the multiple lineage issue, please propose in the main page mentioning the correct branch and related issue.

**Comment by FedeGueli** [comment]
it is branch 18 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097 please propose it.

**Comment by FedeGueli** [comment]
20 now +5 Georgia California Texas. ping @corneliusroemer it seems expanding both for smpela and states counts. maybe worth designating it.
