### ISSUE TITLE
FL.1 with ORF1b:K2557R, S:F456L, S:K478R (6 seq.) 3 countries

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#139]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a26142ad-fc74-44ae-b67c-1a88933f4cd0)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b2770dce-8e25-4080-9ba6-ca1768e39686)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_57b4_be4dd0.json?c=gt-nuc_2128&label=id:node_6715194
first sequenced: 2023-04-22
Most recent: 2023-05-23
EPI_ISL_17727597 EPI_ISL_17736495 EPI_ISL_17737458 EPI_ISL_17716754 EPI_ISL_17595460

Gisaid Query: T22928C,T2128C, A21137G,C22995G (Edited)

**Comment by FedeGueli** [comment]
Please make a proposal with three steps: Orf1b:K2557R deserves to be a branch of FL.1 by itself  then S:F456L and then S:T478R. Here we could have 3 steps= .1.1.1.

@corneliusroemer maybe you can take a look and designate this highly cause it is high convergently evolving?

My reasoning on the Orf1b:K2557R is the branch with the NSP6 mutation: NSP6_I189V (Orf1a:I3758V) 
![Schermata 2023-06-04 alle 09 51 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1d078d4a-d0f1-4c7e-b8b0-e3a6c47fa707)
