### ISSUE TITLE
XDN seqs still not included in usher while XDR and XDQ already included

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1390]
It seems that the previously-removed XDR and XDQ seqs are back due to updated designation. 

However, XDN seqs are still not back, despite designated before XDR and XDQ. The only XDN seqs are still those previously added in recombinant.tsv before designation. 

@AngieHinrichs, is there something wrong here?  

Usher branch containing full XDQ and XDT but only a small part of XDN. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice107_genome_test_2958e_460da0.json?label=id:node_6877394

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/80af5ced-a414-49d5-933d-2f8eaf6c57bf)

**Comment by AngieHinrichs** [comment]
I need to re-run the latest nextclade data release on older sequences. I will do that today and then hopefully these will be added in tomorrow's build (2024-02-21).
