### ISSUE TITLE
Maybe A New Spot Within JN.1*? S:T385I polytomy+JN.1* (also XDD* and JN.2.5* as they get essentially the same Spike as JN.1*)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1392]
I was roaming the jbloom lab calculator to look for mutations. As JN.1* most certainly lacks some ACE2 binding I am looking for those, and one mutation caught my attention- S:T385 position. I did the gisaid search and find that most of them are S:T385I, itself maybe not very interesting on the calculator but still demonstrating possible growth among JN.1* population.

<img width="985" alt="Screenshot 2024-02-22 at 2 16 33 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/c8b368e6-7eba-4141-b9a9-facea5b923a5">
Note: Look at how blue the column is, T385I is not the bluest yet it is very readily available 

<img width="985" alt="Screenshot 2024-02-22 at 2 16 41 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/bd27abd5-76bf-463d-8eab-d12fbc7ef843">
Growth of S:T385I, comparable to me with S:T572I, which we can be sure gives a boast to JN.1* sublineages carrying it.

A Gisaid Inquiry I performed:T22926C,C22716T (it is very rare that just some search like that limits to JN.1* spikes, not some random ancient bat sequences) This gives in total 119 seqs
No too interesting geographic distributions. Ukraine and Bostwana would be relatively interesting, while the larger countries in terms of sequencing looks proportional here.
Earliest Sequence: EPI_ISL_18544272 Spain 2023-11-15
Latest Sequence: EPI_ISL_18913290 England 2024-02-09
If we are counting monthly values, then there is  2 in Nov (15th-30th), 39 in Dec, 67 in Jan, 11 (13?) in Feb, 2 unspecified comparing with 7262 in Nov, 38163 in Dec, 37072 in Jan, 3014 in Feb. We can also see here it is growing.

usher：https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2a0e1_63f7d0.json?f_userOrOld=uploaded%20sample&label=id:node_2326799
<img width="985" alt="Screenshot 2024-02-22 at 2 23 36 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/5d217677-3480-4b97-b1e7-823847128b00">

**Comment by FedeGueli** [comment]
Hi @krosa1910 i've checked quite early S:T385I in JN.1 and it was not monophyletic, it seems one of that mutations that goes on popping up in Jn.1 without great results ( 95X, 221L, 307I, 408X, 445X, 554X) but appearing in multiple lineages they still increase their prevalence.

**Comment by FedeGueli** [comment]
145 total now with T22926C,C22716T

**Comment by krosa1910** [comment]
T22926C,C22716T now gives 158. 
I guess it can keep up with JN.1* population in general but possibly not a game changes like the big three, I will still watch it.

**Comment by FedeGueli** [comment]
> T22926C,C22716T now gives 158. I guess it can keep up with JN.1* population in general but possibly not a game changes like the big three, I will still watch it.

maybe it will occur in a fast combo lineage in the next weeks

**Comment by FedeGueli** [comment]
276 total samples with 385I but its frequence is clearly decreasing , closing it for now
