### ISSUE TITLE
XBB.1.5.110 saltation in 2 patients, 2 forms. Finland. 

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#1394]
**Description**
**Collection Date:** Both are Feb 6
**Location:** Both are the same region in Finland. 
**Mutations:**
The following are shared. 
**Nucleotides**: A299G, C512T, G670T (rev), C1121A, T5507G, A5648C, T6667C, A11600G, A11943G, G12566A, C13517T, T13704C, C14220T, C21789T, A22578G (rev), C22716A, A22881G, [C23277T, C23423T, C26833T **These are in JN.1.1.1 and JN.1.8.1**], G27676C, T27682C, C28057T, C28310T
**ORF1ab**: T12A, H83Y,  R135S (rev), P286T, L1748V, K1795Q, I3779V, Q3893R, V4101I, T4418I
**Spike**: T76I, H339R, T385N, K440R, T572I, P621S
**M**: A104V
**ORF7a**: E95Q, Y97H
**ORF8**: A55V
**N**:L13F

Query: A299G, C512T, C1121A (Edited)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/b7e3177d-c58b-4a0e-a511-fed8c80e8eb1)

**Unique to EPI_ISL_18918931**: 
Nucleotides: G5513A, C12624T, C23393T, C23897G, G25091T, C26681T, C26985A, G27084T, C27247T, C28289T, A28319T
ORF1ab: V1750M, P4120L
Spike: L611F, Q779E, V1177L
M: H155N, A188S
N: P6S, T16S
ORF9b: P3L, L12F

**Unique to EPI_ISL_18918932**:
Nucleotides: G393A, C15240T, C19763T, A22000T, C23430T,  G25106C, T25502C, G27112C, C27128T, T27568G, A28268G, T28311G, 
ORF1ab: R43H, T6500I
Spike: Q146H (rev), A623V, E1182Q
ORF3a: I37T
M: S197T
ORF7a: F59V
N: F13C, N29Y, K100R
ORF9b: S10A, R25S, K97E

**Discussion:**
Since the IDs are 1 integer apart, I think the lab already is aware of these two sequences being connected in some fashion. 
The patient metadata indicates they are different patients. 
If we compare the first 2/3rds of the genome vs the last 3rd, then they have... 

Shared mutations in first 2/3rd: 13 
Shared mutations in last 3rd: 11 
Differences (combined) in first 2/3rd: 5
Differences (combined) in last 3rd: 18 

The concentration of differences in the last third makes me think that there could have been some recombination event? It looks like there isn't a recombination with the JN.1 sequences even though having 3 shared mutations -- it would have inherited more JN.1 mutations in that region if that was the case. 

I'm thinking that if this is a recombinant it's something like... 
Let's treat EPI_ISL_18918931 as the direct uncomplicated result of the chronic infection. Some time ago after it has 11 mutations in the last third of its genome, a different form of it also becomes successful and keeps having successful descendants inside the host, and so there are now two divergent forms of the variant inside the host. The second form recombines with the EPI_ISL_18918931-ish one, with a breakpoint around 2/3rds of the way through the genome. At this point they are identical before the 2/3rd mark but fairly different after that. 

Some time passes - enough to accumulate 5 differences in the first 2/3rd of the genome, and then these two forms both get sequenced.

**Comment by FedeGueli** [comment]
Thx @Sinickle great spot! Agree with your recombinant hypothesis likely intrahost?
I would like to add a couple of points:
Orf7b stop codon appears to be removed and the first 7 AA of Orf8 appear to be deleted suggesting  some deletion happening maybe an out of frame one? 
Second the very complex pattern of mutations in orf9b/N each different for each sample, but both showing at least one AA mutation linked to a silent one.
I am sure @ryhisner will do an analysis of them ! 
Notably one of them in one sample only occurred in N:P13L defining of Omicron shifting it to N:P13L>C bringing with it an unprecedented Orf9b:S10A . Another one is N:P6S N:6 mutations has been associated with fast lineages in the past as AY.36.1 but i dont recall any before with S there.

**Comment by FedeGueli** [comment]
I am taking a second look to the Orf7b/orf8 deletion , i am giving a try so it could be completely wrong hope maybe @corneliusroemer @thomasppeacock @ryhisner  could verify what i will say now:
It appears that both orf7b:*44Y and the Orf8:1-7del in reality come from an out of frame deletion of del27888_27914 
Considering that XBB.1.5 has Orf8:8* from G27915T :
these sequences:
<img width="499" alt="Screenshot 2024-02-22 alle 18 06 05" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b56c52b9-453a-46ab-918a-67fa9c7f37fe">
<img width="718" alt="Screenshot 2024-02-22 alle 18 06 21" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/10787fea-74d6-45cb-96e4-8b2e7edc2be9">
WT:
<img width="569" alt="Screenshot 2024-02-22 alle 18 07 23" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c850cc62-115c-4c30-85a6-c1283f8a974d">
 to me the deletion really starts with A27887del and takes the T from 27915T ( = Orf8:8*) ,
in fact then Nextclade misreads the 27915 as N 
<img width="74" alt="Screenshot 2024-02-22 alle 18 10 20" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/cfed49c8-181e-4975-adbf-a0f035578ff2">

If ,and a big IF here  , this is true it is likely that the Orf7b is fused with Orf8 in a brand new Orf7b8 protein with a different sequence. I am now checking which it would be and if and when it meets a stop codon.

**Comment by FedeGueli** [comment]
This would bring a new out of frame start codon for Orf8 at Orf8:H40M
<img width="146" alt="Screenshot 2024-02-22 alle 18 20 55" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3465a0bb-b7ab-4960-b160-1f2ff9df4867">

**Comment by FedeGueli** [comment]
Deleted there is a start codon at Orf8:31 but followed by a stop codon.

**Comment by FedeGueli** [comment]
> So this my attempt for the PUTATIVE new sequence: orf7b:44YESSQL* So the effect would be just of having a 6AA longer Orf7b that should end with Orf7b:51*
> 
> So this will also bring to a new start codon :
> 
> there is a start codon at Orf8:31 but followed by a stop codon. then it will form a short Orf8a protein, if any, spanning between Orf8:D34M to Orf8:G50* with new sequence being Orf8a:34MTRVLFTSILNGILE* <img alt="Screenshot 2024-02-22 alle 18 30 28" width="690" src="https://private-user-images.githubusercontent.com/87669813/307091498-7131e2ac-ddbe-4932-b166-092f05bdfd88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjU4MzgsIm5iZiI6MTcwODYyNTUzOCwicGF0aCI6Ii84NzY2OTgxMy8zMDcwOTE0OTgtNzEzMWUyYWMtZGRiZS00OTMyLWIxNjYtMDkyZjA1YmRmZDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE4MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZjA2YzRhMDFmZTYzZDc4MTcwMTIyN2M4NDk1ZDU5OTY0ZGI3ZjA1M2Y2ZDlhN2EwYmMyMzRjNGRkODMxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6-VC0SUkBV_-IMJ6TMt-filcCkF6mRsczznF4V-3QQ">
> 
> And then another longer one (potentially Orf8b) spanning between Orf8:D63M to Orf8:V99* with the new sequence looking like : Orf8b:63MRLVLNHPFSTSISVIIQFPVYLLQLIARNLNWVVL*
> 
> <img alt="Screenshot 2024-02-22 alle 18 37 14" width="1111" src="https://private-user-images.githubusercontent.com/87669813/307093345-d5450dba-300d-42a3-a40e-3b0b8598594f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjU4MzgsIm5iZiI6MTcwODYyNTUzOCwicGF0aCI6Ii84NzY2OTgxMy8zMDcwOTMzNDUtZDU0NTBkYmEtMzAwZC00MmEzLWE0MGUtM2IwYjg1OTg1OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE4MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTNkOGRiMDQxN2FjZjllMTBhYjdhODVkYjA4YWI4NmRkZmY0ZWQ1ODJmNjQ4YTAzOGQ0MWY4NTc4ZDYxZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVOcYZOFPZkeWwHv1Xltxio_xTmyoJSbL8q8jmfEPRY">
> And a third one very short unrelavant one Orf8c spanning from Orf8:Y105M to Orf8:L109*: Orf8c:105MKTF*
> 
> <img alt="Screenshot 2024-02-22 alle 18 41 24" width="1412" src="https://private-user-images.githubusercontent.com/87669813/307094549-593f56ac-65a9-4dca-8c8b-bffe59aa047f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjU4MzgsIm5iZiI6MTcwODYyNTUzOCwicGF0aCI6Ii84NzY2OTgxMy8zMDcwOTQ1NDktNTkzZjU2YWMtNjVhOS00ZGNhLThjOGItYmZmZTU5YWEwNDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE4MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDRiYTQzZDE2MTMxMmI4MTJiMDQ0NTJlNGVjZjM4NjQ5NzRhZDc2YzAxYjAwM2M4NmMwMDY5YTBiZTM0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b4bXqNJ-c9eE-mELgMRjWIlOzkGfb0mgUtQ2s2fsi9g">
> and another short one (Orf8d) spanning from Orf8:H112M to Orf8:L118* consisting in Orf8d:112MTFVLF*
> 
> IF all of above is true the frameshift will be in frame with orf9b and out of frame with N but here i will stop cause really in muddy waters for me. If anything i wrote is wrong i apologize in advance.

Completely edited sorry for the previous mistakes.  i ve checked with https://web.expasy.org/translate/ very useful tool

**Comment by ryhisner** [comment]
Fede, I think more likely what we're seeing here is both the deletion of the ORF8 TRS and no change in ORF7b. I think the deletion is actually ∆27887-27814, with the alleged A27887T being an artifact due to the G27915T mutation. I think the algorithm for Nextclade (and BLAST as well as other sequencing programs) tends to assume that substitutions happen at the first possible instance, and they generally don't take into account inherited mutations like G27915T. 

<img width="1480" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/8cd77264-683f-4063-8ab6-3c3d2418a6e6">


Here you can see that ORF7b still gets a stop codon in its usual location (purple-highlighted nucleotides) while virtually the entire ORF8 TRS is deleted (deletion highlighted in red). So ORF8 will cease to be translated altogether—not even the first 8 nucleotides like before. Should make transcription slightly more efficient without the wasted copies of the truncated ORF8 sgRNA being produced.

**Comment by ryhisner** [comment]
Fede, I think more likely what we're seeing here is both the deletion of the ORF8 TRS and just a few new AA (YFL) being added to the end of ORF7b. I believe the deletion is actually ∆27887-27814, with the alleged A27887T being an artifact due to the G27915T mutation. I think the algorithm for Nextclade (and BLAST as well as other sequencing programs) tends to assume that substitutions happen at the first possible instance, and they generally don't take into account inherited mutations like G27915T. 

<img width="1481" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a669e9bd-ce42-4245-b904-3a3d1d82b6d5">

Here you can see that ORF7b still gets a new stop just a few AA downstream of its old one (purple-highlighted nucleotides) while virtually the entire ORF8 TRS is deleted (deletion highlighted in red). So ORF8 will cease to be translated altogether—not even the first 8 nucleotides like before—and ORF7b adds YFL.  Should make transcription slightly more efficient without the wasted copies of the truncated ORF8 sgRNA being produced.

**Comment by FedeGueli** [comment]
> Fede, I think more likely what we're seeing here is both the deletion of the ORF8 TRS and just a few new AA (YFL) being added to the end of ORF7b. I believe the deletion is actually ∆27887-27814, with the alleged A27887T being an artifact due to the G27915T mutation. I think the algorithm for Nextclade (and BLAST as well as other sequencing programs) tends to assume that substitutions happen at the first possible instance, and they generally don't take into account inherited mutations like G27915T.
> 
> <img alt="image" width="1481" src="https://private-user-images.githubusercontent.com/33738461/307288903-a669e9bd-ce42-4245-b904-3a3d1d82b6d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODc0NDAsIm5iZiI6MTcwODY4NzE0MCwicGF0aCI6Ii8zMzczODQ2MS8zMDcyODg5MDMtYTY2OWU5YmQtY2U0Mi00MjQ1LWI5MDQtM2EzZDFkODJiNmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDExMTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMjQwMjcxNDJjNGZhZjA2ZTcyZDI1NDQyMGMwMjAyMTZlYjk3M2Q3MjZjMjIwMzg5ZjFmMTY2YzY5OWVjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0SSiTLx20wcp2hNO7Qn4URO-vOxN7l5djgsA92gozk">
> Here you can see that ORF7b still gets a new stop just a few AA downstream of its old one (purple-highlighted nucleotides) while virtually the entire ORF8 TRS is deleted (deletion highlighted in red). So ORF8 will cease to be translated altogether—not even the first 8 nucleotides like before—and ORF7b adds YFL. Should make transcription slightly more efficient without the wasted copies of the truncated ORF8 sgRNA being produced.

Agree on 28715T being added to orf7b stop codon and changing it in Y, and giving that additional few AA to Orf7b but if that is true the deletion is 28nucleotides and it should produce a frameshift indeed. Could you check this argument please?

**Comment by ryhisner** [comment]
> Agree on 28715T being added to orf7b stop codon and changing it in Y, and giving that additional few AA to Orf7b but if that is true the deletion is 28nucleotides and it should produce a frameshift indeed. Could you check this argument please?

I made a stupid mistake in my previous diagram, so it changes things slightly. There is a frameshift. It leads to six new AA being added to ORF7b. ORF8 TRS is demolished, so it is even more thoroughly obliterated than it was before.

**Comment by FedeGueli** [comment]
> > Agree on 28715T being added to orf7b stop codon and changing it in Y, and giving that additional few AA to Orf7b but if that is true the deletion is 28nucleotides and it should produce a frameshift indeed. Could you check this argument please?
> 
> I made a stupid mistake in my previous diagram, so it changes things slightly. There is a frameshift. It leads to six new AA being added to ORF7b. ORF8 TRS is demolished, so it is even more thoroughly obliterated than it was before.

@ryhisner i have a double Serine there instead of Leucine, being in my manual rendering TCATCA isnt it?

**Comment by ryhisner** [comment]
Yeah, that's right, Fede. I always do this stuff in my head and occasionally make mistakes. Should've double-checked.

**Comment by FedeGueli** [comment]
> Yeah, that's right, Fede. I always do this stuff in my head and occasionally make mistakes. Should've double-checked.

Thank you Ryan for your help don't worry it doesn't matter  thjis kind of re alignment are always messy. if you look above i put here a tool to make the translation of string of nucs nucs to aa , it may be useful to double check
