### ISSUE TITLE
JN.1+S:A67V(39 seqs, 11 countries ,60% Chongqing)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1395]
JN.1+C5512T,G2782T,C21762T(S:A67V)

GISAID query: C5512T,G2782T,C21762T,C18894T
No. of seqs: 19(China 6(Chongqing 5 Liaoning 1), UK 1 France 1 Oman 1 Japan 1 Poland 1 Singapore 2(1 from Saudi Arabia) USA 6(2 from  Italy, CO,CA,MD,NY 1 each)

First:EPI_ISL_18819543, 2023-11-28, Japan,
Latest: EPI_ISL_18926252, 2024-2-16, Chongqing

This lineage seems extremely widely distributed, suggesting circulating in undersampled regions. 
It also takes 5/5 of Chongqing seqs in 2024. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3ac72_8776e0.json?label=id:node_6906755)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/cdb934a0-06f3-4c9a-99c9-8ffbcce82a47)

**Comment by Memorablea** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/d58a805d-ac3b-49f0-91c1-49c7f23ea787)
Please refer to the testing number.So, it shouldn't be 100% Chongqing？

**Comment by aviczhl2** [comment]
> ![image](https://private-user-images.githubusercontent.com/125779492/307313598-d58a805d-ac3b-49f0-91c1-49c7f23ea787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTAxNDAsIm5iZiI6MTcwODY4OTg0MCwicGF0aCI6Ii8xMjU3Nzk0OTIvMzA3MzEzNTk4LWQ1OGE4MDVkLWFjM2ItNDlmMC05MWMxLTQ5YzdmMjNlYTc4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMjA0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWEyNWNiMGVlMDYxMTM4ZmU0ZDVhNTJjNjY1NjYwYzM4ZWIzZWFlOTI0OGIzODE0OTg2Zjc2MTdhNTkyODM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T_ISDBWDMtdoMuMm65aAHh5qyFHlEHZKzlm2448Jzbk) Please refer to the testing number.So, it shouldn't be 100% Chongqing？

Unfortunately nobody knows what other seqs look like. Based on existing seqs it is 100%.

**Comment by HynnSpylor** [comment]
Oh I had intended to propose it about 6 hours ago, but failed for the poor network!

Chongqing updates very new 5 seqs, all of them on the branch. Despite it could be a cluster, there is another one detected in Liaoning Province, which is more than 1,000 km from Chongqing, indicating the spread in China.

Genomes:
EPI_ISL_18651177, EPI_ISL_18678962, EPI_ISL_18815387, EPI_ISL_18819543, EPI_ISL_18835379, EPI_ISL_18847565,
EPI_ISL_18854014, EPI_ISL_18869787, EPI_ISL_18876905, EPI_ISL_18881153, EPI_ISL_18886344, EPI_ISL_18886394,
EPI_ISL_18900903, EPI_ISL_18909539, EPI_ISL_18926250-18926254,

**Comment by aviczhl2** [comment]
> Oh I intended to propose it about 6 hours ago, but failed for the poor network!
> 
> Chongqing updates very new 5 seqs, all of them on the branch. Despite it could be a cluster, there is another one detected in Liaoning Province, which is more than 1,000 km from Chongqing, indicating the spread in China.
> 
> Genomes: EPI_ISL_18651177, EPI_ISL_18678962, EPI_ISL_18815387, EPI_ISL_18819543, EPI_ISL_18835379, EPI_ISL_18847565, EPI_ISL_18854014, EPI_ISL_18869787, EPI_ISL_18876905, EPI_ISL_18881153, EPI_ISL_18886344, EPI_ISL_18886394, EPI_ISL_18900903, EPI_ISL_18909539, EPI_ISL_18926250-18926254,

There is another JN.1+S:A67V branch achieving high local prevalence in another undersampled area of Assam, India, #1293.

**Comment by FedeGueli** [comment]
One scientist of the Chongqing  lab that seequenced this has opened an issue on the Pango report, i suggest to track this in the main repo: @aviczhl2 if you have suggestions/better queries / trees put them in the main page proposal Thank you!

https://github.com/cov-lineages/pango-designation/issues/2498

**Comment by aviczhl2** [comment]
> One scientist of the Chongqing lab that seequenced this has opened an issue on the Pango report, i suggest to track this in the main repo: @aviczhl2 if you have suggestions/better queries / trees put them in the main page proposal Thank you!
> 
> [cov-lineages/pango-designation#2498](https://github.com/cov-lineages/pango-designation/issues/2498)

I think his proposal is a general JN.1+S:A67V containing 10+ separate lineages?

**Comment by HynnSpylor** [comment]
2 more in CO, US

**Comment by FedeGueli** [comment]
> > One scientist of the Chongqing lab that seequenced this has opened an issue on the Pango report, i suggest to track this in the main repo: @aviczhl2 if you have suggestions/better queries / trees put them in the main page proposal Thank you!
> > [cov-lineages/pango-designation#2498](https://github.com/cov-lineages/pango-designation/issues/2498)
> 
> I think his proposal is a general JN.1+S:A67V containing 10+ separate lineages?

thank you for noticing and thanks for reopening this one. we could comment here and there transfer our findings to the issue opened by the lab.

**Comment by aviczhl2** [comment]
> thank you for noticing and thanks for reopening this one. we could comment here and there transfer our findings to the issue opened by the lab.

He says 6/10 of his samples are from this branch. So I change the prevalence to 60%.

**Comment by HynnSpylor** [comment]
+2 in Henan Province, China

**Comment by FedeGueli** [comment]
27 +2 Henan + 4 Germany please propose it once reaches 40.

**Comment by FedeGueli** [comment]
It seems that the other issue is now aligned with this. closing this then
