### ISSUE TITLE
JN.1/KL.1 recombinant(9 seqs,Canada)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1396]
I thought it was a singlet, but @JosetteSchoenma finds another 8. Make an issue. 

JN.1--KL.1--JN.1

Breakpoint 1 between 12816 and 13338
Breakpoint 2 between 28298 and 28957

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3673c762-5094-44ee-8182-893045ef0221)

Additional mutations: 
G28027A

Orf8:W45*

G28027A from a KL.1 branch

GISAID query: G15451A, G11727A, G28027A
No. of seqs: 9(Canada)

First: EPI_ISL_18769330, 2024-1-4
Latest: EPI_ISL_18867732, 2024-1-26

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_c41c_8a3490.json)

One of the seqs get the JN.1.4 mutation of C774T, suggesting this mutation may be convergent in JN.1* or JN.1-like variants. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/cbd71e0e-72d0-42c9-9f6b-110a44d2cc9a)

**Comment by aviczhl2** [comment]
No new seqs

**Comment by Walde1nsamkeit** [comment]
C11003T,C12815T,A16878T 15
