### ISSUE TITLE
JN.1.22/XDD.1 recombinant(35 seqs, 2 countries, 21% Galicia, 4 with S:F456L)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1397]
There seems to be a new recombinant which is best explained by XDD.1/JN.1.22 recomb.

XDD.1+A5720G(rev),A6183G,T6541C(rev),C13019T,G12111A,C19164T

Orf1a: S1819G(rev), S3949N

XDD.1--JN.1.22--XDD.1

Breakpoint 1 between 3566 and 5719
Breakpoint 2 between 13020 and 23972

G12111A,C19164T are private

GISAID query: C13019T, A6183G, C29625T
No. of seqs: 3(Spain)
EPI_ISL_18927194, 2024-2-13
EPI_ISL_18927200,18927201, 2024-2-15

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_3b6b9_a1c220.json?c=gt-nuc_13019&gmax=14019&gmin=12019&label=id:node_11302060)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/744f869b-56aa-47b6-80d8-b0de37455f72)

**Comment by aviczhl2** [comment]
5 more from Spain

**Comment by aviczhl2** [comment]
It represents 8/25=32% of Galicia's seqs in 2024-3. (or 8/84=10% of whole Spain)

**Comment by FedeGueli** [comment]
it seems fast!

**Comment by FedeGueli** [comment]
Lets propose it once it gets 25!

**Comment by aviczhl2** [comment]
Galicia uploads a new batch, share goes down to 9/43=21%.

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
+2 Galicia

**Comment by FedeGueli** [comment]
still circulating earlier in May in Galicia, i bet it won't make it through the next month but lets keep it open
