### ISSUE TITLE
FL.4 with S:D1259Y and N:T334I misclassified in FL.2 usher branch (170 seqs, 10 countries, last seqs from Global) 

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#140]
FL.4+C2416T+C29274T(N:T334)+G25337T(S:D1259Y)
GISAID query: C2416T,C29274T,G25337T

No. of seqs: 92 on GISAID, some more on GenBase (1 Singapore(from China), 1 Thailand 3 USA(NY,IL,CA), 1 New Zealand, 5 Japan,   2 Anhui 5 Fujian 20 Guangdong 6 Heilongjiang 1 Henan 19 Hong Kong 6 Hubei 8 Shanghai 6 Sichuan 8 Yunnan) 

First seq: EPI_ISL_17433565, 2023-3-13, Hong Kong
Latest: EPI_ISL_17739668, 2023-5-23, Heilongjiang

Note that some 2023.5 GenBase seqs do not have a GISAID alternative, so actual seq count is more than 92. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35dd7_bfb250.json?label=id:node_6720601)

Usher classifies it on an FL.2+orf1b:V1092F(FL.4 defining)+ A4579T(reversion of FL.2 defining) branch, so it is actually FL.4. 
@AngieHinrichs shall fix it. 

<img width="1395" alt="Screenshot 2023-06-04 at 11 46 24" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/22eadb6d-e6a0-4748-869a-e88a78dd19ce">

**Comment by aviczhl2** [comment]
1 more from Laos.

**Comment by aviczhl2** [comment]
152  seqs, Canada

**Comment by aviczhl2** [comment]
158 seqs, UK

**Comment by aviczhl2** [comment]
163 seqs, South Korea.

**Comment by aviczhl2** [comment]
@FedeGueli Do you think this one needs a proposal/designation?

**Comment by FedeGueli** [comment]
> @FedeGueli Do you think this one needs a proposal/designation?

Yes definetely! i would run through growing issues later this noon but lets propose this one.
I was waiting for usher tree to be fixed is it still misplaced to FL.2?? Cc @angiehinrichs

**Comment by aviczhl2** [comment]
>  I was waiting for usher tree to be fixed is it still misplaced to FL.2??
Unfortunately, yes.
