### ISSUE TITLE
NY: XBB.1.5.106 saltation with S:F157S ,S:K202N, S:K304N and tot 16 AA ( 3 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1400]
I was tracking this saltation that apparently grew to 3

Defining mutations:
XBB.1.5.106 (S:A623V) > Orf1a:V28I (G347A)> Orf1a:E937G (A3075G) > G1148A, Orf1a:K367T (A1365C) , Orf1a:N1081S (A3507G), Orf1a:S1218N (G3918A), Orf1a:L1368I (C4367A), C4456T, Orf1a:T1881I (C5907T), C6781T, Orf1a:H2794Y(C8645T), Orf1a:H2794Y (T10721C),C11173T C20178G, S:F157S (T22032C),S:K202N (A22168T), S:K304N (A22474C), T24028C, C25378T, orf3a:I35M (A25497G), M:I52T (T26677C), C26894T,  A28266T, N:T135I (C28677T),C29272T, N:K361I (A29355T)
<img width="939" alt="Screenshot 2024-02-26 alle 09 59 23" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a186cf09-a4fe-4701-a81e-bd25f6768875">
 

Query:A1365C, A3507G, G3918A

Samples : 3 
EPI_ISL_18828912, EPI_ISL_18856190, EPI_ISL_18914858,
tree:
<img width="1182" alt="Screenshot 2024-02-26 alle 09 58 52" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/75761ddd-4949-4630-93d0-4b5b055c1d70">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_809e_c4ce40.json?label=id:node_4036219

**Comment by aviczhl2** [comment]
No further seqs.
