### ISSUE TITLE
Undesignated S:V1264L lineage in JN.1 (248 Samples, 15 Countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1401]
I just noticed that beside JN.1.1.4 there is another branch of JN.1 displaying the known beneficial mutation S:V1264L

Defining mutations:
JN.1> C5497T > S:V1264L (G25352T)

Query: C5497T ,G25352T,T3565C
Samples : 140
First collected in Germany on 2023-11-21
Countries: 13 ( US the most representative)
Tree:
<img width="1173" alt="Screenshot 2024-02-27 alle 09 47 36" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ae1586d8-30d3-4bfe-b484-2498bb2b27b2">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4c567_da0d60.json?label=id:node_6904587

<Details>
<Summary>
Genomes
</Summary>
EPI_ISL_18593890, EPI_ISL_18599951, EPI_ISL_18602001,
EPI_ISL_18619780, EPI_ISL_18663535, EPI_ISL_18668211,
EPI_ISL_18692245, EPI_ISL_18696840, EPI_ISL_18697169,
EPI_ISL_18707775, EPI_ISL_18708838, EPI_ISL_18722379-18722381,
EPI_ISL_18724921, EPI_ISL_18728312, EPI_ISL_18728795,
EPI_ISL_18729289, EPI_ISL_18732331, EPI_ISL_18754855,
EPI_ISL_18756986, EPI_ISL_18757010, EPI_ISL_18757215,
EPI_ISL_18757353, EPI_ISL_18757421, EPI_ISL_18757474,
EPI_ISL_18768678-18768679, EPI_ISL_18769009, EPI_ISL_18775374,
EPI_ISL_18779349, EPI_ISL_18779488, EPI_ISL_18779954,
EPI_ISL_18780009, EPI_ISL_18784573, EPI_ISL_18789992,
EPI_ISL_18794088, EPI_ISL_18794952, EPI_ISL_18798117,
EPI_ISL_18802118, EPI_ISL_18803585, EPI_ISL_18804641,
EPI_ISL_18804689, EPI_ISL_18808490, EPI_ISL_18808696,
EPI_ISL_18808806, EPI_ISL_18817322, EPI_ISL_18817346,
EPI_ISL_18821236, EPI_ISL_18826421, EPI_ISL_18826452,
EPI_ISL_18826652, EPI_ISL_18826768, EPI_ISL_18827680,
EPI_ISL_18827707, EPI_ISL_18827748, EPI_ISL_18827931,
EPI_ISL_18828918, EPI_ISL_18829900-18829901, EPI_ISL_18829904,
EPI_ISL_18830308, EPI_ISL_18832369, EPI_ISL_18834980,
EPI_ISL_18835921, EPI_ISL_18836044, EPI_ISL_18836455,
EPI_ISL_18836594, EPI_ISL_18836768, EPI_ISL_18839699,
EPI_ISL_18841310, EPI_ISL_18847617, EPI_ISL_18847731,
EPI_ISL_18847790, EPI_ISL_18849700, EPI_ISL_18852196,
EPI_ISL_18852509, EPI_ISL_18854924, EPI_ISL_18856200,
EPI_ISL_18859530, EPI_ISL_18859538, EPI_ISL_18859731,
EPI_ISL_18861930, EPI_ISL_18863231, EPI_ISL_18863283,
EPI_ISL_18863290, EPI_ISL_18863410, EPI_ISL_18863599,
EPI_ISL_18863895, EPI_ISL_18871056, EPI_ISL_18871284,
EPI_ISL_18871289, EPI_ISL_18877729, EPI_ISL_18877982,
EPI_ISL_18880464, EPI_ISL_18880474, EPI_ISL_18880507,
EPI_ISL_18880725, EPI_ISL_18881948, EPI_ISL_18882387,
EPI_ISL_18882413, EPI_ISL_18882450, EPI_ISL_18882589,
EPI_ISL_18882644-18882645, EPI_ISL_18882721, EPI_ISL_18882958,
EPI_ISL_18882989, EPI_ISL_18883904, EPI_ISL_18886233,
EPI_ISL_18887349, EPI_ISL_18887548, EPI_ISL_18888389,
EPI_ISL_18892302, EPI_ISL_18892367, EPI_ISL_18893294,
EPI_ISL_18895135, EPI_ISL_18895209, EPI_ISL_18896870,
EPI_ISL_18905448, EPI_ISL_18908732, EPI_ISL_18914888,
EPI_ISL_18917603, EPI_ISL_18919407, EPI_ISL_18919434,
EPI_ISL_18920155, EPI_ISL_18920201, EPI_ISL_18920450,
EPI_ISL_18920567, EPI_ISL_18920734, EPI_ISL_18920958,
EPI_ISL_18921045, EPI_ISL_18921730-18921731, EPI_ISL_18921756,
EPI_ISL_18922760, EPI_ISL_18927869, EPI_ISL_18928322,
EPI_ISL_18933271, EPI_ISL_18935273
</Details>

**Comment by aviczhl2** [comment]
188 now

**Comment by aviczhl2** [comment]
202

**Comment by FedeGueli** [comment]
> C5497T ,G25352T,T3565C

worth proposing?

**Comment by aviczhl2** [comment]
> > C5497T ,G25352T,T3565C
> 
> worth proposing?

I guess you should. Although decreasing it is not a small branch.

**Comment by FedeGueli** [comment]
Now proposed in https://github.com/cov-lineages/pango-designation/issues/2573
