### ISSUE TITLE
JN.1.4/JG.3 recombinant(10 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1402]
There is a new JN.1.4/JG.3 recombinant.

JN.1.4--JG.3

Breakpoint between 23424 and 23602

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/dc770a9d-d16b-44b4-8e14-91e7dea679a4)

Additional mutations:
T11247C, C17502T, C24919T, T25303C (new)

Orf1a: M3661T

C17502T from a JN.1.4 branch, T11247C is private mutation
one of  C24919T and T25303C from JG.3 branch, the other is private

GISAID query: C17502T, C24919T,T18453C
No. of seqs: 2(USA-OH)

EPI_ISL_18933753, 2024-2-4
EPI_ISL_18933792, 2024-2-6

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_577db_db3620.json?f_userOrOld=uploaded%20sample&label=id:node_11307011)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0fa69a43-82a1-4e06-8c2e-e86294fae1f8)

**Comment by FedeGueli** [comment]
thanks for spotting, curious tom see how it goes with S2 from JG.3

**Comment by aviczhl2** [comment]
+1 USA-CA

**Comment by aviczhl2** [comment]
+4 USA-CA

**Comment by FedeGueli** [comment]
> +4 USA-CA

query changed (or it was me i ve saved a wrong one): C17502T, C24919T,T18453C

**Comment by aviczhl2** [comment]
No new seqs.

**Comment by aviczhl2** [comment]
+2 USA

**Comment by FedeGueli** [comment]
Unsure if still around. lets see.

**Comment by FedeGueli** [comment]
no new sequence closing it
