### ISSUE TITLE
JN.1+ C26894T+ C25680T Branch with S:M153I  (41)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1403]
It is the same branch of JN.1.13, so this is a sibling lineage of it 

JN.1 > C26894T > C25680T > C4202T > S:M153I (G22021T)
Query:  C25680T,C4202T,G22021T
Samples:41
First sample from NY 2023-12-14
Countries: 2 (Us mainly + Puerto Rico)
Tree:
<img width="1171" alt="Screenshot 2024-02-27 alle 11 15 35" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/67851283-9a56-4be4-ab5e-ea0372d8bd81">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_47413_db2e30.json?c=gt-S_153&label=id:node_6925414

<Details>
<Summary
Genomes
</Summary>
EPI_ISL_18728528, EPI_ISL_18728927, EPI_ISL_18757422,
EPI_ISL_18775622, EPI_ISL_18775648, EPI_ISL_18779167,
EPI_ISL_18780144, EPI_ISL_18780415, EPI_ISL_18808285,
EPI_ISL_18808757, EPI_ISL_18816657, EPI_ISL_18826155,
EPI_ISL_18826213, EPI_ISL_18826258, EPI_ISL_18826317,
EPI_ISL_18827465, EPI_ISL_18828325, EPI_ISL_18836167,
EPI_ISL_18847855, EPI_ISL_18859625, EPI_ISL_18861991,
EPI_ISL_18863165, EPI_ISL_18868196, EPI_ISL_18871824,
EPI_ISL_18880461, EPI_ISL_18895076, EPI_ISL_18895406,
EPI_ISL_18899500, EPI_ISL_18899506, EPI_ISL_18899532,
EPI_ISL_18899537, EPI_ISL_18899541, EPI_ISL_18899546,
EPI_ISL_18899600, EPI_ISL_18899637, EPI_ISL_18908910,
EPI_ISL_18918273, EPI_ISL_18921023, EPI_ISL_18921098,
EPI_ISL_18921356, EPI_ISL_18928943

</Details>

**Comment by aviczhl2** [comment]
Designated JN.1.27
