### ISSUE TITLE
JN.1 sublineage with pandemic defining mutation reverted :S:D614D plus S:R273S and Orf9b:M1V, N:N4S, N:G97S  (9 Samples 4 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1406]
I just spotted a lineage that seemes to be dead instead it was recently sampled in February again.
The main thing of this lineage is that it has reverted the B.1 defining mutation S:D614G>D. 
In addition to this it has S:R273S that seems occuring mutliple times recently while it was sampled only 450 times from the start of the pandemic.
It is interesting also the pattern shown in Orf9b/N with the removal of the Orf9b start codon so that ORF9b should be 7AA shorter starting then withOrf9b:M8  and two additional N mutation N:N4S and N:G97S

Defining mutations:
JN.1 >A28284G (N:N4S/Orf9b:M1V)> S:R273S(G22381C), S:D614D (A>G23403A), C25276T, N:G97S (G28562A) 

Query: A28284G ,G22381C 

Samples : 8 ( 4 countries)
First sample collected on 2023-12-12
From a traveller to US (GBW) from Spain
Last sample collected on 2024-02-18 in Ontario

Tree:
<img width="1162" alt="Screenshot 2024-02-27 alle 11 49 19" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/29bd180d-b3d6-4615-8341-63a315b0f31f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_41fce_db1db0.json?label=id:node_6903865

IDs:
EPI_ISL_18615365, EPI_ISL_18636143, EPI_ISL_18702321,
EPI_ISL_18702326, EPI_ISL_18702330, EPI_ISL_18771440,
EPI_ISL_18910193, EPI_ISL_18933596

**Comment by krosa1910** [comment]
Not the first attempt to get rid of D614G, I think my HV.1* collection recorded something like D/G614S once

**Comment by FedeGueli** [comment]
One more sample coming from Italy but it is old from 2023.

**Comment by FedeGueli** [comment]
it seems estinguished
