### ISSUE TITLE
XDK.1: [=XDK+S:G213E,R346T] plus S:F456L ( 5 samples Uk, Switzerland)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1407]
<Details>
<Summary>
Original XDK.1 proposal
</Summary>

Spot this. XDK has S:T572I, and the F456L sample is the first to gather all 3 popular JN.1 levels, S:T572I,R346T and F456L.

XDK+G11596A,G22200A, G22599C(S:G213E,R346T)

GISAID query: G11596A, T22200A,G22599C,C5314T, 
No. of seqs: 5(New Zealand 1 Sweden 1 Switzerland 1 UK 1 France 1)
First: EPI_ISL_18864828, Sweden, 2024-1-27
Latest: EPI_ISL_18923351, New Zealand, 2024-2-7
</Details>

XDK > G22200A, G22599C(S:G213E,R346T) > G11596A > S:F456L (T22928C)
GISAID query for S:F456L branch: G11596A, C5314T, T22928C,C23277T ( 3 samples)

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice101_genome_test_29a25_dad850.json?label=id:node_11308114)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a9d7d7d5-adb7-4315-9a63-457e81687ee8)

Tree of 456L branch as of  April 22 (**EDITED**):
<img width="1062" alt="Screenshot 2024-04-22 alle 09 55 00" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ee6a1ccd-10fb-40a9-b444-ea804b277dad">

**Comment by aviczhl2** [comment]
Designated XDK.1

**Comment by FedeGueli** [comment]
The FLiRTrio branch has now reached three sequences with one very recent from Uk ( the new zealand one is an unrelated recomb found by @JosetteSchoenma  ): 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3084d_616170.json?label=id:node_11411254
<img width="1152" alt="Screenshot 2024-04-22 alle 09 53 24" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0de78400-9234-4780-b078-21118e49541b">

Reopen it.  @aviczhl2 please track back this one!

**Comment by JosetteSchoenma** [comment]
Just adding that one from England, EPI_ISL_19055682, has A475V as well?

**Comment by FedeGueli** [comment]
+1 England

**Comment by aviczhl2** [comment]
Designated XDK.1.2
