### ISSUE TITLE
XDQ with S:N487D, 11 seqs, 11 countries (with a singlet with S:A222V)

### ISSUE THREAD

**Issue by DeepakPhuyal** [sars-cov-2-variants/lineage-proposals#1408]
XDQ with additional ORF1a:F2802C (T8670G) and S:N487D (A23021G).

N487D is masked by Usher.

3 sequences since Jan 10th 2024.

EPI_ISL_18771091 Singapore from Hong Kong.
EPI_ISL_18840256 US-NY (GBW) from Qatar.
EPI_ISL_18932405 England.

Query: T8670G, A23021G  
A23021G,T22846 new query to exclude 8670.  (found and edited by @aviczhl2 )

**Comment by aviczhl2** [comment]
+1 Vietnam.

**Comment by aviczhl2** [comment]
@AngieHinrichs, what is the issue causing S:487 masked?

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs, what is the issue causing S:487 masked?

As far as I can tell, S:487 is not masked.  Can you show where it appears to be masked?

Here is a view of the branch in taxonium -- the mutation A23021G (S:N487D) is in the mutation list in the mouseover for the selected node.
<img width="482" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/186983/700c0cfe-6b5a-44d5-b4b3-f98b249ba7e5">

**Comment by aviczhl2** [comment]
> > @AngieHinrichs, what is the issue causing S:487 masked?
> 
> As far as I can tell, S:487 is not masked. Can you show where it appears to be masked?
> 
> Here is a view of the branch in taxonium -- the mutation A23021G (S:N487D) is in the mutation list in the mouseover for the selected node. <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/186983/309962327-700c0cfe-6b5a-44d5-b4b3-f98b249ba7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDY4MTMsIm5iZiI6MTcwOTYwNjUxMywicGF0aCI6Ii8xODY5ODMvMzA5OTYyMzI3LTcwMGMwY2ZlLTZiNWEtNDRkNS1iNGIzLWY5OGIyNDliYTdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjIzZTJkMjJhYWYxMjUyNjUxYTM2MmE1ODc3M2JjMWRiMmE2MDVjMGRiYTY0ZGNhNmQyNWUwZjYyZjUxYTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CgQ1VO51bwxKNpIO7t6jv08_yDu2POVj_RPJ-M8ikTI">

I believe in previous versions it was masked. I don't think I've seen any S:N487D branch before. Maybe some technical issues, glad it's now solved.

**Comment by FedeGueli** [comment]
> > > @AngieHinrichs, what is the issue causing S:487 masked?
> > 
> > 
> > As far as I can tell, S:487 is not masked. Can you show where it appears to be masked?
> > Here is a view of the branch in taxonium -- the mutation A23021G (S:N487D) is in the mutation list in the mouseover for the selected node. <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/186983/309962327-700c0cfe-6b5a-44d5-b4b3-f98b249ba7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDY4MTMsIm5iZiI6MTcwOTYwNjUxMywicGF0aCI6Ii8xODY5ODMvMzA5OTYyMzI3LTcwMGMwY2ZlLTZiNWEtNDRkNS1iNGIzLWY5OGIyNDliYTdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjIzZTJkMjJhYWYxMjUyNjUxYTM2MmE1ODc3M2JjMWRiMmE2MDVjMGRiYTY0ZGNhNmQyNWUwZjYyZjUxYTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CgQ1VO51bwxKNpIO7t6jv08_yDu2POVj_RPJ-M8ikTI">
> 
> I believe in previous versions it was masked. I don't think I've seen any S:N487D branch before. Maybe some technical issues, glad it's now solved.

there was one BA.2.86 + 487D proposed here.

**Comment by aviczhl2** [comment]
> > > > @AngieHinrichs, what is the issue causing S:487 masked?
> > > 
> > > 
> > > As far as I can tell, S:487 is not masked. Can you show where it appears to be masked?
> > > Here is a view of the branch in taxonium -- the mutation A23021G (S:N487D) is in the mutation list in the mouseover for the selected node. <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/186983/309962327-700c0cfe-6b5a-44d5-b4b3-f98b249ba7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDY4MTMsIm5iZiI6MTcwOTYwNjUxMywicGF0aCI6Ii8xODY5ODMvMzA5OTYyMzI3LTcwMGMwY2ZlLTZiNWEtNDRkNS1iNGIzLWY5OGIyNDliYTdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjIzZTJkMjJhYWYxMjUyNjUxYTM2MmE1ODc3M2JjMWRiMmE2MDVjMGRiYTY0ZGNhNmQyNWUwZjYyZjUxYTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CgQ1VO51bwxKNpIO7t6jv08_yDu2POVj_RPJ-M8ikTI">
> > 
> > 
> > I believe in previous versions it was masked. I don't think I've seen any S:N487D branch before. Maybe some technical issues, glad it's now solved.
> 
> there was one BA.2.86 + 487D proposed here.

Yeah that's proposed by me today. The seqs were uploaded in 2-28 but at that time I didn't find any 487 branches.

**Comment by FedeGueli** [comment]
Sorry i recallef badly it was 487T months ago

https://github.com/sars-cov-2-variants/lineage-proposals/issues/985#issue-1949590309

**Comment by aviczhl2** [comment]
> Sorry i recallef badly it was 487T months ago
> 
> [#985 (comment)](https://github.com/sars-cov-2-variants/lineage-proposals/issues/985#issue-1949590309)

Yeah that's position 23022. Seems that the bugged position was 23021.

**Comment by FedeGueli** [comment]
> > Sorry i recallef badly it was 487T months ago
> > [#985 (comment)](https://github.com/sars-cov-2-variants/lineage-proposals/issues/985#issue-1949590309)
> 
> Yeah that's position 23022. Seems that the bugged position was 23021.

@aviczhl2 :
Now there is also a XDS branch with S:N487D  of 4 sequences three with S:R273S found with A23021G,G22381T,C15656T,T22928G

<img width="1139" alt="Screenshot 2024-03-09 alle 14 23 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c55bbd79-bd1c-4c3b-a719-14741078ce1c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_42c37_c61110.json?label=id:node_6992584

Do you want to propose it hence you followed first this mutation?

**Comment by aviczhl2** [comment]
+1 South Korea

**Comment by Over-There-Is** [comment]
Russia

**Comment by aviczhl2** [comment]
+2 Japanese seqs without A8670G. 

Suggest to alter query to A23021G,T22846 which finds the total 10.

**Comment by aviczhl2** [comment]
+1 Australia with additional S:A222V
