### ISSUE TITLE
JN.1.4 + N:R40H & ORF9b:V37I (48 seqs, 4 countries)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#1409]
Sub-lineage of: JN.1.4
Substitution on top of JN.1.4: N:R40H + ORF9b:V37I 
Earliest sequence: 2023-12-19, New York, USA — EPI_ISL_18756904
Most recent sequence: 2024-02-04, New York. USA — EPI_ISL_18921031
Countries circulating: Puerto Rico (20), USA (10) [4 CO, 3 NY, 2 TX, 1 OK], France (1), Canada (1)
Number of sequences: 32
GISAID nucleotide query:  C774T, C28311T, G28392A
CovSpectrum query: [JN.1.4* (Nextclade) + N:R40H, ORF9b:V37I](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=N%3AR40H%2CORF9b%3AV37I&nextcladePangoLineage=JN.1.4*&)

```{r, echo=FALSE}
EPI_ISL_18756904,EPI_ISL_18782492,EPI_ISL_18817626,EPI_ISL_18837455,EPI_ISL_18837488,EPI_ISL_18847344,EPI_ISL_18862100,EPI_ISL_18869580,EPI_ISL_18869633,EPI_ISL_18916988,EPI_ISL_18916989,EPI_ISL_18917018,EPI_ISL_18917049,EPI_ISL_18917050,EPI_ISL_18917051,EPI_ISL_18917070,EPI_ISL_18917071,EPI_ISL_18917079,EPI_ISL_18917080,EPI_ISL_18917081,EPI_ISL_18917082,EPI_ISL_18917083,EPI_ISL_18917084,EPI_ISL_18917085,EPI_ISL_18917086,EPI_ISL_18917087,EPI_ISL_18917088,EPI_ISL_18917089,EPI_ISL_18917090,EPI_ISL_18921031,EPI_ISL_18927928,EPI_ISL_18927959
```

![Screenshot 2024-02-27 at 13-35-11 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ singleSubtreeAuspice_genome_108a6_e0e160 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/ac8de920-fc8b-4d99-b294-4120aa76edb9)

Both mutations are estimated to increase fitness

![Nmut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/16e4f3d8-6a52-4bf5-a4a7-2aab052fe059)
![orf9bmut(1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/cdcf1b6e-2ced-40f9-ac4b-9766f2d72303)

**Comment by FedeGueli** [comment]
Thanks for proposing! orf9b/N mutations could give unexpected advantages. cc @ryhisner do you already met this mutation?

**Comment by FedeGueli** [comment]
It disappeared closing it
