### ISSUE TITLE
JN.1.11.1 (S:F456L, V1104L) + S:Q493E 12 seq, [ 6 travel seq: India(4), Honduras(1), Turkey (1) ] + 1 UK, 1 Canada

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1410]
**Description**
**Sub-lineage of:** JN..1.11.1
**Earliest sequence:** 2024-2-11, USA, Virginia (traveler from India) — EPI_ISL_18931427
**Most recent sequence:** 2024-2-16, USA, California (traveler from India) — EPI_ISL_18937626
**Continents circulating:** Asia (2)
**Countries circulating:** India (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** T22926C, T22928C, C23039G
**CovSpectrum Query:** Nextcladepangolineage:JN.1.11* & S:Q493E
**Substitutions on top of JN.1.11:**
**Spike:** Q493E
**Nucleotide:** C23039G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.11.1_Q493E.json?c=gt-S_493&gmax=25384&gmin=21563&label=id:node_6922158
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ed34ee84-0afa-4fb5-b1ef-2e4d7943b3c5">

**Evidence**
These two sequences were detected in airports on the US East Coast (Virginia) and West Coast (California) and both uploaded in the past three days. Collection dates are February 11 and February 16. Unless this is at least somewhat prevalent in some region of India, it's highly unlikely it would show up in two unrelated travel sequences like this in quick succession.

S:Q493 is an interesting residue. Mutations like Q493K/H/Y/V/A show up on rare occasions in chronic-infection sequences, usually ones that are quite extreme. Q493V and Q493A in particular result in large increases in ACE2 affinity, and Q493E puts both of those residues one nucleotide mutation away. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18931427, EPI_ISL_18937626
</details>

**Comment by FedeGueli** [comment]
Thanks Ryan!

**Comment by ryhisner** [comment]
Two more of these showed up today. Both Ginkgo Bozoworks sequences, so the quality is bad. One was from India and another, which has extremely low coverage, came from a traveler from Honduras. Different airports again, one New Jersey, the other California. Collection dates Feb 25 and Feb 27. 
EPI_ISL_18965356, EPI_ISL_18965364

**Comment by FedeGueli** [comment]
+1 Canada.

@corneliusroemer i suggest to look at this:
 493 is a key residue 
here mutated to negative charge (as we saw some 478E at the start of the BA.2.86 rise) 
prevalence in GBW samples points at some prevalence in an undersampled are around/within India

**Comment by FedeGueli** [comment]
@ryhisner please propose it when it reaches 15

**Comment by FedeGueli** [comment]
+1 England it is expanding quite fastly

**Comment by ryhisner** [comment]
Two more travel sequences from the US today: one a traveler from India, the other a traveler from Turkey. Ginkgo Bozoworks sequences again, so they're terrible.

**Comment by FedeGueli** [comment]
Thx Ryan. Please take the gisaid count as a whole , gbw are usually doubled but we count the doubled one as real sequence. 
It is hard work disentangle doubled seqs forneach lineages. Better to track it easily, everyone of us knows that already.

**Comment by aviczhl2** [comment]
Designated KP.3
