### ISSUE TITLE
JN.1/(XCH.1+S:N450K) recombinant that cannot be added to usher(2 seqs, Italy)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1411]
One interesting singlet in #991 finds a partner, and it seems due to unknown reason the original singlet was not in usher, too.@AngieHinrichs

JN.1--XCH.1

Breakpoint between 13340 and 15450

Additional mutations: G4205A, C7105T, G9130T, C16289T, G17425T, T22912G, C24061T,C26437T

Orf1a:A1314T
Orf1b:C688F,A1141V, V1320L
S:N450K

One of G4205A, C7105T, G9130T from an JN.1 branch, the other 2 are private mutations
T22912G from an XCH.1 branch, C16289T, G17425T, C24061T,C26437T are private mutations

GISAID query: T22912G, T13339C,G15451A
No. of seqs: 2(Italy)

EPI_ISL_18824050,2024-1-16
EPI_ISL_18939561, 2024-2-10

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice271_genome_test_3dc43_f507b0.json?f_userOrOld=uploaded%20sample&label=id:node_11308617)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/4db4b788-2239-4316-9dc8-e689028b49dd)

@AngieHinrichs, please add them to usher.

**Comment by AngieHinrichs** [comment]
EPI_ISL_18939561 is so new that it's not even in fasta that we downloaded yesterday evening.  Hopefully it will be in tonight's download; if so then it will be added tomorrow (2024-02-29).

EPI_ISL_18824050 has 28 private mutations relative to placement so it is being filtered out.  When EPI_ISL_18939561 is added, EPI_ISL_18824050 will no longer be a singleton and that should reduce the number of private mutations.  So again, hopefully in tomorrow's build, both sequences should be added.

**Comment by aviczhl2** [comment]
Dead
