### ISSUE TITLE
Potential BA.2.86.1/JN.1 recombinant(6 sequences, France)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1418]
BA.2.86.1> C11396T, C13554T(Orf1a:L3711F)> C6573T(Orf1a:S2103F)> T22926C(S:L455S), T27810C(Orf7b:F19L)
Query: C6573T, C11396T, T22926C

Potential recombinant of BA.2.86.1> C11396T, C13554T> C6573T and JN.1
Breakpoint: 18894\~22926

Earliest sequence: 12-08 Auvergne-Rhône-Alpes, France EPI_ISL_18676076
Latest sequence: 01-29 Rhône, Auvergne-Rhône-Alpes, France EPI_ISL_18902222
Regions detected: France 6(ARA 4, BFC 1, PAC 1)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_67762_5162d0.json?label=id:node_6886935

Sequences:
EPI_ISL_18676076, EPI_ISL_18799700, EPI_ISL_18831585,
EPI_ISL_18832568, EPI_ISL_18902158, EPI_ISL_18902222

**Comment by FedeGueli** [comment]
No sequence came from this after January
