### ISSUE TITLE
JN.1+Orf7a:T14I, S:N185S, Orf7b:L19F(rev) (103 seqs, 9 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1419]
I find an interesting branch with JN.1-defining Orf7b:L19F reverted. Unsure about the reason but it seems not from single-BP 3' recomb of other BA.2.86* branch. 
 If it is a sandwich recomb the BP is  limited to BP1: 27434-27810, BP2: 27810-27863

The reversion shall be real as it co-appears with S:N185S and no seq with S:N185S on this branch has Orf7b:19L. 

JN.1+C11833T+T27863C+C27434T(Orf7a:T14I)+A22116G,C27810T(S:N185S, Orf7b:L19F(rev))

GISAID query: T27863C, C27434T,A22116G
No. of seqs: 103(UK 6 France 23 Italy 14 Netherlands 1 Oman 1 South Korea 1 Spain 43 Sweden 6 USA 6)

First: EPI_ISL_18724688, Spain, 2023-10-31
Latest: EPI_ISL_18950962, UK, 2024-2-24

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice128_genome_test_364b5_6d0040.json?label=id:node_6971015)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/436b83dc-7f7f-4062-a67e-ed55c7d66a95)

**Comment by FedeGueli** [comment]
Hi @aviczhl2  this was proposed by @doropfan and already transferred to main page please comment in the pango to highlight the reversion and your thoughts on that : https://github.com/sars-cov-2-variants/lineage-proposals/issues/1214

**Comment by FedeGueli** [comment]
main page issue: https://github.com/cov-lineages/pango-designation/issues/2471

**Comment by aviczhl2** [comment]
> Hi @aviczhl2 this was proposed by @DoropFan and already transferred to main page please comment in the pango to highlight the reversion and your thoughts on that : #1214

Oh. thanks.
