### ISSUE TITLE
FL.4 with orf7a:I10T and S:T961M misclassified in FL.2 usher branch(33 seqs,3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#142]
FL.4+T27422C(orf7a:I10T)+C27549T+C24444T(S:T961M)
GISAID query: C24444T,C27549T,T27422C

No. of seqs: 31( Canada 14 Japan 1 USA-CA 1 USA-UT 2 USA-HI 13)

First seq: EPI_ISL_17321916 USA-HI 2023-3-14
Latest: EPI_ISL_17706072 USA-CA 2023-5-4

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35dd7_bfb250.json?label=id:node_6720601)

Like #140, usher classifies it on another FL.2+orf1b:V1092F(FL.4 defining)+ A4579T(reversion of FL.2 defining) branch, so it is actually FL.4.
@AngieHinrichs 

<img width="1395" alt="Screenshot 2023-06-04 at 11 46 24" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d94e773f-5ad6-4fe2-8850-979423745209">

**Comment by FedeGueli** [comment]
i m closing this for now.
