### ISSUE TITLE
BA.1.1 saltation branch with >20 Spike aa mutations (2 seqs in Utah, US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1423]
Spotted by @ryhisner first (edited)

Earliest seq: 2024-02-08 (US- EPI_ISL_18960149)
Most recent seq: 2024-02-13 (US- EPI_ISL_18960183)
Countries detected: US (2)

mutations on top of BA.1.1:
Spike: P9L, 136-141del, 145-147del (actually 136-147del), N148F, P174S, L176F, 212del, A222V, 242-243del, F377L, S446G (rev), N450D, V445A, N460K-L461I, A484K, F486A->P (2-nuc), Q493R (rev), A575S, F592S, V642G, E654K, H681R, A688V, D843G, D936G, F1103L

ORF1a: E102A, E1223G, A1298V, D1323G, T1638I, A2344T, L3199S, N3443Y, V3718I, T4090I, T4161A

ORF1b: V1164L, N2328S

ORF3a: Y211C, T223I

M:I80V, A104V

ORF8:V62A, F120V, I121L

ORF9b:M1I

N: G5R, Q281L

![联想截图_20240307103155](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/26bca531-6c4e-4eaa-814f-a81904aec634)
![联想截图_20240307103126](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/dfca7a1b-be7b-4d2f-8887-e4f67dd7e500)

Usher Tree:

![联想截图_20240307103100](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/03e3e529-1fd4-4d54-a2d1-bb8d6f56234c)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31c34_91e3d0.json?c=gt-S_450

the 2 seqs are likely from one patient (very likely chronic?) However, some RBD-region features are interesting including N450D, E484A->K, F486P and Q493 rev, which is convergent to BA.2.86*, despite there are no additional mutations on 452-456 "hot spots".

Due to the large amount of mutations, we can monitor it for a time.  

Genomes:
EPI_ISL_18960149, EPI_ISL_18960183

**Comment by FedeGueli** [comment]
Thx @HynnSpylor this was the one described by @ryhisner in the groups yesterday!

**Comment by HynnSpylor** [comment]
Thx @FedeGueli ! Very sorry that I was busy recently and could not discuss in X group

**Comment by FedeGueli** [comment]
> Thx @FedeGueli ! Very sorry that I was busy recently and did not discuss in X group

No worries always good to be more than one to discover things

**Comment by aviczhl2** [comment]
No further seqs
