### ISSUE TITLE
HK.3/JN.1.1 recombinant(7 seqs, Australia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1424]
HK.3--JN.1.1

Breakpoint between 3566 and 5719

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/98f42e9a-c3d4-4061-bd0a-998f6942c802)

Additional mutations: 

G1886A, C2662T, T2698C,A3019G, C6310T, C10456T,G12522T

Orf1a: A541T, G4086V

G1886A, C2662T, T2698C,A3019G from an HK.3 branch
One of C6310T, C10456T,G12522T from a JN.1.1 branch, the other 2 are private mutations

GISAID query: A3019G, A6183G, C11747T
No. of seqs: 2(Australia)

EPI_ISL_18880829, 2023-2-3
EPI_ISL_18960711, 2023-2-16

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice13_genome_test_488ce_996be0.json?label=id:node_11323815)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b72ce868-760a-44ea-a2bd-d42991dcccd3)

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
Thx

**Comment by aviczhl2** [comment]
+1 Victoria
