### ISSUE TITLE
XDS+Orf1a:T891I, S:S680F(9 seqs, 5 countries) - roughly 10% in Portugal in February.

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1425]
This was in the original XDS proposal, and recently new seqs are added, make an issue.
XDS+C2937T,A6994G, C23601T (Orf1a:T891I, S:S680F)

GISAID query: C2937T,A6994G, C23601T
No. of seqs: 5(USA 2(from Portugal), Sweden 2 Germany 1)

First: EPI_ISL_18724545, Germany, 2023-12-7
Latest: EPI_ISL_18965332, USA from Portugal, 2024-2-27

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice21_genome_test_4b7a_c286b0.json?label=id:node_6992548)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/57403b6e-950d-449b-8716-8d9c2a64e123)

**Comment by aviczhl2** [comment]
+3 Portugal

**Comment by FedeGueli** [comment]
high prevalence in February: out of 41 samples labelled as from Portugal or travellers froom Portugal 4 are from this lineage

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by aviczhl2** [comment]
No new seqs
