### ISSUE TITLE
JN.1 + S:N417T + 2-nuc ORF1b:K774I (7 seq, USA, MN; Mar 22)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1427]
### **Description**
**Recombinant of:** JN.1*
**Earliest sequence:** 2024-1-23, USA, Minnesota — EPI_ISL_18880115
**Most recent sequence:** 2024-2-2, USA, Minnesota — EPI_ISL_18968458
**Continents circulating:** North America (5)
**Countries circulating:** USA (5)
**Number of Sequences:** 5
**GISAID Nucleotide Query:** A15788T, G15789T, A22812C
**CovSpectrum Query:** [3-of: A15788T, G15789T, A22812C]

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_NSP12_K783I_A15788T_G15789T.json?c=gt-S_417&gmax=25384&gmin=21563&label=id:node_7010757

<img width="1434" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6bd13c96-4b73-457e-88f3-a632cbf71469">

**Evidence**
S:417T was in Gamma and is almost universal in cryptic wastewater lineages. It very rarely shows up these days, but when it does, it's often in a highly mutated chronic-infection sequence. 

ORF1b:K774I, or NSP12_K783I, is a 2-nucleotide mutation that has never been seen before. It could have gotten from K→I by two amino acid routes: K→N→I or K→M→I. Both of these nuc mutations, as well as S:N417T, were acquired in one jump, or so it appears. There have only ever been ~208 sequences ever with G15789T and just four previous sequences with A15788T. 

<img width="1101" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/3491640f-060d-4b11-adec-c9751becab91">

This branch has only been detected in the state of Minnesota, USA, so far.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18880115, EPI_ISL_18955844, EPI_ISL_18965962, EPI_ISL_18968453, EPI_ISL_18968458
</details>

**Comment by aviczhl2** [comment]
No new seqs
