### ISSUE TITLE
3-Breakpoint GJ.1.2/JN.3.2.1 recombinant (8 seqs, 4 countries, 3 with 2-nuc S:1143F)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1428]
Previously there was a potential 3-BP GJ.1.2/JN.3.2.1 recombinant in #991, and now it gets company in another country.

JN.3.2.1--GJ.1.2--JN.3.2.1--GJ.1.2

Breakpoint 1 between 2940 and 3430
Breakpoint 2 between 11043 and 12788
Breakpoint 3 between 28210 and 28957

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1e148f3a-96fc-4e29-a140-8e55294107d4)

Additional mutations:
A2443G, C3876T, A6646G, T6747C, T10723C,  G19327T,C23191T

Orf1a:A1204V, L2161S, 
Orf1b: A1954S

T6747C,G19327T,C23191T are private mutations
A2443G from a JN.3.2.1 branch
C3876T,A6646G,T10723C from a GJ.1.2 branch

GISAID query: A17637G, T22928G, C7819G
No. of seqs: 3(UK 2 Luxembourg 1)
EPI_ISL_18969540,18969543, UK, 2024-2-26
EPI_ISL_18948961, Luxembourg, 2024-1-15

GISAID query for S:1143F branch: A17637G, T22928G, C7819G, C24989T (2 seqs)

This recomb shows that recombs with 3 potential BPs can be real. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice15_genome_test_4ab2f_f01390.json?label=id:node_11336704)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/01a1f7c2-711a-4295-9b7b-b5fee67c154e)

**Comment by ryhisner** [comment]
Very strange, but there's a very similar recombinant sequence from Utah, USA, but the breakpoints are not exactly the same.  It may actually be unrelated. If so, this would represent an incredible example of convergent recombination. 
EPI_ISL_18975795
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39d6b_1801a0.json?c=gt-nuc_14118&gmax=15118&gmin=13118&label=id:node_11338312

<br class="Apple-interchange-newline">
<img width="1496" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/663afbe1-f1f1-4d89-b08b-d8ae8de94c35">

**Comment by aviczhl2** [comment]
+1 USA

**Comment by aviczhl2** [comment]
> Very strange, but there's a very similar recombinant sequence from Utah, USA, but the breakpoints are not exactly the same. It may actually be unrelated. If so, this would represent an incredible example of convergent recombination. Or perhaps the person in which the recombination happened may have infected different people with slightly different versions of this recombinant? EPI_ISL_18975795 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39d6b_1801a0.json?c=gt-nuc_14118&gmax=15118&gmin=13118&label=id:node_11338312
> 
> 
> <img alt="image" width="1496" src="https://private-user-images.githubusercontent.com/33738461/312419355-663afbe1-f1f1-4d89-b08b-d8ae8de94c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjc2NzIsIm5iZiI6MTcxMDMyNzM3MiwicGF0aCI6Ii8zMzczODQ2MS8zMTI0MTkzNTUtNjYzYWZiZTEtZjFmMS00ZDg5LWIwOGItZDhhZThkZTk0YzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwNTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZDNjYzc1YjljMjE0OThlNGY0YTEwZWJkZWYyMTI5YjkwMmE2NzhlODk4MGI0OTAxMDFjNTU1ODVhNWZiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QNulu8xxziTx_DlvutMAl6lEztgKAcUONYScXUSsNRY">

They shall be the same recombinants. Usher edits seqs and fixes some JN.1 mutations to seqs to prevent artefacts, however this brings recombinants on the tree JN.1 mutations that they shouldn't have, hence new uploaded  seqs for the recombinant will have additional "reversions." because they don't have those JN.1 mutations. 

@AngieHinrichs This seems to be a terrible feature of usher for recombinant lineages.

**Comment by Over-There-Is** [comment]
A2443G is also inherited from a JN.3.2.1 branch. And as 3431 is reverted, the breakpoint should be upstream of it.

https://github.com/sars-cov-2-variants/lineage-proposals/issues/991#issuecomment-1979643252 (1513 and 11417 is not in the Utah sequence)

**Comment by Over-There-Is** [comment]
https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_6c9b_389ab0.json?label=id:node_11176276

**Comment by ryhisner** [comment]
One more from California today, collected 2024-3-3.
EPI_ISL_19015176

**Comment by FedeGueli** [comment]
> One more from California today, collected 2024-3-3. EPI_ISL_19015176

Ryan i cna't find a query to catch it too, have u a suggestion?

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1e49aed3-de88-43aa-b760-3ea68caa921c)

No mutation bug again.

> > One more from California today, collected 2024-3-3. EPI_ISL_19015176
> 
> Ryan i cna't find a query to catch it too, have u a suggestion?

**Comment by aviczhl2** [comment]
+1 Germany

**Comment by aviczhl2** [comment]
No new seqs

**Comment by corneliusroemer** [comment]
Hmm this one is interesting as it's appeared in quite a few countries - so likely circulating somewhere that doesn't sample.

Let's reopen and watch! Thanks for analyzing - I found it through github search 🎉  had missed it at first as it was closed.

<img width="1869" alt="Brave Browser 2024-05-15 18 50 39" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/1b4bfdd8-ae06-418f-8496-6958ac8e657e">

**Comment by Over-There-Is** [comment]
*5 countries now, EPI_ISL_19060029 is imported from India

**Comment by Over-There-Is** [comment]
But this lineage has not been detected for more than a month.

**Comment by Over-There-Is** [comment]
I think it doesn't need a under sampled source to spread to UK, Germany and Luxembourg. These countries are near enough each other.
It's already known this lineage is circulating in India now. But if a lineage emerges extensively in India, it will spread to Singapore soon. But it's not detected in Singapore yet.

**Comment by FedeGueli** [comment]
Closing it likely dead

**Comment by aviczhl2** [comment]
Designated XEG
