### ISSUE TITLE
XBB.1.16/JG.3 recombinant, 6 samples, Germany 4, Israel 1, England 1.

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1429]
Description: XBB.1.16.2/JG.3 recombinant, JG.3 Spike
Private mutations: none certain
Breakpoint: between nucleotide 5720 and 6008
Earliest sequence: 2023-09-26 from Israel
Most recent sequence: 2024-02-06 from Germany
Countries circulating: Germany 4, Israel 1, England 1.
GISAID query: C20104T, T4885C, C3042A 

The 4 German ones have extra S:K417Y

Nextclade:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/6779e0f9-0128-48bc-afbb-0ab390715a5d)

Nextclade comparison:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/b507609b-ca4e-4165-9456-95d4f26118eb)

**Comment by aviczhl2** [comment]
No more seqs for this one.
