### ISSUE TITLE
P.2 (Zeta)/XBB.1.5* Recombinant, Singlet, Brazil

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1431]
### **Description**
**Recombinant of:** P.2 and XBB.1.5*
**Breakpoint:** 20055-21617
**Most recent sequence:** 2024-2-4, Brazil, Santa Catarina, Ararangua — EPI_ISL_18971336
**Continents circulating:** South America (1)
**Countries circulating:** Brazil (1)
**Number of Sequences:** 1
**GISAID Nucleotide Query:** G970T, A4091T
**CovSpectrum Query:** [10-of: C100T, T3295C, T3766C, C4012T, C4586T, C5622T, T6218C, C6402T, C7688A, C8956T, C9924T, T10573C, T10667G, C11669T, C11824T, C12053T, A12964G, T14408G, T15738C, C16342T, C17104T, T17220C, C19586T, G20937A]
**Private Substitutions on top of P.2:**
**ORF1a:** E102K, E235D, R545V (2-nuc), I1276F, V1393M, P1786L, P2046L, V2252G, A3220V, C3423Y, R3802C
**ORF1b:** H1213Y, T2040I
**Nucleotide:** T3295C, C4012T, C4586T, C5622T, T6218C, C6402T, C7688A, C8956T, T10573C, C11669T, T15738C, C16342T, C17104T, T17220C, C19586T, G20937A

**Private Substitutions on top of XBB.1.5:**
**Spike:** N481I
**N:** G96V
**E:** D72N
**ORF3a:** K16E, T89I, M125L
**ORF9b:** V93L
**Nucleotide:** C22530T, A23004T, C23673T, A25438G, A25765T, C25658T, G26458A, G28202A, G28560T, C28657T, C29203T

**Nucleotide Deletions:** ∆A28254 (creates N/ORF9b TRS extended homology with TRS-L)
**Nucleotide Insertions:** ins27899T (frameshift leads to stop codon at 27953-27955)

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5764_1f4f0.json?c=gt-nuc_10667&gmax=11667&gmin=9667&label=id:node_3795707
<img width="1482" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/041a0883-0181-44ae-89ec-230c7930c6f9">

**Evidence**
I noticed this sequence because it has several mutations typically found in chronic infections. There is a lot of dropout, but there were are no Omicron mutations in ORF1ab and plenty of unfamiliar ones, which made me think this had to be a recombinant with a pre-Omicron variant. It turns out to share eight nucleotide mutations with P.2 (Zeta), including some very rare ones: C100T (5' UTR), T3766C (synonymous), T6218C (synonymous), C9924T (ORF1a:A3220V), T10667G (ORF1a:L3468V), C11824T (synonymous), C12053T (ORF1a:L3930F), A12964G (synonymous), and T14408G (ORF1b:L314R). 

As P.2 was prevalent in Brazil, this makes sense. P.2 circulated in Brazil mainly from November 2020 to February 2021, which means this person has been infected with P.2 **_for three years_**.

There is unfortunately a lot of dropout in ORF1ab, so there are likely other mutations that weren't registered. The exact areas of dropout are listed below:

**Nucleotide Dropout**—1341-1400, 1581, 1946-2252, 7200-7545, 7548, 7558, 7769-7797, 9950-10245, 14704, 16395, 16486, 16492, 16494, 16617-16647, 20409-20441, 24221, 24444-24445, 24448-24450, 24453, 24455, 24457, 24459, 24462
**Amino Acid Dropout**—ORF1a:359-379, ORF1a:439, ORF1a:561-663, ORF1a:2312-2428, ORF1a:2431, ORF1a:2502-2511, ORF1a:3229-3327, ORF1b:413, ORF1b:1007, ORF1b:1009, ORF1b:1051-1060, ORF1b:2314-2325, S:887, S:961, S:963-967

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18971336
</details>

**Comment by FedeGueli** [comment]
"Zed is back" (cit.)! unbelievable!

**Comment by Over-There-Is** [comment]
P.2> A12964G> T3766C> T6218C> C7834T
GK.1

G569A, G970T, C1898G, G1899T, T3295C, C4012T, A4091T, G4442A, C4586T, C5622T, C6402T, T7020G, C7688A, C8956T, T9139C, C9924T, G10533A, T10573C, T11542C, C11669T, T13282C, T14408G, A14493G, A16410G, C17104T, T17220C, T19278C, C19586T, G20937A, C22530T, A23004T, A25438G, A25765T, G26458A, ins27899T, C27903T, G28202A, del28254, G28560T, C29203T

**Comment by FedeGueli** [comment]
> P.2> A12964G> T3766C> T6218C> C7834T (6 seq) GK.1 (non GK.1.1)
> 
> G569A, G970T, C1898G, G1899T, T3295C, C4012T, A4091T, G4442A, C4586T, C5622T, C6402T, T7020G, C7688A, C8956T, T9139C, C9924T, G10533A, T10573C, T11542C, C11669T, T13282C, T14408G, A14493G, A16410G, C17104T, T17220C, T19278C, C19586T, G20937A, C22530T, A23004T, A25438G, A25765T, G26458A, ins27899T, C27903T, G28202A, del28254, G28560T, C29203T

Donors?

**Comment by Over-There-Is** [comment]
> > P.2> A12964G> T3766C> T6218C> C7834T (6 seq) GK.1 (non GK.1.1)
> > G569A, G970T, C1898G, G1899T, T3295C, C4012T, A4091T, G4442A, C4586T, C5622T, C6402T, T7020G, C7688A, C8956T, T9139C, C9924T, G10533A, T10573C, T11542C, C11669T, T13282C, T14408G, A14493G, A16410G, C17104T, T17220C, T19278C, C19586T, G20937A, C22530T, A23004T, A25438G, A25765T, G26458A, ins27899T, C27903T, G28202A, del28254, G28560T, C29203T
> 
> Donors?

Yeah, the donors are the branch I listed. And the rest are the private mutations.

**Comment by FedeGueli** [comment]
> > > P.2> A12964G> T3766C> T6218C> C7834T (6 seq) GK.1 (non GK.1.1)
> > > G569A, G970T, C1898G, G1899T, T3295C, C4012T, A4091T, G4442A, C4586T, C5622T, C6402T, T7020G, C7688A, C8956T, T9139C, C9924T, G10533A, T10573C, T11542C, C11669T, T13282C, T14408G, A14493G, A16410G, C17104T, T17220C, T19278C, C19586T, G20937A, C22530T, A23004T, A25438G, A25765T, G26458A, ins27899T, C27903T, G28202A, del28254, G28560T, C29203T
> > 
> > 
> > Donors?
> 
> Yeah, the donors are the branch I listed. And the rest are the private mutations.

Thanks good job
