### ISSUE TITLE
XDP+S:E309Q(39 seqs, 2 countries, 38 with JN.1-defining Orf7b:F19L restored)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1432]
XDP loses its JN.1-defining Orf7b:F19L through recomb with FL.15, however in this branch it regains this mutation. 

XDP+G6850A+G22487C,T27810C(Orf7b:F19L, S:E309Q)

GISAID query: G6850A,G22487C,C28846T 
GISAID query for Orf7b:F19L branch: G6850A,G22487C,T27810C
No. of seqs: 5(Canada)

First: EPI_ISL_18935397, 2024-2-12
Latest: EPI_ISL_18974638, 2024-2-25

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice227_genome_test_60f45_1d24f0.json?label=id:node_6991153)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0a90413c-1edd-456a-b951-168ac2381172)

**Comment by aviczhl2** [comment]
+1 Brazil without Orf7b:F19L. edit query.

**Comment by FedeGueli** [comment]
17 now 16 with the jn.1 defining mut reverted

**Comment by FedeGueli** [comment]
one new sample from May, @ryhisner noticed a trend of emergence of this mutation so lets keep it open for some more time

**Comment by aviczhl2** [comment]
Designated XDP.2
