### ISSUE TITLE
JN.1.13.1 (S:F59S, R346T, A1087S) + S:K679N reversion (~360 seq, Sep 14)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1434]
### **Description**
**Sub-lineage of:** JN.13.1
**Earliest sequence:** 2024-1-14, USA, New York — EPI_ISL_18848812
**Most recent sequence:** 2024-3-1, USA, New Jersey — EPI_ISL_18979160
**Continents circulating:** North America (27)
**Countries circulating:** USA (27)  — US State Breakdown: New York (19), New Jersey (6), California (1), Texas (1)
**Number of Sequences:** 27
**GISAID Nucleotide Query:** C897A, G22599C, -T23599, C23604G, -G28806T
**CovSpectrum Query:** Nextcladepangolineage:JN.1.13.1* & S:K679N
**Substitutions on top of JN.1.13.1:**
**Spike:** K679N (reversion)
**Nucleotide:** G22933A, G23599T (reversion)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.13.1_K679N.json?c=gt-S_679&gmax=25384&gmin=21563&label=id:node_6973804
<img width="1497" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2153acfc-181d-46a6-a26e-40306df79f36">

**Evidence**
These are all from the USA, mostly from New York (19) and New Jersey (6), but with one each from California and Texas. The earliest was collected on January 14, and 15/27 were collected on February 20 or later. They come from several different labs, including the US CDC, whose sequence are more reliable than any other lab in my experience. All are on the G22933A branch of JN.1.13.1, though one fails to show up with a G22933A GISAID search because it has dropout in that area (the one from Texas, EPI_ISL_18940730). 

I think there are other branches of BA.2.86 that also have the S:K679N reversion, but because this site is masked by Usher (as it has to be given the number of artifacts at that residue), it's very hard to locate them. This one was easier to find because so many came in the same upload and from the same region. There are probably even larger S:K679N branches out there though.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18848812, EPI_ISL_18856144, EPI_ISL_18868035,
EPI_ISL_18880654, EPI_ISL_18883859, EPI_ISL_18908908,
EPI_ISL_18920735, EPI_ISL_18933256, EPI_ISL_18933258,
EPI_ISL_18936945, EPI_ISL_18940730, EPI_ISL_18945972,
EPI_ISL_18945975, EPI_ISL_18945995, EPI_ISL_18952535,
EPI_ISL_18956697, EPI_ISL_18957703, EPI_ISL_18965865,
EPI_ISL_18978614, EPI_ISL_18978623, EPI_ISL_18978801,
EPI_ISL_18978870, EPI_ISL_18979100, EPI_ISL_18979153,
EPI_ISL_18979160, EPI_ISL_18979485, EPI_ISL_18979514,
</details>

**Comment by FedeGueli** [comment]
Please propose it @ryhisner

**Comment by FedeGueli** [comment]
> Please propose it @ryhisner

still around but it has clearly slowed down

**Comment by FedeGueli** [comment]
125

**Comment by aviczhl2** [comment]
208 seqs now.

**Comment by aviczhl2** [comment]
278 seqs now.

**Comment by FedeGueli** [comment]
It persists so please propose it

**Comment by FedeGueli** [comment]
317, Russia Nepal

**Comment by FedeGueli** [comment]
not fast but worth proposing it?

**Comment by ryhisner** [comment]
Sorry I missed the previous posts. Let me take a look and try to put together a proposal soon.

**Comment by DailyCovidCases** [comment]
Please propose it

**Comment by ryhisner** [comment]
I prepared a proposal for this, but I closed it immediately afterward. I don't think this is monophyletic. The query isn't strict enough. If you include C25680T, which is in all JN.1.13, it returns just 122 sequences. A few are fairly recent (two from August), but I'm not even sure if those are from the same lineage. I think it's best to close this issue.

**Comment by FedeGueli** [comment]
> I prepared a proposal for this, but I closed it immediately afterward. I don't think this is monophyletic. The query isn't strict enough. If you include C25680T, which is in all JN.1.13, it returns just 122 sequences. A few are fairly recent (two from August), but I'm not even sure if those are from the same lineage. I think it's best to close this issue.

Thx Ryan it happens all the time with old lineages sometimes also with relatively young ones.
