### ISSUE TITLE
XBB.1.16.24/HK.3 recombinant (4 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1436]
XBB.1.16.24--HK.3

Breakpoint between 13628 and 14855

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c6573853-5dda-4a29-800d-4bdc678820ad)

Additional mutations: 
G3562A, T22357C

G3562A from an XBB.1.16.24 branch
T22357C is private mutation

GISAID query: G3562A, T22357C,C29625T
No. of seq: 4(USA-CA, AZ)

First: EPI_ISL_18774868, 2023-12-15
Latest: EPI_ISL_18979476, 2024-2-22

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice297_genome_test_3393_2dfbc0.json?label=id:node_3189706)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/02876f4d-af06-4225-bf95-424f3e3a0dcc)

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
thx for this and the others
