### ISSUE TITLE
XDK.1 + ORF3a:S74F + S:F456L (1)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1438]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/264f2a01-721e-4e9c-82a9-81cc3ecd6239)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_186b7_333c90.json?c=gt-S_456

This is the first pirola with s:346t, s:572i, s:456L

Seq: 2024-02-06

OZ019713.1

Gisaid query: T22928C, C25613T, C25626T

**Comment by FedeGueli** [comment]
Thank you it was tracked in the original issue of XDK.1 : https://github.com/sars-cov-2-variants/lineage-proposals/issues/1407

**Comment by aviczhl2** [comment]
Despite being the first FLIRT, it is not spreading.
