### ISSUE TITLE
Sublineage of KP.2 (FLiRT) with S:Q1201K ( 6 sequences , 5 countries, 4 continents 0,5% samples collected worlwide in March)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1440]
i just noticed that fast growing KP.2 lineage has got also S:Q1201K (C25163A)  , 
this mutation is a one nuc mutation but it is usually accompanied by a silent mutation in the S:1200  Codon : (C25162A).
This combination is not new and has been spotted and discussed first by @ryhisner since 2023 or even before.
While this mutation has not suceeded in become fixated in circualting viruses , this time popped up in the fastest lineage on earth (apparently and as of today) KP.2 . 
All the 4 samples of KP.2 with this mutation have been collected in March scoring a 4/893 globally.
More interestingly these samples come from 4 countries dislocated in 3 continents.
Hence i propose it immediately.
Nextclade screening of the double nuc mutation:
<img width="444" alt="Screenshot 2024-03-15 alle 14 52 22" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f66bc0b5-28e9-4192-a919-6964cd31e991">

Defining mutations: KP.2 > C25162A, S:Q1201K (C25163A) 
Query: C25162A, C25163A, T3565C,G22599C
Samples: 4 
Countries: England, US (California), India (via GBW), Canada
IDs: EPI_ISL_18974372, EPI_ISL_18975453, EPI_ISL_18980156,
EPI_ISL_18983461
Tree: 
<img width="1160" alt="Screenshot 2024-03-15 alle 14 47 23" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/90dfaafa-dfea-47f1-8dc7-9d017b6a7f14">
<img width="1159" alt="Screenshot 2024-03-15 alle 14 47 47" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ed43c03a-9a20-4052-8bb0-bc5cb793cd47">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_35acd_44e770.json?c=gt-nuc_22599,22928,7113,3565&gmax=23928&gmin=2565&label=id:node_6943906

**Comment by aviczhl2** [comment]
+1 GBW from Brazil
+1 GBW-H10, country unknown

**Comment by FedeGueli** [comment]
> +1 GBW from Brazil +1 GBW-H10, country unknown(not the same as other GBWs as it is collected on 3-7 and sampled in NJ)

Thank you it seems exploding , lets see if more samples will come in

**Comment by aviczhl2** [comment]
Designated KP.2.1
