### ISSUE TITLE
Another JN.1+S:S31F(59 seqs, 3 countries, 9 with S:R346T)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1445]
JN.1+C24023T+C21654T(S:S31F)

GISAID query:C24023T,C21654T,C18894T
No. of seqs: 54(South Korea 53 USA 1)
53 on GISAID , the USA seq not.
GISAID query for S:R346T branch: C24023T,C21654T,C18894T,G22599C (9 seqs)

First: EPI_ISL_18687243, 2023-11-21
Latest: EPI_ISL_18982666, 2024-2-22

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice158_genome_test_f417_5a8810.json?label=id:node_6993236)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/004d10e9-7c17-416b-843c-3e9b410cfffb)

**Comment by FedeGueli** [comment]
the r346T now added as branch 65 into #1089 too

**Comment by aviczhl2** [comment]
59, Japan

**Comment by FedeGueli** [comment]
Please propose it highlighting the 346T sublineage as here.
