### ISSUE TITLE
LF.1.1 (JN.1.16.1+Orf1a:A1268T,S2103F+S:P1263L) with a sub branch with S:S31del (16)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1448]
LF.1.1 = [JN.1.16.1+G4067A,C6573T(Orf1a:A1268T,S2103F)+C18912T+C16551T,C25350T(S:P1263L)]
GISAID query: C18912T,C16551T,C25350T
GISAID query for S:31del branch: C18912T,C16551T,C25350T,del21653 (@FedeGueli )
No. of seqs: 6(USA 5(4 from Qatar, 1 from Turkey) Sweden 1)

First: EPI_ISL_18882963, 2024-1-28, Sweden
Latest: EPI_ISL_18965360, 2024-2-25, USA from Qatar

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_10d2c_79ec60.json?label=id:node_6964194)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b4dd9391-ccd5-4ea2-85e9-857d12bc4e10)

Edited on 4/26:
It seems there is a branch with S:S31Del 
Query: C18912T,C16551T,C25350T,del21653
Samples 3 : GBW ( 1 From Germany, 1 From Egypt, 1 duplicate)

**Comment by FedeGueli** [comment]
+1 Denmark

**Comment by aviczhl2** [comment]
+1 Switzerland

**Comment by aviczhl2** [comment]
+2 USA from UAE

**Comment by aviczhl2** [comment]
+1 France

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
16 now with Airport samples from travellers from Germany and Egypt.

**Comment by FedeGueli** [comment]
The last airport samples from Germany and Egypt got also S:S31del

**Comment by FedeGueli** [comment]
+1 S.Korea (new country)

**Comment by FedeGueli** [comment]
one more with S:S31del from Canada

**Comment by FedeGueli** [comment]
22 from 13 countries

**Comment by FedeGueli** [comment]
24 , +2 ( 1 with S:S31del >> 5 tot)

**Comment by FedeGueli** [comment]
please propose it when reaches 40

**Comment by FedeGueli** [comment]
+1 from new Country (Spain) with S:S31del

**Comment by FedeGueli** [comment]
Designated LF.1.1 via https://github.com/cov-lineages/pango-designation/commit/5688ef9c17657bf4746d4df6d1cd3cb93d8d5d97

**Comment by FedeGueli** [comment]
11 now. @aviczhl2 please propose it. (even if it will never be designated)

**Comment by aviczhl2** [comment]
@AngieHinrichs, as there's actually is a base selection phase in usher, I think it can detect deletions (but not exactly accurate), is it possible to apply an urgent fix that includes S:31-(del21653_21655) as a separate node on tree? There are many S:31- branches now and they are quite vital.  

No need to work on other deletions, only S:31-.

**Comment by FedeGueli** [comment]
16

**Comment by aviczhl2** [comment]
31del sub-branch is designated LF.1.1.1
