### ISSUE TITLE
XBB.1.16 Sublineage with S:F456L, ORF1a:H3581Q (17 seq, USA, CA—July 4)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#145]
### **Description**
**Sub-lineage of:** XBB.1.16.4
**Earliest sequence:** 2023-5-9, USA, California — EPI_ISL_17764095, EPI_ISL_17764096
**Most recent sequence:** 2023-5-18, USA, California — EPI_ISL_17764105, EPI_ISL_17764106
**Countries circulating:** USA (11)
**Number of Sequences:** 11
**GISAID AA Query:** Spike_F456L, Spike_T678I, NSP2_T256I
**GISAID Nucleotide Query:** G16485A, A22769C, T22930A
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16.4* & [2-of: G16485A, A22769C, T22930A]
**Substitutions on top of XBB.1.16.4:**
**Spike:** F456L
**ORF1a:** T436I, H3581Q (NSP2_T256I, NSP6_H12Q)
**Nucleotide:** C1572T, G6205A, C11008A, T18918C, G16485A, A22769C, T22930A
 
**Phylogenetic Order of Mutations:**
C11008A (ORF1a:H3581Q), T18918C  **→**
G6205A **→**
C1572T **→**
G16485A, A22769C, T22930A (S:F456L)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16.4_F456L.json?c=gt-S_456&label=id:node_6653791

<img width="1401" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7e59ff19-8385-4346-8494-13e287d7750a">

**Evidence**
S:F456L is a proven winner, and XB.1.16* is still the fastest lineage around. Not much else to say. If this becomes a proper proposal I'll try to add some more commentary.
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17393953, EPI_ISL_17482521, EPI_ISL_17492350, EPI_ISL_17511454, EPI_ISL_17527942, EPI_ISL_17558810, EPI_ISL_17558838, EPI_ISL_17629851, EPI_ISL_17646188, EPI_ISL_17648938, EPI_ISL_17649192-17649193, EPI_ISL_17678344, EPI_ISL_17678664, EPI_ISL_17764095-17764101, EPI_ISL_17764104-17764107
</details>

**Comment by FedeGueli** [comment]
16 now all from Marin county California, very weirdly no other samples have been uploaded with this county lable to Gisaid.
And consider that is a very small 200K county. 
From their dedicated page it seems there is some oubreaks in long term facility:
![Schermata 2023-06-13 alle 11 07 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/abeb33c6-b912-4266-93f3-5b8383a1c770)
https://coronavirus.marinhhs.org/covid-19-status-update-06092023

**Comment by FedeGueli** [comment]
17. from another county. Solano.

**Comment by FedeGueli** [comment]
no new sequence but lets wait  abit being a very delimited outbreak: if it has seeded outside the county it could take some time before showing up.

**Comment by ryhisner** [comment]
Seems likely this has been extinguished. It it reappears, we can always reopen, but better to close now I think.
