### ISSUE TITLE
JN.1.7* with S:704L  cluster in Ireland (40)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#1452]
Mutations on top of JN.1*: T9757C,C15960T, A21137G, C23673T
Gisaid Inquiry: T22896A,A22629,C23673T,T9757
First Sequence: EPI_ISL_18984051 Dublin, Ireland 2024-02-06
Second Sequence: EPI_ISL_18994147 Dublin, Ireland 2024-02-28
Last Sequence: EPI_ISL_18994168 Dublin, Ireland 2024-03-13
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3099f_bf7ce0.json?f_userOrOld=uploaded%20sample&label=id:node_5540100
<img width="974" alt="Screenshot 2024-03-21 at 5 05 05 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/2f43d76d-9325-4926-9e4c-65e07f481972">
Note: it reached 16/46 since the second sequence in Ireland, and while nearly all seqs are in Dublin, the capital, there is one sequence in Galway indicating possible spread, and we could expect it to go to UK or mainland Europe soon given its high prevalence now.
Another thing is that it seemed to got some apparent gap issue that's fooling nextclade, usher seemed to ignore it already and just place them in a tree.
<img width="1222" alt="Screenshot 2024-03-21 at 5 06 49 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/fb43a9fe-21f2-4053-b963-ceb3e5cb8c6d">

**Comment by krosa1910** [comment]
S704L had been relatively successful in XBB*, maybe the most successful S2 mutation. It is convergently gained by XBB.1.5.70.1*, HV.1.6.1*, JG.3* and GA.4*. It also appeared in XDD.1* which is essentially JN.1* spike. jbloom lab once mentioned it as a mutation increasing ACE2 binding, so like T572I it could grow a bit within JN.1*

**Comment by FedeGueli** [comment]
19 now

**Comment by FedeGueli** [comment]
40, but has decreased its growth, closing it
