### ISSUE TITLE
JN.1.46+S:A123S(48 seqs. 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1454]
JN.1.46 [T4885C,C9611T(Orf1a:L3116F)],G21929T(S:A123S)

GISAID query: C9611T,G21929T,C18894T
No. of seqs: 39(Mexico 1 Canada 1 South Korea 1 USA 36)

First: EPI_ISL_18621519, USA, 2023-11-26
Latest: EPI_ISL_18994591, USA, 2024-2-27

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice111_genome_test_17fd1_bfa670.json?label=id:node_6906952)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8be219f4-bf49-4200-a7d6-8d6c440263eb)

**Comment by FedeGueli** [comment]
parental lineage designated JN.1.46

**Comment by FedeGueli** [comment]
first sample from March

**Comment by FedeGueli** [comment]
48, no recent sequence closing it
