### ISSUE TITLE
JN.1/XBB.1.16 recombinant(18 seqs, UK, 7 with S:S704L)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1455]
There seems to be a JN.1/XBB.1.16 recombinant starting to acquire new spike mutations. 

JN.1--XBB.1.16

Breakpoint between 26834 and 27809

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/298d9d08-20ef-45b5-a2a6-c35cdced4765)

Additional mutations: T9964C,C15237T

 T9964C,C15237T from a JN.1 branch

GISAID query:  T9964C,C15237T, C29386T
No. of seqs: 12(UK)

First:EPI_ISL_18707847, 2023-12-21
Latest: EPI_ISL_18993609, 2024-3-11

GISAID query for Orf8:E64D, S:S704L branch: T9964C,C15237T, C29386T,C23673T

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice249_genome_test_17fd1_bfa720.json?label=id:node_6971398)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b2e09486-ed0c-4d7c-96a7-78b6a9847723)

**Comment by FedeGueli** [comment]
The never ending story between recombinants and S:704L. 
I m starting wondering if it is not a mutation tha compensates some sort of disequilibrium after gaining mutations.
It started to pop together with FLip and in recombinants, while before it was seen in BA.2.12 , maybe BA.2.12 is the only one time it came as first mutation before evolving?

**Comment by aviczhl2** [comment]
> The never ending story between recombinants and S:704L. I m starting wondering if it is not a mutation tha compensates some sort of disequilibrium after gaining mutations. It started to pop together with FLip and in recombinants, while before it was seen in BA.2.12 , maybe BA.2.12 is the only one time it came as first mutation before evolving?

Yeah it is a very common mutation, especially in recombinants.

**Comment by aviczhl2** [comment]
> The never ending story between recombinants and S:704L. I m starting wondering if it is not a mutation tha compensates some sort of disequilibrium after gaining mutations. It started to pop together with FLip and in recombinants, while before it was seen in BA.2.12 , maybe BA.2.12 is the only one time it came as first mutation before evolving?

The S704L branch doubles to 4.
