### ISSUE TITLE
JN.1.7.2+S:R78M(35 seqs, UK, 17 with S:Y269H, 15% Scotland)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1456]
This branch was only a small cluster a few days ago, but suddenly expands in Scotland.

JN.1.7.2+G21795T(S:R78M)

GISAID query: G21795T,G18155T
No. of seqs: 35(UK, England 1 Scotland 34)

First: EPI_ISL_18735768, 2023-12-14
Latest: EPI_ISL_18990189, 2024-3-7

6/39=15% in Scotland 2024.3 seqs, all from the S:Y269H branch. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_17fd1_bfa5f0.json?branchLabel=Spike%20mutations&label=id:node_7000084&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/086c5a09-6c2f-4354-96bd-96d8bcb621fb)

Query for S:Y269H : A11600G,C9073T
Samples : 17

**Comment by FedeGueli** [comment]
Yeah this one was the one i posted in the groups, to me likely just clusters but nice to track it publicly.

**Comment by FedeGueli** [comment]
Added a query for the 269H branch that gave me 17 :A11600G,C9073T

**Comment by FedeGueli** [comment]
likely clusters

**Comment by aviczhl2** [comment]
No new seqs
