### ISSUE TITLE
KP.1+Orf8:F3S(73 seqs, 4 countries, 3 with S:R346T, 18% Hawaii)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1457]
KP.1+T27901C(Orf8:F3S)

GISAID query: T27901C,A24819G
No. of seqs: 29(USA 28 Australia 1)

First: EPI_ISL_18866280, Australia, 2024-1-15
Latest: EPI_ISL_18994547, USA, 2024-2-28

This is 23/308=8% of Hawaii seqs in 2024-2, up from 3/692=0.4% in 2024-1.

Query for FLIRT branch : T27901C,A24819G, G22599C  (Edited)
Samples: 3
EPI_ISL_19025401, EPI_ISL_19036829, EPI_ISL_19038978,

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice10_genome_test_17fd1_bfa600.json?label=id:node_6947552)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b382ce29-c530-4b3b-bb06-366a232dac3f)

**Comment by FedeGueli** [comment]
Thx @aviczhl2 

@ryhisner @peacockflu: this T27901C resembles me the Orf8:K2T (A27898C) of XBC could it impact the expression of Orf8?

**Comment by aviczhl2** [comment]
45, Japan

**Comment by aviczhl2** [comment]
17/159=11% in Hawaii seqs after 2-15

**Comment by FedeGueli** [comment]
One sample from Hawaii is FLiRT! :
<img width="1159" alt="Screenshot 2024-04-02 alle 23 54 32" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0b548891-fb1e-4517-8b1c-94008ff04efb">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1c78b_c759b0.json?c=gt-S_346&gmax=25384&gmin=21563&label=id:node_6958911

**Comment by aviczhl2** [comment]
73, Canada, 3 with S:R346T(FLiRT)

**Comment by aviczhl2** [comment]
12/68=18% in seqs after 2024-3-1.

**Comment by FedeGueli** [comment]
Please propose it
