### ISSUE TITLE
KP.2.3 (S:H146Q, Orf3a:K67N) with S:S31del (34 sequences, 15 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1459]
KP.2.3 [S:H146Q, Orf3a:K67N,Orf3d:E24*(C22000A,G25593T)] + C28714T,del21653_21655(S:S31del)

GISAID query: C22000A,G25593T,G24872T
No. of seqs: 6(USA, 2 from France, 2 from South Korea, 2 from UAE)

First: EPI_ISL_18983764, USA from UAE, 2024-3-6
Latest: EPI_ISL_18999293, USA from France, 2024-3-12

GISAID query for  S:S31del branch: del21653_21655, C22000A,G25593T  

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_24bc3_d8e990.json?label=id:node_11353197)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/51807a76-d1fb-4272-ad92-b9352500f5ca)

**Comment by FedeGueli** [comment]
Great catch thank you!

@ryhisner would you like to comment here on the  N Glycan ?

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by aviczhl2** [comment]
+3 UK(only 1 on GISAID)

**Comment by aviczhl2** [comment]
19, Netherlands

**Comment by aviczhl2** [comment]
+2 Canada

**Comment by FedeGueli** [comment]
please propose it

**Comment by FedeGueli** [comment]
Please propose it now 24 one of the fastest apparently

**Comment by FedeGueli** [comment]
Already designated! KP.2.3 via https://github.com/cov-lineages/pango-designation/commit/b0a0b070f319135b080a839623db6496789a7744

**Comment by aviczhl2** [comment]
22 in USA, UK, New Zealand, Canada, UAE(via GBW), Qatar(GBW), Argentina(GBW), India(GBW), France(GBW), South Korea(GBW)

**Comment by FedeGueli** [comment]
pls propose it

**Comment by FedeGueli** [comment]
34 please propose it
