### ISSUE TITLE
XBB.1.5.24+S:L216F in Mauritius (125 seqs, 9 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#146]
XBB.1.5.24+S:L216F(C22208T)
GISAID query: C2710T,C22208T,T23018C,G27915T

No. of seqs: 98(South Korea 1 Sweden 1 Reunion 1 UK 2 Mauritus 93)

First seq: EPI_ISL_17245028, Mauritus 2023-1-30
Latest: EPI_ISL_17741074, South Korea 2023-5-10

92/845 of Mauritius seqs starting from 2023-2-1.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_3b2a0_e8e110.json?f_userOrOld=uploaded%20sample&label=id:node_6995152)

<img width="1401" alt="Screenshot 2023-06-06 at 12 50 56" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/375c2a74-6277-4678-af78-3eea16b01216">

**Comment by aviczhl2** [comment]
detected in Italy and Croatia.

**Comment by aviczhl2** [comment]
+2 South Africa

**Comment by aviczhl2** [comment]
111 seqs, France

**Comment by FedeGueli** [comment]
It seems reducing its share in the coutnry where it emerged lets recheck it when the may picture will be complete.
