### ISSUE TITLE
HN.5*(FL.1.5.1.5*) x FY.5.1.1+S:R683Q recombinant (3 seqs in St. Petersburg, Russia)  

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1461]
Description:
Recombinant of: HN.5* (FL.1.5.1.5*, XBB.1.9.1.1.5.1.5) and FY.5.1.1 (XBB.1.22.1.5.1.1*) +S:R683Q and N:T49I branch
Breakpoint: nuc:6415-11956, Before = HN.5*, After = FY.5.1.1*)
Earliest sequence: 2024-01-26 (St. Petersburg, Russia-EPI_ISL_18105656)
Most recent sequence: 2024-02-05 (St. Petersburg, Russia-EPI_ISL_18284946)
Countries circulating: Russia (3)
GISAID Nucleotide Query: G3242A, A6415C, A22161G, G22302A

Usher Tree:
![联想截图_20240323160805](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/043d7c2d-2669-4a08-80d2-eaf01b68238b)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c1e4_c064d0.json
It is also interesting that the FY.5.1.1* part gets S:R683Q, which destroys FCS and also popular in some JN.1* branches recently.

Genomes:
EPI_ISL_18973797, EPI_ISL_18973946, EPI_ISL_18974024

**Comment by aviczhl2** [comment]
New Russian batch doesn't include this.
