### ISSUE TITLE
JN.1.20+2-nuc S:P1143F( 25 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1464]
This is the 2nd time I see this 2-nuc S:1143F. It follows a S:1143P->L(BA.2.86)->F path.
Interestingly, this is not a single South Korean seq, but also detected in 2 GBW seqs from Qatar. 
JN.1.20+G19563A,C21057T+C24989T(S:L1143F)

GISAID query: G19563A,C21057T,C24989T
No. of seqs: 7(USA 3(from Qatar), South Korea 4)

First: EPI_ISL_18945693, USA from Qatar, 2024-2-19
Latest: EPI_ISL_19001415, South Korea, 2024-2-26

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice12_genome_12269_edcdc0.json?label=id:node_6931952)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/21a1d84f-0331-4ed5-9752-e69f79801b23)

**Comment by FedeGueli** [comment]
S:P1143L got lost in XDN and XDQ (if m not wrong) both going quite well then, i suspect it is neutral or deleterious so maybe this could have some effect then.

**Comment by aviczhl2** [comment]
No new seqs
