### ISSUE TITLE
XDK+Orf1a:T708I, S:F456L(13 seqs, 2 countries, 10 with S:A260V)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1467]
XDK+C25626T+C2388T(Orf1a:T708I)+ T22928C(S:F456L)

GISAID query:C2388T, T22928C,C25626T(edited)
No. of seqs: 6(France)

First: EPI_ISL_18913117, 2024-1-24
Latest: EPI_ISL_19006283, 2024-3-11

GISAID query for S:A260V branch: C22341T,C3510T,C18646T, T22928C(4 seqs)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_10569_16e110.json?label=id:node_11364027)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a8301118-6fcb-40b7-b866-ddf2d061802f)

**Comment by aviczhl2** [comment]
+6 on S:A260V branch

**Comment by FedeGueli** [comment]
It is weird that oldest sequences of this  were already with S:A260V ,

**Comment by aviczhl2** [comment]
The tree splits and one more seq comes from Luxembourg
