### ISSUE TITLE
JN.1.32 (S:T572I) with S:S704L (Or JN.1.34+S:T572I) recent cluster in Wales/England (12)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1469]
Just noticed a cluster of Jn.1.32 with additional S:S704L mutation.
Put here for short tracking of it
Defining mutations: JN.1.32 > S:S704L (C23673T) ,A24673G
Query: C23673T ,A24673G,T3565C
Samples : 4 on Gisaid 9 on Usher
<img width="352" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/14481c8a-d1dc-4762-8f18-11ffe329c2c8">

Tree:
<img width="1168" alt="Screenshot 2024-03-25 alle 14 44 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/97058e4a-55ba-49fe-ab28-6bb31d95d859">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_36659_17e4c0.json?c=gt-S_704&gmax=25384&gmin=21563&label=id:node_6958613

**Comment by aviczhl2** [comment]
Or JN.1.34+S:T572I

**Comment by FedeGueli** [comment]
now 8 on Gisaid
