### ISSUE TITLE
XBB.1.5 and XBB.1.9.2 branches with S:L1244F (53 seqs, 5 countries / 26 seqs, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#147]
### Branch 1: 

**Defining mutations:** _(On top XBB.1.5's T17124C > T23018C branch)_ > G21668A(S:V36I) > C6196T > C20823T > C25292T(S:L1244F) >
**Query:** G21668A, C25292T [53 seqs]
**Earliest seq:** 2023-02-18 (EPI_ISL_17141723, Michigan or EPI_ISL_17075504, Japan)
**Latest seq:** 2023-05-20 (EPI_ISL_17762007, South Korea)
**Sampled in Countries:** South Korea (47), Japan (2), Australia (2, WA, NSW), China (1, Shanghai), USA (1, Michigan)

<details><summary>Genomes: </summary>
EPI_ISL_17075504, EPI_ISL_17141723, EPI_ISL_17150370, EPI_ISL_17213370, EPI_ISL_17294885, EPI_ISL_17375152,
EPI_ISL_17473616, EPI_ISL_17473732, EPI_ISL_17511403, EPI_ISL_17538436, EPI_ISL_17538796, EPI_ISL_17538957,
EPI_ISL_17538991, EPI_ISL_17539050, EPI_ISL_17539183, EPI_ISL_17539339, EPI_ISL_17561478, EPI_ISL_17563233,
EPI_ISL_17563419, EPI_ISL_17563954, EPI_ISL_17563999, EPI_ISL_17564130, EPI_ISL_17604230, EPI_ISL_17604288,
EPI_ISL_17604516, EPI_ISL_17604651, EPI_ISL_17604943, EPI_ISL_17605197, EPI_ISL_17646990, EPI_ISL_17647044,
EPI_ISL_17647162, EPI_ISL_17647200, EPI_ISL_17647328, EPI_ISL_17647370, EPI_ISL_17647581, EPI_ISL_17648578,
EPI_ISL_17677762, EPI_ISL_17690634, EPI_ISL_17691123, EPI_ISL_17696788, EPI_ISL_17723325, EPI_ISL_17723462,
EPI_ISL_17723648, EPI_ISL_17723969, EPI_ISL_17724002, EPI_ISL_17724130, EPI_ISL_17730308, EPI_ISL_17730398, EPI_ISL_17730399, EPI_ISL_17730608, EPI_ISL_17730756, EPI_ISL_17741113, EPI_ISL_17762007
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14fc4_ebcac0.json?c=gt-S_1244&f_userOrOld=uploaded%20sample&showBranchLabels=all
overview from XBB.1.5 polytomy
![XBB 1 5 on T17124C + S_L1244F Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/9abb395b-cb46-44ce-b325-c2fb0668cea5)
details
![XBB 1 5 on T17124C + S_L1244F Detailed](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f6a56bed-2ab7-43bf-8b23-a1014b073eb3)

**Trivia:**
- The parent branch, XBB.1.5 on undesignated S:V36I (query: T17124C, G21668A, -T10204C) has at least 334 seqs
- S:V36I was on @FedeGueli 's XBB.1.5 spike diversity tracker cov-lineages/pango-designation#1510

---

### Branch 2: 

**Defining mutations:** _(On top of XBB.1.9.2's A27507C) >_ G2659T(ORF1a:K798N) > C8752T > T6688C > A21137G(ORF1a:K2557R) > C25292T(S:L1244F), C29370T(N:T366I) > 
**Query:** G2659T, C25292T [24 seqs]
**Earliest seq:** 2023-03-13 (EPI_ISL_17346273, France)
**Latest seq:** 2023-05-18 (EPI_ISL_17711713, Spain)
**Sampled in Countries:** France (22), Spain (1), Switzerland (1)

<details><summary>Genomes: </summary>
EPI_ISL_17346273, EPI_ISL_17422108, EPI_ISL_17480618, EPI_ISL_17490171, EPI_ISL_17490173, EPI_ISL_17522958,
EPI_ISL_17564407, EPI_ISL_17564797, EPI_ISL_17587080, EPI_ISL_17615144, EPI_ISL_17615218, EPI_ISL_17657541,
EPI_ISL_17657576, EPI_ISL_17670794, EPI_ISL_17670872, EPI_ISL_17673709, EPI_ISL_17711713, EPI_ISL_17715825,
EPI_ISL_17715842, EPI_ISL_17731645, EPI_ISL_17731654, EPI_ISL_17743340, EPI_ISL_17743385, EPI_ISL_17764256,
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_5753_eb4700.json?c=gt-S_1244&f_userOrOld=uploaded%20sample&showBranchLabels=all
overview from XBB.1.9.2 polytomy
![XBB 1 9 2+S_L1244F_Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/025226d5-7f27-461c-943e-806c0d49e571)
details
![XBB 1 9 2+S_L1244F_Detail](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/576765fc-f093-4d34-b602-5998ff4e199b)

**Trivia:**
- Parent branch G2659T(ORF1a:K798N) on XBB.1.9.2's polytomy (query: A27507C, G2659T) has 870 seqs.
- ORF1a:K798N is one of the definition mutations of BA.2.3.17
- ORF1a:K2557R is one of the definition mutations of AY.126, BN.1.4.2, BE.1.4.2, BF.42, XBB.1.30
- N:T366I is one of the definition mutations of EE.1(BQ.1.1.4.1), FR.1(BN.1.2.3.1)

**Comment by FedeGueli** [comment]
They seem slow closing this for now. Ping me if they will be back.

**Comment by Over-There-Is** [comment]
Branch 2 is also detected in Algeria.
