### ISSUE TITLE
JN.2/XDA recombinant with additional S:R346T(8 seqs, Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1471]
One singlet in #991 gets company.

JN.2--XDA

Breakpoint between 23424 and 23603(between S:622 and S:680)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a2d75e12-81ca-40a9-91d0-95dcf1347ff1)

Additional mutations: T1030C, C21301T,G22599C
S:R346T
Orf1b:P2612S

T1030C, C21301T from a JN.2 branch.
G22599C is private mutation.

GISAID query: C28471T,A2127G,T1030C
No. of seqs: 2(Japan)

EPI_ISL_18854347, 2024-1-16
EPI_ISL_19005974, 2024-1-31

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_10569_16e120.json?label=id:node_11363978)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/14a7fc07-02d9-4984-bbca-2f2f2bc824a7)

**Comment by aviczhl2** [comment]
@FedeGueli It is a mixed spike, 0~621 is JN.2+S:R346T, 622~end is XDA.

**Comment by corneliusroemer** [comment]
It's now 7 sequences - quite an interesting recombinant as it's effectively like XDQ + S:R346T, S:P681H, S:A701V (and a branch with S:A263V)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/cf6ed74b-09ff-4a1d-9567-a41a3cafa61b)

These are all quite possibly fitness increasing compared to XDQ which is doing ok even without the extra 475V of XDQ.1


![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/6af3a8c6-ef80-486a-9f3a-cc5e2c5301eb)

**Comment by corneliusroemer** [comment]
Just rediscovered this on the Usher tree - designated XDW as it's clearly circulating and has an interesting genotype.

How are you certain that XDA is the donor rather than XDA's donor HN.5? Does it share a mutation with XDA only @aviczhl2? In general it's easier to remember the genotype if one refers to the non-recombinant donor (if possible) as recombinants are hard to remember!

**Comment by aviczhl2** [comment]
> Just rediscovered this on the Usher tree - designated XDW as it's clearly circulating and has an interesting genotype.
> 
> How are you certain that XDA is the donor rather than XDA's donor HN.5? Does it share a mutation with XDA only @aviczhl2? In general it's easier to remember the genotype if one refers to the non-recombinant donor (if possible) as recombinants are hard to remember!

XDA is more widespread than its specific HN.5 donor I guess?
