### ISSUE TITLE
XBB.1.5* saltation seq with 18 Spike aa mutations and 40 nuc mutations (WA, Australia, singlet collected in Mar 19, 2024)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1476]
mutations on top of XBB.1.5* (GISAID and clades-nextstrain classify as XBB.1.5.20*, Usher classifies as XBB.1.5.17*):

Spike: I19T (rev), S31F, F32S, K150N, R158S, S255P, A264D, P445S, Y453F, G476S, K478R, N487D, T500N, T553N, E554K, T572I, S939F, C1247F 

ORF1a: V5I, T866I, T2936I, L2969F, L3588F, I4098V

ORF1b: A167V, A1643V

ORF7: Q62K

ORF9b: G31R

Usher Tree:
![联想截图_20240327165619](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/59023c9f-c5c2-49ac-a715-fac1b5480ebc)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b6f3_3da7d0.json

Some Spike aa mutations are coupled (S:S31F-F32S, G476S-S477N-T478R, T500N-N501Y, T553N-E554K). Moreover, some aa mutations are convergent to some JN.1* branch (S:A264D, S:E554K, S:T572I, S:S939F). 

Genomes:
EPI_ISL_19013418

Putative queries:(Edited)
C920T, T1474A,
or
A22920T, A23021G

**Comment by FedeGueli** [comment]
Two queries added : C920T, T1474A  or  A22920T, A23021G

**Comment by FedeGueli** [comment]
Not MOV related it seems 
<img width="902" alt="Screenshot 2024-03-27 alle 10 18 50" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3315dbae-4a70-43d3-a38d-19ff7d4df527">

**Comment by ujoshi4** [comment]
T553N is crazy

**Comment by aviczhl2** [comment]
No further seqs
