### ISSUE TITLE
JN.1+Orf1b:S638I+Orf9b:R47H(54 seqs, 4 countries, 3.5% Hubei)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1478]
JN.1+T18471C+G15380T(Orf1b:S638I)+G28423A(Orf9b:R47H)

GISAID query: T18471C,G15380T,G28423A
No. of seqs: 25(Japan 2 Singapore 1(from China) China 22(Hubei,Sichuan, Chongqing, Shanghai, Anhui, Fujian))

First: EPI_ISL_18947850, Sichuan, 2024-1-22
Latest: EPI_ISL_19013725, Hubei, 2024-3-20

10/282=3.5% of Hubei seqs in 2024.3

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_14833_412960.json?label=id:node_6965929)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/4c032c51-65d5-427c-96f0-3e2b3cd6a4e9)

**Comment by FedeGueli** [comment]
great catch , it seems quite fast
<img width="617" alt="Screenshot 2024-03-27 alle 18 49 11" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c8ce3d0f-0e65-499a-b5ea-6b8ef1376da0">

**Comment by FedeGueli** [comment]
@ryhisner what do you think of this orf9b mutation? asking you as sworld authority on that ;)

**Comment by aviczhl2** [comment]
52, USA
