### ISSUE TITLE
One more JN.1+S:F59S(99 seqs, 11 countries, 5 with S:R346T)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1479]
JN.1+C25566T+C4570T,C6941T+T21738C(S:F59S)

GISAID query: T21738C, C4570T,C6941T
No. of seqs: 22(China 21(Anhui, Henan, Heilongjiang, Fujian, Liaoning, Hubei) Denmark 1)

First: EPI_ISL_18857569, Heilongjiang, 2024-1-6
Latest: EPI_ISL_19013743, Hubei, 2024-3-20

6/158 of Heilongjiang seqs since 2024-2.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14833_412960.json?gt=S.59S&label=id:node_7007788)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e5fcc206-75d0-4ef6-bb4a-987b9fbac080)

**Comment by aviczhl2** [comment]
Also in Shanxi

**Comment by aviczhl2** [comment]
54, USA

**Comment by FedeGueli** [comment]
LEts wait a bit more to understand Dynamics in China once FLiRT hitting there. ( even if it could be that previous FLiP wave maybe crossprotects better than other kind of immunity )

**Comment by FedeGueli** [comment]
slowing down a lot

**Comment by aviczhl2** [comment]
73, Spain

**Comment by FedeGueli** [comment]
+1 Thai

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by aviczhl2** [comment]
87, Portugal, Netherlands

**Comment by aviczhl2** [comment]
94, UK

**Comment by FedeGueli** [comment]
4 samples with S:R346T. 

Am i wrong but 59X is a feature of lineages with 346T ?

**Comment by aviczhl2** [comment]
> 4 samples with S:R346T.
> 
> Am i wrong but 59X is a feature of lineages with 346T ?

It can emerge independently.

**Comment by FedeGueli** [comment]
> > 4 samples with S:R346T.
> > Am i wrong but 59X is a feature of lineages with 346T ?
> 
> It can emerge independently.

I was meaning that it is beneficial especially when 346T is there

**Comment by aviczhl2** [comment]
99, Ireland, South Korea

**Comment by FedeGueli** [comment]
Still no samples from July and few from June. lets wait a bit more before closing iit

**Comment by FedeGueli** [comment]
only one recent sample from July
