### ISSUE TITLE
XCD: XBB.1.5 (or XBW?) with S:R214H, S:T478I, N:E136D (13 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#148]
While checking #72 routinely, I found another strange cluster.

**Defining mutations:** _(suppose it is from XBB.1.5's T10204C >)_ ORF6:L61D_rev (C27382G_rev, T27383A_rev, C27384T_rev) > C10204T_rev > C27259A_rev > C27889T, G28681T (N:E136D) > G26275A_rev (E:A11T_rev), G26529A_rev (M:N3D_rev), C28312T (ORF9b:P10F) > T25416C_rev, T27915G_rev (ORF8:*8G_rev) > C17124T_rev, T18006C, A19173G, G22203A (S:R214H), A22995T (S:T478I), G28077T (ORF8:V62L), C28657T > 

**Query:** G22203A, C22995T, G28681T
**Earliest seq:** 2023-01-26 (EPI_ISL_17683933, Indonesia)
**Latest seq:** 2023-05-25 (EPI_ISL_17742133, Australia)
**Sampled in Countries:** Indonesia (6), South Korea (5), Australia (1, NSW), USA (1, Virginia)

**Genomes:** EPI_ISL_17647594, EPI_ISL_17647595, EPI_ISL_17647596, EPI_ISL_17723340, EPI_ISL_17723346, EPI_ISL_17742133, EPI_ISL_17716667, EPI_ISL_17736554, EPI_ISL_17736565, EPI_ISL_17683903, EPI_ISL_17683933, EPI_ISL_17736545, EPI_ISL_17736560

**UShER:**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3dd43_ed0b40.json?f_userOrOld=uploaded%20sample

Overview from XBB.1.5 polytomy:
![Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d10bc529-5c3f-450c-a02d-d45e7f414425)

according to the tree, right from there it reverts ORF6:61 back to D (C27382G > T27383A > C27384T), and then there are many more reversions follows: C10204T > C27259A >, which is quite unlikely, it would be easier to be explained as some XBB.1.5 × BQ.1 recombinant.

Detailed view from C27889T, G28681T(N:E136D) branch
![Detailed](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0192eec5-9cac-4634-a1b6-2d78b7f7d1d8)

Now here's the tricky part, UShER finds a cluster that does dot have S:R214H, S:T478I as XBW, so is this proposed cluster a sub-branch of XBW or another XBB.1.5 × BQ.1 recombinant? Help needed.

**Comment by FedeGueli** [comment]
![Schermata 2023-06-06 alle 10 04 16](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/010dba5f-171a-43fe-b282-fcd7eca3c44d)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XBW*&aaMutations1=S%3AT478I%2CS%3A214H&analysisMode=CompareEquals&
![Schermata 2023-06-06 alle 10 05 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7681476a-77a0-4903-a74e-8d24a79b6d54)

To me it is a new recombinant cause XBW has T17124C this one has T instead.


Please propose in the main page.

**Comment by FedeGueli** [comment]
To be clear this lineage have M:D3N :
![Schermata 2023-06-06 alle 17 30 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/66404236-785c-42ef-bdb3-a04886b4e68f)

I did a bit of analysis on the putatitve parental lineages:
I looked at the putatitve donors, but first to clarify the proposal:
This is XBB.+486P until maximum E:10 ( 26272) and then from 26272 to end is BQ*

I think i have identified the BQ.1 side parent : looking at Bq.1 from 2023 carrying both Orf8:V62L and N:P365L i found just two sequences from Indonesia belonging to BQ.1.1.25 (EPI_ISL_17683939
EPI_ISL_17683936) As shown below they have no difference in the recombinant side to the lineage proposed here:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AT478I%2CS%3A214H&aaMutations1=Orf8%3AG8*&nextcladePangoLineage1=XBB.1*&nucMutations2=C28312T%2CC28657T%2CG28681T%2CC29367T&nextcladePangoLineage2=BQ.1.1.25*&analysisMode=CompareEquals&

While for the xbb.1 side i didnt find any certain parent: ORF1b:T1621I doesnt seem circualting in Indonesia while io found some XBB.1.9.1 with that in Australia that frequently collects lineages from Indonesia (EPI_ISL_17561522) but too weak as proof of anything

To me is highly improbable that XBB.1.5 is involved cause 96% of XBB.1.5 sequences have T17124C and Indonesia where this likely emerged is the homeland of multiple xbb.1 lineages with 486P XBB.1.9 clan but also xbb.1.11.1 and other ones, but still XBB.1.5.24 could be a good candidate so ok.

**Comment by FedeGueli** [comment]
XCD
