### ISSUE TITLE
KP.2 + ORF3a:T221K (307 Seq. in 11 countries)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1482]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/193cbe25-5a4b-4c31-8c35-80bf7749f853)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/6614eb96-f90e-4b38-a1c3-2db9f9094336)
Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d006_71aa00.json?c=gt-ORF3a_221&gmax=26220&gmin=25393&label=id:node_6956477

First Seq: 2024-03-02
Most Recent: 2024-03-17

Gisaid Query: C26054A, A22556G

EPI_ISL_18983710 EPI_ISL_19011001 EPI_ISL_19002254 EPI_ISL_19010984

**Comment by Fearuncle** [comment]
20 new sequences from canada.

**Comment by FedeGueli** [comment]
100 now

**Comment by FedeGueli** [comment]
it seems still a canadian lineage

**Comment by FedeGueli** [comment]
307 in 11 countries.

**Comment by Over-There-Is** [comment]
410

**Comment by FedeGueli** [comment]
Still very few from August but quite impressive how this was widespread geographically
