### ISSUE TITLE
JN.1 + S:G75R + N:Q294L (5 in Japan)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1483]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/52c70941-232b-4de3-af76-a08806f897d7)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37112_71dd60.json?c=gt-S_75&gmax=25384&gmin=21563&label=id:node_6951032

First Seq: 2024-03-14
Most Recent: 2024-03-18

Gisaid: G21785C, A29154T

EPI_ISL_19005888 EPI_ISL_19005882 EPI_ISL_19005878 EPI_ISL_19005877 EPI_ISL_19005890

**Comment by FedeGueli** [comment]
no new sequence of this closing for now
