### ISSUE TITLE
GW.5/JN.1 sandwich recombinant with SLip (3 seqs: HK/US-travel from HK/Germany)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1486]
This might be the first SLip recombinant, it appears to be most common in Hong Kong, at least it was sequenced there and US travel surveillance picked it up in a traveller from Hong Kong.

Potentially related to a Gansu (China) sequence as well, but there's quite a bit of divergence so unclear whether same recombinant or not.

Nextclade calls it XDR, but it's clearly not.

If someone would like to look into breakpoints and parents that'd be great. It looks like GW.5 based on having C541T, C1170T, C6501A

All sequences very recent, so might be growing:

<img width="2156" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/934c22f4-0097-417f-bce9-3f7bb910d8f9">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_68c1_be7360.json?label=id:node_6996085

Rough breakpoints are at 20k and 28k, so only the spike really is from JN.1

**Comment by FedeGueli** [comment]
i think it is this one proposed here: https://github.com/cov-lineages/pango-designation/issues/2402#issuecomment-2031728757

**Comment by aviczhl2** [comment]
That's https://github.com/cov-lineages/pango-designation/issues/2402  (which is a 3-BP XDE/JN.1 recomb) plus S:F456L.
