### ISSUE TITLE
GN.1.4/JN.1 recombinant (5 seqs, Peru)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1487]
There seems to be a GN.1.4/JN.1 recomb from Peru. 

JN.1--GN.1.4--JN.1

Breakpoint 1 between 3566 and 6182
Breakpoint 2 between 9867 and 10331

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/60ce204d-e084-497f-8aa5-5325b6d62dca)

Additional mutations: T6700C, from a Peru GN.1.4 branch.

GISAID query: T6700C,C7834T,T3565C
No. of seqs: 5(Peru)

First: EPI_ISL_18958020, 2024-1-12
Latest: EPI_ISL_19024450, 2024-1-30

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_38717_befab0.json?f_userOrOld=uploaded%20sample&label=id:node_11375321)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/43d87d0d-d0db-41cb-b70b-bddd6f3f706b)
[usher for GN.1.4 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38717_befab0.json?gt=nuc.6700C&label=id:node_3732467)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ae555f6a-dcf8-4b92-93ec-19d3f6ea4ead)

**Comment by FedeGueli** [comment]
great catch thx

**Comment by aviczhl2** [comment]
No new seqs
