### ISSUE TITLE
BA.1.1 saltation branch with 26 aa mutations (3 seqs in Nebraska, US)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1489]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1aee290d-717a-4d4d-9db6-157f51a65ce8)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/75cfcfba-f2d4-4e01-87cd-fe8fb4cfe650)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_234d6_ccb720.json?c=gt-nuc_160&gmax=1160&label=id:node_2493993

First Seq: 2024-03-09
Most Recent: 2024-03-14

Gisaid query: G160T, G2494T, C4230T, G5180A

EPI_ISL_19009131  EPI_ISL_19009123 

Mutations:

Orf1a: E743D, T1322I, A1420V, D1639N, T2300I, S2500F, L3060F, A3697V, Y3765H, L3829P, T4065I, T4090I, A4156T

Orf1b: A1131V, T1424I, L1681F, K2557R

E: S16N

Orf3a: H182Y

Orf7b: C41W

Orf8: S67F

S: L48V, N74T, V90F, S371F, I1179S

**Comment by ujoshi4** [comment]
5 spike mutations may not be conducive for robust immune escape.

**Comment by FedeGueli** [comment]
The patients seem two one of 62 the other of 69.
screening the saltation with @theosanderson tool it seems it could be a MOV related saltation, but i would wait for @ryhisner analysis the three NTD mutations are very rare

**Comment by MCB6** [comment]
Not an APOBEC3 footprint with a bunch of C->T's and few antibody-driven changes in the S? Kind of like it evolves in the deer, with few targeted changes in the spike but deamination-driven changes across the genome?
Two of the S-gene mutations were reported in the deer but I don't think it *is* specifically deer in this case, but possibly another zoonotic vector?

**Comment by Fearuncle** [comment]
3rd Seq. EPI_ISL_19030183

**Comment by FedeGueli** [comment]
no new sequence closing it
