### ISSUE TITLE
BA.5.2.46 Molnupiravir Lineage Circulating(?) in Western Australia + Related Recombinant (7 seq, June 6)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#149]
### **Description**
**Sub-lineage of:** BA.5.2.46
**Earliest sequence:** 2023-3-3 — EPI_ISL_17187405
**Most recent sequence:** 2023-5-11 — EPI_ISL_17765632
**Countries circulating:** Australia (7)
**Number of Sequences:** 7
**GISAID AA Query:** Spike_A264T, NSP2_A80V, NSP3_A1321V, NSP3 V1420I
**GISAID Nucleotide Query:** G3974A, G6977A, G14250A, G17972A, G19254A
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2.46* & [9-of: C1044T, T1066C, G2117A, C2388T, T3578C, G3974A, C5183T, G6977A, G13118A, G14250A, G17972A, G19106A, G19254A, G21606T, G21608T, G22352A, C23741T, C25549T, T27402C]
**Substitutions on top of BA.5.2.46:**
**Spike:** C15F, V16F, A264T
**ORF3a:** L53F
**ORF1a:** A260V, G618S, T708I, E1237K, V2238I, A4285T (NSP2_A80V, NSP2_G438S, NSP2_ T528I, NSP3_E419K, NSP3_V1420I, NSP10_A32T)
**ORF1b:** R1502K, C1880Y (NSP13_R579K, NSP14_C356Y)
**Nucleotide:** C1044T, T1066C, G2117A, C2388T, T3578C, G3974A, C5183T, G6977A, G13118A, G14250A, G17972A, G19106A, G19254A, G21606T, G21608T, G22352A, C23741T, C25549T, T27402C
**AA Deletions:** S:∆Y144, ORF1a:∆82-86, ORF1a:∆141-143
**Nucleotide Deletions:** ∆509-523, ∆686-694, ∆21992-21994, ∆27572-27597

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/MOV_BA.5.2.46_AUS,WA_2023_5_11__7seq.json?c=gt-S_15&label=id:node_8863779
 
<img width="1495" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f9a7809d-88e4-4923-96f9-eec851168820">

**Evidence**
The molnupiravir signature in this one is clear, as pictured below. The 9/19 G→A nucleotide mutations are a dead giveaway. The only transversions are a very strange duo of G→T mutations, G21606T & G21608T, which result in S:C15F and S:V16F, an extremely rare mutational combination. S:C15F is known to alter the signal peptide cleavage location, eliminate a disulfide bond (between S:C15 and S:C136 if I remember right), and radically restructure the NTD.
 
<img width="1224" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0768178e-c7a4-4a13-9381-fc1feefc710e">
 
All sequences here have a 26-nucleotide ORF7a deletion (∆27572-27597) that causes a frameshift.
 
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/21e9edde-eb68-4b26-815b-3cdfc7d59ede">
 
The long molnupiravir branch is disrupted because an apparent complex recombinant between a sequence from this lineage and an XBB* of some sort. ORF1ab (and probably spike through S:213) and the region from 25416-27384 seem to have been taken from the XBB* with most of the remainder from this BA.5.2.46 lineage. It's possible this sequence is an artifact due to contamination. The odd inclusion of one private mutation from this BA.5.2.46 branch within the XBB* portion of ORF1b seems suspicious.

<img width="1451" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/50f87047-dc46-4340-944d-090f032d7e1a">

 
**MOV-Lineage Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17187405, EPI_ISL_17374733, EPI_ISL_17374799, EPI_ISL_17374806, EPI_ISL_17527471, EPI_ISL_17527567, EPI_ISL_17765632
</details>
 
**Recombinant Genome**
<details>
<summary>Genomes</summary>
EPI_ISL_17661357
</details>

**Comment by FedeGueli** [comment]
Note that the entire branch evolved from a route defined by NSP6_C221F ( curiously again G > T , G11634T)
I dont know anything on NSP6 but @zach-hensel maybe could help what could mean a lose of a cysteine there, i suspect it could be relevant.

**Comment by FedeGueli** [comment]
No new sequence of this closing for now.
