### ISSUE TITLE
JN.1.1+S:R346T mini saltation branch with S:L455S->A, S:31del and ORF7a:T28I (3 seqs in Singapore and Malaysia)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1499]
Defining mutations:
**EDITED** : JN.1.1+C9442T > C5407A,C27476T,G22599C,T22925G,del21653_21655
[ _original proposal :JN.1.1.7>G22599C (S:R346T)>C5407A, C9442T, T22925G (S:L455S->A), C27476T (ORF7a:T28I)]_

GISAID query: C5407A, T22925G, C27476T
Earliest seq: 2024-03-18 (Malaysia, EPI_ISL_19025958)
Most recent seq: 2024-03-25(Singapore, EPI_ISL_19033217)
Countries detected: Singapore (2), Malaysia (1)

Usher Tree: (Notice that the S:K484E rev is common artefact in Singapore)
![联想截图_20240408111438](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/783f662b-6448-4909-b042-ba2b05d017fc)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16ce3_3578d0.json

It is a small saltation branch from JN.1.1.7+S:R346T sublineage. As S:L455S achieves great success recently, there is still few S:L455F (for XBB* FLip) and S:L455A (for some JN.1* seq S:L455S->A). 
We can monitor the new branch for a time.

Genomes:
EPI_ISL_19025958, EPI_ISL_19033217, EPI_ISL_19033219

**Comment by aviczhl2** [comment]
That's not JN.1.1.7. They have S:S31del instead of the JN.1.1.7-defining S:S31F.

**Comment by aviczhl2** [comment]
The real path shall be 
JN.1.1+C9442T+C5407A,C27476T,G22599C,T22925G,del21653_21655

There may also be a recombinant event with JN.1.8.1 that may explain 2 mutations, C27476T,G22599C

**Comment by FedeGueli** [comment]
> The real path shall be JN.1.1+C9442T+C5407A,C27476T,G22599C,T22925G,del21653_21655
> 
> There may also be a recombinant event with JN.1.8.1 that may explain 2 mutations, C27476T,G22599C

JN.1.8.2

**Comment by FedeGueli** [comment]
if the path is the one propose by @HynnSpylor this is a LC.1 sublineage , please check if placement have been modified

**Comment by aviczhl2** [comment]
> if the path is the one propose by @HynnSpylor this is a LC.1 sublineage , please check if placement have been modified

Nope. This one has S:31-, not 31F.

**Comment by FedeGueli** [comment]
> > if the path is the one propose by @HynnSpylor this is a LC.1 sublineage , please check if placement have been modified
> 
> Nope. This one has S:31-, not 31F.

i ve modified the defining mutations accordingly

**Comment by aviczhl2** [comment]
No more seqs
