### ISSUE TITLE
BN.1.3.5 mini-saltation(8 nuc/5 aa) in China (25 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#15]
Migrated from https://github.com/cov-lineages/pango-designation/issues/1981
sub-lineage of: BN.1.3.5
mutations on top of BN.1.3.5: G4556A(orf1a:V1431I),G9753A(orf1a:R3163K),C17999T(orf1b:T1511I),G21785A(S:G75S), T25343C,C28102T(orf8:P70L),C28507T,T28588C

GISAID query: C28507T,T28588C,C28102T
No. of seqs: 6(Zhejiang 3 Hebei 2 Singapore 1)

First seq: EPI_ISL_17490490(Hebei) 2023-3-17
Latest seq: EPI_ISL_17596232(Singapore) 2023-4-13

Sequences: EPI_ISL_17490383, EPI_ISL_17490490, EPI_ISL_17492813,
EPI_ISL_17495314-17495315, EPI_ISL_17596232
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_2d1ff_360ae0.json)

Screen Shot 2023-05-04 at 16 24 22

**Comment by FedeGueli** [comment]
2 new sequences came of this lineage from Hubei and Sichuan collected in May. Worth keeping this tracked, hard that it will compete but still  very interesting.

**Comment by aviczhl2** [comment]
2 more in Fujian.

**Comment by aviczhl2** [comment]
1 more in Liaoning.

**Comment by aviczhl2** [comment]
1 more from Beijing

**Comment by aviczhl2** [comment]
Shanxi uploads a batch of 7 of this.

**Comment by FedeGueli** [comment]
At this point better proposing it , the last batch doesnt contain very recent samples but we already know from other samples it was circulating still in June. So it is ok to propose it.

**Comment by aviczhl2** [comment]
Original proposal reopened.
