### ISSUE TITLE
XBB.1.41 + S:T478R - 10 seqs France England and Netherlands (discovered by Ryan Hisner)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#150]
There maybe a sublineage of XBB.1.41 with S:T478R that likely has been imported to France, England and Netherlands.
It was already highlighted by @ryhisner first and then tracked by @HynnSpylor in https://github.com/cov-lineages/pango-designation/issues/1997
But i think it is worth monitoring it here after a recent upload of 2 more sequences from France.
(note that the first sequences with S:T478R belonging to this lineage spotted by Ryan in China doesnt belong to the subcluster proposed here:

Tree:
![Schermata 2023-06-07 alle 12 49 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/80a7eb3e-dc56-45d0-bb62-9882677c3603)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24028_5f350.json?c=gt-S_478&label=id:node_6748477

Defining mutations
XBB.1.41 >> S:T478R ( C>A22995G)

Gisaid query:
C1473T,C22995G, G20102T,-C1454T

Samples:
EPI_ISL_17622410, EPI_ISL_17676269, EPI_ISL_17689135,
EPI_ISL_17694854, EPI_ISL_17732195, EPI_ISL_17769595-17769596,

**Comment by FedeGueli** [comment]
3 more sequences from France

**Comment by FedeGueli** [comment]
It has been just designated XBB.1.41.1 via https://github.com/cov-lineages/pango-designation/commit/55342b294a817b40824c6a21a7caa16f5ac83af0 full credit to @ryhisner who discovered it and @HynnSpylor who tracked it from the start.

**Comment by HynnSpylor** [comment]
Today DRC updated 14 seqs collected in 2023 (almost of them are missing specific date), 12 of 14 are XBB.1.41, including 4 XBB.1.41.1

**Comment by FedeGueli** [comment]
Yes and the last who report map shows COngo DRC in red.

**Comment by aviczhl2** [comment]
@FedeGueli Please add a milestone for this.
