### ISSUE TITLE
JN.1+Orf8:E19*, Orf9b:A22V(10 seqs, 3 countries)+S:T572I(8 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1501]
JN.1+C16323T+G27948T, C28348T(Orf8:E19*, Orf9b:A22V)

GISAID query: G27948T, C28348T
No. of seqs: 7(Spain 5 Germany 1 USA 1)

First: EPI_ISL_18846423, Spain, 2024-1-5
Latest: EPI_ISL_19033356, Spain, 2024-3-17

Query for S:T572I branch: G27948T, C28348T, C23277T (5 seqs)

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice43_genome_test_2566d_3cbfc0.json?label=id:node_6939865)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/dd481526-0bc6-459e-81ba-0b38d6553199)

**Comment by FedeGueli** [comment]
slowed down
