### ISSUE TITLE
JN.1+2-nuc Orf1b:I2273S(65 seqs, 13 countries, 35 with S:R346T, 27 with additional S:F456L)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1503]
There seems to be a 2-nuc mutation under JN.1. 

JN.1+T20285C,A20284T(Orf1b:I2273S)

GISAID query: T20285C, A20284T, C18894T,-13584,-1762,-C774T,-29684,-12781,-17334
No. of seqs: 41(Brazil 2 Canada 1 Costa Rica 6 UK 6 France 2 Germany 1 Guatemala 1 Ireland 1 Mexico 1 China 2 Sweden 5 USA 13(4 from Mexico, 2 from UK))
GISAID query for S:R346T branch: T20285C, A20284T, C18894T, G22599C,-17334 (8 seqs)
GISAID query for S:R346T+S:F456L branch: T20285C, A20284T, C18894T, G22599C,T22928C,-17334 (2 seqs)

First: EPI_ISL_18534932, Canada, 2023-11-6
Latest: EPI_ISL_19026930, Sweden, 2024-3-7

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice6_genome_test_281fd_4280c0.json?label=id:node_7022939)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f5d0470d-76e3-4e11-b55d-89e0ff200f32)

**Comment by ryhisner** [comment]
This is a probable TRS-L recombination mutation that sometimes is accompanies by ORF1b:E2274K, which makes the TRS-L  match more extensive. 
<img width="1508" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/24ae0400-de46-4edd-822d-1e4572532ed8">

There was a sequences from Costa Rica recently—probably one of the sequences on this branch—that had another 2-nuc mutation in addition to ORF1b:I2273S. 
<img width="1192" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/bc60a585-ffc7-4220-a39f-73c7346ad5ec">

**Comment by FedeGueli** [comment]
Thx very good catch added as branch 90 of #1089 to try to keep che tglobal picture there (unsure if possible for long time then)

**Comment by FedeGueli** [comment]
Now 46 /10/ 3 i suggest to propose it also due it is widespread in three central american countries

**Comment by FedeGueli** [comment]
49/12/5 pls propose it

**Comment by aviczhl2** [comment]
Some convergent ones are separated by usher now. Correct toll shall be

**Comment by FedeGueli** [comment]
48 now with 20 with r346T and 13 with FLiRT , please propose it @aviczhl2

**Comment by FedeGueli** [comment]
Ps the last FLiRT ones has got S:T95I  too.

**Comment by FedeGueli** [comment]
51 tot +1 Flirt pleaase propose it

**Comment by FedeGueli** [comment]
@aviczhl2 propose this one please.

**Comment by FedeGueli** [comment]
24 for the FLirt sublineage pls propose it.

**Comment by FedeGueli** [comment]
27 i would restrcit the proposal to the FLiRT one bwing the only one still circulating

**Comment by aviczhl2** [comment]
> 27 i would restrict the proposal to the FLiRT one being the only one still circulating

Sure

**Comment by DailyCovidCases** [comment]
This branch might be dying off, please close this

**Comment by DailyCovidCases** [comment]
85 seqs now

**Comment by FedeGueli** [comment]
> 85 seqs now

when closed we updated in the transferred issue # 2679

**Comment by DailyCovidCases** [comment]
85 seqs now
Is this branch worth to be designated?

**Comment by DailyCovidCases** [comment]
93 seqs now, 74 with Orf1ab:I6674S please propose it @aviczhl2
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30c22_7a12e0.json?f_userOrOld=uploaded%20sample
![Screenshot (152)](https://github.com/user-attachments/assets/74214d8e-d82b-4b79-804a-c05fd5e6f6f6)

**Comment by FedeGueli** [comment]
> 93 seqs now, 74 with Orf1ab:I6674S please propose it @aviczhl2 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30c22_7a12e0.json?f_userOrOld=uploaded%20sample ![Screenshot (152)](https://private-user-images.githubusercontent.com/92421581/353105293-74214d8e-d82b-4b79-804a-c05fd5e6f6f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzAzNDYsIm5iZiI6MTcyMjI3MDA0NiwicGF0aCI6Ii85MjQyMTU4MS8zNTMxMDUyOTMtNzQyMTRkOGUtZDgyYi00Yjc5LTgwNGEtYzA1ZmQ1ZTZmNmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2MjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODgzMjM0ZTJhZmNmZDk0MDdlYjgzNWUxM2ExYjJjYmZkMGVlNTNiNzFlZTM2NzExZWNiNGNlZDI1ZjhmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fiIim8H-1ZVlT83AyGBmcNZUlr9jONoCGRHXpDwAA-I)

It is already proposed
