### ISSUE TITLE
FLIRT - KW.1.1 with S:T95S, S:R346T. 10 seqs, two regions in Australia .

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#1504]
KW.1.1 which already had F456L, T572i, has gained T95S, R346T in a single step. 

Earliest seq: 2/27, Victoria Australia. 
Most recent seq: 3/18, SA, Australia. 
nuc mutations: C21846G, G22599C, C27600T
Query: C21846G, G22599C, C27600T,T3565C (Edited)

https://genome.ucsc.edu/cgi-bin/hgPhyloPlace
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/0c24d1e7-3557-4f8c-ba59-02d2f1433c8a)

See [this post](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1135) for more info on S:95 mutations in JN.1*

**Comment by FedeGueli** [comment]
Thx @Sinickle this was Singlet 21 of #1089 but the query of the first sample didn't catch the others. thank you for proposing adding a query to the proposal ( C21846G, G22599C, C27600T,T3565C)
 
 
 
 
 
 
 
 
 
 
2

**Comment by FedeGueli** [comment]
thx @aviczhl2 for labels

**Comment by FedeGueli** [comment]
+2 SA

**Comment by FedeGueli** [comment]
+5 South Australia please propose it.

**Comment by FedeGueli** [comment]
Designated KW.1.1.1 (>95S) and LG.1 (>346T) via https://github.com/cov-lineages/pango-designation/commit/bd06dd40e3a0052de8e9643a550c67f3f69300b1
