### ISSUE TITLE
JN.1+C23054A ( S:R498R)  with a sub branch with S:F79L -79 seqs

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1505]
Edited:
JN.1 > C23054A 
Query : C23054A ,T3565C, C12815T
Samples: 58
Countries: 10 countries mostly China, Singapore and South Korea plus further samples from under-sampled areas  including Philippines, Vietnam, Thailand

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/26466697-dfd0-4058-b712-b3e2fddb4303)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12ac2_625ff0.json?f_userOrOld=uploaded%20sample&label=id:node_2347303

**Comment by FedeGueli** [comment]
C23054T shoukld create a stop codon TGA aloong with A23055G  (S:Q498R) i think this whole part of the tree is an artifact. @ryhisner @aviczhl2 @angiehinrichs what do u think?

**Comment by FedeGueli** [comment]
mm it is C23054A not T  so  it will create AGA ( silent S:R498R)

**Comment by FedeGueli** [comment]
> C23054T should create a stop codon TGA along with A23055G (S:Q498R) i think this whole part of the tree is an artifact. @ryhisner @aviczhl2 @AngieHinrichs what do u think?

scratch this.

**Comment by FedeGueli** [comment]
@Memorablea it is interesting that this has been sampled in Singapore from a Traveler from Philippines: it was in  Philippines that earlier in 2023 a XBB.2.3 sublineage with C23054A emerged and was spotted by @ryhisner ( cfr: https://github.com/sars-cov-2-variants/lineage-proposals/issues/58). It died off but still interesting (some place some silent mutaation some key residue)

**Comment by Memorablea** [comment]
> mm it is C23054A not T so it will create AGA ( silent S:R498R)

Thank you, because what I see is not this mutation, and I cannot distinguish it.

> @Memorablea it is interesting that this has been sampled in Singapore from a Traveler from Philippines: it was in Philippines that earlier in 2023 a XBB.2.3 sublineage with C23054A emerged and was spotted by @ryhisner ( cfr: #58). It died off but still interesting (some place some silent mutaation some key residue)

WOW

**Comment by Memorablea** [comment]
China +1 USA+1

**Comment by Memorablea** [comment]
64

**Comment by Memorablea** [comment]
72

**Comment by Memorablea** [comment]
77

**Comment by ryhisner** [comment]
> > mm it is C23054A not T so it will create AGA ( silent S:R498R)
> 
> Thank you, because what I see is not this mutation, and I cannot distinguish it.
> 
> > @Memorablea it is interesting that this has been sampled in Singapore from a Traveler from Philippines: it was in Philippines that earlier in 2023 a XBB.2.3 sublineage with C23054A emerged and was spotted by @ryhisner ( cfr: #58). It died off but still interesting (some place some silent mutaation some key residue)
> 
> WOW

The biggest implication of this, I think, is that it opens up the door to R498K, which without this silent mutation is 2 nuc mutations distant but which with it is only one G->A nuc mutation away. 498K has been seen in some cryptic wastewater lineages and Q493K + Q498K was in a chronic Beta from France and a couple chronic Alphas. 

It was also in a legendary chronic B.1.1.448 from South Africa that had spike mutations P9L, T95I, C136H, D138V, V143D, ∆Y144, T240I, ∆243-244, ∆Y266, G339D, R346K, N354K, K444T, L452Q, S477N, T478K, G482S, V483A, G485D, Q498K, N501Y, P681R, T859N—as well as additional mixed-nucleotide spike mutations not in the consensus sequence. So 498K can work with N501Y, though I'm not sure if it would be capable of transmitting and circulating.

**Comment by FedeGueli** [comment]
One sample only from May tough. THX @ryhisner for the analysis

**Comment by Memorablea** [comment]
79

**Comment by FedeGueli** [comment]
One recent sample from Japan

**Comment by FedeGueli** [comment]
only two recent samples closing it
