### ISSUE TITLE
KP.1.1+Orf1b:L2213F+S:N185del, F186I(114 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1509]
It seems that other than KP.1.1.1(S:K182N), other seqs on the Orf1b:L2213F branch of KP.1.1 have another NTD mutation set that usher doesn't display. 

KP.1.1+C20104T(Orf1b:L2213F)+del22115_22117,T22118A(S:N185-, F186I)

GISAID query: T22926C,C7113T,T22118A
No. of seqs: 14(UK 4 Canada 1 India 1 Thailand 1 Ireland 1 USA 6(1 from South Africa 2 from Qatar))

First:EPI_ISL_19025542, 2024-2-11, Thailand
Latest: EPI_ISL_19038720, 2024-3-26, USA(GBW baseline)

Usher doesn't display both mutations @AngieHinrichs, I think it shall at least display S:F186I, reading frame issue? 
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1b6d_789bc0.json?f_userOrOld=uploaded%20sample&label=id:node_6959487)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/94da153e-4364-4040-be15-8561cd8b4b8e)

Top is KP.1.1.1, all others belong to this branch.

**Comment by AngieHinrichs** [comment]
Looking at the reference sequence at 22111-22120, it looks like that deletion could be placed one base to the right without a substitution:
```
1234567890
GGGT---ATC  left-aligned:  del22115_22117(AAT),T22118A
GGGTAATTTC  reference
GGGTA---TC  right-aligned: del22116_22118(ATT)
```
(The uploaded sequence is "GGGTATC" with either alignment.)

The child of this branch with A22108C (S:K182N) has been designated KP.1.1.1.

**Comment by aviczhl2** [comment]
> Looking at the reference sequence at 22111-22120, it looks like that deletion could be placed one base to the right without a substitution:
> 
> ```
> 1234567890
> GGGT---ATC  left-aligned:  del22115_22117(AAT),T22118A
> GGGTAATTTC  reference
> GGGTA---TC  right-aligned: del22116_22118(ATT)
> ```
> 
> (The uploaded sequence is "GGGTATC" with either alignment.)
> 
> The child of this branch with A22108C (S:K182N) has been designated KP.1.1.1.

KP.1.1.1 doesn't have this deletion. They seem to be different branches.

**Comment by aviczhl2** [comment]
22, Denmark, Singapore, Spain

**Comment by aviczhl2** [comment]
71, France, Nepal,Germany, Japan, South Korea

**Comment by FedeGueli** [comment]
114

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
Designated KP.1.1.6 starting with S:S31F  via https://github.com/cov-lineages/pango-designation/commit/6637343d6226fd8dac057fdea05d39c1c51f419b
