### ISSUE TITLE
XDK.3: XDK+Orf1a:F3397L+S:F456L(9 seqs, 4 countries, 2 with S:V1228A)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1511]
There seems to be another XDK+F456L branch.

XDK+C10456A(Orf1a:F3397L)+T22928C(S:F456L)

GIDAID query: C5314T, C10456A, T22928C
No. of seqs: 3(South Korea 1 Spain 1 France 1)

First:EPI_ISL_18677099, 2023-12-4, France
Latest: EPI_ISL_19046304, 2024-3-21, South Korea

GISAID query for S:V1228A branch: C5314T, C10456A, T22928C,T25245C

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice44_genome_test_4d287_9115c0.json)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6bd71d70-3d98-4eb5-b925-835cdb74333a)

**Comment by aviczhl2** [comment]
+1 Netherlands

**Comment by FedeGueli** [comment]
+2 France

**Comment by FedeGueli** [comment]
+2

**Comment by FedeGueli** [comment]
Desingated XDK.3 via https://github.com/cov-lineages/pango-designation/commit/541e8ec946eed59ac5da893f020db0f6eb9695f8
