### ISSUE TITLE
JN.1+Orf1b:K82R, Orf1a:A2529S, D1513E+S:S680P(23 seqs, 5 countries, 4 with S:M153I)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1513]
JN.1+A13712G(Orf1b:K82R)+G7850T(Orf1a:A2529S)+T4804G(Orf1a:D1513E)+T23600C(S:S680P)

GISAID query: G7850T, T4804G, T23600C
No. of seqs: 20(South Korea 1 China 6 USA 1 Brunei 9 Japan 3)

First: EPI_ISL_18788923, Brunei, 2023-12-8
Latest: EPI_ISL_19045944, China, 2024-3-23

GISAID query for S:M153I branch: G22021C, T23600C, T4804G (4 seqs)

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice35_genome_test_4d287_9115c0.json?label=id:node_6954933)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b08bd063-7909-4404-9bcb-aa2d8b8c539b)

**Comment by FedeGueli** [comment]
Orf1b:K82R, Orf1a:A2529S both reminds me of Delta, 2529V was AY.4 while Orf1b:K82R was in a sibling undesignated lineage of AY.41 that gave birth to a very bad south east europe wave.

**Comment by aviczhl2** [comment]
No new seqs

**Comment by aviczhl2** [comment]
JN.1+Orf1b:K82R, Orf1a:A2529S, D1513E designated JN.1.63 and JN.1.63.1.
