### ISSUE TITLE
New DY.4+orf1b:E1602D+S:G252D,S:Q183H (12 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#152]
DY.4+orf1b:E1602D(A18273C)+C10507T,S:G252D(G22317A)+S:Q183H(G22111T)

GISAID query: G22111T,C10507T,G22317A,A18273C

No. of seqs: 11 (Jiangsu 1 Yunnan 3 Shannxi 1 Xinjiang 6) 

The four provinces are very far apart from each other, and the seqs are quite new. 

First seq: EPI_ISL_17493334, 2023-3-16, Yunnan
Latest: EPI_ISL_17775152, 2023-5-17, Xinjiang

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_28cd5_1d80a0.json?label=id:node_9092240)

<img width="1414" alt="Screenshot 2023-06-09 at 01 10 09" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a88a3db5-1b82-4663-88be-ad31356faf7e">

**Comment by HynnSpylor** [comment]
Notice that over half of seqs are before the second wave in China (since late April). Xinjiang may be the one of last region to suffer the second XBB* wave, but the BA.5.2.48* sublineage is unlikely to have growth potential. Anyway, we should track it for a time.

**Comment by FedeGueli** [comment]
Xinjiang has its new undesignated xbb.1+486P lineage plus likely some FR.1.1 starting to circulate there. we will see. I didnot expect this one to be fast but worth tracking.

**Comment by FedeGueli** [comment]
Closing this one: just one sample in the last batch uploaded from the regions
