### ISSUE TITLE
KP.2 + S:L56V cluster in UK,California, India (39 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1520]
Noticed a cluster of interest in UK with a rare mutation S:L56V that popped up around 150 times before this lineage.
and not surprisingly after looking at Dadonaite and Bloom tool:
<img width="247" alt="Screenshot 2024-04-17 alle 11 41 29" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a47321d8-b15a-4ccc-a1d5-44b3f0ade2c2">

Still appearing in one of the fastest lineage better to track it to be sure it is just a cluster as appears.
Tree:
<img width="1158" alt="Screenshot 2024-04-17 alle 11 42 34" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2bd1865a-8a43-497a-96d7-3aa29c8ef139">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_51bc8_eece90.json?label=id:node_6969364

Defining mutations:
KP.2> Orf1a:T2093I (C6543T)> T19377C, S:L56V (T21728G)
Query: T19377C, T21728G,T3565C 
or _new alternative query to catch a basal sample caught by GBW from a traveler from India as spotted by @ryhisner_ : T21728G,T3565C,-T18453C ,-C18687T,-A2242,2G,-G2173
Samples: 9 (UK) on _Gisaid_, but there are already 21 on _Climb_

**Comment by ryhisner** [comment]
There's a travel sequence from India collected on March 3 in the US. It's clearly basal to the English branch. I think there's a good chance this is fairly widespread somewhere in India. 
<img width="1496" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/b0f3ba0f-9f41-4166-9b61-81f4604ab4b2">

**Comment by FedeGueli** [comment]
> There's a travel sequence from India collected on March 3 in the US. I think there's a good chance this is fairly widespread somewhere in India. <img alt="image" width="1496" src="https://private-user-images.githubusercontent.com/33738461/323387287-b0f3ba0f-9f41-4166-9b61-81f4604ab4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzM2NTMsIm5iZiI6MTcxMzQzMzM1MywicGF0aCI6Ii8zMzczODQ2MS8zMjMzODcyODctYjBmM2JhMGYtOWY0MS00MTY2LTliNjEtODFmNDYwNGFiNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5NDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZjMxN2VmNWUwYTczMTYzMmUxNTNhNDdiMmRjZTUyMmZiNmI4OTVmYzdkNmM3ODc2YmY4ZDE1OTUyZTFjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Ur1M-S2YFHym4XbgmqbMla5lPp9957foqTLM27CYO0">

Thank you Ryan, now 20 on Gisaid , my query misses your GBW sample, have u a better one please?

**Comment by FedeGueli** [comment]
It seems there are three independent branches with S:L56V: 

Branch 1: KP.2 proposed here T21728G,T3565C,-T18453C ,-C18687T,-A22422G
Branch 2: JN.1.4 > T18453C > C16308T, S:L56V (T21728G) query: C16308T,T21728G samples: 4
Branch 3: JN.1.31 > C18687T > Orf1a:S2500F (C7764T) > G28621A > C21595T S:Q836L (A24069T)> C12823T,S:L56V (T21728G) Query: C12823T,T21728G,T3565C Samples: 3 ( not recent ones)



 
<img width="1164" alt="Screenshot 2024-04-18 alle 11 52 48" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4e85eb82-190b-42bf-88b0-26942715446b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_60ce9_ebb40.json?f_userOrOld=uploaded%20sample&label=id:node_6918564

**Comment by FedeGueli** [comment]
38 still uk only. i will propose when it will show up in some other countries and reaches at least 50. cc @aviczhl2

**Comment by FedeGueli** [comment]
+1 California

**Comment by aviczhl2** [comment]
Designated KP.2.11
