### ISSUE TITLE
JN.1.1 + S:F456L + S:H445P(45 seq, 9 countries)

### ISSUE THREAD

**Issue by DoropFan** [sars-cov-2-variants/lineage-proposals#1521]
Sub-lineage of:JN.1.1(BA.2.86.1.1.1)
Earliest sequence:2024-02-27(USA)EPI_ISL_18965280
Most recent sequence:2024-03-27(USA)EPI_ISL_19038694
Countries circulating:United States(3), Canada(3), Netherlands(1), United Kingdom(1)
Sequences:8

UShER Tree
JN.1.1>T22930A(S:F456L)>C850T, Orf1a:S2083I (G6513T), A22896C(S:H445P) [Edited]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33b20_e10a0.json?c=gt-nuc_22896&gmax=23896&gmin=21896&label=id:node_7000681
![JN1 1+456L+445P](https://github.com/sars-cov-2-variants/lineage-proposals/assets/118802079/b73dcec6-7acd-4e51-92e2-fe21a4901ebe)
Query proposed by Mod: C850T, G6513T,T3565C
[Original query: GISAID: C850T, G6513T, A22896C, T22930A]
[CovSpectrum](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C850T%2CG6513T%2CA22896C%2CT22930A)
Genomes
EPI_ISL_18965280
EPI_ISL_18965380
EPI_ISL_19038694
EPI_ISL_19044302
EPI_ISL_19042295
EPI_ISL_19044245
EPI_ISL_19036076
EPI_ISL_19044211

**Comment by FedeGueli** [comment]
Hi @doropfan i suggest to use C850T, G6513T,T3565C as query, it finds 10 . added then to the proposal, check if it is ok for you.

**Comment by FedeGueli** [comment]
5 countries being one GBW sample from a traveler from Qatar

**Comment by DoropFan** [comment]
> Hi @DoropFan i suggest to use C850T, G6513T,T3565C as query, it finds 10 . added then to the proposal, check if it is ok for you.

Thank you as always.

**Comment by DoropFan** [comment]
UK + 2

**Comment by DoropFan** [comment]
Australia(new) 4

**Comment by FedeGueli** [comment]
23 now last ones from Canada

**Comment by FedeGueli** [comment]
Designated JN.1.1.8 via https://github.com/cov-lineages/pango-designation/commit/5191300c600e7d71f4fb70517406330d42b572e1 

First S:H445P designated on JN.1 Backbone

**Comment by FedeGueli** [comment]
thanks for crediting @aviczhl2 i missed that .
