### ISSUE TITLE
XDQ.1+Orf1b:M1573V+Orf1a:P1207L, Orf1b:H2285Y, S:T572I(6 seqs, Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1522]
XDQ.1+A18184G(Orf1b:M1573V)+C3885T, A12709G, A26594T, C20320T, C20719T, C23277T, G29254A(Orf1a:P1207L, Orf1b:H2285Y, S:T572I)

GISAID query: C23277T, A18184G, C28846T
No. of seqs: 5(Japan)

First:EPI_ISL_19053147, 2024-3-24
Latest: EPI_ISL_19053134, 2024-3-27

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_36051_241a20.json?label=id:node_6910379)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c0e5c070-c228-47ae-8f23-46156db89108)

**Comment by FedeGueli** [comment]
Thank you very interesting 475V + 572I unprecedented combo i think.

**Comment by FedeGueli** [comment]
closing it
