### ISSUE TITLE
KP.2 + T22795G (S:A411A) plus S:N185D (13 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1527]
There is a small but internationally spread branch of KP.2 with S:N185D.
S:N185D has been a recurrent mutation thorugh XBB and BA.2.75 era and already popped up with some success in JN.1.4.2 at the start of the JN.1. wave.
I don't think it would add much more fitness to already super tuned KP.2, but better to track also because two sequences come from two undersampled areas.

Defining Mutations:
KP.2 > T22795G > S:N185D (A22115G)
Query: A22115G,T22795G
Samples : 4 on Gisaid + 2 on Climb
Countries: Qatar, Russia, US, UK
Tree:
<img width="1166" alt="Screenshot 2024-04-21 alle 11 07 38" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/618fa191-948e-476c-9ac3-b25ebf0e924a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice15_genome_test_259b2_43aeb0.json?c=userOrOld&label=id:node_6972059

**Comment by FedeGueli** [comment]
+1 NZL 7 seq 4 continents

**Comment by FedeGueli** [comment]
+1 Western Australia

**Comment by FedeGueli** [comment]
+1 England not on Gisaid

**Comment by FedeGueli** [comment]
10 now last two are one patient GBW-tested coming  from India

**Comment by aviczhl2** [comment]
Designated KP.2.5

**Comment by ryhisner** [comment]
About half of these (12/26) have a large NSP3 deletion, ORF1a:∆2131-2139, or NSP3_∆1313-1321, including 11 of the 17 collected April 15 or later. 
<img width="1461" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/143f3df7-34d6-431b-833c-3fb5bfdf9c9d">

**Comment by FedeGueli** [comment]
Thx for catching that @ryhisner i missed it when proposing it!

**Comment by FedeGueli** [comment]
Added to the headline if anyone in future investigating NSP3.
