### ISSUE TITLE
BQ.1.1 saltation with S:Y144del, H245Y, N343S, N417D, A653V and 15+ additional non-spike aa mutations (2 seqs, US)

### ISSUE THREAD

**Issue by Vnes97** [sars-cov-2-variants/lineage-proposals#1528]
Sequences: EPI_ISL_19036878, PP713005.1 (Likely from the same patient, though metadata indicates that it is sequenced from baseline surveillance).
BQ.1.1 recently (March 21st 2024) sampled with interesting mutation profile.
Earliest sequence: 21.03.2024 (United States)
Countries detected: United States
aa mutations:
BQ.1.1+
ORF1a: F8L (2-nuc), I114V, V627I, S1272N, S1372A, K2507R, S2972P, T2977I, I4098T
ORF1b: V87I, V1164M, P1570S, Q2635H
S: Y144del, H245Y, N343S, N417D (2-nuc), A653V
E: I9T
M: L67F, H125Y
ORF7a: T115I
Though BA.5 descendents tend to have low Spike mutation rate than other Omicron sublineage in chronic cases, this BQ.1.1 has some rare mutations such as S:N417D that needs to be monitored. The 2-nuc mutation ORF1a:F8L in ORF1a's signal peptide is also worth notifying.
Gisaid query: T287C, C289A, G22599C
EDIT: one of them (PP713005.1) has an additional ORF1a:V366I

**Comment by Vnes97** [comment]
This one seems to trade ACE2 binding for immune escape, but with little success
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/167881374/c899f70b-5c5f-4e95-91bc-b0f2e08867bf)

**Comment by FedeGueli** [comment]
S:N343S removes the key N Glycan at 343. 
I think @ryhisner found this one too.

**Comment by ryhisner** [comment]
Anything that removes the N343 glycan has to involve a serious rearrangement of spike, so I don't know how accurate current ACE2 affinity or antibody-evasion assays will be. M:H125Y is a classic chronic mutation that Tom Peacock first identified in an analysis of immunocompromised patients. 

The E:I9T reversion is a fascinating one. It's occurred dozens of times, almost always in exceptionally divergent chronic-infection sequences. There have been various claims made about E:T9I, but I'm not sure I believe most of them as I think they're all overexpression studies.

**Comment by ryhisner** [comment]
Another interesting aspect of this one is the 2-nuc ORF1a:F8L, which had to have been acquired via recombination with the TRS-L. It seems that it has only been in about 25 sequences ever. 

<img width="1486" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5bac3712-705e-405e-9feb-7d18d426aea5">

**Comment by FedeGueli** [comment]
Thanks @ryhisner !

**Comment by FedeGueli** [comment]
No new sequence of this i m closing it
