### ISSUE TITLE
KS.1+ N:P383L, ORF3a:H78Y (19 in Canada)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1529]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/37203447-8aaf-481a-a528-04531bde1cad)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_830a_883d10.json?c=gt-N_383&gmax=29533&gmin=28274&label=id:node_7014539

First Seq: 2024-04-05
Most Recent: 2024-04-15

Gisaid Query: C25624T, C29421T, T22917G, A29510C

EPI_ISL_19051389 EPI_ISL_19051392 EPI_ISL_19063897 EPI_ISL_19051397 EPI_ISL_19051384 EPI_ISL_19051345 EPI_ISL_19051439 EPI_ISL_19063905 EPI_ISL_19063953 EPI_ISL_19063901 EPI_ISL_19051447 EPI_ISL_19051451 EPI_ISL_19051438 EPI_ISL_19051440

**Comment by FedeGueli** [comment]
Orf3a:H78Y was the defining of BA.2.9 one of the first mutation popping up in BA.2

**Comment by FedeGueli** [comment]
19
