### ISSUE TITLE
JN.1.9 sublineage with S:S60P, L176F in Gansu,China (2 seqs)

### ISSUE THREAD

**Issue by Vnes97** [sars-cov-2-variants/lineage-proposals#1530]
First Seq: 2024-04-22
Most Recent: 2024-04-22
Those sequences are on Genbase (C_AA068036.1, C_AA068039.1)
Mutations:
Nt 
Unique (2):C12119A, T21740C 
Homoplasies (2):C22088T, C29311T
AA
ORF1a Unique (1):P3952T 
S Unique (1):S60P 
Homoplasies (2):L176F, G212I
One of them (C_AA068036.1) has an additional ORF7a:Q94H.
The other has an additional N:I131M.
Some rare NTD mutations worth monitoring.

**Edited** 
Query: C12119A, T21740C

**Comment by FedeGueli** [comment]
S:56-60 is an area that started to evolving fast with JN.1 , especially S:F59S and S:S60P seem beneficial.
S:L176F is a known mutation already definign of carious lineages:
<img width="630" alt="Screenshot 2024-04-24 alle 13 50 21" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9834863d-6b7d-4349-9d42-f342e08ac715">

It is likely to escape to a broad neutralizing AB studied by David Ho Shapiro and Liu
<img width="614" alt="Screenshot 2024-04-24 alle 13 52 03" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a2ec37d8-deb4-468d-8a08-0b4bc4213315">
https://www.biorxiv.org/content/10.1101/2023.04.08.536123v1.full.pdf

**Comment by Vnes97** [comment]
> S:56-60 is an area that started to evolving fast with JN.1 , especially S:F59S and S:S60P seem beneficial. S:L176F is a known mutation already defining of various lineages: <img alt="Screenshot 2024-04-24 alle 13 50 21" width="630" src="https://private-user-images.githubusercontent.com/87669813/325207266-9834863d-6b7d-4349-9d42-f342e08ac715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjAyNjYsIm5iZiI6MTcxMzk1OTk2NiwicGF0aCI6Ii84NzY2OTgxMy8zMjUyMDcyNjYtOTgzNDg2M2QtNmI3ZC00MzQ5LTlkNDItZjM0MmUwOGFjNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDExNTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMDBiZGIxNWY3YmM0NDBjM2FlM2Q5YzYwOTVhOTNiYWI3ZjRhOWZlMWY0MTdiMzdiZTYyNTdkNGU0NjU2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O6oFSFO7nNkPx3S95Uq4AV9JJnT5NHPwgVAfDi7XVrc">
> 
> It is likely to escape to a broad neutralizing AB studied by David Ho Shapiro and Liu <img alt="Screenshot 2024-04-24 alle 13 52 03" width="614" src="https://private-user-images.githubusercontent.com/87669813/325207726-a2ec37d8-deb4-468d-8a08-0b4bc4213315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjAyNjYsIm5iZiI6MTcxMzk1OTk2NiwicGF0aCI6Ii84NzY2OTgxMy8zMjUyMDc3MjYtYTJlYzM3ZDgtZGViNC00NjhkLThhMDgtMGI0YmM0MjEzMzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDExNTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3OWJlYzk5Y2E1YWVjZjAwZjIzYjBjNzc2ZTJiZmZjMjliMGZkOWFlYzQ3Mzg3N2NiNzNmZTZiYzdkNGJhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ruUJMJZcArVT04_qB5KneWTad_GB5e4QHwpZPxesFQ"> https://www.biorxiv.org/content/10.1101/2023.04.08.536123v1.full.pdf

Thanks for your information!

**Comment by Mydtlwn** [comment]
It should be added that the mutations of S:S31F, S:S31P, S:S31Del, and S:F59S seem to be convergent mutations, and there is also a sign of convergence in the mutation on S:60.

**Comment by FedeGueli** [comment]
no new sequence came if this
