### ISSUE TITLE
KP.3+N:204P,Orf9b:P3H(45 seqs, 3 countries, mainly Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1531]
KP.3+C25006T,G28884C(N:R204P) +C28291A(Orf9b:P3H)

GISAID query: C25006T,G28884C,C28291A
No. of seqs: 16(Japan 15 USA 1)

Currently GISAID returns 15, EPI_ISL_19068848 is suffering from no mutation bug again.

First: EPI_ISL_19059439, Japan, 2023-3-1
Latest: EPI_ISL_19068848, USA, 2024-4-16

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_52804_8729e0.json?label=id:node_6971688)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/22405896-2239-4738-a307-089acfbd83f1)

**Comment by FedeGueli** [comment]
45! please propose it

**Comment by FedeGueli** [comment]
one got 475V proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1554
