### ISSUE TITLE
HK.3.2+S:18S,19L,T588I,G946R(7 seqs, Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1532]
HK.3.2+T8623C,T13060C,C20148T,C21614T,T21615C,A21617C,C23325T,G24398C,C25339T,C25728T,A27669G (S:L18S,T19L,T588I,G946R)

I don't know what happens to this one. It seems that it has two 2-nuc mutations placed together. C21614T,T21615C,A21617C combined with the existing C21618T, resulting in S:L18S+S:I19L. 

GISAID query: C21614T,T21615C,A21617C,A27669G
No. of seqs: 7(Japan)

First: EPI_ISL_19062408, 2024-3-13
Latest: EPI_ISL_19062400, 2024-3-26

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice248_genome_test_541c9_873640.json?label=id:node_3543298)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/7c304d48-72ce-4fd8-ba94-a2174b3fea81)

**Comment by FedeGueli** [comment]
Found by @ryhisner yesterday too. i suspect Japan does target sequencing of non JN.1 samples. but we will see.
