### ISSUE TITLE
KS.1 + S:V642A (56) 6-7% in Dominican Republic

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1535]
KS.1 > S:V642A ( T23487C)

Query: T22928C, G24821T,T23487C

Samples : 5 on Gisaid 7 on Usher

EPI_ISL_19019160, EPI_ISL_19019188, EPI_ISL_19019200,
EPI_ISL_19054256, EPI_ISL_19070085

Tree:
<img width="1159" alt="Screenshot 2024-04-26 alle 10 26 19" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7574131a-b324-4071-83e8-106d7afb74f8">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice6_genome_test_471cf_abe240.json?c=userOrOld&label=id:node_7036547

**Comment by ryhisner** [comment]
This is on the opposite side of the 630 loop from P621S. S:V642G is more common, but I'm guessing V642A has a similar effect. BA.2.87.1 had/has both P621S and V642G. P621S definitely makes the RBD-up conformation more common. I'm not sure what V642G does though.

**Comment by FedeGueli** [comment]
Thank you Ryan!

**Comment by FedeGueli** [comment]
luckily it seems slow

**Comment by FedeGueli** [comment]
This one is back with many samples uploaded in June from Dominican Republic and via GBW from Dominican republic and Panama
New Tree:
<img width="1172" alt="Screenshot 2024-06-25 alle 23 02 00" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bb4f774e-e368-443f-bc9d-6514cce51e5f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice11_genome_test_20ceb_b11020.json?label=id:node_7150966

Estimated prevalence in Rep. Dominicana is around 7% after May 15

**Comment by FedeGueli** [comment]
@corneliusroemer ping

**Comment by FedeGueli** [comment]
25 +3 Japan via GBW

**Comment by FedeGueli** [comment]
Designated KS.1.3 via https://github.com/cov-lineages/pango-designation/commit/ea75ab8e923e0e05ae7a94fa70c3c4172d2bd50b
