### ISSUE TITLE
JN.1.4.6/(anything with Orf9b:I5T) recombinant(17 seqs, UK)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1537]
JN.1.4.6+G3052T, C6471T, C15720T, C17172T,G18163T, C19118T, T28297C, A28958C(rev)

Orf1a:E929D, T2069I
Orf1b:V1466L, A2284V
Orf9b:I5T
N:K229Q(rev)

JN.1.4.6--anything with Orf9b:I5T (most likely XBB* )

Breakpoint between 27916 and 28296

G3052T,C15720T, C17172T,G18163T, C19118T from an JN.1.4.6 branch
T28297C, A28958C(rev) from anything with Orf9b:I5T
C6471T is private mutation. 

GISAID query: G3052T, T28297C,T27810C
No. of seqs: 6(UK)

First: EPI_ISL_19062774, 2024-4-12
Latest: EPI_ISL_19069638, 2024-4-16

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice93_genome_test_56ef6_e03d80.json?label=id:node_7093490)
The top one is this recomb.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/97802cb2-a660-4fca-bf66-4c5ac8c3fa08)

**Comment by FedeGueli** [comment]
+2 Uk

**Comment by FedeGueli** [comment]
no recent samples, closing it for now
