### ISSUE TITLE
XDR.1: XDR + S:F59S(7 seq, 4 countries) + S:R346T(6 seq)

### ISSUE THREAD

**Issue by DoropFan** [sars-cov-2-variants/lineage-proposals#1542]
Sub-lineage of:XDR
Earliest sequence:2024-02-08(Brazil)EPI_ISL_18970545
Most recent sequence:2024-04-03(England)EPI_ISL_19055525
Countries circulating:Peru(2), Brazil(1), United States(1),  United Kingdom(1)
Sequences:5

UShER Tree
XDR>C5005T>ORF1a:A1938S(G6077T), A14031G, S:F59S(T21738C), C26801T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1cc89_4656e0.json?c=gt-S_346&gmax=25384&gmin=21563&label=id:node_7012477
![XDR+59S+346T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/118802079/a1957213-44cf-4965-a0fe-4aa41f29f171)

Query:C2668T, G6077T, T21738C
[CovSpectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=C2668T%2CG6077T%2CT21738C&)

Genomes
EPI_ISL_19084464
EPI_ISL_19084465
EPI_ISL_18970545
EPI_ISL_18960074
EPI_ISL_19055525

**Comment by FedeGueli** [comment]
7 seqs now (6 346T)

**Comment by FedeGueli** [comment]
XDR.1 designated starting from S:F59S 
https://github.com/cov-lineages/pango-designation/commit/acd0f55e8f939548c444a9d919076972bca86e1e

**Comment by FedeGueli** [comment]
Lets see if all the sequences have 346T it could be don and dusted here.

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/47813845-e5f6-49ea-acf4-41b3470d5807)

Usher tree changes and it seems not recognizing XDR.1 now.

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2!  It will be fixed in the 2024-06-27 tree later today.
