### ISSUE TITLE
JN.1 + FLiRT + S:N679R + ORF1a:N2147S (13 in 5 Countries)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1547]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b626ff2c-aa80-4ca4-a651-c480e3e50ce6)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f2d4_6355b0.json?c=gt-S_679&gmax=25384&gmin=21563&label=id:node_7108328

First Seq: 2024-03-14
Most Recent: 2024-04-24

Gisaid Query: A23598G, A6705G

England/CLIMB-CM7YJJNA/2024 EPI_ISL_19041364 EPI_ISL_19084570  England/CLIMB-CM7YGYDK/2024 EPI_ISL_19086035 EPI_ISL_19060071 PP716748.1 EPI_ISL_19044406 EPI_ISL_19060030 EPI_ISL_19066354 EPI_ISL_19066353  England/CLIMB-CM7YR13E/2024

**Comment by FedeGueli** [comment]
Hi @Fearuncle thanks for spotting! as i ve already answered you before, this is proposed already in https://github.com/cov-lineages/pango-designation/issues/2560
