### ISSUE TITLE
BA.2.12.1 saltation, likely single patient (8 seq., France) 

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#1549]
Proposal for a sublineage of BA.2.12.1
Earliest sequence: 15.04.2024 (France)
Countries detected: France

nuc	unique	T241C, T378C, G428A, T586A, T766G, C813T, A2693C, C2706T, A2784G, C2940T, G3728T, A4236C, A4830G, T5151C, T5179A, A5648C, A6133C, T7106C, G7272A, G7452T, C9042T, G9220A, G9489A, C9510T, T10429C, T11081G, T11170C, T11223C, C11407T, A11456G, T11601C, A12088G, T13033A, T13716C, G14126A, G14290A, T15975C, A18270G, A19077G, C19451T, A19954C, G20302A, A20399G, T20407C, T21752G, G21969T, T22085C, A22161G, G22180T, G22200A, G22249T, G22316A, G22599A, A22811T, G22882T, G22899A, A22905G, T22942G, A22947C, A22994G, G23012A, T23018C, T23019C, G23040T, G23049A, G23236T, T23569C, A23604G, C23692T, A23854C, C24042A, G25726A, G26065T, G26116A, A26952G, T28271C, T28382C, C29249T
nuc	homoplasies	C829T, A1367G, C7011T, T14408C, C17304T, C18744T, A21137G, C22679T, T22686C, G22688A, C23013A, G26529T, C26873T, C27509T, T28297C, C29144T
nuc	reversionsToRoot	T241C, T14408C, C22679T, T22686C, G22688A, G22882T, C23013A, A23854C
ORF1ab	unique	V38A, E55K, S167R, T183I, N810H, T814I, N840S, P892L, G1155C, N1324T, Q1522R, V1629A, K1795Q, K1956N, Y2281H, R2336K, S2396I, S2926F, S3075N, T3082I, L3606V, V3653A, I3731V, I3779T, N4256K, S4621N, D4676N, A6396V, I6564L, E6680K, E6712G, F6715L
ORF1ab	homoplasies	I368V, A2249V, L4715P, K6958R
ORF1ab	reversionsToRoot	L4715P
S	unique	W64G, C136F, F175L, Y200C, K206N, G213E, L229F, G252S, R346K, N417Y, K440N, G446D, N448S, K462T, K478E, A484K, F486P, R493L, G496D, K558N, H681R, K764N, T827K
S	homoplasies	P373S, F375S, A376T, N460K
S	reversionsToRoot	P373S, F375S, A376T
ORF3a	unique	V112I, V225F, E242K
M	unique	I144V
M	homoplasies	D3Y
ORF7a	homoplasies	T39I
N	unique	S37P, P326S

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/7591b905-6051-4f3b-9e83-2ccff9d9b73d)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/7971064e-b35f-48ab-875c-64f3c27033e5)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3121e_a2ef40.json?c=userOrOld

EPI_ISL_19081416, EPI_ISL_19081419, EPI_ISL_19081422,
EPI_ISL_19081425, EPI_ISL_19108198-19108200, EPI_ISL_19108208

**Comment by FedeGueli** [comment]
Yes this was discussed by @ryhisner last week!

**Comment by FedeGueli** [comment]
> Where can i find this discussion? Sequences were uploaded today

There were 4 last week too. I think Ryan made a thread on twitter

**Comment by aviczhl2** [comment]
Under query T378C, G428A, T586A we can find actually 8 seqs, all from a 39-year-old female.

**Comment by FedeGueli** [comment]
> This seems to be 4 new seqs besides the already discussed ones.
> 
> Given high number of reversions, I suspect any recomb event involved.

Yes exactly these are the ones discussed yesterday by Ryan, while tehre were 4 more last week.

**Comment by FedeGueli** [comment]
> Under query T378C, G428A, T586A we can find actually 8 seqs, all from a 39-year-old female.

Thx

**Comment by aviczhl2** [comment]
No more seqs
