### ISSUE TITLE
FE.1.1.1+Orf8:A55V+S:V622I in Puerto Rico and Canada (110 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#155]
FE.1.1+C3261T(Orf1a:T999I),T3577G,C15180T+T9445C+C28057T(orf8:A55V)+G23426A(S:V622L)

GISAID query: G23426A,C28057T,T9445C
No of seqs: 52( Puerto Rico 18 Canada 30 USA-FL 1 USA-OH 2 USA-TX 1)
First:EPI_ISL_17537601 2023-2-12, Canada
Latest:EPI_ISL_17700219,2023-5-16,Puerto Rico

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_429dd_2a7470.json?branchLabel=Spike%20mutations&label=id:node_6646361&showBranchLabels=all)

<img width="1415" alt="Screenshot 2023-06-10 at 13 23 34" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3e0f4a17-c145-4437-8afb-b2f05d8ae91e">

**Comment by FedeGueli** [comment]
The parental lineage has been designated with orf1a:T999I has been designated FE.1.1.1

**Comment by FedeGueli** [comment]
Parental lineage has been designated FE.1.1.1 starting with Orf1a:T999I

**Comment by aviczhl2** [comment]
> Parental lineage has been designated FE.1.1.1 starting with Orf1a:T999I

Thanks for the correction.

**Comment by FedeGueli** [comment]
Please propose this one. as said in #239 pkease edit your proposal with the correct aminoacid change S:V622I
![Schermata 2023-06-23 alle 17 03 16](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/88005c5c-bf2e-483d-8a3d-222542598ebe)
