### ISSUE TITLE
JN.1.23 with  Orf1a:L1130F/NSP3_L312F and S:V1264L (29 , 1 with S:A475V) with a further sublineage with S:N137K (18)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1552]
Credits: @ryhisner that tracked this since the start i m proposing it in his behalf

Defining mutations:
JN.1.23>> Orf1a:L1130F (C3653T) , C6896T  > S:V1264L (G25352T) > S:N137K (T21973G)

[Note that Orf1a:L1130F is a double nuc mutation   corresponds to NSP3_L312F . According to updated Neher/Bloom calculator it could be [beneficial](https://jbloomlab.github.io/SARS2-mut-fitness/nsp3.html) . cc @ryhisner ] EDITED thx for @aviczhl2 for spotting the double nuc error!

Query for 1264L: C3653T, C6896T  ,G25352T
Samples: 24  from 4 countries

Query for further sublineage with S:N137K :  G25352T,T21973G
Samples:14 from 4 Countries (Br, Us , Can, Puertorico)

IDs:
Without N137K: 
EPI_ISL_18872372, EPI_ISL_18872374, EPI_ISL_18917328,
EPI_ISL_19091640, EPI_ISL_19091658, EPI_ISL_19091675,
EPI_ISL_19091680-19091681, EPI_ISL_19091683, EPI_ISL_19109360
with N137K:
EPI_ISL_18992209, EPI_ISL_19021224, EPI_ISL_19054192,
EPI_ISL_19056521, EPI_ISL_19058380, EPI_ISL_19091643,
EPI_ISL_19091648, EPI_ISL_19091655, EPI_ISL_19091662,
EPI_ISL_19091665, EPI_ISL_19091684, EPI_ISL_19091687,
EPI_ISL_19094266, EPI_ISL_19110147

Tree:
<img width="1150" alt="Screenshot 2024-05-08 alle 12 52 04" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7102ea94-9748-4c89-a883-83d989908e0a">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c063_b4d000.json?label=id:node_7039209

Note that there is one sample with S:A475V in the branch without S:N137K
Query for S:A475V : C3653T ,A1588T  ,C22986T,T3565C

**Comment by aviczhl2** [comment]
3653 and 3565 has a 88 gap.

**Comment by FedeGueli** [comment]
> 3653 and 3565 has a 88 gap.

Thank you!! Epic fail by me!

**Comment by FedeGueli** [comment]
3 new samples for 1264L/137K with 3 new states of USA

**Comment by FedeGueli** [comment]
Designated JN.1.23.1 starting with S:N137K via https://github.com/cov-lineages/pango-designation/commits/master/
