### ISSUE TITLE
Small lineage monitor:KP.3.3 one singlet with S:A475V （1seq from Thailand）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1554]
**KP.3 with Orf9b:P3H ( proposed in #2579) got one singlet with S:A475V （1seq from Thailand）**
KP.3 >C25006T,G28884C(N:R204P) + C28291A(Orf9b:P3H) + **C22986T(S:A475V)**

GISAID query: C7113T, G17334T, T22928C, C22986T, C23191T, G24872T, C25006T, G28884C
Alternative query proposed by mod: C22986T, C23191T,C28291A

First: EPI_ISL_19130073,Thailand,2024-04-17
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/49900122-6d91-4fb2-b481-64118cd9e3f9)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_58308_dda470.json?f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
Thank you good catch , i ve edited a bit to add some info and a shorter query.

**Comment by Memorablea** [comment]
> Thank you good catch , i ve edited a bit to add some info and a shorter query. It is a sublineage of [cov-lineages/pango-designation#2579](https://github.com/cov-lineages/pango-designation/issues/2579)

THX
