### ISSUE TITLE
KP.3.2.1 (S:A263V) with S:30-31del + S:F32I (3)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1556]
KP.3.2 (A2611C) +C26858T+C22350T(S:A263V)

GISAID query: C23039G,C26858T,C22350T
No. of seqs: 7(Australia 4 Singapore 2 Spain 1)

First: EPI_ISL_19095773, Singapore, 2024-4-11
Latest: EPI_ISL_19131027, Spain, 2024-5-3

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_36de4_e26520.json?label=id:node_6984012)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/160c49f3-c210-4349-a35e-92a791b32d0a)

Edited:
There is S:S31del branch of this one but with a larger deletion invlving also S:N30 and resulting in S:F32I 
Query for S:S31del branch : C23039G,C26858T,C22350T, del21650

**Comment by Mydtlwn** [comment]
Label S:1263？

**Comment by FedeGueli** [comment]
@aviczhl2 i ve just noticed that one of these sequence has **S:N30Del** ! that was more widespread than i thought in JN.1
the sequence is EPI_ISL_19110635  from Western Australia, but when checking for it on Nextclade...Surprise it is actually a double del S:30-31 plus S:F32I !
<img width="538" alt="Screenshot 2024-05-14 alle 01 28 01" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3a9126e1-55cb-46d0-b778-c3177ae2aeda">

@ryhisner @aviczhl2 @corneliusroemer @angiehinrichs i am not super sure all of these are real:

<img width="928" alt="Screenshot 2024-05-14 alle 01 29 36" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/03a19ecd-2a71-47a3-911c-d91576c0499f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_33a3f_2a1230.json?f_userOrOld=uploaded%20sample&label=id:node_6931962

**Comment by FedeGueli** [comment]
+3 SA

**Comment by FedeGueli** [comment]
Parental designated KP.3.2 from 22858T

**Comment by FedeGueli** [comment]
Desingated KP.3.2.1 from https://github.com/cov-lineages/pango-designation/commit/7beae7dbb9f743197dafd30976413a1e413ae28e

**Comment by FedeGueli** [comment]
third sequence from West Australia

**Comment by aviczhl2** [comment]
The 30-31del sub-branch is still at 3.

**Comment by FedeGueli** [comment]
> The 30-31del sub-branch is still at 3.Yeah thx, this is important to highlight the N GLycan is what gives superpowers to S:S31del . Thx for tracking
