### ISSUE TITLE
LF.3.1 (FLiRT+ S:V445P)  with S:P>L1143F (42)  

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1558]
Very early to propose but there could be a trend toward 445P in lineages with S:F456L, caught first by @doropfan, 

LF.3 [Jn.1.16.1>  C5581A, C7594T, Orf1a:A4285V (C13119T) ]> S:V>H445P ( T>A22896C) 
[_alternative placement JN.1.42 (C5581A) >> FLirt >> S:445)  analysed by @aviczhl2_ ]
Query:C13119T,C5581A, C7594T,T22896C
Samples: 4 (California) (3 on Gisaid)
First collected on 2024-05-01
IDs: 
EPI_ISL_19101707, EPI_ISL_19101709, EPI_ISL_19135408, USA/2024CV0744/2024|PP747627.1

Tree:
<img width="1170" alt="Screenshot 2024-05-14 alle 10 32 28" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3160e5ab-e75e-43f0-92ae-fd1e113fc3aa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5f6c9_31e760.json?c=userOrOld&label=id:node_7124795

This very new lineage has been already splitted in tweo branches that both carry spike mutations:

Branch 1 with **S:P>L1143F** 
Jn.1.16.1>  C5581A, C7594T, Orf1a:A4285V (C13119T) > S:V>H445P ( T>A22896C) > C13860T > C10894T, C18888T, C20628T,   S:P>L1143F ( C24989T)
Query: C10894T, C18888T,T3565C

Branch 2 with **S:D745A**
Jn.1.16.1>  C5581A, C7594T, Orf1a:A4285V (C13119T) > S:V>H445P ( T>A22896C) > S:D745A (A23796C)
Query: T22896C,A23796C,T3565C

Note: This was formerly placed not under JN.1.16.1 and it has been tracked as Branch 124 in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089

**Comment by aviczhl2** [comment]
This shall be sub-branch of JN.1.42 due to C5581A.

**Comment by FedeGueli** [comment]
Thx added that placement as hypothesis as of today, we will se if more will pop up. i m curious to see where JN.1.42 emerged first

**Comment by FedeGueli** [comment]
5

**Comment by FedeGueli** [comment]
parental lineage designated LF.3

**Comment by FedeGueli** [comment]
DESIGNATED LF..3.1 VIA https://github.com/cov-lineages/pango-designation/commit/33233d80f4843ff07edacd8549d520f5f7450186

**Comment by Memorablea** [comment]
Hello, I found it here due to observing many S: V445P sequences. May I ask, what role does S: V445P exhibit in the sequence? How should we view a mutation that has been observed in a previous sequence but has no growth advantage?

**Comment by FedeGueli** [comment]
> Hello, I found it here due to observing many S: V445P sequences. May I ask, what role does S: V445P exhibit in the sequence? How should we view a mutation that has been observed in a previous sequence but has no growth advantage?

445P was in all XBB so for sure not bad. JN.1.50 with it is one of the fastest lineage. Most of sequences with it at the start of Jn.1 wave were artifacts likely. and likely it works well with 456L with some Epistatic effect.

**Comment by FedeGueli** [comment]
proposed now:; https://github.com/cov-lineages/pango-designation/issues/2669

**Comment by FedeGueli** [comment]
Designated LF.3.1.1 via https://github.com/cov-lineages/pango-designation/commit/b0a4a61f6bbc49802b3e644a3117e48fb0426372

**Comment by xz-keg** [comment]
The S:D745A branch is designated LF.3.1.2
