### ISSUE TITLE
LB.1 with S:∆S31, R190T (5 seq, 4 countries including Qatar) + Recombinant with KP.2 (1 seq, Canada) + Recombinant with KP.3.2 (4 seq, Sweden,Spain) [May 27]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1559]
**Description of LB.1 + S:∆S31, R190T, ORF1b:G2068R**
**Sub-lineage of:** LB.1 (JN.1 + S:Q183H, S:R346T, S:F456L)
**Earliest sequence:** 2024-4-21, Qatar (sample from traveler to New York, USA)
**Most recent sequence:** 2024-4-21, Qatar (sample from traveler to New York, USA) 
**Continents circulating:** Asia (1)
**Countries circulating:** Qatar (1)
**Number of Sequences:** 1
**GISAID Nucleotide Query:** [Edited  by mod: i suggest to use **G22111T, G22131C, G22599C, T22928C**]
 vs Original query: G22111T, G22131C,T3565C 
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [3-of: G19669A, G22111T, G22131C]
**Substitutions/Deletions on top of LB.1:**
**Spike:** ∆S31, R190T
**ORF1b:** G2068R (NSP15_G17R)
**Nucleotide:** C8692T, ∆21653-21655, G19669A, G22131C
**Usher Tree** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/LB.1_S31del_R190T.json?c=gt-S_190&gmax=25384&gmin=21563&label=id:node_2409627
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19108797
</details>
<img width="1493" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/de7f82d5-a301-44b3-8048-50f663f1e4a6">

**Description of LB.1 + S:∆S31, R190T/KP.2 Recombinant**
**Recombinant of:** LB.1 (JN.1 + S:Q183H, S:R346T, S:F456L) + ∆S31, R190T and KP.2
**Breakpoint:** 22131-24871 
**Earliest sequence:** 2024-4-22, Canada, Quebec — EPI_ISL_19118127
**Most recent sequence:** 2024-4-22, Canada, Quebec — EPI_ISL_19118127
**Continents circulating:** North America (1)
**Countries circulating:** Canada (1)
**Number of Sequences:** 1
**GISAID Nucleotide Query:** G17334T, G22111T, G22131C
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [3-of: G17334T, G22111T, G22131C]
**Substitutions/Deletions on top of LB.1 + S:∆S31, R190T/KP.2:**
**ORF3a:** P104T
**Nucleotide:** C4891T, C25702A
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/LB.1_S31del_R190T_KP.2%20Recomb.json?c=gt-S_190&gmax=25384&gmin=21563
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19118127
</details>
<img width="1412" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2cbcb559-f9f2-43f9-9f98-36fe4f1afdb1">

**Description of LB.1 + S:∆S31, R190T/KP.3 Recombinant**
**Recombinant of:** LB.1 (JN.1 + S:Q183H, S:R346T, S:F456L) + ∆S31, R190T and KP.3
**Breakpoint:** 22131-22599
**Earliest sequence:** 2024-5-2, Sweden, Varmland
**Most recent sequence:** 2024-5-2, Sweden, Varmland
**Continents circulating:** Europe (1)
**Countries circulating:** Sweden  (1)
**Number of Sequences:** 1
**GISAID Nucleotide Query:** G22111T, G22131C, C23039G
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [3-of: G22111T, G22131C, C23039G]
**Substitutions/Deletions on top of LB.1 + S:∆S31, R190T/KP.3:**
**Nucleotide:** C22858T
**USHER Tree** https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/LB.1_S31del_R190T.json?c=gt-S_190&gmax=25384&gmin=21563&label=id:node_2409627
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19136338
</details>

Normally I would ignore singlet recombinants, but these seem quite unusual. The original lineage has only been detected in a traveler to the USA (New York) from Qatar. Yet there are already two recombinants of this lineage on two different continents, meaning that this lineage has spread to three continents and already undergone two recombinations with fast-growing, recent lineages. It seems very likely to me that this lineage is widespread and growing rapidly in some unsampled part of the world.

**Comment by FedeGueli** [comment]
Great catch Ryan! i ve modified the query of the non recombinant( DONOR ) to exclude its recombinant : new query: G22111T, G22131C,T3565C . It is enough to remove T3565C to catch all the four samples.

**Comment by FedeGueli** [comment]
Second sequence for the KP.3 recomb, this time from... Spain! (it seems everything fast is there right now)

**Comment by corneliusroemer** [comment]
Hah, I independently found this LB.1 + 190T / KP.3.2 recombinant:

```
hCoV-19/Sweden/S-1260950467R4/2024|EPI_ISL_19136338|2024-05-02
hCoV-19/Spain/CT-HUVH-E46508/2024|EPI_ISL_19165017|2024-05-20
```

Breakpoint between 22132 (S:190T) and 22599 (S:346T) - fascinating that it chose to get rid of 346T, as if that wasn't useful in KP.3

The donor is KP.3.2 by the way, as it contains C22858T

<img width="2086" alt="Brave Browser 2024-05-28 18 45 24" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/936f4356-abbe-4948-9f5d-bf271344ddbf">

Query is: `G22111T,G22131C,C22858T`

**Comment by FedeGueli** [comment]
Same thought on 346T .

**Comment by ryhisner** [comment]
Yeah, I've thought from the beginning that KP.3 probably would not get R346T. It's always been bad on an N450D background, and Q493E is in the same region as both residues, making me suspect KP.3 has found a way to evade antibodies without suffering the ill effects of the R346T-N450D combo.

**Comment by FedeGueli** [comment]
5 with G22111T, G22131C, G22599C, T22928C, 

Updated tree:
<img width="1161" alt="Screenshot 2024-06-04 alle 00 17 00" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/eb6d2b14-d997-4d6b-8779-cb5c2cd320d2">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5af81_e3fa60.json?label=id:node_7131110

**Comment by HynnSpylor** [comment]
2 more LB.1 x KP.3.2 recombinant in Spain. Interesting

**Comment by corneliusroemer** [comment]
This designation will help untangle/monitor stuff here:

commit 03122159898f6456c28d8bc616d08ba503c57e49 (HEAD -> master, origin/master, origin/HEAD)
      2 Author: Cornelius Roemer <cornelius.roemer@gmail.com>
      3 Date:   Tue Jun 4 13:22:27 2024 +0200
      4 
      5     Designate LB.1.2 (ORF1b:G2068R) and LB.1.2.1 (S:R190T)
      6     
      7     See https://github.com/sars-cov-2-variants/lineage-proposals/issues/1559
      8     for discussion of this branch and potential recombinants
      9

**Comment by corneliusroemer** [comment]
@HynnSpylor - hah I just saw this as well - I hadn't read your comment before.

Can someone do a proper recombinant analysis, with breakpoints? Then we can designate it!

Speaking of this one:

```
Description of LB.1 + S:∆S31, R190T/KP.3 Recombinant
Recombinant of: LB.1 (JN.1 + S:Q183H, S:R346T, S:F456L) + ∆S31, R190T and KP.3
Breakpoint: 22131-22599
Earliest sequence: 2024-5-2, Sweden, Varmland
Most recent sequence: 2024-5-2, Sweden, Varmland
Continents circulating: Europe (1)
Countries circulating: Sweden (1)
Number of Sequences: 1
GISAID Nucleotide Query: G22111T, G22131C, C23039G
CovSpectrum Query: Nextcladepangolineage:JN.1* & [3-of: G22111T, G22131C, C23039G]
Substitutions/Deletions on top of LB.1 + S:∆S31, R190T/KP.3:
Nucleotide: C22858T
USHER Tree https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/LB.1_S31del_R190T.json?c=gt-S_190&gmax=25384&gmin=21563&label=id:node_2409627
Genomes
```

Very interesting Spike, combination of the 2 fittest lineages around, and spotted in 2 countries, and in sentinel surveillance over time, so unlikely this is unreal.

**Comment by corneliusroemer** [comment]
Designated as XDY in https://github.com/cov-lineages/pango-designation/commit/e14d5bfd8745f3da579dd5c8a48cfe254e75589b

**Comment by FedeGueli** [comment]
> Designated as XDY in [cov-lineages/pango-designation@e14d5bf](https://github.com/cov-lineages/pango-designation/commit/e14d5bfd8745f3da579dd5c8a48cfe254e75589b)

Sorry @corneliusroemer for some reasons i didnt receive the notifications of your comments
