### ISSUE TITLE
Very weirdly xbb.1.5 branch assigned to B by Usher

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#156]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_e516_47a4e0.json
![Schermata 2023-06-10 alle 15 29 35](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c4cc57ce-f0d3-4699-bb10-40e31729c5f5)

CC @angiehinrichs i noticed this weirdness

**Comment by AngieHinrichs** [comment]
Yikes, a mini-Omicron anchored in the wrong place by a few partial sequences!  Thanks @FedeGueli, I will fix that ASAP.
