### ISSUE TITLE
JN.1+S:S27L (approx. 204 sequences, 13 countries, mainly in China)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1561]
JN.1> A29086T> C21642T(S:S27L)
C21642T makes S:del24-26, A27S become del25-27.
As the mutation is next to deletion, it is analyzed as the moving of the deleted section, and could not be analyzed with Usher.
Query: -T21633C, del21635_21643, A29086T
China 150(1 from Japan, 1 from Ethiopia, 1 from Macao SAR), Japan 4, Korea 4, Thailand 1, Finland 1, Russia 1, Switzerland 3, UK 1, Canada 4, US 26(1 from Hong  Kong SAR, China), Australia 6, Malaysia 2

**Comment by Over-There-Is** [comment]
some sequences are misplaced on JN.1.32(S:T572I) branch. They should be JN.1> S:S27L> S:T572I.

**Comment by Over-There-Is** [comment]
21634-21642N=21635-21643N=del21635-21643=C21642T

**Comment by Over-There-Is** [comment]
Sequences with 21634-21642N or 21635-21643N instead del21635-21643:
EPI_ISL_18961249, EPI_ISL_18982953, EPI_ISL_19025103, 
EPI_ISL_19025135, EPI_ISL_19028387, EPI_ISL_19040230, 
EPI_ISL_19040241, EPI_ISL_19040253, EPI_ISL_19041015, 
EPI_ISL_19061149, EPI_ISL_19061150, EPI_ISL_19061214, 
EPI_ISL_19086922, EPI_ISL_19150429, EPI_ISL_19150490, 
EPI_ISL_19150511
Only sequences from China is included.

**Comment by Over-There-Is** [comment]
Henan/PYCDC-LG0214/2024|EPI_ISL_19028479|2024-03-12 29086 drop out
other sequences lack evidence to prove A29086T

**Comment by Over-There-Is** [comment]
some sequences matching the query -T21633C, del21635_21643, A29086T don't belong to this branch.

**Comment by Over-There-Is** [comment]
Some already known subbranches: G28423A(28), T692G(23), C23277T(S:T572I, 11)

**Comment by Over-There-Is** [comment]
covSPECTRUM query: nextcladePangoLineage:JN.1 & A29086T & [1-of: T21633T, G21642T]

**Comment by FedeGueli** [comment]
only two recent samples closing it for now

**Comment by Over-There-Is** [comment]
232
