### ISSUE TITLE
KP.3.1 with S:31del [18 seq, Basque, Extremadura,Madrid, Catalunya- Spain, Italy, USA, Wales]

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#1563]
Defining mutations:
KP.3.1 (G15372T, A19722G) > C12616T >Orf1a:S4286C (A13121T) S:S31del(del21653-55)

**GISAID query**: C12616T,A13121T

Credit to @FedeGueli for the query. 

Earliest seq: April 30. 
Recent seq: May 06. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/feff495e-9542-4e37-b48a-4dae4f133a75)

**Discussion:** So far this is one of two KP.3 branches with S:31del. Although there are KP.3s with other S:31 mutations, S:31del appears to be the best mutation for that region, based on how it is performing in FLiRT variants. Since KP.3 is growing faster than FLiRT that do not have S:31del, it is likely that this sublineage will be faster than FLiRT with S:31del, which would make this a potential top variant today.

**Comment by FedeGueli** [comment]
Just noticed it is a KP.3.1 sublineage now.

**Comment by FedeGueli** [comment]
+2 one new area in northern Spain: Badajoz Extremadura

**Comment by FedeGueli** [comment]
@Sinickle please propose it when it reaches 10seqs

**Comment by FedeGueli** [comment]
+1 Madrid

**Comment by JosetteSchoenma** [comment]
+2 Spain, Sevilla

**Comment by FedeGueli** [comment]
ping @corneliusroemer

**Comment by JosetteSchoenma** [comment]
+1 USA traveler from Italy

**Comment by JosetteSchoenma** [comment]
+1 Wales

**Comment by JosetteSchoenma** [comment]
+2 Spain, Basque

**Comment by FedeGueli** [comment]
+1 Catalunya

**Comment by aviczhl2** [comment]
Designated KP.3.1.1
