### ISSUE TITLE
KP.3.1 + S:S31del and S:A1078S in NZL (2) spotted by Josette Shoenmakers

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1564]
Credit : @JosetteSchoenma spotted it

Defining mutations:
KP.3.1 > 
ORF1a:T1597I (C5055T), Orf1b:A2222V (C20132T), S:A1078S (G24794T), N:P67L (C28473T), N:T417I (C29523T)
New Queries: -G22111T,C5055T,del21653,T3565C, -A13121T,-C12616T
Old Queries: **C20132T, G24794T,del21653** or  **C28473T,C29523T,del21653**  
Samples: 2 New Zealand
EPI_ISLs: EPI_ISL_19142767-19142768

Tree:
<img width="1101" alt="Screenshot 2024-05-17 alle 16 41 40" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7f28a0e6-250f-418a-8867-bbe66bca6c93">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_630e2_752b80.json?c=gt-S_1078&gmax=25384&gmin=21563

**Comment by aviczhl2** [comment]
So these 2 are different lineages, or shall they share a same parent of KP.3.1+S31del?

**Comment by FedeGueli** [comment]
To me  they are different

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
This revived new query:-G22111T,C5055T, del21653,T3565C, --A13121T,-C12616T 
New samples came from Singapore Israel and Australia
