### ISSUE TITLE
KS.1 (JN.1.13.1.1) + S:T22N (glycan) [12 seq, May 17]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1565]
**Description**
**Sub-lineage of:** KS.1 (JN.1.13.1.1) = JN.1 + S:F59S, S:R346T, S:F456L, S:A1087S
**Earliest sequence:** 2024-4-15, Singapore
**Most recent sequence:** 2024-5-8, Taiwan
**Continents circulating:** Asia (7), North America (5)
**Countries circulating:** Singapore (6), Canada (5), Taiwan (1)
**Number of Sequences:** 12
**GISAID Nucleotide Query:** C19716T, C21627A, T21738C
**CovSpectrum Query:** Nextcladepangolineage: JN.1.13* & [2-of: T21738C, C21627A]
**Substitutions on top of X:**
**Spike:** T22N (adds glycan)
**Nucleotide:** C19716T, C21627A 

**Phylogenetic Order of Mutations:** C19716T & C21627A (S:T22N) both gained on same branch (as it now appears)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KS.1_T22N.json?branchLabel=nuc%20mutations&c=gt-nuc_19716&gmax=20716&gmin=18716&label=id:node_7127001
<img width="1510" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/4978736f-eb47-4317-b339-898637a836a0">

**Evidence**
Like S:∆S31, T22N adds a glycan in the N1 NTD loop. The reference-genome residue numbers make these glycans seem far apart (S:22 and S:30), but the S:24-26 deletion in all BA.2 means these glycans are only separated by 5 AA. The distinct growth advantage of S:∆S31 suggests that S:T22N might convey an advantage as well. Recent collection dates and sequences in two very distant regions of the world (SE Asia and Canada) make this one worth monitoring. 

Usher fails to register S:T22N for the majority of the sequences here, presumably because so many labs are still unable to register either BA.2.86's MPLF insertion or BA.2's S:∆24-26.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19095650, EPI_ISL_19095653, EPI_ISL_19095801, EPI_ISL_19095899, EPI_ISL_19095929, EPI_ISL_19096025, EPI_ISL_19100317, EPI_ISL_19119032, EPI_ISL_19119211, EPI_ISL_19119226, EPI_ISL_19130961, EPI_ISL_19134178
</details>

**Comment by FedeGueli** [comment]
Designated KS.1.1 via https://github.com/cov-lineages/pango-designation/commit/c1b4638bf723c29be72904147477ec8880dfae65
