### ISSUE TITLE
XBB.1.19.1 sublineage with ORF1a:D264N and N:M322V circulating in Beijing(135 seq, 8 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#157]
XBB.1.19.1> G1055A(Orf1a:D264N), G10465A, C15960T> C10186T> C28519T, A29237G(N:M322V)
Query: G23222A, G1055A, A29237G

Earliest Sequence: 03-26 Beijing, China EPI_ISL_17592189

Latest Sequence: 06-14 Ontario, Canada EPI_ISL_17814837

Regions Detected:
**China** 118+1: Beijing 66, Xinjiang 26, Jiangxi 6, Jiangsu 4, Shanghai 4(1 import from **UK**), Fujian 2, Guangdong 2, Hubei 2, Yunnan 2, Anhui 1, Henan 1, Qinghai 1, Sichuan 1; Taiwan 1(import from **Thailand**).
**Canada**(Ontario) 9, **Singapore**(Local) 2, South Korea 2, **US**(NYC) 2, **Portugal** 1

Since all the sequences uploaded by Beijing CDC are not visible for 1 month, and the nearby provinces (e.g. Tianjin, Hebei, Inner Mongolia, Shandong) have not uploaded any sequences recently, this sublineage has circulated for a long time.
[usher](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_303b8_577d40.json?label=id:node_10276361)
![2023-06-11 (11)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/65a8baee-e02b-4671-a244-9a92e69ab95b)

<details><summary>Sequences</summary>
EPI_ISL_17536875, EPI_ISL_17592189, EPI_ISL_17625469,
EPI_ISL_17637375, EPI_ISL_17637380, EPI_ISL_17671942,
EPI_ISL_17671960, EPI_ISL_17689350, EPI_ISL_17689510,
EPI_ISL_17694807, EPI_ISL_17697556, EPI_ISL_17698196,
EPI_ISL_17714411, EPI_ISL_17717557, EPI_ISL_17723132,
EPI_ISL_17724741, EPI_ISL_17725149, EPI_ISL_17725298,
EPI_ISL_17725488, EPI_ISL_17729772, EPI_ISL_17770415,
EPI_ISL_17775166, EPI_ISL_17775186, EPI_ISL_17775233,
EPI_ISL_17775235, EPI_ISL_17775296, EPI_ISL_17775309,
EPI_ISL_17775313, EPI_ISL_17775317, EPI_ISL_17775351,
EPI_ISL_17775532, EPI_ISL_17775570, EPI_ISL_17775587,
EPI_ISL_17775601, EPI_ISL_17775603, EPI_ISL_17775653,
EPI_ISL_17775673, EPI_ISL_17778677, EPI_ISL_17783601,
EPI_ISL_17784907, EPI_ISL_17784933, EPI_ISL_17784935,
EPI_ISL_17784937, EPI_ISL_17784940-17784952, EPI_ISL_17784964-17784965,
EPI_ISL_17784978, EPI_ISL_17784983, EPI_ISL_17784986,
EPI_ISL_17785024, EPI_ISL_17785027, EPI_ISL_17785030,
EPI_ISL_17785044, EPI_ISL_17785048-17785049, EPI_ISL_17785051,
EPI_ISL_17785064-17785066, EPI_ISL_17785068-17785069, EPI_ISL_17785072-17785073,
EPI_ISL_17785075-17785077, EPI_ISL_17785080, EPI_ISL_17785083,
EPI_ISL_17785086, EPI_ISL_17785089, EPI_ISL_17785096,
EPI_ISL_17785098-17785101, EPI_ISL_17785104-17785105, EPI_ISL_17785117,
EPI_ISL_17785125-17785126, EPI_ISL_17785133, EPI_ISL_17785135-17785136,
EPI_ISL_17785149, EPI_ISL_17785153, EPI_ISL_17785156,
EPI_ISL_17785161, EPI_ISL_17785176, EPI_ISL_17785184,
EPI_ISL_17785189, EPI_ISL_17785191, EPI_ISL_17785215,
EPI_ISL_17786195, EPI_ISL_17794034, EPI_ISL_17794537,
EPI_ISL_17794541, EPI_ISL_17794558-17794559, EPI_ISL_17794575,
EPI_ISL_17794582, EPI_ISL_17795052, EPI_ISL_17801780,
EPI_ISL_17814668, EPI_ISL_17814702, EPI_ISL_17814704-17814705,
EPI_ISL_17814811-17814812, EPI_ISL_17814814, EPI_ISL_17814836-17814837,
EPI_ISL_17834810, EPI_ISL_17835325, EPI_ISL_17836286,
EPI_ISL_17836288, EPI_ISL_17836297-17836298, EPI_ISL_17836300,
EPI_ISL_17836302-17836303, EPI_ISL_17836305, EPI_ISL_17836307,
EPI_ISL_17836355
</details>

**Comment by Over-There-Is** [comment]
On the latest covid weekly report by China CDC, a portion of XBB.1.19.1 in Beijing is shown.
![W020230429583275216453](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/32543689-f29b-4e68-8a32-15e09ecaf507)
![W020230429583275242891](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/36939691-acfc-4996-ba07-9ca528888968)

Not only Beijing, there are also other provinces like Jiangxi, Hunan, Chongqing and Guangxi have sequenced some samples but did not upload to public platforms like GenBase or GISAID. With the report, we can know that the predominant lineage of Beijing is XBB.1.19.1, and XBB.1.9.1 for Chongqing, XBB.1.5.15(probalbly FD.2) for Guangxi, XBB.1.16.1(probably FU.1+A460G) for Jiangxi. Although the second infection wave is not start in Hunan then, we can know that XBB.1.9.1 is detected there.

And China CDC's covid report updates monthly now, and the concrete lineages are not shown anymore. According to the report, only less than 42% of sequences are uploaded to GISAID.

> 　　2023年5月1日-5月31日，全国31个省（自治区、直辖市）及新疆生产建设兵团共报送14732例本土病例新冠病毒基因组有效序列，均为奥密克戎变异株，涵盖160个进化分支，主要流行株为XBB系列变异株，占比前三位的分别为XBB.1.9及其亚分支、XBB.1.16及其亚分支、XBB.1.5及其亚分支。
>  　　*From May 1 to May 31, 2023, 14732 valid SARS-CoV-2 genome sequences from domestic cases were reported nationwide, all of which were Omicron variants with a total of 160 lineages. The predominant lineages are XBB series, and the top three are XBB.1.9 and its descendant lineages, XBB.1.16 and its descendant lineages and XBB.1.5 and its descendant lineages.*
> 
> 　　根据采样日期， XBB及其亚分支的占比逐渐增加，从5月1日-5月7日的84.6%，增长到5月22日-5月28日的92.4%。见图4。
>  　　*According to the sampling date, the proportion of XBB and its descendant lineages is increasing, from 84.6% in May 1-7, increased to 92.4 in May 22-28. (Figure 4)*

![W020230611553892114419](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/c4d40344-e1ba-4ee2-825a-94d4b1dc54ce).

Among the sequences uploaded by Beijing in April (publicized in May), only 1 sequence is XBB.1.19.1. Although multiple provinces have detected XBB.1.19.1 already, the amount is still too small to attract us.

**Comment by aviczhl2** [comment]
>Among the sequences uploaded by Beijing in April (publicized in May), only 1 sequence is XBB.1.19.1. Although multiple provinces have detected XBB.1.19.1 already, the amount is still too small to attract us.

But there's at least 66 Beijing XBB.1.19.1 of this one on GISAID.

**Comment by Over-There-Is** [comment]
> > Among the sequences uploaded by Beijing in April (publicized in May), only 1 sequence is XBB.1.19.1. Although multiple provinces have detected XBB.1.19.1 already, the amount is still too small to attract us.
> 
> But there's at least 66 Beijing XBB.1.19.1 of this one on GISAID.

But these sequences are uploaded on May 11 and publicized yesterday.

**Comment by FedeGueli** [comment]
Lets see if it spreads outside China as did inside it.  Then it could be proposed.

**Comment by Over-There-Is** [comment]
Ontario +9

**Comment by Over-There-Is** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/73e901b6-38e5-42df-a407-5449d1931065)
this one is recombined with XBB.1.5\*?

**Comment by Over-There-Is** [comment]
South Korea+2

**Comment by FedeGueli** [comment]
Designated GW.1 
https://github.com/cov-lineages/pango-designation/commit/ca84b0984bf60af852262f8e84cd1f59f4608e68

**Comment by Over-There-Is** [comment]
May you add a milestone please?

**Comment by FedeGueli** [comment]
Hi @Over-There-Is we are not giving milestones here (but also  i think in the main page some are missing too.) I commented in the commit and that is what does count.

**Comment by Memorablea** [comment]
> Hi @Over-There-Is we are not giving milestones here (but also i think in the main page some are missing too.) I commented in the commit and that is what does count.

I think it's best to add a milestone or use other methods

**Comment by FedeGueli** [comment]
@Memorablea i add the label designated.it is the max we can do here. If you found something designated without the proper label let me know i will do for sure. Being in the commits credit are there . Next time i will add also the name of the spotter there.

**Comment by Memorablea** [comment]
> @Memorablea i add the label designated.it is the max we can do here. If you found something designated without the proper label let me know i will do for sure. Being in the commits credit are there . Next time i will add also the name of the spotter there.

I understand. Thank you for your excellent work

**Comment by FedeGueli** [comment]
> > @Memorablea i add the label designated.it is the max we can do here. If you found something designated without the proper label let me know i will do for sure. Being in the commits credit are there . Next time i will add also the name of the spotter there.
> 
> I understand. Thank you for your excellent work

Thank you. happy to help.

**Comment by Over-There-Is** [comment]
Milestone

**Comment by Over-There-Is** [comment]
C28519T = Orf9b:T79I
