### ISSUE TITLE
KP.3.1 with G22599T（S:R346I）singlet（1seqs from France）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1571]
KP.3.1 (G15372T, A19722G) > ORF1a:Q998H (G3259T), T5773C, C4586T, G19962A, **S:R346I (G22599T)**

EPI_ISL_19139125,Collection date: 2024-04-04,France
GISAID Query:G3259T, C4586T, C7113T, G15372T, G22599T, T22928C, G24872T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_16cb3_98f130.json?f_userOrOld=uploaded%20sample
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/c9885b9c-e173-48d6-900b-6d1b2e0bd0fe)

**Comment by FedeGueli** [comment]
Thx! It was tracked in #1089 singlets section, but good to propose it

**Comment by Memorablea** [comment]
> Thx! It was tracked in #1089 singlets section, but good to propose it

Oh sorry, I didn't see it! Do I need to close it?

**Comment by FedeGueli** [comment]
> > Thx! It was tracked in #1089 singlets section, but good to propose it
> 
> Oh sorry, I didn't see it! Do I need to close it?

No no let it open it is good to see if any 346X works with 493E , there are different opinions on that , lets see.
