### ISSUE TITLE
XDK+S:F456L on C29762T branch (45)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1572]
XDK> C29762T> T22297C, T22928C
(Not to be confused with T22927C)

Query: C5314T, T22297C, T22928C

EDITED By @FedeGueli : Most of the samples now have also S:N237K and S:Q1201K  .
Mutation in the branch : XDK> C5314T > A1633G, S:N237K (G22272A), T22297C ,S:F456L (T22928C) , S:Q1201K (C25162A, C25163A) 

Earliest sequence: 04-16 Shatin, Hong Kong SAR, China EPI_ISL_19146025
Latest sequence: 05-09 England, United Kingdom EPI_ISL_19146708
Regions Detected: UK 43(England), China 2(Hong Kong)

Tree updated on May 23:
<img width="1171" alt="Screenshot 2024-05-23 alle 14 11 22" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4d6da91e-c465-4473-a8ab-5ede0d857a5e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4266b_f31600.json?label=id:node_7033495

Sequences:
EPI_ISL_19088230, EPI_ISL_19088237, EPI_ISL_19133005,
EPI_ISL_19133026, EPI_ISL_19133032, EPI_ISL_19133042,
EPI_ISL_19139191, EPI_ISL_19139197, EPI_ISL_19143961,
EPI_ISL_19146025, EPI_ISL_19146029, EPI_ISL_19146684,
EPI_ISL_19146688, EPI_ISL_19146702, EPI_ISL_19146706,
EPI_ISL_19146708, EPI_ISL_19146773, EPI_ISL_19151204,
EPI_ISL_19157209-19157214, EPI_ISL_19157216-19157217, EPI_ISL_19157219-19157220,
EPI_ISL_19157223, EPI_ISL_19157231-19157233, EPI_ISL_19157235,
EPI_ISL_19157238, EPI_ISL_19157241, EPI_ISL_19157248,
EPI_ISL_19157250, EPI_ISL_19157264, EPI_ISL_19157270-19157271,
EPI_ISL_19157274, EPI_ISL_19157277-19157279, EPI_ISL_19157287,

**Comment by aviczhl2** [comment]
17 seqs now

**Comment by FedeGueli** [comment]
Jumped to 45!

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by FedeGueli** [comment]
Edited the proposal it seems it has also S:N237K and S:Q1201K, but i think it is a couple of english cluster.

**Comment by Over-There-Is** [comment]
the new tree is too flip-flopped.

**Comment by Over-There-Is** [comment]
only a part of british sequences have C25162A, C25163A.

**Comment by Over-There-Is** [comment]
it seems these sequences have mutation on 28371 too, but it's not shown on usher.

**Comment by Over-There-Is** [comment]
the real tree would be more similar to this:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/caa338c3-402b-4354-bedb-8d8e47f59148)

**Comment by FedeGueli** [comment]
Thanks for proposing it. @ryhisner could you take a look at the deletion at N:33 it seems a similar pattern to BF.7 

BF.7 deletion:
<img width="222" alt="Screenshot 2024-05-25 alle 17 22 01" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/76e6508e-a415-4360-9503-c1ca202cdecd">

XDK Deletion:
<img width="263" alt="Screenshot 2024-05-25 alle 17 23 06" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0a153fb7-3c15-4e97-8887-9bbf5eee0580">

**Comment by FedeGueli** [comment]
Designated XDK.6 via https://github.com/cov-lineages/pango-designation/commit/8bd6644bd4309f49d32f5a6f801346269d2529de
