### ISSUE TITLE
KP.3.1 + S:E309Q, ORF9b:V41A [13 seq, Canada]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1574]
**Description**
**Sub-lineage of:** KP.3.1.
**Earliest sequence:** 2024-4-22
**Most recent sequence:** 2024-5-13
**Continents circulating:** North America (7)
**Countries circulating:** Canada (7)
**Number of Sequences:** 7
**GISAID Nucleotide Query:** C2232T, T28405C 
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of KP.3:**
**Spike:** E309Q
**ORF1a:** A537S (NSP2_A357S)
**ORF9b:** V41A
**Nucleotide:** G210T, G1874T, C2232T, C2644T, C18570T, G22487C, T28405C 

**Phylogenetic Order of Mutations:** G1874T (ORF1a:A537S), C18570T **→** G210T (5' UTR), C2232T (ORF1a:A656V), C2644T, G22487C (S:E309Q), T28405C (ORF9b:V41A) 

**USHER Tree (temporary link)**
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_2d26b1_d39de0.json?label=id:node_5598188
<img width="1483" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/8a826fe2-3f75-4e35-9aa3-ea74f91bb82c">

**Evidence**
The metadata seem to indicate that this is not a nursing home cluster. Probably not significant, so I'm not doing a proper proposal yet. S:E309Q is interesting, and it's rare to see ORF9b mutations at V41. If it grows, I'll do better. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19086026, EPI_ISL_19136896, EPI_ISL_19151586,
EPI_ISL_19151588, EPI_ISL_19151619, EPI_ISL_19151623,
EPI_ISL_19151633
</details>

**Comment by FedeGueli** [comment]
11

**Comment by FedeGueli** [comment]
13, +2 Ontario

**Comment by aviczhl2** [comment]
15 but no June seqs, considering this is Canadian-only better close this.
