### ISSUE TITLE
JN.1.52 plus S:S31del S:R346I S:S704L (17 sequences, 5 countries, likely from Qatar )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1575]
New combination of advantageous mutations, better to track it publicly (mentioned in #1502 comment first)

JN.1.52  [Orf1a:K3353R (A10323G )] > S:S31del ( S:S704L (C23673T), Reversion defining JN.1 C>T25207C (S:Y1215Y) > S:R346I (C22599T )

Query: G22599T,del21653,C23673T
Countries: Germany, Denmark, Sweden, Qatar (via GBW) , Australia
Samples: 5 (7 on USher)
EPI_ISL_19117059, EPI_ISL_19136365, EPI_ISL_19136372,
EPI_ISL_19140700, EPI_ISL_19152988

Tree:

<img width="1126" alt="Screenshot 2024-05-22 alle 15 12 26" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9cdd8be9-aece-41e9-a879-ffb889a7f7cd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1d7f1_def0d0.json?label=id:node_7064182

_I have ignored the flip flop from 346T to 346I_

**Comment by FedeGueli** [comment]
Parent designated JN.1.52

**Comment by FedeGueli** [comment]
11 now with a new sample from Germany , and a cluster of 5 in Galicia.

**Comment by FedeGueli** [comment]
15 now +1 Germany , +3 Galicia and one ore GBW sample from Qatar

**Comment by FedeGueli** [comment]
ping @corneliusroemer it seems fast or likely somewhat prevalent in Qatar

**Comment by DailyCovidCases** [comment]
This branch might be dying now, please update it
