### ISSUE TITLE
 Multiple KP.3 and sub lineageas with S:S31F:

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1576]
Edited 14/7/24 because of designations and extra branches
KP.3 (S:Q493E=C23039G) plus S:S31F (=C21654T)

KP.3.1 (G15372T, A19722G)
KP.3.1.1 + S31F > query C12616T, A13121T, C21654T > 118 samples Denmark (considering this an artifact as long as it does not show up in another country)
KP.3.1.3 > G15372T, A19722G, C21654T,-C18490T,-T19305C,-A13121T,-C4084T,-C5413T,-A20458C > designated
KP.3.1.4 + S31F > query C18490T, A16474G, C21654T > 40 samples, Scotland, France (GBW) ( parental branch proposed [here](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1697) )
MK.1 (KP.3.1.6.1) > query T19305C, C21654T, C23039G > designated

KP.3.2 (A2611C, C22858T)
branch 1 > query C22858T, C21654T, C4345T > 36 samples, England
Pseudo branch 2 > T772C, T12101A > 29 samples, 8 countries
Actually a recombinant: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1650
Or https://github.com/cov-lineages/pango-designation/issues/2731
branch 3 > C21654T, A8302G > 32 samples, USA (1 traveler Qatar) and Mexico
KP.3.2.4 + S31F > A2611C, C25609T, C21654T > 2 samples, Spain , Portugal

KP.3.3 (C28884C)
Query G6545A, C14235T > 8 samples Japan

KP.3.4.1 > query C21654T, G3839A > designated

***********
Original
KP.3 seems to have gained S:S31F on 4 different branches, with samples from Canada, England, USA, Scotland and Spain. 
**EDITED** 19/6: 
Better KP.3.2 S31F query:
 C22858T, C21654T, C23039G

Edited 19/6 Another. KP.3 Query: C21654T, G3839A

**Original Proposal**
With the biggest branch of 5 samples having G15372T and A19722G. Query: Spike_Q493E, C21654T. Branch query:  G15372T, A19722G, C21654T 

Note: this is a downsampled tree! And the Scottish sample is being misplaced because of missing coverage.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/8b1a7aa7-8df3-444b-836c-cca68fea33cc)

**Comment by FedeGueli** [comment]
where is the other issue? the one with G15372T, A19722G, C21654T now at 6

**Comment by JosetteSchoenma** [comment]
12 in total now, 8 for the main branch

**Comment by JosetteSchoenma** [comment]
KP.3.1.3 has been assigned for the main branch

Since there is a branch (KP.3.2) that has grown to 7 now, I made a query for that one as well.
C7113T, C22858T, C21654T
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/f26f6cdd-5093-4e99-8dad-3a789831e312)


![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/466d0962-4c96-44d9-91de-67230fdfac13)

**Comment by FedeGueli** [comment]
First branch proposed now Designated KP.3.1.3 via https://github.com/cov-lineages/pango-designation/commit/000e4446ff22dd2a53003e11e26d99b2e3c6a2c6

**Comment by FedeGueli** [comment]
> KP.3.1.3 has been assigned for the main branch
> 
> Since there is a branch (KP.3.2) that has grown to 7 now, I made a query for that one as well. C7113T, C22858T, C21654T ![image](https://private-user-images.githubusercontent.com/94831035/336567007-f26f6cdd-5093-4e99-8dad-3a789831e312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDA4NjcsIm5iZiI6MTcxNzU0MDU2NywicGF0aCI6Ii85NDgzMTAzNS8zMzY1NjcwMDctZjI2ZjZjZGQtNTA5My00ZTk5LThkYWQtM2E3ODk4MzFlMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIyMzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NDBhZWI2YjQzZTEzYzZjMGFlNmZkZDc4Y2UyZTQ5NjhkNTZkMGQzYjdhYWNhZTMxYWViOGNhMGQyMjFhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1F_CzlCNQeCRLDGJl-Patt4kZTHfdLTvWklEMAMewfU)

i transfer this comment to main proposal

**Comment by JosetteSchoenma** [comment]
Here it is proposed that the first branch is actually 2 branches. So, not all KP.3.1.3.
Query: T19305C,C21654T,C23039G
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1605

**Comment by JosetteSchoenma** [comment]
New, hopefully better query of 4(?) branches of KP.3.2 plus S:S31F. 13 samples.
C22858T, C21654T, C23039G
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/687d9a69-1892-4eeb-93f5-c66dbf16cf48)

**Comment by JosetteSchoenma** [comment]
> New, hopefully better query of 4(?) branches of KP.3.2 plus S:S31F. 13 samples. C22858T, C21654T, C23039G ![image](https://private-user-images.githubusercontent.com/94831035/338973204-687d9a69-1892-4eeb-93f5-c66dbf16cf48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzA4MTQsIm5iZiI6MTcxODYzMDUxNCwicGF0aCI6Ii85NDgzMTAzNS8zMzg5NzMyMDQtNjg3ZDlhNjktMTg5Mi00ZWViLTkzZjUtYzY2ZGJmMTZjZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEzMjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjJmOTc0ZTRlMGFkZjA0M2ZiN2UyYTE5NzBjNDU5NWU2MjhlY2M0NmFlNzViODA2MmM5NzJiYjliMWQyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KzOAPavPDM9-k-QFd_gNw6n5iNn95cvM2JXt0nMCeVg)

16 now

**Comment by JosetteSchoenma** [comment]
KP.3.2 G15372T, A19722G, C21654T 22 now

**Comment by FedeGueli** [comment]
> C22858T, C21654T, C23039G

Please propose it

**Comment by JosetteSchoenma** [comment]
New branch. 8 samples 4 countries, mostly Australia.
Query: C21654T, G3839A
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/45b08f03-3f28-4e5a-a257-831a3a30aca5)

**Comment by JosetteSchoenma** [comment]
Query: C22858T, C21654T, C4345T
Because I doubt that the KP.3.2 has only one S31F branch, I made this new query to select for the biggest English branch. 15 samples.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/34439aa8-6aa9-4e89-8457-1a1560e9ce5b)

**Comment by JosetteSchoenma** [comment]
Query for another KP.3.2 plus S31F branch.
T772C, T12101A. 6 samples

**Comment by FedeGueli** [comment]
> Query for another KP.3.2 plus S31F branch. T772C, T12101A. 6 samples

now proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1650 by @aviczhl2 as a recombinant.

**Comment by JosetteSchoenma** [comment]
KP.3 branch almost at the bottom, 10 samples, 5 countries (1 English one not yet on GISAID)
Query: C3839A, C21654T, Spike_Q493E
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/b2002b99-30ba-4940-8f92-54890dcdab52)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/feba6deb-7fa4-4768-a6ed-9913f3c52a84)

**Comment by FedeGueli** [comment]
> KP.3 branch almost at the bottom, 10 samples, 5 countries (1 English one not yet on GISAID) Query: C3839A, C21654T, Spike_Q493E 

thx @JosetteSchoenma, i ve found a better query:  A12199G,C25609T, C23039G  (pls check if it is the same lineage, it gives 10 samples on Gisaid)

**Comment by JosetteSchoenma** [comment]
> A12199G,C25609T, C23039G

Yes, that's better @FedeGueli . It bypasses the missing coverage on AA 31 common in English samples.

**Comment by JosetteSchoenma** [comment]
> Query: C22858T, C21654T, C4345T Because I doubt that the KP.3.2 has only one S31F branch, I made this new query to select for the biggest English branch. 15 samples. ![image](https://private-user-images.githubusercontent.com/94831035/341846805-34439aa8-6aa9-4e89-8457-1a1560e9ce5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODY2ODAsIm5iZiI6MTcyMDE4NjM4MCwicGF0aCI6Ii85NDgzMTAzNS8zNDE4NDY4MDUtMzQ0MzlhYTgtNmFhOS00ZTg5LTg0NTctMWExNTYwZTljZTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEzMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4N2ZkNmU4Y2JhZWU3NjM4MzEzODVjNGY5MDhhZmNkMWFjYjYyNGQ2MTkwNWNmZTFlN2FkM2IwYzJmN2JkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AKS0mW2HRN2BoO6DiGYX_6Kuc9Rg-rxgzZMTPzeZ724)

This one is 32 samples now (Query: C22858T, C21654T, C4345T). 9 new ones from England today.

**Comment by aviczhl2** [comment]
> New branch. 8 samples 4 countries, mostly Australia. Query: C21654T, G3839A ![image](https://private-user-images.githubusercontent.com/94831035/340958882-45b08f03-3f28-4e5a-a257-831a3a30aca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODg4NTksIm5iZiI6MTcyMDc4ODU1OSwicGF0aCI6Ii85NDgzMTAzNS8zNDA5NTg4ODItNDViMDhmMDMtM2YyOC00ZTVhLWEyNTctODMxYTNhMzBhY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEyNDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDJkMjI5MjBhODdkZmY1Yzg5NWU3MzIxMTMxZWI0NjNmNzM1NTJkMzliN2ZjNDQ2OTU1NDU0M2JiNDc0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aohDqMg5ZefaddgJiawDq18t6svHv7baJTLQ16Iz284)

This shall be KP.3.4.1

**Comment by JosetteSchoenma** [comment]
New Japanese KP.3.3 plus S31F cluster. 8 samples. Query G6545A, C14235T

**Comment by FedeGueli** [comment]
> New Japanese KP.3.3 plus S31F cluster. 8 samples. Query G6545A, C14235T

@JosetteSchoenma could you edit the main proposal please recapitulaing all the lineages tracked and then designated and the ones still pending? it is enough > Lineage > QUery > Designated or count if not designated, because with updates in comments i get lost!

**Comment by FedeGueli** [comment]
Thank you very much @JosetteSchoenma

**Comment by FedeGueli** [comment]
Kp.3.1.3 query: G15372T, A19722G, C21654T,-C18490T,-T19305C i m checking if still good

**Comment by FedeGueli** [comment]
Updated with the KP.3.1.3 query

**Comment by JosetteSchoenma** [comment]
KP.3.1.1 + S31F > query C12616T, A13121T, C21654T > 16 samples Denmark

**Comment by aviczhl2** [comment]
> KP.3.1.1 + S31F > query C12616T, A13121T, C21654T > 16 samples Denmark I am not completely sure I can trust those sequences though.

KP.3.1.1 shall have S:31del.

**Comment by JosetteSchoenma** [comment]
> > KP.3.1.1 + S31F > query C12616T, A13121T, C21654T > 16 samples Denmark I am not completely sure I can trust those sequences though.
> 
> KP.3.1.1 shall have S:31del. 

KP.3.1.1 has 2 other defining mutations, which these samples have, but a S31F instead of S31del. But it seems strange and even though the samples look oke, Danish sequencing tends to do strange things with deletions.

**Comment by JosetteSchoenma** [comment]
KP.3.1.4 + S31F > query C18490T, A16474G, C21654T, Scotland growing from 9 to 21

**Comment by FedeGueli** [comment]
> KP.3.1.4 + S31F > query C18490T, A16474G, C21654T, Scotland growing from 9 to 21

this is a sub branch of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1697

**Comment by JosetteSchoenma** [comment]
> KP.3.1.4 + S31F > query C18490T, A16474G, C21654T, Scotland growing from 9 to 21

37  now

**Comment by JosetteSchoenma** [comment]
Adjusted the main comment. Especially KP.3.2 branch 2, 29 from 8 countries now

**Comment by FedeGueli** [comment]
> Adjusted the main comment. Especially KP.3.2 branch 2, 29 from 8 countries now

please propose it

**Comment by aviczhl2** [comment]
> > Adjusted the main comment. Especially KP.3.2 branch 2, 29 from 8 countries now
> 
> please propose it

It is #1650 .

**Comment by FedeGueli** [comment]
none of them seems fast

**Comment by ryhisner** [comment]
17 sequences from Mexico City just uploaded with S:S31F, N:T135I, ORF3a:L101I, ORF1a:P4337S, and ORF1b:L1504F, all collected July 15 or later. 

I assume it's the KP.3.2 lineage being discussed here. One previous travel sequence to the US from Qatar as well, collected June 25. 

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.2_S31F_etc.json?c=gt-N_135&gmax=29533&gmin=28274&label=id:node_7049793

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e8ab0104-adbb-49fe-aff8-7d42a59e22c5">

**Comment by aviczhl2** [comment]
New S31F branch under KP.3.2.3, Query: C6582T,A17712G,C21654T

![image](https://github.com/user-attachments/assets/d06f2062-43ad-40b6-96ce-c47f06971fd1)

**Comment by aviczhl2** [comment]
Everything seems resolved. Close this one.

**Comment by DailyCovidCases** [comment]
KP.3.1.3 branch now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_23684_5ef430.json?c=pango_lineage&f_userOrOld=uploaded%20sample)
https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?nextcladePangoLineage=KP.3.1.3*&
![Screenshot (252)](https://github.com/user-attachments/assets/218731d2-eb9b-4b1d-90ef-9b16956d068d)
