### ISSUE TITLE
101 JN.1 with S:R346T, S:F456L (FLiRT) and S:S31F. Many branches

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1577]
Query: Spike_S31F, Spike_R346T, Spike_F456L, T22926C

Mostly putting it here to keep an eye on it and because it has many recent samples.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/62772bd9-080c-4394-8721-4a8e2dad1d39)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/b382dcc4-4f6c-4d10-a984-7704d78eef9c)

**Comment by FedeGueli** [comment]
Yes thanks @JosetteSchoenma there are two of them tracked in #1089 the one with S:H1101Y and the other that got FLiRT after 31F

**Comment by JosetteSchoenma** [comment]
112 now

@ryhisner has made a separate proposal for one of these branches, including interesting background information.
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1578
