### ISSUE TITLE
KP.2 with S:T22N (glycan), S:S31F, S:G184V [15 seq, 3 countries)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1578]
**Description**
**Sub-lineage of:** KP.2
**Earliest sequence:** 2024-4-24, Canada, Alberta - EPI_ISL_19110156
**Most recent sequence:** 2024-5-10, Canada, Alberta (3 seqs)
**Continents circulating:** North America (11)
**Countries circulating:** Canada (10) [9 Alberta, 1 Ontario], England (4—probable), USA (1)
**Number of Sequences:** 15
**GISAID Nucleotide Query:** C21654T, G22113T, C7113T, -A7797C
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & [3-of: S:T22N, S:S31F, S:G184V]
**Substitutions on top of KP.2:**
**Spike:** T22N, S31F, G184V
**Nucleotide:** C21627A, C21654T, G22113T

**Phylogenetic Order of Mutations:** C21654T (S:S31F), G22113T (S:G184V) **→** C21627A (S:T22N)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.2_T22N_S31F_G184V.json?c=gt-nuc_22113&gmax=23113&gmin=21113&label=id:node_2374100
<img width="1488" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e4f062b4-efe2-462b-9a96-161b097257b8">

**Evidence**
It's been pretty clear that mutations and glycans around S:22-35 in spike are advantageous in JN.1 lineages. The fastest lineages have added a glycan, usually with S:∆S31. This KP.2 sublineage goes one better and gets both a glycan (with S:T22N) and adds a bulky AA residue with S:S31F. S:G184V came along for the ride as well. 

The sequences from England here do not register as having S:T22N but I think that's almost certainly only because they all have dropout from S:17-27. Most sequences here are from Alberta, Canada, but there is also one from Ontario, Canada, and one from Delaware, USA, indicating pretty rapid geographical spread. 

The sequence from Delaware has ORF8:Q27*, an old Alpha throwback. There hasn't been as much movement to eliminate ORF8 in BA.2.86 as in previous variants, but maybe it's only a matter of time. Or perhaps there's something different about BA.2.86 that makes ORF8 expression less deleterious than in nearly all major lineages since the rise of BA.5.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19110156, EPI_ISL_19139288, EPI_ISL_19140151,
EPI_ISL_19140278, EPI_ISL_19146770, EPI_ISL_19146802,
EPI_ISL_19146858, EPI_ISL_19153455, EPI_ISL_19159145,
EPI_ISL_19163087, EPI_ISL_19163147, EPI_ISL_19163196,
EPI_ISL_19163258, EPI_ISL_19163279, EPI_ISL_19163290,
</details>

**Comment by aviczhl2** [comment]
Designated KP.2.14

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/bb59f6b4-8a6a-4246-8470-c19633f8f2ae)
?
There seems to be many S:T22N branches under KP.2.14 in the newest usher tree. Do all seqs of KP.2.14 having S:T22N and those without T22N are just coverage issues, or is there many separate emergence of this?

**Comment by FedeGueli** [comment]
> ![image](https://private-user-images.githubusercontent.com/10445944/344964673-bb59f6b4-8a6a-4246-8470-c19633f8f2ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjI5NzMsIm5iZiI6MTcxOTkyMjY3MywicGF0aCI6Ii8xMDQ0NTk0NC8zNDQ5NjQ2NzMtYmI1OWY2YjQtOGE2YS00MjQ2LTg0NzAtYzE5NjMzZjhmMmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyMTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZGE2NmVlYjNkMDUyZmIzYjJjMDNjYTJhYmVkY2E5NWY4ZGQ0MTcwYTBiZTA4ZjFkYzhmNjViZjAyZGY5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GdLB315y5ntWqFl3Q8u1YNSmTdrDuvgf41y34S17oO8)
> 
> There seems to be many S:T22N branches under KP.2.14 in the newest usher tree. Do all seqs of KP.2.14 having S:T22N and those without T22N are just coverage issues, or is there many separate emergence of this?
> 
> @AngieHinrichs

Yeah noticed that too. KP.2.14 tough has not T22N as defining, but it is in most of the sequences belonging to this lineage.i think it is not ideal but dont see how to do better

**Comment by AngieHinrichs** [comment]
Yes, some sequences from Canada without S:T22N seem to be breaking up what could otherwise be one big S:T22N branch.  I will add it to the list for the next round of prune & replace.

**Comment by FedeGueli** [comment]
the S:T22N desingated KP.2.14.1 via https://github.com/cov-lineages/pango-designation/commit/01948c288ce086e8b2feaa0093e93ac79bbc1574

**Comment by aviczhl2** [comment]
KP.2.14.1 is retracted.
