### ISSUE TITLE
   Jn.1.52 + FLiRT( placed as JN.1.16.1+Orf1a:K3353R ) with S:F59S in Spain, Sweden (14)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1579]
Defining :
JN.1.16.1 > Orf1a:K3353R (A10323G) > ORF1a:S2246L (C7002T), S:F59S (T21738C)
Query: A10323G,C7002T,T21738C
Samples: 7 Mostly Spain
First sample collected on 2024-04-01 from Israel
IDs: EPI_ISL_19147469, EPI_ISL_19162087, EPI_ISL_19162090-19162091,
EPI_ISL_19162094, EPI_ISL_19162099

Tree:
<img width="1171" alt="Screenshot 2024-05-26 alle 01 54 43" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2bdcb89b-f181-45c2-9277-eb6a7e054f59">

**Comment by aviczhl2** [comment]
Shall be JN.1.52+FLiRT+S:F59S?

**Comment by FedeGueli** [comment]
> Shall be JN.1.52+FLiRT+S:F59S?

where is it plavced now? Orf1a:K3353R is very homoplasic so unsure

**Comment by aviczhl2** [comment]
> > Shall be JN.1.52+FLiRT+S:F59S?
> 
> where is it plavced now? Orf1a:K3353R is very homoplasic so unsure

Is it really homoplastic, or just misplacement like G2782T? Needs investigation.

**Comment by aviczhl2** [comment]
Given the extreme convergence of FLiRT it shall be more possibly sub-branch of JN.1.52?

**Comment by FedeGueli** [comment]
maybe just a cluster

**Comment by FedeGueli** [comment]
14 now worth closing it

**Comment by DailyCovidCases** [comment]
Now 26 seqs
