### ISSUE TITLE
GF.1 with S:K478N (7 seqs, Indonesia and Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#158]
GF.1+C10456T,A22996C(S:K478N),A22600G
No.of seqs: 7 (Indonesia 6, Japan 1)

Earliest: EPI_ISL_17372799, 2023-3-13, Indonesia
Latest: EPI_ISL_17719574, 2023-5-20,Indonesia

Query: C10456T,A22996C,A22600G (edited)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_32be1_5b4860.json?label=id:node_6911784&showBranchLabels=all)

<img width="1400" alt="Screenshot 2023-06-11 at 20 12 27" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8da865d6-2a22-4fd9-a540-c8da509d1272">

**Comment by FedeGueli** [comment]
Thx for proposing this one , spotted that too.

**Comment by FedeGueli** [comment]
likely slow . let see next week.

**Comment by aviczhl2** [comment]
No new seqs in 3 weeks, close down.
