### ISSUE TITLE
KP.3 + S:N417T, ORF1a:D2492N, I3108V, ORF1b:Q48R + T177C [5' UTR] (26 seq, Canada, June 24)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1580]
**Description**
**Sub-lineage of:** KP.3
**Earliest sequence:** 2024-5-5, Canada, British Columbia — EPI_ISL_19161088
**Most recent sequence:** 2024-5-11, Canada, BC — EPI_ISL_19169116, EPI_ISL_19169126
**Continents circulating:** North America (7)
**Countries circulating:** Canada (7) [British Columbia (6), Alberta (1)]
**Number of Sequences:** 7
**GISAID Nucleotide Query:** A22812C, A13610G
**CovSpectrum Query:** Nextcladepangolineage:KP.3* & A22812C & [2-of: T177C, G7739A, A9587G, A13610G]
**Substitutions on top of KP.3:**
**Spike:** N417T
**ORF1a:** D2492N, I3108V
**ORF1b:** Q48R
**Nucleotide:** T177C, G7739A, A9587G, C11644T, A13610G, A22812C

**Phylogenetic Order of Mutations:** C11644T **→** T177C, A9587G, A13610G, (ORF1a:I3108V, ORF1b:Q48R) **→** G7739A, A22812C (ORF1a:D2492N, S:N417T) **→** () **→** () **→** 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3_N417T_7_seq.json?c=gt-S_417&gmax=25384&gmin=21563&label=id:node_6995166

<img width="1441" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/36db9654-d616-4388-abce-1713574a166d">

**Evidence**
Now in two Canadian provinces, British Columbia (6) and Alberta (1). All collection dates within 6 days of one another, from May 5-11. Upload dates all between May 23-28.

S:417T is one of the two most classic cryptic wastewater lineage mutations and is also quite common in conventional chronic-infection sequences, the other being ORF1a:K1795Q. Both also famously in Gamma. 

The Alberta sequence also has ORF1a:T319S—a rare C->G nuc mutation—and N:G243C, which likely forms a disulfide bond in the predominant N dimer form. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19161088, EPI_ISL_19163268, EPI_ISL_19169013,
EPI_ISL_19169035, EPI_ISL_19169064, EPI_ISL_19169116,
EPI_ISL_19169126
</details>

**Comment by FedeGueli** [comment]
+1 Alberta

**Comment by ryhisner** [comment]
> A22812C, A13610G

The fact that the new Alberta sequence is identical to six sequences from British Columbia makes me think this could be spreading rapidly. Canada is quicker than the US (and just about all other countries) at uploading sequences, so I would not be surprised to see sequences of this showing up in the US in the next two weeks.

**Comment by ryhisner** [comment]
> +1 Alberta

The fact that the new Alberta sequence is identical to six sequences from British Columbia makes me think this could be spreading rapidly. Canada is quicker than the US (and just about all other countries) at uploading sequences, so I would not be surprised to see sequences of this showing up in the US in the next two weeks.

**Comment by FedeGueli** [comment]
26 all from Canada BC

**Comment by FedeGueli** [comment]
likely just a clustwer closing it
