### ISSUE TITLE
KS.1 + S:K147N, N417I, ORF1a:P2287L, V4216I (4 seq, Germany, May 29)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1581]
**Description**
**Sub-lineage of:** KS.1 (JN.1.13.1.1 = JN.1 + S:F59S, R346T, F456L, A1087S)
**Earliest sequence:** 2024-4-16, Germany, North Rhine-Westphalia — EPI_ISL_19108237
**Most recent sequence:** 2024-4-29, Germany, Saxony-Anhalt —EPI_ISL_19170250, EPI_ISL_19170252
**Continents circulating:** Europe (4)
**Countries circulating:** Germany (4) [Saxony-Anhalt  (3), North Rhine-Westphalia (1)]
**Number of Sequences:** 4
**GISAID Nucleotide Query:** C7125T, G12911A, A22003C, A22812T, T23815C
**CovSpectrum Query:** Nextcladepangolineage:KS.1* & [3-of: C7125T, G12911A, A22003C, A22812T, T23815C]
**Substitutions on top of X:**
**Spike:** K147N, N417I
**ORF1a:** P2287L, V4216I
**Nucleotide:** C7125T, G12911A, A22003C, A22812T, T23815C

**Phylogenetic Order of Mutations:** All in same branch 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KS.1_N417I_4_seq.json?c=gt-S_417&gmax=25384&gmin=21563&label=id:node_2421843
<img width="1497" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/de89b303-cb73-4f2e-886d-0078abf622ed">

**Evidence**
S:417I has been extremely rare and mostly found only in long-branch, chronic-infection singlets, probably exclusively up to this point. Germany does virtually no surveillance, so it's possible this is more widespread than the four sequences would indicate. Three sequences are from Saxony-Anhalt while the first sequence was from North Rhine-Westphalia. The provinces do not border each other, so this is not a locally confined cluster. 

Notably, SARS-CoV-1 and related Bat-CoVs have S:417V, which is very similar to S:417I.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19108237, EPI_ISL_19156994, EPI_ISL_19170250, EPI_ISL_19170252
</details>

**Comment by aviczhl2** [comment]
No more seqs
