### ISSUE TITLE
KP.2.3 + S:∆S31, T572I [Full Quad] (51 seq,  12 countries, July 25)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1582]
**Description**
**Sub-lineage of:** KP.2.3 (JN.1.11.1.2.3 = JN.1 + S:H146Q, R346T, F456L, V1104L, ORF3a:K67N, ORF1a:T2283I)
**Earliest sequence:** 2024-4-24, Mauritius, Grand Port — EPI_ISL_19170222
**Most recent sequence:** 2024-5-7, Canada, Alberta — EPI_ISL_19163154
**Continents circulating:** Africa (1), Europe (1), North America (1)
**Countries circulating:** Canada (1), Mauritius (1), Sweden (1)
**Number of Sequences:** 3
**GISAID Nucleotide Query:** C23277T, G25593T, C28714T, T3565C, C28714T, -C25416T, -T16746C, -A21917G, -C25708A, -G25088T
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & [2-of: C23277T, G25593T]
**Substitutions on top of KP.2.3:** 
**Spike:** ∆S31, T572I
**Nucleotide:** ∆21653-21655, C23277T, C28714T

**Phylogenetic Order of Mutations:** C28714T, ∆21653-21655 (S:∆S31)  **→** C23277T (S:T572I) 

**USHER Tree** (Temporary link)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e5c7_2455d0.json?f_userOrOld=uploaded%20sample&label=id:node_7039539
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/2e546d86-cdc3-4d4e-94bd-e144db755a61">

**Evidence**
This is maybe the first branch to have the Full Quad, as I call it: S:∆S31, S:R346T, S:F456L, S:T572I. KP.2.3 also has S:H146Q, famously in  BJ.1/XBB. However, the Mauritius sequence does not register S:H146Q, but given the amount of dropout in that sequence, along with the fact that his region of spike is often a troublesome one (with either S:G142D or S:∆Y144 often missing from sequences), and *especially* the fact that the Mauritius sequence shares the synonymous C28714T with the other two sequences I think it's almost certain that it really has H146Q. 

Incidentally, C28714T is one of the three defining mutations of KP.2.3.1, along with S:∆S31. So these sequences have two of the three defining KP.2.3.1 mutations but all lack the third, which is S:A475V.

If the Mauritius sequence really does not have S:H146Q, then it would not technically be part of KP.2.3, even though it contains the other KP.2.3-defining mutation, ORF3a:K67N, and two of the three defining KP.2.3 mutations (S:∆S31 & C28714T). It would constitute a separate KP.2 + S:∆S31 + S:T572I + ORF3a:K67N branch. But that seems extraordinarily unlikely.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19163154, EPI_ISL_19166256, EPI_ISL_19170222,
EPI_ISL_19192876, EPI_ISL_19194175, EPI_ISL_19195633,
EPI_ISL_19195901, EPI_ISL_19201415, EPI_ISL_19214034,
EPI_ISL_19219787, EPI_ISL_19228107, EPI_ISL_19229098,
EPI_ISL_19229121, EPI_ISL_19230366, EPI_ISL_19244526,
EPI_ISL_19251944-19251945, EPI_ISL_19251949, EPI_ISL_19251960,
EPI_ISL_19251977, EPI_ISL_19251985, EPI_ISL_19251994,
EPI_ISL_19252002, EPI_ISL_19258121, EPI_ISL_19260931,
EPI_ISL_19260967, EPI_ISL_19262078, EPI_ISL_19262370,
EPI_ISL_19264949, EPI_ISL_19265008, EPI_ISL_19268306-19268308,
EPI_ISL_19273894, EPI_ISL_19279050, EPI_ISL_19279054,
EPI_ISL_19279079, EPI_ISL_19279111, EPI_ISL_19279801,
EPI_ISL_19283729, EPI_ISL_19283864, EPI_ISL_19284964,
EPI_ISL_19285044, EPI_ISL_19285068, EPI_ISL_19285092,
EPI_ISL_19285125, EPI_ISL_19285132, EPI_ISL_19285191,
EPI_ISL_19285201
</details>

**Comment by FedeGueli** [comment]
@ryhisner just found another full quad lineage this time on LB.1 Backbone , weirdly it has too a Mauritius sample!:
<img width="1124" alt="Screenshot 2024-05-29 alle 18 40 10" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/224f11a6-c9a8-43fc-b5b5-72ac052c546e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_4871_707ae0.json?f_userOrOld=uploaded%20sample&label=id:node_7128678

**Comment by ryhisner** [comment]
@FedeGueli, that was the one I talked about the other day, but I don't know if any of those are actually related. There's a huge ORF1b:T1555I branch that all of these should be included in, and it's widespread internationally, though not common in any of the countries with good surveillance.

**Comment by FedeGueli** [comment]
> @FedeGueli, that was the one I talked about the other day, but I don't know if any of those are actually related. There's a huge ORF1b:T1555I branch that all of these should be included in, and it's widespread internationally, though not common in any of the countries with good surveillance.
> 
> <img alt="image" width="1505" src="https://private-user-images.githubusercontent.com/33738461/334893905-c07fe949-6b22-4721-bcb0-c9ba9b335143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMDI4MzIsIm5iZiI6MTcxNzAwMjUzMiwicGF0aCI6Ii8zMzczODQ2MS8zMzQ4OTM5MDUtYzA3ZmU5NDktNmIyMi00NzIxLWJjYjAtYzliYTliMzM1MTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDE3MDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhM2EyYmY0MGJjMWYzYWZhMDNjMDRmMzZiMTg1YTE4OWJhNzYzZDlhMWQzOTc3ODA0OGY1YWIwZTkxOTIwODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2bv237dtvP4BA4jNl4-bHWdhGt8LmPJWQ9ko27eAdcw">

Thank you Ryan ! i see now that it was that, and weirdly Usher included also the Mauritius one. i ve proposed but i would add an aritfact label.

**Comment by FedeGueli** [comment]
8 now , also in Canada

**Comment by aviczhl2** [comment]
There is also a KP.2.3+T572I branch without C28714T
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice91_genome_test_3e518_5dbe40.json?label=id:node_5464816

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c97c67f1-c23e-4e8b-9b1d-b362938da9b4)

**Comment by FedeGueli** [comment]
> There is also a KP.2.3+T572I branch without C28714T https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice91_genome_test_3e518_5dbe40.json?label=id:node_5464816
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/345709846-c97c67f1-c23e-4e8b-9b1d-b362938da9b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzkyMzAsIm5iZiI6MTcyMDA3ODkzMCwicGF0aCI6Ii8xMDQ0NTk0NC8zNDU3MDk4NDYtYzk3YzY3ZjEtYzIzZS00ZThiLTliMWQtYjM2MjkzOGRhOWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA3NDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzY2ZlOWFjNmM5YTljNzdjZjgzNmQzMDM3ZjRmOWVhNjU0NmUxOGU3MmRhMTJjOTAwOWJhMWFjMTZjMjU0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hj-650-kXSr4PAnjFpX8UZfW3q6M9wcaAA8rzPPtu5I)

thx query changed. please propose this

**Comment by FedeGueli** [comment]
34 now 11 countries 5% prevalence in Sweden pls propose it

**Comment by FedeGueli** [comment]
51 from 12 countries

**Comment by aviczhl2** [comment]
New query from #1781: C28714T, C23277T, G25593T,G17334T,-9286,-24418, -C7851T,-C20233T,-C1267T

adding many -s to exclude separate emergences.

**Comment by FedeGueli** [comment]
Designated KP.2.3.6 via https://github.com/cov-lineages/pango-designation/commit/4ee31e1915ed234bfcd5ae74e79aec4842a0aadd
