### ISSUE TITLE
LB.1.3 second FULL QUAD ( DEFLiRT+ S:T572I) lineage  (33 Isr, Us, UK, Spain)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1583]
Edited Intro:
This was tracked as Singlet 71 of #1089 (from Israel) then it became Branch 136 when the Uk sample came spotted also by @HynnSpylor and @ryhisner . Rediscovered from a downsampled tree that mistakenly showed this and #1582 together.

LB.1.3 [S:S31del ( Del21653-55)  > Orf1b:T1555I (C18131T) ] > S:T572I (C23277T) 
Query: Del21653,C23277T,C18131T
Samples: 3
Countries: Israel UK NYC 
Tree:
<img width="1160" alt="Screenshot 2024-05-29 alle 19 07 43" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a3e101be-736f-414a-984f-8c64bc4b69ba">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4c223_75ccd0.json?label=id:node_7128678

**Comment by HynnSpylor** [comment]
Yeah I also mentioned the English seq in X group several days ago(+S:V642G, S:P809S)

**Comment by FedeGueli** [comment]
> Yeah I also mentioned the English seq in X group several days ago(+S:V642G, S:P809S)

Ah thx is it that one? So it was tracked back in #1089 as singlet before the 642G came.let me see the branch so i could match it with this! (I ve found this casually from a s:31del downsampled tree that mistakenly showed this and the other you proposed together as LB.1 (and i cant see how it happened! ) so i didnt realize this was the same of the one that you mentioned on X  ;) )

**Comment by FedeGueli** [comment]
Ok mistery solved it was singlet 71 of #1089 (the isr.sample)  that became branch 136 when the uk seq popped up then i closed the issue so i didnt see the third coming! 
Thx both for the help.

But is this real or just multiple unrelated samples put together by Usher?

**Comment by HynnSpylor** [comment]
Yeah I also mentioned the English seq in X group several days ago(+S:V642G, S:P809S)

**Comment by FedeGueli** [comment]
+1 Scotland

**Comment by FedeGueli** [comment]
Parent designated LB.1.3

**Comment by FedeGueli** [comment]
5 now England

**Comment by Memorablea** [comment]
PING

**Comment by FedeGueli** [comment]
33 around 2% in Israel in Mid June

**Comment by aviczhl2** [comment]
Is it MH.1? Does it have C25413T?

**Comment by aviczhl2** [comment]
It seems that the designation of LB.1.3.2 and MH.1 are ambigious. They follow C24844T instead of C25413T.

For this proposal (Pure LB.1.3+S:T572I) I think we shall add -24844 to the query to separate from LB.1.3.2 and MH.1. 
This gives only 3 seqs but sequenced very recently. 

@FedeGueli

**Comment by FedeGueli** [comment]
i am checking too. i have some doubt also on LB.1.8 i will be back when finishing the analysis

**Comment by FedeGueli** [comment]
No no @aviczhl2 this proposal is for the entire S:T572I branch not for one part of it i don't get why this had been designated so deep in the tree leaving out a big chunk of the lineage:
<img width="1171" alt="Screenshot 2024-07-10 alle 15 43 08" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/82925dc3-18c1-4b2c-9f64-bcfb8c90c22a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5d24d_e8da00.json?c=gt-nuc_25413&gmax=26413&gmin=24413&label=id:node_7193672

consider there is no LB.1.3 branch otuside this with C25413T so it is hard to get why not designasting everything from S:T572I ahead or at least from C24844T cc @corneliusroemer @angiehinrichs
