### ISSUE TITLE
BA.2 saltation, ≥34 spike mutations (4 seq, Canada, Ontario and Alberta)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1584]
An extraordinary BA.2 sequence was collected from Ontario, Canada, on August 2023. One of its most distinctive aspects was S:I651V, a 2-nucleotide mutation (though it only requires one). Another astounding BA.2 sequence was collected in mid May, 2024, and the 2-nuc S:I651V (now accompanied by S:L650I) caught my eye and made me think this was likely another sequence from the same patient. I checked and there was indeed a previous sequence that shared 35 of the mutations this sequence had. 

But the sequences come from different provinces in Canada. The May 2024 sequence is from Alberta; the August 2023 sequence came from Ontario. The first sequence has metadata, but the second (from Alberta) does not, so it is not possible to know if this sequence comes from the same patient or not. It seems unlikely that sequences from two different, non-bordering provinces would come from the same patient, but it seems even more unlikely that this lineage is circulating and has spread from across Canada. If anyone has connections with either of the labs involved here (Public Health Ontario Laboratory in Toronto, Ontario, and Alberta Precision Labs in Edmonton, Alberta), it would be great if you could contact them and find out whether or not this lineage is circulating.

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/chronic_multiples/main/BA.2_Canada.Alberta_and_Ontario_70_80_private_mutations.json?label=id:node_1378902
<img width="1490" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/3537f2c3-0e25-47b2-9749-6891acc4b33a">

These sequences share 35 mutations, but they differ by an astonishing **_77 nucleotide mutations_**. 

Below are pictures of my summary of the private mutations for each sequence. The second sequence has dropout in several spike regions, so some mutations in the first sequence that aren't listed in the second—like S:ins212_AG—are most likely in both sequences. 

The turquoise-highlighted mutations involve 2 nucleotide substitutions. The yellow-highlighted mutations are in the four genomic regions where I've noticed mutations in chronic infections tend to cluster together (ORF1a:1542-1543, ORF1a:4395-4398, ORF1b:820-824, and N:270-271). It's fascinating that while both mutations contain mutations in three of these four regions, the mutations differ, with one sequence having ORF1b:L820F and one having N:T271I. 

<img width="1314" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5dc61f41-b2f1-46db-80c6-1f0b31b28386">

Also striking is the change from ORF1a:∆S4398 to ORF1a:S4398L. This exact same change occurred in a BQ.1.1 branch from England that had mutations in all four of these regions, but in reverse order. The BQ.1.1 had S4398L first and then switched to ∆4398. (Curiously, that branch also had a mutation at M:E12, but instead of E12D, it had the unique 2-nuc M:E12Y.)

As in many of the most extraordinarily divergent sequences, there are multiple reversions. All of the reversions here—S:K478T, S:A484E, S:R493Q, S:H505Y, and S:I9T—are convergent in chronic infections. 

The 2-nuc version of S:I651V suggests it may have passed through M on its way to V (I651M-->M651V). The addition of S:L650I in the interim is even more unusual. These are not locations where mutations are normally found, in chronic-infection sequences or otherwise. 

Much more could be said, as always, but I'll leave it here for now.

<img width="1277" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/3f1749da-717b-4180-be96-ebd7d300226c">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18224410, EPI_ISL_19173640 
</details>

**Comment by FedeGueli** [comment]
Thank you @ryhisner !!

**Comment by FedeGueli** [comment]
[alex-m-a](https://github.com/alex-m-a) @alex-m-a maybe could help ??

**Comment by FedeGueli** [comment]
or maybe: @Codes1985 could be interesting in?

**Comment by Codes1985** [comment]
@FedeGueli: I'll pass this along to a contact from AB.

**Comment by ryhisner** [comment]
Another of these showed up today, and the number of mutations has ballooned. More surprising still is that this sequence is more closely related to the Ontario sequence from 9 months ago than it is to the other BA.2 collected in Alberta 6 days earlier. I'm now pretty convinced these are all from the same patient, though I have no confirmation of anything. 

It lacks 10 mutations the Ontario sequence had, but it has 48 additional ones. 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/chronic_multiples/main/BA.2_Chronic_Canada_Ontario_to_Alberta_3_seq.json?label=id:node_11477653
<img width="1506" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d11cb588-5b5e-4d6d-80d2-722554b661ae">

My preliminary summary of the mutations on top of baseline BA.2 is below. 

<img width="1447" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c22069cd-da8f-40da-a8e6-fff6017aa813">

**Comment by FedeGueli** [comment]
new query:T378C, A761G, A5648C, C241T  ,C9803T,C19186T,C4832T
@ryhisner did you notice how many nuc mutations are reversion toward bats?? looking for the query if not adding C241T i would have found some bat viruses with them. try to check!

**Comment by FedeGueli** [comment]
About S:I651V it is not necessarily a double nuc mutation if A23513G comes first it is enough to bring to V : 
ATA >> GTA = I >> V ,
i am saying this cause just recently popped up another S:I651V sublioneage with this single nuc mutation in South Australia:
<img width="1154" alt="Screenshot 2024-06-07 alle 00 15 11" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e5b644b2-0058-438f-ad96-1164ddecf341">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5f373_232400.json?label=id:node_6968966

**Comment by ryhisner** [comment]
Yeah, I realize that. But I think the fact that two nucleotides there are mutated is meaningful regardless, particularly given that the 2nd sequence had an additional nuc mutation right next door, forming S:L650I. It's possible the amino acid effects of these mutations are not important—they're all fairly similar—and that the real action is occurring in secondary RNA structure. Pretty much impossible to know.

**Comment by FedeGueli** [comment]
> Yeah, I realize that. But I think the fact that two nucleotides there are mutated is meaningful regardless, particularly given that the 2nd sequence had an additional nuc mutation right next door, forming S:L650I. It's possible the amino acid effects of these mutations are not important—they're all fairly similar—and that the real action is occurring in secondary RNA structure. Pretty much impossible to know.

Yeah for sure,  agree

**Comment by corneliusroemer** [comment]
Another one today, we're up to 4 - I suspect the Alberta samples are all from the same (chronic) patient, which checks out with the high diversity.

<img width="2171" alt="Brave Browser 2024-06-12 23 24 16" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/b1baa2ef-239b-47a9-b3bc-37697f6e4dbb">

hCoV-19/Canada/AB-ABPHL-118440/2024|EPI_ISL_19192806|2024-05-31

**Comment by ryhisner** [comment]
Yeah, it seems to be bouncing back and forth between two intrahost lineages that differ at >100 nucleotides. 

Three notable changes in the new sequence compared to the other sequence from the bottom branch collected 15 days earlier: 
• S:N417K reversion (for once I think it's real) and 
• A mutation in the insertion at S:212, changing it from AG (GCTGGA) to AE (GCTGAA). 
• A mixed nucleotide (T23525Y) that would cause an S:Y655H reversion. 

<img width="1485" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/fdf60362-2fec-4a91-90b5-ae717df20ef3">

**Comment by aviczhl2** [comment]
Seems not growing.
