### ISSUE TITLE
KP.3.2 with S:E309Q（14 seqs from Canada）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1585]
KP.3.2>**S:E309Q(G22487C)**
GISAID search:A2611C,C22858T,G22487C

UshER have bug,so I can not give link
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/1caf7cdc-b157-4d50-9d65-e9f9b467a540)

EPI_ISL ID:EPI_ISL_19158895-19158897, EPI_ISL_19158900-19158901

**Comment by FedeGueli** [comment]
Already proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1574 .
Thanks for re-spotting it

**Comment by FedeGueli** [comment]
Sorry it seems a different one! i ve had mistakenly saved the other also as KP.3.2 so was thinking it was the same

**Comment by Memorablea** [comment]
11

**Comment by FedeGueli** [comment]
slow closing it.
