### ISSUE TITLE
KP.3.2 with S:S680F（54 seqs, 12 countries）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1588]
KP.3.2>**S:S680F(C23601T)**
GISAID search:A2611C,C22858T,C23601T
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/5bdb2426-f7df-4384-b417-2ea7bc20c006)

**Comment by Memorablea** [comment]
Canada +3 10now

**Comment by Memorablea** [comment]
Canada +2 12now

**Comment by Memorablea** [comment]
13

**Comment by Memorablea** [comment]
16

**Comment by FedeGueli** [comment]
18 now also England, ireland and Netherlands

**Comment by FedeGueli** [comment]
26 now, but it seems quite slow to me

**Comment by Memorablea** [comment]
31

**Comment by FedeGueli** [comment]
41

**Comment by Memorablea** [comment]
slowly so i think should close it

**Comment by FedeGueli** [comment]
45, 4 samples from 3  countries at the very end of July better keeping this open although for sure not super fast

**Comment by FedeGueli** [comment]
2 new seqs from laos new country one from September
