### ISSUE TITLE
New JN.1.16.1 with S:S31del and Orf8:Q29*  emerged recently in France (21 seqs, 8 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1590]
Just spotted another DeFLiRT/FLiRT31

JN.1.16.1>> N:R385K (G29427A) > Orf1a:T4368I (C13368T) > Orf1a:G519S (G1820A) > S:S31del (del21653_55), G8824A, Orf8:Q29* (C27978T )
Query:C13368T,del21653, G1820A
Samples: 6 
Countries: France ( 3 regions), Italy , Spain, NYC
First collected on 2024-04-16
IDs: EPI_ISL_19157165, EPI_ISL_19162603, EPI_ISL_19166117, EPI_ISL_19166138, EPI_ISL_19173792, EPI_ISL_19174164,
Tree:
<img width="1164" alt="Screenshot 2024-05-31 alle 10 36 16" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c7d2ac35-8302-42e2-b502-ad58d3828e22">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_15160_98af10.json?c=userOrOld&label=id:node_7132518

**Comment by FedeGueli** [comment]
9 now , new country Canada

**Comment by FedeGueli** [comment]
proposed in https://github.com/cov-lineages/pango-designation/issues/2652

**Comment by aviczhl2** [comment]
Designated LF.4.1
