### ISSUE TITLE
KP.2.3 + S:S31del with S:V445P (10 Samples, 7 Countries)  

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1596]
Two DeFlirt KP.2.3 samples with further S:V445P  have been just uploaded now from Singapore

Defining:
KP.2.3> S:S31del (Del21653-55), C28714T>  A15759G, S:V445P(A22896C), C27804T
 
Query: A15759G, C27804T ,T22896C,
Samples: 7 (Singapore,Spain , India, UAE , Qatar,Spain England)
IDs: EPI_ISL_19181498, EPI_ISL_19182408
Tree: (edited on June 21)
<img width="1175" alt="Screenshot 2024-06-21 alle 20 00 11" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f94644d2-897e-4d83-b295-55a80988d055">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5384_5bf040.json?f_userOrOld=uploaded%20sample&label=id:node_12074095

**Comment by FedeGueli** [comment]
There could be also a LB.1 DeFLirt +445P query:  T3565C,C27476T, C29409T,22896C

If this will become a trend i will change this in a multiple lineages issue (i hope not)

**Comment by FedeGueli** [comment]
New Query new tree: A15759G, C27804T ,T22896C,

now 7 widespread in multiple areas

**Comment by FedeGueli** [comment]
ping @corneliusroemer

**Comment by FedeGueli** [comment]
10 +1 uk it seems quite fast.

**Comment by aviczhl2** [comment]
Designated KP.2.3.4
