### ISSUE TITLE
KP.2 with S:D1184N（8seqs from Sweden）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1598]
KP.2> T8482C, Orf1a:A2785T (G8618A), Orf3a:L52F (C25546T)> C17373A, S:D1184N (G25112A)

GISAID query:T8482C, G8618A, G25112A, C25546T  
tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_e2ed_1809e0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/4632f5c1-d508-4bb3-94ad-8c5c0137609f)

Samples:
EPI_ISL_19143856, EPI_ISL_19143862, EPI_ISL_19143867,
EPI_ISL_19143879, EPI_ISL_19143886, EPI_ISL_19166231-19166232,
EPI_ISL_19166234

**Comment by Memorablea** [comment]
I apologize for not being able to clarify this evolutionary relationship. If anyone can assist, I would greatly appreciate it. Thank you! @FedeGueli

**Comment by FedeGueli** [comment]
> I apologize for not being able to clarify this evolutionary relationship. If anyone can assist, I would greatly appreciate it. Thank you! @FedeGueli

It seems you got all right , alternative query: T8482C,G8618A, C25546T,C17373A
It is KP.2 interestingly 
Orf3a:L52I was also in HK.26 and did quite well so worth monitoring this
Tree:
<img width="1163" alt="Screenshot 2024-06-06 alle 12 19 30" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7a0a493c-3442-4f27-8ff4-5aaee70b9958">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e2ed_1809d0.json?c=userOrOld&label=id:node_5599012

**Comment by FedeGueli** [comment]
added defining for this

**Comment by FedeGueli** [comment]
it seems just a cluster no new sample coming from this

**Comment by Memorablea** [comment]
> T8482C, G8618A, G25112A, C25546T

**Comment by Memorablea** [comment]
> it seems just a cluster no new sample coming from this
