### ISSUE TITLE
KP.3.3 plus S:A27P, 102 samples 8 Places

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1599]
KP.3.3 plus S:A27P, 5 samples Japan
3 from Saitama and 2 from Tokyo
Query: Spike_A27P, Spike_Q493E
NEW Nuc Query: C7299T, C28291A, -A4364C, -C6543T  (by @Over-There-Is )
(Old Nuc Query:  T21610C,C7299T,C28291A )

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/ff9b1545-e863-4516-9ed1-fcfabcbc9dbd)

**Comment by FedeGueli** [comment]
i ve added a nuc query  T21610C,C7299T,C28291A

**Comment by JosetteSchoenma** [comment]
> i ve added a nuc query  T21610C,C7299T,C28291A

Thanks, @FedeGueli !

**Comment by FedeGueli** [comment]
+1 Jap

**Comment by FedeGueli** [comment]
10 all from JAapan likely slow.

**Comment by aviczhl2** [comment]
19 and in USA, Germany and France

**Comment by FedeGueli** [comment]
Please propose it a quite big batch from South Korea with it, 2/13 samples from there in August.

**Comment by FedeGueli** [comment]
52 now, @JosetteSchoenma would you propose it please?

**Comment by aviczhl2** [comment]
I only find 46 using the nuc query.

**Comment by DailyCovidCases** [comment]
I think this is nearly dead, so please close this issue

**Comment by FedeGueli** [comment]
> I think this is nearly dead, so please close this issue

15/51 in august, it is not dead @JosetteSchoenma please ignore .

**Comment by FedeGueli** [comment]
Instead propose it please @JosetteSchoenma

**Comment by Over-There-Is** [comment]
S:A27P is T21632C in GISAID.
T21610C, T21632C, C7299T,C28291A=48
-T21610C, T21632C, C7299T,C28291A=33
T21610C, -T21632C, C7299T,C28291A=5

**Comment by Over-There-Is** [comment]
S:A27P is T21632C in GISAID.
T21610C, T21632C, C7299T,C28291A=48
-T21610C, T21632C, C7299T,C28291A=33
T21610C, -T21632C, C7299T,C28291A=5
-T21610C, -T21632C, C7299T,C28291A=1

T21610C is a well-known misinterpretation of ins21608, it's unrelated to S:27.

sequences without T21632C:
hCoV-19/Germany/SH-RKI-I-1143903/2024|EPI_ISL_19283857|2024-07-04 KP.3.3.4
hCoV-19/South_Korea/KDCA293904/2024|EPI_ISL_19340653|2024-07-22 21610-21641N shares A20013G and C2470T with other sequences, it should belong to this lineage.(-T21610C)
hCoV-19/Canada/BC-BCCDC-726017/2024|EPI_ISL_19345984|2024-07-26 KP.3.3.4
hCoV-19/USA/NV-SNPHL-817177/2024|EPI_ISL_19350782|2024-08-13 21611-21641N KP.3.3.4
hCoV-19/South_Korea/KDCA294215/2024|EPI_ISL_19352431|2024-07-27 on a C6543T branch. 
hCoV-19/USA/CO-CDPHE-42195353/2024|EPI_ISL_19406336|2024-07-29 KP.3.3.4

A better query would be: C7299T, C28291A, -A4364C, -C6543T
Totally 82 now:
KR41 JP21 US17 CA1 CN-HK1 FR1

**Comment by Over-There-Is** [comment]
And it would be 84 if adding non-GISAID sequences like USA/NJ-CDC-QDX21693001/2024|PQ212164.1|2024-07-31 and USA/NC-CDC-LC1115476/2024|PQ237566.1|2024-08-16.

**Comment by Over-There-Is** [comment]
In usher's database it's T21632C, but in uploaded sequences, it would be interpreted as G21641C and unable to be combined with existing tree.
![image](https://github.com/user-attachments/assets/3cb37e77-d69f-4a68-ab04-3104dd290e36)

**Comment by FedeGueli** [comment]
Added the new query: C7299T, C28291A, -A4364C, -C6543T

**Comment by FedeGueli** [comment]
> S:A27P is T21632C in GISAID. T21610C, T21632C, C7299T,C28291A=48 -T21610C, T21632C, C7299T,C28291A=33 T21610C, -T21632C, C7299T,C28291A=5 -T21610C, -T21632C, C7299T,C28291A=1
> 
> T21610C is a well-known misinterpretation of ins21608, it's unrelated to S:27.
> 
> sequences without T21632C: hCoV-19/Germany/SH-RKI-I-1143903/2024|EPI_ISL_19283857|2024-07-04 KP.3.3.4 hCoV-19/South_Korea/KDCA293904/2024|EPI_ISL_19340653|2024-07-22 21610-21641N shares A20013G and C2470T with other sequences, it should belong to this lineage.(-T21610C) hCoV-19/Canada/BC-BCCDC-726017/2024|EPI_ISL_19345984|2024-07-26 KP.3.3.4 hCoV-19/USA/NV-SNPHL-817177/2024|EPI_ISL_19350782|2024-08-13 21611-21641N KP.3.3.4 hCoV-19/South_Korea/KDCA294215/2024|EPI_ISL_19352431|2024-07-27 on a C6543T branch. hCoV-19/USA/CO-CDPHE-42195353/2024|EPI_ISL_19406336|2024-07-29 KP.3.3.4
> 
> A better query would be: C7299T, C28291A, -A4364C, -C6543T Totally 82 now: KR41 JP21 US17 CA1 CN-HK1 FR1

Thx

**Comment by Over-There-Is** [comment]
Japan +3, 85(or including non-GISAID sequences 87)

**Comment by Over-There-Is** [comment]
Korea+5, 90

**Comment by xz-keg** [comment]
92, Netherlands

**Comment by Over-There-Is** [comment]
95

**Comment by FedeGueli** [comment]
7/95 after September 1 . likely dying off

**Comment by FedeGueli** [comment]
dead

**Comment by FedeGueli** [comment]
108 but dead

**Comment by Over-There-Is** [comment]
117, China Mainland

**Comment by FedeGueli** [comment]
120 with three US old samples

**Comment by Over-There-Is** [comment]
128

**Comment by FedeGueli** [comment]
> 128

last sample is. a XEC, unrelated. still 127  and dead
