### ISSUE TITLE
12-nuc/9-aa saltation of XBB.1.9.1 in Shanghai (3 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#16]
Mutations on top of XBB.1.9.1:
C1377A, A2207G, G3476A, G3483A, C6762T, C15352T, C24378T, C25667T, G29134T
C5512T, C9170T, C21114T

ORF1a | P371Q, I648V, V1071I, G1073E, T2166I, L2969F
ORF1b | L629F
S | S939F
ORF3a | S92L

GISAID query:C5512T, C9170T, C21114T

EPI_ISL_17536902, 2023-4-15
EPI_ISL_17618663, EPI_ISL_17618665, 2023-4-20

I don't know why usher only displays 2 of them but actually 3 seqs, all having the 12-nuc saltation.

I'll upgrade this to main if any seqs detected elsewhere. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice51_genome_3ce0c_710d50.json?f_userOrOld=uploaded%20sample&label=id:node_10130260)
<img width="1404" alt="Screen Shot 2023-05-07 at 11 37 47" src="https://user-images.githubusercontent.com/10445944/236656387-f2d14fb0-5934-4b85-9bc9-348f6a06ee75.png">

**Comment by FedeGueli** [comment]
@ryhisner  could this be MOV like sequences?

**Comment by krosa1910** [comment]
orf3a:S92L is awfully famaliar with me, as it appeared in my proposal 1907 that got to be xbb.1.5.44, my first accepted lineage.
This mutation magically appear in US during June-July 2020, got some relevancy during age of Delta. Yet most of the time including now it is some border mutation at levels like 0.03%.

**Comment by aviczhl2** [comment]
> orf3a:S92L is awfully famaliar with me, as it appeared in my proposal 1907 that got to be xbb.1.5.44, my first accepted lineage. This mutation magically appear in US during June-July 2020, got some relevancy during age of Delta. Yet most of the time including now it is some border mutation at levels like 0.03%.

We have lots of non-spike convergent evolutions, unfortunately very few of them are explained for any little bit.

**Comment by ryhisner** [comment]
@FedeGueli, it doesn't look like a MOV lineage to me. 2/12 transversions is a 5:1 transition/transversion (Ts/Tv) ratio, which is high but not an outlier, and 2/12 G->A mutations is about the expected amount

**Comment by FedeGueli** [comment]
Thx @ryhisner !!

**Comment by FedeGueli** [comment]
No sequences closing for now. If any seq will pop up ping me please.
