### ISSUE TITLE
Taiwanese FB.1 saltation with Orf1b:G662S, S:T299I, D339Y, K440R, S982L, E1195Q and Orf9b:I5T (27 nuc, 20 aa, 3 sequences, 2 with further S:T572I)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1600]
FB.1(=BQ.1.2.1.1)> C3903T(Orf1a:P1213L)> C9169T, C11758T, T17955G, C19938T, G25145C(S:E1195Q)
\> C853T, G2600A(Orf1a:V779I), G3091A, T3118C, A3235G, C3330T(Orf1a:T1022I), A6474C(Orf1a:E2070A), T7099C, C7732T, C8078T(Orf1a:P2605S), C8619T(Orf1a:A2785V), G15451A(Orf1b:G662S), A16999G(Orf1b:T1178A), C22458T(S:T299I), G22577T(S:D339Y), A22881G(S:K440R), C24507T(S:S982L), T25518C, C25546T(Orf3a:L52F), C26822T, C27092T, A27897G(Orf8:K2E), A27979G(Orf8:Q29R), G28028T(Orf8:W45C), T28297C(Orf9b:I5T), A28386G(N:K38R, Orf9b:N35D), A28572G(N:E136D, Orf9b:K97E)
\> C23277T(S:T572I)

Sequences: EPI_ISL_19183910, EPI_ISL_19183917, EPI_ISL_19183924
02-05~05-27 Tainan, Taiwan, China

Please ignore 4414 flip-flop in the tree.
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice16_genome_test_26e58_19fb00.json?label=id:node_5219454
![2024-06-07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/ab90a3a7-49de-464b-84b3-cfb317e34b00)

Possible query: C853T, G2600A, G3091A, T3118C (Edited)

**Comment by aviczhl2** [comment]
No new seqs
