### ISSUE TITLE
LB.1.3 + S:K147E, Y660R (2-nuc) (31 seq, 12 countries, Aug 3)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1601]
**Description**
**Sub-lineage of:** LB.1.3 (S:∆S31, Q183H, R346T, F456L)
**Earliest sequence:** 2024-4-29, France - EPI_ISL_19166088
**Most recent sequence:** 2024-5-16, Switzerland -  EPI_ISL_19185299
**Continents circulating:** Europe (2)
**Countries circulating:** France (1), Switzerland (1)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** T23540C, A23541G, G27261T
**CovSpectrum Query:** Nextcladepangolineage:LB.1* & [3-of: T23540C, A23541G, G27261T, C18131T]
**Substitutions on top of X:**
**Spike:** K147E, Y660R
**Nucleotide:** A22001G, T23540C, A23541G, G27261T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/LB.1.3_Y660R.json?c=gt-S_660&gmax=25384&gmin=21563&label=id:node_7131969
<img width="1493" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9dd3922d-6472-4e54-9f6f-f5ffb2ca60a6">

**Evidence**
I call LB.1.3 the "global" branch of LB.1 because it seems to come disproportionately from travel sequences. The xtremely unusual 2-nuc S:Y660R mutation caught my eye here. S:K147E has been advantageous in the past and is another mutation increasing NTD's negative charge, which is a trend that's been going on for a long time now and shows no signs of slowing. 

The most closely related sequence is a travel sequence from Qatar collected in the US. 

<img width="1201" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/28428a50-eff8-41d6-b24e-ae6c2e5c1014">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19166088, EPI_ISL_19185299, EPI_ISL_19189757,
EPI_ISL_19192350, EPI_ISL_19193564, EPI_ISL_19195905,
EPI_ISL_19195971, EPI_ISL_19198865, EPI_ISL_19202120,
</details>

**Comment by HynnSpylor** [comment]
1 more in France

**Comment by FedeGueli** [comment]
6 now i m checking them . new samples from ENv Germany France and Denmark

**Comment by FedeGueli** [comment]
+2 in two travellers from Germany (same day but different samples)

**Comment by ryhisner** [comment]
One of these showed up in British Columbia, Canada, so this one's skipping oceans now.

**Comment by FedeGueli** [comment]
10 Seqs 6 countries not slow at all pleaase propose it: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nextcladePangoLineage=JN.1*&nucMutations1=T23540C%2CA23541G%2CG27261T&analysisMode=CompareToBaseline&

**Comment by DailyCovidCases** [comment]
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=T23540C%2CA23541G%2CG27261T&nextcladePangoLineage=LB.1.3*&

**Comment by FedeGueli** [comment]
20 seqs from 9 countries.

To be noticed that 5/9 french samples come from inpatients. 
could it be a BQ.1.2.2 thing?

**Comment by aviczhl2** [comment]
30 seqs now.

**Comment by FedeGueli** [comment]
31 with two branches one mainly from France, the other more international, still i don't think it is fast enough to compete.
A couple of samples have no 147E
 
<img width="1172" alt="Screenshot 2024-08-03 alle 14 31 16" src="https://github.com/user-attachments/assets/24f88997-76de-4eb9-be6e-fffa2a65abc3">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_27d3b_e22670.json?f_userOrOld=uploaded%20sample&label=id:node_7239347
