### ISSUE TITLE
JN.1.16.1(S:F456L) with S:T250N(C22311A)（23seqs many countries）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1602]
JN.1.16.1>**S:T250N(C22311A)**

First Sequence: Virginia, USA，2024-03-12
Recent Sequence: Taiwan,China,2024-05-22

It is distributed in multiple countries including China, the United States, and Russia in Asia, Europe, and North America.

Due to the similarity between the newly named LQ.1 (JN.1.18>C22311A>T22928C) and the branch I proposed. For example, they all have T22928C and T22928C. So I'm sorry, I can only propose it at the moment and cannot provide a specific UshER tree and query method. Thank you for your understanding.

EPI_ISL ID：
EPI_ISL_19022944, EPI_ISL_19024740, EPI_ISL_19030222,
EPI_ISL_19065225, EPI_ISL_19070982, EPI_ISL_19122458,
EPI_ISL_19130958, EPI_ISL_19136201, EPI_ISL_19141968,
EPI_ISL_19143326, EPI_ISL_19143579, EPI_ISL_19144247,
EPI_ISL_19145819, EPI_ISL_19146886, EPI_ISL_19157919,
EPI_ISL_19161056, EPI_ISL_19161069, EPI_ISL_19163200,
EPI_ISL_19164435, EPI_ISL_19167090, EPI_ISL_19169259,
EPI_ISL_19169273, EPI_ISL_19175795

**Comment by Memorablea** [comment]
@FedeGueli @Over-There-Is

**Comment by FedeGueli** [comment]
They are the same lineage all have C14220T defining of LQ.1 closing this for now
