### ISSUE TITLE
KP.2.3 + S:S31del branch with N:H145Y + S:K679R + ORF1a:T2016K (101 in 7 countries) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1603]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/542f10c0-1b0f-4a8f-9934-29fbf5ff9171)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/5a4d6da0-a6e4-4c1e-9445-48651373f652)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_245b4_346f40.json?c=gt-S_679&gmax=25384&gmin=21563&label=id:node_7001206

First Seq: 2024-05-11
Most Recent: 2024-05-28

Gisaid Query: C6312A, T19449C, A23598G, C28706T

EPI_ISL_19178464 EPI_ISL_19165530 EPI_ISL_19153543 EPI_ISL_19178431 EPI_ISL_19178477 EPI_ISL_19178476 EPI_ISL_19165521 EPI_ISL_19178378 EPI_ISL_19165460 PP832030.1 PP832067.1 PP857924.1

**Comment by Mydtlwn** [comment]
Labels KP.3?

**Comment by Mydtlwn** [comment]
The definition mutation of KP.2.3 has been adjusted to include the S: S31del mutation!

**Comment by FedeGueli** [comment]
> The definition mutation of KP.2.3 has been adjusted to include the S: S31del mutation!

a really i didnt know.

**Comment by FedeGueli** [comment]
one very rare double mutation popped up in this lineage: S:G72W, S:F159V : Query: G21776T, G22037T,T3565C

It is from a GBW sample so it should be prevalent somewhere

**Comment by FedeGueli** [comment]
101 from 7 countries please propose it @Fearuncle

**Comment by DailyCovidCases** [comment]
Please propose it

**Comment by FedeGueli** [comment]
> Please propose it

green light to be proposed on the main page could be given only by moderators of this repo.

**Comment by FedeGueli** [comment]
Kp.2.3.14 via https://github.com/cov-lineages/pango-designation/commit/0c6652152ec349f92de8f6dfcd0f6d62a5c919a2
