### ISSUE TITLE
Another KP.3.1+S:S31F (81 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1605]
KP.3.1+T19305C+C21654T(S:S31F)

GISAID query: T19305C,C21654T,C23039G
No. of seqs: 9(Ireland 1 UK 8)

First: EPI_ISL_19147141, 2024-4-30, UK
Latest:EPI_ISL_19177146, 2024-5-21, UK

Most of the seqs also have C4795T, indicating a potential recomb of this branch with JN.1.51, however it is hard to prove or disprove that given only a single mutation.

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_49e91_560b60.json?label=id:node_6994906)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/190013dc-3fee-4150-808a-054e7d52e529)

**Comment by JosetteSchoenma** [comment]
What makes you say "another"? My query in this issue catches those as well. G15372T, A19722G, C21654T
Why would it not be a subbranch of KP.3.1.3 with an extra T19305C misplaced by Usher?
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1576

**Comment by aviczhl2** [comment]
> What makes you say "another"? My query in this issue catches those as well. G15372T, A19722G, C21654T Why would it not be a subbranch of KP.3.1.3 with an extra T19305C misplaced by Usher? #1576

Because there is a large KP.3.1+T19305C branch. S:S31F is quite convergent but highly unlikely for T19305C to be convergent.

**Comment by JosetteSchoenma** [comment]
Oke. 

I will put this issue under my issue then.

**Comment by aviczhl2** [comment]
28 seqs now, Sweden, Netherlands, Canada, USA

**Comment by aviczhl2** [comment]
34,Australia, France

**Comment by aviczhl2** [comment]
48, Japan, Singapore, Spain

**Comment by FedeGueli** [comment]
Please propose it

**Comment by aviczhl2** [comment]
Designated MK.1
