### ISSUE TITLE
KP.1.1.3 + S:∆S31, S:T572I, ORF8:A65V (Full Quad) [32 sequences, 10 countries)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1607]
**Description**
**Sub-lineage of:** KP.1.1.3 (S:R346T, F456L, K1086R, V1104L)
**Earliest sequence:** 2024-5-21 – Spain, Catalunya
**Most recent sequence:** 2024-6-3 – Canada, Ontario (2 seq)
**Continents circulating:** North America (2), Europe (1)
**Countries circulating:** Canada (2), Spain (1)
**Number of Sequences:** 3
**GISAID Nucleotide Query:** G12160A, C29762T ,C23277T, C28087T 
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions/Deletions on top of KP.1.1.3:**
**Spike:** ∆S31, T572I
**ORF8:** A65V
**3' UTR:** C29762T

**Nucleotide:** G12160A, ∆22193-22195, C23277T, C28087T, C29762T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.1.1.3_Full_Quad.json?c=gt-nuc_12160&gmax=13060&gmin=11060&label=id:node_2376593
<img width="1501" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/91ddbcce-aa81-494d-a7b2-9533564af0a4">

**Evidence**
Collection date for Spain sequence is May 21 and for the two Canadian sequences June 3, so very recent. We haven't seen anything with all four known advantageous spike mutations (∆S31, R346T, F456L, T572I) take off though, so it may be that they don't work all that well together. 

Logically, it seems like they should: S:T572I is known to increase ACE2 binding by increasing the 1-RBD-up conformation. This comes at the expense of antibody evasion since the RBD is more exposed, but one would expect T572I to be most tolerated on the most highly evasive RBDs, most notably sequences such as these that have the three major antibody-escape mutations. You would also expect S:T572I to go well with S:Q493E, particularly when joined with S:∆S31 (or maybe S:S31F). 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19165019, EPI_ISL_19188373, EPI_ISL_19188377
</details>

**Comment by FedeGueli** [comment]
One more sample from Canary Island , but @angiehinrichs i m noticing that USher changes placement frequently , sometimes from night to morning, now it is placed as KP.1.2 sublineage (and it is a misplacement cause having C4999T and S:S31del for sure it belongs top KP.1.1.3 
@ryhisner i suggest this as query: G12160A, C29762T  ,C23277T, C28087T

tree:
<img width="1166" alt="Screenshot 2024-06-11 alle 11 28 20" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/322f0324-9ff0-475b-a87c-a1c89afdd8c1">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_10246_817200.json?label=id:node_11482801

**Comment by AngieHinrichs** [comment]
I think this is fixed now, and hopefully matOptimize won't move it again, but let me know if it does!  Thanks.

**Comment by FedeGueli** [comment]
Thank you @AngieHinrichs

**Comment by FedeGueli** [comment]
13 now 5 uploaded today from 5 different countries, 6 from 6 countries since past Sunday

**Comment by FedeGueli** [comment]
16 now last uploads from 3 different countries

**Comment by FedeGueli** [comment]
22 now

**Comment by FedeGueli** [comment]
32 , 10 countries including Italy and Slovenia

**Comment by FedeGueli** [comment]
Designated LP.4 via https://github.com/cov-lineages/pango-designation/commit/138717a1911280c49a16b68a53efce4294356bf7
