### ISSUE TITLE
KP.1.1.1 + S:N417T, N:P67L, ORF9b:L64F (Canada, New Zealand; 18 seq, June 11)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1608]
**Description**
**Sub-lineage of:** KP.1.1.1 (S:K182N, R346T, F456L, K1086R, V1104L)
**Earliest sequence:** 2024-4-25, Canada, British Columbia
**Most recent sequence:** 2024-5-20, New Zealand
**Continents circulating:** Oceania (17), North America (1)
**Countries circulating:** New Zealand (17), Canada (1)
**Number of Sequences:** 18
**GISAID Nucleotide Query:** C1684T, A22812C, C28473T
**CovSpectrum Query:** Nextcladepangolineage:KP.1.1.1* & A22813C & [1-of: C1684T, C28473T]
**Substitutions on top of KP.1.1.1:**
**Spike:** N417T
**N:** P67L
**ORF9b:** L64F
**Nucleotide:** C1684T, A22812C, C28473T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.1.1.1_N417T_N_P67L_ORF9b_L64F.json?c=gt-S_417&gmax=25384&gmin=21563&label=id:node_6999566
<img width="1456" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1d9a8a64-1878-4afc-b02b-8a61382e0fa4">

**Evidence**
Seems embedded in a branch of KP.1.1.1 that's dominated by sequences from British Columbia, Canada, and the earliest sequence by several weeks was from BC. However, the New Zealand sequences look genetically basal to the Canadian sequence, so it seems more likely to have originated in New Zealand. It's in two different counties in New Zealand, so this isn't a hyper-local outbreak.   

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19141845, EPI_ISL_19186934, EPI_ISL_19186953,
EPI_ISL_19187006, EPI_ISL_19187013, EPI_ISL_19187020,
EPI_ISL_19187026-19187028, EPI_ISL_19187152-19187153, EPI_ISL_19187161,
EPI_ISL_19187284, EPI_ISL_19187286, EPI_ISL_19187288,
EPI_ISL_19187290, EPI_ISL_19187400-19187401
</details>

**Comment by aviczhl2** [comment]
No growth of this.
