### ISSUE TITLE
New LE.1 (= JN.1.4.7/R346T) sublineage got S:L84V S:F456L and S:Q173K  (8)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1612]
**Full credit to @ryhisner who spotted the first sample (that has also S:V>H445R) from Minnesota weeks ago**

Just spotted a new sublineage of LE.1 (JN.1.4.7 with S:R346T) that got S:L84V and then S:F456L and S:Q173K 
Recency of samples suggest it is or fast or prevalent in some undersampled area , recalling that JN.1.4.7 was sampled in multiple African countries it could be that also this one arose there.

Defining mutations:
LE.1 > C10615T, C23638T, Orf7a:t120I (C27752T), G29254T > C6040T, S:L84V (C21812G) > T29194C > T7396C, S:Q173K (C22079A), S:f456L (T22928C), Orf7a:A66V (C27590T)
Query: T7396C, C27590T, C22079A,  
Samples: 7
Countries: Canada , Us and via GBW France and Spain

Tree: 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3e753_af7e90.json?c=country&label=id:node_7091849
<img width="1169" alt="Screenshot 2024-06-13 alle 15 57 48" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a94f95e9-ef5f-42ce-828f-3237c93be882">

Genomes: EPI_ISL_19148675, EPI_ISL_19162370, EPI_ISL_19184862,
EPI_ISL_19184966, EPI_ISL_19191540, EPI_ISL_19191560,
EPI_ISL_19192761

Query for 445R branch : T7396C, C27590T, C22079A

**Comment by FedeGueli** [comment]
8 now

**Comment by aviczhl2** [comment]
Designated LE.1.3.1

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/a4d280c81f0e30a31a651c00d1dd5d9f1fb82fa7

**Comment by ryhisner** [comment]
An interesting one to watch for sure. Q173K seems to show up in a lot of interesting sequences. It's an uncommon reversal of the ongoing trend toward negative charge in the NTD, similar to how Q493E is a reversal of the increasing positive-charge movement in the RBM.
