### ISSUE TITLE
KP.3.1 + S:F59S + Orf1a:E36D + Orf10:I4V (60 from 17 countries including Brazil and Georgia)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1615]
Just spotted a sublineage of KP.3.1 carrying the convergent and beneficial (in Jn.1)  mutation S:F59S ,
it has been sampled two times by GBW airport surveillance from travellers from Spain and Brazil and it has been locally sampled in Spain , all very recent. Interestingly these samples have mutations both  toward the 5'  end (G373T)  and toward the 3' end of the virus with one mutation in Orf10 and two mutations  in the 3' end UTR (4/5) (A29567G, G29706T G29781T)
Two samples have a further spike mutation S:A260T but likely from the same traveller.
It is interesting that three out of six defining mutations are  G>T  trasversions.

Defining mutations:
Kp.3.1 > orf1a:E36D (G373T), A9235G, S:F59S (T21738C), Orf10:I4V (A29567G), G29706T , G29781T (4/5)

New Query: A9235G, T21738C, G15372T by @aviczhl2 in #1756
Old Query: G373T, A9235G

Samples: 5 ( 3 Spain , 1 Spain via GBW 1 Brazil via GBW)
IDs:EPI_ISL_19162492, EPI_ISL_19191338, EPI_ISL_19191730,
EPI_ISL_19193946, EPI_ISL_19193970

Tree:
<img width="1181" alt="Screenshot 2024-06-13 alle 22 00 08" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7db5d4c6-8b63-4511-9c52-e73e0b0d54dd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_249b2_b4bbd0.json?c=userOrOld&label=id:node_6996822

**Comment by FedeGueli** [comment]
ping @corneliusroemer 
@ryhisner not sure if interesting for you but you are def the 3' UTR man here!

**Comment by ryhisner** [comment]
Yeah, this is super interesting! The other notable thing is that although G373T is in the ORF1a coding region, it's still part of an extensive stem-loop structure that resembles the 5' UTR and which I think likely plays a role in the structural functions of the 5' UTR. Looking at the conventional secondary RNA structures, there's no obvious connection between the 3' UTR mutations, but there could still be something non-obvious happening.

And I think there's a decent change G373T is in someway connected to one of the 3' UTR mutations. I'll try to do some investigating to see what the posited connections between the 3' UTR and 5' UTR are. I know I've seen a few secondary structure maps that laid out possible places where they could interact.

**Comment by ryhisner** [comment]
Here's a view of where those 3' UTR mutations are located. s2m is of course mostly deleted (∆29734-29759) in all Omicron, but according to a couple analyses I've seen, the s2m deletion isn't expected to cause any major changes in the rest of the 3' UTR structure. 
<img width="1342" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2a31b7d9-842b-479c-b1a4-9906b74554d4">

**Comment by FedeGueli** [comment]
Thank you @ryhisner ! Great!

**Comment by FedeGueli** [comment]
8 with GBW samples from Spain,Brazil, Iceland

**Comment by FedeGueli** [comment]
13

**Comment by FedeGueli** [comment]
it expands further but seems quite slow

**Comment by FedeGueli** [comment]
Sudden spike for this one now 23.  Spain uploaded from 4 different regions this means this was able to spread geographically despite KP.3.1.1

**Comment by FedeGueli** [comment]
49 3 new countries (Ru, Nor, Isr)

**Comment by FedeGueli** [comment]
60 Greece Sweden

**Comment by aviczhl2** [comment]
Designated KP.3.1.8

**Comment by Over-There-Is** [comment]
This lineage is not able to be identified by usher yet. @angiehinrichs

**Comment by AngieHinrichs** [comment]
> This lineage is not able to be identified by usher yet. @AngieHinrichs

Sorry, I took a vacation last week and now there are 75 new lineages to annotate on the tree.  (Not to mention the hundreds of emails).  I will annotate them ASAP, hopefully today & tomorrow.

**Comment by FedeGueli** [comment]
MY.1 revived after a while with 3 samples from 3 continents collected in mid December .
One of them has S:T22N Query: C5787T, A21625T, T25679G,
<img width="1171" alt="Screenshot 2025-01-08 alle 23 21 41" src="https://github.com/user-attachments/assets/8447be72-09d7-4fb2-bddd-c30cb97e1d0f" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_3b675_ef78e0.json?c=userOrOld&label=id:node_7358948

**Comment by FedeGueli** [comment]
> MY.1 revived after a while with 3 samples from 3 continents collected in mid December . One of them has S:T22N Query: C5787T, A21625T, T25679G,  

Proposed now in #2424  with a different query
