### ISSUE TITLE
XDV.1+Orf1a:L3116F, S:R346T, N:I292T (13 seqs, China, 10 with S:K462R)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1617]
XDV.1 has reached 30% share in China. And it has got some FLiRT lineages now.

XDV.1+C9611T, T29148C,G22599C(Orf1a:L3116F, S:R346T, N:I292T)
GISAID query: C9611T, T29148C,G22599C,C11572T
GISAID query for S:K462R branch:C9611T, T29148C,G22599C,C11572T,A22947G
No. of seqs: 2(Shanxi, Hubei)

EPI_ISL_19110341, Shanxi, 2024-4-18
EPI_ISL_19167569, Hubei, 2024-5-6

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_32ec8_bfc180.json?label=id:node_5499672)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/4b4c0523-c06c-4855-b493-330571a64b30)

**Comment by aviczhl2** [comment]
+1 Heilongjiang

**Comment by aviczhl2** [comment]
+1 Sichuan. The 4th province distant from existing 3.

**Comment by FedeGueli** [comment]
OT there is also a G181V 478Q under XDV.1 : https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_489ee_66d700.json?label=id:node_7062128
G22104T, C25782T,C17550T

**Comment by aviczhl2** [comment]
No new seqs

**Comment by aviczhl2** [comment]
+9 Heilongjiang with additional S:K462R.

**Comment by HynnSpylor** [comment]
Also notice that 9 of 10 seqs on K462R branch get C11750T(ORF1a:L3829F) , which emerged in XBB.16*

**Comment by aviczhl2** [comment]
Designated XDV.1.2 and XDV.1.2.1

**Comment by Over-There-Is** [comment]
most of XDV.1.2.1 have del29729-29776.

**Comment by FedeGueli** [comment]
> most of XDV.1.2.1 have del29729-29776.

cc: @ryhisner
