### ISSUE TITLE
KP.2.3 (∆S31) + S:N185T, ORF8:∆53-92 (oof) [43 seq, 4 continents; July 3]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1618]
**Description**
**Sub-lineage of:** KP.2.3 (S:∆S31, H146Q, R346T, F456L)
**Earliest sequence:** 2024-4-22, Singapore — EPI_ISL_19096038
**Most recent sequence:** 2024-6-11, Ireland, Dublin — EPI_ISL_19196009
**Continents circulating:** Asia (7), Europe (4), North America (2), Africa (1)
**Countries circulating:** Ireland (4),  Singapore (3), Canada (1), Hong Kong (2), India (1), Kenya (1), Taiwan (1), USA (1)
**Number of Sequences:** 14
**GISAID Nucleotide Query:** A22116C, G25593T, C28714T
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & [3-of: A22116C, G25593T, C28714T]
**Substitutions/Deletions on top of KP.2.3:**
**Spike:** N185T
**ORF8:** ∆53-92
**Nucleotide:** A22116C, ∆28050-28168, C28714T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.2.3_N185T_ORF8_deletion.json?c=gt-S_185&gmax=25384&gmin=21563&label=id:node_5611638
<img width="1429" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0c0beeb3-24ca-4c16-92ce-12009ae891ce">

**Evidence**
There is one sequence from India from a traveler to the US and another from Kenya from a traveler to the US, both regions where there is virtually no surveillance, so it seems possible that this lineage is more widespread than its small numbers would suggest.

<img width="1468" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/65102802-7368-4025-9789-717a3d5e4221">

ORF8 has remained surprisingly intact in BA.2.86 thus far. There have been remarkably few stop codons and very little in the way of TRS destruction. But maybe ORF8 is just biding its time with JN.1, allowing a few immune-evasive spike mutations to pile up before obliterating itself (along with its tendency to reduce spike-surface expression). 

This lineage has a large ORF8 deletion, ORF8:∆53-92 (∆28050-28168) that registers in most sequences as dropout, along with various artifactual mutations along the edges of the deletion, which causes the Usher tree to be more divided than it really should be. Two recent sequences from Ireland, however, have gotten the deletion right. 

A stop codon almost immediately follows the deletion (TAA from 28172-28174, or ORF8:93-94)

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19093699, EPI_ISL_19096038, EPI_ISL_19146033,
EPI_ISL_19146038, EPI_ISL_19178153, EPI_ISL_19181364,
EPI_ISL_19182095, EPI_ISL_19185987, EPI_ISL_19189567,
EPI_ISL_19191245, EPI_ISL_19195345, EPI_ISL_19195347,
EPI_ISL_19196009, EPI_ISL_19196017
</details>

**Comment by FedeGueli** [comment]
+1 Ireland

**Comment by FedeGueli** [comment]
@ryhisner SO the orf8 is only 54 AA long in this lineage correct?

**Comment by ryhisner** [comment]
> @ryhisner SO the orf8 is only 54 AA long in this lineage correct?

Yes, exactly. Except in the one sequence that has ORF8:G8* of course.

**Comment by FedeGueli** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
43 now  please propose now!
