### ISSUE TITLE
KP.2.3 (S:∆S31) + S:V382L, ORF1a:I3090V (152 seq, 16 countries , Sep 5)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1619]
**Description**
**Sub-lineage of:** KP.2.3 (S:∆S31, H146Q, R346T, F456L, V1104L)
**Earliest sequence:** 2024-5-14, USA, Utah — EPI_ISL_19175796
**Most recent sequence:** 2024-6-2, Singapore traveler to USA—EPI_ISL_19195862; New York City, USA—EPI_ISL_19189066
**Continents circulating:** Europe (3), Asia (3), North America (2)
**Countries circulating:** Iceland (5), Ireland (2), Singapore (2), USA (2), India (1)
**Number of Sequences:** 12
**GISAID Nucleotide Query:** G22706T, A9533G
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & G22706T & [1-of: A9533G, C29095T]
**Substitutions on top of KP.2.3:**
**Spike:** V382L
**ORF1a:** I3090V
**Nucleotide:** A9533G,  G22706T, C29095T

**USHER Tree**
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_31972a_c78810.json?label=id:node_2377461
<img width="1500" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/4b6aff7f-7407-45ae-abcd-e00c1b32666e">

**Evidence**
Mainly of interest due to recency of collection, wide geographic spread, and the fact that one sequence is from a traveler from India. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19159306, EPI_ISL_19159313-19159314, EPI_ISL_19159318,
EPI_ISL_19162365, EPI_ISL_19162491, EPI_ISL_19175796,
EPI_ISL_19189066, EPI_ISL_19195199, EPI_ISL_19195626,
EPI_ISL_19195862
</details>

**Comment by FedeGueli** [comment]
+3 GBW samples i think

**Comment by FedeGueli** [comment]
19 please propose it

**Comment by FedeGueli** [comment]
26 now with around 6% of prevalence in Iceland

**Comment by FedeGueli** [comment]
BIG JUMP TO 41 FROM ENGLAND propose it @ryhisner

**Comment by FedeGueli** [comment]
50 now from 9 countries. it seems spreading in Uk Iceland Portorico and has been sampled from travelers coming from india and Singapore and in Hong Kong

**Comment by FedeGueli** [comment]
101 , 15 countries, @ryhisner please propose it.

**Comment by FedeGueli** [comment]
119 now , today six samples uploaded from Canada with S:R214L , likely just a cluster.

**Comment by FedeGueli** [comment]
126 @ryhisner  please propose it

**Comment by FedeGueli** [comment]
142 Sweden

**Comment by FedeGueli** [comment]
cc @ryhisner i would propose this one

**Comment by aviczhl2** [comment]
152, Also in Norway,
