### ISSUE TITLE
LB.1.3 + s:H445P + orf7a:T28I + N:T379I (12 in 4 countries) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1620]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/42c2150f-5ecd-4cae-9889-7101c1712df0)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/7398aca9-f24f-438c-a37d-c70d12642d5f)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39116_c895f0.json?c=gt-ORF7a_28&gmax=27759&gmin=27394&label=id:node_7140797

First Seq: 2024-05-20
Most Recent: 2024-05-24

Gisaid Query: T22896C, C27476T, C29409T, C18131T (Edited T>A22896C)

EPI_ISL_19191361 EPI_ISL_19191677 England/CLIMB-CM7YKO56/2024 EPI_ISL_19176173 Wales/CLIMB-CM7YMKXG/2024

**Comment by FedeGueli** [comment]
Thx for proposing i was monitoring this one too with  T3565C,C27476T, C29409T,22896C, good that now it is proposed

**Comment by FedeGueli** [comment]
+2 California and Uk (via GBW) this last one had S:N354S

<img width="1183" alt="Screenshot 2024-06-26 alle 01 39 58" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8b802171-be19-4e31-adca-00856d34781e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_20ceb_b11010.json?label=id:node_7142904

**Comment by Fearuncle** [comment]
Designed as LB.1.3.1
