### ISSUE TITLE
BN.1.3.5 saltation sequenced in France

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1621]
I noticed this odd BN.1.3.5 singlet sequenced 

hCoV-19/France/IDF-APHPSU_PSL-662405025479/2024|EPI_ISL_19193543|2024-05-12

<img width="2172" alt="Brave Browser 2024-06-14 23 26 50" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/f6b81fd7-ae71-4b81-b99b-c626ccf6ba59">

BN.1.3.5 wasn't common in France, much more so in East/South East Asia, so this could be an import rather than sequenced in a chronic patient.

<img width="1860" alt="Brave Browser 2024-06-14 23 28 51" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/daff2ce7-5b92-479f-9e18-d8b9089e76b6">

23 Spike amino acid substitutions:

```
P9S, S13C, H69N, P139S, G213E, P217L, F306L, R403K, K440R, 
S446G, G476S, F486L, S490Y, A570V,  T572I, Q613H, V615F, 
P621S, V642G, I670M, A688V, E1144Q, G1219V
```

Reversions to root (1):S446G

<img width="1020" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/bff19c63-d63c-4cdf-a07e-873ad541380b">

**Comment by ryhisner** [comment]
I think it's possible that BN* variants are for some reason especially good at causing chronic infections. They seem to be overrepresented relative to their modest share of cases, even at their peak. One unusual aspect of this one is H69N, which likely forms a glycan with S71. 

Also, the P9S + S13C combo is really confusing. P9L and S13I both shorten the signal peptide cleavage to eliminate C15, destroying the disulfide it forms with C136. I don't think anyone has ever looked to see if either P9S (which has occurred quite a few times) or S13C (extremely rare) does the same. But this one seems to have an intact C136, which is supposed to be an unstable arrangement, so it's hard to make sense of.

**Comment by corneliusroemer** [comment]
Here's another French BN.1.3 saltation - though definitely unrelated, and closest relatives are from Germany so less interesting

<img width="2192" alt="Brave Browser 2024-06-14 23 55 11" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/7f9adfa5-4c88-4b88-9e4d-db98847147ae">
hCoV-19/France/ARA-HCL024045158301/2024|EPI_ISL_19019122|2024-03-15

**Comment by ryhisner** [comment]
There was a similar one (not in sequence but in terms of branch length) from the Netherlands earlier in the year as well as from Texas (USA), Singapore, and Japan. Yunlong Cao and Ravi Gupta's paper on JN.1 hint at a possible reason that BN.1* variants seem to be disproportionately represented in chronic-infection branches like this: K356T evades antibodies involved in antibody-dependent cell cytotoxicity, perhaps making viral clearance difficult. 
https://www.biorxiv.org/content/10.1101/2024.01.29.577677v1
<img width="1044" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5cd6082c-2329-46b5-87d5-e124200d483c">

**Comment by FedeGueli** [comment]
@ryhisner about BN.1 and BN.1.3 especially it managed to become dominant in multiple countries S.Korea Vietnam Thailand and Hong Kong and it was the only one BA.2.75 reaching dominance that beyond the original Ba.2.75 in India  (CH.1 never did that)

**Comment by aviczhl2** [comment]
Seems no more of this.
