### ISSUE TITLE
JN.1.11.1 with ORF1b: A2143V and S: R346T branches,（22seqs,two get S:T572I）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1622]
JN.1.11.1>**ORF1b:A2143V(C19895T),S:R346T(G22599C)**_(>S:T572I(C23277T))_

I didn't find the exact the query yet

EPI_ISL ID:
EPI_ISL_19049694, EPI_ISL_19050099, EPI_ISL_19054210,
EPI_ISL_19057412, EPI_ISL_19110231, EPI_ISL_19139261,
EPI_ISL_19140214, EPI_ISL_19144427, EPI_ISL_19153324,
EPI_ISL_19153924, EPI_ISL_19153959, EPI_ISL_19162851,
EPI_ISL_19175900,EPI_ISL_19176020, EPI_ISL_19176062, 
EPI_ISL_19183327,EPI_ISL_19183335, EPI_ISL_19186634, 
EPI_ISL_19188579,EPI_ISL_19188718, EPI_ISL_19189368,
EPI_ISL_19191602

UshER tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3e7d_e78b20.json?f_userOrOld=uploaded%20sample&label=id:node_6995581
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/d06bf805-c378-4527-8d0c-66120a96f397)

**Comment by FedeGueli** [comment]
Duplicate proposed in https://github.com/cov-lineages/pango-designation/issues/2562 
Thank you for proposing
