### ISSUE TITLE
KP.1.1.1 + S:T572I, S:K679N (R), ORF1a:V3091I (14, July 9)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1623]
### **Description**
**Sub-lineage of:** KP.1.1.1 (S:K182N, R346T, F456L, V1104L, K1086R)
**Earliest sequence:** 2024-5-14, USA, NC — EPI_ISL_19175961
**Most recent sequence:** 2024-6-7, Canada, Ontario — EPI_ISL_19199202
**Continents circulating:** North America (5), Europe (1)
**Countries circulating:** Canada (3), USA (2), Finland (1)
**Number of Sequences:** 6 good sequences + some Ginkgo Bozoworks Garbage
**GISAID Nucleotide Query:** A22108C, C23277T, T23599C
**CovSpectrum Query:** Nextcladepangolineage:KP.1* & [2-of: A22108C, C23277T, G23599C]
**Substitutions on top of KP.1.1.1:**
**Spike:** T572I, K679N (R)
**Nucleotide:** G9536A, A22108C, C23277T, G23599C

**Phylogenetic Order of Mutations:** Unclear due to garbage Ginkgo Bozoworks sequences, including pooled samples

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.1.1.1_T572I_K679N.json?c=gt-S_572&gmax=25384&gmin=21563&label=id:node_7003949
<img width="1488" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ff80c247-4478-4a30-8232-c85cb7b5199e">

**Evidence**
The Usher tree for this one is unfortunately a mess with artifactual reversions and "unreversions" due to more Ginkgo Bozoworks tomfoolery, including pooled samples and bad individual samples. We've seen a lot of action around the FCS in JN.1 but nothing that's really caught fire. I doubt if this will either, but there's no doubt that the K679N reversion is real: the reversion is to 23599C when it was originally T23599.

The combination of K182N, R346T, F456L, and T572I is interesting in any case. And the fact that this has been seen in distant states in the US (Colorado and North Carolina), Canada (Ontario), and Finland means it's traveling well. It's apparently been partially present in some of the atrocious GBW sequences, so it could be in some other countries as well. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19175961, EPI_ISL_19186434, EPI_ISL_19193357,
EPI_ISL_19199154, EPI_ISL_19199165, EPI_ISL_19199202
</details>

**Comment by FedeGueli** [comment]
@ryhisner i was tracking another KP.1.1.1 with 572I you found in the past as: 
Branch 126 of #1089 
>TRIO found by @ryhisner
KP.1.1.1 > S:T572I (C23277T)
Query:C23277T,A22108C,C20104T
Samples: 11 USA

this seems a different one correct?

**Comment by ryhisner** [comment]
Is that the one with S:I100L that's mostly in Colorado? That's the other KP.1.1.1 + T572I branch that I see on the KP.1.1.1 tree. 
<img width="1484" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/bc46fb98-fc43-468a-a458-040caad37832">

**Comment by FedeGueli** [comment]
Apparently not that one it is for that reason i was asking, i wonder where did it finish then. let me recheck.

**Comment by FedeGueli** [comment]
Ok checked right now that one query you flagged weeks ago and i ve tracked in #1089 now finds both the KP.1.1.1 572I branches at least partially:
<img width="1170" alt="Screenshot 2024-06-19 alle 21 47 23" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3334b4af-76b7-44e4-a240-7307d4acdf85">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5afe0_3352b0.json?f_userOrOld=uploaded%20sample&label=id:node_7004502 
so i will redirect that to this issue.

**Comment by FedeGueli** [comment]
Designated MG.1 via https://github.com/cov-lineages/pango-designation/commit/f95ef962a259317a268b0b4a9c9ea2ba9e087f7f
