### ISSUE TITLE
JN.1.1.5+S:F456L+Orf1a:Q3346K, S:T572I misplaced under JN.1.1.6 (23 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1626]
It seems that there is JN.1.1.5+S:F456L(T22928C)) branch misplaced as JN.1.1.6+S:R346T+C9142T. 
Note this branch is different from KR.1 as it doesn't have Orf9b:T72I.
And this branch now has a S:T572I FLIRT branch. 

JN.1.1.5+T22928C(S:F456L)+C7768T,C10301A(Orf1a:Q3346K)+C23277T,A29467T(S:T572I)

GISAID query: C10301A,C23277T, C9142T,T22928C
No. of seqs: 6(USA 1 France 4 Canada 1)

First: EPI_ISL_19139084,France, 2024-4-5
Latest: EPI_ISL_19195900, USA, 2024-6-3

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice173_genome_test_ad72_f50320.json?label=id:node_5490735)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2eba780d-fe4e-461b-87ee-8463517b70b6)

**Comment by FedeGueli** [comment]
it si shwon in the tree with https://github.com/cov-lineages/pango-designation/issues/2557

**Comment by aviczhl2** [comment]
12, Luxembourg

**Comment by aviczhl2** [comment]
15, Germany

**Comment by FedeGueli** [comment]
<img width="1171" alt="Screenshot 2024-07-11 alle 08 46 56" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/cc7a9ed0-47f9-4328-b13f-991795083c21">
Also the branch above this one has recent sample including a mini Korean branch with S:Q183R

**Comment by aviczhl2** [comment]
+1 Spain

**Comment by aviczhl2** [comment]
22, Netherlands

**Comment by FedeGueli** [comment]
only 4 samples from July i think we can close it

**Comment by Over-There-Is** [comment]
26

**Comment by Over-There-Is** [comment]
47
