### ISSUE TITLE
LF.1 (JN.1.16.1.1) with S:K304Q (6 seqs, England)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1629]
**Defining Mutations:** `LF.1` > `C18912T` > `A22472C(S:K304Q)`
**Query:** `C18912T, A22472C`
**Earliest seq:** 2024-04-24 (`EPI_ISL_19108627`, England)
**Latest seq:** 2024-06-05 (`EPI_ISL_19197952`, England)
**Sampled Countries:** UK (6: EN)
<details><summary>Genomes: </summary>

for lineages.csv commit:
```
England/CLIMB-CM7YE5QJ/2024
England/CLIMB-CM7YEBMU/2024
England/CLIMB-CM7YGUUA/2024
England/CLIMB-CM7YJQX8/2024
England/CLIMB-CM7YMP7D/2024
England/CLIMB-CM7YMQWB/2024
```

epi_isl accessions:
`EPI_ISL_19151283, EPI_ISL_19108479, EPI_ISL_19108627, EPI_ISL_19165072, EPI_ISL_19197952, EPI_ISL_19146883`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1deee_17b920.json?f_userOrOld=uploaded%20sample&label=id:node_7083165
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/81388784-0e74-4581-99a1-7aa3a2521a62)

**Trivia:**
- It's been quite some time to see `S:K304Q` which can be quite homoplastic on `XBB` backbone popping up again.

**Comment by FedeGueli** [comment]
LE.1.2 got it as defining (S:K304N)

**Comment by FedeGueli** [comment]
it was a cluster closing it
