### ISSUE TITLE
JN.1.18.3 + S:∆S31, S:R190S, C27259A (rev) (20 seqs, 5 continents, Jun 21)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1635]
### **Description**
**Sub-lineage of:** JN.1.18.3 (JN.1 + S:R346T, F456V)
**Earliest sequence:** 2024-5-13, Sweden, Stockholm — EPI_ISL_19166238
**Most recent sequence:** 2024-6-4, United Arab Emirates (traveler to USA) — EPI_ISL_19195886
**Continents circulating:** Europe (4), North America (3), Asia (2), Oceania (2), South America (1)
**Countries circulating:** USA (3), Australia (2), Netherlands (2), UAE (2), Argentina (1), Denmark (1), Sweden (1)
**Number of Sequences:** 12
**GISAID Nucleotide Query:** C13620T, A29664G, G22132T, -A27259C 
(_Query suggested by fed to catch a GBW sample from India:  C13620T,G22132T,T22928G_)
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & !A27259C & [3-of: C13620T, A29664G, G22132T]
**Substitutions/Deletions on top of JN.1.18.3:**
**Spike:** ∆S31, R190S 
**3' UTR:** A29664G
**Nucleotide:** C13620T, ∆21653-21655, G22132T, A29664G

**Phylogenetic Order of Mutations:** C13620T  **→** A29664G (3' UTR) **→** G22132T (S:R190S) **→** C27259A (reversion)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1.18.3_S31del_R190S.json?c=gt-nuc_22132&gmax=23132&gmin=21132&label=id:node_7082128
<img width="1486" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/53458c6c-7037-4580-9001-3316d7cb8515">

**Evidence**
Several of these sequences are from travelers to the USA, including the two UAE sequences and the Argentina sequence. S:F456V doesn't seem as successful as F456L, so this lineage may be handicapped by this. It does, however, have S:∆S31, R346T, and R190S, which is starting to appear more lately. ∆S31 and R190S both add glycans, which can help shield spike from antibodies and also have important structural effects.

One sequence from Denmark supposedly has S:S31F, but I think this is a misread of a deletion. Denmark has had longstanding problems sequencing deletions. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19166238, EPI_ISL_19187993, EPI_ISL_19187995,
EPI_ISL_19192355, EPI_ISL_19193240, EPI_ISL_19194503,
EPI_ISL_19195632, EPI_ISL_19195710, EPI_ISL_19195886,
EPI_ISL_19197347, EPI_ISL_19201214, EPI_ISL_19201239
</details>

**Comment by FedeGueli** [comment]
is Orf10:N36S  real for you (i saw you didnt list it)?

**Comment by FedeGueli** [comment]
yeah likely just a conventional one but useful to flag things on Usher ;)

**Comment by FedeGueli** [comment]
+1 Japan

**Comment by FedeGueli** [comment]
20 now a cluster in Wales plus a GBW sample from India

**Comment by DailyCovidCases** [comment]
21 now

**Comment by FedeGueli** [comment]
> 21 now

Already proposed

**Comment by FedeGueli** [comment]
Designated MA.1 via https://github.com/cov-lineages/pango-designation/commit/17a53f071f9c378c379b3e31945c868f887af201
