### ISSUE TITLE
KP.3.2 with ORF1b:Y1761H [nsp14_Y237H] and S:S477D [S>N477D] (43 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1636]
**Defining Mutations:** `KP.3.2` > `C29530A` > `C5407T` > `C17745T, T18748C(ORF1b:Y1761H)` > `A22991G(S:S477D`, _on top of `G22992A/S:S477N)`_, `C25614T`
**Query:** `C17745T, A22991G`
**Earliest seq:** 2024-05-28 (`EPI_ISL_19199273`, Ontario, Canada)
**Latest seq:** 2024-06-03 (`EPI_ISL_19199282`, Ontario, Canada)
**Sampled Countries:** Canada (10: ON)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/ON-PHL-202408936/2024
Canada/ON-PHL-202408938/2024
Canada/ON-PHL-202408939/2024
Canada/ON-PHL-202408940/2024
Canada/ON-PHL-202408941/2024
Canada/ON-PHL-202408942/2024
Canada/ON-PHL-202408943/2024
Canada/ON-PHL-202408945/2024
Canada/ON-PHL-202408946/2024
Canada/ON-PHL-202408947/2024
```

epi_isl accessions:
`EPI_ISL_19199273-19199282`

</details>

**UShER:**

**Trivia:**
- This branch changed B.1.1.529 basal `S:S477N(G22992A)` to `S:S477D(A22991G)` through 2-nuc mutations.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4ac5e835-59c5-434e-a8e1-9de3655f8143)
- It might just be some targeted cluster seqs from Canada, the accession numbers hinted that. Coincidence or not, there's also another sub-branch of KP.3.2.4 from England with this 2-step mutation.

**Comment by FedeGueli** [comment]
> closing this one, probably a targeted cluster; however there's another branch mentioned above from England developed something odd (`C22506T/S:T315I`, `G23282C/S:D574H`), though most seqs are not on gisaid yet. ![image] 
C22506T, G23282C 1 on Gisaid

**Comment by FedeGueli** [comment]
yeah i think so!
