### ISSUE TITLE
KP.3.3 with Orf7b:I27V and Orf3a:W45C (574 seqs 16 countries ) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1637]
Hawaii is experiencing a surge in cases, with KP.3 at 30% of samples collected after May 15 it is very likely that it is the main driver of this new wave.
About 1/3 of KP.3 samples belong to a local lineage with two mutations outside the spike : Orf7b:I27V, Orf3a:W45C.
Even if unlikely this will turn to be other than founder effect it is worth checking if it will expand outside Hawaii
Two samples have been collected in US airports by GBW in travellers from France and South Korea, so it is likely this lineage has originated elsewhere maybe in Philippines or Polinesia.

Defining mutations:
KP.3.3>> orf7b:I26V (A27831G), Orf3a:W45C (G25527T)
Query: A27831G,G25527T
Samples:54 (Hawaii, US, Canada, Japan, France, South Korea)
Tree:
<img width="1164" alt="Screenshot 2024-06-19 alle 15 42 30" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5eb81df2-872f-4215-ba6a-67e5db41fef2">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_44525_2da2d0.json?label=id:node_7000250

IDs:
EPI_ISL_19101713, EPI_ISL_19153993, EPI_ISL_19164085,
EPI_ISL_19169331, EPI_ISL_19176013, EPI_ISL_19176060,
EPI_ISL_19176077, EPI_ISL_19176089, EPI_ISL_19176096-19176097,
EPI_ISL_19176104, EPI_ISL_19176117, EPI_ISL_19176122,
EPI_ISL_19176236, EPI_ISL_19178146, EPI_ISL_19182967,
EPI_ISL_19189030-19189031, EPI_ISL_19189387-19189388, EPI_ISL_19189406,
EPI_ISL_19189421, EPI_ISL_19189442, EPI_ISL_19189452,
EPI_ISL_19189608, EPI_ISL_19191625, EPI_ISL_19191829,
EPI_ISL_19193282, EPI_ISL_19193340, EPI_ISL_19193388,
EPI_ISL_19194098, EPI_ISL_19195948, EPI_ISL_19196556,
EPI_ISL_19197304, EPI_ISL_19197414, EPI_ISL_19197548,
EPI_ISL_19197564, EPI_ISL_19200405, EPI_ISL_19200425,
EPI_ISL_19200428, EPI_ISL_19200432, EPI_ISL_19200434,
EPI_ISL_19200450, EPI_ISL_19200454, EPI_ISL_19200492,
EPI_ISL_19200494-19200495, EPI_ISL_19200516, EPI_ISL_19200518,
EPI_ISL_19200530, EPI_ISL_19200541, EPI_ISL_19202350,
EPI_ISL_19203445, EPI_ISL_19203965

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
At the end of June this is around 20% in Hawaii .
It has been sampled in 5 States: US (5 states) , Japan (3 provinces), Canada (2 states), France and Israel.

**Comment by FedeGueli** [comment]
150 now, prevalence in Hawaii looks like growing further

**Comment by FedeGueli** [comment]
It seems going down where it emerged

**Comment by FedeGueli** [comment]
This topped 479 , with a wide geographical ditribution expecially in the pacific area Hawaii, French Polinesi, Japan and then Oceania with a GBW sample recently collected from a traveller from India!

ping @corneliusroemer

**Comment by FedeGueli** [comment]
539 new countries Hong Kong and Denmark: ping @corneliusroemer this sublineage has emerged as a local Hawaian lineage but it seems able to spread globally , maybe helped by tourism in the area of emergence

**Comment by FedeGueli** [comment]
574

**Comment by FedeGueli** [comment]
big but it cannot compete

**Comment by Walde1nsamkeit** [comment]
666
