### ISSUE TITLE
KP.2.2+S:T572I (35 seqs, 7 countries) and its sublineage with S:K182R,S:A846V (29)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1643]
KP.2.2+C23277T(S:T572I)

GISAID query: C23277T, A25359G, T21737C, -A2745G, -24364,-28468,-25455,-29410
No. of seqs: 12( USA 3(from China) UK 9)

First: EPI_ISL_19161980, UK, 2024-5-12
Latest: EPI_ISL_19206011, USA from China, 2024-6-7

There already exists some S:T572I singlets on other KP.2.2 branches. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_734f_76d740.json?label=id:node_5466747)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e1d8db7d-4e2d-437a-8379-382a37d325f2)

This has also a further main branch with two further spike mutations S:K182R,S:A846V
KP.2.2 > S:T572I (C23277T) > Orf1a:P1640S (C5183T = PLPRO_P77S),  S:K182R (A22107G), S:A846V (C24099T), A25315G
Query: C5183T, C24099T,T3565C (alternative query:C5183T, A22107G,C24099T edited)
Samples: 9
Note tha this sublineage has **8 spike mutations** from Vanilla JN.1 : 59S,K182R,346T,456L,S:t572I, S:A846V,S:1104L,S:K1266R

**Comment by FedeGueli** [comment]
greta catch i ve found that too last days but failed to write down a query to track it.
I have explicited the sublineage with 2 more spike mutations bringing the total to 8 spike mutations from vanilla JN.1.

**Comment by aviczhl2** [comment]
22, France

**Comment by FedeGueli** [comment]
26 now propose it please

**Comment by aviczhl2** [comment]
32,Singapore, Canada

**Comment by aviczhl2** [comment]
Seqs from Orf9b:N62S branch shall be excluded , actual count is 27.

**Comment by aviczhl2** [comment]
30, Sweden

**Comment by aviczhl2** [comment]
Add more -s.

**Comment by DailyCovidCases** [comment]
54 seqs total

**Comment by aviczhl2** [comment]
Only 32/25. I don't know how you get 54.

**Comment by FedeGueli** [comment]
WIth the query: C5183T, A22107G,C24099T i find 29 of the 182R-846V branch, @aviczhl2 i would propose it directly from there even if there was circulation in Asia without these two muts too.

**Comment by aviczhl2** [comment]
Looks slowed down, close it.

**Comment by FedeGueli** [comment]
Designated Kp.2.2.2 via https://github.com/cov-lineages/pango-designation/commit/f04d7b55346c83554f20eff9e5614c381d22b16b#diff-a121ea4b8cbeb4c0020511b5535bf24489f0223cc83511df7b8209953115d329R2576617

**Comment by FedeGueli** [comment]
revived in. one sample from Taiwan ( traveler from outside)
