### ISSUE TITLE
KP.1.1+S:F59S,S:T572I (20 seqs,5 countries)

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1646]
**KP.1.1(S:F456L,S:R346T)+S:F59S,S:T572I**
GISAID Query:C2488T, C19172T, T21738C, C23277T, C26735T
(suggested query: C2488T, C19172T, T21738C,C23277T finds 17)

EPI_ISL ID:
EPI_ISL_19181923, EPI_ISL_19182161, EPI_ISL_19182250,
EPI_ISL_19183300, EPI_ISL_19186883-19186884, EPI_ISL_19192229,
EPI_ISL_19192783, EPI_ISL_19208041, EPI_ISL_19210331,
EPI_ISL_19210346, EPI_ISL_19210627

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1678_953e80.json?f_userOrOld=uploaded%20sample
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/a0fcd211-4648-4a28-bb04-333886c19dfe)

Thanks for @FedeGueli and @aviczhl2 in #1632

**Comment by Memorablea** [comment]
> I ve added a query tha finds 17 samples: C2488T, C19172T, T21738C,C23277T

Update UshER tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1678_953e80.json?f_userOrOld=uploaded%20sample
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/595fb65b-df96-4d90-aa63-bf56149d3d33)

**Comment by FedeGueli** [comment]
> > I ve added a query tha finds 17 samples: C2488T, C19172T, T21738C,C23277T
> 
> Update UshER tree https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1678_953e80.json?f_userOrOld=uploaded%20sample ![image](https://private-user-images.githubusercontent.com/125779492/342314969-595fb65b-df96-4d90-aa63-bf56149d3d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA4MTQsIm5iZiI6MTcxOTIzMDUxNCwicGF0aCI6Ii8xMjU3Nzk0OTIvMzQyMzE0OTY5LTU5NWZiNjViLWRmOTYtNGQ5MC1hYTYzLWJmNTYxNDlkM2QzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMjAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTU0ZDI4YThmZjE2NDQwN2M0YmI4ZjgyM2I0MWYzOTg3OTFjMzU2YmQ5NGVjNjQ4NTRhYWZmMTczNzEzYzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mVHoFc2Vw3tB2poGhUZ_qqG-aNbKnJEOuR3pUYtMzxA)
> 
> Please add the S: 27 tag @FedeGueli

S:27 is tricky especially from Singapore they read many times the deletion this way, have you checked the nucleotide sequence with the deletion?

**Comment by Memorablea** [comment]
USA+1 18

**Comment by Memorablea** [comment]
USA+1 Ireland+1 20now

**Comment by FedeGueli** [comment]
pls propose it

**Comment by Memorablea** [comment]
> pls propose it

If I don't request it from the Pango repository, it can still be specified. isn't it?

**Comment by Mydtlwn** [comment]
Yes, it will still be designated, but there is a difference in meaning between proposing and not proposing. For some historically significant strains, it will allow more people to better understand them. Meanwhile, the variant with two convergent mutations is more significant in that repository.

**Comment by Memorablea** [comment]
> Yes, it will still be designated, but there is a difference in meaning between proposing and not proposing. For some historically significant strains, it will allow more people to better understand them. Meanwhile, the variant with two convergent mutations is more significant in that repository.

to https://github.com/cov-lineages/pango-designation/issues/2676

**Comment by FedeGueli** [comment]
> > Yes, it will still be designated, but there is a difference in meaning between proposing and not proposing. For some historically significant strains, it will allow more people to better understand them. Meanwhile, the variant with two convergent mutations is more significant in that repository.
> 
> to [cov-lineages/pango-designation#2676](https://github.com/cov-lineages/pango-designation/issues/2676)

thank you

**Comment by Memorablea** [comment]
34

**Comment by Memorablea** [comment]
56

**Comment by aviczhl2** [comment]
Designated MU.1

**Comment by FedeGueli** [comment]
@corneliusroemer this should not be a descendant of KP.1.1.5
