### ISSUE TITLE
XDV.1(S:F456L)+S:T572I (10 seqs, 6 countries, 2 GET S:A27S）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1647]
**XDV.1(S:F456L)>S:T572I>S:A27S**
Sorry, I haven't found a suitable search method yet.

EPI_ISL ID:
EPI_ISL_19160979, EPI_ISL_19165543, EPI_ISL_19181069,
EPI_ISL_19181802, EPI_ISL_19191740, EPI_ISL_19191759,
EPI_ISL_19197983, EPI_ISL_19205909, EPI_ISL_19206079,
EPI_ISL_19213506

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3985e_94ecd0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/70c5ba0f-5ada-4498-bc33-091d6771adeb)

**Comment by FedeGueli** [comment]
Thx this has been already proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1597

**Comment by Memorablea** [comment]
sorry
