### ISSUE TITLE
KP.2 with ORF1a:P1803L (nsp3_P985L = PLPro_P240L) and S:P793S (55 seqs, 14~18 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1649]
**Defining Mutations:** `KP.2` > `C5673T(ORF1a:P1803L)` > `C14220T` > `C23939T(S:P793S)`
**Query:** `C7113T, C14220T, C23939T`
**Earliest seq:** 2024-04-02 (`EPI_ISL_19145665`, Oman)
**Latest seq:**  2024-06-06 (`EPI_ISL_19206138`, _GBW_ sample with travel history to: Qatar)
**Sampled Countries:** UK (10: EN); Kuwait (8); USA (6: OH/2; _GBW_ samples with travel history to: Germany, Mexico, Qatar); Canada (3: AB; ON; QC); Japan (2); Oman (1); Portugal (1); Spain (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/AB-ABPHL-118607/2024
Canada/ON-PHL-202408700/2024
Canada/QC-L00744354001/2024
England/CLIMB-CM7Y8MIH/2024
England/CLIMB-CM7Y8WOT/2024
England/CLIMB-CM7YE9CW/2024
England/CLIMB-CM7YEIDW/2024
England/CLIMB-CM7YGEIZ/2024
England/CLIMB-CM7YGOFJ/2024
England/CLIMB-CM7YMKZF/2024
England/CLIMB-CM7YR7HX/2024
England/CLIMB-CM7YRPDN/2024
England/CLIMB-CM7YRXJX/2024
Japan/FR012-0177/2024
Japan/TKYnat17035/2024
Kuwait/Jaber20235200/2024
Kuwait/Jaber20269368/2024
Kuwait/Jaber20284395/2024
Kuwait/Jaber20295783/2024
Kuwait/Jaber20302365/2024
Kuwait/Jaber20317337/2024
Kuwait/Jaber20321317/2024
Kuwait/Jaber20324817/2024
Oman/CPHL_7242103/2024
Portugal/PT50983/2024
Spain/MC-HCUVA-20026263/2024
USA/CA-GBW-GKISBBBB38669/2024
USA/CA-GBW-GKISBBBC20350/2024
USA/CA-GBW-GKPLAAAA20616/2024
USA/NJ-GBW-GKISBBBC53819/2024
USA/OH-ODH-SC4031767/2024
USA/OH-ODH-SC4031778/2024
```

epi_isl accessions:
`EPI_ISL_19211035, EPI_ISL_19188332, EPI_ISL_19202270, EPI_ISL_19213726, EPI_ISL_19190138, EPI_ISL_19213695, EPI_ISL_19108369, EPI_ISL_19108432, EPI_ISL_19108364, EPI_ISL_19108357, EPI_ISL_19108346, EPI_ISL_19108425, EPI_ISL_19108601, EPI_ISL_19197859, EPI_ISL_19178800, EPI_ISL_19213984, EPI_ISL_19213990, EPI_ISL_19213996, EPI_ISL_19213967, EPI_ISL_19213969, EPI_ISL_19213970, EPI_ISL_19213972, EPI_ISL_19213973, EPI_ISL_19145665, EPI_ISL_19190764, EPI_ISL_19178539, EPI_ISL_19206138, EPI_ISL_19205982, EPI_ISL_19191318, EPI_ISL_19162497, EPI_ISL_19134377, EPI_ISL_19183092`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13feb_a66010.json?label=id:node_7006748
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/39d0c798-48d6-48f6-9ffc-229b5e3aaad1)

**Trivia:**
-  There are 3 seqs currently placed under a F456L-dropout subbranch, those are: `EPI_ISL_19145665, EPI_ISL_19202270, EPI_ISL_19178539`

**Comment by FedeGueli** [comment]
PLPRO_P240L could be interesting it is placed at the itnerface between Palm and Fingers of Pocket 2 of SC2 PLpRO
I have no idea of what kind of impact it could have tough. Maybe @ryhisner studied that a bit ?
<img width="748" alt="Screenshot 2024-07-12 alle 12 53 06" src="https://github.com/user-attachments/assets/df0044fb-59ae-4f3e-a3c2-822a48d75df9">

**Comment by FedeGueli** [comment]
55 one recent sample from Scotland in August,but it is still fading away

**Comment by FedeGueli** [comment]
Designated KP.2.25.3 via https://github.com/cov-lineages/pango-designation/commit/a3d38ca258578e6487aebe3e976302f258aeaeef#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1204
