### ISSUE TITLE
FY.1 (XBB.1.22.1.1) sublineage with S:K478R (67 seqs mainly in USA)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#165]
*Separated from https://github.com/cov-lineages/pango-designation/issues/1965

Defining mutations: FY.1>A22995G (S:K478R), A19134G, C25836T
GISAID query: Spike_Y200C, Spike_T478R, A19134G, G18811A or (G18811A,A24813G edited)
Earliest seq: 2023-04-06 (USA, EPI_ISL_17637501)
Most recent seq: 2023-05-11 (Taiwan Region, EPI_ISL_17645470)
Countries detected: USA (7), China (1, from Taiwan Region) 

Usher Tree:
![QQ截图20230612041632](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/c6e9640f-8b07-4a30-8b0d-69c9f8cbc978)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8963_62b260.json?c=gt-S_478

A small lineage of FY.1 with S:K478R. 7 of 8 further get S:D1084G (nuc A24813G). I'll track it for a time.

Genomes:
EPI_ISL_17535060, EPI_ISL_17550839, EPI_ISL_17581991, EPI_ISL_17589030, EPI_ISL_17651675, EPI_ISL_17695163, EPI_ISL_17706307, EPI_ISL_17744373

**Comment by FedeGueli** [comment]
My query : G18811A,A24813G finds 9. 
8 of them have S:D1084G predicted to be slighty beneficial by Bloom lab calculator:
![Schermata 2023-06-13 alle 10 51 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/067e3a0f-f3b3-4c70-be35-2eddb902e2e4)https://jbloomlab.github.io/SARS2-mut-fitness/S.html

**Comment by FedeGueli** [comment]
Weirdly it is not expanding..

**Comment by FedeGueli** [comment]
1 more from Florida

**Comment by FedeGueli** [comment]
23 now, last ones from Japan and California. i think  u should propose if reaches 40

**Comment by FedeGueli** [comment]
No samples from July. . last ones uploaded from CHina, Tawan, Japan and US

**Comment by FedeGueli** [comment]
still slow, closing it.

**Comment by HynnSpylor** [comment]
It seems rising again (52 seqs now and 15 seqs updated in last 7 days).
The recent samples are with S:N185S and S:I569T 
I suggest reopening it.

**Comment by FedeGueli** [comment]
67 as today

**Comment by FedeGueli** [comment]
It cannot compete:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G18811A%2CA24813G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated FY.1.4 via https://github.com/cov-lineages/pango-designation/commit/1a048d512a836568457999f6e8d49a45af853a97
