### ISSUE TITLE
KP.3.2/JN.1* recombinant with additional S:S31F (29 seqs, 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1650]
_Spotted and discussed first by @JosetteSchoenma in #1576_ 

There seems to be a new S:S31F branch that emerges from a recombinant of KP.3.2 and JN.1*

JN.1--KP.3.2

Breakpoint between 2612 and 7112

Additional mutations: T772C, C1473T,C7998T, T12101A,C12439T, C21654T, T22702C, T25510C
Orf1a:T403I, S2578F, S3946T
S:S31F
Orf3a:S40P

T772C from a JN.1* branch
A2611C>A reversion of the defining of KP.3.2 (edited)
T25510C from the branch including KP.3.2.3
C1473T,C7998T, T12101A,C12439T, C21654T, T22702C are private mutations

GISAID query: T772C, C7113T, T25510C
No. of seqs: 6(UK 4 Spain 2)

First:EPI_ISL_19198456, Spain, 2024-5-28
Latest: EPI_ISL_19213598, UK, 2024-6-13

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5933e_b3d010.json?label=id:node_5451532)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8d2fc56a-fc6c-4109-a73b-044c66505ee8)

**Comment by FedeGueli** [comment]
I have explicited the reversion, that is a key to understand that this is a recombinant

**Comment by JosetteSchoenma** [comment]
> I have explicited the reversion, that is a key to understand that this is a recombinant

Indeed. I thought A2611C had been reverted or an artifact because of missing coverage closeby. But of course, it being a recombinant explains that as well!

**Comment by FedeGueli** [comment]
10 new country France

**Comment by aviczhl2** [comment]
15, Australia

**Comment by FedeGueli** [comment]
18 new countries Denmaark, Ireland

**Comment by aviczhl2** [comment]
28, Canada, Luxembourg
