### ISSUE TITLE
Another JN.1.15.1+S:R346T branch(14 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1652]
There is one JN.1.15.1+S:R346T branch designated LU.1 following C19269T. 
There seems to be another recent one following T20865C in Ecuador.

JN.1.15.1+T20865C,G22599C(S:R346T)

GISAID query: T20865C, G22599C,A25758T
No. of seqs: 14(Ecuador 5 USA 9(2 from Ecuador))

First: EPI_ISL_19183059,USA, 2024-4-28
Latest: EPI_ISL_19214244, USA, 2024-6-17

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice113_genome_test_2ad89_aa50c0.json?label=id:node_5471412)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/265afb6f-98c9-4857-93d9-48e01c9e13bd)

**Comment by FedeGueli** [comment]
thx sorry i ve mssed this proposal. Interesting one.

**Comment by aviczhl2** [comment]
Designated LU.2

**Comment by FedeGueli** [comment]
LU.2 reached a very high prevalence in Ecuador recently around 30% . It has a new branch with an interesting mutation : S:L176F and S:F186S that i m going to propose: 
<img width="1164" alt="Screenshot 2024-07-18 alle 17 42 38" src="https://github.com/user-attachments/assets/eb0ac736-4372-4ce0-8448-5506cd7d6829">
Seeing it spreading so fast i checked if it had S:S31del but it has not it. a lot of diversity in the tree to track.
