### ISSUE TITLE
KP.3.1.1 + ORF1a:T2274I (50 seq.) >20% of cases in Iceland after June 15 (2 seq. with further S:H49Y and S:L176F)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1653]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/f0c5e46d-666e-4112-9cc4-158f02a8a848)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17c31_c1a450.json?label=id:node_6998569

First Seq: 2024-05-27
Most Recent: 2024-06-18

Gisaid Query: C7086T, A13121T

EPI_ISL_19210033 EPI_ISL_19210100 EPI_ISL_19210084 EPI_ISL_19210080 EPI_ISL_19210094 EPI_ISL_19210086 EPI_ISL_19210089 EPI_ISL_19210074 EPI_ISL_19210034 EPI_ISL_19210061 EPI_ISL_19208010 EPI_ISL_19210079 EPI_ISL_19210035 EPI_ISL_19210093 EPI_ISL_19210081 EPI_ISL_19210090 EPI_ISL_19210078

**Comment by Huachuan1120** [comment]
There are now 25 related sequences.

**Comment by Huachuan1120** [comment]
> There are now 25 related sequences.

27 now.

**Comment by FedeGueli** [comment]
5/24 in Samples collected in iceland or from travelers coming from Iceland after June 15

**Comment by Huachuan1120** [comment]
There are now 39 related sequences. 
Two of them are sequences of 0-year-old girls from the same place in Spain: 
1️⃣ EPI_ISL_19255968, collected on June 24; 
2️⃣ EPI_ISL_19255982, collected on June 26. 
These two sequences belong to one KP.3.1.1+ORF1a:T2274I+ ORF1ab: R7014C+S:R346T+ ORF6: 136V! The emergence of S:R346T surprised me very much, so I think it is necessary to pay more attention to this branch, such as seeing if more relevant sequences will be reported in the future.
![IMG_0190](https://github.com/user-attachments/assets/ea8da5a3-d13b-43d6-ae07-6eca1a7140c6)

**Comment by Huachuan1120** [comment]
Canada +1 ➡️EPI_ISL_19264152, collected in Canada on July 1, brings the total number of this branch to 40.

**Comment by Huachuan1120** [comment]
The United States + 1, Portugal + 1, Canada + 1. 
Now there are 43 sequences.

**Comment by Fearuncle** [comment]
reached 50

**Comment by FedeGueli** [comment]
Pls propose it
