### ISSUE TITLE
KP.3.1 + S:R346T, H445R; ORF1a:L293F, S1272G, T2069N, D2592Y (12 seq, [10 USA, 1 JPN, 1 UAE]; Jul 24)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1655]
### **Description**
**Sub-lineage of:** KP.3.1
**Earliest sequence:** 2024-6-8, USA, Colorado – EPI_ISL_19217715, EPI_ISL_19217894
**Most recent sequence:** 2024-7-9, USA, Iowa - EPI_ISL_19284825 and USA, New York - EPI_ISL_19277632
**Continents circulating:** North America (10), Asia (2)
**Countries circulating:** USA (10), Japan (1), United Arab Emirates (1)
**Number of Sequences:** 12
**GISAID Nucleotide Query:** C6471A, G22599C, G22895C, T22896G
**CovSpectrum Query:** Nextcladepangolineage:KP.3.1* & [2-of: G22599C, A22896G]
**Substitutions on top of KP.3.1:**
**Spike:** R346T, H445R
**ORF1a:** L293F, S1272G, T2069N, D2592Y
**Nucleotide:** C1142T, A4079G, C6471A, A7432G, G8039T, T19305C, G22599C, A22896G 

**Phylogenetic Order of Mutations:** T19305C   **→**   G8039T (ORF1a:D2592Y)   **→**   A4079G (ORF1a:S1272G)   **→**   C1142T (ORF1a:L293F)   **→** C6471A, A7432G, G22599C, A22896G (S:R346T, S:H445R, ORF1a:T2069N)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.1_v445r_r346t.json?c=gt-S_445&gmax=25384&gmin=21563&label=id:node_7003604
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/5c180507-a6b2-439d-9899-68ac28c51703">

**Evidence**
These are just the 3rd and 4th KP.3 sequences with S:R346T, and they are the first with evidence of transmission. Clearly, there is something about R346T that does not mesh well with S:Q493E. I don't think it's a coincidence that S:H445R showed up simultaneously with R346T here. Historically, R346T has been nearly incompatible with N450D, for reasons that remain unclear. H445R is a significant shift toward more positive charge, so perhaps it somehow is able to neutralize whatever deleterious interaction R346T and N450D have. 

Also worth noting is ORF1a:S1272G, a very rare mutation that when it appears, is often associated with chronic infections. Here it appears to have been acquired in circulation and is transmitting well. 

**Genomes** - Note: There are still three sequences on Usher from New York that are not on GISAID. I'm pretty sure there's a lab in New York whose sequences never get uploaded to GISAID but which show up on Usher trees, so I'm not sure if these sequences will ever be on GISAID.
<details>
<summary>Genomes</summary>
EPI_ISL_19217715, EPI_ISL_19217894, EPI_ISL_19221915,
EPI_ISL_19231606, EPI_ISL_19262935, EPI_ISL_19273796,
EPI_ISL_19277632, EPI_ISL_19284824-19284825
</details>

**Comment by plomano** [comment]
Remove a positive charge (R-T), alter 445 to a more positive charge (H-R). Very interesting observation!

**Comment by FedeGueli** [comment]
this could be a thing.

**Comment by FedeGueli** [comment]
cc @ryhisner i looked at bit further in the past emergences of S:V445R on Jn.1 Backbone:
First there are only 24 samples of 445R in the pandemic.
11/24 have been sampled after April 2024
9 out of these recent 11 had S:R346T !

There is some epistasis at work considering the prevalence of S:R346T in these months after April was 38% peaking at 50% in May (2024)

Tree of recent JN.1+445R:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3f4ff_edff20.json?c=gt-S_346,445&f_userOrOld=uploaded%20sample&gmax=25384&gmin=21563&label=id:node_6921382
<img width="1172" alt="Screenshot 2024-06-28 alle 18 39 59" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f92530a8-8555-4a92-a845-554407e250c5">


[The input of this analysis was that today another recent sample with 445R was uploaded from Canada and again it had also S:R346T (Jn.1.13.1)]

**Comment by ryhisner** [comment]
> +1 Japan `EPI_ISL_19231606`

To me, that fact that this has jumped the Pacific is a pretty big deal. It could still just be a fluke thing that never has a major impact, but I think there's at least a chance that this branch could open up a new fitness landscape for KP.3. We'll see what it does in the next few weeks.

**Comment by FedeGueli** [comment]
> > +1 Japan `EPI_ISL_19231606`
> 
> To me, that fact that this has jumped the Pacific is a pretty big deal. It could still just be a fluke thing that never has a major impact, but I think there's at least a chance that this branch could open up a new fitness landscape for KP.3. We'll see what it does in the next few weeks.

agree Ryan to me is a new thing. Faster than other fast lineages hard to say now

**Comment by ryhisner** [comment]
I don't know why they aren't on GISAID, but from the Usher tree, it's clear that there are four sequences from New York, two from Colorado, and the one from Japan. The collection date for the NY sequence on the top-right is June 25. 
<img width="1512" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/04234d6b-4397-4070-a40c-aa393227a468">

**Comment by FedeGueli** [comment]
great catch Ryan! propose it when it turns 10

**Comment by FedeGueli** [comment]
maybe they will be uploaded in one batch especially the NYULH ones seems plausible to think that way

**Comment by ryhisner** [comment]
One more uploaded, a travel sequence to the USA from the United Arab Emirates. 
EPI_ISL_19273796

This isn't growing fast, but its geographic range could mean it's present in some undersequenced regions of the world.

**Comment by FedeGueli** [comment]
> One more uploaded, a travel sequence to the USA from the United Arab Emirates. EPI_ISL_19273796
> 
> This isn't growing fast, but its geographic range could mean it's present in some undersequenced regions of the world.
one more uplaoded the saem day but from NY , local sample-

**Comment by FedeGueli** [comment]
Thank you for proposing! my last comment was incomplete , i see now two more samples from Iowa.

**Comment by FedeGueli** [comment]
Designated MK.3 via https://github.com/cov-lineages/pango-designation/commit/2b11a9d8c2daa2f71ba63d0ddf96e61e4d43a0d0

**Comment by FedeGueli** [comment]
Milestone already in the commit.
