### ISSUE TITLE
KP.2.3 with ORF1a:T2016K,S:K679R,S:H146Q,ORF3a:K67N,N:H145Y (42 seqs, 2 countries, mainly in Canada）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1656]
KP.2.3>**ORF1a:T2016K,S:K679R,S:H146Q,ORF3a:K67N,N:H145Y**

GISAID Query:A23598G, C28706T

EPI_ISL ID:
EPI_ISL_19153543, EPI_ISL_19165460, EPI_ISL_19165521,
EPI_ISL_19165530, EPI_ISL_19177729, EPI_ISL_19178378,
EPI_ISL_19178431, EPI_ISL_19178464, EPI_ISL_19178476-19178477,
EPI_ISL_19188338-19188344, EPI_ISL_19195652, EPI_ISL_19199151-19199153,
EPI_ISL_19199155-19199159, EPI_ISL_19199162, EPI_ISL_19199222,
EPI_ISL_19199268, EPI_ISL_19199293-19199295, EPI_ISL_19202258,
EPI_ISL_19205550, EPI_ISL_19210372, EPI_ISL_19210611,
EPI_ISL_19210646, EPI_ISL_19214322, EPI_ISL_19214401,
EPI_ISL_19214417, EPI_ISL_19215336, EPI_ISL_19216310,

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_b24_d33da0.json
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/03b2d19c-02a1-4f47-9d82-e393cc15fccf)

**Comment by aviczhl2** [comment]
Already proposed in #1603

**Comment by FedeGueli** [comment]
My fault.

**Comment by Memorablea** [comment]
> My fault.

o

**Comment by FedeGueli** [comment]
101 now
