### ISSUE TITLE
BA.2.12.1 saltation, USA (California, 3 counties, 3 seqs)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1658]
### **Description**
**Sub-lineage of:** BA.2.12.1
**Earliest sequence:** 2024-3-9
**Most recent sequence:** 2024-5-6
**Continents circulating:** North America (3)
**Countries circulating:** USA (3)
**Number of Sequences:** 3
**GISAID Nucleotide Query:** G5180A, C7420T, C13356T
**CovSpectrum Query:** Nextcladepangolineage:BA.2.12.1* & [6-of: C16608T, C18312T, G22132T, A22206G, G22770A, A22881G, T22896C, G22899T, A22995T]
**Substitutions/Deletions on top of BA.2.12.1 on Shared Branch #1:**
**Spike:** ∆Y144, R190S, R214H, D215G, K440R, V445A, G446V, N460K, K478I
**ORF1a:** D1639N, L3829F, T4364I
**ORF1b:** H1087Y
**E:** V62F
**Nucleotide:** C3874T, A5371G, G5180A, C7420T, C11750T, C13356T, C16608T, C16726T, T16776C, C18312T, ∆21992-21994, G22132T, G22203A, A22206G, A22881G, T22896C, G22899T, A22995T, T22942A, C23683T, G26428T

**Substitutions/Deletions on top of BA.2.12.1 on Branch #2:**
**Spike:** P9L, F157S, E340K, R346T, N417T, G482R, ∆A484, E554Q, A570V, K679R, T859S, V1177I
**N:** P279S
**Nucleotide:** A11600G, A16512G, C21588T, T22032C, C22033A, G22580A, G22599C, A22812C, G23006C, ∆23012-23014, G23222C, C23271T, A23598G, A24137T, G25091A, A25512T, G28001A, T28297C, C29108T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/chronic_multiples/main/BA.2.12.1_USA_CA__2024.json?label=id:node_4659742
<img width="1491" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/652a9771-e974-4b50-b7ce-4fca30034f1e">

**Evidence**
I think these sequences are all likely from the same patient, but because they were collected in three different counties in California, I suppose there is a small chance that these are three different patients, which is why I put this post together. Two of the counties border each other on the west coast of California while the third is on the eastern border of the state. 

There is dropout in all three sequences, so there is some uncertainty about the full mutational profile. Below is an approximation of the mutations in the most recent sequence, which was uploaded today but collected on May 6. 

<img width="1400" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9c16b4f5-4572-4e6a-8e86-4b366ad9946a">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19142916, EPI_ISL_19164072, EPI_ISL_19223353
</details>

**Comment by HynnSpylor** [comment]
Great Catch! Different counties are slightly worried, but the detail information is unknown. I wonder if we could confirm them.

**Comment by aviczhl2** [comment]
No further seqs
