### ISSUE TITLE
JN.1.49.1 got S:T22N,S:S31F,S:K182N,S:F456V ( 5 Samples , 5 countries including India,Singapore,Japan, Australia and NY,US)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1659]
I spotted this JN.1.49.1 with 4 beneficial mutation (22n,31F,182N,456V>FViRT), gained in two steps ,in a GBW sample from India, 

Defining mutations:
JN.1.49.1 >  C8917T, S:S31F (C21654T), S:F456V (T22928G), Orf10:I27K (T29637A) > G7393T, S:T22N (C21627A),S:K182N (A22108C)

Query:  G7393T  ,C21627A, A22108C
Samples: 5 from India (GBW), Singapore (GBW), Australia, NY, Japan
Tree:
<img width="1155" alt="Screenshot 2024-06-29 alle 08 19 09" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b8c1d7f7-2de9-4c8c-9e90-214d9908a7ac">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_372f7_fa3e30.json?label=id:node_6954814

IDs: EPI_ISL_19169383, EPI_ISL_19174966, EPI_ISL_19206131,
EPI_ISL_19221159, EPI_ISL_19221903

**Comment by ryhisner** [comment]
Wow, great spot, Fede! 

I think the most remarkable mutation here is the most inconspicuous one: T29637A. This has been in fewer than 100 sequences ever—and the majority of those sequences are very questionable, coming from labs known for high rates of sequencing errors. There may really be only ~20 genuine sequences with T29637A. It's so rare that I BLASTed two of these sequences to make sure something else wasn't going on, but both BLAST runs confirmed T29637A.

T29637 sits right on the edge of a stem-loop in the 3' UTR. There is some slight disagreement about the exact structure here between different studies—some have a larger loop at the end of this stem (see top two structures below) and others have the larger loop interrupted with two sets of paired nucleotides, leaving a smaller loop and bilateral bubbles preceding it (see bottom structure below). 

But probably the most important aspect of T29637 is that it is sits two nucleotides away from what most (but not all) 3' UTR structures identify as a pseudoknot formed between 29608-29614 and 29639-29645.


<img width="1386" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/120fd222-f42f-4dc5-88b5-a4ce7fdd4715">


<img width="1449" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/572f3b32-c97f-4550-b935-ccb09416ca6a">


<img width="1388" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7a23e805-d498-46ba-a427-ceddbea9d95a">


T29637 is conserved between SARS-CoV-2, SARS-CoV-1, and MERS-CoV. It could be argued that a better alignment for MHV (mouse hepatitis virus) and BCV (bovine CoV) it is also semi-conserved.
<img width="1491" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/287aa214-1dd3-40e7-a388-38d8d059aea5">

**Comment by Fearuncle** [comment]
Designated as MB.1 and MB.11

**Comment by ryhisner** [comment]
What's the link where you can see new designated lineages? I don't know why it's so hard to find that page on here.

**Comment by FedeGueli** [comment]
> What's the link where you can see new designated lineages? I don't know why it's so hard to find that page on here.

https://github.com/cov-lineages/pango-designation/commits/master/ in the other repo .

Thank you fot the 'orf10' explanation!!

**Comment by aviczhl2** [comment]
Designated MB.1.1

**Comment by FedeGueli** [comment]
Designated MB.1 and MB.1.1 via https://github.com/cov-lineages/pango-designation/commit/c714b71da82d4f759555f580dbacdaa9cdd5a506

**Comment by FedeGueli** [comment]
One sample (2 GBW) got also S:V445R:
<img width="1159" alt="Screenshot 2024-07-28 alle 00 01 05" src="https://github.com/user-attachments/assets/f51a6d5c-19be-4b96-a28f-6b5752f36b07">

**Comment by FedeGueli** [comment]
Better query for it: C8917T, C21654T,G7393T

**Comment by FedeGueli** [comment]
There should be. new sublineage of MB.1.1 adding two RBD mutations 444R 478E:
<img width="1177" alt="Screenshot 2024-08-31 alle 01 52 59" src="https://github.com/user-attachments/assets/241ad465-f59a-422f-993f-27cab3fe3f17">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_d52_259200.json?label=id:node_11628878
For now two GBW sequences, one patient so not worth proposing it: 
QUery: C16575T, G20011A

cc @aviczhl2
