### ISSUE TITLE
XBB.1.5 sublineage with S:Q173R and S:E554K (22 seqs in 6 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#166]
Defining mutations: XBB.1.5>A12790G>T23671C>A22080G (S:Q173R), G23222A (S:E554K), C9808T
GISAID query: Spike_Q173R, Spike_E554K, T23671C or A12790G,A22080G , G23222A  , C9808T (edited)
Earliest seq: 2023-04-08 (Canada, EPI_ISL_17644110)
Most recent seq: 2023-05-31 (Australia, EPI_ISL_17780104)
Countries detected: New Zealand (7), Australia (3), China (1), Canada (1), Italy (1)

Usher Tree:
![QQ截图20230612154610](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d55bca8f-8fa4-409f-a0ae-0d4556781b82)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_355df_6c5d30.json?c=gt-S_173,554

Description:
S:E554K is one of the popular convergent Spike mutations, while S:Q173R is relatively rare, once emerged in some Delta sublineage in Europe. 

Genomes:  
EPI_ISL_17625575, EPI_ISL_17644110, EPI_ISL_17739381, EPI_ISL_17739567, EPI_ISL_17740041, EPI_ISL_17740082, EPI_ISL_17740273, EPI_ISL_17740297, EPI_ISL_17740451, EPI_ISL_17741990-17741991, EPI_ISL_17767021, EPI_ISL_17780104,

**Comment by FedeGueli** [comment]
+2 from NZL doesnt seem to have traction also there. (2 out of 500+)

**Comment by FedeGueli** [comment]
two more from Australia i have come here to close it but lets wait if it expands further.

**Comment by FedeGueli** [comment]
lets wait another week.

**Comment by FedeGueli** [comment]
Only one sequence in the last batch from NZL closing it for now
