### ISSUE TITLE
KP.2.2 + S:T22N   (71, 13 countries likely emerged in Nepal) mostly with  ORF1b:K2660R (60)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1662]
Defining mutations:
KP.2.2 > T24364C >   S:T22N (C21627A) >> ORF1b:K2660R (A21446G),
NEW QUERY: T24364C ,C21627A   ( OLD 2 : A21446G,C21627A  (OLD 1 :T24364C ,A21446G,C21627A)
Samples: 71
First sampled on 2024-05-13 in NJ and few days after that in Nepal.
Country:Bhutan, US, France, Germany, China, India , Italy, Japan, Nepal, Singapore, Taiwan, Spain, UK
Tree:
 <img width="1163" alt="Screenshot 2024-08-25 alle 00 16 16" src="https://github.com/user-attachments/assets/a17222f1-4dad-4cbe-81b8-866dcb8e75eb">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_66a6f_a59210.json?label=id:node_7016742

IDs
EPI_ISL_19175957, EPI_ISL_19195789, EPI_ISL_19195940,
EPI_ISL_19196466, EPI_ISL_19196469, EPI_ISL_19196472,
EPI_ISL_19215569, EPI_ISL_19215579, EPI_ISL_19215584,
EPI_ISL_19221625, EPI_ISL_19227119, EPI_ISL_19227848,
EPI_ISL_19262919, EPI_ISL_19263096, EPI_ISL_19266639,
EPI_ISL_19268121, EPI_ISL_19273639, EPI_ISL_19273650,
EPI_ISL_19273754, EPI_ISL_19279853, EPI_ISL_19280236,
EPI_ISL_19281309, EPI_ISL_19284847, EPI_ISL_19286287,
EPI_ISL_19288317, EPI_ISL_19288321, EPI_ISL_19289660,
EPI_ISL_19289751, EPI_ISL_19298481, EPI_ISL_19298698,
EPI_ISL_19300171, EPI_ISL_19306360, EPI_ISL_19308849,
EPI_ISL_19309009, EPI_ISL_19309114, EPI_ISL_19310487,
EPI_ISL_19311662, EPI_ISL_19311737, EPI_ISL_19311762,
EPI_ISL_19315274, EPI_ISL_19317137, EPI_ISL_19318636,
EPI_ISL_19318656, EPI_ISL_19323618, EPI_ISL_19326342,
EPI_ISL_19328302, EPI_ISL_19328305, EPI_ISL_19328481,
EPI_ISL_19328538, EPI_ISL_19329420, EPI_ISL_19329974,
EPI_ISL_19333104, EPI_ISL_19338989, EPI_ISL_19339618,
EPI_ISL_19340061, EPI_ISL_19340255, EPI_ISL_19341177,
EPI_ISL_19341265-19341266, EPI_ISL_19346691, EPI_ISL_19346811,
EPI_ISL_19346825, EPI_ISL_19346919, EPI_ISL_19347330,
EPI_ISL_19349917, EPI_ISL_19350183, EPI_ISL_19350328,
EPI_ISL_19350667, EPI_ISL_19351728, EPI_ISL_19351751,
EPI_ISL_19353646

**Comment by FedeGueli** [comment]
new query finds 17 A21446G,C21627A

**Comment by FedeGueli** [comment]
too slow closing it

**Comment by aviczhl2** [comment]
25 seqs, found by GBW from Qatar and France , as well as Singapore, Austria and Canada

**Comment by FedeGueli** [comment]
> 25 seqs, found by GBW from Qatar and France , as well as Singapore, Austria and Canada

Reopened thanks!

**Comment by FedeGueli** [comment]
27

**Comment by FedeGueli** [comment]
32 10 countries

**Comment by Memorablea** [comment]
@corneliusroemer

**Comment by FedeGueli** [comment]
56 and growing, some samples have acquired S:T478T rev too

**Comment by FedeGueli** [comment]
It seems being able to keep the pace of KP.3 at least.

**Comment by FedeGueli** [comment]
i m proposing it , Query has changed again

**Comment by FedeGueli** [comment]
Designated KP.2.2.1 via https://github.com/cov-lineages/pango-designation/commit/efe8e07488add0710c5a21427ee3737ac5b1c8b9
