### ISSUE TITLE
LP.1 + S:R190S emerged inDominican Rep./ Puertorico ( 35 seqs, 6 countries including Dom.Rep, PR, Salvador)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1664]
Just spotted this one while looking at the LP.1.1 tree,
With LP.1.1 it shares the area where it is spreading in the Caribbean mayor islands.
It has the convergent S:R190S resulting in a new N GLycan N188

LP.1 > T14508C > T18300A > S:R190S (G22132T)

Query: T14508C , T18300A ,G22132T
Samples: 8
Countries: Dominican Republic ( 3 locally sampled 3 GBW) Puerto Rico (2)
Tree:
<img width="1117" alt="Screenshot 2024-07-01 alle 07 03 33" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bc6fa269-057e-4477-b538-b263f9f5de42">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice8_genome_test_1041f_2361f0.json?label=id:node_7017476

IDs:
EPI_ISL_19190680, EPI_ISL_19206074, EPI_ISL_19210377,
EPI_ISL_19214194, EPI_ISL_19214200, EPI_ISL_19215679,
EPI_ISL_19221154

**Comment by Memorablea** [comment]
14

**Comment by FedeGueli** [comment]
> 14

thx i see only ten, which query do you use?

**Comment by FedeGueli** [comment]
19 , mutliple US states, Canada and Rep.Dominicana

**Comment by FedeGueli** [comment]
24

**Comment by aviczhl2** [comment]
29 with GBW from Japan

**Comment by aviczhl2** [comment]
And there is a new S:445P branch under this.

**Comment by FedeGueli** [comment]
> And there is a new S:445P branch under this

I don't see that one, could u link the usher please?

**Comment by FedeGueli** [comment]
Designated LP.1.2 via https://github.com/cov-lineages/pango-designation/commit/138717a1911280c49a16b68a53efce4294356bf7

**Comment by FedeGueli** [comment]
There is. a branch of 4 sequences under LP.1.2 with further S:V445P
LP.1.2 > Orf1a:P1207H (C3885A) > S:V445P
Query: 22896C, T18300A ,G22132T
Tree:

<img width="1170" alt="Screenshot 2024-08-20 alle 00 04 45" src="https://github.com/user-attachments/assets/c16431be-3df0-4dfa-8dc2-fb656bfe87c1">

<img width="1175" alt="Screenshot 2024-08-20 alle 00 04 59" src="https://github.com/user-attachments/assets/bea93fa1-c04d-43e2-a256-271a98dfd391">
