### ISSUE TITLE
BA.2.86 sublineage with S:T478R and S:K444T in South Africa (11 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1665]
It seems that in South Africa managed to survive an undesignated sublineage of BA.2.86 
that has got S:K478R and S:K444T together with Orf1b:A2431V, some of the samples have also N:A134V.
This lineage due to the dropout is splitted in two branches and only two sequences have s:K444T but the remaining 9 have dropout at 444 so i think they all or most of them have S:K444T same for S:K478R that is dropout in the other branch:
<img width="528" alt="Screenshot 2024-07-01 alle 23 27 14" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5a1a9386-404e-4662-9300-3fa5a3d249ff">
Tree:
<img width="779" alt="Screenshot 2024-07-01 alle 23 25 31" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8061ca93-a6eb-494f-a3fc-02bfe6ffe23d">
<img width="1159" alt="Screenshot 2024-07-01 alle 23 27 44" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/818d5f69-8fce-42f3-a9e9-e14ccd538d2e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_3eedf_2d2e80.json?c=gt-S_444&label=id:node_7190852

Query: A2821G ,C20759T, C20844T
Samples: 11
Countries: South Africa
First collected on 2024-02-11
Last collected on  2024-05-09

IDs:
EPI_ISL_19025681, EPI_ISL_19025712, EPI_ISL_19029368,
EPI_ISL_19125701, EPI_ISL_19174182, EPI_ISL_19195271,
EPI_ISL_19195276, EPI_ISL_19195291-19195292, EPI_ISL_19195300,
EPI_ISL_19225600

**Comment by aviczhl2** [comment]
No new seqs

**Comment by HynnSpylor** [comment]
recently some seqs are still updated (even one in GA, US) despite very slow.
14 seqs now

**Comment by FedeGueli** [comment]
> recently some seqs are still updated (even one in GA, US) despite very slow. 14 seqs now

thank you for checking i m sure it is still there now

**Comment by Over-There-Is** [comment]
17 now, all of them have S:S31-

**Comment by FedeGueli** [comment]
> 17 now, all of them have S:S31-

Thx didnt spot that at the time it was going
