### ISSUE TITLE
GL.1 (XAY.1.1.1.1) with S:F490V (2 seqs in Portugal)  

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#167]
Defining mutations: GL.1>C5239T>T23030G (S:F490V)

GISAID query: Spike_F490V, Spike_D420N, C5239T
Earliest seq: 2023-05-18 (Portugal, EPI_ISL_17786106)
Most recent seq: 2023-05-29 (Portugal, EPI_ISL_17786176)
Countries detected: Portugal (2)

Usher Tree:
![QQ截图20230612195330](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/051e94f0-c0ec-4ad5-b1be-3dbde6eb312b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_176e5_704410.json?c=gt-S_420,490

GL.1 is a very new lineage with S:D420N, and today 2 seqs are updated from Portugal with S:F490V.
S:F490V once emerged in some Alpha (B.1.1.7) sublineages, and BJ.1 (BA.2.10.1.1) --one source of XBB*, despite site S:490 has been S since early XBB* lineages.  

S:F490V is considered as higher fitness than S:F490S by Bloom and Neher (2023). Despite 2 seqs only now, we can monitor for a time.
![QQ截图20230612195233](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/ce709eb6-8b02-4dde-b273-83587db7989c)
![QQ截图20230612195226](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/0d615e70-0d9f-44ef-ab1b-8f177db44363)

Genomes:
EPI_ISL_17786106, EPI_ISL_17786176

**Comment by Sinickle** [comment]
These also have S:144del, which seem to be on most but not all GL.1?

**Comment by FedeGueli** [comment]
Apparently died off. let me know if it something new pops up
