### ISSUE TITLE
KR.1 (FLiRT) got S:F59S (89, 10 countries including Philippines and Japan)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1670]
transferred back from https://github.com/cov-lineages/pango-designation/issues/2681
KR.1 >  S:F59S (T21738C)
Query: C28498T ,T22928C,C1762A,T21738C
Samples: 15
Countries: Australia, Canada, US, Philippines, Japan
IDs
EPI_ISL_19162486, EPI_ISL_19162527, EPI_ISL_19189341,
EPI_ISL_19190117, EPI_ISL_19191455, EPI_ISL_19192899,
EPI_ISL_19195692, EPI_ISL_19199242, EPI_ISL_19208173,
EPI_ISL_19210931, EPI_ISL_19220364, EPI_ISL_19220372,
EPI_ISL_19222088, EPI_ISL_19226740

Tree:
<img width="1170" alt="Screenshot 2024-07-02 alle 12 16 47" src="https://github.com/cov-lineages/pango-designation/assets/87669813/801165f3-b341-4db7-8960-fe07d663eb9f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_134e9_3caa80.json?c=userOrOld&label=id:node_7067364

**Comment by FedeGueli** [comment]
43 seqs 9 countries

**Comment by FedeGueli** [comment]
55 with a recent upload from California, i bet it mirrors circulation in Philippines.

**Comment by FedeGueli** [comment]
70

**Comment by FedeGueli** [comment]
75, South Korea

**Comment by FedeGueli** [comment]
89 new batch from South Korea

**Comment by aviczhl2** [comment]
The new South Korean branch has S:A435S and S:S680P. 

![image](https://github.com/user-attachments/assets/774f3510-bd89-4662-b677-bd62a898c0dc)

**Comment by FedeGueli** [comment]
@aviczhl2 thx for spotting that. i m reopening it in Pango where i mistakenly proposed it first.

**Comment by FedeGueli** [comment]
>> reopened https://github.com/cov-lineages/pango-designation/issues/2681

**Comment by xz-keg** [comment]
designated KR.1.4
