### ISSUE TITLE
Issue to Register Singlet Recombinants that shall be not be removed by usher (starting from 2024-7-2)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1675]
Successor issue of https://github.com/sars-cov-2-variants/lineage-proposals/issues/991 

> Anything with >5 reversion(refer to the last checkpoint ,usually a designation) or >20 private mutations(distance to the last node) may be removed by usher. However some of them are real recombinants.

> There are quite a few recombinants meeting this criteria. Whenever you happen to see any of them, please register them here to help those recombinant singlets not becoming invisible, hence when a 2nd seq appears we may easily realize the cluster.

As github only displays 60 comments at the same time for each issue, better refresh this issue for every 60 comments so that searching for specific recomb is easier.  

@FedeGueli @AngieHinrichs @ryhisner @NkRMnZr @JosetteSchoenma @corneliusroemer

**Comment by Mydtlwn** [comment]
I think it would be better to replace issues regularly every one to three months, with the expiration date and initiation date clearly marked in the title of each issue.

**Comment by aviczhl2** [comment]
EPI_ISL_19229374, HV.1/anything recomb.

**Comment by aviczhl2** [comment]
EPI_ISL_19231824, JN.1/XBB.1.16

**Comment by FedeGueli** [comment]
EPI_ISL_19254616 this is a quite interesting recombinant between LB.1 and an undesignated KR.1 + S:F59S with Orf1a:C3419Y.

<img width="1170" alt="Screenshot 2024-07-10 alle 09 15 49" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4209e79d-4642-41e5-aa59-111d1f8d4fbb">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_273ec_e17080.json?c=gt-S_59&gmax=25384&gmin=21563

It exchanged S:S31del with S:F59S confirming somewhat the observation of @ryhisner about incompatibility between 31del and S:59X

**Comment by aviczhl2** [comment]
EPI_ISL_19229782, KS.1/KP.3.1.1

**Comment by FedeGueli** [comment]
19259353 very recent From Mexico LB.1.3.1 with JN.1.7 resulting in a Full Quad JN.1 spike plus S:E1150D !

**Comment by aviczhl2** [comment]
EPI_ISL_19263582, LF.1.1.1/MG.1 with additional S:F59S and S:E654A.

**Comment by aviczhl2** [comment]
EPI_ISL_19264846, it has a JN.1+S;F456L spike but other places seems invovling complex recomb pattern. Some unique mutations are added on so unlikely pure contam.

**Comment by aviczhl2** [comment]
EPI_ISL_19261040, JN.1+S:F456L,Q493E spike with a unique Orf1ab that may involve recomb.

**Comment by ryhisner** [comment]
EPI_ISL_19266767

LB.1.2/KP.3 recombinant with S:L335S collected June 26 in Utah, USA. The only three sequences with the same ORF1a:∆1023-1026 collected in the past four months are all LB.1.2 from the US—two collected in the bordering state of Utah and one in Ohio.

**Comment by FedeGueli** [comment]
> EPI_ISL_19261040

there were two JN.1.4 with that Orf1b from Italy too back in early 2024, so likely that is the donor

**Comment by aviczhl2** [comment]
> > EPI_ISL_19261040
> 
> there were two JN.1.4 with that Orf1b from Italy too back in early 2024, so likely that is the donor (EPI_ISL_18831265)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_26393_73ed10.json?f_userOrOld=uploaded%20sample&label=id:node_6250736

It seems that the initial JN.1.4 is already is a recomb, and then it further recombs with KP*/ JN.1.16+Q493E. 

@corneliusroemer @ryhisner @JosetteSchoenma  what do you think of this branch?

**Comment by aviczhl2** [comment]
EPI_ISL_19267875, HK.3 recombs with sth. on Orf1ab.

**Comment by aviczhl2** [comment]
EPI_ISL_19283607, LP.3 recombs with some JN.1+S:K182E+S:F456L Spike. It doesn't have S:S31del but have other LP.3-definings.

**Comment by aviczhl2** [comment]
EPI_ISL_19304947, EG.5.1.1/JN.1+S:F456L

**Comment by FedeGueli** [comment]
mm bitht hte last ones from SKorea both with the same lilttle NTD switch and i think me or others have already posted some above similar to thse ones. i tend to think they are all artifacts.

**Comment by Over-There-Is** [comment]
EPI_ISL_19284930 EG.5.1.6*/JN.1 15935/~16342
JN.1> C27434T(Orf7a:T14I)> T24406G> G3692T(ORf1a:V1143F), T24951C(S:I1130T)

**Comment by FedeGueli** [comment]
EPI_ISL_19339136 LB.1.3/Kp.3.3 recombinant got 5'end from LB.1 till 456-493, it has 183H 346T 493E 1104L .
It is GBW from Poland
Tree:
<img width="1157" alt="Screenshot 2024-08-19 alle 00 26 48" src="https://github.com/user-attachments/assets/a4dbe230-707d-4186-b54f-27b97410b49c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice42_genome_test_27cee_265a70.json?c=userOrOld&label=id:node_11605762&s=hCoV-19/USA/CA-GBW-GKISBBBD24653/2024%7CEPI_ISL_19339136%7C2024-08-07

It is placed by Usher in the branch just below the XEC one.

**Comment by aviczhl2** [comment]
EPI_ISL_19269396, XDV.1/KP.1.2

**Comment by aviczhl2** [comment]
EPI_ISL_19351744, KP.1.1.1/LB.1.2

**Comment by FedeGueli** [comment]
there should be a KP.3.2/LB.1.7+C24421T sublineage that got the S2 from this LB.1.7 branch reverting S:V1104L and adding C24421T.
Interestingly it has got also a Sotrovimab known escape mutation with S:E340Q:
<img width="1170" alt="Screenshot 2024-08-28 alle 00 00 13" src="https://github.com/user-attachments/assets/06ae36a6-8ee0-400b-b623-3532a75547aa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a6e6_e4b0a0.json?c=userOrOld&label=id:node_7038399
Query: T12244C  ,T22292C, C24421T, 
Samples: 4 (3 w 340Q)
IDs:EPI_ISL_19272373, EPI_ISL_19353170, EPI_ISL_19353178,
EPI_ISL_19357751

**Comment by aviczhl2** [comment]
> there should be a KP.3.2/LB.1.7+C24421T sublineage that got the S2 from this LB.1.7 branch reverting S:V1104L and adding C24421T. Interestingly it has got also a Sotrovimab known escape mutation with S:E340Q: <img alt="Screenshot 2024-08-28 alle 00 00 13" width="1170" src="https://private-user-images.githubusercontent.com/87669813/361993920-06ae36a6-8ee0-400b-b623-3532a75547aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTcyMjMsIm5iZiI6MTcyNDc5NjkyMywicGF0aCI6Ii84NzY2OTgxMy8zNjE5OTM5MjAtMDZhZTM2YTYtOGVlMC00MDBiLWI2MjMtMzUzMmE3NTU0N2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIyMTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDQ3MWE0ZTUzYzAyODM0ZjYzNTI3ZDE3ZmMzZGNkZjllM2Y4ODI5YmViZWRhOTE2ZTU0YjMwMjg4ZjM4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8uLH3EvI2-gmy09mbElzWWGPixxmTiUUqOw12_fYS44"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a6e6_e4b0a0.json?c=userOrOld&label=id:node_7038399 Query: T12244C ,T22292C, C24421T, Samples: 4 (3 w 340Q) IDs:EPI_ISL_19272373, EPI_ISL_19353170, EPI_ISL_19353178, EPI_ISL_19357751

Please make a separate issue?

**Comment by FedeGueli** [comment]
> > there should be a KP.3.2/LB.1.7+C24421T sublineage that got the S2 from this LB.1.7 branch reverting S:V1104L and adding C24421T. Interestingly it has got also a Sotrovimab known escape mutation with S:E340Q: <img alt="Screenshot 2024-08-28 alle 00 00 13" width="1170" src="https://private-user-images.githubusercontent.com/87669813/361993920-06ae36a6-8ee0-400b-b623-3532a75547aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTcyMjMsIm5iZiI6MTcyNDc5NjkyMywicGF0aCI6Ii84NzY2OTgxMy8zNjE5OTM5MjAtMDZhZTM2YTYtOGVlMC00MDBiLWI2MjMtMzUzMmE3NTU0N2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIyMTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDQ3MWE0ZTUzYzAyODM0ZjYzNTI3ZDE3ZmMzZGNkZjllM2Y4ODI5YmViZWRhOTE2ZTU0YjMwMjg4ZjM4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8uLH3EvI2-gmy09mbElzWWGPixxmTiUUqOw12_fYS44"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a6e6_e4b0a0.json?c=userOrOld&label=id:node_7038399 Query: T12244C ,T22292C, C24421T, Samples: 4 (3 w 340Q) IDs:EPI_ISL_19272373, EPI_ISL_19353170, EPI_ISL_19353178, EPI_ISL_19357751
> 
> Please make a separate issue?

Done thx: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1942

**Comment by FedeGueli** [comment]
Not sure if this is LB.1 +22N or just a recombinant with XEC maybe :
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_3de05_f92a70.json?label=id:node_11619450
<img width="1161" alt="Screenshot 2024-08-28 alle 23 52 03" src="https://github.com/user-attachments/assets/1cf3d5e7-9c5e-447f-a04c-93ea5681dd32">

**Comment by aviczhl2** [comment]
> Not sure if this is LB.1 +22N or just a recombinant with XEC maybe : https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_3de05_f92a70.json?label=id:node_11619450 <img alt="Screenshot 2024-08-28 alle 23 52 03" width="1161" src="https://private-user-images.githubusercontent.com/87669813/362462422-1cf3d5e7-9c5e-447f-a04c-93ea5681dd32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODM0NjIsIm5iZiI6MTcyNDg4MzE2MiwicGF0aCI6Ii84NzY2OTgxMy8zNjI0NjI0MjItMWNmM2Q1ZTctOWM1ZS00NDdmLWEwNGMtOTNlYTU2ODFkZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIyMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMWFmNzk4NDQ1MmI1NjE4NzQ5ZjQ3ODYzMjUyNDRhM2Q1ZmVjNjIwM2JiODdlNDVlM2E3YzQzMzA1ZWE3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6SVeYBcdD5_vOHD_Te8ygY-rBeld1Q25IY3V3zngDk">

It doesn't have 31del, shall be recombinant.

**Comment by FedeGueli** [comment]
> > Not sure if this is LB.1 +22N or just a recombinant with XEC maybe : https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_3de05_f92a70.json?label=id:node_11619450 <img alt="Screenshot 2024-08-28 alle 23 52 03" width="1161" src="https://private-user-images.githubusercontent.com/87669813/362462422-1cf3d5e7-9c5e-447f-a04c-93ea5681dd32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODM0NjIsIm5iZiI6MTcyNDg4MzE2MiwicGF0aCI6Ii84NzY2OTgxMy8zNjI0NjI0MjItMWNmM2Q1ZTctOWM1ZS00NDdmLWEwNGMtOTNlYTU2ODFkZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIyMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMWFmNzk4NDQ1MmI1NjE4NzQ5ZjQ3ODYzMjUyNDRhM2Q1ZmVjNjIwM2JiODdlNDVlM2E3YzQzMzA1ZWE3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6SVeYBcdD5_vOHD_Te8ygY-rBeld1Q25IY3V3zngDk">
> 
> It doesn't have 31del, shall be recombinant.

Thank you! right i have not thought at that!

**Comment by aviczhl2** [comment]
EPI_ISL_19332182, MB.1.1/undesignated KP.2.3+S:T572I.

**Comment by FedeGueli** [comment]
LK.2.1/JN.1.11.1.X recombinant  losing Orf1a:P>H3395Y and taking Orf1a:T2283I
3 samples
EPI_ISL_19386820
EPI_ISL_19386817
EPI_ISL_19386819

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3cafd_199bf0.json?label=id:node_7275732

**Comment by aviczhl2** [comment]
EPI_ISL_19407493, XDV.1/JN.1.4.5

**Comment by FedeGueli** [comment]
> a weird cluster reverting `BA.2.86`'s synonymous `C25207T/S:Y1215Y` also having some spike diversity already, unsure if recomb involved, just drop it here with query: `T3160A, A13121T, G21800T` ![image](https://private-user-images.githubusercontent.com/125747944/365439745-a96a535c-f5f0-46e7-8bb8-a53f3bfbc0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODgxMjYsIm5iZiI6MTcyNjA4NzgyNiwicGF0aCI6Ii8xMjU3NDc5NDQvMzY1NDM5NzQ1LWE5NmE1MzVjLWY1ZjAtNDZlNy04YmI4LWE1M2YzYmZiYzBkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQyMDUwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTg5NTllOTU3MzY3YjU2NDc4MTUyMTllNmQ1NTdjMDQwOTFhMmQxMmQ0OGZmNGNiYTU0MDAwZGVkYTQ5NWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5nrlV52uV7QeOjy5GmX9A8mbws3igdRyXnw6__ZgFXY)
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice25_genome_1a12c_d72d50.json?label=id:node_7131106


This is getting big, even if only a canadian cluster it is going on adding spike mutation , very interesting please propose it

Spike Mutations: S:D80Y, S:K440R 
Query: T3160A, A13121T, G21800T
Samples: 19
Country : 1 Canada

<img width="1167" alt="Screenshot 2024-09-11 alle 22 51 07" src="https://github.com/user-attachments/assets/db33bffc-03f8-4120-b87a-1c83f8adae3f">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5baa1_1fa030.json?label=id:node_7133705

Please @NkRMnZr propose it

**Comment by aviczhl2** [comment]
EPI_ISL_19410817, JN.1.11.1/KS.1

**Comment by FedeGueli** [comment]
Jn.1.4/LB.1.3 recombinant : EPI_ISL_19409479
Tree: 
<img width="1153" alt="Screenshot 2024-09-16 alle 14 57 48" src="https://github.com/user-attachments/assets/8dfce32f-df8a-4581-b0a9-c39aa1373815">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b9f_82a280.json?label=id:node_7113730

**Comment by FedeGueli** [comment]
Weird # 2774-XEC-alike recombinant sample having S:S31del and Orf1a:S4286C and C12616T maybe a further recombinant? :
EPI_ISL_19413561
<img width="1169" alt="Screenshot 2024-09-19 alle 10 34 47" src="https://github.com/user-attachments/assets/39ec8af6-941b-43ad-b67e-b982d36a495a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_56317_be12f0.json?label=id:node_7053962

**Comment by FedeGueli** [comment]
JN.1.7.3/KP.2 recombinant with S:S31L and S:S704L: EPI_ISL_19424789

**Comment by aviczhl2** [comment]
EPI_ISL_19430030, XDV.1.7/BA.2.86?

**Comment by aviczhl2** [comment]
EPI_ISL_19430120, XDV.1/BA.2.86?

**Comment by FedeGueli** [comment]
> EPI_ISL_19430030

with also S:A1174V

**Comment by FedeGueli** [comment]
There could be a recombinant between JN.1.7 and  KP* with S:T22N
Query: T13954C  ,C7113T, C21627A
Samples: 17
Tree:
<img width="1167" alt="Screenshot 2024-09-24 alle 01 42 45" src="https://github.com/user-attachments/assets/7ee7aab1-a4db-4ae0-8c51-03fce7719b2f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_379f6_1f7e40.json?f_userOrOld=uploaded%20sample&label=id:node_7288113

I am unusre if 22N was inherited by JN.1.7 or by some KP* + 22N

**Comment by aviczhl2** [comment]
> There could be a recombinant between JN.1.7 and KP* with S:T22N Query: T13954C ,C7113T, C21627A Samples: 17 Tree: <img alt="Screenshot 2024-09-24 alle 01 42 45" width="1167" src="https://private-user-images.githubusercontent.com/87669813/370080369-7ee7aab1-a4db-4ae0-8c51-03fce7719b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzU0MzgsIm5iZiI6MTcyNzEzNTEzOCwicGF0aCI6Ii84NzY2OTgxMy8zNzAwODAzNjktN2VlN2FhYjEtYTRkYi00YWUwLThjNTEtMDNmY2U3NzE5YjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDIzNDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMTk0ZWYxZDIxODBkYmUzMTAwZDQyMWZhMTI2MTExN2ExYzcyMjJiMDBkMWNiZmZlMGU4MjdiNGQ2YzI0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g0qSHOUE37BocbF1SXki_WsnwYh-VsTqmidui-WjTWo"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_379f6_1f7e40.json?f_userOrOld=uploaded%20sample&label=id:node_7288113
> 
> I am unusre if 22N was inherited by JN.1.7 or by some KP* + 22N

It doesn't have reversions and C7113T is very convergent, I think it shall be separate emergence as they lack G17334T.

**Comment by FedeGueli** [comment]
> I am unsure if 22N was inherited by JN.1.7 or by some KP* + 22N

mm looking at the tree ,not downsampled, it could have been also convergent evolution:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_379f6_1f7e40.json?label=id:node_7297284
<img width="1161" alt="Screenshot 2024-09-24 alle 01 46 17" src="https://github.com/user-attachments/assets/dcac03aa-8ab9-45bc-9887-7e4cd093e172">

**Comment by aviczhl2** [comment]
> > I am unsure if 22N was inherited by JN.1.7 or by some KP* + 22N
> 
> mm looking at the tree ,not downsampled, it could have been also convergent evolution: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_379f6_1f7e40.json?label=id:node_7297284 <img alt="Screenshot 2024-09-24 alle 01 46 17" width="1161" src="https://private-user-images.githubusercontent.com/87669813/370080829-dcac03aa-8ab9-45bc-9887-7e4cd093e172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDQ2NjAsIm5iZiI6MTcyNzE0NDM2MCwicGF0aCI6Ii84NzY2OTgxMy8zNzAwODA4MjktZGNhYzAzYWEtOGFiOS00NWJjLTk4ODctN2U0Y2QwOTNlMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzEyMWE5M2QzNzVjN2EzNDg2MGZjZGJlYTA4NmNkYTgzZGJhODIyYjFkY2NlNGIxNDNmOTc3Y2VhNDdkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wojs_HU7ij6OcZru3I0wGSbyyeiwo205091xFejddCs">

Yeah you can make an issue for the S:F456L sub-branch. It seems recent.

**Comment by FedeGueli** [comment]
> > > I am unsure if 22N was inherited by JN.1.7 or by some KP* + 22N
> > 
> > 
> > mm looking at the tree ,not downsampled, it could have been also convergent evolution: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_379f6_1f7e40.json?label=id:node_7297284 <img alt="Screenshot 2024-09-24 alle 01 46 17" width="1161" src="https://private-user-images.githubusercontent.com/87669813/370080829-dcac03aa-8ab9-45bc-9887-7e4cd093e172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDQ2NjAsIm5iZiI6MTcyNzE0NDM2MCwicGF0aCI6Ii84NzY2OTgxMy8zNzAwODA4MjktZGNhYzAzYWEtOGFiOS00NWJjLTk4ODctN2U0Y2QwOTNlMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzEyMWE5M2QzNzVjN2EzNDg2MGZjZGJlYTA4NmNkYTgzZGJhODIyYjFkY2NlNGIxNDNmOTc3Y2VhNDdkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wojs_HU7ij6OcZru3I0wGSbyyeiwo205091xFejddCs">
> 
> Yeah you can make an issue for the S:F456L sub-branch. It seems recent.

also in the branch below there is a recent seq from Canada with weird S:F2L mutation

**Comment by FedeGueli** [comment]
> 
> Yeah you can make an issue for the S:F456L sub-branch. It seems recent.

thx for helping now proposed in #2083

**Comment by aviczhl2** [comment]
EPI_ISL_19430317, JN.1.13/XDV.1.3
