### ISSUE TITLE
KR.1 with S:S60P and S:K304Q sampled multiple times in GBW airport surveillance (18 from 7 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1676]
Noticed this one because it is overpresented among GBW samples.

Defining 
KR.1 >> Orf1a:L204F (C875T), T14619C > T616A, Orf1a:Q455K (C1628A), C6395T, Orf1a:I2346V (A7301G), S:S60P (T21740C), S:K304Q (A22472C), C23533T
Query:   C1628A,A7301G
Samples: 12 ( Australia NSW, Japan Kagawa, Uk Wales, US California, GBW from Jamaica,Japan,Taiwan) 13 on Usher

Tree:
<img width="1180" alt="Screenshot 2024-07-03 alle 06 41 26" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/891b5365-3adb-4e8a-9c17-e94d5102b1aa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_438de_4d3950.json?label=id:node_7067980

IDs:
EPI_ISL_19144484, EPI_ISL_19189055, EPI_ISL_19191490,
EPI_ISL_19191550, EPI_ISL_19195575, EPI_ISL_19195657,
EPI_ISL_19209936, EPI_ISL_19210240, EPI_ISL_19210384,
EPI_ISL_19227548, EPI_ISL_19228852, EPI_ISL_19228874,

**Comment by FedeGueli** [comment]
16,

**Comment by FedeGueli** [comment]
18 but only 2 from July closing this although interesting and likely coming from an undersampled area

**Comment by aviczhl2** [comment]
Designated KR.1.3
