### ISSUE TITLE
JN.1.39 with S:T572I (20 seqs,4 countries, mainly found in China)

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1677]
**JN.1.39>T111C>S:T572I**
GISAID Query:`C23277T,T111C,A7842`

EPI_ISL ID:
EPI_ISL_18952122, EPI_ISL_18954443, EPI_ISL_19008247,
EPI_ISL_19078874, EPI_ISL_19080778, EPI_ISL_19080792,
EPI_ISL_19110280, EPI_ISL_19133462, EPI_ISL_19133659,
EPI_ISL_19144075, EPI_ISL_19163919, EPI_ISL_19165700-19165701,
EPI_ISL_19165704, EPI_ISL_19178466, EPI_ISL_19229923,
EPI_ISL_19229926

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a8f9_4da540.json?label=id:node_7158884
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/e8754740-975b-4fba-af88-bdb95abbfcd5)

**Comment by Memorablea** [comment]
Gansu,China +2.19now

**Comment by Memorablea** [comment]
Henna +1 20

**Comment by FedeGueli** [comment]
No recent samples closing it
