### ISSUE TITLE
JN.1.55.2 became FLiRT with S:Q677H and Orf3a:L52F in South America (57, 10 countries) with very high recent prevalence in Pernambuco, Brazil ( after July 1 = 65%)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1678]
A JN.1.55.2 (456L) branch likely emerged in Brazil and now became FLiRT  in a mini saltation. 
Yesterday one GBW sample from Colombia have been uploaded pointing at a continued circulation in an undersampled area
[ Formerly tracked as Singlet 61 on #1089 ]

Defining
JN.1.55.2 >> T13246C > C19269T, S:R346T (G22599C), S:Q677H (G23593T), Orf3a:L52F (C25546T)
Query:  C19269T,C25546T,T3565C or **NEW**: _A1461G,T3565C,C25546T_
Samples: 10
Countries: Brazil, Colombia, Spain, France, UK
IDs:EPI_ISL_19093670, EPI_ISL_19193046, EPI_ISL_19194956-19194957,
EPI_ISL_19194963, EPI_ISL_19199706, EPI_ISL_19205911,
EPI_ISL_19211192, EPI_ISL_19216643, EPI_ISL_19229734,

Tree: (updated on July 26)
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4062_3573b0.json?f_userOrOld=uploaded%20sample&label=id:node_7071428
<img width="1155" alt="Screenshot 2024-07-26 alle 11 51 50" src="https://github.com/user-attachments/assets/f1a4ea24-04d1-455d-bb9d-1b26f25b2ca2">

Addendum July 26: the Brazilian branch is defined by Orf1a:P1640S (Jn.1.18/KW* sub-lineages have 1640L) corresponding to PLPro_P77S and it is showing a lot of interesting diversity as S:T572I or S:H445R or S:L84I

**Comment by FedeGueli** [comment]
+3 of this from Spain Italy and pooled GBW

**Comment by FedeGueli** [comment]
15 now new countries Italy and Japan

Ping @corneliusroemer this should have some prevalence in South America. 15 samples with 4 by GBW

**Comment by FedeGueli** [comment]
17 +2 GBW from France

**Comment by FedeGueli** [comment]
36 with a skyhigh 80% prevalence since June 1 in Pernambuco Brazil

cc @corneliusroemer @angiehinrichs i suggest to designate this.

**Comment by Over-There-Is** [comment]
Netherlands

**Comment by FedeGueli** [comment]
39, Denmark

**Comment by FedeGueli** [comment]
Again a big batch of this from Brazil today not caught by the query , i m trying to update it

**Comment by FedeGueli** [comment]
New query : A1461G,T3565C,C25546T but it catches only 42.

**Comment by FedeGueli** [comment]
no recent samples.

**Comment by Over-There-Is** [comment]
95

**Comment by FedeGueli** [comment]
> 95

thx but weirdly died off after spreading internationally

**Comment by xz-keg** [comment]
designated NU.1
