### ISSUE TITLE
New JN.1.7.3 (346T) with S:S455A and S:T547K emerged in Central America (6 samples, 4 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1679]
Defining mutations: JN.1.7.3 > Orf1a:H3395Y (C10448T) > G21255C,  S:L>S455A (T22925G), S:T547K (C23202A), T23569C 
 Query: T22925G, T23569C,C23202A
Samples: 6 (4 countries : Honduras, el Salvador, Ohio, Alberta)
IDs: EPI_ISL_19173687, EPI_ISL_19195913, EPI_ISL_19195964,
EPI_ISL_19221491, EPI_ISL_19229599, EPI_ISL_19229676,
Tree:
<img width="1158" alt="Screenshot 2024-07-03 alle 11 28 04" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/018bff0f-e7f7-4a9e-81ab-9ae234342de9">
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice19_genome_test_1d520_452fc0.json?label=id:node_7164446

**Comment by FedeGueli** [comment]
ping @corneliusroemer @ryhisner @aviczhl2 @thomasppeacock @JosetteSchoenma @angiehinrichs @Sinickle

**Comment by aviczhl2** [comment]
Designated LK.2.1
