### ISSUE TITLE
Another LB.1* and KP.3* Recombinant (2 seqs, England)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1681]
**Query**: C4683T, C23039G,C5031T (**Edited**)
**Earliest seq**: 2024-06-09 (`EPI_ISL_19225085`, England)
**Latest seq**: 2024-06-14 (`EPI_ISL_19232469`, England)
**Sampled Countries**: UK (2: EN)

**Recombinant Profiles**:
- Placement on Phylogenetic Tree: `LB.1.4` > `C186T` > `C5031T(ORF1a:T1589I)` > `C12763T` > _`C22599G_rev(S:T346R_rev)`_, `C23039G(S:Q493E), G24872T(S:V1104L), C29541T, C29586T(ORF10:P10L)`
- Donor A: `LB.1.4`, from 5' end to breakpoint (probably `LB.1.4` > **`C186T`** > **`C5031T(ORF1a:T1589I)`**)
- Donor B: `KP.3`, from breakpoint to 3' end (probably `KP.3.1.4` > `G17338A(ORF1b:1291)` > `C5284T` > **`C29541T`**)
- Breakpoint: `nuc_22112/spike_184` to `nuc_22598/spike346`
- Private mutation(s): `C186T`, `C5031T(ORF1a:T1589I)`, `C12763T` on `LB.1.4` side; `C29541T`, `C29586T(ORF10:P10L)` on `KP.3` side
- Details of mutations:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b0f42ab8-da4c-4c3f-b034-a3285af311d9)
- Effectifly this would be `LB.1.4` with `S:Q493E` and `S:V1104L` at a cost of `S:R346T`; or `KP.3` with `S:S31Δ` and `S:Q183H`; or `XDY` minus `S:R190T`

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
England/CLIMB-CM7Y8GOW/2024
England/CLIMB-CM7YKFZG/2024
```

epi_isl accessions:
`EPI_ISL_19225085, EPI_ISL_19232469`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2299e_557ee0.json?label=id:node_7155518
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6e19b66d-7fe0-4dcf-8515-c116d197a39d)

**Comment by FedeGueli** [comment]
+1 GBW

**Comment by FedeGueli** [comment]
+1 Utah

**Comment by FedeGueli** [comment]
Scratch both the updates, the query finds two unrelated sample ( one is a recombinant spotted by @ryhisner from Utah).
The corrected query is: C4683T, C23039G,C5031T
tree with the previous query:
<img width="1162" alt="Screenshot 2024-07-17 alle 08 47 28" src="https://github.com/user-attachments/assets/8b6358d4-50c1-459f-81fb-81ba6e409b5d">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3395e_767930.json?f_userOrOld=uploaded%20sample&label=id:node_6941409

**Comment by aviczhl2** [comment]
Still the initial 2.

**Comment by FedeGueli** [comment]
Thx for the updates
