### ISSUE TITLE
KP.3.3 (JN.1.11.1.3.3) sublineage with S:R681H (65 seqs, with high local prevalence in Japan-Okinawa  and Australia- Tasmania )

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#1683]
Defining mutations:
KP.3.3>G23604A (S:R681H)

GISAID query (EDITED): C23604A, C25006T, C28291A, G28884C

Earliest seq: 2024-04-24 (Japan, EPI_ISL_19159061)
Most recent seq: 2024-06-20 (Japan, Detected from US International Airport- EPI_ISL_19229618)
Countries detected: Japan (15), New Zealand (2), US (1), China(1), Spain (1)

Usher Tree: (I suppose these branches can be combined)
![微信截图_20240703235314](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7aa39b5a-ef89-4be4-a370-43afe4fc8a7e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10bfb_4fb870.json

the pre-BA.2.86 Omicron lineages are S:P681H, while BA.2.86 changes to S:H681R. However,  H or R for site S:681 seems not very important. 

Genomes:
EPI_ISL_19142187, EPI_ISL_19159061, EPI_ISL_19164436, EPI_ISL_19183883, EPI_ISL_19186880, EPI_ISL_19201171, EPI_ISL_19203436, EPI_ISL_19203824, EPI_ISL_19213368, EPI_ISL_19213439, EPI_ISL_19218441, EPI_ISL_19219970, EPI_ISL_19219974, EPI_ISL_19220450, EPI_ISL_19221277, EPI_ISL_19223082, EPI_ISL_19227550, EPI_ISL_19229618, EPI_ISL_19231604, EPI_ISL_19232172

**Comment by FedeGueli** [comment]
@HynnSpylor  i cannot use your query could you search for a new one please?

**Comment by HynnSpylor** [comment]
Sorry that G23604A is for R681H (the original nuc is C).
GISAID query: C23604A, C25006T, C28291A, G28884C @FedeGueli

**Comment by FedeGueli** [comment]
> Sorry that G23604A is for R681H (the original nuc is C). GISAID query: C23604A, C25006T, C28291A, G28884C @FedeGueli

ah sorry! thx! i   didn't get that was so simple! thank you

**Comment by HynnSpylor** [comment]
+14 seqs (+13 in Tasmania, Australia, possibly a cluster, +1 Japan)

**Comment by HynnSpylor** [comment]
+26 seqs (Japan+25, ~15% prevalence in Okinawa  Australia+1)

**Comment by FedeGueli** [comment]
I didnt notice that the now designated branch KP..3.3.3 has A9424G>T mutated:  it was one of the **B.1.1.529** defining nuc mutation!!
