### ISSUE TITLE
JN.1.16.1+S:T572I(52 seqs=31+9+12(additional S:S31del))

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1687]
JN.1.16.1+S:T572I(C23277T)

Given the extreme convergence I cannot find a query to describe exactly JN.1.16.1+S:T572I, and they most likely emerged separately. 
There are currently 3 major branches, C12073T, C24466A, and G5617T branch. They may or may not be independent branches. The sum of the seqs is 40.

GISAID query for 12073T branch : C23277T,T22928C,G22599C,C12073T
GISAID query for 24466A branch: C23277T,T22928C,G22599C,C24466A
GISAID query for 5617T branch (**FULL QUAD + Orf9b:D16G**): C23277T,T22928C,G22599C,G5617T

No. of seqs: 21(Sweden 2 Slovenia 1 Japan 2 Ireland 2 France 1 UK 13)

First: EPI_ISL_19135064, Japan, 2024-4-30
Latest: EPI_ISL_19225376, UK, 2024-6-18

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice146_genome_test_3e518_5dbe50.json?label=id:node_5608982)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e62e873e-dba0-4cd1-93d1-014b2d4b21d9)

**Comment by aviczhl2** [comment]
23, Norway

**Comment by FedeGueli** [comment]
25, Netherlands

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/7105b73c-b296-4d5c-852f-d85ed6ab68fd)

There seems to be some new branches of the Trio gathered together.

**Comment by aviczhl2** [comment]
The sum of the 3 major sub-branches is 40 now.

**Comment by FedeGueli** [comment]
Now in the G5617T branch there is a subbranch sampled in Israel and in Arizona that features **Orf9b:D16G (A28330G)** the signature of BA.5.2
<img width="1168" alt="Screenshot 2024-07-22 alle 07 47 40" src="https://github.com/user-attachments/assets/b7c2a869-2f61-44b5-848d-e459aa361482">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice10_genome_test_204b4_df0510.json?c=userOrOld&label=id:node_7207062

**Comment by aviczhl2** [comment]
> Now in the G5617T branch there is a subbranch sampled in Israel and in Arizona that features **Orf9b:D16G (A28330G)** the signature of BA.5.2 and it is a FULL QUAD BRANCH! (all the G5617T!) <img alt="Screenshot 2024-07-22 alle 07 47 40" width="1168" src="https://private-user-images.githubusercontent.com/87669813/350849940-b7c2a869-2f61-44b5-848d-e459aa361482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mjc3NzEsIm5iZiI6MTcyMTYyNzQ3MSwicGF0aCI6Ii84NzY2OTgxMy8zNTA4NDk5NDAtYjdjMmE4NjktMmY2MS00NGI1LTg0OGQtZTQ1OWFhMzYxNDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA1NTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhN2VkMGU2OTIzMWFiOTEwZjU0MzcxYzM0M2IxN2I0MjhjM2UwMDQxZDBiNzlhNThjYTQyMjg5ODZmNjkyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MXglIh4lxw2eizHB2SpmkGd-2-Pxf_AWt8l_ljKTCAo"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice10_genome_test_204b4_df0510.json?c=userOrOld&label=id:node_7207062

It shall be a separate branch?

**Comment by aviczhl2** [comment]
Nope it can emerge directly from JN.1.16.1+S:T572I. The 31del can be branch specific.  So better designate JN.1.16.1+S:T572I as LF.x and that specific S:S31del branch as LF.x.1. @corneliusroemer

**Comment by FedeGueli** [comment]
> Nope it can emerge directly from JN.1.16.1+S:T572I. The 31del can be branch specific. So better designate JN.1.16.1+S:T572I as LF.x and that specific S:S31del branch as LF.x.1. @corneliusroemer

agree no way to establish that

**Comment by FedeGueli** [comment]
The Deflirt branch went to 7 today wioth two samples from Israel

**Comment by FedeGueli** [comment]
8 in the new deflirt branch

**Comment by FedeGueli** [comment]
> C23277T,T22928C,G22599C,G5617T

it looks like it now got only 7

**Comment by FedeGueli** [comment]
the Full Quad branch reached 11 and could be something to monitor closely

**Comment by aviczhl2** [comment]
It seems that all 3 branches stopped growing. Close down.
