### ISSUE TITLE
JN.1.42.2 plus S:S31del and Orf1a:E940G (62 , Central America - <10% of samples related to El Salvador and collected after July 1)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1692]
I spotted back weeks ago in #1502 a sublineage of JN.1.42.2 (346T) with S:S31del, it turned out to have grown a lot and more interestingly it has been sampled multiple times by GBW in American airports. This could point to some sort of prevalence in some undersampled area or more unlikely towarrd a rapid growth.

Defining mutations:
JN.1.42.2 > Orf1a:E940G (A3084G),S:S31del (del21653-55 ) 
Query:A3084G,del21653
Samples:35 
Countries:  GBW (8 El Salvador, 2 Mexico, 1 Nicaragua, Uk, HK-CHN  ),California, Spain
<Details>
<Summary>
Genomes
</Summary>
EPI_ISL_19168259, EPI_ISL_19175848, EPI_ISL_19188499,
EPI_ISL_19191567, EPI_ISL_19195014, EPI_ISL_19195593,
EPI_ISL_19195602, EPI_ISL_19195715, EPI_ISL_19195722,
EPI_ISL_19195777, EPI_ISL_19195906, EPI_ISL_19195930,
EPI_ISL_19197516, EPI_ISL_19199370, EPI_ISL_19199486,
EPI_ISL_19199496, EPI_ISL_19203034, EPI_ISL_19203037,
EPI_ISL_19205991, EPI_ISL_19210165, EPI_ISL_19210174,
EPI_ISL_19210253, EPI_ISL_19210334, EPI_ISL_19215294,
EPI_ISL_19215331, EPI_ISL_19215344, EPI_ISL_19221242,
EPI_ISL_19222839, EPI_ISL_19223237, EPI_ISL_19229608,
EPI_ISL_19229634, EPI_ISL_19229675, EPI_ISL_19229787,
EPI_ISL_19229800, EPI_ISL_19229818
</Details>
[Tree: ]( https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_52347_6b6720.json?c=userOrOld&label=id:node_7149164)
<img width="1164" alt="Screenshot 2024-07-04 alle 16 55 09" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5549b3ed-c531-4637-986d-311b24640639">
<img width="1169" alt="Screenshot 2024-07-04 alle 16 56 09" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fadbe286-7e0a-4629-b8cb-60a2261a78f5">

**Comment by FedeGueli** [comment]
57 now but its prevalence in the area where emerged is decreasing.

**Comment by aviczhl2** [comment]
Designated MS.1
