### ISSUE TITLE
KP.2+S:S31del with C9286T branch (86 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1693]
From branch 12 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
KP.2 > C9286T,C14919T, S:S31del 
Query:del21653, C9286T,C14919T
No. of seqs: 38 (Canada 4 Germany 2 USA 32 China 2 Portugal 1)
First: EPI_ISL_19050071, 2024-3-24
Latest: PP967422.1, 2024-6-13
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1fd74_6bebd0.json?f_userOrOld=uploaded%20sample)
![Screenshot (133)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/92421581/b54afd9b-56f8-4d9d-8231-c90393f90a25)

**Comment by FedeGueli** [comment]
44.  now , Taiwan

**Comment by DailyCovidCases** [comment]
Trạked in [branch12](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?aaMutations=S%3AS31-&nucMutations=C9286T%2CC14919T&nextcladePangoLineage=KP.2*&)

**Comment by FedeGueli** [comment]
53 with a GBW sample from Costa Rica

**Comment by FedeGueli** [comment]
@DailyCovidCases please propose it:

tree- updated:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_37ed3_4a5a00.json?c=gt-nuc_14919&gmax=15919&gmin=13919&label=id:node_7036765
<img width="1174" alt="Screenshot 2024-07-27 alle 09 53 16" src="https://github.com/user-attachments/assets/c71efdcf-9170-4ab5-a9c1-9b0e1eee2640">

**Comment by DailyCovidCases** [comment]
Possible designation on this branch

**Comment by FedeGueli** [comment]
> Possible designation on this branch

Please transfer this to the main page (pango) and the close this

**Comment by FedeGueli** [comment]
this is 67 not 86, how did u get 86?

**Comment by FedeGueli** [comment]
Designated KP.2.24
