### ISSUE TITLE
Recent KP.3.1.1 + S:A397V 29 sequences , 7 countries

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1695]
KP.3.1.1 is actually the lineage growing faster globally with a global share around 10% in the very few last weeks 
(6% outside Spain)
Now there is a recent small branch that got S:A397V , it is predicted to increase binding, lowering entry and improving slighty escape on a XBB.1.5 backbone by [Bloom and Dadonaite ](https://dms-vep.org/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/summary_overlaid.html)
<img width="295" alt="Screenshot 2024-07-04 alle 19 37 52" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0d6fa391-4e60-4c42-9f00-eb42de459a8a">
It was quite uncommon in the pandemic being sampled less than 400 times ( 1/4 of them in AY.4)
hence i propose it here

Defining mutations:
KP.3.1.1 > A7330T, S:A397V (C22752T) 
Query: A7330T,C22752T
Samples: 4
Countries : Spain (2), Canada, Netherlands
IDs:EPI_ISL_19201724, EPI_ISL_19229209, EPI_ISL_19230347,
EPI_ISL_19231071
Tree
<img width="1167" alt="Screenshot 2024-07-04 alle 19 32 10" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1e02270e-bbe3-402e-9438-dc4104802ec8">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1c48e_6d8440.json?c=userOrOld&label=id:node_11513231

**Comment by Huachuan1120** [comment]
The fifth sequence, from Switzerland, collected on June 18, EPI_ISL_19240398.

**Comment by FedeGueli** [comment]
thank you

**Comment by FedeGueli** [comment]
+ 1 Netherlands

**Comment by Huachuan1120** [comment]
> * 1 Netherlands

EPI_ISL_19254475, collected in Ireland on June 23, is the 7th sequence and the true fifth country.
![IMG_0161](https://github.com/sars-cov-2-variants/lineage-proposals/assets/142312996/67e63218-0ee8-4b4f-8100-24f17446ba25)

**Comment by FedeGueli** [comment]
> > * 1 Netherlands
> 
> EPI_ISL_19254475, collected in Ireland on June 23, is the 7th sequence and the true fifth country. ![IMG_0161](https://private-user-images.githubusercontent.com/142312996/346986753-67e63218-0ee8-4b4f-8100-24f17446ba25.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjMzOTIsIm5iZiI6MTcyMDU2MzA5MiwicGF0aCI6Ii8xNDIzMTI5OTYvMzQ2OTg2NzUzLTY3ZTYzMjE4LTBlZTgtNGI0Zi04MTAwLTI0ZjE3NDQ2YmEyNS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMjIxMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJkNDM2NjEwMjc3ZGQ0YWJlMTAwNzg5NmE1YTI3NjVkYjQzM2E2MzIyYWY0ZDY4NTA0Y2ZkODRiODNiNmQ1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.49ykuPCEkgDMiyXDm16kAbIJWo2tC35r8TdWJiQm72c)

thx i wrongoed the count.

**Comment by Huachuan1120** [comment]
EPI_ISL_19258758, collected in England, UK on June 24. This is the eighth related sequence and the sixth country to report it.
![IMG_0189](https://github.com/user-attachments/assets/15b035a1-632a-49c8-b2ee-9abcdf12aeeb)

**Comment by Huachuan1120** [comment]
On July 15, 8 new related sequences were submitted, including: Spain +2, Canada +6, bringing the total number of related sequences to 16.

**Comment by FedeGueli** [comment]
most recent sequences are a canadian cluster so i m closing it

**Comment by aviczhl2** [comment]
Designated MC.7
