### ISSUE TITLE
KP.3.1.4 plus S:G184A  (66, 6 countries including China and Hong Kong) with a S:S31F sublineage (38)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1697]
The S:181-187 area is a known area for moderate improvements,  here i found a small KP.3.1.4 branch with S:G184A  , i got convinced to propose it when seeing a recent GBW sequence from China.
Out of 9 Chinese GBW samples in June we have 3 XDV.1 but the DeFLirt army is advancing  with KP.2.3 , LB.1.3 and one undesignated KP.1.1.1 deflirt . This one is the only KP.3 representative from China sampled in American airports in June.

Defining mutations
KP.3.1.4 >> **N:Q241H** (A28996T) > **Orf1b: I1468V**(A17869G) > **Orf1a:P1497S** (C4754T), C6968T > **Orf1a:T3488I** (C10728T), **S:G184A** (G22113C)**>>** A6328G > **Orf1b:S1003G** (A16474G ) > **S:S31F** (C21654T)
Query: G22113C  ,C10728T
Query for S:S31F branch spotted by @josetteshoenma in #1576  first and then by @aviczhl2 :
 **C18490T, A16474G, C21654T** or A16474G, C21654T,A6328G
Samples: 63 , 37 with 31F
Countries: Scotland, Spain, US, China ( via GBW)
Tree:
 <img width="1423" alt="Screenshot 2024-07-23 alle 11 38 46" src="https://github.com/user-attachments/assets/1e6a7b30-c7d1-4f42-bfe4-5ba23405114f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1dda7_f77220.json?label=id:node_7007122

 

IDs: 
EPI_ISL_19165014, EPI_ISL_19185635, EPI_ISL_19198395,
EPI_ISL_19208350, EPI_ISL_19213878, EPI_ISL_19213882,
EPI_ISL_19215092, EPI_ISL_19229664, EPI_ISL_19253164,
EPI_ISL_19253172, EPI_ISL_19253181, EPI_ISL_19253196,
EPI_ISL_19253238, EPI_ISL_19253246, EPI_ISL_19253251,
EPI_ISL_19253367, EPI_ISL_19253500, EPI_ISL_19253656,
EPI_ISL_19253756, EPI_ISL_19253791-19253792, EPI_ISL_19253794,
EPI_ISL_19253861, EPI_ISL_19253886, EPI_ISL_19269753,
EPI_ISL_19269755-19269756, EPI_ISL_19269765, EPI_ISL_19269881,
EPI_ISL_19269885, EPI_ISL_19269991-19269992, EPI_ISL_19270001-19270005,
EPI_ISL_19270013, EPI_ISL_19270025, EPI_ISL_19270074,
EPI_ISL_19270171, EPI_ISL_19272401, EPI_ISL_19272405,
EPI_ISL_19272432, EPI_ISL_19272509, EPI_ISL_19272512-19272513,
EPI_ISL_19272536, EPI_ISL_19272557, EPI_ISL_19273675,
EPI_ISL_19273683, EPI_ISL_19275840, EPI_ISL_19276646,
EPI_ISL_19276648, EPI_ISL_19276653, EPI_ISL_19276662,
EPI_ISL_19276666-19276668, EPI_ISL_19276739, EPI_ISL_19279822,
EPI_ISL_19279959, EPI_ISL_19280144

**Comment by FedeGueli** [comment]
big upload from Scotland triplicated this from 8 to 24

**Comment by aviczhl2** [comment]
There is an S:S31F sub-branch emerging from this.

**Comment by FedeGueli** [comment]
two more samples from UK found by GBW surveillance both with S:S31F , this could be something different from a cluster

**Comment by ryhisner** [comment]
ORF1b:S1003G (NSP13_S80G) is somewhat homoplasic and is one of the few ORF1b mutations that shows up in a decent number of chronic-infection sequences. 

N:Q241H, an A->T nuc mutation is pretty interesting as well. It's a very rare mutation—fewer than 300 sequences ever prior to this lineage according to CovSpectrum. It's in the middle of the Q-rich region of N, which is adjacent to a key region for the binding of N with NSP3 (specifically, the Ubl1 domain of NSP3). 
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/33054eeb-cae3-4775-b144-392a7e18ab98">

The PDB structure only shows one half of the full dimer formation. There are 10 structures that vary, illustrating the flexibility of the various regions of N and Ubl1. Below I've picked two of those structures at random and highlighted N:Q241. It's near where N and Ubl1 bind, but it's also in a fairly flexible region and therefore it's location varies quite a bit in the different structures. 

PDB 7KPU

Ubl1 is blue and N in red

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/b2e21fdf-69d0-4321-bfca-c438ec07fc88">

All of this is from the fantastic paper, "The intrinsically disordered SARS-CoV-2 nucleoprotein in dynamic complex with its viral partner nsp3a." 
https://www.science.org/doi/10.1126/sciadv.abm4034

**Comment by FedeGueli** [comment]
One new sample of this one has been sampled by GBW coming from Hong Kong China:
Interestingly it has S:F377L and a reversion T15756T : T15756A was one of the defining of JN.1
<img width="1138" alt="Screenshot 2024-07-27 alle 10 39 45" src="https://github.com/user-attachments/assets/9e287ef0-2dcb-4631-89a7-ef854353bbb8">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_4eef1_4a85f0.json?c=gt-nuc_15756&gmax=16756&gmin=14756&label=id:node_7031967

**Comment by FedeGueli** [comment]
Only 2 out of 296 in the today batch from Scotland.

**Comment by FedeGueli** [comment]
it was a cluster closing it.
