### ISSUE TITLE
KP.1.1.1 became DeFLiRT starting with N:S183P (29 samples US, Canada,France and China)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1698]
KP.1.1.1 got S:S31del

Defining mutations: 
KP.1.1.1 >> Orf1b: S2312L(C20402T) > T451C,C14178T, S:S31del (del21653-55), G26690T, N:S183P (T28820C)
Query: C14178T ,G26690T, T3565C
Samples: 5 
Countries: California, China (via GBW)
Tree:
<img width="1166" alt="Screenshot 2024-07-05 alle 10 53 36" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/be837760-4825-46da-b70d-c20f67b1008c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5b16_7a6d70.json?c=gt-N_183&gmax=29533&gmin=28274&label=id:node_7023278

IDs: EPI_ISL_19169317, EPI_ISL_19216061, EPI_ISL_19216063,
EPI_ISL_19221169, EPI_ISL_19229655

**Comment by FedeGueli** [comment]
9 NY

**Comment by FedeGueli** [comment]
no new seqs closing it

**Comment by FedeGueli** [comment]
+1 Wyoming

**Comment by FedeGueli** [comment]
This is. now 16 with a recent sample from August coming from Utah reopening

**Comment by FedeGueli** [comment]
18

**Comment by FedeGueli** [comment]
21

**Comment by aviczhl2** [comment]
22 seqs now.
I think any notable branches of S:S31del shall be designated, because they are not shown on usher and better assign them a label to distinguish these branches from others.

**Comment by FedeGueli** [comment]
26 now @aviczhl2 

i have missed this message, i will propose it.
>Despite not fast, I think any notable branches of S:S31del shall be designated, because they are not shown on usher and better assign them a label to distinguish these branches from others

**Comment by FedeGueli** [comment]
@aviczhl2 only 5 in August are you sure i shpuld propose it ?

**Comment by DailyCovidCases** [comment]
I think this is nearly dead, so please close this issue

**Comment by DailyCovidCases** [comment]
> @aviczhl2 only 5 in August are you sure i shpuld propose it ?

I think this is nearly dead, so please close this issue

**Comment by FedeGueli** [comment]
29 now i will propose it

**Comment by FedeGueli** [comment]
> KP.1.1.1 got S:S31del
> 
> Defining mutations: KP.1.1.1 >> Orf1b: S2312L(C20402T) > T451C,C14178T, S:S31del (del21653-55), G26690T, N:S183P (T28820C) Query: C14178T ,G26690T, T3565C Samples: 5 Countries: California, China (via GBW) Tree:

Proposed in. https://github.com/cov-lineages/pango-designation/issues/2776
