### ISSUE TITLE
KP.2 Plus S:I934V and S:N30K emerged in China (32 , 7 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1699]
Defining mutations:
KP.2 > Orf1a:P1803L (C5673T = PLPro_P240L) > C14220T > S:I934V (A24362G) > T931A, G8872A, S:N30K (T21652G)
Query: T931A,C5673T,G8872A

Samples: 7 ( 6 on Gisaid) 
Countries: China 3, Hong Kong 2, Canada 1, NY 1 not on Gisaid
Tree:
<img width="1166" alt="Screenshot 2024-07-05 alle 12 06 54" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/530ad8c7-cc74-44d4-bf9f-51c821d7ebc7">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_210f3_7c4540.json?label=id:node_7010897

Note that the three samples from Mainland China misses a lot of areas in the NTD so i think they have S:N30K too
<img width="542" alt="Screenshot 2024-07-05 alle 12 07 55" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/13b0a95d-649d-438a-826d-ade32c8243b0">

**Comment by FedeGueli** [comment]
11 with 4 samples from HK and a new one from Japan

**Comment by FedeGueli** [comment]
not fast enough clsoing it

**Comment by aviczhl2** [comment]
Two more of this branch from the 8-14 Hong Kong batch.

**Comment by aviczhl2** [comment]
Also 1 more in the 8-14 Gansu batch.

**Comment by FedeGueli** [comment]
GThx reopened it.

**Comment by FedeGueli** [comment]
+1 Malaysia

**Comment by FedeGueli** [comment]
+2 , new country Australia (Vic)

**Comment by aviczhl2** [comment]
+1 Denmark +4 Shanxi

I think this one shall be proposed.

**Comment by FedeGueli** [comment]
> +1 Denmark +4 Shanxi
> 
> I think this one shall be proposed.

please propose it and the other you highlighted me some days ago. i cant propose them until monday

**Comment by FedeGueli** [comment]
now proposed here: https://github.com/cov-lineages/pango-designation/issues/2770

**Comment by FedeGueli** [comment]
Designated KP.2.25.1 via https://github.com/cov-lineages/pango-designation/commit/a3d38ca258578e6487aebe3e976302f258aeaeef#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1204

**Comment by FedeGueli** [comment]
KP.2.25.1 was doomed until a recent sample came from MA with 478E 670M, 677H and 1264L . 
We can include it in those wanderer lineages which are able to reappear after many months.
