### ISSUE TITLE
[4 seqs] Xbb.1.17.1 with S:356T, S:351H, England, Wales and USA

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#17]
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A351h%2Cs%3A356t&

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b730_449e60.json?c=userOrOld

![image](https://user-images.githubusercontent.com/94097102/236656672-dc6df561-6e70-4e18-a954-05cb85afb709.png)

Odd mutational combo on a fit looking XBB (S:215H, S:486P).  
It comes as a part of a small saltation. S:351H doesn't appear favored in BN.1, so it's unclear if it is a combo with S:356T or the close proximity is just coincidence. 
Needs larger volume before being proposed. 

Edited Gisaid query: Spike_D215H, Spike_F486P,Spike_Y351H

**Comment by Sinickle** [comment]
No new sequences as of 5/20, so in the last 16 days. Will close if it hits 30 days.

**Comment by Sinickle** [comment]
@ryhisner noticed 2 more sequences from England. Not sure why it has the S:351H coming in as a separate branch  

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/3ec9c935-cd55-4971-b426-f4de09099a61)

**Comment by FedeGueli** [comment]
Now proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/265 the bigger branch starting with S:K356T
