### ISSUE TITLE
Recent XBB.1.5.92 or (XBB.1.5+C823T??) with S:E554K spreading from Ecuador (57 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#170]
Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1dd30_717d50.json?label=id:node_6701095
![Schermata 2023-06-12 alle 15 13 53](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5ad78969-fcb8-4c83-b125-5a69da16dc2b)

Defining mutations:
XBB.1.5.92 [C823T , Orf1a:T1168I (C3768T), C10615T ]> S:E554K (G23222A)

Gisaid query: C3768T ,G23222A (18 on Gisaid , 22 on Usher)

Country:
![Schermata 2023-06-12 alle 15 18 22](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/328b38b3-5c38-4234-84bb-3b8ddb93b10a)

**Comment by FedeGueli** [comment]
Now also in Dominican Republic and Guatemala

**Comment by FedeGueli** [comment]
this is around 10% after June 15 in Ecuaador. ping @corneliusroemer

**Comment by FedeGueli** [comment]
New samples from Colombia, Us and Canada

**Comment by ciscorucinski** [comment]
@FedeGueli can you modify the title of the milestone not to include an additional space? When grabbing the milestones from the GitHub API, the title shows as ` HQ.1`

```
{
  "number": 44,
  "title": " HQ.1",
  ...
}
```

Here is another spacing issue: https://github.com/cov-lineages/pango-designation/issues/2012 (if you are able to edit milestones there)

**Comment by ciscorucinski** [comment]
Thank you. A simple rename of milestone 44 should have been sufficient, but creating a new milestone should also be okay
