### ISSUE TITLE
Other KP.3 sublineages with S:S31del

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1700]
While searching for KP.3.1.1. samples that might be missed due to missing coverage, I found some probable convergent KP.3 sublineages with S:S31del. I used the query: Spike_S31del, Spike_Q493E,  -A13121T, -G22111T

-A13121T to exclude KP.3.1.1 found by the nuc query. -G22111T to exclude XDY.

Usher, top branches are probably (partly) KP.3.1.1 with some missing coverage.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/b1b45781-2347-4014-a7e9-18f45554ca1e)
 
@FedeGueli helped me to look at the branches and found queries for them. Thank you!

KP.3.3.1 with extra S:A163V
2 samples from USA/California airport screening. 1 from Taiwan, other probably pooled
Query: C22050T, C2668T, T3565C

KP.3.2.4 singlet with extra S:S155I
Query: T22292C, A28984G, del21653
1 Canada/Ontario

KP.3.2 singlet
Western Australia
Query: T28952C, del21653 

KP.3.3 singlet
England
Query: G1836A , C18744T, del21653

**Comment by FedeGueli** [comment]
Thank you @JosetteSchoenma great spot!!
This could be a game changer if these singlets will turn out to be growing it would mean that soon we will see fireworks with even more fit lineages than KP.3.1.1. 
Especially the KP.3.3.1 + 31del is one to watch: already a fast lineage ( the only one competing with KP.3.1.1 according to Collection 42 with 3 spike mutations over vanilla KP.3 (31del,163V 547K) , emerging in an undersampled area ( or better saying a slow in uploading area) and already found via GBW airport surveillance so hinting at some sort of prevalence in the region where it emerged.
Ping @corneliusroemer i will keep you updated on all these convergent lineages  and  especially if more KP.3.3.1-31del wil pop up

**Comment by FedeGueli** [comment]
@JosetteSchoenma there are two ones:
first the one i proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1770
and then a KP.3.3 that could be found with:  G3971A,C25416T,T8263C,T3565C 
2 seqs: Canary and Spain via GBW

**Comment by FedeGueli** [comment]
> @JosetteSchoenma there are two ones: first the one i proposed in #1770 and then a KP.3.3 that could be found with: G3971A,C25416T,T8263C,T3565C 2 seqs: Canary and Spain via GBW

the  G3971A,C25416T,T8263C,T3565C jumped to 7, multiple countries proposing it

**Comment by FedeGueli** [comment]
> > @JosetteSchoenma there are two ones: first the one i proposed in #1770 and then a KP.3.3 that could be found with: G3971A,C25416T,T8263C,T3565C 2 seqs: Canary and Spain via GBW
> 
> the G3971A,C25416T,T8263C,T3565C jumped to 7, multiple countries proposing it

proposed in https://github.com/cov-lineages/pango-designation/issues/2704

**Comment by FedeGueli** [comment]
KP.3.5 +31del singlet: query: C823T,A19722G,C1471T
it could be also a recombinant with a A19722G KP.3.1.1 branch

**Comment by FedeGueli** [comment]
> > > @JosetteSchoenma there are two ones: first the one i proposed in #1770 and then a KP.3.3 that could be found with: G3971A,C25416T,T8263C,T3565C 2 seqs: Canary and Spain via GBW
> > 
> > 
> > the G3971A,C25416T,T8263C,T3565C jumped to 7, multiple countries proposing it
> 
> proposed in [cov-lineages/pango-designation#2704](https://github.com/cov-lineages/pango-designation/issues/2704)

Now designated MR.1

**Comment by FedeGueli** [comment]
Closing this, @josetteshoenma if you will update this finding new branches please reopen it.

**Comment by Over-There-Is** [comment]
S:A163V branch is 10 now
Query: C8293T, G15543T, C22050T
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_13608_c80580.json?c=country&label=id:node_7023548
![2024-08-26 (17)](https://github.com/user-attachments/assets/5a80dc11-9fe1-4648-b186-21f335ee5d45)

**Comment by FedeGueli** [comment]
> S:A163V branch is 10 now, but only 2 of them have S:S31-. Query: C8293T, G15543T, C22050T https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_13608_c80580.json?c=country&label=id:node_7023548 ![2024-08-26 (17)](https://private-user-images.githubusercontent.com/38100637/361447526-5a80dc11-9fe1-4648-b186-21f335ee5d45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTI0MTMsIm5iZiI6MTcyNDcxMjExMywicGF0aCI6Ii8zODEwMDYzNy8zNjE0NDc1MjYtNWE4MGRjMTEtOWZlMS00NjQ4LWIxODYtMjFmMzM1ZWU1ZDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDIyNDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWM1NTZjZjhmZTNjMjExNDhkMDkxOGFhOGU2ZjZmNTZlNGM4NzQ2ODllYzkyNTI1M2M1YjU4NDZlYTAwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ht8nEnvwWUroo8cbTeclIC_T4YxlCfj_ButkSxBYnfs)

please propose it. it has not s:s31del ( except two)

**Comment by FedeGueli** [comment]
There is a new branch of KP.3.3.3 with 31del:
Query C2226T, T20748C
finds 6 samples 
4 from Japan and one recent from Singapore
Kp.3.3.3 > Orf1a:T654I ( C2226T) , T20784C, S:S31del (del21653-55)
tree:
<img width="1158" alt="Screenshot 2024-08-31 alle 02 12 35" src="https://github.com/user-attachments/assets/feb46007-37ea-4381-b367-788f96671fc4">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_1022f_248f80.json?label=id:node_7080504

**Comment by FedeGueli** [comment]
> There is a new branch of KP.3.3.3 with 31del: Query C2226T, T20748C finds 6 samples 4 from Japan and one recent from Singapore Kp.3.3.3 > Orf1a:T654I ( C2226T) , T20784C, S:S31del (del21653-55) tree: <img alt="Screenshot 2024-08-31 alle 02 12 35" width="1158" src="https://private-user-images.githubusercontent.com/87669813/363367400-feb46007-37ea-4381-b367-788f96671fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjg4NDEsIm5iZiI6MTcyNjA2ODU0MSwicGF0aCI6Ii84NzY2OTgxMy8zNjMzNjc0MDAtZmViNDYwMDctMzdlYS00MzgxLWIzNjctNzg4Zjk2NjcxZmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE1MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYjM1YjhmMTI1NTg2NTc1MjU3MzIxZGJmZmZkOTU0ZDMwZGRjNmUxMDBkYzg2ZGFjZGZhMjFkZDQxOTkyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zz1UiEOxa4xW8C5foa3eH27vsQ55pNHpoZbtiotGDPc"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_1022f_248f80.json?label=id:node_7080504
> 
> cc @aviczhl2

this is now 8 from 3 countries new one Australia (Victoria) cc @JosetteSchoenma

**Comment by FedeGueli** [comment]
> There is a new branch of KP.3.3.3 with 31del: Query C2226T, T20748C finds 6 samples 4 from Japan and one recent from Singapore Kp.3.3.3 > Orf1a:T654I ( C2226T) , T20784C, S:S31del (del21653-55) tree: <img alt="Screenshot 2024-08-31 alle 02 12 35" width="1158" src="https://private-user-images.githubusercontent.com/87669813/363367400-feb46007-37ea-4381-b367-788f96671fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjA2MzQsIm5iZiI6MTcyNzI2MDMzNCwicGF0aCI6Ii84NzY2OTgxMy8zNjMzNjc0MDAtZmViNDYwMDctMzdlYS00MzgxLWIzNjctNzg4Zjk2NjcxZmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEwMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzViYzJjNmFhYjFhMDViZDg4ODczOWFiNDllOGU2ZWFlZDljZjczNjhhZGMyYmRhN2UwZWNiZGY4MmYyNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.71CUI6YsTaL-bMowsGKFwlgN-XCF5JLXGen3DQ83NNk"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_1022f_248f80.json?label=id:node_7080504
> 
> cc @aviczhl2

this is now 11 sampled in September in Australia

**Comment by FedeGueli** [comment]
> 

> his is now 11 sampled in September in Australia

12 proposing it now
