### ISSUE TITLE
KP.3.2.3 with ORF1a:A1508V (nsp3_A690V), S:T286I and S:P793T (18 seqs, Canada, Us, Scotland)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1704]
**Defining Mutations:** `KP.3.2.3` > `C4788T(ORF1a:A1508V), C12973T, C12974T, C13965T, C22419T(S:T286I), C23939A(S:P793T)`
**Query:** `C4788T, C12974T, C22419T`
**Earliest seq:** 24-05-30 (`EPI_ISL_19192816`, Alberta, Canada)
**Latest seq:** 24-06-21 (`EPI_ISL_19238555`, Alberta, Canada)
**Sampled Countries:** Canada (10: 9/AB; 1/ON)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/AB-ABPHL-118450/2024
Canada/AB-ABPHL-118602/2024
Canada/AB-ABPHL-118734/2024
Canada/AB-ABPHL-118735/2024
Canada/AB-ABPHL-119356/2024
Canada/AB-ABPHL-119561/2024
Canada/AB-ABPHL-119549/2024
Canada/AB-ABPHL-119562/2024
Canada/AB-ABPHL-119666/2024
Canada/ON-PHL-202409338/2024
```

epi_isl accessions:
`EPI_ISL_19192816, EPI_ISL_19211030, EPI_ISL_19211133-19211134, EPI_ISL_19222336, EPI_ISL_19230919, EPI_ISL_19238476, EPI_ISL_19238480-19238481, EPI_ISL_19238555`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28020_983910.json?label=id:node_7005406
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5a2775be-2100-4c0c-a38a-73aae86281fa)

**Trivia:**
- There is another `KP.2` proposed sublineage with `S:P793S` #1649, there are about 4.6k samples collected during the whole pandemic with substitution on that codon, and only about 600 samples that has changed to Threonine.
- There're also consecutive `C>T` SNPs somewhere at the end of `nsp_9` happened to be synonymous.
![CT](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d089e23d-f36a-41cb-8054-8824d9872a9e)

**Comment by FedeGueli** [comment]
Thanks for proposing S:793 seems convergent although likely not adding much growth.

**Comment by FedeGueli** [comment]
This is now 18 using a new query ( i ve added to the proposal) : C4788T, C12974T, C22419T
Tree updated as of 8/28 
<img width="1176" alt="Screenshot 2024-08-28 alle 00 27 29" src="https://github.com/user-attachments/assets/e071dde1-118b-422f-8086-6048fdc141bd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_292df_e50ce0.json?label=id:node_7034810

**Comment by FedeGueli** [comment]
Hence i reopened it, even if it mainly made by clusters from Alberta
