### ISSUE TITLE
DV.3.1 (CH.1.1.1.3.1) Sublineage with S:T22N, S:Q493L, ORF1a:S40L, ORF1a:M85I, ORF1a:A474T, ORF1a:L1438F, ORF1a:L4391F, ORF1b:L1248F (3 seq, Portugal, Jun 12)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#171]
### **Description**
**Sub-lineage of:** DV.3.1 (CH.1.1.1.3.1 = CH.1.1.1 + ORF3a:A110V, ORF1a:E377K, ORF1b:V839I)
**Earliest sequence:** 2023-5-13, Portugal — EPI_ISL_17720268
**Most recent sequence:** 2023-5-28, Portugal — EPI_ISL_17786255
**Countries circulating:** Portugal (3)
**Number of Sequences:** 3
**GISAID AA Query:** NSP1_S40L, NSP2_A294T, NSP3_L620F
**GISAID Nucleotide Query:** T383C, C384T, G1685A
**CovSpectrum Query:** Nextcladepangolineage: CH.1.1* & [5-of: C384T, C4577T, C13436T, T15096C, C15240T, C21627A, A23040T A23209T, T23698A)
**Substitutions on top of DV.3.1:**
**Spike:** T22N, Q493L
**ORF1a:** S40P→P40L, M85I, A474T, L1438F, L4391F
**ORF1b:** L1248F
**Nucleotide:** G520A, T383C, C384T, G1685A, C4577T, C7735T, C13436T, T14619C, T15096C, C15240T, G17211T, C21627A, A23040T, A23209T, T23698A
 
**Phylogenetic Order of Mutations:** G520A (ORF1a:M85I) **→** T383C (ORF1a:S40P) **→** G1685A (ORF1a:A474T) **→** C7735T, T14619C, G17211T (ORF1a:L1248F) **→** C384T (ORF1a:P40L), C4577T (ORF1a:L1438F), C13436T (ORF1a:L4391F), T15096C, C15240T, C21627A (S:T22N), A23040T (S:Q493L), A23209T, T23698A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/DV.3.1_T22N_Q493L_etc__3seq.json?c=gt-S_22&label=id:node_7222631  
<img width="1286" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0cc5942a-6aec-4348-ba89-8b3e9207f775">

**Evidence**
Even the fastest CH.1.1* lineages seem to be on the way out, so this one is not likely to stick around too long either. But it has several interesting aspects I think are worth noting. First, it has a lot of mutations—about as many (relative to the reference genome) as I've seen in any lineage not linked to molnupiravir. The long branch immediately preceding the three sequences in this lineage has nine mutations, and two of these are A→T, one T→A, and one C→A. These are all uncommon mutations, particularly A→T and T→A. Strangely, two of these are synonymous. One sequence has an additional A→T mutation, which leads to S:E554V.
 
Second, the consecutive mutations T383C + C384T, both non-synonymous, are unique to this lineage. They were acquired stepwise, with T383C causing ORF1a:S40P and T384C subsequently causing ORF1a:P40L.
 
<img width="1372" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a7487e23-9c8b-45fd-84fb-7bf2e18d6c72">
 
Finally, the two spike mutations here are in important AA residues. S:Q493 has been an important antigenic residue both in Omicron lineages and in numerous chronic-infection and cryptic-wastewater lineages. S:T22N is noteworthy because it very likely restores the N-linked glycan that was lost from S:N17 with the S:T19I mutation. The glycan motif is N-[not P]-[T or S]. Due to the S:24-26 deletion in all circulating Omicron lineages, which not only deletes nine nucleotides but also changes the AA residue after S:Q23 to S:A27S. This therefore creates an N-Q-S sequence, which forms a glycan-attachment site. Since it is very close to where the N17 glycan used to be, I'm guessing it probably has the required structural position to form a glycan, though I can't be sure. 
<img width="1502" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e9769b47-c275-4c99-adca-4ce617ab89d9">
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17720268, EPI_ISL_17786248, EPI_ISL_17786255
</details>

**Comment by FedeGueli** [comment]
I spotted yesterday a S:T22N (unrelated) i think maybe that area being back at work on the evolution side. Ryan did u look at the XAY in those residues? is there still a glycan?

**Comment by FedeGueli** [comment]
Still 3 luckily

**Comment by ryhisner** [comment]
Dodged another one! Time to close.
