### ISSUE TITLE
JN.1+S:S31del , Orf1a:G993D on a C26013T branch (24 seqs, 5 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1713]
From branch 4 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
JN.1+Orf1a:G993D,A656V+C26013T+S:S31del
Query: del21653_21655,C26013T, C2232T,G3243A
No. of seqs: 24 (China 8 Germany 1 Ireland 1 Japan 1 South Korea 13)
First: C_AA059205.1, 2024-1-15
Latest: C_AA077248.1, 2024-5-14
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3b8d6_abb510.json?f_userOrOld=uploaded%20sample)
![Screenshot (136)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/92421581/e50e94c3-039b-4609-859d-2bf1811c0775)

**Comment by FedeGueli** [comment]
It is apparently dead, i would close and reopen if some chinese regions will upload more.
