### ISSUE TITLE
JN.1.4+ S:R346T & S:S31del  & Orf7a:Q94H emerged in Guatemala (39 samples, 8% local prevalence after July 1) 

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1714]
Edited Proposal:
hence the original proposal found not one lineage but multiple unrelated DelRT lineages i have checked them : most of them are already dead but one is worth to be proposed also because it emerged (or it is circulating) in an undersampled area Guatemala.
Defining mutations:
JN.1.4>T18453C > S:S31del (del21653) S:R346T (G22599C) ,Orf7a:Q94H (A27675C), A29799G
Query: del21653,G22599C,A27675C,C774T
Samples: 11
Countries: Guatemala (also via GBW)
<img width="1168" alt="Screenshot 2024-07-08 alle 10 22 41" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/651288f2-8ad8-44b0-86a3-4851af0dbcb8">
IDs: EPI_ISL_19168189-19168191, EPI_ISL_19168194, EPI_ISL_19196279,
EPI_ISL_19196281-19196284, EPI_ISL_19221367, EPI_ISL_19229727,

###############################

Original Proposal:
From branch 9 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
JN.1.4+S:S31del
Query: C774T,T18453C, -28201, del21653_21655
No. of seqs: 60 (Brazil 19 Canada 4 Denmark 1 France 1 Guatemala 9 Ireland 1 Italy 4 Norway 1 UK 7 USA 13)
First: EPI_ISL_18710550, 2023-12-18
Latest: EPI_ISL_19224449, 2024-6-24
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3eaa7_abd320.json?f_userOrOld=uploaded%20sample)
![Screenshot (137)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/92421581/28fffd47-7b14-43e7-ab97-6c8dcdb9e549)

**Comment by FedeGueli** [comment]
There are multiple JN.1.4 + DelRT branches on this JN.1.4 branch, one with 1263L is a recombinant already proposed ,
the three with Orf8:E106Q are likely dead , on the bottom of the tree sparse singlets already dead ,

the only one worth proposing is the branch from Guatemala on the top, i will edit the proposal consequently.

**Comment by FedeGueli** [comment]
New upload yesterday i would propose it @DailyCovidCases

**Comment by DailyCovidCases** [comment]
Tracked in [branch9](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AS31-&nucMutations=C774T%2CT18453C%2CT28201T&nextcladePangoLineage=JN.1.4*&)

**Comment by FedeGueli** [comment]
You have to wait the next upload from Guatemala before closing this.

**Comment by FedeGueli** [comment]
When the Emerged in an undersampled area label is applied it means it will be kept open for a longer time due the fact we can't track properly local circulation

**Comment by FedeGueli** [comment]
This is now 39, many recent samples and 7-8% prevalence in Guatemala @aviczhl2 would you propose it has been tracked originally in your #1502 please?

**Comment by aviczhl2** [comment]
> This is now 39, many recent samples and 7-8% prevalence in Guatemala @aviczhl2 would you propose it has been tracked originally in your #1502 please?

I think the Orf8:E106Q and this Orf7a:Q94H may belong to a general branch of JN.1.4(with T18453C)+S:R346T+S:S31del. 

However they are not put together due to usher issues. 

I'll propose it in one issue and describe two branches.
