### ISSUE TITLE
LB.1.3.3 (S:K182R) with a further S:N148T sublineage (8 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1717]
<details><Summary> original LB.1.3.3 proposal
</Summary>
LB.1.3+C9163T, A22107G(S:K182R) Now designated LB.1.3.3
GISAID query: C18131T,C9163T,A22107G,-16386
No. of seqs: 7(Netherlands 2 France 3 Israel 1 Belgium 1)

First: EPI_ISL_19205794, 2024-5-28, France
Latest: EPI_ISL_19242728, 2024-6-30, Israel

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice29_genome_test_26a0_dfd530.json?label=id:node_5645163)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/141bd40e-336b-4b77-b504-c7c5e1cce65f)
</Details>

With a singlet with S:N148T Query: G2305T, C17502T,T3565C

**Comment by FedeGueli** [comment]
added a potential query for the 148T singlet: With a singlet with S:N148T Query: G2305T, G27281A,T3565C

**Comment by FedeGueli** [comment]
there should be a LB.1.3 + 182E from India. i m looking into it

**Comment by aviczhl2** [comment]
+1 Israel

**Comment by FedeGueli** [comment]
> +1 Israel

It is the second sequence with S:N148T 
Query for the N148T branch : G2305T,  C17502T,T3565C
Tree:
<img width="1171" alt="Screenshot 2024-07-23 alle 11 03 23" src="https://github.com/user-attachments/assets/e423893a-f5f0-4d83-8180-d8862264e241">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_83e5_e8a790.json?label=id:node_11553737

**Comment by aviczhl2** [comment]
13, Germany, Canada, Denmark

**Comment by aviczhl2** [comment]
21, Italy

**Comment by aviczhl2** [comment]
26, USA, UK

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
>there should be a LB.1.3 + 182E from India...

this is now 6 with four samples from US quite recent i m proposing it.

**Comment by FedeGueli** [comment]
Designated LB.1.3.3 via https://github.com/cov-lineages/pango-designation/commit/1d153da0d1cd2fd514eaf0d3586dfbe353037b15 i suggest to re open it to track the S:N148T sublineage.

**Comment by FedeGueli** [comment]
Milestone in the commit

**Comment by FedeGueli** [comment]
6 now, reopened

**Comment by DailyCovidCases** [comment]
This branch is designated, so I think you should close it

**Comment by FedeGueli** [comment]
> This branch is designated, so I think you should close it

Please check what you say when commenting before commenting, this is a undesignated branch of LB.1.3.3

**Comment by aviczhl2** [comment]
No new seqs close this.
