### ISSUE TITLE
New GE.1 (XBB.2.3.10.1) sublineage may circulate in Kenya with defining S:P521P reverted and multiple AA muts ( 12 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#172]
Here i want to propose a Lineage that is circulating in Kenya along with FY.4.
It is a XBB.2.3 descendant that got the defining S:P521S reverted back to P.

Defining mutations:
XBB.2.3.10.1 >>> C601T, Orf1a:G661S (G2246A) > Orf1a:V4369A (T13371C) > Orf7a:P99S (C27688T) > > Orf1a:P1921S (C6026T), S:N148T (A22005C) then the reversion S:P521P (T23123C ) 
(Note that then a sub-branch not proposed here has gained further  ORF1a:Q1737R,ORF3a:W131R, S:R214H, this last one acquired convergently with XCD)

Gisaid query: T13371C,C27688T,C6026T,-C23123T

Samples 5: EPI_ISL_17772263, EPI_ISL_17772282, EPI_ISL_17772285-17772287

Tree:
 
![Schermata 2023-06-12 alle 22 17 21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f8792b8f-d329-4ee3-bbc3-ebd12a89d894)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1acc7_775430.json?c=userOrOld&label=id:node_6940172

**Comment by FedeGueli** [comment]
This jumped from 5 to 12 quite unexpectedly. Something to monitor.

**Comment by FedeGueli** [comment]
S:P521P is not real but just NNN in kenyan sequence,
My bad.
The broader has been proposed now in #200 i close this one and let #200 as main proposal

**Comment by aviczhl2** [comment]
This one (not the broader one) is designated GE.1.2

**Comment by FedeGueli** [comment]
> This one (not the broader one) is designated GE.1.2

sorry i missed it should i add the milestone here?
