### ISSUE TITLE
KP.1.1.1 with S:A475V emerged in Philippines (14  from 6 countries) and further S:G35R (4)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1720]
Defining mutations: Jn.1.1.1 >  ORF1a:T4083M (C12513T) > C24031T > S:A475V (C22986T) > N:T165I (C28767T)
Note that N:T165I is homoplasic in this branch, so it could be one branch only being splitted ( or not) i have added to the defining as reminder

Query: C12513T,C28767T,A22108C
Samples:14
Countries:6 (Philippines, Japna, Taiwan, China, Spain, US)

Tree:
<img width="1169" alt="Screenshot 2024-07-10 alle 07 53 31" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fb9ea3db-1691-4546-8aca-7264bfa572b6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4f967_e1fc90.json?c=gt-nuc_28767,22986&gmax=29767&gmin=1298&label=id:node_7032363

IDs: EPI_ISL_19162458, EPI_ISL_19191324, EPI_ISL_19191565,
EPI_ISL_19191776, EPI_ISL_19219536, EPI_ISL_19223321,
EPI_ISL_19226520, EPI_ISL_19227263, EPI_ISL_19227265,
EPI_ISL_19227267, EPI_ISL_19239152, EPI_ISL_19243130,
EPI_ISL_19251365, EPI_ISL_19251374

As @aviczhl2 pointed at me in the comments this has a sublinegae with S:G35R 
  Query: C12513T,C28767T,A22108C, G21665C,  
Samples: 4 (qiuite old ones)

**Comment by aviczhl2** [comment]
Again G35R

**Comment by FedeGueli** [comment]
> Again G35R

Just minutes before Cornelius started to designate it already a couple more lineages with it this and your KP.3.1.4 185D. 
Sincerely i was noticing that from few days but i downplayed it wrongly confounding it with S:34C i proposed some times ago!

**Comment by aviczhl2** [comment]
No more seqs of this.
