### ISSUE TITLE
KP.2 with S:Q173E (C>G) lineage (23 seqs , 9 countries, 3 continents)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1722]
Defining mutations:  
KP.2 > T22795G > S:Q173E> C1609T > T14946C, S:Q173E (C22079G)
Query: C1609T,T14946C,  T3565C
Countries: 9 (Likely emerged in France)
Tree:
<img width="1170" alt="Screenshot 2024-07-10 alle 09 22 01" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b212f255-057d-4ddf-9770-010d8cae82f1">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_30e40_e2d750.json?c=userOrOld&label=id:node_7026972

IDs: EPI_ISL_19152973, EPI_ISL_19162561, EPI_ISL_19166046,
EPI_ISL_19169609, EPI_ISL_19178116, EPI_ISL_19178119,
EPI_ISL_19188417, EPI_ISL_19190935, EPI_ISL_19197500,
EPI_ISL_19201034, EPI_ISL_19204320, EPI_ISL_19213185,
EPI_ISL_19229419, EPI_ISL_19229440, EPI_ISL_19229467,
EPI_ISL_19232563, EPI_ISL_19243177, EPI_ISL_19244765,

**Comment by aviczhl2** [comment]
23 now. 3/10 in new batch of Hong Kong

**Comment by FedeGueli** [comment]
2 only from July
