### ISSUE TITLE
KP.2+Orf1b:D436N,S:T572I,K1266R misplaced by usher (25 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1723]
KP.2+A2512G,G14773A(Orf1b:D436N)+C23277T(S:T572I)+A25359G(S:K1266R)

This is misplaced by usher in a flip-flop branch @AngieHinrichs

GISAID query: A2512G,G14773A,C23277T,A25359G
No. of seqs: 14(Australia 13 China 1(from USA))

First: EPI_ISL_19122571, 2024-4-23, Australia
Latest: EPI_ISL_19251635, 2024-6-21, Australia

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice163_genome_test_2afe_dfd500.json?label=id:node_5483682)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/4d065007-4db2-4a0f-9c23-91ac4d3ff2db)

**Comment by aviczhl2** [comment]
+1 Switzerland

**Comment by aviczhl2** [comment]
25, Netherlands

**Comment by FedeGueli** [comment]
Only two in July closing it

**Comment by aviczhl2** [comment]
Designated KP.2.20.1
