### ISSUE TITLE
KP.3.1.1 + s:T22N, F59S, R346T and 5 ORB1ab mut (1)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1727]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/478e07fd-b453-48f1-9ab3-721ca86d0c38)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/168bca24-7ac2-4fd0-bf9f-6afa93bf71e1)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41c_f4f6e0.json?c=gt-S_22&gmax=25384&gmin=21563&label=id:node_7006455

Seq: 2024-06-30

Gisaid Query: C539T, C5806T, C7471T, A1674C

EPI_ISL_19254500

**Comment by aviczhl2** [comment]
Looks like a GBW pooled sample.

**Comment by FedeGueli** [comment]
The last 400 samples with T1368C (orf1a:I368T) are all GBW spanning from HV.1 to Kp.3.1.1 that is clearly a GBW artifact.
Not sure why and how.

cc @ryhisner

**Comment by aviczhl2** [comment]
No seqs of this.
