### ISSUE TITLE
KR.1 DEFLIRT emerged in Philippines (6 sequences, 4 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1728]
KR.1 got its DeFLiRT sublineage likely in Philippines
Defining mutations: KR.1 >> C6568T > C6388T, S:S31del (del21653-55)
(New) Query: C6568T,C6388T,T3565C,C897A (by @aviczhl2 )
Samples: 3 
Countries: Philippines and Taiwan (local and GBW)

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4e228_f79cf0.json?label=id:node_7082277
<img width="1148" alt="Screenshot 2024-07-11 alle 08 31 13" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/717e108e-ae31-41ef-8610-73df6215323a">

**Comment by FedeGueli** [comment]
not present in the last uploads from both Taiwan and Philippines closing it

**Comment by FedeGueli** [comment]
5 with new samples from Taiwan, US, South Korea i m going to reopen this

**Comment by aviczhl2** [comment]
+1 Uraguay

**Comment by aviczhl2** [comment]
The previous query now catches a newly-submitted 2021 seq of Uraguay. 

New query:  C6568T,C6388T,T3565C,C897A.

**Comment by FedeGueli** [comment]
closing it
