### ISSUE TITLE
XBB.1.22.2 plus S:K529N (56 seqs) likely exported from an undersampled area to France, Finland, Portugal with a sublineage with S:Y28H and S:E471Q (21 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#173]
Defining mutations:XBB.1.22.2 >> C15237T, A27507C > A12316G  > C2881T, S:K529N (G23149T)
Gisaid query: C2881T, G23149T, T28297C

![Schermata 2023-06-12 alle 22 47 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d9189681-f761-42f4-b326-1746b85ae1da)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1acc7_775430.json?c=gt-nuc_2881&label=id:node_6643485

Note that the mayor part of XBB.1.22 has also A27507C one of the defining mutation of XBB.1.9.2

Samples : 32
EPI_ISL_17202879, EPI_ISL_17300089, EPI_ISL_17383862,
EPI_ISL_17386493, EPI_ISL_17471157, EPI_ISL_17492010,
EPI_ISL_17566093, EPI_ISL_17590971, EPI_ISL_17597972-17597974,
EPI_ISL_17626296, EPI_ISL_17640558, EPI_ISL_17642518-17642519,
EPI_ISL_17661530, EPI_ISL_17666857, EPI_ISL_17667355,
EPI_ISL_17667605, EPI_ISL_17671322, EPI_ISL_17671345,
EPI_ISL_17694124, EPI_ISL_17715779, EPI_ISL_17720143,
EPI_ISL_17720160, EPI_ISL_17720167-17720171, EPI_ISL_17732128,
EPI_ISL_17737571

**EDITED**:
This seems growing since it got two additional spike mutations: S:Y28H,S.E471Q 

Defining mutations:
XBB.1.22.2 >> C15237T, A27507C > A12316G  > C2881T, S:K529N (G23149T) >17910G, S:Y28H (T21644C), S:E471Q (G22973C)

Query:  G23149T, T28297C,A17910G, G22973C

Samples: 9 (Usa / France) 
EPI_ISL_17671345, EPI_ISL_17853679, EPI_ISL_17856736,
EPI_ISL_17856751, EPI_ISL_17961067, EPI_ISL_17965272,
EPI_ISL_17976701, EPI_ISL_17976713, EPI_ISL_17979107,

**Comment by FedeGueli** [comment]
Edited and reopened

**Comment by HynnSpylor** [comment]
21 seqs for S:Y28H and S:E471Q branch now
I suggest it can be proposed in main page if further increases

**Comment by FedeGueli** [comment]
> 21 seqs for S:Y28H and S:E471Q branch now I suggest it can be proposed in main page if further increases

Proposed in https://github.com/cov-lineages/pango-designation/issues/2136

**Comment by FedeGueli** [comment]
HU.1 and HU.1.1
