### ISSUE TITLE
LB.1.2 + S:F175L (30 samples from 8 countries) with a Canadian cluster with S:S704L and S:N282T (12)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1730]
Just found a new mutation on LB.1 backbone: S:F175L
it is worth mentioning that S:F175L escapes strongly a category of broadly neutralizing ABs described here:  https://www.biorxiv.org/content/10.1101/2023.04.08.536123v1.full.pdf
<img width="857" alt="Screenshot 2024-07-17 alle 09 07 20" src="https://github.com/user-attachments/assets/4ca99568-72bf-46c1-a766-c55d99407430">

Defining mutations: **LB.1.2** >> C4021T, Orf1a:I1568F (A4967T), **S:F175L** (T22085C) >> Orf1a:T1001i (C3267T) > C16848T, **S:S704L** (C23673T) > C9836T, Orf1b:D100G (A13766G), **S:N282T** (A22407C)
Query: A4967T  ,C4021T, T22085C
Samples: 29
Countries: 8 (Germany, Canada, Colorado, Sweden, England, France, Denmark, Australia)
<Details><Summary> IDs </summary>EPI_ISL_19204342, EPI_ISL_19225662, EPI_ISL_19234055,
EPI_ISL_19244734, EPI_ISL_19251981, EPI_ISL_19256065-19256066,
EPI_ISL_19261449, EPI_ISL_19263123, EPI_ISL_19267075,
EPI_ISL_19269414, EPI_ISL_19275996, EPI_ISL_19281840,
EPI_ISL_19281928, EPI_ISL_19283022, EPI_ISL_19284049,
EPI_ISL_19284051, EPI_ISL_19284054-19284055, EPI_ISL_19284057,
EPI_ISL_19284059, EPI_ISL_19284061, EPI_ISL_19284064,
EPI_ISL_19284066-19284067, EPI_ISL_19284072, EPI_ISL_19285834,
EPI_ISL_19287167, EPI_ISL_19287449</Details>
Tree as July 29 (Edited):
<img width="1169" alt="Screenshot 2024-07-29 alle 08 30 41" src="https://github.com/user-attachments/assets/d892f80a-ec00-4253-b737-1036bb385b1e">

[https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4b776_734910.json?f_userOrOld=uploaded%20sample&label=id:node_7227297
](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4b776_734910.json?f_userOrOld=uploaded%20sample&label=id:node_7227297
)
As @aviczhl2 pointed out in the comments the Canadian cluster in New Brunswick has got two more spoike mutations:
S:S704L and S:N282T.
S:S704L is one of those spike mutations that went through the whole pandemic popping up in multiple fast lineages (JG.3, BA.2.12, FK.4.1, GK.1*) but has been in hard times since the JN.1 rise
S:N282T shifts a N GLycan from  S:N282 to S:N280 

Query for the 704L/282T branch: C9836T, A13766G
Samples: 12
Country : Canada

**Comment by FedeGueli** [comment]
+2 new country Spain

**Comment by aviczhl2** [comment]
26 now

**Comment by aviczhl2** [comment]
29 now, 13 has additional S:N282T and S704L

**Comment by FedeGueli** [comment]
> 29 now, 13 has additional S:N282T and S704L

thank you very much re-arranged the proposal to include and describe them.

**Comment by FedeGueli** [comment]
Desingated LB.1.2.3 via https://github.com/cov-lineages/pango-designation/commit/b51c5b04c0b1a1e6e2859018cbddd2195f718ca4
