### ISSUE TITLE
LB.1.8   with S:T572I (44 sequences, 6 countries including three South-Central American countries )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1731]
LB.1.8 (WITHOUT S:S31Del)  is over 50% in Venezuela in June and over 10% in Guatemala meaning it is locally a leading lineage

Defining mutations : LB.1.8 >> S:t572I (C23277T)
Query:  C23277T,A2618G,G22111T
Samples: 15
Countries: 4 Venezuela, Guatemala, Costa Rica, US (Utah, Illinois, Tennessee)
IDs:
EPI_ISL_19199621, EPI_ISL_19199624, EPI_ISL_19199629,
EPI_ISL_19199636-19199637, EPI_ISL_19212156, EPI_ISL_19226482,
EPI_ISL_19256363, EPI_ISL_19256367, EPI_ISL_19256383,
EPI_ISL_19256720, EPI_ISL_19256732, EPI_ISL_19256740-19256741,
EPI_ISL_19256743
Tree:
<img width="1179" alt="Screenshot 2024-07-11 alle 11 07 04" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/79c54a60-b3b7-477f-b7d1-47e4fdd1ee56">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2ca6a_fa0230.json?label=id:node_7196115

There is quite spike diversity in the tree with S:A222T, S:L441I , S:S31P , S:N148T , so we would expect that this will grow and evolve further

**Comment by FedeGueli** [comment]
26 now with one GBW sample from France not caught by the query.
<img width="1091" alt="Screenshot 2024-07-27 alle 11 26 45" src="https://github.com/user-attachments/assets/8b9b645f-77d9-478a-8313-397d4aa28117">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_59228_4bc150.json?c=userOrOld&label=id:node_11561033

**Comment by FedeGueli** [comment]
42

**Comment by FedeGueli** [comment]
44 Closing this for now

**Comment by Over-There-Is** [comment]
64

**Comment by FedeGueli** [comment]
> 64

thx no one recent

**Comment by Over-There-Is** [comment]
72

**Comment by FedeGueli** [comment]
> 72

dead
