### ISSUE TITLE
LB.1  branch collecting various unrelated LB.1+FullQuad branches  and  a LB.1.3.1/Jn.1.7 recombinant (1,Mexico)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1732]
see now : #1792 where the main branch originally proposed here and now identified as LB.1.2 by @aviczhl2  will be tracked.
Hence i will rearrange this archiving the proposal to track the tracks gathered together and the recombinant described here
<Details><Summary> Original Proposal </Summary> After LB.1.3.2/MH.1 have been designated there is another LB.1 FULL QUAD to track
LB.1 with S:S31del> S:T572I (C23277T) 
Query:Del21653,C23277T,G22111T, -C7869T,-C18131T,-C5770T,-C13721T,-C4784T
Samples: 5
Countries: 5 ( Israel, Malaysia, Peru, US (NY,FLorida), Canada, Ireland , Wales)
Usher:
<img width="1170" alt="Screenshot 2024-07-11 alle 11 25 55" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/79df1ad5-d7e9-4e7c-bf29-b11b56439ac6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_6289e_f99640.json?c=userOrOld&label=id:node_7193830
</Details>

1) LB.1.2.2 from #1792 

2) Recombinant branch:
On July 2 one sample placed by Usher in this lineage has been collected in Mexico but it is likely a recombinant between LB.1.3.1 and JN.1.7 featuring a FULLQUAD spike plus S:Q183H S:V445P and S:E1150D.
Query for it: T1165C, A2707G, C2841A,T3565C
 

2) Branches not tracked in #1792 :
LB.1 with S:S31del> S:T572I (C23277T) 
New Query: Del21653,C23277T,G22111T, -C7869T,-C24844T,-C18131T,-C5770T,-C13721T,-C4784T,-G19669A,-T1165C,-G25534A,-G21123T, 
Samples: 5
Countries: 3
Tree:
<img width="1164" alt="Screenshot 2024-07-29 alle 09 22 16" src="https://github.com/user-attachments/assets/7f02561e-bb29-42d1-896e-925d8a3b45e0">

[https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_455e0_742490.json?f_userOrOld=uploaded%20sample&label=id:node_7224080](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_455e0_742490.json?f_userOrOld=uploaded%20sample&label=id:node_7224080)

**Comment by FedeGueli** [comment]
New sample came from Mexico this seems to be very widespread suggesting it could have a good growth advantage

**Comment by FedeGueli** [comment]
> Add your comment here...
> 
> [ Markdown is supported ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

The mexican sample belongs to this lineage but i have now adjusted the query to exclude unrelated LB-fullquad samples: Del21653,C23277T,G22111T, -C7869T,-C18131T,-C5770T,-C13721T,-C4784T . still remarkable geographical expansion but too early to say.

**Comment by FedeGueli** [comment]
Wait wait the recent mexican samples is the same i mentioned in the recombinants issue @aviczhl2 : it is palced in this lineage but likely it doesn't belong to it being likely a recombinant with LB.1.3.1 (445P) and JN.1.7 (572I-1150D)
<img width="1144" alt="Screenshot 2024-07-15 alle 11 36 37" src="https://github.com/user-attachments/assets/9b662539-7c8e-432b-bcb1-03f2b9cfcbee">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4200c_4ecf60.json

**Comment by aviczhl2** [comment]
So it is 31del+183H+346T+456L+445P+572I+1150D?

**Comment by FedeGueli** [comment]
> So it is 31del+183H+346T+456L+445P+572I+1150D?

Exactly

**Comment by FedeGueli** [comment]
+1 Spain

**Comment by FedeGueli** [comment]
this jumped to 21 with multiple GBW samples from 3 continents including Netherlands Japan and Guatemala and more samples from Peru' and Guatemala

**Comment by aviczhl2** [comment]
This seems to be a gather of multiple LB.1+S:T572I s.  At least the top big branch must be sub-branch of LB.1.2.
