### ISSUE TITLE
KP.3.1.1 with S:G72R and Orf9b:M78T (49 , 11 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1733]
I just spotted via cov-spectrum mutations tool that there is a branch of Kp.3.1.1 with S:G72R and an Orf9b mutations.

Defining mutations:
KP.3.1.1 > C9778T, G17679T > S:G72R (G21776A), Orf9b:M78T  (T28516C)
Query:  G21776A,T28516C,C9778T
Samples: 6 
Countries: Spain, France, Germany
Tree:
<img width="1041" alt="Screenshot 2024-07-12 alle 14 05 10" src="https://github.com/user-attachments/assets/f0a763a7-bf11-4580-b720-68f8ca56a3e8">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_190df_11a650.json?c=userOrOld&label=id:node_7006166

IDs:
EPI_ISL_19215653, EPI_ISL_19216776, EPI_ISL_19221825,
EPI_ISL_19235902, EPI_ISL_19237901, EPI_ISL_19244628,

**Comment by Mydtlwn** [comment]
I hope everyone can pay attention to the minor errors found in the lineage_notes.txt file. There are at least three small mistakes. One is the misspelled alias on the branch near KS.1, another is that the mutation S:T22N on MB.1.1 has been incorrectly written as S:ST22N, for which I have already submitted a pull request but it has not been changed yet, and the last one is the alias on another branch.

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by Mydtlwn** [comment]
Specifically, it's the aliases for KS.1.1 to KS.1.3 that have the errors, and in addition, there is also a minor error in the alias for MJ.1.

**Comment by Huachuan1120** [comment]
On July 15, 14 new sequences were submitted, bringing the total to 20. (Spain +5, Canada +9)

**Comment by aviczhl2** [comment]
There is an S:R346T singlet under this branch.

**Comment by aviczhl2** [comment]
49 now.

**Comment by aviczhl2** [comment]
Designated MC.3
