### ISSUE TITLE
KP.2.3+S:Q173R (70 seqs, 14 countries) with a further S:T22N sublineage (8, Brazil, US) 2 of them with S:Q146P

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1742]
KP.2.3+S:S31del+A22080G(S:Q173R)

GISAID query: C22000A, A22080G,G25593T
Query for T22N:A22080G,C21627A,T3565C 
Query for T22N + S:Q146P: A22080G,T14136A,T3565C
No. of seqs: 20(Canada 2 UK 2 Germany 1 Iceland 1 Ireland 1 Netherlands 3 Singapore 1 Switzerland 1 USA 8(2 from Greece))

First: EPI_ISL_19183126, USA, 2024-5-1
Latest: EPI_ISL_19260069, USA, 2024-6-29

[usher updated on Sept 27]( https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_5710c_65ccc0.json?label=id:node_7292855)
<img width="1174" alt="Screenshot 2024-09-27 alle 11 09 15" src="https://github.com/user-attachments/assets/a0e4924b-3e44-48b9-8498-5bd9b655ddce">

**Comment by FedeGueli** [comment]
23 new country UAE

**Comment by aviczhl2** [comment]
34, Brazil

**Comment by aviczhl2** [comment]
37, Sweden, Japan

**Comment by FedeGueli** [comment]
It seems slow

**Comment by FedeGueli** [comment]
65 the 22N branch is interesting.

**Comment by FedeGueli** [comment]
> 65 the 22N branch is interesting.

Added a query for it , interestingly two of the recent samples with T22N have also S:H>Q146P, query added for that too.

**Comment by FedeGueli** [comment]
Please propose it

**Comment by DailyCovidCases** [comment]
@aviczhl2 Please propose it

**Comment by FedeGueli** [comment]
Designated KP.2.3.9 starting from S:Q173R
and NG.1 starting with S:T22N
via https://github.com/cov-lineages/pango-designation/commit/4744b7ae1eb832bad6b27a1b73baa66ecb928cce#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1177
