### ISSUE TITLE
KS.1+S:R190S ( 28 seqs, 5 countries including Russia )  

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1745]
**KS.1(JN.1.13.1.1)>**S:R190S**(G22132T)
Query:`T22928C,G22132T,C26894T,C25680T,-G28001T,-C19716T,-T14541C,-C344T,-C6555T,-C6310T,-A1674C,-T1978C ,` (edited on September 12)
Samples: 24
Countries: 5  [Russia, Switzerland (GBW), France, Italy(GBW) ,England]

 
<details><summary>_The 22N sub-branch should be not a sublineage of this and **it has been proposed** on **#1995** </Summary> 
Query for 190S + T22N sublineage:  A1674C,G5180A,C21627A
Samples: 4 
Countries: 2 Turkey (GBW), Delaware_ 
</Details>

EPI_ISL ID: (updated on September 12)
EPI_ISL_19081507, EPI_ISL_19167008, EPI_ISL_19231994,
EPI_ISL_19240825, EPI_ISL_19240971, EPI_ISL_19241037,
EPI_ISL_19257062, EPI_ISL_19260441, EPI_ISL_19260500,
EPI_ISL_19260542, EPI_ISL_19260547, EPI_ISL_19297244,
EPI_ISL_19297328, EPI_ISL_19297357-19297358, EPI_ISL_19297374,
EPI_ISL_19297422, EPI_ISL_19297424, EPI_ISL_19297437,
EPI_ISL_19297470, EPI_ISL_19297512, EPI_ISL_19308780,
EPI_ISL_19335191, EPI_ISL_19341978, EPI_ISL_19342013,
EPI_ISL_19347169, EPI_ISL_19362360, EPI_ISL_19381885,
EPI_ISL_19386052, EPI_ISL_19386077

UshER Tree updated on September 12:
<img width="1126" alt="Screenshot 2024-09-12 alle 23 41 42" src="https://github.com/user-attachments/assets/7d70531e-4ee7-4189-98c0-0a9a21946764">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice51_genome_test_2745d_32e510.json?label=id:node_7306833

**Comment by FedeGueli** [comment]
Query: T22928C,G22132T,C26894T,C25680T,-C6310T,-C26735T 
finds 11

**Comment by FedeGueli** [comment]
21 sequences now after Russia uploaded a big batch yesterday, surprisingly KS.1 there represents the dominant lineage close to 50% of Samples

**Comment by Memorablea** [comment]
22 seqs,all from Russia

**Comment by Memorablea** [comment]
Russia+2,USA+2,26seqs now.

**Comment by aviczhl2** [comment]
25 when excluding #1995, no new samples so close it,

**Comment by FedeGueli** [comment]
Now 30 with last samples coming from Philippines (local) and Turkey (via GBW)
interestingly it has now S:T22N sublineage of 4 seqs with also a PLPRO mutation PLPro_D76N

**Comment by FedeGueli** [comment]
New query to exclude some branches unrelated t0 this: T22928C,G22132T,C26894T,C25680T,-G28001T,-C19716T,-T14541C,-C344T,-C6555T,-C6310T,-T1978C 
Count updated down to 28

**Comment by aviczhl2** [comment]
The S:T22N sub-branch shouldn't belong to this and proposed in #1995.

**Comment by FedeGueli** [comment]
thx corrected then

**Comment by FedeGueli** [comment]
new query: T22928C,G22132T,C26894T,C25680T,-G28001T,-C19716T,-T14541C,-C344T,-C6555T,-C6310T,-A1674C,-T1978C finds 24 in 5 countries.

**Comment by Memorablea** [comment]
> new query: T22928C,G22132T,C26894T,C25680T,-G28001T,-C19716T,-T14541C,-C344T,-C6555T,-C6310T,-A1674C,-T1978C finds 24 in 5 countries.

Thanks. Russia +1,25 seqs now.

**Comment by Over-There-Is** [comment]
both branches with or without A1674C are circulating in former-USSR countries.

**Comment by Memorablea** [comment]
USA+1 26

**Comment by FedeGueli** [comment]
28 recent samples from US
