### ISSUE TITLE
Complex recombinants(and maybe recomb of recombs) in Italy (4 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1746]
There seems to be a complex branch in Italy that shares some same very unique mutations but different in other parts of the virus. There shall be something that recomb/contams with major JN.1 variants (JN.1.4/ JN.1.11.1/JN.1.16+S:Q493E)

GISAID query: G16283C, A19080T, T19081C,C28958A
No. of seqs: 4(Italy)

JN.1+A6425G, G16283C, A19080T, T19081C, T22208C(rev), G23604C(rev), A23854C
,T3431G(rev), T9344C(rev), C10078T, T14408C(rev), A15756T(rev), C16308T, C17634T, G18163A(rev), T18738A, T26060C(rev), A26709G(rev)

ORF1ab | N2054D, C5340S, E6272D, W6273R,L1056V(rev), F3027L(rev), L4715P(rev), V5967I(rev), F6158L
S | F216L(rev), R681P(rev), K764N
ORF3a | I223T(rev)
M | T63A(rev)

EPI_ISL_18831265, 18831266, with JN.1.4-defining,  2024-1
EPI_ISL_19261041, with JN.1.11.1-defining (S:F456L+S:V1104L), 2024-6
EPI_ISL_19261040, with S:F456L+S:Q493E, 2024-6

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_26393_73ed10.json?f_userOrOld=uploaded%20sample&label=id:node_6250736
![image](https://github.com/user-attachments/assets/d8e4c78b-8572-422c-a15c-7f2e759b1c4e)

**Comment by FedeGueli** [comment]
I would not exclude some sort of artifact being all by the same lab but worth looking into it. thx.

**Comment by ryhisner** [comment]
All from the Lombardy lab, so I would guess these are artifacts. Lots of bad sequences from that lab.

**Comment by aviczhl2** [comment]
No new seqs

**Comment by xz-keg** [comment]
> Uganda just uploaded a handful of LF.7 sequences collected back in october 2024 that has a pretty identical pattern of reversions maybe worth looking if it is the pipeline or instead there is something different around that went unnoticed or better saying misunderstood: https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_1f1d1e_afff80.json?c=userOrOld&label=id:node_11890408
> 
> <img alt="Image" width="1171" src="https://private-user-images.githubusercontent.com/87669813/420377663-ccac5084-b0da-4eac-905e-4ca50aaa15f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNjQ3MzcsIm5iZiI6MTc0MTM2NDQzNywicGF0aCI6Ii84NzY2OTgxMy80MjAzNzc2NjMtY2NhYzUwODQtYjBkYS00ZWFjLTkwNWUtNGNhNTBhYWExNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA3VDE2MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MjA1NDZlNjJiYTZlMzk1MzUyOTA5YjMxZDYyZDUzOGFiNmRlZjljNzgxZWFiNjAxZmJmYTA5NjFmNDM0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k-x6JCyxZgYSoRaHZn4Jdxzxcdta9BrF2QGOvWR3lWY">
> cc [@xz-keg](https://github.com/xz-keg)

The reversive sites look pretty the same but they dont share common mutations. @ryhisner @corneliusroemer any idea?'

**Comment by xz-keg** [comment]
> > Uganda just uploaded a handful of LF.7 sequences collected back in october 2024 that has a pretty identical pattern of reversions maybe worth looking if it is the pipeline or instead there is something different around that went unnoticed or better saying misunderstood: https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_1f1d1e_afff80.json?c=userOrOld&label=id:node_11890408
> > <img alt="Image" width="1171" src="https://private-user-images.githubusercontent.com/87669813/420377663-ccac5084-b0da-4eac-905e-4ca50aaa15f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNjQ3MzcsIm5iZiI6MTc0MTM2NDQzNywicGF0aCI6Ii84NzY2OTgxMy80MjAzNzc2NjMtY2NhYzUwODQtYjBkYS00ZWFjLTkwNWUtNGNhNTBhYWExNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA3VDE2MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MjA1NDZlNjJiYTZlMzk1MzUyOTA5YjMxZDYyZDUzOGFiNmRlZjljNzgxZWFiNjAxZmJmYTA5NjFmNDM0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k-x6JCyxZgYSoRaHZn4Jdxzxcdta9BrF2QGOvWR3lWY">
> > cc [[@xz-keg](https://github.com/xz-keg)](https://github.com/xz-keg)
> 
> The reversive sites look pretty the same but they dont share common mutations. [@ryhisner](https://github.com/ryhisner) [@corneliusroemer](https://github.com/corneliusroemer) any idea?'

@AnigieHinrichs, do you think usher has something to do with these reversions?

**Comment by xz-keg** [comment]
S

> Uganda just uploaded a handful of LF.7 sequences collected back in october 2024 that has a pretty identical pattern of reversions maybe worth looking if it is the pipeline or instead there is something different around that went unnoticed or better saying misunderstood: https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_1f1d1e_afff80.json?c=userOrOld&label=id:node_11890408
> 
> <img alt="Image" width="1171" src="https://private-user-images.githubusercontent.com/87669813/420377663-ccac5084-b0da-4eac-905e-4ca50aaa15f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNjQ3MzcsIm5iZiI6MTc0MTM2NDQzNywicGF0aCI6Ii84NzY2OTgxMy80MjAzNzc2NjMtY2NhYzUwODQtYjBkYS00ZWFjLTkwNWUtNGNhNTBhYWExNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA3VDE2MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MjA1NDZlNjJiYTZlMzk1MzUyOTA5YjMxZDYyZDUzOGFiNmRlZjljNzgxZWFiNjAxZmJmYTA5NjFmNDM0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k-x6JCyxZgYSoRaHZn4Jdxzxcdta9BrF2QGOvWR3lWY">
> cc [@xz-keg](https://github.com/xz-keg)

shared reversions: T9344C, G18163A, A26709G, A15756T, G23604C,T22208C

**Comment by AngieHinrichs** [comment]
> shared reversions: T9344C, G18163A, A26709G, A15756T, G23604C,T22208C

The sequences have unambiguous reference bases at those positions, not Ns or ambiguous bases.  So it's not UShER, it's the sequences.
