### ISSUE TITLE
KP.1.1.3 + Orf1b:C2341F got S:A475V and reverted S:K478T in Singapore  (5 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1747]
Very small very likely a cluster but involving two close (and key) mutations worth tracking a bit

KP.1.1.3 > S:A475V (C22986T) > C4345T, G13459A, Orf1b:C2341F (G20489T), S:T478T( A22995C REV), C29095T

Query: C4345T, G13459A,DEL21653

Samples: 3 Singapore
IDs:EPI_ISL_19228415, EPI_ISL_19268184, EPI_ISL_19268191,

Tree:
<img width="1165" alt="Screenshot 2024-07-17 alle 14 43 50" src="https://github.com/user-attachments/assets/deedcda7-9a42-445d-8e53-c237c0d3912f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_5efe8_7bac50.json?c=userOrOld&label=id:node_11545194

**Comment by FedeGueli** [comment]
Closing this for now

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/f1381ad3-4077-466e-aa87-bd381eae60cd)

The branch seems prevalent in Today's India batch. But you have to adjust the proposal not to include the K478T rev.
