### ISSUE TITLE
KP.3+S:T22N ( 54 seqs, 8 countries,mainly find in Canada)

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1748]
**KP.3(S:Q493E)>S:T22N**

GISAID Query: `C21627A, C23039G, -C12459T,-G15372T,C7113T,-C2263A,-G26217A` ( THX @FedeGueli)

EPI_ISL ID:
EPI_ISL_19168000, EPI_ISL_19188388, EPI_ISL_19199085,
EPI_ISL_19229289, EPI_ISL_19239996, EPI_ISL_19254416,
EPI_ISL_19254424, EPI_ISL_19264683, EPI_ISL_19264685-19264686,
EPI_ISL_19264689-19264693, EPI_ISL_19264701, EPI_ISL_19264705-19264706,
EPI_ISL_19264710, EPI_ISL_19264731, EPI_ISL_19264733,
EPI_ISL_19264735, EPI_ISL_19264737, EPI_ISL_19264739,
EPI_ISL_19264763-19264765, EPI_ISL_19264768, EPI_ISL_19264770,
EPI_ISL_19264781, EPI_ISL_19264783

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a6b4_7decc0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/3d05e3df-de60-47fd-9348-e2a7e9a5f6d5)

**Comment by Memorablea** [comment]
Canada +10. 41 now.

**Comment by Memorablea** [comment]
Canada+5,Germany+1.47 now.

**Comment by FedeGueli** [comment]
Still mainly a Canadian cluster but being the fastest in the charts need to be monitored closely: very likely its advantage will flatten soon , but it could be also it will be anyway fast.

**Comment by aviczhl2** [comment]
50 seqs, also in UK, France and USA

**Comment by aviczhl2** [comment]
+1 Spain

**Comment by aviczhl2** [comment]
+1 Denmark.

**Comment by aviczhl2** [comment]
+1 Ireland

**Comment by Memorablea** [comment]
> Still mainly a Canadian cluster but being the fastest in the charts need to be monitored closely: very likely its advantage will flatten soon , but it could be also it will be anyway fast.

At present, it has spread to many other countries.Please remove the label.

**Comment by Memorablea** [comment]
> +1 Ireland

Thank you very much for your work.❤️

**Comment by FedeGueli** [comment]
> > Still mainly a Canadian cluster but being the fastest in the charts need to be monitored closely: very likely its advantage will flatten soon , but it could be also it will be anyway fast.
> 
> At present, it has spread to many other countries.Please remove the label.

yeah but if you remove the cluster there are just a few sequences.  when i ll see its advantage stopping diving down i will remove it.

**Comment by FedeGueli** [comment]
Designated MC.17 via https://github.com/cov-lineages/pango-designation/commit/56fe08a73baacc670a7910651b1b962205d6ba0f

**Comment by aviczhl2** [comment]
Why MC.17? It doesn't belong to KP.3.1.1.

**Comment by FedeGueli** [comment]
MC.17 is sub judice. already pointed at Cornelius

**Comment by FedeGueli** [comment]
> MC.17 is sub judice. already pointed at Cornelius

Now redesignated KP.3.6 via https://github.com/cov-lineages/pango-designation/commit/6c26cbf1d8b9f1a460762962ce6faa32a0b314ea
