### ISSUE TITLE
New KP.3 sublineage with S:A435S and Orf8:E59* (68 sequences, 8 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1749]
As described in #1668 and #1673 S:A435S seems a mutation convergently appearing in multiple backbones recently:
<img width="1164" alt="Screenshot 2024-07-18 alle 12 10 47" src="https://github.com/user-attachments/assets/db3b032f-8b67-4de3-a828-d2aad0ffbe5d">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_4d82c_8e8bc0.json?f_userOrOld=uploaded%20sample&label=id:node_6941555

Here i will propose aKP.3 sublineage with it and featuring also an Orf8:E59* truncation.
Moreover it has a silent nuc mutation at S:N343 the  N Glycan thought to have a key role in Sars Cov 2 RBD (see: [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8488004/))

KP.3 > S:N343N (C22591T), S:A435S (G22865T), A27540G, Orf8:E59* (G28068T)
Query: C22591T,G22865T
Samples: 6 
First collected in Alberta on 2024-06-06
Countries: Canada, Wales, England

Tree:
<img width="1171" alt="Screenshot 2024-07-18 alle 12 18 45" src="https://github.com/user-attachments/assets/5399b783-c156-43e5-abed-80fea5950526">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_4d82c_8e8bb0.json?label=id:node_7038975

**Comment by aviczhl2** [comment]
14 seqs now

**Comment by FedeGueli** [comment]
> 14 seqs now

Thx it started again to be collected after a hyathus in uploads

**Comment by FedeGueli** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
20

**Comment by FedeGueli** [comment]
23, it seems slow.

**Comment by FedeGueli** [comment]
27 Netherlands

**Comment by FedeGueli** [comment]
33 Denmark, France, Norway

**Comment by FedeGueli** [comment]
39 +6 NY

**Comment by Over-There-Is** [comment]
A New York cluster got del28062_28067(Orf8:del57-58)

**Comment by FedeGueli** [comment]
> A New York cluster got del28062_28067(Orf8:del57-58)

in frame deletion?

**Comment by FedeGueli** [comment]
> > A New York cluster got del28062_28067(Orf8:del57-58)
> 
> in frame deletion?

mm looking at all samples it seems there are three way to see Orf8:E59* one Orf8:E59* the other Orf8:57-58del + Orf8:59* and then Orf8:ins57X  , maybe there is some single nuc inserted then creating the stop codon, just guessing. cc @corneliusroemer @ryhisner

**Comment by FedeGueli** [comment]
only two samples from September for a lineage that emerged in June closing it

**Comment by FedeGueli** [comment]
52 now with 10 seqs from September although a NY cluster in it better reopening it

**Comment by FedeGueli** [comment]
+1 NY it is circulating there.

**Comment by FedeGueli** [comment]
56

**Comment by FedeGueli** [comment]
67

**Comment by xz-keg** [comment]
designated KP.3.7
