### ISSUE TITLE
Cluster of KP.3.1.1 with S:N282S (5 , Canada)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1750]
Very clearly just an elderly people cluster from Ontario but still worth watching because S:N282S mutation ablates the N-Glycan at S:N282 while creating another one at S:N280 . 
Interestingly it has two close silent mutation at S:A829 and S:A831, their significance is beyond my konwledge maybe @ryhisner could look at them.

KP.3.1.1 > T3106C > S:N282S (A22407G), S:A829A (A24049C),S:A831A (T24055C)
Query: A24049C,T24055C,T3565C
Samples: 5 (Canada, Ontario)
Tree:
<img width="1137" alt="Screenshot 2024-07-18 alle 17 05 02" src="https://github.com/user-attachments/assets/77757da8-73bb-4435-bd9b-e298bca96192">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3774_928360.json?label=id:node_7010162

**Comment by ryhisner** [comment]
The synonymous A24049C + T24055C mutations here are fascinating as they may cause a dramatic change in the secondary RNA structure in this region. Both nucleotides are unpaired in the predicted secondary structure, and together, they create a perfect GCCG/CGGC reverse-complement match between nucleotides 24047-24050 and 24055-24058. Furthermore, all four nucleotide matches are G-C, which is the strongest type of pairing.

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/9ff152e9-d54f-4ddd-82ae-d2a1499c9be5">


I've seen many examples where multi-nuc mutations, usually in unpaired nucleotides, manage to eliminate multiple unpaired nucs on a stem-loop, creating a more perfect match and a tighter, more secure stem-loop. However, these mutations, if they lead to 24047-24050 and 24055-24058 pairing, would have to cause a major rearrangement in the secondary RNA structure. 

<img width="1420" alt="image" src="https://github.com/user-attachments/assets/d92fb4c5-1293-466f-a14f-b476bb418eb6">


I don't know whether such a rearrangement would actually happen or what it would look like, but the fact that these two mutations—one of which is a rare A->C transversion—occurred together seems to me to suggest they have some kind of real effect on the secondary RNA structure here.

**Comment by ryhisner** [comment]
Also interesting: this region is the 17th conserved region of SARS-CoV-2 conserved secondary RNA structure in "RNA genome conservation and secondary structure in SARS-CoV-2 and SARS-related viruses: a first look" by Rangan et al
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/4358fa56-4fa8-4445-9328-ea9f9df937eb">
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7373990/

**Comment by FedeGueli** [comment]
> Also interesting: this region is the 17th conserved region of SARS-CoV-2 conserved secondary RNA structure in "RNA genome conservation and secondary structure in SARS-CoV-2 and SARS-related viruses: a first look" by Rangan et al <img alt="image" width="1186" src="https://private-user-images.githubusercontent.com/33738461/350112760-4358fa56-4fa8-4445-9328-ea9f9df937eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzk0MzUsIm5iZiI6MTcyMTMzOTEzNSwicGF0aCI6Ii8zMzczODQ2MS8zNTAxMTI3NjAtNDM1OGZhNTYtNGZhOC00NDQ1LTkzMjgtZWE5ZjlkZjkzN2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIxNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDBlNDFmODdhMzZkZGNhMzFiZjEyNDczMjY3ZmY0MjMzOTY4MjIxNmQ0ZGM2MzhiOTQxZjFlMmY2YzEyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m46ab8eRcLA4oRmSCNQ0oNIVS07_Slt_8G0dj4SFZSc"> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7373990/

Conserved also in bat-covs?

**Comment by FedeGueli** [comment]
Thank you very much for your precious insight! @ryhisner

**Comment by ryhisner** [comment]
> Conserved also in bat-covs?

No, there's a separate list in that paper of 30 conserved secondary structures in SARS-related viruses, and it's not listed there.

<img width="952" alt="image" src="https://github.com/user-attachments/assets/0db09702-1471-42c7-a031-70796ee4e781">

**Comment by FedeGueli** [comment]
> > Conserved also in bat-covs?
> 
> No, there's a separate list in that paper of 30 conserved secondary structures in SARS-related viruses, and it's not listed there.
> 
> <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/33738461/350396216-0db09702-1471-42c7-a031-70796ee4e781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDM1OTMsIm5iZiI6MTcyMTQwMzI5MywicGF0aCI6Ii8zMzczODQ2MS8zNTAzOTYyMTYtMGRiMDk3MDItMTQ3MS00MmM3LWEwMzEtNzA3OTZlZTRlNzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE1MzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMjE0ZDIwY2U0YThjMjVjYWMxOTUyZjgxZTVkNzYxM2YxNmRjYjg1NjgwY2FjNjAxY2QzMWFlZjY2M2UyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bJnBc1o0oHhTXtRcW61oovCUkZYspBq2PFTtZthrVNY">

thank you!!!

**Comment by aviczhl2** [comment]
No more of this
