### ISSUE TITLE
LU.2 sub-branch with S:L176F (23, Ecuador,Us) with two sublineages one with S:F186S (9) and the other with S:S60P and S:K182N(14)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1751]
Credit: spotted by @HynnSpylor 
LU.2 reached a sky-high prevalence in Ecuador in  late June around 25%.
Looking at its tree i noticed a S:F176F branch that got then splitted in two interesting subbranches: one defined by S:F186S and the other , smaller, with S:S60P and S:K182N.

For now i will propose the broader branch tracking the S:F186S one with an eye on the other branch.

[Tree](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_64543_933e10.json?label=id:node_7046285):
<img width="1170" alt="Screenshot 2024-07-18 alle 17 47 07" src="https://github.com/user-attachments/assets/e23d8b90-5d65-47d2-9726-5327772638a6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_64543_933e10.json?label=id:node_7046252

Defining mutations: LU.2 > T20865C > S:L176F (C22088T) >> S:F186S (T22119C) **or** >> Orf1a:L204F (C875T), Orf1a:T1854I (C5826T), S:S60P (T21740C), S:K182N (A22108C)
Query for 176F: T20865C ,C22088T, C897A > 14 Samples
Query for 176F+186S: T20865C ,T22119C, C897A > 9 Samples
Query for 60P + 182N: T20865C ,C875T ,C5826T > 5 Samples

**Comment by HynnSpylor** [comment]
Ah I forgot to propose it! the branch with S:S680Y also should be noticed.

**Comment by FedeGueli** [comment]
+1 Denmark in the 60P Branch

**Comment by FedeGueli** [comment]
the 60P branch jumped to 10 today with two countries Scotland adn Spain

**Comment by FedeGueli** [comment]
23 now all new ones belonging to the 60P 182N sublineage

**Comment by aviczhl2** [comment]
Designated LU.2.1 and LU.2.1.1

**Comment by FedeGueli** [comment]
> Designated LU.2.1 and LU.2.1.1 via [cov-lineages/pango-designation@f7249dc](https://github.com/cov-lineages/pango-designation/commit/f7249dc8559ccbd3a4147ee9c4464993a4e1e375)

I ve noticed only now that LU.2.1.1 has also T28474C that corresponds to Orf9b:L64P cc @xz-keg
