### ISSUE TITLE
KS.1+S:R237K+S:K478T(rev) (21 seqs, USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1752]
KS.1+C22414T+G22272A(S:R237K)+T19935C,A22995C(S:K478T, rev)

GISAID query: C22414T, G22272A,T19935C
No. of seqs: 17(USA-SD,OH,IA)

First: EPI_ISL_19271540, 2024-6-9
Latest: EPI_ISL_19271575, 2024-7-10

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_6160d_9d9990.json)
![image](https://github.com/user-attachments/assets/34acac02-cfca-4231-a150-6da03e43c918)

**Comment by FedeGueli** [comment]
Sorry i ve missed this one. Both 237 to M or K and 478 reversion seems convergent right now.

**Comment by aviczhl2** [comment]
Designated KS.1.4
