### ISSUE TITLE
KP.1.1.3+S:M153I(141 seqs, >15 countries, 47 with S:C1247S)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1753]
KP.1.1.3+G22021T(S:M153I)

GISAID query: C4999T,G22021T,G24872T
GISAID query for S:C1247S branch: C4999T,G22021T,G24872T,G25302C
No. of seqs: 20(France 1 India 1 UK 1 Canada 1 Sweden 1 Spain 1  USA 14(3 from UK))

First: EPI_ISL_19033100, India, 2024-2-28
Latest: EPI_ISL_19271014, USA, 2024-7-11

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5725_9dc430.json?label=id:node_5472982)
![image](https://github.com/user-attachments/assets/e3fc5c6d-83c8-43f5-85fc-f669462c7ecd)

**Comment by aviczhl2** [comment]
25, Japan, Iceland, Germany,Austria

**Comment by aviczhl2** [comment]
35, Denmark

**Comment by FedeGueli** [comment]
there is also a LB.1.7 that got S:M153K i ha ve to check if it grew enough to be proposed.

**Comment by aviczhl2** [comment]
70, GBW from Kenya. 

21 for the S:C1247S branch.

**Comment by aviczhl2** [comment]
95, Italy, New Zealand
35 for C1247S branch

**Comment by FedeGueli** [comment]
12/137 from Spetember likely dying off

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
Slow

**Comment by xz-keg** [comment]
designated LP.6
