### ISSUE TITLE
New Usher bug causing XDP mislabeled as JN.1.4

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1754]
![image](https://github.com/user-attachments/assets/53970a9e-6c81-4df8-8a71-20272b9db9db)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice241_genome_test_357b1_9d43a0.json

@AngieHinrichs

**Comment by AngieHinrichs** [comment]
It looks like this has been resolved just by matOptimize moving things around -- as of the 2024-07-29 tree, XDP was placed in BA.2.86.1.
