### ISSUE TITLE
KP.1.1.1+S:T572I,Orf7a:R78L (64 seqs,2 countries, 59 with S:I100L)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1755]
KP.1.1.1+C27143T+C23277T, G27626T(S:T572I, Orf7a:R78L)

GISAID query: C27143T, C23277T, G27626T
GISAID query for S:I100L branch: C23277T, G27626T, A21860T

First: EPI_ISL_19122349, 2024-4-12, USA
Latest: EPI_ISL_19269319, 2024-7-2, USA

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice85_genome_test_357b1_9d4360.json?label=id:node_6256967)
![image](https://github.com/user-attachments/assets/014cd1dd-3207-4184-95d3-763a665bce08)

**Comment by FedeGueli** [comment]
Yeah this is branch 149 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089 
>KP.1.1.1 > C27143T > T9769C,S:T572I (C23277T), G27626T> Spike_I100L (A21860T)
Query:T9769C, G27626T ,C27143T
Samples: 15 (Colorado)

To me still a cluster.

**Comment by aviczhl2** [comment]
39, Denmark

**Comment by FedeGueli** [comment]
Still very much a Colorado thing

**Comment by FedeGueli** [comment]
no recent samples closing it
