### ISSUE TITLE
 JN.1.16.1  (Usher places it under LR.1) plus S:T22N, S31P, K182R, R190S, K444R + ORF9b:I5T + ORF1a:S2535L  (7 seq, 6 countries; Aug 13)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1758]
**Description**
**Sub-lineage of:** JN.1.16.1
**Earliest sequence:** 2024-6-24, Senegal
**Most recent sequence:** 2024-6-25, Senegal
**Continents circulating:** Africa (2)
**Countries circulating:** Senegal (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** C5239T, C7869T, C8818T, G12892A, T16600C
**CovSpectrum Query:** Nextcladepangolineage:JN.1* & [4-of: C5239T, C7869T, C8818T, G12892A, T16600C]
**Substitutions on top of JN.1.16.1:**
**Spike:** T22N, S31P, K182R, R190S, K444R
**ORF1a:** S2535L
**ORF9b:** I5T
**Nucleotide:** C5239T, C7869T, C8818T, G12892A, T16600C, C21627A, T21653C, A22107G, G22132T, C22792T, A22893G, C22993T, T28297C

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31267_ab1a70.json?label=id:node_11550501

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/07dfc597-8d15-4348-8cdc-2e74ca1544ff">

**Evidence**
Just doing a crappy, short proposal for now since it's 2 sequences. If it grows, I'll do a proper one. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19273031, EPI_ISL_19273041
</details>

**Comment by FedeGueli** [comment]
Both the samples are imported from elsewhere, but their collection bodes well with the targeted sequencing, done by Senegal, of returning pilgrims from Mecca.
So this lineage likely emerged in another country, noticeably it has similarities both with MA.1 and MB.1.1

**Comment by ryhisner** [comment]
One of these showed up in Canada, collection date July 23. EPI_ISL_19293986

**Comment by ryhisner** [comment]
Sequence from France today with an additional S:D228H. 
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/0d46b183-5a32-4de2-9e7b-ebd1255b6360">

**Comment by FedeGueli** [comment]
New sample of this from GBW .

But more interestingly now it has been placed under LR.1 (JN.1.58.1)  as sublineage:
<img width="1153" alt="Screenshot 2024-08-13 alle 17 03 50" src="https://github.com/user-attachments/assets/bd4d0ef7-8a8c-4ad6-80bc-96f2b097d491">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice24_genome_test_468d1_b6c340.json?label=id:node_6968744

Another annotation: it is very likely that all of them have Orf1b:K2557R being only the samples from Senegal missing it.

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
@ryhisner please propose it i bet @corneliusroemer will designate it soon.

**Comment by corneliusroemer** [comment]
oh yeah this one is a no brainer, thanks!

**Comment by FedeGueli** [comment]
Designated LF.7 via https://github.com/cov-lineages/pango-designation/commit/43d7733254e29c91714acb4ed0ea2003b2873551
