### ISSUE TITLE
KP.2.3 (∆S31) + S:K440R, H445P (18 samples, 8 countries including India, UAE and Honduras)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1760]
**Description**
**Sub-lineage of:** KP.2.3
**Earliest sequence:** 2024-6-20 – India (travel to USA, Washington state Airport), EPI_ISL_19229712
**Most recent sequence:** 2024-7-7 – India (travel to USA, New Jersey Airport), EPI_ISL_19273749
**Continents circulating:** Asia (2), North America (1)
**Countries circulating:** India (2—both travel to USA), Canada (1)
**Number of Sequences:** 3
**GISAID Nucleotide Query:** 22881G, 22896C, 25021C, T3565C (via @FedeGueli)
**CovSpectrum Query:** Nextcladepangolineage:KP.2* & [4-of: C16768A, C17733T, A22881G, A22896C, T25021C]
**Substitutions on top of KP.2.3:**
**Spike:** K440R, H445P
**Nucleotide:** C16768A, C17733T, A22881G, A22896C, T25021C, C28714T

**Phylogenetic Order of Mutations:** C28714T  **→** C16768A **→** C17733T, A22881G, A22896C, T25021C (S:K440R, S:H445P)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.2.3_K440R_H445P_tree.json?c=gt-S_440&gmax=25384&gmin=21563&label=id:node_7030445

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/1fd1d52c-6891-460c-9bf7-2d55b8b92b57">

**Evidence**
Two interesting RBD mutations, one of which (S:K440R) has never been in a circulating lineage but which is highly convergent in chronic-infection sequences. 

Most intriguing is that two of these three sequences are from travelers to the USA from India. It's possible that this lineage is fairly widespread somewhere in India, where sequencing is very scarce.

The most recent sequence, first noticed by @FedeGueli, has three additional non-synonymous nucleotide mutations (A8633G, C23757T, G25507A) leading to AA substitutions ORF1a:I2790V, S:T732I, and ORF3a:A39T.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19229712, EPI_ISL_19256040, EPI_ISL_19273749
</details>

**Comment by FedeGueli** [comment]
I ve checked the apparent prevalence is 2/17 GBW samples, collected after June 20, from travelers arriving  into US from India , 2 /19 considering also two locally sequenced samples from Assam India.

**Comment by FedeGueli** [comment]
fifth sample this time Qatar via GBW

**Comment by ryhisner** [comment]
Another travel sequence from India today, collection July 28. You have to wonder how widespread this is in India. Could be just a small pocket with a lot of wealthy travelers or it could be widespread in a region of 100 million people.

**Comment by FedeGueli** [comment]
11 now more gbw samples from UAE and local samples in Texas.

**Comment by aviczhl2** [comment]
14, Also in Netherlands

**Comment by FedeGueli** [comment]
+1 India (GBW)

**Comment by aviczhl2** [comment]
17, Denmark

**Comment by FedeGueli** [comment]
>Denmark 

first from September

**Comment by FedeGueli** [comment]
18 but no recent one closing this
