### ISSUE TITLE
JN.1.4.5+S:S31del with Orf1b:P2404S (10seqs, 5 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1763]
From branch 11 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
JN.1.4.5+S:R346T+Orf1b:P2404S,S:S31del
NEW Query: C28201T, del21653_21655,G22599C,C20677T (EDITED)
No. of seqs: 10 
Countries: 5 Including Russia
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3582f_d275e0.json?f_userOrOld=uploaded%20sample)
[branch11](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?aaMutations=S%3AS31-&nucMutations=C28201T%2CG22599C&)
![Screenshot (141)](https://github.com/user-attachments/assets/cd202c17-3c90-4825-b30b-a3b9775ae345)

**Comment by FedeGueli** [comment]
This is not monophyletic, closing it:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_10687_dfdb60.json?f_userOrOld=uploaded%20sample&label=id:node_6941766
<img width="1172" alt="Screenshot 2024-07-22 alle 08 41 35" src="https://github.com/user-attachments/assets/c39ed4db-6709-4669-a845-70dcdcc943ff">

**Comment by FedeGueli** [comment]
@DailyCovidCases i ve edited the proposal to get one lineage that should be tracked after being sampled in Russia.
the correct query is: 
>**NEW Query: C28201T, del21653_21655,G22599C,C20677T (EDITED)**

**Comment by aviczhl2** [comment]
This seems to be re-arranged by usher as a sub-branch of C11020T branch.

**Comment by aviczhl2** [comment]
I re-arranged the original branch 11 of #1502, this one can be closed.

**Comment by FedeGueli** [comment]
Thx
