### ISSUE TITLE
LB.1+S:Q677H(151 seqs, >10 countries)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1765]
LB.1+G23593T(S:Q677H)

GISAID query: G23593T, del21653, G22111T,-18131,-4784,-3724,-19669,-4683,-15960,-19560
No. of seqs: 6(Spain 1 USA 1 UK 1 Canada 3)

First: EPI_ISL_19230847, Canada, 2024-6-18
Latest: EPI_ISL_19274476, Spain, 2024-7-15

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice193_genome_test_1a04a_db2390.json?label=id:node_5662661)
![image](https://github.com/user-attachments/assets/f885ffe9-383e-4785-837e-79c8b488dc2d)

**Comment by aviczhl2** [comment]
14, Cuba, France

**Comment by aviczhl2** [comment]
57, Denmark

**Comment by aviczhl2** [comment]
66, Netherlands

**Comment by Over-There-Is** [comment]
70, Puerto Rico

**Comment by aviczhl2** [comment]
73, Sweden

**Comment by aviczhl2** [comment]
121, Mexico

**Comment by FedeGueli** [comment]
It seems going better now than before

**Comment by FedeGueli** [comment]
Only 11/134 from September likely dying off

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
Slow @DailyCovidCases pls look at labels

**Comment by FedeGueli** [comment]
5 seqs in October (Spain and a Canadian cluster)

**Comment by FedeGueli** [comment]
159, with an october sample from Australia. if the query is still correct please propose it

**Comment by xz-keg** [comment]
add some more -s and the toll becomes 148.

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch now?

**Comment by DailyCovidCases** [comment]
@xz-keg Please propose this branch on the main page

**Comment by FedeGueli** [comment]
> @xz-keg Please propose this branch on the main page

only two samples from october with the new query so lets wait

**Comment by FedeGueli** [comment]
dead likely

**Comment by Over-There-Is** [comment]
167

**Comment by FedeGueli** [comment]
no recent seqs though
