### ISSUE TITLE
LB.1.3 with S:P217H (54, US, Canada, Puertorico)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1769]
A new LB.1.3 sublineage recently emerged carrying S:P217H 

LB.1.3> ORF1a:E381D(G1408T), S:P217H (C22212A)
Query: C18131T,C22212A,del21653
Samples: 8
Countries: 2
IDs:EPI_ISL_19153984, EPI_ISL_19154018, EPI_ISL_19197411,
EPI_ISL_19245369, EPI_ISL_19250955, EPI_ISL_19268668,
EPI_ISL_19269273, EPI_ISL_19279685

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_abdd_fdb2c0.json?c=gt-S_217&label=id:node_7211216
<img width="1156" alt="Screenshot 2024-07-24 alle 00 34 29" src="https://github.com/user-attachments/assets/cee46eac-e60c-439f-8acf-4707abff79c1">
<img width="1180" alt="Screenshot 2024-07-24 alle 00 35 10" src="https://github.com/user-attachments/assets/07f0d3a7-2c70-403b-91ee-30f67272f12f">

**Comment by FedeGueli** [comment]
16 now

**Comment by aviczhl2** [comment]
28 now

**Comment by FedeGueli** [comment]
45 but it has slowed down a lot

**Comment by aviczhl2** [comment]
51 now,

**Comment by FedeGueli** [comment]
54 no recent samples unable to compete
