### ISSUE TITLE
KP.1.1.5+Orf1a:A2785V,A4357V+S:S680Y(40 seqs, 6 countries- 5% in Mexico after July 1)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1777]
KP.1.1.5+C8619T(Orf1a:A2785V)+T18547C,C13335T(Orf1a:A4357V)+C23601A(S:S680Y)

GISAID query: T18547C,C13335T,C23601A
No. of seqs: 9(USA 4(2 from Qatar), Mexico 2 Canada 3)

First: EPI_ISL_19259343, 2024-6-21, Mexico
Latest: EPI_ISL_19281267, 2024-7-16, Canada

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice162_genome_test_971_1b2f20.json?label=id:node_5481038)
![image](https://github.com/user-attachments/assets/b2f58288-8a7d-4e6b-99ad-bad94a1a351b)

**Comment by aviczhl2** [comment]
35, Austria

**Comment by FedeGueli** [comment]
Please propose it it has a good prevalence in Mexico

**Comment by FedeGueli** [comment]
designated MU.2.1

via https://github.com/cov-lineages/pango-designation/commit/d39304704862930caed86d10b5785fa1131b2b17
