### ISSUE TITLE
KP.3.1.4+Orf1b:S2198I, S:S31P, Orf7a:P68S, N:T366I(45 seqs, 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1780]
KP.3.1.4+G20060T, T21653C, C27595T, C29370T(Orf1b:S2198I, S:S31P, Orf7a:P68S, N:T366I)

GISAID query: G20060T, T21653C, C27595T, C29370T
No. of seqs: 17(Australia 9 Canada 2 New Zealand 1 UK 1 USA 1 Singapore 3)

First: EPI_ISL_19161717, 2024-5-8, Australia
Latest: EPI_ISL_19284076, 2024-7-15, Canada

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice139_genome_test_971_1b2eb0.json?label=id:node_6264070)
![image](https://github.com/user-attachments/assets/441a3049-4b68-453e-a9d6-ff9942b62277)

**Comment by FedeGueli** [comment]
Another Aussie sample > 19

**Comment by aviczhl2** [comment]
25, Japan

**Comment by aviczhl2** [comment]
35, Georgia

**Comment by FedeGueli** [comment]
It is circulating in Canada only and still very slow moving

**Comment by FedeGueli** [comment]
Most of the recent samples are from two canadian clusters closing it for now
