### ISSUE TITLE
BA.2.86 with S: N487D then acquired  S:R346T and S:A348P on a C28115T branch (13 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1782]
From branch 107 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1089
BA.2.86 > T10819C,C28720T > Orf1b:Y1344H (T17497C) > C21646T, S:N487D (A23021G) ,A23089G, C28115T > S:A348P (G22604C), S:R346T (G22599C)
Query for 487D : T17497C,T10819C,C28115T
Samples: 13 : SA Mozambique
Query for 346T, 348P: A23089G, C28115T ,G22604C,G22599C
Samples : 3 South Africa
[usher1](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1661a_26daa0.json?f_userOrOld=uploaded%20sample)
[usher2](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1a406_26ef50.json?f_userOrOld=uploaded%20sample)
![Screenshot (145)](https://github.com/user-attachments/assets/3ed46bea-273c-4788-9642-0bc8a6e02dd5)

**Comment by FedeGueli** [comment]
13 (10+3) and headline modified.

**Comment by aviczhl2** [comment]
Designated BA.2.86.7, MP.1 and MP.1.1

**Comment by FedeGueli** [comment]
> Designated BA.2.86.7, MP.1 and MP.1.1  

BA.2.86.7 has been designated previously not all together with this @aviczhl2 i ve removed the milestone.

**Comment by aviczhl2** [comment]
> > Designated BA.2.86.7, MP.1 and MP.1.1
> 
> BA.2.86.7 has been designated previously not all together with this @aviczhl2 i ve removed the milestone.

I cannot find the proposal for BA.2.86.7. Is it designated after this proposal, or just Daily not updating during his copy/paste phase?

**Comment by FedeGueli** [comment]
> > > Designated BA.2.86.7, MP.1 and MP.1.1
> > 
> > 
> > BA.2.86.7 has been designated previously not all together with this @aviczhl2 i ve removed the milestone.
> 
> I cannot find the proposal for BA.2.86.7. Is it designated after this proposal, or just Daily not updating during his copy/paste phase?

i think it was designated on its own by Cornelius directly one or two. months ago see https://github.com/cov-lineages/pango-designation/commit/b5893d575b4b7ae5c61fc0100344466129a93902

**Comment by aviczhl2** [comment]
> i think it was designated on its own by Cornelius directly one or two. months ago see [cov-lineages/pango-designation@b5893d5](https://github.com/cov-lineages/pango-designation/commit/b5893d575b4b7ae5c61fc0100344466129a93902)

@DailyCovidCases , if you want to make separate issues from multiple lineage issues, please

1: Ask for permission

2: Update descriptions. including 

2-1: Adjust the query to ensure monophyletic  
2-2: Update counts according to new query 
2-3: Adjust description according to updated designations (for example, when proposing this one, you shall describe it as sub-lineage of BA.2.86.7 instead of BA.2.86 in the original issue)
2-4: 2-1~2-3 shall be updated repeatedly to keep track with the new situation (I suggest every week) 

That will be helpful, thanks.
