### ISSUE TITLE
JN.1.3+S:F456L with Orf8:Q18* (C27945T branch) (94 seqs,16 countries)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1783]
From branch 25 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
JN.1.3+S:F456L
Query: T3565C,T22928C,C27945T,-C4777T
No. of seqs: 94
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12938_3066d0.json?f_userOrOld=uploaded%20sample)
![Screenshot (146)](https://github.com/user-attachments/assets/2023de52-061a-4aaa-80a8-99a1f7ecf899)

**Comment by FedeGueli** [comment]
Again this is not monophyletic, the real JN.1.3 is just this one and dead for sure please close this.
<img width="1157" alt="Screenshot 2024-07-26 alle 07 45 28" src="https://github.com/user-attachments/assets/8877c7df-34b6-4dc8-bb56-0b25dc89be1c">
