### ISSUE TITLE
KP.3.1.1+Orf1a:T2274I+S:R346T, Orf6:I36V( 6 seqs, Spain)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1785]
This seems to be another DeFLiRT+DeFLuQE lineage.  

KP.3.1.1+C7086T(Orf1a:T2274I)+G22599C, A27307G, C27513T(S:R346T, Orf6:I36V)

GISAID query: C23039G, G22599C, C7086T
No. of seqs: 5(Spain)

First: EPI_ISL_19255968, 2024-6-24
Latest: EPI_ISL_19270893, 2024-7-5

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_cf8d_3c8780.json?label=id:node_5479103)
![image](https://github.com/user-attachments/assets/2368912c-8ff5-47e7-85d6-056cd2829e48)

**Comment by FedeGueli** [comment]
Another after XDY +346T right?

**Comment by aviczhl2** [comment]
> Another after XDY +346T right?

Yeah, and there are also lots of singlets.

**Comment by FedeGueli** [comment]
the new sample is from different region of Spain , Murcia

**Comment by FedeGueli** [comment]
it seems dead.

**Comment by aviczhl2** [comment]
Dead
