### ISSUE TITLE
KP.3.1.4 + S:T29N, S:N477S (R), S:T791P, ORF9b:Q18R, ORF1a:V1143F; ORF1b:T794I, ORF1b:P1675S, ORF1b:T2165M (14 seq, USA, Canada; Oct 3)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1786]
### **Description**
**Sub-lineage of:** KP.3.1.4
**Earliest sequence:** 2024-6-26, USA, North Carolina — EPI_ISL_19216826
**Most recent sequence:** 2024-7-14, Canada, New Brunswick — EPI_ISL_19284093
**Continents circulating:** North America (3)
**Countries circulating:** USA (2), Canada (1)
**Number of Sequences:** 3 
**GISAID Nucleotide Query:** G19800A, C19961T, A23933C 
**CovSpectrum Query:** Nextcladepangolineage:KP.3.1* & [5-of: G3692T, C15848T, G19800A, C19961T, C21648A, A22992G, A23933C, T27807C, A28336G]
**Substitutions on top of KP.3.1:**
**Spike:** T29N, S477N (Reversion), T791P
**ORF9b:** Q18R
**ORF1a:** V1143F
**ORF1b:** T794I, T2165M 

**Nucleotide:** G3692T, C15848T, G19800A, C19961T, C21648A, A22992G (R), A23933C, T27807C (R), A28336G

**USHER Tree**
Note: This is definitely a misplacement due to the dropout in the North Carolina sequence, which registers as reversions W452L, S455L, and L456F. It ought to be somewhere in the KP.3.1.4 branch instead. 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.1_T29N_N477S_T791P.json?c=gt-S_791&gmax=25384&gmin=21563&label=id:node_7030493

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/32208abb-2fd9-4db1-81bd-63ad25892820">

**Evidence**
There are several remarkable mutations in this mini-saltation lineage. 

• S:T29N – This creates a glycan at N29. Since glycans at N22 (via T22N) and N30 (via ∆S30) have proven highly advantageous, it seems reasonable to suppose that N29 would have a similar effect.

• S:N477S (Reversion) — This is an extremely rare reversion. I can't recall ever seeing it. S477N was a convergent spike mutation even before Omicron.

• S:T791P – S:T791 mutations seem to show up disproportionately in highly mutated sequences. One study found that T791 was the only phosphorylated residue in spike, so there is likely a real functional effect of some sort here.

• T27807C (Reversion) – The number of mutations in this region of ORF7b, many of them synonymous, makes me think they play some significant role in the secondary RNA structure. Once I checked for reverse complement matches to the Octanucleotide Motif, a 3' UTR sequence that is absolutely conserved in all coronaviruses, and this region of ORF7b was one of the top matches. Could be a coincidence though. Hard to say.  

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19216826, EPI_ISL_19284093, EPI_ISL_19290323
</details>

**Comment by FedeGueli** [comment]
>S:N477S (Reversion) — This is an extremely rare reversion. I can't recall ever seeing it. S477N was a convergent spike mutation even before Omicron.

it is also very deleterious according to the new T.Starr calculator:
<img width="342" alt="Screenshot 2024-07-27 alle 16 16 23" src="https://github.com/user-attachments/assets/0d0b255f-ea28-44f9-8e79-d5be69962845">
https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-EG5-FLip-BA286/RBD-heatmaps/

But i have seen it multiple times recently always thought it was not real i ve to check that then

**Comment by FedeGueli** [comment]
The query is not correct i ve edited it to the right one: G19800A, C19961T, A23933C

**Comment by ryhisner** [comment]
> The query is not correct i ve edited it to the right one: G19800A, C19961T, A23933C

Thanks, I think I forgot to fill that out and so a query from a previous proposal was still sitting there.

**Comment by aviczhl2** [comment]
I believe this is a descendant of KP.3.1.4. (Orf1b:P1675S)

**Comment by aviczhl2** [comment]
Seems not growing.

**Comment by Over-There-Is** [comment]
11 now

**Comment by FedeGueli** [comment]
Thx for noticing. could be T29N being better now? we will see

**Comment by Over-There-Is** [comment]
12, Ohio

**Comment by FedeGueli** [comment]
> 12, Ohio

6 regions in US and 2 in Canada it seems interesting

**Comment by FedeGueli** [comment]
no new seqs closing it

**Comment by FedeGueli** [comment]
+2 California (recent ) reopening it

**Comment by FedeGueli** [comment]
dead
