### ISSUE TITLE
GK.1 with 3 orf1ab mutations( E633A, D5531G, R287G) 47 seq.

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#179]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/65f738c3-7617-4d77-9309-960a456620e0)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e4f6_8bd6f0.json?c=gt-nuc_2163&label=id:node_6733721 
first seq: 2023-04-18
Most Recent: 2023-05-30
query A2163C, A16856G, C25658T
EPI_ISL_17764494 EPI_ISL_17700421 OR018609.1 EPI_ISL_17722645 OQ914246.1 OQ977461.1 OQ893999.1 EPI_ISL_17781977 EPI_ISL_17700407 EPI_ISL_17743338 OQ997328.1 OR016245.1 EPI_ISL_17782353 EPI_ISL_17767528 OQ932133.1 OQ976297.1

**Comment by Fearuncle** [comment]
https://github.com/cov-lineages/pango-designation/commit/fe717fcbdc6ed890d7c8f11c911b56e347fcf70d

**Comment by aviczhl2** [comment]
@FedeGueli Please add a milestone for this.
