### ISSUE TITLE
KP.2.15.1 (KP.2.15 + 572I)+ S:G798S(43 seqs, 6 countries)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1791]
<details><Summary>Original KP.2.15.1 proposal </summary>
KP.2.15(DeFLiRT)+T12304C+A3580G, T9418C, C23277T(S:T572I), another FULL QUAD branch.

GISAID query: C23277T, T12304C, A10861G, G17334T
No. of seqs: 19(Denmark 4 Germany 1 Sweden 9 USA 5(1 from Germany))

First: EPI_ISL_19254796, Sweden, 2024-6-5
Latest: EPI_ISL_19287195, USA, 2024-7-15

</Details>

GISAID query for S:G798S sub-branch:  C23277T, T12304C, A10861G, G23954A

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_45629_722220.json)

![image](https://github.com/user-attachments/assets/72b6e945-9a9a-4849-ae34-0f6b37a23b85)

**Comment by aviczhl2** [comment]
21, Luxembourg

**Comment by FedeGueli** [comment]
propose it when it turns 25 please

**Comment by FedeGueli** [comment]
please propose it now 26, NY

**Comment by FedeGueli** [comment]
KP.2.15 via https://github.com/cov-lineages/pango-designation/commit/74458d84b3940a49a6b9b2b75daf8f071d7d508c

**Comment by FedeGueli** [comment]
Milestone already applied by Corneliius in the commit

**Comment by aviczhl2** [comment]
Re-open here to track the G798S sub-lineage. 10 seqs from Sweden, Luxembourg, Germany and USA

**Comment by aviczhl2** [comment]
> Milestone already applied by Corneliius in the commit

Yeah and I want to collect a dataset for successful/unsuccessful proposals (for potential future AI training), so I try to keep up with milestones.

**Comment by FedeGueli** [comment]
> > Milestone already applied by Corneliius in the commit
> 
> Yeah and I want to collect a dataset for successful/unsuccessful proposals (for potential future AI training), so I try to keep up with milestones.

ok , i will stick with the old scheme not to mess things.

**Comment by aviczhl2** [comment]
27, Denmark

**Comment by aviczhl2** [comment]
+1 GBW from China

**Comment by FedeGueli** [comment]
+4 Sweden

**Comment by FedeGueli** [comment]
39, California

**Comment by FedeGueli** [comment]
+1 Colorado

**Comment by FedeGueli** [comment]
43 but likely dying off
