### ISSUE TITLE
LB.1.2+S:T572I( 34 seqs, 14 countries) likely emerged in South America

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1792]
**EDITED**: Duplicate of #1732 where this branch was earlier misplaced as LB.1+FULL QUAD , keeping this open and the other to discuss if more unrelated branches are gathered there and to track the fullquad recombinant described there.

LB.1.2+C23277T(S:T572I)

GISAID query: G19669A, C23277T, G22111T
No. of seqs: 18(Denmark 1 Ireland 1 Israel 2 Malaysia 1 Spain 1 USA 12(2 from Mexico, 2 from Netherlands, 3 from Peru, 1 from Guatemala)

Usher places this branch together with other LB.1+S:T572I branches (and wrongly proposed in #1732), however this shall be sub-branch of LB.1.2(G19669A) @AngieHinrichs

First: EPI_ISL_19205993, USA from Peru, 2024-6-7
Latest: EPI_ISL_19283124, Israel, 2024-7-14

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice156_genome_test_152de_704de0.json?label=id:node_5678162)
![image](https://github.com/user-attachments/assets/0154bae5-fbbf-400d-957d-c4b5ba506aa3)

**Comment by FedeGueli** [comment]
It is the one proposed in #1732 no need to open another issue.

**Comment by FedeGueli** [comment]
lets keep this open and the other for ddiscussing the branches and the recombinant.

**Comment by FedeGueli** [comment]
20 , new country Netherlands

**Comment by aviczhl2** [comment]
27, Australia, Canada

**Comment by FedeGueli** [comment]
please propose this one

**Comment by aviczhl2** [comment]
Usher now places it correctly. 
The Singapore seqs seem to be XDY+T572I, I'll alter query.

**Comment by FedeGueli** [comment]
Designated LB.1.2.2 via https://github.com/cov-lineages/pango-designation/commit/968a20bc7a6ecf26db18dc0cc4bcbc86a37f4659
