### ISSUE TITLE
KP.3.1.6 with N:G25S (155 seqs, mainly in New Zealand, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1793]
**Defining Mutations:** `KP.3.1.6` > `G28346A(N:G25S)`
**Query:** `T19305C, G28346A`
**Earliest seq:** 24-03-27 (`EPI_ISL_19061730`, Auckland, New Zealand)
**Latest seq:** 24-07-13 (`EPI_ISL_19281161`, Tasmania, Australia)
**Sampled Countries:** New Zealand (113), USA (3: MN/2; 1 _GBW_ sample with travel history to: Australia), UK (2: SC), Australia (1: TAS), Israel (1), Japan (1), Singapore (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Australia/TAS008006/2024
Israel/ICH-741201834/2024
Japan/FR012-0287/2024
NewZealand/24YA3351/2024
NewZealand/24YA3704/2024
NewZealand/24YA3804/2024
NewZealand/24YA3811/2024
NewZealand/24YA3889/2024
NewZealand/24YA3931/2024
NewZealand/24YA4486/2024
NewZealand/24YA4529/2024
NewZealand/24YA4542/2024
NewZealand/24YA4562/2024
NewZealand/24YA4571/2024
NewZealand/24YA4590/2024
NewZealand/24YA4591/2024
NewZealand/24YA4618/2024
NewZealand/24YA4624/2024
NewZealand/24YA4646/2024
NewZealand/24YA4659/2024
NewZealand/24YA4661/2024
NewZealand/24YA4669/2024
NewZealand/24YA4671/2024
NewZealand/24YA4682/2024
NewZealand/24YA4684/2024
NewZealand/24YA4685/2024
NewZealand/24YA4687/2024
NewZealand/24YA4732/2024
NewZealand/24YA4940/2024
NewZealand/24YA4948/2024
NewZealand/24YA4975/2024
NewZealand/24YA5050/2024
NewZealand/24YA5051/2024
NewZealand/24YA5068/2024
NewZealand/24YA5083/2024
NewZealand/24YA5089/2024
NewZealand/24YA5102/2024
NewZealand/24YA5118/2024
NewZealand/24YA5123/2024
NewZealand/24YA5159/2024
NewZealand/24YA5183/2024
NewZealand/24YA5215/2024
NewZealand/24YA5317/2024
NewZealand/24YA5327/2024
NewZealand/24YA5329/2024
NewZealand/24YA5330/2024
NewZealand/24YA5344/2024
NewZealand/24YA5358/2024
NewZealand/24YA5364/2024
NewZealand/24YA5421/2024
NewZealand/24YA5427/2024
NewZealand/24YA5476/2024
NewZealand/24YA5477/2024
NewZealand/24YA5486/2024
NewZealand/24YA5514/2024
NewZealand/24YA5531/2024
NewZealand/24YA5541/2024
NewZealand/24YA5551/2024
NewZealand/24YA5570/2024
NewZealand/24YA5575/2024
NewZealand/24YA5592/2024
NewZealand/24YA5594/2024
NewZealand/24YA5597/2024
NewZealand/24YA5606/2024
NewZealand/24YA5612/2024
NewZealand/24YA5654/2024
NewZealand/24YA5674/2024
NewZealand/24YA5683/2024
NewZealand/24YA5703/2024
NewZealand/24YA5708/2024
NewZealand/24YA5710/2024
NewZealand/24YA5724/2024
NewZealand/24YA5730/2024
NewZealand/24YA5759/2024
NewZealand/24YA5764/2024
NewZealand/24YA5806/2024
NewZealand/24YA5809/2024
NewZealand/24YA5816/2024
NewZealand/24YA5820/2024
NewZealand/24YA5830/2024
NewZealand/24YA5834/2024
NewZealand/24YA5839/2024
NewZealand/24YA5850/2024
NewZealand/24YA5852/2024
NewZealand/24YA5855/2024
NewZealand/24YA5875/2024
NewZealand/24YA5882/2024
NewZealand/24YA5898/2024
NewZealand/24YA5906/2024
NewZealand/24YA5910/2024
NewZealand/24YA5924/2024
NewZealand/24YA5927/2024
NewZealand/24YA5932/2024
NewZealand/24YA5933/2024
NewZealand/24YA5954/2024
NewZealand/24YA5961/2024
NewZealand/24YA5976/2024
NewZealand/24ZA1526/2024
NewZealand/24ZA1778/2024
NewZealand/24ZA1782/2024
NewZealand/24ZA1947/2024
NewZealand/24ZA2097/2024
NewZealand/24ZA2188/2024
NewZealand/24ZA2208/2024
NewZealand/24ZA2216/2024
NewZealand/24ZA2231/2024
NewZealand/24ZA2244/2024
NewZealand/24ZA2246/2024
NewZealand/24ZA2416/2024
NewZealand/24ZA2417/2024
NewZealand/24ZA2421/2024
NewZealand/24ZA2425/2024
NewZealand/24ZA2701/2024
NewZealand/24ZA2749/2024
NewZealand/24ZA2829/2024
NewZealand/24ZA2921/2024
Scotland/CLIMB-CM7YESYC/2024
Scotland/CLIMB-CM7YROW3/2024
Singapore/R22MQ59/2024
USA/CA-GBW-GKISBBBC31162/2024
USA/MN-MDH-41779/2024
USA/MN-UM-G43S44E0/2024

```

epi_isl accessions:
`EPI_ISL_19061730, EPI_ISL_19095954, EPI_ISL_19108761, EPI_ISL_19142199, EPI_ISL_19142306, EPI_ISL_19142333, EPI_ISL_19142407, EPI_ISL_19142409, EPI_ISL_19142688, EPI_ISL_19186713, EPI_ISL_19186775, EPI_ISL_19186803, EPI_ISL_19186876, EPI_ISL_19186882, EPI_ISL_19186952, EPI_ISL_19187079, EPI_ISL_19187125, EPI_ISL_19187266, EPI_ISL_19187291-19187292, EPI_ISL_19187296, EPI_ISL_19187300, EPI_ISL_19187437, EPI_ISL_19187442, EPI_ISL_19187454, EPI_ISL_19187466, EPI_ISL_19187468, EPI_ISL_19245244, EPI_ISL_19253175, EPI_ISL_19253611, EPI_ISL_19268455, EPI_ISL_19269563, EPI_ISL_19274526, EPI_ISL_19274536, EPI_ISL_19274569, EPI_ISL_19274636, EPI_ISL_19274643, EPI_ISL_19274646, EPI_ISL_19274657, EPI_ISL_19274660, EPI_ISL_19274664-19274665, EPI_ISL_19274683, EPI_ISL_19274690, EPI_ISL_19274703, EPI_ISL_19274714, EPI_ISL_19274734, EPI_ISL_19274736, EPI_ISL_19274742, EPI_ISL_19274746, EPI_ISL_19274755, EPI_ISL_19274759, EPI_ISL_19274764, EPI_ISL_19274775, EPI_ISL_19274777, EPI_ISL_19274780, EPI_ISL_19274800, EPI_ISL_19274807, EPI_ISL_19274814, EPI_ISL_19274825, EPI_ISL_19274829, EPI_ISL_19274834, EPI_ISL_19274836, EPI_ISL_19274849, EPI_ISL_19274855, EPI_ISL_19274883, EPI_ISL_19274888, EPI_ISL_19274933, EPI_ISL_19274949, EPI_ISL_19274957, EPI_ISL_19274982, EPI_ISL_19275000, EPI_ISL_19275005, EPI_ISL_19275020, EPI_ISL_19275022, EPI_ISL_19275025, EPI_ISL_19275032, EPI_ISL_19275036, EPI_ISL_19275090-19275091, EPI_ISL_19275099, EPI_ISL_19275123, EPI_ISL_19275139, EPI_ISL_19275146, EPI_ISL_19275207, EPI_ISL_19275217, EPI_ISL_19275219-19275220, EPI_ISL_19275233, EPI_ISL_19275237, EPI_ISL_19275241, EPI_ISL_19275254, EPI_ISL_19275259, EPI_ISL_19275270, EPI_ISL_19275285, EPI_ISL_19275290, EPI_ISL_19275378, EPI_ISL_19275386, EPI_ISL_19275410, EPI_ISL_19275475-19275476, EPI_ISL_19275495-19275497, EPI_ISL_19275499, EPI_ISL_19275526, EPI_ISL_19275564-19275565, EPI_ISL_19275588, EPI_ISL_19275594, EPI_ISL_19275614, EPI_ISL_19275626, EPI_ISL_19275628, EPI_ISL_19275635-19275636, EPI_ISL_19275646, EPI_ISL_19275686, EPI_ISL_19275695, EPI_ISL_19275713, EPI_ISL_19275722`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b1b5_76cf40.json?f_userOrOld=uploaded%20sample&label=id:node_7022824
![image](https://github.com/user-attachments/assets/f309dbdd-bcac-461f-98d6-3ce8452748be)

**Comment by FedeGueli** [comment]
If not present in numbers in the next NZL batch please close it

**Comment by FedeGueli** [comment]
one only sample is recent closing it for now
