### ISSUE TITLE
Lineages with S:255-257 deletions: BR.1 = KP.2.8 (S:S60P) 23seqs , BR.2 = LB.1.3 - 16 seqs

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1794]
<a name="task_header"></a>
```[tasklist]
### Multiple lineages with `S:SSG255-257Δ`
- [ ] [Branch 1](#branch_1) : Transferred to cov-lineages/pango-designation#2773 `KP.2.8` > `A1819G` > `C29095T` > `del22325_22333`,
- [ ] [Branch 2](#branch_2) : `LB.1.3` > `G943A` > `A2389G, del22325_22333`, query: `G943A, A2389G, C18131T`, 16 seqs, 5 countries as of 08/15
```

<a name="branch_1"></a>
### Branch 1

<details><summary>Transferred to main repo </summary>

_Transferred to cov-lineages/pango-designation#2773_

**Defining Mutations:** `KP.2.8` > `A1819G` > `C29095T` > `del22325_22333 (S:SSG255-257Δ)`
**Query:** `A1819G, del22325_22333`
**Earliest seq:** 2024-03-29 (`EPI_ISL_19037182`, South Australia)
**Latest seq:** 2024-07-06 (`EPI_ISL_19286145`, Coquimbo, Chile)
**Sampled Countries:** Australia (7: SA/4; QLD/3), Spain (4), USA (2: CO; OH), Chile (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Australia/QLD0x014426/2024
Australia/QLD0x01446A/2024
Australia/QLD0x01446C/2024
Australia/SA1368591/2024
Australia/SA1370772/2024
Australia/SA1372155/2024
Australia/SA1390078/2024
Chile/CO-53362/2024
Spain/CT-HUB09097/2024
Spain/CT-HUGTiP-G8R182/2024
Spain/CT-HUVH-E54791/2024
Spain/CT-HUVH-E67625/2024
USA/CO-CDPHE-42011782/2024
USA/OH-PLMI-6GN-25209/2024

```

epi_isl accessions:
`EPI_ISL_19037182, EPI_ISL_19055759, EPI_ISL_19085178, EPI_ISL_19085317, EPI_ISL_19150328, EPI_ISL_19169441, EPI_ISL_19169445, EPI_ISL_19191188, EPI_ISL_19203552, EPI_ISL_19223501, EPI_ISL_19243908, EPI_ISL_19269209, EPI_ISL_19286108, EPI_ISL_19286145`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32bd6_777330.json?label=id:node_7038842
![image](https://github.com/user-attachments/assets/304734dd-35b2-4191-8cd6-19e74645f3c3)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2

**Defining Mutations:** `LB.1.3` > `G943A` > `A2389G, del22325_22333 (S:SSG255-257Δ)`
**Query:** `G943A, A2389G, C18131T`
**Earliest seq:** 24-05-30 (`EPI_ISL_19198089`, England)
**Latest seq:** 24-07-05 (`EPI_ISL_19276404`, England)
**Sampled Countries:** UK (5: EN), France (1), Ireland (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
England/CLIMB-CM7YJR3M/2024
England/CLIMB-CM7YJZHC/2024
England/CLIMB-CM7YKJ3Y/2024
England/CLIMB-CM7YKZA4/2024
England/CLIMB-CM7YR8R1/2024
France/BFC-RELAB-IPP07658/2024
Ireland/G-GUH-N2672/2024
```

epi_isl accessions:
`EPI_ISL_19198089, EPI_ISL_19232448, EPI_ISL_19262153, EPI_ISL_19267156, EPI_ISL_19276372, EPI_ISL_19276404, EPI_ISL_19276460`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b8c2_77b2e0.json?label=id:node_7231919
![image](https://github.com/user-attachments/assets/a2c37c14-bc5c-472c-bebc-5071ac3500c1)
note: only the _GBW_ samples under this branch are without 255-257 deletions

[Back to Tasklist](#task_header)

**Trivia:**
- Of all the NTD deletions, S:Δ255-257 is something much less common than Δ69-70 (SGTF), Δ142-146, Δ185-189, Δ210-212, Δ241-243, to name a few.
![image](https://github.com/user-attachments/assets/eced232b-144a-4081-9310-04d6098318da)

**Comment by FedeGueli** [comment]
There is also the large del between S:184-190 that should be monitored

**Comment by FedeGueli** [comment]
17 seqs for br.1
 10 for branch 2

**Comment by FedeGueli** [comment]
Branch 1 likely dying off while branch 2 went to 13

**Comment by FedeGueli** [comment]
20
16

**Comment by FedeGueli** [comment]
Br.1 > 25

**Comment by FedeGueli** [comment]
Br.1 went to 34 @NkRMnZr please propose it

**Comment by FedeGueli** [comment]
Thx @NkRMnZr
