### ISSUE TITLE
XDR.1 + S:F456L (5 seq, 4 countries, 3 with S:R237K)

### ISSUE THREAD

**Issue by DoropFan** [sars-cov-2-variants/lineage-proposals#1795]
Sub-lineage of:XDR.1
Earliest sequence:2024-06-06|Brazil|EPI_ISL_19284486
Most recent sequence:2024-07-09|USA|
Countries circulating:Brazil(1), Switzerland(1), USA(1)
Sequences:3

[UShER Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28f89_7827c0.json?c=gt-nuc_22930&gmax=23930&gmin=21930&label=id:node_7103204)
XDR.1>ORF1a:A2142V(C6690T)>ORF1b:A2480D(C20906A), S:F456L(T22930A), ORF8:E92K(G28167A)
![XDR 1+456L](https://github.com/user-attachments/assets/f45b7a9e-da79-4100-9f9c-66184e7b8e52)
Query:G28167A, C6690T, T21738C

[CovSpectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nucMutations=28167A%2C6690T%2C21738C&nextcladePangoLineage1=XDR.1&)
Genomes
EPI_ISL_19255587
EPI_ISL_19284486

**Comment by FedeGueli** [comment]
I was tracking this one too! i deleted the query the day before the new sample came out!

**Comment by aviczhl2** [comment]
+1 GBW from Brazil

**Comment by aviczhl2** [comment]
3 of the seqs have additional S:R237K

![image](https://github.com/user-attachments/assets/02aae82c-4ce9-4f43-9bf3-76e0e292b342)

**Comment by aviczhl2** [comment]
Designated XDR.1.1

**Comment by Over-There-Is** [comment]
R237K is 21 now.
