### ISSUE TITLE
LB.1.8 with Orf1a:A2529V (232 sequences, 10 countries) emerged in Guatemala or Honduras  

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1796]
LB.1.8 is one of the few FLiRT lineages that was able to establish a dominance in one country (Venezuela)
Now it reached 144 samples globally and interestingly its biggest and most international branch is defined by the infamous AY.4 defining Orf1a:A2529V, this sublienage emerged in Guatemala or Honduras where it has high prevalence ( 9/75 and 12/49 respectively after May 1)
Defining LB.1.8 > T2561C> Orf1a:A2529V (C7851T)
Query:T2561C,C7851T,T3565C
Samples: 75
First collected on 2024-04-26 in Guatemala
Countries: 10  ( Honduras, Guatemala, US, Mexico with more than 1 sample)
Tree:
<img width="1171" alt="Screenshot 2024-07-30 alle 01 03 19" src="https://github.com/user-attachments/assets/5c519ef9-d976-49e5-a9de-d1bde484ab56">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_30f3d_81c490.json?c=gt-ORF1ab_2529&gmax=21555&gmin=266&label=id:node_7234278

**Comment by ryhisner** [comment]
All the long branches visible on the Usher Tree that Fede posted above are artifacts—except for the top one, which stretches out to 160 mutations. That one is unquestionably a molnupiravir creation. Unfortunately, it came from a pooled sample by Ginkgo Bioworks (AKA Ginkgo Bozoworks), the company that, despite its longstanding inability to deliver quality sequences, somehow wrangled the federal contract to do airport travel sequences in the US. No one is supposed to upload pooled samples, but these clowns continue to do so against database rules. 

Travel information is only included on individual GBW sequences, not pooled sequences, so we have no idea what country this sequence originated in. Sometimes, an individual sequence appears sometime after the corresponding pooled sequence was uploaded, so hopefully the individual sequence for this comes out in the next week or so.

Anyway, below is my analysis of this pooled sequence's private mutations, which clearly demonstrates its origin in molnupiravir treatment. 

The nucleotide context figures come from @theosanderson's invaluable Mov Mutations Analysis app, which can be found here: https://movbranchapp.streamlit.app/ 

<img width="940" alt="image" src="https://github.com/user-attachments/assets/06d05d9a-4347-4d9f-ab5c-c4478346a3c6">

**Comment by FedeGueli** [comment]
Thank you @ryhisner

**Comment by FedeGueli** [comment]
+3

**Comment by ryhisner** [comment]
So the individual sequence from the pooled, molnupiravir travel sequence came in today, and it was from a traveler from Mexico. Sequence is identical to the pooled sequence. Quite unusually for a GBW sequence, it has good coverage, which likely indicates a high viral load.
EPI_ISL_19289747

**Comment by FedeGueli** [comment]
> So the individual sequence from the pooled, molnupiravir travel sequence came in today, and it was from a traveler from Mexico. Sequence is identical to the pooled sequence. Quite unusually for a GBW sequence, it has good coverage, which likely indicates a high viral load. EPI_ISL_19289747

Thanks for updating on this, Ryan! I ve changed the title consequently

**Comment by FedeGueli** [comment]
89, with a traveler from Honduras carrying two further mutations in the spike S:D428Y and S:V705I

**Comment by FedeGueli** [comment]
104

**Comment by FedeGueli** [comment]
123 with a big batch from Guatemala. ping @corneliusroemer

**Comment by FedeGueli** [comment]
144

**Comment by FedeGueli** [comment]
175

**Comment by aviczhl2** [comment]
197 seqs including many previous seqs from Mexico.

**Comment by FedeGueli** [comment]
Only two recent samples closing this

**Comment by Over-There-Is** [comment]
336

**Comment by Over-There-Is** [comment]
a branch gets K150N

**Comment by FedeGueli** [comment]
Dead since september

**Comment by Over-There-Is** [comment]
L>W452R 31?
