### ISSUE TITLE
MM.1 + S:T240I + ORF1a:T619I (19 in Israel) with further S:F59L (4)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1797]
![image](https://github.com/user-attachments/assets/cbe5a5bd-f294-481c-9675-c5f96fef198b)
![image](https://github.com/user-attachments/assets/0a2bf580-7bd1-4817-b978-550882afa339)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24af9_8651d0.json?label=id:node_7034918

Gisaid Query: C2121T, G3562A

Gisaid Query with 59L: A19291T, T21737C

EPI_ISL_19274222 EPI_ISL_19283153 EPI_ISL_19274323 EPI_ISL_19274246 EPI_ISL_19243016 EPI_ISL_19242983 EPI_ISL_19242937 EPI_ISL_19256461 EPI_ISL_19275765 EPI_ISL_19274262 EPI_ISL_19283176 EPI_ISL_19256519 EPI_ISL_19203632 EPI_ISL_19242849 EPI_ISL_19275838 EPI_ISL_19274376

**Comment by Fearuncle** [comment]
there are 3 seq. with s:59L EPI_ISL_19256461 EPI_ISL_19290882 EPI_ISL_19290842

**Comment by FedeGueli** [comment]
> there are 3 seq. with s:59L EPI_ISL_19256461 EPI_ISL_19290882 EPI_ISL_19290842

Please add it to the proposal with a specific query for this sublineage

**Comment by FedeGueli** [comment]
still 18, likely a cluster

**Comment by Fearuncle** [comment]
dead
