### ISSUE TITLE
Multiple lineages with multiple AA deletions around 184-190, 6 branches as of Aug 21

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1798]
It seems that in this phase of the pandemic deletions around 184-190 could be convergently beneficial.
We are used to the S:N185del+S:F186I recurrent deletion (As GE.1) or we have already observed large deletion in that area but it usually happened between 180-184 (as XBB.1.5.103) .
Now we have already two lineages designated with it LS.1 and JN.1.7.8 and one proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1703 but more are popping up.

1) **LS.1** Query: G9049A,G3085T, T21644C Samples: 30
2) **JN.1.7.8** Query:C29367T,C2695T,C7840T,T22930A Samples: 69
with a Trio sub: C16954T,del22115,T3565C Samples:5  ( tracked as Br 155 of #1089) 
3) KR.1 + 186-89del+190W dead Query:del22118_22129,C1762A Samples: 13 proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1703
4) KP.3.2.4 + 186-189del Query: C15654T, C21516T,del22115 Samples:3 dead
5) LB.1.4 +186-189del and 176F :  A10018G,del22115 Samples: 2 dead
6) LB.1.7 + 186-189del Query: C4784T,del22115,G21123T Samples:39
7) JN.1.16.1 + 186-189del Query:  del22115,C7072T, C9803T Samples: 10 dead
8) KP.2.3 + 185-189del proposed in #2003

**Comment by georg122** [comment]
In what way beneficial?

**Comment by FedeGueli** [comment]
> In what way beneficial?

adding some growth advantage.

**Comment by FedeGueli** [comment]
Br.6 goes to 12 
Br.7 to 6

**Comment by FedeGueli** [comment]
Br.6 went to 14
Br.4 to 3

they doesnt seem fast

**Comment by FedeGueli** [comment]
Br.6 now 18
Br.7 now 8

**Comment by FedeGueli** [comment]
+1 each br.6 and br.7

**Comment by Mydtlwn** [comment]
#2003

**Comment by FedeGueli** [comment]
Added branch 8 from #2003, 

branch 6 is now 25, maybe worth proposing it? cc @aviczhl2 @over-there-is @nkrmnzr ?

branch 7 is 10 growing slowly

**Comment by FedeGueli** [comment]
only branch 6 is still going , now at 27

**Comment by FedeGueli** [comment]
Branch 6 is the only alive 33 samples with the last samples from different US states. Leaving it open for a while

**Comment by FedeGueli** [comment]
Br 6 now 35, @aviczhl2 what about if i propose br.6 and close this? i m unusre BR.6 can compete but it is still growng so maybe worth being tracked

**Comment by FedeGueli** [comment]
> > Br 6 now 35, @aviczhl2 what about if i propose br.6 and close this? i m unsure BR.6 can compete but it is still growng so maybe worth being tracked
> 
> Yeah sure.

i will wait a week more i suspect this wll stop growing as the most of lineages as of today

**Comment by FedeGueli** [comment]
Br.6 up to 39 proposing it and closing this
