### ISSUE TITLE
JN.1+S:F456L possible dead or designated branch 

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1799]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253
Branch 21: 85 seqs, last sample was on 22 June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2f7cb_9082a0.json?f_userOrOld=uploaded%20sample)
Branch 36: 116 seqs, last sample was in June 2024:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11b47_7b8cc0.json?label=id:node_6998538)
Branch 41: 16 seqs, last sample was on 22 June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_37e11_9a4940.json)
Branch 48: 38 seqs, last smaple was on 24 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3d519_9a7780.json?f_userOrOld=uploaded%20sample)
Branch 58: 77 seqs, last sample was on 27 June 2024:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_374cd_90bb30.json?f_userOrOld=uploaded%20sample)
Branch 73: 20 seqs, last sample was on 2 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_42b6c_90cee0.json?f_userOrOld=uploaded%20sample&label=id:node_6979794)
Branch 113: 9 seqs, last sample was on 6 May 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_ff0_9ffa60.json?f_userOrOld=uploaded%20sample)
Branch 51,57 and 62 are not monophyletic

**Comment by FedeGueli** [comment]
Br.21 already closed
Br.36 aka https://github.com/cov-lineages/pango-designation/issues/2613  you can close it
Branch 41: already closed
Branch 48 already closed
Branch 58 you should rearrange the proposal to propose exclusively the FLiRT branch now 12 (query G16269A,C12781T,T22928C,G22599C) it is the fast you should do it urgently.
Branch 73 already closed
Branch 113 now closed.

**Comment by DailyCovidCases** [comment]
Branch 51,57 and 62 are not monophyletic, please update it

**Comment by FedeGueli** [comment]
> Did you denote it with * instead of [P]?

As i ve said the updating back to secondary repo is too time expensive especially when 456L is already over 90%

**Comment by DailyCovidCases** [comment]
Branch 51: 281 seqs, not monophyletic, last sample was on 12 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_329d8_a35e30.json?f_userOrOld=uploaded%20sample)
Branch 57: 137 seqs, not monophyletic, last sample was on 10 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2b95e_a33340.json?f_userOrOld=uploaded%20sample)
Branch 62: 214 seqs, not monophyletic, last sample was on 7 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_353ef_a36990.json?f_userOrOld=uploaded%20sample)

**Comment by DailyCovidCases** [comment]
+) Branches slowing down, but still possible designation:
Branch 7: 298 seqs, last sample was on late June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4228b_a40110.json?f_userOrOld=uploaded%20sample)
Branch 17: 291 seqs, last sample was on late June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_c0d_a411a0.json?f_userOrOld=uploaded%20sample)
Branch 15: 142 seqs, last sample was on 4 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1497_a41700.json?f_userOrOld=uploaded%20sample)
Branch 11: 470 seqs, last sample was on 9 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4b87_a42ac0.json?f_userOrOld=uploaded%20sample)
Branch 26: At least 1632 seqs
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_148d4_a43e00.json?f_userOrOld=uploaded%20sample)
Branch 67: 75 seqs: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_13c_a54510.json?f_userOrOld=uploaded%20sample&label=id:node_7121299)
Branch 100: 121 seqs:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_10c92_a55b40.json?f_userOrOld=uploaded%20sample)
+)Dead branches:
Branch 51: 281 seqs, not monophyletic, last sample was on 12 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_329d8_a35e30.json?f_userOrOld=uploaded%20sample)
Branch 57: 137 seqs, not monophyletic, last sample was on 10 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2b95e_a33340.json?f_userOrOld=uploaded%20sample)
Branch 62: 214 seqs, not monophyletic, last sample was on 7 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_353ef_a36990.json?f_userOrOld=uploaded%20sample)
Branch 110: 58 seqs, not monophyletic, last sample was on 25 June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_133e9_a56680.json?f_userOrOld=uploaded%20sample)

**Comment by DailyCovidCases** [comment]
+) Branches slowing down, but still possible designation:
Branch 7: 298 seqs, last sample was on late June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4228b_a40110.json?f_userOrOld=uploaded%20sample)
Branch 17: 291 seqs, last sample was on late June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_c0d_a411a0.json?f_userOrOld=uploaded%20sample)
Branch 15: 142 seqs, last sample was on 4 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1497_a41700.json?f_userOrOld=uploaded%20sample)
Branch 11: 470 seqs, last sample was on 9 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4b87_a42ac0.json?f_userOrOld=uploaded%20sample)
Branch 26: At least 1632 seqs
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_148d4_a43e00.json?f_userOrOld=uploaded%20sample)
Branch 67: 75 seqs: 
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_13c_a54510.json?f_userOrOld=uploaded%20sample&label=id:node_7121299)
Branch 100: 121 seqs:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_10c92_a55b40.json?f_userOrOld=uploaded%20sample)
+) Dead branches:
Branch 15: 217 seqs, not monophyletic, last smaple was on 15 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_128f7_dec090.json?f_userOrOld=uploaded%20sample)
Branch 51: 281 seqs, not monophyletic, last sample was on 12 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_329d8_a35e30.json?f_userOrOld=uploaded%20sample)
Branch 57: 137 seqs, not monophyletic, last sample was on 10 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2b95e_a33340.json?f_userOrOld=uploaded%20sample)
Branch 62: 214 seqs, not monophyletic, last sample was on 7 July 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_353ef_a36990.json?f_userOrOld=uploaded%20sample)
Branch 110: 58 seqs, not monophyletic, last sample was on 25 June 2024
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_133e9_a56680.json?f_userOrOld=uploaded%20sample)

**Comment by DailyCovidCases** [comment]
Some branches on 
I think some branch on 
https://github.com/cov-lineages/pango-designation/issues/2543 
https://github.com/cov-lineages/pango-designation/issues/2517
https://github.com/cov-lineages/pango-designation/issues/2577
https://github.com/cov-lineages/pango-designation/issues/2578
https://github.com/cov-lineages/pango-designation/issues/2589
https://github.com/cov-lineages/pango-designation/issues/2531
should be either designated or count as dead

**Comment by FedeGueli** [comment]
#1253 is closed and archived now.
