### ISSUE TITLE
South Korean CH.1.1.26 (+N:A208V) with S:V483F (5seqs 2023-05-07)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#18]
<img width="2147" alt="image" src="https://user-images.githubusercontent.com/25161793/236667624-fef7c186-6260-4536-a6a7-3967e916800e.png">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43436_760ef0.json?label=id:node_6372592

Edited: N_A208V,Spike_V483F finds 4 samples

**Comment by FedeGueli** [comment]
Still 4 seqs closing it for the moment.
