### ISSUE TITLE
JN.1.7 subranch with S:F456L and Orf1b:A1428V (54 seqs, 14 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1800]
Found with @aviczhl2 's phylogenic tree analysis tool.

JN.1.7> C25416T> C25578T> C17750T(Orf1b:A1428V), T24304C> T22928C(S:F456L)
Query: C17750T, T22928C, T24304C

Earliest sequence: 05-11 Zürich, Switzerland EPI_ISL_19178040
Latest sequence: 07-14 Ontario, Canada EPI_ISL_19281252
Regions Detected: Canada 5, Netherlands 4, Germany 2, Spain 2, Switzerland 2, US 2, France 1, Portugal 1, UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_633c2_a35720.json?gt=nuc.25416T&label=id:node_7212051
![image](https://github.com/user-attachments/assets/97b3ce33-efb2-494c-a474-388d103ac22e)

<details> <summary> Sequences: </summary>

EPI_ISL_19178032, EPI_ISL_19178040, EPI_ISL_19185909,
EPI_ISL_19202236, EPI_ISL_19230346, EPI_ISL_19243719,
EPI_ISL_19253418, EPI_ISL_19254411, EPI_ISL_19258458,
EPI_ISL_19266028, EPI_ISL_19272969, EPI_ISL_19273805,
EPI_ISL_19277312, EPI_ISL_19280241, EPI_ISL_19281252,
EPI_ISL_19281372, EPI_ISL_19281375, EPI_ISL_19283944,
EPI_ISL_19292932, EPI_ISL_19294028
</details>

**Comment by Over-There-Is** [comment]
39, Ireland

**Comment by FedeGueli** [comment]
missed the scottish sample.

**Comment by Over-There-Is** [comment]
Japan

**Comment by Over-There-Is** [comment]
Luxembourg

**Comment by FedeGueli** [comment]
revived after one month hyatus, dunno think it will go anywhere though

**Comment by FedeGueli** [comment]
> Greece

Old one! Still circualting only in a  Canadian cluster. Lets see if it will go out from there

**Comment by FedeGueli** [comment]
Closing for now
