### ISSUE TITLE
KP.3.1 subbranch with S:N>K679R(99 seqs, 15 countries, mainly in Spain) and further S:L176F(27, 5 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1802]
Found with @aviczhl2 's phylogenic tree analysis tool.
Spotted first by @aviczhl2 .

KP.3.1> A1620G(Orf1a:E452G)> T2593C> C8616T(Orf1a:A2784V)> C14216T(Orf1b:T250I), A23598G(S:K679R)> C22088T(S:L176F)
Query: C14216T, A23598G

Earliest sequence: 04-21 Madrid, Spain EPI_ISL_19164708
Latest sequence: 07-30 Skåne, Sweden EPI_ISL_19326372
Regions detected: 
Spain 52(including 1 from Canary Islands), France 6, UK 6, Sweden 4, Ireland 4, Italy 2, Portugal 2, Finland 1, Greece 1, Netherlands 1, Luxembourg 1;
US 7(1 from Greece, 1 from Spain), Canada 1;
Israel 1.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_66f36_b651f0.json?c=country&label=id:node_7028498
![2024-08-13 (16)](https://github.com/user-attachments/assets/b52bfa1b-7360-4af7-a24e-129b4ad417d7)

<details> <summary> Sequences: </summary>

EPI_ISL_19164708, EPI_ISL_19164712, EPI_ISL_19176965,
EPI_ISL_19178589, EPI_ISL_19179515, EPI_ISL_19185426,
EPI_ISL_19186676, EPI_ISL_19189621, EPI_ISL_19194760,
EPI_ISL_19194769, EPI_ISL_19195261, EPI_ISL_19197928,
EPI_ISL_19201438, EPI_ISL_19201738, EPI_ISL_19214624,
EPI_ISL_19215264, EPI_ISL_19215276, EPI_ISL_19216662,
EPI_ISL_19218924, EPI_ISL_19219465, EPI_ISL_19220641,
EPI_ISL_19221168, EPI_ISL_19221172, EPI_ISL_19221310,
EPI_ISL_19221771, EPI_ISL_19222000, EPI_ISL_19225530,
EPI_ISL_19225568, EPI_ISL_19225573, EPI_ISL_19229220,
EPI_ISL_19229223, EPI_ISL_19231626, EPI_ISL_19232532-19232533,
EPI_ISL_19232597, EPI_ISL_19235907, EPI_ISL_19252937,
EPI_ISL_19258573, EPI_ISL_19261329, EPI_ISL_19261586,
EPI_ISL_19263174, EPI_ISL_19263232, EPI_ISL_19263264,
EPI_ISL_19263302, EPI_ISL_19263321, EPI_ISL_19264890,
EPI_ISL_19265498, EPI_ISL_19265509, EPI_ISL_19266060,
EPI_ISL_19267058, EPI_ISL_19267060, EPI_ISL_19270338,
EPI_ISL_19271730, EPI_ISL_19273215, EPI_ISL_19276263,
EPI_ISL_19276287, EPI_ISL_19277304, EPI_ISL_19280649,
EPI_ISL_19280673, EPI_ISL_19280872, EPI_ISL_19281671,
EPI_ISL_19287047, EPI_ISL_19289400, EPI_ISL_19290827,
EPI_ISL_19291541, EPI_ISL_19292706, EPI_ISL_19293241,
EPI_ISL_19296711, EPI_ISL_19296910, EPI_ISL_19300146,
EPI_ISL_19305441, EPI_ISL_19305699, EPI_ISL_19307088,
EPI_ISL_19309647, EPI_ISL_19310720, EPI_ISL_19311299,
EPI_ISL_19312405, EPI_ISL_19312486, EPI_ISL_19312559,
EPI_ISL_19313452, EPI_ISL_19319581, EPI_ISL_19322327,
EPI_ISL_19322362, EPI_ISL_19322545, EPI_ISL_19323296,
EPI_ISL_19323471, EPI_ISL_19326372, EPI_ISL_19327347,
EPI_ISL_19331142
</details>

**Comment by FedeGueli** [comment]
I think this was spotted by @aviczhl2 tto : https://github.com/cov-lineages/pango-designation/issues/2646#issuecomment-2199279663 and i ve added a slighty different query: 
>Query: C14216T, A23598G,T3565C

**Comment by Over-There-Is** [comment]
81, Sweden, Luxembourg, Italy

**Comment by Over-There-Is** [comment]
89, Finland

**Comment by FedeGueli** [comment]
100 Denmark

**Comment by Over-There-Is** [comment]
Transferred to cov-lineages/pango-designation#2743

**Comment by FedeGueli** [comment]
Designated NR.1 Via https://github.com/cov-lineages/pango-designation/commit/5872a5a02c2723909dfb5cf8b211cbf485b552fa#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1326
