### ISSUE TITLE
KP.2.3 subbranch with S:L945I (AU-TAS 13)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1803]
Found with @aviczhl2 's phylogenic tree analysis tool.

KP.2.3> C28714T> C9430T> C2189T(Orf1a:L642F), A29350T> C4456T, C6031T, C12312T(Orf1a:A4016V), C19041T, C24395A(S:L945I), C29149T
Query: C2189T,C4456T,C6031T

06-23~06-28, Tasmania, Australia 13

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_67083_a7c3c0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/9b79df1f-5fd9-4641-86cd-f4fe87185b1f)

<details> <summary> Sequences: </summary>

EPI_ISL_19281038, EPI_ISL_19281040-19281041, EPI_ISL_19281048,
EPI_ISL_19281051, EPI_ISL_19281055-19281056, EPI_ISL_19281058,
EPI_ISL_19281061, EPI_ISL_19281067, EPI_ISL_19281069,
EPI_ISL_19281071, EPI_ISL_19281079

</details>

**Comment by FedeGueli** [comment]
It looks like a cluster to me but mutations in that area are always interesting so good to track it

**Comment by ryhisner** [comment]
Really unusual mutation. Can't recall seeing L945I before.

**Comment by FedeGueli** [comment]
> Really unusual mutation. Can't recall seeing L945I before.

Me too, vaugely i recall in the past we discussed of residue S:944 for some reason or in some paper,  but i have to check.

**Comment by aviczhl2** [comment]
Still the initial ones
