### ISSUE TITLE
LB.1.2.1 + S:H445N, ORF1b:K2557R (3 seq, India; Aug 19)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1804]
**Description**
**Sub-lineage of:** LB.1.2.1 (S:S31del, S:Q183H, S:R190T)
**Earliest sequence:** 2024-7-20 – India (travelers to USA) EPI_ISL_19300522, EPI_ISL_19300563
**Most recent sequence:** 
**Continents circulating:** Asia (2)
**Countries circulating:** India (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** _NEW EDITED_: A21137G,C18693A,T3565C (Old by author: C18693A, A25327G)
**CovSpectrum Query:** Nextcladepangolineage:LB.1* & [3-of: C18693A, A21137G, C22895A, A25327G]
**Substitutions on top of LB.1.2.1:**
**Spike:** H445N
**ORF1b:** K2557R (NSP16_K160R)
**Nucleotide:** C18693A, A21137G, C22895A, A25327G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/LB.1.2.1_H445N.json?c=gt-S_445&gmax=25384&gmin=21563&label=id:node_11573498

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/83f6b51a-59ee-46cd-9823-df25f67082fa">

**Evidence**
Not the first time S:H445N has shown up, but coming in a lineage like LB.1.2.1 (S31del, Q183H, R190T, R346T, F456L) from two travelers from India and with a very recent collection date (July 20), I think it's the first time it's worth paying some attention to.

These are Ginkgo Bozoworks sequences, so that quality is not good. Tons of dropout scattered throughout the genome. One of the sequences has several additional mutations—ORF1a:F1214V, ORF1a:T1216N, ORF1a:T2283I, ORF1a:I3255T (reversion), N:N48D/ORF9b:I44M)—but coming from GBW, it's hard to know whether they are real or artifacts. If more sequences show up, we may eventually know. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19300522, EPI_ISL_19300563
</details>

**Comment by FedeGueli** [comment]
One more sequence of this one and guess who? GBW again, India again.

**Comment by FedeGueli** [comment]
And i just checked Tyler Starr new JN.1 Calculator and 445N could be a thing:
<img width="261" alt="Screenshot 2024-08-05 alle 17 29 44" src="https://github.com/user-attachments/assets/fbed06d2-33b2-485b-95c3-b395ef0e1f9f">

**Comment by FedeGueli** [comment]
Oh i just see you excluded the pooled sample, for simnplicity please take it in the count and if you want you can differentiate between seqs and patients (3 samples , 2 patients)

**Comment by aviczhl2** [comment]
No new seqs
