### ISSUE TITLE
Super weird EU.1.1.1 + ORF9b:T83I lineage mostly Utah,US 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#181]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/194036d3-222a-4bec-bafe-cd876dee63ed)
tree https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3809f_8d7fa0.json?label=id:node_6694878

**Edited**:

Defining mutations:
EU.1.1.1>>C21646T >C23185T, C28531T= **ORF9b:T83I** , C28651T >G10201T=**Orf1a:M3312I** (NSP5_M49I), C12741T = **ORF1a:T4159I** (NSP9_T19I)

Gisaid query: **C23185T, C28531T, C28651T**

Samples: 40 seqs

EPI_ISL_17602253, EPI_ISL_17639593, EPI_ISL_17669781,
EPI_ISL_17689548, EPI_ISL_17690035, EPI_ISL_17727521-17727522,
EPI_ISL_17727529-17727530, EPI_ISL_17727533, EPI_ISL_17727544,
EPI_ISL_17727557-17727560, EPI_ISL_17727574, EPI_ISL_17727577,
EPI_ISL_17727586, EPI_ISL_17727598, EPI_ISL_17727600,
EPI_ISL_17727609, EPI_ISL_17727617, EPI_ISL_17727619,
EPI_ISL_17727628, EPI_ISL_17727636, EPI_ISL_17727638,
EPI_ISL_17727640-17727645, EPI_ISL_17727651, EPI_ISL_17727660,
EPI_ISL_17727662, EPI_ISL_17727665, EPI_ISL_17727667,
EPI_ISL_17727670, EPI_ISL_17788415, EPI_ISL_17788521,

**Comment by MCB6** [comment]
the hardest to believe part is that almost all of them are from the same small batch (33 / 45 samples collected on May 18 and submitted on May 30).  Either a targeted outbreak or perhaps more likely a contamination case?

**Comment by FedeGueli** [comment]
41 closing.
