### ISSUE TITLE
JN.1/BA.2.86 recombinant with FLiRT+S:S704L (5 seqs, France)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1810]
There seems to be a French JN.1/BA.2.86 recombinant , or chronic. 

JN.1+C27810T(rev)+A1817G, T10921C, T27878C,T1570C, C2445T, C11518T, G22599C, T22928C, C23673T

Orf1a: K518E, T727I
S: F456L, R346T, S704L

Likely formed via recomb
JN.1.16.1(most likely)--BA.2.86

Breakpoint between 23674 and 27809
C27810T(rev), T27878C from BA.2.86 branch 
Other mutations are private. 

Can that reversion be gained from chronic infection? 

GISAID query: T22928C,C23673T,G22599C,T1570C
No. of seqs: 5(France, different patients)

EPI_ISL_19299980-82, 87,90 , 2024-7-15

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice232_genome_test_35b05_b09810.json)

![image](https://github.com/user-attachments/assets/b3cc46a7-93e9-4e2b-9ad3-0e04f4d273d1)

**Comment by FedeGueli** [comment]
704L Loves Recombinants part two.

**Comment by aviczhl2** [comment]
No more seqs
