### ISSUE TITLE
JN.1.29.1(S:F456L) subbranch with S:R346T(32 seqs, 5 regions) and further S:L56V(19 seqs, 4 regions) then S:T22N (BR 3)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1813]
Found with @aviczhl2 's phylogenic tree analysis tool.

JN.1.29.1> C8917T> G22599C(S:R346T)> G18318T, C20930T(Orf1b:T2488M)> del686-694(Orf1a:del141-143)> A259G, A28984G> T21728G(S:L56V)> T11635C, T17407C, C21627A(S:T22N)
Query: C8917T, A9935G, G22599C, -A405G
Query for 56V: C8917T, A9935G, T21728G (edited)
Query for 56V+22N: T11635C, C21627A, T21728G (edited)

Earliest sequence: 03-26 Eusebio, Ceara, Brazil EPI_ISL_19282419
Latest sequences: 06-30 California, USA(imported from Spain) EPI_ISL_19273788
Regions detected: Brazil 18, US 4(including 1 in Puerto Rico, 2 from Spain, 1 from unknown), UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3adbf_bc87e0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/c356d40f-1bfa-431a-a4c4-94c834410c44)

<details> <summary> Sequences: </summary>

EPI_ISL_18952414, EPI_ISL_18961998, EPI_ISL_18998958-18998959,
EPI_ISL_19043828, EPI_ISL_19064049, EPI_ISL_19133577,
EPI_ISL_19230423, EPI_ISL_19254506, EPI_ISL_19269974,
EPI_ISL_19271357, EPI_ISL_19273788, EPI_ISL_19282403-19282404,
EPI_ISL_19282406-19282409, EPI_ISL_19282420, EPI_ISL_19282423-19282424,
EPI_ISL_19287115, EPI_ISL_19288494

</details>

**Comment by FedeGueli** [comment]
Sorry i ve missed this one

**Comment by FedeGueli** [comment]
I see three of this one uplaoded today from brazil all with 56V but Gisaid shows one only when querying, i think the trick of white metadata and mutation by Gisaid is back. For examples there were at least 25 JN.1.55.2 flirt uploaded todaybut the best query i ve found catches only 4 or 5 . cc @aviczhl2

**Comment by FedeGueli** [comment]
3 samples uploaded yesterday from Brazil collected in September have also S:T22N. Added relative queries that were missing for 56V and the new 22N branch

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. How many seqs right now?

**Comment by Over-There-Is** [comment]
still 32

**Comment by FedeGueli** [comment]
closing for now

**Comment by xz-keg** [comment]
designated MJ.2.1 and MJ.2.1.1
