### ISSUE TITLE
JN.1.4+Orf1a:T4087I,Orf1b:S1512N+S:F456L(297 seqs, 19 countries, 20 with S:T572I, 8 with S:R346T)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1818]
From branch 7 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1253

JN.1.4+Orf1a:T4087I(C12525T)+Orf1b:S1512N(G18002A)+S:F456L (T22928C)

GISAID Query: T18453C, C12525T,T22928C
No. of seqs: 297

First: EPI_ISL_18681708, USA,2023-12-12
Latest:  EPI_ISL_19280065, USA, 2024-7-10

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3e11e_ca0270.json?f_userOrOld=uploaded%20sample)
![Screenshot (157)](https://github.com/user-attachments/assets/1ec9d469-91bf-4f63-a721-b794e5f5878e)

**Comment by aviczhl2** [comment]
This one was long proposed in main repo.
