### ISSUE TITLE
KP.2.6 + S:V367A, S:A376T (R), ORF1b:R1518K (36 seq, 3 countries; Oct 1)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1819]
### **Description**
**Sub-lineage of:** KP.2.6 (S:∆F32, S:W64R)
**Earliest sequence:** 2024-6-19, Wales – EPI_ISL_19239408
**Most recent sequence:** 2024-7-21, Wales – EPI_ISL_19305909
**Continents circulating:** Europe (13)
**Countries circulating:** Wales (13)
**Number of Sequences:** 13
**GISAID Nucleotide Query:** G18020A, C1254T
**CovSpectrum Query:** Nextcladepangolineage:KP.2.6* & [3-of: G18020A, C1254T, C24106T, T22662C, !A22688G]
**Substitutions on top of X:**
**Spike:** V367A, A376T (reversion)
**ORF1b:** R1518K
**Nucleotide:** C1254T, G18020A, T22662C, G22688A, C24106T, C29095T

**USHER Tree** (temporary link for now)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4c02_cf70c0.json?c=gt-S_367&label=id:node_7050717

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/0b19e21f-72c2-4173-83f0-8007303d32cc">

**Evidence**
Looks like just a local Wales cluster at the moment. Will update if it expands to other countries. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19239408, EPI_ISL_19265422, EPI_ISL_19272185, EPI_ISL_19272210, EPI_ISL_19272278, EPI_ISL_19276469, EPI_ISL_19288054, EPI_ISL_19292046, EPI_ISL_19305834, EPI_ISL_19305903, EPI_ISL_19305909, EPI_ISL_19305925, EPI_ISL_19305940
</details>

**Comment by FedeGueli** [comment]
Thx Ryan! KP.2.6 despite being a relative small branch has a lot of interesting spike diversity!

**Comment by FedeGueli** [comment]
+3 Wales

**Comment by FedeGueli** [comment]
It seems fast @ryhisner please propose it

**Comment by FedeGueli** [comment]
26 but still Wales

**Comment by FedeGueli** [comment]
> It seems fast @ryhisner please propose it

i think we should wait very likely clusters in Wales.

**Comment by FedeGueli** [comment]
it seems dead

**Comment by aviczhl2** [comment]
+3 USA-NY

**Comment by FedeGueli** [comment]
no recent samples closing it

**Comment by xz-keg** [comment]
designated KP.2.6.2
