### ISSUE TITLE
XBB.1.16 with S:E156Q (110 seqs, mainly in India, 13 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#182]
**Defining Mutations:** on top of XBB.1.16 polytomy > C18486T > G22028C (S:E156Q)
**Query:** A22101T, C18486T, G22028C
**Earliest seq:** 2023-03-07 [EPI_ISL_17326102, India]
**Latest seq:** 2023-05-30 [EPI_ISL_17787083, Ireland]
**Sampled Countries:** India (67, Assam/4, Chhattisgarh/1, Gujarat/55, Haryana/3, Maharashtra/2, Rajasthan/2), Australia (3, All NSW), Ireland (3), Japan (2), Thailand (2), Belgium (2), USA (2, Cali/1, NY/1), France (1), Netherlands (1)

<details><summary>Genomes: </summary>

No T23018C Dropout: (Catch by query: A22101T, C18486T, G22028C, T23018C)

EPI_ISL_17269953, EPI_ISL_17269957, EPI_ISL_17269984, EPI_ISL_17326102, EPI_ISL_17326115, EPI_ISL_17326198, EPI_ISL_17326310, EPI_ISL_17395880, EPI_ISL_17427689, EPI_ISL_17427762, EPI_ISL_17427771, EPI_ISL_17427808, EPI_ISL_17427811, EPI_ISL_17427859, EPI_ISL_17427976, EPI_ISL_17428063, EPI_ISL_17428064, EPI_ISL_17428142, EPI_ISL_17428247, EPI_ISL_17480206, EPI_ISL_17489964, EPI_ISL_17497105, EPI_ISL_17497144, EPI_ISL_17497145, EPI_ISL_17497175, EPI_ISL_17497203, EPI_ISL_17497212, EPI_ISL_17497322, EPI_ISL_17497346, EPI_ISL_17497348, EPI_ISL_17497357, EPI_ISL_17586336, EPI_ISL_17586351, EPI_ISL_17586386, EPI_ISL_17586566, EPI_ISL_17586898, EPI_ISL_17586903, EPI_ISL_17586905, EPI_ISL_17591400, EPI_ISL_17591417, EPI_ISL_17591627, EPI_ISL_17591711, EPI_ISL_17611225, EPI_ISL_17616043, EPI_ISL_17620256, EPI_ISL_17626951, EPI_ISL_17627094, EPI_ISL_17627279, EPI_ISL_17627280, EPI_ISL_17627286, EPI_ISL_17627288, EPI_ISL_17661798, EPI_ISL_17682539, EPI_ISL_17702745, EPI_ISL_17702759, EPI_ISL_17704207, EPI_ISL_17731846, EPI_ISL_17762265, EPI_ISL_17774380, EPI_ISL_17787081, EPI_ISL_17787083-17787084, EPI_ISL_17787285

Potential T23018C Dropout: (Catch by query: A22101T, C18486T, G22028C, -T23018C)

EPI_ISL_17269977, EPI_ISL_17427715, EPI_ISL_17427827, EPI_ISL_17434115, EPI_ISL_17434129, EPI_ISL_17517242, EPI_ISL_17586519, EPI_ISL_17586613, EPI_ISL_17586643, EPI_ISL_17586719, EPI_ISL_17586765, EPI_ISL_17586792, EPI_ISL_17586874, EPI_ISL_17586911, EPI_ISL_17586985, EPI_ISL_17663145, EPI_ISL_17683690, EPI_ISL_17731805, EPI_ISL_17731825, EPI_ISL_17764197

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_315ac_933ca0.json?f_userOrOld=uploaded%20sample

XBB.1.16 polytomy overview
![XBB 1 16+S_E156Q_Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bf4eca12-5ab6-4bda-8a75-9bb63ec3628e)

Details
![XBB 1 16+S_E156Q_Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b7fc152d-669a-4220-88ef-a0c839fc572c)

**Trivia:**
- G22028C (S:E156Q) only has 1136 sequences so far, last wave was driven by some undesignated BQ*. Got no idea what it does, but this seems to be one of the largest undesignated XBB.1.16 sub-branch.
- An XBB.1.16.1 branch G1535A(ORF1a:V424I), G22028C(S:E156Q) also has it with 10 seqs (query: G1535A, G22028C).
- A bit share of India's sequence have potential T23018C dropout (displayed as F486S), as listed above.

**Comment by FedeGueli** [comment]
Good catch, lets see how it evolves, hard to think it has any advantage in itself but looking at the tree there is some more spike mutations as 747I maybe something faster can come from one of them

**Comment by FedeGueli** [comment]
87 i still dont see recent samples. lets wait a bit more how it evolves

**Comment by FedeGueli** [comment]
Local cases in Singapore showing up, likely this should be proposed  lets put a 150 threeshold to see if it speeds u or slows down.

**Comment by FedeGueli** [comment]
How many samples from July 1 ahead?

**Comment by FedeGueli** [comment]
Please propose it.
