### ISSUE TITLE
XDV.1.1 ( T4579A , S:S60P)  with further S:H146Y, S:N185D (30 Taiwan Hubei Shanxi Hong Kong)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1820]
Credits : spotted and tracked first by @memorablea in https://github.com/Memorablea/COVID-19-/issues/102#issuecomment-2208210157

T4579A was the defining of FL.2 , now popped up and seems expanding recently on XDV.1 backbone and seems successful if compared with XDV.1 4579T.
<img width="847" alt="Screenshot 2024-08-03 alle 18 01 29" src="https://github.com/user-attachments/assets/910dd500-d5d8-49c3-bd05-333dbd377a2c">
it further gained a S:S60P sublineage convergently with JN.1 descendants.

Defining XDV.1 > T4579A > T9208G > S:S60P (T21740C) > Orf1a:R226K (G942A)> S:H146Y (C21998T) > S:N185D (A22115G)
Query for T4579A: T4579A, C1170T,C6501A,T22930A
Samples: 49, first collected on 2024-04-22 in Sichuan
Countries: 13
Query for S:S60P: T4579A,T9208G ,T21740
Samples: 17, first collected on 2024-04-27 in Yunnan
Countries: 6
Query for 60P + H146Y + N185D: T4579A, G942A, A22115G
Samples:7
Country: Hubei

Tree:
<img width="1174" alt="Screenshot 2024-08-03 alle 18 11 03" src="https://github.com/user-attachments/assets/07317f05-331d-4050-9161-a27498560292">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_383e7_e50380.json?f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
Big upload from three different regions of China 66/31

**Comment by FedeGueli** [comment]
+3 with 60P Gansu

This is really interesting cc @corneliusroemer

**Comment by aviczhl2** [comment]
Designated XDV.1.1 for the S60P branch

**Comment by Memorablea** [comment]
should add "partially designated"

**Comment by FedeGueli** [comment]
i will close this for now.

**Comment by FedeGueli** [comment]
XDV.1.1 is one of the fastest lineage circulating with a small disadvantage vs KP.3.1.1 , now the branch with 146Y and 185D reached 20. i m reopening it.

Another mini branch of XDV.1.1 has now acquired S:D420N query: G22820A , G942A,C1387T

**Comment by aviczhl2** [comment]
The S:H146Y,N185D branch seems to be spread all over Hubei in Xiaogan, Xiantao,Wuhan, Huangshi, Enshi, Jingzhou, Yichang, Qianjiang and Ezhou. It also spreads to Shanxi.

 It shall not be a cluster.

**Comment by FedeGueli** [comment]
+1 Hubei

**Comment by FedeGueli** [comment]
+1 HK

**Comment by FedeGueli** [comment]
no chance to compete closing this

**Comment by xz-keg** [comment]
+1 Taiwan

**Comment by FedeGueli** [comment]
> +1 Taiwan

super recent one, reopening for a while

**Comment by FedeGueli** [comment]
one only recent is not enough to keep this open

**Comment by FedeGueli** [comment]
new sample of XDV.1.1 from Gansu features 435S and 478E .Query for it: A5689G, A26591G ,G10997A,
