### ISSUE TITLE
XBB.1.33 saltation lineage with S:139-144del, S:Y453F, S:F486Srev, S:T500G, S:P681R and N:203-205del (4 sequences, Italy)

### ISSUE THREAD

**Issue by Clrs17** [sars-cov-2-variants/lineage-proposals#1821]
Some weird things to discover.
Sequences:
EPI_ISL_19297116
EPI_ISL_19075350
EPI_ISL_19243158
EPI_ISL_19243171

Shared mutation list:

> S:T19I, S:L24-, S:P25-, S:P26-, S:A27S, S:V83A, S:V90F, S:P139-, S:F140-, S:L141-, S:G142-, S:V143-, S:Y144-, S:Y145H, S:H146Q, S:Q183E, S:I210T, S:V213E, S:T250N, S:G252V, S:D294N, S:G339H, S:R346T, S:N354K, S:R357I, S:L368I, S:S371F, S:S373P, S:S375F, S:T385I, S:D405N, S:R408S, S:K417N, S:N440R, S:V445H, S:Y453F, S:N460K, S:L461I, S:S477N, S:T478K, S:E484A, S:F490S, S:Q498R, S:T500G, S:N501Y, S:Y505H, S:T572N, S:D614G, S:H655Y, S:N679K, S:P681R, S:N764K, S:D796Y, S:D936Y, S:Q954H, S:K964E, S:N969K

> ORF1a:K47R, ORF1a:H83F, ORF1a:V84L, ORF1a:M85Q, ORF1a:V86F, ORF1a:S135R, ORF1a:E233G, ORF1a:G645S, ORF1a:T842I, ORF1a:G1307S, ORF1a:S1372A, ORF1a:T1665I, ORF1a:I2230V, ORF1a:Q2486P, ORF1a:T2952V, ORF1a:L3027F, ORF1a:T3090I, ORF1a:L3201S, ORF1a:T3255I, ORF1a:P3395H, ORF1a:S3675-, ORF1a:G3676-, ORF1a:F3677-, ORF1a:R3802H, ORF1a:A4357T

> ORF1b:K82G, ORF1b:P314L, ORF1b:G662S, ORF1b:S959P, ORF1b:L1061I, ORF1b:R1315C, ORF1b:I1566V, ORF1b:T2163I

> E:T9I, E:T11A

> M:G6V, M:Q19E, M:A63T, M:H155N

> N:E31-, N:R32-, N:S33-, N:R203-, N:G204-, N:T205-, N:S206T, N:Q389H, N:S413R

> ORF3a:K21N, ORF3a:V55F, ORF3a:T217N, ORF3a:T223I

> ORF7a:L116F

Three of the sequences have an additional Spike NTD mutation S50L (convergent mutation in recent JN.1).
![image](https://github.com/user-attachments/assets/92f73914-093f-4ca6-b4f1-7df1920ac413)

**Comment by Clrs17** [comment]
Large NTD deletions have been reported in numerous lineages (e.g. BA.2.87.1) which are proven to boost immune escape (Wang, X., Jiang, S., Ma, W. et al. 2024). Y453F is a known mutation to enhance hACE2 binding affinity, and nucleocapsid mutation N:203-205del results in modification of B.1.1 defining mutation R203K+G204R.

**Comment by FedeGueli** [comment]
I think this has been tracked by @ryhisner

**Comment by ryhisner** [comment]
> I think this has been tracked by @ryhisner

Yeah, it's very likely the same patient, but only the most recent sequence has had any metadata, so there's no way to know for sure. It's unusual that there has been virtually no change in the sequence over a period of about 5 months. Normally you'd see quite a few changes over a time period that long in a chronic. 

Lots of interesting things happening in this one, including *four* 2-nuc mutations. But probably its most distinctive aspect is the deletion in a vital part of the SR-rich region. 

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/3b1c8c0a-2de7-41e5-b5e1-4ed1ec1b07aa">

I think the real deletion is probably ∆28881-28889. This probably had the A28877T + G28878C, the extended homology for the N* TRS. In any case, N* is erased because this completely deletes its TRS.

**Comment by FedeGueli** [comment]
> > I think this has been tracked by @ryhisner
> 
> Yeah, it's very likely the same patient, but only the most recent sequence has had any metadata, so there's no way to know for sure. It's unusual that there has been virtually no change in the sequence over a period of about 5 months. Normally you'd see quite a few changes over a time period that long in a chronic.
> 
> Lots of interesting things happening in this one, including _four_ 2-nuc mutations. But probably its most distinctive aspect is the deletion in a vital part of the SR-rich region.
> 
> <img alt="image" width="1370" src="https://private-user-images.githubusercontent.com/33738461/354948837-3b1c8c0a-2de7-41e5-b5e1-4ed1ec1b07aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDAyMzUsIm5iZiI6MTcyMjgzOTkzNSwicGF0aCI6Ii8zMzczODQ2MS8zNTQ5NDg4MzctM2IxYzhjMGEtMmRlNy00MWU1LWI1ZTEtNGVkMWVjMWIwN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA2Mzg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZTJhYzc4ZWM4NTFiMGViMzUxMGYyYWIwYzJhYzU2Mzg2MDM0OTA1YTMyZDhjN2I0MjVmNjc5Y2ZkYTJmYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nBD4ZNuLW55wWqhTuOBYrgqFKLp7hULsxcENCkI5pyY">
> I think the real deletion is probably ∆28881-28889. This probably had the A28877T + G28878C, the extended homology for the N* TRS. In any case, N* is erased because this completely deletes its TRS.
> 
> Below is my summary of the private mutations in the most recent sequence. Its identical to the other sequences except it lost S:S50L and gained ORF1a:K3353R.
> 
> <img alt="image" width="1458" src="https://private-user-images.githubusercontent.com/33738461/354949988-17a7c183-6ddf-4032-ba39-eff5085d895f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDAyMzUsIm5iZiI6MTcyMjgzOTkzNSwicGF0aCI6Ii8zMzczODQ2MS8zNTQ5NDk5ODgtMTdhN2MxODMtNmRkZi00MDMyLWJhMzktZWZmNTA4NWQ4OTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA2Mzg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNWZmNWRlMGU4N2ZkZTdlMmNlZWU5MmNlYjYzOGI0YmFhNzA0ZGMyMWU2ZTRjZGY1NDAwYTYwYjM1ZjRiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6qVRd2AdQAFM_byZVLrGRJdx0CTpRPwzOcSmLNxmQo">
Thx Ryan!
Did you try already to ask to Antonio Grimaldi of Tigem about this one?

One thing in your table i think it should be Orf1b:K82 not Orf1b:R82 or it was already mutated to R? Orf1b:K82R was in a sibling branch of AY.41 and AY.103 that never got designated  but was deadly in southern eastern Europe back in summer -fall 2021

**Comment by aviczhl2** [comment]
No new seqs
