### ISSUE TITLE
KP.2+S:F59L via T21739G(67 seqs, 9 countries)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1826]
S:F59L is usually achieved via T21737C, however, this branch gets it by T21739G.

KP.2+T6844C, C28603T+T21739G(S:F59L)

GISAID query: T6844C, C28603T, T21739G
No. of seqs: 41(Australia 1 Canada 6 UK 2 Germany 3 Italy 1 Spain 1 China 1 USA 26)

First: EPI_ISL_19176145, USA, 2024-5-12
Latest: EPI_ISL_19294127, USA, 2024-7-16

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice285_genome_test_8dde_f233b0.json?label=id:node_5501556)
![image](https://github.com/user-attachments/assets/43805c85-440e-4f1a-9eba-6291d70a8652)

**Comment by FedeGueli** [comment]
great catch

**Comment by FedeGueli** [comment]
ah i was tracking too with T6844C  ,T21739G, C28603T it is from Hawaii mostly, i think i ve found it back when analyzing that local KP.3.3 with two non spike mutations. I didnt notice the different nucs thing tough

**Comment by aviczhl2** [comment]
66, Portugal

**Comment by FedeGueli** [comment]
lets wait the next batch from Taiwan. is suspect it is dying off

**Comment by DailyCovidCases** [comment]
Likely dying off now
