### ISSUE TITLE
Potential KS.1.1/KP.3.3 recombinant(27 seqs, 7 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1827]
Mutations based on JN.1: C18657T, C19716T, C21627A, T21738C, T22928C, C23039G, G24872T, C25006T, C28291A, G28884C
The 5' donor could be from a pre-C6701T KS.1.1 branch with C18657T.
Breakpoint: 21738\~22599
Query: C18657T, C19716T, C25006T

Earliest sequence: 06-24 Berlin, Germany EPI_ISL_19283881
Latest sequence: 07-19 Berlin, Germany EPI_ISL_19300184
Regions detected: Germany 11, France 1, Netherlands 1, South Korea 1, UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_592af_f5e730.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/f6a87dd3-c912-4fa8-9cca-874503fd1e77)

Sequences:
EPI_ISL_19270230, EPI_ISL_19283843, EPI_ISL_19283881,
EPI_ISL_19283891, EPI_ISL_19283905, EPI_ISL_19288354,
EPI_ISL_19292873, EPI_ISL_19299882, EPI_ISL_19300184,
EPI_ISL_19304941, EPI_ISL_19308953, EPI_ISL_19308959,
EPI_ISL_19308971, EPI_ISL_19308982, EPI_ISL_19308990

**Comment by aviczhl2** [comment]
So this is KP.3.3+T22N,F59S?

**Comment by aviczhl2** [comment]
S:T22N is usually missed from sequencing. 
Use C19716T, G24872T, C25006T we can get an actual toll of 15.

**Comment by Over-There-Is** [comment]
S:22 seems getting affected by the insertion.
![image](https://github.com/user-attachments/assets/1a840cdd-afff-45a9-b2d1-f712eccfac22)

**Comment by JosetteSchoenma** [comment]
+3 in today's upload from the Netherlands.

**Comment by FedeGueli** [comment]
It seems fast.

**Comment by ryhisner** [comment]
> +3 in today's upload from the Netherlands. The now 4 Dutch samples are from 4 separate regions.

Also two from Sweden, three from the United States (Virginia), and one from Spain uploaded today. That's some really fast geographic spread.

**Comment by aviczhl2** [comment]
+2 GBW from Germany , 1 USA local and 1 from Sweden today.

**Comment by Over-There-Is** [comment]
Transferred to cov-lineages/pango-designation#2717.

**Comment by FedeGueli** [comment]
Designated XEC via https://github.com/cov-lineages/pango-designation/commit/c8b9d2ded49bf3d2870e94d1702046efeea8e533

**Comment by Over-There-Is** [comment]
Another XEC-liked recombinant:
Hubei/HCDC-JZ7482/2024|EPI_ISL_19529646|2024-10-22 Jingzhou, Hubei, China
KS.1.1.2+**A12627G**, C24463T / KP.3.3.1
C4927T, C6628T, _C6701T_, C7165T, G11335T, **A12627G**, _C19716T, C21627A, T21738C_ / _T22928C, C23039G, C23202A, G24872T, C25006T, T25652C, C25803T, C28291A, G28884C_

**Comment by FedeGueli** [comment]
> Another XEC-liked recombinant: Hubei/HCDC-JZ7482/2024|EPI_ISL_19529646|2024-10-22 Jingzhou, Hubei, China KS.1.1.2+**A12627G**, C24463T / KP.3.3.1 Breakpoint: 21738~22599 (same as XEC) JN.1+C4927T, C6628T, _C6701T_, C7165T, G11335T, **A12627G**, _C19716T, C21627A, T21738C_ / _T22928C, C23039G, C23202A, G24872T, C25006T, T25652C, C25803T, C28291A, G28884C_ aa mutations compared to XEC: Orf1a:-A599T, Orf1a:N4121S, S:T547K, Orf3a:F87S
> 
> As KS.1.1.2+A12627G, C24463T is detected in Hong Kong and KP.3.3.1 is circulating in whole China, I think this recombinant should be from some where in South China without (publicized) sequencing, e.g. Guangdong, Guangxi, Hunan or Jiangxi.

thx do you have a query for it please?

**Comment by Over-There-Is** [comment]
I think it'd be better to avoid private mutations: C6701T, A12627G, T25652C
