### ISSUE TITLE
KP.1.1.3 + S:F306L (40 seqs , 5 countries including Egypt) with a mini saltation singlet (8AA) with S:N185I and S:E471Q (20, Canada)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1828]
Just noticed a GBW sample from a traveller from Egypt carrying S:F306L , it turns out to be a small lineage already sampled in a few countries. Better proposing it although it should not be fast.
the S:304-309 area has been constantly on the move since XBB, when S:K304N appeared to be beneficial at least in some lineages (HF.1).
S:F306L was seen in at least one chronic patient (https://github.com/sars-cov-2-variants/lineage-proposals/issues/872) 
and it was defining of [B.1.1.523](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2103d_fa5a80.json?c=userOrOld&label=id:node_579816) a Russian lineage  that was one of the "VOC" Era lineages featuring  multiple Spike Mutations (211K,306L,484K,494P,780A,839V,1027I), Spike deletions (S:157-58del), a M Insertion (M:142ins) C22480Aand N mutations (N:G212C) that finished overlooked in comparison to other global lineages despite reaching 30% prevalence in Russia in early 2021.

But S:F306L corresponds to C22480 mutated to A,  and while S:F306L is quite anonymous , most of you will remember that **C22480T was one of the defining of EG.5.1***!

Defining mutations:
Kp.1.1.3 > Orf3a:I186V (A25948G)> Orf1a:T1638I (C5178T = PLPro_T75I)) > S:F306L (C22480A)
Query: C22480A,C5178T
Samples: 11
First sampled in Spain on 2024-05-24
Countries: Spain (7), France, Scotland, Egypt (via GBW)
Tree:
<img width="1160" alt="Screenshot 2024-08-04 alle 18 19 10" src="https://github.com/user-attachments/assets/e425dc99-cfdd-47c4-9ae0-34d616369aa6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice42_genome_test_439cf_f95950.json?c=gt-S_306&gmax=25384&gmin=21563&label=id:node_7065042

**Edited on October 16:**
A mini saltation appeared in this branch with spike mutations S:N185I, E471Q 
#1828 >> 
ORF1a:V274L (G1085T), Orf1a:N430S (A1554G), Orf1a:V438A (T1578C), C5884T, Orf1a:P4120S(C12623T), Orf1a:T4300V  (A13163G,C13164T), Orf1B:K82R  (A13712G), T16494C, S:N185I (A22116T), S:E471Q (G22973C), C23758T  

Putative query: A13163G,C13164T,A13712G
Places : Canada
Singlet
<img width="1159" alt="Screenshot 2024-10-16 alle 11 29 16" src="https://github.com/user-attachments/assets/0f28af3c-f556-49dc-9ba9-729563650bc6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_e159_f832a0.json?label=id:node_11704466

**Comment by FedeGueli** [comment]
+2

**Comment by FedeGueli** [comment]
+2 France

**Comment by Over-There-Is** [comment]
18 now, with a French sequence collected on 08-19

**Comment by FedeGueli** [comment]
Thx still very slow one.

**Comment by FedeGueli** [comment]
A mini saltation appeared in this branch with spike mutations S:N185I, E471Q 
#1828 >> 
ORF1a:V274L (G1085T), Orf1a:N430S (A1554G), Orf1a:V438A (T1578C), C5884T, Orf1a:P4120S(C12623T), Orf1a:T4300V  (A13163G,C13164T), Orf1B:K82R  (A13712G), T16494C, S:N185I (A22116T), S:E471Q (G22973C), C23758T  

Putative query: A13163G,C13164T,A13712G
Places : Canada
Singlet

**Comment by xz-keg** [comment]
18 seqs for the S:N185I, E471Q sub-branch.

**Comment by FedeGueli** [comment]
> 18 seqs for the S:N185I, E471Q sub-branch

Wow unexpected. It is a cluster ok, but being a saltation involved i put it under strict watch

**Comment by FedeGueli** [comment]
cc @ryhisner please could you look at non spike mutations here? there is a double nuc that appeared in a Kp.3.1.1 branch in Spain Orf1a:T4300V corresponding to NSP10_T47V.

**Comment by ryhisner** [comment]
> > 18 seqs for the S:N185I, E471Q sub-branch
> 
> Wow unexpected. It is a cluster ok, but being a saltation involved i put it under strict watch

I think Tom Peacock (no idea how to tag him here) once mentioned that some experiments had found that E471Q resulted in substantial rearrangement of spike. I'm not sure if it's published or not.

**Comment by FedeGueli** [comment]
cc @thomasppeacock

> I think Tom Peacock (no idea how to tag him here) once mentioned that some experiments had found that E471Q resulted in substantial rearrangement of spike. I'm not sure if it's published or not.

**Comment by DailyCovidCases** [comment]
@FedeGueli please propose this branch

**Comment by FedeGueli** [comment]
> @FedeGueli please propose this branch

Very likely being only a cluster,

**Comment by FedeGueli** [comment]
dead
