### ISSUE TITLE
JN.1.7 subbranch with S:F456L, Orf1a:I2010V, Orf7a:G26S on Orf1b:S1003G branch (16, 5 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1829]
JN.1.7> A16474G(Orf1b:S1003G)> A6293G(Orf1a:I2010V), T22928C(S:F456L), G27469A(Orf7a:G26S)
Query: A6293G, G27469A

Earliest sequence: 02-19 Maricopa, Arizona, USA EPI_ISL_18962183
Latest sequence: 06-26 Monroe, New York, USA EPI_ISL_19285145
Regions Detected: US 8, Canada 2, Ireland 1, UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1ee23_f9a9b0.json?c=country&label=id:node_7219828
![image](https://github.com/user-attachments/assets/3d6cc089-fa0b-47d0-ae7c-48ce40469020)

Sequences: 
EPI_ISL_18962183, EPI_ISL_19059137, EPI_ISL_19132016,
EPI_ISL_19134139, EPI_ISL_19158893, EPI_ISL_19163625,
EPI_ISL_19223358, EPI_ISL_19253501, EPI_ISL_19284991,
EPI_ISL_19284993, EPI_ISL_19284997, EPI_ISL_19285145

**Comment by FedeGueli** [comment]
Very weird it has been around for 4 months accumulating only a dozen of sequences while spreading in multiple countries.
It is one of that persistent lineages that quite misteriously being clearly slow still survive for a long period of time:
CM.7.1 in Europe/Israel or CM.8.1.1 in Utah, BQ.1.2.2 in Nigeria , XBC.1.3 in Australia, FR.1.1 in China , JB* in South Africa, XAY itself ( just the first examples but likely there are others)

**Comment by aviczhl2** [comment]
> Very weird it has been around for 4 months accumulating only a dozen of sequences while spreading in multiple countries. It is one of that persistent lineages that quite misteriously, despite being clearly slow, are still able to survive for a long period of time: CM.7.1 in Europe/Israel or CM.8.1.1 in Utah, BQ.1.2.2 in Nigeria , XBC.1.3 in Australia, FR.1.1 in China , JB* in South Africa, XAY itself ( just the first examples but likely there are others)

Refrigerated and spread via cargo ship?

**Comment by aviczhl2** [comment]
+2 Mexico

**Comment by aviczhl2** [comment]
No new seqs
