### ISSUE TITLE
LU.2 subbranch with S:Q677P, Orf1a:T1000I and Orf7b:F13L (9 seqs, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1830]
LU.2> C3264T(Orf1a:T1000I), A23592C(S:Q677P), T27794A(Orf7b:F13L)
Query: C3264T, A23592C, T27794A

Earliest sequence: 06-04 Puerto Rico, US EPI_ISL_19230395
Latest sequence: 07-12 Badajoz, Extremadura, Spain EPI_ISL_19291798
Regions Detected: US 4(Puerto Rico), Ecuador 3, Spain 1, UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_309cb_f93340.json?c=country&label=id:node_7074450
![image](https://github.com/user-attachments/assets/b049de55-5951-4fb0-97cb-f527c4747e91)

Sequences:
EPI_ISL_19211323, EPI_ISL_19230395, EPI_ISL_19262897,
EPI_ISL_19280736, EPI_ISL_19284532, EPI_ISL_19284613-19284614,
EPI_ISL_19287280, EPI_ISL_19291798

**Comment by FedeGueli** [comment]
no new sequences i tend to think this is dead closing for now. pls ping if it pops up again

**Comment by aviczhl2** [comment]
Designated LU.2.2
