### ISSUE TITLE
KP.4.2+S:S31del with S:R190S (13 seqs)

### ISSUE THREAD

**Issue by DailyCovidCases** [sars-cov-2-variants/lineage-proposals#1831]
From branch 21 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1502
KP.4.2+Orf1a:Q575R+S:S256L,S:S31del,
Query:del21653,A1989G,C6070T
No. of seqs: 13 (UK 1 USA 12)
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2bcc5_3b9d0.json)
![Screenshot (158)](https://github.com/user-attachments/assets/af9a838a-9d2a-4dbe-8206-43faa3a5a0f2)

**Comment by FedeGueli** [comment]
@DailyCovidCases you wrongoed the headline there is no C6020T branch, it is C6040T and C6070T.
Please answer this where did u find that C6020T? It is non existent. i will close this one.

cc @corneliusroemer @ryhisner

**Comment by aviczhl2** [comment]
And the seqs are not from USA.

**Comment by DailyCovidCases** [comment]
> @DailyCovidCases you wrongoed the headline there is no C6020T branch, it is C6040T and C6070T. Please answer this where did u find that C6020T? It is non existent. i will close this one.
> 
> cc @corneliusroemer @ryhisner

I somehow just typed it incorrectly, thanks
No automated tool was found

**Comment by FedeGueli** [comment]
> > @DailyCovidCases you wrongoed the headline there is no C6020T branch, it is C6040T and C6070T. Please answer this where did u find that C6020T? It is non existent. i will close this one.
> > cc @corneliusroemer @ryhisner
> 
> I somehow just typed it incorrectly, thanks No automated tool was found

Please look at the rules that have been ongoing here but i have explicited it again: https://github.com/sars-cov-2-variants/lineage-proposals/issues/1833 From now ahead everything that does not respect these rules will be closed and labeled con sequently

**Comment by DailyCovidCases** [comment]
Tracked in [branch21](https://cov-spectrum.org/explore/World/AllSamples/Y2024/variants?aaMutations=S%3AS31-&nucMutations=A1989G%2CC6070T&nextcladePangoLineage=KP.4.2*&)
