### ISSUE TITLE
JN.1.16 subbranch with S:R346T on Orf1a:W2769C branch(26 seqs, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1832]
JN.1.16> G8572T(Orf1a:W2769C)> A16770G> G22599C(S:R346T)
Query: G8572T, A16770G, G22599C

Earliest sequence: 05-19 Mexico City, Mexico EPI_ISL_19259364
Latest sequence: 08-15 Utah, USA EPI_ISL_19360404
Regions detected: US 12, Mexico 7, Japan 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_56a5a_42d20.json?c=country&label=id:node_7222338
![image](https://github.com/user-attachments/assets/2d7faece-8c49-4606-8cf9-0acb6eaf3c99)

Sequences:
EPI_ISL_19259318, EPI_ISL_19259320, EPI_ISL_19259357,
EPI_ISL_19259364, EPI_ISL_19260197, EPI_ISL_19269065,
EPI_ISL_19285021, EPI_ISL_19285025, EPI_ISL_19285060,
EPI_ISL_19285585, EPI_ISL_19304443, EPI_ISL_19326078,
EPI_ISL_19326097, EPI_ISL_19326118, EPI_ISL_19329309,
EPI_ISL_19336890, EPI_ISL_19337550, EPI_ISL_19337559,
EPI_ISL_19360316, EPI_ISL_19360404

**Comment by FedeGueli** [comment]
18 growing 2% in mexico after July 1

**Comment by Over-There-Is** [comment]
Utah +2

**Comment by aviczhl2** [comment]
26, sweden

**Comment by FedeGueli** [comment]
no recent samples closing it

**Comment by Over-There-Is** [comment]
Mexican old sequences +6
