### ISSUE TITLE
KP.2.3 + S:K478T (Rev) (110)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1834]
There seems to be a trend in reverting 478K to T in KP.2.3 ,
Usher actually put three branches together i m a bit skeptical they are one only one lineages.
But being mostly GBW samples from India and Middle East , where KP.2 FLiRT emerged first, i think it is worth tracking them.
Obviously to find a query with a reversion is a very hard job so i will set a general query toi catch all KP.2.3 + 478T sequences, plus three queries specific for the three main branches of the tree.
Query for all KP.2.3+ 478T: del21653, C22000A,G25593T, -22995A,-22995T,-22995G, C28714T Samples: 110
Query for Kp.2.3+ 478T>C28714T: del21653, C22000A,G25593T, -22995A,-22995T,-22995G, C28714T Samples: 78
Query for Kp.2.3+ 478T>C2232T: C2232T,del21653, C22000A,G25593T, -22995A Samples: 5
Query for Kp.2.3+ 478T>C4296T : del21653, C22000A,G25593T, -22995A

Apparent tree:
<img width="1157" alt="Screenshot 2024-08-05 alle 12 06 59" src="https://github.com/user-attachments/assets/3153add4-54bc-4f4c-83f5-648e9c332612">
<img width="1137" alt="Screenshot 2024-08-05 alle 12 07 11" src="https://github.com/user-attachments/assets/10b03c56-698c-4e99-93d7-b17d440b5023">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_9f8f_1e10.json?c=gt-S_478&f_userOrOld=uploaded%20sample&gmax=25384&gmin=21563&label=id:node_7055844

**Comment by aviczhl2** [comment]
How can we query exactly for seqs with 22995 being C on usher (not missing coverage)

**Comment by FedeGueli** [comment]
> How can we query exactly for seqs with 22995 being C on gisaid (not missing coverage)?

i m still trying to get that.

**Comment by aviczhl2** [comment]
> > How can we query exactly for seqs with 22995 being C on gisaid (not missing coverage)?
> 
> it should be -Spike_T478 8nextclading then for count manually the NNN and exclude them)

Query on cov-spectrum with S:478T, it has a few days delay.

**Comment by FedeGueli** [comment]
Not useful, just now the trend  toward 478rev is clear  for many lineages.

**Comment by xz-keg** [comment]
designated KP.2.3.10
