### ISSUE TITLE
KP.3.1.1 + S:N148T (82 >15 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1836]
Although it doesn't seem fast it is worth keeping an eye of it being S:N148T found in fast sublineages in the past (likely much less on JN.1 backbone)

KP.3.1.1 > S:N148T (A22005C) 
Query : A22005C,A13121T,T3565C,-C10681T
Samples: 82
First collected on 2024-06-13 in England
Countries: UK, US, Germany (via GBW),Australia,Brazil,Canada,Czech,Denmark,France,Japan,Italy,Slovenia,New Zealand,Netherlands,Poland,Portugal ,Singapore, South Korea
Hosts: Human, Tiger
Tree: updated on December 27
 <img width="1168" alt="Screenshot 2024-12-27 alle 13 27 28" src="https://github.com/user-attachments/assets/5933d775-0628-44c6-9556-250111a12312" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_5cbcd_e99ed0.json?c=country&label=id:node_7266438

**Comment by FedeGueli** [comment]
+1 Singapore

**Comment by FedeGueli** [comment]
+1 Germany

**Comment by FedeGueli** [comment]
+1 NZL

**Comment by FedeGueli** [comment]
slow closing this

**Comment by FedeGueli** [comment]
+2 Portugal,Soputh Korea. reopening this but it seems slow.

**Comment by Over-There-Is** [comment]
KR+3

**Comment by FedeGueli** [comment]
28, France

**Comment by FedeGueli** [comment]
31, Poland

**Comment by Over-There-Is** [comment]
33, Nordrhein-Westfalen

**Comment by aviczhl2** [comment]
Propose this?

**Comment by FedeGueli** [comment]
> Propose this?
Yeah likely it is worth
lets wait it touches 50, it doesn't seem very fast and it will be slowed by XEC rise .

**Comment by FedeGueli** [comment]
38 Poland
it will be proposed at 50 (if it gets there soon)

**Comment by FedeGueli** [comment]
39 , not sure if worth proposing, i ve brought it back to under review label

**Comment by xz-keg** [comment]
50 now

**Comment by DailyCovidCases** [comment]
Slowing down now

**Comment by FedeGueli** [comment]
> Slowing down now

it has never been fast. still interesting to watch.

**Comment by FedeGueli** [comment]
56 with recent samples from 3 continents ( Australia, Singapore, Denmark)

**Comment by FedeGueli** [comment]
82 now , interestingly it managed to infect a Tiger in Oregon in November (cc @ryhisner ).  reopen to check it a bit

**Comment by FedeGueli** [comment]
Scratch that . the query is no more working and the sample from the tiger appears to another 148T branch:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/singleSubtreeAuspice_genome_test_281f0_e9e290.json?f_userOrOld=uploaded%20sample&label=id:node_7260531
<img width="1162" alt="Screenshot 2024-12-27 alle 13 33 27" src="https://github.com/user-attachments/assets/2777772b-fbc5-4391-864c-355954a34aa3" />

<img width="1159" alt="Screenshot 2024-12-27 alle 13 34 00" src="https://github.com/user-attachments/assets/d089e22f-762c-48d5-968f-61b8f5a1ef33" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice3_genome_test_281f0_e9e290.json?label=id:node_11812583

**Comment by FedeGueli** [comment]
@
