### ISSUE TITLE
KP.2.2 subbranch with S:Q239R (52 seqs, US)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1837]
KP.2.2> C6525T(Orf1a:T2087I)> A22278G(S:Q239R)
Query: C6525T, A22278G

Earliest sequence: 05-15 Puerto Rico, USA EPI_ISL_19192978
Latest sequence: 07-25 Virginia, USA EPI_ISL_19298174
Regions detected: US 42(Puerto Rico 37, North Carolina 2, Ohio 1, South Carolina 1, Virginia 1)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_41c99_f5800.json?c=country&label=id:node_7059357
![image](https://github.com/user-attachments/assets/ddd01043-301d-4588-bae9-b5d8e1c48c9e)

<details><summary>Sequences: </summary>

EPI_ISL_19192978, EPI_ISL_19207888-19207897, EPI_ISL_19207902,
EPI_ISL_19207912, EPI_ISL_19207924-19207929, EPI_ISL_19214117,
EPI_ISL_19214188, EPI_ISL_19230396, EPI_ISL_19230439,
EPI_ISL_19230506, EPI_ISL_19250935, EPI_ISL_19268621,
EPI_ISL_19268627, EPI_ISL_19268716, EPI_ISL_19268719,
EPI_ISL_19268724, EPI_ISL_19268735-19268737, EPI_ISL_19268797,
EPI_ISL_19284655, EPI_ISL_19284660, EPI_ISL_19289461,
EPI_ISL_19298174, EPI_ISL_19301117, EPI_ISL_19314031,
EPI_ISL_19314064, EPI_ISL_19317348
</details>

**Comment by Over-There-Is** [comment]
PR+2, Virginia +1

**Comment by FedeGueli** [comment]
Only four samples in July closing this

**Comment by Over-There-Is** [comment]
Puerto Rico +3

**Comment by FedeGueli** [comment]
Still only 7 from July and mostly from early July.

**Comment by Over-There-Is** [comment]
46

**Comment by FedeGueli** [comment]
reopening due the sample from August

**Comment by FedeGueli** [comment]
52 but only one from August closing it
