### ISSUE TITLE
KP.something ( or likely KP.1.1.3/KP.3.1.1 recombinant?) + S:∆S31, R346T, Q493E, ORF6:L61I, N:R413L, C4999T (22 seqs, 3 countries)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1838]
**Description**
**Sub-lineage of:** KP.X (unclear, probably KP.1.1.3/KP.3.1.1 recomb)
**Earliest sequence:** 2024-7-9, USA, New York – EPI_ISL_19277804
**Most recent sequence:** 2024-9-9, USA, Utah – EPI_ISL_19433572
**Continents circulating:** North America (22), Europe (1)
**Countries circulating:** USA (19) Canada (3), England (1)
**Number of Sequences:** 23
**GISAID Nucleotide Query:** C4999T, G27382A, G29511T
**CovSpectrum Query:** Nextcladepangolineage:JN.1** & [4-of: S:S31del, C499T, G22599C, C23039G, C27382A, G29511T] 
**Substitutions on top of KP.X:**
**Spike:** ∆S31, R346T, Q493E
**N:** R413L
**ORF6:** L61I

**Nucleotide:** C4999T, ∆21653-21655, G22599C, C23039G, C27382A, G29511T

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_974b_1803c0.json?c=gt-ORF6_61&gmax=27387&gmin=27202&label=id:node_7038322
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/24610f1f-53c9-4064-80ce-5c53127ca768">

**Evidence**
EDIT: apparently a recombinant most likely. Not sure it matters as this thing seems likely to go extinct any day now.

It's not clear to me which KP* lineage this belongs to. It has S:∆S31 and S:Q493E but not ORF1a:S4286C. It also has S:R346T, which is rare in KP.3. 

It has S:∆S31, S:R346T, and C4999T, which are all in KP.1.1.3, but it does not have S:K1086R. 

It also has two mutations found in very few JN.1* sequences over the past 2-3 months—ORF6:L61I (C27382A) and N:R413L (G29511T). Usher puts it in an artifactual branch full of environmental samples from Germany. 

Nextclade calls it KP.2, but that seems wrong. Seems it could very well have emerged from the KP* polytomy.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19277804, EPI_ISL_19311262, EPI_ISL_19312228,
EPI_ISL_19317065, EPI_ISL_19321574, EPI_ISL_19330042,
EPI_ISL_19340296, EPI_ISL_19343129, EPI_ISL_19343224,
EPI_ISL_19344062, EPI_ISL_19358024, EPI_ISL_19358663,
EPI_ISL_19360364, EPI_ISL_19362073, EPI_ISL_19376515,
EPI_ISL_19377374, EPI_ISL_19408485, EPI_ISL_19416777,
EPI_ISL_19416949, EPI_ISL_19420047, EPI_ISL_19425340,
EPI_ISL_19428039, EPI_ISL_19433572
</details>

**Comment by aviczhl2** [comment]
Likely KP.1.1.3/KP.3 recomb?

**Comment by aviczhl2** [comment]
C4999T seems not a convergent mutation, and it shares S:S31del and S:R346T,  so it must come from KP.1.1.3 before S:493. 

Lack of S:K1086R signifies it must be recomb, presence of V1104L means it recombs with KP.*
 Q493E suggests the recomb is likely from KP.3 
Both C27382A and G29511T appears in multiple KP.3 lineages, most likely KP.3.1.1 but others are also possible.

**Comment by FedeGueli** [comment]
> C4999T seems not a convergent mutation, and it shares S:S31del and S:R346T, so it must come from KP.1.1.3 before S:493.
> 
> Lack of S:K1086R signifies it must be recomb, presence of V1104L means it recombs with KP.* Q493E suggests the recomb is likely from KP.3 Both C27382A and G29511T appears in multiple KP.3 lineages, most likely KP.3.1.1 but others are also possible.

agree

**Comment by aviczhl2** [comment]
C4999T seems not that unique in KP* backbone. At least 100 non-KP.1.1.3 seqs have C4999T, many under KP.3. 

But I still think this one is better explained as recombination as recomb explains 4 mutations, C4999T, S:S31del, S:R346T and one of 27832 and 29511.

**Comment by FedeGueli** [comment]
+1 NJ

**Comment by aviczhl2** [comment]
There's one more of this.

**Comment by aviczhl2** [comment]
7th seq from Connecticut

**Comment by aviczhl2** [comment]
+3 from OR,LA and UT

**Comment by FedeGueli** [comment]
Impressive being from 7 different American States in such a short time.

**Comment by FedeGueli** [comment]
Please propose it i think @corneliusroemer as usual for recombinants could grant a rapid designation.

**Comment by FedeGueli** [comment]
13 @ryhisner please propose it

**Comment by aviczhl2** [comment]
Another sample from AZ(new state)

**Comment by aviczhl2** [comment]
+2, total 16 now.

**Comment by ryhisner** [comment]
I think this is very nearly dead. If it picks up again, I'll move it to the Pango page. Seems unlikely though.

**Comment by FedeGueli** [comment]
> I think this is very nearly dead. If it picks up again, I'll move it to the Pango page. Seems unlikely though.

mm Ryan in August it has been sampled in multiple american states and Ontario i would keep this open for a while more.

**Comment by DailyCovidCases** [comment]
I think this is nearly dead, so please close this issue

**Comment by FedeGueli** [comment]
> I think this is nearly dead, so please close this issue

6/17 in August not dead

**Comment by aviczhl2** [comment]
+3 USA

**Comment by aviczhl2** [comment]
There exists a seq EPI_ISL_19353736 from Chile that have KP.1.1.3/KP.3 recomb thing(or KP.1.1.3+S:Q493E thing) but not the 2 private mutations of G27382A, G29511T, that seq may be the origin of this.

**Comment by aviczhl2** [comment]
There's one more seq from the original recomb branch. 

![image](https://github.com/user-attachments/assets/b6a0b26a-62e2-43c7-a768-1866a510b5ee)


Query: C4999T, del21653, C23039G,G22599C,-24819 , gets 24 seqs. And  C4999T, G27382A, G29511T,-del21653 gets 1 additional, so total shall be 25 seqs.

**Comment by FedeGueli** [comment]
@ryhisner please propose it.

**Comment by aviczhl2** [comment]
26 now for the KP.1.1.3/KP.3 recomb.

**Comment by FedeGueli** [comment]
This has a sibling recombinant branch now:
<img width="1172" alt="Screenshot 2024-09-28 alle 14 09 12" src="https://github.com/user-attachments/assets/44c6bb8d-a5b8-4e9e-9789-89e7a2b4af77">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice32_genome_test_170b5_7ac5e0.json?label=id:node_11672991

**Comment by aviczhl2** [comment]
> This has a sibling recombinant branch now: <img alt="Screenshot 2024-09-28 alle 14 09 12" width="1172" src="https://private-user-images.githubusercontent.com/87669813/371756288-44c6bb8d-a5b8-4e9e-9789-89e7a2b4af77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjYwMTcsIm5iZiI6MTcyNzUyNTcxNywicGF0aCI6Ii84NzY2OTgxMy8zNzE3NTYyODgtNDRjNmJiOGQtYTViOC00ZTllLTk3ODktODllN2EyYjRhZjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEyMTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZWNhZGE1YWFkNDI5ZTZiZTY0NDEwMjdhMTA1NTlhMTViY2ZiNzY3NGVlMWMwMzgyZWY4OTMzODcxZWZhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RXSUq984OPnwAEqPOUkRo3wAuPPQ5fUKw0AYwius6zg"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice32_genome_test_170b5_7ac5e0.json?label=id:node_11672991

It shall be another branch of the same KP.1.1.3/KP.3 recombinant, given G27382A, G29511T are private mutations? 

 Or do they have different parents?

**Comment by FedeGueli** [comment]
> Or do they have different parents?

it seems to me they are different ( two branches of KP.1.1.3 and MC.1), please check on the proposed issue: https://github.com/sars-cov-2-variants/lineage-proposals/issues/2103

**Comment by aviczhl2** [comment]
> > Or do they have different parents?
> 
> it seems to me they are different ( two branches of KP.1.1.3 and MC.1), please check on the proposed issue: #2103 this one (the one spotted by me) lacks G27382A and the other pvt so i dont think they can be the same or related

sure, so let's limit this proposal to the top branch only.

**Comment by FedeGueli** [comment]
> > > Or do they have different parents?
> > 
> > 
> > it seems to me they are different ( two branches of KP.1.1.3 and MC.1), please check on the proposed issue: #2103 this one (the one spotted by me) lacks G27382A and the other pvt so i dont think they can be the same or related
> 
> sure, so let's limit this proposal to the top branch only.

yeah i just highlighted here that another recomb appeared in this tre ;) not meant to enlarge this . After analyzing it i thought it wa worth a separate issue and not just a mention here or in the recomb issue. that is

**Comment by corneliusroemer** [comment]
Designated XEH
