### ISSUE TITLE
KP.3.1+S:477K (2 sequences, USA)

### ISSUE THREAD

**Issue by Clrs17** [sars-cov-2-variants/lineage-proposals#1842]
KP.3.1+C22993A, A14319G
GISAID query: C22993A,A14319G
sequences:
EPI_ISL_19263860
EPI_ISL_19301766
![image](https://github.com/user-attachments/assets/07d1f659-6e1f-4e51-9938-471602084136)

**Comment by FedeGueli** [comment]
i think @nkmnzr spotted this too. it seems dead tough

**Comment by FedeGueli** [comment]
dead
