### ISSUE TITLE
KP.2.3+S:A1174V (103 seqs, 15 countries) >10% in Brazil in August (3 States)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1843]
KP.2.3(with 31del)+C28714T+C11518T+C25083T(S:A1174V)

GISAID query: C28714T, C11518T, C25083T
No. of seqs: 53(Belgium 1 Brazil 4 Canada 1 Denmark 1 UK 5 France 4 Ireland 3 Italy 3 Netherlands 4 Spain 15 Sweden 2 USA 10(1 from Greece 1 from Spain 2 from Japan)

First: EPI_ISL_19276081, France, 2024-5-14
Latest: EPI_ISL_19312022, Spain, 2024-7-30

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice134_genome_test_19505_2cfd50.json?label=id:node_5484209)
![image](https://github.com/user-attachments/assets/7535b679-e005-42f5-ae13-066fdb235043)

**Comment by FedeGueli** [comment]
+2 one with S:I726V that in the past was in a XBL.3 sublineage

**Comment by Over-There-Is** [comment]
82

**Comment by FedeGueli** [comment]
103 with a big batch from Bahia,Brazil today i would propose it.

**Comment by FedeGueli** [comment]
KP.2.3.12 via https://github.com/cov-lineages/pango-designation/commit/5021628bcc00476e95cf370cbf5ba9e759b99def

**Comment by FedeGueli** [comment]
KP.2.3.12 represents still around 8-10% of samples from Brazil in December.
And it displays a notable spike diversity:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2cbe98_f589e0.json?branchLabel=Spike%20mutations&f_userOrOld=uploaded%20sample&label=id:node_7416903
<img width="1170" alt="Image" src="https://github.com/user-attachments/assets/8e70c249-17bd-4e5c-b1c1-1ffde8b468d9" />

Among them 
i would monitor 
S:435S+899S + Orf1b:D1735E
Query: T18672A,G22865T, G24257T
Samples: 2

S:A435S + N:A35V + Orf1b:V345L
Query: G14500T, G22865T, C28377T
Samples: 1

S:R190S + N:K62I/Orf9b:N62Y + Orf1a:V4216I 
Query: TG12911A, G17418A, G22132T
Samples: 1

S:V1264L
Query: T15597C, C19983T, G25352C
Samples: 9

S:G181A+S:T572I
Query: , G22104C ,C23277T, C28748T
Samples: 1

**Comment by krosa1910** [comment]
@FedeGueli The 435S+899S+Orf1b:D1735E branch seems to grow significantly, the upload in 02-05 uploads adds 4 to them. Should I open a new issue for this?

<img width="906" alt="Image" src="https://github.com/user-attachments/assets/411f3bc7-e11e-4626-a13a-6d9797f41416" />

**Comment by FedeGueli** [comment]
> [@FedeGueli](https://github.com/FedeGueli) The 435S+899S+Orf1b:D1735E branch seems to grow significantly, the upload in 02-05 uploads adds 4 to them. Should I open a new issue for this?
> 
> <img alt="Image" width="906" src="https://private-user-images.githubusercontent.com/131021067/412314589-411f3bc7-e11e-4626-a13a-6d9797f41416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzNDk5MTYsIm5iZiI6MTczOTM0OTYxNiwicGF0aCI6Ii8xMzEwMjEwNjcvNDEyMzE0NTg5LTQxMWYzYmM3LWUxMWUtNDYyNi1hMTNhLTZkOTc5N2Y0MTQxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMlQwODQwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWNhYjllMWFjYzViNzAxNWExYWEwZTAzMWEzNTRlYTkyZDMxNDA3OGRhMjE2MDliYjMzMmU4OGExODU0MWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rpOvXG7U7zpFNPwgZj0Py6abnN7d_IZPIsNlWjQSIRc">

yes please.

**Comment by FedeGueli** [comment]
more divrsity but not super recent : S:S446I or S:R102G
