### ISSUE TITLE
KP.2.3+S:478E (6 sequences, 5 countries)

### ISSUE THREAD

**Issue by Clrs17** [sars-cov-2-variants/lineage-proposals#1844]
KP.2.3+A22994G (S:T478K>E)
Sequences:
EPI_ISL_19182695
EPI_ISL_19215496
EPI_ISL_19293889
GISAID query: A22994G, C28714T
![image](https://github.com/user-attachments/assets/d9e1ffdd-c4a4-4725-aeb9-ff1304c4b4b2)

**Comment by FedeGueli** [comment]
6 from three more countries please check if the query still catches one only sublineage.

**Comment by aviczhl2** [comment]
No new seqs
