### ISSUE TITLE
KP.3.1.1+Orf1a:T1854I, S2661F, S:G181V (40 seqs, 13 countries)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1846]
KP.3.1.1+C5826T(Orf1a:T1854I)+C8247T, G22104T(Orf1a:S2661F, S:G181V)

GISAID query: C5826T, C8247T, G22104T
No. of seqs: 16(France 1 Germany 2 Luxembourg 2 Spain 1 Sweden 1 USA 8(2 from Portugal))

First:EPI_ISL_19195753, USA from Portugal, 2024-6-2
Latest: EPI_ISL_19310604, Sweden, 2024-7-21

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice17_genome_test_1f890_2e4530.json?label=id:node_5513875)
![image](https://github.com/user-attachments/assets/87882ce9-59e9-40c0-b97c-12da7e270d93)

**Comment by aviczhl2** [comment]
21,Belgium, Netherlands

**Comment by aviczhl2** [comment]
23,UK

**Comment by FedeGueli** [comment]
25 Austria, it seems slow though

**Comment by aviczhl2** [comment]
30, New Zealand

**Comment by aviczhl2** [comment]
+1 Poland

**Comment by FedeGueli** [comment]
no new sample coming closing this

**Comment by Over-There-Is** [comment]
38 luxembourg & belgium

**Comment by FedeGueli** [comment]
Reopening it due t recent samples but it looks like to be quite slow.

**Comment by FedeGueli** [comment]
Dying

**Comment by FedeGueli** [comment]
There is another Kp.3.1.1 circulating that recently got S:E654K in UK ( according to the always useful Dave McNally tooL)

<img width="1165" alt="Screenshot 2024-12-27 alle 13 18 37" src="https://github.com/user-attachments/assets/58c20771-55ca-448f-a9dd-9755da7340c3" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_5a79f_e99c60.json?c=userOrOld&label=id:node_7290757
