### ISSUE TITLE
XDV.1.10 + S:K478Q  (44, Hubei  )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1849]
XDV.1 + S:G181V was first spotted and tracked by @memorablea in https://github.com/Memorablea/COVID-19-/issues/102#issuecomment-2208220006

XDV.1.10 [ C9365T > orf1a:T4175I (C12789T), A28870T, G29254A > S:G181V (G22104T), C25782T] > C17550T, S:T>K478Q (A22994C), C29614T
Query:  C25782T , C17550T,  C9365T
Samples: 33 
Countries: Hubei (China)

Tree updated on September 10:
<img width="1164" alt="Screenshot 2024-09-09 alle 19 40 43" src="https://github.com/user-attachments/assets/e6987ed8-5e88-47a8-af29-0dfa2354cbfa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_426d3_f31000.json?c=userOrOld&label=id:node_7172854

Little cluster of two sequences with further S:G232V that was rare in the Pandemic (around 250 seqs) with just a B.1.1.7 sublineage reaching around 70 seqs.
Query:  , C17550T, C9365T,G22257T 
Samples: 2

**Comment by aviczhl2** [comment]
Parent is  XDV.1.10

**Comment by aviczhl2** [comment]
No new seqs from this particular branch.

**Comment by FedeGueli** [comment]
big upload from Hubei it is now 33. Locally the 478Q branch is doing well representing alone 4% of samples in Hubai after Aug 15

**Comment by FedeGueli** [comment]
it seems exclusively Hubei , so a local lineage. closing for now.

**Comment by FedeGueli** [comment]
+1 Hubei
