### ISSUE TITLE
FY.4.1 (S:451H,494P)  may have gained S:S514F ( 2 samples from England)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#185]
I just noticed that two recent samples from England have gained further S:S514F , note that Kenyan samples usually have dropout there.
It is likely  that this mutation emerged in local circualtion in Uk cause it clusters with other older samples from Uk
, but still worth to look at it cause  it would mean a triple RBD mutation 451-494-514 

Tree:
![Schermata 2023-06-14 alle 13 04 25](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d46a6d53-8ec0-46c0-b4c9-3905ab761e49)
![Schermata 2023-06-14 alle 13 04 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d6505f8d-9b6a-4678-a266-c654e599b414)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42cef_99e120.json?label=id:node_6642635

Defining mutations:
FY.4.1>>> Orf1a:S2926F (C9042T = NSP4_S163F)> Orf1b:K2557R (A21137G = NSP16_K160R), C23638T, T24091C > S:S514F (C23103T)

Gisaid query: C23638T, T24091C, C23103T

Samples: EPI_ISL_17762656, EPI_ISL_17786794

**Comment by HynnSpylor** [comment]
Good catch! despite the evolution of XBB.1.22.1* lineages are slightly fast, the RBD mutation is relatively rare (only S:S494P on FY.4.1) 
Let's track it for a time

**Comment by FedeGueli** [comment]
Thx @HynnSpylor i didnt notice that but true!

**Comment by FedeGueli** [comment]
No new sequence from this one.
