### ISSUE TITLE
JN.1.4.5 subbranch with S:S31F, R346T, F456L being misplaced (36 seqs, 10 regions) and further S:T22N(17, 9) then S:K478Trev(7, 4), mainly in Yunnan and Thailand

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1851]
## JN.1.4.5+S:S31F, R346T, F456L on C28948T branch
JN.1.4.5> C28948T(Orf9c:T72I)> C21654T(S:S31F), G22599C(S:R346T), T22928C(S:F456L)> A4872G(Orf1a:Y1536C), C21627A(S:T22N)> A22995Crev(S:K478Trev)
It's placed on a JN.1.4> C5284T> T22928C> G22599C> T5284Crev branch with XED now.
S:T22N and S:K478Trev branch is found by @xz-keg .

Query: C774T, G22599C, T22928C, C28948T (19)
Query for dropout sequences: C21627A, C28948T, -C22995A, -T22928C (2)
Query for S:T22N branch: A4872G, C21627A (10)
Query for S:K478T rev branch: A4872G, C21627A, -C22995 (4)
Query for dropout sequences: C21627A, C28948T, -C22995A, -T22928C, -A4872G (1)

Earliest sequence: 05-06 Krabi, Thailand EPI_ISL_19175337
Latest sequence: 11-15 Bangkok, Thailand EPI_ISL_19573081
Regions Detected: 
Thailand 8, China 4(Mainland 3; Taiwan 1, imported from unknown), Singapore 2, Japan 1(from Thailand), Korea 1;
France 2, Denmark 1 Ireland 1, Netherlands 1.

A Singaporean sequence has no S:S31F. But S:24-26 deletion is not detected in this sequence, so it's believable that there is a dropped-out S:S31F.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_378d_bd8870.json?c=country&label=id:node_7098067
![image](https://github.com/user-attachments/assets/54b976c8-b94d-4ded-bdd2-9f1ff5d26d44)

Sequences:
EPI_ISL_19175337, EPI_ISL_19175346, EPI_ISL_19175349,
EPI_ISL_19180980, EPI_ISL_19220434, EPI_ISL_19242375,
EPI_ISL_19242475, EPI_ISL_19242480, EPI_ISL_19285716,
EPI_ISL_19291460, EPI_ISL_19340768, EPI_ISL_19372385,
EPI_ISL_19388703, EPI_ISL_19444197, EPI_ISL_19444207,
EPI_ISL_19462030, EPI_ISL_19501913, EPI_ISL_19563652,
EPI_ISL_19573049, EPI_ISL_19573051, EPI_ISL_19573081,

## Another branch in original proposal(not growing): JN.1.4.5+S:F59S, R346T, F456L
JN.1.4.5> C10519T, G11389A, A13901G(Orf1b:D145G), T18125C(Orf1b:V1553A), A21231T, T21738C(S:F59S), G22599C(S:R346T), T22928C(S:F456L), C29358T
It's placed on JN.1.18.6 now.

Query: G11389A, A13901G

Earliest sequence: 05-22 Metz, Grand Est, France EPI_ISL_19189761
Latest sequence: 06-26 Luxembourg EPI_ISL_19306808
Regions detected: Luxembourg 4, France 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_4e302_4618f0.json?c=country&f_userOrOld=GISAID%20and/or%20public&label=id:node_7247062
![image](https://github.com/user-attachments/assets/b541ffa5-8e36-4a2a-8b39-e760910e6fb0)

Sequences:
EPI_ISL_19189761, EPI_ISL_19306808, EPI_ISL_19306824,
EPI_ISL_19306916, EPI_ISL_19306926

**Comment by FedeGueli** [comment]
Br.2 could not be a recombinant with one of the JN.1.18 +59S branches?

**Comment by FedeGueli** [comment]
Br.1 now 11
Br,2 dead

**Comment by FedeGueli** [comment]
Both dead or Dying

**Comment by xz-keg** [comment]
Branch 1 seems to get S:T22N and S:K478T rev in Thailand @FedeGueli

**Comment by xz-keg** [comment]
Suggest to change the proposal (or make a new one) specified on B1-S31F+T22N branch.

**Comment by FedeGueli** [comment]
> Suggest to change the proposal (or make a new one) specified on B1-S31F+T22N branch.

@Over-There-Is propose Branch 1 in the main page with the specific sublineage found by @xz-keg

**Comment by FedeGueli** [comment]
> > Suggest to change the proposal (or make a new one) specified on B1-S31F+T22N branch.
> 
> @Over-There-Is propose Branch 1 in the main page with the specific sublineage found by @xz-keg please
> 
> Query: A4872G ,C21627A Tree: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1bdbd_4eb600.json?f_userOrOld=uploaded%20sample&label=id:node_7086363

this 22N 31F branch went up to 7 with a recent Irish sample

**Comment by xz-keg** [comment]
> A4872G ,C21627A

10 now for this T22N, and 4 with S:K478T rev

**Comment by Over-There-Is** [comment]
> Suggest to change the proposal (or make a new one) specified on B1-S31F+T22N branch.

I didn't saw this. sorry.

**Comment by Over-There-Is** [comment]
Updated, please reopen it

**Comment by FedeGueli** [comment]
Big upload from Yunnan old ones though. It is interesting it emerged  between Thailand and Yunnan, the motherland of Sarbecoviruses

**Comment by xz-keg** [comment]
I think this one worth proposal @FedeGueli

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation#2843
