### ISSUE TITLE
LB.1 (JN.1.9.2.1) with ORF1a:M2606I (nsp3_M1788I ) S:T240I and S:T478R (61 seqs, 3+1 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1852]
**Defining Mutations:** `LB.1` > `G8083A(ORF1a:M2606I), C22281T(S:T240I), C22995G(S:T478R)`
**Query:** `G8083A, C22281T, C22995G`
**Earliest seq:** 24-05-24 (`EPI_ISL_19188794`, Texas, USA)
**Latest seq:** 24-07-21 (`EPI_ISL_19318292`, British Columbia, Canada)
**Sampled Countries:** Canada (10: BC), USA (7: TX/6; NE/1), Mexico (1: CMX)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/BC-BCCDC-722475/2024
Canada/BC-BCCDC-723309/2024
Canada/BC-BCCDC-723310/2024
Canada/BC-BCCDC-723311/2024
Canada/BC-BCCDC-723333/2024
Canada/BC-BCCDC-723351/2024
Canada/BC-BCCDC-723358/2024
Canada/BC-BCCDC-723359/2024
Canada/BC-BCCDC-723360/2024
Canada/BC-BCCDC-723361/2024
Mexico/CMX-INER-INMEGEN-3031/2024
USA/NE-NM_L379194558/2024
USA/TX-DSHS-26564/2024
USA/TX-HMH-M-141249/2024
USA/TX-HMH-M-141305/2024
USA/TX-HMH-M-142191/2024
USA/TX-HMH-M-142592/2024
USA/TX-UHS-UTHSA11355-P0/2024
```

epi_isl accessions:
`EPI_ISL_19188794, EPI_ISL_19259328, EPI_ISL_19286685, EPI_ISL_19294017, EPI_ISL_19295175, EPI_ISL_19298808, EPI_ISL_19306296, EPI_ISL_19317839, EPI_ISL_19318158, EPI_ISL_19318241-19318243, EPI_ISL_19318263, EPI_ISL_19318279, EPI_ISL_19318289-19318292`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f519_56a3b0.json
![image](https://github.com/user-attachments/assets/8401a253-622d-4de1-9f72-8ea1ebde09e6)

**Comment by FedeGueli** [comment]
34

**Comment by aviczhl2** [comment]
40, 3 new GBW-BBB from 1 Japan and 2 Mexico

**Comment by FedeGueli** [comment]
PLpro goes only from NSP3_745 to NSP3_1060 so i ve edited the title. it is from Orf1a:1563 to Orf1a:1878.
i ask for confirmation to @ryhisner and @alurqu about where it exactly ends while i m quite sure the starting point is correct

**Comment by alurqu** [comment]
From Ullrich and Nitsche [SARS‐CoV‐2 Papain‐Like Protease: Structure, Function and Inhibition](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9538446/), "PLpro is located on residues 746–1060 of nsp3". 745 is the offset to add or subtract when moving between PLpro and NSP3 coordinates. In ORF1a, referenced in Ullrich and Nitsche as pp1ab, PLpro is 1564-1878 and 1563 is the offset to add or substract when moving between PLpro and ORF1a/pp1ab coordinates.

**Comment by FedeGueli** [comment]
> From Ullrich and Nitsche [SARS‐CoV‐2 Papain‐Like Protease: Structure, Function and Inhibition](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9538446/), "PLpro is located on residues 746–1060 of nsp3". 745 is the offset to add or subtract when moving between PLpro and NSP3 coordinates. In ORF1a, referenced in Ullrich and Nitsche as pp1ab, PLpro is 1564-1878 and 1563 is the offset to add or substract when moving between PLpro and ORF1a/pp1ab coordinates.

Thank you! sure i messed the explanation! thank you for the correction.

**Comment by ryhisner** [comment]
This is the diagram from the study "NSP3: The Swiss army knife of SARS CoV 2—The Structures & Functions of NSP3" that I keep handy.
![image](https://github.com/user-attachments/assets/b1ebe556-1bd9-4895-b54b-0d45f393a089)

**Comment by FedeGueli** [comment]
> This is the diagram from the study "NSP3: The Swiss army knife of SARS CoV 2—The Structures & Functions of NSP3" that I keep handy. ![image](https://private-user-images.githubusercontent.com/33738461/365472762-b1ebe556-1bd9-4895-b54b-0d45f393a089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODA5NzEsIm5iZiI6MTcyNTg4MDY3MSwicGF0aCI6Ii8zMzczODQ2MS8zNjU0NzI3NjItYjFlYmU1NTYtMWJkOS00ODk1LWI1NGItMGQ0NWYzOTNhMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDExMTc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTg5YWNmY2NlN2FmM2ZhYzkyMDdiNzgxYjVjMTY3NGUyYTkyYWY1Mjk1NDZiNDc4MWQzMjI0YjFmMjU5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVUeoXpYreXpbaJ00g0fhFJyPiRqHp6-FdUd4ezH8do)

thank you Ryan! since it is now paywalled i couldnt check it but it is the source of our PLPro mutations displayed here and in pango issues.

**Comment by FedeGueli** [comment]
59

**Comment by FedeGueli** [comment]
Please propose it

**Comment by Over-There-Is** [comment]
76
