### ISSUE TITLE
KP.3.1 subbranch with S:N185D and Orf1a:V3917I (99, 7 countries, Mainly in US)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1853]
KP.3.1> G12014A(ORf1a:V3917I)> A22115G(S:N185D)

Query: G12014A, G15372T, A22115G
Query for sequences with S:N185D dropped out: C2061T, G12014A, G15372T, -A22115G

Earliest sequence: 04-08 Illinois, USA EPI_ISL_19070161
Earliest sequence(without S:N185D): 03-27 Santa Clara, California, USA EPI_ISL_19145504
Latest sequence: 07-22 Maryland, USA EPI_ISL_19298224
Regions Detected: US 47, Canada 2, Belgium 1, Denmark 1, France 1, Netherlands 1, Spain 1

EPI_ISL_19214043, EPI_ISL_19214047 and EPI_ISL_19293512 share C2061T and A17697G with other sequences, and have no coverage on S:185. But it's still not sure that if EPI_ISL_19143101 and EPI_ISL_19145504 have S:N185D or not. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_65088_4a2f00.json?gt=nuc.1314C&label=id:node_7028151
![image](https://github.com/user-attachments/assets/990310c1-6752-442c-abb7-7352481a3c3d)

<details><summary>Sequences:</summary>

EPI_ISL_19070161, EPI_ISL_19116334, EPI_ISL_19143101,
EPI_ISL_19145504, EPI_ISL_19155522, EPI_ISL_19188485,
EPI_ISL_19197416, EPI_ISL_19205513, EPI_ISL_19214043,
EPI_ISL_19214047, EPI_ISL_19216229, EPI_ISL_19223749,
EPI_ISL_19224132, EPI_ISL_19224161, EPI_ISL_19232929,
EPI_ISL_19245476, EPI_ISL_19245500, EPI_ISL_19257071,
EPI_ISL_19258111, EPI_ISL_19261840, EPI_ISL_19262350,
EPI_ISL_19265594, EPI_ISL_19273183, EPI_ISL_19281413,
EPI_ISL_19285254, EPI_ISL_19285928, EPI_ISL_19286121,
EPI_ISL_19286377, EPI_ISL_19286438-19286439, EPI_ISL_19286452,
EPI_ISL_19286529, EPI_ISL_19286567, EPI_ISL_19286727,
EPI_ISL_19286800, EPI_ISL_19287409, EPI_ISL_19290154,
EPI_ISL_19293512, EPI_ISL_19293534, EPI_ISL_19293618,
EPI_ISL_19295220, EPI_ISL_19298224, EPI_ISL_19302502,
EPI_ISL_19303440, EPI_ISL_19304230, EPI_ISL_19308466,
EPI_ISL_19308526, EPI_ISL_19310695, EPI_ISL_19317468,
EPI_ISL_19317741, EPI_ISL_19317747, EPI_ISL_19317777,
EPI_ISL_19317786, EPI_ISL_19318204
</details>

**Comment by FedeGueli** [comment]
56

**Comment by Over-There-Is** [comment]
> 56

There is another query with 5 more sequences. So the total amount is 61.

**Comment by Over-There-Is** [comment]
US +4, ES +1

**Comment by FedeGueli** [comment]
please propose it although not fast it is big enough to be designated

**Comment by Over-There-Is** [comment]
Transferred to cov-lineages/pango-designation#2775

**Comment by FedeGueli** [comment]
Designated KP.3.1.10 via https://github.com/cov-lineages/pango-designation/commit/d39304704862930caed86d10b5785fa1131b2b17
