### ISSUE TITLE
XEF:LB.1.4/KP.3 recombinant(or LB.1.4+S:L335S, Q493E,V1104L) (7 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1855]
This one was discussed as singlet in #1675 by @ryhisner , and there's now 4 seqs from 4 countries. More seqs help refine Ryan's initial analyse. 

LB.1.4--KP.3

Breakpoint between 22600 and 23038 (between S:346 and 493)

Additional mutation: del3332_3343, G4255T, T22566C

Orf1a: del1023_1026
S: L335S

G4255T from a LB.1.4 branch
del3332_3343, T22566C are private mutations. 

Ryan thought del3332_3343 was from a LB.1.2 branch, but all these seqs have C4683T which is LB.1.4 defining and G4255T which belongs to an LB.1.4 branch, and all seqs lack the LB.1.2 defining 19669 mutation so must be LB.1.4. 

 It is more likely to gain del3332_3343 independently.

Ryan also thinks the other donor being KP.3.2 due to C28657T, however it doesn't appear on other 3 seqs so the donor is likely just KP.3. 

GISAID query: C4683T,G4255T,G22111T,C23039G, G24872T
No. of seqs: 4( Australia 1 Canada 1 USA 2(1 from India)

First: EPI_ISL_19266767, USA, 2024-6-26
Latest: EPI_ISL_19300619, USA from India, 2024-7-21

This recomb has very good potential, it emerges in undersampled region of India, starts in multiple countries, and has the current fastest DeFLiRT+DeFLuQE double combo via breakpoint on Spike, and with lots of additional spikes Q183H, L335S and V1104L. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice8_genome_test_8f72_5c8490.json?label=id:node_5706110)
![image](https://github.com/user-attachments/assets/e7303d36-085d-4cb0-a98f-080407085ac4)

**Comment by FedeGueli** [comment]
I think also @nkrmnzr was tracking this as sublineage not recombinant tough

**Comment by aviczhl2** [comment]
> I think also @NkRMnZr was tracking this as sublineage not recombinant tough

Yeah recomb explains only 2 mutations S:Q493E and S:V1104L, it can be explained as convergent mutation despite both have strong KP.3-signature.

**Comment by aviczhl2** [comment]
+1 USA from UK.

**Comment by FedeGueli** [comment]
Ping @corneliusroemer if you are still in designathlon session i suggest to take a look to two more lineages: 1st is this

**Comment by aviczhl2** [comment]
This one is designated XEF. 

XEE is skipped for unknown reason (EE was not skipped)
