### ISSUE TITLE
One more KP.3.1+S:S31F( 158 seqs, 14 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1856]
Misplaced under KP.3.1.3 before so we didn't detect. Now there's enough seqs with G25644T only so usher gives it an independent branch  @corneliusroemer 
KP.3.1+G25644T+C21654T(S:S31F)

GISAID query: G25644T,C21654T,G15372T
No. of seqs: 158(Canary Islands 1 Denmark 4 UK 9 France 8 Germany 1 Ireland 1 Israel 1 Italy 1 Japan 2 Luxembourg 2 Netherlands 3 Norway 1 Puerto Rico 1 Spain 95 Sweden 4 USA 23(2 from France 1 from Italy 2 from Germany))

First: EPI_ISL_19108408, UK, 2024-4-25
Latest: EPI_ISL_19324871, Spain, 2024-8-1

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice127_genome_test_3fcb1_6a81e0.json?label=id:node_5493731)
![image](https://github.com/user-attachments/assets/e445fbb5-8b86-4f22-9bc4-0d3426cbaa3a)

**Comment by FedeGueli** [comment]
propose it directly is big enough to be designated

**Comment by FedeGueli** [comment]
> G25644T

i would consider to make this KP.3.1.3 because KP.3.1.3. without it is only 18 with most of recent samples belonging to one single Irish cluster 

ping @corneliusroemer

**Comment by aviczhl2** [comment]
Proposed in the main repo as a lineage alter suggestion.
