### ISSUE TITLE
KP.1.1.3+S:H146Y (28 seqs,10 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1858]
There is a KP.2+S:H146Y branch, now there is also a branch under KP.1.1.3, with the more powerful DeFLiRT backbone

KP.1.1.3+C21998T(S:H146Y)

Like #1666, there is also a GISAID misread problem here. GISAID reads it as S:H146del while removing the S:Y144del. 

GISAID query: C4999,A24819, del21998
No. of seq: 14( Dominician Republic 1 UK 1 France 1 Germany 1 Israel 1 Poland 1 USA 8)

First: EPI_ISL_19144428, USA, 2024-5-6
Latest: EPI_ISL_19302655, Poland, 2024-7-25

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice221_genome_test_59cc1_6c0060.json?label=id:node_5503391)
![image](https://github.com/user-attachments/assets/4d8b11c9-fcf5-4b0a-9795-1eacd0dc9aa4)

**Comment by FedeGueli** [comment]
> There is a KP.2+S:H146Y branch, now there is also a branch under KP.1.1.3, with the more powerful DeFLiRT backbone
> 
> KP.1.1.3+C21998T(S:H146Y)
> 
> Like #1666, there is also a GISAID misread problem here. GISAID reads it as S:H146del while removing the S:Y144del.
> 
> GISAID query: C4999,A24819, del21998 No. of seq: 14( Dominician Republic 1 UK 1 France 1 Germany 1 Israel 1 Poland 1 USA 8)
> 
> First: EPI_ISL_19144428, USA, 2024-5-6 Latest: EPI_ISL_19302655, Poland, 2024-7-25
> 
> [usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice221_genome_test_59cc1_6c0060.json?label=id:node_5503391) ![image](https://private-user-images.githubusercontent.com/10445944/356785011-4d8b11c9-fcf5-4b0a-9795-1eacd0dc9aa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDUwMjUsIm5iZiI6MTcyMzMwNDcyNSwicGF0aCI6Ii8xMDQ0NTk0NC8zNTY3ODUwMTEtNGQ4YjExYzktZmNmNS00YjBhLTk3OTUtMWVhY2QwZGM5YWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE1NDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NmM4MDdhNDUyZTI1MTQ4ODg2OThjYjk1YzRjYjAxZDcxMWRmMTI5N2YzNzRmY2Q0NTc0YjBjNjhlZmNkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lkbyyJ4ZI0tOgW5HFaHvSAdjYzVjVPbKB9SY5yhIPLw)

i notice that also Nextclade did the same for other sequences unrelated to this, did u check how nextclade reads this in that way?

**Comment by FedeGueli** [comment]
Ah i got why it is Y144 so finding 146Y after the deletion for the pipelines is more likely the deletion happens after 144 and not there.

**Comment by FedeGueli** [comment]
+1 Israel from August

**Comment by aviczhl2** [comment]
23, Norway

**Comment by aviczhl2** [comment]
25,Ukraine,Canary Islands(Spain)

**Comment by Over-There-Is** [comment]
US+3

**Comment by FedeGueli** [comment]
only two recent samples closing it

**Comment by Over-There-Is** [comment]
46 now

**Comment by Over-There-Is** [comment]
5 from Chernihiv and 1 from Kyiv Oblast. Maybe also circulates in Belarus?

**Comment by Over-There-Is** [comment]
50

**Comment by FedeGueli** [comment]
new query: C4999,A24819, del21998,-G1954A,-T14508C,-C2937T,-A10323G,-T25556G,-T2533G finds 36.
