### ISSUE TITLE
XDQ.1+S:S31F, A67V, Orf9b:P10F(4, Japan)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1862]
XDQ.1> C29409T(N:T379I)> A5606C(Orf1a:K1781Q)> C4048T, C28312T(Orf9b:P10F)> C18570T, C21654T(S:S31F), C21762T(S:A67V), C27294T
Query: C4048T, C7420T, C18570T

07-05~08 Sendai City, Miyagi Prefecture, Japan

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_e3be_6de730.json?c=country&label=id:node_6939202
![image](https://github.com/user-attachments/assets/9d08e02a-3261-4cb5-924f-49814833a4f4)

Sequences:
EPI_ISL_19287583, EPI_ISL_19287585-19287586, EPI_ISL_19287602

**Comment by FedeGueli** [comment]
Sorry i was thinking it was XDV

**Comment by FedeGueli** [comment]
No new sequences came in closing this one, very likely just a local lineage.
