### ISSUE TITLE
XEC + S:K182R (6 , 4 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1869]
There is a sublineage of XEC that apparently spread from France to Canada and Ireland
Defining mutations: XEC> Orf1a:A599T (G2060A)> A424G, C12809T, A22107G, C22414T
Query: A424G,C12809T
Samples: 5
First: collected on 2024-07-15 in Strasbourg France
Countries: France , Ireland, Canada

Tree:
<img width="1082" alt="Screenshot 2024-08-13 alle 08 43 49" src="https://github.com/user-attachments/assets/5e1b65ba-2c69-4cee-9beb-a22d4d558313">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_13340_afead0.json?label=id:node_7015933

**Comment by FedeGueli** [comment]
+1 Denmark

**Comment by aviczhl2** [comment]
Designated XEC.1
