### ISSUE TITLE
KP.3.3 subbranch with S:A688V and Orf1a:L642F, T2093I (47, Japan, 13 prefectures)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1870]
KP.3.3> C6543T(Orf1a:T2093I)> C2189T(Orf1a:L642F)> C7528T> C23625T(S:A688V)
Query: C2189T, C6543T, C23625T

Earliest sequence: 05-27 Chiba, Japan EPI_ISL_19185369
Latest sequence: 08-06 Sapporo, Hokkaido, Japan EPI_ISL_19360796
Regions detected: Japan 38(Miyagi 26, Niigata 4, Chiba 2, Osaka 1, Kagoshima 1, Tokyo 1, Hiroshima 1, Fukushima 1, Hokkaido 1)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_32be0_b2e370.json?c=userOrOld&label=id:node_7016458
![image](https://github.com/user-attachments/assets/9ad400d7-ecc7-40a8-9545-7e0076b0d14f)

<details><summary>Sequences:</summary>

EPI_ISL_19183874, EPI_ISL_19185369, EPI_ISL_19238915,
EPI_ISL_19266966, EPI_ISL_19269566, EPI_ISL_19280769,
EPI_ISL_19287557, EPI_ISL_19287562, EPI_ISL_19287568,
EPI_ISL_19287587, EPI_ISL_19295706, EPI_ISL_19305292,
EPI_ISL_19305312, EPI_ISL_19305322, EPI_ISL_19309005-19309007,
EPI_ISL_19309014, EPI_ISL_19309020, EPI_ISL_19309023,
EPI_ISL_19309025, EPI_ISL_19309034-19309036, EPI_ISL_19309230,
EPI_ISL_19348340, EPI_ISL_19348343, EPI_ISL_19348353,
EPI_ISL_19348356, EPI_ISL_19348358, EPI_ISL_19348368,
EPI_ISL_19348371-19348372, EPI_ISL_19348376, EPI_ISL_19357076,
EPI_ISL_19357078, EPI_ISL_19357086, EPI_ISL_19360796
</details>

**Comment by Over-There-Is** [comment]
Miyagi +9

**Comment by Over-There-Is** [comment]
Niigata +3

**Comment by Over-There-Is** [comment]
Sapporo

**Comment by Over-There-Is** [comment]
Gifu & Saitama

**Comment by Over-There-Is** [comment]
Iwate+1

**Comment by FedeGueli** [comment]
None of this in the last 439 Japanese samples closing it

**Comment by Over-There-Is** [comment]
KP.3.3.7
