### ISSUE TITLE
ML.1 subbranch with S:D1260Y (8, Japan-Kagoshima)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1871]
ML.1> A4015G> G25340T(S:D11260Y)
Query: A4015G, G25340T,T3565C (edited)

06-22~07-19 Kagoshima, Japan
Sequence:
EPI_ISL_19239337, EPI_ISL_19287912, EPI_ISL_19287914-19287915,
EPI_ISL_19287919-19287920, EPI_ISL_19287928, EPI_ISL_19287939

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_411da_b328b0.json?c=userOrOld&label=id:node_7021899
![2024-08-13 (11)](https://github.com/user-attachments/assets/3b822e9b-f49a-437b-ab71-77228d362a52)

**Comment by FedeGueli** [comment]
+1

**Comment by FedeGueli** [comment]
Query edited to exclude an unrelated sample

**Comment by Over-There-Is** [comment]
Dead?

**Comment by FedeGueli** [comment]
Likely, wait the end of the. month to close it

**Comment by Over-There-Is** [comment]
Osaka +3
