### ISSUE TITLE
LB.1 subbranch with S:S680P and Orf3a:I63T, R134H(10 seqs, 6 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1873]
LB.1> C19011T, T23600C(S:S680P), T25580C(Orf3a:I63T), G25793A(Orf3a:R134H)
Query: C19011T, T23600C, T25580C

Earliest sequence: 05-15 New Jersey, USA (Imported from Greece) EPI_ISL_19191239
Latest sequence: 07-03 Bayern, Germany EPI_ISL_19288390
Regions Detected: **US** 7(1 from **Greece**, 1 from **UAE**, 1 from **UK**, 3 from airport pooled test), **Germany** 2, **Spain** 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_536ac_b56b30.json?c=country&label=id:node_7262224
![image](https://github.com/user-attachments/assets/df610291-5643-4c56-a32d-086ba33b5a14)

Sequences:
EPI_ISL_19162479, EPI_ISL_19191239, EPI_ISL_19191475,
EPI_ISL_19191775, EPI_ISL_19240907, EPI_ISL_19241047,
EPI_ISL_19254648, EPI_ISL_19283731, EPI_ISL_19288390,
EPI_ISL_19300856

**Comment by FedeGueli** [comment]
it seems no recent sample of this

**Comment by aviczhl2** [comment]
No new seqs
