### ISSUE TITLE
LB.1 with S:K478T (rev) 12 samples from 9 countries including India and Qatar

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1874]
Also LB.1 got the S:K478T that is clearly a trending mutation right now

LB.1 > C15960T > G20931T, S:K478T (A22995C) REV,  T29194C
Query: C15960T , G20931T,T29194C,C897A
Samples:12 ( Usher shows two more from Sweden)
First collected on 2024-06-24 in Denmark
Countries: 9
(Denmark, Sweden, Spain, Australia, Canada, Netherlands, US and via GBW Qatar & India)

Tree:
<img width="1168" alt="Screenshot 2024-08-13 alle 16 31 40" src="https://github.com/user-attachments/assets/8144d299-ca31-4139-a82f-969d97a9223f">
<img width="1157" alt="Screenshot 2024-08-13 alle 16 35 17" src="https://github.com/user-attachments/assets/6ace2355-f1ae-4732-8c17-72f5e8ce9868">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_468d1_b6c320.json?label=id:node_7262433

**Comment by aviczhl2** [comment]
Designated LB.1.9
