### ISSUE TITLE
FL.5 with ORF10:S23F and S:I651V 102 seq.

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#188]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/d8ee527a-1a3b-445e-b51a-d983009de179)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d623_9feec0.json?c=gt-S_651&label=id:node_6605404
first seq: 2023-03-01
most recent: 2023-05-29
gisaid query: C29625T, A23513G, C29358T
EPI_ISL_17764591 EPI_ISL_17727179 EPI_ISL_17641796 EPI_ISL_17743176 EPI_ISL_17764580 EPI_ISL_17688294 EPI_ISL_17764382 EPI_ISL_17764561 EPI_ISL_17764386 EPI_ISL_17688292 EPI_ISL_17764601 EPI_ISL_17764603 EPI_ISL_17701541 EPI_ISL_17764384 EPI_ISL_17727181 EPI_ISL_17727183 EPI_ISL_17688275 EPI_ISL_17764575 EPI_ISL_17727175 EPI_ISL_17630611 EPI_ISL_17764678 EPI_ISL_17764676 EPI_ISL_17537310 EPI_ISL_17764558 EPI_ISL_17726703 EPI_ISL_17764582 EPI_ISL_17764611 EPI_ISL_17764677 EPI_ISL_17764389 EPI_ISL_17764592 EPI_ISL_17683371 EPI_ISL_17764576 EPI_ISL_17764559 EPI_ISL_17726899 EPI_ISL_17727180 EPI_ISL_17763995 EPI_ISL_17764573 EPI_ISL_17764385 OQ655176.1 EPI_ISL_17764579 EPI_ISL_17764679 EPI_ISL_17727184 EPI_ISL_17764383 EPI_ISL_17688243 EPI_ISL_17764581 EPI_ISL_17764590 EPI_ISL_17688296 EPI_ISL_17726727 EPI_ISL_17688242 EPI_ISL_17727182

**Comment by FedeGueli** [comment]
Tempted to close this next week
