### ISSUE TITLE
KP.3.1.1/XDV.1 recombinant (3 seqs. 3 countries)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1881]
![image](https://github.com/user-attachments/assets/327ac9fd-d9e8-4b03-8925-314b760a5f9e)
Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_59bc_ed67e0.json?c=gt-N_204&gmax=29533&gmin=28274&label=id:node_7036069

Seq: 2024-07-28

Mutations: 
ORF1a:K47R, ORF1a:D211A (R), ORF1a:S302F, ORF1a:L1056V (R), ORF1a:T1322I, ORF3a:N82D, N:R204Q

Gisaid: C4230T, A25636G

EPI_ISL_19324526 EPI_ISL_19324633 EPI_ISL_19324816

**Comment by aviczhl2** [comment]
It seems that the 2 GBW-BBB seqs are from different countries, Iceland and UK.

**Comment by FedeGueli** [comment]
great catch thx

**Comment by Memorablea** [comment]
USA-GBW+1，4seqs now

**Comment by aviczhl2** [comment]
> USA-GBW+1，4seqs now

Which one? Still 3 using the query.

**Comment by Memorablea** [comment]
> > USA-GBW+1，4seqs now
> 
> Which one? Still 3 using the query.

Sorry, I didn't find any sequencing errors in India. Still three.

**Comment by aviczhl2** [comment]
No new seqs
