### ISSUE TITLE
KP.2.3 subbranch with S:S704L (67 seqs, 6 countries, mainly found in US)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1883]
KP.2.3> C16768A> T16374C> C23673T(S:S704L)
Query: T16374C, C16768A, C23673T

Earliest sequence: 05-20 Massachusetts, USA EPI_ISL_19251188
Latest sequence: 07-30 Ontario, Canada EPI_ISL_19313342
Regions detected: US 37(2 from Cuba, 2 from Netherlands, 1 from Turkey), Canada 2

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1ccad_e3d930.json?c=country
![image](https://github.com/user-attachments/assets/6eb8c434-7a2e-4d6d-9d6e-d2b53f800350)

<details><summary> Sequences: </summary>

EPI_ISL_19195873, EPI_ISL_19195960, EPI_ISL_19197397,
EPI_ISL_19201079, EPI_ISL_19209622, EPI_ISL_19230638,
EPI_ISL_19233889, EPI_ISL_19238181, EPI_ISL_19239524,
EPI_ISL_19240818, EPI_ISL_19251188, EPI_ISL_19259049,
EPI_ISL_19268463, EPI_ISL_19268967, EPI_ISL_19271128,
EPI_ISL_19277600, EPI_ISL_19278945, EPI_ISL_19289001,
EPI_ISL_19289829, EPI_ISL_19290042, EPI_ISL_19298349,
EPI_ISL_19298464, EPI_ISL_19307758, EPI_ISL_19308402,
EPI_ISL_19313342, EPI_ISL_19317096, EPI_ISL_19324943,
EPI_ISL_19325321, EPI_ISL_19328834, EPI_ISL_19329464,
EPI_ISL_19334964, EPI_ISL_19335488
</details>

**Comment by Memorablea** [comment]
USA +3.35 seqs now.

**Comment by Over-There-Is** [comment]
Tennessee +10

**Comment by Over-There-Is** [comment]
DC+1

**Comment by Over-There-Is** [comment]
Greece

**Comment by FedeGueli** [comment]
This lineage is likely faster than KP.2.3 baseline but unsure if able to compete with newcomers.

**Comment by FedeGueli** [comment]
one recent sample only closing this for now

**Comment by Over-There-Is** [comment]
79
