### ISSUE TITLE
KP.3.2.4 subbranch with S:G1171D and Orf1a:G2342E (6 seqs, 3 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1884]
KP.3.2.4> C29218T> A10558T> G7290A(Orf1a:G2342E)> C25069A, G25074A(S:G1171D), C25728T, C29284T
Query: G7290A, C25069A

07-17 5 seqs, US(from Finland)
07-24 1 seq, UK

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_8bd4_fafb70.json?c=country&label=id:node_7050349
![image](https://github.com/user-attachments/assets/169f76a0-19d1-410a-8659-28d064e27ad9)

EPI_ISL_19289762, EPI_ISL_19289783, EPI_ISL_19289795,
EPI_ISL_19289921, EPI_ISL_19289934, EPI_ISL_19338545

**Comment by aviczhl2** [comment]
Shall be S:G1171D

**Comment by Over-There-Is** [comment]
> Shall be S:G1171D

thx

**Comment by Over-There-Is** [comment]
@FedeGueli I mistyped 1171 into 1174. The actual mutation site is 1171. A correct label is needed.

**Comment by FedeGueli** [comment]
Sorry i dint check in depth after the hard day yesterday. thx @aviczhl2 for checking

**Comment by aviczhl2** [comment]
No new seqs
