### ISSUE TITLE
KP.3.4 subbranch with S:P39T, Orf1b:C3S on Orf3a:L73F branch (6 sequences, US-GU)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1885]
KP.3.4> C25521T> C25609T(Orf3a:L73F)> T13474A(Orf1b:C3S), C21677A(S:P39T)
Query: C21677A, C25609T

07-08~07-22 Guam, USA

EPI_ISL_19293748-19293749, EPI_ISL_19293751, EPI_ISL_19302264-19302265,
EPI_ISL_19302267

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4b9cc_fb6ce0.json?c=country&label=id:node_7025129
![image](https://github.com/user-attachments/assets/0f7e27b8-198e-4bd9-b690-8a707fbd0204)

**Comment by FedeGueli** [comment]
S:39 has been on the move since some months but usually without big contributions to growth.

**Comment by aviczhl2** [comment]
Not going anywhere
