### ISSUE TITLE
KS.1+Orf3a:A33S, D155Y,N:L139F, S:T22N, T573I (14 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1886]
This shall be separate branch from KS.1.1

KS.1+T3592C, C28948T+G25489T(Orf3a:A33S)+G25855T(Orf3a:D155Y)+G28690T(N:L139F)+C21627A,C23280T(S:T22N, T573I)

GISAID query: C21627A, C23280T, G28690T
No. of seqs: 11(Ireland 3 UK 8)

First: EPI_ISL_19253834, UK, 2024-6-17
Latest: EPI_ISL_19323305, UK, 2024-7-29

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice9_genome_test_4c946_31f40.json?label=id:node_5659979)
![image](https://github.com/user-attachments/assets/792b2d87-de06-432b-8b82-780bb7c39fa9)

**Comment by FedeGueli** [comment]
no recent seqs closing it
