### ISSUE TITLE
LB.1.2.1 with S:K478Q (17, 5 countries including Singapore,UAE, India, South Korea and France) High prevalence in Assam India (20%)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1887]
Likely emerged in India but now sampled in three different countries i thin k it is worth tracking it

Defining mutations:
LB.1.2.1> G4561A > S:K478Q (A22994C) > S:P384S (C22712T)

Query:G4561A,A22994C

Samples: 5 

Countries: India (Assam), Singapore,  South Korea, UAE (via GBW)

Tree updated with sequences from Assam , India on October 2:
 <img width="1164" alt="Screenshot 2024-10-02 alle 10 01 29" src="https://github.com/user-attachments/assets/653729b1-13ab-4674-817a-86ef7db6a67a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2a18e_cfa610.json?label=id:node_7340425

**Comment by FedeGueli** [comment]
6 / 3

**Comment by FedeGueli** [comment]
9 now, new samples via GBW from UAE (tot 3) and France (1st)

**Comment by FedeGueli** [comment]
slow closing it

**Comment by aviczhl2** [comment]
+7 India-Assam

**Comment by aviczhl2** [comment]
It seems to have 20-30% prevalence in Assam, propose it?

**Comment by FedeGueli** [comment]
> G4561A,A22994C

thx

**Comment by FedeGueli** [comment]
i will propose it when it reaches 20

**Comment by DailyCovidCases** [comment]
Slowing down now

**Comment by DailyCovidCases** [comment]
> It seems to have 20-30% prevalence in Assam, propose it?

I think it is only an inflation (too few samples)

**Comment by DailyCovidCases** [comment]
> It seems to have 20-30% prevalence in Assam, propose it?

I think it is only an inflation (too few samples)

**Comment by DailyCovidCases** [comment]
Slow closing it now

**Comment by FedeGueli** [comment]
> G4561A,A22994C

again when u see the Undersampled tag dont comment anything they can stay open for months.

**Comment by DailyCovidCases** [comment]
Not any seq from the past 8 weeks, please close it.

**Comment by FedeGueli** [comment]
> Not any seq from the past 8 weeks, please close it.

see the msg above.

**Comment by DailyCovidCases** [comment]
Dead please close it
