### ISSUE TITLE
EG.5.2 with ORF1a:N2155S, ORF1a:H1113Y, ORF3a:I118V, S:S704L -33seqs 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#189]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/3c10dcb2-dc6a-4c2a-a38c-54deaae491ec)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11483_a041f0.json?c=gt-nuc_832&label=id:node_6611715
first seq: 2023-05-10
Most recent 2023-05-27
gisaid query: C3602T, A25744G, C832T or  C3602T, A25744G, C23673T (by @NkRMnZr )
OR064458.1 OR064455.1 OR038006.1 OR075486.1 OR075456.1 EPI_ISL_17763472 EPI_ISL_17763540

**Comment by FedeGueli** [comment]
with your query i find less than 9 could you check please?

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a19bc70b-d4c2-4501-93c4-03c1cb9246f1)

**Comment by FedeGueli** [comment]
26 or 27 samples now.

**Comment by FedeGueli** [comment]
I think it is worth proposing it . please include the observations from @NkRMnZr about the broader lineage.
