### ISSUE TITLE
KP.1.1.3 got S:K478T( 28, 2 places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1893]
_Edited on October 4:
Now Usher shows many branches of KP.1.1.3 in one only tree. Hard to find a credible query for this, but ushering from this proposal could be enough to track the whole thing._

Original proposal:
S:K478T is now trending globally even if its exact share is not easy to establish due the confounding of missing coverage.

Here i want to propose a mini saltation S:K478T lineage under KP.1.1.3

KP.1.1.3 > S:K478T (A22995C rev), Orf1a:H919Y (C3020T), C3787T, ORF1a:I2076V (A6491G), C6628T, Orf1b:A241T (G14188A),Orf1b:F1557L (T18136C), T26130C
Query: C3020T, C3787T, A6491G
Samples: 6 ( 3/6 sampled in August)
Country : 1 US (Iowa, Colorado)
Tree:
<img width="1150" alt="Screenshot 2024-08-19 alle 18 11 04" src="https://github.com/user-attachments/assets/966c6e06-922f-44fe-9534-ebf6cb60e417">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_635b7_36c130.json?label=id:node_7059171

**Comment by FedeGueli** [comment]
10 Nevada

**Comment by FedeGueli** [comment]
25 Ontario

**Comment by FedeGueli** [comment]
recent samples are Ontario Only closing this

**Comment by FedeGueli** [comment]
Now USher  collects many branches of KP.1.1.3 + S:k478T inn one only tree:
<img width="1163" alt="Screenshot 2024-10-04 alle 14 50 21" src="https://github.com/user-attachments/assets/a62410e7-e0cd-4616-b32f-c07ab0d3c092">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_3e7c_fe30a0.json?label=id:node_7283985

Hard to find a query for it

**Comment by xz-keg** [comment]
designated LP.5

**Comment by FedeGueli** [comment]
There is a second LP.5 branch found by the query : A10344G,C4999T
and it is defined by N:G200D and Orf1a:K3360R

**Comment by FedeGueli** [comment]
> There is a second LP.5 branch found by the query : A10344G,C4999T and it is defined by N:G200D and Orf1a:K3360R <img alt="Screenshot 2024-11-14 alle 18 53 59" width="1176" src="https://private-user-images.githubusercontent.com/87669813/386311364-38eb3b26-a705-4aef-aaa7-03a1e24e620b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2MjIxNjcsIm5iZiI6MTczNjYyMTg2NywicGF0aCI6Ii84NzY2OTgxMy8zODYzMTEzNjQtMzhlYjNiMjYtYTcwNS00YWVmLWFhYTctMDNhMWUyNGU2MjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTExVDE4NTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZTE4ODk4MGU1YTZmZDA1MjVlN2RkODk4N2I0NTIzNTQyMmVkMzBhYzkwNDY1N2U3MjA0ZGNmYjJiMmMyNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O-IprEHyKAJ63n1Y8JwurUTUNHZ1_bieSMIY5_PsSMg"> https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2fa18_6331b0.json?label=id:node_7401269

67 with December samples from Russia and SK
