### ISSUE TITLE
Long branch XBB.1.5.18 from Italy-Monza (2 samples, July)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1894]
```
hCoV-19/Italy/LOM_ASSTMonza_6000393969_121600/2024|EPI_ISL_19341144|2024-07-02
hCoV-19/Italy/LOM_ASSTMonza_6000403652_103600/2024|EPI_ISL_19341128|2024-07-03
```

<img width="837" alt="Google Chrome 2024-08-19 18 56 26" src="https://github.com/user-attachments/assets/ddca8847-d0a3-4b1d-917e-6310ffdcbd53">

<img width="563" alt="Google Chrome 2024-08-19 18 56 34" src="https://github.com/user-attachments/assets/a2b1b1c6-b480-4327-95b0-65d57caf763d">

<img width="660" alt="Google Chrome 2024-08-19 18 56 44" src="https://github.com/user-attachments/assets/8c598353-0ef6-43d3-aaab-2abc7cdb89a8">

**Comment by corneliusroemer** [comment]
Probably a chronic based on the ancestral sequences being from same lab:

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_51e9f_3794a0.json

<img width="2268" alt="Google Chrome 2024-08-19 18 57 50" src="https://github.com/user-attachments/assets/c4f9d769-299a-45ea-a678-1717f0692fa1">

**Comment by corneliusroemer** [comment]
Private mutations on branch:
Gene | Unique | Homoplasy | Reversions
-- | -- | -- | --
Nt | Unique (36):A969C, T3161C, T3169C, A4091C, T4882C, C5184T, T5404C, A8390G, T9495C, T11751C, A12095G, C12116T, C14688T, C16877T, T21146G, T21752C, C21998A, T22220A, A22320G, T22930G, T23030A, G23340T, A23531C, G24124T, G24764A, G25013C, A26231C, T26302C, A26507C, C26533T, A26557G, T27634C, A28266G, C28486A, T28906C, C28928T | Homoplasies (14):C799T, C3096T, C6336T, C6449T, C7164T, C10125T, C10776T, C11003T, T14313C, G18163A, C19011T, C21622T, C27247T, C28567T | Reversions to root (1):G18163A
ORF1ab | Unique (11):E235A, S966P, I1276L, P1640L, I2709V, V3077A, L3829P, I3944V, L3951F, T5538I, L6961R | Homoplasies (8):S944L, S2024L, L2062F, T2300I, T3287I, P3504L, H3580Y, V5967I | Reversions to root (1):V5967I
S | Unique (10):W64R, Q146K, F220I, D253G, S490T, G593V, N657H, K854N, V1068I, E1151Q | Homoplasies (1):F456L |
E | Unique (1):F20L | |
M | Unique (2):S4F, E12G | |
ORF7a | Unique (1):S81P | |
N | Unique (1):L219F | |

**Comment by FedeGueli** [comment]
Thx @corneliusroemer, Also @ryhisner spotted this.  yes very likely a chronic.

**Comment by FedeGueli** [comment]
Closing this .
