### ISSUE TITLE
KP.2.3 + S:H445Q ( 19 Samples, 7 places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1895]
445Q has been extremely rare in this pandemic with only 14 sequences carrying it , 5 of them popped up in July 2024, 2 unrleated on KP.3.1.1 backbone whikle three clustering together from Japan and from Iceland (via GBW two different patients).
According to [Tyler Starr last calculator](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-EG5-FLip-BA286/RBD-heatmaps/) based on BA.2.86 it could be beneficial:
<img width="262" alt="Screenshot 2024-08-20 alle 10 04 29" src="https://github.com/user-attachments/assets/b14be11f-041b-4585-95cf-51e42a3b7d1a">

Kp.2.3>  C28714T > S:H445Q (T22897A)
Query: C28714T,T22897A
Samples:3
First: 2024-07-15 Iceland (via GBW)
Last 2024-08-08 Japan, Saitama
Countries: Japan, Iceland

Tree:
<img width="1179" alt="Screenshot 2024-08-20 alle 10 02 09" src="https://github.com/user-attachments/assets/c1093ec0-a52f-4dfe-8349-1563121e3663">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4bf5_43c600.json?c=userOrOld&label=id:node_11605874

**Comment by FedeGueli** [comment]
+2 US, Japan (Tokyo new prefecture)

**Comment by FedeGueli** [comment]
+3 Norway,Switzerland

**Comment by FedeGueli** [comment]
can't compete closing it

**Comment by FedeGueli** [comment]
New recent sample from Australia reopening for a while

**Comment by Over-There-Is** [comment]
13

**Comment by FedeGueli** [comment]
15, France

**Comment by FedeGueli** [comment]
thx a lot @NkRMnZr

**Comment by FedeGueli** [comment]
+1 Colorado

**Comment by FedeGueli** [comment]
Dying off
