### ISSUE TITLE
JN.1.16 + S:T22N and S:Q493E (12) and 7 with S:S31P

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1898]
![image](https://github.com/user-attachments/assets/1a61b434-faab-4bc6-9ccc-88d1caf9011c)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c00b_54f080.json?c=gt-S_493&gmax=25384&gmin=21563&label=id:node_7258923

Query: C21627A & C23039G & !C18657T & !C7113T & !C4582T & !C5806T & !C19524T & !C29466T & !A22108C

Query with s:31P : C3923T, T21653C

First Seq: 2024-07-19
Most Recent: 2024-08-12

EPI_ISL_19344475 EPI_ISL_19342074 EPI_ISL_19344477 EPI_ISL_19333785 EPI_ISL_19344422 EPI_ISL_19333774 England/CLIMB-CM7Y8HHI/2024 PQ150665.1 EPI_ISL_19334400 EPI_ISL_19331331 EPI_ISL_19334393 EPI_ISL_19343901

**Comment by aviczhl2** [comment]
That's JN.1.16.5

**Comment by Over-There-Is** [comment]
S:S31P branch is 61 now.

**Comment by FedeGueli** [comment]
> S:S31P branch is 61 now.

yeha already proposed on pango
