### ISSUE TITLE
KP.3.2+S:S31P(  12 seqs, 6 countries, 1 with S:T22N, 1 with S:K478T rev)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1899]
KP.3.2+G25617A+G11761A, T21653C(S:S31P)

GISAID query: G11761A, T21653C, G25617A (By @FedeGueli )
No. of seqs: 3(Hubei 1 Gansu 1 USA from Hong Kong 1)

First: EPI_ISL_19299334, Hubei, 2024-7-7
Latest: EPI_ISL_19345248, USA from Hong Kong, 2024-8-9

The Gansu seq has additional S:K478T rev while the GBW one has additional S:T22N
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_4a76b_555970.json)

![image](https://github.com/user-attachments/assets/dfef371f-a07e-4165-a66b-0b4b506c8cfd)

**Comment by aviczhl2** [comment]
+1 Shanxi

**Comment by FedeGueli** [comment]
@aviczhl2 with G11761A, T21653C, G25617A i found 5 , the additional one should be a Spanish sample with a NNN stretch in the RBD so misplaced by USher elsewhere: 
EPI_ISL_19341207
Collected on August 8 in a 103years old woman from Madrid

**Comment by Memorablea** [comment]
S:S31P branch Japan+1.With ORF3a:Q213H.

**Comment by aviczhl2** [comment]
+1 Singapore with S:K478T rev

**Comment by aviczhl2** [comment]
+2 Gansu +1 Australia

**Comment by FedeGueli** [comment]
i would propose this one.

**Comment by FedeGueli** [comment]
Designated KP.3.2.6 via https://github.com/cov-lineages/pango-designation/commit/81c3b2dea03e3b95901ec189c8694b58926c8783
