### ISSUE TITLE
XBB.1.9.1 with S:S256L and S:S494P and 5 other aa muts in france (21 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#19]
Mutations from xbb.1.9.1: orf1ab:v3747i >> orf1ab:m5974t >> A11386G >> N:R195I >> s:S494P >>  s:i19t & s:n616d >> s:s256l.

Query: Spike_s256l, spike_s494p, spike_f486p, -spike_p521s

There is also another branch in the tree with s:h339g, that reversion is probably an artefact.

S:n616d is a very rare mutation, only 112 sequences
Detailed view:
![Screenshot_20230507_132519_Chrome](https://user-images.githubusercontent.com/119106095/236674727-b1511b5c-9acc-4274-82dc-362ff49a5bb1.jpg)

View from orf1ab:v3747i branch of xbb.1.9.1:
![Screenshot_20230507_132711_Chrome](https://user-images.githubusercontent.com/119106095/236674749-06d2d6f1-e411-463a-abfd-4f08b3ee05fa.jpg)

This doesnt really have enough spread yet for a proposal but I think the cluster is interesting and it has so many mutations compared to xbb.1.9.1. 
 Xbb.1.9.1 + s:494p + s:256l:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A256l%2Cs%3A494p&nextcladePangoLineage=xbb.1.9.1*

**Comment by BorisUitham** [comment]
Actually looking at the reversion s:i19t in france i think its probably not real considering it suddenly rose to 100% there across all sequences

**Comment by BorisUitham** [comment]
One more thing: gisaid says the sampling strategy is random. Most sequences are from isere, one from nancy, and its three different labs

**Comment by krosa1910** [comment]
Oh this was proposed first, I guess I would shut down my #22. Happy to continue discussion here.

**Comment by BorisUitham** [comment]
@krosa1910 i just found that you also made another issue of an xbb.1.9.1 with 256L in the main repo a week ago, i didnt find that earlier because i searched for p256l which apparently doesnt return that issue. However i think that is a parallel branch perhaps https://github.com/cov-lineages/pango-designation/issues/1980

**Comment by FedeGueli** [comment]
17 as today.

**Comment by BorisUitham** [comment]
1 in spain, with s:F855L

**Comment by FedeGueli** [comment]
20 last one from Shanghai

**Comment by BorisUitham** [comment]
That one is assigned xbb.2.3 (but it is still an interesting sequence to watch if it spreads with these mutations), here is a new query to filter that out; Spike_s256l, spike_s494p, spike_f486p, -spike_p521s

**Comment by FedeGueli** [comment]
I think this is not going anywhere , closing it for now please ping me if it will come back.
