### ISSUE TITLE
KP.3.1.1+Orf1a:E1136G, N:204Q (34 seqs, >10 places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1900]
KP.3.1.1+C1093T, T15750C+A3672G, T27244C(Orf1a:E1136G)+G28884A(N:R204Q)

GISAID query: T15750C, G28884A,A3672G
No. of seqs: 8(USA, 2 from Spain, 1 from Austria, 1 from Iceland, 2 from Norway)

First :EPI_ISL_19273432, USA from Norway, 2024-7-1
Latest: EPI_ISL_19345249, USA from Spain, 2024-8-9

This one is interesting in 3 ways.
1: mutation on N:204 like KP.3.3 (3-nuc mutation)
2: only 1 USA local, others are all GBW in different airports from different countries
3: it is donor of #1881, which is also an all-GBW recomb branch. 

It is also placed on Flip-flop branch that needs fixed @AngieHinrichs

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_32318_564730.json?label=id:node_7032156)
![image](https://github.com/user-attachments/assets/8ccc2c4d-ee75-4f88-b7b3-2814932140b3)

**Comment by aviczhl2** [comment]
11, Netherlands

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by aviczhl2** [comment]
+2 in MO and UT (new states)

**Comment by aviczhl2** [comment]
18, Germany, UK, Sweden(via GBW)

**Comment by aviczhl2** [comment]
+1 New Zealand

**Comment by FedeGueli** [comment]
slow closing it

**Comment by aviczhl2** [comment]
23, Denmark

**Comment by FedeGueli** [comment]
> 23, Denmark

more importantly two recent gbw samples from two different countries

**Comment by FedeGueli** [comment]
26 Queensland

**Comment by FedeGueli** [comment]
28 , Canada

**Comment by FedeGueli** [comment]
+1

**Comment by FedeGueli** [comment]
Still no samples from October likely slow

**Comment by FedeGueli** [comment]
Closing it for now
