### ISSUE TITLE
LB.1.1+S:M153I,A475V( 7 seqs, 4 countries, 3 with S:I68T)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1906]
LB.1.1+C1420T+T8335G, G22021T, C22986T(S:M153I,A475V)

GISAID query: G22021T, C22986T,C1420T
No. of seqs: 6(Switzerland 3 Malaysia 2 South Korea 1)
GISAID query for S:I68T sub-branch: G22021T, C22986T,C1420T,del21764_21769 

First: EPI_ISL_19220097, South Korea, 2024-6-3
Latest: EPI_ISL_19347861, Malaysia, 2024-7-15

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice13_genome_test_52fef_6c35b0.json?label=id:node_5703774)
![image](https://github.com/user-attachments/assets/92d0fc94-9a08-4e58-8390-70ebf6e52d73)

**Comment by FedeGueli** [comment]
+1 HK new country collected on August 30

**Comment by aviczhl2** [comment]
![image](https://github.com/user-attachments/assets/ae0de1aa-a9b8-4bc5-8083-707a554d63aa)

3 of the seqs have S:I68T misread as S:V70A(usher)/ S:I68del+S:V70T(GISAID) @AngieHinrichs

**Comment by FedeGueli** [comment]
Stale closing it
