### ISSUE TITLE
KP.1.1.5 with S:S680Y （ 4 countries , 40 seqs ）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1907]
KP.1.1.5>**S:S680Y**(C23601A)
GISAID Query:T21738C,-C2488T,A24819G,-C14621T,C23601A

Earliest seq:2024-06-20,EPI_ISL_19337625
Recent seq:2024-08-08,EPI_ISL_19340175

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fa5e_716ca0.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/aa9116d7-842e-4238-9438-9352b7f4bf2b)

**Comment by FedeGueli** [comment]
Duplicated of #1777

**Comment by Memorablea** [comment]
sorry

**Comment by FedeGueli** [comment]
> sorry

No worries it happens all the time,
