### ISSUE TITLE
XEC + Orf1a:I1367L (41, 11 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1908]
XEC has two main branches one defined by Orf1a:A599T the other defined by Orf1a:I1367L that is convergent with Kp.3.3.4 

Defining mutations: XEC > Orf1a:I1367L (A4364C)
Query: C19716T, C25006T,A4364C
Samples: 11
Countries: 6
Tree:
<img width="1180" alt="Screenshot 2024-08-22 alle 12 52 11" src="https://github.com/user-attachments/assets/46ac783b-392a-48af-ba30-3b6247fffe68">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1cf79_7169a0.json?c=gt-ORF1ab_1367&f_userOrOld=uploaded%20sample&label=id:node_7013744

**Comment by Memorablea** [comment]
I noticed the branche for S:157,S:158,S:403, but I am unable to locate them?

**Comment by FedeGueli** [comment]
> I noticed the branche for S:157,S:158,S:403, but I am unable to locate them?

It is likely an artifact

**Comment by Memorablea** [comment]
Canada+8.19

**Comment by FedeGueli** [comment]
It enetered a Canadian cluster so we will have perturbated growth advantage for a while unfortunately.

**Comment by FedeGueli** [comment]
> Canada+8.19

thx

**Comment by Memorablea** [comment]
Japan+1，Germany+1，Ireland+2,23now

**Comment by FedeGueli** [comment]
Thx

**Comment by FedeGueli** [comment]
+1 FInland

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by aviczhl2** [comment]
It is likely faster than XEC. Please propose. 
![image](https://github.com/user-attachments/assets/46342d0a-7e3b-4f84-bd9b-d3bcc359ea9a)

**Comment by FedeGueli** [comment]
now proposed in https://github.com/cov-lineages/pango-designation/issues/2768

**Comment by FedeGueli** [comment]
Designated XEC.2 via https://github.com/cov-lineages/pango-designation/commit/ba3711a5615956ed97150288eb68356aa0fe7cdd
