### ISSUE TITLE
GF.1 (XBB.1.5.24.1) with ORF1b:G814D (nsp12_G823D), ORF1b:Q1546H (nsp14_G22H) (552 seqs, mainly in China, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#191]
**Defining Mutations:** _on top of GF.1 (XBB.1.5.24.1)_ > A8197G > G15908A (ORF1b:G814D), G18105T(ORF1b:Q1546H)
**Query:** A8197G, G15908A
**Earliest seq:** 2023-03-15 [EPI_ISL_17494031, Jiangsu, China]
**Latest seq:** 2023-06-07 [EPI_ISL_17790291, Singapore]
**Sampled Countries:** China (367, Anhui/61, Beijing/7, Fujian/4, Guangdong/4, Heilongjiang/2, Henan/4, Hubei/10, Jiangsu/119, Jiangxi/11, Qinghai/2, Shanghai/113, Shanxi/1, Sichuan/5, Taiwan/3, Xinjiang/4, Yunnan/17), USA (11, Cali/4, NY/6, Utah/1), Singapore (4), Canada (1, Ontario), Japan (1), South Korea (1)

<details><summary>Genomes: </summary>
EPI_ISL_17494031, EPI_ISL_17505628-17505629, EPI_ISL_17505635,
EPI_ISL_17505648-17505649, EPI_ISL_17511820, EPI_ISL_17511892,
EPI_ISL_17516743, EPI_ISL_17584959-17584960, EPI_ISL_17614989,
EPI_ISL_17615012, EPI_ISL_17618432, EPI_ISL_17618482,
EPI_ISL_17618501, EPI_ISL_17618641, EPI_ISL_17618659,
EPI_ISL_17618667, EPI_ISL_17618719, EPI_ISL_17619023,
EPI_ISL_17619119, EPI_ISL_17619127, EPI_ISL_17619161,
EPI_ISL_17619185, EPI_ISL_17620292, EPI_ISL_17625285,
EPI_ISL_17625540, EPI_ISL_17625589, EPI_ISL_17625652,
EPI_ISL_17637385, EPI_ISL_17637387-17637395, EPI_ISL_17637399-17637400,
EPI_ISL_17637402-17637405, EPI_ISL_17637412, EPI_ISL_17637420,
EPI_ISL_17637440, EPI_ISL_17637446-17637447, EPI_ISL_17637467,
EPI_ISL_17637473, EPI_ISL_17637475, EPI_ISL_17637477,
EPI_ISL_17645420, EPI_ISL_17645699, EPI_ISL_17645801,
EPI_ISL_17646003, EPI_ISL_17652359, EPI_ISL_17652364,
EPI_ISL_17669050, EPI_ISL_17669084, EPI_ISL_17669111,
EPI_ISL_17669165, EPI_ISL_17672027, EPI_ISL_17678325,
EPI_ISL_17678389, EPI_ISL_17683967, EPI_ISL_17684040,
EPI_ISL_17684051, EPI_ISL_17684113, EPI_ISL_17684123,
EPI_ISL_17684180, EPI_ISL_17684265, EPI_ISL_17684276-17684277,
EPI_ISL_17684290-17684295, EPI_ISL_17684335, EPI_ISL_17684449,
EPI_ISL_17689267, EPI_ISL_17689269, EPI_ISL_17689271,
EPI_ISL_17689275, EPI_ISL_17689292-17689293, EPI_ISL_17689310,
EPI_ISL_17689312, EPI_ISL_17689347, EPI_ISL_17689434,
EPI_ISL_17696871, EPI_ISL_17696894, EPI_ISL_17696897,
EPI_ISL_17696983, EPI_ISL_17697567, EPI_ISL_17697984,
EPI_ISL_17698091, EPI_ISL_17698136, EPI_ISL_17698830,
EPI_ISL_17703735, EPI_ISL_17703964, EPI_ISL_17703991,
EPI_ISL_17714315, EPI_ISL_17714358, EPI_ISL_17714385,
EPI_ISL_17714389, EPI_ISL_17714421, EPI_ISL_17714429,
EPI_ISL_17723154, EPI_ISL_17724510, EPI_ISL_17724514,
EPI_ISL_17724978, EPI_ISL_17724981, EPI_ISL_17725015,
EPI_ISL_17725019, EPI_ISL_17725056, EPI_ISL_17725099,
EPI_ISL_17725103, EPI_ISL_17725169, EPI_ISL_17725192,
EPI_ISL_17725197, EPI_ISL_17725199-17725200, EPI_ISL_17725233,
EPI_ISL_17725241, EPI_ISL_17725243, EPI_ISL_17725250-17725251,
EPI_ISL_17725259, EPI_ISL_17725288, EPI_ISL_17725295-17725296,
EPI_ISL_17725302, EPI_ISL_17725311, EPI_ISL_17725322,
EPI_ISL_17725328-17725329, EPI_ISL_17725353, EPI_ISL_17725359,
EPI_ISL_17725371, EPI_ISL_17725461, EPI_ISL_17725477,
EPI_ISL_17725485, EPI_ISL_17725502, EPI_ISL_17728929,
EPI_ISL_17729094, EPI_ISL_17729760-17729761, EPI_ISL_17729765,
EPI_ISL_17729769, EPI_ISL_17729775, EPI_ISL_17729787,
EPI_ISL_17729791, EPI_ISL_17729966, EPI_ISL_17735956,
EPI_ISL_17738979, EPI_ISL_17739687, EPI_ISL_17739715,
EPI_ISL_17744592, EPI_ISL_17744604, EPI_ISL_17744611,
EPI_ISL_17744643, EPI_ISL_17744747, EPI_ISL_17744791,
EPI_ISL_17744794, EPI_ISL_17765823, EPI_ISL_17765848,
EPI_ISL_17765885, EPI_ISL_17765891, EPI_ISL_17765914,
EPI_ISL_17765930-17765931, EPI_ISL_17765938, EPI_ISL_17769933,
EPI_ISL_17769957, EPI_ISL_17769973, EPI_ISL_17769984,
EPI_ISL_17769990, EPI_ISL_17769998, EPI_ISL_17770042,
EPI_ISL_17770050, EPI_ISL_17770092, EPI_ISL_17770109,
EPI_ISL_17770123, EPI_ISL_17770146, EPI_ISL_17770150,
EPI_ISL_17770169, EPI_ISL_17770174, EPI_ISL_17770201,
EPI_ISL_17770206, EPI_ISL_17770226-17770227, EPI_ISL_17770231,
EPI_ISL_17770244-17770245, EPI_ISL_17770251, EPI_ISL_17770267,
EPI_ISL_17770280, EPI_ISL_17770291, EPI_ISL_17770314,
EPI_ISL_17770325, EPI_ISL_17770338, EPI_ISL_17770354,
EPI_ISL_17770411, EPI_ISL_17774029, EPI_ISL_17775176,
EPI_ISL_17775200, EPI_ISL_17775214, EPI_ISL_17775654,
EPI_ISL_17778684, EPI_ISL_17778705, EPI_ISL_17778717,
EPI_ISL_17778726, EPI_ISL_17778750, EPI_ISL_17779892,
EPI_ISL_17780121, EPI_ISL_17783137, EPI_ISL_17784868,
EPI_ISL_17784892, EPI_ISL_17785122, EPI_ISL_17785146,
EPI_ISL_17785148, EPI_ISL_17785169, EPI_ISL_17785205,
EPI_ISL_17785214, EPI_ISL_17785217, EPI_ISL_17785271-17785272,
EPI_ISL_17785277, EPI_ISL_17785287, EPI_ISL_17785289,
EPI_ISL_17785318, EPI_ISL_17785364, EPI_ISL_17788502,
EPI_ISL_17788863, EPI_ISL_17789542, EPI_ISL_17790291,
EPI_ISL_17790843, EPI_ISL_17791896, EPI_ISL_17793980,
EPI_ISL_17793983-17793985, EPI_ISL_17793987, EPI_ISL_17793989,
EPI_ISL_17793991-17793992, EPI_ISL_17793994-17793996, EPI_ISL_17793998-17793999,
EPI_ISL_17794001-17794003, EPI_ISL_17794005, EPI_ISL_17794008-17794009,
EPI_ISL_17794031-17794033, EPI_ISL_17794035, EPI_ISL_17794037,
EPI_ISL_17794041-17794046, EPI_ISL_17794049-17794051, EPI_ISL_17794053,
EPI_ISL_17794057, EPI_ISL_17794530, EPI_ISL_17794560,
EPI_ISL_17794699-17794700, EPI_ISL_17794727, EPI_ISL_17794752,
EPI_ISL_17794845, EPI_ISL_17794852, EPI_ISL_17794857,
EPI_ISL_17794884, EPI_ISL_17794981, EPI_ISL_17795016,
EPI_ISL_17795022-17795023, EPI_ISL_17795025-17795026, EPI_ISL_17795053,
EPI_ISL_17795056-17795058, EPI_ISL_17795062-17795063, EPI_ISL_17795067-17795072,
EPI_ISL_17795075, EPI_ISL_17795078-17795079, EPI_ISL_17795081,
EPI_ISL_17795083-17795084, EPI_ISL_17795086-17795088, EPI_ISL_17795108,
EPI_ISL_17795122, EPI_ISL_17795152-17795153, EPI_ISL_17795172,
EPI_ISL_17795179, EPI_ISL_17795190-17795191, EPI_ISL_17795198,
EPI_ISL_17795206, EPI_ISL_17795235, EPI_ISL_17795278,
EPI_ISL_17795296, EPI_ISL_17795332, EPI_ISL_17795347,
EPI_ISL_17795371, EPI_ISL_17795379, EPI_ISL_17795428,
EPI_ISL_17795456, EPI_ISL_17795471, EPI_ISL_17795479,
EPI_ISL_17795500, EPI_ISL_17795502, EPI_ISL_17795505,
EPI_ISL_17795524, EPI_ISL_17795528, EPI_ISL_17795532,
EPI_ISL_17795542, EPI_ISL_17795564, EPI_ISL_17795572,
EPI_ISL_17795574, EPI_ISL_17795578, EPI_ISL_17795581-17795584,
EPI_ISL_17795586-17795587, EPI_ISL_17795600-17795608, EPI_ISL_17795620,
EPI_ISL_17795626, EPI_ISL_17795652, EPI_ISL_17795656,
EPI_ISL_17795660, EPI_ISL_17795676, EPI_ISL_17795685-17795686,
EPI_ISL_17795688, EPI_ISL_17795693, EPI_ISL_17795696,
EPI_ISL_17795708, EPI_ISL_17795727-17795728, EPI_ISL_17795743,
EPI_ISL_17795746, EPI_ISL_17795768, EPI_ISL_17795777,
EPI_ISL_17795779-17795780, EPI_ISL_17795783, EPI_ISL_17795786,
EPI_ISL_17795789
</details>

**UShER:**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16dd6_a77d90.json?f_userOrOld=uploaded%20sample&showBranchLabels=all

Overview from GF.1 (XBB.1.5.24.1) polytomy
![Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d3aeb6aa-2892-4205-8715-a8061aec82ca)

Details
![Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/08521a8c-fd57-48be-97e2-206c9dc0a267)

**Comment by FedeGueli** [comment]
Please propose this one it is the main branch of XBB.1.5.24 so nothing of special interesting or different from the parental lineage but still it has a notable 5% of prevalence in Shanghai after June 15 

More just look at NSPs you indicated are wrong. Use https://codon2nucleotide.theo.io/ being carefully to distinguish between orf1a and orf1b

**Comment by Memorablea** [comment]
> Edited : being curious to see if these two relevant mutations were doing something i have redon my math, this is doubling every 9/10 days it is in the very high ranking of fast lineages. Please propose it.
> 
> @Memorablea i suggest to add this to your tracking list.

I agree with this, after all, his probability is indeed relatively high, and there is a sequence distribution in China. We will follow it.
