### ISSUE TITLE
KP.3.1.4 subbranch with S:A263V(52 seqs, 8 regions), most with further S:R765H(49 seqs, 8 regions)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1910]
KP.3.1.4> C19554T> C24034T> C22350T(S:A263V)> C2644T, G23856A(S:R765H)

Query: C8293T, C22350T, C24034T
Query for S:R765H branch: C8293T, C22350T, G23856A
Australia 10, US 2, Chile 1, Greece, Japan 1(from Australia)

Earliest sequence: 04-09 Victoria, Australia EPI_ISL_19251668
Latest sequence: 08-11 Viña, Valparaiso, Chile EPI_ISL_19353753
Regions detected: Australia 10, US 2, Chile 1, Greece, Japan 1(from Australia)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_e265_952140.json?c=country&label=id:node_7056217
![image](https://github.com/user-attachments/assets/2671d013-4700-4bd8-b9a2-4ae6d2f59fc4)

Sequences:
EPI_ISL_19192252, EPI_ISL_19197796, EPI_ISL_19203117,
EPI_ISL_19251668, EPI_ISL_19272451, EPI_ISL_19294101,
EPI_ISL_19319750, EPI_ISL_19322991, EPI_ISL_19330867,
EPI_ISL_19330881, EPI_ISL_19350098, EPI_ISL_19353010,
EPI_ISL_19353033, EPI_ISL_19353056, EPI_ISL_19353753

**Comment by Over-There-Is** [comment]
Puerto Rico

**Comment by FedeGueli** [comment]
18/15 Chile

**Comment by Over-There-Is** [comment]
Puerto Rico is a part of USA

**Comment by FedeGueli** [comment]
> Puerto Rico is a part of USA

Pls keep it separated as Taiwan Hong Kong Reunion Curacao Canary etc

**Comment by FedeGueli** [comment]
19/16

**Comment by Over-There-Is** [comment]
Greece+10

**Comment by FedeGueli** [comment]
Reappearing after a bit

**Comment by FedeGueli** [comment]
33/30 NZL for both

**Comment by FedeGueli** [comment]
First sample from october coming from NY it appears slow.

**Comment by Over-There-Is** [comment]
Sweden

**Comment by FedeGueli** [comment]
+3 Queensland all with 765H all from October

**Comment by FedeGueli** [comment]
[noticed a MK.1 + R765H found by G23856A,C4795T, t3565c, 11 samples in Canada recently but originally could be from [Chile](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41697_603890.json?c=userOrOld&label=id:node_7273520) ]

**Comment by FedeGueli** [comment]
52/49

**Comment by FedeGueli** [comment]
This is one of the few KP.3 still going on recently even if not super fast please propose it, maybe @corneliusroemer will notice it even if i think it has no chance vs LP.8

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation#2833
