### ISSUE TITLE
LB.1.4 subbranch with S:A845S and Orf9b:P>S10F (19, US 16, CA 3)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1911]
LB.1.4> C14925T, C25603T> C27012T, C28312T(Orf9b:S10F)> G24095T(S:A845S)
Query: G24095T, C27012T, C28312T

Earliest sequence: 05-25 San Francisco, California, USA EPI_ISL_19308389
Latest sequence: 08-07 Monterey, California, USA EPI_ISL_19352328
Regions Detected: US 16, Canada 3

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3f5ff_955510.json?c=country&label=id:node_7258777
![image](https://github.com/user-attachments/assets/e91c33b9-dc6c-4c5f-b69f-b285f6622615)

Sequences:
EPI_ISL_19215589, EPI_ISL_19260236, EPI_ISL_19282133-19282134,
EPI_ISL_19304572, EPI_ISL_19306379, EPI_ISL_19308389,
EPI_ISL_19308531, EPI_ISL_19311167, EPI_ISL_19314168,
EPI_ISL_19316708, EPI_ISL_19319402, EPI_ISL_19326028,
EPI_ISL_19337983, EPI_ISL_19346259, EPI_ISL_19346647,
EPI_ISL_19352311, EPI_ISL_19352324, EPI_ISL_19352328

**Comment by FedeGueli** [comment]
Orf9b:P10S is in  all Omicron-s except BQ* and few other lineages that had F there

**Comment by Over-There-Is** [comment]
> Orf9b:P10S is in all Omicron-s except BQ* and few other lineages that had F there

Typo, sorry

**Comment by FedeGueli** [comment]
Designated LB.1.4.3 via https://github.com/cov-lineages/pango-designation/commit/8536270805d19b8de746f004b6dfbbb59f08d330
