### ISSUE TITLE
KP.3.1.1 subbranch with S:I1225T and Orf1a:V2047G(39 seqs, 11 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1914]
KP.3.1.1> T6405G(Orf1a:V2047G), T25236C(S:I1225T)
Query: T6405G, T25236C
<Details><Summary>Bug solved by Usher </Summary> This branch has been split into 2 parts in usher due to the S:455-456 artefactual reversion. @angiehinrichs </details>

Earliest sequence: 05-24 Alburquerque, Badajoz, Extremadura, Spain EPI_ISL_19188412
Latest sequence: 08-02 Limburg, Netherlands EPI_ISL_19351202
Regions detected: Spain 12, Netherlands 6, Guatemala1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_2f83_96f500.json?c=country&f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/7e3ee1dc-b3c3-480c-ab05-3ba44b1f3dbf)

Sequences:
EPI_ISL_19188412, EPI_ISL_19188414, EPI_ISL_19188420,
EPI_ISL_19188435, EPI_ISL_19197147, EPI_ISL_19219066,
EPI_ISL_19244290, EPI_ISL_19260882, EPI_ISL_19260888,
EPI_ISL_19263176, EPI_ISL_19263184, EPI_ISL_19265537,
EPI_ISL_19265575, EPI_ISL_19293037, EPI_ISL_19293180,
EPI_ISL_19325139, EPI_ISL_19334446, EPI_ISL_19351202,
EPI_ISL_19351444

**Comment by AngieHinrichs** [comment]
> This branch has been split into 2 parts in usher due to the S:455-456 artefactual reversion. @AngieHinrichs

Good find @Over-There-Is.  I guess it's time for some reversion-masking in KP.3.1.1.  Should be fixed later today in 2024-08-29 tree.

**Comment by Over-There-Is** [comment]
Deutschland

**Comment by FedeGueli** [comment]
it is still splitted in two?

**Comment by Over-There-Is** [comment]
> it is still splitted in two?

no any more.

**Comment by FedeGueli** [comment]
> > it is still splitted in two?
> 
> no any more.

oh good news, i ve edited the proposal then

**Comment by Over-There-Is** [comment]
Canada

**Comment by FedeGueli** [comment]
too slow to be worth tracking it

**Comment by FedeGueli** [comment]
27, France with one super recent from Spain

**Comment by FedeGueli** [comment]
33 , 6 since Oct 1 from 4 different countries, i have tio say i wrongoed this as slow. it is not. Likely we saw it very early in Spain hence it looked like to be a slow one then

**Comment by xz-keg** [comment]
36, Portugal

**Comment by Over-There-Is** [comment]
France, Germany, Luxembourg, Netherlands, Portugal, Spain, Canada, Guatemala, US, Australia

**Comment by FedeGueli** [comment]
> France, Germany, Luxembourg, Netherlands, Portugal, Spain, Canada, Guatemala, US, Australia

5 of them in october please propose if it reaches 50

**Comment by DailyCovidCases** [comment]
Please propose this branch on the main page

**Comment by FedeGueli** [comment]
38 , England new country

**Comment by DailyCovidCases** [comment]
Dead please close this issue

**Comment by DailyCovidCases** [comment]
Likely dying off, please close it:
![Screenshot (95)](https://github.com/user-attachments/assets/22544ea0-3cf1-49c8-b404-c0f51f34b25b)

**Comment by FedeGueli** [comment]
dead
