### ISSUE TITLE
KP.3.1.7 subbranch with S:P384S (18, CA-NB)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1915]
KP.3.1.7> C21216T> C22712T
Query: C21216T, C21812A, C22712T

07-19~08-13 New Brunswick, Canada

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_12f1a_971fd0.json?c=country&label=id:node_7038079
![image](https://github.com/user-attachments/assets/13858b2e-3ec2-44db-b234-d59c8a8ca878)

Sequences:
EPI_ISL_19323776-19323777, EPI_ISL_19323788, EPI_ISL_19323798,
EPI_ISL_19351947, EPI_ISL_19351949, EPI_ISL_19351951-19351955,
EPI_ISL_19351987-19351989, EPI_ISL_19352020-19352021, EPI_ISL_19352023-19352024

**Comment by Over-There-Is** [comment]
Dead?

**Comment by FedeGueli** [comment]
Likely closing for now
