### ISSUE TITLE
KP.2.3 subbranch with S:T385I and Orf1a:E444K(66, US, 2 states)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1921]
KP.2.3> C28714T> C12085T> A18618G> G1595A(Orf1a:E444K)> C25710T> C22716T(S:T385I)
Query: G1595A, C22716T, C28714T
Queries for sample without C22716T: G1595A, -C22716T, C28714T, T4600C and G1595A, -C22716T, C28714T, C3162T

06-05~08-15 Caddo Parish, Louisiana, USA

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3f27_ab63d0.json?c=country&label=id:node_7090231
![image](https://github.com/user-attachments/assets/f2905d1c-b62b-4f01-b6c9-f7f13f62caab)

<details><summary>Sequences:</summary>

EPI_ISL_19240315, EPI_ISL_19240321, EPI_ISL_19240327-19240330,
EPI_ISL_19293511, EPI_ISL_19293520, EPI_ISL_19293523,
EPI_ISL_19293530-19293531, EPI_ISL_19293533, EPI_ISL_19293535,
EPI_ISL_19293537, EPI_ISL_19293542, EPI_ISL_19293565,
EPI_ISL_19293571, EPI_ISL_19293583, EPI_ISL_19293594,
EPI_ISL_19293599, EPI_ISL_19325198, EPI_ISL_19343160,
EPI_ISL_19343174, EPI_ISL_19343185, EPI_ISL_19343220,
EPI_ISL_19343240-19343241, EPI_ISL_19343256, EPI_ISL_19343258-19343259,
EPI_ISL_19343261, EPI_ISL_19343276, EPI_ISL_19343283,
EPI_ISL_19343286, EPI_ISL_19343296, EPI_ISL_19343299,
EPI_ISL_19343339, EPI_ISL_19343347, EPI_ISL_19343360-19343361,
EPI_ISL_19343372, EPI_ISL_19343387, EPI_ISL_19343402,
EPI_ISL_19343420, EPI_ISL_19343423, EPI_ISL_19353774
</details>

**Comment by FedeGueli** [comment]
Likely a cluster in Louisiana

**Comment by Over-There-Is** [comment]
Oregon

**Comment by Over-There-Is** [comment]
66 now (still finding the new query for 2 more dropout sequences)

**Comment by FedeGueli** [comment]
still Louisiana

**Comment by FedeGueli** [comment]
no recent samples closing it
