### ISSUE TITLE
BA.2.86.2 subbranch with S:T>K478Q  on S:S155I branch (13 sequences, 6 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1922]
BA.2.86.2> G22026T(S:S155I)> C8917T> C3602T(S:H1113Y)> C3589T> A22994C(S:K478Q)
Query: C3589T, C3602T, A22994C

Earliest sequence: 11-20 Isère, Auvergne-Rhône-Alpes, France EPI_ISL_18560545
Latest sequence: 05-23 Gaborone, Greater Gaborone, Botswana EPI_ISL_19295930
Regions Detected: UK 4, US 4(1 from South Africa, 1 from Zimbabwe, 1 not on GISAID), Botswana 3, France 1, South Africa 1

![image](https://github.com/user-attachments/assets/78e0a0f5-4e65-4d4e-84e8-f33e13171b00)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4ffa8_ac6010.json?c=country&label=id:node_7293174

Sequences:
EPI_ISL_18560545, EPI_ISL_18712688, EPI_ISL_18727255,
EPI_ISL_18731483, EPI_ISL_18731516, EPI_ISL_18754637,
EPI_ISL_18871072, EPI_ISL_18881709, EPI_ISL_18886441,
EPI_ISL_19295922, EPI_ISL_19295926, EPI_ISL_19295930,
PP318358.1

**Comment by aviczhl2** [comment]
No new seqs
