### ISSUE TITLE
JN.1.4 subbranch with S:L56V and Orf1a:L730F, F1632L on T18453C branch(5, RU-KGD)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1924]
JN.1.4> T18453C> C26022T> C2453T(Orf1a:L730F), T5159C(Orf1a:F1632L), T19119C, T21728G(S:L56V)
Query: C774T, T19119C, T21728G

05-06~05-20 Königsberg, Kaliningrad Oblast, Russia

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2b133_ad27b0.json?f_userOrOld=uploaded%20sample&label=id:node_7205196
![image](https://github.com/user-attachments/assets/bb49d21b-62f6-4192-912c-bccbac94c3d5)

Sequences: 
EPI_ISL_19297712, EPI_ISL_19297714, EPI_ISL_19297717-19297718,
EPI_ISL_19297724

**Comment by Over-There-Is** [comment]
updated

**Comment by FedeGueli** [comment]
thx!

**Comment by aviczhl2** [comment]
no new seqs
