### ISSUE TITLE
JN.1.1.5(S:R346T)+S:F456L, S680Y, Orf1b:I1293V misplaced under JN.1.1.6 (11 sequences, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1925]
Usher's placement: JN.1.1.6> G22599C(S:R346T)> C9142T> A17344G(Orf1b:I1293V), C23601A(S:S680Y)
JN.1.1.5 subbranch?
Query: A17344G, C23601A

Earliest sequence: 02-15 Songkhla, Thailand EPI_ISL_19023300
Latest sequence: 06-02 Hawally, Kuwait EPI_ISL_19213971
Regions detected: Russia 8, Kuwait 1, Thailand 1, US 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2ffb9_ad4060.json?c=country&label=id:node_7120357
![image](https://github.com/user-attachments/assets/779339b8-2fc4-4cca-881f-8b8a56ce2c17)

And Israel/ICH-741201876/2024|EPI_ISL_19283178|2024-07-14  (LB.1.3) seems also related to this branch, potential recombinant or contamination.

Sequences:
EPI_ISL_19023300, EPI_ISL_19081546, EPI_ISL_19081563,
EPI_ISL_19193275, EPI_ISL_19213971, EPI_ISL_19245567,
EPI_ISL_19260519, EPI_ISL_19297295, EPI_ISL_19297301,
EPI_ISL_19297308, EPI_ISL_19297317

**Comment by FedeGueli** [comment]
Please complete it or close.

**Comment by Over-There-Is** [comment]
updated

**Comment by FedeGueli** [comment]
Thank you @Over-There-Is !

**Comment by FedeGueli** [comment]
it is a sibling lineage of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1626

**Comment by aviczhl2** [comment]
no new seqs
