### ISSUE TITLE
JN.1.16.1 subbranch with S:E1092D (29, 5 countries, mainly in Russia)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1926]
JN.1.16.1> A24838C(S:E1092D)> T13090C
Query: C8293T, T22928C, G22599C, A24838C, -24821

Earliest sequence: 03-21 Saint Petersburg, Russia EPI_ISL_19060742
Latest sequence: 07-29 Saint Petersburg, Russia EPI_ISL_19341984
Regions detected: Russia 25, US 1, Germany 1, Italy 1, Spain 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_b709_aeeec0.json?c=country&label=id:node_7284120
![image](https://github.com/user-attachments/assets/5f9c65fa-befc-4c3b-9ded-0544eb5fa838)

Russia/SPE-RII-MH192331S/2024|EPI_ISL_19297351|2024-05-27 has both S:E1092D and S:A1087S, and usher places it under S:A1087S.

<details><summary>Sequences:</summary>

EPI_ISL_19060720, EPI_ISL_19060742, EPI_ISL_19062314,
EPI_ISL_19081515, EPI_ISL_19081529, EPI_ISL_19167054,
EPI_ISL_19190503, EPI_ISL_19190524, EPI_ISL_19216680,
EPI_ISL_19231898, EPI_ISL_19232018, EPI_ISL_19255977,
EPI_ISL_19260541, EPI_ISL_19260558, EPI_ISL_19260572,
EPI_ISL_19297310, EPI_ISL_19297320, EPI_ISL_19297363,
EPI_ISL_19297466, EPI_ISL_19297471-19297472, EPI_ISL_19297474,
EPI_ISL_19297524-19297525, EPI_ISL_19308675, EPI_ISL_19308920,
EPI_ISL_19328482, EPI_ISL_19341984, EPI_ISL_19342017
</details>

**Comment by Over-There-Is** [comment]
updated

**Comment by aviczhl2** [comment]
No new seqs
