### ISSUE TITLE
BA.2 mini saltation, single chronic? (2 seq., Canada)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#193]
Proposal for a sublineage of BA.2
Earliest sequence: 02.12.2022 (Canada)
Countries detected: Canada

Defining Mutations:
nuc	unique	T4092C, T7226C, T9530C, C10776T, A13395G, A19908G, G21604A, A22011G, A22012G, A24864G, G27084T
nuc	homoplasies	A9935G, C12789T, A22206G, A22775G, C23673T, C25521T
nuc	reversionsToRoot	A22775G
ORF1ab	unique	I1276T, F2321L, F3089L, P3504L, K4377R, I6548M
ORF1ab	homoplasies	T3224A, T4175I
S	unique	K150R, H1101R
S	homoplasies	D215G, N405D, S704L
S	reversionsToRoot	N405D
M	unique	A188S

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/54a81978-3e83-42f0-a560-cecb3881ab92)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_200c5_ac3010.json?c=pango_lineage

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/8c458ab1-f19b-47ec-a03d-d5de97153a33)

EPI_ISL_16399824
EPI_ISL_17799068

**Comment by FedeGueli** [comment]
closing it for now
