### ISSUE TITLE
KP.3.1.1 subbranch with Orf6:K42* (14, CA-ON)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1930]
KP.3.1.1> C10432T> C24337T> C2358T(Orf1a:A698V)> G4444T> A27325T(Orf6:K42*)
Query: G4444T, A27325T

08-13~17 Ontario, Canada

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_331c2_ca4170.json?c=country&label=id:node_7048038
![image](https://github.com/user-attachments/assets/38b6c824-7b5a-4fd3-abec-2f0771a84d7c)

Sequences:
EPI_ISL_19357974, EPI_ISL_19358052, EPI_ISL_19358057-19358060,
EPI_ISL_19358072-19358073, EPI_ISL_19358079

**Comment by FedeGueli** [comment]
there is also a Orf6:Q8* mini branch of Kp.3.1.1, so good to have another one proposed here

**Comment by FedeGueli** [comment]
still a cluster

**Comment by FedeGueli** [comment]
Closing it no further spread outside original cluster
