### ISSUE TITLE
KP.1.1.3 subbranch with Orf1b:Q1546H and Orf9b:G38D (122 seqs, 19 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1931]
KP.1.1.3> C15120T, G18105T(Orf1b:Q1546H), G28396A(Orf9b:G38D)
Query: C15120T, G18105T, G28396A
Query for dropout sequences: C10507T, C15120T, G18105T, -G28396A

Earliest sequence: 04-28 Rhône, Auvergne-Rhône-Alpes, France EPI_ISL_19132815
Latest sequence: 08-14 Ontario, Canada EPI_ISL_19358041
Regions detected: US 26(1 from Greece, 1 from Spain, 1 from South Korea), Canada 10, France 6, Spain 3, Ireland 2, Italy 2, Germany 1, Slovenia 1, Sweden 1, Switzerland 1, UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_264e9_cb66c0.json?c=country&label=id:node_7069094
![image](https://github.com/user-attachments/assets/e043fa0d-6b82-474a-b62f-b327087337e3)

<details><summary>Sequences:</summary>

EPI_ISL_19132815, EPI_ISL_19176380, EPI_ISL_19185650,
EPI_ISL_19189862, EPI_ISL_19191528, EPI_ISL_19191715,
EPI_ISL_19191758, EPI_ISL_19198939, EPI_ISL_19216190,
EPI_ISL_19217791, EPI_ISL_19223399, EPI_ISL_19223432,
EPI_ISL_19239298, EPI_ISL_19243912, EPI_ISL_19251991,
EPI_ISL_19254322, EPI_ISL_19258300, EPI_ISL_19259223,
EPI_ISL_19260268, EPI_ISL_19267140, EPI_ISL_19277694,
EPI_ISL_19286190, EPI_ISL_19286493, EPI_ISL_19287327,
EPI_ISL_19289101, EPI_ISL_19294328, EPI_ISL_19294332,
EPI_ISL_19294476, EPI_ISL_19294538, EPI_ISL_19298286,
EPI_ISL_19298363, EPI_ISL_19302206, EPI_ISL_19302716,
EPI_ISL_19304770, EPI_ISL_19316505, EPI_ISL_19318091,
EPI_ISL_19318591, EPI_ISL_19319858, EPI_ISL_19326194,
EPI_ISL_19326691, EPI_ISL_19327663, EPI_ISL_19329098,
EPI_ISL_19329443, EPI_ISL_19332569, EPI_ISL_19333744,
EPI_ISL_19344269, EPI_ISL_19344278, EPI_ISL_19346112,
EPI_ISL_19346116-19346117, EPI_ISL_19347691, EPI_ISL_19349203,
EPI_ISL_19349836, EPI_ISL_19354853, EPI_ISL_19358041,
EPI_ISL_19358475

Sequences without G28396A:
EPI_ISL_19240337, EPI_ISL_19240339, EPI_ISL_19293476,
EPI_ISL_19293502, EPI_ISL_19293519, EPI_ISL_19293538,
EPI_ISL_19293541, EPI_ISL_19293579, EPI_ISL_19307241,
EPI_ISL_19343163, EPI_ISL_19343310, EPI_ISL_19343321
</details>

**Comment by Over-There-Is** [comment]
Netherlands +1, Japan +1
And the Japanese case has travelling history from Vietnam and Indonesia. Which country the patient gets infected is unknown, but I think this lineage has spread to both countries.

**Comment by Over-There-Is** [comment]
US+4

**Comment by FedeGueli** [comment]
69

**Comment by FedeGueli** [comment]
No recent samples closing it

**Comment by Over-There-Is** [comment]
79

**Comment by Over-There-Is** [comment]
New York 09-20

**Comment by DailyCovidCases** [comment]
How many seq right now?

**Comment by DailyCovidCases** [comment]
Now 89 seqs

**Comment by Over-There-Is** [comment]
El Salvador via US-CA

**Comment by FedeGueli** [comment]
Still circualting hard it will be able to compete then

**Comment by Over-There-Is** [comment]
+3, NZ

**Comment by Over-There-Is** [comment]
adding 12 american dropout

**Comment by FedeGueli** [comment]
> adding 12 American dropout thx

**Comment by DailyCovidCases** [comment]
This branch can be proposed on the main page

**Comment by FedeGueli** [comment]
only 3 recent ones closing it
