### ISSUE TITLE
MC.1 subbranch with S:A942S (50 seqs, 12 countries) and further S:A626V(FR 6)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1932]
MC.1> C13297T> C14220T> G24386T(S:A942S)> C23439T(S:A626V) (edited typo)
Query: C8293T, C13297T, G24386T

Earliest sequence: 07-16 California, US (from Serbia) EPI_ISL_19289846
Latest sequence: 08-17 Barcelona, Catalunya, Spain EPI_ISL_19361195
Regions detected: France 4, Spain 3, US 3(1 from Serbia), Canada 1, Germany 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_553_cc6a40.json?c=country&label=id:node_7053477
![image](https://github.com/user-attachments/assets/f21df6a5-cd81-498f-8d00-095c16412ed7)

Sequences:
EPI_ISL_19289846, EPI_ISL_19308141, EPI_ISL_19312018,
EPI_ISL_19316977, EPI_ISL_19327643, EPI_ISL_19337445,
EPI_ISL_19338901, EPI_ISL_19357447-19357448, EPI_ISL_19357491,
EPI_ISL_19357504, EPI_ISL_19361195

**Comment by Over-There-Is** [comment]
Duplicated

**Comment by Over-There-Is** [comment]
Barcelona+1

**Comment by FedeGueli** [comment]
13 now new country Japan , it seems fast, 
btw there was a typo in the title it is S:A626V not S:A262V!

**Comment by Over-There-Is** [comment]
Ireland

**Comment by FedeGueli** [comment]
18, Sweden  , 2 more for the interesting 626V branch still only sampled in France

**Comment by Over-There-Is** [comment]
UK+1

**Comment by Over-There-Is** [comment]
CA+2 FR+1

**Comment by Over-There-Is** [comment]
Denmark

**Comment by aviczhl2** [comment]
44 seqs now

**Comment by aviczhl2** [comment]
@FedeGueli  I think this one shall be proposed

**Comment by FedeGueli** [comment]
> @FedeGueli I think this one shall be proposed
This represents around 10% of recent samples in South Australia 
@Over-There-Is please propose it

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation#2794
