### ISSUE TITLE
KP.3.1.1+S:P85S(58 seqs, >10 places) 6% in NZL

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1934]
KP.3.1.1+C21815T(S:P85S)

GISAID query: C21815T,C12616T,A13121T,-17430,-10681,C23039G,-25595,-29716,-15750,-T4579A,-9559,-19220
No. of seqs: 6(UK 3 USA 1 Portugal 1 Italy 1)

First: EPI_ISL_19321477, USA, 2024-7-11
Latest: EPI_ISL_19357802, UK, 2024-8-8

Usher seems to be putting it on a flip-flop reversion branch together with some unrelated seqs with S:85 missing coverage. This needs a fix @AngieHinrichs
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice70_genome_test_24c77_ca1b70.json?label=id:node_5490257)

![image](https://github.com/user-attachments/assets/83fa08d8-f9c7-458b-ba67-83c35c5c6bc5)

**Comment by AngieHinrichs** [comment]
> Usher seems to be putting it on a flip-flop reversion branch together with some unrelated seqs with S:85 missing coverage.

I see the flip-flop on 22858, but there are a lot of sequences that have A13121T and C12616T in common with this and that will probably keep pulling this in.  Are they really unrelated?  The path to this branch is

KP.3.1 > C22858T > A13121T > C12616T > C21815T > T22858C (rev)

Only one sequence (Italy/FVG-TS-65330394/2024|EPI_ISL_19323845) is supporting the node with C21815T, and only one sequence supports the node with A13121T (Spain/MD-H12O_282/2024|EPI_ISL_19243495), but there are a lot more seqs supporting the other nodes.

If you have a list of sequences missing coverage at S:85 then I could try prune & replace.

**Comment by aviczhl2** [comment]
> If you have a list of sequences missing coverage at S:85 then I could try prune & replace.

Get all seqs here(I don't know what's attracted to this branch in the new tree), and exclude GISAID seqs with C21815T,C12616T,A13121T, the remaining shall be missing coverage at S:85.

List of real S:P85S seqs

EPI_ISL_19321477, EPI_ISL_19323845, EPI_ISL_19327564,
EPI_ISL_19332977, EPI_ISL_19332985, EPI_ISL_19357802,
EPI_ISL_19362100

**Comment by aviczhl2** [comment]
> > If you have a list of sequences missing coverage at S:85 then I could try prune & replace.
> 
> Get all seqs here(I don't know what's attracted to this branch in the new tree), and exclude GISAID seqs with C21815T,C12616T,A13121T, the remaining shall be missing coverage at S:85.
> 
> List of real S:P85S(C21815T,C12616T,A13121T) seqs
> 
> EPI_ISL_19321477, EPI_ISL_19323845, EPI_ISL_19327564, EPI_ISL_19332977, EPI_ISL_19332985, EPI_ISL_19357802, EPI_ISL_19362100

**You shall exclude them and take everything else**

**Comment by aviczhl2** [comment]
11, France, Spain, New Zealand

**Comment by aviczhl2** [comment]
+1 Switzerland

**Comment by FedeGueli** [comment]
15 , Denmark

**Comment by FedeGueli** [comment]
21

**Comment by Over-There-Is** [comment]
T572I?

**Comment by FedeGueli** [comment]
> C21815T,C12616T,A13121T

old ones not?

**Comment by aviczhl2** [comment]
+1 Netherlands

**Comment by FedeGueli** [comment]
25 , Canada

**Comment by FedeGueli** [comment]
39 with a big batch in NZL where it is around 6%
16/39 sampled in September

**Comment by xz-keg** [comment]
47, also in Czech Republic

**Comment by FedeGueli** [comment]
Please propose it

**Comment by DailyCovidCases** [comment]
@xz-keg Please propose it

**Comment by xz-keg** [comment]
usher seems fixed the misplacement bug, and I add a lot of -s, real toll shall be 33.

**Comment by FedeGueli** [comment]
36 last samples from UK

**Comment by FedeGueli** [comment]
MMM it seems convergent evolution> multiple emergence  rather  than growth:
<img width="1147" alt="Screenshot 2024-11-26 alle 09 29 24" src="https://github.com/user-attachments/assets/b4e4a0a1-d32d-4642-9747-994efa305b54">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/singleSubtreeAuspice_genome_test_31191_584d50.json?f_userOrOld=uploaded%20sample&label=id:node_7264625

New Query: C21815T,C12616T,A13121T,-17430,-10681,C23039G,-25595,-29716,-15750,-T4579A,-9559,-19220,-C16332T,-C13297T,-G2890A,-C6286A,-C15273T,-G18734A,-A3910G,-G4709A,-A5250G

Brings it back to 41 

closing it.
