### ISSUE TITLE
KP.2.3+S:P85R(30 seqs, >10 places, 12 with S:N185K)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1936]
KP.2.3(with S:S31del)+C21816G(S:P85R)

GISAID query: C22000A,C21816G,G25593T
No. of seqs: 17(Denmark 1 UK 1 France 1 India 2 Japan 1(from Poland/Germany) Luxembourg 3 Portugal 2 Spain 2 USA 4(2 from India))

First: EPI_ISL_19190715, Portugal, 2024-5-2
Latest: EPI_ISL_19358567, USA from India, 2024-8-10

GISAID query for S:N185K sub-branch: C22000A,C21816G,G25593T,T22117G(6 seqs)

Especially the S:N185K branch deserves attention, 2 from India local, 2 from GBW-India, 1 from Japan EIS from Poland/Germany and 1 USA local.

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_241d1_d82630.json?label=id:node_5527406)

![image](https://github.com/user-attachments/assets/9bc01338-d055-4fc6-94f1-d7cdbc70a5a4)

**Comment by FedeGueli** [comment]
S:P85R is a C>G mutation

**Comment by FedeGueli** [comment]
7 from Argentina for the 185K sublineage

**Comment by aviczhl2** [comment]
22, Italy

**Comment by FedeGueli** [comment]
24 last from September

**Comment by FedeGueli** [comment]
27/12 but all samples are from an Ontario cluster , likely slowed down already .

**Comment by aviczhl2** [comment]
30, Costa Rica

**Comment by FedeGueli** [comment]
Very likely dying off better closing it.

**Comment by Over-There-Is** [comment]
35, Oman

**Comment by FedeGueli** [comment]
> 35, Oman

Thx , dead
