### ISSUE TITLE
KP.3.3 subbranch with S:L1197F(30 sequences, 4 countries, mainly in Japan)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1937]
KP.3.3> C25151T(S:L1197F)
Query: C25006T, C25151T, C28291A

Earliest sequence: 04-09 Hamamatsu, Shizuoka, Japan EPI_ISL_19309072
Latest sequence: 08-06 Saitama, Japan EPI_ISL_19341943
Regions detected: Japan 21, Korea 1, Singapore 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1281a_ddb4a0.json?c=country&label=id:node_7023187
None of the T1936G(Orf1a:N557K) branch has S:L1197F, probably misplaced.
![image](https://github.com/user-attachments/assets/6743ff5e-7df7-4ff8-9177-675a5465fd74)

Sequences: 
EPI_ISL_19182371, EPI_ISL_19193772, EPI_ISL_19197636,
EPI_ISL_19213434, EPI_ISL_19219959, EPI_ISL_19232209,
EPI_ISL_19257805, EPI_ISL_19257813, EPI_ISL_19272092,
EPI_ISL_19287550, EPI_ISL_19287776, EPI_ISL_19287779,
EPI_ISL_19305375-19305376, EPI_ISL_19309072, EPI_ISL_19319364,
EPI_ISL_19340383, EPI_ISL_19341943, EPI_ISL_19341945,
EPI_ISL_19342635, EPI_ISL_19352543, EPI_ISL_19360822,
EPI_ISL_19360832

**Comment by Over-There-Is** [comment]
US+5, 3 from Japan, 2 pooled

**Comment by Over-There-Is** [comment]
Japan+1

**Comment by FedeGueli** [comment]
it seems very slow.

**Comment by Over-There-Is** [comment]
Yamaguchi

**Comment by FedeGueli** [comment]
No recent samples closing it

**Comment by Over-There-Is** [comment]
chiba, tochigi, nara, nagano, hokkaido

**Comment by FedeGueli** [comment]
> chiba, tochigi, nara, nagano, hokkaido

No one recent
