### ISSUE TITLE
MC.2 + S:K440R (17 US, Scotland, Canada)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1939]
MC.2>>S:K440R (A22881G)
Query: 22881G,G24095T,del21653
Samples: 3 on Gisaid plus one from Scotland only on Climb Uk
Countries: US(NJ,NC), Scotland
Tree:
<img width="1144" alt="Screenshot 2024-08-27 alle 18 40 14" src="https://github.com/user-attachments/assets/0bc40b4a-5dbe-466e-acb0-2aa8cfedd7aa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_90d2_e00030.json?label=id:node_7052770

**Comment by FedeGueli** [comment]
closing this

**Comment by FedeGueli** [comment]
7, one new from september reopening for a while

**Comment by xz-keg** [comment]
16 seqs now. Canada and multiple USA states.
And the Scotland seq seems not on GISAID, so total shall be at least 17.

**Comment by FedeGueli** [comment]
I ve reopend this, but it doubt it is going anywhere
