### ISSUE TITLE
LB.1.2.2 with ORF7a:T39I and S:L456V (7 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1948]
**Defining Mutations:** **`LB.1.2.2`** > `C23029T(S:Y489Y)` >` C27509T(ORF7a:T39I)` > `T22928G(S:F456V,` _`or F>L456V/C22928G),`_`C27513T`
**Query:** `G19669A, T22928G`
**Earliest seq:** 2024-08-04 (`EPI_ISL_19331508`, Ontario, Canada)
**Latest seq:** 2024-08-12 (`EPI_ISL_19345664`, Ontario, Canada)
**Sampled Countries:** Canada (7: ON)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/ON-KHS-03663-v1/2024
Canada/ON-KHS-03681-v1/2024
Canada/ON-KHS-03743-v1/2024
Canada/ON-KHS-03758-v1/2024
Canada/ON-KHS-03765-v1/2024
Canada/ON-KHS-03838-v1/2024
Canada/ON-KHS-03842-v1/2024
```

epi_isl accessions:
`EPI_ISL_19331492, EPI_ISL_19331508, EPI_ISL_19345603, EPI_ISL_19345616, EPI_ISL_19345623, EPI_ISL_19345660, EPI_ISL_19345664`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a82b_eac0a0.json?label=id:node_7270524
![image](https://github.com/user-attachments/assets/c4ee4544-0ba9-4338-95cd-040e85b95aac)

**Trivia:**
- There's a set of synonymous and a non-synonymous mutations in the adjacent codons of ORF7a
![image](https://github.com/user-attachments/assets/3fb82df9-cb75-4d71-bf68-3f3ad96e6908)
- This lineage has 2 synonymous mutations on Spike: `C22075T (S:V171V, from parent LB.1.2.2)`, `C23029T(S:Y489Y)`
- It's interesting to see `S:F456L` to further mutate into `S:F456V`, if it is not invovled in recombination, nor an UShER misplacement (labelled as `JN.1.18.3` on GISAID)
- It could just be a single cluster.

**Comment by ryhisner** [comment]
ORF7a:T39I shows up in chronics all the time. It also occurs in circulating lineages, but not as often. It's one of many ORF7a mutations convergent in chronics, which makes me think it has to be doing something, though I'm not sure what.
