### ISSUE TITLE
FL.3.3 with E:P71L, orf8:D34n, orf1b:s2212n (nsp15:s161n) in Wales (39 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#195]
Similar to issue #194 , same story with e:p71l:
P71L on the envelope protein is slightly stabilizing (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7723457/) and is thought to be related to VOC cell lethality (https://www.biorxiv.org/content/10.1101/2023.01.09.523338v1)

No metadata, could very well be a long term hospital/care facility outbreak so lets watch this
![Screenshot_20230707_140631_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/51f50019-c467-4af0-982c-30ead6c55428)
![Screenshot_20230707_140651_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/73d814d6-d397-49a1-83f8-2040017b168e)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_34eee_7fdef0.json?c=gt-E_71&label=id:node_6694289&showBranchLabels=all

First: 2023-05-23
Latest: 2023-06-18
Query:  G27993A, C26456T, G9257A, G2579A

**Comment by FedeGueli** [comment]
It seems circulating quite well in Wales

**Comment by BorisUitham** [comment]
![Screenshot_20230704_213522_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/6e9125c3-c833-4be4-9760-1a93ef86db6d)

This is the new tree for wales. Perhaps the tree in my first post did indeed have three separate incidents of e:p71l arising from fl.3.3.

Whole fl.3.3 view:
![Screenshot_20230704_213715_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/e9cbcd0a-30fe-40b7-9472-3a6524a32fe3)

**Comment by FedeGueli** [comment]
@BorisUitham please specify your proposal splitting the three lineages if they are all caught by the same query or explaining which one you want to propose  here with its specific query. Thx!

**Comment by BorisUitham** [comment]
Since the other two branches are dead ends, i'd focus on the wales one. Which jumped to 39 sequences.

**Comment by FedeGueli** [comment]
m closing this , please keep it checked tough.
