### ISSUE TITLE
LB.1 + S:K478T (rev) + S:E96V emerged in Nepal (10) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1953]
There is another LB.1 sublineage different from LB.1.9 that got the uptrending S:K478T reversion.
In addition it has S:E96V that has been sampled 1500 times in the course of the pandemic mostly in a sublineage of AY.98 that accounts for 80% of the total S:E96V and in Uk it was [faster](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/AllTimes/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nextcladePangoLineage=AY.98*&aaMutations1=S%3AE96V&nextcladePangoLineage1=AY.98*&analysisMode=CompareToBaseline&) than basic AY.98

The interesrting thing of this LB.1 is that it comes from Nepal with 3/7 samples being from there

Defining mutations:
LB.1> S:K478T (rev A22995C) > G29254A > S:E96V (A21849T)
Query:  A21849T,G29254A
Samples: 7 (Nepal 3 ) US (4 , Ohio,NY)

Tree:
<img width="1170" alt="Screenshot 2024-08-28 alle 13 34 27" src="https://github.com/user-attachments/assets/2e9adc0f-3fc2-419f-a74b-d41966ccd6e4">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice61_genome_test_3e2da_edac70.json?label=id:node_7270368

**Comment by aviczhl2** [comment]
10 seqs including a new GBW sample from India. 

Please propose this one.

**Comment by FedeGueli** [comment]
Proposed in https://github.com/cov-lineages/pango-designation/issues/2769
