### ISSUE TITLE
KP.2.3 + S:ins182ERA (ins22108_GAGAGAGCG) [65 Seqs, Nov 26]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1955]
**Description**
**Sub-lineage of:** KP.2.3
**Earliest sequence:** 2024-5-20, Singapore, EPI_ISL_19181759
**Most recent sequence:** 2024-8-19 (2 Canada, 1 Utah, USA)
**Continents circulating:** North America (17), Asia (5), Europe (3)
**Countries circulating:** USA (15), Singapore (4), Canada (2), France (1), Nepal (1), Netherlands (1), Scotland (1)
**Number of Sequences:** 25
**GISAID Nucleotide Query:** GAGAGAGCG, -GAGAGAGCGGGA, -ins22303, -ins3856, -ins9442
**CovSpectrum Query:** Nextcladepangolineage:KP.2.3* & 
**Substitutions on top of X:**
**Spike:** ins182_ERA
**Nucleotide:** C2710T, C5144T, ins22108_GAGAGAGCG

**Phylogenetic Order of Mutations:** C2710T **→** C5144T 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.2.3_ins182_ERA.json?c=gt-nuc_5144&gmax=6144&gmin=4144&label=id:node_7082006
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/9ad4e3ef-b956-43da-80bc-0922d4a87433">

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/20d33b82-4666-4e93-b9a0-8bbc1c7c6d9b">

**Evidence**
This is a strange insertion. It’s showed up at least three times independently—once in ~23 EG.5.1.1, mostly in Russia, in late 2023, but with an additional GGA at the end, making the insertion S:214_ERAG (ins22204_GAGAGAGCGGGA). The exact insertion in this lineage also showed up as S:247_ERA in a JG.3 in California in late 2023 (ins22303_GAGAGAGCG). 

These sequences get scattered about the Usher tree a bit, though there’s no doubt that they belong together, so the tree linked to above is not complete. There’s also a good chance that this insertion has been missed. 

It's been around for a long time—the first sequence was in May—so I don't think it's going to grow quickly or anything. But there's been a weird resurgence lately, so it's worth noting, if only because it's at least the 3rd time this insertion has appeared, though it has been in different locations in the spike NTD each time.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19181759, EPI_ISL_19227579, EPI_ISL_19228251,
EPI_ISL_19262559, EPI_ISL_19268178, EPI_ISL_19289247,
EPI_ISL_19293252, EPI_ISL_19300025, EPI_ISL_19304320,
EPI_ISL_19306394, EPI_ISL_19326056, EPI_ISL_19327260,
EPI_ISL_19328897, EPI_ISL_19332448, EPI_ISL_19332530,
EPI_ISL_19332580, EPI_ISL_19335108, EPI_ISL_19335319,
EPI_ISL_19350125, EPI_ISL_19358349, EPI_ISL_19358522,
EPI_ISL_19359709, EPI_ISL_19360419, EPI_ISL_19361639,
EPI_ISL_19361956
</details>

**Comment by FedeGueli** [comment]
thx Ryan for proposing

**Comment by FedeGueli** [comment]
29, i dont think it has any chance to compete i would close this

**Comment by FedeGueli** [comment]
This has managed to enter some Canadian cluster and to be sampled in a traveler from Mexico at the end of September reopening for a while

**Comment by FedeGueli** [comment]
59 with 6 recent samples i have to reopen it

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
Not fast enough. I hope @corneliusroemer when has finished to look at most urgent designations as he is doing greatly will examine if deisgnate or not the secondary lineages of interest for mutational profile

**Comment by FedeGueli** [comment]
65 but likely limited to canadian cluster only closing for now

**Comment by Over-There-Is** [comment]
69

**Comment by Over-There-Is** [comment]
some with alternative insertion, like ins182ESA(ins22108GAGAGCGCG, 2) or ins182ARA(ins22108GCGAGAGCG, 1). And there are 2 dropout sequences, 1 with only 1 seq inserted, and 1 without coverage around S:182.
Alternative query: C5144T, ins22108 (71)
dropout: C28714T,C2710T,C5144T, -ins22108(1)
dropout: ins22108GAGAGAGCG, -C5144T(2)

**Comment by FedeGueli** [comment]
70 w ins22108GAGAGAGCG , dead
