### ISSUE TITLE
LP.1.2+Orf1a:P1207H+S:445P( 18 seqs, 3 countries)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1957]
LP.1.2+C3885A(Orf1a:P1207H)+A22896C(S:H445P)

GISAID query: C3885A, T22896C, G22132T
No. of seqs: 7(USA 6 Denmark 1)

First: EPI_ISL_19289456, USA-FL, 2024-7-3
Latest: EPI_ISL_19350321, USA-GA, 2024-8-12

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_59cf8_ff5d50.json?label=id:node_5540713)
![image](https://github.com/user-attachments/assets/5770d90b-f7c0-4eac-aa0e-849a5733bbe4)

**Comment by FedeGueli** [comment]
+1 Puerto Rico

**Comment by FedeGueli** [comment]
likely dying but three samples at the start of september from three different states, worth waiting a bit before closing it

**Comment by FedeGueli** [comment]
Dying off

**Comment by FedeGueli** [comment]
Designated LP.1.2.1 via https://github.com/cov-lineages/pango-designation/commit/dd477c4a513dacccb7e6bce6b761dc88c632d1c0#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R4668
