### ISSUE TITLE
KP.4.2 with ORF1a:Q575R (nsp2_Q395R), S:F59S and S:K187S (12 seqs, Nepal, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1958]
**Defining Mutations:** `KP.4.2` > `A1989G(ORF1a:Q575R)` > `T21738C(S:F59S), A22123T(S:K187S, or K>R187S)`
**Query:** `A1989G, C6070T, A22123T`
**Earliest seq:** 24-04-19 (`EPI_ISL_19091396`, Texas, USA)
**Latest seq:** 24-08-08 (`EPI_ISL_19359876`, Maryland, USA)
**Sampled Countries:** USA(7: MD/4; NY; TX; UT), Nepal (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Nepal/NPHL-S-2639/2024
USA/MD-HP51720-PIDUCKLEEC/2024
USA/MD-MDH-10274/2024
USA/MD-MDH-10443/2024
USA/MD-UM-G44S50I9/2024
USA/NY-PRL-240715_82H09/2024
USA/TX-DSHS-26520/2024
USA/UT-UPHL-240628420835/2024
```

epi_isl accessions:
`EPI_ISL_19091396, EPI_ISL_19226473, EPI_ISL_19239507, EPI_ISL_19277589, EPI_ISL_19327780, EPI_ISL_19328862, EPI_ISL_19333097, EPI_ISL_19359876`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2b8dd_473a0.json?label=id:node_7073217
![image](https://github.com/user-attachments/assets/95ba8231-b7e9-4246-bd2b-8c549185b08f)

**Trivia:**
- Not a fast one it seems, but persisting. Placed as a side branch to `b21` of #1502 , albeit this proposed lineage does not have `S:S31Δ`
- It further mutates KP.4.2's `S:K187R(A22122G)` to `S:K187S(A22122G, A22123T)` which is likely to form an N-linked glycan with N185
![image](https://github.com/user-attachments/assets/55efd5f5-27e3-42c0-b50c-d61940d8c7da)

**Comment by ryhisner** [comment]
Just want to note here that K187S creates a glycan at N185, just a little upstream of the more common N188 glycan (caused by either R190S or R190T).

**Comment by FedeGueli** [comment]
+1
