### ISSUE TITLE
LB.1.3 with S:T76I (30 seqs, USA)

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1960]
LB.1.3>G25500T>**S:T76I(C21789T)**

At present, this branch is just an ambiguous small cluster from the USA.
GISAID Query:`G25500T,C21789T,A7842`

UshER Tree:
![image](https://github.com/user-attachments/assets/7c8f446d-45cb-4c2e-b809-da74db5e3f28)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f09e_167d50.json?label=id:node_7279228

**Comment by FedeGueli** [comment]
Yeah not very recent , worth tracking it here for a bit.

**Comment by Memorablea** [comment]
USA+2.22NOW

**Comment by Over-There-Is** [comment]
28

**Comment by FedeGueli** [comment]
30, none recent closing it
