### ISSUE TITLE
KP.3.3 with ORF1a:E1801K, 16 get S:Q52R(23 seqs,3 countries,mainly found in Japan)

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1961]
**KP.3.3>ORF1a:E1801K>S:Q52R**

- KP.3.3>ORF1a:E1801K GISAID Query:`G5666A,A19515G`
- KP.3.3>ORF1a:E1801K GISAID Query:`C14931T, A21717G,A7842`

EPI_ISL ID:
EPI_ISL_19169494, EPI_ISL_19175063, EPI_ISL_19220084,
EPI_ISL_19231498, EPI_ISL_19243275, EPI_ISL_19251515,
EPI_ISL_19260370, EPI_ISL_19269574, EPI_ISL_19279924,
EPI_ISL_19305311, EPI_ISL_19305320, EPI_ISL_19306049,
EPI_ISL_19309059, EPI_ISL_19315723, EPI_ISL_19341659,
EPI_ISL_19348232, EPI_ISL_19348245, EPI_ISL_19348329,
EPI_ISL_19359020, EPI_ISL_19363400, EPI_ISL_19363484,

UshER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12b7_17a420.json
![image](https://github.com/user-attachments/assets/c9cea90e-b3d6-4a81-8554-218506ceb915)

**Comment by FedeGueli** [comment]
23/15

**Comment by FedeGueli** [comment]
No recent samples closing it
