### ISSUE TITLE
KP.3.3 and MC.13 branches with S:Q613E

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1962]
<a name="task_header"></a>

```[tasklist]
### Tracking Lineages with `S:Q613E(C23399G)`
- [ ] [Branch 1](#branch_1) `KP.3.3` > `C1567A(ORF1a:N434K), C7840T, C13647T, G18811A(ORF1b:D1782N), C23399G(S:Q613E)`, query: `C7840T, C23399G`, 10 seqs, South Korea, as of Sep27
- [x] [Branch 2](#branch_2)Designated **MC.13.3** Transferred to cov-lineages/pango-designation#2793 phylogenetic tree follows: `MC.13` > `C23399G(S:Q613E)`, query: `C10681T, A13121T, C23399G`, 20 seqs, 3 countries, as of Sep 23
```

<a name="branch_1"></a>
### Branch 1

**Defining Mutations:** `KP.3.3` > `C1567A(ORF1a:N434K), C7840T, C13647T, G18811A(ORF1b:D1782N), C23399G(S:Q613E)`
**Query:** `C7840T, C23399G`
**Earliest seq:** 24-07-10 (`EPI_ISL_19340504`, South Korea)
**Latest seq:** 24-08-02 (`EPI_ISL_19368942`, South Korea)
**Sampled Countries:** South Korea (7)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
SouthKorea/KDCA293766/2024
SouthKorea/KDCA294088/2024
SouthKorea/KDCA294242/2024
SouthKorea/KDCA294249/2024
SouthKorea/KDCA294368/2024
SouthKorea/KDCA294426/2024
SouthKorea/KDCA294598/2024
```

epi_isl accessions:
`EPI_ISL_19340504, EPI_ISL_19340826, EPI_ISL_19352454, EPI_ISL_19352461, EPI_ISL_19352569, EPI_ISL_19352626, EPI_ISL_19368942`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40fcb_1e08c0.json?label=id:node_7059740
![image](https://github.com/user-attachments/assets/ba6cc154-86d6-4f97-8150-f1d290e97608)

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2

<details><summary>Transferred to main repo</summary>

_Transferred to cov-lineages/pango-designation#2793_

**Defining Mutations:** `MC.13` > `C23399G(S:Q613E)`
**Query:** `C10681T, A13121T, C23399G`
**Earliest seq:** 24-06-13 (`EPI_ISL_19265922`, Portugal)
**Latest seq:** 24-08-23 (`EPI_ISL_19385724`, Brazil)
**Sampled Countries:** Brazil (5: MS), Spain (1), Portugal (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Portugal/PT51065/2024
Brazil/MS-FIOCRUZ-FMS306/2024
Brazil/MS-FIOCRUZ-FMS311/2024
Spain/CT-LabRefCat-3669331/2024
Brazil/MS-FIOCRUZ-FMS319/2024
Brazil/MS-FIOCRUZ-FMS333/2024
Brazil/MS-FIOCRUZ-FMS340/2024
```

epi_isl accessions:
`EPI_ISL_19265922, EPI_ISL_19340619, EPI_ISL_19340624, EPI_ISL_19374899, EPI_ISL_19385707, EPI_ISL_19385718, EPI_ISL_19385724`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_899a_27b950.json?label=id:node_7127826
![image](https://github.com/user-attachments/assets/6b61cbd0-c3a6-4daa-9789-fb2f01e72507)

</details>

[Back to Tasklist](#task_header)

**Trivia:**
- Just to track the rare `C>G` mutation on residue 613, `Q613E` is much less popolar than famous `Q613H`, only sampled about 2K times during the whole pandemic.

**Comment by FedeGueli** [comment]
Thx for the spot on MC.13 too

**Comment by FedeGueli** [comment]
> the MC.13 branch goes up to 7 seqs (all newly added ones from Brazil)

propose it please

**Comment by FedeGueli** [comment]
> the MC.13 branch goes up to 7 seqs (all newly added ones from Brazil)

please propose it

**Comment by FedeGueli** [comment]
> latest seq from `Branch 1` is a mini-saltation ![image](https://private-user-images.githubusercontent.com/125747944/367656155-eef69ba2-9e38-4594-8fab-995488e1381b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzM5NzgsIm5iZiI6MTcyNjQ3MzY3OCwicGF0aCI6Ii8xMjU3NDc5NDQvMzY3NjU2MTU1LWVlZjY5YmEyLTllMzgtNDU5NC04ZmFiLTk5NTQ4OGUxMzgxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQwODAxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmU3OTBkNWIzYTY3Mzk1M2M3OTFlMTEyNWJlNzE3OTAxMWUyOWZmZTkzNWJiM2ZhMWI4MGRiZDBmYWIwOTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G88aHFMIbQol8UcURoc1Uic-XA9N8nPwYI3NyZ0eXlQ)

did u check for MOV use for that? >> https://movbranchapp.streamlit.app/

**Comment by FedeGueli** [comment]
Br.2 went to 20 with a BRazilian batch of very recent sequences please propose it

**Comment by FedeGueli** [comment]
+1 for BR.1

**Comment by FedeGueli** [comment]
Designated MC.13.3 via https://github.com/cov-lineages/pango-designation/commit/16205e716c6a68ff1c3d0f26f0c77478682368ac#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1289
