### ISSUE TITLE
KP.2.14 (with S:22N) + ORF1a:T2183I + ORF1a:S443T + S:A435S (12)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1964]
![image](https://github.com/user-attachments/assets/bcc387d5-3bcd-40fe-b4d4-1f576dfea75b)
![image](https://github.com/user-attachments/assets/97c37933-a917-424a-9809-a27909d924a7)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10035_20b050.json?f_userOrOld=uploaded%20sample

First Seq: 2024-07-12
Most Recent: 2024-08-19

Gisaid: C24700T, G22865T

PQ211668.1 PQ237420.1 EPI_ISL_19301636 PQ147761.1 PQ237609.1 PQ061078.1 PQ237497.1

**Comment by FedeGueli** [comment]
KP.2.14 has already S:T22N as defining ( it was designated KP.2.14.1 and then retracted) . Great catch one to watch!

**Comment by FedeGueli** [comment]
7 on Gisaid last one from Illinois, very recent one

**Comment by xz-keg** [comment]
designated KP.2.14.2
