### ISSUE TITLE
BA.2 Saltation, 20+ spike mutations (3 seq - one retracted, apparently 1 chronic patient or maybe 2 different patients)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1965]
**Description**
**Sub-lineage of:** BA.2
**Earliest sequence:** 2024-7-14, Spain – EPI_ISL_19322462
**Most recent sequence:** 2024-7-16, Spain – EPI_ISL_19370418
**Continents circulating:** Europe (2)
**Countries circulating:** Spain (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** G278A, T11075A, -C46G
**CovSpectrum Query:** Nextcladepangolineage:BA.2* & [10-of: G278A, C1616T, A3406G, A5391G, C6286T, C7081T, T11075A, C11572T, G12028A, C14120T, T16389C, T17543C, A18273G, C18326T, A20355G]
**Substitutions on top of BA.2:**
**Spike:** P9L, Q14H, ∆Y144, S151C, F157L, R190K, H245N, R346T, N354K, L368I, K444R, K478E, A484E (reversion), F490S, T547K, A688V, T747I, T883I, D1118H, E1202Q, P1263L
**N:** A90S
**M:** D3Y
**ORF8:** F120V, I121L (N/ORF9b TRS extended homology)
**ORF9b:** S50L, E86D
**ORF1a:** V5I, L451F, N1709S, F3604I, L3606F, M3921I
**ORF1b:** P218L, M1359T, A1620V

**Nucleotide:** G278A, C1616T, A3406G, A5391G, C6286T, C7081T, T11075A, G11083T, C11572T, G12028A, C14120T, T16389C, T17543C, A18273G, C18326T, A20355G, C21588T, C21595T (artifact?), G21604T, A22013T, C22033A, G22131A, C22264T, C22295A, G22599C, C22624A, C22664A, A22893G, A22994G, T23031C, T23134C, C23202A, C23625T, C23802T, T24487C, G24914C, C26222T, G26529T, C27059T, T28251G, A28254C, C28432T, G28541T, A29125G, C29642T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons3/main/BA.2_saltation_Spain_July_2024.json?label=id:node_11626229
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/67a1544a-a3ea-4575-9901-dfbdbabfa988">

**Evidence**
The metadata indicate that these two BA.2 sequences came from different patients. Both were collected in mid-July, 2024, in the same region of Spain. The sequence quality for both is not great, with some dropout and frameshifts, so there are likely additional deletions and substitutions not visible. 

Several of the spike mutations I've listed above do not show up in the first sequence collected due to dropout and/or frameshifts, but I am assuming they are present in both sequences. 

I might add some more analysis later, but for just a few short notes.

• S:P9L and S:S151C, this BA.2 branch has replaced the C15-C136 spike NTD disulfide bond with a C136-C151 disulfide, likely causing a substantial rearrangement of the NTD. 
• T11075A (ORF1a:F3604I) is extraordinarily rare. It has only ever appeared in 7-8 previous sequences. This branch also has the highly homoplasic ORF1a:L3606F, though that site is masked by Usher.
• A few notable mutations seen in previous major variants:
  —S:H245N (creates glycan) - BA.2.3.20, BA.2.86
  —S:D1118H - Alpha (B.1.1.7)
  —M:D3Y - BJ.1 (which later recombined with a BA.2.75 descendant to form XBB)

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19322462, EPI_ISL_19370418
</details>

**Comment by FedeGueli** [comment]
First few analysis of mutations:
S:Q14H was very good in FLiP lineages especially in China but here the S:P9L could change everything so not sure about its effect here.
S:L368I is a comeback from XBB
S:547-1263 are all know mutations we saw here and there and for sure not detrimental at least:
547K is doing very well now in KP.3.3.1
688V is around since bQ.1 in mutliole designated lineage the last ones are JN.1.15/LU.1/LU.2 and descendants
S:T747I was in BA.2.51 and XBB.1.44.1
S:T883I was popular since BQ.1 CH.1 and XBB.1 era
S:E1202Q was popular in the VOCs era while S:E1202K is very widespread in combination with a silent nuc at 1201. 
S:D1118H was in all Alpha
S:P1263L is circualting in LF.1.1.1 and XED
M:D3Y was in BJ.1 that then recombined to give birth to XBB
Orf1b:P218L was in FY.1.2
Orf9b:E86D/N:A90S was in BF.7.4.3 that shares also S:F157L with this (see https://github.com/cov-lineages/pango-designation/issues/1743)

**Comment by FedeGueli** [comment]
Sorry i just saw Ryan already upodated while i was writing the comment.

**Comment by FedeGueli** [comment]
Alternative queries to check for it : T24487C, C26222T, G26529T or G278A, A3406G, A5391G to target different parts of the genome and catch eventually recombs.

**Comment by FedeGueli** [comment]
ping @corneliusroemer 
cc @silcn @oobb45729 @thomasppeacock @angiehinrichs @shay671

**Comment by corneliusroemer** [comment]
Thanks for the ping, interesting stuff - but of course not ready for designation given just 2 sequences from same region (i.e. could be just 2 people from same household, one of which is chronic themselves). Stuff I'd check next: where does it actually descend from (placement on Usher is in some reversion island = artefactual) and could it be recombinant of something?

**Comment by ryhisner** [comment]
> Sorry i just saw Ryan already updated while i was writing the comment.

No worries, your comments are great!

**Comment by FedeGueli** [comment]
> > Sorry i just saw Ryan already updated while i was writing the comment.
> 
> No worries, your comments are great, Fede!

thanks Ryan! one thing i missed to mention: the 478E plus 484E (rev): 478E is quite trending lately in multiple lineages without giving big advantages tough, interestingly it was one of the first spike mutations picked up by BA.2.86 in South Africa very early in its spread: they didnt anything but maybe that was the first hint that RBD could like a negative charge in the RBM, and note that the second Ba.2.86 RBD mutation in South Africa was S:N487D ( that is likely still around there), anotehr negative charged AA. This BA.2 takes two if the reversion is real.

**Comment by cvejris** [comment]
The combo Orf1a: F3604I+L3606F is interesting, both by proximity of the amino acids and also because neither is caused by the otherwise prevalent transition mutations (T11075A+G11083T)

**Comment by ryhisner** [comment]
One early study on Alpha noted that D1118H, which is near the base of the spike, could could interact with D1118H from the other spike protomers and may cause a local rearrangement. 
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/b6b21ee0-7503-4411-a1c3-6ef33c3aadba">
Gobeil SM, Janowska K, McDowell S, et al. Effect of natural mutations of SARS-CoV-2 on spike structure, conformation, and antigenicity. Science. 2021;373(6555):eabi6226. doi:10.1126/science.abi6226

**Comment by corneliusroemer** [comment]
I reached out to the submitter via Twitter so that they know about the discussion here.

Just in cases one of the submitters comes across this here - all the people here are extremely grateful to your continued work sequencing and rapidly sharing the data.

**Comment by ryhisner** [comment]
> > > Sorry i just saw Ryan already updated while i was writing the comment.
> > 
> > 
> > No worries, your comments are great, Fede!
> 
> thanks Ryan! one thing i missed to mention: the 478E plus 484E (rev): 478E is quite trending lately in multiple lineages without giving big advantages tough, interestingly it was one of the first spike mutations picked up by BA.2.86 in South Africa very early in its spread: they didnt anything but maybe that was the first hint (before 493E) that RBD could like a negative charge in the RBM, and note that the second Ba.2.86 RBD mutation in South Africa was S:N487D ( that is likely still around there), another negatively charged AA. This BA.2 takes two negatively charged AA if the reversion is real.

The combination of S:S477N and S:K478E creates a TRS motif. I suspect it's deleterious. There are no open reading frames (the first start codon goes ~26 codons before hitting a stop), and anything it would produce is probably junk in any case. It could increase the proportion of subgenomic RNA relative to genomic RNA, though at the cost of being very inefficient.
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/8b930d3c-df48-49ee-acb8-4af42a01e6ce">

**Comment by corneliusroemer** [comment]
Importantly, the assemblies are quite sketchy - possibly due to low coverage/low viral load, or also maybe dropout due to the many mutations.

I wouldn't be confident about the number of spike substitutions now based on what we see here:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5e3ed557-9349-45b1-a111-63ecaee988de">

Nextclade places it on the BA.2 branch with C9866T (i.e. not the BA.2 that's predominantly Southern African and also BA.2.86 ancestor) and also extra C25416T, the parent of BA.2.12.2 and BA.2.75 and more.

**Comment by ryhisner** [comment]
> Importantly, the assemblies are quite sketchy - possibly due to low coverage/low viral load, or also maybe dropout due to the many mutations.
> 
> I wouldn't be confident about the number of spike substitutions now based on what we see here: <img alt="image" width="1728" src="https://private-user-images.githubusercontent.com/25161793/363349294-5e3ed557-9349-45b1-a111-63ecaee988de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNTgxNjMsIm5iZiI6MTcyNTA1Nzg2MywicGF0aCI6Ii8yNTE2MTc5My8zNjMzNDkyOTQtNWUzZWQ1NTctOTM0OS00NWIxLWExMTEtNjNlY2FlZTk4OGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIyNDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMzI0MTU1ODdiM2FjMzZmMjJkOTQ5Yzc4Y2Y2OTRjYzZhY2Q3OGQwMDhkZjc4M2Y3NDE0NTkyYzgzZmFlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tWono3sdyYnrrQXQ0Zcfjv7eiOz9MBoo3AuzCZN-byQ">
> 
> Nextclade places it on the BA.2 branch with C9866T (i.e. not the BA.2 that's predominantly Southern African and also BA.2.86 ancestor) and also extra C25416T, the parent of BA.2.12.2 and BA.2.75 and more.

All the sequences from the upload by this lab look like this, so I don't think it can tell us much about the viral load.
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/498ad32c-f52e-484e-bd1e-269b21ae852f">

**Comment by FedeGueli** [comment]
> and also extra C25416T, the parent of BA.2.12.2 and BA.2.75 and more.

oh that one! many of the fastest BA.2 descendants, saltations came from that branch! and also XBB had it via Ba.2.75

**Comment by corneliusroemer** [comment]
I think I've found the likely ancestor branch, evidence is strong because it's 2-fold:

I looked for the BA.2 lineages with the biggest mutational overlap with this cluster using covSpectrum (excluding Spike).

Clear hit in Spain, BA.2 sublineage sampled in the same Spanish state in April/May 2022.

<img width="1349" alt="Brave Browser 2024-08-31 04 08 13" src="https://github.com/user-attachments/assets/286bae2e-7a97-4305-b0c8-810cda29dcdc">

<img width="1361" alt="Brave Browser 2024-08-31 04 08 26" src="https://github.com/user-attachments/assets/0e13b11b-4127-4e61-8fcd-1f58e356f641">


So we're looking at a local 2y chronic infection (maybe more than one chronic infectee involved) and now it got sequenced in 2 people. Possibly one of the 2 sequences is from one of the chronic infectees, that leaves one more who got it somehow and got sequenced. Hard to interpret unless we know how samples were selected.

Fact that it got sequenced where it came form means it's unlikely to have a big population size somewhere unsampled - meaning less likely to become relevant outside of the local region.

@ryhisner @FedeGueli do you know of other recent cases where a saltation/chronic infection was sequenced in >1 person?

GISAID query for the 13 sequences (including the 2 new ones): `C14120T,A18273G,9866T`

Here's a rough sketch of states (just one location used with scatter per known city/state) where the samples were collected. This is just for illustration of rough geographic distribution, the actual samples might well be quite differently distributed. 2 green `+` are the new ones.

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/3738931d-4412-433f-8678-1fa0c30ad6fa">

**Comment by cvejris** [comment]
I´m still sceptical about the potential of this variant to initiate a new wave, since it lacks the affinity-enhancing mutations in RBD (N460K, R493rev), but let´s wait and see...

**Comment by ryhisner** [comment]
> @ryhisner @FedeGueli do you know of other recent cases where a saltation/chronic infection was sequenced in >1 person?

Yes, it's unusual, but there have been dozens of times where a chronic-infection virus transmits to one or two people but then ends there. To give one of the more remarkable examples, there's this BA.1 branch from Brazil in which most sequences are from the same individual but two were from different patients. Potentially, this one could be ongoing I suppose, but the most recent sequence was collected in April.

![image](https://github.com/user-attachments/assets/8a49609b-2923-4212-95d3-2e60f08fd6d5)

**Comment by ryhisner** [comment]
> I´m still sceptical about the potential of this variant to initiate a new wave, since it lacks the affinity-enhancing mutations in RBD (N460K, R493rev), but let´s wait and see...

Yeah, it's extremely rare to see a chronic virus with Q493R transmit. I think it's clear now that Q493R is one of the worst spike mutations we've ever seen circulate. For me, the whole reason BJ.1 didn't grow rapidly but then took off upon recombination (turning into XBB) is that it lost Q493R—and as little else as possible—in the recomb. That was all it needed. You'd think R493Q would have happened more often in circulating lineages, but as far as I know, it's only ever occurred in chronics. It is, in fact, still the single most common substitution in chronic-infection sequences.

**Comment by corneliusroemer** [comment]
We won't designate as is of course but I'm considering making a sizeable ancestral parent branch with say 500 sequences a BA.2 sublineage to make it easier to a) talk about it, and b) for people to quickly spot related sequences of this cluster if they do lineage assignment in pangolin/Usher/Nextclade

**Comment by cvejris** [comment]
> > I´m still sceptical about the potential of this variant to initiate a new wave, since it lacks the affinity-enhancing mutations in RBD (N460K, R493rev), but let´s wait and see...
> 
> Yeah, it's extremely rare to see a chronic virus with Q493R transmit. I think it's clear now that Q493R is one of the worst spike mutations we've ever seen circulate. For me, the whole reason BJ.1 didn't grow rapidly but then took off upon recombination (turning into XBB) is that it lost Q493R—and as little else as possible—in the recomb. That was all it needed. You'd think R493Q would have happened more often in circulating lineages, but as far as I know, it's only ever occurred in chronics. It is, in fact, still the single most common substitution in chronic-infection sequences.

Very good point with BJ.1! Virtually all the most mutated BA.2-based saltation variants from the soup 2 years ago (how I miss these times) had 493rev. BA.2.10.4, BA.2.75, BA.2.77, BA.2.83, BA.2.3.20, BS.1, BA.4/5 (there were definitely more). N460K followed in frequency among these.

**Comment by alurqu** [comment]
One of these samples, EPI_ISL_19320418, seems to have disappeared from GISAID at least at the present time.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer, i don't remember any chronic transmitting beyond the one highlighted by Ryan, there were some suspected chain of transmission in Campania, Italy but once we contacted Grimaldi of Tigem lab, he verified that there were just input errors.

**Comment by Sinickle** [comment]
New sequence EPI_ISL_19374843 - Collected July 15
Patient metadata and location matches EPI_ISL_19322462,  which is the one that was NOT retracted.

**Comment by corneliusroemer** [comment]
Thanks @Sinickle - good that it's been fixed. We all know mistakes happen. But it would be good if GISAID didn't just silently change data without a record.

**Comment by aviczhl2** [comment]
No new samples for this.
