### ISSUE TITLE
XDV.1.7 + S:T22N + S:V62F (4 seqs - Japan and , via GBW, Taiwan, Shanxi)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1966]
Just spotted this recent branch of XDV.1 with trending mutation S:T22N: being caught in two different countries better tracking it here:
XDV.1.7 [C8950T > Orf1a:D2980N (G9203A)] >> C5173T > Orf1a:L681F ( C2306T), C8683T, S:T22N (C21627A), S:V62F (G21746T)
Query:C2306T, C8683T, C21627A
Samples: 3
Countries: 2 (Japan, Taiwan-GBW)
Tree:
<img width="1169" alt="Screenshot 2024-08-31 alle 00 47 11" src="https://github.com/user-attachments/assets/16a3004a-653b-4013-90fd-26de66d4ee33">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice6_genome_test_1022f_248f80.json?c=userOrOld&label=id:node_7162368

**Comment by aviczhl2** [comment]
+1 Shanxi

**Comment by FedeGueli** [comment]
Designated XDV.1.7.1 via  https://github.com/cov-lineages/pango-designation/commit/0d17efb4331b65679cee32080169401649c7f943
