### ISSUE TITLE
LB.1.2.2 (Full quad)  + S:S704L (32 US, Mexico, France, Australia , Denmark)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1967]
LB.1.2.2 >C22075T (S:V171V silent ) >C23029T (S:Y489Y silent ) > S:S704L (C23673T), M:L29F (C26607T)
Query: C23673T, C26607T,C23029T 
Samples: 9 ( plus one from Nevada not on Gisaid yet9
Countries: US ( 3 states: Maryland, NY, Nevada), Mexico (via GBW)
Last sample collected from Mexico via GBW had also S:R683L and S:K478T

Tree:
<img width="1186" alt="Screenshot 2024-08-31 alle 01 18 02" src="https://github.com/user-attachments/assets/f7fc80bf-b22e-4e0a-94f3-8d3789d330bf">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_1022f_248f70.json?label=id:node_7035391

**Comment by FedeGueli** [comment]
+1 France

**Comment by FedeGueli** [comment]
16 no recent samples

**Comment by Over-There-Is** [comment]
17

**Comment by FedeGueli** [comment]
3 recent samples better reopening it for a while

**Comment by FedeGueli** [comment]
32 but dying off
