### ISSUE TITLE
XDV.1+Orf1a:T1844I, A2821V, N:P383S+Orf8:V114I,S:S221L/F(4 seqs, 3 countries, 2 for S:221F)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1968]
S:S221L appears multiple times but do nothing. However, on this XDV.1 branch it further mutates to F just after S221L via 2-nuc mutation. 
 
XDV.1+C4655A+C5796T, C8727T,C29420T(Orf1a:T1844I, A2821V, N:P383S)+G28233A,G22224T(Orf8:V114I,S:S221L)

GISAID query: C5796T, C8727T,C22224T
No. of seqs: 4(Japan 2 USA 2(from Singapore))

First: EPI_ISL_19333464, Japan, 2024-7-24
Latest: EPI_ISL_19369880, USA from Singapore, 2024-8-21

GISAID query for S:221F sub-branch: C5796T, C8727T,C22224T, G22225T (2 seqs)

[uher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice82_genome_test_2b522_25f410.json?label=id:node_5613908)
![image](https://github.com/user-attachments/assets/63f26d3b-799e-4985-8cac-fb185b2297c0)

**Comment by FedeGueli** [comment]
It seems slow

**Comment by FedeGueli** [comment]
S:S221X confirms to be convergent but deleterious then, closing it
