### ISSUE TITLE
small saltation of FY.3.1 with S:G181A, S:T307I and 3 non-Spike mutation (9 seqs in Sweden)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#197]
Defining mutations: FY.3.1>G4109T (ORF1a:D1282Y)>C21998 (S:Q146K)>A8663G (ORF1a:T2800I), C12756A (ORF1a:T4164N), G22104C (S:G181A), C22482T (S:T307I), G25971T (ORF3a:W148C)

GISAID query: T28297C, G4109T, C22482T, G22104C
Earliest seq: 2023-06-02 (Sweden, EPI_ISL_17788246)
Most recent seq: 2023-06-04 (Sweden, EPI_ISL_17788222)
Countries detected: Sweden (3)

Usher Tree:
![QQ截图20230615231210](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/2bda8eb0-55cf-422e-ac03-5aa2ab6cb518)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c58c_b23a30.json

a small saltation in Sweden with 2 NTD-mutations. S:G181A is considered as the highest fitness on the site, and has been emerged in some sublineages. We can monitor for a time if it spreads further.  

By the way, FY.3.1 with ORF1a:D1282Y has been a large branch with a very convergent Spike mutation S:Q146K. I suggest designating it  for a further watch.

Genomes:
EPI_ISL_17788222, EPI_ISL_17788246, EPI_ISL_17788248

```[tasklist]
### Tasks
```

**Comment by FedeGueli** [comment]
good catch S:t307I rising in the last times

**Comment by HynnSpylor** [comment]
2 more seqs from Sweden

**Comment by FedeGueli** [comment]
closing this for now
