### ISSUE TITLE
JN.1.67.1 / KS.1 Recombinant (RU 7, US 1)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1970]
JN.1.67.1 / KS.1
'
Query: G1126A, T3100C, T21738C, G22599C

Mutations based on JN.1: T177C, G1126A, T3100C(private), G4162A / T21738C, C22450T, G22599C, T22928C, G24821T, C25680T, C26894T
Breakpoint: 4162\~21738
T177C, G1126A, G4162A are from the JN.1.67.1> G1126A> T177C branch.
All mutations from KS.1 are reserved.

Earliest sequence: 06-17 Saint Petersburg, Russia EPI_ISL_19297493
Latest sequence: 07-28 New York City, New York, USA EPI_ISL_19329202
Regions detected: Russia 7, US 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_6410_2d1420.json?c=country&f_userOrOld=GISAID%20and/or%20public&label=id:node_7294696
![image](https://github.com/user-attachments/assets/1e7023f5-4a85-4f56-af94-a9f1b489e4c8)

Sequences:
EPI_ISL_19297414, EPI_ISL_19297456, EPI_ISL_19297475,
EPI_ISL_19297493, EPI_ISL_19297497, EPI_ISL_19297506,
EPI_ISL_19297520, EPI_ISL_19329202

**Comment by FedeGueli** [comment]
no recent samples closing it
