### ISSUE TITLE
JN.1.67.1 subbranch with S:F59S, R346T on G1126A branch (23, 5 countries, mainly found in CN-LN)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1971]
JN.1.67.1> T21738C(S:F59S), G22599C(S:R346T)
Query: T21738C, G22599C, G26660T

It's placed under JN.1.67.1> G22599C> T21738C yet, but another branch under JN.1.67.1> G22599C is a JN.1.67.1> T177C> G22599C branch being misplaced, and the rest are two singlet, so there is no enough evidence to prove JN.1.67.1> G22599C exist.

Earliest sequence: 06-24 Taiwan, China (Imported*) EPI_ISL_19243399
Latest sequence: 08-13 Fushun, Liaoning, China EPI_ISL_19371535
Regions detected: **China** 19(including 1 imported sequence report by Taiwan), **US** 2(1 from **Thailand**), **Japan** 1, **UK** 1

\* Both local sequences and imported sequences from Mainland, Hong Kong or Macau are labeled as CDC-Fxxxxx, and imported sequences from non-"Greater China" regions are labeled as CDC-Wxxxxx.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_6410_2d1420.json?c=country&label=id:node_7134192
![image](https://github.com/user-attachments/assets/0cb98980-8ab2-4a1e-84e5-b559a418f689)

Sequences:
EPI_ISL_19243399, EPI_ISL_19280086, EPI_ISL_19299387,
EPI_ISL_19315664, EPI_ISL_19333960, EPI_ISL_19333962,
EPI_ISL_19347740, EPI_ISL_19356896, EPI_ISL_19357905,
EPI_ISL_19371482, EPI_ISL_19371512-19371514, EPI_ISL_19371516,
EPI_ISL_19371518-19371519, EPI_ISL_19371535, EPI_ISL_19371555,
EPI_ISL_19371593, EPI_ISL_19371595, EPI_ISL_19371597-19371599

**Comment by aviczhl2** [comment]
Hi, Fede is on vacation and I'm in charge of this repo now. I think this shall be proposed to main.

**Comment by FedeGueli** [comment]
Designated MZ.3 via https://github.com/cov-lineages/pango-designation/commit/577670c7bb874ed23dda10d33481723eea58ec19
