### ISSUE TITLE
KP.3.1.1 subbranch with S:R765L and Orf1a:E217K (6 sequences, 3 countries)

### ISSUE THREAD

**Issue by Walde1nsamkeit** [sars-cov-2-variants/lineage-proposals#1972]
KP.3.1.1> G25595T> G174C, G914A(Orf1a:E217K), G23856T(S:R765L), A28877T, G28878C
Query: G174C, G914A, G23856T

Earliest sequence: 07-20 Saint Denis, Ile de France, France EPI_ISL_19368348
Latest sequence: 07-29 Brest, Bretagne, France EPI_ISL_19368389
Regions detected: France 3, US 2(1 from Italy, 1 pooled)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4ee7f_40c790.json?c=country&f_userOrOld=uploaded%20sample&label=id:node_7107900
![image](https://github.com/user-attachments/assets/c6312fbe-11d9-4603-9b5a-6cc0f6f49c62)

Sequences:
EPI_ISL_19324707, EPI_ISL_19324809, EPI_ISL_19368348,
EPI_ISL_19368389, EPI_ISL_19368393

**Comment by Over-There-Is** [comment]
France+1

**Comment by FedeGueli** [comment]
Slow closing this
