### ISSUE TITLE
LB.1.4 subbranch with S:A879S(39, 4 countries, mainly in US)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1974]
LB.1.4> C29296T> G2272A, G7675T, G26918A> G24197T(S:A879S)> G1681T(Orf1a:E472D), T27438C
Query: C4683T, C8293T, G24197T
Query for sequences without C4683T: G2272A, G24197T, G26918A, -C4683T
Query for sequences without G26918A: G2272A, C7108T, G7675T, -G26918A

Earliest sequence: 06-08 DC, USA EPI_ISL_19269061
Latest sequence: 08-20 Ontario, Canada EPI_ISL_19358362
Regions detected: US 34(1 import from Taiwan, China, 1 not on GISAID), Canada 4, Germany 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_b0e8_5181b0.json?label=id:node_7028021
![image](https://github.com/user-attachments/assets/585bfe41-cc39-4079-bb57-7c0107e7770e)

EPI_ISL_19231019, EPI_ISL_19239508, EPI_ISL_19239514,
EPI_ISL_19258205, EPI_ISL_19260864, EPI_ISL_19268968,
EPI_ISL_19269061, EPI_ISL_19273468, EPI_ISL_19284145,
EPI_ISL_19292680, EPI_ISL_19294098, EPI_ISL_19298109,
EPI_ISL_19298207, EPI_ISL_19303524, EPI_ISL_19310652,
EPI_ISL_19310660, EPI_ISL_19310687, EPI_ISL_19314451,
EPI_ISL_19317151, EPI_ISL_19323699, EPI_ISL_19327791,
EPI_ISL_19327840, EPI_ISL_19328349, EPI_ISL_19328363,
EPI_ISL_19330092, EPI_ISL_19333164, EPI_ISL_19335059,
EPI_ISL_19344560, EPI_ISL_19346967, EPI_ISL_19349929,
EPI_ISL_19358362, EPI_ISL_19359883, EPI_ISL_19362379,
EPI_ISL_19362484, EPI_ISL_19362685, EPI_ISL_19368129,
EPI_ISL_19368142, EPI_ISL_19368275, PP976909.1

**Comment by aviczhl2** [comment]
This is already designated LB.1.4.2 I guess.

**Comment by aviczhl2** [comment]
@AngieHinrichs, due to the usher order shift usher seems not displaying LB.1.4.2.

**Comment by Over-There-Is** [comment]
It seems LB.1.4.2 disappears from "staging".

**Comment by aviczhl2** [comment]
> It seems LB.1.4.2 disappears from "staging".

@corneliusroemer
