### ISSUE TITLE
KP.2.3.4 subbranch with S:S155I, G184V (65 seqs, 6 countries, mainly found in US)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1975]
KP.2.3.4> C835T> C21952T, G22026T(S:S155I), G22113T(S:G184V)
Query: C835T, C8293T, G22113T

Earliest sequence: 05-23 New York City, New York, USA EPI_ISL_19177685
Latest sequence: 08-13 North Carolina, USA EPI_ISL_19362165
Regions detected: **US** 25(1 imported from **UAE**, 8 not on GISAID), **Canada** 4, **Spain** 4, **Sweden** 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_65d78_55bfe0.json?c=country&label=id:node_7060671
![image](https://github.com/user-attachments/assets/02964d2e-610c-4741-a352-0561ff527d89)
USA/DE-DHSS-90/2024|EPI_ISL_19314883|2024-07-21 has single N's on 21952 and 22026, so it has C21952T and G22026T too.

Sequences:
EPI_ISL_19177685, EPI_ISL_19196981, EPI_ISL_19206144,
EPI_ISL_19233230, EPI_ISL_19262535, EPI_ISL_19265186,
EPI_ISL_19271593, EPI_ISL_19280328, EPI_ISL_19281828,
EPI_ISL_19291678, EPI_ISL_19291682, EPI_ISL_19293859,
EPI_ISL_19293873, EPI_ISL_19310832, EPI_ISL_19311067,
EPI_ISL_19311479, EPI_ISL_19314883, EPI_ISL_19331337,
EPI_ISL_19331682, EPI_ISL_19359855, EPI_ISL_19361940,
EPI_ISL_19362165, EPI_ISL_19367488, EPI_ISL_19367511,
EPI_ISL_19367525, EPI_ISL_19368144, PP972881.1,
PP976694.1, PQ060862.1, PQ147992.1,
PQ147804.1, PQ148035.1, PQ207579.1,
PQ211669.1

**Comment by Over-There-Is** [comment]
label:"Emerged in an undersampled area"

**Comment by aviczhl2** [comment]
Only 1 June UAE sample from undersampled area.

**Comment by Over-There-Is** [comment]
US+2

**Comment by Over-There-Is** [comment]
US +1 CA +1

**Comment by aviczhl2** [comment]
Shall be KP.2.3.4

**Comment by FedeGueli** [comment]
42 on Gisaid

**Comment by FedeGueli** [comment]
alive only in a cluster recently

**Comment by DailyCovidCases** [comment]
Closing this, it doesn't seem to be fast now

**Comment by Over-There-Is** [comment]
Colombia via US-VA

**Comment by xz-keg** [comment]
designated NM.1
