### ISSUE TITLE
KP.1.1 subbranch with Orf1a:A498V, T4161I and Orf3d:Q17*(39, 3 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1976]
KP.1.1> C11653T> C9724T, C12747T(Orf1a:T4161I), C26882A> A498V(Orf1a:A498V), C25572T(Orf3d:Q17*)
Query: C1758T, C9724T, C25572T

Earliest sequence: 04-12 Monroe, New York, USA EPI_ISL_19095045
Latest sequence: 07-28 Tennessee, USA EPI_ISL_19367579
Regions detected: US 34(5 not on GISAID), Canada 3, UK 2

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_40bd0_563c90.json?c=country&label=id:node_7050574
![image](https://github.com/user-attachments/assets/363e32f6-e7ef-4176-a545-3f75526eece1)

Sequences:
EPI_ISL_19084564, EPI_ISL_19094360, EPI_ISL_19095045,
EPI_ISL_19095060, EPI_ISL_19126174, EPI_ISL_19144445,
EPI_ISL_19175964, EPI_ISL_19190265, EPI_ISL_19212270,
EPI_ISL_19222725, EPI_ISL_19223070-19223071, EPI_ISL_19239390,
EPI_ISL_19262932, EPI_ISL_19262934, EPI_ISL_19262983,
EPI_ISL_19273856, EPI_ISL_19288936, EPI_ISL_19288945,
EPI_ISL_19290024, EPI_ISL_19290307, EPI_ISL_19298158,
EPI_ISL_19298198, EPI_ISL_19298913, EPI_ISL_19303222,
EPI_ISL_19308391, EPI_ISL_19318508, EPI_ISL_19323710,
EPI_ISL_19324947, EPI_ISL_19335072, EPI_ISL_19335081,
EPI_ISL_19367319, EPI_ISL_19367372, EPI_ISL_19367579,
PP832097.1, PP938822.1, PP965579.1,
PP973081.1, PQ108413.1,

**Comment by aviczhl2** [comment]
Yeah this C25572T is convergent to EG.5.1.1, and my tool show it applies a stop codon on Orf3d.

**Comment by aviczhl2** [comment]
1 past seq in Costa Rica. No new seqs
