### ISSUE TITLE
KP.3.1.1+ S:F32L + S:T747N (8 in 2 Countries)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1978]
![image](https://github.com/user-attachments/assets/d3a06852-9936-411f-a091-d1b432744eb8)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29286_66c6c0.json?c=gt-S_32&gmax=25384&gmin=21563&label=id:node_7115647

First Seq: 2024-08-06
Most Recent: 2024-08-15

Gisaid Query: G1738T, C21658G, A22456G, C23802A, C26139T

EPI_ISL_19369258 EPI_ISL_19348611 EPI_ISL_19369251 EPI_ISL_19326596

**Comment by Over-There-Is** [comment]
AU+3

**Comment by FedeGueli** [comment]
no new seqs better closing this
