### ISSUE TITLE
XBB.1.42 (S:Q613H) + S:478R (29 Seqs as 14/07)circulating in Austria (around 2% in June)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#198]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/74b480df-5928-4aba-b036-8e238a1b2c7a)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2974f_b6e660.json?c=gt-S_478&label=id:node_6627370
first seq: 2023-04-21
most recent: 2023-05-30
EPI_ISL_17743532 EPI_ISL_17619026 EPI_ISL_17669720 EPI_ISL_17782534 EPI_ISL_17782156 EPI_ISL_17782351 EPI_ISL_17782430 

Gisaid query: 
-G23345A,-A22101T,C22995G,T23018C,T28297C,C12789T,-G5720A,A16878T,-A27507C,-C11956T,-C26322T,-A2514G

Edited this query finds all the 7 sequences but be aware that could catch samples from unrelated lineages in the next weeks .

**Comment by FedeGueli** [comment]
Very good catch XBB.1.42 recombinant lineage is expanding m likely faster than we think.

**Comment by FedeGueli** [comment]
New tree shows ten sequences for this lineage: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d936_c9120.json?c=userOrOld&label=id:node_6632239
![Schermata 2023-06-19 alle 23 34 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/966df1f0-6402-4a64-8b7a-2aea56ced981)

**Comment by FedeGueli** [comment]
17 today a batch uploaded yesterday from Vienna all from June. This  could be something.

**Comment by FedeGueli** [comment]
new query: -G23345A,-A22101T,C22995G,T23018C,T28297C,C12789T,-G5720A,A16878T,-A27507C,-C11956T,-C26322T,-A2514G finds 22


New tree:
![Schermata 2023-07-01 alle 11 48 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2d009600-92bd-41e5-893f-a5848e54e82a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d02_ff4f30.json?c=userOrOld&label=id:node_6679449

please keep this updated. It is likely something to propose soon.

**Comment by Fearuncle** [comment]
Designated as XBB.1.42.1
