### ISSUE TITLE
JN.1.67.1+S:S60P (41 Seqs, >10 regions)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1980]
JN.1.67.1+T21740C(S:S60P)

This S60P+F456L combo also appears in XDV.1.1, LF.9 and https://github.com/cov-lineages/pango-designation/issues/2745, despite not fast, it is still circulating with very few additional spikes. 

GISAID query: T21740C, G26660T, T22928C,-10834,-T177C
No. of seqs: 20(New Zealand 1 Germany 1 Singapore 1 USA 1 China 16(6 different provinces))

First: EPI_ISL_19264833, China-Henan, 2024-5-16
Latest: EPI_ISL_19330211, China-Gansu, 2024-8-8

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_630_6cbe90.json?label=id:node_5589183)
![image](https://github.com/user-attachments/assets/6e6afacb-9462-4086-b208-e245683d72cd)

**Comment by FedeGueli** [comment]
6countries , please take Taiwan as separate country

**Comment by aviczhl2** [comment]
> 6countries , please take Taiwan as separate country

Well, I don't separate out regions like Puerto Rico, Taiwan, Guam, Canary Islands, French Guiana etc.

**Comment by aviczhl2** [comment]
@FedeGueli  I think I'll use "regions" in future proposals. 
Regions may include
1: Chinese provinces
2: USA states and overseas territories like Guam/Puerto Rico
3: India Pradesh
4: UK countries (England, Scotland etc.)
5: Overseas territories for other countries like Greenland, French Guiana etc. 

For imported cases they will be regarded as their original regions and their destination regions won't be counted.

**Comment by aviczhl2** [comment]
For this one, it is in Gansu,Shanxi,Liaoning,Henan, Hubei, Taiwan, Germany, New Zealand, Singapore, GA, TX, total 11 regions.

**Comment by FedeGueli** [comment]
> For this one, it is in Gansu,Shanxi,Liaoning,Henan, Hubei, Taiwan, Germany, New Zealand, Singapore, GA, TX, total 11 regions.
mm you should use then also the same for Canadian States, Brazilian states , Germany federal regions, i think it is a mess. 
we should keep this mirrored to Gisaid and Gisaid has the divisions i mentioned above, so please don't mess things further
(Wales,England, Scotland are all under united kingdom together).
Personally talking we are here in these repos with our little and very limited lives to try to help and benefit Juman kind as a whole, independently from any nationalism, as Nations far to be expression of people sovereignity are the common tools used by elites to force people under their powers and don not represent any identity that is truck into people hearts and souls and are instead way to oppress thos identities and tools.

**Comment by FedeGueli** [comment]
Said that when you propose anything you can do as you want but as moderator please don't change the usual way to identify countries. If there are issues with that write to Gisaid explaining why that should be changed.

**Comment by aviczhl2** [comment]
> mm you should use then also the same for Canadian States, Brazilian states , Germany federal regions, i think it is a mess. we should keep this mirrored to Gisaid and Gisaid has the divisions i mentioned above, so please don't mess things further (Wales,England, Scotland are all under united kingdom together). Personally talking we are here in these repos with our little and very limited lives to try to help and benefit human kind as a whole, independently from any nationalism, as Nations far to be expression of people sovereignity are the common tools used by elites to force people under their powers and don not represent any identity that is stuck into people hearts and souls and are instead way to oppress those identities and souls.

By number of countries, we are actually looking for "number of separate seq collection sources", that's why regions shall be a better estimate,

**Comment by aviczhl2** [comment]
> we should keep this mirrored to Gisaid and Gisaid has the divisions i mentioned above, so please don't mess things further (Wales,England, Scotland are all under united kingdom together). 

Many non-country regions are separated out on GISAID. All Chinese provinces including Hong Kong and Taiwan, UK countries and overseas territories of Canary Islands, Puerto Rico, French Guiana etc. are all separated out. 

If you want to keep the term "country" maybe we shall follow UN membership.

**Comment by FedeGueli** [comment]
> > we should keep this mirrored to Gisaid and Gisaid has the divisions i mentioned above, so please don't mess things further (Wales,England, Scotland are all under united kingdom together).
> 
> Many non-country regions are separated out on GISAID. All Chinese provinces including Hong Kong and Taiwan, UK countries and overseas territories of Canary Islands, Puerto Rico, French Guiana etc. are all separated out.
> 
> If you want to keep the term "country" maybe we shall follow UN membership.

no, if you search China you find those regions but not Taiwan , so please again keep things as there as moderator , as proposer you can do what you prefer

**Comment by FedeGueli** [comment]
> > we should keep this mirrored to Gisaid and Gisaid has the divisions i mentioned above, so please don't mess things further (Wales,England, Scotland are all under united kingdom together).
> 
> Many non-country regions are separated out on GISAID. All Chinese provinces including Hong Kong and Taiwan, UK countries and overseas territories of Canary Islands, Puerto Rico, French Guiana etc. are all separated out.
> 
> If you want to keep the term "country" maybe we shall follow UN membership.

and btw i do not give a fuck about nations or countries, call it regions the onluy thing that i m interested in is that the different issues are comparable and the count updated by everyone in the same way so if you want to call it regions call it as you want also "places " it is ok for me, earth is one it is all about conventions and wars so not inherent our mission here.

**Comment by aviczhl2** [comment]
> 
> and btw i do not give a fuck about nations or countries, call it regions the onluy thing that i m interested in is that the different issues are comparable and the count updated by everyone in the same way so if you want to call it regions call it as you want also "places " it is ok for me, earth is one it is all about conventions and wars so not inherent our mission here.

We are doing quite silly debate. I actually don't know why we use number of country while GISAID actually does not (it separates country and their semi-independent territories like Puerto Rico, Greenland etc.). It is just for convenience to show how wide a lineage spread.

**Comment by FedeGueli** [comment]
> > and btw i do not give a fuck about nations or countries, call it regions the onluy thing that i m interested in is that the different issues are comparable and the count updated by everyone in the same way so if you want to call it regions call it as you want also "places " it is ok for me, earth is one it is all about conventions and wars so not inherent our mission here.
> 
> We are doing quite silly debate. I actually don't know why we use number of country while GISAID actually does not. It separates country and their semi-independent territories like Puerto Rico, Greenland etc. And actually some Puerto Rico seqs are submitted by USA and some Canary Island seqs are submitted by Spain, what a mess! It is just for convenience to show how wide a lineage spread.

Agree you started that.

**Comment by Mydtlwn** [comment]
I generally use the term 'region' rather than 'country' because there is inconsistency in the recognition of countries across different nations or regions of the world. Using or not using the word 'country' may offend any of these parties. From the perspective of a rigorous scientific worker, it is also more appropriate to say 'region' rather than 'country.

**Comment by FedeGueli** [comment]
> I generally use the term 'region' rather than 'country' because there is inconsistency in the recognition of countries across different nations or regions of the world. Using or not using the word 'country' may offend any of these parties. From the perspective of a rigorous scientific worker, it is also more appropriate to say 'region' rather than 'country.

yeah we are using Places now, my point was exactly that. Not offending people but no care about governments.

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_346e7_a2f710.json?f_userOrOld=uploaded%20sample)
![Screenshot (260)](https://github.com/user-attachments/assets/626911ca-d42f-46ae-b23c-7d4634b5a9bc)
Propose this branch?

**Comment by FedeGueli** [comment]
lets wait next Chinese batches

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
> @FedeGueli Propose this branch?

thx i will propose when it reaches 50

**Comment by xz-keg** [comment]
not detected in any recent Chinese batches, close down.

**Comment by Over-There-Is** [comment]
Sichuan+5

**Comment by FedeGueli** [comment]
>Sichuan+5
No one recent though
