### ISSUE TITLE
LF.8.1.1+Orf1a:L4391F+Orf6:I33M, S:K478T(rev) (8 seqs, 6 Places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1982]
LF.8.1.1+C13436T+A27300G+A22995C(rev)

GISAID query: C13436T,A27300G,-22995
 
No. of seqs: 3(USA , 2 from Qatar)

EPI_ISL_19362364, 2024-8-19, USA-VA
EPI_ISL_19375171,19375176, 2024-8-23, USA from Qatar

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_134fc_828d10.json)
![image](https://github.com/user-attachments/assets/8524d642-2faf-4f26-a7da-d430c069fa39)

**Comment by FedeGueli** [comment]
Interestingly this is the second branch with 478T beside the one with also 222V in comments in the original issue.

**Comment by aviczhl2** [comment]
No new seqs

**Comment by xz-keg** [comment]
+1 USA-OH
+2 China, from Hubei and Gansu

**Comment by FedeGueli** [comment]
Designated ND.1 via https://github.com/cov-lineages/pango-designation/commit/bb7b4ed873bc2cea1fcd9a2cecbd7d84895073a6

**Comment by FedeGueli** [comment]
> C13436T,-22995,C9169T,C21654T,C21627A

yeah i think the tree now collectes all the singlets with 478T too, we spotted them at the start but they werent together in the same branch
