### ISSUE TITLE
LY.1 + ORF1a:S1189R (157 mostly Texas USA) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1983]
![image](https://github.com/user-attachments/assets/7273bbfd-75f0-4d35-acd7-1229f32ffc96)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_cdab_90bd10.json?f_userOrOld=uploaded%20sample

![image](https://github.com/user-attachments/assets/3bfc4616-05e5-4d19-8514-8285eed6a31a)

Gisaid Query: !C6384T & C3832A & T20367C

**Comment by FedeGueli** [comment]
please propose it

**Comment by DailyCovidCases** [comment]
@Fearuncle Should I transfer this issue to the man page right now?

**Comment by DailyCovidCases** [comment]
@Fearuncle please propose it, it grows quite fast now:
![Screenshot (245)](https://github.com/user-attachments/assets/5724142a-ea44-4b9d-b995-020b8e52f8fd)
