### ISSUE TITLE
JN.1*/LF.1.1.1 recombinant(91 seqs, 9 countries) 40% in St Petersburg in September

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1984]
There seems to be an LF.1.1.1 branch that loses Orf1a mutations due to recombinant.

JN.1--LF.1.1.1

Breakpoint between 6574 and 16550

It is basically LF.1.1.1 losing G4067A and C6573T. It keeps C16551T and C18912T and T19209C

GISAID query: C16551T, C18912T, T19209C, -4067, -6573
No. of seqs: 66(Canada 1 Denmark 1 Egypt 1 France 4 Germany 1 USA 3(1 from Egypt) Russia 56)

First: EPI_ISL_19231765, Russia, 2024-4-30
Latest: EPI_ISL_19361589, Canada, 2024-8-14

It is mainly detected in Russia and also in Egypt, signifying its circulation in vast undersampled regions. Not likely to grow now though but still worth designation. @corneliusroemer 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice75_genome_test_53e02_91e060.json?label=id:node_5492451)
![image](https://github.com/user-attachments/assets/a2b31372-bf14-44df-8a9e-ba5220a4415d)

**Comment by FedeGueli** [comment]
91 with the new Russian batch, high local prevalence in St Petersburg. propose it please

**Comment by FedeGueli** [comment]
Designated XEJ via  https://github.com/cov-lineages/pango-designation/commit/1a23ef0ca3b0ed60b3b2e321ab8c90e5c94d84fa
