### ISSUE TITLE
KP.2.2 + S:N679R, ORF1a:E929G, ORF1a:I3927T (6 in Thailand)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1987]
![image](https://github.com/user-attachments/assets/7cf1ac6b-3b0b-4f58-a656-75b022cb3f40)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2694e_9d5a10.json?f_userOrOld=uploaded%20sample

First Seq: 2024-08-05
Most Recent: 2024-08-19

Gisaid Query: A3051G, T12045C

EPI_ISL_19370747 EPI_ISL_19370746 EPI_ISL_19370729 EPI_ISL_19370728 EPI_ISL_19370722 EPI_ISL_19370745

**Comment by aviczhl2** [comment]
No new seqs
