### ISSUE TITLE
KP.3+Orf1b:T2488M+S:C1235F(7 seqs, 4 countries, 3 with S:L335F, D1084Y)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1988]
KP.3+T2950A,C11620T+A29683G+C20930T(Orf1b:T2488M)+G25266T(S:C1235F)

GISAID query: G25266T,T2950A
No. of seqs: 6(New Zealand 1 Australia 3 USA 2(from Fiji))

First: EPI_ISL_19339176, USA from Fiji, 2024-8-7
Latest: EPI_ISL_19377903, Australia, 2024-8-25

GISAID query for S:L335F,D1084Y branch: G25266T,T2950A,G22567T
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice181_genome_test_6639c_a5f020.json?label=id:node_5539573)
![image](https://github.com/user-attachments/assets/9c1f682e-0ce7-4a99-929b-6827e3a0e6f0)

**Comment by FedeGueli** [comment]
Not present in recent batches from Australia, closing it

**Comment by aviczhl2** [comment]
+4 Australia
