### ISSUE TITLE
maybe a recombinant of XBB.1.5.62 & XBB.1.5.55 33 seq. in Canada

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#199]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/81c108ce-a7fa-437d-8431-854eb0a79cbc)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_b468_b7eac0.json?c=gt-nuc_4087&label=id:node_6703343
first sequenced: 2023-03-02
most recent: 2023-05-30
gisaid query: G21160T, T4087C, T9964C
EPI_ISL_17385556 EPI_ISL_17537513 EPI_ISL_17764626 EPI_ISL_17764620 EPI_ISL_17701232 EPI_ISL_17386073 EPI_ISL_17192657 EPI_ISL_17701219 EPI_ISL_17537738 EPI_ISL_17442437 EPI_ISL_17306695 EPI_ISL_17490745 EPI_ISL_17630320 EPI_ISL_17722620 EPI_ISL_17764621 EPI_ISL_17537633 EPI_ISL_17701777 EPI_ISL_17764669 EPI_ISL_17722637 EPI_ISL_17442125 EPI_ISL_17442885 EPI_ISL_17764539 EPI_ISL_17442851 EPI_ISL_17491018 EPI_ISL_17491010 EPI_ISL_17491011 EPI_ISL_17764713 EPI_ISL_17442632 EPI_ISL_17490965 EPI_ISL_17764538 EPI_ISL_17764665 EPI_ISL_17764667 EPI_ISL_17764663 EPI_ISL_17764616

**Comment by FedeGueli** [comment]
Not sure it is a recombinant this one. while 5 seqs of it have the defining mutations of both lineages it seems weird to me that it shares so many mutations with the tree where it has been placed by Usher. If it grows ( be aware that Canada does targeting sequencing and  so sometimes upload batches sampled from the same outbreak) i will look further at it,
