### ISSUE TITLE
JN.1+Orf1a:T1638I,K3353R, S:F59S,F456L,Q493E (5 seqs, China)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1991]
There seems to be a new FLuQE+F59S branch emerging in China and detected in 2 distant provinces. I cannot find evidence of recombination, likely a separate emergence. 

JN.1+C5178T, A10323G, A20388G, T21738C, T22928C, C23039G

S:F59S, F456L, Q493E
Orf1a:T1638I, K3353R

It can be most closely viewed as either a sub-branch of JN.1.16 or JN.1.52. 

GISAID query: C5178T, A10323G, T21738C,T22928C(edited)
No. of seqs: 4(China, Hubei and Liaoning)

First: EPI_ISL_19385118, Hubei, 2024-7-23
Latest: EPI_ISL_19371610, Liaoning, 2024-8-12

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice88_genome_test_3da62_c7ebd0.json?label=id:node_6344456)
![image](https://github.com/user-attachments/assets/609dd1ce-72f4-4b4c-9e93-25e1267c9009)

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by FedeGueli** [comment]
Please higlight in the comments when query changed

**Comment by aviczhl2** [comment]
> Please higlight in the comments when query changed

There is an unrelated Italian seq caught by this query.

**Comment by FedeGueli** [comment]
> > Please higlight in the comments when query changed
> 
> There is an unrelated Italian seq caught by the original query.

Thank you, i was just meaning to signal when the query changes so we can track the same thing. thank you for your work

**Comment by DailyCovidCases** [comment]
This branch has slowed down a lot. You can close this @xz-keg

**Comment by xz-keg** [comment]
no more seqs
