### ISSUE TITLE
KP.2+ s:A435S+S:T478Q + N:G204P+ 6 ORF1ab Mutations (2 in USA)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1992]
![image](https://github.com/user-attachments/assets/73793efc-2ec5-4e8a-8d9b-0106c0faa783)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d95f_c909b0.json?f_userOrOld=uploaded%20sample

Seq: 2024-08-20

query: G3287A, T7264C, T18581C, T21015C, A22994C

EPI_ISL_19369932 EPI_ISL_19369855

**Comment by aviczhl2** [comment]
This is the T22795G branch of KP.2. @AngieHinrichs, another weird Flip-flop branch here.
