### ISSUE TITLE
XEC + S:G252S on the ORF1a:A599T branch (39 in 17 places 6 countries ) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1993]
![image](https://github.com/user-attachments/assets/2a92ad3d-b33f-4d60-86d8-1417ff4fcf61)
![image](https://github.com/user-attachments/assets/9da107d9-0633-4c08-9888-e13693b1b6af)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25d52_d09b10.json?f_userOrOld=uploaded%20sample

First Seq: 2024-08-12
Most Recent: 2024-08-20

Gisaid: G22316A, T25039C,T3565C

EPI_ISL_19378281 EPI_ISL_19375825 PQ277301.1 PQ277106.1

**Comment by FedeGueli** [comment]
Query edited to exclude bat viruses: G22316A, T25039C,T3565C

**Comment by FedeGueli** [comment]
252V 253G were the defining of the two main XBB branches while not relevant until now in JN.1, lets see what this will do.

**Comment by aviczhl2** [comment]
6 including one from China.

**Comment by FedeGueli** [comment]
12 on Gisaid. @Fearuncle where the other samples not on Gisaid are from?

**Comment by xz-keg** [comment]
13 on GISAID now.

**Comment by Fearuncle** [comment]
> 12 on Gisaid. @Fearuncle where the other samples not on Gisaid are from?

![image](https://github.com/user-attachments/assets/fb5b8b46-b76f-42f0-a755-d2ebfffac0c9)

**Comment by xz-keg** [comment]
> > 12 on Gisaid. @Fearuncle where the other samples not on Gisaid are from?
> 
> ![image](https://private-user-images.githubusercontent.com/78371872/376092735-fb5b8b46-b76f-42f0-a755-d2ebfffac0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzM0MTQsIm5iZiI6MTcyODg3MzExNCwicGF0aCI6Ii83ODM3MTg3Mi8zNzYwOTI3MzUtZmI1YjhiNDYtYjc2Zi00MmYwLWE3NTUtZDJlYmZmZmFjMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAyMzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2I5YzFlZDFkYzBiMzdjN2Y1MmE4MTQ3YzZlNzI2YzY4MzMwZmVkMzI1YjllZGEzZTJiNmJiNjIyMmZiMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.amkCur-dyD1yY0uG1TjCJYmHES-C7R4xuoCTCx1Mp9s)

most are duplicates of same seqs from different platforms. Better put the real toll according to GISAID to avoid duplication.

**Comment by FedeGueli** [comment]
It seems slow

**Comment by FedeGueli** [comment]
Local an d slow closing it

**Comment by Over-There-Is** [comment]
Sweden, Denmark, UK, Canada, US(including 1 from HKSAR)

**Comment by FedeGueli** [comment]
> Sweden, Denmark, UK, Canada, US(including 1 from HKSAR)

Thx revived quite well , >reopened it.

**Comment by xz-keg** [comment]
39 now,I think worth proposal

**Comment by FedeGueli** [comment]
yes please @Fearuncle propose it



> 39 now,I think worth proposal

**Comment by FedeGueli** [comment]
Designated XEC.12 via https://github.com/cov-lineages/pango-designation/commit/58afeb200abbbcdc988c0d82a3b05db2f83a136d
