### ISSUE TITLE
LF.7+S:T961M(10 seqs, 3 countries)  2 with Orf9b:A22V and PLPro_T291I

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#1996]
LF.7> ORF1a:G1125S (G3638A),C5812T, Orf1a:T1854I (C5826T = PLPro_T291I), **S:T961M** (C24444T), C26885T >> 
C13620T,23449C, Orf9b:A22V (C28348T), G29587A [Edited]

GISAID query: C5239T, C7869T,C24444T(edited)
No. of seqs: 2(USA 1(from Nigeria) UK 1)

EPI_ISL_19342253, UK, 2024-8-7
EPI_ISL_19386074, USA from Nigeria, 2024-8-29

The UK seq has S:22 missing coverage, it shall have S:T22N and sub-branch of LF.7 
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice15_genome_test_255f6_d41b60.json?label=id:node_5495612)
![image](https://github.com/user-attachments/assets/b6f59934-d666-473d-9070-2e154ccea4cb)

**Comment by HynnSpylor** [comment]
The S:T961M branch could be expanded (without G25494A)
![微信截图_20240928095119](https://github.com/user-attachments/assets/fbcc4d74-c386-4618-9b2f-06a294a1cfa5)

**Comment by aviczhl2** [comment]
> The S:T961M branch could be expanded (without G25494A) 

Thanks. Query edited. One more GBW from Nigeria

**Comment by FedeGueli** [comment]
thx @HynnSpylor . LF.7 should be very large in Africa.

**Comment by FedeGueli** [comment]
I gave a second watch to this in its braodened vrsion of 5 samoples:
It has two branches one with C13620T, T23449C,C28348T , G29587A: C28348T  corresponds to Orf9b:A22V
The other could be a recombinant having 3 reversions and among them Orf9b:I5T, it has also a double nuc mutation (one silent)  at  Orf1b:V980I and G25183A.

**Comment by DailyCovidCases** [comment]
Still 6 seqs now, this branch has slowed down a lot

**Comment by FedeGueli** [comment]
> Still 6 seqs now, this branch has slowed down a lot, closing this

please when u see undersampled tag don't even comment it will stay open also for long time

**Comment by FedeGueli** [comment]
+3 England

**Comment by xz-keg** [comment]
+1 USA-TX

**Comment by FedeGueli** [comment]
this is another one i bet on.

**Comment by xz-keg** [comment]
Designated LF.7.4
