### ISSUE TITLE
XDV.1 + ORF3a:A98T + S:K478I + ORF1a:T891I (21, 3 countries) 8% prevalence in Hubei in late August > growing

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#1999]
![image](https://github.com/user-attachments/assets/4cea9094-6dac-46b4-914a-e4ce089bdeac)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39561_fbb950.json?f_userOrOld=uploaded%20sample

First Seq: 2024-07-17
Most Recent: 2024-08-27

Gisaid Query: G25684A, A405G, T22930A, C22295A

EPI_ISL_19384843 EPI_ISL_19384849 EPI_ISL_19384865 EPI_ISL_19384864 EPI_ISL_19384847 EPI_ISL_19384855 EPI_ISL_19384845 EPI_ISL_19384868 EPI_ISL_19384839 EPI_ISL_19384838 EPI_ISL_19384869 EPI_ISL_19384609 EPI_ISL_19299348 EPI_ISL_19384856 EPI_ISL_19384848 EPI_ISL_19384852 EPI_ISL_19384851 EPI_ISL_19384457 EPI_ISL_19384862

**Comment by FedeGueli** [comment]
Convergent with XDV.1.5 it seems XDV likes very much mutations at K478 >T,Q,I

**Comment by FedeGueli** [comment]
Looking at samples collected in Hubei after August 15 it is around 8% growing from 1% in the first 15 days of August.
Covspectrum scores it as the highest for growth advantage right now, we must wait for spread outside HUbei to draw any conclusions but still something to watch closely.

**Comment by FedeGueli** [comment]
+1 from Illinois

**Comment by FedeGueli** [comment]
it seemed to be a small cluster.

**Comment by xz-keg** [comment]
+1 Netherlands

**Comment by FedeGueli** [comment]
+1 Heilongjiang

**Comment by Over-There-Is** [comment]
37

**Comment by FedeGueli** [comment]
Last one from Sichuan very recent, but not enough to reopen it for now
