### ISSUE TITLE
XBB.1 + S:486P + S:456L with G4006A, T17067C, T26012G (26 seqs  2022-06-03) circulating in Reunion, Canada, Ireland , Spain)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#2]
There are around 10 sequences of XBB.1 + S:486P + S:456L that have extra nuc mutations G4006A, T17067C, T26012G (ORF3a:F207C)

What confuses me is that 26012G is also part of FE.1, which also has the same Spike XBB.1 + S:486P + S:456L

This could be chance, or it could be recombination or the origin of FE.1 is different than I thought (A8001G didn't happen first)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1*+%26+S%3A486P+%26+%5B3-of%3AC1878T%2C%09G4006A%09%2CT17067C%2C%09T20600C%2C%09T22928C%2C%09T26012G%2C%09C27881T%09%2CG29449T%5D&nextcladePangoLineage1=FE.1*&nextcladePangoLineage2=XBB.1.5*&analysisMode=CompareEquals&

Some recent sequences:
hCoV-19/USA/MS-CDC-VSX-A079750/2023|EPI_ISL_17618604|2023-04-15
hCoV-19/USA/CA-CDC-LC1038686/2023|EPI_ISL_17619098|2023-04-19
hCoV-19/USA/PA-CDC-LC1038837/2023|EPI_ISL_17619168|2023-04-20

Usher puts them in a weird (probably wrong) place with lots of reversions:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/25161793/236637633-f95bcbf8-51c0-4340-a544-4271632dc2a3.png">

<img width="2172" alt="image" src="https://user-images.githubusercontent.com/25161793/236637636-0e4a52d4-bd55-495a-b5db-ef02219b9808.png">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_131c1_688ca0.json?f_userOrOld=uploaded%20sample

Gisaid query: G4006A, T17067C, T26012 (edited)

**Comment by FedeGueli** [comment]
14 as today with your query @corneliusroemer G4006A, T17067C, T26012G but Usher shows me 15 all in the branch that has all the three nuc mutation of Orf7b:A43L (C27881T, G27882C, C27883T reverted so  Orf7b:43A likely just a misbranching of this one or artefact?  cc @ryhisner @angiehinrichs

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22104_362660.json?c=gt-nuc_27882&label=id:node_674574
![Schermata 2023-05-16 alle 13 07 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/98ee0484-8968-4de6-ab7c-37394ddd2e76)
![Schermata 2023-05-16 alle 13 11 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/98d10be9-0ff6-4e32-9a84-9817f9203817)

**Comment by ryhisner** [comment]
No, the ORF7b:A43L thing is definitely real—it's repeatedly shown up in a variety of sequences from all over the world throughout the course of the pandemic—though the branches that have it reverted almost certainly don't belong in this tree.

**Comment by FedeGueli** [comment]
Thx @ryhisner great explanation!

**Comment by FedeGueli** [comment]
18 seqs as today last three coming fom Canada  found with G4006A, T17067C, T26012

**Comment by FedeGueli** [comment]
last tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c3ff_c9a290.json?label=id:node_6903416

**Comment by FedeGueli** [comment]
23 seqs as today

**Comment by corneliusroemer** [comment]
Just rediscovered this, sequences from French Guiana (right next to Brazil) make this look quite strongly like an FE.1 recombinant, so I've designated it as XCF

**Comment by FedeGueli** [comment]
Thx @corneliusroemer Guyana Suriname and french Guyana seems under a surge (Cases and deaths for Suriname, Cases for Guyana, still not much for French Guyana) and they are next to the Brazilian region of AMAPA' from some worrying warning has been raised. So very good to designate everything we are certainly circulating there.
![Schermata 2023-06-10 alle 13 18 16](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8977e8a7-224c-4d7b-8106-121c67517edd)

**Comment by FedeGueli** [comment]
PS : i agree it is a recombinant it took the orf1ab from some other XBB lineage:
![Schermata 2023-06-10 alle 13 25 06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/07cfcdac-7e30-4525-a77e-91874b81b8c2)
https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-03-31%26to%3D2023-06-10/variants?nucMutations=G4006A%2CT17067C%2CT26012&nextcladePangoLineage1=FE.1*&analysisMode=CompareEquals&

**Comment by FedeGueli** [comment]
XCF
