### ISSUE TITLE
Proposal to withdraw several lineages or make better definitions

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#20]
In recent update, there are several lineages designated with 3' UTR mutations, those are
XBB.1.5.64 cov-lineages/pango-designation@d558bca
and
FL.9 cov-lineages/pango-designation@5ff879e

~~Besides,
XBB.1.5.68 cov-lineages/pango-designation@90ada11
seems to be a sub-lineage of XBB.1.5.43? Wasn't sure about this one, can someone check it?~~

@corneliusroemer

**Comment by krosa1910** [comment]
> Besides, XBB.1.5.68 [cov-lineages/pango-designation@90ada11](https://github.com/cov-lineages/pango-designation/commit/90ada11) seems to be a sub-lineage of XBB.1.5.43? Wasn't sure about this one, can someone check it?

Quite sure it is not. As we have long seen, most of xbb.1.5* has T17124C, 1.5.43 does not, 1.5.68 does. Although we are not so sure if that mutation occurred one time, but the fact that there exist a major subgroup defined by T10204C, which is entirely within T17124C clade suggest that T17124C probably evolve within a single event.
