### ISSUE TITLE
KP.2.3 subbranch with S:del243-244, Orf1a:P2079S and Orf1b:E913D(US-CA 3)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2002]
KP.2.3> C28714T> T16563A> C6500T(Orf1a:P2079S), C12115T> G16206T(Orf1b:E913D), del22289_22294(S:del243-244)
Query: C6500T, C12115T, del22289_22294

06-22 San Diego, California, US
Sequences: EPI_ISL_19391889, EPI_ISL_19391895-19391896

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3fedd_5de60.json?c=country&label=id:node_7063625
![image](https://github.com/user-attachments/assets/8b7142f5-7656-481e-bfe0-ac904c335b00)

![image](https://github.com/user-attachments/assets/f7399e20-e573-4993-a8ce-3788aef66c08)

**Comment by FedeGueli** [comment]
Likely already dead

**Comment by FedeGueli** [comment]
Thx
