### ISSUE TITLE
KP.2.3 subbranch with S:del185-189(20 sequences, 3 countries) 8% in Chile in September

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2003]
KP.2.3> C28714T> C18555T> G12208A> C878T, del22114-22128(S:del185-189)
Query: C878T, G12208A, C18555T

Earliest sequence: 07-15 Texas, USA PQ147847.1
Latest sequence: 08-26 Punta Arenas, Magallanes, Chile EPI_ISL_19390712
Regions detected: US 9(1 not on GISAID, 1 airport pooled), Chile 3, UK 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5b00e_5a600.json?c=country&label=id:node_11644620
![image](https://github.com/user-attachments/assets/bd80f979-ecda-4c9b-83d7-e618862cbfcd)

![image](https://github.com/user-attachments/assets/b56bbb6d-be37-4e40-b169-0e1e102c74ea)

This lineage is found with a modified version of @aviczhl2 's tool:
https://github.com/aviczhl2/usher_analyse_tool/blob/Over-There-Is-1/analyse-modified.py
![image](https://github.com/user-attachments/assets/e0860ea1-1e8b-44af-bdb4-0822851a0060)

Sequences:
EPI_ISL_19307745, EPI_ISL_19316820, EPI_ISL_19335234,
EPI_ISL_19335490, EPI_ISL_19342392, EPI_ISL_19347439,
EPI_ISL_19349121, EPI_ISL_19349319, EPI_ISL_19349993,
EPI_ISL_19390712, EPI_ISL_19390746, EPI_ISL_19390749,
PQ147847.1

**Comment by Over-There-Is** [comment]
label:"Deletions between S:180-190" @aviczhl2 @FedeGueli

**Comment by DailyCovidCases** [comment]
Currently still no new seqs

**Comment by FedeGueli** [comment]
Chile has not uploaded anything since

**Comment by DailyCovidCases** [comment]
Close this issue @Over-There-Is

**Comment by FedeGueli** [comment]
No one in the last batch from Chile
