### ISSUE TITLE
KP.3.1.1 subbranch with S:G946R and Orf1a:K527R, A2821T, I3587V(CA-ON 13)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2004]
KP.3.1.1> G2890A> C186T, A1845G(Orf1a:K527R), A11024G(Orf1a:I3587V), C27513T, G29434A> G8726A(Orf1a:A2821T), G13459A, G24398A(S:G946R)
Query: C186T, A1845G, G8726A

08-17~09-20 Ontario, Canada
Sequences:
EPI_ISL_19386345, EPI_ISL_19386351-19386352, EPI_ISL_19386388,
EPI_ISL_19386412, EPI_ISL_19386511, EPI_ISL_19386524,
EPI_ISL_19386646, EPI_ISL_19389713, EPI_ISL_19389807

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4710d_3d730.json?c=country&label=id:node_7116757
![image](https://github.com/user-attachments/assets/a9d30bb1-912a-4669-a88f-7df00f238e2c)

**Comment by FedeGueli** [comment]
13

**Comment by FedeGueli** [comment]
Ontario Only closing it for now
