### ISSUE TITLE
LB.1.7.2 subbranch with S:T208M(US 11, 2 states)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2005]
LB.1.7.2> C22185T(S:T208M)
Query: C22185T, T23600C

Earliest sequence: 06-16 Colorado, USA EPI_ISL_19217764
Latest sequence: 08-15 Colorado, USA EPI_ISL_19376434
Regions detected: Colorado 9(1 not on GISAID), Minnesota 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3b78f_41440.json?c=country&label=id:node_7026417
![image](https://github.com/user-attachments/assets/8d3468fd-6358-4cb2-b48b-1b58a32f3ff6)

Sequences:
EPI_ISL_19217764, EPI_ISL_19269206, EPI_ISL_19269222,
EPI_ISL_19281982, EPI_ISL_19376354, EPI_ISL_19376434,
EPI_ISL_19387366, EPI_ISL_19387368, EPI_ISL_19387491,
PQ242928.1

**Comment by FedeGueli** [comment]
it seems slow

**Comment by FedeGueli** [comment]
no recent samples closing this
