### ISSUE TITLE
KP.2.3 subbranch with S:H1101Y (US 64, 8 states)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2006]
KP.2.3> C28076T> A5431G> C24863T(S:H1101Y)
Query: A5431G, C24863T
Query for Louisiana sequence without A5431G: -A5431G, C18894T, C24863T, C26151T

Earliest sequence: 06-01 Colorado, US EPI_ISL_19217815
Latest sequence: 08-25 Utah, US EPI_ISL_19376465
Regions detected:  Colorado 33, Louisiana 8, Nevada 3, Florida 1(not on GISAID), Michigan 1, New Mexico 1, Utah 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_14fdc_55720.json?c=country&label=id:node_7058579
![image](https://github.com/user-attachments/assets/98e97c32-d243-4a24-9e59-2475da1e5bb2)

<details><summary>Sequences:</summary>

EPI_ISL_19208491, EPI_ISL_19217725, EPI_ISL_19217815,
EPI_ISL_19233995, EPI_ISL_19234101, EPI_ISL_19234134,
EPI_ISL_19269274, EPI_ISL_19269292, EPI_ISL_19287179,
EPI_ISL_19287189, EPI_ISL_19290311, EPI_ISL_19293598,
EPI_ISL_19304822, EPI_ISL_19304879, EPI_ISL_19325202,
EPI_ISL_19333288, EPI_ISL_19333353, EPI_ISL_19343245,
EPI_ISL_19343285, EPI_ISL_19343317, EPI_ISL_19343335-19343336,
EPI_ISL_19343359, EPI_ISL_19346335, EPI_ISL_19346372,
EPI_ISL_19346402, EPI_ISL_19346456, EPI_ISL_19346486,
EPI_ISL_19346517, EPI_ISL_19346575, EPI_ISL_19368016,
EPI_ISL_19368025, EPI_ISL_19368054, EPI_ISL_19376370,
EPI_ISL_19376402, EPI_ISL_19376410, EPI_ISL_19376430,
EPI_ISL_19376465, EPI_ISL_19387335, EPI_ISL_19387355,
EPI_ISL_19387374, EPI_ISL_19387379, EPI_ISL_19387382,
EPI_ISL_19387423, EPI_ISL_19387442, EPI_ISL_19387452,
EPI_ISL_19390129, PQ040697.1
</details>

**Comment by FedeGueli** [comment]
Few recent samples and very geographically limited.

**Comment by Over-There-Is** [comment]
Iowa

**Comment by FedeGueli** [comment]
no recent samples closing it
