### ISSUE TITLE
MB.1.1 subbranch with S:P809S(7 sequences, IT 6, US 1)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2007]
MB.1.1> G10465A> C12970T, C23987T(S:P809S)
Query: G10465A, C12970T, C23987T

Earliest sequence: 07-27 Umbria, Italy EPI_ISL_19322549
Latest sequence: 08-20 Umbria, Italy EPI_ISL_19387737
Regions detected: Italy 5, US 1(not on GISAID)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5ea03_90270.json?c=country&label=id:node_6966906
![image](https://github.com/user-attachments/assets/0a192a9b-6598-4693-9d44-0d62790fee1f)

Sequences:
EPI_ISL_19322549-19322550, EPI_ISL_19387715, EPI_ISL_19387737,
EPI_ISL_19387750, PQ242884.1

**Comment by Over-There-Is** [comment]
Roma

**Comment by xz-keg** [comment]
G10465A branch designated MB.1.1.3
