### ISSUE TITLE
LB.1.3 subbranch with Orf10:Q29*(CA-ON 60)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2008]
LB.1.3> C3817T> C18591T> C12400T, C29095T, C29642T(Orf10:Q29*)
Query: C12400T, C18591T, C29095T

08-20~08-30 Ontario, Canada
Sequences:
EPI_ISL_19375086, EPI_ISL_19386421, EPI_ISL_19386451-19386452,
EPI_ISL_19386488, EPI_ISL_19386532, EPI_ISL_19386543-19386544,
EPI_ISL_19386560, EPI_ISL_19386614-19386618, EPI_ISL_19386620,
EPI_ISL_19386622-19386628, EPI_ISL_19386632-19386639, EPI_ISL_19386735,
EPI_ISL_19386772-19386773, EPI_ISL_19386777, EPI_ISL_19386789-19386790,
EPI_ISL_19389463, EPI_ISL_19389468, EPI_ISL_19389814,
EPI_ISL_19389822

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_72d9_92f20.json?c=country&label=id:node_7024354
![image](https://github.com/user-attachments/assets/d7bf7e56-7a3d-48ed-93c8-01cac496e768)

**Comment by FedeGueli** [comment]
Likely an Ontario CLuster

**Comment by FedeGueli** [comment]
Still Ontario only closing it
