### ISSUE TITLE
LB.1 subbranch with S:M731I (42, CA 33, US 9) and further Orf3d:Q22*(CA-ON 31) on Orf1b:R276C, Orf3a:A33S branch

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2009]
LB.1> C14293T(Orf1b:R276C), T22357C, G25489T(Orf3a:A33S)> T18033C, C18060T> G23755T(S:M731I)> C22639T, C25587T(Orf3d:Q22*)
Query: C14293T, T18033C, G23755T

Earliest sequence: 06-11 Puerto Rico, USA EPI_ISL_19224197
Latest sequence: 08-30 Ontario, Canada EPI_ISL_19389530
Regions detected: Canada 23, US 9(1 not on GISAID, including Puerto Rico 4)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_12dad_959d0.json?c=country&label=id:node_7030454
![image](https://github.com/user-attachments/assets/52f1dfc4-2800-4334-a389-49e63f41a1ad)

Sequences:
EPI_ISL_19224197, EPI_ISL_19224202, EPI_ISL_19234054,
EPI_ISL_19284558-19284559, EPI_ISL_19303437, EPI_ISL_19318394,
EPI_ISL_19328487, EPI_ISL_19336889, EPI_ISL_19343671,
EPI_ISL_19386417, EPI_ISL_19386471, EPI_ISL_19386709-19386710,
EPI_ISL_19386714-19386715, EPI_ISL_19389529-19389530, EPI_ISL_19389532,
EPI_ISL_19389534, EPI_ISL_19389544, EPI_ISL_19389583,
EPI_ISL_19389586, EPI_ISL_19389594, EPI_ISL_19389605,
EPI_ISL_19389624, EPI_ISL_19389626, EPI_ISL_19389639,
EPI_ISL_19389641, EPI_ISL_19389658, EPI_ISL_19389671,
PQ108181.1

**Comment by FedeGueli** [comment]
It likely revived due to a Canadian cluster.

**Comment by FedeGueli** [comment]
recent oneas are all from Ontario closing it for now
