### ISSUE TITLE
BA.1.1 mini saltation (2 seq., USA)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#201]
Proposal for a sublineage of BA.1.1
Earliest sequence: 03.02.2023 (USA)
Countries detected: USA

Two different originating & submitting labs in Nashville, TN, USA.

Defining Mutations:
nuc	unique	C147T, G295T, G521T, G896A, T3952C, C4189T, C4878T, G7677A, G11417T, T11515A, C11687T, C13506T, C15579T, C16915A, T17613C, C19881T, C20515G, G22017T, G22139T, T22246C, A22582T, G22895T, T22942G, G23040T, A23125T, C26728T, C28473T
nuc	homoplasies	C313T, C8139T, C15720T, G17122T, C18698T, T22926C, C25002T, C26571T, C27131T, C29085T
ORF1ab	unique	E10D, V86F, A211T, T1538I, R2471K, V3718F, L3808F, L5551M, L6751V
ORF1ab	homoplasies	S2625F, A5620S, A6145V
S	unique	W152L, E340D, V445F, N460K, R493L
S	homoplasies	V193L, L455S, S1147L
M	unique	A69V
M	homoplasies	L17F
N	unique	P67L
N	homoplasies	T271I

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/f758d819-f309-4e38-868d-3dbe8544bffb)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ad01_bfcab0.json?c=userOrOld&label=id:node_5640989

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/f5156a48-ee5c-4db1-a366-d7db631dc1a7)

EPI_ISL_17544283
EPI_ISL_17806504

**Comment by FedeGueli** [comment]
Impressive but luckily very old samples.
