### ISSUE TITLE
LF.7 subbranch with S:K529N and Orf1a:R1225I (NG 2 via US-VA)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2010]
LF.7> G3939T(Orf1a:R1225I), C7973T, G23149T(S:K529N)
Query: C7973T, C8293T, G23149T

08-28 IAD Airport, Virginia, USA(1 pooled, 1 from Nigeria)
Sequences: EPI_ISL_19386101, EPI_ISL_19386131

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_36fa2_9a010.json?c=country&label=id:node_7043785
![image](https://github.com/user-attachments/assets/ec460779-2d9d-4c5e-8a05-fed9e40bdc1e)

**Comment by FedeGueli** [comment]
K529N likely creates a new Glycan, but it has never been advantageous as of today

**Comment by aviczhl2** [comment]
No new seqs
