### ISSUE TITLE
KP.2.3 subbranch with Orf9b:P>S10F, Orf1a:Q884E, Q1201K and Orf3a:F105L(CA-ON 19)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2011]
SubBranch of  https://github.com/cov-lineages/pango-designation/issues/2767

KP.2.3> C2915G(Orf1a:Q884E)> T25705C(Orf3a:F105L)> C3866A(Orf1a:Q1201K)> C22624T> C28312T(Orf9b:S10F)
Query: C3866A, C22624T, C28312T
08-06~08-21 Ontario, Canada

Sequences:
EPI_ISL_19343672, EPI_ISL_19343864, EPI_ISL_19343900,
EPI_ISL_19343903, EPI_ISL_19343905, EPI_ISL_19345730,
EPI_ISL_19358010-19358012, EPI_ISL_19358197, EPI_ISL_19386384,
EPI_ISL_19386397-19386398, EPI_ISL_19386404, EPI_ISL_19386406,
EPI_ISL_19386428, EPI_ISL_19386430-19386431

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4be24_9ed30.json?branchLabel=nuc%20mutations&c=country&label=id:node_7055003
![image](https://github.com/user-attachments/assets/5af9c50d-ece8-40af-a468-ad5914b297dc)

**Comment by Over-There-Is** [comment]
subbranch of cov-lineages/pango-designation#2767

**Comment by FedeGueli** [comment]
Also this one is quite exclusively Ontario
