### ISSUE TITLE
KP.1.1.3 subbranch with S:T>K478R, Orf1a:L1249F, D2026N, Orf1b:S442N and Orf6:L35F(CA-ON 32)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2012]
(_First spotted by @nkrmnzr in the groups wi and tracked hence with the query : C4010T, C27304T_)

KP.1.1.3> G6341A(Orf1a:D2026N)> G14792A(Orf1b:S442N)> C4010T(Orf1a:L1249F), A22995G(S:K478R), C27304T(Orf6:L35F)
Query:C4010T, G6341A, C22995G

06-08~08-28 Ontario, Canada

Sequences:
EPI_ISL_19201570, EPI_ISL_19214613, EPI_ISL_19229253,
EPI_ISL_19254379, EPI_ISL_19254401, EPI_ISL_19293869-19293870,
EPI_ISL_19293981, EPI_ISL_19293992, EPI_ISL_19343941,
EPI_ISL_19358090, EPI_ISL_19358096, EPI_ISL_19358102,
EPI_ISL_19358156, EPI_ISL_19358229-19358230, EPI_ISL_19358365,
EPI_ISL_19375120, EPI_ISL_19386306, EPI_ISL_19386308,
EPI_ISL_19386392-19386394, EPI_ISL_19386402, EPI_ISL_19386460,
EPI_ISL_19386631, EPI_ISL_19393507-19393508

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_66142_a51e0.json?c=country&label=id:node_7016788
![image](https://github.com/user-attachments/assets/5d1f4279-fa4a-42ac-96b9-e173baf61982)

**Comment by FedeGueli** [comment]
This was spotted by @nkrmnzr one or two weeks ago i was tracking it with C4010T, C27304T

**Comment by FedeGueli** [comment]
32 still cluster only

**Comment by Over-There-Is** [comment]
I could only find 28. Are there some sequences deleted?

**Comment by Over-There-Is** [comment]
C4010T, C27304T catches 4 unrelated sequences.

**Comment by FedeGueli** [comment]
ah yeah i ve tracked since  it has been found with the original query, 4 old samples.

**Comment by FedeGueli** [comment]
Still a cluster we can close it.
