### ISSUE TITLE
KP.1.1.1 subbranch with S:del257-260 on Orf1a:S2488F branch(29 seqs, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2013]
KP.1.1.1> C7728T(Orf1a:S2488F)> T18771C> C20178T> del22331-22342(S:del257-260)
Query: T18771C, del22331_22342

Earliest sequence: 05-03 Ontario, Canada EPI_ISL_19134259
Latest sequence: 07-01 Denmark EPI_ISL_19265046
Regions detected: Canada 21, US 6, Denmark 1, India 1

[Phylogenic Tree](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4b87c_be4a0.json?c=country&label=id:node_7051049&s=Canada/BC-BCCDC-716300/2024%7CEPI_ISL_19223796%7C2024-06-10,Canada/ON-PHL-202407710/2024%7CEPI_ISL_19134259%7C2024-05-03,Canada/ON-PHL-202407721/2024%7CEPI_ISL_19134270%7C2024-05-04,Canada/ON-PHL-202407722/2024%7CEPI_ISL_19134271%7C2024-05-04,Canada/ON-PHL-202407727/2024%7CEPI_ISL_19134276%7C2024-05-03,Canada/ON-PHL-202407737/2024%7CEPI_ISL_19134285%7C2024-05-03,Canada/ON-PHL-202407815/2024%7CEPI_ISL_19153332%7C2024-05-05,Canada/ON-PHL-202407818/2024%7CEPI_ISL_19153335%7C2024-05-05,Canada/ON-PHL-202407827/2024%7CEPI_ISL_19153344%7C2024-05-05,Canada/ON-PHL-202407828/2024%7CEPI_ISL_19153345%7C2024-05-05,Canada/ON-PHL-202407835/2024%7CEPI_ISL_19153352%7C2024-05-07,Canada/ON-PHL-202407844/2024%7CEPI_ISL_19153361%7C2024-05-07,Canada/ON-PHL-202407862/2024%7CEPI_ISL_19153377%7C2024-05-08,Canada/ON-PHL-202407987/2024%7CEPI_ISL_19165473%7C2024-05-09,Canada/ON-PHL-202408014/2024%7CEPI_ISL_19165451%7C2024-05-11,Canada/ON-PHL-202408043/2024%7CEPI_ISL_19153475%7C2024-05-09,Canada/ON-PHL-202408044/2024%7CEPI_ISL_19153476%7C2024-05-09,Canada/ON-PHL-202408160/2024%7CEPI_ISL_19153587%7C2024-05-14,Canada/ON-PHL-202408186/2024%7CEPI_ISL_19165470%7C2024-05-15,Canada/ON-PHL-202408275/2024%7CEPI_ISL_19165534%7C2024-05-19,Canada/ON-PHL-202408663/2024%7CEPI_ISL_19188295%7C2024-05-31,Denmark/DCGC-686940/2024%7CEPI_ISL_19265046%7C2024-07-01,India/MH_BJCOG_INSACOG_6750/2024%7CEPI_ISL_19208451%7C2024-05-28,USA/CO-CDPHE-42012076/2024%7CPQ056468.1%7C2024-06-20,USA/OH-PLMI-7CL-26160/2024%7CEPI_ISL_19378774%7C2024,USA/OH-PLMI-7CL-26196/2024%7CEPI_ISL_19378810%7C2024,hCoV-19/USA/TN-SPHL-3765/2024%7CEPI_ISL_19393689%7C2024-06-26,hCoV-19/USA/TN-SPHL-3766/2024%7CEPI_ISL_19393690%7C2024-06-26,hCoV-19/USA/TN-SPHL-3774/2024%7CEPI_ISL_19393694%7C2024-06-28)
![image](https://github.com/user-attachments/assets/c1ed7497-9470-488a-ab36-48d45042481a)

Sequences:
EPI_ISL_19134259, EPI_ISL_19134270-19134271, EPI_ISL_19134276,
EPI_ISL_19134285, EPI_ISL_19153332, EPI_ISL_19153335,
EPI_ISL_19153344-19153345, EPI_ISL_19153352, EPI_ISL_19153361,
EPI_ISL_19153377, EPI_ISL_19153475-19153476, EPI_ISL_19153587,
EPI_ISL_19165451, EPI_ISL_19165470, EPI_ISL_19165473,
EPI_ISL_19165534, EPI_ISL_19188295, EPI_ISL_19208451,
EPI_ISL_19223796, EPI_ISL_19265046, EPI_ISL_19269252,
EPI_ISL_19378774, EPI_ISL_19378810, EPI_ISL_19393689-19393690,
EPI_ISL_19393694

**Comment by FedeGueli** [comment]
apparently dead

**Comment by aviczhl2** [comment]
No new seqs

**Comment by Over-There-Is** [comment]
Mexican old sequences +2
