### ISSUE TITLE
XDY.1  (S:A435S, S:A1174T, N:R36Q, ORF7a:P34L, ORF9b:D33N )  with S:T572I [15 SEQS]

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#2014]
XDY.1 > S:T572I (C23277T)
Query: C23277T,G25082A, G28380A
Samples: 11
Places: 6 including South Africa and Greece
Tree:
<img width="1173" alt="Screenshot 2024-11-16 alle 20 11 17" src="https://github.com/user-attachments/assets/46f063d5-eea4-4faf-bb9e-a95576df0f22">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_504eb_8ed910.json?label=id:node_7202420

### **XDY.1 ORIGINAL PROPOSAL:**
**Description**
**Sub-lineage of:** XDY
**Earliest sequence:** 2024-7-31, USA, Massachusetts — EPI_ISL_19347338
**Most recent sequence:** 2024-8-28, USA, South Carolina — EPI_ISL_19394879
**Continents circulating:** Europe (4), North America (2)
**Countries circulating:** France (2), USA (2), Scotland (1), Sweden (1)
**Number of Sequences:** 6
**GISAID Nucleotide Query:** C27494T, G28380A, G22865T
**CovSpectrum Query:** [3-of: C27494T, G28380A, G22865T]
**Substitutions on top of XDY:**
**Spike:** A435S, A1174T (+ T572I in further, 3-seq branch)
**N:** R36Q
**ORF7a:** P34L
**ORF9b:** D33N
**ORF1a:** ∆82-84, M85V (only in further, 3-seq branch)
**Nucleotide:** G22865T, G25082A, C27494T, G28380A (+ ∆510-518, C23277T in further branch)

**Phylogenetic Order of Mutations:** C27494T (ORF7a:P34L) **→** G25082A, G28380A (S:A1174T, N:R36Q, ORF9b:D33N) **→** G22865T (S:A435S) **→** ∆510-518, C23277T (ORF1a:∆82-84, ORF1a:M85V, S:T572I) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons3/main/XDY_A435S_A1174T.json
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/4480a11e-11cd-4462-8649-2bb22cf25345">

**Evidence**
Seems to be a lot of positive selection in this branch. All mutations here are non-synonymous, and one sequence here has, on top of baseline XDY, eight AA mutations—four in spike—on just seven nuc substitutions (5/6 non-synonymous with one double N/ORF9b mutation + an out-of-frame ORF1a deletion causing ORF1a:M85V). Wide geographic spread and recent collection dates make it worth watching. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19344396, EPI_ISL_19347338, EPI_ISL_19357169, EPI_ISL_19372202, EPI_ISL_19389996, EPI_ISL_19394879
</details>

**Comment by FedeGueli** [comment]
Very interesting one : Orf7a:P34L/S has been in 50K sequences and mutliple lineages especially in the vocs era. 
435S is the only convergent&successful mutation in the rbd recently (beyond 493E,FLiRT, 445X and 478X)
S:A1174V (here is T) is convergent (and going) in #1843 and #1997 despite not being widespread it was already in B.1.1.7 and other lineages.
Plus double Orf9b/N mutation are always something to watch although this one has not been widesporead

**Comment by ryhisner** [comment]
One showed up in Italy today. Clusters with sequences from France, Scotland, and Sweden. The Swedish sequence belongs with the middle branch but isn't included due to dropout. They all share C5482T.
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/8e1d4661-103b-4345-9684-606ebe5691ff">

**Comment by FedeGueli** [comment]
+2 FRANCE, ONE FROM GBW pointing to some sort of prevalence there. please propose when it reaches 20

**Comment by FedeGueli** [comment]
@ryhisner there was at ypo in the title it is Orf9b:D33N as correctly reported in the proposal , right?
![Uploading Screenshot 2024-09-16 alle 10.29.17.png…]()

**Comment by FedeGueli** [comment]
13 Canada

**Comment by DailyCovidCases** [comment]
> 13 Canada

I will proposed it on the main page if this branch reaches 20 seqs

**Comment by FedeGueli** [comment]
> > 13 Canada
> 
> I will proposed it on the main page if this branch reaches 20 seqs

No you have to ask Ryan before doing anything.

**Comment by DailyCovidCases** [comment]
@ryhisner You should propose this branch if it reaches at least 20 seqs

**Comment by FedeGueli** [comment]
+1 US

**Comment by FedeGueli** [comment]
Better tracking this here for a while more.

**Comment by FedeGueli** [comment]
+1 NY

**Comment by xz-keg** [comment]
+1 Greece +1 South Africa for the S:T572I branch.

**Comment by FedeGueli** [comment]
> +1 Greece +1 South Africa for the S:T572I branch.

THX  JUST REOPENED IT

**Comment by FedeGueli** [comment]
recent samples from netherlands , keeping this open for a while (XDY seems better now than when emerged likely due the double N Glycan)

**Comment by FedeGueli** [comment]
15 but not fast even if likely spread somewhere without sampling strategy

**Comment by Over-There-Is** [comment]
Finland +4

**Comment by FedeGueli** [comment]
20, better keeping an eye on it even if it is close

**Comment by FedeGueli** [comment]
+1 Canada January

**Comment by FedeGueli** [comment]
Further S:T572I sublineage Designated XDY.1.1 from https://github.com/cov-lineages/pango-designation/commit/3ed0f3a48a55928d1f22bc4ff453eed27ad3e36a
