### ISSUE TITLE
MC.10 (C16332T) + S:I101T, S:A376D  [11 seq, USA, Denmark, Canada,Netherlands] with a S:A376N (2-nuc), ORF1a:K2200R, ORF1a:K3353R, ORF1b:Y113H sub branch (7)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#2015]
**Description**
**Sub-lineage of:** KP.3.1.1
**Earliest sequence:** 2024-8-19, Denmark — EPI_ISL_19378193
**Most recent sequence:** 2024-8-26, USA, Delaware — EPI_ISL_19394774
**Continents circulating:** Europe (1), North America (1)
**Countries circulating:** Denmark (1), USA (1)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** A6864G, T10033C
**Suggested query to catch all the sequences of this branch** : T21864C, C22689A, T28924C (**EDITED**)
**CovSpectrum Query:** Nextcladepangolineage:KP.3.1* & [3-of: A6864G, T10033C, T13804C, C16332T, T21864C, C22689A, T28924C]
**Substitutions on top of KP.3.1.1:**
**Spike:** I101T, A376N (2-nuc)
**ORF1a:** K2200R, K3353R
**ORF1b:** Y113H
**Nucleotide:** A6864G, T10033C, A10323G, T13804C, C16332T, T21864C, G22688A, C22689A, T28924C

**Phylogenetic Order of Mutations:** Probably all at once.

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/KP.3.1.1_I101T_A376N_K3353R.json?c=gt-S_376&gmax=25384&gmin=21563&label=id:node_11644621
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/ca6668b0-8810-4992-966e-4b8ca53dda9a">

**Evidence**
S:I101T adds a glycan at S:N99, while S:A376N is an extremely rare 2-nuc mutation. Just two sequences, but they’ve appeared on opposite sides of the Atlantic. The seq on the Usher tree that appears to have S:A376D is an artifact. Both sequences have S:A376N. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19378193, EPI_ISL_19394774
</details>

**Comment by ryhisner** [comment]
Thought this was dead, but another just showed up in Canada (Ontario) today. September 17 collection date. EPI_ISL_19432615

Very weird: just three sequences, but they've appeared in Denmark, USA (Delaware), and Canada (Ontario).

**Comment by FedeGueli** [comment]
KP.3.1.1 sublineages are always slow starter so this could be fast even if it has only three seqs in one month

**Comment by FedeGueli** [comment]
anyway it seems slow

**Comment by DailyCovidCases** [comment]
Closing this, it doesn't seem to be fast now

**Comment by ryhisner** [comment]
This one's still kicking a bit. Three sequences uploaded in the past three days, including the first from Australia and a travel sequence from the Netherlands, also a first. 

The most recent sequence has S:N99K, which eliminates the N99 glycan that S:I101T created. 

<img width="1486" alt="image" src="https://github.com/user-attachments/assets/25a01a90-bd04-4cc9-987c-948c31c76c71">

**Comment by FedeGueli** [comment]
I suggest to use the query that finds all the sequences on the branch : T21864C, C22689A, T28924C
Samples: 8
Places : 6
Tree:
<img width="1160" alt="Screenshot 2024-10-24 alle 09 15 10" src="https://github.com/user-attachments/assets/4046e663-6026-4593-bdb5-203bb5eed0a0">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_b50f_9f22b0.json?label=id:node_7250962

**Comment by FedeGueli** [comment]
Parental lineage of this has now been defined MC.10 with C16332T: Orf1a:K3353R (A10323G) it is homoplasic and likely emerged independently, so it is likely just a misplacement by Usher putting it under the KP.3.1.1 + orf1a:K3353R node:
<img width="1152" alt="Screenshot 2024-10-26 alle 20 41 47" src="https://github.com/user-attachments/assets/be742d56-3890-4a5e-906a-5f87a63f0f38">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice23_genome_test_10884_d0ebe0.json?label=id:node_7247935

cc @angiehinrichs

**Comment by AngieHinrichs** [comment]
Yep, hopefully fixed later today when the 2024-10-31 build is done.

**Comment by FedeGueli** [comment]
11 and 7 but i m ushering them be cause it seems to me there could be more of this in reality for the 376N branch they came from Canada, while for the parental 376D branch they came from New Zealand and Netherlands (GBW)

@ryhisner to me this is highkly interersting and spreading quite well. i suggest to propose it

**Comment by xz-keg** [comment]
designated MC.10.2

**Comment by xz-keg** [comment]
ORF1a:K2200R  ORF1a:K3353R branch is designated MC.10.2.2
