### ISSUE TITLE
KS.1.1/KP.3 recombinant (10 seqs, 5 places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2017]
It seems that there's another KS.1.1/KP.3 recombinant result in the XEC spike of S:T22N,F59S,F456L,Q493E,V1104L. 
It has a slightly different breakpoint that allows it to keep an additional S:R346T. 

KS.1.1--KP.3

Breakpoint between 22600 and 23038 (S:346 and S:493)

Additional mutations: C6701T, T12418C, G16943T, C19716T, 

Orf1a:L2146F
Orf1b:S1159I

C6701T,C19716T,T12418C from a KS.1.1 branch.
G16943T is private

GISAID query: C6701,T12418C, G24872T edited
No. of seqs: 2(Puerto Rico)

EPI_ISL_19391597,19391598, 2024-8-26

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice205_genome_test_5eb4a_253a70.json?label=id:node_5488286)
![image](https://github.com/user-attachments/assets/c6d500df-aef5-4941-9d82-7d1511a6e0e1)

**Comment by FedeGueli** [comment]
+1 PR

**Comment by aviczhl2** [comment]
> C6701T,T12418C, C23039G,

What's the EPI ID?

**Comment by FedeGueli** [comment]
> What's the EPI ID?

it should be EPI_ISL_19433219

I mistaknely use the additional mutations as query : C6701T, T12418C, G16943T, C19716T, T25542A, i guess it belongs to this but i didnt check!

**Comment by FedeGueli** [comment]
Checked it belongs it just dropout at 493

**Comment by aviczhl2** [comment]
There seems to be a new seq without T25542A, change query.

**Comment by FedeGueli** [comment]
> C6701,T12418C, G24872T

Thx!

**Comment by FedeGueli** [comment]
+1 Colorado but one month old

**Comment by xz-keg** [comment]
8, also in Italy.

**Comment by FedeGueli** [comment]
+2 Texas this is growing please propose it.

**Comment by FedeGueli** [comment]
Designated XEQ via https://github.com/cov-lineages/pango-designation/commit/cb20c62917185069475f35cbf11fdc504663431c
