### ISSUE TITLE
JN.1.67.1+S:I794T(21 seqs, Northeastern China)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2018]
This branch seems to have some prevalence in all provinces of NE China(Liaoning, Jilin and Heilongjiang). 

While that region is surrounded by undersampled blackholes( Mongolia, East Russia, North Korea, Inner Mongolia and Beijing, all of them has 0 sampling), this branch may have spread more than it shows. 

JN.1.67.1+G1126A+G14118A+T23943C(S:I794T)

GISAID query: T23943C, G14118A
No. of seqs: 16(China)

First: EPI_ISL_19081033, 2024-4-17, Heilongjiang
Latest: EPI_ISL_19392768, 2024-8-21, Liaoning

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice188_genome_test_5ef8a_253c50.json?label=id:node_56026840)
![image](https://github.com/user-attachments/assets/2d0bdaf8-ce6e-41bb-b581-2b6bf8b0d641)

**Comment by DailyCovidCases** [comment]
@xz-keg This branch has slowed down a lot, please close this

**Comment by FedeGueli** [comment]
@DailyCovidCases when you see the undersampled label think that it could be open for a large period even if without new seqs

**Comment by xz-keg** [comment]
no new seqs
