### ISSUE TITLE
KP.3.1.1 with S:D80Y on T25207C reversion branch (43 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2019]
_Taken as the [comment](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1675#issuecomment-2336679872) from Recombinant Tracking issue #1675_

**Defining Mutations:** `KP.3.1.1` > `T25207C` > `T3160A, G21800T(S:D80Y)`
**Query:** `T3160A, A13121T, G21800T`
**Earliest seq:** 24-08-27 (`EPI_ISL_19386784`, Ontario, Canada)
**Latest seq:** 24-09-03 (`EPI_ISL_19389830`, Ontario, Canada)
**Sampled Countries:** Canada (19: ON)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/ON-PHL-202412700/2024
Canada/ON-PHL-202412701/2024
Canada/ON-PHL-202412702/2024
Canada/ON-PHL-202412703/2024
Canada/ON-PHL-202412776/2024
Canada/ON-PHL-202412777/2024
Canada/ON-PHL-202412778/2024
Canada/ON-PHL-202412779/2024
Canada/ON-PHL-202412780/2024
Canada/ON-PHL-202412799/2024
Canada/ON-PHL-202412882/2024
Canada/ON-PHL-202412889/2024
Canada/ON-PHL-202412918/2024
Canada/ON-PHL-202412936/2024
Canada/ON-PHL-202412954/2024
Canada/ON-PHL-202412962/2024
Canada/ON-PHL-202412963/2024
Canada/ON-PHL-202413148/2024
Canada/ON-PHL-202413149/2024
```

epi_isl accessions:
`EPI_ISL_19386784-19386787, EPI_ISL_19389477-19389481, EPI_ISL_19389499, EPI_ISL_19389580, EPI_ISL_19389587, EPI_ISL_19389615, EPI_ISL_19389633, EPI_ISL_19389649, EPI_ISL_19389654-19389655, EPI_ISL_19389829-19389830`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38369_8f07c0.json?label=id:node_7215918
![image](https://github.com/user-attachments/assets/00b7a171-658d-4980-a342-b26660ffe72c)

**Trivia:**
- Synonymous `C25207T/S:Y1215Y` was introduced on BA.2.86 basal, which is reverted from the parent branch first detectd back in late May. Not sure if this one is involved in any recombinant event, if so, what is the other donor?
- This further `S:D80Y` sub-branch may just be another Canadian cluster, but it already showed some spike diversity, like `S:N440R (from N>K440R)`, `S:T500A`, and `S:Q173K, S:N188D` to name a few.

**Comment by FedeGueli** [comment]
22 still cluster only

**Comment by aviczhl2** [comment]
43 seqs now

**Comment by FedeGueli** [comment]
Ontario only closing it

**Comment by Over-There-Is** [comment]
57, US1

**Comment by FedeGueli** [comment]
60 Slowed down good to be closed
