### ISSUE TITLE
KP.3.1.1 with S:T430I (30 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2020]
**Defining Mutations:** `KP.3.1.1` > `T10561C, C22851T(S:T430I)`
**Query:** `T10561C, C22851T`
**Earliest seq:** 24-07-31 (`EPI_ISL_19346148`, British Columbia, Canada)
**Latest seq:** 24-09-03 (`EPI_ISL_19393560`, Ontario, Canada)
**Sampled Countries:** Canada (14: ON/10, BC/3; AB)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/AB-ABPHL-122026/2024
Canada/BC-BCCDC-726197/2024
Canada/BC-BCCDC-727138/2024
Canada/BC-BCCDC-728229/2024
Canada/ON-KHS-04112-v1/2024
Canada/ON-KHS-04194-v2/2024
Canada/ON-KHS-04201-v2/2024
Canada/ON-PHL-202412824/2024
Canada/ON-PHL-202412825/2024
Canada/ON-PHL-202412826/2024
Canada/ON-PHL-202412839/2024
Canada/ON-PHL-202412976/2024
Canada/ON-PHL-202413006/2024
Canada/ON-PHL-202413007/2024
```

epi_isl accessions:
`EPI_ISL_19346148, EPI_ISL_19364840, EPI_ISL_19365006, EPI_ISL_19375133, EPI_ISL_19380407, EPI_ISL_19389524-19389526, EPI_ISL_19389539, EPI_ISL_19389667, EPI_ISL_19389696-19389697, EPI_ISL_19393553, EPI_ISL_19393560`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_210d2_287d40.json?label=id:node_7128639
![image](https://github.com/user-attachments/assets/4ceefe69-ebfb-45bc-94f2-d6721f554533)

**Comment by FedeGueli** [comment]
A RBD mutation seems an event as of today so worth checking it will not exit from its clkuster only dimension

**Comment by FedeGueli** [comment]
21 still Canada only

**Comment by FedeGueli** [comment]
30 it entered a second cluster in British Columbia

**Comment by FedeGueli** [comment]
no recent samples closing it
