### ISSUE TITLE
KP.2.3/XEC recombinant( 16 seqs)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2023]
![image](https://github.com/user-attachments/assets/2b304d57-c7cb-46bb-87af-73d4105617e2)
![image](https://github.com/user-attachments/assets/6e3ef665-92df-49fe-a0af-0d2af99179bb)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_177ef_34c820.json?f_userOrOld=uploaded%20sample

First Seq: 2024-07-29
Most Recent: 2024-09-02

Gisaid: C7113T & C18657T & C19716T & C25006T & !G20433T
Gisaid with ORF1a:H110Y: C593T & C7113T & C18657T & C19716T & C25006T

EPI_ISL_19390181 EPI_ISL_19373085 EPI_ISL_19372478 EPI_ISL_19368849 Scotland/CLIMB-CM7YJYUU/2024 EPI_ISL_19368841 England/CLIMB-CM7YJNRW/2024 EPI_ISL_19381036 England/CLIMB-CM7YF9X9/2024 EPI_ISL_19381934 EPI_ISL_19364165 OZ175606.1 PQ222176.1

**Comment by Over-There-Is** [comment]
This is a recombinant

**Comment by Over-There-Is** [comment]
Except 3 sequences without coverage on 593, all 16 sequences with C3505T, T5701C, C9286T have C593T too, and this C593T is inherited from a KP.2.3 branch as well as C3505T, C9286T

**Comment by Over-There-Is** [comment]
If you allow, I'll open a new proposal to track it

**Comment by Over-There-Is** [comment]
KP.2.3 / XEC recombinant
Query: C3505T, T5701C, C9286T

Break point: 9286/~15402
Mutations based on JN.1:
C593T(Orf1a:H110Y), C3505T, T5701C(private), C7113T(Orf1a:T2283I), C9286T / C18657T, C19716T, C21627A(S:T22N), T21738C(S:F59S), T22928C(S:F456L), C23039G(S:Q493E), G24872T(S:V1104L), C25006T, C28291A(Orf9b:P3H), G28884C(N:R204P)

5' donor: **KP.2.3> C9286T> C593T> C3505T, A15402G**(=JN.1+C593T, C3505T, C7113T, C9286T / A15402G, G17334T, C22000A, G22599C, T22928C, G24872T, G25593T, C28714T, 3 seqs, DE 2, NL 1)
3' donor: **XEC**(=JN.1+C18657T, C19716T, C21627A, T21738C, T22928C, C23039G, G24872T, C25006T, C28291A, G28884C)

Earliest sequence: 07-19 Denmark EPI_ISL_19332668
Latest sequence: 09-02 England, United Kingdom EPI_ISL_19406440
Regions detected: UK 5, Austria 3, Germany 3, Sweden 2, Denmark 1, Netherlands 1, Ukraine 1

Sequences:
EPI_ISL_19332668, EPI_ISL_19364165, EPI_ISL_19368841,
EPI_ISL_19368849, EPI_ISL_19372478, EPI_ISL_19373085,
EPI_ISL_19381036, EPI_ISL_19381934, EPI_ISL_19385623,
EPI_ISL_19389047, EPI_ISL_19389054, EPI_ISL_19390181,
EPI_ISL_19406420, EPI_ISL_19406440, EPI_ISL_19410161,
EPI_ISL_19410789


And 1 sequence seem also related to this branch: EPI_ISL_19378121(potential contaminated)

**Comment by Over-There-Is** [comment]
@aviczhl2 only 16 are recombinant

**Comment by FedeGueli** [comment]
Designated XEK via https://github.com/cov-lineages/pango-designation/commit/ba3711a5615956ed97150288eb68356aa0fe7cdd
