### ISSUE TITLE
MK.1 (KP.3.1.6 +31F) +S:P384S, Orf3a:G44V, N:G30D or N:S33D, Orf9b:V30M(AU-QLD 15)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2024]
MK.1> C4795T> C16995T> C15024T> T16170C, C22712T(S:P384S), G25523T(Orf3a:G44V), G28371A(N:G30D, Orf9b:V30M)
Query: C22712T, G25523T, G28371A
![image](https://github.com/user-attachments/assets/352ddf43-d484-42ec-878b-c2bf8d6ad882)

07-24~08-13 Queensland, Australia

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_854e_415da0.json?label=id:node_7103851
![image](https://github.com/user-attachments/assets/9a08a071-cc1d-4dc8-94b7-9e617a1829e3)

Sequences: 
EPI_ISL_19330856, EPI_ISL_19330861, EPI_ISL_19330898,
EPI_ISL_19330913, EPI_ISL_19353027, EPI_ISL_19353047,
EPI_ISL_19411820, EPI_ISL_19411824, EPI_ISL_19411827,
EPI_ISL_19411831

_Edited: note that Gisaid and Covspectrum reads it as N:S33D not N:G30D while Usher mistakes it due the deletion as N:S33N _

**Comment by Over-There-Is** [comment]
Label:"ORF9b"

**Comment by FedeGueli** [comment]
Gisaid and Covspectrum reads it as N:S33D

**Comment by Over-There-Is** [comment]
G30D and S33D are same, it's originally N:GERS30-33G, and that amino acid becomes D now.

**Comment by FedeGueli** [comment]
> G30D and S33D are same, it's originally N:GERS30-33G, and that amino acid becomes D now.
yeah for sure but the important thing here is to highlight always how different tools read something,

**Comment by FedeGueli** [comment]
11 still QLD,Aus

**Comment by DailyCovidCases** [comment]
@xz-keg This branch has slowed down a lot, please close this

**Comment by FedeGueli** [comment]
no new seqs in the recent Aus batches

**Comment by Over-There-Is** [comment]
16, still in Queensland
