### ISSUE TITLE
KP.2.3 subbranch with Orf3d-2:K6* (141 sequences, 8 or 9 countries, mainly in US-TX)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2025]
KP.2.3> C28714T> T7438C> T18438C> A25983T(Orf3d-2:K6*)
Query: C8293T, T18438C, A25983T
Query for sequences without T18438C: -T18438C, A25983T, C28714T

Earliest sequence: 05-18 England, UK EPI_ISL_19187747
Latest sequence: 09-01 Nebraska, US EPI_ISL_19407519
Regions detected: US 118(Texas 69, 12 states, 8 not on GISAID), Canada 5, Brazil 3, UK 5, Italy 2, Chile 1, Japan 1(from US or Mexico)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4baf7_42be10.json?c=country&label=id:node_7070228
![image](https://github.com/user-attachments/assets/017a2812-5f10-4b61-b442-43598075d0cc)

<details><summary>Sequences:</summary>

EPI_ISL_19187747, EPI_ISL_19210644, EPI_ISL_19216695,
EPI_ISL_19216697, EPI_ISL_19224979, EPI_ISL_19239302,
EPI_ISL_19251198, EPI_ISL_19259887, EPI_ISL_19262428,
EPI_ISL_19264026, EPI_ISL_19268485, EPI_ISL_19270034,
EPI_ISL_19286922, EPI_ISL_19295163, EPI_ISL_19295173,
EPI_ISL_19295198, EPI_ISL_19295243, EPI_ISL_19301092,
EPI_ISL_19306322, EPI_ISL_19311032, EPI_ISL_19311537,
EPI_ISL_19311543, EPI_ISL_19314519, EPI_ISL_19317627,
EPI_ISL_19317653, EPI_ISL_19317681, EPI_ISL_19317749,
EPI_ISL_19317889, EPI_ISL_19318121, EPI_ISL_19318528,
EPI_ISL_19318925, EPI_ISL_19324448, EPI_ISL_19325512,
EPI_ISL_19332212, EPI_ISL_19334693, EPI_ISL_19334850,
EPI_ISL_19334890, EPI_ISL_19334913, EPI_ISL_19334930,
EPI_ISL_19334954, EPI_ISL_19335070, EPI_ISL_19335373,
EPI_ISL_19335394, EPI_ISL_19335403, EPI_ISL_19335429-19335430,
EPI_ISL_19335502, EPI_ISL_19335841, EPI_ISL_19337557,
EPI_ISL_19337610, EPI_ISL_19339715, EPI_ISL_19343445,
EPI_ISL_19343849, EPI_ISL_19344142, EPI_ISL_19346021,
EPI_ISL_19346982, EPI_ISL_19347453, EPI_ISL_19347800,
EPI_ISL_19347811, EPI_ISL_19347825, EPI_ISL_19347829,
EPI_ISL_19347845, EPI_ISL_19347848, EPI_ISL_19348774,
EPI_ISL_19348831, EPI_ISL_19348858, EPI_ISL_19349216,
EPI_ISL_19349257, EPI_ISL_19349411, EPI_ISL_19349436,
EPI_ISL_19349447, EPI_ISL_19349453, EPI_ISL_19349567,
EPI_ISL_19350758, EPI_ISL_19353743, EPI_ISL_19354122,
EPI_ISL_19354456, EPI_ISL_19354507, EPI_ISL_19359829,
EPI_ISL_19360071, EPI_ISL_19360132, EPI_ISL_19360301,
EPI_ISL_19360444, EPI_ISL_19362229, EPI_ISL_19362545,
EPI_ISL_19362589, EPI_ISL_19362790, EPI_ISL_19365550,
EPI_ISL_19365623, EPI_ISL_19365635, EPI_ISL_19365672,
EPI_ISL_19365695, EPI_ISL_19365985, EPI_ISL_19365997,
EPI_ISL_19366091, EPI_ISL_19366144, EPI_ISL_19366151,
EPI_ISL_19366177, EPI_ISL_19366223, EPI_ISL_19367932,
EPI_ISL_19368802, EPI_ISL_19379243, EPI_ISL_19379403,
EPI_ISL_19379588, EPI_ISL_19382464, EPI_ISL_19382790,
EPI_ISL_19382797, EPI_ISL_19382804, EPI_ISL_19383697,
EPI_ISL_19383792, EPI_ISL_19385720-19385721, EPI_ISL_19385870,
EPI_ISL_19387459, EPI_ISL_19391161, EPI_ISL_19392559,
EPI_ISL_19392576, EPI_ISL_19392580, EPI_ISL_19392586,
EPI_ISL_19392596, EPI_ISL_19394669, EPI_ISL_19407519,
EPI_ISL_19408610, EPI_ISL_19408636, EPI_ISL_19411733,
EPI_ISL_19411741, EPI_ISL_19411940, PQ041158.1,
PQ108265.1, PQ147929.1, PQ212289.1,
PQ221275.1, PQ242812.1, PQ242883.1,
PQ289413.1

</details>

**Comment by FedeGueli** [comment]
it seems faster than usual KP.2.3

**Comment by Over-There-Is** [comment]
France

**Comment by FedeGueli** [comment]
please propose it is already big @cornelius will decide if worth designating it, it is faster than KP.2.3

**Comment by Over-There-Is** [comment]
Transferred to cov-lineages/pango-designation#2780
