### ISSUE TITLE
KP.3.1.1 subbranch with M:I80L, Orf9b:R47P (20 sequences, 6 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2026]
KP.3.1.1> C1441T> A26760C(M:I80L), G28423C(Orf9b:R47P)
Query: A26760C, G28423C

Earliest sequence: 07-22 New York City, New York, USA EPI_ISL_19310813
Latest sequence: 09-06 Utah, USA EPI_ISL_19416909
Regions detected: US 5, Italy 4, Denmark 3, Canada 2

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5e932_acec00.json?c=country&label=id:node_7033124
![image](https://github.com/user-attachments/assets/9c7c3375-a6e7-4241-86fb-c936a839c952)
Sequences:
EPI_ISL_19310813, EPI_ISL_19340122, EPI_ISL_19378173,
EPI_ISL_19378191, EPI_ISL_19378985, EPI_ISL_19410881,
EPI_ISL_19410913, EPI_ISL_19410917, EPI_ISL_19411048,
EPI_ISL_19412118, EPI_ISL_19416249, EPI_ISL_19416902,
EPI_ISL_19416909, EPI_ISL_19420984

**Comment by FedeGueli** [comment]
M:I80L despite being jsut in 200 seqs was featured in AY.122 sublineage in Sweden that reached 100Seqs and showed an advantage over Delta and Ay.122 in Sweden. it had also S:S221L but i don't think the advantage came from that

**Comment by FedeGueli** [comment]
+1 NJ

**Comment by Over-There-Is** [comment]
It's too hard to handle so much proposals.

**Comment by FedeGueli** [comment]
> It's too hard to handle so many proposals.

it happens all the time don't worry. i will close many in the next days.  better cklosing and reopening if something starts growing than leaving an issue lost among hundreds

**Comment by Over-There-Is** [comment]
Ireland, Sweden

**Comment by FedeGueli** [comment]
@Over-There-Is did u change the query? i had a different one registered

**Comment by Over-There-Is** [comment]
I have removed T23464C from the query to include sequences without it.

**Comment by Over-There-Is** [comment]
And I have a deadline in 2 days, so I have no enough time to transfer this proposal right now.

**Comment by FedeGueli** [comment]
> And I have a deadline in 2 days, so I have no enough time to transfer this proposal right now.

no hurry

**Comment by Over-There-Is** [comment]
It's still 20 sequences now. Should I propose it?

**Comment by FedeGueli** [comment]
> It's still 20 sequences now. Should I propose it?
yes plese

**Comment by DailyCovidCases** [comment]
@Over-There-Is Should I transfer this issue to the man page right now?

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation#2796

**Comment by FedeGueli** [comment]
> [cov-lineages/pango-designation#2796](https://github.com/cov-lineages/pango-designation/issues/2796)

Thx!
