### ISSUE TITLE
LB.1.3.1 subbranch with S:V1176F and Orf1b:R1687C (27 sequences, 8 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2027]
LB.1.3.1> C18526T(Orf1b:R1687C)> G25088T(S:V1176F)
Query: C18131T, C27476T, G25088T

Earliest sequence: 07-18 England, United Kingdom EPI_ISL_19305729
Latest sequence: 08-29 Galway, Ireland EPI_ISL_19410692
Regions detected: Ireland 3, Sweden 2, UK 2, Canada 1, Luxembourg 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_56e6a_437550.json?c=country&label=id:node_7026835
![image](https://github.com/user-attachments/assets/91ef5e8c-4bb9-4fec-83aa-cf0485a1b11f)

Sequences:
EPI_ISL_19305729, EPI_ISL_19340041, EPI_ISL_19372147,
EPI_ISL_19375274, EPI_ISL_19375362, EPI_ISL_19410565,
EPI_ISL_19410684, EPI_ISL_19410686, EPI_ISL_19410692

**Comment by FedeGueli** [comment]
S:V1176F was in all Gamma and recently got designated in KP.2.12 but it was slow.

**Comment by FedeGueli** [comment]
+1 italy

**Comment by Over-There-Is** [comment]
Italy

**Comment by FedeGueli** [comment]
+1 Wales

**Comment by FedeGueli** [comment]
14, US

**Comment by Over-There-Is** [comment]
Denmark

**Comment by FedeGueli** [comment]
4 collected in October from 3 different places

**Comment by xz-keg** [comment]
designated NL.6
