### ISSUE TITLE
XEC subbranch with S:R346I on Orf1a:A599T branch (5 sequences, 3 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2029]
XEC> G2060A(Orf1a:A599T)> G22599T(S:R346I)
Query: G2060A, C18657T, G22599T

Regions detected: France 2, US 2(1 from Spain, 1 airport pooled)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1ea3c_4b7650.json?c=country&f_userOrOld=uploaded%20sample&label=id:node_11653324
![image](https://github.com/user-attachments/assets/6b8b72ab-d7ac-47f3-9393-e16fbe90c36a)

EPI_ISL_19412261, EPI_ISL_19412289, EPI_ISL_19412973,
EPI_ISL_19413008

**Comment by DailyCovidCases** [comment]
Still 5 seqs now, this branch has slowed down a lot

**Comment by xz-keg** [comment]
This one seems dead, mysterious.

**Comment by FedeGueli** [comment]
> This one seems dead, mysterious.

S:R346I is quite deleterious to me maybe even more with the XEC NTD
