### ISSUE TITLE
XBC.1.6 with S:V445A  (39 seqs- South Australia)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#203]
I spotted a little interesting recent cluster of XBC.1.6 carrying additional mutation at S:445 , this time to A.

Defining mutations: XBC.1.6 >>T8707C, C26735T > C10156T > C29762T > S:V445A (T22896C)

Tree:
![Schermata 2023-06-16 alle 11 48 33](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9f1069c9-8102-41a8-b282-e6a175fc2140)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_15f98_c04500.json?label=id:node_6127573

Gisaid query : T8707C,T22896C,C10156T (edited)
Samples 6

EPI_ISL_17703905, EPI_ISL_17793665, EPI_ISL_17793682,
EPI_ISL_17793695, EPI_ISL_17793826, EPI_ISL_17793913,

**Comment by HynnSpylor** [comment]
6 more seqs updated today (also from SA, Australia)

**Comment by FedeGueli** [comment]
It seems slow.

**Comment by FedeGueli** [comment]
no new seq in the last batch from Australia. lets wait a week more.

**Comment by HynnSpylor** [comment]
9 seqs updated and we can track it again.

**Comment by FedeGueli** [comment]
Closing this for now

**Comment by FedeGueli** [comment]
> seems split in two sub-branches now https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f6a8_e609a0.json?c=gt-S_445&label=id:node_6399877 ![image](https://user-images.githubusercontent.com/125747944/261399127-c88af84a-fb0a-4465-aa7a-b76cda2a7043.png)

I bet they are the same.

**Comment by FedeGueli** [comment]
New query finds 39 : T8707C,T22896C,C10156T

**Comment by FedeGueli** [comment]
I am going to propose this one in the main page.

**Comment by FedeGueli** [comment]
JT.1 via https://github.com/cov-lineages/pango-designation/commit/0f50930c6ec5b433af5b343e169213871ef903ca
