### ISSUE TITLE
KP.3.1.1 subbranch with S:R34G, N:S33C, Orf9b:A29I  (35, Scotland)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2030]
_**This was first highlighted on X by [@UseBy2022](https://x.com/UseBy2022) >> https://x.com/siamosolocani/status/1834735537837478299**_

KP.3.1.1> C673T, C21662G(S:R34G), G28361T(=G28370T, N:GERS>G30-33C = N:S33C=N:G30C, Orf9b:MENA>M26-29I = Orf9b:A29I =Orf9b:M26I)
Query: C673T, C21662G
08-11~08-27, Scotland, United Kingdom 16

Tree: (updated after the bug was resolved)
<img width="1165" alt="Screenshot 2024-09-17 alle 11 22 14" src="https://github.com/user-attachments/assets/a9b6c171-f423-4ed2-89a1-a3c9acb49c4c">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_50279_949320.json?label=id:node_11659193
 
Sequences:
EPI_ISL_19372191, EPI_ISL_19412375-19412376, EPI_ISL_19412378,
EPI_ISL_19412380, EPI_ISL_19412409-19412413, EPI_ISL_19412416,
EPI_ISL_19412420-19412421, EPI_ISL_19412426, EPI_ISL_19412446-19412447

Note that Usher Gisaid Covspectrum Nextclade  read N:G30C as N:S33C  so that is how it will be called here.
(same for Orf9b:A26I it is read as Orf9b:A29I and that will be the way we will call it here)

**Comment by FedeGueli** [comment]
Please use the common reading by the tools.
u can add the correspondance as additional information.

This was spotted first by UseBy2022 " Future"  on [Twitter/X](https://x.com/UseBy2022/status/1833815688571425023)

**Comment by FedeGueli** [comment]
Interestingly BF.7 has S:N33F so it could be relevant

**Comment by FedeGueli** [comment]
Misplacement has been already highlighted to @angiehinrichs  .

**Comment by Over-There-Is** [comment]
In my understanding, N:31-33ERS and Orf9b:27-30ENA are already deleted.

**Comment by FedeGueli** [comment]
> In my understanding, N:31-33ERS and Orf9b:27-30ENA are already deleted.

it doesnt matter here what it matters is the comprehension and replicability, with N:G30C you dont get anything in any tool. So it is useless using it while interesting to highlight. 
using the same logic you should rename all the spike due to the 24-26 deletion, would it make any sense? quick answer no.

**Comment by FedeGueli** [comment]
Misplacement solved thx @angiehinrichs !
<img width="1153" alt="Screenshot 2024-09-17 alle 11 21 09" src="https://github.com/user-attachments/assets/b5cdb266-1c5b-4ad0-a013-37c543d4522f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_50279_949320.json?label=id:node_11659193

**Comment by FedeGueli** [comment]
it is massive but in Scotland only

**Comment by FedeGueli** [comment]
Scotland only closing this
