### ISSUE TITLE
KP.3.3 subbranch with S:A>S27L, approx. 73 sequences, 5 countries, Mainly in US)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2035]
KP.3.3> C15540T> C21642T(S:A>S27L)
Query: C7113T, C15540T, -T21633C, del21635_21643

05-31 Honolulu, Hawaii, USA EPI_ISL_19226109
08-28 Illinois, USA EPI_ISL_19394924
US 40, Canada 14, Italy 1, Japan 1, New Zealand 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_581be_5dbc30.json?c=country&f_userOrOld=uploaded%20sample&label=id:node_7082884
![image](https://github.com/user-attachments/assets/f9441de7-61ec-49d7-8ed6-7a127ae02ff4)
EPI_ISL_19199177-19199178, EPI_ISL_19216159, EPI_ISL_19226109,
EPI_ISL_19226593, EPI_ISL_19231016, EPI_ISL_19245150,
EPI_ISL_19245519, EPI_ISL_19250945, EPI_ISL_19269004,
EPI_ISL_19280235, EPI_ISL_19282192, EPI_ISL_19282202,
EPI_ISL_19293789, EPI_ISL_19297875, EPI_ISL_19301708,
EPI_ISL_19301775, EPI_ISL_19303438, EPI_ISL_19303505,
EPI_ISL_19304553, EPI_ISL_19310401, EPI_ISL_19310976,
EPI_ISL_19310982, EPI_ISL_19311436, EPI_ISL_19312991,
EPI_ISL_19313182, EPI_ISL_19313192, EPI_ISL_19313195,
EPI_ISL_19327767, EPI_ISL_19329486, EPI_ISL_19329871,
EPI_ISL_19332152, EPI_ISL_19335385, EPI_ISL_19336871,
EPI_ISL_19337383, EPI_ISL_19341490, EPI_ISL_19347461,
EPI_ISL_19350070, EPI_ISL_19353109, EPI_ISL_19357916,
EPI_ISL_19360589, EPI_ISL_19362092, EPI_ISL_19363189,
EPI_ISL_19363417, EPI_ISL_19367373, EPI_ISL_19371117,
EPI_ISL_19378839, EPI_ISL_19392296, EPI_ISL_19392303,
EPI_ISL_19392395, EPI_ISL_19392450, EPI_ISL_19394456,
EPI_ISL_19394924, EPI_ISL_19408434, EPI_ISL_19413110,
EPI_ISL_19413112, EPI_ISL_19413119

**Comment by FedeGueli** [comment]
The deletion is 24-26 it cannot changes so this is S:A27L if real. 
S:24 is L so the pipelines think it is parsimoniosus to push the deletion one AA ahead but it is not real.
So i will edit consequently @Over-There-Is i ask gently to stop messy things around the deletions. take things as they  are is usual here.

**Comment by Over-There-Is** [comment]
It seems there is another KP.3.3+S:S27L branch appearing in Japan now.

**Comment by DailyCovidCases** [comment]
How many seqs on this branch now?

**Comment by FedeGueli** [comment]
70 only 5 from Spetember

**Comment by FedeGueli** [comment]
No recent sample closing it
