### ISSUE TITLE
Mini saltation XDV.1.8 appeared in Taiwan with 4 spike mutations S:A67G (C>G), S:N148T , S:T240I, S:R683W (2)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2038]
Just two sequences but featuring four spike mutations worth proposing it here.

Defining mutations:
XDV.1.8 >>  T9892G > A23971G, A9715T, Orf1a:A3615V (C11109T), S:A67G (C21762G), S:N148T (A22005C), S:T240I (C22281T), S:R683W (C23609T)
Query: C21762G,A22005C
Samples: 2
Country: 1 (Taiwan)
Tree:
<img width="1160" alt="Screenshot 2024-09-16 alle 10 43 09" src="https://github.com/user-attachments/assets/e527707f-a586-429d-811d-748bb7e49b9f">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_326b9_7ed040.json?c=gt-S_67&label=id:node_7188833

Highlights:
A67G is a C>G nuc mutation rare in the course of the pandemic (less than 100seqs)
S:N148T has been successful especially in GE.1.2.1 and XBB.1.28
S:T240I was in BQ.1.24 and previously in an undesignated branch of AY.122
S:R683W should disrupt the FCS

**Comment by aviczhl2** [comment]
G6183A (rev, real?) , T9142C (rev, real?), C13339T(rev, real?) do not really appear in any XDV.1, they are usher bugs. @AngieHinrichs.

**Comment by Over-There-Is** [comment]
G6183A and C13339T are reverted while recombining, and XDV never got C9142T.

**Comment by FedeGueli** [comment]
> G6183A and C13339T are reverted while recombining, and XDV never got C9142T but Usher places it under a JN.1.1+C9142T branch, so 9142 reverts later.

thx  u and @aviczhl2

**Comment by FedeGueli** [comment]
closing for now
