### ISSUE TITLE
MB.1.1.1 + S:A67V (27 samples, 4 countries : India, Canada-3 states, US-6 states, Ireland)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2039]
There seems to be another MB.1.1.1 branch, other than MV.1, growing. It is defined by S:A67V that has been moderately beneficial on JN.1 backbone.

MB.1.1.1 > S:A67V (C21762T)
Query: C936T,C21762T,G7393T
Samples: 8 first collected in India on 2024-07-04
Countries 4 (India, Us-NV+NY, Canada , Ireland
Tree:
<img width="1176" alt="Screenshot 2024-09-16 alle 15 10 59" src="https://github.com/user-attachments/assets/0a2e6228-fde6-4dfc-b4aa-7d73b5455bc2">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_68f1_82ca70.json?label=id:node_6967415

**Comment by Mydtlwn** [comment]
I noticed a branch with the S:Q183H mutation above. Although it's still small, it may be worth keeping an eye on.

**Comment by FedeGueli** [comment]
> I noticed a branch with the S:Q183H mutation above. Although it's still small, it may be worth keeping an eye on.

yeah under MV.1 propose it if you want.

**Comment by FedeGueli** [comment]
12

**Comment by aviczhl2** [comment]
Now also in VA.

**Comment by FedeGueli** [comment]
24 Ontario New Jersey

**Comment by FedeGueli** [comment]
26 expanding in US

**Comment by xz-keg** [comment]
Designated MV.2

**Comment by Over-There-Is** [comment]
> I noticed a branch with the S:Q183H mutation above. Although it's still small, it may be worth keeping an eye on.

28 now, singapore
