### ISSUE TITLE
Another XBB.1.9.2 branch with s:456L and M:K15N (68 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#204]
Query: A27507C, T22928C, C21998A, G26567T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=A27507C%2CT22928C%2CC21998A%2CG26567T&

Back when i made the proposal that later got designated as eg.5 (xbb.1.9.2 + s:456l), i found three branches of 1.9.2 with 456l, of which only eg.5 got designated because it was the fastest. I think the second branch also got designated later. One branch only had 4 sequences and didn't seem like it would go anywhere, while eg.5 grew much quicker (probably because of mutations like orf1a:a690v). It seems that it has found its growth advantage by now after a mutation M:K15N:

![Screenshot_20230616_133430_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/99c8fea3-d3a7-46da-bb37-d11357d69728)

**Comment by BorisUitham** [comment]
24 sequences now, when I opened this issue 2 weeks ago it was 16

**Comment by FedeGueli** [comment]
Ir doesnt seem fast.

**Comment by BorisUitham** [comment]
These small findings always seem to peak just as I make an issue, maybe I should make this my fulltime job so there will never be a new strain again ;)

**Comment by FedeGueli** [comment]
> These small findings always seem to peak just as I make an issue, maybe I should make this my fulltime job so there will never be a new coronavirus strain again ;)

Very good to find propose and track them. It is  The good of this pre proposal page!

**Comment by BorisUitham** [comment]
So curious, i thought this query was dormant but there was an upload from japan of all places, so far from the other sequences!

**Comment by FedeGueli** [comment]
Even if it doesnt appear too fast it is worth keeping it tracked. LAst recent samples came fro travellers from Netherlands.

**Comment by FedeGueli** [comment]
After a visible slowdown in July this has restarted to circulate, being caught on arrival to US multliple (?) times in the last days . Please propose it on the main page,

**Comment by BorisUitham** [comment]
I'm wondering if i should not just propose the bigger branch without M:K15N instead, seems like the other parts of the tree are now still growing too: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=A27507C%2CT22928C%2CC21998A&

**Comment by FedeGueli** [comment]
ping @BorisUitham propose it.

**Comment by BorisUitham** [comment]
Yes, thanks for the reminder, I will make an issue tomorrow when i'm back from vacation.

**Comment by FedeGueli** [comment]
@borisuitham this went to 68  please propose it! 

ping @corneliusroemer
