### ISSUE TITLE
Kp.3.1.1 + S:H49Y (52 Samples, >10 places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2043]
S:H49Y has popped up multiple times on KP.3.1.1 ,first mentioned in #1653 by @fearuncle, without adding any evident advantage
Now there is a branch with that it is worth tracking for a while:

Kp.3.1.1 > S:H49Y (C21707T)
Query: C21707T, A13121T,- G23804A, -A11971G, -C11036T,-C12855T, -C7086T,-C2306T,-T809C,-C2570T,-G2890A,-T5824C,-A13868G 
Samples: 17
First collected on 2024-06-21  in Scotland
Countries: 8

Tree:
<img width="1159" alt="Screenshot 2024-09-17 alle 14 28 07" src="https://github.com/user-attachments/assets/0e4b6958-cee8-4e2d-a0a4-d466aabd6ad1">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_51035_972eb0.json?label=id:node_7029775

**Comment by FedeGueli** [comment]
25 France

**Comment by FedeGueli** [comment]
33

**Comment by FedeGueli** [comment]
43 no sign of advantage over KP.3.1.1 baseline though

**Comment by FedeGueli** [comment]
Recent samples are from Canada-2 provinces and Scotland

**Comment by FedeGueli** [comment]
52. but checking the query i suspect many more -s to be added

**Comment by FedeGueli** [comment]
> 52. but checking the query i suspect many more -s to be added

41 with the new C21707T, A13121T,- G23804A, -A11971G, -C11036T,-C12855T, -C7086T,-C2306T,-T809C,-C2570T,-G2890A,-T5824C,-A13868G  query but there are 13 new independent emergence of it with  total only 27 sequences belonging to this . closing it 
<img width="1170" alt="Screenshot 2024-11-05 alle 12 53 43" src="https://github.com/user-attachments/assets/c51a92bb-a6cd-49dd-9962-f01e516087fc">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/singleSubtreeAuspice_genome_test_164b4_a06180.json?f_userOrOld=uploaded%20sample&label=id:node_7230939

**Comment by Over-There-Is** [comment]
57 now

**Comment by FedeGueli** [comment]
> C21707T, A13121T,- G23804A, -A11971G, -C11036T,-C12855T, -C7086T,-C2306T,-T809C,-C2570T,-G2890A,-T5824C,-A13868G

it is incomplete one not worth follow this

**Comment by xz-keg** [comment]
> > C21707T, A13121T,- G23804A, -A11971G, -C11036T,-C12855T, -C7086T,-C2306T,-T809C,-C2570T,-G2890A,-T5824C,-A13868G
> 
> it is incomplete one not worth follow this

there are 73 seqs following this query now. This H49Y seems quite fast and convergent.

**Comment by FedeGueli** [comment]
> > > C21707T, A13121T,- G23804A, -A11971G, -C11036T,-C12855T, -C7086T,-C2306T,-T809C,-C2570T,-G2890A,-T5824C,-A13868G
> > 
> > 
> > it is incomplete one not worth follow this
> 
> there are 73 seqs following this query now. This H49Y seems quite fast and convergent. @corneliusroemer it is very hard to get a query for this new convergent site, maybe worth a designation.

The query catches a dozen of unrelated lineages. It is convergent but not fast , at least some weeks ago  i will recheck it

**Comment by xz-keg** [comment]
104 according to the query, around 90 on usher now.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice66_genome_test_29505_d00460.json?label=id:node_5752366

**Comment by FedeGueli** [comment]
I think also the branch is a collector if at least two emrgences from the politomy one in Canada and the other in Wales/Uk

**Comment by FedeGueli** [comment]
C21707T, A13121T,- G23804A, -A11971G, -C11036T,-C12855T, -C7086T,-C2306T,-T809C,-C2570T,-G2890A,-T5824C,-A13868G ,-C1884T,-T8915C,-T3771C,-C10681T,-T9151C, gives 86 and there are 20 more unrelated singlets.

**Comment by Over-There-Is** [comment]
72?
