### ISSUE TITLE
KP.2.3+S:Q675H (36 seqs, 5 countries, 7% in Costarica)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2046]
KP.2.3+del21653_21655(S:S31-)+C28714T+C18555T+G14622A+G23587C(S:Q675H)

GISAID query: G23587C, C18555T, G14622A, C28714T
No.of seqs: 18(Canada 1 Costa Rica 8 Netherlands 1 USA 8(4 from Nicaragua))

First: EPI_ISL_19254607, USA from Nicaragua, 2024-6-24
Latest: EPI_ISL_19408331, Canada, 2024-8-25

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_2624c_a227b0.json?label=id:node_5591614)
![image](https://github.com/user-attachments/assets/b0dff613-abc8-462f-a249-621ebcd3890f)

**Comment by FedeGueli** [comment]
not fasrt but reached 34 with a 7% in Costa Rica recently

**Comment by DailyCovidCases** [comment]
Tree now:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_23c79_a29850.json?f_userOrOld=uploaded%20sample)
![Screenshot (259)](https://github.com/user-attachments/assets/889cbc39-fbd1-4515-b42b-9450f90beb39)

**Comment by FedeGueli** [comment]
> G23587C, C18555T, G14622A, C28714T

not yet

**Comment by xz-keg** [comment]
no new seqs
