### ISSUE TITLE
KP.2.3/KP.3.2.3 recombinant (4 seqs, Canada)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2047]
KP.2.3--KP.3.2.3

breakpoint between 22600 and 22857

Additional mutations: G974A, G2323A, C12710T, C14688T, C19118T,del21653_21655, C28695T
Orf1a: E237K
Orf1b:A1884V
Orf3a:W69C
S:S31-
N:T141I

del21653_21655 and one of G2323A, C12710T,  C19118T from a KP.2.3 branch, 
C28695T from a KP.3.2.3 branch. 
G974A, C14688T and the other 2 of  G2323A, C12710T,  C19118T  are private mutations.

GISAID query: C28695T, C22858T, C22000A
No. of seqs: 3(Canada)

EPI_ISL_19417487,19417488,19417495, 2024-9-9 and 2024-9-10

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_e780_a689c0.json)
![image](https://github.com/user-attachments/assets/683c22e9-2e94-499c-b2d4-ccddeada084b)

**Comment by FedeGueli** [comment]
Orf3a:W69C was in XDM too

**Comment by DailyCovidCases** [comment]
@xz-keg This branch has slowed down a lot, please close this

**Comment by xz-keg** [comment]
no more seqs
