### ISSUE TITLE
KP.2.3/KP.3.3 recombinant (22 seqs, USA, 15 with S:R346T)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#2049]
It seems that a lot of new DeFLiRT+DeFLuQE recombinants are submitted these days.
Among them, this seems a very interesting one, it loses S:R346T during recomb in exchange for S:Q493E, but gains S:R346T independently afterwards.  Like #1784. 

KP.2.3--KP.3.3

Breakpoint between 22001 and 22598

Additional mutations: C4891T, C5310T, C6471A,A18642C,del21653_21655

Orf1a:T1682I, T2069N
S:S31-

 C4891T, C5310T, C6471A,A18642C,del21653_21655 from a KP.2.3 branch

GISAID query: C4891T, C22000A, G28884C
No. of seqs: 11(USA-CA,UT,TX,NY)

First: EPI_ISL_19339481, Texas, 2024-7-10
Latest: EPI_ISL_19416943, Utah, 2024-9-2

GISAID query for S:R346T sub-branch: C4891T, C22000A, G28884C,G22599C

Usher places it on a flip-flop reversion branch. It shouldn't have Orf1a:A690V @AngieHinrichs
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_3da44_a74a00.json?f_userOrOld=uploaded%20sample&label=id:node_5520744)
![image](https://github.com/user-attachments/assets/69c70f2d-21e4-456a-8386-262f646a438c)

_Edited: Orf1a:T1682I corresponds to PLPro_T119I_

**Comment by FedeGueli** [comment]
Big upload today from Utah highlighted by @ryhisner all with 346T total 22

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
XES via https://github.com/cov-lineages/pango-designation/commit/173d1b7c5cd537488f7a05e93f2563755e1e8a2e
