### ISSUE TITLE
LB.1.3 subbranch with N:Q9H, Orf9b:S6T(58, 10 regions)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2050]
LB.1.3> G28300C(N:Q9H, Orf9b:S6T)
Query: C18131T, G22111T, G28300C

Earliest sequence: 04-10 Yokosuka, Kanagawa, Japan EPI_ISL_19150859
Latest sequence: 09-11 Taiwan, China EPI_ISL_19414839
Regions detected: US 17(2 from Mainland China, 1 from Japan), China(Mainland 8, Taiwan 1), Japan 6, Canada 1, Denmark 1, Sweden 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_25efb_ab1920.json?c=country&label=id:node_11661141
![image](https://github.com/user-attachments/assets/26bb1f81-360f-4415-897e-07a3008f19c4)

Sequences:
EPI_ISL_19093673, EPI_ISL_19094019, EPI_ISL_19150859,
EPI_ISL_19175064, EPI_ISL_19223602, EPI_ISL_19260127,
EPI_ISL_19274002, EPI_ISL_19295537, EPI_ISL_19304188,
EPI_ISL_19310612, EPI_ISL_19312500, EPI_ISL_19315143,
EPI_ISL_19315177, EPI_ISL_19345559, EPI_ISL_19345572,
EPI_ISL_19352334, EPI_ISL_19353600, EPI_ISL_19358518,
EPI_ISL_19358556, EPI_ISL_19361404, EPI_ISL_19361408,
EPI_ISL_19362603, EPI_ISL_19365388, EPI_ISL_19369313,
EPI_ISL_19369337, EPI_ISL_19371127, EPI_ISL_19371456,
EPI_ISL_19392757, EPI_ISL_19392772, EPI_ISL_19405785,
EPI_ISL_19414839, EPI_ISL_19420299, EPI_ISL_19420565,
EPI_ISL_19420599, EPI_ISL_19420607

**Comment by Over-There-Is** [comment]
Typo, 35

**Comment by FedeGueli** [comment]
N:P9L was the defining mutation of AY.43, it never popped up again in fast lineages maybe due the S:P13L mutation in all Omicrons.  So very good to track a similar mutation here.
It seems around since a long time probably it is part of the wave of undersampled Chinese lineages .

**Comment by Over-There-Is** [comment]
Österreich

**Comment by Over-There-Is** [comment]
Heilongjiang +5

**Comment by Over-There-Is** [comment]
Kenya and UAE reported by japan

**Comment by FedeGueli** [comment]
+1 Liaoning collected in October

**Comment by Over-There-Is** [comment]
Luxembourg

**Comment by FedeGueli** [comment]
dead
