### ISSUE TITLE
KP.3.1.6 subbranch with S:S31F, N:R68P and Orf9b:E65Q on the branch with MK.3 (16, US 14, CA 2)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2051]
KP.3.1.6> G8039T(Orf1a:D2592Y)> A4079G(Orf1a:S1272G)> C1142T(Orf1a:L293F)> C9169T> G28476C(N:R68P, Orf9b:E65Q)
Query: C9169T, C21654T, G28476C

Earliest sequence: 07-01 Alameda, California, USA EPI_ISL_19304381
Latest sequence: 09-09 California, USA EPI_ISL_19420777
US 14(1 not on GISAID), Canada 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4726e_ab3a20.json?c=country&label=id:node_7027004
![image](https://github.com/user-attachments/assets/5439577e-5c06-4cc0-bdad-a8e573c9cda6)

EPI_ISL_19281920, EPI_ISL_19304381, EPI_ISL_19304655,
EPI_ISL_19337352, EPI_ISL_19337718, EPI_ISL_19347636,
EPI_ISL_19350696, EPI_ISL_19362087, EPI_ISL_19387700,
EPI_ISL_19389489, EPI_ISL_19404786, EPI_ISL_19420775-19420777,
PQ212360.1

**Comment by aviczhl2** [comment]
This branch seems to have MK.3 mutations of C1142T,A4079G,G8039T, shall be a sister branch  of MK.3, or recombinant of MK.1 and MK.3.

**Comment by Over-There-Is** [comment]
you are right.

**Comment by FedeGueli** [comment]
It is in the countries with the highest sequencing intensity and it fails to grow closing this
