### ISSUE TITLE
MC.13 subbranch with S:V47F(59, 12 regions)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2052]
MC.13> G21701T(S:V47F)
Query: C7113T, C10681T, G21701T

Earliest sequence: 06-14 JFK airport, New York, US (from Spain) EPI_ISL_19215367
Latest seuquence: 08-21 Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France EPI_ISL_19418241
Regions detected: US 16(1 from Spain, 1 from Peru), France 5, Portugal 3, Brazil 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_678ff_abfc90.json?c=country&label=id:node_7057897
![image](https://github.com/user-attachments/assets/afd55330-6d60-4858-b905-50e8541c6ccb)

EPI_ISL_19215367, EPI_ISL_19275969, EPI_ISL_19295064,
EPI_ISL_19304761, EPI_ISL_19307156, EPI_ISL_19324581,
EPI_ISL_19327464, EPI_ISL_19327575, EPI_ISL_19327584,
EPI_ISL_19335501, EPI_ISL_19337447, EPI_ISL_19348756,
EPI_ISL_19367938, EPI_ISL_19385846, EPI_ISL_19392192-19392193,
EPI_ISL_19392907, EPI_ISL_19392955, EPI_ISL_19394380,
EPI_ISL_19409608, EPI_ISL_19411726, EPI_ISL_19418241,
EPI_ISL_19418245, EPI_ISL_19418410, EPI_ISL_19419167

**Comment by FedeGueli** [comment]
S:V47F rare mutations, likely slow here.

**Comment by FedeGueli** [comment]
36 from both the two coasts of US

**Comment by FedeGueli** [comment]
Only 4 recent samples

**Comment by Over-There-Is** [comment]
Italy and Puerto Rico

**Comment by Over-There-Is** [comment]
Ireland

**Comment by FedeGueli** [comment]
Only 2 from October

**Comment by Over-There-Is** [comment]
chile

**Comment by FedeGueli** [comment]
lastr samples only from Wales closing it
