### ISSUE TITLE
KP.3.1.1 subbranch with S:S680F and Orf1b:K2063N(CA-ON 32)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2056]
Query: G19656T,C23601T,T27986C
KP.3.1.1> T17226C> G19656T(Orf1b:K2063N), C23601T(S:S680F), T27986C> C186T

08-18~09-06 Ontario, Canada
EPI_ISL_19358250, EPI_ISL_19386411, EPI_ISL_19386668,
EPI_ISL_19389511-19389512, EPI_ISL_19389514-19389515, EPI_ISL_19389520,
EPI_ISL_19389569, EPI_ISL_19389603, EPI_ISL_19389657,
EPI_ISL_19417052-19417053, EPI_ISL_19417055, EPI_ISL_19417058,
EPI_ISL_19417061, EPI_ISL_19417065, EPI_ISL_19417067,
EPI_ISL_19417116, EPI_ISL_19417118, EPI_ISL_19417120-19417122,
EPI_ISL_19417141, EPI_ISL_19417244, EPI_ISL_19417260

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_10b1b_ad0580.json?c=country&f_userOrOld=GISAID%20and/or%20public&label=id:node_7039381
![image](https://github.com/user-attachments/assets/a1f40519-1648-4590-92e2-e69e921654aa)

**Comment by FedeGueli** [comment]
no seqs outside Ontario closing it
