### ISSUE TITLE
MC.10 subbranch with S:T95I and Orf1a:K2120E on potential T25207C reversion branch(CA 31, US 1)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2057]
MC.10> T25207Crev> A6623G(Orf1a:K2120E), C21846T(S:T95I)
Query: A6623G, C8293T, C21846T

08-10~09-10 Ontario, Canada
08-14 Monroe, New York, USA

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_58bd7_ad8470.json?c=country&label=id:node_7051292
![image](https://github.com/user-attachments/assets/4e054c02-8696-4947-8cc2-ef472e1f8ee8)

EPI_ISL_19343783, EPI_ISL_19361668, EPI_ISL_19371248,
EPI_ISL_19386722, EPI_ISL_19386771, EPI_ISL_19389521,
EPI_ISL_19389785, EPI_ISL_19389787-19389788, EPI_ISL_19389795,
EPI_ISL_19417056, EPI_ISL_19417201, EPI_ISL_19417206,
EPI_ISL_19417225-19417227, EPI_ISL_19417238, EPI_ISL_19417270-19417271,
EPI_ISL_19417420, EPI_ISL_19417428, EPI_ISL_19417436,
EPI_ISL_19417439, EPI_ISL_19417454

**Comment by FedeGueli** [comment]
Many samples from Canada but i believe it is just clusters closing it for now,
