### ISSUE TITLE
Another KP.2.3+S:V382L subbranch (US-LA 24)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2058]
KP.2.3> C28714T> C18555T> T17781C> G22706T(S:V382L)
Query: T17781C, C18555T, G22706T

07-15~08-26 Caddo Parish, Louisiana, USA

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_60aa5_adc1f0.json?c=country&label=id:node_7141169
![image](https://github.com/user-attachments/assets/018b9a79-c645-490f-9f38-b3c0c3af88ae)

EPI_ISL_19293605, EPI_ISL_19293624, EPI_ISL_19343172,
EPI_ISL_19343184, EPI_ISL_19343201, EPI_ISL_19343218,
EPI_ISL_19343222, EPI_ISL_19343269, EPI_ISL_19343407,
EPI_ISL_19343416, EPI_ISL_19353771, EPI_ISL_19382643,
EPI_ISL_19414089, EPI_ISL_19414120, EPI_ISL_19414122,
EPI_ISL_19414124, EPI_ISL_19414165, EPI_ISL_19414179,
EPI_ISL_19414232-19414233, EPI_ISL_19414269, EPI_ISL_19414274,
EPI_ISL_19414279, EPI_ISL_19414299

**Comment by FedeGueli** [comment]
no recent samples closing it
