### ISSUE TITLE
MC.6 subbranch with S:R190S, Orf1a:P2055S and Orf1b:P218L(9 sequences, 6 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2061]
_It was spotted and tracked by @aviczhl2 as Branch 20 of #1771_

MC.6> C29503T> C6428T(Orf1a:P2055S), C14120T(Orf1b:P218L), G22132T(S:R190S)
Query: C14120T, G22132T, C29503T

Earliest sequence: 07-24 SEA airport, Washington, USA (from Switzerland) EPI_ISL_19307653
Latest sequence: 08-23 Apulia, Italy EPI_ISL_19412193
Regions detected: Germany 2, Italy 2, US 2(1 from Switzerland, 1 airport pooled), Canada 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3c2b2_ae2400.json?c=country&label=id:node_7052800
![image](https://github.com/user-attachments/assets/b1b0dc30-4d1a-4495-b6a1-8f220a18c21a)

EPI_ISL_19307653, EPI_ISL_19307821, EPI_ISL_19338871,
EPI_ISL_19359036, EPI_ISL_19381029, EPI_ISL_19412192-19412193

**Comment by aviczhl2** [comment]
This is branch 20 of #1771

**Comment by DailyCovidCases** [comment]
Still 9 seqs, likely slowing down now
