### ISSUE TITLE
LF.7 + S:Q677L(10 on Gisaid, 9 countries) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2063]
![image](https://github.com/user-attachments/assets/8f7844dd-a106-4a7f-8a2d-74bcdfa26a6f)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15460_b3e3f0.json?f_userOrOld=uploaded%20sample

First Seq: 2024-07-19
Most Recent: 2024-08-29

Query: A23592T, C6310T, C21627A

EPI_ISL_19386660 EPI_ISL_19375525 EPI_ISL_19411044 EPI_ISL_19416613

**Comment by xz-keg** [comment]
Designated LF.7.1.1

**Comment by FedeGueli** [comment]
via https://github.com/cov-lineages/pango-designation/commit/05ebc2e9d60bc6d4f93b01073de0d7b84cf4a71e#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1303
