### ISSUE TITLE
NJ.1 (S:F59L,R346T,F456L+Orf3a:K16N+S:K478T) with S:N185S (5), and further S:T22N, M153I (3)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2068]
Most seqs on this JN.1.11+S:R346T branch are dropouts from KP.2*. However, there seems to be a real branch hiding inside.

JN.1.11+C7979T, A12463G,T21737C,G22599C, T22928C(S:F59L,R346T,F456L)+G25440T(Orf3a:K16N)+C20436T, C21381T,A22995C(S:K478T rev)

All seqs have C7979T,A12463G have G17334T but not C7113T, this means it shall be a descendant directly from JN.1.11. And these two mutations do not appear in other lineages so small chance of recombinant.

And the S:K478T rev sub-branch is particularly interesting as it harbors recent GBW seqs from both China and India as well as USA local seq.

GISAID query: C7979T, A12463G,C20436T
GISAID query for S:N185S sub-branch:  A12463G,C20436T,A22116G
GISAID query for S:T22N,M153I further sub-branch:  A12463G,C20436T,A22116G,C21627A
No. of seqs: 6(Canada 1 USA 5(1 from China, 2 from India))

First: EPI_ISL_19264665, 2024-7-9,Canada
Latest: EPI_ISL_19427404, 2024-9-9, USA from China

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice50_genome_test_59505_da8450.json?label=id:node_5578232)
![image](https://github.com/user-attachments/assets/32dd5c31-57b5-41ed-91c6-e4e95cd6bbf1)

**Comment by FedeGueli** [comment]
this is a sublineage of branch 61 of #1089 ! then proposed in Pango https://github.com/cov-lineages/pango-designation/issues/2542 , but better to trrack the 478T sublineage here, not worth reopening the old things. thx for spotting it.

**Comment by FedeGueli** [comment]
i was tracking this too with C7979T, A12463G,C21381T but your query catches one more.

**Comment by xz-keg** [comment]
No further seqs

**Comment by xz-keg** [comment]
+2 USA-NJ, with additional S:N185S, T22N and M153I

**Comment by FedeGueli** [comment]
+1 Colorado

**Comment by xz-keg** [comment]
designated NJ.1

**Comment by FedeGueli** [comment]
Worth tracking its sublineages

**Comment by FedeGueli** [comment]
no new seqs closing it
