### ISSUE TITLE
KP.1.1.3+S:E1150D( 21 seqs, 6 countries, 5 with S:T572I)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2070]
KP.1.1.3+T7090C, G25012T(S:E1150D)

GISAID query: G25012T,C4999T,T7090C
No. of seqs: 12(Singapore 1 Australia 3 Canada 1 China 1 USA 6)

First: EPI_ISL_19227217, Singapore, 2024-6-3
Latest: EPI_ISL_19423754, USA-NY, 2024-9-5

GISAID query for S:T572I sub-branch: C23277T, G25012T,C4999T,A17585G
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice213_genome_test_52440_e41d30.json)

![image](https://github.com/user-attachments/assets/186bc671-c0db-44cd-8acc-0788bfa31385)

**Comment by FedeGueli** [comment]
reappered after a hyatus

**Comment by FedeGueli** [comment]
typo corrected it is E1150D ad JN.1.7

**Comment by aviczhl2** [comment]
> typo corrected it is E1150D ad JN.1.7

Yeah and it also gets S:T572I consequently

**Comment by FedeGueli** [comment]
> > typo corrected it is E1150D ad JN.1.7
> 
> Yeah and it also gets S:T572I consequently
Recomb could be excluded?

**Comment by aviczhl2** [comment]
> > > typo corrected it is E1150D ad JN.1.7
> > 
> > 
> > Yeah and it also gets S:T572I consequently
> 
> Recomb could be excluded?

Yeah it can be excluded. It doesn't get S:T572I initially but get it as a sub-branch.

**Comment by FedeGueli** [comment]
20, NY and Queensland Aus

**Comment by xz-keg** [comment]
India uploads 3 new seqs without A3647G and A17585G, adjust proposal accordingly

**Comment by FedeGueli** [comment]
No recent sample closing it
