### ISSUE TITLE
KP.2.2 with ORF1a:K2017R (nsp3_K1199R), ORF1b:P970L (nsp13_P47L), and S:T22N (19 seqs, >10 places  including Lebanon,Jordan,Mexico) with  9 samples carrying 478T

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2072]
**Defining Mutations:** `KP.2.2` > `A6315G(ORF1a:K2017R)` > `C16376T(ORF1b:P970L), C19164T, C21627A(S:T22N)`
**Query:** `A6315G, C21627A`
**Earliest seq:** 24-08-06 (`EPI_ISL_19339128`, _GBW_ sample ex. Lebanon; `EPI_ISL_19344505` from Arizona the same day)
**Latest seq:** 24-09-02 (`EPI_ISL_19419846`, New York)
**Sampled Countries:** USA: 6 (TX/3; AZ; NY; _GBW_ ex. Lebanon), Denmark (1)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Denmark/DCGC-688529/2024
USA/AZ-ASPHL-1514/2024
USA/NY-CDC-LC1119646/2024
USA/NY-GBW-GKISBBBC42930/2024
USA/TX-HMH-M-145338/2024
USA/TX-HMH-M-145398/2024
USA/TX-HMH-M-145444/2024
```

epi_isl accessions:
`EPI_ISL_19339128, EPI_ISL_19344505, EPI_ISL_19405796, EPI_ISL_19419846, EPI_ISL_19425951, EPI_ISL_19426039, EPI_ISL_19426076`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22772_e9ee00.json?label=id:node_7104267
![image](https://github.com/user-attachments/assets/0c8cad8a-0cf5-49ef-9d88-b2c0fe4444cf)

**Trivia:**
- Already with further spike mutations like `T478X` (query : A29257G,C16376T) and `A475V` (Query:A3069C, T7922G  ,C1473T)

**Comment by FedeGueli** [comment]
convergent with https://github.com/cov-lineages/pango-designation/issues/2748

**Comment by FedeGueli** [comment]
I think this was highlighted by @aviczhl2 in the group i misread it as the other bigger lineages.

**Comment by FedeGueli** [comment]
I ve added the queries for the sublineages of interest

**Comment by FedeGueli** [comment]
8, France this last sample has 478T so i would track it with the query A29257G,C16376T

**Comment by FedeGueli** [comment]
+1 again with 478T

**Comment by aviczhl2** [comment]
it further gains an S:K97E sub-branch from the K478T rev branch.

![image](https://github.com/user-attachments/assets/2aed2e49-eed9-46a9-a452-00a6f87dec33)

**Comment by FedeGueli** [comment]
> it further gains an S:K97E sub-branch from the K478T rev branch.
> 
> ![image](https://private-user-images.githubusercontent.com/10445944/371727083-2aed2e49-eed9-46a9-a452-00a6f87dec33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjEwNTcsIm5iZiI6MTcyNzUyMDc1NywicGF0aCI6Ii8xMDQ0NTk0NC8zNzE3MjcwODMtMmFlZDJlNDktZWVkOS00NmE5LWE0NTItMDBhNmY4N2RlYzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZTlmYTY0MTZmZmEyMDZkYTk0ZGUwYmNmYzY3ZjY4Mzc2NmVlN2FlOTYyODVlODI4Yzg2YmNiOTM0NWVjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nQkRBvYWn7Y4GUgOK9EEM1Hfn7WYtmpy-HILVhgSot4)

i cannot find a query for that it seems adding S:K97E Gisaid do not find any in this lineage..not sure whats ongoing with it

**Comment by FedeGueli** [comment]
Oh i get it  the 478T + 97E found by @aviczhl2 belongs to  https://github.com/cov-lineages/pango-designation/issues/2748 
<img width="1175" alt="Screenshot 2024-09-28 alle 13 02 56" src="https://github.com/user-attachments/assets/ee9438f2-05b7-40d1-8dfd-3ee6da9d843a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_d315_7e1180.json?label=id:node_7310672

**Comment by FedeGueli** [comment]
11, new place: Netherlands. 7 of them with 478T

**Comment by FedeGueli** [comment]
New sample from Japan in the 478T rev branch. It has also S:V308L
