### ISSUE TITLE
MC.18(Kp.3.1.1 + S:N185D) with a S:D808E,S:E1195Q sub lineage (28) and further S:A879V (26)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2075]
Apparently this has not been proposed yet , it doesn't seem fast but S:N185D has been in several lineages faster than parents so better to track it

Kp.3.1.1 >> ORF1a:G465S (G1658A) > S:N185D (A22115G)
Query: G1658A,A22115G
Query for S:D808E+S:E1195Q:T18688C, T23986G, G25145C
Query for S:A879V: T18688C, T23986G, C24198T
Samples: 85 / 23 / 21
Places: 8 likely emerged in Catalunya Spain
Tree updated on October 21:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3bde5_6d11c0.json?label=id:node_7242628
<img width="1171" alt="Screenshot 2024-10-22 alle 00 12 26" src="https://github.com/user-attachments/assets/2cac3056-391e-4abe-a9d3-9c2af90f36e4">

**Comment by FedeGueli** [comment]
32, Japan

**Comment by FedeGueli** [comment]
not fast.

**Comment by aviczhl2** [comment]
53 now

**Comment by FedeGueli** [comment]
closing it

**Comment by FedeGueli** [comment]
55, always Canada but different provinces

**Comment by xz-keg** [comment]
62, France

**Comment by FedeGueli** [comment]
This is still a Canadian cluster but it looks like acquiring a lot of additonal mutations:
Orf1a:A181T, Orf1b:L2560F >> ORF3a:A31T, ORF7a:Q76R >> ORF1a:F1741L, S:D808E, S:E1195Q >> S:A879V
 
 <img width="1169" alt="Screenshot 2024-10-22 alle 00 15 56" src="https://github.com/user-attachments/assets/336d9d5d-8a1f-4c98-80c6-42e3067b9cdf">

**Comment by xz-keg** [comment]
designated MC.18

**Comment by xz-keg** [comment]
reopen to track the further Canadian branch.

**Comment by FedeGueli** [comment]
died off

**Comment by FedeGueli** [comment]
GBW sample belonging to [MC.18 from South Africa ](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_49218_ec2d10.json?c=userOrOld)with additional S:R346T mutation EPI_ISL_19650995

**Comment by xz-keg** [comment]
> Orf1a:A181T, Orf1b:L2560F

This is designated MC.18.1

**Comment by FedeGueli** [comment]
parent of the sublineage with D808E designated MC.18.1
