### ISSUE TITLE
KP.3.1.1 + S:D88E (60 Seqs , 7 places including US-15 States))

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2076]
S:D88E has been sampled less than 1K in the course of the pandemic mainly during the VOCs era.
Now it popped up on Kp.3.1.1 backbone, as usual KP.3.1.1 sublineages don't show any advantage over parental baseline.

Still interesting to keep it tracked for a while. S:P85X has been under selective pressure since S:S31del is widespread.

KP.3.1.1 > Orf1a:K141R (A687G) > A24820G (= S:K1086K silent) > S:D88E (T21826A) 
Query: A687G,T21826A
Samples: 17
First collected on 2024-06-23 (UK)
Places : 3 Uk, Us, Can

Tree:
Interestingly the main two branches are defined by two Orf3a mutations:  the upper branch by Orf3a:S60F. (convergent with JN.1.48.3) and the bottom branch by Orf3a:K16N 8 convergent with #2068 

<img width="1174" alt="Screenshot 2024-09-23 alle 02 08 40" src="https://github.com/user-attachments/assets/b7cee0b7-3084-4152-8d72-48f47bfcea9d">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5d138_fc5250.json?c=userOrOld&label=id:node_7028939

**Comment by FedeGueli** [comment]
19 now from 11 American States and the most recent 4 September samples from three states.

**Comment by FedeGueli** [comment]
24 Denmark

**Comment by Over-There-Is** [comment]
31

**Comment by FedeGueli** [comment]
40 seqs notably now there are 13 American states where it is circulating

**Comment by FedeGueli** [comment]
50 Ireland

**Comment by FedeGueli** [comment]
54

**Comment by xz-keg** [comment]
> @xz-keg also this one could deserve a proposal, rare mutation good spread, if our goal is to propose last noticeable KP.3.1.1 that are not just clusters this 638R and 185S could be the ones to move on the main proposal (still digigng in the issues for others)

yeah this could propose to better describing spike diversity of KP.3.1.1

**Comment by FedeGueli** [comment]
> > @xz-keg also this one could deserve a proposal, rare mutation good spread, if our goal is to propose last noticeable KP.3.1.1 that are not just clusters this 638R and 185S could be the ones to move on the main proposal (still digigng in the issues for others)
> 
> yeah this could propose to better describing spike diversity of KP.3.1.1

Thx now proposed in https://github.com/cov-lineages/pango-designation/issues/2831

**Comment by FedeGueli** [comment]
Designated MC.36.2 via https://github.com/cov-lineages/pango-designation/commit/39bc7e567df1c234cb42725caedddd5e2e2a585e
