### ISSUE TITLE
JN.1.67.1+N:T379A,S:K478T rev(36 seqs, 8 places) with a recent branch with S:F59L (2, Hubei, Liaoning)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2079]
JN.1.67.1+G1126A+A29408G,A22995C(N:T379A,S:K478T rev)

GISAID query: A29408G,G26660T
No. of seqs: 16(China 15(Zhejiang Hubei Shanxi) Japan 1)

Query for S.F59L : T21737C,A29408G,G26660T
Samples: 2 ( Liaoning, Hubei)

First: EPI_ISL_19325816, Zhejiang, 2024-7-1
Latest: EPI_ISL_19409480, Hubei, 2024-9-2

[usher edited on October 4]( https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3a34a_41450.json?c=gt-nuc_13304&gmax=14304&gmin=12304&label=id:node_7184986)
<img width="1168" alt="Screenshot 2024-10-04 alle 22 18 51" src="https://github.com/user-attachments/assets/4c14defc-a6ee-4c4e-9f3d-891ee5a77dce">

**Comment by FedeGueli** [comment]
It emerged in Zhejiang that is very undersampled area ( in proportion to pop)

**Comment by FedeGueli** [comment]
+1 Hubei

It seems there is a S:F59L branch in Hubei e Liaoning 
Query : T21737C,A29408G,G26660T 
Samples: 2
<img width="1166" alt="Screenshot 2024-10-04 alle 22 16 38" src="https://github.com/user-attachments/assets/e885490a-b499-4a99-8291-5a3f58d49d19">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3a34a_41450.json?c=gt-nuc_13304&gmax=14304&gmin=12304&label=id:node_7184986

**Comment by xz-keg** [comment]
+1 Sweden

**Comment by FedeGueli** [comment]
Designated MZ.4 via https://github.com/cov-lineages/pango-designation/commit/577670c7bb874ed23dda10d33481723eea58ec19
