### ISSUE TITLE
New KP.3.2 + S:S31del emerged recently (34, 7 places, first sampled in India)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2081]
There is a recent defluqe branch expanding
KP.3.2 >> C18981T > C21590T > S:S31del (del21653-55), C14790T then C23086T (not present in all samples)
Query: C18981T, T3565C,C14790T
Samples: 34
Places: 7
First sample collected on 2024-07-10 in a traveler from India (GBW)

Tree:
<img width="1175" alt="Screenshot 2024-09-23 alle 14 28 23" src="https://github.com/user-attachments/assets/8155348b-7203-4b3a-adaf-96db2b1f184a">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_c560_15cb80.json?branchLabel=nuc%20mutations&label=id:node_7082742

**Comment by aviczhl2** [comment]
Propose this?

**Comment by FedeGueli** [comment]
> Propose this?

Do you mean directly in Pango?

**Comment by aviczhl2** [comment]
> > Propose this?
> 
> Do you mean directly in Pango?

Yeah of course,

**Comment by FedeGueli** [comment]
> > > Propose this?
> > 
> > 
> > Do you mean directly in Pango?
> 
> Yeah of course,

Proposed in https://github.com/cov-lineages/pango-designation/issues/2784

**Comment by FedeGueli** [comment]
Designated KP.3.2.8 via https://github.com/cov-lineages/pango-designation/commit/b1e238c06bee3b81c2215478df708a0db6ca1e05#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1289
