### ISSUE TITLE
 JN.1.7 with S:T22N (35) and then S:F456L (16) got recently S:S31F (7 US)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2083]
JN.1.7 branch with convergent Orf1a:T2283I gained S:T22N and then S:F456L

JN.1.7>> Orf1a:T2283I (C7113T) > T13954C > S:T22N (C21627A) **>>** 
ORF1a:K798N (G2659T), Orf1a:L1110I (C3593A), C17397T, S:F456L (T22928C), ORF7a:T39I  (C27509T) **>>** C2470T, Orf1a:Q1582R (A5010G), Orf1a:T1794I (C5646T=PLPro_T231I ),S:S31F (C21654T), C25710T

Query for 22N: T13954C, C7113T, C21627A
Samples: 17 
Last collected on 2024-09-12 in Ontario, Canada
Query for 22N+456L branch: G2659T,C3593A, C17397T
Samples: 6
Last collected on 2024-08-29 in Texas, US
Samples: 17
Query for 22N+31F+456L branch (thx @Over-There-Is for looking at this): G2659T, C25710T,C21654T
Samples: 3 on Gisaid  (4 on Usher

Tree updated on Nov 24:
 
<img width="1168" alt="Screenshot 2024-11-24 alle 08 07 25" src="https://github.com/user-attachments/assets/ba99eee3-a2a5-4ae9-ae28-d8afd7cc0db8">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_62b01_2ce620.json?label=id:node_7157582

_Originally posted by @FedeGueli in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1675#issuecomment-2369787651_

**Comment by FedeGueli** [comment]
closing this

**Comment by Over-There-Is** [comment]
26/11

**Comment by FedeGueli** [comment]
One recent smaple from California with three on the branch with 456L carrying S:S31F too adding it to the proposal thx @Over-There-Is

**Comment by Over-There-Is** [comment]
Mexican old sequences +4, 30-12-3

**Comment by FedeGueli** [comment]
2 samples from November both in the 31F branch

**Comment by Over-There-Is** [comment]
another T22N: T961C,C11020T,C21627A mainly in Korea

**Comment by FedeGueli** [comment]
> another T22N: T961C,C11020T,C21627A mainly in Korea

the one from Germany is KS.1.1.2 so no recent sample

**Comment by FedeGueli** [comment]
35/16/7 still around in early november interesting but likely slowly dying off now

**Comment by FedeGueli** [comment]
no recent samples closing it for now
