### ISSUE TITLE
KP.3.1.1+Orf1a:K1655N+S:K182E( 61 seqs, >10 places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2085]
KP.3.1.1+G5230T(Orf1a:K1655N)+C853T+A22106G(S:K182E)

GISAID query: G5230T,C853T,A22106G
No. of seqs: 25(USA 1 Japan 2 New Zealand 1 Australia 21(SA, QLD, NSW))

First: EPI_ISL_19305166,2024-7-12, Australia-NSW
Latest: EPI_ISL_19434351, 2024-9-11,Australia-SA

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice18_genome_test_10272_26c740.json?label=id:node_5489352)
![image](https://github.com/user-attachments/assets/b4005af1-cc59-424a-9d99-6b5950468d80)

**Comment by FedeGueli** [comment]
Orf1a:K1655N  = PLPro_K92N was in the maiority of Beta samples

**Comment by FedeGueli** [comment]
+1 NSW

**Comment by FedeGueli** [comment]
31 Australia Vic, first sample from there

**Comment by Over-There-Is** [comment]
34

**Comment by FedeGueli** [comment]
one of the few proposed Kp.3.1.1 faster than KP.3.1.1 baseline

**Comment by xz-keg** [comment]
41, USA-IL,NJ,CO, France

**Comment by xz-keg** [comment]
+14 Australia-TAS and WA

**Comment by FedeGueli** [comment]
61

**Comment by xz-keg** [comment]
designated MC.20
