### ISSUE TITLE
JB.2 (S:R403K,T478R) sublineage circulating in South Africa with  S:H245Y & S:E554D (17 samples)  and a further sublineage with S:T500A (4)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#209]
Tree:
![Schermata 2023-06-17 alle 16 03 33](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e6424a92-781f-421d-8317-f2cd1a718394)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_38b57_dbb2d0.json?label=id:node_10275433

Gisaid query: C22295T, G23224T, G22770A

Samples: 1
EPI_ISL_17801585

Def mutations:
XBB.1.5.53 >> G22770A (S:r403K) C22295T (S:H245Y) A22995G (S:T478R), G23224T (S:E554D)

**Comment by FedeGueli** [comment]
Another sequence of this one popped up from South Africa, although quite old from the start of May (EPI_ISL_17859332)
This last sample gained S:T500A and S:L582F

**Comment by FedeGueli** [comment]
third sample of this came from SA but it is the oldest of them! (from April..) lets wait how is this going really on the ground.

**Comment by FedeGueli** [comment]
Parental with S:K478R designated JB.2

**Comment by silcn** [comment]
Quite a few more in today's South Africa upload @FedeGueli

**Comment by FedeGueli** [comment]
> Quite a few more in today's South Africa upload @FedeGueli

wow 17 now! i mu shering to understand if it makes sense to propose this as sublineage of JB.2 or not.
(Btw interesting to say a shadow convergence with BA.2.86 in 3 out 4 defining mutations, shadow cause we were tracking these ones but likely the same immunity landscape favored the emergence of the other much more heavily mutated lineage.

**Comment by FedeGueli** [comment]
Thanks to @silcn i have reopened this one cause it is recently circulating in South Africa and keeping acquiring spike mutations.
If you have time @corneliusroemer i think the whole tree could give a couple more of sublineage of JB.2:
![Schermata 2023-08-23 alle 02 31 22](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ee9572e7-760a-44ba-a7e1-698a92502474)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_227c1_5513a0.json?label=id:node_7074602

**Comment by FedeGueli** [comment]
Designated JB.2.1 

cc @silcn thank you!
