### ISSUE TITLE
KP.3.1.1+Orf9b:T79I+S:D1260Y (121 seqs, >10 places )

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2094]
KP.3.1.1+C28519T(Orf9b:T79I)+T13120C,G25340T(S:D1260Y)

Besides the spike and orf9b mutation, it is worth noting that the T13120C mutation is just besides the A13121T mutation defining /of KP.3.1.1.

GISAID query: C28519T, T13120C, G25340T
No. of seqs: 38(France 2 USA 9(CA, IA, NY, OH) Canada 27(AB,BC,NB,NS,ON,QC))

First: EPI_ISL_19310503, Canada-QC, 2024-7-21
Latest: EPI_ISL_19442380, USA-IA, 2024-9-19

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice67_genome_test_9cb4_60d1b0.json?label=id:node_5647854)
![image](https://github.com/user-attachments/assets/ac4580c0-a667-4aa1-8419-b0b98509a124)

**Comment by FedeGueli** [comment]
If this exists NY and NB Can clusters we should propose it.

**Comment by DailyCovidCases** [comment]
@FedeGueli Now 64 seqs:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C28519T%2CT13120C%2CG25340T&nextcladePangoLineage=KP.3.1.1*&
Do you want to propose this branch now?

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
>Propose this branch? i m waiting for sustained circulation outside Canada and New York

**Comment by FedeGueli** [comment]
It seems able to get out of clusters. lets look at it closely

**Comment by FedeGueli** [comment]
105 , with 2 Canadian clusters but growing also outside them

**Comment by xz-keg** [comment]
121, Denmark

**Comment by FedeGueli** [comment]
Probably it is worth proposing now, it has spread in multiple Canadian provinces and outside Canada.

**Comment by FedeGueli** [comment]
Thx

**Comment by FedeGueli** [comment]
MC.25

via https://github.com/cov-lineages/pango-designation/commit/16205e716c6a68ff1c3d0f26f0c77478682368ac#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1302
