### ISSUE TITLE
XEC/JN.1 recombinant (15 seqs, 10 places, 3 with S:F58V)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2099]
There seems to be a branch under XEC that has none of the KP.3.3 signature mutations of G28884C and C28291A, it may be formed by either XEC/JN.1 recomb. Interestingly, it has an S:F58V sub-branch next to S:F59S.

XEC--JN.1

Breakpoint between 25007 and 28290

GISAID query:  C18657T, C19716T, C25006T,-28884,-28291
No. of seqs: 4(USA 3(1 GBW-AAA unknown source, 2 GBW from Spain) Germany 1)

EPI_ISL_19364310, Germany, 2024-8-5
EPI_ISL_19445477,19445533, GBW from Spain, 2024-9-18
EPI_ISL_19445567, GBW-AAA, 2024-9-19

GISAID query for S:F58V sub-branch: C18657T, C19716T, C25006T,T21734G (3 seqs)

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_4e218_780310.json?label=id:node_5690724)

![image](https://github.com/user-attachments/assets/9119c27a-929e-49a1-8060-5bf33a210dbc)

**Comment by FedeGueli** [comment]
it is F 58V not L 58V (L>V it would have been C>G)

**Comment by FedeGueli** [comment]
the 58-59 mutated combo was present in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1671 but there was YL58/59 here VS58/59

**Comment by FedeGueli** [comment]
There are four with S:F58V : EPI_ISL_19445477, EPI_ISL_19445512, EPI_ISL_19445533,
EPI_ISL_19445567

**Comment by aviczhl2** [comment]
> C25006T,T21734G

EPI_ISL_19445512 is a GBW pooled seq with Orf1ab from KP not XEC.

**Comment by FedeGueli** [comment]
> > C25006T,T21734G
> 
> EPI_ISL_19445512 is a GBW pooled seq with Orf1ab from KP not XEC.

i think it is the same lineage missread by GBW or a further recombinant

**Comment by aviczhl2** [comment]
> i think it is the same lineage missread by GBW or a further recombinant

GBW-AAA so likely just artefact

**Comment by FedeGueli** [comment]
> > i think it is the same lineage missread by GBW or a further recombinant
> 
> GBW-AAA so likely just artefact

if ana rtifact it is likely thsi lineage

**Comment by DailyCovidCases** [comment]
Closing this, it doesn't seem to be fast now

**Comment by FedeGueli** [comment]
As for undersampled tag also recombinant tag should indicate you not to comment about shutting them down.

**Comment by xz-keg** [comment]
+1 Netherlands

**Comment by xz-keg** [comment]
one more from Netherlands

**Comment by xz-keg** [comment]
+1 UK

**Comment by xz-keg** [comment]
12, USA-CA,OH,UT

**Comment by xz-keg** [comment]
15, Canada and Australia

**Comment by xz-keg** [comment]
it seems that it is becoming a collection of recombinants of XEC and other variants. Close this. If any of those recombinants rise I'll post a separate issue.
![image](https://github.com/user-attachments/assets/27fa4b76-b0ef-47a0-a210-cc4ec7ae2c2a)

**Comment by FedeGueli** [comment]
thjx @xz-keg good to have a query that catches these recombs in advance
