### ISSUE TITLE
MT.1+S:T22N ( 27 seqs, 8 places)  

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2100]
When there is T22N, it gets S31P, when there is S31P, it gets T22N. 

MT.1+C21627A(S:T22N)

GISAID query: T21653C,C29108T,C21627A,C23039G  (alternative query: T27568A,  C21627A edited)
GISAID supplementary query: T21653C,C29108T,-21627,C23039G,C28507T (9 seqs from Liaoning edited)
No. of seqs: 9( China 3(Liaoning) USA 6(GBW from China, Israel and Germany, and an additional AAA seq that don't belong to any of the BBB listed))

First: EPI_ISL_19386098, USA from China, 2024-8-29
Latest: EPI_ISL_19445487, GBW-AAA, 2024-9-19

Usher places this on two branches but I check the C28507T branch and the Chinese seqs don't have coverage at S:22. They shall belong to a general S:T22N branch @AngieHinrichs.

_Notes: (Edited) C28507T corresponds to Orf9b:A75V so one of the two branches of this has it._

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice7_genome_test_4e218_780310.json?label=id:node_5635019)
![image](https://github.com/user-attachments/assets/4a96b9ef-52e2-45e8-b24c-3458fdc66dab)

**Comment by FedeGueli** [comment]
Wow great catch MT.1 had also a batch upload from Thailand with 680F that i m going to propose. this could go.

**Comment by FedeGueli** [comment]
Alternative queries : T27568A,C28507T, T3565C catches 6 overlapping 3 out of 6 found with other query T27568A,C21627A
This will be helpful to estimate its growth advantage that i predict to be high.

**Comment by aviczhl2** [comment]
One more Liaoning from the C28507T branch

**Comment by FedeGueli** [comment]
please propose when it reaches 20

**Comment by DailyCovidCases** [comment]
This branch is slowing down now

**Comment by FedeGueli** [comment]
> T21653C,C29108T,-21627,C23039G,C28507T

too early to say

**Comment by xz-keg** [comment]
Not any seq from the past 3 weeks, close it.

**Comment by FedeGueli** [comment]
#1938

**Comment by FedeGueli** [comment]
16 now new sequences from Liaoning and Australia reopening it

**Comment by FedeGueli** [comment]
Taiwan but infected abroad

**Comment by DailyCovidCases** [comment]
Dead please close it

**Comment by DailyCovidCases** [comment]
Dead please close it

**Comment by FedeGueli** [comment]
20 Jap

**Comment by xz-keg** [comment]
The new seqs are from Thailand and a Japanese traveler seq of Travel history: Europe / Germany, Europe / Netherlands, Europe / Belgium, Europe / Luxembourg,

**Comment by DailyCovidCases** [comment]
> please propose when it reaches 20

  Do you want to propose it? It's slowing down now

**Comment by DailyCovidCases** [comment]
Do you want to propose it? It's slowing down now

**Comment by DailyCovidCases** [comment]
Dead closing it now

**Comment by DailyCovidCases** [comment]
Dead please close this issue

**Comment by FedeGueli** [comment]
+1 WA

**Comment by FedeGueli** [comment]
+1 Liaoning

**Comment by Over-There-Is** [comment]
F186S

**Comment by Over-There-Is** [comment]
24, Thailand +2

**Comment by xz-keg** [comment]
> 24, Thailand +2

Seems on different branch but separated by only 1 seq. Unsure.

**Comment by FedeGueli** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
>Seems on different branch  

Yeah lets keep all together until more will accumulate

<img width="1159" alt="Screenshot 2024-12-03 alle 10 35 26" src="https://github.com/user-attachments/assets/ae543cc6-f375-4e27-ac95-29e23343bd27">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_96d5_ece9f0.json?c=userOrOld&label=id:node_11770510

**Comment by FedeGueli** [comment]
+1 NSW this is the fourth Australian state where it shows up

**Comment by xz-keg** [comment]
+1 South Korea

**Comment by FedeGueli** [comment]
it is likely the most interesting of the iunderdog lineages. please propose it

**Comment by DailyCovidCases** [comment]
@FedeGueli Reaches 20 seqs, please propose it

**Comment by DailyCovidCases** [comment]
@FedeGueli Reaches 25 seqs, please propose it

**Comment by xz-keg** [comment]
designated MT.1.1
