### ISSUE TITLE
Defluqe/FULLQUAD Recombinant KP.1.1.3/MC.1 (12 sequences, US-5 States, Australia-GBW, Canada-BC,AB,On) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2103]
Recombinant between KP.1.1.3 branch with C4423T, C7083T (orf1a:S2273F)
and a MC.1 branch with S:R346T and T28978A with a breakpoint after 19723: all before it Kp.1.1.3 all after it KP.3.1.1)
[Now placed as sibling of XEH]
Private mutations:A17864G,G21055A
Query: C4423T,  A17864G,G21055A
Samples: 3 ( 2 patients)
Places: US (tX) Australia (GBW)
Tree updated on November 19: 
 <img width="1172" alt="Screenshot 2024-11-19 alle 11 01 19" src="https://github.com/user-attachments/assets/54a2091d-ea70-4682-b0f1-83f507b97113">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_1e19a_c60f00.json?label=id:node_7231360

_Originally posted by @FedeGueli in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1838#issuecomment-2380619510_

Zoom on Parents:
<img width="1021" alt="Screenshot 2024-09-28 alle 16 24 54" src="https://github.com/user-attachments/assets/69150f97-88c9-4d91-a425-f7784ac98c8f">
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&aaMutations=S%3AR346T&nucMutations=T28978A&nextcladePangoLineage=MC.1*&nucMutations1=A17864G%2CC4423T%2CC7083T&nucMutations2=C4423T%2CC7083T&nextcladePangoLineage2=KP.1.1.3*&analysisMode=CompareEquals&

**Comment by FedeGueli** [comment]
+1 NY

**Comment by xz-keg** [comment]
+1 PA

**Comment by FedeGueli** [comment]
7 with three samples from October from three different places.

cc @xz-keg this one could be interesting

**Comment by FedeGueli** [comment]
+1 Alberta

**Comment by FedeGueli** [comment]
10 Ontario,Minnesota both new places both recent

**Comment by FedeGueli** [comment]
cc @xz-keg @corneliusroemer likely worth designating it

**Comment by FedeGueli** [comment]
+2 BC,ON

**Comment by xz-keg** [comment]
no new seqs
