### ISSUE TITLE
XEC.2 + N:T379I (51 on Gisaid in 6 countries) 19 with S:G181V

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2104]
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36f5c_8c1550.json?f_userOrOld=uploaded%20sample
![image](https://github.com/user-attachments/assets/fb8e233f-39cf-40d5-8903-629ce086119d)

First seq: 2024-08-29
Most Recent: 2024-09-18

Gisaid: T7168C, T16476C

EPI_ISL_19445496 EPI_ISL_19445578 EPI_ISL_19445521 EPI_ISL_19427523 PQ387829.1 EPI_ISL_19426862 EPI_ISL_19441170

**Comment by FedeGueli** [comment]
40

**Comment by Fearuncle** [comment]
Adding S:G181V to the proposal

**Comment by xz-keg** [comment]
I think this one is worth proposal too.

**Comment by FedeGueli** [comment]
> I think this one is worth proposal too.

Thx please @Fearuncle propose it

**Comment by FedeGueli** [comment]
XEC.2.3 and XEC.2.3.1 (181V) via https://github.com/cov-lineages/pango-designation/commit/9b486e72cec35cc59633dd4035663f61479051ed#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R4383
