### ISSUE TITLE
 XEM : KP.3.3.1 Recombinant Islands: XEM = Branch 1 with S:F59S, S:R346T additions (8 seqs, Canada); B2 with S:S31-, S:Q183H (Japan, Thailand)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2105]
<a name="task_header"></a>

```[tasklist]
### `KP.3.3.1` Recombinant Islands
- [x] [Branch 1](#branch_1) : `KP.3.3.1` and `KS.1` recombinant gaining `S:F59S` and `S:R346T` [query: `C6568T, T21738C, C23039G`, 41 seqs, Canada, as of Oct 22]
- [ ] [Branch 2](#branch_2) : `KP.3.3.1` and `LB.1.9` recombinant gaining `S:S31Δ` and `S:Q183H` [query: `C17430T, G22111T, C23039G`, 2 seqs, Japan, Thailand, as of Sep27]
```

<a name="branch_1"></a>
### Branch 1

**Placement on phylogenetic tree:** `KP.3.3.1` > _`T7113C_rev`, _`T15543G_rev`_, `T17334G_rev`_ > `C6568T, T21738C (S:F59S), G22599C (S:R346T)`
**Query:** `C6568T, T21738C, C23039G`
**Earliest seq:** 24-07-09 (`EPI_ISL_19264602`, Ontario, Canada)
**Latest seq:** 24-09-12 (`EPI_ISL_19432109`, Ontario, Canada)
**Sampled Countries:** Canada (5: ON/3; NL; SK)

**Recombinant Profile:**
 ![image](https://github.com/user-attachments/assets/4c6a5e0a-71b0-4929-9447-536c74993441)
- Effectifely this is `KP.3.3.1` losing `JN.1.11`'s `G17334T`; `JN.1.11.1`'s `C7113T` and `KP.3.3.1`'s `G15543T`; while gaining `C6568T, T21738C (S:F59S), G22599C (S:R346T)`
- The other potential donor could be `JN.1.13.1*` (`JN.1`+`S:A1087S`+`S:F59S`+`S:R346T`, while `S:A1087S` and other synonymous mutations are after breakpoint so they wouldn't count) or `JN.1.18.6*` (`JN.1`+`S:R346T`+`S:F59S`+`S:F456L` without any synonymous mutations at all)
- Breakpoint would be between `nuc_22600 (spike_346)` and `nuc_23038 (spike_492)`
- The other potential donor contributes 5' to bp, then `KP.3.3.1` contributes bp to 3' end.
- Private mutation(s): `C6568T`

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/NL-NML-724799/2024
Canada/ON-PHL-202409969/2024
Canada/ON-PHL-202412404/2024
Canada/ON-PHL-202414071/2024
Canada/SK-RRPL-732461/2024
```

epi_isl accessions:
`EPI_ISL_19264602, EPI_ISL_19334658, EPI_ISL_19386507, EPI_ISL_19432109, EPI_ISL_19446089`

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2

**Placement on phylogenetic tree:** `KP.3.3.1` > _`T7113C_rev`, _`T15543G_rev`_, `T17334G_rev`_ > `C15960T, C17430T, G22111T(S:Q183H)`
**Query:** `C17430T, G22111T, C23039G`
**Earliest seq:** 24-08-16 (`EPI_ISL_19444211`, Bangkok, Thailand)
**Latest seq:** 24-08-26 (`EPI_ISL_19416452`, Miyagi, Japan)
**Sampled Countries:** Japan (1), Thailand (1)

**Recombinant Profile:**
- Effectifely this is `KP.3.3.1` losing `JN.1.11`'s `G17334T`; `JN.1.11.1`'s `C7113T` and `KP.3.3.1`'s `G15543T`; while gaining `C15960T, C17430T, del21653_21655 (S:S31Δ), G22111T (S:Q183H)`
- The other potential donor would be `LB.1*` (`JN.1`+`S:Q183H`+`S:R346T`+`S:S31Δ`+`S:F456L`, while `S:R346T` is after breakpoint so they wouldn't count), more specifically, a parallel branch to `LB.1.9`, which follows: `LB.1` > `C15960T` > `C17430T`
- Breakpoint would be between `nuc_22112 (spike_184)` and `nuc_22598 (spike_346)`
- The other potential donor contributes 5' to bp, then `KP.3.3.1` contributes bp to 3' end.

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Japan/FR049-0829/2024
Thailand/NIC_BKK_P3159/2004
```

epi_isl accessions:
`EPI_ISL_19416452, EPI_ISL_19444211`

</details>

[Back to Tasklist](#task_header)

---

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice35_genome_ed5e_8d4550.json?label=id:node_7246176
![image](https://github.com/user-attachments/assets/7c835ee8-b95a-41e3-b1e1-2faa1aa9d298)

**Comment by aviczhl2** [comment]
EPI_ISL_19287096 shall be the donor of branch 1, it is KS.1 with C6568T and no other mutations before S:346. It is collected in Canada.

**Comment by FedeGueli** [comment]
+2 for Br.1 from CAN

**Comment by xz-keg** [comment]
B2 was dead long ago, better close it.

**Comment by FedeGueli** [comment]
Xem is leading by far Collection 42 due to Ontario Clusters, interestingly  it seemed to have gained S:T22N whilke looking at this branch it turned out to be a sub branch of XEC. it could be still possible iw would be a micro recombination event but unlikely
so i suggest to modify the XEM query to -C13405T ,C6568T, T21738C, C23039G cc @alurqu for Coll42
<img width="1166" alt="Screenshot 2024-10-29 alle 13 38 26" src="https://github.com/user-attachments/assets/9b6627c9-7a58-446c-8f07-e084b9015ce6">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_19c72_d46f0.json?c=gt-S_346&label=id:node_7270070
