### ISSUE TITLE
MB.1.1.1+Orf1a:P4211S,S:M177I(5 seqs, 4 places, GBW from 3 different countries on 3 different continents)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2106]
MB.1.1.1+T16794C+C12896T, G22093T, C22591T, G29398A(Orf1a:P4211S,S:M177I)

GISAID query: G22093T, T16794C,C936T
No. of seqs: 2(USA from Nicaragua and Austria)

EPI_ISL_19445554, GBW from Nicaragua, 2024-9-16
EPI_ISL_19445463, GBW from Austria, 2024-9-18

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice115_genome_test_990f_a0aed0.json?label=id:node_5414360)
![image](https://github.com/user-attachments/assets/5d235024-a7ec-4d53-a24e-a96cca93580f)

**Comment by aviczhl2** [comment]
+1 GBW from gypt

**Comment by DailyCovidCases** [comment]
No new seqs closing it

**Comment by xz-keg** [comment]
+2 USA-CA

**Comment by xz-keg** [comment]
no new seqs
