### ISSUE TITLE
KP.3.1.1+S:D111N (47 seqs, >10 places, global)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2108]
KP.3.1.1+G21893A(S:D111N)

There seems to be a S:D111N branch under KP.3.1.1, however, this mutation is very convergent the tree seems messy.

GISAID query: G21893A, C12616T,A13121T, -24095, -1354,-29716,-13297,-16332,-25595,-9699,-6066,-4851,-11094,-6391,-27692,-27128,-21855,-25998,-6536,-6286 (may include more -s)

No. of seqs: 36(Australia 2 Brazil 1 Canada 2(BC,ON), Denmark 2 UK 3(England, Scotland, Wales) France 1 Germany 2 Ireland 2 Israel 1 Italy 2 Netherlands 1 South Korea 1 Spain 1 USA 16(AR,CA,LA,MD,MI,NY,PA, GBW from Greenland))

I don't exclude the following branches:
G1820A,C29095T,A29700G-- they are very convergent
C21654T--artifact
G9425T--separated only by 2 Spanish seqs with many additional mutations that certainly not from the same source

First: EPI_ISL_19235732, USA-NY, 2024-7-26
Latest: EPI_ISL_19440628, Ireland, 2024-9-24

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1694e_a299d0.json?label=id:node_5661354)
![image](https://github.com/user-attachments/assets/e493a6a7-70a4-4927-868f-ab373b6a27e2)

**Comment by FedeGueli** [comment]
Yeah i think this was kept separated until a few days ago i checked D111N wiothout finding big branches like this last week.

**Comment by aviczhl2** [comment]
> Yeah i think this was kept separated until a few days ago i checked D111N wiothout finding big branches like this last week.

They are distributed on usher, I think the following shall all belong to this branch.

G1820A,C29095T,A29700G-- they are very convergent
C21654T--artifact
G9425T--separated only by 2 Spanish seqs with many additional mutations that certainly not from the same source

**Comment by FedeGueli** [comment]
Yeah likely. Anyway it is slow but important to see if it gains S:K113T that was not so uncommon in the past creating a new N Glycan

**Comment by aviczhl2** [comment]
> G21893A, C12616T,A13121

Not slow.  S:D111N has 22% advantage against baseline KP.3.1.1.

USA:
![image](https://github.com/user-attachments/assets/5af5ff31-7b31-4d3c-bb57-2c6bc9341df9)
World:
![image](https://github.com/user-attachments/assets/0e4ac166-656d-4873-a179-9dab2fdff0df)

**Comment by aviczhl2** [comment]
> Yeah likely. Anyway it is slow but important to see if it gains S:K113T that was not so uncommon in the past creating a new N Glycan

It seems only second to S:A435S which has 40% advantage.

**Comment by FedeGueli** [comment]
Thx interesting last week was shown a lot slower , still unsure about it we will see in the next few weeks then if it is solid or not. Also different moment to choice the baseline KP.3 or KP.3.1.1 or XEC maybe the best is JN.1 that is all without recombinants. i can't see how to choice. Kp.3.1.1 baseline is heavily influenced by North America/Europe

**Comment by aviczhl2** [comment]
> Thx interesting last week was shown a lot slower , still unsure about it we will see in the next few weeks then if it is solid or not. Also difficult moment to choice the baseline KP.3 or KP.3.1.1 or XEC maybe the best is JN.1 that is all without recombinants. i can't see how to choice. Kp.3.1.1 baseline is heavily influenced by North America/Europe

if you look at the seqs most are from Sep. This mutation is not among the initial mutations KP.3.1.1 get, the first only appears in late July.

**Comment by FedeGueli** [comment]
> > Thx interesting last week was shown a lot slower , still unsure about it we will see in the next few weeks then if it is solid or not. Also difficult moment to choice the baseline KP.3 or KP.3.1.1 or XEC maybe the best is JN.1 that is all without recombinants. i can't see how to choice. Kp.3.1.1 baseline is heavily influenced by North America/Europe
> 
> if you look at the seqs most are from Sep. This mutation is not among the initial mutations KP.3.1.1 get, the first only appears in late July.

Yeah but if you look at apparent fast growing KP.3.1.1 designated lineages MC.9 MC.10 are all super boosted by multiple canadaian clusters. D111N is in 1/3 of its september sequences from Canada and the other 1/3 from US  its advantage could be real but i bet it will go down soon. Anyway the way the world is break in two currently it is quite a thing and we dont know what is happening in Africa, a lot of Asia and only a weak picture from South America (where KP.3.1.1 seems taking dominance) I think nominal advantages right now don't tell the history though and it is an unluck situation just before the winter in the northern emisphere

**Comment by FedeGueli** [comment]
+1 Ireland

**Comment by FedeGueli** [comment]
@aviczhl2 u were right clearly growing D111N now

**Comment by DailyCovidCases** [comment]
@aviczhl2 Propose this?

**Comment by FedeGueli** [comment]
@DailyCovidCases 

under review better keeping it here for open discussion it could be an emerging convergent mutation.

**Comment by FedeGueli** [comment]
48 NY

**Comment by FedeGueli** [comment]
> 48 NY (checking the query)

-s to be included : -C11094T (it belongs to a C29095T branch) ,  -A29716T ( branch on its own), -A6391G

the query resulting should be : G21893A, C12616T,A13121T, -24095, -1354,-29716,-13297,-16332,-25595,-9699,-6066,-4851,-C11094T  ,  
-A29716T  , -A6391G 

and it finds 43

**Comment by FedeGueli** [comment]
+2 Scotland please propose it

**Comment by xz-keg** [comment]
Add a lot of new -s, toll shall be 47 for main branch

**Comment by FedeGueli** [comment]
> G21893A, C12616T,A13121T, -24095, -1354,-29716,-13297,-16332,-25595,-9699,-6066,-4851,-11094,-6391,-27692,-27128,-21855,-25998,-6536,-6286

thx!

**Comment by FedeGueli** [comment]
MC.27 via https://github.com/cov-lineages/pango-designation/commit/16205e716c6a68ff1c3d0f26f0c77478682368ac#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1303
