### ISSUE TITLE
MC.16+S:E1144A(3 seqs, GBW from 2 different countries)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2109]
MC.16+C17649A+C4331T, C4582T, A24993C(S:E1144A)

GISAID query: G2890A, C12616T,A24993C
No. of seqs: 3(USA, GBW from Austria and Italy)

EPI_ISL_19436755,19445561, 2024-9-16, GBW from Italy
EPI_ISL_19445566, 2024-9-18, GBW from Austria

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_472e9_a367b0.json?label=id:node_5670905)
![image](https://github.com/user-attachments/assets/72d49a81-5a3f-4b23-8071-257b0553f330)

**Comment by FedeGueli** [comment]
I have seen this too, the one on the top could be a recomb with any MB.1.1

**Comment by aviczhl2** [comment]
> I have seen this too, the one on the top could be a recomb with any MB.1.1

Or convergent evolution, no evidence of recomb though.

**Comment by FedeGueli** [comment]
> > I have seen this too, the one on the top could be a recomb with any MB.1.1
> 
> Or convergent evolution, no evidence of recomb though.

Hard to have any becasue they are identical after orf3a/E/M  i think

**Comment by DailyCovidCases** [comment]
Closing this, it doesn't seem to be fast now

**Comment by FedeGueli** [comment]
Austria unluckily has stopped its superlative sequencing program, better wait a bit

**Comment by xz-keg** [comment]
no new seqs

**Comment by Over-There-Is** [comment]
*C17649T
