### ISSUE TITLE
KP.3.1.1 with S:N148S (6 seqs, Canada, USA), 3 with further S:T572I

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2112]
**Defining Mutations:** `KP.3.1.1` > `C4891T, A5608G` > `A22005G (S:N148S)`
**Query:** `C4891T, A5608G, A22005G`
**Earliest seq:** 24-08-09 (`EPI_ISL_19345625`, Ontario, Canada)
**Latest seq:** 24-09-14 (`EPI_ISL_19432363`, Ontario, Canada)
**Sampled Countries:** Canada (4: ON/3; QC/1), USA (1: PA)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/ON-KHS-03767-v1/2024
Canada/ON-KHS-03832-v1/2024
Canada/ON-PHL-202414343/2024
Canada/QC-L00781444001/2024
USA/PA-CDC-LC1116229/2024
```

epi_isl accessions:
`EPI_ISL_19345625, EPI_ISL_19345655, EPI_ISL_19379549, EPI_ISL_19408393, EPI_ISL_19432363`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31c6e_a5fed0.json?label=id:node_7208774
![image](https://github.com/user-attachments/assets/6b9a9ae4-7552-4234-a3c9-cdeac367fa4f)

**Comment by FedeGueli** [comment]
673 closing this for now
