### ISSUE TITLE
MC.13 with ORF1a:S1857A (nsp3_S1039A / PLPro_S294A) and S:K150R (23 seqs , 2+1 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2113]
**Defining Mutations:** `MC.13` > `T5834G (ORF1a:S1857A)` > `C13426T` > `A22011G (S:K150R)`
**Query:** `T5834G, A22011G`
**Earliest seq:** 24-07-04 (`OZ180910.1`,Scotland, UK, _not on GISAID yet_)
**Latest seq:** 24-09-09 (`PQ387704.1`, Arizona, USA, _not on GISAID yet_)
**Sampled Countries:** Canada (8: ON/5; BC; NS; QC), USA (4: AZ; CA; CO; DE), UK (2: SC, _not on GISAID yet_)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/BC-BCCDC-732632/2024
Canada/NS-NSH-728571/2024
Canada/ON-PHL-202412670/2024
Canada/ON-PHL-202413403/2024
Canada/ON-PHL-202413405/2024
Canada/ON-PHL-202413406/2024
Canada/ON-PHL-202413584/2024
Canada/QC-L00776238001/2024
USA/CA-CDPH-500141578/2024
USA/CO-CDPHE-42243011/2024
USA/DE-CDC-LC1113537/2024
Scotland/CLIMB-CM7Y813Y/2024
Scotland/CLIMB-CM7Y819W/2024
USA/AZ-CDC-QDX23564357/2024
```

epi_isl accessions:
`EPI_ISL_19350155, EPI_ISL_19364491, EPI_ISL_19386754,
EPI_ISL_19416728, EPI_ISL_19417174, EPI_ISL_19417176-19417177,
EPI_ISL_19417306, EPI_ISL_19438080, EPI_ISL_19438785,
EPI_ISL_19439471
`
genbank accessions:
`OZ171958.1, OZ180910.1, PQ387704.1`

</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_257d5_a68c10.json?label=id:node_7224477
![image](https://github.com/user-attachments/assets/c4d54dd1-1612-4597-8cea-62214f378a1c)

**Comment by FedeGueli** [comment]
16

**Comment by FedeGueli** [comment]
20

**Comment by FedeGueli** [comment]
23 likely dying off only three samples in october all from Canada
