### ISSUE TITLE
XDV.1 + S:K478T reversion (83)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2114]
S:478X is very homoplasing in XDV.1, now the USher tree collects several branches with S:T478T  in one unique tree :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a4cc_bc8b40.json?c=gt-S_478&gmax=25384&gmin=21563&label=id:node_7042565
<img width="1173" alt="Screenshot 2024-10-01 alle 12 47 32" src="https://github.com/user-attachments/assets/2feb1a29-73d0-44fb-a1b9-1bd0e2acb6b4">
Far from me believing this is a real monophyletic lineage but this could be useful as JN.1.16 or Jn.1.18 as collector of eventual new branches with S:T478T stemming out from the politomy,
Especially the sublineage with S:H207Q is misplaced here and likely belongs to a XDV.1 + S:H207Q that circulated until July.
Then acquired S:T478T and consequently it is now assigned to this. So i will treat it as a sublineage this especially because the original branch died off.

Defining mutations: XDV.1 > S:K478T (S:A22995C)
Query:C1170T,C6501A,T22926C,T28297C,T22930A,-C22995T,-22996,-A22994C,-A22994G, -C22995A, -C8950T,-C8299T,-T4579A,-C6855T,-C8140T,-T12847C,-C28432T,-G5612A,-C28674T,-T9892G,-G29717A,-A21526G,-C20759T,-C6861T,-G3728T,-C17547T,-G3728T,-A4584G,-T1237G,-G3068T,-A2006G,-A15641G
Samples: 59
Places: Hubei mostly, Shanxi, California
 
Query for the S:H207Q sublineage: A14116G, C16308T,
Samples: 4 all from Hubei

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this?
Note: 59 seqs not 599 seqs

**Comment by FedeGueli** [comment]
> @FedeGueli Propose this? Note: 59 seqs not 599 seqs

thx, not yet lets see next batches from China

**Comment by FedeGueli** [comment]
+6 Heilongjang

**Comment by FedeGueli** [comment]
69 with more -s in the new query : C1170T,C6501A,T22926C,T28297C,T22930A,-C22995T,-22996,-A22994C,-A22994G, -C22995A, -C8950T,-C8299T,-T4579A,-C6855T,-C8140T,-T12847C,-C28432T,-G5612A,-C28674T,-T9892G,-G29717A,-A21526G,-C20759T,-C6861T,-G3728T,-C17547T,-G3728T,-A4584G,-T1237G,-G3068T,-A2006G,-A15641G

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
Waiting for spread outside China

**Comment by DailyCovidCases** [comment]
This branch can be proposed on the main page

**Comment by FedeGueli** [comment]
+2 Sichuan, counting HK it is present in 8 different Chinese provinces cc @xz-keg

**Comment by xz-keg** [comment]
> +2 Sichuan, counting HK it is present in 8 different Chinese provinces cc @xz-keg

yeah maybe worth proposal.

**Comment by FedeGueli** [comment]
> > +2 Sichuan, counting HK it is present in 8 different Chinese provinces cc @xz-keg
> 
> yeah maybe worth proposal.

Lets see how it goes in November then, maybe already crushed by NB.1

**Comment by FedeGueli** [comment]
83 none from november closing it
