### ISSUE TITLE
Weird Shaped Tree (likely clusters):  98 seqs of XBB.1.16* with mutation G1274T/ ORF1a:V337F and C25626T in Canada

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#212]
sublineage of XBB.1.16 (not certain which)
Inquiry: T12730A,G1274T,C25626T (EDITED)
Extra mutations: G1274T and then C25626T
Earliest Sequence: EPI_ISL_17605615 2023-04-17 Alberta, Canada
Latest Sequence: EPI_ISL_17809790 2023-06-04 Quebec, Canada
Sequences: EPI_ISL_17605614-17605615, EPI_ISL_17605619, EPI_ISL_17605639,
EPI_ISL_17605669, EPI_ISL_17645082, EPI_ISL_17659950,
EPI_ISL_17660234, EPI_ISL_17660266, EPI_ISL_17682259-17682261,
EPI_ISL_17682291-17682292, EPI_ISL_17682296, EPI_ISL_17682299,
EPI_ISL_17682303, EPI_ISL_17682307, EPI_ISL_17682326,
EPI_ISL_17682358, EPI_ISL_17686751, EPI_ISL_17711679,
EPI_ISL_17711685, EPI_ISL_17711688, EPI_ISL_17711693,
EPI_ISL_17761125, EPI_ISL_17761135, EPI_ISL_17761148,
EPI_ISL_17761153, EPI_ISL_17761159, EPI_ISL_17761165,
EPI_ISL_17761179, EPI_ISL_17761185, EPI_ISL_17761276,
EPI_ISL_17761294-17761295, EPI_ISL_17761298, EPI_ISL_17761303,
EPI_ISL_17761317, EPI_ISL_17761325-17761327, EPI_ISL_17761333,
EPI_ISL_17761335, EPI_ISL_17761338-17761339, EPI_ISL_17783194,
EPI_ISL_17783204, EPI_ISL_17783214-17783216, EPI_ISL_17783242-17783243,
EPI_ISL_17783245, EPI_ISL_17783265, EPI_ISL_17783269,
EPI_ISL_17783272-17783273, EPI_ISL_17783278, EPI_ISL_17783285,
EPI_ISL_17783288, EPI_ISL_17783290, EPI_ISL_17798861,
EPI_ISL_17799077, EPI_ISL_17799081-17799082, EPI_ISL_17799087,
EPI_ISL_17799112, EPI_ISL_17799121, EPI_ISL_17799127,
EPI_ISL_17799131, EPI_ISL_17799143, EPI_ISL_17809790,
EPI_ISL_17809897

Inquiry: (I display the search with a larger tree with criterion simply G1274T to let you have sense about this lineage's development and stuff)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_57c3_fbaca0.json?f_userOrOld=uploaded%20sample
I discovered this when checking the X+XBB.1.16* mutation that shows growth upon the baseline and discovered G1274T, yet when I analyze the tree it is very weird because it appears in very big clusters that seemingly carry the same genome. With not abundant metadata I could not decide whether this is duplicate or simply multiple patient with the same variant.

**Comment by krosa1910** [comment]
Some more samples from Canada appears, now it has 87 seqs, but except for one in US being relatively early, all else appeared in Canada. I believe its number is inflated, but I think it is some actual mutation.

**Comment by krosa1910** [comment]
Have looked at the geographical distribution again.
It seemed that Alberta is simply a huge hotspot of this. it submitted 81 out of 92 total sequences. XBB.1.16* (with E180V) is present 280 times since May1st in the region, so 81 is shy of 30% of the XBB.1.16* samples there. The total samples uploaded in the timeframe is 1463, and 81 is about 5%.
Besides Alberta, the other 11 samples are 7 Quebec, 3 British Columbia and 1 California.
I don't know Canadian geography well, but I think that BC is in the west while Quebec on the east, Alberta should be in the middle. So probably the Quebec and BC samples resulted from exports of the Alberta outbreak. The California one is weird though as it is detected before the Alberta outburst, maybe it is the origin I am not sure.

**Comment by FedeGueli** [comment]
Yeah consider that Canada does targeted sampling so some small local cluster could seem suddenly huge. I think this is the case too.

**Comment by FedeGueli** [comment]
![Schermata 2023-07-16 alle 18 14 02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b5f7a19e-674b-4ad1-9128-f347fcdf8c40)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_747b_411580.json?label=id:node_6619902

Looking at the tree now it is quite normal. Some recent branches seem coming fromm circulation and not targeted sequencing . For example here there is an exported branch to Quebec from Alberta:
![Schermata 2023-07-16 alle 18 15 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f9c5dd61-b3f3-46ab-aab5-525708761489).

Still i dont think this has any real growth advantage over parental XBB.1.16 but lets see how it evolves

**Comment by FedeGueli** [comment]
It seems to have slowed down a lot. closing for now cause likely it was just a cluster and trgeting sequencing

**Comment by krosa1910** [comment]
Entirely Dead (just a comment by myself to not check it again).
