### ISSUE TITLE
KP.1.1.1+S:T22N,N30-,S31-,F32I,K478T rev(21 seqs, 10 places including GBW from India and UAE, 4 with S:A688S)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2120]
_First highlighted in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1920#issuecomment-2382752474_

There seems to be a KP.1.1.1 branch that shares the S:N30-,S31-,F32I with XDV.1.9.1 as well as S:T22N,K182N,K478T with MV.1 that is misplaced in an F59S flip-flop branch on usher.

KP.1.1.1+A6124G, C21627A, del21650_21655, T21656A, A22995C( S:T22N,N30-,S31-,F32I,K478T)

GISAID query: A6124G , A22108C ,C20104T, -C6500T(by @FedeGueli )
No. of seqs: 8(USA 5(CA, GBW from India and UK), Ireland 1 Canada 1 UK 1)
GISAID query for S:A688S sub-branch: A6124G, C20104T,A22108C,-22995,G23624T

First: EPI_ISL_19439491, USA-CA, 2024-8-12
Latest:EPI_ISL_19461123, GBW from UK, 2024-9-26

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice237_genome_test_1516c_13e5c0.json)
![image](https://github.com/user-attachments/assets/515837fc-ff9c-4f7e-ad02-6d11e4495a11)

Everything on the A6124G branch belongs to this and no seq actually have S:F59S. @AngieHinrichs

**Comment by FedeGueli** [comment]
Thank you for proposing i noticed it the last week.   it seems growing fast so very good to be proposed separately from the branch where uSher places it.

**Comment by xz-keg** [comment]
Change query to exclude the recombinant in #2134

**Comment by FedeGueli** [comment]
+1 France

**Comment by xz-keg** [comment]
+1 GBW from UAE

**Comment by FedeGueli** [comment]
PING @corneliusroemer this seems fast

**Comment by FedeGueli** [comment]
9 California

**Comment by FedeGueli** [comment]
+1 Japan

**Comment by xz-keg** [comment]
+1 Germany

**Comment by xz-keg** [comment]
+1 USA-NY

**Comment by FedeGueli** [comment]
> +1 USA-NY

still one only since  october 1

**Comment by xz-keg** [comment]
There is also an S:A688S sub-branch of this now.

**Comment by FedeGueli** [comment]
Now 15 with the Utah sample, looking for a query that catches it too.

**Comment by FedeGueli** [comment]
> Now 15 with the Utah sample, looking for a query that catches it too.

this one should catch all : A6124G  , A22108C  ,C20104T, -C6500T
excludint the KP.2.2 recombinant, also the last from Utah is likely a recent recombinant but i. would keep tracked here maybe specifying it in the proposal cc @xz-keg

**Comment by corneliusroemer** [comment]
You guys are so early with stuff! Just came across this when cleaning up tree for Nextclade release - there was a bunch of stuff wrong with KP.1.1.1 and KP.1.1.6.

**Comment by corneliusroemer** [comment]
MG.3

**Comment by xz-keg** [comment]
> You guys are so early with stuff! Just came across this when cleaning up tree for Nextclade release - there was a bunch of stuff wrong with KP.1.1.1 and KP.1.1.6.

Thanks to the tool that can catch almost everything at early stage as long as they gather on usher. 
https://github.com/xz-keg/Lineage-Detector

**Comment by corneliusroemer** [comment]
> Thanks to the tool that can catch almost everything at early stage as long as they gather on usher.
> https://github.com/xz-keg/Lineage-Detector

Looks interesting, I don't know what it does but I guess it calculates collection date based growth rates for each Usher branch, or maybe submission date based growth rates? I'll have a look at it when I have time.

**Comment by xz-keg** [comment]
> Looks interesting, I don't know what it does but I guess it calculates collection date based growth rates for each Usher branch, or maybe submission date based growth rates? I'll have a look at it when I have time.

It doesn't. When new lineages emerge it is hard to compute growth advantage with only 2-5 seqs. What I'm doing is just highlighting undesignated branches that appears in different regions in recent times, and then manually look at them.

**Comment by FedeGueli** [comment]
New sample from Taiwan but not super recent

**Comment by FedeGueli** [comment]
21 reopening it

**Comment by xz-keg** [comment]
> 21 reopening it

It is already designated MG.3

**Comment by FedeGueli** [comment]
> > 21 reopening it
> 
> It is already designated MG.3

aah thx! i was checking random queries that i have archived. thank you
