### ISSUE TITLE
KP.3.1.1 + ORF9b:I5T + S:Q677H (13 in NY and 1 in Pennsylvania, 10 on Gisaid) 5 with S:R346T

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2125]
![image](https://github.com/user-attachments/assets/cb70b4cb-4af1-4312-9601-b9d824eed486)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8c90_35ca60.json?f_userOrOld=uploaded%20sample

First Seq: 2024-08-16
Most Recent: 2024-09-19

Gisaid: G23593T, T28297C, T27484C

PQ387629.1 PQ409687.1 PQ426798.1 EPI_ISL_19423728 EPI_ISL_19447378 EPI_ISL_19447146 PQ277259.1 PQ409794.1 EPI_ISL_19423829 PQ386731.1 PQ363340.1

**Comment by FedeGueli** [comment]
Good catch, it is still NY only but Orf9b:I5T always something to watch
