### ISSUE TITLE
KP.1.1.3 with S:F186L,S:V445R and S:Q493E (22 seqs - 6 countries including Philippines) with two branches: one with S:R190S (20) and the other with S:L176F+S:M153I (2)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2126]
This was spotted first by @xz-keg in the groups and then tracked as Branch 30 of #1771 
it is defined by three spike mutations 186L,445R and 493E
The tree has now changed  and it appears to be a lineage with two branches: 
one earlier tracked  as Br.30 with S:R190S  
and the bottom one with S:L176F and S:M153I 
Query for the whole branch: C22120A, 22896G, C23039G
Query for S:R190S: C23039G,C4999T,G22132T,C25925T (by @aviczhl2 )
Query for S:L176F+S:M153I branch: C17822T, G22021C  ,C22088T
Samples: 4
Places: Israel, Germany, US, Philippines
<img width="1163" alt="Screenshot 2024-10-07 alle 01 03 24" src="https://github.com/user-attachments/assets/67b54e01-6593-463e-b240-068dd5678c1f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3d8d6_3159c0.json?c=userOrOld&label=id:node_7286077

 

_Originally posted by @FedeGueli in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1771#issuecomment-2395621524_

**Comment by xz-keg** [comment]
+3 Singapore for S:R190S branch

**Comment by FedeGueli** [comment]
+4 Singapore

**Comment by xz-keg** [comment]
+1 Canada-BC

**Comment by FedeGueli** [comment]
This appears more and more interesting

**Comment by xz-keg** [comment]
+5 Singapore +1 Canada-ON.

**Comment by FedeGueli** [comment]
> +5 Singapore +1 Canada-ON.
> 
> Propose this?

of course. thx

**Comment by FedeGueli** [comment]
> > +5 Singapore +1 Canada-ON.
> > Propose this?
> 
> of course. thx

oh please propose it you, it was you the first spotting this.

**Comment by FedeGueli** [comment]
22 Now with samples from three Canadian provinces.

**Comment by FedeGueli** [comment]
proposed in https://github.com/cov-lineages/pango-designation/issues/2811

**Comment by FedeGueli** [comment]
LP.8 via https://github.com/cov-lineages/pango-designation/commit/ef380be77b8fa66823880fe1b9aa29cca46543d7
