### ISSUE TITLE
Sandwich recombinant between LP.10.1/Lineage X with S:R346T and S:A435S    (14: Canada-3 provinces, Us-4 states,Malaysia)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2127]
There is a likely recombinant branch in the #1729 branch (>> Pango # 2755) with 75S 475V  that exchanged S:R190S for S:A435S 
Two Breakpoints  between S:76 (because of S:G75S) and S:811 (because of A23998G) ,
very likely  breakpoint1  is between S:76 and S:189 and BP2 between S:436 and S:474
it has also two private mutations:Orf1a:G493S (G1742A) and Orf1b:E2253V (A20225T)
Query: G1742A, A20225T, G22865T
Samples: 7 
First collected in NJ on 2024-07-25
Places: Canada, US
Tree:
<img width="1176" alt="Screenshot 2024-10-07 alle 01 28 25" src="https://github.com/user-attachments/assets/d42e2764-3960-4908-a696-b7d0883380f0">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_53c43_319870.json?c=gt-S_190&label=id:node_7284399

**Comment by aviczhl2** [comment]
Lineage X can be one of KP.2.3, KP.2.14, KP.2.16, LB.1.2,LB.1.4 or KR.1. 
It may also come from other lineages, there are many many potential lineages with S:R346T+S:A435S that can be its donor.

**Comment by FedeGueli** [comment]
> Lineage X can be one of KP.2.3, KP.2.14, KP.2.16, LB.1.2,LB.1.4 or KR.1. All these R346T lineages have significant A435S sub-branches.
> 
> It may also come from other lineages, there are many many potential lineages with S:R346T+S:A435S that can be its donor.

Thank you.

**Comment by DailyCovidCases** [comment]
Dead please close it

**Comment by FedeGueli** [comment]
+1 Ontario

**Comment by xz-keg** [comment]
![image](https://github.com/user-attachments/assets/e0c4c0b5-a179-49b7-850b-fffb3b094390)

There seems really is a small branch hiding inside LP.7 that shows the real origin of B2. So B2 is designated LP.10.1.

**Comment by FedeGueli** [comment]
> There seems really is a small branch hiding inside LP.7 from Germany/Costa Rica that shows the real origin of B2. So B2 is designated LP.10.1.

yeah both LP.10 and Lp.10.1 were the original proposal of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1729 and https://github.com/cov-lineages/pango-designation/issues/2755, interestingly the small dead bracnh on the bottom was 1 when proposed and the first german sample was included in the 190S branch and only three after being transferred to Pango but this time already separate and with the 190R rev and already dead so i never take consideration about it! . Then when Usher merged Kp.1.1.3+190S in one tree the focus went to that and the newly designated LP.10.1 was much slower than the rest so didnt look much into it. at this point i suggest to designate this recombinant   having 435S to complete the tree cc @corneliusroemer

**Comment by FedeGueli** [comment]
+1 California new state reopening for a while

**Comment by FedeGueli** [comment]
likely dead

**Comment by FedeGueli** [comment]
13,Malaysia but old ones

**Comment by FedeGueli** [comment]
+1 Canada new province recent sample, reopening for a while.

**Comment by xz-keg** [comment]
designated LP.10.1.1, shall be recombinant .

**Comment by FedeGueli** [comment]
For now designated LP.10.1 via  via https://github.com/cov-lineages/pango-designation/commit/d89bba9dc0b9d50ecea956d538e851c2a4b3f027

**Comment by FedeGueli** [comment]
Interestingly the last sample gained back 190T

**Comment by xz-keg** [comment]
@corneliusroemer LP.10.1.1 shall be a recombinant.

**Comment by FedeGueli** [comment]
> @corneliusroemer LP.10.1.1 shall be a recombinant.

mailed him likely he didnt see the tags.
