### ISSUE TITLE
KP.4.1 got Deflirt and it is still circulating in three continents in September (62, 14 places including Iraq) with a recent minibranch adding S:T22N (2, Australia, QLD)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2128]
This went unnoticed ( or we lost track of it) maybe due the fact Usher puts it under S:S31F but instead all of the sequences has S:S31del.
It managed to fly under the radar until September when it was samples 5 times from three continents (Australia, France, Spain, Florida) 
Interestingly it is converging now toward S:T22N with a mini branch sampled in Australia in September

KP.4.1 > S:S31del (del21653-55)
Query:   G26918A,del21653,T3565C
Samples: 62
Countries: 14 countries including Iraq
Query for S:T22N subbranch:T7061C, C7482T, G19656A
Tree:
<img width="1162" alt="Screenshot 2024-10-07 alle 19 35 32" src="https://github.com/user-attachments/assets/43ee53a7-a336-4bd5-a0b2-a1a0f89d3d1f">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_16eb4_416c90.json?label=id:node_7190898

**Comment by FedeGueli** [comment]
Ah and btw this is not KP.4.1.3 found and designated directly by Cornelius because it misses both the nucs defining it:
see: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_16eb4_416c90.json?c=gt-nuc_2057,5245&gmax=6245&gmin=1057&label=id:node_7190898
<img width="1166" alt="Screenshot 2024-10-07 alle 19 42 29" src="https://github.com/user-attachments/assets/2d17a5d8-374f-40be-bb7c-ae95797667ad">

**Comment by xz-keg** [comment]
I think this deserves a main page proposal

**Comment by FedeGueli** [comment]
> I think this deserves a main page proposal

Thx, proposed in https://github.com/cov-lineages/pango-designation/issues/2800
