### ISSUE TITLE
KP.3.1.1 + S:I203V (45, 6 places US, Canada, Australia)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2129]
Likely just clusters but very recent.
S:I203V appears to be a very rare mutations 
even if it is predicted by Dadonaite and Bloom to boost binding on XBB backbone
<img width="335" alt="Screenshot 2024-10-08 alle 01 04 11" src="https://github.com/user-attachments/assets/e4eadcd7-3597-432e-8f7e-55432642b3bc">
Nearby mutations in that area as S:Y200C has shown to be effective  in XBB.1.22.1/FY* or to a much lesser extent S:I197V

Defining mutations:Kp.3.1.1 > > A19722G >  C10681T > C1973T, S:I203V (A22169G)
Query: C10681T,A22169G  ,C1973T
Samples:  7
Places: US -2 States, Canada - 2Provinces
Tree:
<img width="1175" alt="Screenshot 2024-10-08 alle 01 09 36" src="https://github.com/user-attachments/assets/a4fbf40a-e4b5-4a9a-b1c7-0fb244240d33">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5527e_465a30.json?c=userOrOld&label=id:node_7202203

**Comment by FedeGueli** [comment]
11 maybe clusters?

**Comment by FedeGueli** [comment]
Jumped to 26 due a cluster in British Columbia

**Comment by xz-keg** [comment]
35 now,

**Comment by DailyCovidCases** [comment]
@FedeGueli please propose this branch

**Comment by FedeGueli** [comment]
> @FedeGueli please propose this branch

too early , but interestinglky found also in Australia now

**Comment by FedeGueli** [comment]
41 now also in Alberta

**Comment by FedeGueli** [comment]
Looking at non Canadian samples it is circulating but likely slow

**Comment by FedeGueli** [comment]
dying
