### ISSUE TITLE
FL.2.3+N:R189L,S:V642G  (38 seqs, 6 countries, mainly Guangdong)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#213]
FL.2.3+N:R189L,S:V642G (T23487G,G28839T)
GISAID query: T23487G,G28839T,A17615G

No. of seqs: 18(Sweden 3 USA 2(1 Airport, 1 from South Korea) Guangdong 3 Hubei 7 Taiwan 1 Fujian 1 Yunnan 1)

First seq: EPI_ISL_17697623, Guangdong, 2023-4-22
Latest seq: EPI_ISL_17788274, Sweden, 2023-6-2

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_1c9cb_fee180.json?label=id:node_6642553)
<img width="1394" alt="Screenshot 2023-06-19 at 14 19 15" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2eda25e8-9dff-4746-bcad-01abecf80807">

**Comment by aviczhl2** [comment]
21, UK

**Comment by Over-There-Is** [comment]
South Korea+1

**Comment by aviczhl2** [comment]
+12 from Guangdong, reopen
