### ISSUE TITLE
KP.1+ S:T22N,F59S,G72R,R346T,T572I(9 seqs, 4 places) [ it could be KP.1.2 or KP.1.1.5 or a recomb)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2136]
There seems to be a new branch of KP.1 getting S:T22N,F59S,G72R,R346T,T572I in China.

It can be explained as KP.1.2+S:T22N,F59S,G72R,R346T, or KP.1.1.5+S:T22N,G72R,T572I, or a KP.1-FULL QUAD branch recombines with the XEC+S:G72R branch. There are many possible ways to form it. 

KP.1+C2704T, C19572T, C21627A,G21776A, T21738C, G22599C, C23277T(S:T22N,F59S,G72R,R346T,T572I)

GISAID query: G21776A, C21627A, A24819G
No. of seqs: 3(China 1(Shanxi) Japan 1 New Zealand 1)

First: EPI_ISL_19426553, New Zealand, 2024-8-22
Latest: EPI_ISL_19467648, Shanxi, 2024-9-12

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice9_genome_test_528d4_728b40.json?label=id:node_5736919)
![image](https://github.com/user-attachments/assets/2c17f204-be08-4f1f-8fdd-64d8191a70f3)

**Comment by FedeGueli** [comment]
i would keep the palcement by usher only not to confound if someone else spots it.

**Comment by xz-keg** [comment]
> i would keep the palcement by usher only not to confound if someone else spots it.

Next time it may appear elsewhere. Usher tree is not very stable these days given the extreme high convergence.

**Comment by xz-keg** [comment]
> i would keep the palcement by usher only not to confound if someone else spots it.

I list those potential positions in title so we can find it even if usher changes its position.

**Comment by FedeGueli** [comment]
> > i would keep the palcement by usher only not to confound if someone else spots it.
> 
> I list those potential positions in title so we can find it even if usher changes its position.

Yeah and we will change consequently the issue.

**Comment by FedeGueli** [comment]
+2 Japan and Australia this last one from middle october >reopened

**Comment by FedeGueli** [comment]
+1 Australia different place (NSW vs SA earlier)

**Comment by FedeGueli** [comment]
+2 Saitama Japan

**Comment by FedeGueli** [comment]
+1 Jap, Chiba

**Comment by xz-keg** [comment]
designated MU.3 as a KP.1.1.5 descendant.

**Comment by FedeGueli** [comment]
Thx sorry i was tracking this without matching it with this issue.

**Comment by Over-There-Is** [comment]
It should be EPI_ISL_19467468

**Comment by FedeGueli** [comment]
> It should be EPI_ISL_19467468

What do you mean?

**Comment by Over-There-Is** [comment]
> Latest: EPI_ISL_19467648, Shanxi, 2024-9-12

**Comment by FedeGueli** [comment]
There is a sibling branch of MU.1 with S:T22N in Ukraine,Poland proposing it right now
