### ISSUE TITLE
KP.2.18+Orf1a:R3267K,Orf1b:A1428V, S:R190S(5 seqs, 4 places in 3 continents , 2 with S:A475V)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2140]
KP.2.18+G10065A, C15048T, C17750T,G22132T,C27881T(Orf1a:R3267K,Orf1b:A1428V, S:R190S)

GISAID query: T22795G, G22132T, C17750T
GISAID query for S:A475V sub-branch: T22795G, G22132T, C17750T,C22986T
No. of seqs: 5(UK 3(Scotland, England), USA 1 New Zealand 1 )

First:EPI_ISL_19372206, Scotland, 2024-8-10
Latest: EPI_ISL_19465023, England, 2024-9-25

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice51_genome_test_4dba5_763750.json?label=id:node_5743067)
![image](https://github.com/user-attachments/assets/c5804797-07d5-4c18-b161-960dbd5753c0)

**Comment by xz-keg** [comment]
no further growth

**Comment by Over-There-Is** [comment]
10, Mauritius, S:S31-, without C17750T

**Comment by FedeGueli** [comment]
> 10, Mauritius, S:S31-, without C17750T

new query G10065A, C15048T,C27881T finds 9
