### ISSUE TITLE
New KP.1.1.1 plus S:K478T and Orf3a:D199E emerged in Nepal (6 , 5 places including Qatar)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2143]
KP.1.1.1 >> C12400T > G24757T > ORF1a:V464I (G1655A), Orf1a:I2086N (T6522A), S:K478T (A22995C), ORF3a:D199E (C25989A), T27438C, C29296T 
Query: C25989A, T27438C,G24757T
Samples: 6
Places:  5 Nepal, Singapore, Qatar, Australia-NSW, Canada BC, 
Tree:
<img width="1177" alt="Screenshot 2024-10-10 alle 11 20 46" src="https://github.com/user-attachments/assets/031d2779-b769-45f4-b5db-78468f59b22e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_42b6d_7975b0.json?c=gt-ORF3a_199&label=id:node_7352464
![Uploading Screenshot 2024-10-10 alle 11.23.33.png…]()

**Comment by xz-keg** [comment]
was propose in #1985.

**Comment by xz-keg** [comment]
It also has S:S31del, making it DeFLiRT.
