### ISSUE TITLE
XDV.1.7 with S:T22N (6 , 6 places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2144]
XDV.1.7 acquired for a second time S:T22N
XDV.1.7>> S:T22N (C21627A)
Query: -C5173T, C21627A,G9203A,-G9923A 
Samples: 3
Places: Hubei, US - Oregon, Singapore
Tree:
<img width="1171" alt="Screenshot 2024-10-10 alle 17 22 29" src="https://github.com/user-attachments/assets/2b9044a6-f263-4122-a6f5-4fcf48dec608">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_435d7_7f04c0.json?c=gt-S_22&gmax=25384&gmin=21563&label=id:node_11694895

**Comment by FedeGueli** [comment]
one sample from Croatia in early october

**Comment by FedeGueli** [comment]
6 now California and Japan, this could be itneresting cc @xz-keg

**Comment by DailyCovidCases** [comment]
Please close this issue @FedeGueli

**Comment by FedeGueli** [comment]
11 with +5 from Sweden

**Comment by FedeGueli** [comment]
> 11 with +5 from Sweden

Scratch this they were LF.7 samples, new query: -C5173T, C21627A,G9203A,-G9923A finds 6 closing it then
