### ISSUE TITLE
MV.1 + ORF1b:K2557R (113 in 9 countries)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2149]
![image](https://github.com/user-attachments/assets/9d31be3c-f79a-492a-b659-af384330db36)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_60f5_b40c10.json?f_userOrOld=uploaded%20sample

First Seq: 2024-07-20
Most Recent: 2024-10-02

Gisaid: A21137G, C936T,  C21627A (edited)
Gisaid for Orf1a:S2103F sub branch: A21137G, C936T, C6573T (mainly Singapore) (edited)

PQ432138.1 EPI_ISL_19467870 EPI_ISL_19437940 EPI_ISL_19467950 EPI_ISL_19420685 EPI_ISL_19336983 EPI_ISL_19390513 EPI_ISL_19467948 EPI_ISL_19420677 EPI_ISL_19467818 EPI_ISL_19373003 EPI_ISL_19467842 EPI_ISL_19467802 EPI_ISL_19467919 EPI_ISL_19467873 EPI_ISL_19467911 EPI_ISL_19467844 EPI_ISL_19464449 EPI_ISL_19467850 EPI_ISL_19437370 EPI_ISL_19467822 EPI_ISL_19467892 EPI_ISL_19467914 EPI_ISL_19467878

**Comment by FedeGueli** [comment]
ORF1a:S2103F is close to 50K samples sparse in most of the fast lineages of the Pandemic. likely not deleterious.
In fact Bloom and Neher scored it as beneficial
<img width="231" alt="Screenshot 2024-10-13 alle 12 36 42" src="https://github.com/user-attachments/assets/dcbe054e-9859-4206-a40b-e271a06e8598">

@alurqu could you check for recent variants please?

**Comment by FedeGueli** [comment]
@Fearuncle i have adjusted the queries separating the main and the sub lineage

**Comment by FedeGueli** [comment]
the ORF1a:S2103F is Singapore only , likely a cluster. Hence its growth advantage (ahead of everything) should be taken with a grain of salt.

**Comment by alurqu** [comment]
> @alurqu could you check for recent variants please?

Bloom and Neher fitness estimates for ORF1aLS2103F across all clades for which estimates are available:

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,S2103F,1.0088
20B,ORF1ab,S2103F,1.0866
20C,ORF1ab,S2103F,1.3487
20E,ORF1ab,S2103F,1.1428
20G,ORF1ab,S2103F,1.2279
20H,ORF1ab,S2103F,1.4357
20I,ORF1ab,S2103F,1.3698
20J,ORF1ab,S2103F,1.3659
21C,ORF1ab,S2103F,1.2679
21I,ORF1ab,S2103F,1.0466
21J,ORF1ab,S2103F,1.0928
21K,ORF1ab,S2103F,0.76662
21L,ORF1ab,S2103F,1.2247
22A,ORF1ab,S2103F,1.2061
22B,ORF1ab,S2103F,1.0717
22C,ORF1ab,S2103F,1.1527
22D,ORF1ab,S2103F,1.0019
22E,ORF1ab,S2103F,0.82584
22F,ORF1ab,S2103F,1.0542
23A,ORF1ab,S2103F,1.0988
23B,ORF1ab,S2103F,1.1919
23C,ORF1ab,S2103F,0.95542
23D,ORF1ab,S2103F,0.60712
23E,ORF1ab,S2103F,0.99946
23F,ORF1ab,S2103F,0.92266
23H,ORF1ab,S2103F,0.24313
23I,ORF1ab,S2103F,1.037

So ORF1a:S2103F likely increases viral fitness a little but not a lot.

Unfortunately there are not yet any estimates available for mutation relative fitness on clades designated after 23I (BA.2.86).

**Comment by FedeGueli** [comment]
> > @alurqu could you check for recent variants please?
> 
> Bloom and Neher fitness estimates for ORF1aLS2103F across all clades for which estimates are available:
> 
> clade,gene,aa_mutation,delta_fitness 20A,ORF1ab,S2103F,1.0088 20B,ORF1ab,S2103F,1.0866 20C,ORF1ab,S2103F,1.3487 20E,ORF1ab,S2103F,1.1428 20G,ORF1ab,S2103F,1.2279 20H,ORF1ab,S2103F,1.4357 20I,ORF1ab,S2103F,1.3698 20J,ORF1ab,S2103F,1.3659 21C,ORF1ab,S2103F,1.2679 21I,ORF1ab,S2103F,1.0466 21J,ORF1ab,S2103F,1.0928 21K,ORF1ab,S2103F,0.76662 21L,ORF1ab,S2103F,1.2247 22A,ORF1ab,S2103F,1.2061 22B,ORF1ab,S2103F,1.0717 22C,ORF1ab,S2103F,1.1527 22D,ORF1ab,S2103F,1.0019 22E,ORF1ab,S2103F,0.82584 22F,ORF1ab,S2103F,1.0542 23A,ORF1ab,S2103F,1.0988 23B,ORF1ab,S2103F,1.1919 23C,ORF1ab,S2103F,0.95542 23D,ORF1ab,S2103F,0.60712 23E,ORF1ab,S2103F,0.99946 23F,ORF1ab,S2103F,0.92266 23H,ORF1ab,S2103F,0.24313 23I,ORF1ab,S2103F,1.037
> 
> So ORF1a:S2103F likely increases viral fitness a little but not a lot.
> 
> Unfortunately there are not yet any estimates available for mutation relative fitness on clades designated after 23I (BA.2.86).

thank you!

**Comment by FedeGueli** [comment]
+12 Singapore

**Comment by DailyCovidCases** [comment]
@FedeGueli Propose this branch?

**Comment by FedeGueli** [comment]
No it is mostly Singapore only .

**Comment by FedeGueli** [comment]
76/55 one sample came from Wales on the main branch

**Comment by FedeGueli** [comment]
84

**Comment by FedeGueli** [comment]
Please propose it when and if you see this in other two places beside Singapore.

**Comment by FedeGueli** [comment]
I see a trend that could be real  looking at its advantage in Singapore :
<img width="833" alt="Screenshot 2024-10-30 alle 13 20 27" src="https://github.com/user-attachments/assets/0ef7c56c-0f66-4e16-9776-a8c3d4de5590">
https://cov-spectrum.org/explore/Singapore/AllSamples/Past3M/variants?%2FAllSamples%2FPast3M%2Fvariants%3FnextcladePangoLineage=JN.1*&nucMutations=C6573C&nextcladePangoLineage=MV.1&nucMutations1=A21137G%2CC936T%2CC6573T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
I still don't see seqs from outside Singpaore as requested for the proposal but ok we will track it in the other repo.

**Comment by FedeGueli** [comment]
Designated MV.1.1 via https://github.com/cov-lineages/pango-designation/commit/17508bfb81b7eb0ce399f8e4d3a3bddb9c31c93a#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1297
