### ISSUE TITLE
KP.3.1.1 MOV related saltation singlet with S:A67T, T76I, T250I, P272S, E340K, G566S, A626V, T678I, A1016V, A1174T, C1248Y and several ORF mutations(AU-WA)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2150]
_This was first analyzed by @ryhisner yesterday here: https://x.com/LongDesertTrain/status/1844696890836693027_
(edited)

EPI_ISL_19472214
West Australia, Australia

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice91_genome_test_21c15_b4bcb0.json?label=id:node_7210825
![image](https://github.com/user-attachments/assets/320653b2-35dc-4c00-80e9-266bc777359c)

KP.3.1.1> C4113T(Orf1a:A1283V)> T26561C> C11036T(Orf1a:L3591F)
\> C412T, C556T, G923A(Orf1a:D220N), C1059T(Orf1a:T265I), C2263A, A2466G(Orf1a:K734R), G2539A, G2885A(Orf1a:V874I), G3167A(Orf1a:A968T), T3306C(Orf1a:M1014T), C3686T(Orf1a:H1141Y), G4232A(Orf1a:D1323N), A4359G(Orf1a:Q1365R), A4638G(Orf1a:N1458S), A5935G, A6034G, T6595C, A7347G(Orf1a:N2361S), A7450G, A7785G(Orf1a:K2507R), G8408A(Orf1a:V2715I), T9283C(Orf1a:V3091I), G9536A, C9907T, T10093C, A10323G(Orf1a:K3353R), G11179A, G11335A, G11507A(Orf1a:V3748I), G11548A(Orf1a:V3761I), T11611C, A11716G, C12025T, C12651T(Orf1a:T4129I), G13122A(Orf1a:C4286Y), G14160A, A14791G(Orf1b:S442G), G15627A, G15649A(Orf1b:V728I), T15690C, G15921A, C16409T(Orf1b:T981I), T16709C(Orf1b:L1081P), G17797A(Orf1b:V1444I), G18025A(Orf1b:V1520M), C18252T, T18258C, A18336G, G18832A(Orf1b:G1789S), G18948A, C19803T, G20033A(Orf1b:R2189H), G20060A(Orf1b:S2198N), G20083A(Orf1b:V2206I), G20521A(Orf1b:D2352N), G21761A(S:A67T), C21789T(S:T76I), C22311T(S:T250I), C22376T(S:P272S), A22420G, C22477T, G22580A(S:E340K), C22591T, C22624T, G23258A(G566S), T23278C, C23439T(S:A626V), C23595T(S:T678I), C24157T, C24559T, C24609T(S:A1016V), G25082A(S:A1174T), G25234A, G25305A(S:C1248Y), C25339T, T25542C, G25555A(Orf3a:V55I), G25641A, G25681A(Orf3a:V97I), C25844T(Orf3a:T151I), A25940G(Orf3a:D183G), C26004T, G26230A, C26335T, C26388T, G27361A(Orf6:E54K), G27589A(Orf7a:A66T), G27703A(Orf7a:V104I), T28203C(Orf8:F104L), G28307A(N:A12T, Orf9b:M8I), T28311Crev(N:L13Prev, Orf9b:S10Prev), T28588C, C28876T, A28984G

**Comment by Over-There-Is** [comment]
Already found by @Ryhisner

**Comment by FedeGueli** [comment]
This was analyzed by @ryhisner yesterday here: https://x.com/LongDesertTrain/status/1844696890836693027

it is related to MOV

**Comment by FedeGueli** [comment]
No need to close let it open and track it please.

**Comment by Mydtlwn** [comment]
I suggest you take a look at this; it has a lot of spike mutations. @corneliusroemer

**Comment by DailyCovidCases** [comment]
Dead please close it
