### ISSUE TITLE
S:D111N lineage emerging from LU.2.1.1 (9, 2 Places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2152]
There is a S:D111N lineage emerging from LU.2.1.1
LU.2.1.1 > S:D111N (G21893A) 
Query:G21893A,G7675T, C5826T
Samples: 6
Places: Ny, Ontario
it was sampled first in July but 5/6 are recent from late September 
tree:
<img width="1172" alt="Screenshot 2024-10-13 alle 12 17 14" src="https://github.com/user-attachments/assets/1af55374-fc12-4ee9-8002-187defadf367">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a877_b1aff0.json?label=id:node_7013119

_Originally posted by @FedeGueli in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2101#issuecomment-2408917700_

**Comment by DailyCovidCases** [comment]
Dead please close it

**Comment by FedeGueli** [comment]
3 very recent samples from the NY cluster reopening it for a while

**Comment by FedeGueli** [comment]
Closing it
