### ISSUE TITLE
LB.1.7 subbranch with S:A>D264G (US 17, 6 states) and further S:Q14H(US-CA 3)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2156]
LB.1.7> T18402C> A10042T> T28226C> A22353G(S:D264G)> C20133T> T17652C, G21604T(S:Q14H)
Query: C8293T, C22353G, T28226

Earliest sequence: 05-18 Santa Clara, California, USA EPI_ISL_19226702
Latest sequence: 09-06 California, USA PQ387583.1
Regions detected: US(California 12[1 not on GISAID], Delaware 1, Hawaii 1, Iowa 1, NJ 1, Virginia 1)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4b829_cce850.json?label=id:node_7333901
![image](https://github.com/user-attachments/assets/427107e8-6050-4156-9ac6-5efbfd296363)

Sequences:
EPI_ISL_19226702, EPI_ISL_19282126, EPI_ISL_19289401,
EPI_ISL_19298513, EPI_ISL_19314752, EPI_ISL_19347718,
EPI_ISL_19350666, EPI_ISL_19352136, EPI_ISL_19394384,
EPI_ISL_19405344, EPI_ISL_19414340, EPI_ISL_19423506,
EPI_ISL_19456623, EPI_ISL_19474012, EPI_ISL_19474204,
EPI_ISL_19474232, PQ387583.1

**Comment by FedeGueli** [comment]
Died off
