### ISSUE TITLE
KP.3.3 subbranch with Orf9b:A75V(25, JP 20, US 6)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2157]
KP.3.3> C556T> C28507T(Orf9b:A75V)
Query: C556T, C28291A, C28507T
Query for dropout sequences: -C556T, T9151C, C28291A, C28507T

Earliest sequence: 04-28 Tokyo, Japan EPI_ISL_19145856
Latest sequence: 09-07 Chiba, Japan EPI_ISL_19456703
Regions detected: Japan 18(1 from US), US 5

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4ad78_cce4a0.json?c=country&label=id:node_7259976
![image](https://github.com/user-attachments/assets/86779b25-a2aa-40eb-ba51-bf10139fa302)

Sequences:
EPI_ISL_19145856, EPI_ISL_19197645, EPI_ISL_19205638,
EPI_ISL_19238901, EPI_ISL_19238903-19238905, EPI_ISL_19238907,
EPI_ISL_19238923, EPI_ISL_19269677, EPI_ISL_19305499,
EPI_ISL_19342594, EPI_ISL_19365368, EPI_ISL_19383781,
EPI_ISL_19420839, EPI_ISL_19424556, EPI_ISL_19424662,
EPI_ISL_19456703, EPI_ISL_19474103, EPI_ISL_19474107-19474108,
EPI_ISL_19474146, EPI_ISL_19474157

**Comment by FedeGueli** [comment]
Slow and local closing it
