### ISSUE TITLE
LF.8.1.1 subbranch with S:T>K478I and N:S23T(4, US 3, NZ 1)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2158]
LF.8.1.1> A22995T(S:K478I), T28340A(N:23T)
Query: C22995T, T28340A

Earliest sequence: 08-29 Alameda, California, USA EPI_ISL_19474245
Latest sequence: 09-04 Manukau, New Zealand EPI_ISL_19446878
Regions detected: New Zealand 3, US 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_192a1_cd53e0.json?c=country&label=id:node_6980466
![image](https://github.com/user-attachments/assets/8168bb48-32ae-4bc8-96f3-6f36c6a394ed)

Sequences:
EPI_ISL_19446878, EPI_ISL_19474091, EPI_ISL_19474141,
EPI_ISL_19474245

**Comment by FedeGueli** [comment]
designated ND.3 via https://github.com/cov-lineages/pango-designation/commit/bb7b4ed873bc2cea1fcd9a2cecbd7d84895073a6
