### ISSUE TITLE
FL.4+S:S254P, orf3a:D173G( 132 seqs, 13 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#216]
FL.4+A28615G+A25910G(orf3a:D173G),T22322C(S:S254P)
GISAID query: A25910G,A28615G
No. of seqs: 98(Australia 4 Austria 2 USA 5 South Korea 1 Oman 1 Malaysia 2 Israel 1 Italy 1 Ireland 1 Germany 1 France 2 UK 1 Canada 76)

69 of the seqs have position 22322 masked. 

Of the 29 seqs with position 22322 unmasked, 28 of them show T22322C(S:S254P) and one of them show T22322Y, it is likely also have T22322C. So the branch have T22322C(S:S254P)

First seq: EPI_ISL_17344648, Israel, 2023-3-20
Latest seq: EPI_ISL_17809789, Canada, 2023-6-6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_1c9cb_fee190.json)
<img width="1374" alt="Screenshot 2023-06-19 at 15 56 48" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9a4083e7-d6cc-4c27-a975-8dea25495cf8">

**Comment by FedeGueli** [comment]
I think this one is very clear better propose it and see if Cornelius wants to complete the FL.4 picture he started to draw last week

**Comment by FedeGueli** [comment]
One seq of this acquired S:L455F

**Comment by aviczhl2** [comment]
> I think this one is very clear better propose it and see if Cornelius wants to complete the FL.4 picture he started to draw last week

Proposed.

**Comment by FedeGueli** [comment]
mass upload from Canada of this lineage today with an additional rbd mutation S:Y351H
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a822_5f4ac0.json?c=userOrOld&label=id:node_6706908
![Schermata 2023-07-06 alle 00 57 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bdcea9e1-20c4-4f6d-bbd9-793a2512bbb4)

**Comment by FedeGueli** [comment]
Designated FL.4.9 via https://github.com/cov-lineages/pango-designation/commit/c2c296328cfb690654cd7dcc6a01e612b46ce034
