### ISSUE TITLE
JN.1.16.3 subbranch with S:V>H445P on Orf1a:W2769C branch(15, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2160]
JN.1.16.3> G8572T(Orf1a:W2769C), G16065A> T9508C, A22896C(S:H445P)
Query: G8572T, T9508C
Query for dropout sequences: A2406G, G8572T, -T9508C, T22896C

Earliest sequence: 06-03 Fukuoka City, Fukuoka, Japan EPI_ISL_19232171
Latest sequence: 09-18 Miyagi, Japan EPI_ISL_19472078
Regions detected: US 5(1 GKIS from unknown), Japan 5, Korea 4, Belgium 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_55586_ce0640.json?c=country&label=id:node_7189998
![image](https://github.com/user-attachments/assets/75f637c7-9541-46a8-8f3a-2b13b99c1e5b)

Sequences:
EPI_ISL_19229790, EPI_ISL_19232171, EPI_ISL_19240934,
EPI_ISL_19289171, EPI_ISL_19314511, EPI_ISL_19339406,
EPI_ISL_19340592, EPI_ISL_19352628, EPI_ISL_19352684,
EPI_ISL_19405221, EPI_ISL_19407004, EPI_ISL_19411517,
EPI_ISL_19472063, EPI_ISL_19472066, EPI_ISL_19472078,

**Comment by FedeGueli** [comment]
Not going anywhere closing it

**Comment by xz-keg** [comment]
designated NS.1.1
