### ISSUE TITLE
LB.1.3 + S:T>A376S circulating in South Africa (17, 4 places, 25% South Africa)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2165]
LB.1.3>> orf1a:G432S (G1559A) > S:A376S (G22688T)
Query:22688T,G1559A
Samples: 14 (South Africa 11, Denmark 2, Canada 1)
First sampled on 2024-08-06 in a traveler from SA
Last sampled on 2024-09-23 Denmark
Tree:
<img width="1133" alt="Screenshot 2024-10-18 alle 01 26 04" src="https://github.com/user-attachments/assets/f5080d36-56e0-441e-853a-2e2f8f87df82">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_5e67b_192cc0.json?c=userOrOld&label=id:node_7336116

**Comment by xz-keg** [comment]
6/24 in South Africa seqs after 9-1, the prevalence seems large. I think maybe this one deserves proposal.

**Comment by xz-keg** [comment]
17 now, also in Portugal

**Comment by FedeGueli** [comment]
This makes me think that also MC.10.2 could become more interesting, South Africa usually anticipates trends.

**Comment by FedeGueli** [comment]
> 6/24 in South Africa seqs after 9-1, the prevalence seems large. I think this one deserves proposal.

Considering also GBW is slighty inferior than that around 20% 6/32

**Comment by FedeGueli** [comment]
> 6/24 in South Africa seqs after 9-1, the prevalence seems large. I think this one deserves proposal.

Thx now proposed in https://github.com/cov-lineages/pango-designation/issues/2825

**Comment by FedeGueli** [comment]
LB.1.3.4 via https://github.com/cov-lineages/pango-designation/commit/16205e716c6a68ff1c3d0f26f0c77478682368ac
