### ISSUE TITLE
MC.8.1/KP.3.3 or XEC recombinant(13 seqs, 6 places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2167]
MC.8.1--KP.3.3 or XEC 

Breakpoint between 23278 and 25005

Additional mutations: C18486T,G20397T, G27798T, A29700G

Orf1b:K2310N
Orf7b:A15S

C18486T from the main MC.8.1 branch
A29700G from KP.3.3 branch or XEC branch. Both have such a branch. 
G20397T,G27798T are private mutations

GISAID query:C18486T, C25006T,G28884C,C23277T,C12616T
No. of seqs: 7( France 3 Belgium 2 Luxembourg 1 UK 1)
6 on GISAID, one UK seq currently not.

First: EPI_ISL_19374941, Belgium, 2024-8-13
Latest: CLIMB-CM7YRJJ9, Wales, 2024-10-3

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice52_genome_test_24bec_47bc30.json?label=id:node_5651581)
![image](https://github.com/user-attachments/assets/858997d4-f731-42dd-8e36-806a6345a5af)

**Comment by xz-keg** [comment]
+1 France +1 Ireland

**Comment by FedeGueli** [comment]
Not slow

**Comment by xz-keg** [comment]
+1 USA-IL +1 GBW from France

**Comment by FedeGueli** [comment]
Likely very slow but still around we will check it later

**Comment by FedeGueli** [comment]
dead
