### ISSUE TITLE
XBB.1.34.2 sublineage with S:F456L (T22928C)(14 seqs, including a small saltation branch with S:K478R and S:E554Q)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#217]
Defining mutations: XBB.1.34.2>C21998A(S:Q146K)>T22928C(S:F456L)

GISAID query: Spike_P681R, Spike_K182I, Spike_F456L, Spike_F486P
Nuc Query: T22928C, G3230T , A22107T (EDITED)
Earliest seq: 2023-04-25 (USA, EPI_ISL_17705477)
Most recent seq: 2023-06-06 (Austria, EPI_ISL_17810634)
Countries detected: USA (3), Austria (2), Israel (2), China (1)
A small saltation in Israel (2 seqs) with: G3056A (ORF1a:E931K), C3828T(ORF1a:S1188L), C19029T, A22995G (S:K478R), G23222C (S:E554Q), C29095T
Usher Tree: Notice that one sample is on another branch. 

![QQ截图20230619174615](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/8e05d392-afc0-4b6a-9982-0b9b29890b56)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_386b_22170.json?c=gt-S_456

Recently S:F456L is one of the most popular Spike mutations. The sublineage deserves further tracking despite it is small now. 

Genomes: 
EPI_ISL_17664620, EPI_ISL_17705477, EPI_ISL_17707041, EPI_ISL_17788904, EPI_ISL_17803559, EPI_ISL_17803730, EPI_ISL_17810624, EPI_ISL_17810631

**Comment by HynnSpylor** [comment]
2 seqs from Canada

**Comment by FedeGueli** [comment]
3 more sequence from California and Arizona.

I would not wait further and i would like you to propose this one.
