### ISSUE TITLE
KP.3.3.2 (S:A435S) sublineage got S:S31del (52 seqs, Canada- 5 regions, Minnesota) and then S:S446N (13 seqs, 3 regions in Canada) 

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#2172]
**Main Branch (S:S31del)**
GISAID query: C10741T,C14757T,G22865T
No. of seqs: 29 (28 from multiple Canadian regions, 1 from USA) 
First: EPI_ISL_19350608, Manitoba Canada, July 20 
Latest: EPI_ISL_19494753, Ontario Canada, October 9 

Mutations relative to KP.3.3.2: 
C10741T -> C10605T, C14757T, 21653-21655del 

**Sub-branch (S:S446N)**
GISAID Query: G16221T, G22899A
No. of seqs: 7 from 3 Canadian regions. (Saskatchewan - 4. Alberta - 2. Ontario - 1)
First: EPI_ISL_19446125, Saskatchewan Canada, September 8
Latest: EPI_ISL_19494753, Ontario Canada, October 9

Mutations relative to Main Branch:
G16221T, G22899A
This only results in S:S31del, S:S446N across the two branches

[Usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8b4f_663ae0.json)
![image](https://github.com/user-attachments/assets/6e1f1fc3-5a28-4b43-a43d-f635e8b77740)

**Discussion:** After acquiring S:31del, this branch of KP.3.3.2 matches MC.10.1's spike which currently appears to be one most quickly growing variants today. The sub-branch with S:S446N currently makes up 13/25 of JN.1* sequences with S:S446N that have been submitted globally since July 1. Possibly the mutation is surviving on this lineage because the variant was very fit and therefore able to sustain detrimental mutations, or perhaps S:A435S has changed the favorability of S:S446N.

**Comment by FedeGueli** [comment]
Great catch Nick! Curiously 446N has been previously proposed in a XBF sublineage that was hard to die ! : https://github.com/cov-lineages/pango-designation/issues/2105

**Comment by ryhisner** [comment]
ORF1a:P3447L (NSP5_P184L), despite being C->T, is a rare mutation as well. Only ~70 sequences in 2024 have had it and fewer than 4000 ever. There's something interesting about the 175-185 range of NSP5, though I'm not sure what or why. I haven't read very much about NSP5, so I'm not sure where that region fits in the structure or what its role might be. 

I don't know of S:K444N would be an advantageous mutation in KP.3 or not, but S446N makes it a possibility for the first time. Before, with G446S, K444N would've created a lethal glycan in the RBD. Now that option is open.

**Comment by FedeGueli** [comment]
+1 Alberta

**Comment by FedeGueli** [comment]
@Sinickle this is not MC.10.1!!
This is a sublineage of Kp.3.3.2 (=Kp.3.3 + A435S)! that gained further S:S31del ( together with C14757T node)  and then S:S446N!
KP.3.3.2> C10741T > C14757T, S:S31del (del21653-55) >> G16221T, S:S446N (G22899A)

Query:C10741T,G22865T,C14757T 
Samples: 29 From Canada (5 Regions) and US (Minnesota) 
<img width="1133" alt="Screenshot 2024-10-25 alle 14 39 52" src="https://github.com/user-attachments/assets/7067f5c0-65c7-4a14-9000-27180820152b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1a8dd_b90570.json?label=id:node_7289619

I modify now the title please update the proposal consequently!

**Comment by Sinickle** [comment]
Thanks Fede! Updated!

**Comment by FedeGueli** [comment]
> Thanks Fede! Updated!

Thank you!

**Comment by FedeGueli** [comment]
51 with new samples from Australia too.

**Comment by xz-keg** [comment]
I think this one deserves proposal.

**Comment by FedeGueli** [comment]
> I think this one deserves proposal. Deletion lineages are always worth designation due to invisibility on usher.

agree the most recent samples are from 4 different Canadian provinces even if clusters this shows a great capability of doing that.

**Comment by FedeGueli** [comment]
@Sinickle please propose it in the main page

**Comment by Sinickle** [comment]
https://github.com/cov-lineages/pango-designation/issues/2821

**Comment by FedeGueli** [comment]
Designated NP.1 Starting with 446N via https://github.com/cov-lineages/pango-designation/commit/ad2242f9751cc6c3409b95075af7269fcc5170f7#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1310

**Comment by FedeGueli** [comment]
In the Kp.3.3.2 branch with 31del before NP.1 appeared a S:P139S (N137 new N Glycan) sample recently , query for it : C3253T, G12191T, C16111T

**Comment by Over-There-Is** [comment]
A Canadian cluster of S:S31- branch has no C10605T.

**Comment by FedeGueli** [comment]
> In the Kp.3.3.2 branch with 31del before NP.1 appeared a S:P139S (N137 new N Glycan) sample recently , query for it : C3253T, G12191T, C16111T [tree](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_1a2be_7f3750.json?label=id:node_7293868)

This is now 15 but the query is wrong , looking for a new one

**Comment by FedeGueli** [comment]
> C3096T, C3253T, C21977T

20 now for 139S

**Comment by FedeGueli** [comment]
23 for 139S now but still a cluster

**Comment by FedeGueli** [comment]
32 for 139S still Ontario (C3096T, C3253T, C21977T)

**Comment by FedeGueli** [comment]
> 32 for 139S still Ontario (C3096T, C3253T, C21977T)

48 Ontario only
