### ISSUE TITLE
XEC subbranch with Orf9b:R32L on Orf1a:A599T branch(63 seqs, 11 countries) and its recombinant with KP.3.1.1(4 sequences, DE 3, US 1)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2173]
## XEC> G2060A(Orf1a:A599T)> G28378T(Orf9b:R32L)

Query: -C1684A, T3565C, C19716T, G28378T, -C6701T, -C18687T, -A21766T, -G25234T
("-"s are added to remove convergent sequences)

Earliest sequence: 08-07 Schleswig-Holstein, Germany EPI_ISL_19364163
Latest sequence: 10-11 Asturias, Spain EPI_ISL_19497008
Regions detected: Denmark 9, UK 9, Germany 8, Italy 8, Netherlands 7, Sweden 7, France 5, Spain 4, US 3(1 from Denmark, 1 pooled, 1 not on GISAID), Luxembourg 2, Belgium 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_7f5f_7a0d10.json?c=country&label=id:node_7267532
![image](https://github.com/user-attachments/assets/23bcd1a9-6f0e-406a-896b-cedb547dd265)

<details><summary>Sequences:</summary>

EPI_ISL_19364163, EPI_ISL_19378139, EPI_ISL_19383090,
EPI_ISL_19410252, EPI_ISL_19415557, EPI_ISL_19417577,
EPI_ISL_19417585, EPI_ISL_19421034, EPI_ISL_19426850,
EPI_ISL_19431751, EPI_ISL_19433943, EPI_ISL_19435638-19435640,
EPI_ISL_19436766, EPI_ISL_19436780, EPI_ISL_19443858,
EPI_ISL_19444527, EPI_ISL_19447700, EPI_ISL_19447703,
EPI_ISL_19448892, EPI_ISL_19448913, EPI_ISL_19450798,
EPI_ISL_19451326, EPI_ISL_19451444, EPI_ISL_19451506,
EPI_ISL_19451675, EPI_ISL_19456847, EPI_ISL_19456850,
EPI_ISL_19456875, EPI_ISL_19458753, EPI_ISL_19463326,
EPI_ISL_19464961, EPI_ISL_19467664, EPI_ISL_19468204,
EPI_ISL_19468795, EPI_ISL_19472522, EPI_ISL_19477073,
EPI_ISL_19477087, EPI_ISL_19477236, EPI_ISL_19477238,
EPI_ISL_19477492, EPI_ISL_19477776, EPI_ISL_19478671,
EPI_ISL_19478700, EPI_ISL_19481383, EPI_ISL_19481474,
EPI_ISL_19481484, EPI_ISL_19481515, EPI_ISL_19481533,
EPI_ISL_19484080, EPI_ISL_19485103, EPI_ISL_19485195,
EPI_ISL_19485671, EPI_ISL_19486463, EPI_ISL_19488255,
EPI_ISL_19488579, EPI_ISL_19493850, EPI_ISL_19493952,
EPI_ISL_19494033, EPI_ISL_19497008, EPI_ISL_19497087,
PQ409725.1

</details>

## KP.3.1.1 / XEC

Query for recombinant: C1684A, C19716T, G28378T

Mutations based on KP.3:
C1684A(private?), C12616T / T17334Grev, C18657T, C19716T, C21627A, T21738C, C25006T, C28291A, G28378T(Orf9b:R32L), G28884C
Breakpoint: 12616\~13121
C1684A is in 2 sequences from different branches, or it could be private.

09-02~10-01, Bayern, Germany 3
Date unavailable, Ohio, US 1
Sequences:
EPI_ISL_19424919, EPI_ISL_19477344, EPI_ISL_19488853,
EPI_ISL_19497066

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_29260_7a80e0.json?c=country&label=id:node_7268393
![image](https://github.com/user-attachments/assets/1fa8377f-0adf-47ed-b4b0-7e210932da2c)

**Comment by Over-There-Is** [comment]
@FedeGueli

**Comment by Over-There-Is** [comment]
this branch could be from somewhere around the border of Germany and Denmark, as the earliest collected sample is from Schleswig-Holstein, a state next to Denmark.

**Comment by xz-keg** [comment]
better propose it to main? It is already very large despite almost no additional fitness than XEC.

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation#2813

**Comment by Over-There-Is** [comment]
@FedeGueli @xz-keg Milestone

**Comment by FedeGueli** [comment]
XEC.18 & XEV

via https://github.com/cov-lineages/pango-designation/commit/4a6e529c6a8f03328ddafd3800e1252708f75f71
