### ISSUE TITLE
KP.3.1.1 + S:F643K (3-nuc), M:S214T, ORF1a:V3056G (5 seq, Wales) + 3 w/ additional S:D574N, S:R847I 

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#2174]
**Description**
**Sub-lineage of:** KP.3.1.1
**Earliest sequence:** 2024-9-8, Wales, EPI_ISL_19431531
**Most recent sequence:** 2024-10-2, Wales, EPI_ISL_19493965
**Continents circulating:** Europe (5)
**Countries circulating:** Wales (5)
**Number of Sequences:** 5
**GISAID Nucleotide Query:** T9432G, T23489A
**CovSpectrum Query:** Nextcladepangolineage:KP.3.1* & T9432G
**Substitutions on top of KP.3.1.1:**
**Spike:** D547N (3/5), F643K (3-nuc), R847I (4/5)
**M:** S214T
**ORF1a:** H83Y, V3056G 
**Nucleotide:** C512T,  T9432G, G19872T, T21546A, G23282A (3/5), T23489A, T23490A, T23491A, G24102T (4/5), G27163C

**Phylogenetic Order of Mutations:** C512T (ORF1a:H83Y) **→** G19872T **→** T9432G, T21546A, T23489A, T23490A, T23491A, G27163C (ORF1a:V3056G, S:F643K, M:S214T) **→** (G24102T) S:R847I  **→** G23282A (S:D574N ) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons3/refs/heads/main/KP.3.1.1_F643K__5_seq.json?c=gt-S_643&gmax=25384&gmin=21563&label=id:node_7230621

<img width="1461" alt="image" src="https://github.com/user-attachments/assets/7c748109-5ebb-4fc3-a364-72f32c2e21d7">

**Evidence**
I think there’s a decent chance that all five of these sequences are from the same patient. One of the sequences has ambiguous nucleotides at S:R847 and S:D574 (both of which later mutated, to S:R847I and S:D547N), and the earliest sequence has ∆143-144 instead of the usual ∆Y144. This sort of diversity is commonly seen in chronics. However, the UK has a frustrating policy of never including metadata in any of their sequence uploads, so it’s never possible to know for sure if sequences are from the same patient or not. 

ORF1a:V3056G (NSP4_V293G) is extraordinarily rare. It has only ever occurred in seven previous sequences: four Delta (AY.100 [2], AY.122, AY.4), two BA.1.16, and one BA.2. It's in the second transmembrane region of NSP4 (TM2), which is just downstream of the NSP4-ectodomain, which binds with the NSP3 ectodomain within the SARS-CoV-2 replication organelles (ROs), or double-membrane vesicles (DMVs). All images below are from the incredible "Molecular architecture of coronavirus double-membrane vesicle pore complex" by Huang Y et al in Nature. https://www.nature.com/articles/s41586-024-07817-y
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/192d1d3b-1809-4209-ace6-939b98dfb14c">

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/36cd168b-de45-4d56-b139-ae65744915c4">

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/dc851bfb-7416-47f0-b162-1c7d8c8ee7f7">
.

.

.
S:F643K is a 3-nuc mutation that has appeared before, though it is rare. It’s one of a number of triple X→A nucleotide mutations (usually all or nearly all T→A) that have appeared intermittently in the past several years. It’s not always clear how or why these mutations occur. In some cases, I think it’s almost certain that recombination with the untranslated region between ORF8 and N is the cause, but that’s not the case here. This one does form an AAACAAAC motif, which is just one nucleotide away from the TRS-L pattern of AAACGAAC. Since recombination between TRS regions is a common cause of multi-nuc mutations, there is a chance this is the cause of S:F643K.  

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/b57089ee-f974-4dbf-b54e-d4d2aa1340f1">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19431531, EPI_ISL_19486457, EPI_ISL_19486534, EPI_ISL_19493865, EPI_ISL_19493965
</details>

**Comment by ryhisner** [comment]
The other unusual thing about this branch that I forgot to mention is that all six nucleotide mutations on the long branch are rare transversions: four T->A, one G->C, and one T->G. The next branch, shared by four of the five sequences, is another transversion (G->T) though one much less rare than the others.

**Comment by FedeGueli** [comment]
It was likely just a cluster closing for now
