### ISSUE TITLE
XEC saltation (5 Spike NTD mutations, Botswana, singlet)

### ISSUE THREAD

**Issue by cvejris** [sars-cov-2-variants/lineage-proposals#2175]
EPI_ISL_19493609 (collected Oct17th) is not the best sequence but in the clear portion contains 5 Spike mutations over vanilla XEC: 
S45Y, G72R, S98F, R246N (2-nuc), S256L. Plus a lot of Orf1ab mutations.
![image](https://github.com/user-attachments/assets/bfacfaa5-50b7-4c86-a38d-448cd8eb4a74)
All Spike mutations are in the NTD. We already saw mutations in G72, S98 and S256 popping up in XEC, but always separately, their combination looks worrisome. Originated from an 80yo hospitalized patient.

Putatitev query: G2964C, C4139G (Edited)

**Comment by FedeGueli** [comment]
This is full of interesting thing cc @ryhisner :
<img width="1124" alt="Screenshot 2024-10-22 alle 23 39 59" src="https://github.com/user-attachments/assets/caf0acc7-e22c-4144-a820-98e1a754066b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3c043_81acb0.json?label=id:node_11717611

**Comment by FedeGueli** [comment]
mm it has also a stop codon in Orf1a... hard to think it is real

**Comment by FedeGueli** [comment]
Query: G2964C, C4139G

**Comment by cvejris** [comment]
> mm it has also a stop codon in Orf1a... hard to think it is real

If the Spike muts were not in positions which are known to mutate in XEC, I would probably not propose it. Might be a mixture of real and artificial (sequencing error, e.g. base calling) mutations.

**Comment by ryhisner** [comment]
> This is full of interesting thing cc @ryhisner 

Yeah, I think most of the mutations are artifacts. Most of the spike mutations are probably real. S:N211I is a dropout artifact. Hard to say if S:S246N is real or not.

**Comment by DailyCovidCases** [comment]
Dead please close it
