### ISSUE TITLE
KP.3.1.1 subbranch with S:L335F, Orf1a:K2109E and Orf10:Y26H(51, 6 countries, 4% in NZ)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2176]
KP.3.1.1> C21859T> A20712G> A6590G(Orf1a:K2109E), G22567C(S:L335F), T29633C(Orf10:Y26H)
Query: C12616T, C21859T, G22567C by @xz-keg

07-18 British Columbia, Canada EPI_ISL_19318265
10-08 Utah, USA EPI_ISL_19479658
US 10, UK 8, Australia 4, Canada 3

**Comment by FedeGueli** [comment]
Thx i was tracking it with G22567C,A6590G,del21653

**Comment by FedeGueli** [comment]
Sorry i ve mistankenly closed it some days agop. now 30

**Comment by xz-keg** [comment]
A20712G seems missing in some seqs, +6 New Zealand with new query: C21859T, G22567C,C12616T

**Comment by FedeGueli** [comment]
43, germany

**Comment by xz-keg** [comment]
+6 in NZL again

**Comment by FedeGueli** [comment]
4% in NZl

**Comment by Over-There-Is** [comment]
AU-NSW+2

**Comment by FedeGueli** [comment]
1% in Oceania

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
Two samples of this from NSW have further S:Q1208H and S:L1143F

**Comment by Over-There-Is** [comment]
github.com/cov-lineages/pango-designation#2832
