### ISSUE TITLE
New 31del-493E-1104L carrying Unknown/KP.3.1.1 recombinant  (3, Ontario)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2177]
New 31del-493E-1104L carrying recombinant likely between Unknown(not KP*)/KP.3.1.1 with breakpoint after 19722  ( all unsure in my view)
that gained further S:E702V and S:R102K
Query: G11283A, C17762T, A20289G
Samples: 3
Ontario  
<img width="1139" alt="Screenshot 2024-10-23 alle 14 26 27" src="https://github.com/user-attachments/assets/d36d041d-3fa9-4d39-a365-bfb5ecb026cd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_106f8_8e7040.json?c=userOrOld&label=id:node_11717614
 

 

_Originally posted by @FedeGueli in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2086#issuecomment-2431985074_

**Comment by xz-keg** [comment]
Likely the other donor is the top JN.1.16.1+S:R214H branch.

**Comment by DailyCovidCases** [comment]
Dead please close it @FedeGueli

**Comment by DailyCovidCases** [comment]
@FedeGueli Dead please close it
