### ISSUE TITLE
JN.1.4 Saltation [12 AA subs, 5 in Spike]  (Hong Kong, 6 seq, 3 pts)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#2178]
**Description**
**Sub-lineage of:** JN.1.4
**Earliest sequence:** 2024-9-20, Hong Kong, EPI_ISL_19464534 
**Most recent sequence:** 2024-10-10, Hong Kong, EPI_ISL_19498393 
**Continents circulating:** Asia (2)
**Countries circulating:** Hong Kong (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** T21652A, G21701A
**Alternative query by Fed**: _C5365T,C7851T, T10636C_
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of JN.1.4:**
**Spike:** N30K, V47I, S151I, R346T, D936H
**ORF9b:** I5T, L64P
**ORF1a:** H388Y, P1786L, V2276A, A2529V, Q2574H, A4285V
**ORF1b:** L137F
**Nucleotide:** C1427T, C4543T, C5192T, C5365T, C5622T, G5629T, T7092C, C7851T, T7855C, G7987T, T10636C, A12508G, C13119T, C13876T, T21652A, G21701A, G22014T, G22599C, A24325G, G24368C, C27630T, T28297C. T28474C

**Phylogenetic Order of Mutations (edited after the tree on Nov 10 by Fed) :** C13119T (ORF1a:A4285V)  **→**  C5622T (ORF1a:P1786L)  **→**  C5365T  **→**    C7851T, T10636C, C13876T, T21652A, G21701A, G22599C, T28474C  (  ORF1a:A2529V,   ORF1b:L137F, S:N30K, S:V47I, S:R346T, Orf9b:L64P)  
**→→** C1427T,C4543T, C5192T, G5629T, T7092C, T7855C, G7987T, A12508G, G22014T, A24325G, G24368C, C27630T, T28297C (ORF1a:H388Y,ORF1a:Q2574H, ORF1a:V2276A, S:S151I, S:D936H, ORF9b:I5T) 

C1427T, C4543T, C5192T, C5365T, C5622T, G5629T, T7092C, C7851T, T7855C, G7987T, T10636C, A12508G, C13119T, C13876T, T21652A, G21701A, G22014T, G22599C, A24325G, G24368C, C27630T, T28297C. T28474C

**USHER Tree updated as November 10 By Fed**
<img width="1164" alt="Screenshot 2024-11-11 alle 00 50 41" src="https://github.com/user-attachments/assets/5cd1d3b1-cccd-4ff9-aadb-86a1939036d9">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2376f_1463c0.json?f_userOrOld=uploaded%20sample&label=id:node_7102870
 

**Evidence (Not updated)**
Metadata indicate these two sequences are from different patients. The first sequence had 14 mixed nucleotides, likely indicating a chronically infected patient. Five of those mixed-nuc mutations were fixed in the second sequence, including two spike mutations. The second sequence had one mixed nucleotide, which isn’t uncommon for sequences from Hong Kong. Both of the ORF9b mutations (I5T and L64P) are commonly found in chronic-infection sequences. 

Assuming the metadata is correct (not always the case), this second case could be a close contact of the first, with no further transmission. Or the second sequence could be an indication of some low-level circulation. In either case, this branch almost certainly arose from a chronic infection in the first patient. The closest sequences on the tree were collected over 10 months ago. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_19464534, EPI_ISL_19498393, EPI_ISL_19529679, EPI_ISL_19529699, EPI_ISL_19555102, EPI_ISL_19555114
</details>

**Comment by FedeGueli** [comment]
Third sequence of this but likely another sample from same 78yr patient

**Comment by FedeGueli** [comment]
> Third sequence of this but likely another sample from same 78yr patient

Oh wait @ryhisner i must have re found it later and made a query to track it: C5365T,C7851T, T10636C , that query gives me 4 samples. 3 of them from a single patient likely

**Comment by FedeGueli** [comment]
@ryhisner i have added the query , updated the tree and edited the phylogenetic order of mutations to respect the actual tree: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2376f_1463c0.json?f_userOrOld=uploaded%20sample&label=id:node_7102870
<img width="1161" alt="Screenshot 2024-11-11 alle 00 58 42" src="https://github.com/user-attachments/assets/00f3c4e8-8729-46a9-8ed9-62195ea5e131">

**Comment by FedeGueli** [comment]
Looking at the tree it could be also that an Immunocompromised patient infected his/her caregiver but i dunno if it could be true

**Comment by ryhisner** [comment]
Fifth sequence in this branch was uploaded today, and the metadata indicate it is from a third patient. It is the longest branch yet and was collected November 8.   EPI_ISL_19555114

So we now have five sequences from three different patients. 

There are no mixed nucleotides in this sequence. The three sequences from the same patient all had 14-15 mixed nucleotides. It seems likely that this chronically infected person has transmitted to at least two others who are not themselves chronically infected. It would be good to know if this chain of transmission is confined to one facility or whether it is transmitting in the wider community.


<img width="1436" alt="image" src="https://github.com/user-attachments/assets/47f8f858-c242-47d4-9166-4b8f8409eac9">

**Comment by xz-keg** [comment]
no new seqs
