### ISSUE TITLE
BN.1.3.13 with S:A264D and Orf9b:S50L (28 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#218]
BN.1.3.13 (S:V445A)+C3817T+C7006A,C22353A(S:A246D),C28432T(Orf9b:S50L)

GISAID query: T22896C,C17818T,C593T,C7390A
GISAID query for S:A264D branch: C22353A,C28432T (12 seqs from China, Japan, South Korea and Singapore)

No. of seqs: 28 (USA 1 Japan 9(1 from Taiwan), Singapore 1(from Taiwan) South Korea 7(2 from Singapore) Thailand 1 Taiwan 6(1 from South Korea, 1 from Malaysia), Shanghai 2 Fujian 1)

First seq: EPI_ISL_17729868, USA, 2022-12-21
Latest seq: EPI_ISL_17811175, Shanghai, 2023-6-6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice62_genome_1c9cb_fee260.json)
<img width="1405" alt="Screenshot 2023-06-19 at 18 35 28" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1def5c10-cdd1-4764-ba1f-0fed5d81588c">

**Comment by FedeGueli** [comment]
Also S:A264D is popping up recently.

**Comment by FedeGueli** [comment]
@aviczhl2 being all the last samples from the branch with S: A264D  i suggest to keep the issue just for this subbranch , last sample without S:A264D is from April in Taiwan, although it is possible low level circulation there could be somehting we can decide not to track. SO please re arrange the issue if you agre with my thoughts.

**Comment by aviczhl2** [comment]
Just realized that S:264D branch also has Orf9b:S50L

**Comment by aviczhl2** [comment]
The BN.1.3+V445A is designated as BN.1.3.13 @FedeGueli

**Comment by FedeGueli** [comment]
> The BN.1.3+V445A is designated as BN.1.3.13 @FedeGueli

thx!! i ve noticed again BN.1 +445A but then checking it was already designated, i missed it was from here! thank you very much !

**Comment by aviczhl2** [comment]
25, USA

**Comment by FedeGueli** [comment]
Being already designated the aprental lineage i dont see the need to track it anymore.
