### ISSUE TITLE
NEW DEFLUQE  KP.3.2 sublineage mostly with Orf1a:I1005L (43, mainly Ontario)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2180]
Defining mutations: KP.3.2 >> C19269T > S:S31del (del21653-55) > Orf1a:I1005L (A3278C), T9016A, A14421G, C14931T
Query:A3278C, C19269T,DEL21653
Samples: 42
Places: Texas, Ontario , New Mexico
Tree:
<img width="1154" alt="Screenshot 2024-10-24 alle 13 13 11" src="https://github.com/user-attachments/assets/7a30be20-db09-47e1-91e5-a2bf5c27b236">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_493c4_a29750.json?c=userOrOld&label=id:node_7299430

**Comment by DailyCovidCases** [comment]
@FedeGueli please propose this branch

**Comment by FedeGueli** [comment]
> @FedeGueli please propose this branch

thx too early to propose very likely not going anywhere

**Comment by xz-keg** [comment]
designated KP.3.2.7
