### ISSUE TITLE
XEC + 4 spike Mutations (K150R, K529E, S704L, L1104V (R)) 4 all in Czechia all different patients

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2182]
![image](https://github.com/user-attachments/assets/9f07f7ff-f275-40d8-8950-a2c4a29223be)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3679e_b2fd50.json?f_userOrOld=uploaded%20sample

Mutations: ORF1b:V464I, ORF1b:S2312L, ORF1a:K1230N, ORF1b:T2514I, S:K150R, S:K529E, S:S704L, S:L1104V

First Seq: 2024-09-26
Most Recent: 2024-10-02

Gisaid: T4312C, G14857A

EPI_ISL_19497921 EPI_ISL_19497920

**Comment by cvejris** [comment]
Ha, I as a Czech did not notice this, shame. GISAID does not count it among XEC* - probably because of 1104rev

**Comment by corneliusroemer** [comment]
@cvejris Oh you are Czech! I'm often in Prague, shoot me an email if you want to meet up some time.
