### ISSUE TITLE
Delta(21J)/ KP.2.3 recombinant singlet with Spike NTD and RBD breakpoint in Malaysia

### ISSUE THREAD

**Issue by Clrs17** [sars-cov-2-variants/lineage-proposals#2188]
_first detected by @JosetteSchoenma in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2086._ (Edited)

Sequence: EPI_ISL_19506572
The Delta donor is a 21J+G9053T (ORF1a:V2930L), and the recombinant kept the Delta S2.
Possible genome composition:
5'- 2790(3430): 21J Delta
2791(3431) - 7113(7841): 24G KP.2.3
7114(7842) - 22000(22028): 21J Delta
22001(22029) - 22928(22941) 24G KP.2.3
22929(22942) - 25469(26059) 21J Delta
25460(26060) - 28461(28880) 24G KP.2.3
28462(28881) - 28957 21J Delta
28957 - 29402 24G KP.2.3
29402 -3' 21J Delta

Mutations on 24G part: A6183Grev (ORF1a:K1973Rrev)
Mutations on 21J part: C64T, C703T, A2848G, C3096T (ORF1a:S944L), C3157T, A3205G, G8851A,,G9053T (ORF1a:V2930L), C9430T, C9907T, G11365T, C11575T, C11651T( ORF1a:L3796F), A11782G, A11908G, C13876T( ORF1b:L137F), A13953T, A15046G, C15738T, C16616T(ORF1b:T1050I), C16767T, G17334T, C17410T(ORF1b:R1315C), T17700C, A18153G, C18312T, A18533G(ORF1b:K1689R), A18671C(ORF1b:D1735A), C19017T, C19140T, G19180T(ORF1b:V1905L), A19283C(ORF1b:D1939A), T21657C(S:F32S), T21738A(S:F59Y), G23282T(S:D574Y), C24909G(S:T1116S), C25006T, A28704T(N:D144V), 28913-28918del (N:214-215del),  

The Spike NTD breakpoint is between 22000 ( S:H146Q which is present in 24G)and 22029 ( S:E156del which is present in 21J), and the RBD breakpoint is between 22928 (S:F456L) and 22942 (S:N460K), which results in keeping the Delta FCS and S2 potential to increase pathogenicity by enhancements in medidating cell-cell fusion and increase cell-entry efficiency.

![image](https://github.com/user-attachments/assets/ef3989bf-f1e4-485b-8a5a-dcc662f90751)

![image](https://github.com/user-attachments/assets/f1a22e99-14fb-42cd-9f3f-b91778c1375e)
![image](https://github.com/user-attachments/assets/6ac3d5d4-24e1-4909-a193-0c8b00444447)

**Comment by Clrs17** [comment]
possible GISAID query: C13876T, A13953T

**Comment by xz-keg** [comment]
first detected by @JosetteSchoenma in #2086. 

But worth a separate issue though. There seems some Delta/JN.1 recombs emerging these days.

**Comment by JosetteSchoenma** [comment]
> first detected by @JosetteSchoenma in #2086. 
> 
> But worth a separate issue though. There seems some Delta/JN.1 recombs emerging these days.

Thanks, @xz-keg. I will copy what I wrote in the singlets issue here.

EPI_ISL_19506572, Delta/JN.1 (most likely KP.2). Malaysia 2024-06-02
Probably 11 breakpoints.
ORF1A-E, mostly Delta
M-ORF9B mostly JN.1
ORF1A, middle 3431-9053? JN.1
ORF1B, middle 17410-19220 JN.1
Spike 22029-22034 (F157S) and 22599-22928 (R346T-F456L) JN.1
N 28704-28958 Delta
With some pointers from @ryhisner , who might like to share his analysis, that could be more precise at some points.

**Comment by Over-There-Is** [comment]
A6183Grev could be from Delta, or artefactual.

**Comment by FedeGueli** [comment]
i just noticed it is old one from June 24 closing for now.
