### ISSUE TITLE
Delta (21J) Sequence in Asturias Spain (1) + 3 likely artifacts (or coinfections) with part of it.

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#2190]
These sequences have questions surrounding them right now, but it's at least possible that this is a real event. I'm starting this thread so that there's a place to discuss this. 

@thomaspeacock has reached out to a couple members of the lab via email to inquire for further details. 

EPI_ISL_19508878 - appears to be a highly mutated Delta sequence, and the patient metadata suggests it was sampled from a 1-year-old, which would mean it was likely recently transmitted to them, since they were born after Delta stopped circulating. **@ryhisner points out that there is a small portion of this genome that also is from a JN.1**

**Putative query for Delta** : G434A, A3709G, C5654G (edited)
**Putative query for Coinfections/Artifacts**: **C888T, G5463T, C8344T** (edited)

EPI_ISL_19508880
EPI_ISL_19508877
EPI_ISL_19497020
These 3 sequences come from 3 separate patients based on metadata, and all partially contain the genome from EPI_ISL_19508878. They also all partially contain JN.1* genome. They are dissimilar to one another, and from my brief analysis don't appear likely to be legitimate recombinants. **Is it possible that these represent co-infections in separate patients?**
**@FedeGueli points out that the 880 and 877 sequence are actually pretty similar for the portions that aren't NNN**

Here is EPI_ISL_19508878, for convenience. 
nuc changes
>>	G210T, C241T, G434A, T514C, C835T, C888T, C1288T, C1912T, G2944A, C3037T, C3505T, A3709G, C3817T, G4181T, C5654G, C5979A, C6336T, C6402T, C6720T, G7037A, C7086T, C7124T, C7165T, C8344T, C8986T, G9053T, C10029T, C10156T, T10204C, C10969T, T11080G, A11201G, A11332G, G11365T, A11430G, A11474G, C11674T, C12501T, G12718T, C13019T, C14408T, T14440C, C14919T, G15451A, C16466T, C17550T, A19173C, C19220T, C19610T, A19945C, C21614T, C21618A, C21636T, C21648A, G21666T, A21794T, A21892T, C22079A, C22120T, G22203A, T22222C, T22325A, C22439T, A22559T, G22599C, T22662C, C22713T, A22805G, C22879G, G22898A, G22899A, T22917A, T22942G, A22991G, G22992A, A22994G, C22995A, A22996T, T23010C, G23012A, C23202T, C23280T, A23403G, C23604G, T23672C, C23859T, C24138A, A24369G, G24524A, A24813G, G24858A, G24893C, C25463T, C25469T, C25936G, G25993A, G26257A, T26297G, A26400G, T26491C, T26767C, C26895T, C26985A, C27807T, T27810C, A28271T, C28311T, C28807T, G28881T, G28916T, C29370T, G29402T

nuc	reversionsToRoot	
>> T27638T, C27752C, C27874C, A28461A, G29742G

ORF1ab	changes
>>	E57K, A208V, A1306S, L1797V, S1905Y, S2024L, P2046L, T2152I, G2258S, T2274I, P2287S, V2930L, T3255I, F3605L, T3646A, Y3722C, I3737V, T4079I, Q4151H, P4715L, F4726L, G5063S, P5401L, A6319V, T6449I, K6561Q

S	changes
>>	L18F, T19K, P25L, T29N, G35V, R78W, L110F, Q173K, R214H, S255T, L293F, T333S, R346T, V367A, P384L, T415A, N439K, G446N, L452Q, N460K, S477D, T478D, V483A, E484K, T547I, T573I, D614G, P681R, S704P, A766V, T859N, D936G, E988K, D1084G, G1099D, E1111Q

ORF3a	changes	
>>T24I, S26L, H182D, V201I  

E	changes	
>>V5I, L18R

M	changes	
>>I82T, H125Y, H155N

ORF7a	reversionsToRoot	
>> V82V, T120T

ORF7b	changes	
>> F19L

ORF7b	reversionsToRoot	
>> T40T

N	changes	
>>P13L, R203M, G215C, T366I, D377Y

N	reversionsToRoot	
>>D63D

![image](https://github.com/user-attachments/assets/64e6cba9-81f5-4836-b121-17d8a7dabdd9)

Tree (edited):
<img width="1150" alt="Screenshot 2024-10-28 alle 17 26 55" src="https://github.com/user-attachments/assets/ee489def-bd8f-43a7-8ead-468cb6083644">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5ccee_fba2a0.json?f_userOrOld=uploaded%20sample&label=id:node_11727344

Credit to @FedeGueli and @JosetteSchoenma who were the first to find these 4 sequences and understand them to contain Delta, to my knowledge.

**Comment by JosetteSchoenma** [comment]
Thanks @Sinickle 
EPI_ISL_14100331 , an AY.7 from Canary Islands (Tenerife/Spain) from 2021 has several not so common mutations in common with EPI_ISL_19508878. C5979A, G7037A and C7165T. The combination of those 3 is also a query that finds only these 2 samples.

**Comment by FedeGueli** [comment]
The initial query that i putatively found last week catches all the three sequences this is not good to me.
Query: C888T, G5463T, C8344T
I ve added it to the main proposal

cc @rambaut @corneliusroemer @angiehinrichs @theosanderson @jbloom

**Comment by FedeGueli** [comment]
For the spike sequences i would use 
EPI_ISL_19508880
that has less NNN




<img width="943" alt="Screenshot 2024-10-28 alle 17 21 26" src="https://github.com/user-attachments/assets/a258031d-3a80-4ab0-8333-a4c558e40a96">

**Comment by FedeGueli** [comment]
I ve added to the main proposal the Usher  tree: 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5ccee_fba2a0.json?f_userOrOld=uploaded%20sample&label=id:node_11727344
<img width="1129" alt="Screenshot 2024-10-28 alle 17 28 09" src="https://github.com/user-attachments/assets/36183003-cb3b-45bc-9327-18f5f0153b28">

**Comment by FedeGueli** [comment]
It has a new  N Glycan at S:T29N

**Comment by Sinickle** [comment]
> For the spike sequence i would use EPI_ISL_19508880 that has less NNN
> 
> <img alt="Screenshot 2024-10-28 alle 17 36 22" width="1024" src="https://private-user-images.githubusercontent.com/87669813/380804525-d26a1a77-70b0-43c0-adb6-a92d3b3fae89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzM3OTIsIm5iZiI6MTczMDEzMzQ5MiwicGF0aCI6Ii84NzY2OTgxMy8zODA4MDQ1MjUtZDI2YTFhNzctNzBiMC00M2MwLWFkYjYtYTkyZDNiM2ZhZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE2MzgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkN2QyNWFiOTRiMzA5YTU3MmQyYTk0NzUyYzdmNGUwYmQ0OWVjOWZkNDczZjdlNGY5OTg4MzBmOTEyODY0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dx7gMYmXDN41j8SrB5RJ6hwxgLBSOEgvPuKBO7HHPbU"> (now edited to compare it to WT)

EPI_ISL_19508880 is largely displaying a KP.3* spike though. 
Are there NNNs in EPI_ISL_19508878 aside from 675-683?

**Comment by FedeGueli** [comment]
> 
> EPI_ISL_19508880 is largely displaying a KP.3* spike though. Are there NNNs in EPI_ISL_19508878 aside from 675-683?

Yeah! also i noticed the only sequence (19497020) keeping 655Y 754K is the one with a large gap in-between
 Here compared to WT
<img width="552" alt="Screenshot 2024-10-28 alle 17 50 26" src="https://github.com/user-attachments/assets/9e05dcf0-c36e-4dec-a6d1-8ad71562d5ac">

**Comment by FedeGueli** [comment]
> EDIT: To be clear, my theory/understanding is that only EPI_ISL_19508878 contains a real and potentially transmitting genome. The other 3 sequences partially contain this sequence's genome, but are not genuine recombinant sequences.

Why do you think so? if you compare to WT they are all credible in my view with the least credible being the one found by me last week (...7020) but if you look at collection dates it is not the first collected.

**Comment by FedeGueli** [comment]
<img width="540" alt="Screenshot 2024-10-28 alle 17 54 45" src="https://github.com/user-attachments/assets/c130f734-5614-4bae-8f1e-b27c9331f157">
Look at Orf1a : differences are in or close to NNN

**Comment by FedeGueli** [comment]
<img width="653" alt="Screenshot 2024-10-28 alle 17 56 11" src="https://github.com/user-attachments/assets/8e82295b-37d4-45dd-8b85-b5b3abf54b06"> cc @ryhisner did u see this pattern before?

**Comment by FedeGueli** [comment]
@Sinickle there is a typo in the S mutations listed i have S:l452W in all of them  on Usher, Gisaid and Nextclade: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5ccee_fba2a0.json?c=gt-S_452&f_userOrOld=uploaded%20sample&gmax=25384&gmin=21563&label=id:node_11727344

**Comment by FedeGueli** [comment]
@silcn @shay671 @oobb45729 help needed here

**Comment by FedeGueli** [comment]
Wait guys there are 7 seqs with G5463T,  uploaded by Asturias Spain in two batches let me check them

**Comment by ryhisner** [comment]
I think there's a very high chance that only one of these sequences is real—and I would guess that the Omicron parts of the Delta sequence (from at least early-mid ORF7a to N:63 + the 3' UTR) are contamination as well. Sequences from this lab have historically been full of artifacts—false reversions, dropout, misread deletions, frameshifts, false insertions, etc.

Want to add that there are also three spike deletions as well: ∆Y144, ∆211-212, and ∆243-244. The Delta ∆156-157 deletion was allegedly "lost", but I would be anything this is an artifact. There's no sign of recombination elsewhere in spike in this sequence.

Wildest part is these back-to-back 2-nuc mutations: S477D + K478D. I can't recall ever seeing two negative-charge AA in the RBD like that before. I would guess there's a decent chance it's involved in some sort of alternative cell entry, similar to E484D. 
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/3706f757-2f83-40de-ac12-5f8e0054a05d">

**Comment by FedeGueli** [comment]
> I think there's a very high chance that only one of these sequences is real—and I would guess that the Omicron parts of the Delta sequence (from at least early-mid ORF7a to N:63 + the 3' UTR) are contamination as well. Sequences from this lab have historically been full of artifacts—false reversions, dropout, misread deletions, frameshifts, false insertions, etc.
 
I don't get why this should be an artifact it could be but there is no clear sign of being that way. The three most recent deltacrons we know have been all very complex ones, i would not be surprised if this turns out to be real . Especially in the three sequences putatively recombinant or coinfections which would be the signs to be not real?

**Comment by FedeGueli** [comment]
One argument that points to artifact so no coinfection is that there is. private combo  C8986T,C9344T that has been in Ay.103 in the past as XEC or Kp.3.1.1 , it would be weird to have a third lineage at play.

**Comment by xz-keg** [comment]
this was first detected by @FedeGueli in #2086

**Comment by FedeGueli** [comment]
> this was first detected

yes it is mentioned  i hide this

**Comment by FedeGueli** [comment]
> One argument that points to artifact (so no coinfection) is that there is in EPI_ISL_19508880 a private combo C8986T,C9344T that has been in Ay.103 in the past as XEC or Kp.3.1.1 , it would be weird to have a third lineage at play.

scratch this @JosetteSchoenma reanalyzed this and it is not this way.

**Comment by JosetteSchoenma** [comment]
> > One argument that points to artifact (so no coinfection) is that there is in EPI_ISL_19508880 a private combo C8986T,C9344T that has been in Ay.103 in the past as XEC or Kp.3.1.1 , it would be weird to have a third lineage at play.
> 
> scratch this @JosetteSchoenma reanalyzed this and it is not this way.

Yes. C8986T is in around 90% of Delta and in the AY.7 from Canary Islands from 2021 that I think is closely related to the recent AY.7. Plus, C9344T is in almost all KP.3.1, so it is not unlikely for them to be joined in a coinfection. The table is work in progress!

[Screenshot_20241029_103456_Photos.jpg](https://github.com/user-attachments/assets/2508c3f7-6733-4d55-b690-1261b6fe5201)

**Comment by FedeGueli** [comment]
I have added a temporary query for the Delta : G434A, A3709G, C5654G

**Comment by DailyCovidCases** [comment]
Dead please close it
