### ISSUE TITLE
JN.1.67.1 / XDV.1.9.1 recombinant (2, CN-AH 1, DE-BY 1)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2193]
Mutations based on JN.1: **G1126A**, _G4162A_, C6751T, G10610T, C17802T, **G18169T**, C19402T, _del21650-21655*, T21656A*, G22865T, T22930A_, C23707T, _T28297C, A28958Crev_
\* T21656A only appears in the German sequence, and it has no coverage until 21654, and 21654~21655CT are same as 21648-21649 which means this sequence could have del21650-21655 already known occurring in XDV.1.9.1. And the Chinese sequence has no coverage on 21607-21666.

Breakpoint: 19326~21650
G1126A and G18169T are from JN.1.67.1> G1126A> C28054T> G18169T, 2 sequences in Heilongjiang and Jilin.

07-22 Bayern, Germany EPI_ISL_19327202
08-?? Hefei, Anhui, China EPI_ISL_19512245

Usher placed it on a recombinant island with few reversions, so it's not caught by @xz-keg 's tool.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice65_genome_test_3954d_22fe20.json?c=country&label=id:node_7142254
![image](https://github.com/user-attachments/assets/164f5bb0-a395-4b0c-a6f0-6b61785334d6)

**Comment by Over-There-Is** [comment]
While Hefei locates in Eastern China and one of the donor locates in Northeastern China, it's believable that this recombinant originates in somewhere in Northern China without sequencing. label:"Emerged in an undersampled area" is needed.

**Comment by Over-There-Is** [comment]
To this recombinant, T28297C and A28958Crev are the only 2 mutations reserved from XBB*(or XDE). We could call it "Theseus' XBB*".

**Comment by Over-There-Is** [comment]
Query: G1126A, G18169T, G22865T

**Comment by FedeGueli** [comment]
> G1126A, G18169T, G22865T

old samples..

**Comment by DailyCovidCases** [comment]
Dead please close it @Over-There-Is
