### ISSUE TITLE
Suggestion to use SGTF as base for BA.2.86 seqs to handle S:68 mutations

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2194]
@AngieHinrichs, @corneliusroemer  recently there appears some S:68 mutations. The S:I68F one on XEC is growing rapidly, and @FedeGueli and @JosetteSchoenma also found some S:I68T/ S:I68V branches. 

However, such mutations are nearly always read as S:68-69 deletion plus S:V70X, and then ignored by usher due to treating it as artefact. 

Given XEC+S:I68F is likely the fastest branch currently, it seems necessary to handle this problem. 

To handle it, SGTF shall be used as base for BA.2.86* seqs and any potential 2-spike deletions around it shall be fixed to position S:69 and S:70.

**Comment by Mydtlwn** [comment]
Agreed, especially regarding the potential emergence of S:I68N and S:G72S. Although it's uncertain whether they will occur, we should remain vigilant.

**Comment by AngieHinrichs** [comment]
@xz-keg can you list some example sequence names so I can take a closer look?  Thanks.

**Comment by xz-keg** [comment]
> @xz-keg can you list some example sequence names so I can take a closer look? Thanks.

Sure.
I68F:

EPI_ISL_19448045, EPI_ISL_19461262, EPI_ISL_19463812,
EPI_ISL_19465899, EPI_ISL_19468782-19468783, EPI_ISL_19468919,
EPI_ISL_19472791, EPI_ISL_19472826, EPI_ISL_19472838,
EPI_ISL_19478490, EPI_ISL_19478951, EPI_ISL_19484071,
EPI_ISL_19487250, EPI_ISL_19487252, EPI_ISL_19487297,
EPI_ISL_19487348, EPI_ISL_19487380, EPI_ISL_19487957,
EPI_ISL_19497209, EPI_ISL_19501853, EPI_ISL_19505233,
EPI_ISL_19507701, EPI_ISL_19516608, EPI_ISL_19516618,
EPI_ISL_19517750, EPI_ISL_19520687, EPI_ISL_19521094,
EPI_ISL_19523210

I68T:
EPI_ISL_19424914, EPI_ISL_19483951, EPI_ISL_19516667,

I68V:
EPI_ISL_19512724

**Comment by AngieHinrichs** [comment]
Thanks @xz-keg.

> I68F
> EPI_ISL_19448045, ...

nextclade aligns these as S:I68-,S:H69- with substitution S:V70F (nt deletion 21764-21769, subst G21770T).  Unfortunately the deletion range masked for BA.2.85 is 21765-21770 which masks that substitution.  Now that I am using nextclade to align sequences for UShER, I will change the masked range to 21764-21769, remove those sequences and add them back.


> I68T:
> EPI_ISL_19424914, EPI_ISL_19483951, EPI_ISL_19516667,

nextclade aligns this as S:I68-,S:H69- with substitution S:V70T (nt deletion 21765-21770, substitution T21771C).  Since the tree doesn't know about deletions it is showing T21771C as S:V70A, but it does put those three sequences together on a branch with T21771C.


> I68V:
> EPI_ISL_19512724

nextclade aligns this as a deletion of two amino acids, S:I68-,S:H69-, with no substitutions (nt deletion 21764-21769).  If some other source is showing a substitution then it might be an issue of deletion boundaries / not being codon-aware?

**Comment by AngieHinrichs** [comment]
> I will change the masked range to 21764-21769

On second thought, just sliding the masked range left to start at 21764 is not right because the deletion by itself does not slide left (it could slide one base to the right).  I will just unmask 21770 going forward, changing the masked range to 21765-21769, and trust nextclade.

**Comment by xz-keg** [comment]
> Thanks @xz-keg.
> 
> > I68F
> > EPI_ISL_19448045, ...
> 
> nextclade aligns these as S:I68-,S:H69- with substitution S:V70F (nt deletion 21764-21769, subst G21770T). Unfortunately the deletion range masked for BA.2.85 is 21765-21770 which masks that substitution. Now that I am using nextclade to align sequences for UShER, I will change the masked range to 21764-21769, remove those sequences and add them back.
> 
> > I68T:
> > EPI_ISL_19424914, EPI_ISL_19483951, EPI_ISL_19516667,
> 
> nextclade aligns this as S:I68-,S:H69- with substitution S:V70T (nt deletion 21765-21770, substitution T21771C). Since the tree doesn't know about deletions it is showing T21771C as S:V70A, but it does put those three sequences together on a branch with T21771C.
> 
> > I68V:
> > EPI_ISL_19512724
> 
> nextclade aligns this as a deletion of two amino acids, S:I68-,S:H69-, with no substitutions (nt deletion 21764-21769). If some other source is showing a substitution then it might be an issue of deletion boundaries / not being codon-aware?

All of them shall have S:68 mutations and S:69del. S:70del in reality. They start from SGTF and physically it is very unlikely for them to get S:70 back and delete S:68 instead. These mutations shall happen on S:68.
