### ISSUE TITLE
LB.1.3 subbranch with S:N185del, F186I and Orf1a:P4197S on Orf6:T10I branch(55, 4 countries in Americas)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2197]
LB.1.3> G25947A, C27230T(Orf6:T10I)> C12854T(Orf1a:P4197S)> T5734C, T15003C, C25276T> del22116-22118(S:N185del, F186I)

Query: T5734C, T15003C, C25276T, del22115
Alternative query: T5734C, T15003C, C25276T, -A4675G, -C13694T
Query for dropout sequences:
T3565C, -T5734C, T15003C, C25276T(2)
A264G, T5734C, T15003C, -C25276T(1)

Earliest sequence: 06-03 Sacramento, California, USA EPI_ISL_19308324
Latest sequence: 09-16 New York, USA EPI_ISL_19452706
Regions detected: US 46(1 from El Salvador, 2 not on GISAID), Brazil 1, Costa Rica 1, El Salvador 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4c42b_6921f0.json?c=country&gt=nuc.13694C,4675A&label=id:node_7384725
![image](https://github.com/user-attachments/assets/6cbcfa68-63fb-4ed0-bf6e-7209c38ac38a)

Sequences:
EPI_ISL_19212265, EPI_ISL_19269006, EPI_ISL_19304250,
EPI_ISL_19304269, EPI_ISL_19304279-19304280, EPI_ISL_19304399,
EPI_ISL_19304405, EPI_ISL_19308324, EPI_ISL_19313876,
EPI_ISL_19316669, EPI_ISL_19319437, EPI_ISL_19324546,
EPI_ISL_19332468, EPI_ISL_19335157, EPI_ISL_19346319,
EPI_ISL_19347685, EPI_ISL_19369502, EPI_ISL_19371859,
EPI_ISL_19373859, EPI_ISL_19378655, EPI_ISL_19383931,
EPI_ISL_19390233, EPI_ISL_19391200, EPI_ISL_19405308,
EPI_ISL_19408462, EPI_ISL_19420229, EPI_ISL_19422984,
EPI_ISL_19423616, EPI_ISL_19425037, EPI_ISL_19425041,
EPI_ISL_19428357, EPI_ISL_19428413, EPI_ISL_19428417,
EPI_ISL_19429448, EPI_ISL_19434476, EPI_ISL_19439451,
EPI_ISL_19452706, EPI_ISL_19471366, EPI_ISL_19474025,
EPI_ISL_19474034, EPI_ISL_19493280, EPI_ISL_19497851,
EPI_ISL_19503260, EPI_ISL_19503437, EPI_ISL_19517213,
EPI_ISL_19517234, PQ040693.1, PQ041066.1

**Comment by FedeGueli** [comment]
Thx for highlighting this , i tracked this back in September in the chats too but to me it is dying off.

**Comment by FedeGueli** [comment]
No recent one closing it
