### ISSUE TITLE
MC.22 + S:A435S with S:C1235F and Orf9b:R32L  (12, 5 places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2201]
MC.22 [KP.3.1.1 > C11020T] >> T16224C, S:A435S (G22865T), S:C1235F (C23929T),G25266T, ORF9b:R32L (G28378T)

Query: C11020T, G22865T, C23929T
 
Samples: 12 
Places: 5 Ireland , France, Canada, Us , Wales
First collected in Illinois on 2024-08-26

Tree:
<img width="1172" alt="Screenshot 2024-11-05 alle 01 10 01" src="https://github.com/user-attachments/assets/3d7266be-787f-42f8-a4da-65aa34503767">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_13245_95d120.json?c=userOrOld&label=id:node_7246097

**Comment by FedeGueli** [comment]
Parent designated MC.22

**Comment by FedeGueli** [comment]
no new sequences

**Comment by xz-keg** [comment]
This one designated MC.28.1, it seems the C11020T is independent?

**Comment by Over-There-Is** [comment]
cov-lineages/pango-designation@16205e7
