### ISSUE TITLE
 KS.1.1.2/JN.1.11.1.X (likely KP.3.1.1) recombinant  with a 4AA mini saltation (16, Ontario)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2203]
This recombinant  seems quite interesting to me because appears, beyond having 22N+59S, to be a mini saltation branch (3/4 AA changes not inherited by donors , apparently).
It involves KS.1.1 and JN.1.11.X (not KP.1,KP.2.2 and other excluded by missing mutations)  and it is placed in a branch appearing in the same tree of XEL at the bottom of it , but separate from it:
<img width="1168" alt="Screenshot 2024-11-05 alle 17 04 06" src="https://github.com/user-attachments/assets/ff1e4337-ec5a-4e0f-9ca6-8feb0fd043dd">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_37d72_a3d8b0.json?label=id:node_7216150
 

### Donors [_Thx to @xz-keg help in identifying them_]: 
**5'End:**
Orf1ab + S1 + S" until S:1086 from **KS.1.1.2** with **C2113T, Orf1b:A1662V (C18452T)** inheriting **Orf1a:L2146F, Orf1b:A1662V S:T22N S:F59S** and **Flirt** ) 
**3'End**
From S:1086 to 3'end one **KP*** (not being KP.1*) inheriting **S:V1104L**  [likely **KP.3.1.1 + ORF3a:V13L** or less likey KP.3.1.1 + Orf9b:M8I/N:A12T]

### Private mutations: 
C1684T, C4540T, **ORF1b:T1139A** (A16882G), A17406G,  **Orf1b:L2017F** (G19518T), **ORF3a:V13L** (G25429T) [?PVT?],  **Orf9b:M8I / N:A12T** (G28307A)   [?PVT?]

**Query**: C18452T, G19518T,T3565C
**Samples**: 15
**Places:** 1,  Ontario- Canada

No sign of MOV use.
<img width="1166" alt="Screenshot 2024-11-05 alle 17 20 12" src="https://github.com/user-attachments/assets/b4f8d1ba-83a8-425a-8c45-1beb544b8d05">

### Mutational recap:
<img width="539" alt="Screenshot 2024-11-06 alle 09 43 33" src="https://user-images.githubusercontent.com/87669813/383472045-efc94f59-18f6-41ae-9405-b28204e75dc4.png">

_Originally posted by @FedeGueli in https://github.com/sars-cov-2-variants/lineage-proposals/issues/2086#issuecomment-2457619416_

**Comment by xz-keg** [comment]
C2113T, C18452T from a KS.1.1.2 branch.

one of G25429T,G28307A from KP.x

others are private mutations

**Comment by FedeGueli** [comment]
> C2113T, C18452T from a KS.1.1.2 branch.
> 
> one of G25429T,G28307A from KP.x
> 
> others are private mutations

Thank you very much for these findings and your help, i have added to the main proposal , i think KP.3.1.1 + orf3a_V13L could be the potential donor)

**Comment by Memorablea** [comment]
By the way, China-Hubei found KS.1.1.2/KP.3.3.1 recombinant.GISAID said it is XEC becuase its breakpoint highly like XEC.

**Comment by Memorablea** [comment]
> By the way, China-Hubei found KS.1.1.2/KP.3.3.1 recombinant.GISAID said it is XEC becuase its breakpoint highly like XEC.

EPI_ISL_19529646

**Comment by Over-There-Is** [comment]
> By the way, China-Hubei found KS.1.1.2/KP.3.3.1 recombinant.GISAID said it is XEC becuase its breakpoint highly like XEC.

It's already here: https://github.com/cov-lineages/pango-designation/issues/2717#issuecomment-2460777213
