### ISSUE TITLE
Usher separation of MK.1 to two branches.

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2205]
![image](https://github.com/user-attachments/assets/98c1b28b-9022-4ea7-aa2c-17ac648f7ac8)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice38_genome_test_58193_daf1b0.json
@AngieHinrichs, it seems that MK.1 has been separated to two branches in the recent build due to some seqs having C4795T but not S:S31F. C4795T is known to be quite convergent so that could just be convergent mutation. Maybe deserve some fix.

**Comment by AngieHinrichs** [comment]
I see, I will try to fix that in the next round of fixes.

**Comment by AngieHinrichs** [comment]
I believe this was fixed in the 2024-11-19 tree.
