### ISSUE TITLE
MC.16+S:F65S(77 seqs, 10 places around 15% in Chile)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2207]
MC.16+A23416T+C7639T+A11782G, T21756C(S:F65S)

GISAID query: T21756C ,A11782G,T3565C(by @FedeGueli )
No. of seqs: 7(Chile 6 Australia 1)

First: EPI_ISL_19390750, Chile, 2024-8-29
Latest: EPI_ISL_19530786, Australia, 2024-10-13

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice14_genome_test_1424_dc72b0.json?label=id:node_5742985)
![image](https://github.com/user-attachments/assets/68e4c16f-f201-4d8a-b4e9-652c025922cc)

**Comment by FedeGueli** [comment]
good catch thx

**Comment by FedeGueli** [comment]
> good catch thx

Turned out i was tracking this one too with T21756C  ,A11782G,T3565C that gives 8 cc @xz-keg

**Comment by Over-There-Is** [comment]
23 now

**Comment by xz-keg** [comment]
also in Spain. 
It seems distributed in 7 different regions of Chile

**Comment by FedeGueli** [comment]
+1 Spain

**Comment by xz-keg** [comment]
+1 USA-OH

**Comment by FedeGueli** [comment]
to be proposed please

**Comment by FedeGueli** [comment]
@xz-keg please propose it it seems faster than XEC and it is from 10 different regions in Chile

**Comment by FedeGueli** [comment]
110 seqs but prevalence down to 4% in CHile

**Comment by FedeGueli** [comment]
+1 Jap

**Comment by FedeGueli** [comment]
121 still around in Chile , low levels
