### ISSUE TITLE
KP.3.3 with S:F201L and S:F565S in Japan (10)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2208]
Likely just a cluster (looking at ages of patients), but with two unusual spike mutations 8both with less than 500seqs all pandemic long) better to track it for a while

Defining mutations: KP.3.3 >>  C5221T > N:T366I (C29370T) > orf1a:K3353R (A10323G) > G20670A, S:F201L (T22163C), S:F565S (T23256C)
Query: T22163C, T23256C
Samples: 10
Places: Tokyo
First sample: 2024-10-01
Tree:
<img width="1165" alt="Screenshot 2024-11-09 alle 12 42 39" src="https://github.com/user-attachments/assets/afdab2e7-9b6a-472d-9f42-7b81c5d37d53">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_510a3_f49480.json?label=id:node_7330276

**Comment by DailyCovidCases** [comment]
Please close this issue @FedeGueli
