### ISSUE TITLE
FU.1 + A460G, ORF1b:V2082I and ORF3a:S60F 11 seq. in NYC

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#221]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1d3b656f-03ff-480d-ba20-4f7fd6f5796c)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/d270874e-65eb-44f7-9b5f-9b3b47c8a27f)
tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28376_d8290.json?c=gt-nuc_25571&label=id:node_6577687
first seq: 2023-06-04
Most recent: 2023-06-12
query: G19711A, A460G, C25571T
EPI_ISL_17810219 EPI_ISL_17810186 EPI_ISL_17810194 EPI_ISL_17810221 EPI_ISL_17810193 EPI_ISL_17783110 EPI_ISL_17810188 EPI_ISL_17810195

**Comment by FedeGueli** [comment]
Why do you think this one will be relevant?

**Comment by FedeGueli** [comment]
still 11 . closing it for now
