### ISSUE TITLE
MC.13+S:A435S buried in a Flip-flop branch(13 seqs, 9 places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2210]
There seems to be an MC.13+S:A435S branch mostly buried inside a flip-flop branch.  @AngieHinrichs
MC.13+G22865T(S:A435S)

GISAID query: C10681T,G22865T,-25006
No. of seqs: 13(Germany 3 Belgium 1 Netherlands 3 Australia 1 USA 2(NC,OH), UK 1 Brazil 1 Ireland 1)

First: EPI_ISL_19453273, Belgium, 2024-8-12
Latest: EPI_ISL_19530816, Australia, 2024-10-23

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_317b3_1b22b0.json?label=id:node_5751026)
![image](https://github.com/user-attachments/assets/ce23d9e7-a63c-49a0-bb40-5d2f99fc9d73)

**Comment by FedeGueli** [comment]
Designated MC.13.1 via https://github.com/cov-lineages/pango-designation/commit/dc17e540887751f51bab8e761dc223fe01657467

**Comment by FedeGueli** [comment]
MC.13.2 has at least 4 branches with S:R346T now:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_1692a5_197830.json?c=gt-S_346&label=id:node_7281723
<img width="1179" alt="Image" src="https://github.com/user-attachments/assets/7391b4da-4bd5-4a24-87c7-b6b25232cc91" />

Br.1 
MC.13.2 >> T18159C > ORF1a:T1638I (C5178T), ORF1a:K2511N (G7798T), S:R346T (G22599C)
Query: G7798T ,C5178T, G22599C
Samples: 9 US

Br.2
MC.13.2.1 > ORF1a:S723F (C2433T) > S:R346T (G22599C)
Query:C2433T, G22599C,C24863T,T3565C
Samples: 6 US

Br.3
MC.13.2 > G28942A > S:R346T (G22599C)
Query:G28942A, G22599C, C10681T
Samples: 7 Europe

cc @xz-keg
