### ISSUE TITLE
NC.1 (KS.1.1.1.1) got 445P in Scotland and it is growing (5)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2212]
NC.1 >> C4093T, C11095T , C14931T, (C22498T), S:H445P (A22896C), C27002T
Query: C11095T , C14931T, C27002T
Samples: 2 on Gisaid  5 on Usher all from Scotland
Tree (Misplaced as KS.1.1.1 was already):
<img width="1164" alt="Screenshot 2024-11-12 alle 11 24 48" src="https://github.com/user-attachments/assets/ec7fe4bb-290c-4623-85c1-5ae006d97d03">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_428d4_3294f0.json?label=id:node_7174142

**Comment by FedeGueli** [comment]
Designated NC.1.2 via https://github.com/cov-lineages/pango-designation/commit/dd477c4a513dacccb7e6bce6b761dc88c632d1c0#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1219

**Comment by DailyCovidCases** [comment]
Please close this issue @FedeGueli

**Comment by FedeGueli** [comment]
<img width="1127" alt="Screenshot 2024-12-14 alle 16 44 25" src="https://github.com/user-attachments/assets/c52acc5f-681c-49c5-8db4-9332018a5f61" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_29532_da60b0.json?label=id:node_7179019

NC.1.2 tree has changed
New query for it: 22896C,C11095T,C21627A

cc @xz-keg

**Comment by Over-There-Is** [comment]
+1
