### ISSUE TITLE
LF.7.1 + S:S704L, ORF1a:P4120L, ORF1b:M2381T (18 in Canada)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2216]
![image](https://github.com/user-attachments/assets/5470aba2-f72b-4a08-8178-e7e73b9d2e59)
Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_429be_6041d0.json?f_userOrOld=uploaded%20sample

First Seq: 2024-10-23
Most Recent: 2024-11-06

Gisiad: T9643A, C12624T, T20609C

EPI_ISL_19538122 EPI_ISL_19524206 EPI_ISL_19538655 EPI_ISL_19538424 EPI_ISL_19538498 EPI_ISL_19538134 EPI_ISL_19538151 EPI_ISL_19538158 EPI_ISL_19538748 EPI_ISL_19538509 EPI_ISL_19538143 EPI_ISL_19523830 EPI_ISL_19524136

**Comment by FedeGueli** [comment]
it was a cluster

**Comment by FedeGueli** [comment]
there is another LF.7.1+ 704L in IL query: C829T, C5144T, C23673T,T3565C finds 4.

**Comment by FedeGueli** [comment]
> there is [another LF.7.1+ 704L](https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_3ee442_d3410.json?label=id:node_11871647) in IL query: C829T, C5144T, C23673T,T3565C finds 4.
 this is now 7 mostly IL
