### ISSUE TITLE
Russia nearly-dominant S31P,F456L,R346T id'd as JN.1.40 by GISAID

### ISSUE THREAD

**Issue by MCB6** [sars-cov-2-variants/lineage-proposals#2217]
The recent upload from Russia shows a rise of a S31P,F456L,R346T strain from the first observations in August to the verge of dominance in late October.
GISAID identifies it as JN.1.40 but it doesn't have F58Y, and it DOES have the FLiRT duo. It may have been designated already, but I what is it and why is it labeled JN.1.40?
![image](https://github.com/user-attachments/assets/49f46275-ec90-4820-80a3-fa6c989076f7)
![image](https://github.com/user-attachments/assets/e32aa077-e424-4428-b18d-b230a67a71f6)

**Comment by MCB6** [comment]
Ahh, I see that it's dominant in Qatar where GISAID also calls it JN.1.40, but it appears to actually be LF.7...

**Comment by xz-keg** [comment]
There‘s always such things by GISAID system, it doesn't update very frequently according to the most recent designations.

**Comment by MCB6** [comment]
Still dominant in Qatar, also reached dominance in Kazakhstan, and grows appreciably in Israel, Europe, and the US
![image](https://github.com/user-attachments/assets/38900823-b80e-421d-acf5-f29356a09d7f)
