### ISSUE TITLE
KP.2.6 got 493E ( 2, Canada, Israel)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2219]
KP.2.6 reached the small group of linegaes that acquired S:Q493E, it is the first time we will see with mew N30 Glycan reached through S:F32Del 

KP.2.6 >> T13521C > C2947T, S:Q493E (C23039G), A24778G,  ORF7b:L25F (C27828T)  y:
Query: T13521C , C2947T,T3565C
Samples: 2
First: Israel , 2024-09-29
Last: New Brunswick Canada , 2024-10-24
Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_36bb8_6828b0.json?c=userOrOld&label=id:node_7390042
<img width="1167" alt="Screenshot 2024-11-15 alle 00 15 04" src="https://github.com/user-attachments/assets/5bf14d35-510e-4732-bc4e-93172632d992">

**Comment by DailyCovidCases** [comment]
@FedeGueli Dead please close it
