### ISSUE TITLE
EG.5.1 diverse lineage growing quickly in arizona starting from orf1a:R542C (113 seqs, of which 24 from asu outbreak with n_s193n)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#222]
Query: C22570T, C1889T, G21718T, T22930A
With this query you find 31, but if you use eg.5.1 and c1889t you find 35. Probably some bad samples.

Lots of diversity and interesting mutations in this one:
![Screenshot_20230620_162436_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/3345a4ac-0c34-41ac-a273-7e4ea05c44ef)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_23ef5_1b5a50.json?label=id:node_6618907&showBranchLabels=all

Note the n:s193n branch (also has orf1b:685y but doesnt show up/get sorted in usher) and within that a s:478r singlet. The orf1b:685y branch seems to be growing even quicker in arizona, but small numbers still (EDIT: orf1a:685y is overrepresented in arizona, likely artefact. The branch growing quicker should be represented by n:s193n and orf8:v49i)

**Comment by FedeGueli** [comment]
i was looking at this too just now!

**Comment by BorisUitham** [comment]
Nice, great minds think alike ;)

Also the 484v 475v singlet i also think is interesting. Both mutations individually have proven in the past to be able to at least somewhat circulate to a peak of 1.5% in latvia and canada respectively

**Comment by FedeGueli** [comment]
Looking at collection42 updated by @alurqu it seems faster than the recently designated EG.5.1.1 , lets wait this week to see if it slows down or goes on spreading also outside AZ.

**Comment by MCB6** [comment]
The whole EG.5.1 business in Maricopa County AZ seems to be a campus outbreak at the ASU which didn't spill into the community at this point. Only two labs sequence local Covid specimens, Efrem Lim's lab at the ASU and the state PHL. They have essentially the same output and turnaround time (77 samples each since mid-May, with the most recent samples obtained around June 10). But out of 20 EG.5.1 instances of EG.5.1, only two came from AZPHL, and the rest from Lim's ASU lab.

**Comment by FedeGueli** [comment]
Thank you for clarifying this @mc86  . So this should explain its growth advantage over its sibling. Likely it will spill the same in the community.

**Comment by BorisUitham** [comment]
Added C22570T to remove 4 seqs that are unrelated to this branch: new query C22570T, C1889T, G21718T, T22930A

**Comment by BorisUitham** [comment]
Designated EG.5.1.3

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/90d48d5b9ce3ff81bbb7efcd83b3a3903a7ca001
