### ISSUE TITLE
KP.3.1.1+Orf1b:S2198I+S:M153V with 19722 reverted (45 seqs, 5 places)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2224]
This branch seems interesting that KP.3.1.1 have the KP.3.1 defining A19722G reverted. I don't find clue for recombination and the branch keeps the del21653_21655 near the A19722G reversion. Likely a real reversion and S:M153V is got afterwards

KP.3.1.1+T10738C+G19722A(rev)+G20060T(Orf1a:S2198I)+A22019G(S:M153V)
No. of seqs: 28(USA 3(SC, GBW from UK), UK 25(Scotland, Wales, England))
Query: T10738C,G20060T,A22019G (edited)

First: EPI_ISL_19447708, Wales, 2024-9-16
Latest: EPI_ISL_19546514, GBW from UK, 2024-11-5

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice14_genome_test_1d2dd_9d59c0.json?label=id:node_5797048)
![image](https://github.com/user-attachments/assets/21ceb387-5324-48c1-b50f-54b4cc88063f)

**Comment by FedeGueli** [comment]
Thank you , please add the query i think it was highlighted in the groups, it should be a cluster

**Comment by FedeGueli** [comment]
<img width="1184" alt="Screenshot 2024-11-19 alle 01 12 46" src="https://github.com/user-attachments/assets/59bcd24c-fe63-4410-875b-3d4b5dffe659">
Not sure if already noticed but EPI_ISL_19541530 in the middle of the tree has 1104L and 1143L reverted 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_63d87_bd6ed0.json?c=userOrOld&label=id:node_11760070&s=hCoV-19/USA/SC-CDC-LC1125094/2024%7CEPI_ISL_19541530%7C2024-11-02

**Comment by FedeGueli** [comment]
34 Wales

**Comment by FedeGueli** [comment]
39 France

**Comment by FedeGueli** [comment]
45 but still a Welsh cluster closing it
