### ISSUE TITLE
MC.13 with S:L335F got also S:E281V in Sovenia (6)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2225]
MC.13 >> ORF1a:K419R (A1521G) > S:L335F (G22567T) > ORF1a:G353S (G1322A), Orf1a::G603S (G2072A), Orf1a:G706C (G2381T),Orf1b:G2489D ( G20933A), S:E281V (A22404T), G27708A
Query:G1322A,G2072A,G2381T
Samples: 5
Places: 1 (Slovenia)

Tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_8fd9_b2e000.json?label=id:node_7327927
<img width="1167" alt="Screenshot 2024-11-18 alle 13 15 31" src="https://github.com/user-attachments/assets/40656529-cace-4cc3-a164-e9f93631f2bb">

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Adding new entries for the MC.13 recombinant lineage based on the provided criteria.

You can review changes in this commit: https://github.com/lattaai12/sars-cov-2-variants-lineage-proposals-2225/commit/9cc73a1f4f56043ff920860f9829fa95fb54f6ac.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by FedeGueli** [comment]
> Hello, I tried to solve the issue.
> 
> This is what I did:
> 
> Adding new entries for the MC.13 recombinant lineage based on the provided criteria.
> 
> You can review changes in this commit: [lattaai12@9cc73a1](https://github.com/lattaai12/sars-cov-2-variants-lineage-proposals-2225/commit/9cc73a1f4f56043ff920860f9829fa95fb54f6ac).
> 
> Caution
> 
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

cc @corneliusroemer AI doing something here.

**Comment by FedeGueli** [comment]
+1 Slovenia in a big batch from there likely slowing down

**Comment by FedeGueli** [comment]
not expanding

**Comment by Over-There-Is** [comment]
9
