### ISSUE TITLE
MC.9 + S:T22N and 4AA minisaltation (2 , Arizona, Iowa)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2227]
MC.9 > Orf1a:L454F (C1625T), ORF1a:C873Y (G2883A), C11779T, Orf1a:I4725L (A14437C), S:T22N (C21627A), N:P344L (C29304T)
Query: C1625T,G2883A, C11779T
Samples: 2 Arizona, Iowa
Tree:
<img width="1165" alt="Screenshot 2024-11-18 alle 14 43 46" src="https://github.com/user-attachments/assets/f2bfdc12-6285-4877-a49b-b330d66d77ef">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_5dfe5_b42e30.json?label=id:node_11759180

**Comment by DailyCovidCases** [comment]
@FedeGueli Dead please close it
