### ISSUE TITLE
ND.1.1+Orf1a:G572E,S:L176F(40 seqs, 7 places) and furthwer S:G184V (27)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2230]
ND.1.1+G1980A, G4951A,C22088T(Orf1a:G572E,S:L176F)

GISAID query: C22088T, C13436T, G1980A
No. of seqs: 32(Oman 1 USA 3(OH,NY,CO) UK 9(Wales, Scotland) Canada 19(ON))

First: EPI_ISL_19521859, Oman, 2024-8-7
Latest: EPI_ISL_19551732, Canada, 2024-11-11

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice30_genome_test_1e335_beddf0.json?label=id:node_5436134)
![image](https://github.com/user-attachments/assets/cf81cac8-9a07-43bb-b9bc-ead707b9a9a8)

**Comment by FedeGueli** [comment]
19 with also S:g184V

**Comment by Over-There-Is** [comment]
> 19 with also S:g184V

but didn't spread out of canada.

**Comment by FedeGueli** [comment]
40 now Ontario only with 27 with G184V

**Comment by xz-keg** [comment]
designated ND.1.1.1
