### ISSUE TITLE
KP.3.1.1+Orf1b:R1736K+S:R346T(26 seqs, 10 places, 14 with S:S929T, 9 with S:H445R)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2231]
KP.3.1.1+G18674A(Orf1b:R1736K)+C4423T+G22599C(S:R346T)

GISAID query:  G22599C,C12616T, G18674A,A13121T
GISAID query for S:S929T sub-branch:  G22599C,G18674A,G24348C
GISAID query for S:H445R sub-branch: G22599C,G18674A, T22896G
No. of seqs: 9(Chile 4(MA,VS) Brazil 4(SP,PR,RS,RJ), USA 1(GBW))

It seems distributed in South America, detected in 2 Chile regions and 4 Brazil regions. Other parts of South America don't upload seqs.

8 on GISAID, There is also a GBW-BBB seq that is not on GISAID .

First: EPI_ISL_19519476, Brazil-SP, 2024-8-27
Latest: EPI_ISL_19551069, Chile-MA, 2024-10-17

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice89_genome_test_1e900_bee220.json?label=id:node_5722803)

![image](https://github.com/user-attachments/assets/1febeec4-78bd-4407-885d-6fcfe7f75417)

**Comment by FedeGueli** [comment]
@xz-keg now under the main branch with S:S929T appeared a recent sequence from Canada with S:H445R 
Query: C9559T, C11020T, G17721T 
Samples: 1 Ontario
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice4_genome_test_5bf7_2e2460.json?label=id:node_7275276
<img width="1160" alt="Screenshot 2024-11-24 alle 09 26 28" src="https://github.com/user-attachments/assets/8f880663-b046-4309-8f6a-4bf0dcb2ac32">

**Comment by FedeGueli** [comment]
> @xz-keg now under the main branch with S:S929T appeared another branch consisting in one recent sequence from Canada with S:H445R Query: C9559T, C11020T, G17721T Samples: 1 Ontario 

2 now

**Comment by xz-keg** [comment]
Edit proposal to include the S:H445R branch.

**Comment by FedeGueli** [comment]
21 now with 13 with 929T after a batch from Chile

**Comment by Over-There-Is** [comment]
22

**Comment by xz-keg** [comment]
26, Brazil-GO,SC

**Comment by FedeGueli** [comment]
Please propose it this is likely as fast as XEC baseline

**Comment by DailyCovidCases** [comment]
> Please propose it this is likely as fast as XEC baseline

Waiting for about 30 seqs

**Comment by FedeGueli** [comment]
Designated 
MC.33 with 346T
MC.33.1 with 445R
MC.33.2 with S:929T
via https://github.com/cov-lineages/pango-designation/commit/514e3e32666e6b2934447759fcd58bd1042e8eee
