### ISSUE TITLE
KP.3.1.1 + S:A846G (C>G) (7 , Ontario)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2235]
It is quickly growing but it is just an Ontario cluster, having S:A846G (C>G) mutation i think it is worth to have it proposed here.

KP.3.1.1 > G7936T > T11347C > C20628T >ORF1a:T1854I ( C5826T = PLPro_T291I), A14412T, T22618C,S:A846G (C24099G), ORF8:K94R (A28174G)
Query: A14412T, T22618C, C24099G
Samples: 7
First : 2024-10-23
Places: Ontario  

Tree:
<img width="1151" alt="Screenshot 2024-11-19 alle 23 34 18" src="https://github.com/user-attachments/assets/f0acfd28-60ce-4644-80ef-112d149f8d0b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_62fdc_d10bf0.json?c=userOrOld&label=id:node_7298370

**Comment by DailyCovidCases** [comment]
@FedeGueli Dead please close it
