### ISSUE TITLE
KP.3.1.1 subbranch with S:T678I on Orf1a:A4285V branch(45; CA 43, 4 provinces; US 2, 2 states)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2245]
KP.3.1.1> C13119T(Orf1a:A4285V)> T24628C> C23595T(S:T678I)
Query: C7113T, C13119T, C23595T

Earliest sequence: 09-06 Alberta, Canada EPI_ISL_19441434
Latest sequence: 11-08 Ontario, Canada EPI_ISL_19552979
Regions detected: Canada 32(Alberta 16, Ontario 13, Québec 2, BC 1), US 2(Minnesota 1, Ohio 1)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_4c508_177a40.json?c=country&label=id:node_7274526
![2024-11-23 (8)](https://github.com/user-attachments/assets/5ba01c05-a79a-4b8b-9568-8b4d0efb8a22)

EPI_ISL_19441434, EPI_ISL_19460057, EPI_ISL_19460086,
EPI_ISL_19460112, EPI_ISL_19460221, EPI_ISL_19496657,
EPI_ISL_19496662, EPI_ISL_19496720, EPI_ISL_19501554,
EPI_ISL_19504151, EPI_ISL_19504155, EPI_ISL_19504159,
EPI_ISL_19504332, EPI_ISL_19514002, EPI_ISL_19523592,
EPI_ISL_19527452, EPI_ISL_19528647, EPI_ISL_19532530,
EPI_ISL_19537283, EPI_ISL_19537324, EPI_ISL_19538249,
EPI_ISL_19538358, EPI_ISL_19538456, EPI_ISL_19538694-19538695,
EPI_ISL_19545110, EPI_ISL_19548969, EPI_ISL_19551238,
EPI_ISL_19551242, EPI_ISL_19551248, EPI_ISL_19552979,
EPI_ISL_19558274, EPI_ISL_19558929, EPI_ISL_19560010,

**Comment by FedeGueli** [comment]
43 now all new ones from the Ontario cluster

**Comment by Over-There-Is** [comment]
BC+2

**Comment by FedeGueli** [comment]
Still only a cluster closing it
