### ISSUE TITLE
JN.1.67.1 subbranch with Orf9b:A75V(46, 8 countries, mainly in China)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2247]
JN.1.67.1> C28507T(Orf9b:A75V)
Query: G4162A, C8293T, C28507T

Earliest sequence: 04-22 JFK airport, New York, USA(from Maldives) EPI_ISL_19108798
Latest sequence: 09-22 Ziyang, Sichuan, China EPI_ISL_19558514
Regions detected: China 36(9 provinces, 1 not on GISAID), US 3(1 from Maldives), Japan 2, Singapore 1, Thailand 1, Netherlands 1, Russia 1, Sweden 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_5f4b0_1ac060.json?c=country&label=id:node_7187172
![image](https://github.com/user-attachments/assets/457ac719-9279-4d3b-9e2d-5dab7f416535)

Sequences:
EPI_ISL_19093720, EPI_ISL_19108798, EPI_ISL_19150621,
EPI_ISL_19180773, EPI_ISL_19183692, EPI_ISL_19194193,
EPI_ISL_19194339, EPI_ISL_19201268, EPI_ISL_19205411-19205412,
EPI_ISL_19212064, EPI_ISL_19269276, EPI_ISL_19297851,
EPI_ISL_19299338, EPI_ISL_19299373, EPI_ISL_19299434,
EPI_ISL_19299436, EPI_ISL_19303988, EPI_ISL_19312162,
EPI_ISL_19312168, EPI_ISL_19315038, EPI_ISL_19315236,
EPI_ISL_19325815, EPI_ISL_19330685, EPI_ISL_19363357,
EPI_ISL_19385005, EPI_ISL_19420615, EPI_ISL_19429287,
EPI_ISL_19429293, EPI_ISL_19443754, EPI_ISL_19475162,
EPI_ISL_19504624, EPI_ISL_19512191, EPI_ISL_19512235,
EPI_ISL_19512265, EPI_ISL_19545584, EPI_ISL_19545657,
EPI_ISL_19550237, EPI_ISL_19550272, EPI_ISL_19550309,
EPI_ISL_19550434, EPI_ISL_19558444, EPI_ISL_19558458,
EPI_ISL_19558487, EPI_ISL_19558514, PQ373562.1

**Comment by FedeGueli** [comment]
Thx apparently slow though

**Comment by FedeGueli** [comment]
dead
