### ISSUE TITLE
MJ.1 subbranch with S:R190S on Orf1a:H1738Y(8, Brazil, 3 states)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2248]
MJ.1> C5477T(Orf1a:H1738Y)> T9982C> G22132T(S:R190S)
Query: C5477T, G6473A, G22132T

Earliest sequence: 07-09 Alagoas, Brazil EPI_ISL_19471185
Latest sequence: 09-05 São Paulo, São Paulo, Brazil EPI_ISL_19519482
Regions detected: Brazil 8(Alagoas 3, Rio de Janeiro 3, São Paulo 2)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_49608_2313b0.json?c=country&label=id:node_6982194
![image](https://github.com/user-attachments/assets/cb68c8a5-0fab-4e5d-8cb0-7f02016face8)

Sequences:
EPI_ISL_19440847, EPI_ISL_19440865, EPI_ISL_19471179,
EPI_ISL_19471185, EPI_ISL_19471217, EPI_ISL_19519482,
EPI_ISL_19557050, EPI_ISL_19557070

**Comment by FedeGueli** [comment]
Apparently already gone

**Comment by FedeGueli** [comment]
dead
