### ISSUE TITLE
XDV.1 subbranch with S:C1250F on C25416T branch(30, 5 countries, mainly in CN-SC)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2250]
XDV.1> C25416T> C21928T, G25311T
Query: C21928T, G25311T, C25416T

Earliest sequence: 03-18 Panzhihua, Sichuan, China EPI_ISL_19234586
Latest sequence: 10-12 Queensland, Australia EPI_ISL_19516565
China 23(Sichuan 22, Anhui 1), Singapore 2, Australia 1, US 1(from Netherlands)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_3f96_25aca0.json?c=country&f_userOrOld=uploaded%20sample&label=id:node_7053787
![image](https://github.com/user-attachments/assets/88ecd8bf-afc3-41ad-a6aa-29b37529ec9b)

Sequences:
EPI_ISL_19134947, EPI_ISL_19134952, EPI_ISL_19205444,
EPI_ISL_19230026, EPI_ISL_19230195, EPI_ISL_19234537,
EPI_ISL_19234586, EPI_ISL_19234595, EPI_ISL_19234606,
EPI_ISL_19234612, EPI_ISL_19307583, EPI_ISL_19311829,
EPI_ISL_19311925, EPI_ISL_19512223, EPI_ISL_19516565,
EPI_ISL_19545625, EPI_ISL_19545659, EPI_ISL_19545661,
EPI_ISL_19550358, EPI_ISL_19550368, EPI_ISL_19550376,
EPI_ISL_19550381-19550382, EPI_ISL_19550462, EPI_ISL_19550476,
EPI_ISL_19550500, EPI_ISL_19550514

**Comment by FedeGueli** [comment]
Likely already dead but thx for spotting.

**Comment by FedeGueli** [comment]
30 but dead
