### ISSUE TITLE
KP.3.1.1 subbranch with S:R346K and ORF1a:T1678A(11 NL 8, SWE 3)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2253]
KP.3.1.1> A5297G(Orf1a:T1678A)> G22599A(S:R346K)
Query: A5297G, C12616T, G22599A

Earliest sequence: 09-11 Friesland, Netherlands EPI_ISL_19483984
Latest sequence: 11-07 Overijssel, Netherlands EPI_ISL_19563596
Regions detected: Netherlands 8(5 provinces), Sweden 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_389f3_58fcf0.json?c=country&label=id:node_7288597
![image](https://github.com/user-attachments/assets/ab9bc0d7-38ad-49c4-b6a4-4481377ed3f5)

Sequences:
EPI_ISL_19483984, EPI_ISL_19483992, EPI_ISL_19537419,
EPI_ISL_19562982, EPI_ISL_19562997, EPI_ISL_19563132,
EPI_ISL_19563364, EPI_ISL_19563497, EPI_ISL_19563596,

**Comment by FedeGueli** [comment]
+2 Sweden

**Comment by xz-keg** [comment]
no new seqs
