### ISSUE TITLE
Weird Things About Nucleotide Position description from nucleotide position 21987-22000

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#226]
I am making a new cov-specturm collection that attempt to summarize popular S mutations of XBB* using the entropy gadget that it recently produced, while the greatest difficulty I encounter is the following: a mysterious part that shows weird behaviors.
<img width="983" alt="5E344AFB-C2EF-4C2B-A57E-17B57DF50135" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/e986a11c-1ad3-496f-99ed-885bc2cdc859">

The definition of XBB includes G21987A (a problemsome site) and C22000A, together with deletion of 21992-21994, and this makes some very crowded mutation profile. Yet it seemed that some sequences of XBB contains a even messier profile with complicated mutations that both gisaid and cov-specturm fail to identify out. I doubt that there's seriously anything there, but I wanted to keep cautious.

I make some inquiry and doubt that probably del21989-21991/S:143del could be real, and being connected to del21992-21994, yet it hardly forms a tree, so it makes me confused. (if anyone wants to inquiry themselves, use del21989-21994 with some proper time filter and other XBB filter)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1aea9_2833b0.json?f_userOrOld=uploaded%20sample
Issue #63 talks about some related problem, and I would suggest that maybe there exist a real tree within this fog. I would be happy to include that to my collection if it is proved to be real and abundant. However, the other mutations seem incompatible, that they either form some anomalous frameshift, or is simply collection of low-quality artifacts.

**Comment by AngieHinrichs** [comment]
As of the 2023-07-21 build, nucleotides 21994, 21995 and 21998 will be masked in the XBB branch of the UShER tree -- see https://github.com/cov-lineages/pango-designation/issues/1503#issuecomment-1646243451 and more discussion of this region in cov-lineages/pango-designation#1882.
