### ISSUE TITLE
JN.1 Saltation with S:S60P, S:V83F, S:M153V and the double nuc S:N960G maybe from a single patient (3, BC Canada)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2265]
JN.1 >> ORF1b:T635M(C15371T), Orf1b:Q1985K(C16420A), ORF7a:T39I (C27509T)>>
ORF1a:S142P (T689C), ORF1a:E553G (A1923G), Orf1a:T708I (C2388T), Orf1a:L1507F (C4784T), ORF1a:K2029N (G6352T),Orf1a:S2103F (C6573T), ORF1a:G2207C (G6884T), ORF1a:S2303F (7173T),  Orf1a:I2307M  (A7186G),   T7855C, Orf1a:D2592G (A8040G), A8116G, C8389T, C10615T, C11008T, Orf1a:M3934I (G12067T), C14235T,  A16923G, Orf1b:D1565N (G18160A), Orf1b:I1604M (A18279G),   S:S60P (T21740C), S:V83F (G21809T), S:M153V (A22019G),N960G (A24440G, A24441G), ORF3a:L41P (T25514C), C27612T, ORF7a:S81L (T27634C,C27635T), ORF8:I10T (T27922C), ORF8:C37F (G28003T) , ORF9b:L64P (T28474C), T28759C         
Query: A24440G, A24441G,T3565C
Samples: 2
Places: BC
Tree:
<img width="1173" alt="Screenshot 2024-12-05 alle 01 24 37" src="https://github.com/user-attachments/assets/7c0ca9aa-5f66-4ec5-9983-58491d6445df">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_2c706_ed630.json?c=userOrOld&label=id:node_11771902

S:N960G popped up only three times outside this lineage
<img width="568" alt="Screenshot 2024-12-05 alle 01 25 13" src="https://github.com/user-attachments/assets/6e229a5c-55c5-44cd-88c2-6ab98850e854">
Also Orf7a:S81L is a double nuc mutation:
<img width="578" alt="Screenshot 2024-12-05 alle 01 26 00" src="https://github.com/user-attachments/assets/bf8db8c2-5ff6-4b4f-9912-35e4778efdb0">

**Comment by ryhisner** [comment]
I would bet that the two preceding sequences from British Columbia on the tree are also from the same patient, collected 2024-4-18 and 2024-4-23.  I suspect ORF1b:T635M might be a Remdesivir-resistance mutation. It's interesting that it has ORF1b:Q985K. One other chronic lineage that had ORF1b:T635M had, at different times, ORF1b:D982Y and ORF1b:D982C.

EPI_ISL_19109579, EPI_ISL_19141756

**Comment by xz-keg** [comment]
isn't it in British Columbia?

**Comment by FedeGueli** [comment]
> British Columbia, not Ontario

Thx corrected now

**Comment by FedeGueli** [comment]
no recent samples closing it
