### ISSUE TITLE
XEC saltation with 15 aa mutations (2 in Hong Kong)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#2269]
![image](https://github.com/user-attachments/assets/af5dfbf4-6086-4205-921d-2338ba73ab28)
![image](https://github.com/user-attachments/assets/1660b82a-8563-459c-8bb6-b0204ad17b45)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_259ac_2d2800.json?f_userOrOld=uploaded%20sample

Mutations:
ORF1a:  S2890N, P2929S, D1639N, A2584V, L3829F, S2552P
ORF1b:  S1023N, T2134I, L1641I
S:  I1013V, C1240Y
ORF3a:R122K
ORF7b:A15V
N:  G19E, T135I

First Seq: 2024-11-03
Most Recent: 2024-11-13

Gisaid: G8863A, G8934A, C9050T, 

EPI_ISL_19588464 EPI_ISL_19555103

**Comment by Over-There-Is** [comment]
XEC> G2060A> C16293T> T2314C, T7919C, C18388A> 
G2731A, G5180A, C8016T, G8863A, G8934A, C9050T, C11750T, T12697C, C12823T, C15381T, G16535A, C19868T, A24599G, G25281A, G25757A, C27799T, G28223A, G28329A, C28677T

**Comment by FedeGueli** [comment]
This was discussed earlier with @ryhisner likely same patient and treated with MOV .

**Comment by xz-keg** [comment]
no new seqs
