### ISSUE TITLE
CH.1.1.16 with S:D867N, ORF1a:P276S (nsp2_P96S), ORF1a:S17I (nsp1_S17I), S:D215G (19 seqs, Sweden and Italy)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#227]
**Defining Mutations:** _On top of CH.1.1.16_ > G24161A(S:D867N) > A18405G > C1091T(ORF1a:P276S) > T10561A > G315T(ORF1a:S17I), C12473T > A22206G(S:D215G)
**Query:** G24161A,A18405G,A22206G
**Earliest seq:** 2023-04-28 (EPI_ISL_17640900, Sweden)
**Latest seq:** 2023-06-09 (EPI_ISL_17804222, Sweden)
**Sampled Countries:** Sweden (11), Italy (2)

<details><summary>Genomes: </summary>
EPI_ISL_17640900, EPI_ISL_17704696, EPI_ISL_17731485, EPI_ISL_17731565, EPI_ISL_17763850, EPI_ISL_17803321, EPI_ISL_17803333, EPI_ISL_17803336, EPI_ISL_17804219, EPI_ISL_17804221, EPI_ISL_17804222, EPI_ISL_17817116, EPI_ISL_17817120
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c800_29a0f0.json?f_userOrOld=uploaded%20sample

Overview:
![Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b07cc4fa-70b2-4c01-93a9-4bcca9180093)

Details:
![Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/010d4de8-5d35-4f85-b27f-865bcce73500)

**Trivia:**
- S:D215G(A22206G) is the one to watch, happens to be one of the definitions of  VOC B.1.351/Beta, plus A.30.
- Interestingly, FK.1(CH.1.1.17.1) also got S:D215G+S:Q613H combination like this one.
- S:D867N(G24161A) is quite rare, only sampled 336 times during the whole pandemic. Now is the second biggest branch of CH.1.1.16 (about 100 seqs).

**Comment by HynnSpylor** [comment]
18 seqs now (2 new seqs with S:G181A)
It is highly convergent with FK.1.4+S:G181A in #88
