### ISSUE TITLE
KS.1.1.2/KP.3* Recombinant(2, FR-ARA, 2 departments)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2271]
Mutations based on JN.1: **A382G**, A1787G, _C6701T_, C9348T, _C19716T_, **A21405G**, _C21627A, T21738C_ / C22444T, _T22928C, C23039G, G24872T_, C27143T / **A29700G**
Query: C6701T, A21405G, G24872T

This recombinant is similar to XEC, having S:T22N, F59S, F456L, Q493E, V1104L, but without the N and Orf9b mutations from KP.3.3.

Donor: KS.1.1.2> C28344T(N:T24I)> **A382G, A21405G**, C27247T, **A29700G**
The another donor could be KP.3*+C22444T, KP.3*+C27143T or even KP.3*+A29700G.
Although C27143T is a part of the definition of KP.3.1.2, there are also other KP.3* branches with C27143T, including KP.3.1.1+C27143T and KP.3+C27143T etc.
There is only 1 sequence with 2 of these mutations: Poland/Kce-567/2024|EPI_ISL_19518029|2024-10-04 KP.3.1.1+C27143T+A29700G.
A1787G(Orf1a:N508D) and C9348T(Orf1a:T3028I) are private.

Breakpoint 1: 21738\~22599
Potential breakpoint 2: 28344\~29700

France/ARA-RELAB-HCL724000589201/2024|EPI_ISL_19590962|2024-10-28 Puy-de-Dôme, Auvergne-Rhône-Alpes, France
France/ARA-RELAB-HCL724000615601/2024|EPI_ISL_19590875|2024-11-13 Loire, Auvergne-Rhône-Alpes, France

It is placed on a XEC branch with several reversions now.
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice2_genome_test_3bb3b_2f8180.json?f_userOrOld=uploaded%20sample&label=id:node_11783806
![image](https://github.com/user-attachments/assets/0b6cfc7a-c565-47d3-a46e-7bd348aa26ba)

**Comment by Over-There-Is** [comment]
Typo Fixed

**Comment by Over-There-Is** [comment]
I suggest to set a label for recombinants similar to XEC, such as XEC-oid or XEC-like or so on: e. g. KS.1.1/KP.3 recombinants with a breakpoint between 21627 and 23039, and both T22N and Q493E are reserved.

**Comment by xz-keg** [comment]
no new seqs
