### ISSUE TITLE
FL.2.3 + Orf3a:S162G, S:T883I (Russia, 4seq)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#229]
FL.2.3> A25876G(Orf3a:**S162G**), A28119T(Orf8:~I76F~)> C16111T, C24210T(S:**T883I**), C29353T
05-06\~05-10 Saint Peterburg, Russia(4)
EPI_ISL_17817988-17817989, EPI_ISL_17817997, EPI_ISL_17818012

[usher](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json?label=id:node_10282152)
![2023-06-21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/9470915a-46bf-44c1-b6dc-3abb94f33c87)

Query: C16111T, C24210T,A28119T

**Comment by FedeGueli** [comment]
Not sure how much this could add to FL.2.3 itself, but worth tracking for a bit.

**Comment by FedeGueli** [comment]
still 4 and  all from early May closing it for now
