### ISSUE TITLE
LF.7 + S:T385I, Orf3a:A33S and 2 more AAs (8, 2 places)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2292]
LF.7 >> C29119T > C6472T, A9685T, A9688T, Orf1a:R3164H (G9756A), S:T385I (C22716T), Orf3a:A33S (G25489T),Orf10:L16P (T29604C)
Query:A9685T, A9688T, G9756A
Samples: 6 
Places: Illinois, Netherlands
Tree:
<img width="1161" alt="Screenshot 2024-12-17 alle 17 08 56" src="https://github.com/user-attachments/assets/e4386db3-2378-47ec-93ed-fd3118bb1220" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice26_genome_test_2929d_188d20.json?c=userOrOld&label=id:node_7224587

**Comment by FedeGueli** [comment]
+2 from Texas for this proposed branch.


Today another unrelated mini-saltation w T385I appeared on LF.7.3:
LF.7.3>> C22855T > Orf1a:I1385V (A4457G) > 
Orf1a:F2173C (T6783G), A20262G,S:A222V (C22227T), S:T385I (C22716T),Orf3a:L83F (G25641T), ORF3a:T151I (C25844T)
Query: A4457G,C22716T
Samples: 2 GBW one patient from Kenya
<img width="1175" alt="Screenshot 2024-12-18 alle 18 41 33" src="https://github.com/user-attachments/assets/558366f1-67f9-4ef8-be2c-ded2307c432c" />
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_385be_2fc100.json?label=id:node_7224765

if this will grow i will chang the issue in a multiple lineages issue.

**Comment by xz-keg** [comment]
designated LF.7.6.1

**Comment by xz-keg** [comment]
Spike predictions(12-18 data): S:A475V, S:R444T, S:S680F, S:M153I, S:K1191N

**Comment by FedeGueli** [comment]
LF.7.6.1 landed in Japa and Israel

**Comment by FedeGueli** [comment]
NEW QUERY FOR IT:  G9756A,G25489T, C5239T FINDS 17

**Comment by ryhisner** [comment]
I'm not sure what proportion of LF.7.6.1 has this, but one 30-sequence branch of LF.7.6.1 has two fascinating nearby synonymous mutations: A9685T, A9688T. 

<img width="1308" alt="Image" src="https://github.com/user-attachments/assets/7295cadc-a7c9-485f-9794-1b328923648a" />

**Comment by FedeGueli** [comment]
> I'm not sure what proportion of LF.7.6.1 this is, but one 30-sequence branch of LF.7.6.1 has two fascinating nearby synonymous mutations: A9685T, A9688T.
> 
> <img alt="Image" width="1308" src="https://private-user-images.githubusercontent.com/33738461/408348825-7295cadc-a7c9-485f-9794-1b328923648a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgyODY2NjMsIm5iZiI6MTczODI4NjM2MywicGF0aCI6Ii8zMzczODQ2MS80MDgzNDg4MjUtNzI5NWNhZGMtYTdjOS00ODVmLTk3OTQtMWIzMjg5MjM2NDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTMxVDAxMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWY4NjVlMmViYjM1YWRlYTZlMGEwNjZmNjQ4N2UxMzBmN2JiODJlNDQwZWQ5NDMxYTE2ZTVkY2M4OWRjMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xWJhh779Kez0r2FIGjwnluK5q4Xm2pHvBdC_LK5EHqY">

i think all LF.7.6.1 have it
