### ISSUE TITLE
XBL.3 x BQ.1.1.13 recombinant (2x Australia, 1x Singapore as of 2023-05-01)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#23]
Ported from https://github.com/cov-lineages/pango-designation/issues/1978

edited
Gisaid query:  C17766T, G14400T, G26428T, G26529A

**Comment by FedeGueli** [comment]
Thx @corneliusroemer no new seqs for this one. closing it for now.
