### ISSUE TITLE
MC.19 sublineage with S:A435S (76 seqs, 75 in Ontario)

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#2316]
Of the variants that have S:R346T, S:A435S, S:Q493E, this one has the most submitted sequences. At the moment this mutation combo looks very fast, but is heavily biased by its concentration in Ontario. However, it looks very fast within Ontario (73-134%). Would need to see sustained growth or growth outside of Ontario.

This proposed MC.19 sublineage is not the only variant with the S:R346T, S:A435S, S:Q493E combo circulating in the world or even within Ontario. 

**Query:**  G22599C, G22865T, C25324T,

The full set of mutations includes:
C1919T, C11518T, C19524T, G22865T,C25324T, but this only results in ORF1a:L552F and S:A435S. 

/most/ of the sequences also have G5739A (ORF1A:S1825N)

![image](https://github.com/user-attachments/assets/726fd205-a765-4081-bcb2-a06df40d9dd6)

**Discussion:**
This could be one to watch to see if the growth advantage continues and appears in other countries or regions. 
Drawing from [this recent paper](https://www.biorxiv.org/content/10.1101/2024.12.27.630350v1.full), the only tested variant with S:R346T, S:F456L, S:Q493E is LP.8.1, but it shows the strongest receptor binding efficiency. Meanwhile, MC.10.1 and NP.1 which are the ones with S:A435S show the worst receptor binding efficiency, but show somewhat improved immune evasion. Possibly the R346T mutation can improve MC.10s poor binding?

**Comment by xz-keg** [comment]
this is #2270.

**Comment by FedeGueli** [comment]
> this is #2270.

oh thx i got fooled by MC.19 missed updated there
