### ISSUE TITLE
XBB.1.9.1 with  S:E484K  [21 seqs, Greece, ] and a sublineage with S:A852S [9 seqs, Spain/Sweden/Greece, Canary Islands] 

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#232]
**Summary:**
GISAID Query: spike_e484k,spike_a852s,spike_f486p
First sequence: April-27-23, Greece. EPI_ISL_18042903
Countries circulating: Spain (4), Sweden (3), Canary Islands (1), Greece (1)

**Mutations:**
ORF1a: A79T
Spike: A852S, E484K
Additional Nucleotide: C22858T

[USHER Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34e3c_194ea0.json)
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/9d810621-dd47-4d30-8de5-44d2bafde8d2)

**Discussion:**
S:E484K is a well known mutation for having appeared on Beta and Gamma, as well as other variants. It provided large amounts of immune escape on the ancestral virus. It is a two nucleotide mutation from Omicron, but was one nucleotide from W.T. S:A852S is a defining mutation for XBB.1.5.56.

This is also not the only instance of S:E484K appearing on an XBB with S:F486P, despite it being a 2 NT mutation. See [here](https://github.com/sars-cov-2-variants/lineage-proposals/issues/546) for another example. 

E484K is [predicted](https://jbloomlab.github.io/SARS2-RBD-escape-calc/) to provide a moderate amount of immune escape to an XBB.1.5 spike,[ and also to](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/) slightly increase binding affinity while being neutral to spike expression. 

I think that the relatively older age of this variant in European countries despite only having 9 sequences means it can't be too fast. It is interesting though that the tree suggests this might actually really be two independent acquisitions of E484K that started from an E484T mutation that had some level of circulation.

**Comment by FedeGueli** [comment]
this seems luckily dead as today.

**Comment by ryhisner** [comment]
This lineage is now up to six sequences, with sequences uploaded yesterday and today from Greece (April 27 collection) and the Canary Islands (July 11). 

I don't think there's any doubt this is a real lineage, and given the July 11 collection date of the most recent sequence, it's probably still circulating a bit somewhere.
EPI_ISL_18042903, EPI_ISL_18044969

**Comment by FedeGueli** [comment]
> this seems luckily dead as today.

i was wrong . reopened

**Comment by Sinickle** [comment]
Seems it's actually two separate branches that independently acquired S:E484K from S:E484T?

**Comment by ryhisner** [comment]
Greece uploaded a bunch of sequences today that were collected in May and June, and there were 12 from this lineage, so this one's more than doubled. But none of the Greek sequences have S:A852S—they sit on a branch separate from all the other sequences. 

Definitely worthy of proposing this one now, I'd say. 
<img width="1219" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ed63b3c2-0ee3-46df-aa18-1588f9e7ece3">

**Comment by FedeGueli** [comment]
ping @Sinickle propose it.

**Comment by Sinickle** [comment]
Moved to the main page.

**Comment by FedeGueli** [comment]
Designated FL.30 via  https://github.com/cov-lineages/pango-designation/commit/8f78e43028c7f9c77c2dc5fc1989b85ed294c781
