### ISSUE TITLE
XBB.2.3.14 with ORF1b:T1050I (nsp13_T127I) (92 seqs, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#235]
**Defining Mutations:** XBB.2.3 > G3259T(ORF1a:Q998H) > C16616T(ORF1b:T1050I)
**Query:** C16616T, G3259T, C23123T
**Earliest seq:** 2023-02-13 [EPI_ISL_17190173, Italy]
**Latest seq:** 2023-06-03 [EPI_ISL_17813120, England]
**Sampled Countries:** France (30, 27/Mainland, Martinique/2, Saint Martin/1), Italy (8), USA (4, all New Jersey), Belgium (3), Canada (3, Ontario/2, Quebec/1), Spain (2, Mainland/1, Canary Islands/1), UK (3, all England), Switzerland (1)

<details><summary>Genomes: </summary>
EPI_ISL_17190173, EPI_ISL_17257583, EPI_ISL_17285910, EPI_ISL_17346276, EPI_ISL_17408549, EPI_ISL_17408550, EPI_ISL_17422723, EPI_ISL_17426960, EPI_ISL_17428341, EPI_ISL_17428535, EPI_ISL_17501869, EPI_ISL_17502180, EPI_ISL_17528884, EPI_ISL_17528886, EPI_ISL_17547110, EPI_ISL_17639063, EPI_ISL_17639196, EPI_ISL_17640586, EPI_ISL_17646796, EPI_ISL_17651693, EPI_ISL_17651694, EPI_ISL_17651725, EPI_ISL_17658085, EPI_ISL_17667572, EPI_ISL_17667690, EPI_ISL_17671195, EPI_ISL_17671205, EPI_ISL_17676173, EPI_ISL_17677324, EPI_ISL_17677342, EPI_ISL_17681044, EPI_ISL_17701315, EPI_ISL_17701331, EPI_ISL_17704883, EPI_ISL_17704884, EPI_ISL_17705029, EPI_ISL_17713820, EPI_ISL_17715961, EPI_ISL_17715966, EPI_ISL_17727216, EPI_ISL_17731367, EPI_ISL_17743334, EPI_ISL_17762283, EPI_ISL_17762294, EPI_ISL_17762364, EPI_ISL_17768535, EPI_ISL_17770520, EPI_ISL_17791524, EPI_ISL_17792458, EPI_ISL_17805416, EPI_ISL_17813120, EPI_ISL_17813123, EPI_ISL_17820656, EPI_ISL_17820688
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3261e_3fac10.json?f_userOrOld=uploaded%20sample

overview from XBB.2.3's polytomy
![Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/be4ebb9f-f310-4f82-8bd9-931af724a363)

details:
![Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d95f0f41-4147-48a2-bd23-aabee52b7115)

**Trivia:**
- ORF1b:T1050I(C16616T) is one of the definitions of XBC, one nuc different to BA.5.2's largest undesignated ORF1b:T1050N(C16616A).
- ORF1a:Q998H(G3259T) is one of the largest undesignated branches of XBB.2.3 [query: G3259T, C23123T finds about 160 seqs]
- One of the branch got S:A845V(C24096T), and all the seqs are quite recent. This mutation have about 4k seqs during the whole pandemic, no idea what it does.

**Comment by FedeGueli** [comment]
Slow. lets see next week .
