### ISSUE TITLE
BF.18 mini saltation, potential single chronic? (3 seq. Australia)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#237]
Proposal for a sublineage of BF.18
Earliest sequence: 01.03.2022 (Australia)
Countries detected: Australia

Defining Mutations:
nuc	unique	G487T, C4763T, A7986G, G9489A, C11208T, C17125A, T17126C, G17616A, G21853T, G22017T, C22338G, G23282T, C24099T, A26275G, T27405C, G27703A, G29291A
nuc	homoplasies	G12070T, C16468T, G22599C, A22893G, C23423T, C23929T, C28419T
ORF1ab	unique	H1500Y, Q2574R, S3075N, A3648V, L5621T
ORF1ab	homoplasies	P5402S
S	unique	K97N, W152L, T259R, D574Y, A846V
S	homoplasies	R346T, K444R, P621S
E	unique	T11A
ORF7a	unique	V104I
N	unique	D340N
N	homoplasies	T49I

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/9cd0c450-f7d5-4595-8dd4-1a7265866c01)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a46b_42f3b0.json?c=userOrOld

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/67762c49-3f11-4dcb-8218-852bdc6675eb)

EPI_ISL_17823538, EPI_ISL_17824292, EPI_ISL_17824608

**Comment by FedeGueli** [comment]
i think there are 4 of this but very lld so closing it for now.
