### ISSUE TITLE
FE.1.1.1 (XBB.1.18.1.1.1.1) sublineage with S:V622I (140 seqs, mainly in Puerto Rico)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#239]
Defining mutations: 
FE.1.1.1>C15180T>T9445C>C28057T(ORF8:A55V, despite ORF8:G8* ahead)>G23426A(S:V622I)

GISAID query: G23426A, T4579A, T22928C
Earliest seq: 2023-02-12 (Canada, EPI_ISL_17537601)
Most recent seq: 2023-05-27(Puerto Rico, USA, EPI_ISL_17810634)
Countries detected: USA (96, Including 93 in Puerto Rico), Canada (17), Italy (1)

Usher Tree:
![QQ截图20230622224949](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/8f670d43-3171-4f03-b2ca-1d6edf3f9e0a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_de0c_458510.json

It has a relative high prevalence in Puerto Rico (about 20% since May 2023).

S:V622I mutation is not popular as about 2500 seqs since 2020, once emerged in some B.1.1, Alpha (B.1.1.7) ,Delta (AY.39) and BA.2 sublineages. It may slightly increase the fitness (Bloom and Neher, 2023, shown in https://[jbloomlab.github.io/SARS2-mut-fitness/S.html](https://jbloomlab.github.io/SARS2-mut-fitness/S.html))
![QQ截图20230622225020](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/6f41ce42-276c-424e-9446-531d31360fc5)

Genomes:
EPI_ISL_17386051, EPI_ISL_17537020-17537024, EPI_ISL_17537059, EPI_ISL_17537063, EPI_ISL_17537080, EPI_ISL_17537143,
EPI_ISL_17537565, EPI_ISL_17537601, EPI_ISL_17590550-17590551, EPI_ISL_17590953, EPI_ISL_17651021, EPI_ISL_17653245,
EPI_ISL_17700219, EPI_ISL_17700249, EPI_ISL_17701350, EPI_ISL_17713864, EPI_ISL_17713904-17713905, EPI_ISL_17713915,
EPI_ISL_17717505, EPI_ISL_17737291, EPI_ISL_17737294, EPI_ISL_17737307, EPI_ISL_17737318, EPI_ISL_17777773-17777775,
EPI_ISL_17777777, EPI_ISL_17777779-17777780, EPI_ISL_17777804, EPI_ISL_17777807, EPI_ISL_17792082, EPI_ISL_17800518,
EPI_ISL_17800532, EPI_ISL_17805651-17805656, EPI_ISL_17805669-17805674, EPI_ISL_17805676, EPI_ISL_17805682-17805685, EPI_ISL_17805687-17805698, EPI_ISL_17805702, EPI_ISL_17805708, EPI_ISL_17805712, EPI_ISL_17810311, EPI_ISL_17810314, EPI_ISL_17810501, EPI_ISL_17830884-17830887, EPI_ISL_17830892-17830893, EPI_ISL_17830943, EPI_ISL_17830948, 
EPI_ISL_17831052-17831053, EPI_ISL_17831055-17831056, EPI_ISL_17831059-17831066, EPI_ISL_17831074-17831079, EPI_ISL_17831081, EPI_ISL_17831083, EPI_ISL_17831092-17831097, EPI_ISL_17831104, EPI_ISL_17831115

**Comment by HynnSpylor** [comment]
26 seqs updated (all in Puerto Rico)
I’ll propose in main page if spread internationally

**Comment by aviczhl2** [comment]
#155

**Comment by HynnSpylor** [comment]
@aviczhl2 Ah You have a typo! It is S:V622I instead of S:V622L (hence my search does not show the duplicate)
