### ISSUE TITLE
XBB.2.3 with S:F456L and PLPro_T259I emerged in Spain (35 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#240]
Gisaid query: T22928C,C5730T,C23123T  
Samples 9
EPI_ISL_17617147, EPI_ISL_17679055, EPI_ISL_17679964,
EPI_ISL_17722951, EPI_ISL_17723004, EPI_ISL_17784673,
EPI_ISL_17786070, EPI_ISL_17788606, EPI_ISL_17797637,
First: 
hCoV-19/Spain/GA-CHUVI-22115333/2023 | Original | EPI_ISL_17784673 | 2023-03-13
Last:
hCoV-19/Spain/CT-HUB08375/2023 | Original | EPI_ISL_17788606 | 2023-06-06

Tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_21f7e_4450d0.json?c=gt-S_456&label=id:node_6955996
![Schermata 2023-06-22 alle 18 53 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/6e06ce6c-e482-485e-a597-ac123be19043)

Defining mutations:
XBB.2.3>> S:F456L (T22928C) > Orf1a:T1822I (C5730T = NSP3_T1004I = PLPro_T259I )

**Comment by krosa1910** [comment]
Among the general S:486P population, the last 30 days have about 7.8% of total variants, S:252G have about 8.5%, yet the combination of those only has 0.02%, much lower than the product of two (0.6%). It is interesting to me why non-XBB.1* seems to not be so compatible with S:456L despite it being a beneficial while easy to acquire mutation.

**Comment by FedeGueli** [comment]
Alrhough i m bot a super fan of rhis kind of calculations if not when done in super appropriated as in the neher bloom paper, agree we are seeing very different behaviour of this mutation also in the same lineage.

**Comment by FedeGueli** [comment]
1 more sequence from Spain.

**Comment by FedeGueli** [comment]
This seems circulating now.

**Comment by ryhisner** [comment]
NSP3_T1004I / ORF1a:T1822I / PLPro:T259I is something of a convergent mutation in chronic-infection sequences (though not nearly as common as ORF1a:K1795Q / PLPro:K232Q).

**Comment by FedeGueli** [comment]
two new sequences coming from France. this has started to circulate quite fastly

**Comment by FedeGueli** [comment]
4 new sequences 3 of them from Us (Utah, New Jersey)
