### ISSUE TITLE
Another S:456L(T22928C this time)+S:Q52H combination as XBB.1.9.1 subvariant

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#241]
Sublineage of:XBB.1.9.1*
Mutations On top of XBB.1.9.1*:ORF1a:I2010V,S:Q52H,S:F456L,ORF3a:L108F ， C1912T，C9391T，C14016T
Gisaid Inquiry: Spike_F486P (to exclude some CH),Q52H， T28297C (for XBB.1.9, but actually unnecessary), T22928C (to separate from EG.5)
Sequences: EPI_ISL_17679418, EPI_ISL_17699277, EPI_ISL_17763111,
EPI_ISL_17795947, EPI_ISL_17798867, EPI_ISL_17799061,
EPI_ISL_17800538-17800539, EPI_ISL_17809691, EPI_ISL_17812682,
EPI_ISL_17821332, EPI_ISL_17826969-17826970

Earliest: EPI_ISL_17679418 Spain, 04-29, 2023
Latest:  EPI_ISL_17826970 Austria, 06-14, 2023
Spread: 2 Austria, 3 Canada, 1 England, 1 Finland, 1 France, 2 Peurto Rico, 3 Spain.

Tree： (https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_766d_49c050.json?label=id:node_3519635)
This is epic, a challenger for EG.5.1 from its FL sibling, while casting the altered spell T22928C instead of T22930A. I am eager to see if it could demonstrate the same level of success as EG.5.1, the fastest relatively large variant as of now.

**Comment by krosa1910** [comment]
Note: I believe the three other mutations except for S:456L is very limited within XBB.1.9.1* (0.1,0.13,0.2% respectively) so they likely co-develop, not sure how those are related with S:456L

**Comment by FedeGueli** [comment]
Closing this although always super good when multiple people spot the same lineage.
