### ISSUE TITLE
FL.4 + ORF3a:D173G and S:S254P (123 seq.)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#242]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/bde2f52f-ba86-4f88-88fa-5dc1d0ffcc37)
tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3691f_4d9240.json?c=gt-ORF3a_173&label=id:node_6646630
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/bf987dc2-412c-432e-8859-c44669a75052)
first seq: 2023-03-20
most recent: 2023-06-13

Gisaid query of the main branch : C17436T, A25910G (edited) finds 109 leaving out 10 sequences.

**Comment by FedeGueli** [comment]
Lets see if it is just a cluster boosted by canadian sequencing strategy or really a new branch of FL.4

**Comment by aviczhl2** [comment]
#216

**Comment by aviczhl2** [comment]
> Lets see if it is just a cluster boosted by canadian sequencing strategy or really a new branch of FL.4

According to #216,  It is already detected in 13 countries

**Comment by FedeGueli** [comment]
> > Lets see if it is just a cluster boosted by canadian sequencing strategy or really a new branch of FL.4
> 
> According to #216, It is already detected in 13 countries

yeah mainly the T22327G branch, but if you look at the collection dates it doesnt seem going anywhere outside Canada.
