### ISSUE TITLE
XBB.1.5.44 (S:K356T,S:T572I) branch acquired S:P631S and S:Q146P , total 4 S1 mutations . 29 recent samples

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#244]
Worth to track this lineage with 4 S1 mutations accumulated in a stepwise manner 

Tree:
![Schermata 2023-06-23 alle 14 35 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/76624d29-87ca-4dd1-ac1c-8cf8eaba5100)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice19_genome_test_37f13_547a10.json?label=id:node_6768796

Gisaid query: A11588G ,C5849T,C23453T

Samples:
EPI_ISL_17550812, EPI_ISL_17588167, EPI_ISL_17602886,
EPI_ISL_17616014, EPI_ISL_17621223, EPI_ISL_17621306,
EPI_ISL_17636030, EPI_ISL_17639793, EPI_ISL_17653436,
EPI_ISL_17653484, EPI_ISL_17685857, EPI_ISL_17686970,
EPI_ISL_17687988, EPI_ISL_17688687, EPI_ISL_17689124,
EPI_ISL_17689126, EPI_ISL_17717526, EPI_ISL_17720200-17720201,
EPI_ISL_17726506, EPI_ISL_17735189, EPI_ISL_17763564,
EPI_ISL_17769145, EPI_ISL_17788945, EPI_ISL_17801672,
EPI_ISL_17815252, EPI_ISL_17815290, EPI_ISL_17815294,
EPI_ISL_17831778

Defining mutations:
XBB.1.5.44 >>  Orf1a:P1862S (C5849T), ORF1a:T3775A (A11588G = NSP6_T206A)> S:P631S (C23453T) > S:H>Q146P [A21999C( +T22000A]

**Comment by Fearuncle** [comment]
https://github.com/sars-cov-2-variants/lineage-proposals/issues/106
