### ISSUE TITLE
Sublineage of FL.23.1 defined by S:R214P ( 39 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#245]
Here i want to propose a sub lineage of FL.23  (Orf1b:V1132I  )

Defining mutations:
FL.23 >  ORF1a:A2584V (C8016T = NSP3_A1766V)  , C23185T > C8311T > T15102C > S:R214P (G22203C)

Gisaid query : C8311T ,T15102C ,G22203C,C23185T

24 samples: EPI_ISL_17652340, EPI_ISL_17657210, EPI_ISL_17675277,
EPI_ISL_17688019, EPI_ISL_17720217, EPI_ISL_17734468,
EPI_ISL_17734481, EPI_ISL_17734518, EPI_ISL_17734539,
EPI_ISL_17734558, EPI_ISL_17786212, EPI_ISL_17787334,
EPI_ISL_17801686, EPI_ISL_17807636, EPI_ISL_17815231,
EPI_ISL_17815240, EPI_ISL_17815600, EPI_ISL_17815686,
EPI_ISL_17815769, EPI_ISL_17815877, EPI_ISL_17817854,
EPI_ISL_17820619, EPI_ISL_17830622, EPI_ISL_17832165,

First: 
hCoV-19/USA/HI-H2321738/2023 | Original | EPI_ISL_17675277 | 2023-04-20
Last
hCoV-19/Singapore/R41MR184/2023 | Original | EPI_ISL_17815877 | 2023-06-14

Tree:
![Schermata 2023-06-23 alle 15 21 33](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/cec2e555-3171-41ee-9d55-92245f26825c)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_21bed_59c060.json?c=gt-S_214&label=id:node_6598708

(the long branch displayed is a MOV related sequence maybe @ryhisner interested in)

Confronting this mutation with the global fastest Orf1b:D54N it doesnt seem slow at all:

![Schermata 2023-06-23 alle 15 25 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/559ed127-8b87-46fe-9000-ef80308ccfd0)
https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-05-01%26to%3D2023-06-23/variants?aaMutations=Orf1b%3AD54N&aaMutations1=S%3AR214P&analysisMode=CompareToBaseline&

But this still has not been sampled in numbers we should trust

**Comment by FedeGueli** [comment]
30 as today Japan mostly and Ireland

**Comment by Over-There-Is** [comment]
The parental branch of this one and #291 is designated as FL.23.1 now.
