### ISSUE TITLE
FL.2.4 (Orf8:S67F)+S:G1099D in China (67 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#248]
FL.2.4 (Orf8:S67F =C28093T) > C1645T+S:G1099D( G24858A) **EDITED**

GISAID query:G24858A,C1645T,C28093T

No. of seqs: 32(Anhui Fujian Guangdong Heilongjiang Hubei Jiangxi Qinghai Shanghai Shanxi Sichuan Yunnan）
First seq: EPI_ISL_17625557, Shanghai, 2023-4-26
Latest seq: EPI_ISL_17801857, Hubei, 2023-6-2

Orf8:S67F is defining mutation of  FE.1.1, B.1.1.621 and AY.62

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43470_82d7b0.json)
<img width="1407" alt="Screenshot 2023-06-25 at 20 26 27" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0aca8cc6-1ec2-4fca-af39-a66e2a96f755">

**Comment by FedeGueli** [comment]
Also BR.2.1

**Comment by aviczhl2** [comment]
+1 South Korea

**Comment by Over-There-Is** [comment]
the parental lineage is designated as FL.2.4 now.

**Comment by aviczhl2** [comment]
+3 Japan

**Comment by aviczhl2** [comment]
+1 Singapore local

**Comment by FedeGueli** [comment]
closing it.
