### ISSUE TITLE
FL.4.2 sublineage with S:V289I (229 seqs Guangdong mainly but already exported to 6 countries) with a sublineage of interest with S:F490A (25)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#250]
Defining mutations: FL.4.2>S:V289I (G22427A)
GISAID query: G22427A, C3117T, G5720A, C11956T
Gisaid query for sublineage with S:F490A : G22427A, C3117T, G5720A, C11956T,T23030G (edited)
Earliest seq: 2023-04-04 (Guangdong Province, China-EPI_ISL_17584604)
Most recent seq: 2023-06-05 (Hubei Province, China- EPI_ISL_17801825)
Detected Countries: China (72), Japan (1), Singapore (1), Australia (1)
Usher Tree:
![QQ截图20230625184554](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/4d503d69-4bff-45ee-b845-ee258a4b158c)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27ca5_816300.json?c=gt-S_490
Notice that there are S:F371S /S:I368L rev mutations, but I found that half of the seqs are missing these two sites and may be artefacts. 
5 seqs further get S:F490A (but in different branches), which is a new mutation compared to the popular S:F490S.

Genomes:
EPI_ISL_17584604, EPI_ISL_17584612, EPI_ISL_17584614-17584615, EPI_ISL_17584618, EPI_ISL_17584620-17584621, EPI_ISL_17584627,
EPI_ISL_17584679-17584682, EPI_ISL_17615007, EPI_ISL_17645450, EPI_ISL_17684047-17684048, EPI_ISL_17684427, EPI_ISL_17689288,
EPI_ISL_17697570, EPI_ISL_17697590, EPI_ISL_17697620-17697621, EPI_ISL_17697657, EPI_ISL_17697669, EPI_ISL_17697684,
EPI_ISL_17697687, EPI_ISL_17697771-17697772, EPI_ISL_17697776, EPI_ISL_17697781, EPI_ISL_17697788, EPI_ISL_17697801,
EPI_ISL_17697816, EPI_ISL_17697858, EPI_ISL_17697869, EPI_ISL_17697896, EPI_ISL_17697899, EPI_ISL_17697947, EPI_ISL_17697968, EPI_ISL_17697979, EPI_ISL_17697986, EPI_ISL_17697992, EPI_ISL_17697995, EPI_ISL_17698000, EPI_ISL_17698003-17698004, EPI_ISL_17698042, EPI_ISL_17698057, EPI_ISL_17698061, EPI_ISL_17698082, EPI_ISL_17698085, EPI_ISL_17698186, 
EPI_ISL_17698194-17698195, EPI_ISL_17724785, EPI_ISL_17724954, EPI_ISL_17725263, EPI_ISL_17725365, EPI_ISL_17744722, EPI_ISL_17775207, EPI_ISL_17778757, EPI_ISL_17779928, EPI_ISL_17794052, EPI_ISL_17794252, EPI_ISL_17794398, EPI_ISL_17794479, EPI_ISL_17794512, EPI_ISL_17794605, EPI_ISL_17794877, EPI_ISL_17795029, EPI_ISL_17795202, EPI_ISL_17801825, EPI_ISL_17801981,
EPI_ISL_17803108, EPI_ISL_17808341

**Comment by FedeGueli** [comment]
Hi @HynnSpylor S:V289I was one of the first sublineage of BA.5 to be designated (BA.5.1.3) 
About this proposal: this sublineage represents already the vast mayority of FL.4.2 (•S:V289I ([96.25%](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextcladePangoLineage=FL.4.2*&aaMutations1=S%3AV289I&)) , in this case i am not very favourable to designate until a very fast sublineage would pop up further in the tree, 
but i am curious to hear about this from @corneliusroemer 
This one  seems far from  EG.5.1.1 lineage too : https://cov-spectrum.org/explore/China/AllSamples/Past2M/variants?aaMutations=Orf1b%3AD54N&aaMutations1=S%3AV289I&analysisMode=CompareToBaseline&

**Comment by HynnSpylor** [comment]
2 more seqs from China and both get S:F490A

**Comment by HynnSpylor** [comment]
2 more seqs in China (including one with S:F490A)

**Comment by HynnSpylor** [comment]
Total 85 and S:F490A reaches 8 (one more from South Korea, and it is the first seq abroad China)

**Comment by FedeGueli** [comment]
@HynnSpylor i would propose it.

**Comment by Over-There-Is** [comment]
203

**Comment by FedeGueli** [comment]
ping @HynnSpylor propose it.

**Comment by FedeGueli** [comment]
too few recent samples closing it.
