### ISSUE TITLE
FL.2+Orf8:F120V,I121L (187 seqs, 18 countries, 114 seqs have ins28250CT)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#252]
FL.2+Orf8:F120V,I121L(T28251G,A28254C)

GISAID query: T28251G,A28254C,T4579A,T23018C

No. of seqs: 103(Bahrain 3 Denmark 2 England 2 Indonesia 5 Israel 1 Japan 33 China 9 Singapore 1 South Korea 2(1 from Philippines) Sweden 1 Thailand 4 USA 40(1 from Japan, 1 from Spain)
First seq: EPI_ISL_17081495 2023-1-18, Bahrain
Latest seq: EPI_ISL_17818534 2023-6-8, USA

EPI_ISL_17081495, EPI_ISL_17081554, EPI_ISL_17081556,
EPI_ISL_17146460, EPI_ISL_17250439, EPI_ISL_17278848,
EPI_ISL_17280362, EPI_ISL_17286654, EPI_ISL_17305927,
EPI_ISL_17315728, EPI_ISL_17344492, EPI_ISL_17352740,
EPI_ISL_17372716, EPI_ISL_17372801, EPI_ISL_17372803,
EPI_ISL_17373505, EPI_ISL_17389984, EPI_ISL_17393409,
EPI_ISL_17412235, EPI_ISL_17428792, EPI_ISL_17462546,
EPI_ISL_17465541, EPI_ISL_17477506, EPI_ISL_17486016,
EPI_ISL_17486836, EPI_ISL_17495607, EPI_ISL_17495647,
EPI_ISL_17499307, EPI_ISL_17499441, EPI_ISL_17499589,
EPI_ISL_17534941, EPI_ISL_17540105, EPI_ISL_17540107,
EPI_ISL_17547650, EPI_ISL_17550601, EPI_ISL_17556204,
EPI_ISL_17556365, EPI_ISL_17556379, EPI_ISL_17558701,
EPI_ISL_17558829, EPI_ISL_17585487, EPI_ISL_17585606,
EPI_ISL_17589939, EPI_ISL_17593046, EPI_ISL_17593304,
EPI_ISL_17595486, EPI_ISL_17625660, EPI_ISL_17629706,
EPI_ISL_17629956, EPI_ISL_17629961, EPI_ISL_17629969,
EPI_ISL_17630880, EPI_ISL_17630991, EPI_ISL_17631005,
EPI_ISL_17631164, EPI_ISL_17631222, EPI_ISL_17639604,
EPI_ISL_17649136, EPI_ISL_17652020, EPI_ISL_17652132,
EPI_ISL_17652145, EPI_ISL_17653089, EPI_ISL_17672371,
EPI_ISL_17672493, EPI_ISL_17680438, EPI_ISL_17684020,
EPI_ISL_17692101, EPI_ISL_17692144-17692145, EPI_ISL_17718685-17718689,
EPI_ISL_17725327, EPI_ISL_17736541, EPI_ISL_17740846,
EPI_ISL_17741786, EPI_ISL_17758549, EPI_ISL_17758557,
EPI_ISL_17758569, EPI_ISL_17758571, EPI_ISL_17759913,
EPI_ISL_17764012, EPI_ISL_17768383, EPI_ISL_17770417,
EPI_ISL_17779758, EPI_ISL_17780113, EPI_ISL_17783630,
EPI_ISL_17785889, EPI_ISL_17785891, EPI_ISL_17785896,
EPI_ISL_17787044, EPI_ISL_17795171, EPI_ISL_17795739,
EPI_ISL_17808282, EPI_ISL_17810564, EPI_ISL_17811258,
EPI_ISL_17818484, EPI_ISL_17818534, EPI_ISL_17819899,
EPI_ISL_17830428, EPI_ISL_17835902

It seems that usher cannot handle this branch well as 55/103 of the seqs have ins28250CT.

It is worth mention that Orf8:F120V,I121L is quite common in all XBB* branches, and most(but not all) of them appear together with  ins28250CT( according to GISAID), this makes usher trees with them very messy. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_185a7_840eb0.json?f_userOrOld=uploaded%20sample&label=id:node_6667930)
Highlighted are the seqs actually belonging to this branch. Due to having ins28250CT, usher don't place them in the right place. 
<img width="1386" alt="Screenshot 2023-06-26 at 10 31 30" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/31352583-ae64-4474-bb92-2196567a9570">

**Comment by FedeGueli** [comment]
Very messy. @corneliusroemer @thomeaspeacock @ryhisner already gave a look at this kind of patterns in the past. 
To me if you want better proposing from Orf1a:R3163G node that includes most of the samples proposed here.

**Comment by aviczhl2** [comment]
> Very messy. @corneliusroemer @thomeaspeacock @ryhisner already gave a look at this kind of patterns in the past. To me if you want better proposing from Orf1a:R3163G node that includes most of the samples proposed here.

I think the messy part comes from ins28250CT, which cannot be analysed by usher (as usher ignore insertions) , and as it is right before Orf8:120, it makes usher recognize other mutations. 

For Orf1a:R3163G, unfortunately it is another flip-flop reversion. Only 24/103 of these seqs have this mutations and most actually lies in the Orf1a:G3163R(rev) branch.

**Comment by aviczhl2** [comment]
124, Bulgaria

**Comment by aviczhl2** [comment]
152, Pakistan

**Comment by FedeGueli** [comment]
Cc @angiehinrichs could youn ake a look at rhis tree please? Not sure it is real.

**Comment by AngieHinrichs** [comment]
Yes, 28251+28254 is a problematic combo that I have seen several times and I've been keeping an eye on it.  So far I haven't considered it bad enough to mask but if it's associated with an indel and is causing trouble for lineage designation then it's probably worth it.

**Comment by ryhisner** [comment]
The most common mutation in this area (at least according to NextClade's interpretation) is ∆28254, along with T28251G+C28253T+A28254C. But there seem to be about a dozen slightly different versions of the ORF8:119-121 mutations. Some involve only substitutions, some involve deletions, and some involve insertions. The common theme is that they all create more extended homology for the N/ORF9b TRS. 

But really, I'm not sure if any substitutions, deletions, or insertions are involved at all—they may all just involve recombination with the TRS-L. I don't know the exact dynamics of how such recombination happens, but I know it is considered to be the primary way novel TRS motifs (like the N* TRS at N:203-204) occur. 

Anyway, the two most common ones that I see are pictured below. 
<img width="1260" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7f7f9b9d-d76b-4175-b490-b41eae2d57ad">

**Comment by aviczhl2** [comment]
> The most common mutation in this area (at least according to NextClade's interpretation) is ∆28254, along with T28251G+C28253T+A28254C. But there seem to be about a dozen slightly different versions of the ORF8:119-121 mutations. Some involve only substitutions, some involve deletions, and some involve insertions. The common theme is that they all create more extended homology for the N/ORF9b TRS.
> 
> But really, I'm not sure if any substitutions, deletions, or insertions are involved at all—they may all just involve recombination with the TRS-L. I don't know the exact dynamics of how such recombination happens, but I know it is considered to be the primary way novel TRS motifs (like the N* TRS at N:203-204) occur.
> 
> Anyway, the two most common ones that I see are pictured below. <img alt="image" width="1260" src="https://user-images.githubusercontent.com/33738461/257347989-7f7f9b9d-d76b-4175-b490-b41eae2d57ad.png">

Do you mean it is a self-recombination event that part of the virus recombines with another part of the virus?

**Comment by ryhisner** [comment]
@aviczhl2, yes, that's what I mean. I gather that experts view this to be the primary way that both novel TRS motifs and extended homology of canonical TRS's occur.

**Comment by aviczhl2** [comment]
> Yes, 28251+28254 is a problematic combo that I have seen several times and I've been keeping an eye on it. So far I haven't considered it bad enough to mask but if it's associated with an indel and is causing trouble for lineage designation then it's probably worth it.

It seems that the mutations are real but they involve self-recombination-driven insertion/deletions that usher cannot handle.

**Comment by aviczhl2** [comment]
Also in Brazil.

**Comment by aviczhl2** [comment]
183,detected in Cook Islands.

**Comment by FedeGueli** [comment]
Sorry @aviczhl2 i have had lost this one out of my sight for a while I have the serious doubt this is unreal. anyway it is too slow i am closing it. (while checking the artifcat or not)

**Comment by aviczhl2** [comment]
> Sorry @aviczhl2 i have had lost this one out of my sight for a while I have the serious doubt this is unreal. anyway it is too slow i am closing it. (while checking if it is an artifact or not)

Yeah, FL.2 is decaying. 

Actually I'm seeing EG.5.1 and EG.5.1.1 sub-branch of this now. They are growing quickly.
