### ISSUE TITLE
BA.1.1 singleton (1 seq, Germany)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#254]
Proposal for a sublineage of BA.1.1
Earliest sequence: 23.05.2023 (Germany)
Countries detected: Germany

Defining Mutations:
nuc	unique	A570T, T2537C, A4645G, A11917G, C13264T, C15678T, C17336T, C17465T, C18166T, C22439T, A22563G, C22571A, C22572A, G22770A, T22896C, A22898G, C22916A, T23042C, A23049C, T23487G, G23642T, C23643T, C23934T, G24314C, G24515C, T24903C, A24999G, G25019T, G25395A, G28631C, C29253T, C29784T
nuc	homoplasies	C8247T, C9214T, C11750T, C21588T, A22599G, T22942G, A23604G, C24374T, G25049T, C25904T, C26408T, T27384C, C28674T
nuc	reversionsToRoot	A22599G, A22898G
ORF1ab	unique	E102V, T5691I, T5734I, P5968S
ORF1ab	homoplasies	S2661F, L3829F
S	unique	L293F, N334S, P337N, R403K, V445A, S446G, L452M, S494P, N496T, V642G, A694F, T791I, E918Q, D985H, I1114T, D1146G, D1153Y
S	homoplasies	P9L, K346R, N460K, H681R, L938F, D1163Y
S	reversionsToRoot	K346R, S446G
ORF3a	unique	M1I
ORF3a	homoplasies	S171L
E	homoplasies	S55F
N	unique	G120R, S327L
N	homoplasies	A134V

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/f48a575c-7a05-43ee-83c1-03f71829c4d8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_402c9_92acc0.json?c=userOrOld

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/3c6c1f18-23c3-4a6f-8085-b27c3bee5814)

EPI_ISL_17833161

Gisaid query: Spike_P9L,Spike_L293F (edited)

**Comment by FedeGueli** [comment]
This was first spotted last saturday by @c19850727 .
My guess it comes from Africa as we have seen with BA.5.9 and FY.4 first sampled in Germany but emerged in some african area.

**Comment by FedeGueli** [comment]
Notice that Orf3a has lost his start codon.

**Comment by oobb45729** [comment]
A lot of S2 mutations, including three HR2 ones that changed positive charge level a lot, D1146G+D1153Y+D1163Y.

**Comment by FedeGueli** [comment]
luckily no more samples of this one. closing for now
