### ISSUE TITLE
XBB.1.34.2 with S:Q146K, S:F456L (11+3 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#255]
**Defining Mutations:** XBB.1.34.2 > C21998A(S:Q146K) > T22928C(S:F456L)
**Query:** C21998A, T22928C, G28162T
**Earliest seq:** 2023-04-25 (EPI_ISL_17705477, Wisconsin, USA)
**Latest seq:** 2023-06-13 (EPI_ISL_17827042, Austria)
**Sampled Countries:** USA (3, California/2, Wisconsin/1), Austria (3), Canada (2, all Ontario), Israel (2), China (1, Sichuan)

<details><summary>GISAID Genomes: </summary>
EPI_ISL_17664620, EPI_ISL_17705477, EPI_ISL_17707041, EPI_ISL_17788904, EPI_ISL_17803559, EPI_ISL_17803730, EPI_ISL_17810624, EPI_ISL_17810631, EPI_ISL_17814561, EPI_ISL_17814567, EPI_ISL_17827042
</details>

<details><summary>GenBank Genomes: (California/1, Arizona/2)</summary>
USA/CA-CDC-QDX80348100/2023|OR062014.1|2023-05-10

USA/AZ-CDC-LC1042889/2023|OR064371.1|2023-05-15
USA/AZ-CDC-LC1043890/2023|OR131351.1|2023-05-24
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_47ba_94dd40.json

Overview from XBB.1.34 polytomy
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/57a81047-6fc0-42f5-a484-b94adece2f8f)

Details:
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b071ce6d-4c31-4977-b7b6-04d66170759b)

**Trivia:**
- One branch (2 seqs from Israel) and a singlet from Sichuan even got S:T478R, makes it F456L+T478R+F486P+P681R combo.
- 3 GenBank seqs not on GISAID yet.
- One seq South_Africa/NICD-N55304/2023|EPI_ISL_17803340|2023-05-15 having Ns from 443-468 on S gene, the dropout probably causing branches on UShER,

**Comment by Memorablea** [comment]
Please @FedeGueli add a tag, I think it's worth tracking!
