### ISSUE TITLE
FR.1.1 with S:82 reverted (115 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#256]
FR.1.1+T14961C+A3715G,C15960T, A21807C(S:P82H, reversion)

GISAID query: A3715G,C15960T,C1142T,T2372C,T14961C,C7318T,-21807

None of the seqs under A3715G,C15960T branch has S:H82P, none of them has S:82 masked, so on position 82 it is P.  

No. of seqs: 61(Austria 1 Italy 2(from China), Singapore 2(1 from Italy, 1 from China), South Korea 1 USA 2 China 53)

First seq: EPI_ISL_17516758, 2023-4-6, Liaoning
Latest: EPI_ISL_17836899, 2023-6-13, Shanghai

It shares lots of FR.1.1 specific mutations (C1142T,T2372C, and T14961C on FR.1.1's main branch), so shall be FR.1.1+S:82 reversion. Which is a bit strange as S:P82H is FR.1.1's defining mutation and it immediately reverts back. 

Another possibility is FR.1/FR.1.1 recombinant. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice19_genome_317ce_9687c0.json?label=id:node_7225210)
<img width="1398" alt="Screenshot 2023-06-26 at 19 03 23" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/22b372d4-4586-44c9-ae24-557beb811e2c">

**Comment by FedeGueli** [comment]
Hi @aviczhl2 for opening this one. I multiple times lost a lot of time trying tomunderstande the FR.1.1 tree.
I never was able to draw any conclusion but to me everything is messed by 337 C337T that undergoes multiple reversions in the proposed branch and outside.

cc @angiehinrichs @corneliusroemer could you take a look please?
![Schermata 2023-06-26 alle 13 54 21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0ba176a9-6e97-4106-ac33-ab323da1ee58)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice19_genome_317ce_9687c0.json?c=gt-nuc_337&label=id:node_7225110

**Comment by aviczhl2** [comment]
> Hi @aviczhl2 for opening this one. I multiple times lost a lot of time trying tomunderstande the FR.1.1 tree. I never was able to draw any conclusion but to me everything is messed by 337 C337T that undergoes multiple reversions in the proposed branch and outside.

I just ignore 337 and it turns out that without 337 it still shall belong to FR.1.1 due to shared C1142T,T2372C, and T14961C.

**Comment by aviczhl2** [comment]
99 and in Japan
