### ISSUE TITLE
small saltation of XBB.1.22.1 with S:D228E, S:G769A and S:D1168E (6 seqs in 2 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#257]
Defining mutations: XBB.1.22.1>C25517T (ORF3a:P42L)>A8347G>C11674T, T22246G (S:D228E), G23868C (S:G769A), C24442T, C25066A (S:D1168E), A25974G, C27429T, C28603T
GISAID query: T28297C, A22161G, T22246G, G23868C, C25066A
Earliest seq: 2023-05-25 (Israel, EPI_ISL_17803812)
Most recent seq: 2023-06-13 (Austria, EPI_ISL_17827045)
Detected Countries: Austria (3), Israel (1)
![QQ截图20230626204019](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/5ab82f2f-d3e5-4cba-bf78-9fa517d4a303)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1344d_9763c0.json
A small but very new and interesting saltation (all aa mutations are on Spike, and it is neighbored with FY.4 sublineage). we can track it for a time. 
Genomes:
EPI_ISL_17782273, EPI_ISL_17803812, EPI_ISL_17810636, EPI_ISL_17827045

**Comment by FedeGueli** [comment]
Good catch @HynnSpylor wondering if this comes from Africa too.

**Comment by HynnSpylor** [comment]
1 more seq from Austria

**Comment by FedeGueli** [comment]
still circualting in Austria, likely slow.

**Comment by HynnSpylor** [comment]
designated as FY.7

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/4504d16228fdd4bfb694af226ac742ae9c77548d
