### ISSUE TITLE
#2037 + S:Q493L (22 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#258]
FU.1+A460G+S:Q493L(A23040T)

GISAID query:A460G,A23040T
No. of seqs: 8 (Shanghai 6 Singapore 1 Yunnan 1)
First seq: EPI_ISL_17725003, 2023-5-14, Shanghai
Latest: EPI_ISL_17836912, 2023-6-13 ,Shanghai

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_317ce_968770.json?branchLabel=Spike%20mutations&label=id:node_6607745&showBranchLabels=all)
<img width="1329" alt="Screenshot 2023-06-26 at 21 57 42" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/eca943a2-d635-4c61-968a-63cb0a1c71f2">

**Comment by FedeGueli** [comment]
It seems growing fast. lets see

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by FedeGueli** [comment]
1 seq only in august closing it .
