### ISSUE TITLE
GD.1 (S:Y453F) with S:F456L, definite international spread [2 seqs, USA, China]

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#262]
GISAID Query: Spike_V445P,Spike_Y453F,Spike_F456L
Nucs query : T18402C, G26640T, C28146T (edited)
Sequence 1: 2023-05-10, USA. EPI_ISL_17676308
Sequence 2: 2023-06-17, China. EPI_ISL_17836786

**Mutations:**

Spike_F456L
M_A40S
ORF8:P85S
N:T417I

[Usher Tree](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/fccd4624-c46a-470c-8b68-b8e64ade0fd5)

**Discussion:**
I'm opening this just to show that F456L can work with Y453F on XBB. Y453F hasn't appeared to be incompatible with F486P, but it is still managing to circulate (for now) with F486S. F456L is one of the main advantage-granting mutations on XBB at the moment, on an F486P background. 

One possible explanation is that Y453F and F486P haven't been successful because they give too much binding affinity. In this case, Y453F might make a return on F486P after more affinity-sacrificing mutations are present. I believe that the two sequences in this issue show that F456L won't disqualify a return of Y453F. 

Aside from that speculation -- these two sequences clearly cluster together due to the high number of shared mutations that are unique to them. GD.1 is most frequent in Mexico, so it's likely this proposed lineage didn't appear in either the USA or China.  

I'll wait for there to be at least 5 sequences before bringing to the main page.

**Comment by Over-There-Is** [comment]
/organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230619-2139/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 41; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-06-17"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Unite States"

**Comment by FedeGueli** [comment]
Still 2. i m closing this . if any new seq will pop up i will reopen
