### ISSUE TITLE
XBB.1.5.39 with 3 steps: FT.3, S:Q52H; FT.3.1, S:T478R and S:D1168H; FT.3.1 with S:A348S (20+1 seqs, mainly in the USA, 5+1 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#266]
<details><summary>Original proposal for what designated as FT.3 and FT.3.1 now: </summary>

_now this seems to be a 3-step, 1st S:Q52H, 2nd S:T478R and S:D1168H, 3rd S:A348S_

**Defining Mutations:** [_on top of XBB.1.5.39's T11316C/ORF1a:M3684T_] > G21718T(S:Q52H) > C6628T, A18366G, C22995G(S:T478R), G25064C(S:D1168H) >

**Query:** A18366G, C22995G, G25064C
**Earliest seq:** 2023-05-02 (EPI_ISL_17778244, New Mexico, USA)
**Latest seq:** 2023-06-21 (EPI_ISL_17960823, Arizona, USA)
**Sampled Countries:** USA (13, New Mexico/4, California/2, Texas/2, Maryland/1, Iowa/1, Arizona/1, New Jersey/1, Ohio/1), UK (8, all Scotland), Canada (2, all Ontario), Germany (1), Netherlands (1)

<details><summary>Genomes WITHOUT further S:A348S, query:A18366G, C22995G, G25064C, -G22604T: </summary>
EPI_ISL_17722784, EPI_ISL_17838316-17838320, EPI_ISL_17838474, EPI_ISL_17842741, EPI_ISL_17950377, EPI_ISL_17952151, EPI_ISL_17952164, EPI_ISL_17952446, EPI_ISL_17953468, EPI_ISL_17955753
</details>

<details><summary>Genomes WITH further S:A348S, query:G22604T, C22995G, G25064C: </summary>
EPI_ISL_17722787, EPI_ISL_17778244, EPI_ISL_17778247, EPI_ISL_17854262, EPI_ISL_17950631, EPI_ISL_17950921, EPI_ISL_17960823, EPI_ISL_17964557, EPI_ISL_17965738, EPI_ISL_17965766, EPI_ISL_17971244
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14ee2_8235a0.json?f_userOrOld=uploaded%20sample&showBranchLabels=all

Overview from XBB.1.5.39 polytomy:
![Overview2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/44516006-f62f-4fad-92b4-e2bc04bcb256)

Detailed view from S:Q52H branch:
![Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/069d4cbe-d2d8-4f6a-9fa3-b716801b169e)

**Trivia:**
- S:Q52H(G21718T) is on the rise, probably driven by EG.5.1, but also found on EE.4(BQ.1.1.4.4), GP.1(CH.1.1.11.1), XBB.2.10, probably it should be designated first? (XBB.1.5.39 with S:Q52H, query:T11316C, G21718T, T10204C returns 175 )
- S:D1168H is rare, only sampled 530-ish times during the whole pandemic, last wave was driven by some BA.2* and AY.122*
- Futher step S:A348S (G22604T), which is predicted to have extra immune escape.
- All three steps seems growing at the moment.

Tracking updates:

<details><summary>Update 1: 23-06-30, 4 seqs from the USA</summary>

previously GenBank sequence from Maryland: EPI_ISL_17854262
1 from Ohio EPI_ISL_17950921
1 from Cali EPI_ISL_17950631
1 from Jersey with metadata showing travel history to Switzerland: EPI_ISL_17950377
</details>

<details><summary>Update 2: 23-07-02, 3 seqs from UK and USA</summary>

2 previously non-GISAID seqs from Scotland: EPI_ISL_17952151, EPI_ISL_17952164
1 from Texas: EPI_ISL_17952446
</details>

<details><summary>Update 3: 23-07-06, 3 seqs from UK and USA</summary>

1 from Scotland: EPI_ISL_17953468
1 from Texas: EPI_ISL_17955753
1 from Arizona: EPI_ISL_17960823
</details>

<details><summary>UShER after 3 updates: </summary>

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_179_6768b0.json?f_userOrOld=uploaded%20sample&showBranchLabels=all
![Update3](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/35c887a9-aed5-414f-a7eb-74c21ab0a289)

</details>

<details><summary>Update 4: 23-07-07, 4 seqs from 3 countries</summary>

2 from New Mexico, USA:EPI_ISL_17965738, EPI_ISL_17965766

new entry:
1 from Germany: EPI_ISL_17964557
2 from Netherlands: EPI_ISL_17971244
</details>

<details><summary>Update 5: 23-07-13, 3 seqs from USA</summary>

1 from California: EPI_ISL_17979172
2 from Florida: EPI_ISL_17976613, EPI_ISL_17979199
</details>

<details><summary>Update 6: 23-07-15, 4 seqs from USA</summary>

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ba43_254bc0.json?f_userOrOld=uploaded%20sample&showBranchLabels=all
![update6](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1c8abaf7-7499-48c3-954c-dca013b4169d)

EPI_ISL_17985445, EPI_ISL_17985484, EPI_ISL_17985498, EPI_ISL_17985556
</details>

<details><summary>Update 7: 23-07-19, 3 seqs from USA</summary>

![update7](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f8249e64-20f3-414e-9a7d-018da025b98c)

Florida: EPI_ISL_17996258
New Mexico: EPI_ISL_18006013
New Jersey: EPI_ISL_18006058
</details>

<details><summary>Update 8: 23-07-23, 4 seqs from USA and Mexico</summary>

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a65_d52be0.json?f_userOrOld=uploaded%20sample
![update8](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/80b7dbb0-3560-40d5-84ff-87e436175c6d)

1 from California: EPI_ISL_18011163
1 from Puerto Rico:EPI_ISL_18012148

New entry: 
2 from Mexico: EPI_ISL_18011910, EPI_ISL_18011954

</details>

</details>

#### Further proposal for S:A348S sub-branch:

**Defining Mutations:** FT.3.1 > G22604T(S:A348S)
**Query:** G22604T, C22995G, G25064C
**Earliest seq:** 2023-05-02 (EPI_ISL_17778244, New Mexico, USA)
**Latest seq:** 2023-07-14 (EPI_ISL_18012787, Delaware, USA)
**Sampled Countries:** USA (15, New Mexico/5, Florida/3, New Jersey/2, Arizona/1, California/1, Delaware/1, Maryland/1, Ohio/1, Puerto Rico/1), Canada (1, Ontario), Germany (1), Mexico (1), Netherlands (1)

<details><summary>Genomes: </summary>
EPI_ISL_17722787, EPI_ISL_17778244, EPI_ISL_17778247, EPI_ISL_17854262, EPI_ISL_17950631, EPI_ISL_17950921, EPI_ISL_17960823, EPI_ISL_17964557, EPI_ISL_17965738, EPI_ISL_17965766, EPI_ISL_17971244, EPI_ISL_17976613, EPI_ISL_17979199, EPI_ISL_17985445, EPI_ISL_17985484, EPI_ISL_17996258, EPI_ISL_18006013, EPI_ISL_18011910, EPI_ISL_18012148, EPI_ISL_18012787
</details>

<details><summary>non-GISAID Genomes: </summary>
Wales/CLIMB-CM7Y8ID7/2023|2023-07-05
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_abe8_fbcff0.json?f_userOrOld=uploaded%20sample
![A348S](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8b0a0a7e-feb3-464d-9903-62ec2d35bea6)

**Comment by FedeGueli** [comment]
@NkRMnZr please when a lineage seems growing write a comment so i can see that growth.

**Comment by FedeGueli** [comment]
Please propose the lineage with S:A348S

**Comment by FedeGueli** [comment]
> > @NkRMnZr please when a lineage seems growing write a comment so i can see that growth.
> 
> The original proposal is for S:T478R and S:D1168H, not S:A348S, you can check the historical updates by clicking the drop-down button after "edited" [#266 (comment)](https://github.com/sars-cov-2-variants/lineage-proposals/issues/266#issuecomment-1615137165) . I'll update follow up S:A348S sequences there.

If you edit just the main text i m not notified of anything . So whem something happems please writen a comment.
