### ISSUE TITLE
GR.1 (S:V445S) may have acquired recently S:R403K  ( 3 sequences New York)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#269]
Defining mutations: GR.1 >> T20847C > Orf1a:D156N (G731A), C3583T, Orf1b:I748T (T15710C), C16173T, T20833C, S:r403K (G22770A), C26139T, C26822T

Gisaid query : G731A, C3583T, T15710C

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d95_c44cc0.json?c=userOrOld&label=id:node_6901126

Samples:
EPI_ISL_17810223, EPI_ISL_17859873

**Comment by HynnSpylor** [comment]
Ah I'm also preparing to propose it!
I suggest EPI_ISL_17859873 (also in New York) is another sample, as it is missing the site S:445 and nowadays almost XBB.1.5.42* seqs are GR.1*
 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/777db3a7-2380-4b3e-a973-e5e2fa312092)

**Comment by FedeGueli** [comment]
Thx  @HynnSpylor !

**Comment by FedeGueli** [comment]
@ryhisner did an analysis of this lineage , hope he will find time to share here.

**Comment by ryhisner** [comment]
This has the look of a molnupiravir-driven branch. If you count the mutations from the base of the branch to the most recent sequence, the molnupiravir signature is obvious. 
<img width="1356" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/8ebb14de-da4b-4f7f-8f4c-7e0cac0c63e2">

This last sequence has a lot of missing coverage (see spike below), so it likely has numerous additional mutations that weren't registered. 
<img width="1216" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0562839f-f595-4264-aa00-c8368371fe51">

The 2nd sequence sits on a fairly long branch which also has a pretty strong molnupiravir signature, as pictured below. 
<img width="1365" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/b7d44967-0ca2-494c-bc47-383503d28a25">

Most recent molnupiravir sequences from the USA seem to have come from New York. Partly that reflects the fact that New York has done more sequencing than other locations, but I think they may also be using MOV at higher rates than the rest of the country.

**Comment by FedeGueli** [comment]
it seems no more circulating
