### ISSUE TITLE
First XBB.1.9.1 with S:456L, likely started in Vietnam (20 seqs, 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#27]
This is the 1st XBB.1.9.1 sub-lineage with the popular S:F456L.

Sub-lineage of: XBB.1.9.1
Mutations on top of XBB.1.9.1: C28846T, G2174A(orf1a:E637K), T22928C(S:456L)
GISAID query: C28846T, G2174A, T22928C

No. of seqs: 15(3 USA 4 China 4 Vietnam 1 Singapore(from Vietnam) 2 France  1 Canada 1 South Korea(from Vietnam)

Note that all 3 green Vietnamese seqs have S:456 dropout, they're likely to also have 456L. 
GISAID query for the green Vietnamese seqs: C28846T, G2174A, G1464T,-T22928C,C12890T

First seq: 17481621, 2023-3-9, Vietnam
Latest seq: 17615437, 2023-4-24 ,France

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice17_genome_1570f_7df140.json?c=gt-S_456&label=id:node_5873226)
<img width="1400" alt="Screen Shot 2023-05-08 at 08 59 19" src="https://user-images.githubusercontent.com/10445944/236712772-69f50478-580d-4032-85cd-7a8f0a75bdb9.png">

**Comment by Over-There-Is** [comment]
C_AA011014.1 and EPI_ISL_17511861 are the same sequence.

**Comment by aviczhl2** [comment]
> C_AA011014.1 and EPI_ISL_17511861 are the same sequence.

15 only counts GISAID.

**Comment by aviczhl2** [comment]
20 seqs, new country of Japan.

**Comment by FedeGueli** [comment]
24 sequences as today last samples from Canada, South Korea, Japan .

I think this needs to be proposed in the main sublineage.

Feel free to choose a number of sequences after you will propose it in the other issue.

**Comment by aviczhl2** [comment]
Proposed in https://github.com/cov-lineages/pango-designation/issues/1994
