### ISSUE TITLE
Multiple XBB*+S:157L strains (A=23 quite slow, B assigned:EU.1.1.3, C assigned:XCF.1,D assigned:EG.5.1.6)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#274]
I was just looking at how XBB* was taking some other major variant's mutations. S:157L seems quite beneficial and occupying a rising fraction of XBB*. So I looked at a large tree about it and discovered these trees.
Large Tree Usher:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_31195_c8c190.json?f_userOrOld=uploaded%20sample
Variant 1:
G922T,T16785C,C22033A/S:F157L on FL.4.1
Inquiry: T16785C,C22033A,G922T (edited)
Sequences: 18 **Updated**
EPI_ISL_17696714, EPI_ISL_17696732-17696733, EPI_ISL_17765687,
EPI_ISL_17765690, EPI_ISL_17765692, EPI_ISL_17765752,
EPI_ISL_17765754, EPI_ISL_17790973, EPI_ISL_17811795,
EPI_ISL_17811799, EPI_ISL_17811806, EPI_ISL_17815954,
EPI_ISL_17816215, EPI_ISL_17816242, EPI_ISL_17816265,
EPI_ISL_17816271, EPI_ISL_17822224
Earliest: EPI_ISL_17696714 Australia, 05-09, 2023
Latest: EPI_ISL_17815954 Singapore, 06-14, 2023
Usher Individual Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_310ed_c92040.json?label=id:node_4922118
Distribution: Australia Origin, Spread to Singapore

-----------------------------------------------------------------
Variant 2: 
Mutations:C28045T(ORF8:A51V)+C22033A(S:157L)+C14322T on EU.1.1*
Inquiry: C22033A,C28045T,C14322T
Distribution: Austria,GERMANY, NORWAY,USA
Assigned as EU.1.1.3* (look #312 )
Sequences: 28 (**Updated**)
EPI_ISL_17685531, EPI_ISL_17700382, EPI_ISL_17700422,
EPI_ISL_17782526, EPI_ISL_17803439, EPI_ISL_17810615,
EPI_ISL_17826702, EPI_ISL_17826738, EPI_ISL_17826777,
EPI_ISL_17826963, EPI_ISL_17827001, EPI_ISL_17827098,
EPI_ISL_17827105, EPI_ISL_17827111, EPI_ISL_17833139,
EPI_ISL_17837081, EPI_ISL_17837085
Earliest: 
EPI_ISL_17685531 ,GERMANY, 05-02,2023
Latest: EPI_ISL_17827111 Austria 06-13,2023
Usher Individual Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26cf5_ca3a80.json?f_userOrOld=uploaded%20sample&label=id:node_4922117

------------------------------------------------------------------
Variant 3: 
Mutations: XCF+C22033A,C2062T,C27881T,C29632T 
**NOW DESIGNATED XCF.1** via  https://github.com/cov-lineages/pango-designation/commit/8a47ca9d0cadf81bafb16d1d5e5551149311a9d4
Inquiry: C22033A,   G4006A, C27881T (edited)
Sequences: 12 (**Updated**)
 EPI_ISL_17780686, EPI_ISL_17780703, EPI_ISL_17781571,
EPI_ISL_17813506, EPI_ISL_17815246, EPI_ISL_17831200,
EPI_ISL_17855371, EPI_ISL_17855466, EPI_ISL_17856150,
Earliest: EPI_ISL_17781571 France, 05-22,2023
Latest: EPI_ISL_17813506 Italy, 06-10, 2023
Distribution: France, USA and Italy
Individual Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28150_ca4520.json?f_userOrOld=uploaded%20sample 
Variant 4: ( proposed in #394) 
Mutations: EG.5.1*+C5837T (orf1a:S1857L)+C22033A(S:F157L)
Inquiry:Spike_F157L+T22930A,C2334T ( or C22033A,T22930A, C2334T Edited)
Sequences: EPI_ISL_17803964, EPI_ISL_17818492, EPI_ISL_17838394,
EPI_ISL_17885526, EPI_ISL_17885589, EPI_ISL_17949508,
EPI_ISL_17951685, EPI_ISL_17952407, EPI_ISL_17952448,
EPI_ISL_17956602, EPI_ISL_17960141
Earliest: EPI_ISL_17803964, England 05-27,2023
Latest: EPI_ISL_17951685, US 06-19,2023

Distribution: Probably from England, spread to US (multiple states), Italy, Ireland
Individual Usher Tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42fea_743c20.json?f_userOrOld=uploaded%20sample

Note: There is a very strange singlet in Yunnan as EPI_ISL_17808317 that I would take with caution. It appeared closest to variant D, yet it seems a messy combine with some XBB* mutations (specifically it got T22930A and S:Q52H and T28297C, so I am pretty sure it would be EG.5.1 trait) but also some BA.2.75* (the typical S:K147E, W152R,F157L for example)  mutations so I am not sure.
It is mentioned in potential recombination collection #108 and hypothesized as EG.5.1*+FR.1.3* recom. But given that the variant got S:K356T, a rather not common mutation in XBB* while defining of some BA.2.75* strains, I would argue it is probably more complex or just an artefect.

**Comment by krosa1910** [comment]
There is a large upload of lineage B, increasing it to 28 seqs total. 10 new Austrian and one German sequences.
No change to other proposed lineages.

**Comment by krosa1910** [comment]
A large upload in Germany and Austria makes variant B 40 seqs. It seems quite fast there. No changes to other two.

**Comment by Over-There-Is** [comment]
Yunnan/YNCDC-1164/2023|EPI_ISL_17808317|2023-05-27
![2023-07-08 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/a45a86b5-27cc-4cce-91c5-bd8dce7485fe)
does not contain C5837T, but the significant frameshift of FR.1(ins27791T)
Probably contamination sample of FR.1.3 and EG.5.1.1+T6736C, T23287C
Mutations from FR.1.3: C203T, C882T, C1471T, C1513T, C3796T, C3927T, C4586T, A12444G, C20235T, A22001G, T22016C, C22033A, A22121G, A22190G, A22629C, C25603T, A26275G, ins27791T, T28019C, G28374A, 
Mutations from EG.5.1.1: A405G, C6541T, *T6736C, C9693T, C12789T, G15451A, C15738T, T16342C, A16878T, A19326G, G21718T, T21810C, G22317T, G22895C, T22896C, T22930A, T23018C, T23019C, *T23287C, T28297C
Private mutations: G3152T, G15372C

EG.5.1.1+T6736C, T23287C branch have 3 more sequences.

**Comment by Over-There-Is** [comment]
Sorry, I means there are 3 more sequences can be the donor of the recombinant, this recombinant is not spreading.

**Comment by FedeGueli** [comment]
Variant 3 designated XCF.1

**Comment by FedeGueli** [comment]
i think EG.5.1 got S:F157L lemme check in depth.

**Comment by krosa1910** [comment]
A is apparently slow, B is descent, C assigned and D seems fast while Fed is watching it. I guess I will shift the main focus of this proposal to B then. ( If B is assigned and A does not give new sequence then I would consider closing it)

**Comment by FedeGueli** [comment]
Propose D please.

**Comment by FedeGueli** [comment]
Sorry i realized i proposed the Variant D separately. Variant A is not growing so fast.

**Comment by krosa1910** [comment]
> Sorry i realized i proposed the Variant D separately. Variant A is not growing so fast.

Agree,I am considering adding variant E/F under this proposal. But it may look weird to make big modification to one existing proposal. If I decided not to, then this proposal could be shut temporarily (B,C assigned, A slow, D discussed at newer proposal) while I propose E and F in a new proposal.

**Comment by FedeGueli** [comment]
just found also a couple seqs with it in XBB.1.5.71. yes please make a another proposal

**Comment by FedeGueli** [comment]
EG.5.1.6 alias D got designated closing this one for the moment.
