### ISSUE TITLE
Branch of XBB.1.5.18* with S:W152R, K478R (55) with a recent Mini Saltation lineage with Orf1a:A2345V (NSP3_A1627V) & Orf1b:M1581I (NSP14_M57I) (35) as of 20-8

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#275]
Mutations of the parent Branch: XBB.1.5.18*(XBB.1.5*+C7164T(orf1a: T2300I)) plus  T8601C, C21697T ,G7058A(orf1a: G2265S), , T22016A (S:W152R), A22995G(S:K478R)
Note: T27384C, a mutation that belongs to all BA.2* descendent have weirdly disappeared and reappeared in this whole variant, I would consider it as imperfect sequencing techniques.
Tree:
![Schermata 2023-06-29 alle 09 22 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fcfbaa10-0b88-4c54-a1b7-822cddff4e78)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_fbdc_cb8ed0.json?c=gt-S_478&label=id:node_6837059
Gisaid query: C7164T , T22016A , C22995G (edited)
Sequences: 29 (as 07/07)
EPI_ISL_17204559, EPI_ISL_17232278, EPI_ISL_17306893,
EPI_ISL_17319686, EPI_ISL_17346299, EPI_ISL_17385648,
EPI_ISL_17385794, EPI_ISL_17386279, EPI_ISL_17444921,
EPI_ISL_17502406, EPI_ISL_17506169, EPI_ISL_17657465,
EPI_ISL_17660242, EPI_ISL_17676100, EPI_ISL_17676249,
EPI_ISL_17743391, EPI_ISL_17789137, EPI_ISL_17849241,
EPI_ISL_17850072, EPI_ISL_17851510, EPI_ISL_17851544,
EPI_ISL_17852362

The latest 6 （7， gisaid just updates) sequences belong to a relatively small saltation with three extra mutations:
A5821G, C7299T(Orf1a:A2345V = NSP3_A1627V),G18210T(Orf1ab:M5982I=Orf1b:M1581I =NSP14_M57I)
**edited : pls use [Codon2Nucleotide](https://codon2nucleotide.theo.io/) or the little trick: ( Orf1ab -4401 = Orf1b)**
Gisaid query : C7164T , T22016A , A5821G, C7299T (edited)
Sequences: 12 (as 07/07)
EPI_ISL_17789137, EPI_ISL_17849241, EPI_ISL_17850072,
EPI_ISL_17851510, EPI_ISL_17851544, EPI_ISL_17852362,
EPI_ISL_17872403

Earliest Sequence: EPI_ISL_17204559 France 02-28,2023
Earliest New Saltation Sequence: EPI_ISL_17852362 US, 05-11,2023
Latest Sequence (in new saltation branch) :EPI_ISL_17849241 Canada 06-20,2023
Spread and Origin: The original tree appeared first in France, then Canada, the new saltation appeared in USA first, spread to Italy, Canada.

Comments: S:W152R is one of the less noticed mutations of BA.2.75*, and it sproadically appeared in other strains like this one. That combined with S:K478R makes this variant promising, instead of rising it stayed low for a while. Yet the new saltation seems to provide it with some new momentum and I would like to see if it could spread further.  As it already spread to a different continent at 7 seqs, it is likely that it would keep expanding in the following weeks.

**Comment by FedeGueli** [comment]
Spotted this one too on Monday , good you proposed . i ve added the tre that was missing

**Comment by krosa1910** [comment]
Very interestingly this new sub-saltation spread to Dominica with 3 seqs, also +1 for USA.
There is also a French one updated on the parent branch, itself is quite different from the parent and gained S:Q613H.

**Comment by krosa1910** [comment]
new sequences in Dominica and other North America places. I would wonder if this could spread there as it seems FL.1.5.1 is reaching complete dominance there.

**Comment by krosa1910** [comment]
Coming back from some busy summer job, and it is time for me to review my issues.
For this one, it seems like the parent branch stayed dormant, as the most recent seq was collected about two months ago. The child branch have grown to 25 seqs, with several additional seqs not on Gisaid (have not counted exact number).

**Comment by FedeGueli** [comment]
The saltation lineage seems going quite well please propose it.

![Schermata 2023-08-20 alle 09 45 53](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f2ba9d3f-70a0-4ce0-a6d8-b0f7e7475250)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C7164T%2CT22016A%2CA5821G%2CC7299T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
ping @krosa1910 please propose it.

**Comment by krosa1910** [comment]
> C7164T , T22016A , C22995G

I would propose this (probably discarding the parent as it disappeared after . It seemed to further acquire a branch with S:E554Q, similar to commonly acquired S:E554K but predicted to be very beneficial).
