### ISSUE TITLE
XBB.1.16 with ORF7a:T39I (422 seqs, 22 countries), further gained N:P13F, S:D1153Y, and S:F456L (2 seqs, France)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#276]
**Defining Mutations:** XBB.1.16 > C27509T(ORF7a:T39I)
**Query:** C29386T, A28447G, C27509T, -G284A, -T29410C, -A4681T, -C24382T, -G420T, -T3802C
**Earliest seq:** 2023-03-08 (EPI_ISL_17270013, Gujarat, India)
**Latest seq:** 2023-06-13 (EPI_ISL_17814779, Ontario, Canada)
**Sampled Countries:** China (84, Shanghai/12, Sichuan/12, Guangdong/11, Liaoning/8, Hongkong/7, Fujian/6, Heilongjiang/5, Taiwan/5, Hubei/4, Yunnan/4, Henan/3, Jiangxi/2, Qinghai/2, Beijing/1, Gansu/1, Jiangsu/1), USA (43, California/15, Michigan/4, Virginia/4, Washington/4, Illinois/2, New Jersey/2, New York/2, Vermont/2, Arizona/1, Florida/1, Georgia/1, Hawaii/1, Kentucky/1, Missouri/1, Ohio/1, Tennessee/1), India (31, Gujarat/7, Maharashtra/7, Karnataka/5, Tamil Nadu/5, Rajasthan/2, Chhattisgarh/1, Madhya/1, Odisha/1, Puducherry/1, Telangana/1), South Korea (23), Australia (19, Victoria/10, NSW/8, ACT/1), UK (17, England/16, Scotland/1), Thailand (15), Japan (14), Israel (8), Singapore (7), Canada (6, Ontario/4, Alberta/1, New Brunswick/1), France (3), Germany (3), Indonesia (3), Sweden (2), Austria (1), Brunei (1), Finland (1), Mauritius(1), Norway (1), Russia (1), 

<details><summary>Genomes: </summary>
EPI_ISL_17244711, EPI_ISL_17262440, EPI_ISL_17270013,
EPI_ISL_17280612, EPI_ISL_17326775, EPI_ISL_17349567,
EPI_ISL_17412158, EPI_ISL_17427663, EPI_ISL_17428150,
EPI_ISL_17428388, EPI_ISL_17428399, EPI_ISL_17433585,
EPI_ISL_17445754, EPI_ISL_17464002, EPI_ISL_17473050,
EPI_ISL_17478181, EPI_ISL_17483727, EPI_ISL_17483810,
EPI_ISL_17486535, EPI_ISL_17496228, EPI_ISL_17497497,
EPI_ISL_17499634, EPI_ISL_17500475, EPI_ISL_17500630,
EPI_ISL_17510925, EPI_ISL_17511452, EPI_ISL_17516232,
EPI_ISL_17516413, EPI_ISL_17519019, EPI_ISL_17526968,
EPI_ISL_17535358, EPI_ISL_17537793-17537794, EPI_ISL_17537805,
EPI_ISL_17537888, EPI_ISL_17538761, EPI_ISL_17539405,
EPI_ISL_17539422, EPI_ISL_17548048, EPI_ISL_17550869,
EPI_ISL_17553754, EPI_ISL_17558112, EPI_ISL_17558193,
EPI_ISL_17558205, EPI_ISL_17558242, EPI_ISL_17558261,
EPI_ISL_17582142, EPI_ISL_17584665, EPI_ISL_17586056,
EPI_ISL_17586421, EPI_ISL_17587053, EPI_ISL_17596142,
EPI_ISL_17601910, EPI_ISL_17602000, EPI_ISL_17608686,
EPI_ISL_17608878, EPI_ISL_17613527, EPI_ISL_17614352,
EPI_ISL_17615846, EPI_ISL_17618288, EPI_ISL_17618342,
EPI_ISL_17618350, EPI_ISL_17622208, EPI_ISL_17623946,
EPI_ISL_17626983, EPI_ISL_17627112, EPI_ISL_17629763,
EPI_ISL_17629966, EPI_ISL_17629977, EPI_ISL_17630458,
EPI_ISL_17633743, EPI_ISL_17637617, EPI_ISL_17640505,
EPI_ISL_17645661, EPI_ISL_17646192, EPI_ISL_17646979,
EPI_ISL_17648909, EPI_ISL_17651424, EPI_ISL_17652383-17652384,
EPI_ISL_17653070, EPI_ISL_17656890, EPI_ISL_17656904,
EPI_ISL_17657004, EPI_ISL_17657018, EPI_ISL_17661343,
EPI_ISL_17661767, EPI_ISL_17663275, EPI_ISL_17663286,
EPI_ISL_17664557, EPI_ISL_17665938, EPI_ISL_17667465,
EPI_ISL_17672435, EPI_ISL_17672467, EPI_ISL_17677425,
EPI_ISL_17677520, EPI_ISL_17677527, EPI_ISL_17677650,
EPI_ISL_17678543, EPI_ISL_17680399, EPI_ISL_17681290,
EPI_ISL_17681565, EPI_ISL_17683537, EPI_ISL_17683553,
EPI_ISL_17683653, EPI_ISL_17684097, EPI_ISL_17684102,
EPI_ISL_17684323, EPI_ISL_17686328, EPI_ISL_17686446,
EPI_ISL_17687869, EPI_ISL_17689361, EPI_ISL_17689771,
EPI_ISL_17689817, EPI_ISL_17689927, EPI_ISL_17690966,
EPI_ISL_17692067, EPI_ISL_17692121, EPI_ISL_17692243,
EPI_ISL_17694956, EPI_ISL_17696973, EPI_ISL_17697656,
EPI_ISL_17697680, EPI_ISL_17697749, EPI_ISL_17697921,
EPI_ISL_17697971, EPI_ISL_17698006, EPI_ISL_17698051,
EPI_ISL_17698096, EPI_ISL_17698242, EPI_ISL_17698291,
EPI_ISL_17699415, EPI_ISL_17700670, EPI_ISL_17701808,
EPI_ISL_17703937, EPI_ISL_17704274, EPI_ISL_17704816,
EPI_ISL_17705155, EPI_ISL_17706045, EPI_ISL_17706088,
EPI_ISL_17707087, EPI_ISL_17709517, EPI_ISL_17710126,
EPI_ISL_17711148, EPI_ISL_17711237, EPI_ISL_17714338-17714339,
EPI_ISL_17714349, EPI_ISL_17714850, EPI_ISL_17716152,
EPI_ISL_17718766, EPI_ISL_17718845, EPI_ISL_17719669,
EPI_ISL_17719936, EPI_ISL_17720422, EPI_ISL_17720457,
EPI_ISL_17720567, EPI_ISL_17720641, EPI_ISL_17720790,
EPI_ISL_17721632, EPI_ISL_17723274, EPI_ISL_17724053,
EPI_ISL_17725420, EPI_ISL_17729601, EPI_ISL_17729872,
EPI_ISL_17730007, EPI_ISL_17730156, EPI_ISL_17731819,
EPI_ISL_17731855, EPI_ISL_17732753, EPI_ISL_17734635,
EPI_ISL_17734708, EPI_ISL_17736030, EPI_ISL_17739679,
EPI_ISL_17739835, EPI_ISL_17741544, EPI_ISL_17741763,
EPI_ISL_17742209, EPI_ISL_17742212, EPI_ISL_17742230,
EPI_ISL_17743936, EPI_ISL_17744360, EPI_ISL_17744692,
EPI_ISL_17744731, EPI_ISL_17762917, EPI_ISL_17763272,
EPI_ISL_17764843, EPI_ISL_17766577, EPI_ISL_17766663,
EPI_ISL_17769930, EPI_ISL_17770243, EPI_ISL_17773392,
EPI_ISL_17774373, EPI_ISL_17775074, EPI_ISL_17779142,
EPI_ISL_17779384, EPI_ISL_17780695, EPI_ISL_17784190,
EPI_ISL_17784231, EPI_ISL_17785016, EPI_ISL_17785906,
EPI_ISL_17785915, EPI_ISL_17786917, EPI_ISL_17786927,
EPI_ISL_17786992, EPI_ISL_17789897, EPI_ISL_17790228,
EPI_ISL_17790657, EPI_ISL_17790703, EPI_ISL_17791900,
EPI_ISL_17791914, EPI_ISL_17791937, EPI_ISL_17792389,
EPI_ISL_17792551, EPI_ISL_17794030, EPI_ISL_17794818,
EPI_ISL_17794879, EPI_ISL_17795227, EPI_ISL_17795531,
EPI_ISL_17801918, EPI_ISL_17801987, EPI_ISL_17802056,
EPI_ISL_17802701, EPI_ISL_17802714, EPI_ISL_17802848,
EPI_ISL_17803241, EPI_ISL_17803764, EPI_ISL_17804063,
EPI_ISL_17807341, EPI_ISL_17807568, EPI_ISL_17808006,
EPI_ISL_17808110, EPI_ISL_17808123, EPI_ISL_17808435,
EPI_ISL_17811334, EPI_ISL_17811342, EPI_ISL_17811344,
EPI_ISL_17811408, EPI_ISL_17811686, EPI_ISL_17813244,
EPI_ISL_17814779, EPI_ISL_17815036, EPI_ISL_17816278,
EPI_ISL_17816297, EPI_ISL_17816349, EPI_ISL_17816625,
EPI_ISL_17816985, EPI_ISL_17819801, EPI_ISL_17830369,
EPI_ISL_17830690, EPI_ISL_17834778, EPI_ISL_17834899,
EPI_ISL_17834931, EPI_ISL_17835095, EPI_ISL_17835154,
EPI_ISL_17835711, EPI_ISL_17836108, EPI_ISL_17836639,
EPI_ISL_17837055, EPI_ISL_17838108, EPI_ISL_17838232,
EPI_ISL_17838386, EPI_ISL_17838407, EPI_ISL_17848414,
EPI_ISL_17848446, EPI_ISL_17850196, EPI_ISL_17850300,
EPI_ISL_17850409, EPI_ISL_17850593, EPI_ISL_17850624,
EPI_ISL_17850628, EPI_ISL_17850702, EPI_ISL_17850729,
EPI_ISL_17850732, EPI_ISL_17850773-17850774, EPI_ISL_17850778-17850779,
EPI_ISL_17850782, EPI_ISL_17852289, EPI_ISL_17854578,
EPI_ISL_17879336, EPI_ISL_17880193, EPI_ISL_17880230,
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1eab9_d3d9d0.json?c=country&label=id:node_6611214

view from XBB.1.16 polytomy
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c4a3ea58-13d3-4999-b2f3-fe413adb9cb6)

ORF7a:T39I branch diversity check:
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/01d149bf-6672-4b0a-89d4-310f1c7539ae)
notable mutations like N:A398V, S:Q675H and XBB's definition-changing N:P13F(from N:P13L) are on the rise.

**Trivia:**
- One of the large, undesignated branches of XBB.1.16.
- Despite low seqs count, there seems to be a 8% prevalence rate in Thailand at some point, and many seqs from airport screening with metadata shows travel history to India or Thailand.
![thailand](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e7653ae5-ab6a-41b4-9ff1-59ef138d76d3)
- Newly emerged N:P13F + S:D1153Y + S:F456L, query: T22928C, G25019T, C16134T, 2

**Comment by FedeGueli** [comment]
Interesting thx Orf7a:39 is quite a hotspot of mutations . N:A398V seems the main branch circualting in China. Likely this is circualting in taiwan too.

**Comment by FedeGueli** [comment]
Just noticed that a little sublineage of the N:A398V has one sample from Okinawa uploaded today (that is experimenting a bad covid wave right now) and two  caught by american airport surveillance and one of these two was from Japan:
![Schermata 2023-06-29 alle 18 40 02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/747ebc29-1795-4e73-a38d-b4f72d6f334f)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_267c7_dae1d0.json?c=userOrOld&label=id:node_10455558 . Not sure if the S:261V mutation is real. Japan had an issue in the past with that residue but the two american sequences have it too so maybe is it real this time?
