### ISSUE TITLE
XBB.1.5.55 with N:P13F and S:T478R (26 seqs, 6 countries), further gained S:E554K (4 seqs, Mexico)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#277]
**Defining Mutations:** XBB.1.5.55 > C28310T (N:P13F on top of existing C28311T/N:P13L) > C29095T > C22995G (S:T478R on top of existing C22995A/S:T478K)
**Query:** C22995G,C29095T,C28310T
**Earliest seq:** 2023-05-09 (EPI_ISL_17831851, Chile)
**Latest seq:** 2023-06-08 (EPI_ISL_17842458, Mexico)
**Sampled Countries:** USA (5, Georgia/3, California/1, Delaware/1), Mexico (2), Chile (1), Germany (1), Spain (1)

<details><summary>GISAID Genomes: </summary>
EPI_ISL_17700429, EPI_ISL_17716775, EPI_ISL_17716845, EPI_ISL_17831819, EPI_ISL_17831851, EPI_ISL_17833150, EPI_ISL_17833533, EPI_ISL_17842439, EPI_ISL_17842458, EPI_ISL_17854119
</details>

<details><summary>GenBank Genomes: </summary>

USA/NY-PRL-230601_81G10/2023|OR122416.1|2023-05-28,
USA/NY-PRL-230606_81C11/2023|OR144067.1|2023-06-07
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1601f_d57fe0.json?f_userOrOld=uploaded%20sample&showBranchLabels=all

view from XBB.1.5.55 polytomy
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/48c246c0-4ec3-4bae-957c-d8429d12bb13)

details:
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3ffd0874-5c12-4178-acf4-0269c2a94bc7)

**Comment by FedeGueli** [comment]
Although small i suspect this is more widespread we are seeing. Interestingly Mexico was the first country hit by S:T478K with B.1.1.519 before Delta in early 2021. So it makes sense S:T478R could do something there also on a no super fast backbone as XBB.1.5.55.

**Comment by aviczhl2** [comment]
also in China now.

**Comment by FedeGueli** [comment]
> Oh wait, this has been designated as HP.1 and HP.1.1
> 
> @FedeGueli need milestone for this, I'll monitor S:E554K from my private lineage tracker

thanks i completely missed it!

**Comment by FedeGueli** [comment]
from https://github.com/cov-lineages/pango-designation/commit/b4aa752b61815f3d9f277d07a380a469ef198b64
