### ISSUE TITLE
XBB.1.5 with ORF1a:P971S (nsp3_P153S), ORF7a:Q94H and S:F456L (26 seqs, mainly in the USA, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#279]
**Defining Mutations:** [On top of XBB.1.5's T17124C > T23018C] > C3176T(ORF1a:P971S) > G17079A, T22930G(S:F456L), A27675C(ORF7a:Q94H), C29323T
**Query:** G17079A, T22930G, A27675C
**Earliest seq:** 2023-03-01 (EPI_ISL_17211530, Illinois, USA)
**Latest seq:** 2023-06-07 (EPI_ISL_17832663, England, UK)
**Sampled Countries:** USA (19, Virginia/4, California/3, Illinois/3, Arizona/2, New York/2, Florida/1, Iowa/1, Michigan/1, North Carolina/1, New Jersey/1), France (3), UK (2, all England), Israel (1)

<details><summary>Genomes: </summary>
EPI_ISL_17211530, EPI_ISL_17259243, EPI_ISL_17321326, EPI_ISL_17333376, EPI_ISL_17373355, EPI_ISL_17430054, EPI_ISL_17524669, EPI_ISL_17585436, EPI_ISL_17585469, EPI_ISL_17588599, EPI_ISL_17618893, EPI_ISL_17639662, EPI_ISL_17657627, EPI_ISL_17673604, EPI_ISL_17694227, EPI_ISL_17694228, EPI_ISL_17768067, EPI_ISL_17789201, EPI_ISL_17803716, EPI_ISL_17803985, EPI_ISL_17832663, EPI_ISL_17853897, EPI_ISL_17854730, EPI_ISL_17855048, EPI_ISL_17855890
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38869_d69ad0.json?f_userOrOld=uploaded%20sample

view from XBB.1.5 polytomy:
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d31b6799-e8a5-4fcd-ab9a-c97753f31001)

details:
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/90f61fcc-8be7-4f52-a56c-e18be515de2d)

**Trivia:**
- This lineage started early March in the USA, seemlingly dying off but now is on a second drive.

**Comment by FedeGueli** [comment]
it seems very slow (surprisingly) closing it for now.
