### ISSUE TITLE
More than 300 seqs on a XBB.1.9.1->G2235A(FL.10)->C4234T->T7995G->T4234C->A2235G flip-flop branch.

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#28]
There are more than 300 seqs on this branch, I guess some fix is needed. @AngieHinrichs

Interestingly, C4234T is one of XBB.2.3's defining mutation. Don't know whether this is coincidence, convergence, or some sorts of recombination(unlikely) involved here.  

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice8_genome_7161_8780e0.json?branchLabel=nuc%20mutations&label=id:node_5876039)
<img width="1403" alt="Screen Shot 2023-05-08 at 12 47 57" src="https://user-images.githubusercontent.com/10445944/236736427-b0ece6e3-3c94-4686-b363-6ae01d6f7061.png">

**Comment by AngieHinrichs** [comment]
Thanks, I will work on this today.

**Comment by FedeGueli** [comment]
@AngieHinrichs @aviczhl2 has this been resolved? if yes please close it. If it is real or it is really a recombinant please update it.

**Comment by AngieHinrichs** [comment]
The double flip-flop (on both 4234 and 2235) is gone, although FL.10 has two branches with C4234T where it should have one, and there is still a branch (all BHR/Bahrain sequences) that starts with T7995G and then has a reversion on 2235.  I wonder if the Bahrain-only T7995G is real or a bad-batch effect.  If there are no more sequences on it then it won't matter.  🙂  I'll see if I can unify C4234T.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs ! i leave this open to.discuss further if that reversion is real or not.

**Comment by FedeGueli** [comment]
The sublineage of this one with S:E554K has been designated FL.10.1 and i have checked no one of the other branches of it has any schance to compete with it.
More : the tree seems quite clear.
![Schermata 2023-06-10 alle 14 36 16](https://github.com/sars-cov-2-variants/lineage-proposals/as
