### ISSUE TITLE
XBB.2.3 with S:T883I in a branch with  a BA.2 defining reversion at Orf1a:S135S. It seems circulating recently in Japan ( 59 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#281]
Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20dc7_d9b000.json?c=userOrOld&label=id:node_7019531
![Schermata 2023-06-29 alle 17 02 58](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7c4ce6d5-4a52-4b10-882d-69d805bdb118)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20dc7_d9b000.json?c=userOrOld&label=id:node_7019531

Defining mutations:
XBB.2.3 >> > C13959T > Orf1a:S135S REV (G670T), C2119T > Orf1a:D3042N (G9389A = NSP4_D279N), C25797T > G14712T, S:T883I (C24210T) 

Gisaid query : C25797T ,G14712T,C2119T

Samples : 18
First: 
hCoV-19/Japan/PG-526676/2023 | Original | EPI_ISL_17882431 | 2023-05-02
Last : 
hCoV-19/Japan/SUPCRC-5180/2023 | Original | EPI_ISL_17820050 | 2023-06-14

**Comment by FedeGueli** [comment]
This is going on spreading in Japan. maybe worth proposing? @aviczhl2 @hynnspylor @ryhisner qhat do you think?

**Comment by aviczhl2** [comment]
There's one seq from USA, 17961064

So agreed to propose.

**Comment by HynnSpylor** [comment]
Yeah I agree to propose in main page (for the international transimission)

**Comment by FedeGueli** [comment]
TY all proposing it.

**Comment by FedeGueli** [comment]
Designated XBB.2.3.21 via https://github.com/cov-lineages/pango-designation/commit/3106b904fbfd7d13c3882e7ebc49c16934f2afa2
