### ISSUE TITLE
XBB.1.9.1 with S:Q613H, S:A688V ,Orf3a:N82S  and Orf1b:I539V( 75 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#284]
I spotted this one looking at Japanese samples it is already interesting and widespread in far eaastern asian countries.

XBB.1.9.1 >> C22570T >Orf1b:I539V (A15082G), S:Q613H (G23401T), S:A688V (C23625T), Orf3a:N82S (A25637G)

Gisaid query: **A15082G, G23401T, C23625T** 

Samples : 67
from
![Schermata 2023-06-29 alle 20 34 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b68bc11b-4c27-472c-9397-66f0d53580a2) plus Slovenia that uploaded one today and Georgia that uploaded yesterday

IDs:
First: hCoV-19/Israel/ICH-741197348/2023 | Original | EPI_ISL_17483798 | 2023-03-30
Last:hCoV-19/Hubei/HCDC-SY2112/2023 | Original | EPI_ISL_17837030 | 2023-06-12

EPI_ISL_17442740, EPI_ISL_17483798, EPI_ISL_17491072-17491073,
EPI_ISL_17537315, EPI_ISL_17547936, EPI_ISL_17550795,
EPI_ISL_17563824, EPI_ISL_17589334, EPI_ISL_17605230,
EPI_ISL_17605910, EPI_ISL_17648637, EPI_ISL_17652331,
EPI_ISL_17684392, EPI_ISL_17690890, EPI_ISL_17691337,
EPI_ISL_17691514, EPI_ISL_17698309, EPI_ISL_17706996,
EPI_ISL_17724087, EPI_ISL_17730474, EPI_ISL_17730478,
EPI_ISL_17730815, EPI_ISL_17739535, EPI_ISL_17740587,
EPI_ISL_17741285, EPI_ISL_17741605, EPI_ISL_17778842,
EPI_ISL_17778844, EPI_ISL_17779069, EPI_ISL_17779385,
EPI_ISL_17779419, EPI_ISL_17779601, EPI_ISL_17779812,
EPI_ISL_17785327, EPI_ISL_17794082, EPI_ISL_17794098,
EPI_ISL_17801801, EPI_ISL_17807088, EPI_ISL_17807198,
EPI_ISL_17807340, EPI_ISL_17807527, EPI_ISL_17807583-17807584,
EPI_ISL_17807882, EPI_ISL_17807917, EPI_ISL_17808308,
EPI_ISL_17810660, EPI_ISL_17818246, EPI_ISL_17818302,
EPI_ISL_17819814, EPI_ISL_17826901, EPI_ISL_17830490,
EPI_ISL_17831426, EPI_ISL_17831508, EPI_ISL_17832599,
EPI_ISL_17832780, EPI_ISL_17834723, EPI_ISL_17837030,
EPI_ISL_17853974, EPI_ISL_17856814, EPI_ISL_17876321,
EPI_ISL_17879308, EPI_ISL_17883007, EPI_ISL_17883953,
EPI_ISL_17883960, EPI_ISL_17884731

Tree:
![Schermata 2023-06-29 alle 20 35 52](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8e305784-2832-457e-9d1c-66db062d4c6e)
![Schermata 2023-06-29 alle 20 36 29](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c1f01f7f-43be-4c88-ab7e-ffb74e49beb1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41d58_dcc3d0.json?c=country&label=id:node_6648391

**Comment by aviczhl2** [comment]
Seems to spread around Russia?

**Comment by FedeGueli** [comment]
> Seems to spread around Russia?

yeah maybe i saw the Crimean sample.
