### ISSUE TITLE
Multiple XBB.1.5.1 Lineages with S:T478R (28/12/7)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#286]
<a name="task_header"></a>
```[tasklist]
### Multiple XBB.1.5.1 Lineages with S:T478R
- [ ] [Branch 1](#branch_1): XBB.1.5.1 > T22615C > T23272A > C18252T > C22995G(**S:T478R**) [Query: `T22615C, T23272A, C22995G`, 28 seqs, 08/21]
- [ ] [Branch 2](#branch_2): XBB.1.5.1 > C8389T > C17528T(ORF1b:T1354I), C22995G(**S:T478R**) [Query: `C8389T, C17528T, C22995G` 12 seqs, 09/02]
- [ ] [Branch 3](#branch_3): XBB.1.5.1 > C22995G(**S:T478R**) > G11464A(ORF1a:M3733I), A16474G(ORF1b:S1003G), T28177C(ORF8:L95S), C29077T [Query: `G11464A, A16474G, T28177C`, 7 seqs, 08/25]
```

<a name="branch_1"></a>
### Branch 1

**Defining Mutations:** `XBB.1.5.1` > `T22615C` > `T23272A` > `C18252T` > `C22995G(S:T478R)`
**Query:** `T22615C, T23272A, C22995G`
**Earliest seq:** 2023-03-16 (`EPI_ISL_17879238`, Adygea, Russia)
**Latest seq:** 2023-06-12 (`EPI_ISL_17837325`, France)
**Sampled Countries:** France (5), Austria (3), Sweden (3), USA (3, NY/2, Virginia/1), Russia (1), China (1, Shanghai), South Korea (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17472681, EPI_ISL_17669078, EPI_ISL_17670883, EPI_ISL_17717543, EPI_ISL_17731527, EPI_ISL_17743384, EPI_ISL_17764255, EPI_ISL_17779253, EPI_ISL_17781596, EPI_ISL_17786449, EPI_ISL_17786494, EPI_ISL_17826749, EPI_ISL_17826886, EPI_ISL_17836960, EPI_ISL_17837325, EPI_ISL_17852250, EPI_ISL_17879238`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d865_e1e830.json?c=gt-S_478&f_userOrOld=uploaded%20sample&label=id:node_6792097

view from XBB.1.5.1 polytomy, note there's a `T10204C` branch (also got sub-branches with S:T478R, and S:T478N, unrelated to this proposal) probably misplaced here, having a lot of reversions and flip-flops
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/93fad0d6-c1dc-4432-94bb-e9e7fac88450)

detailed view from `T22615C` branch
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/fdc65185-6ab7-403c-8ebd-286ae08ee3af)

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2

**Defining Mutations:** `XBB.1.5.1` > `C8389T` > `C17528T(ORF1b:T1354I), C22995G(S:T478R)`
**Query:** `C8389T, C17528T, C22995G`
**Earliest seq:** 2023-07-12 (`EPI_ISL_18069659`, California, USA)
**Latest seq:** 2023-07-30 (`EPI_ISL_18075851`, California, USA, Travel history: China)
**Sampled Countries:** USA (5)

<details><summary>Genomes: </summary>

`EPI_ISL_18069659, EPI_ISL_18069828, EPI_ISL_18069961, EPI_ISL_18075823, EPI_ISL_18075851`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f711_3ae980.json?f_userOrOld=uploaded%20sample
![Branch2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a07e74cc-ae08-4dae-bf1d-5e02895af391)

[Back to Tasklist](#task_header)

---

<a name="branch_3"></a>
### Branch 3

**Defining Mutations:** `XBB.1.5.1` > `C22995G(S:T478R)` > `G11464A(ORF1a:M3733I), A16474G(ORF1b:S1003G), T28177C(ORF8:L95S), C29077T`
**Query:** `G11464A, A16474G, T28177C`
**Earliest seq:** 2023-05-31 (`EPI_ISL_17788993`, California, USA)
**Latest seq:** 2023-08-08 (`EPI_ISL_18119772`, Texas, USA)
**Sampled Countries:** USA (6), Mexico (2)

<details><summary>Genomes: </summary>

`EPI_ISL_17477743, EPI_ISL_17788993, EPI_ISL_17997950, EPI_ISL_18011943, EPI_ISL_18099118, EPI_ISL_18119747, EPI_ISL_18119772, EPI_ISL_18137402`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4329b_9eb3f0.json?label=id:node_7213190
![Branch3](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bab8a18c-4ac7-45ff-bd95-e1a1a17d0912)

[Back to Tasklist](#task_header)

**Comment by FedeGueli** [comment]
Growth dis/advantages: (26-08)
B1:
-29% 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T22615C%2CT23272A%2CC22995G&analysisMode=CompareToBaseline&

B2:
+
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C8389T%2CC17528T%2CC22995G&analysisMode=CompareToBaseline&

B3:
-
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G11464A%2CA16474G%2CT28177C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
They cant compete closing for now.

**Comment by FedeGueli** [comment]
> There's a singlet from Branch 1 piling up some spike mutations through stepwise evolution: `USA/CA-SC-282562/2023|EPI_ISL_18797278|2023-12-15`, which got additional `D253G`, `F456L`, `L455F` and `S704L` https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_649dc_b55b60.json?label=id:node_3909980 ![image](https://private-user-images.githubusercontent.com/125747944/298257402-c6db8783-43a6-423d-aa62-3145f842912e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDI5MDcsIm5iZiI6MTcwNTc0MjYwNywicGF0aCI6Ii8xMjU3NDc5NDQvMjk4MjU3NDAyLWM2ZGI4NzgzLTQzYTYtNDIzZC1hYTYyLTMxNDVmODQyOTEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwOTIzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDY1ZTA1MmZhYjdlZWUyZmM3YTRmMGViZWEwNzc0MmU1Njg4MGNlODgyYjI5NDA1MTFhZDhkNTNkODA2YTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vCfl5xJ9ii7CF0_vfiFp8p6eFPRYc38t4JP7ZfGkhxc)

good spot , that could be also the resultant of some sparse recombination event. lets see if any other seq pops up , in that case better analzying it in depth and proposing here in a separate issue.
