### ISSUE TITLE
Multiple CJ.1.3 branches circulating around Korea and Japan

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#287]
```[tasklist]
### Multiple CJ.1.3 branches circulating around Korea and Japan
- [ ] Branch 1: CJ.1.3 > T11618C(ORF1a:F3785L) > G24368C(S:D936H) [Query: T11618C, G24368C, 198]
- [ ] Branch 2: CJ.1.3 > T11618C(ORF1a:F3785L) > T28251G(ORF8:F120V), A28254C(ORF8:I121L) [Query: T11618C, T28251G, A28254C, 120]
- [ ] Branch 3 CJ.1.3 > C14649T > C4582T > C2197T, G10997A(ORF1ab:G3578S), T11737C, C11962T, C22202A(S:R214S) mini-saltation [Query: G10997A, C22202A, 47]
```
### Branch 1:

**Defining Mutations:** CJ.1.3 > T11618C(ORF1a:F3785L) > G24368C(S:D936H)
**Query:** T11618C, G24368C
**Earliest seq:** 2022-11-13 (EPI_ISL_15980041, South Korea)
**Latest seq:** 2023-06-01 (EPI_ISL_17815601, Singapore)
**Sampled Countries:** South Korea (192) Singapore (3), Japan (2), USA (1, Washington)

<details><summary>Genomes: </summary>
EPI_ISL_15980041, EPI_ISL_15980066, EPI_ISL_15980113, EPI_ISL_16136285, EPI_ISL_16136418, EPI_ISL_16334157, EPI_ISL_16334171, EPI_ISL_16336554, EPI_ISL_16338086, EPI_ISL_16339485, EPI_ISL_16341286, EPI_ISL_16341345, EPI_ISL_16341583, EPI_ISL_16413699, EPI_ISL_16418974, EPI_ISL_16419390, EPI_ISL_16456161, EPI_ISL_16506208, EPI_ISL_16506730, EPI_ISL_16506841, EPI_ISL_16507029, EPI_ISL_16514037, EPI_ISL_16568459, EPI_ISL_16578308, EPI_ISL_16578351, EPI_ISL_16578566, EPI_ISL_16600033, EPI_ISL_16714901, EPI_ISL_16715932, EPI_ISL_16716011, EPI_ISL_16899676, EPI_ISL_16899820, EPI_ISL_16900691, EPI_ISL_16901660, EPI_ISL_16901757, EPI_ISL_16975615, EPI_ISL_16975804, EPI_ISL_16975908, EPI_ISL_16976349, EPI_ISL_16976428, EPI_ISL_16976581, EPI_ISL_17040536, EPI_ISL_17046372, EPI_ISL_17090092, EPI_ISL_17090141, EPI_ISL_17090144, EPI_ISL_17090358, EPI_ISL_17090360, EPI_ISL_17090451, EPI_ISL_17090607, EPI_ISL_17090612, EPI_ISL_17090657-17090658, EPI_ISL_17090664, EPI_ISL_17090751-17090752, EPI_ISL_17090772, EPI_ISL_17090923-17090925, EPI_ISL_17090951, EPI_ISL_17091017, EPI_ISL_17091241, EPI_ISL_17091345, EPI_ISL_17091497, EPI_ISL_17091594, EPI_ISL_17091681, EPI_ISL_17092139, EPI_ISL_17163932, EPI_ISL_17163995, EPI_ISL_17171145, EPI_ISL_17171256, EPI_ISL_17171360, EPI_ISL_17171405, EPI_ISL_17171433, EPI_ISL_17171435, EPI_ISL_17171581, EPI_ISL_17171636, EPI_ISL_17171905, EPI_ISL_17172428, EPI_ISL_17229589, EPI_ISL_17229619, EPI_ISL_17229626, EPI_ISL_17229763, EPI_ISL_17229882, EPI_ISL_17230233, EPI_ISL_17230264, EPI_ISL_17230353, EPI_ISL_17230422, EPI_ISL_17230471, EPI_ISL_17230475, EPI_ISL_17230478, EPI_ISL_17230540, EPI_ISL_17230825-17230826, EPI_ISL_17230877, EPI_ISL_17231097, EPI_ISL_17283736, EPI_ISL_17293837, EPI_ISL_17293907, EPI_ISL_17294110, EPI_ISL_17294179, EPI_ISL_17294193, EPI_ISL_17294198, EPI_ISL_17294235, EPI_ISL_17294373, EPI_ISL_17294431, EPI_ISL_17294468, EPI_ISL_17294481, EPI_ISL_17294641, EPI_ISL_17294737, EPI_ISL_17373819, EPI_ISL_17373848, EPI_ISL_17374316-17374317, EPI_ISL_17374824, EPI_ISL_17374877, EPI_ISL_17374947, EPI_ISL_17374970, EPI_ISL_17375268, EPI_ISL_17414750, EPI_ISL_17414758, EPI_ISL_17414761, EPI_ISL_17414947-17414948, EPI_ISL_17414992, EPI_ISL_17415036, EPI_ISL_17415108, EPI_ISL_17415117, EPI_ISL_17415327, EPI_ISL_17415682, EPI_ISL_17415692, EPI_ISL_17415847, EPI_ISL_17415924, EPI_ISL_17415973, EPI_ISL_17416046, EPI_ISL_17416270, EPI_ISL_17463540, EPI_ISL_17473134, EPI_ISL_17473139, EPI_ISL_17473177, EPI_ISL_17473214, EPI_ISL_17473642, EPI_ISL_17474309, EPI_ISL_17511481, EPI_ISL_17511533, EPI_ISL_17511537, EPI_ISL_17511597, EPI_ISL_17538562, EPI_ISL_17538580, EPI_ISL_17538584, EPI_ISL_17538734, EPI_ISL_17538889, EPI_ISL_17538964, EPI_ISL_17539191, EPI_ISL_17539331, EPI_ISL_17539871, EPI_ISL_17554711, EPI_ISL_17563089, EPI_ISL_17563247, EPI_ISL_17563335, EPI_ISL_17563337-17563338, EPI_ISL_17563875, EPI_ISL_17563891, EPI_ISL_17563940, EPI_ISL_17564000, EPI_ISL_17564073, EPI_ISL_17604349, EPI_ISL_17604399, EPI_ISL_17604406, EPI_ISL_17604882, EPI_ISL_17604891, EPI_ISL_17604966, EPI_ISL_17605272, EPI_ISL_17605835, EPI_ISL_17606068, EPI_ISL_17606076, EPI_ISL_17646994, EPI_ISL_17647166, EPI_ISL_17647321, EPI_ISL_17647402, EPI_ISL_17647721, EPI_ISL_17647732, EPI_ISL_17690632, EPI_ISL_17691157, EPI_ISL_17718693, EPI_ISL_17723205, EPI_ISL_17723572, EPI_ISL_17723785, EPI_ISL_17730734, EPI_ISL_17740648, EPI_ISL_17779181, EPI_ISL_17779461, EPI_ISL_17807281, EPI_ISL_17807464, EPI_ISL_17815601, EPI_ISL_17815665
</details>

---

### Branch 2:

**Defining Mutations:** CJ.1.3 > T11618C(ORF1a:F3785L) > T28251G(ORF8:F120V), A28254C(ORF8:I121L)
**Query:** T11618C, T28251G, A28254C
**Earliest seq:** 2022-12-15 (EPI_ISL_16419035, South Korea)
**Latest seq:** 2023-06-06 (EPI_ISL_17885265, Puerto Rico)
**Sampled Countries:** South Korea (111), Japan (3), Puerto Rico (2), India (2, all Delhi), Slovenia(1), USA (1, North Carolina)

<details><summary>Genomes: </summary>
EPI_ISL_16419035, EPI_ISL_16419428, EPI_ISL_16506941, EPI_ISL_16599995, EPI_ISL_16600052, EPI_ISL_16600360, EPI_ISL_16600434, EPI_ISL_16715581, EPI_ISL_16747228, EPI_ISL_16848303, EPI_ISL_16900155, EPI_ISL_16901156, EPI_ISL_16901934, EPI_ISL_16965271, EPI_ISL_16975633, EPI_ISL_16975949, EPI_ISL_16976671, EPI_ISL_17090955, EPI_ISL_17091680, EPI_ISL_17091682, EPI_ISL_17164318, EPI_ISL_17171764, EPI_ISL_17172012, EPI_ISL_17229986, EPI_ISL_17230514, EPI_ISL_17230517, EPI_ISL_17230558, EPI_ISL_17283916, EPI_ISL_17365016, EPI_ISL_17373741, EPI_ISL_17373958, EPI_ISL_17374493, EPI_ISL_17375080, EPI_ISL_17447218, EPI_ISL_17447226, EPI_ISL_17473131, EPI_ISL_17473573, EPI_ISL_17474158, EPI_ISL_17474366, EPI_ISL_17474546, EPI_ISL_17511496, EPI_ISL_17511565, EPI_ISL_17511582, EPI_ISL_17538591, EPI_ISL_17539052, EPI_ISL_17539081, EPI_ISL_17539249-17539250, EPI_ISL_17539363, EPI_ISL_17554645-17554646, EPI_ISL_17554648, EPI_ISL_17554650, EPI_ISL_17554655, EPI_ISL_17554657-17554658, EPI_ISL_17563178, EPI_ISL_17563285, EPI_ISL_17563469, EPI_ISL_17563799, EPI_ISL_17563859, EPI_ISL_17563952, EPI_ISL_17604157, EPI_ISL_17604191, EPI_ISL_17604281, EPI_ISL_17604429, EPI_ISL_17604539, EPI_ISL_17604600, EPI_ISL_17604798, EPI_ISL_17604944, EPI_ISL_17604955, EPI_ISL_17604991, EPI_ISL_17605020, EPI_ISL_17605065, EPI_ISL_17605095-17605096, EPI_ISL_17605260, EPI_ISL_17606053, EPI_ISL_17606061, EPI_ISL_17646846, EPI_ISL_17646909, EPI_ISL_17647189, EPI_ISL_17647222, EPI_ISL_17647230, EPI_ISL_17647457, EPI_ISL_17647710, EPI_ISL_17647745, EPI_ISL_17647809, EPI_ISL_17648467, EPI_ISL_17648477, EPI_ISL_17690585, EPI_ISL_17690854, EPI_ISL_17690974-17690975, EPI_ISL_17690977, EPI_ISL_17691195, EPI_ISL_17691200, EPI_ISL_17700070, EPI_ISL_17723265, EPI_ISL_17723338, EPI_ISL_17723418, EPI_ISL_17723643, EPI_ISL_17723682, EPI_ISL_17723758, EPI_ISL_17723778-17723779, EPI_ISL_17724247, EPI_ISL_17730404, EPI_ISL_17730745, EPI_ISL_17740810, EPI_ISL_17740825, EPI_ISL_17740857, EPI_ISL_17740873, EPI_ISL_17741023, EPI_ISL_17777808, EPI_ISL_17779430, EPI_ISL_17807371, EPI_ISL_17807968, EPI_ISL_17881960, EPI_ISL_17885265, 
</details>

---

### Branch 3:

**Defining Mutations:** CJ.1.3 > C14649T > C4582T > C2197T, G10997A(ORF1ab:G3578S), T11737C, C11962T, C22202A(S:R214S)
**Query:** G10997A, C22202A
**Earliest seq:** 2023-03-17 (EPI_ISL_17416126, South Korea)
**Latest seq:** 2023-06-08 (EPI_ISL_17820042, Japan)
**Sampled Countries:** Japan (29), South Korea (13)

<details><summary>Genomes: </summary>
EPI_ISL_17416126, EPI_ISL_17463557, EPI_ISL_17554447, EPI_ISL_17604511, EPI_ISL_17604660, EPI_ISL_17642428, EPI_ISL_17647333, EPI_ISL_17648968, EPI_ISL_17652291, EPI_ISL_17690701, EPI_ISL_17704209-17704210, EPI_ISL_17704270, EPI_ISL_17704276, EPI_ISL_17718654, EPI_ISL_17723386, EPI_ISL_17723678, EPI_ISL_17724167, EPI_ISL_17741837, EPI_ISL_17780119, EPI_ISL_17807200, EPI_ISL_17820042, EPI_ISL_17835614, EPI_ISL_17835628, EPI_ISL_17859110, EPI_ISL_17880062, EPI_ISL_17880095, EPI_ISL_17880381, EPI_ISL_17880482, EPI_ISL_17881528, EPI_ISL_17881539, EPI_ISL_17882094, EPI_ISL_17882311, EPI_ISL_17882526, EPI_ISL_17882663, EPI_ISL_17883152, EPI_ISL_17883345, EPI_ISL_17883408, EPI_ISL_17883492, EPI_ISL_17883633, EPI_ISL_17883693, EPI_ISL_17883911, 
</details>

---

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29d05_e1b9a0.json?f_userOrOld=uploaded%20sample

view from CJ.1 polytomy, filtered by recent samples since May:
![Diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ed5bf445-4c46-43e2-be31-0abd4070b538)

**Trivia:**
- CJ.1* is basically BA.2.75.3 with S:R346T, S:F486P and S:F490S, short of S:V445P and S:G446S on RBD compare to XBB*.
- There are many more sub-branches on the rise at the moment, this proposal only pick largest 3 of them.
- Branch 2 with ORF8:F120V and ORF8:I121L could be another way to mimic XBB.1+ORF8:G8*? Not sure abou this, but it seems to be most widely transmitted around the world.
- Interestingly, BM.1.1.1, ancestor of CJ.1, is also one of the donor to XBB, so this might just be tug-of-war of 2 BM.1.1.1 offsprings in East Asia right now.

**Comment by FedeGueli** [comment]
They have all, but lineage 3 samples from May only if they dont circulate is unuseful to track them further. lets wait next week to see if  more recent samples pop up.

**Comment by FedeGueli** [comment]
> G10997A, C22202A

As i said above to me the only one worth to tracking is the Branch 3 that interestingly has been sampled in Okinawa. So if next week no new sample will come for branch 1 and 2 shut them down and keep only branch here.

**Comment by FedeGueli** [comment]
Designated 1 and 3 @NkRMnZr please monitor privately branch 2 , for now this is closed.
