### ISSUE TITLE
XBB.1.5 + ORF1a:K2029N, ORF1a:T2846I, S:G798D, ORF9b:T79I(34 seq, 7 countries)

### ISSUE THREAD

**Issue by DoropFan** [sars-cov-2-variants/lineage-proposals#288]
Description
Sub-lineage of:XBB.1.5
Earliest sequence:2023-05-16(Singapore)
Most recent sequence:2023-06-15(Singapore)
Countries circulating:Singapore(13), United States(3), South Korea(1), China(1)
Sequences:18

correction"
UShER Tree
C15024T>C28519T>ORF9b:T79I>T15024C>G6352T(ORF1a:K2029N), C8802T(ORF1a:T2846I), A12949G, G23955A(S:G798D)
"
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24072_e29b60.json?c=country&gt=S.798D&label=id:node_6846954
![xbb1,5,sg798d](https://github.com/sars-cov-2-variants/lineage-proposals/assets/118802079/f9f61026-6abd-4ee1-b0f1-abc2686ce17d)

CovSpectrum:ORF1a:K2029N, ORF1a:T2846I, S:G798D, ORF9b:T79I
GISAID:G6352T, C8802T, G23955A
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AG798D%2CORF1a%3AK2029N%2CORF1a%3AT2846I%2CORF9b%3AT79I&

Genomes
https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2022-12-26&dateTo=2023-06-23&aaMutations=S%3AG798D%2CORF1a%3AK2029N%2CORF1a%3AT2846I%2CORF9b%3AT79I&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random

**Comment by FedeGueli** [comment]
Welcome back @DoropFan interesting one mayba also the bigger branch with Orf9b:T79I worth a designation first. but let see how this will go in Singapore.

**Comment by DoropFan** [comment]
thank you.

**Comment by FedeGueli** [comment]
It cant compete : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G6352T%2CC8802T%2CG23955A&analysisMode=CompareToBaseline& 
closing it for now.
