### ISSUE TITLE
small saltation of CM.10 (BA.2.3.20.10) with S:D253N and 4 non-Spike mutations (3 seqs in Philippines)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#289]
*Notice: the whole Usher tree is messy, which may be related the relatively low quality seqs in Philippines. Hence I directly show the saltation branch 

Defining mutations: CM.10>C274T, C1263T (ORF1a:T333M), G3259T (ORF1a:Q998H), A6293G (ORF1a:I2010V), C9487T, A11305G, T22207C, G22319A (S:D253N), C28000T (ORF8:P36L), A28877T, G28878C
GISAID query: C1263T, A6293G, G22319A
Earliest seq: 2023-05-15 (Philippines, EPI_ISL_17948883)
Most recent seq: 2023-05-21 (Philippines, EPI_ISL_17948918)
Countries detected: Philippines (3)

Usher Tree:
![QQ截图20230630213421](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/9ed7c622-1a42-45f5-842d-4dbec4ea8cf6)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6cb2_e936a0.json?c=gt-S_253

CM.10 is a Southeast Asia-originated sublineage with S:K478T reversion and S:V445A. This saltation branch further get site 253 mutation on Spike, as S:D253G is popular in XBB.2*, while S:D253N is very rare recently.

We can monitor it for a time if it emerges outside Philippines.  

Genomes:
EPI_ISL_17948883, EPI_ISL_17948915, EPI_ISL_17948918

**Comment by FedeGueli** [comment]
CM.10 (C1471T, C2445T, T5406C, A6770G,A22893G, T22896C, A22910G) is still a little less than 10% of sequences sampled in Philippines after May 15, very good to dig it ( i would have start in minutes) also cause it has S:T478T reversion, it will be of utmost imporance to understand if maybe T478T could be fitter than 478R

**Comment by FedeGueli** [comment]
I think if it was spreading we would have seen from other countries so closing it for now
