### ISSUE TITLE
XBB.1.5.18 with spike muts Q675K and F456L (59 seqs, UK, France and Portugal)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#29]
[transferred from the pango repo. This cluster has slowed down a lot so im closing it there and keeping it here only to keep an eye on it once in a while]
GISAID query: C23585A, C7926T, C7164T, T22930A
First sequence: 27-02-2023
Most recent sequence: 03-05-2023

USHER tree: (first zoomed in on subbranch of xbb.1.5.18, second is from root of xbb.1.5.18)
![part1](https://user-images.githubusercontent.com/119106095/230585991-80149eb8-b68c-4a1d-a9a5-6ebec025ac3b.png)
![part2](https://user-images.githubusercontent.com/119106095/230585997-1af41ce2-d8b1-4540-8025-e441f4909caf.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2423f_fdef30.json?c=gt-S_456
675K has had some mild success in other xbb.1.5 lineages, nothing too crazy though. The mutation site has however been designated before with 675H in EL.1.
F456L is present in the designated XBB.1.5.10. The mutations have not yet been together before. In that issue, the decreased ace2 affinity has been discussed, it still managed to reach 339 sequences. https://github.com/cov-lineages/pango-designation/issues/1614
F456L is also trending upwards in general over the last half year, reaching 1% globally and as high as 30-40% in brazil (where there is another xbb.1.5.18 with F456L, but without the Q675K and maybe unrelated to this one) https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=s%3A456l&
Currently all sequences come from the UK, but from different labs and spanning across one month. Perhaps monitor for a while for spread.

Covspectrum (xbb.1.5.18 + Q675K): https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A675k&nextcladePangoLineage=xbb.1.5.18*&aaMutations1=S%3Af456L%2Cs%3A675k&nextcladePangoLineage1=xbb.1.5.18*&
Covspectrum (xbb.1.5.18 + Q675K + F456L): https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A675k%2Cs%3A456l&nextcladePangoLineage=xbb.1.5.18*&aaMutations1=S%3Af456L%2Cs%3A675k&nextcladePangoLineage1=xbb.1.5.18*&

EPI:
EPI_ISL_17178847, EPI_ISL_17179037, EPI_ISL_17179130,
EPI_ISL_17210195, EPI_ISL_17267562, EPI_ISL_17284241,
EPI_ISL_17284584, EPI_ISL_17298483, EPI_ISL_17359825-17359826,
EPI_ISL_17359906, EPI_ISL_17359982, EPI_ISL_17359988,
EPI_ISL_17360033, EPI_ISL_17372899, EPI_ISL_17372927,
EPI_ISL_17372947, EPI_ISL_17373052, EPI_ISL_17373054,
EPI_ISL_17381791, EPI_ISL_17382468, EPI_ISL_17400433,
EPI_ISL_17400495, EPI_ISL_17400528

**Comment by FedeGueli** [comment]
50 as today. Boris could you find a more specific nuc mutations query? i fear soon this will catch seqs from other lineages.

**Comment by BorisUitham** [comment]
There is recently a rising amouny of s:t961m in this lineage (about 13 in the most recent 25).

While looking for a better query, i started with this one  which is based on s:675k, orf1a:2554v and orf1a:t2300i: C23585A, C7926T, C7164T
It finds 52 sequences, the 2 extra had gaps at 456. But one of the 2 does seem to have 961m so it belongs to this lineage. However the other one is from usa and i cant really tell if it belongs or not. Usher places the usa one just outside the branch.

So here is the more strict one, missing the one sequence that probably does belong here, 50 seq:
C23585A, C7926T, C7164T, T22930A
(S:456l, s:675k, orf1a:2554v and orf1a:t2300i)

For the newer subbranch with 961m (here i exclude s:456l in the query to catch the extra one, i think it wouldnt matter much since 961m is only 0.1% prevalence in general) 
C24444T, C23585A, C7926T, C7164T
Which gives us 13 sequences

**Comment by BorisUitham** [comment]
Furthermore, within this 961m branch there is also s:t76i which is a reasonably fit mutation, known from ba.5.5

**Comment by FedeGueli** [comment]
Two more from England, even if it appears to me not that fast. better tracking it for a while more

**Comment by BorisUitham** [comment]
Doesn't seem to be going anywhere, i'll give this issue one more week

**Comment by FedeGueli** [comment]
Closing this for now
