### ISSUE TITLE
EG.6.1 (F456L) with S:T961M, 15 sequences, 1 with 478r too (Israel, USA)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#290]
Query: A27507C, T22928C, C1684T, C24444T

I'm not really sure if the 961m is relevant as it occurs frequently across all lineages, but this is 1 new case of a 456l 478r combination

![aa](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/4d6a0a8d-e8ba-47b0-b419-4e646de792f4)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c911_ed7f70.json?c=gt-S_961,478&label=id:node_6663029

**Comment by FedeGueli** [comment]
It seems slow closing it for now.

**Comment by FedeGueli** [comment]
2 seqs now with 478+456 maybe @BorisUitham check it it should be very slow but never say never.

**Comment by BorisUitham** [comment]
Thanks for notifying, I'll start monitoring it again!

**Comment by BorisUitham** [comment]
Checking the tree again, i think it might be a separate mutation to k478r that is grouped together as they have different orf muts:
![Screenshot_20230903_111627_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/f3263e54-f506-4d50-a5cd-8ccd2f71774a)

Another newly active part is a branch with spike mutation s:98f which i will also keep an eye on since it was succesful in b.1.122 back in 2020:
![Screenshot_20230903_111706_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/3f4c99c3-0cce-470c-a0cf-ac5eecb8948f)

**Comment by FedeGueli** [comment]
yes likely
