### ISSUE TITLE
FL.20 + S:L455W  Full credit to Boris Uitham to spotting this one. (11 as 25/07)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#295]
@Borisuitham unluckily cannot open an issue on its own due to to family reasons.
He asked me to open this one as this seems quite urgent to be reviewed. 
It was spotted by him and tracked mostly by him and @hynnspylor
Please look at the FL.20 issue here where Tyler Starr, Jesse Bloom and ooBB commented on S:L455W

Defining mutations: FL.20 >> S:L455W (T22926G) 
Gisaid query: G21718C, T22928C, C25714T, T22926G

Tree:
![Schermata 2023-07-01 alle 10 29 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1b7ff26b-2f39-4c53-902a-253e73120c62)
![Schermata 2023-07-01 alle 10 28 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/dad179e1-3059-4047-a0a9-17e4c6494da8)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_62df8_fe3a30.json?label=id:node_6651584

Samples: 3
EPI_ISL_17812682, EPI_ISL_17884493, EPI_ISL_17950363

Note that the american sample is from a traveller from England.

**Comment by FedeGueli** [comment]
Three new sequences still not on Gisaid: (all recent from Northern Ireland)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22443_ac00b0.json?label=id:node_6666823
![Schermata 2023-07-09 alle 16 13 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/df3ba02a-6a7a-4b9c-9f9b-5046a483414b)

**Comment by BorisUitham** [comment]
Where can I find these sequences that are not yet uploaded to gisaid?

**Comment by FedeGueli** [comment]
> Where can I find these sequences that are not yet uploaded to gisaid?

on Usher.

I found them thx to the double mutation tracker of Dave that grabs all uk sequences also pre uploaded to Gisaid.

**Comment by FedeGueli** [comment]
> Where can I find these sequences that are not yet uploaded to gisaid?
you candownload the csv with the AA you search for from:
https://sars2.cvr.gla.ac.uk/cog-uk/

**Comment by BorisUitham** [comment]
#437 the delta huge saltation also has w455 l456 combination, making it the 5th separate "lineage" to get it. The 4th and only nonchronic is this one, but i did notice that 3 of all of these 5 spawned since june. The other two being from january and last year september

**Comment by FedeGueli** [comment]
5 samples (not all recent) uploaded by Northern Ireland not yet on Gisaid:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_41326_fbadf0.json?label=id:node_6695021
![Schermata 2023-07-25 alle 15 42 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/59099ddd-ae07-4ec9-a87e-ddba01b60ca1)

**Comment by FedeGueli** [comment]
@BorisUitham i think you should propose it now.

**Comment by BorisUitham** [comment]
To be honest i expected it to be a bit quicker given the favourable fpredictions and having grown convergently in several chronics lately. Northern ireland doesn't upload much though and it does seem to possibly have a high prevalence there in the few that are uploaded: 3 out of 11 on gisaid collected since 11 june, and with these 5 new ones its 7 out of at least 15, but there are probably some others waiting to be uploaded as well so probably smaller than that. (Noting too that one of the 5 new ones is collected 17 may, and i dont ). I think I will wait a bit more until this new batch is on gisaid to make a better estimate of its prevalence, or until some new ones pop up in different places

**Comment by FedeGueli** [comment]
> To be honest i expected it to be a bit quicker given the favourable fpredictions and having grown convergently in several chronics lately. Northern ireland doesn't upload much though and it does seem to possibly have a high prevalence there in the few that are uploaded: 3 out of 11 on gisaid collected since 11 june, and with these 5 new ones its 7 out of at least 15, but there are probably some others waiting to be uploaded as well so probably smaller than that. (Noting too that one of the 5 new ones is collected 17 may, and i dont ). I think I will wait a bit more until this new batch is on gisaid to make a better estimate of its prevalence, or until some new ones pop up in different places

now all 11 seqs on Gisaid. please propose it.

**Comment by BorisUitham** [comment]
Thanks for notifying, with this batch of uploads seems to be 7 out of 38 since 1st of june (18.4%), or 6 out of 16 since 18th of june (37.5%) in northern ireland. I will make a proposal.
