### ISSUE TITLE
FY.6 sublineage got S:R408N in Spain (48 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#296]
I spotted a sublineage of FY.6 that has acquired an AA substitution at one of defining mutations of BA.2 S:R>S408N

Tree:
![Schermata 2023-07-01 alle 16 53 38](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f6529b3b-8a92-4548-94bf-d523c2926272)
![Schermata 2023-07-01 alle 16 54 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d9d9aec8-7da6-4a66-a177-2f761ac7afa2)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a8f_3a240.json?c=gt-S_408&label=id:node_6709465

Defining mutations:
FY.6>> C13620T > A23989C > S:S408N (G22785A )

Gisaid query: C13620T , A23989C,G22785A

Samples: 
EPI_ISL_17541214, EPI_ISL_17559425, EPI_ISL_17652568,
EPI_ISL_17679326, EPI_ISL_17679477, EPI_ISL_17679678,
EPI_ISL_17731319, EPI_ISL_17761393, EPI_ISL_17804764,
EPI_ISL_17817736, EPI_ISL_17937833, EPI_ISL_17948484,
EPI_ISL_17949078, EPI_ISL_17949110

FIrst: hCoV-19/Spain/AN-PMC-34534/2023 | Original | EPI_ISL_17541214 | 2023-04-12

**Comment by HynnSpylor** [comment]
S:R408N is abnormally "popular" in XBB.1.22.1, as it can be also found in FY.1.1 sublineage and my proposal in pango #2053
https://[github.com](https://github.com/cov-lineages/pango-designation/issues/2053)/cov-lineages/pango-designation/issues/2053

**Comment by FedeGueli** [comment]
Yeah XBB.1.22.1 seems able to gain more different mutations or before the other lineages.

**Comment by FedeGueli** [comment]
one more from Canada

**Comment by FedeGueli** [comment]
Closing for now

**Comment by FedeGueli** [comment]
Thx @nkrmnzr

**Comment by FedeGueli** [comment]
It still cant compete but have some sort of circulation in France.

**Comment by FedeGueli** [comment]
It reached Australia today. I m closing it. pinging @corneliusroemer about 408 mutations in the case could be useful to designate one of them.

**Comment by FedeGueli** [comment]
![Schermata 2023-11-02 alle 08 55 25](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/38169e34-a52f-434d-a30d-9c41b2d20bde)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a48c_355390.json?c=userOrOld&label=id:node_3225385
Some circualtion of this in France.
