### ISSUE TITLE
XBB.1.16 with S:K304N circulating in South Korea and Japan ( 100 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#298]
Tree:
![Schermata 2023-07-01 alle 22 44 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2061d826-5423-4b09-8f86-e3d4b5d26f21)

![Schermata 2023-07-01 alle 22 43 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9da57238-a6ed-49f5-a3f2-6bbeb1b1325c)

![Schermata 2023-07-01 alle 22 43 38](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/de330b09-16b2-4d92-a012-6c588d3c220e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_5aee_3c8a0.json?c=gt-S_304&label=id:node_6600262

Defining mutations:
XBB.1.16 >> Orf1a:G519S (G1820A )> Orf1a:G1101D (G3567A =NSP3_G283D) >C17949T, C25006T > S:K304N  (A22474C)

Gisaid Query: C17949T, C25006T,A22474C

Samples : 96
First: hCoV-19/USA/WA-GBW-H20-312-9890/2023 | Original | EPI_ISL_17700412 | 2023-05-10 (traveller from S.Korea)
Last: hCoV-19/Singapore/R42MR63/2023 | Original | EPI_ISL_17837587 |2023-06-15 (local case)

IDs:
EPI_ISL_17685653, EPI_ISL_17700412, EPI_ISL_17730673,
EPI_ISL_17741288, EPI_ISL_17741320, EPI_ISL_17741374,
EPI_ISL_17741397, EPI_ISL_17778963, EPI_ISL_17779097,
EPI_ISL_17779216, EPI_ISL_17779312, EPI_ISL_17779342,
EPI_ISL_17779344, EPI_ISL_17779443, EPI_ISL_17780164,
EPI_ISL_17788737, EPI_ISL_17788935, EPI_ISL_17789145,
EPI_ISL_17789270, EPI_ISL_17790707, EPI_ISL_17796659,
EPI_ISL_17806884-17806885, EPI_ISL_17807115, EPI_ISL_17807449,
EPI_ISL_17807461, EPI_ISL_17807528, EPI_ISL_17807826,
EPI_ISL_17807864, EPI_ISL_17815255, EPI_ISL_17815741,
EPI_ISL_17816404, EPI_ISL_17816522, EPI_ISL_17816580,
EPI_ISL_17816589, EPI_ISL_17816622, EPI_ISL_17831217,
EPI_ISL_17834715, EPI_ISL_17834831, EPI_ISL_17834875,
EPI_ISL_17834930, EPI_ISL_17835021, EPI_ISL_17835183,
EPI_ISL_17835223, EPI_ISL_17835327, EPI_ISL_17835360,
EPI_ISL_17835374, EPI_ISL_17835376, EPI_ISL_17835397,
EPI_ISL_17835468, EPI_ISL_17835489, EPI_ISL_17835766,
EPI_ISL_17837587, EPI_ISL_17853927, EPI_ISL_17853953,
EPI_ISL_17856343, EPI_ISL_17856704, EPI_ISL_17882477,
EPI_ISL_17882660, EPI_ISL_17882684, EPI_ISL_17883111,
EPI_ISL_17883938, EPI_ISL_17883947-17883948, EPI_ISL_17884021,
EPI_ISL_17884125, EPI_ISL_17884164-17884165, EPI_ISL_17927763,
EPI_ISL_17927778, EPI_ISL_17927823, EPI_ISL_17927853,
EPI_ISL_17927880, EPI_ISL_17927920, EPI_ISL_17927928,
EPI_ISL_17927980, EPI_ISL_17928040, EPI_ISL_17928057,
EPI_ISL_17928061, EPI_ISL_17928150, EPI_ISL_17930348,
EPI_ISL_17930435, EPI_ISL_17930494, EPI_ISL_17930513,
EPI_ISL_17930655, EPI_ISL_17930658, EPI_ISL_17930685,
EPI_ISL_17930720, EPI_ISL_17930775, EPI_ISL_17932506,
EPI_ISL_17932551, EPI_ISL_17932592, EPI_ISL_17949234,
EPI_ISL_17950544, EPI_ISL_17950604, EPI_ISL_17950710,

Countries:
![Schermata 2023-07-01 alle 22 54 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a3cda418-dcbf-41ef-b660-8845f5f880cc)

Growth rate:
Checking [here](https://cov-spectrum.org/explore/South%20Korea/AllSamples/from%3D2023-05-01%26to%3D2023-06-30/variants?nextcladePangoLineage=XBB.1.16*&aaMutations1=S%3AK304N&nextcladePangoLineage1=xbb.1.16*&analysisMode=CompareToBaseline& 
) in South Korea through May it appears slighty faster than the average of XBB.1.16

![Schermata 2023-07-01 alle 22 58 35](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a815a504-b0ab-4ffc-bdcd-b1524b593de0)

Ping @corneliusroemer this is a new mutation, although it does not create a new N Glycan ( K>NSF) ,around  1/5 - 1/6 of samples sequenced carrying this mutation belongs to this lineage.

**Comment by HynnSpylor** [comment]
100 seqs now and it deserves to be designated

**Comment by FedeGueli** [comment]
> 100 seqs now and it deserves to be designated

Thanks for yourhelp! i ve proposed it just now.

**Comment by FedeGueli** [comment]
HF.1

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/c36d5d613c740826d2ec46a4a99fb3e9ad542db2
