### ISSUE TITLE
FD.1.1 sublineage with ORF1a:S2303F, ORF9b:V37A, ORF7a:*122S/ORF7b:M1I, and S:L455F (2 seq. Canada)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#299]
Substitutions on top of FD.1.1: ORF1a:S2303F(C7173T)+nuc:C10279T then T12346C then ORF9b:V37A(T28393C) then ORF7a:*122S/ORF7b:M1I(G27758C) then C12974T then S:L455F(G22927T)+C25680T

Aside from S:L455F, G27758C(ORF7a:*122S/ORF7b:M1I) is also interesting.

FD.1.1 already as ORF7b:E3*. This mutation would extend ORF7a a little bit.

![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/7a1a78e1-991b-48a2-b587-901ad84cad62)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_355e_94af0.json?c=gt-S_455&label=id:node_6740186
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3AL455F%26S%3AF456L%26ORF7b%3AM1I&

Gisaid query: C25680T,C12974T,T28393C (Edited)

**Comment by FedeGueli** [comment]
Very good catch oobb thax!

**Comment by ryhisner** [comment]
This is really interesting. I've recently come across a deletion that extends ORF7b by about 20 AA residues. First saw it in an XBB.1.22.1 sequence that also had the 3-nuc (from WT) mutation S:R408D but then checked and saw that it's been in about 50 sequences in 2023. They're from 16 different lineages, however, so this seems to be something that recurs but hasn't really caught on. This exact same deletion was also found in B.1.1.318, which I understand was something of a big deal back in the day. 
<img width="1402" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e30ad35a-4bff-448e-a122-45f5ff1a4b05">

**Comment by FedeGueli** [comment]
Closing this for now
