### ISSUE TITLE
XBB.1.32 with S:Y453F and multiple AA substitutions likely circulating in Davao Philippines - 10 sequences  

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#3]
Transferred from https://github.com/cov-lineages/pango-designation/issues/1908

While commenting a @ryhisner cool observation on Philippines "exceptionality" around the prolonged leading BA.2.3.20 era there then i digged a bit and found an apparently interesting sublineages circulating there.

If i look for samples collected after 1st march 2023 and labeled as Philippines in Gisaid i found that 9 out of 92 are from XBB.1.32.
Out of these 9 only one has not S:Y453F while 6 has S:Y453F and the 2 remaining have NNN but sharing with the S:Y453F an orf7a mutation: Orf7a:A50S.

So i decided to usher it and i found this is a clear sublineage of XBB.1.32 that emerged likely in Davao province and it is around 5% of samples collected in the region after 15 february.

Tree:
 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_29215_da73e0.json?c=userOrOld&label=id:node_5879801

Defining mutations:

XBB.1.32 >>>ORF1a:T2121I (C6627T)(NSP3_T1303I) > T3676C, T14865C, Orf7a:A50S (G27541T) > Orf1a:L642F (C2189T)(NSP2_L462F), ORF1b:L2497I (C20956A)(NSP16_L100I) , S:Y453F (A22920T )

Gisaid query: NSP16_L100I,NSP3_T1303I,NSP2_L462F

Sequences:
EPI_ISL_17343831, EPI_ISL_17343863, EPI_ISL_17343901,
EPI_ISL_17343903-17343908, EPI_ISL_17343910

**Comment by corneliusroemer** [comment]
Designated XBB.1.32.1
