### ISSUE TITLE
FC.1 (BQ.1.1.72.1) sublineage with S:K147I, S:G181V, S:G184D (4seqs Indonesia)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#30]
Defining mutations: FC.1>C3317T(ORF1a:P1018S)>C11322T(ORF1a:A3686V), T5182C,
T22615C>A22002T(S:K147I)>G22104T (S:G181V)>G22113A(S:G184D), C26894T, G29711T
GISAID query: Spike_K147I, Spike_G181V, Spike_G184D, Spike_T478R
Earliest seq: 2023-03-15 (Indonesia, EPI_ISL_17372752)
Most recent seq: 2023-04-22 (Indonesia, EPI_ISL_17622312)
Countries detected: Indonesia (2), South Korea (1- imported from indonesia EDITED)
Usher Tree:
![QQ截图20230508170805](https://user-images.githubusercontent.com/121703496/236784758-1f0ce74a-8114-4083-9040-837d797c93d3.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_89d6_8a53b0.json?c=gt-S_147,181,184

A very small branch with 3 NTD mutations. Another branch get S:T883I.

Genomes:
EPI_ISL_17372752, EPI_ISL_17606092, EPI_ISL_17622312

**Comment by FedeGueli** [comment]
still 4 closing for now
