### ISSUE TITLE
XBB.1.5.70 (455-456) sublineage with S:V511I already internationally spread.(17 seqs 9 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#300]
Gisaid query: T2824C  ,G23093A

Samples: 13
EPI_ISL_17737583, EPI_ISL_17737585, EPI_ISL_17782370,
EPI_ISL_17782389, EPI_ISL_17790041, EPI_ISL_17792496,
EPI_ISL_17804459, EPI_ISL_17831187, EPI_ISL_17859383,
EPI_ISL_17872016, EPI_ISL_17881008, EPI_ISL_17881100,

Countries: 9
US, Austria, Iceland, Italy, France, Canada , Switzerland,Spain, Japan (edited)

Tree:
![Schermata 2023-07-02 alle 00 58 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2f098530-7a14-4865-87c9-895c4ce2ec91)
![Schermata 2023-07-02 alle 00 58 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/39cfadf8-4e29-4ebe-9106-3abbb6026390)

Updated with new samples (04/07)
![Schermata 2023-07-05 alle 20 01 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5d375b1e-3573-4059-bea5-ddc56fd9ee64)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2a097_5afc10.json?label=id:node_6905156

Defining mutations:
XBB.1.5.70 >>> C7564T, Orf1a:A4068S (G12467T = NSP8_A126S) > C23741T > T2824C, S:V511I (G23093A)

To be noticed that S:V511I is the defining of XBB.1.5.71 that seems doing well in Spain and represents 50+% of the samples carrying this mutation since the start of the pandemic.

Ping @corneliusroemer

**Comment by FedeGueli** [comment]
One more coming from Spain

**Comment by FedeGueli** [comment]
4 new samples one new country (japan) It seems fst ping @corneliusroemer

**Comment by FedeGueli** [comment]
Designated GK.2

**Comment by aviczhl2** [comment]
Shall add milestone for this

**Comment by FedeGueli** [comment]
Thank you @aviczhl2
