### ISSUE TITLE
EG.5.1* + Orf1b:V1644I branch (63)with a sub-branch with S:158G (A22034G) (32)in Japan as of 7-20

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#301]
Mutations on top of EG.5.1*: G18397A first (orf1ab:V6045I = Orf1b:V1644I)-> T20631C->A22034G (S:158G)
Inquiry: Spike_Q52H,Spike_F456L,G18397A (use A22034G to search for the subbranch)
Sequences: EPI_ISL_17539425, EPI_ISL_17539476, EPI_ISL_17648957,
EPI_ISL_17726284-17726285, EPI_ISL_17803882, EPI_ISL_17803903,
EPI_ISL_17819820, EPI_ISL_17880338, EPI_ISL_17881731,
EPI_ISL_17882012, EPI_ISL_17882137, EPI_ISL_17882249,
EPI_ISL_17882474, EPI_ISL_17883222, EPI_ISL_17883445,
EPI_ISL_17883689, EPI_ISL_17883865, EPI_ISL_17883868,
EPI_ISL_17883871, EPI_ISL_17883904, EPI_ISL_17884144,
EPI_ISL_17941101, EPI_ISL_17941121, EPI_ISL_17952040,
Earliest EPI_ISL_17539425 Hong Kong 04-06,2023
Earliest 158G sub branch: EPI_ISL_17882137 05-19,2023
Latest 158G sub branch: EPI_ISL_17883904 06-09, 2023
Latest EPI_ISL_17952040 England 06-13, 2023
Distribution: the branch originated in Hong Kong but except for the three sequences without T20631C, the intermediate mutation, every sequence are in Japan, the crown branch then spread to England as its third sequence.
Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35436_131070.json?f_userOrOld=uploaded%20sample&label=id:node_5103296
I discovered this when routinely checking for Delta (22029-22034del, but interpreted as S:R158G usually). I am not sure if this is actually beneficial mutation but I would monitor it as it is interesting.

**Comment by FedeGueli** [comment]
I am sure @corneliusroemer very soon will start to look at sub branches of EG.5.1 so  good to help him in tracking them.

**Comment by krosa1910** [comment]
Another 7 seqs uploaded, I guess that it ought to be fast as EG.5.1 descendent. 5 of those belong to the S:158G part and those are all in Japan.
It would be natural for lineages to have high growth in Japan nowadays, and I would see if it would have more international spread.

**Comment by krosa1910** [comment]
Got to iceland, and still consistent growth in Japan.

**Comment by FedeGueli** [comment]
I have created a chart of the various branches of EG.5.1 taking the ones > 10 for EG.5.1.1 and he ones >15 fro EG.5.1 : https://cov-spectrum.org/collections/181

**Comment by FedeGueli** [comment]
> This is designated as EG.5.1.2 @FedeGueli

Thanks!! i recall i ve searched for it without finding it! thanks for your help

**Comment by FedeGueli** [comment]
> Is `22029-22034del` or `S:R158G` sub-branch still being monitored? Query: `G18397A, G21718T, A22034G`, returns 54 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1508_b61130.json?f_userOrOld=uploaded%20sample

it has been designated EG.5.1.2

**Comment by FedeGueli** [comment]
> > > Is `22029-22034del` or `S:R158G` sub-branch still being monitored? Query: `G18397A, G21718T, A22034G`, returns 54 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1508_b61130.json?f_userOrOld=uploaded%20sample
> > 
> > 
> > it has been designated EG.5.1.2
> 
> EG.5.1.2 only assigned to `ORF1b:V1644I (G18397A)` from [cov-lineages/pango-designation@240d38f](https://github.com/cov-lineages/pango-designation/commit/240d38f)

Ah ok it is the main branch of EG.5.1.2 that already gave birth to #511 and #512  proposed both by @aviczhl2  i think i will close all these down and make one collective proposal on Pango crediting various spotters there:
![Schermata 2023-08-03 alle 12 14 23](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b499b9a5-2e7a-4b15-bd6d-c53ccc13f2d6)
