### ISSUE TITLE
XBB.1.5.59+orf9b:G38D in Scotland (32seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#303]
XBB.1.5.59+C14481T,C19152T,G28396A(orf9b:G38D)

GISAID query: C14481T,C19152T,G28396A,T8729C,T22928C,T23018C
No. of seqs: 29 (Scotland)

First seq: EPI_ISL_17614487, 2023-4-13
Latest: EPI_ISL_17952172, 2023-6-9

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice38_genome_36b0_1629d0.json?label=id:node_3039098)
![屏幕截图 2023-07-02 221503](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8a9b07cf-370e-4895-b62a-024c1861b114)

**Comment by FedeGueli** [comment]
good to track this orf9b mutation. but i dont think it is fast looking at collection date

**Comment by FedeGueli** [comment]
It seems very slow.
