### ISSUE TITLE
XBB.1.5.59 ( S:F456L) +orf1a:T1429I, S:V510I in China (46 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#304]
XBB.1.5.59+C4551T,G23090A(orf1a:T1429I, S:V510I)

GISAID query: C4551T,G23090A,T8729C,T22928C,T23018C
No of seqs: 25( Japan 3 Singapore 2 China 20)

First seq: EPI_ISL_17637707, Japan, 2023-4-13
Latest: EPI_ISL_17850441, China, 2023-6-13

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f262_1872f0.json?label=id:node_3039166)
![屏幕截图 2023-07-02 222247](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2ddd0346-2d40-4265-85e7-9c1d538b09fe)

**Comment by FedeGueli** [comment]
I ve seen this too! good catch.

**Comment by aviczhl2** [comment]
1 more in New Zealand.

**Comment by FedeGueli** [comment]
10 new samples came from Nez Zealand this week, it seems that it managed to reach around 5% of prevalence there in July. Please propose it.

**Comment by FedeGueli** [comment]
This reached 51 but the only two recent samples came from Tasmania. I'll close it for now
