### ISSUE TITLE
XBB.1.5 saltation with S:R403K on undesignated S:N703S branch (2 seqs, Australia)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#305]
**Defining Mutations:** [_On top of XBB.1.5's T17124C > T10204C > T23018C_] > A23670G(S:N703S) > G1890A(ORF1a:R542H) > A2380G > A7754C(ORF1a:K2497Q), C21855T(S:S98F) > C1722T(ORF1a:A486V), A3740G(ORF1a:I1159V), C3984T(ORF1a:T1240I), C5575T, A5627G(ORF1a:T1788A), C8991T(ORF1a:A2909V), C14119T(ORF1b:P218S), A15033G, G22580A(S:E340K), G22770A(S:R403K), A24838G, G25091A(S:V1177I), G27806A, G29291A(N:D340N)

**Query:** A15033G, G22580A, A24838G
**Earliest seq:** 2023-06-02 (EPI_ISL_17821941, NSW, Australia)
**Latest seq:** 2023-06-17 (EPI_ISL_17857957, NSW, Australia)
**Sampled Countries:** Australia (2)

<details><summary>Genomes: </summary>
EPI_ISL_17821941, EPI_ISL_17857957
</details>

**Saltation Profile:**
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/713d224c-5472-46c8-9eb1-03ac1959f484)

Mutation on Nearest Branch:
```
nuc	unique	A3740G, C3984T, A5627G, C8991T, A15033G, G22580A, A24838G, G25091A, G27806A, G29291A
nuc	homoplasies	C1722T, C5575T, C14119T, G22770A
ORF1ab	unique	I1159V, T1240I, T1788A, A2909V
ORF1ab	homoplasies	A486V, P4619S
S	unique	E340K, V1177I
S	homoplasies	R403K
N	unique	D340N
```

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fccd_185f80.json?f_userOrOld=uploaded%20sample&label=id:node_6789302
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/433b5559-4319-4c13-b98a-aa61c8861aa2)

**Trivia:**
- S:N703S used to be tracked cov-lineages/pango-designation#1510 by @FedeGueli , despite not being one of the fastest lineages, it is still growing, query: T17124C,T10204C,A23670G returns 460-ish sequences.
- The whole S:N703S branch is without any known convergent mutations like 478X or 456L, as of now, I woulnd't propose this if it doesn't have R403K.
- A23670G(S:N703S) > G1890A(ORF1a:R542H) branch with query: T10204C,A23670G,G1890A finds 344 seqs, and A2380G sub-branch with query: A23670G,G1890A,A2380G finds 158.
- The nearest branch before saltation is A7754C(ORF1a:K2497Q), C21855T(S:S98F), query: A2380G,A7754C, C21855T finds 5, indicating this may be imported to Australia from Europe.
![recent](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4dceddf0-962b-4068-ae9f-438f3cdfeee4)
- UShER assign it as XBB.1, maybe due to misplaced/weird G27915T(ORF8:G8*) > T17124C > T10204C > T24845C > T23018C(S:F486P) > C24845T > flip-flop path

**Comment by FedeGueli** [comment]
I suspect this could be related to the use of Mov , @ryhisner could you check please ?

**Comment by ryhisner** [comment]
Yup, I've got both of these on my molnupiravir (MOV) list. They both list the same age, so they're almost certainly from the same patient. The Usher tree changed a bit in the time between when the first and second sequences were uploaded, but here are the MOV statistics using the most recent Usher tree version:

<img width="1347" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/88919498-1b7e-40c2-93cd-c6294dc12f44">
