### ISSUE TITLE
EG.6.1 (S:F456L) sublineage with ORF1a:A2584V and ORF1a:T2977K first detected in Florida, USA (249 GISAID seqs as of 2023-09-08; 14 countries)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#306]
There may be a EG.6.1 sublineage with ORF1a:A2584V (C8016T; NSP3:A1766V) and ORF1a:T2977K (C9195A; NSP4:T214K) first detected in Florida, USA.

As of 2023-07-01, Cov-Spectrum reports 24 good-quality (24 total) EG.6.1+ORF1a:2584V+ORF1a:2977K sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AEG.6.1+%26+ORF1a%3AA2584V+%26+ORF1a%3AT2977K&nextcladeQcOverallScoreTo=29&

GISAID shows 25 sequences.

While counts are low and so growth advantage calculations are questionable and geographical sampling biases may cause an illusion, this sublineage shows a possible global growth advantage.

The Bloom and Neher fitness estimates at https://jbloomlab.github.io/SARS2-mut-fitness/ show NSP3:A1766V associated with a fitness increase of 0.977 while NSP4:T214K is associated with a fitness decrease of -0.527. So based on the Bloom and Neher fitness estimates this sublineage may have an advantage over its parent EG.6.1.

As of 2023-07-01, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER-EG 6 1+ORF1a_2584V+ORF1a_2977K](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/df8e05d9-4bc6-4c5d-8f6e-fb2becd9c0cc)

To visualize on UShER: https://nextstrain.org/fetch/raw.githubusercontent.com/alurqu/pango-designation-support-alurqu/main/2023/07/subtreeAuspice1_CoV-Spectrum_EG.6.1%2BORF1a_2584V%2BORF1a_2977K.json?c=gt-ORF1ab_2584&label=id%3Anode_6666924

GISAID query: C8016T, C9195A

First GISAID sequence: Florida, USA 2023-04-25 

Most Recent GenBank sequence: Austria 2023-06-21

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum UShER output files for these sequences is available at [Support-EG.6.1_ORF1a_2584V_ORF1a_2977K.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/11930096/Support-EG.6.1_ORF1a_2584V_ORF1a_2977K.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-EG.6.1+ORF1a_2584V+ORF1a_2977K.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/11930097/gisaid-epi-isl-EG.6.1%2BORF1a_2584V%2BORF1a_2977K.txt).

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=EG.6.1&muts=ORF1a%3AA2584V&muts=ORF1a%3AT2977K.

**Comment by FedeGueli** [comment]
Thx @alurqu has this been flagged to you by your automated query tool?

**Comment by alurqu** [comment]
Yes. The growth advantage will likely come down, but even if it does it could remain notable. These following is from my search output at https://cov-spectrum.org/collections/127: ![Screenshot 2023-07-03 at 05-55-31 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/02a64203-3188-4312-9295-3e5a7ad20fa3)
Note the above is across all countries, and the counts are too low for a full proposal since the growth advantages really aren't reliable. However, it has been detected in five countries on three continents, and based on the Bloom and Neher estimates it has plausible fitness-enhancing mutations, so I decided to submit a pre-proposal in case this lineage keeps growing.

**Comment by alurqu** [comment]
Corrected character transposition in GISAID query.

**Comment by FedeGueli** [comment]
Hi @alurqu is this one still scoring high in your charts?

**Comment by alurqu** [comment]
> Hi @alurqu is this one still scoring high in your charts?

The current CI (low) estimate for this one is 44.66% which would place it in about 11th place on Collection 42 between XBB.1.16.15 and EG.5.1.3.

**Comment by alurqu** [comment]
There is also sibling lineage that shares ORF1a:T2977K but has ORF1a:I4308T (NSP10:I55T) instead of ORF1a:A2584V and that may be at a comparable size with slightly faster growth. Bloom and Neher's data does show a modest growth advantage for NSP10:I55T.

**Comment by FedeGueli** [comment]
207 now

**Comment by FedeGueli** [comment]
Growing but stil slower than EG.5.1 : 
https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C8016T%2CC9195A&analysisMode=CompareToBaseline&

Lets keep it monitored until this mid month. It is above 400 seqs i think a designation will be deserved. But it slowed down to more than -20% of leaders i will ask u to close

**Comment by alurqu** [comment]
It may be appropriate to close this without designation. It is growing but not particularly quickly.

**Comment by FedeGueli** [comment]
Thx closing it
