### ISSUE TITLE
Undesignated XBB.1.5 + G2577T/ORF1a:S771I branch (now proposed in #2082) acquired further ORF1a:N2140S (nsp3_N1322S) then ORF7a:K2E then S:Q613H  (8 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#307]
**Defining Mutations:** [XBB.1.5's T17124C > T23018C] > G2577T(ORF1a:S771I) > A6684G(ORF1a:N2140S) > A27397G(ORF7a:K2E) > G4105A, G23401T(S:Q613H), G26325A >
**Query:** G4105A, G23401T, G26325A
**Earliest seq:** 2023-05-02 (EPI_ISL_17669292, Ireland)
**Latest seq:** 2023-06-08 (EPI_ISL_17826910, Austria)
**Sampled Countries:** Spain (5), Ireland (1), Austria (1), USA (1, New York)

<details><summary>Genomes: </summary>
EPI_ISL_17669292, EPI_ISL_17690209, EPI_ISL_17762986, EPI_ISL_17817698, EPI_ISL_17817751, EPI_ISL_17817800, EPI_ISL_17826910, EPI_ISL_17856012
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_319cf_1bc110.json?f_userOrOld=uploaded%20sample

View from distant XBB.1.5 polytomy
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3892bfa1-9a63-41d2-b8db-1fb9a9360b1c)

Details from ORF7a:K2E branch
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/591bf942-2005-40ce-86fa-5d1e269b75ec)

**Trivia:**
- ORF1a:S771I(G2577T) is one of the largest undesignated XBB.1.5 branch (query: T17124C,G2577T finds 1845), suprisingly it doesn't seem to have any convergent mutations like 478X or 456L yet, judging by the size of this branch. About 380 seqs are collected since May, that is roughly 20%.
- It splits into 2 largest sub-branches, ORF1a:N2140S(A6684G) and C5512T
![branches](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6e7a3e3c-c72e-46d1-90f6-f775142e8933)

- ORF1a:N2140S(A6684G) branch with query: T17124C, G2577T, A6684G returns about 900 seqs, of them about 250 seqs are collected since May, that is rougly 27.8%. 
- C5512T branch with query: T17124C,G2577T, C5512T returns about 660 seqs, and 17% of them (about 110 seqs) are collected since May. Interesting spike mutations to watch: P621A, qurey: C23423G, C2910T, C5512T finds 60.
- ORF7a:K2E(A27397G) is the largest sub-branch of ORF1a:N2140S(A6684G), query: G2577T, A6684G, A27397G finds 378 and about a quarter, that is 101 seqs are collected since May.

**Comment by FedeGueli** [comment]
Please @NkRMnZr let the proposal here but propose the main branch in Pango  i think starting with [Orf1a:S771L](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1faf9_29cf20.json?label=id:node_6874084)
This branch is actually missassigned by Nextclade to XBB.1.5.40 but it includes very interesting lineages , i ve just found another with S: E654K ( just close to the potentially attenuating S:H655Y) and spotted the 621A too.

Please propose the main branch in the pango page and then the subbranches of interest you found here  and i will with the ones found by me too.

ping @corneliusroemer 
the XBB.1.5. branch with Orf1a:S771I is showing some potential:
384 out of 1848 samples are from May ahead , 
50 from June.
Query: G2577T,T17124C

**Comment by FedeGueli** [comment]
@NkRMnZr i have tried to sum up things here: https://github.com/cov-lineages/pango-designation/issues/2082

**Comment by FedeGueli** [comment]
The clearest picture is:
![Schermata 2023-07-03 alle 13 16 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9a9d2b2b-694b-473f-b469-6f5303fea73c)

**Comment by FedeGueli** [comment]
thx for closing slower lineages
