### ISSUE TITLE
GY.6 + N:T165I (105 seqs, 11 countries), further gained S:F456L (7 seqs, China, Thailand)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#308]
**Defining Mutations:** [_On top of XBB.1.16.2's G25429C/ORF3a:V13L_] > G5558A (ORF1a:V1765I) > C28767T (N:T165I)
**Query:** G25429C, G5558A, C28767T
**Earliest seq:** 2023-04-15 (EPI_ISL_17656443, Victoria, Australia)
**Latest seq:** 2023-06-17 (EPI_ISL_17859886, New York, USA)
**Sampled Countries:** USA (15, Nevada/7, California/5, New York/2, New Jersey/1), South Korea (12), Vietnam (12), Japan (10), China (7, Shanghai/5, Fujian/1, Hong Kong/1), France (4) UK (3, England), Austria (2), Canada (2, Alberta), Australia (1, Victoria)

<details><summary>Genomes: </summary>
EPI_ISL_17605696, EPI_ISL_17614094, EPI_ISL_17645700, EPI_ISL_17651183, EPI_ISL_17656443, EPI_ISL_17660091, EPI_ISL_17666278, EPI_ISL_17677505, EPI_ISL_17677506, EPI_ISL_17704323, EPI_ISL_17707036, EPI_ISL_17715317, EPI_ISL_17716674, EPI_ISL_17716740, EPI_ISL_17718486, EPI_ISL_17718502, EPI_ISL_17718522, EPI_ISL_17718532, EPI_ISL_17718538, EPI_ISL_17718540, EPI_ISL_17718575, EPI_ISL_17718683, EPI_ISL_17725321, EPI_ISL_17725449, EPI_ISL_17730728, EPI_ISL_17762907, EPI_ISL_17770004, EPI_ISL_17778977, EPI_ISL_17780169, EPI_ISL_17782205, EPI_ISL_17791418, EPI_ISL_17791457, EPI_ISL_17791495, EPI_ISL_17791500, EPI_ISL_17792393, EPI_ISL_17793216, EPI_ISL_17795482, EPI_ISL_17801907, EPI_ISL_17807501, EPI_ISL_17810191, EPI_ISL_17811376, EPI_ISL_17811378, EPI_ISL_17813206, EPI_ISL_17835785, EPI_ISL_17837311, EPI_ISL_17837331, EPI_ISL_17837332, EPI_ISL_17837335, EPI_ISL_17838148, EPI_ISL_17853518, EPI_ISL_17859886, EPI_ISL_17880495, EPI_ISL_17881425, EPI_ISL_17882018, EPI_ISL_17882132, EPI_ISL_17882707, EPI_ISL_17884140, EPI_ISL_17884141, EPI_ISL_17927771, EPI_ISL_17927932, EPI_ISL_17927955, EPI_ISL_17928115, EPI_ISL_17928132, EPI_ISL_17930740, EPI_ISL_17950975, EPI_ISL_17950976, EPI_ISL_17950978, EPI_ISL_17950990
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ce73_1c3480.json?f_userOrOld=uploaded%20sample&label=id:node_6626676&showBranchLabels=all

view from XBB.1.16.2 polytomy:
![Overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b92900b8-bc40-4054-af50-821c5e17b9b3)

details:
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7dcffe68-9374-43e7-be50-b81e9845bfec)

**Trivia:**
- Split branches on UShER are due to theese seqs: EPI_ISL_17602918, EPI_ISL_17720650, potential dropout?
- Should hypothetical ORF9c ever got secreted, C28767T would only bring it to ORF9c:Q12*
- This could be something with high prevalence in Vietnam, but hard to tell due to low seqs count.
![comparison](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0ae7c9d8-aa31-477f-9b6e-a5615f71ff06)
- Now there's a branch got S:F456L(T22928C), query: T22928C, C28767T, T17154C

**Comment by FedeGueli** [comment]
> Tracking updates:
> 
> 23-07-13: 5 seqs from 3 countries

none with 456L?

**Comment by FedeGueli** [comment]
> > > Tracking updates:
> > > 23-07-13: 5 seqs from 3 countries
> > 
> > 
> > none with 456L? yeah none checked with G10805A ,T22928C,C28767T
> 
> Try this: T22928C, C28767T, T17154C

i was meaning no new 456L sequence

**Comment by Over-There-Is** [comment]
The parental branch has been designated as GY.6.

**Comment by Over-There-Is** [comment]
But the C28767T (N:T165I) branch is not designated yet. @FedeGueli

**Comment by FedeGueli** [comment]
One more in the 456L sublineage.

**Comment by FedeGueli** [comment]
Still very slow so closing it.
