### ISSUE TITLE
FL.21.1 sublineage with S:E554A (55 seqs, 3 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#310]
FL.21.1>A23223C(S:E554A)
Query: A10564T, G24812A, A23223C
Query for Spike-only sequences: -A10564T, G24812A, A23223C

Earliest Sequence: 05-17 South Korea EPI_ISL_17779508
Latest Sequence: 08-11 Shanghai, China (from South Korea) EPI_ISL_18114827
Regions Detected: South Korea 41, Japan 13(Miyagi 9, Aichi 1, Osaka 1, Kumamoto 1, Fukushima 1), China 1(Shanghai, from South Korea)

[usher](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_1644e_1aac30.json?c=country&label=id:node_6650164)
![2023-07-28 (15)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/92a74e52-0330-473f-b113-234dace6c136)

<details><summary>Sequences:</summary>

EPI_ISL_17779508, EPI_ISL_17806987, EPI_ISL_17807735,
EPI_ISL_17807799, EPI_ISL_17834671, EPI_ISL_17834716,
EPI_ISL_17834802, EPI_ISL_17835536, EPI_ISL_17927834,
EPI_ISL_17928022, EPI_ISL_17930351-17930352, EPI_ISL_17930524,
EPI_ISL_17930738, EPI_ISL_17930770, EPI_ISL_17930788,
EPI_ISL_17969649, EPI_ISL_17970231, EPI_ISL_17983473,
EPI_ISL_17983597, EPI_ISL_17983674, EPI_ISL_18006638,
EPI_ISL_18006680, EPI_ISL_18006973, EPI_ISL_18031032,
EPI_ISL_18031407, EPI_ISL_18031593, EPI_ISL_18038785,
EPI_ISL_18040361, EPI_ISL_18046791, EPI_ISL_18046823,
EPI_ISL_18048831, EPI_ISL_18062976, EPI_ISL_18063082,
EPI_ISL_18065036, EPI_ISL_18065062, EPI_ISL_18068266,
EPI_ISL_18068286-18068287, EPI_ISL_18068289, EPI_ISL_18068389,
EPI_ISL_18068451, EPI_ISL_18097085, EPI_ISL_18114827,
EPI_ISL_18116485, EPI_ISL_18116641, EPI_ISL_18117062,
EPI_ISL_18117420, EPI_ISL_18117562, EPI_ISL_18117753,
EPI_ISL_18127204, EPI_ISL_18130108, EPI_ISL_18130114-18130115,
EPI_ISL_18130215

South Korean sequences with only spike gene:
EPI_ISL_17973587, EPI_ISL_18032896
</details>

<details><summary>Original proposal(Already transfer to cov-lineages/pango-designation#2143 and designated as FL.21.1):</summary>

FL.21>G24812A(S:D1084N)
Query: A10564T, G24812A
Query for the sub branch with **S:E554A**: G24812A, A23223C (Edited)
Earliest Sequence: 03-15 South Korea EPI_ISL_17416089
Latest Sequence: 07-04 Miyagi, Japan EPI_ISL_18006680
Regions Detected: **South Korea** 103(2 from **Hungary**, 1 from **Vietnam**), **US** 5(Illinois 1, New York 4[2 from **France**, 2 airport screening]), **Japan** 3(Miyagi 2, Aichi 1)
[usher](https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_1644e_1aac30.json?label=id:node_6650137)
![2023-07-03 (8)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/522ea849-9e70-410a-8000-6df26340ccb8)
<details><summary>Sequences:</summary>

EPI_ISL_17416089, EPI_ISL_17474202, EPI_ISL_17538340,
EPI_ISL_17538970, EPI_ISL_17563149, EPI_ISL_17563510-17563511,
EPI_ISL_17563894, EPI_ISL_17564203, EPI_ISL_17604126,
EPI_ISL_17604319, EPI_ISL_17604509, EPI_ISL_17605279,
EPI_ISL_17647080, EPI_ISL_17647312, EPI_ISL_17647712,
EPI_ISL_17648476, EPI_ISL_17677458, EPI_ISL_17677474,
EPI_ISL_17690590, EPI_ISL_17690642, EPI_ISL_17690852-17690853,
EPI_ISL_17690907, EPI_ISL_17691393, EPI_ISL_17691407,
EPI_ISL_17691481, EPI_ISL_17691511, EPI_ISL_17691576,
EPI_ISL_17723168, EPI_ISL_17723763, EPI_ISL_17723886-17723887,
EPI_ISL_17723907, EPI_ISL_17730353, EPI_ISL_17730809,
EPI_ISL_17740690-17740691, EPI_ISL_17741074, EPI_ISL_17741235,
EPI_ISL_17741293, EPI_ISL_17741444, EPI_ISL_17778935,
EPI_ISL_17778949, EPI_ISL_17779369, EPI_ISL_17779508,
EPI_ISL_17779662, EPI_ISL_17779670, EPI_ISL_17779810,
EPI_ISL_17791879, EPI_ISL_17791929, EPI_ISL_17792387,
EPI_ISL_17792406, EPI_ISL_17804392, EPI_ISL_17806987,
EPI_ISL_17807266, EPI_ISL_17807326, EPI_ISL_17807735,
EPI_ISL_17807739, EPI_ISL_17807799, EPI_ISL_17807913,
EPI_ISL_17816709-17816710, EPI_ISL_17816741, EPI_ISL_17834671,
EPI_ISL_17834716, EPI_ISL_17834802, EPI_ISL_17834901,
EPI_ISL_17835089, EPI_ISL_17835341, EPI_ISL_17835526,
EPI_ISL_17835536, EPI_ISL_17835572, EPI_ISL_17835723,
EPI_ISL_17835728, EPI_ISL_17835771, EPI_ISL_17927834,
EPI_ISL_17927968, EPI_ISL_17928017, EPI_ISL_17928020,
EPI_ISL_17928022, EPI_ISL_17930351-17930352, EPI_ISL_17930524,
EPI_ISL_17930738, EPI_ISL_17930770, EPI_ISL_17930788,
EPI_ISL_17969516, EPI_ISL_17969649, EPI_ISL_17970094,
EPI_ISL_17970231, EPI_ISL_17970350, EPI_ISL_17970391,
EPI_ISL_17983473, EPI_ISL_17983597, EPI_ISL_17983631,
EPI_ISL_17983674, EPI_ISL_17984145, EPI_ISL_17984409,
EPI_ISL_18006638, EPI_ISL_18006680, EPI_ISL_18006973,
EPI_ISL_18030754, EPI_ISL_18030792, EPI_ISL_18031032,
EPI_ISL_18031269, EPI_ISL_18031381, EPI_ISL_18031407,
EPI_ISL_18031544, EPI_ISL_18031593, EPI_ISL_18038785
</details>
</details>

**Comment by FedeGueli** [comment]
This a subbranch with S:E554A better tracking it too in the headline

**Comment by Over-There-Is** [comment]
Korea +8, 3 with E554A

**Comment by Over-There-Is** [comment]
There are 2 Korean spike-only sequences with E554A and D1084N.

**Comment by Over-There-Is** [comment]
With query `T23018C, T23019C, G24812A`, all the 103 Korean sequences can be found, and 6 extra spike-only sequences.
117 seq and 30 with E554A?

**Comment by FedeGueli** [comment]
Please propose it . thx for the new query.

**Comment by FedeGueli** [comment]
FL.21.1

**Comment by Over-There-Is** [comment]
Detected by one more Japanese prefecture.

**Comment by Over-There-Is** [comment]
Korea+8; Miyagi, Japan+2

**Comment by Over-There-Is** [comment]
Fukushima +1

**Comment by Over-There-Is** [comment]
China +1(Shanghai)

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/21082f78-07eb-4664-8bc8-aa70c7c64cac)

The E554A branch is much faster than its parent.

**Comment by Over-There-Is** [comment]
South Korea +6

**Comment by FedeGueli** [comment]
Please propose it.
