### ISSUE TITLE
EU.1.1 with Orf8: A51V and its sublineage with S:F157L emerging in Germany.

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#312]
Mutations on top of EU.1.1: Seemingly just Orf8:A51V
Gisaid Inquiry: Spike_I410V,P521S, F486P +C28045T
Sequences: EPI_ISL_17070943, EPI_ISL_17080159, EPI_ISL_17113008,
EPI_ISL_17113070, EPI_ISL_17184064, EPI_ISL_17184110,
EPI_ISL_17184731, EPI_ISL_17186627, EPI_ISL_17189053,
EPI_ISL_17189727, EPI_ISL_17209859, EPI_ISL_17210328,
EPI_ISL_17247464, EPI_ISL_17254193, EPI_ISL_17256409,
EPI_ISL_17257719, EPI_ISL_17257725, EPI_ISL_17258824,
EPI_ISL_17258856, EPI_ISL_17258867, EPI_ISL_17258871,
EPI_ISL_17264453, EPI_ISL_17264729, EPI_ISL_17269020,
EPI_ISL_17269098, EPI_ISL_17269145, EPI_ISL_17274196,
EPI_ISL_17293263, EPI_ISL_17293268, EPI_ISL_17296694,
EPI_ISL_17307289, EPI_ISL_17315222, EPI_ISL_17315650,
EPI_ISL_17315776, EPI_ISL_17326805, EPI_ISL_17327319,
EPI_ISL_17344347, EPI_ISL_17344437, EPI_ISL_17348202,
EPI_ISL_17375588, EPI_ISL_17389819, EPI_ISL_17390163,
EPI_ISL_17394255, EPI_ISL_17394273, EPI_ISL_17397852,
EPI_ISL_17397861, EPI_ISL_17397875, EPI_ISL_17397878,
EPI_ISL_17398093, EPI_ISL_17398138, EPI_ISL_17398161,
EPI_ISL_17407395, EPI_ISL_17410155, EPI_ISL_17414522,
EPI_ISL_17440463, EPI_ISL_17442569, EPI_ISL_17463547,
EPI_ISL_17464666, EPI_ISL_17468239-17468240, EPI_ISL_17468245,
EPI_ISL_17468978, EPI_ISL_17469510, EPI_ISL_17472154,
EPI_ISL_17472339, EPI_ISL_17472996, EPI_ISL_17479759,
EPI_ISL_17479773, EPI_ISL_17479789, EPI_ISL_17479796,
EPI_ISL_17486216, EPI_ISL_17495725, EPI_ISL_17500222,
EPI_ISL_17500231, EPI_ISL_17510436, EPI_ISL_17513880,
EPI_ISL_17513897, EPI_ISL_17513979, EPI_ISL_17514036,
EPI_ISL_17514081, EPI_ISL_17515603, EPI_ISL_17515723,
EPI_ISL_17515785, EPI_ISL_17518756, EPI_ISL_17519958,
EPI_ISL_17521277, EPI_ISL_17525535, EPI_ISL_17525546,
EPI_ISL_17525566, EPI_ISL_17525597, EPI_ISL_17528546,
EPI_ISL_17528548, EPI_ISL_17534789, EPI_ISL_17538356,
EPI_ISL_17540658, EPI_ISL_17541356, EPI_ISL_17547763,
EPI_ISL_17547794, EPI_ISL_17547873, EPI_ISL_17553208,
EPI_ISL_17554952, EPI_ISL_17556024, EPI_ISL_17562745-17562746,
EPI_ISL_17562758, EPI_ISL_17566113, EPI_ISL_17590797,
EPI_ISL_17598039, EPI_ISL_17598106, EPI_ISL_17598246,
EPI_ISL_17607643, EPI_ISL_17615685, EPI_ISL_17621307,
EPI_ISL_17621537, EPI_ISL_17621620, EPI_ISL_17623544,
EPI_ISL_17625217, EPI_ISL_17625495, EPI_ISL_17629574,
EPI_ISL_17634144-17634145, EPI_ISL_17637468-17637472, EPI_ISL_17637476,
EPI_ISL_17637478-17637479, EPI_ISL_17639585, EPI_ISL_17653975,
EPI_ISL_17654084, EPI_ISL_17654208, EPI_ISL_17654216-17654217,
EPI_ISL_17654220, EPI_ISL_17654226, EPI_ISL_17662342,
EPI_ISL_17662357, EPI_ISL_17669094, EPI_ISL_17669109,
EPI_ISL_17672116, EPI_ISL_17679514, EPI_ISL_17680110,
EPI_ISL_17685531, EPI_ISL_17685635, EPI_ISL_17687076-17687077,
EPI_ISL_17689197, EPI_ISL_17695136, EPI_ISL_17700382,
EPI_ISL_17700422, EPI_ISL_17700431, EPI_ISL_17701166,
EPI_ISL_17701171, EPI_ISL_17701277, EPI_ISL_17701359-17701360,
EPI_ISL_17701364, EPI_ISL_17701384-17701385, EPI_ISL_17701391,
EPI_ISL_17701408-17701409, EPI_ISL_17701490-17701491, EPI_ISL_17704028,
EPI_ISL_17714378, EPI_ISL_17716653, EPI_ISL_17723535,
EPI_ISL_17731392, EPI_ISL_17732709, EPI_ISL_17742515,
EPI_ISL_17744615, EPI_ISL_17763218, EPI_ISL_17763400,
EPI_ISL_17764136, EPI_ISL_17765825, EPI_ISL_17769744,
EPI_ISL_17770416, EPI_ISL_17775297, EPI_ISL_17775340,
EPI_ISL_17775526, EPI_ISL_17777366, EPI_ISL_17777370-17777372,
EPI_ISL_17778116, EPI_ISL_17781969, EPI_ISL_17782526,
EPI_ISL_17783467, EPI_ISL_17785250, EPI_ISL_17785859,
EPI_ISL_17787480, EPI_ISL_17789472, EPI_ISL_17794036,
EPI_ISL_17794109, EPI_ISL_17795414, EPI_ISL_17795575-17795576,
EPI_ISL_17795683, EPI_ISL_17795754-17795755, EPI_ISL_17795761,
EPI_ISL_17795764, EPI_ISL_17795771, EPI_ISL_17795842,
EPI_ISL_17795851, EPI_ISL_17795859, EPI_ISL_17795893,
EPI_ISL_17796124, EPI_ISL_17796145, EPI_ISL_17796153,
EPI_ISL_17796242, EPI_ISL_17796359, EPI_ISL_17796409,
EPI_ISL_17803414, EPI_ISL_17803439, EPI_ISL_17804455,
EPI_ISL_17815870, EPI_ISL_17826702, EPI_ISL_17826738,
EPI_ISL_17826777, EPI_ISL_17826963, EPI_ISL_17827001,
EPI_ISL_17827098, EPI_ISL_17827105, EPI_ISL_17827111,
EPI_ISL_17831364, EPI_ISL_17831367, EPI_ISL_17832609,
EPI_ISL_17833139, EPI_ISL_17833158, EPI_ISL_17836379,
EPI_ISL_17836612, EPI_ISL_17837081, EPI_ISL_17837085,
EPI_ISL_17838493, EPI_ISL_17849208-17849210, EPI_ISL_17849244-17849248,
EPI_ISL_17850919, EPI_ISL_17850921, EPI_ISL_17852904,
EPI_ISL_17855095, EPI_ISL_17855995, EPI_ISL_17859517,
EPI_ISL_17859519, EPI_ISL_17859524, EPI_ISL_17859532,
EPI_ISL_17859547, EPI_ISL_17880364, EPI_ISL_17880920,
EPI_ISL_17880998, EPI_ISL_17881022, EPI_ISL_17881070,
EPI_ISL_17881120, EPI_ISL_17881224, EPI_ISL_17881260,
EPI_ISL_17883447, EPI_ISL_17950463, EPI_ISL_17954916,
Earliest Sequence: EPI_ISL_17080159 Netherland 02-07,2023
Latest Sequence: EPI_ISL_17881224 Austria 06-21, 2023
Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_88af_363070.json?f_userOrOld=uploaded%20sample&label=id:node_2991533

Comment: This is weird because I would consider Orf8 mutations after XBB.1* gaining Orf8:G8* to be quasi-silent, yet Orf8:A51V seems to randomly appear among different variants. For example, it is spotted in #33 as part of the mutation chain. This strain seems to be the parent of my lineage B in #274 .
It has shown quite significant growth compared to EU.1.1* base, and could be the reason behind EU.1.1*'s recent recovery in variant share.
<img width="890" alt="2E6B2098-C5BD-4377-AC9C-3EF1733DF90C" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/0500254b-9d9e-41ad-93b7-679c480f24ec">

Edited 
Recently a sublineage of this popped up in GERMANY:
Mutations:C28045T(ORF8:A51V)+C22033A(S:157L)+C14322T on EU.1.1*
Inquiry: C22033A,C28045T,C14322T
Distribution: Austria,GERMANY, NORWAY,USA
Sequences: 28 (Updated)
EPI_ISL_17685531, EPI_ISL_17700382, EPI_ISL_17700422,
EPI_ISL_17782526, EPI_ISL_17803439, EPI_ISL_17810615,
EPI_ISL_17826702, EPI_ISL_17826738, EPI_ISL_17826777,
EPI_ISL_17826963, EPI_ISL_17827001, EPI_ISL_17827098,
EPI_ISL_17827105, EPI_ISL_17827111, EPI_ISL_17833139,
EPI_ISL_17837081, EPI_ISL_17837085
Earliest:
EPI_ISL_17685531 ,GERMANY, 05-02,2023
Latest: EPI_ISL_17827111 Austria 06-13,2023
Usher Individual Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26cf5_ca3a80.json?f_userOrOld=uploaded%20sample&label=id:node_4922117

**Comment by FedeGueli** [comment]
Please tranfer this and its sublineage S:F157L in one issue together on pango Page.  Please mention the recent  157L sublineage in the headline , (to me that is the amin proposal but right to make pango committee aware of the weird orf8 post truncation defining mutation of this branch, they will choose then if this will grow further.

**Comment by FedeGueli** [comment]
Designated
