### ISSUE TITLE
XBB.1.16 with Orf9b:P3S, N:P6L, S:V1264L in China (12 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#313]
XBB.1.16+C28290T(Orf9b:P3S, N:P6L)+S:V1264L (G25352T)

GISAID query: G25352T,C28290T,T28297C,C22995G,C11750T
No. of seqs: 8(Hubei, China)
First: EPI_ISL_17625342, 2023-5-2
Latest: EPI_ISL_17837038, 2023-6-19

The XBB.1.16+C28290T branch itself is quite interesting. 
GISAID query:C28290T,T28297C,C22995G,C11750T (91 seqs, 11 countries globally)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1245b_39b2e0.json?label=id:node_2909636)

![屏幕截图 2023-07-04 122547](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1d492580-67a5-4eaf-90b6-ba3de4ea91b2)

**Comment by FedeGueli** [comment]
N:P6L was the defining of AY.36.1 a fast late lineage emerged in Germany. I routinely chceked for that mutation and as today it was not successful in any omicron lineage, but very good to check it here.
Plus i didnt realize at that time it is also an Orf9b mutation
