### ISSUE TITLE
XBB.1.5.94 (S:Q613H) +11-nuc,5-aa including S:478R (10 seqs, 6 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#314]
XBB.1.5.94+A8434G, A15426G + A2730T(orf1a:K822M), T3766C + C7086T(orf1a:T2274I)+T3460C, C11460A(orf1a:S3732Y, NSP6_S163Y), C15240T, A22995G(S:478R), A26915G, G28090A(orf8:G66D)

GISAID query: T3460C,C11460A,C15240T,C22995G,A26915G,G28090A

No. of seqs: 2
EPI_ISL_17956887, EPI_ISL17956891, 2023-6-24

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice30_genome_1245b_39b370.json?label=id:node_2970323)

![屏幕截图 2023-07-04 125136](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/db854159-8014-4778-a76e-1d1c525dc07d)

**Comment by FedeGueli** [comment]
> There might be something wrong with UShER, T10204C,T17124C are hallmarks of XBB.1.5, this kind of mis-assignment happened in #305 too.
> 
> And this one _does_ have ORF8:G8*(G27915T), assuming it could be misplaced XBB.1.5*.

@angiehinrichs

**Comment by aviczhl2** [comment]
> There might be something wrong with UShER, T10204C,T17124C are hallmarks of XBB.1.5, this kind of mis-assignment happened in #305 too.
> 
> And this one _does_ have ORF8:G8*(G27915T), assuming it could be misplaced XBB.1.5*.

I think this shall be XBB.1.5 too, however usher categorizes it into XBB.1. 

Do you find any unnoticed mutations hiding in the root to let it show XBB.1.

**Comment by AngieHinrichs** [comment]
> There might be something wrong with UShER, T10204C,T17124C are hallmarks of XBB.1.5, this kind of mis-assignment happened in https://github.com/sars-cov-2-variants/lineage-proposals/issues/305 too.

Thanks @ NkRMnZr for flagging this and @FedeGueli for tagging me in.  Yes, the whole XBB.1.5 > G27915T > T10204C with 110k sequences was moved to an XBB.1 branch with questionable sequences.  I will try to fix that soon.

**Comment by aviczhl2** [comment]
+3 from South Korea.

**Comment by aviczhl2** [comment]
+1 Canada +1 France

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by FedeGueli** [comment]
Here is the new tree:
![Schermata 2023-07-25 alle 11 36 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4ecc43d2-89de-4e8b-ac5b-5dbead1ecfc9)
![Schermata 2023-07-25 alle 11 36 32](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9e268739-5e1f-40c8-8491-bb55b08d847d)
![Schermata 2023-07-25 alle 11 36 58](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ae835476-b9bc-40e4-971d-52cdd6a67981)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_174e3_f96350.json?c=gt-S_478&label=id:node_6858822

Looking at the collection dates i think this is fast. Propose it when it reaches 10 . (yeah a bit risky but this tree is quite striking a lineage dead back in april in all its branches then suddenly popping up in multiple countries)

**Comment by aviczhl2** [comment]
> Looking at the collection dates i think this is fast. Propose it when it reaches 10 . (yeah a bit risky but this tree is quite striking a lineage dead back in april in all its branches then suddenly popping up in multiple countries)

It's just circulating in one of the >80% regions on earth that stopped uploading sequences.

**Comment by FedeGueli** [comment]
> > Looking at the collection dates i think this is fast. Propose it when it reaches 10 . (yeah a bit risky but this tree is quite striking a lineage dead back in april in all its branches then suddenly popping up in multiple countries)
> 
> It's just circulating in one of the >80% regions on earth that stopped uploading sequences.
> 
> Even in countries that still uploads seqs, not all its regions do so.
> 
> Here is a list of Chinese provinces that stopped uploading seqs (no seqs uploaded after 6.1):
> 
> Chongqing, Guangdong, Guangxi, Guangxi, Hainan, Hebei, Hunan, Jilin, Inner Mongolia, Ningxia, Shannxi, Shandong, Tibet, Macau

Yeah but if that would be true we should see every lineage doing this, and we are not seeing that.

**Comment by aviczhl2** [comment]
> Yeah but if that would be true we should see every lineage doing this, and we are not seeing that.

Not every lineage circulates at undersampled regions. Most do die out. 

The point is that we can no longer tell them apart until it infected really large amount of people and starts to overflow enough cases to a sampling region. (For sampling regions, you still need 100-10000 infections for one seq, so a lineage needs to overflow enough number of infected people.)

**Comment by aviczhl2** [comment]
+1 USA airport. I'll propose this.
