### ISSUE TITLE
FY.3.1 (XBB.1.22.1.3.1) sublineage with S:Y266C (5 seqs in Singapore and China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#317]
Defining mutations: FY.3.1>G4109T (ORF1a:D1282Y)>C21998A (S:Q146K)>C11416T>A22359G (S:Y266C)
GISAID query: Spike_Y200C, Spike_Y266C (OR: A22161G, A22359G, C11416T)
Earliest seq: 2023-05-26 (Shanghai Municipality, China- EPI_ISL_17795154)
Most recent seq: 2023-06-26 (Singapore, EPI_ISL_17957357)
Countries detected: Singapore (3), China (2)

Usher Tree:
![QQ截图20230704160601](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/60928b09-ee7c-4b45-98db-14f2fc03282e)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_294ad_3b0b70.json?c=gt-S_266

Another S:Y→C aa mutation after the S:Y200C (defining mutation of XBB.1.22.1) , which is relatively rare. We can track it for a time.

P.S. I suggest FY.3.1 with S:Q146K could be desingated.

Genomes:
EPI_ISL_17795154, EPI_ISL_17830479, EPI_ISL_17837753, EPI_ISL_17957249, EPI_ISL_17957357

**Comment by FedeGueli** [comment]
Closing this unless new seqs will come
