### ISSUE TITLE
EG.1 with ORF1b:P2409S (nsp16_P12S), S:A701V and S:S704L (3 seqs, South Korea)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#318]
**Defining Mutations:** EG.1 > G26235T > C23422T > T18759C, C20692T(ORF1b:P2409S), C23664T(S:A701V) > C23673T(S:S704L)
**Query:** T18759C, C20692T, C23664T, C23673T
**Earliest seq:** 2023-06-10 (EPI_ISL_17816899, South Korea)
**Latest seq:** 2023-06-10 (EPI_ISL_17816896, South Korea)
**Sampled Countries:** South Korea

<details><summary>Genomes: </summary>
EPI_ISL_17816896, EPI_ISL_17816898, EPI_ISL_17816899
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c9ad_3e6710.json

view from G26235T sub-branch of EG.1
![G26235T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ec838050-acf5-418d-b955-cfaf2f4ba223)

details from G26235T > C23422T sub-branch
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e78e7e16-a71e-4f7f-81ee-91662b6e93fc)

**Trivia:**
- EG.1's undesignated G26235T branch with query: G23401T, C28928T, G26235T returns 1360.
- 26235 is within the UTR region downstream of ORF3a, upsteam of E, may have to do something with TRS? Not sure about this, maybe @ryhisner could shed some light :)
![trs](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e0043829-1113-4bed-b698-bf11f7ec1b0e)

- There are many other interesting sub-branches of undesignated G26235T branch:

1. EG.1 > G26235T > A25470G > G256A, C22995G(S:T478R), C26139T [query: A25470G, C22995G, C26139T] branch also got 2 seqs with S:S477K(C22993A on top of existing G22992A/S:S477N) [query: C22993A, C22995G, C26139T returns 2], luckily it has gone stale.

2. EG.1 > G26235T > C23422T > C25549T(ORF3a:L53F) > C26571T(M:L17F) [query: C26571T, C25549T, G26235T returns 50]

3. EG.1 > G26235T > G28423C(ORF9b:R47P) [query: G23401T, C28928T, G26235T, G28423C returns 460]

- C23422T is a silent S gene mutation on V620, adjacent to hotspot P621 (eg. P621S)
- S:A701V and S:S704L can be found separately in many recent designated lineages, gotta see how they work together (used to work well on some BA.2.12.1*)

**Comment by FedeGueli** [comment]
Interesting to see how it goes with this combo at the start of S2.  XAY and XBC have mutations in that region and many lineages are acquiring mutation there too. Lets see how it goes

**Comment by FedeGueli** [comment]
Closing this by now
