### ISSUE TITLE
FY.3.1 sublineage with nucleotide deletion 22294-22296 (S:L244- and S:H245F) -35 seqs in 5 countries, mainly in China

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#322]
Defining mutations: FY.3.1>G4109T (ORF1a:D1282Y)>The possible branch (Usher could not show the deletion branch?) 
GISAID query: Spike_Y200C, Spike_L244 (one seq has 4 deletions), G4109T (Maybe I should find a more clear query)
Earliest seq: 2023-05-09 (Anhui Province, China- EPI_ISL_17808319)
Most recent seq: 2023-06-24 (Shanghai Municipality, China- EPI_ISL_17956886)
Countries detected: Countries detected: China (15), South Korea (2), US (1), Austria (1), Israel (1)

Usher Tree: (Samples are shown in red points)
![9499BD05-5C82-48AB-B17F-FEF49E258BDF](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/2f470b21-bcdf-4417-940b-1ed72dbe36af)

The actual deletion nucs are 22294-22296, and it seems that Usher could not show the deletion branch clearly. However, 18 of all the 20 samples get nuc mutation C245A, while all other FY.3.1 samples do not get the mutation, hence I think C245A is also associated with the branch.
Besides, it contains a saltation seq (with 2 Spike mutation S:T286I, S:T883N and 6 non-Spike aa mutations), and it also can be tracked.   
![QQ截图20230705004719](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/2bc6b57c-2542-45e6-b7b4-1c60dc986a87)
![QQ截图20230705005107](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/dda71b9c-a149-438b-bccf-3b9b9aa48dc2)

Genomes:
EPI_ISL_17725081, EPI_ISL_17725083, EPI_ISL_17770021, EPI_ISL_17770080, EPI_ISL_17775215, EPI_ISL_17794024, EPI_ISL_17794027, EPI_ISL_17795397, EPI_ISL_17801798, EPI_ISL_17808139, EPI_ISL_17808598, EPI_ISL_17818552, EPI_ISL_17835387, EPI_ISL_17835606, EPI_ISL_17836850, EPI_ISL_17836901, EPI_ISL_17953563, EPI_ISL_17956863, EPI_ISL_17956886, EPI_ISL_17957166

**Comment by HynnSpylor** [comment]
one more seq from US (San Francisco International Airport)

**Comment by HynnSpylor** [comment]
35 seqs now (all new updated in China)

**Comment by FedeGueli** [comment]
Time to propose it. Maybe @corneliusroemer hardly will find it on his own not appearing on Usher.
