### ISSUE TITLE
Major branch of FL.4.6 with A264G and C6558T (Orf1a:A2098V=NSP3_A1280V) mostly in China 222 seqs

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#324]
Mutations on top of FL.4.6( Defined as FL.4+T5098C, C13965T, which in practical matter happens after acquiring A28615G and C23635T)
Gisaid Inquiry: Spike_F486P+ A264G, C6558T or **A264G, C6558T,T5098C, C13965T** (edited)
Sequences: EPI_ISL_17584623-17584625, EPI_ISL_17584658, EPI_ISL_17584673,
EPI_ISL_17615017, EPI_ISL_17618800, EPI_ISL_17619004,
EPI_ISL_17625335, EPI_ISL_17631219, EPI_ISL_17645670,
EPI_ISL_17649175, EPI_ISL_17649202, EPI_ISL_17649222-17649223,
EPI_ISL_17664526, EPI_ISL_17669242, EPI_ISL_17672479,
EPI_ISL_17678655, EPI_ISL_17678672, EPI_ISL_17684031,
EPI_ISL_17684098, EPI_ISL_17684167, EPI_ISL_17684201,
EPI_ISL_17694905, EPI_ISL_17697607, EPI_ISL_17697614,
EPI_ISL_17697707, EPI_ISL_17697791, EPI_ISL_17697821,
EPI_ISL_17697827, EPI_ISL_17697871, EPI_ISL_17697903,
EPI_ISL_17697924, EPI_ISL_17697963, EPI_ISL_17697967,
EPI_ISL_17698143, EPI_ISL_17698157, EPI_ISL_17698165,
EPI_ISL_17698168, EPI_ISL_17698178, EPI_ISL_17698214,
EPI_ISL_17698230, EPI_ISL_17698232, EPI_ISL_17698254-17698255,
EPI_ISL_17698268, EPI_ISL_17698272, EPI_ISL_17698278,
EPI_ISL_17698289, EPI_ISL_17703967, EPI_ISL_17714193,
EPI_ISL_17714269, EPI_ISL_17714375, EPI_ISL_17714407,
EPI_ISL_17724991, EPI_ISL_17735987, EPI_ISL_17736032,
EPI_ISL_17736080, EPI_ISL_17736082, EPI_ISL_17738969,
EPI_ISL_17739670, EPI_ISL_17739675, EPI_ISL_17739699,
EPI_ISL_17739740, EPI_ISL_17739770, EPI_ISL_17739796,
EPI_ISL_17739824, EPI_ISL_17739846, EPI_ISL_17739858,
EPI_ISL_17744665, EPI_ISL_17744740, EPI_ISL_17744793,
EPI_ISL_17769989, EPI_ISL_17770028, EPI_ISL_17770116,
EPI_ISL_17770395, EPI_ISL_17773893, EPI_ISL_17775162,
EPI_ISL_17775406, EPI_ISL_17775577, EPI_ISL_17775610,
EPI_ISL_17778649, EPI_ISL_17778731, EPI_ISL_17778769,
EPI_ISL_17785334, EPI_ISL_17789602, EPI_ISL_17790436,
EPI_ISL_17790569, EPI_ISL_17794384-17794385, EPI_ISL_17794388-17794389,
EPI_ISL_17794418, EPI_ISL_17794635, EPI_ISL_17794772,
EPI_ISL_17795019, EPI_ISL_17795299, EPI_ISL_17801794,
EPI_ISL_17801805, EPI_ISL_17801839, EPI_ISL_17808305,
EPI_ISL_17808336, EPI_ISL_17808400, EPI_ISL_17808437,
EPI_ISL_17812467, EPI_ISL_17821771-17821780, EPI_ISL_17821784-17821786,
EPI_ISL_17830407, EPI_ISL_17835868, EPI_ISL_17836833,
EPI_ISL_17836902, EPI_ISL_17850287, EPI_ISL_17850329,
EPI_ISL_17850359, EPI_ISL_17850377, EPI_ISL_17850455-17850456,
EPI_ISL_17850483, EPI_ISL_17856232, EPI_ISL_17856234,
EPI_ISL_17856903, EPI_ISL_17871658, EPI_ISL_17882105,
EPI_ISL_17882195, EPI_ISL_17884997, EPI_ISL_17951278,
EPI_ISL_17951324, EPI_ISL_17952715, EPI_ISL_17957020,
Earliest Sequence: EPI_ISL_17584673 Guangdong, China, 04-12, 2023
Latest Sequence: EPI_ISL_17850483 Heilongjiang, China, 06-18, 2023
Geographical Distribution: 19 Canada, 102 China ( about 10 different provinces of China distanced several thousand miles away), 1HK, 1 Indonesia, 10 Japan, 1 Netherland, 1 New Zealand, 3 Singapore, 1 Spain, 2 US
Usher Tree Depicting its prominance among FL.4.6
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3bf97_386910.json?f_userOrOld=uploaded%20sample 
Individual Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38789_45a650.json?f_userOrOld=uploaded%20sample
Its Growth compared to FL.4 In china, likely where it originated
<img width="839" alt="7C2E537E-D6F4-4EE8-8DBC-33D4AC822E78" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/8351a695-e151-4502-acbc-958b2077b3cd">

**Comment by FedeGueli** [comment]
I tend to think we should designate all these big chinese branches. So please proppse this one.

**Comment by Over-There-Is** [comment]
FL.4.6> C6558T(Orf1aA2098V)> A264G, probably starts in Guangdong.
But there is another problem. Although most of sequences without A264G are collected out of China, and most of sequences with A264G are collected in China, but A264G is truncated frequently. And 264 is on non-coding region.

**Comment by krosa1910** [comment]
> Correction: i got fooled by the usher tree that doesnt show yet FL.4.6 this is the main branch of FL.4.6 very recently deisgnated it is not worth specifying further it as today . we have to wait if it grows further acquiring mutations.

Anyway, I propose those lineages just that when a further investigation is conducted, there is a starting point that ensures some early actions of the variant is tracked. For the same reason I propose this, XBB.2.3.2* branch and some other branches that got "major" appearance within designated variants.

**Comment by FedeGueli** [comment]
Yah @krosa1910 i like the fact of descibing branches of new fast lineages , and we should do that. i dont like too much when that happens and the main branch is 70-80-90% of sequences of the parental lineage. Beside the XBB.1.19.1 where it was clearly justified by a spike mutation adding fitness to the lineage for the mayority of cases when there is a single main branch and the others dying off i would wait to see if something interesting pops up  before proposing as a distinct lineage from the parental one.

**Comment by krosa1910** [comment]
> Yah @krosa1910 i like the fact of descibing branches of new fast lineages , and we should do that. i dont like too much when that happens and the main branch is 70-80-90% of sequences of the parental lineage. Beside the XBB.1.19.1 where it was clearly justified by a spike mutation adding fitness to the lineage for the mayority of cases when there is a single main branch and the others dying off i would wait to see if something interesting pops up before proposing as a distinct lineage from the parental one.

Fair point, unless there is X.2 there is no need for X.1

**Comment by FedeGueli** [comment]
THis is def circulating in Guangdong please propose it.

**Comment by krosa1910** [comment]
Well, this seems to be more successful than I originally thought. But on global scale, FL.4* seems to be  retreating compared to 23D basis during the recent few weeks. FL.4.6* or this lineage seems to perform a little better, still not sure if it could compete with the EG.5.1* storm.
<img width="719" alt="38F5B791-94D1-4C7E-9978-F855484CD078" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/b27f98da-9042-4908-99db-228f5e670214">

**Comment by krosa1910** [comment]
I doubt the whole FL.4.6* lineage would be able to sustain its presence, and it seemed that this particular branch is not significantly faster than its parent, so I would temporarily shut it down to watch for new info.

**Comment by krosa1910** [comment]
<img width="1185" alt="Screenshot 2023-10-13 at 10 44 36 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/f639f060-646f-4289-a78e-8c72ce8d71ed">
Surprisingly the thing is still surviving at low level in Europe. However, I don't want to reopen it as its decline is not reversible.
