### ISSUE TITLE
XBB.1.5.39 with S:Q52H, S:T478R, S:D1168H 19 seq.

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#325]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1a2d5bfd-7190-45e9-9c3e-51999a90ac49)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b91311f7-6cd7-4cdd-9bd6-887df308e8de)
tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_138da_49ddb0.json?c=gt-nuc_18366&label=id:node_6772035
gisaid query: A18366G, G25064C, T11316C
first seq: 2023-05-02
most recent: 2023-06-17
OR150520.1 EPI_ISL_17950631 EPI_ISL_17950377 EPI_ISL_17838474 EPI_ISL_17722787 EPI_ISL_17722784 OR195469.1

**Comment by BorisUitham** [comment]
Proposal #266 covers this
