### ISSUE TITLE
GG.1 (478r, 666v) 6 nuc (5 aa) saltation with s:q755h, n:n4s (also resulting in ORF9b:M1V), orf1a:d2980h, orf1a:a3357v (55 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#326]
Posting here because its interesting. Seems mostly a sequence from sweden, preceding an outbreak in italy (mostly veneto and Friuli-Venezia Giulia). Dont expect this to spread much but good to check up on. N Mutation is also interesting. Not much ever happens at s:755 but h is most common

Query; C10335t, c14724t, a23827c

![Screenshot_20230705_025950_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/9534a552-1b16-426a-80d9-33c6eca6ad90)
![Screenshot_20230705_030029_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/61846b0a-ebd4-413e-bb98-1a0064cbfd77)

**Comment by BorisUitham** [comment]
N:N4S also results in ORF9b:M1V

**Comment by FedeGueli** [comment]
That orf9b mut removes the orf9b start codon that would likely start at Orf9b:M8.

@ryhisner i think showed the Trs there is quite good.right?

**Comment by FedeGueli** [comment]
Closing this one

**Comment by FedeGueli** [comment]
Reopening it although i dont think it is able to compete:https://cov-spectrum.org/explore/Europe/AllSamples/Past2M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C10335t%2Cc14724t%2Ca23827c&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
dead
