### ISSUE TITLE
XBB.2.3+S:210del,N:A267S(151 seqs, 17 countries) and its  further sublineage Orf7a:Q90*,Orf9b:T72I with ~15% prevalence in Bangladesh  (39 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#328]
XBB.2.3+T18882C,T27992A,G29072T(N:A267S), del22190_22192(S:210del)+C27661T(Orf7a:Q90*) ,C28498T(Orf9b:T72I)

GISAID query: C27661T,C28498T,G29072T

GISAID query for S:210del, N:A267S: del22190_22192, T27992A

No. of seqs: 23(Bangladesh 9 China 2 USA 5(1 from UAE), Thailand 1 Israel 1 Malaysia 1 Australia 1 UK 3)

First: EPI_ISL_17208395, Israel, 2023-2-20
Latest: EPI_ISL_17850929 ,China, 2023-6-18

Note that it represents 9/57 of Bangladesh seqs from 2023-4-15. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_38168_5267d0.json?c=gt-ORF7a_90&label=id:node_7039306)
![屏幕截图 2023-07-05 162855](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/80dc748d-ff10-4799-a9f2-15083c37837c)

**Comment by aviczhl2** [comment]
+1 South Korea

**Comment by aviczhl2** [comment]
2/20 in today's Bangladesh batch

**Comment by FedeGueli** [comment]
Waiting for the next upload from B.

**Comment by aviczhl2** [comment]
Edited the GISAID query to cover some T18882Y seqs from Singapore. 34 seqs now.

**Comment by FedeGueli** [comment]
> @FedeGueli I just realized that this lineage also has S:210del and is the XBB.2.3-side donor of #535.
Wow! great! i have thought of this one but didnt check then!
cc @ryhisner !!! @aviczhl2 found and proposed already the donor!

**Comment by aviczhl2** [comment]
I check the tree and found that the S:210del comes alongside with N:267S. 

Uploaded are seqs with S:210del. 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/485a8bee-72b4-41bf-bb18-4fd4d7c6b9fd)

I'd like to boarden the proposal to S:210del, N:267S

Query: del22190_22192, G27992A

**Comment by FedeGueli** [comment]
great work @aviczhl2 thx.

**Comment by FedeGueli** [comment]
i cant find any seqs with that query @aviczhl2

**Comment by aviczhl2** [comment]
> i cant find any seqs with that query @aviczhl2 i ll use this one: N_A267S,Spike_I210del

Sorry shall be T27992A,  del22190_22192

N_A267S,Spike_I210del includes a few delta seqs.

**Comment by FedeGueli** [comment]
> i cant find any seqs with that query @aviczhl2 i ll use this one: N_A267S,Spike_I210del

thx i ve added also P521S!

**Comment by FedeGueli** [comment]
it seems to have slowed down a lot. wondering why

**Comment by FedeGueli** [comment]
Closing for now better staying focusing on things with advantage. But still this was interesting.

**Comment by FedeGueli** [comment]
Now this is XBB.2.3.20 via https://github.com/cov-lineages/pango-designation/commit/76e269908b343a9bce0d9545f6a7d090884302ef
