### ISSUE TITLE
Multiple lineages with S:L452Q

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#329]
```[tasklist]
### Tracking multiple lineages with S:L452Q
- [ ] Branch 1: [XBB.1.5's T17124C > T23018C] > C7086T(ORF1a:T2274I) > A3249G(ORF1a:E995G), G3446T(ORF1a:A1061S) > A11206G > T8158C, T22917A(S:L452Q), A23535G(S:N658S) [Query: A11206G,T22917A, C7086T, 14 seqs, 07/27]
- [x] Branch 2: Designated as **XBB.1.16.14** _XBB.1.16 > A11782G > T22917A(S:L452Q)_
- [ ] Branch 3: [XBB.1.5's T17124C > T23018C] > G4712A(ORF1a:V1483I) > C15540T, T22917A(S:L452Q) [Query: C15540T, T22917A, G4712A, 17 seqs, 07/27]
- [ ] Branch 4: XBB.1.5.52 > C1267A > C3140T(ORF1a:P959S), A3234C(ORF1a:Q990P), C4782T(ORF1a:S1506L) > C15360T > C1263T(ORF1a:T333M) > T11084C(ORF1a:Y3607H) > T22917A(S:L452Q) [Query: T22917A, T11084C, C1263T, 10 seqs, 06/21]
- [x] Branch 5: Designated as **FP.2.1.1** _FP.2.1 (XBB.1.11.1.2.1) > T15357C > T22917A(L452Q)_
```

Branch 1:

**Defining Mutations:** [XBB.1.5's T17124C > T23018C] > C7086T(ORF1a:T2274I) > A3249G(ORF1a:E995G), G3446T(ORF1a:A1061S) > A11206G > T8158C, T22917A(S:L452Q), A23535G(S:N658S)
**Query:** A11206G,T22917A, C7086T
**Earliest seq:** 2023-04-20 (EPI_ISL_17608124, Spain)
**Latest seq:** 2023-06-22 (EPI_ISL_17950823, Sweden)
**Sampled Countries:** Spain (5), Germany (1), Sweden (1)

<details><summary>Genomes: </summary>
EPI_ISL_17608124, EPI_ISL_17679622, EPI_ISL_17776493, EPI_ISL_17788576, EPI_ISL_17788595, EPI_ISL_17838532, EPI_ISL_17950823
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3caf7_528e80.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a6414b5f-7bee-4103-8f42-f08eae1e0acc)

---

Branch 2 

<details><summary>DESIGNATED AS XBB.1.16.14</summary>

via cov-lineages/pango-designation@5648ff2

**Defining Mutations:** XBB.1.16 > A11782G > T22917A(S:L452Q) >
**Query:** T22917A, A11782G, A22101T
**Earliest seq:** 2023-04-25 (EPI_ISL_17727276, Michigan, USA)
**Latest seq:** 2023-06-21 (EPI_ISL_17964422, England, UK)
**Sampled Countries:** France (6), USA (5, Michigan/2, Ohio/2, New York/1), Canada (5, Québec), UK (4, England/3, Scotland/1), India (1, Odisha), Netherlands (1), Spain (1)

<details><summary>Genomes: </summary>

EPI_ISL_17653273, EPI_ISL_17726763, EPI_ISL_17726926,
EPI_ISL_17727006, EPI_ISL_17727276, EPI_ISL_17744350,
EPI_ISL_17769629-17769633, EPI_ISL_17781582, EPI_ISL_17808965,
EPI_ISL_17856330, EPI_ISL_17872566, EPI_ISL_17885000,
EPI_ISL_17950881, EPI_ISL_17953465, EPI_ISL_17956123,
EPI_ISL_17957941, EPI_ISL_17959243, EPI_ISL_17964407,
EPI_ISL_17964422
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12e96_6ee270.json?f_userOrOld=uploaded%20sample

![XBB 1 16+S_L452Q_Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6e58fce3-6f65-4e72-b1ee-6a6a4dd3fef8)

</details>

---

Branch 3

**Defining Mutations:** [XBB.1.5's T17124C > T23018C] > G4712A(ORF1a:V1483I) > C15540T, T22917A(S:L452Q)
**Query:** C15540T, T22917A, G4712A
**Earliest seq:** 2023-03-18 (EPI_ISL_17596920, Canary Islands, Spain)
**Latest seq:** 2023-06-06 (EPI_ISL_17949210, Spain)
**Sampled Countries:** Spain (11 Mainland/10, Canary Islands/1) France (3), Austria (2), Denmark (1)

<details><summary>Genomes: </summary>

EPI_ISL_17446259, EPI_ISL_17482703, EPI_ISL_17524658,
EPI_ISL_17596920, EPI_ISL_17614594, EPI_ISL_17650839,
EPI_ISL_17673685, EPI_ISL_17679619, EPI_ISL_17679652,
EPI_ISL_17679665, EPI_ISL_17700036, EPI_ISL_17731372,
EPI_ISL_17731437, EPI_ISL_17859706, EPI_ISL_17949132,
EPI_ISL_17949210, EPI_ISL_17949340

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15fb6_6f00f0.json?f_userOrOld=uploaded%20sample

![Branch 3](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ac1837b8-2e8c-4db3-a685-75ddb9e9fb0b)

---

Branch 4

**Defining Mutations:** XBB.1.5.52 > C1267A > C3140T(ORF1a:P959S), A3234C(ORF1a:Q990P), C4782T(ORF1a:S1506L) > C15360T > C1263T(ORF1a:T333M) > T11084C(ORF1a:Y3607H) > T22917A(S:L452Q) 
**Query:** T22917A, T11084C, C1263T [10]
**Earliest seq:** 2023-05-02 (EPI_ISL_17680075, England)
**Latest seq:** 2023-05-30 (EPI_ISL_17820741, England)
**Sampled Countries:** England (10)

<details><summary>Genomes: </summary>

EPI_ISL_17680075, EPI_ISL_17693016, EPI_ISL_17731193,
EPI_ISL_17731195, EPI_ISL_17731200, EPI_ISL_17731204,
EPI_ISL_17742249, EPI_ISL_17787022, EPI_ISL_17820741,
EPI_ISL_17820748

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_199f5_6f15c0.json?f_userOrOld=uploaded%20sample&label=id:node_6969757&showBranchLabels=all

![XBB 1 5 52+S_L452Q_Details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/018cd178-1c1b-42d8-9fbf-c73a927f1c5c)

---

Branch 5:

<details><summary>DESIGNATED AS FP.2.1.1</summary>

via cov-lineages/pango-designation@7c88225

**Defining Mutations:** FP.2.1 (XBB.1.11.1.2.1) > T15357C > T22917A(L452Q)
**Query:** T15357C, T22917A, G25839T
**Earliest seq:** 2023-05-31 (EPI_ISL_17831580, Puerto Rico, United States)
**Latest seq:** 2023-06-27 (EPI_ISL_17962925, Austria)
**Sampled Countries:** US (3, Ohio, Texas, Puerto Rico), Austria (2)

<details><summary>Genomes: </summary>
EPI_ISL_17831580, EPI_ISL_17950927, EPI_ISL_17956024, EPI_ISL_17962918, EPI_ISL_17962925
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e71d_6f43e0.json?f_userOrOld=uploaded%20sample
![Branch 5](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/44bc3637-a8dc-4901-8e33-9f4bbaff0ddc)

</details>

---

**Trivia:**
- S:N658S is a parent branch of many BA.4* like BA.4.6, BA.4.7 etc.
- S:L452Q is the definition of BA.2.12.1.

**Comment by FedeGueli** [comment]
452Q also defining of BH.1 (BA.2.38.3.1)

**Comment by FedeGueli** [comment]
S:L452Q seems estimated as especially beneficial on XBB.1.5 backbone by [T. Starr](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/)

**Comment by FedeGueli** [comment]
i think it is worth proposing branch 5

**Comment by FedeGueli** [comment]
Ok i think we can close this. Please keep checked branch 1.
