### ISSUE TITLE
Small XBB.1.9.2 with S:T478R circulating in Indonesia (40 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#33]
Another XBB.1.9.2 + S:T478R emerged in Indonesia.

Defining XBB.1.9.2 >>Orf8:A51V (C28045T) >> S:T478R (A22995G) but orf8 mutation is reverted in the main branch.

Tree:
![Schermata 2023-05-08 alle 11 58 36](https://user-images.githubusercontent.com/87669813/236795223-16c7867c-f45f-47b0-bcc7-1dc96133ee6e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_321f5_88f790.json?c=gt-S_478&label=id:node_5887580

this Gisaid query is not exhaustive but permits to show the right **USHER TREE:**  C15525T, C15540T,T28297C

**Comment by aviczhl2** [comment]
Seems to be two independent lineages? One with orf8:V51A, the other with orf3a:Y189C?

**Comment by FedeGueli** [comment]
15 as today:
![Schermata 2023-05-17 alle 22 57 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8e4abd7a-c948-42b8-8502-f5547b4bc91b)

**Comment by FedeGueli** [comment]
33 sequences as today are shown in Usher:
![Schermata 2023-05-23 alle 23 27 06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c4f77ebe-d69e-479c-bda1-b62f6f279c41)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f3_d29fe0.json?c=gt-S_486

**Comment by FedeGueli** [comment]
38 as today and this is the updated tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41808_67d470.json?c=userOrOld&label=id:node_6697387
![Schermata 2023-05-31 alle 00 51 51](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f250340e-e7fe-4b58-9cc4-f048dbf08875)

**Comment by FedeGueli** [comment]
I will drop soon this proposal to an end.

**Comment by FedeGueli** [comment]
40 with this new tree
![Schermata 2023-06-04 alle 11 04 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/10f2adeb-76c9-4458-b766-ed4a5fe88274)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24fc3_c53450.json?label=id:node_6699569

**Comment by FedeGueli** [comment]
Seems slow closed

**Comment by AngieHinrichs** [comment]
Wow, 28045 is very flaky on that branch.  Might just be EG.2 with noise as @NkRMnZr said.  I will try pruning some sequences and letting UShER add them back.

**Comment by AngieHinrichs** [comment]
These have been moved to EG.2 in the 2023-08-17 tree (available on dev.usher.bio now, on usher.bio in a bit over 4 hours).

**Comment by FedeGueli** [comment]
Thx Angie
