### ISSUE TITLE
Nextstrain not updating new designations

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#330]
Previously I use https://nextstrain.org/nextclade/sars-cov-2  to check for exact defining mutations for new designations. 

However it stopped updating after GK.1, and seems to be missing everything after that.  @corneliusroemer 

Where can we check for exact full defining mutations of newly-designated lineages now?

**Comment by FedeGueli** [comment]
Wait

**Comment by FedeGueli** [comment]
Here: https://nextstrain.org/staging/nextclade/sars-cov-2/21L

**Comment by aviczhl2** [comment]
> Here: https://nextstrain.org/staging/nextclade/sars-cov-2/21L

Oh, 21L and the main page are separate pages not updated together. Thanks very much!

Still, shall update also on the main page.
