### ISSUE TITLE
Chinese XBB.1.9.1* with orf1a: V1019F, I2873M and a silent S mutation S:A475A (130 seqs)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#334]
Mutations on top of XBB.1.9.1: A8884G, A10564T,G3320T, C22987A
Gisaid Inquiry: Spike_F486P+A10564T+C22987A
Gisaid query nucs : A8884G, A10564T ,G3320T, C22987A  (edited)
Sequences: 130 
EPI_ISL_17563563, EPI_ISL_17625322, EPI_ISL_17637506,
EPI_ISL_17652379, EPI_ISL_17664610, EPI_ISL_17672011,
EPI_ISL_17684492, EPI_ISL_17689362, EPI_ISL_17689437,
EPI_ISL_17703965, EPI_ISL_17704032, EPI_ISL_17704050,
EPI_ISL_17714262, EPI_ISL_17718394, EPI_ISL_17725131,
EPI_ISL_17725294, EPI_ISL_17729854, EPI_ISL_17729883,
EPI_ISL_17736010, EPI_ISL_17743017, EPI_ISL_17744790,
EPI_ISL_17775204, EPI_ISL_17775496, EPI_ISL_17775540,
EPI_ISL_17775590, EPI_ISL_17775602, EPI_ISL_17775608,
EPI_ISL_17775633, EPI_ISL_17778737, EPI_ISL_17778740,
EPI_ISL_17783566, EPI_ISL_17783578, EPI_ISL_17785274,
EPI_ISL_17794000, EPI_ISL_17794040, EPI_ISL_17794202,
EPI_ISL_17794258-17794260, EPI_ISL_17794262-17794263, EPI_ISL_17794268-17794269,
EPI_ISL_17794272, EPI_ISL_17794274-17794281, EPI_ISL_17794283-17794285,
EPI_ISL_17794287, EPI_ISL_17794290, EPI_ISL_17794293,
EPI_ISL_17794297-17794300, EPI_ISL_17794308-17794309, EPI_ISL_17794311,
EPI_ISL_17794314, EPI_ISL_17794322, EPI_ISL_17794324,
EPI_ISL_17794326, EPI_ISL_17794328-17794330, EPI_ISL_17794487-17794489,
EPI_ISL_17794542, EPI_ISL_17794550, EPI_ISL_17794555,
EPI_ISL_17794561, EPI_ISL_17794636, EPI_ISL_17794645,
EPI_ISL_17794672, EPI_ISL_17794687, EPI_ISL_17794690,
EPI_ISL_17794696, EPI_ISL_17794710, EPI_ISL_17794713,
EPI_ISL_17794744-17794745, EPI_ISL_17794813, EPI_ISL_17794933,
EPI_ISL_17794937, EPI_ISL_17794939, EPI_ISL_17794954,
EPI_ISL_17794992, EPI_ISL_17795002, EPI_ISL_17795009,
EPI_ISL_17795410, EPI_ISL_17795644, EPI_ISL_17801782,
EPI_ISL_17801933, EPI_ISL_17801948, EPI_ISL_17801952,
EPI_ISL_17801958, EPI_ISL_17801980, EPI_ISL_17801989,
EPI_ISL_17808114, EPI_ISL_17808151, EPI_ISL_17808153-17808155,
EPI_ISL_17808160, EPI_ISL_17808286, EPI_ISL_17810989,
EPI_ISL_17811080, EPI_ISL_17811108, EPI_ISL_17811140,
EPI_ISL_17811181, EPI_ISL_17811194, EPI_ISL_17811337,
EPI_ISL_17817034, EPI_ISL_17819877, EPI_ISL_17834307,
EPI_ISL_17835501, EPI_ISL_17836263, EPI_ISL_17836312,
EPI_ISL_17836366, EPI_ISL_17850465, EPI_ISL_17850734,
EPI_ISL_17952695, EPI_ISL_17954897, EPI_ISL_17954956,
EPI_ISL_17956942, EPI_ISL_17957090

Earliest Sequence:  EPI_ISL_17563563 Xinjiang 03-23,2023
Latest Sequence: EPI_ISL_17954897 Isarel 06-18, 2023
Distribution: mostly inside China , 1HK, 1 USA, 2 Isarel, 1 South Korea, 1 Costa Rica
Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_18027_4a00a0.json?f_userOrOld=uploaded%20sample
China is currently having a great wave which XBB.1.9.1* are a major constituent. So I just spotted a lot of XBB.1.9.1* subvariant that could be monitored.
Note: 475A is a relatively minor site of escape, yet appearing as a silent mutation I don't think it would be very significant difference here. And I don't know if the other Orf1ab mutations are beneficial.

**Comment by Over-There-Is** [comment]
#187
