### ISSUE TITLE
GD.1 (S:Y453F) gained S:F456L  and multiple AA mutations 2 sequences (US, China)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#337]
Defining mutations: GD.1 (XBB.1.9.3.1) >T18099C > T18402C, M:A40S (G26640T), S:F456L (T22928C), Orf8:P85S (C28146T) N:T417I (C29523T)
![Schermata 2023-07-06 alle 00 07 42](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5b202163-6668-45e0-b6e1-3123d7fa17f7)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1de9e_5e0b40.json?c=gt-S_456&label=id:node_6639951

Gisaid query:
T18402C, G26640T, C28146T

Samples: 2 (US, CHina)
EPI_ISL_17676308, EPI_ISL_17836786

**Comment by HynnSpylor** [comment]
It has been spotted in #262

**Comment by FedeGueli** [comment]
> It has been spotted in #262

thx i didnt recall it ;)
