### ISSUE TITLE
Sublineage of FL.4 + S:254P proposed in #216 with S:Y351H (19 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#339]
This is  asublineage of FL.4 proposed in #216 

S:Y351H is a mutation recently spotted and proposed first by @Sinickle in a lineage in combo with S:K356T.
Its significance is not clear being predicted to be clearly deleterious.
![Schermata 2023-07-06 alle 01 06 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/059017e8-ec83-4e28-835a-c0899643601e)
But today Canada uploaded am entire batch of very recent samples very likely from a cluster or from targeting sequencing of some venue/pop but better to check it for a while.

Defining mutations FL.4>> #216 >> C17436T > A11875G > S:Y351H (T22613C) 

Gisaid query: C17436T , A11875G ,T22613C

Samples : 19
USA/NJ-CDC-QDX80889103/2023\|OR134152.1\|2023-05-24
Canada/ON-PHL-23-25361/2023\|EPI_ISL_17789449\|2023-05-31
Canada/ON-PHL-23-25461/2023\|EPI_ISL_17789521\|2023-06-02
hCoV-19/Canada/ON-PHL-23-26495/2023\|EPI_ISL_17960738\|2023-06-27
hCoV-19/Canada/ON-PHL-23-26493/2023\|EPI_ISL_17960737\|2023-06-29
hCoV-19/Canada/ON-PHL-23-26492/2023\|EPI_ISL_17960736\|2023-06-28
hCoV-19/Canada/ON-PHL-23-26491/2023\|EPI_ISL_17960735\|2023-06-28
hCoV-19/Canada/ON-PHL-23-26449/2023\|EPI_ISL_17960729\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26370/2023\|EPI_ISL_17960722\|2023-06-23
hCoV-19/Canada/ON-PHL-23-26441/2023\|EPI_ISL_17960668\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26439/2023\|EPI_ISL_17960667\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26438/2023\|EPI_ISL_17960666\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26437/2023\|EPI_ISL_17960665\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26434/2023\|EPI_ISL_17960662\|2023-06-27
hCoV-19/Canada/ON-PHL-23-26433/2023\|EPI_ISL_17960661\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26409/2023\|EPI_ISL_17960642\|2023-06-25
hCoV-19/Canada/ON-PHL-23-26371/2023\|EPI_ISL_17960612\|2023-06-24
hCoV-19/Canada/ON-PHL-23-26362/2023\|EPI_ISL_17960604\|2023-06-22
hCoV-19/Canada/ON-PHL-23-26361/2023\|EPI_ISL_17960603\|2023-06-23

Tree:
![Schermata 2023-07-06 alle 01 04 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/964672ad-ddd2-4ae2-bfc1-b25b3b6b431f)
![Schermata 2023-07-06 alle 01 03 36](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/77b51cec-90db-43c5-8914-9582bed918ac)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a822_5f4ac0.json?c=gt-S_351&label=id:node_6706977

**Comment by HynnSpylor** [comment]
Ah I noticed it! The main samples are likely nosocomial infection (as my proposal of BQ.1.1.40 saltation) so I did not propose.
However, US also updated one seq, which shows the further international transmission

**Comment by FedeGueli** [comment]
Still 19 closing it for now
