### ISSUE TITLE
Potential XBB.1.9* / XBL.1 recombinant with S:L242I, S:V635I (68 seqs 18 of them from ICELAND)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#34]
I've come across a strange cluster. Usher places it as XBB.1.9, Nextclade as XBB.1.9.1 but it doesn't quite fit:

Compared to XBB.1.9.1 it has:
reversions: T11956C (XBB.1.9.1 defining), C28297T (defining mutation of XBB.1.9/XBB.1.16/... branch, distinguishing from XBB.1.5)
extra mut: C28312T (known from BQ.1 and XBL)

But it _has_ XBB.1.9 muts G5720A, C12789T

Most seqs from England, but somewhat recent.

Could this be a XBB.1.9/XBL recombinant?

Muts wrt BA.2
<img width="778" alt="image" src="https://user-images.githubusercontent.com/25161793/236802537-491cc970-01db-44c1-8b88-9e56626efd84.png">

Query: Spike_L242I, spike_V635I or  C28312T,C14318T,C22286A (EDITED)

**Comment by FedeGueli** [comment]
Also XBB.1.5.47 that is the likely donor of XBL

**Comment by corneliusroemer** [comment]
I'm not sure about the XBB.1.5.57 - it's likely the donor of XBL, but it could be either a recombinant itself or an ancestor of this lineage here (if there wasn't any recombination). It's tricky.

**Comment by FedeGueli** [comment]
S:V635I was in XBL.1 i think.it is plausible it is it as donor from RBD ahead?

**Comment by aviczhl2** [comment]
Two XBB.1.9(not 1.9.1 or 1.9.2), EPI_ISL_16744367 and EPI_ISL_17008097, have S:242I.

**Comment by FedeGueli** [comment]
i found now 50 with Spike_L242I, spike_V635I

**Comment by FedeGueli** [comment]
Being 50 the threshold to propose a recombinant i suggest @corneliusroemer to transfer this proposal on the main page.

The tree looks like this way:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e9c2_66b290.json?c=userOrOld&label=id:node_6717881
![Schermata 2023-05-31 alle 00 00 32](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ab29b9a4-e7fe-4b84-973f-e6f88794cf18)

Def needed a proposal.
One only question is the bottom branch a different recombination? (likely not to me )
![Schermata 2023-05-31 alle 00 02 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/6dc57d0c-6b76-43a5-b46d-a9454db1f7d8)

**Comment by FedeGueli** [comment]
This represents 18 out f 87 viruses uploaded from Iceland in MAY. I would reccomend to propose it @corneliusroemer

**Comment by FedeGueli** [comment]
THE TREE SEEMS QUITE LARGE NOW (IN RED ICELANDIC SUPERSPREADING EVENT):
![Schermata 2023-06-17 alle 00 45 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1957c6e2-ce70-4896-a35a-13065fd327dc)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_119a_ce08e0.json?c=userOrOld&label=id:node_6649330

**Comment by FedeGueli** [comment]
it seems dead
