### ISSUE TITLE
GQ.1 (CH.1.1.3.1) sublineage with S:G213E (19 seqs in New Zealand)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#343]
Defining mutations: GQ.1>T6634C, C14183T(ORF1b:T239I), C27532A (ORF7a:H47N)>G22200A (S:G213E), C28831A
GISAID query: G18025T, C24358T, C28831A
Earliest seq: 2023-04-21 (New Zealand, EPI_ISL_17739724)
Most recent seq: 2023-06-24 (New Zealand, EPI_ISL_17961699)
Countries detected: New Zealand (19)

Usher Tree:
![QQ截图20230706181542](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/60c1aedc-acae-425d-b641-9078eb7630fd)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a921_68f230.json?c=gt-S_213

It is first spotted in https://github.com/cov-lineages/pango-designation/issues/1872 
S:213 is G in BA.2.75* lineages (including CH*) while E in XBB* lineages. Based on S:S486P, the branch gets one more XBB* mutation.

Genomes:
EPI_ISL_17739197, EPI_ISL_17739382, EPI_ISL_17739724, EPI_ISL_17740162, EPI_ISL_17740383, EPI_ISL_17961670, EPI_ISL_17961699, EPI_ISL_17961717, EPI_ISL_17961783, EPI_ISL_17961788, EPI_ISL_17961831, EPI_ISL_17961842, EPI_ISL_17961870, EPI_ISL_17961885, EPI_ISL_17962022, EPI_ISL_17962200, EPI_ISL_17962241, EPI_ISL_17962245, EPI_ISL_17962415

**Comment by FedeGueli** [comment]
Local prevalence of GQ.1 is significant around 3-4% good ypu proposed this onw

**Comment by Sinickle** [comment]
Seems to me to be a really important one to watch.
CH.1.1.3 with S:213E has 14 sequences as well -- so this is the second time the lineage acquired the mutation successfully.
