### ISSUE TITLE
XBB.1.16.2 sublineage with S:N450K (17 seqs in 4 countries, mainly in Laos and Japan)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#345]
Defining mutations: XBB.1.16.2> T22912G (S:N450K), C29095T
GISAID query: G25429C, T22912G, C29095T
Earliest seq: 2023-05-13 (Laos, EPI_ISL_17785487)
Most recent seq: 2023-06-27 (Laos, EPI_ISL_17964615)
Countries detected: Laos (6), Japan (1), Singapore (1)

Usher Tree:
![QQ截图20230707015043](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/5f7591e4-73b3-4d81-9fc4-cfc0889d97d4)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27774_6f70e0.json

Another choice for S:N450 (as S:N450D in BA.2.3.20* and S:N450I in FL.4.1).
The fitness calculation shows the fitness :N450D>N450K>N450N (wild type)>N450I (Bloom and Neher, 2023)

Genomes:
EPI_ISL_17720755, EPI_ISL_17785487, EPI_ISL_17790173, EPI_ISL_17883545, EPI_ISL_17964614-17964615, EPI_ISL_17964620,
EPI_ISL_17964625

**Comment by FedeGueli** [comment]
Curious to.know how it goes, i have tracked some songlet in the past that didnt do so much. Thx for spotting.

**Comment by HynnSpylor** [comment]
one more seq from Yunnan Province, China (Notice that Yunnan Province is bordered with Laos)
