### ISSUE TITLE
XBB.1.5.63+Orf1b:H353Y,S:N354S+S:K478R in Mauritius (13 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#347]
XBB.1.5.63+C14524T,A22623G(Orf1b:H353Y, S:N354S)+A22995G(S:K478R),C13665T

GISAID query:C22995G,C13665T,C14524T,A22623G
No. of seqs: 13(Mauritius)
First: EPI_ISL_17620662, 2023-4-7
Latest: EPI_ISL_17963242, 2023-5-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18ccb_796cc0.json?c=gt-S_478&label=id:node_7012748)
It is on a flip-flop branch under XBB.1.5.63 and needs some fix. @AngieHinrichs

![屏幕截图 2023-07-07 124300](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c21b3fa5-174a-43b6-87a7-74089ba38d7a)

**Comment by FedeGueli** [comment]
no new sequence despite Mauritius uploaded further. So i m closing it
