### ISSUE TITLE
BA.2.3 Saltation Singlet with S:F486P, S:L452R and multiple spike mutations popped up in Indonesia 

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#348]
Inquiry: EPI_ISL_17788384
Query: Spike_G261A,Spike_P251T
<img width="1710" alt="Screenshot 2023-07-07 at 2 03 02 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/08be3ea1-03de-4e68-a11c-74df184470b8">
This saltation is very weird to say, I believe it would be the result of some extreme chronic infection.
Some mutations here just happen to be rare. Like S: 251T and S:261A that only appeared several hundred times during the whole pandemic, while only several tens of those are in Asia. Thus it would be very hard to be a recombination or pollution. The number of total mutations also look too normal for frameshift to explain the thing. 
Yet on the other hand, this saltation simply gained some of the most iconic mutations nowadays. S:L368I are one of the hallmark XBB*, S:L452R and S:L212S in recent XBC*, S:245N in BA.2.3.20*, the most successful early BA.2*, finally the prize of S:486P. I believe that "normally chronic infections" would lead to different mutations than these?
@ryanhisner @corneliusroemer I would like help to identify this sequence more closely. Whether it is a weird contamination, a recombination, or a really clever saltation.

**Comment by FedeGueli** [comment]
It has S:375-376 deleted and also a deletion in orf3a:255-257 and orf7a:105V .

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38954_7aeb20.json?c=userOrOld
![Schermata 2023-07-07 alle 10 00 23](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7602b881-873d-44d2-b38a-9c67184fca1b)

![Schermata 2023-07-07 alle 09 59 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a92ea08a-28ab-47ce-8bed-3b53dd771edd)
![Schermata 2023-07-07 alle 09 59 35](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/91188f4d-f2bc-4a41-8949-396a40019664)

**Comment by FedeGueli** [comment]
Why did u close it @krosa1910 ?
