### ISSUE TITLE
XBB.8.2+15-nuc,7-aa containing S:P521T in African French Islands (26 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#349]
XBB.8.2+C6156T,C15925T(orf1b:L820F),A21081G,C25680T,G27467C(Orf7a:R25T)+C934T+C29149T+C8016T(Orf1a:A2584V),C8655T(Orf1a:S2797F),C11866T,G13043T(Orf1a:V2760L),G18816T,C23123A(S:P521T),T23689C,G25534T(Orf3a:V48F)

GISAID query:G18816T,C23123A,T23689C,G25534T
No. of seqs: 22( Italy 1 USA 1 France 20(Reunion 6 Mayotte 14))
First: EPI_ISL_17657887, Mayotte, 2023-3-28
Latest: EPI_ISL_17797039, Italy, 2023-6-6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice35_genome_f394_7742f0.json?c=gt-ORF3a_48&label=id:node_6589923)

![屏幕截图 2023-07-07 161904](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/96bb6244-4d7a-48e8-a569-1b04caacaf6a)

Just realized that Reunion and Mayotte are oversea islands of France(but both in Africa). 

The isolation effect may lead to very long branches.

**Comment by FedeGueli** [comment]
Now the tree is completely mutated. It seems that S:P521T is the main branch of XBB.8.2  splitting then in two sub branches the one proposed here ( and not sequenced recently) and the other caught by NYC airport surveillance with additional S:D178H and S:K478R

![Schermata 2023-07-31 alle 01 18 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8d8a0381-6e84-4d67-bccf-4ae30609bfcb)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e15d_6eea40.json?label=id:node_7129749

**Comment by aviczhl2** [comment]
> Now the tree is completely mutated. It seems that S:P521T is the main branch of XBB.8.2 splitting then in two sub branches the one proposed here ( and not sequenced recently) and the other caught by NYC airport surveillance with additional S:D178H and S:K478R
> 
> ![Schermata 2023-07-31 alle 01 18 39](https://user-images.githubusercontent.com/87669813/257080544-8d8a0381-6e84-4d67-bccf-4ae30609bfcb.png) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e15d_6eea40.json?label=id:node_7129749

Do you think they are independent branches with convergent S:P521T? Maybe the American branch deserve a separate issue?

**Comment by FedeGueli** [comment]
> > Now the tree is completely mutated. It seems that S:P521T is the main branch of XBB.8.2 splitting then in two sub branches the one proposed here ( and not sequenced recently) and the other caught by NYC airport surveillance with additional S:D178H and S:K478R
> > ![Schermata 2023-07-31 alle 01 18 39](https://user-images.githubusercontent.com/87669813/257080544-8d8a0381-6e84-4d67-bccf-4ae30609bfcb.png) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e15d_6eea40.json?label=id:node_7129749
> 
> Do you think they are independent branches with convergent S:P521T? Maybe the American branch deserve a separate issue for additional S:478R?

It could be but unlikely to me an independent acquisition in a small lineage, maybe recombination being islands coccircualtion of similar/siblings strains makes more probable them to mix together?? 
Well done for the proposal you managed to do.

**Comment by aviczhl2** [comment]
This one is 37 now, but seqs are still from May/June.
