### ISSUE TITLE
Several potential XBB.1.9.1/XBB.1.9.2 recombinants

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#35]
Just putting this here, also to show one of the ways I try to track recombinants.
Every now and then, I rerun this kind of queries to see if anything grows. And I will investigate further if it does.

I use this query: C11956T, C12789T, A16878T

The first 2 mutations are from XBB.1.9.1 and A16878T is from XBB.1.9.2 (plus sublineages).

13 samples. 4 singlets, 3 clusters of 2 (of which 1 from 2 countries), 1 cluster of 3.

![image](https://user-images.githubusercontent.com/94831035/236863779-c0fba369-0913-4995-9fcb-6e529db8decd.png)

![image](https://user-images.githubusercontent.com/94831035/236898523-8e38144a-8ab2-4f16-930a-c63d515cd371.png)

**Comment by JosetteSchoenma** [comment]
I made a single query for one, because it is now 4 samples from 4 different countries!

C11956T, C12789T, A16878T, T14264A

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/fb99d652-1127-4f36-aca5-e31ad424420a)

**Comment by JosetteSchoenma** [comment]
5 samples, 5 countries now, for the Asian/US cluster. The one from Singapore had travel history to Vietnam, but 2 others were local cases. Singapore, Vietnam, Japan, South Korea and USA.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/c95c89dd-961b-45a3-ab4e-8f77ba1f3f19)

**Comment by JosetteSchoenma** [comment]
9 samples, 8 countries, 3 continents now. 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/2de43378-3dd6-4877-a4e8-5ba14575f752)

**Comment by FedeGueli** [comment]
@JosetteSchoenma i think this one shoulfd be proposed once it reached 20seqd

**Comment by FedeGueli** [comment]
@JosetteSchoenma it reached 20 seqs ( i mean the one with C11956T, C12789T, A16878T, T14264A) but overall there are now 48 seqs please review this one and propose everything separately over 15 seqs (if any!)

**Comment by FedeGueli** [comment]
@JosetteSchoenma maybe i think that a multiple proposal ( messy itself) with recombinants ( messy itself) become messy squared. Likely best to propose one for issue!! i sincerely try to monitor these ones but got everytime confused!


This one found by the query: C11956T, C12789T, A16878T, T14264A
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d749_82a590.json?f_userOrOld=uploaded%20sample&label=id:node_6615392
![Schermata 2023-06-13 alle 10 36 27](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/42e3da65-2d19-4255-a90e-7d3b431a90f4)
could be worth a proposal on its own.

**Comment by JosetteSchoenma** [comment]
@FedeGueli I agree with it being confusing.
But with this one not growing fast and at 20 samples, while others if over a 100 are not being designated, I find it not really worth the time proposing it. Sorry.

**Comment by FedeGueli** [comment]
Closing this for now
