### ISSUE TITLE
XBB.1.5 lin with s:A623V and orf1a:v28i  in guatamala (119 seqs)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#351]
43 in guatamala (aroundn15-20% dominant?) 3 in usa
Query: C23430t, g347a

Collected between 4-17 and 6-15

623v is seen in some chronics. Like the dutch ba.1.17 one.
Orf1a:v28i seems to happen frequently all throughout, probably some mildly fitness increasing effect

![Screenshot_20230707_123200_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/f9d5061a-7b26-4a63-b90e-e4df0792f4ee)

![Screenshot_20230707_123539_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/465555c7-3dde-4c36-8595-0c549729ea21)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ccee_7e75e0.json?c=gt-S_623&showBranchLabels=all

**Comment by FedeGueli** [comment]
Convergent with #46 there in xbb.1.9* backbone

**Comment by BorisUitham** [comment]
46 to 64 seqs! There was a guatamala upload on the thirteenth, plus a (local?) Case in texas

**Comment by BorisUitham** [comment]
There is one sequence with orf9b:i5t, and one with s:478r.

**Comment by BorisUitham** [comment]
![Screenshot_20230717_060723_Chrome~2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/c4db3795-e70f-42f8-a184-f0f25aaff865)

Look at the extraordinary divergence that has happened over the last upload! It must be very widespread in guatamala. There are lots of interesting  mutations in there. 625r is interesting because it is close to the 623v

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by BorisUitham** [comment]
Thank you, i will make an issue when i'm back from vacation tomorrow.

**Comment by FedeGueli** [comment]
> Thank you, i will make an issue when i'm back from vacation tomorrow.

Did you propose it ? it is now 119

**Comment by BorisUitham** [comment]
Sorry, I had some chaotic weeks. I am making a proposal now.

**Comment by FedeGueli** [comment]
> Sorry, I had some chaotic weeks. I am making a proposal now.

thank you
