### ISSUE TITLE
EG.5.2 with S:N1176D, S:S704L in austria(24 seqs, 2 recombinant sequences with eu.1.1's orf1ab)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#353]
Seq counts updated: 20-07
Query without recomb 23 seqs: A25094G, C23673T, A16878T

Query recomb 2 seqs: A25094G, C23673T, -A16878T

Query combined 25 seqs: A25094G, C23673T

Query austrian Sublin 11 seqs: G27214A, A25094G, C23673T, A16878T 

This is another branch of eg.5.2 with 704l. Perhaps the 1177d or the other orf mutations has something to to with the increased success of this one

Very interestingly, when creating the query, it kept including 2 very recent also from austria eu.1.1. I think these are recombinants with this tiny lineage! I think it is quite special when there is a recombination with 2 sequences where one parent sequence as of yet only has 18
Recombinants: (collected 6-14 and 6-19)
![Screenshot_20230707_151421_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/60535ea1-8b78-4682-b744-7fe42b0535dc)

However the reason I made this proposal is mainly because of this non recombinant tree so lets watch both closely;
![Screenshot_20230707_150445_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/3debf524-7685-4a67-88cf-a6776cb9c7e4)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_56955_80b4f0.json?f_userOrOld=uploaded%20sample&label=id:node_6668948

Based on comparison with usheres estimated common ancestor:
I believe the breakpoint to be in between nuc 18723 (orf1b) and 22576 (spike, although aa wise the spikes are identical)
![Screenshot_20230707_154023_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/e5a7aa6b-12f8-4513-9381-e70a9a8675bc)
![Screenshot_20230707_152920_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/277e5159-a23b-4a78-821e-95de17226506)

**Comment by BorisUitham** [comment]
![Screenshot_20230707_173121_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/afd3e343-a2cf-496b-8692-45bd1b06f920)

One more thing: the recombination must have occured here, since that nranch is the only of these shares nuc mutations

**Comment by Fearuncle** [comment]
mentioned the non recombinant in https://github.com/sars-cov-2-variants/lineage-proposals/issues/189

**Comment by BorisUitham** [comment]
@Fearuncle yes, that is the other divergent branch i was talking about however this one takes another route

**Comment by BorisUitham** [comment]
Wow! The calculated growth advantage after todays covspectrum update is high, even if i must learn to keep this with a grain of salt.

From top to bottom:
1. Proposal + recombinant with eu.1.1
2. Prop X eu.1.1 recomb only
3. Proposal excluding recombinant 
4. Sublin of proposal + recombinants, idk why theres still a hit for the recombinant here
5. sublin of proposal containing orf6:v5i

![Screenshot_20230708_152245_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/bb723a14-8ace-4a6b-85af-6c8aee15317d)
