### ISSUE TITLE
XBB.1.16 with S:E554K in NZL (38)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#354]
Defining mutations: XBB.1.16>> C29386T> S:E554K (G23222A)

Gisaid query: C29386T,G23222A  + New Zealand
real:C29386T,G23222A, -C23202T,-A4681T,-T733C,-C3874T,-A2304G,-G10400T,-C254T,-A2893C,-C13720T,-T2242C

Tree:
![Schermata 2023-07-07 alle 16 29 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/89d6fdbf-0247-464f-9053-f0b7aa2d5da8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24ea2_7adaf0.json?c=userOrOld&label=id:node_6620227

Samples: 24 (new Zealand)
EPI_ISL_17739009, EPI_ISL_17739020, EPI_ISL_17739263,
EPI_ISL_17739279, EPI_ISL_17739282, EPI_ISL_17739383,
EPI_ISL_17739514, EPI_ISL_17740084, EPI_ISL_17961896,
EPI_ISL_17961945, EPI_ISL_17962050, EPI_ISL_17962073,
EPI_ISL_17962262, EPI_ISL_17962264, EPI_ISL_17962308,
EPI_ISL_17962324-17962326, EPI_ISL_17962411, EPI_ISL_17962559,
EPI_ISL_17962561, EPI_ISL_17962563, EPI_ISL_17962763,
EPI_ISL_17962783

**Comment by HynnSpylor** [comment]
Good catch! I preliminarily noticed it yesterday but not proposed it due to my busy work.

**Comment by FedeGueli** [comment]
Yeah 554K is popping everywhere right now , if you look at the query ,, still imperfect, all the - are excluded lineages with it! So i just managed to finish it today. I wonder if some 455-456 or 456 478 catches it if could boost transmissibility or not

**Comment by FedeGueli** [comment]
Sampled in California from a traveller from India. ping @corneliusroemer

**Comment by HynnSpylor** [comment]
designated as XBB.1.16.17

**Comment by MCB6** [comment]
dominates in Central Russia as of November

**Comment by FedeGueli** [comment]
> dominates in Central Russia as of November

Yes Russia has a couple of FL and a couple of XBB.1.16 that took together were close to 50%. Russian flight isolation with western countries plus vast territory likely made its variant scenario quite unique, even if also india Philippines South Afirca and Brazil showed markedly different trends/Lineages.
