### ISSUE TITLE
Recent GW.1 (S:E554K) with S:F456L and Orf1b:K2557R (14 from  Singapore, China, Japan, Malaysia, Washington)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#355]
I have the feeling this XBB.1.19.1 +456L has been already spotted but i wasnt able to find it so i propose it , in the case please ping me to close it down.

as @aviczhl2 noticed in a comment below also Orf1b:K2557R is convergent with EG.5.1.4 and Fl.1.5.1 two of the fastest lineages.

GW.1 is a very diverse XBB.1.19.1 widespread in China defined by an NSP2 and N mutation.

It seems to have further gained S:F456L :

XBB.1.19.1 >> C20823T >> Orf1b:K2557R (A21137G) > S:F456L (T22928C)

Gisaid query:  C20823T ,A21137G, T22928C 

Samples : 3
EPI_ISL_17815754, EPI_ISL_17850521, EPI_ISL_17957336,
first and last collected in Singapore and the other from Heilongjiang

Tree:
![Schermata 2023-07-07 alle 18 03 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/42b10979-b5b7-44d4-bacf-598658464740)
![Schermata 2023-07-07 alle 18 03 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0e2fc771-215c-4bc1-8599-e4bbee5d4a67)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_33cf0_831320.json?c=gt-S_456&label=id:node_6596491

**Comment by FedeGueli** [comment]
The query now returns 5 .

**Comment by FedeGueli** [comment]
Last one from Guangdong

**Comment by aviczhl2** [comment]
Orf1b:K2557R is also a popular convergent site. 

I have a feeling that the current XBB* convergent mutation is much more convergent that last year's BA* convergent mutation. 

Lots of 2/3-nuc convergent combos are seen.

**Comment by aviczhl2** [comment]
+3 Beijing.

**Comment by FedeGueli** [comment]
ping @corneliusroemer i suggest to designate this one directly

**Comment by FedeGueli** [comment]
after a 40 days hyatus another sample collected in July in Shanghai has been uploaded.

**Comment by FedeGueli** [comment]
+2 Japan and Malaysia (via SIngapore)

**Comment by FedeGueli** [comment]
Designated GW.1.1 via https://github.com/cov-lineages/pango-designation/commit/c520d0c6ddfc5b6a51839625f2426da6b479d6b7

**Comment by Over-There-Is** [comment]
USA/WA-IVY-G43Q77F9/2023|EPI_ISL_18120472|2023-08-03 seems so weird. It has neither E554K nor T21363C, but T17124C. Usher places it under an XBB.1.5> T17124C> T24130C> C18508T, T22928C> C20823T> C27883A> G1820A, C4582T, A21137G, C27542T branch.

**Comment by FedeGueli** [comment]
> USA/WA-IVY-G43Q77F9/2023|EPI_ISL_18120472|2023-08-03 seems so weird. It has neither E554K nor T21363C, but T17124C. Usher places it under an XBB.1.5> T17124C> T24130C> C18508T, T22928C> C20823T> C27883A> G1820A, C4582T, A21137G, C27542T branch.

Is it one of sequence used to designate the lineage?
