### ISSUE TITLE
FL.2.3 sublineage with S:T883I, I1114T(2 seq, China)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#357]
FL.2.3>T16326C >C24210T(S:T883I), T24903C(S:I1114T)
Yunnan/YNCDC-0750/2023|EPI_ISL_17744676|2023-05-14
Yunnan/YNCDC-1589/2023|EPI_ISL_17966470|2023-06-21
https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json?label=id:node_10502749
![2023-07-08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/00da215e-a507-4462-a45b-6f866cde7492)

**Comment by FedeGueli** [comment]
Still 2 closing for now.

**Comment by Over-There-Is** [comment]
this branch has been reported by Laos in Nov 2023: EPI_ISL_18512110|Laos/LOMWRU-1868/2023|2023-09-21

**Comment by FedeGueli** [comment]
> this branch has been reported by Laos in Nov 2023: EPI_ISL_18512110|Laos/LOMWRU-1868/2023|2023-09-21

thx!
