### ISSUE TITLE
XBB.1.16.12 (S:Q52H) with T5619C = Orf1a:T1785I and C14117T= Orf1b:T217M (103 seq at 2023-9-15)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#358]
Mutations on top of XBB.1.16.12: T5619C, C14117T
Inquiry: Spike_L368I,E180V,Q52H +T5619C
Sequence: EPI_ISL_17775025, EPI_ISL_17783018, EPI_ISL_17799024,
EPI_ISL_17799052, EPI_ISL_17799498, EPI_ISL_17821360,
EPI_ISL_17832561, EPI_ISL_17838810, EPI_ISL_17856224,
EPI_ISL_17856323, EPI_ISL_17865633, EPI_ISL_17871121,
EPI_ISL_17927679, EPI_ISL_17928065, EPI_ISL_17952666,
EPI_ISL_17954499, EPI_ISL_17954890, EPI_ISL_17959276,
Earliest:  EPI_ISL_17832561 05-15 Thailand
Latest: EPI_ISL_17838810 06-22 Canada
Spatial Distribution: 1 Australia, (weird one), 9 Canada, 1 Isarel, 2 South Korea , 2 Japan, 1 Thailand, 2 US
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36fcd_87d970.json?f_userOrOld=uploaded%20sample&label=id:node_2912161
I discovered this when checking the special sequence (which I found under searching XBC mutations+XBB*) The whole lineage is then investigated since I think it is somewhat "parent" of the special sequence.
Although the mutations are relatively common C-T transitions so are not so interesting, still I believe it would be quite fast for a lineage to spread to three continents in a month, so I propose this one. 
Special Sequence:  EPI_ISL_17434124 in 6-15, Australia.
<img width="1710" alt="Screenshot 2023-07-07 at 4 32 58 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/e0af5f65-c65b-4bd7-a0be-aa57db75b4c6">
This one seems either a recombination or the lineage I mention (If I can temporarily call it XBB.1.16.12.X) and XBC.1.6 or simply a contamination of 1.16.12.X with XBC.1.6 intruded. I believe it has the backbone of 1.16.12.1 because it acquired exactly the two orf1ab mutations compared to XBB.1.16. The appearance of S: V213E among five XBC.1.6* mutations inserted and S:G252V removed make me question if it is a recombination as XBC.1.6 does not have the S:V213G/E mutation other BA.2 children, including XBB* in some way acquired.
```[tasklist]
### Tasks
```

**Comment by FedeGueli** [comment]
Thx for noticing . This recombinant was already spotted by @ryhisner and its Gisiad query is 
C22188T, T22197C,T5619C, C14117T
 
 
 
 
 
 
 
 
 
 
1

**Comment by krosa1910** [comment]
> Thx for noticing . This recombinant was already spotted by @ryhisner and its Gisaid query is C22188T, T22197C,T5619C, C14117T
> 
> When one mutation only is in the middle of the bit coming from the other lineage if it is a singlet this points to contamination, but lets see if more pos up.

I have also seen that, but I think the greater lineage that could serve as its backbone or parent is also worth mentioning. One thing I don't understand is why S:367I is not caught by Usher (I did not see that until I double check the picture of nextclade)

**Comment by FedeGueli** [comment]
I cleaned a bit the title. is uggest to drop the recmbinant thing cause it didnt spread. WHile this one is quite fast , but not enough to compete .

**Comment by krosa1910** [comment]
> I cleaned a bit the title and the query. i suggest to drop the recmbinant thing cause it didnt spread. WHile this one is quite fast , but not enough to compete .

It usually needs a country with huge local spreading for a lineage to boom (US for 1.5, India for 1.16,  China for EG.5.1, etc.) sadly this one did not pick one to settle down.  (Also I think its number is 51, is 61 a mistype or I am missing someone under my search, which is the same as the original proposal).

**Comment by krosa1910** [comment]
Has grown to 69.
This one is keeping a relatively constant share within a relatively constant lineage, so its overall proportion does not change much, I would suppose it to be designated when it reaches 100, although that could take a while.

**Comment by FedeGueli** [comment]
Propose it when reaches 100

**Comment by krosa1910** [comment]
This now go by 99seqs under the nucleotide search T5619C,G21718T,C22995G.
I think it is quite stable now, and if tomorrow some new sequences are uploaded, then I would propose it in the main repo.

**Comment by krosa1910** [comment]
Think it is good enough to be proposed, closing this for now.

**Comment by FedeGueli** [comment]
Transferred to https://github.com/cov-lineages/pango-designation/issues/2285
