### ISSUE TITLE
XBB.2.3/XBB.1.16 recombinant, 2 samples NSW/Australia

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#36]
XBB.2.3/XBB.1.16 recombinant from NSW. 2 samples. C4234T and G6536A from XBB.2.3. From C11750T and forward XBB.1.16.

EPI_ISL_17612843
EPI_ISL_17612873

Query: G6536A, T6262C, A28447G

2 samples at the bottom.
![Screenshot_20230508_201139_Twitter.jpg](https://user-images.githubusercontent.com/94831035/236900959-65672d3d-8d8d-4bcd-a20a-5b86a8eacdf4.jpg)

**Comment by FedeGueli** [comment]
No new sample from this one. Next week i ll close this if nothing changes

**Comment by FedeGueli** [comment]
CLosing this for now
