### ISSUE TITLE
XBB.1.5.15 sublineage (sibling lineage of FD.2?) with Orf1a:G519S(NSP2_G339S), Orf1a:K2511N(NSP3_K1693N) circulating in China(182 seq, 17 countries) then S:Q613H(1 seq, Singapore)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#360]
XBB.1.5.15> G1820A(Orf1a:G519S)> T18321C> C28164A(~Orf8:Q91K~)> G7798T(Orf1a:K2511N), C26625T
Query: T10204C, T18321C, C26625T

Earliest Sequence: 04-18 Shenzhen, Guangdong, China EPI_ISL_17698128
Latest Sequence: 07-31 Bayingol, Xinjiang, China EPI_ISL_18161008

Regions Detected: **China** 158+3(Guangdong 46[15 imported], Shanghai 21[3 from Macao, 3 from **Vietnam**, 1 from **Maldives**, 1 from NZ, 1 from **Thailand**, 1 from Unknown], Hubei 17, Xinjiang 16, Yunnan 15, Sichuan 9, Fujian 8, Jiangxi 7, Beijing 6, Jiangsu 4, Heilongjiang 3, Anhui 2, Henan 2, Gansu 1, Shanxi 1; Hong Kong 1, Taiwan 2[1 from Thailand, 1 from Vietnam]),
**South Korea** 3(2 from **Switzerland**, 1 from **Germany**), **Japan** 2(Hokkaido 1, Saitama 1), **Singapore** 2(Local), **Malaysia** 1(Johor)
**Austria** 1(Wien), **Luxembourg** 1, **Spain** 1(Catalunya), **UK** 1(England),
**US** 4(NY 3[1 from HK, 1 airport screening], California 2), **Canada** 1(Alberta),
**Australia** 2(WA), **New Zealand** 1(Manukau)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_374fd_8dd590.json?label=id:node_6760137
![2023-07-09 (3)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/cf560b55-6fdb-499f-8999-8fd5ee2d8a2c)

Among the sequences with T10204C, T18321C, C26625T mutations, only 2 seq under C26996T, C29281T branch from Bortala, Xinjiang, China and 1 seq with C214A from Zhanjiang, Guangdong, China have C21998A(S:Q146K). So this sublineage is probably not a descendent of FD.2, but maybe a sibling of it.

According to the latest China CDC weekly covid report, XBB.1.5.15 is also circulating in Guangxi, which did not upload sequence since 04-03.

If excluding T10204C from query, there will be 1 more sequence Guangdong/GDCDC_JM_0096/2023|EPI_ISL_17698188|2023-05-10 found, potentially recombined with XBL.3> C17766T> C18888T> T15651C branch.

<details><summary>Sequences:</summary>

EPI_ISL_17614992, EPI_ISL_17618958, EPI_ISL_17625307,
EPI_ISL_17625309, EPI_ISL_17625314, EPI_ISL_17625323,
EPI_ISL_17625334, EPI_ISL_17625549, EPI_ISL_17625564,
EPI_ISL_17645512, EPI_ISL_17645714, EPI_ISL_17645928,
EPI_ISL_17671910, EPI_ISL_17671952, EPI_ISL_17671975,
EPI_ISL_17672055, EPI_ISL_17678386, EPI_ISL_17678390,
EPI_ISL_17684026, EPI_ISL_17684092, EPI_ISL_17684337,
EPI_ISL_17689345, EPI_ISL_17689395, EPI_ISL_17689406,
EPI_ISL_17689423, EPI_ISL_17689452, EPI_ISL_17696759,
EPI_ISL_17697560, EPI_ISL_17697643, EPI_ISL_17697668,
EPI_ISL_17697731, EPI_ISL_17698054, EPI_ISL_17698128,
EPI_ISL_17698135, EPI_ISL_17698161, EPI_ISL_17698167,
EPI_ISL_17698173, EPI_ISL_17698182, EPI_ISL_17698222-17698223,
EPI_ISL_17698320, EPI_ISL_17700452, EPI_ISL_17700758,
EPI_ISL_17704061, EPI_ISL_17714368-17714369, EPI_ISL_17718389,
EPI_ISL_17718396, EPI_ISL_17718414, EPI_ISL_17723148,
EPI_ISL_17724936, EPI_ISL_17725148, EPI_ISL_17725518-17725520,
EPI_ISL_17729913, EPI_ISL_17736004, EPI_ISL_17736078,
EPI_ISL_17739271, EPI_ISL_17739640, EPI_ISL_17739763,
EPI_ISL_17744601, EPI_ISL_17744749, EPI_ISL_17744781,
EPI_ISL_17744783, EPI_ISL_17762886, EPI_ISL_17770175,
EPI_ISL_17771901, EPI_ISL_17775294, EPI_ISL_17775298,
EPI_ISL_17775343, EPI_ISL_17775358, EPI_ISL_17775362,
EPI_ISL_17775405, EPI_ISL_17775551, EPI_ISL_17775607,
EPI_ISL_17785310, EPI_ISL_17789142, EPI_ISL_17790625,
EPI_ISL_17794120, EPI_ISL_17794254, EPI_ISL_17794439,
EPI_ISL_17794448, EPI_ISL_17794739, EPI_ISL_17794799,
EPI_ISL_17794886, EPI_ISL_17794913, EPI_ISL_17794952,
EPI_ISL_17795158, EPI_ISL_17795207, EPI_ISL_17795229,
EPI_ISL_17795390, EPI_ISL_17795506, EPI_ISL_17795639,
EPI_ISL_17795778, EPI_ISL_17801877, EPI_ISL_17801947,
EPI_ISL_17801976, EPI_ISL_17808300, EPI_ISL_17811065,
EPI_ISL_17811210, EPI_ISL_17813188, EPI_ISL_17816479,
EPI_ISL_17816498-17816499, EPI_ISL_17817009, EPI_ISL_17826752,
EPI_ISL_17836290, EPI_ISL_17836292-17836293, EPI_ISL_17836329,
EPI_ISL_17836363, EPI_ISL_17836370, EPI_ISL_17836422,
EPI_ISL_17836668, EPI_ISL_17836686, EPI_ISL_17836865,
EPI_ISL_17836920, EPI_ISL_17850199, EPI_ISL_17850315,
EPI_ISL_17850879, EPI_ISL_17879890, EPI_ISL_17879897,
EPI_ISL_17884002, EPI_ISL_17957145, EPI_ISL_17957170,
EPI_ISL_17960948, EPI_ISL_17965028, EPI_ISL_17966438,
EPI_ISL_17966474, EPI_ISL_17978445, EPI_ISL_17988280,
EPI_ISL_17989058, EPI_ISL_17999709, EPI_ISL_18009727,
EPI_ISL_18009730, EPI_ISL_18009880, EPI_ISL_18014671,
EPI_ISL_18033675, EPI_ISL_18033751, EPI_ISL_18033851,
EPI_ISL_18033937, EPI_ISL_18034191, EPI_ISL_18034368,
EPI_ISL_18034666, EPI_ISL_18034757, EPI_ISL_18034895,
EPI_ISL_18035040, EPI_ISL_18035057, EPI_ISL_18035059,
EPI_ISL_18035141, EPI_ISL_18035260, EPI_ISL_18035314,
EPI_ISL_18035377, EPI_ISL_18035409, EPI_ISL_18035415,
EPI_ISL_18035429, EPI_ISL_18035441, EPI_ISL_18035681-18035682,
EPI_ISL_18035752, EPI_ISL_18036091, EPI_ISL_18036148,
EPI_ISL_18036287, EPI_ISL_18036342, EPI_ISL_18037031,
EPI_ISL_18037144, EPI_ISL_18037200, EPI_ISL_18037210,
EPI_ISL_18037227, EPI_ISL_18049486, EPI_ISL_18049517,
EPI_ISL_18049609, EPI_ISL_18055792, EPI_ISL_18058985,
EPI_ISL_18080540, EPI_ISL_18082590, EPI_ISL_18093847,
EPI_ISL_18111112, EPI_ISL_18146405, EPI_ISL_18207141
</details>

**Comment by krosa1910** [comment]
Sorry for the interruption, but I would just like to ask @FedeGueli , if it would be good to add some labels roughly describing the sequence number when a variant is spotted (for example, >100, or <10)?

**Comment by FedeGueli** [comment]
> Sorry for the interruption, but I would just like to ask @FedeGueli , if it would be good to add some labels roughly describing the sequence number when a variant is spotted (for example, >100, or <10)?

good idea but then it could be very time expensive to update the label

**Comment by Over-There-Is** [comment]
@AngieHinrichs this sublineage is misassigned as FD.2

**Comment by AngieHinrichs** [comment]
FD.2 is XBB.1.15.2 -- it's XBB.1.15 plus ORF1a:G519S (G1820A).  So I think this proposal is now for a sublineage of FD.2.

**Comment by Over-There-Is** [comment]
> FD.2 is XBB.1.15.2 -- it's XBB.1.15 plus ORF1a:G519S (G1820A). So I think this proposal is now for a sublineage of FD.2.

But S:Q146K is also a part of the definition of FD.2, and only 2/138 of this proposal have S:Q146K, so I don't consider it's an artifact.

**Comment by AngieHinrichs** [comment]
S:Q146K is C21998A (together with XBB's C22000A).  C21998A is so noisy across the entire XBB branch of the UShER tree that I started masking it in the XBB branch as of the 2023-07-21 tree.  (Long comment about this: https://github.com/cov-lineages/pango-designation/issues/1503#issuecomment-1646243451)

So even if C21998A/S:Q146K is in some sequences (and lineage descriptions), it will not appear in the XBB branch of the UShER tree anymore.  Sorry about the disruptive change, but I still believe it is necessary to prevent a lot of trouble in the tree.

**Comment by Over-There-Is** [comment]
Guangdong +32

**Comment by Over-There-Is** [comment]
| sequences | C21998A | -C21998A |
| -- | -- | -- |
| T18321C | 3 | 167 |
| -T18321C | 2833 | 266 |

**Comment by Over-There-Is** [comment]
Peking +3

**Comment by Over-There-Is** [comment]
1 seq in Singapore got Q613H

**Comment by FedeGueli** [comment]
It cant compete with fastest lineages: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T10204C%2CT18321C%2CC26625T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
closing this for now . no recent samples.

**Comment by Over-There-Is** [comment]
Shanghai/SCDC-XG08-12897/2023|EPI_ISL_18268403|2023-08-30
