### ISSUE TITLE
XBB.1.5 pre-T17124C on ORF1a:T4129I branch with E:V49L, then mini saltation with ORF1a:T2087I, ORF1b:S2359F and S:T478R (8 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#361]
**XBB.1.5** pre-T17124C on ORF1a:T4129I (nsp8_T187I) branch with **E:V49L**, then mini saltation with ORF1a:T2087I (nsp3_T1269I), ORF1b:S2359F (nsp15_S308F) and **S:T478R**

**Defining Mutations:** [XBB.1.5's T17124C > T23018C > C17124T flip-flop] > C12651T(ORF1a:T4129I) > C13426T > C18714A > G26389T(E:V49L) > C6525T(ORF1a:T2087I), T9352C, C20543T(ORF1b:S2359F), A22681T, C22995G(S:T478R), C27294T, C28609T
**Query:** A22681T, C22995G, C12651T
**Earliest seq:** 2023-04-30 (EPI_ISL_17651643, South Carolina)
**Latest seq:** 2023-06-08 (EPI_ISL_17950654, California)
**Sampled Countries:** USA (6, California/2, South Carolina/1, Georgia/1, North Carolina/1, Delaware/1)

<details><summary>Genomes: </summary>
EPI_ISL_17651643, EPI_ISL_17694119, EPI_ISL_17768929, EPI_ISL_17853822, EPI_ISL_17861527, EPI_ISL_17950654
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31b1a_96ccc0.json?c=gt-S_478,573&f_userOrOld=uploaded%20sample

view from XBB.1.5 pre-T17124C polytomy:
![overview](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/33baaf86-d5e0-40e5-9af8-75e3ce239a72)

diversity from ORF1a:T4129I branch, filtered by 478, 573 codon of S gene, and collection date after May 1st
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8e7d7e2e-4b5c-4857-87d0-3ed0d7adda59)

**Trivia:**
- Another XBB.1.5* flip-flop branch, this time placed before T17124C, means it's a sibling to XBB.1.5.24, XBB.1.5.57 etc.
- ORF1a:T4129I branch with query C12651T, G27915T, -C12789T, -T17124C, -T13704C, returns 416, of them 147 collected since May 1st, 51 collected since June 1st.
- There's another branch featuring S:T573I (definition of XBB.1.5.1), follows: C12651T(ORF1a:T4129I) > A5116G > C23280T(S:T573I) with query:C23280T, A5116G, C12651T, returns 20

**Comment by FedeGueli** [comment]
It seems quite slow
