### ISSUE TITLE
XBB.1.5.92 with ORF1a:L3829F (nsp6_L260F) (98 seqs, mainly in Costa Rica and Ecuador, 12 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#362]
**Defining Mutations:** XBB.1.5.92 (C3768T= ORF1a:T1168I) > C11750T(ORF1a:L3829F)
**Query:** C3768T, C11750T, T17124C
**Earliest seq:** 2023-03-06 (EPI_ISL_17240745, Ecuador)
**Latest seq:** 2023-06-23 (EPI_ISL_17961597, Ecuador)
**Sampled Countries:** Costa Rica (24), Ecuador (24), USA (12, California/5, New Jersey/2, New York/2, North Carolina/1, Pennsylvania/1, Texas/1), Guatemala (8), Germany (2), Belgium (1), Spain (1, Canary Islands), Colombia (1), Mexico (1), Panama (1), UK (1, Wales)

<details><summary>Genomes: </summary>

EPI_ISL_17240745, EPI_ISL_17429082, EPI_ISL_17519027,
EPI_ISL_17519102, EPI_ISL_17525650, EPI_ISL_17527944,
EPI_ISL_17527949, EPI_ISL_17582793-17582796, EPI_ISL_17582798,
EPI_ISL_17582806, EPI_ISL_17612038, EPI_ISL_17612061,
EPI_ISL_17621288, EPI_ISL_17654589, EPI_ISL_17654598,
EPI_ISL_17654687, EPI_ISL_17654750, EPI_ISL_17654777,
EPI_ISL_17654789, EPI_ISL_17674267, EPI_ISL_17683020,
EPI_ISL_17683043-17683044, EPI_ISL_17684571, EPI_ISL_17684577,
EPI_ISL_17695468, EPI_ISL_17695472, EPI_ISL_17712005,
EPI_ISL_17712018, EPI_ISL_17713984, EPI_ISL_17722436,
EPI_ISL_17730094, EPI_ISL_17763506, EPI_ISL_17766883,
EPI_ISL_17774107, EPI_ISL_17774126, EPI_ISL_17774131,
EPI_ISL_17774145, EPI_ISL_17774195-17774196, EPI_ISL_17774198,
EPI_ISL_17774203-17774207, EPI_ISL_17788960, EPI_ISL_17798393,
EPI_ISL_17800566, EPI_ISL_17801644, EPI_ISL_17833803,
EPI_ISL_17833855, EPI_ISL_17833862, EPI_ISL_17834337,
EPI_ISL_17834418, EPI_ISL_17838695, EPI_ISL_17854201,
EPI_ISL_17854470, EPI_ISL_17856036, EPI_ISL_17879866,
EPI_ISL_17950535, EPI_ISL_17954111, EPI_ISL_17954147,
EPI_ISL_17954610, EPI_ISL_17961499, EPI_ISL_17961554,
EPI_ISL_17961593, EPI_ISL_17961597, EPI_ISL_17961609,
EPI_ISL_17961637, EPI_ISL_17970749, EPI_ISL_17972754,
EPI_ISL_17972779
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3eab3_97aef0.json?f_userOrOld=uploaded%20sample

view from XBB.1.5's T17124C polytomy
![3829](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/19b51c66-db1a-45d3-ab22-dfac8e0cf694)

details
![countries](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ee7f5bc3-36f4-4ff6-b9e3-6f7a9552067b)

**Trivia:**
- Probably high local prevalence in certain South America countries, too little samples to confirm this.
![caribbean](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/16aefa70-f307-473c-b3be-c65fff1485b9)

- ORF1a:L3829F is the notorious chronic infection hallmark, this may be worth monitoring for a while.

**Comment by Over-There-Is** [comment]
@AngieHinrichs As a sublineage of new-designated XBB.1.5.92, this lineage is placed under a Orf1a:Y1467C> Orf1a:T1168I> Orf1a:C1467Yrev flip-flop branch. And the sequences with C823T, C3768T, C10615T (parental branch of #170) are placed under C823T branch, but I think they are also a subbranch of XBB.1.5.92.
But C3768T(Orf1a:T1168I) is too homoplastic, some of the sequences with T1168I is actually unrelated to XBB.1.5.92.
![2023-07-12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/ac47844e-f3e9-410f-bb2f-1d8ac183f3b5)

**Comment by FedeGueli** [comment]
There are at least three ecuadorean sublineage of XBB.1.5 with Orf1a:T1168I : 
1
The one designated here is the one with the main sublineage with Orf1a:L3829F proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/362 :
I think Angie fixed the flip flop thing that was highlighted in the issue
![Schermata 2023-07-15 alle 13 19 53](https://github.com/cov-lineages/pango-designation/assets/87669813/aacb3ffd-823a-4cae-993e-04f1dd1e45c1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1007a_27cc00.json?c=gt-nuc_823&label=id:node_7037790
2 
Another XBB.1.5 with C823T and then Orf1a:T1168I that acquired S:E554K ( proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/170  ) that ctually could be one of the fastest lineages at least in South America
![Schermata 2023-07-15 alle 13 23 32](https://github.com/cov-lineages/pango-designation/assets/87669813/1d714fd8-bd99-46c3-b349-9e3c82f1319f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1007a_27cbf0.json?label=id:node_6889930
3
a small unproposed lineage in a flip flop branch with S:W258C>W that further acquired three key NTD mutations:
![Schermata 2023-07-15 alle 13 24 45](https://github.com/cov-lineages/pango-designation/assets/87669813/bc318cbf-803f-49d1-8807-4665de9750bd)
![Schermata 2023-07-15 alle 13 25 08](https://github.com/cov-lineages/pango-designation/assets/87669813/1698a823-261f-4648-bd6e-728b7f525b42)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_1007a_27cc00.json?c=userOrOld&label=id:node_6936104

**Comment by FedeGueli** [comment]
ping @corneliusroemer see discussion above, please.

**Comment by AngieHinrichs** [comment]
@Over-There-Is I see that C3768T (ORF1a:T1168I) happens several times in XBB.1.5, but in each case there are more sequences with XBB.1.5 > [some mutation] than XBB.1.5 > [some mutation] > C3768T.  So to me, the evidence for each of those other mutations occurring first looks pretty strong, and I think it's plausible that either C3768T happened multiple times after those other mutations (and perhaps is sometimes an artefact, especially from Ecuador and Sweden?).  

Why do you think the C823T, C3768T, C10615T sequences in particular belong in XBB.1.5.92?  I see 134 sequences on the branch with all three of those mutations, but even more (207) that have C823T.  Also some of the sequences with C823T have older dates like USA/MA-CDCBI-CRSP_YEAJAWGEG53EKBFX/2022|OP987449.1|2022-11-21.  So I think it's plausible (though not certain) that C823T came first.
