### ISSUE TITLE
XBB.1.5 sublineage with ORF1a:T2280N, S:R346I (13 seqs)and S:K356T (5 seqs, Dominican Republic and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#363]
**Defining Mutations:** [XBB.1.5's T17124C > T23018C] > C19186T > C337T > C15951T > C7104A(ORF1a:T2280N), T18510A, C26807T > T2308C, A7483G, G22599T(S:R346I over existing G22599C/R346T) > A22629C(S:K356T)
**Query for S:R346I:** T2308C, A7483G
**Query for S:K356T.** T2308C, A7483G, A22629C
**Earliest seq:** 2023-05-16 (EPI_ISL_17716836, New Jersey, Airport Screening with unknown travel history)
**Latest seq:** 2023-06-25 (EPI_ISL_17956181, Dominican Republic)
**Sampled Countries:** Dominican Republic (4), USA (1, New Jersey)

<details><summary>Genomes: </summary>

EPI_ISL_17716836, EPI_ISL_17956181, EPI_ISL_17956228, EPI_ISL_17956264

Genome with Ns: EPI_ISL_17956265
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_7238_9875a0.json?c=gt-S_346,356&f_userOrOld=uploaded%20sample&showBranchLabels=all

view from XBB.1.5's T17124C poyltomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/57b33b11-324b-41cc-8a2b-7fdfccef2e15)

details from C19186T branch with filter of codon 346, 356 of S Gene, and collection date since May 1st:
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a26f4996-ca9d-4796-af3a-a9c76c8e964e)

**Trivia:**
- The query finds 4 but there's probably a 5th with Ns from 22341 to 22819.
- The parent S:R346I branch with query: T2308C, A7483G, G22599T finds 12 seqs.

**Comment by FedeGueli** [comment]
I saw 5 samples of this .

And i added the count of R346I cause it is recent and circulating too.
![Schermata 2023-07-11 alle 08 20 32](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0874e7ee-e81e-40e6-8b16-256be6fd3e78)

**Comment by FedeGueli** [comment]
Designated XBB.1.5.93 (S:R346I)

**Comment by FedeGueli** [comment]
Parental libeage designated XBB.1.5.93 and S:R346I HD.1. closing this reopen another for K356T directly on the main page.

**Comment by AngieHinrichs** [comment]
@aviczhl2 I have not read your milestone-parsing code so I don't know if it already supports commas.  I just wanted to point out that while previous milestones with multiple lineages have been space-separated, this milestone has commas in addition to spaces, and so do a few other new milestones.

**Comment by FedeGueli** [comment]
> @aviczhl2 I have not read your milestone-parsing code so I don't know if it already supports commas. I just wanted to point out that while previous milestones with multiple lineages have been space-separated, this milestone has commas in addition to spaces, and so do a few other new milestones.

Commass erased now!

**Comment by aviczhl2** [comment]
> @aviczhl2 I have not read your milestone-parsing code so I don't know if it already supports commas. I just wanted to point out that while previous milestones with multiple lineages have been space-separated, this milestone has commas in addition to spaces, and so do a few other new milestones.

Thanks for pointing out. This was a bug but the current code has fixed it and now it works with commas.
