### ISSUE TITLE
XBB.1.9.1 with ORF1b:A1877S/NSP14:A353S (85 seqs, 2 countries USA/UK)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#365]
Description

Sub-lineage of: XBB.1.9.1
Substitution on top of XBB.1.9.1:
ORF1b:A1877S ORF1ab:A6278S NSP14:A353S
Nucleotide: G19096T
Earliest sequence: 2023-4-17, Puerto Rico — EPI_ISL_17641124
Most recent sequence: 2023-8-4, New York — EPI_ISL_18094998
Countries circulating: USA (77), UK (3)
Number of sequences: 80
GISAID nucleotide query: G19096T,C11956T,G5720A
CovSpectrum query: Nextcladepangolineage:XBB.1.9.1* & G19096T

```{r, echo=FALSE}
EPI_ISL_17734786,EPI_ISL_17884542,EPI_ISL_17713935,EPI_ISL_17830915,EPI_ISL_17713896,EPI_ISL_17830912,EPI_ISL_17885174,EPI_ISL_17800509,EPI_ISL_17884556,EPI_ISL_17853455,EPI_ISL_17830902,EPI_ISL_17805706,EPI_ISL_17681208,EPI_ISL_17831129,EPI_ISL_17885221,EPI_ISL_17856021,EPI_ISL_17800516,EPI_ISL_17805644,EPI_ISL_17885181,EPI_ISL_17713903,EPI_ISL_17831586,EPI_ISL_17831128,EPI_ISL_177,3932,EPI_ISL_17831069,EPI_ISL_17830917,EPI_ISL_17885229,EPI_ISL_17848073,EPI_ISL_17830906,EPI_ISL_17965524,EPI_ISL_17965534,EPI_ISL_17885253,EPI_ISL_17848072,EPI_ISL_17641142,EPI_ISL_17777766,EPI_ISL_17965518,EPI_ISL_17856800,EPI_ISL_17965490,EPI_ISL_17965493,EPI_ISL_17885280,EPI_ISL_17853059,EPI_ISL_17885268,EPI_ISL_17777816,EPI_ISL_17641124,EPI_ISL_17638652,EPI_ISL_17856179,EPI_ISL_17950715,EPI_ISL_17713895,EPI_ISL_17831098,EPI_ISL_17831101,EPI_ISL_17853779,EPI_ISL_17681206,EPI_ISL_17847954,EPI_ISL_17856726,EPI_ISL_17681207,EPI_ISL_17641130,EPI_ISL_17965533,EPI_ISL_17737319,EPI_ISL_17885199,EPI_ISL_17884555,EPI_ISL_17805646,EPI_ISL_17777789,EPI_ISL_17638657,EPI_ISL_17831127,EPI_ISL_17853062

```

[usher](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=5000&remoteFile=https%3A%2F%2Flapis.cov-spectrum.org%2Fgisaid%2Fv1%2Fsample%2Fgisaid-epi-isl%3ForderBy%3Drandom%26limit%3D1000%26dateFrom%3D2023-01-02%26dateTo%3D2023-07-01%26aaMutations%3DORF1b%253AA1877S%26nextcladePangoLineage%3Dxbb.1.9.1*%26host%3DHuman%26accessKey%3D9Cb3CqmrFnVjO3XCxQLO6gUnKPd)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e512_a6ba50.json?f_userOrOld=uploaded%20sample&label=id:node_6666516

![Screenshot 2023-07-08 at 19-31-56 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ singleSubtreeAuspice_genome_1ce75_9e7680 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/c1b8757f-b53d-434f-a949-f039ad184a36)

[Mutations over time](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G19096T&nextcladePangoLineage=xbb.1.9.1*&)
![Screenshot 2023-07-08 at 19-37-21 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/0c7f505c-304b-4c9e-91e9-fc2f32b75e9f)

[Relative growth advantage](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G19096T&nextcladePangoLineage=xbb.1.9.1*&)
![Screenshot 2023-07-08 at 19-37-42 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/b2a32e39-0386-41ab-a324-592a62fa8074)

**Comment by FedeGueli** [comment]
Thx for proposing i ve added the link to the usher tree cause the one to the trees you put expires very soon (also the other but still it lasts a couple of days)

**Comment by FedeGueli** [comment]
I is likely to be slower than other lineages . Lets see how much will resist through July to EG.5/FL.1.5 wave

**Comment by FedeGueli** [comment]
it cant compete: [G19096T,C11956T,G5720](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G19096T%2CC11956T%2CG5720A&analysisMode=CompareToBaseline&)

**Comment by arodzh-sudo** [comment]
Thank you @FedeGueli, will close.
