### ISSUE TITLE
XBB.1.16.1 with s:P521S, ORF1a:L681F 96 seq., 106 with ORF1a:L469F

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#366]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/86c53f94-fb7d-4d36-a17a-9b649ea3d939)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a58ba7af-8cd2-4e28-b8df-c93891aff9a5)
tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_29000_a42940.json?c=gt-nuc_2306&label=id:node_6635022
first seq:2023-03-13
most recent:2023-06-24
gisaid query: C2306T, C23123T, A22101T
EPI_ISL_17804864 EPI_ISL_17524590 EPI_ISL_17953172 EPI_ISL_17953208 EPI_ISL_17606498 EPI_ISL_17715767 EPI_ISL_17953190 EPI_ISL_17953203 EPI_ISL_17953194 EPI_ISL_17804828 EPI_ISL_17953181 EPI_ISL_17804826 EPI_ISL_17953186 EPI_ISL_17793662 EPI_ISL_17953200 EPI_ISL_17463472 EPI_ISL_17953198 EPI_ISL_17606508 EPI_ISL_17953180 EPI_ISL_17953207 EPI_ISL_17804936 EPI_ISL_17793461 EPI_ISL_17953213 EPI_ISL_17953185 EPI_ISL_17823707 OR075468.1 EPI_ISL_17744944 EPI_ISL_17953202 EPI_ISL_17949804 EPI_ISL_17720544 EPI_ISL_17813837 EPI_ISL_17763974 EPI_ISL_17953177 EPI_ISL_17804887 EPI_ISL_17793650 EPI_ISL_17803558 EPI_ISL_17463479 EPI_ISL_17606370 EPI_ISL_17953187

**Comment by FedeGueli** [comment]
Although it doesnt seem super fast it is worth proposing it in Pango page.

**Comment by FedeGueli** [comment]
this is now 106.

Please propose it.


pig @corneliusroemer
