### ISSUE TITLE
GE.1 + Orf1a:G661S (see #2089) got S:E554K and spreading in Bangladesh around 20% prevalence in July (24 seqs) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#367]
This should be designated if it grows just after the two main branches of GE.1 will be designated from https://github.com/cov-lineages/pango-designation/issues/2089

The one i want to propose here is defined by Orf7a:T28I and S:E554K

Defining mutations:
XBB.2.3 >>C601T, Orf1a:G661S (G2246A)  >> Orf7a:T28I (C27476T) >> S:E554K (G23222A)

Gisaid query: G2246A,C27476T,G23222A,C23123T,

Tree:
![Schermata 2023-07-09 alle 11 24 29](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/621bacaf-a473-443d-bc2d-05bcf611eed5)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_37ec9_a654c0.json?c=gt-S_554&label=id:node_7058976

**Comment by FedeGueli** [comment]
Newly found in Finland

**Comment by FedeGueli** [comment]
now 12 it seems spreading quite fast in Finland

**Comment by FedeGueli** [comment]
@corneliusroemer one to watch

**Comment by HynnSpylor** [comment]
Today Singapore updated 3 seqs, including 2 with travel history in Bangladesh and 1 local case.

**Comment by FedeGueli** [comment]
> Today Singapore updated 3 seqs, including 2 with travel history in Bangladesh and 1 local case.

this is fast

**Comment by FedeGueli** [comment]
three more samples today from Singapore all with travel history from Bangladesh.

cc @corneliusroemer @thomaspeacock @angiehinrinchs i suggest direct designation for this one, estimated rough prevalence in July in Bangladesh is around 25%

**Comment by FedeGueli** [comment]
+1 canada

**Comment by FedeGueli** [comment]
+1 England

**Comment by FedeGueli** [comment]
I jsut noticed that all the two from SIngapore were travellers from Bangladesh.
Do i did the maths : for july for Bangladesh we have just samples coming from travellers to Singapore , assuming a random distribution (and that could be false ) of travellers the estimated prevalence for Bangladesh in July for this lineage is: 6 out of 26 reaching a bit more than 20%

**Comment by FedeGueli** [comment]
cc @corneliusroemer i suggest to take a look at this.

**Comment by aviczhl2** [comment]
Designated GE.1.1
