### ISSUE TITLE
XBB.1.16 (FU.1)/XBB.1.9.2 (EG.5.1) recombinant, 13 samples from New Zealand  

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#369]
XBB.1.16 (FU.1)/XBB.1.9.2 (EG.5.1) recombinant

7 samples from New Zealand/Lakes
EG.5.1 Spike
First sample: 2023-06-01
Latest sample: 2023-06-14
Query:  Spike_Q52H, T3802C, A16878T (or T3802C, A16878T,G21718T)
Usher tree: 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/e56dd8ac-82a5-4c8a-bd1e-ed164a630b24)
Breakpoint between 14856 and 16878, EG.5.1 Spike
Nextclade:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/b7b4d42a-3ff2-4265-8e61-6e897fdca17a)
Samples:
EPI_ISL_17962015 
EPI_ISL_17962141
EPI_ISL_17962481 
EPI_ISL_17962012 
EPI_ISL_17962014 
EPI_ISL_17962013 
EPI_ISL_17962140

New Zealand only uploads their sequences like once a month, so it could be a while before we se this ones again. I will keep an eye on it though. Maybe it will show up in other countries.

**Comment by aviczhl2** [comment]
All of them have A460G https://github.com/cov-lineages/pango-designation/issues/2037 , the Chinese version of FU.1.

**Comment by Over-There-Is** [comment]
T9964C is also contained in Shanghai/SCDC-XG05-5351/2023|EPI_ISL_17770225|2023-05-15

**Comment by Over-There-Is** [comment]
These samples do not include XBB.1.9.2's 27507C and XBB.1.16.1's 23202T but XBB.1.16's 28447G. There is another breakpoint between 23202 and 27507. Since the breakpoint can also be before 25572, the EG.5.1* donor can also be EG.5.1.1. Maybe this recombinant originates in China.

**Comment by Memorablea** [comment]
Well proposed, it is recommended to specify.

**Comment by Over-There-Is** [comment]
NZ+6

**Comment by corneliusroemer** [comment]
Just spotted it independently when I encountered the 6 new NZ sequences mentioned by @Over-There-Is
I'm really out of shape these days - 3 weeks behind @JosetteSchoenma in noticing this quite interesting recombinant 😄

**Comment by FedeGueli** [comment]
1 new sample came from Shanghai .

cc @corneliusroemer

**Comment by JosetteSchoenma** [comment]
Thanks @FedeGueli Local or with travel history?

**Comment by FedeGueli** [comment]
the last three came from Chiina.
@JosetteSchoenma when you have time propose it.

**Comment by FedeGueli** [comment]
ping @JosetteSchoenma please propose it.

**Comment by aviczhl2** [comment]
The Chinese seqs and New Zealand seqs are not the same recombinant. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/7ad39d50-02a3-421c-b860-64ca6ab290ae)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_211f6_1d4ab0.json?f_userOrOld=uploaded%20sample

The China-Hubei seqs are with C9693T(EG.5.1 defining) and without Orf1a;L3829F(XBB.1.16)
hence the breakpoint shall between 6542 and 9693. 

The China-Shanghai seqs are proposed in #647 , it is also different recombinant.

**Comment by JosetteSchoenma** [comment]
Thanks, @aviczhl2 . I was planning on checking that today.

**Comment by FedeGueli** [comment]
Thx @aviczhl2 for keeping track of this one. I think the Hubei one should be proposed too.

**Comment by Over-There-Is** [comment]
T9964C probably comes from FU.1, so it should be contained in all the sequences of this lineage.
Maybe a better query to avoid other recombinants: `T9964C, A16878T, G21718T`
FU.1> A460G> G19711A(Orf1b:V2082I)> T9964C have 6 sequences now: `A460G, T9964C, C23202T`

**Comment by JosetteSchoenma** [comment]
@Over-There-Is Thank you. The T9964C, A16878T, G21718T query indeed works fine to catch the New Zealand samples. And the 2 Shanghai and 2 Hubei samples indeed come from 2 different recombinants.

I am not completely sure why you have added that last FU.1 query (A460G, T9964C, C23202T) to this issue though. It finds the FU.1 at the bottom.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/53c830c4-0d8c-4856-b887-9da27ee80dac)


@FedeGueli I am busy right now, and I do not think this will get designated while under 20 samples. Let's wait for a new upload from New Zealand, or if it really shows up elsewhere.

**Comment by FedeGueli** [comment]
no new sample of the nzl branch.

**Comment by aviczhl2** [comment]
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice12_genome_d661_392ca0.json?label=id:node_11063104 ![image](https://user-images.githubusercontent.com/125747944/279999120-e99a2012-741b-47b7-af38-4cc7023fad53.png)
> 
> There's a neighbouring branch seems to be a different XBB.1.16/EG.5.1+M177I+L455F/XBB.1.16 recombinant

Make a separate issue pls.
