### ISSUE TITLE
CM.7.1 (BA.2.3.20+S:F486S+ S:K147E) Saltation Sublineage with S:R403K (12 seqs, Spain, Italy, France - June 23- ) 

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#37]
Edited by Fede:

Ryan found this one very early and so it proposed basically the spanish branch of this one. Now we know that it is spread to 3 countries (Italy, France and Spain) counts 8 sequences (EPI_ISL_17390375, EPI_ISL_17615444, EPI_ISL_17619326,
EPI_ISL_17677150, EPI_ISL_17719461, EPI_ISL_17719468,
EPI_ISL_17726239, EPI_ISL_17726413) found with the query : G14500T, C26801T,G656A, G22770A
and it shows a great within lineage diversity as shown by the today tree:

![Schermata 2023-05-30 alle 23 08 03](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/14fd63bc-683e-40d0-b1c5-c3bdb68c721a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bd9a_662370.json?c=userOrOld&label=id:node_7104726

Today @corneliusroemer designated the parental lineage CM.7.1 .

So now defining mutations are:

CM.7.1 ( S:K147E) >> Orf1a:L16F (C311T),Orf1b:V345L (G14500T), C26801T >ORf1a:A131T (G656A),S:R403K (G22770A )

**I apologizes with @ryhisner for the heavy editing but it is needed to keep proposal up to date to be ready tobe  transferred**

I will close https://github.com/sars-cov-2-variants/lineage-proposals/issues/103

_______ORIGINAL VERY EARLY PROPOSAL BY RYAN HISNER______

### **Description**
**Sub-lineage of:** CM.7
**Earliest sequence:** 2023-4-24, Italy
**Most recent sequence:** 2023-4-26, Spain (2)
**Countries circulating:** Spain (3)
**Number of Sequences:** 3
**GISAID AA Query:** Spike_R403K, NSP2_T547I, NSP1_L16F
**GISAID Nucleotide Query:** T23020C, G22770A, C2445T
_Alternative Gisaid query (Fede) : G14500T, C26801T,G656A, G22770A_
**CovSpectrum Query:** Nextcladepangolineage:BA.2.3.20* & [8-of: C311T, G656A, C1284T, T3802C, T5377A, C12754T, C13059T, G14500T, C14809A, T14892A, C16329T, A22001G, G22770A, T23020C, G23426A, C26256T, C26681T, C26801T, C26894T]
 
**Substitutions on top of CM.7:**
**Spike:** K147E, R403K,  S:V622I
**ORF1a:** L16F, A131T, T340I, T4265I (NSP1_L16F, NSP1_A131T, NSP2_T160I, NSP10_T12I)
**ORF1b:** V345L, R448S, D475E (NSP12_V354L, NSP12, R457S, NSP12_D484E)
**Nucleotide:** C311T, G656A, C1284T, T3802C, T5377A, C12754T, C13059T, G14500T, C14809A, T14892A, C16329T, A22001G, G22770A, T23020C, G23426A, C26256T, C26681T, C26801T, C26894T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CM.7_T23020C_K147E_R403K.json   
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/33738461/236958869-d5d2d020-4e72-4e7b-a94c-3d4f16e13b95.png">

**Evidence**
The three sequences from Spain are from separate patients with very different ages. One collected April 24, the other two April 26. There's a sequence from March 22 from Italy that shares S:K147E, S:R403K, ORF1a:A131T, and ORF1b:V345L. The closest ancestor to all of them is from Germany, so it seems this branch has been kicking around Europe quite a bit.
 
The coverage on one sequence is missing a big chunk of the spike NTD and the April 24 sequence is missing even more—10% of the genome has no coverage.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17615444, EPI_ISL_17619326, EPI_ISL_17620611
</details>

**Comment by FedeGueli** [comment]
No new sequence coming up, likely a good news.

**Comment by HynnSpylor** [comment]
12 seqs now（updated Italy/France recently）

**Comment by FedeGueli** [comment]
Thx @HynnSpylor

**Comment by FedeGueli** [comment]
New sample came from France collect in Mid June. interestingly it has Orf7a:S44L that was mutated to P in the successful late BA.5.11 lineage emerged in SA but spread in Denmark.
