### ISSUE TITLE
Probably EG.1 saltation with ORF1a:T2087I, ORF1a:S2804I, ORF1a:H2831R, ORF1b:L2492V, ORF1b:D2333N and S:F490P (3 seqs, Austria)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#371]
**Defining Mutations:** EG.1 > A5720G_rev(ORF1a:S1819G_rev) > T12789C_rev(ORF1a:I4175T_rev) > A1486G, C6525T(ORF1a:T2087I), G8676T(ORF1a:S2804I), A8757G(ORF1a:H2831R), T13929C, G20464A(ORF1b:L2492V), C20941G(ORF1b:D2333N), T23030C(S:F490P over existing S:F490S/T23031C)
**Query:** T13929C, C20941G, T23030C
**Earliest seq:** 2023-06-12 (EPI_ISL_17827020, Austria)
**Latest seq:** 2023-06-19 (EPI_ISL_17881099, Austria)
**Sampled Countries:** Austria (3)

<details><summary>Genomes: </summary>
EPI_ISL_17827020, EPI_ISL_17880975, EPI_ISL_17881099
</details>

**Saltation Profile:**
Mutations on top of nearest branch:

```
nuc	unique	A1486G, G8676T, A8757G, T13929C, C20941G, T23030C
nuc	homoplasies	C6525T, G20464A
nuc	reversionsToRoot	A5720G, T12789C
ORF1ab	unique	S2804I, H2831R, L6893V
ORF1ab	homoplasies	T2087I, D6734N
ORF1ab	reversionsToRoot	S1819G, I4175T
S	unique	S490P
```

Mutations over reference strain:
![Mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c04c6393-99be-4299-90f8-ba91b34dbcf8)

**Trivia:**
- Came across this strange saltation under a 2-step-reversion branch of EG.1. Right now it's only a small cluster so it may not be a big matter.
- ORF1a:T4175I is the parent branch of XBB.1.9, XBB.1.23 and XBB.1.42 (which got dropped in this proposal)
- ORF1a:G1819S is the definition of XBB.1.9 (which got dropped in this proposal)
- There are another 2 sibling mini-saltation branches, this proposal is the most recent one.
- Query: G23401T, C28928T, A27507C, A16878T, -G5720A, -C12789T to catch them
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_401b9_a9bf60.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3992ed8a-3dfd-4e75-8f74-ee9ef6be0021)
- Coverage seems good, only 1 seq have Ns around 5720 and 12789
![coverage](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/317418b4-d90b-4000-a6ee-fc687116dd44)
- Are these recombinants, _OR_ real EG.1 sub-branches with 2 definition mutations reversed, _OR_ sibling(s) to XBB.1.9, _OR_ simply mis-placed?

**Comment by FedeGueli** [comment]
Could be a recombinant with XBB.1.5.26 family likely EU.1.1 

Not super sure but Austria was where EU.1.1 started spreading in Europe and this proposed one and EU.1.1 have two identical  mutations (G8676T, A1486G) in the orf1a side where the two defining of EG.1 got cancelled. One thing that makes me dubious is that EU.1.1 & parents has C920T absent in this proposed one.
But the Breakpoints could be one  2 after 920 and the other  before T17124C

look:
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nucMutations=G8676T%2CA1486G%2CA8757G&nextcladePangoLineage1=XBB.1.5.26*&analysisMode=CompareEquals&


cc @JosetteSchoenma please take a look at this.

**Comment by JosetteSchoenma** [comment]
The only samples I can find that the EG.1 might have recombined with are some XBB.1.5, that already had gained several extra mutations (mostly stepwise it seems.. You can find them all with this query: A1486G, -G5720A, -C12789C, T13929C
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/5fd1b756-89b3-4777-8808-c410cd67d342)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/d51bc96c-ddb6-458f-a5c9-68f359df3d4d)
The German or Italian one seems the most likely candidate, which does not seem unlikely, since Austria lies in between these 2 countries.
