### ISSUE TITLE
XBB.1.5 with ORF1a:L681F (nsp2_L501F), ORF3a:A103T, ORF7a:S36P, ORF1a:E1413D (nsp5_E595D), ORF1b:A2132V (nsp15_A81V) and S:F490P (3 seqs, South Korea)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#372]
**Defining Mutations:** [XBB.1.5's T17124C > T23018C] > C2306T(ORF1a:L681F) > G25699A(ORF3a:A103T) > C7321T, T10600C > A17892G > T27499C(ORF7a:S36P) > G4504T(ORF1a:E1413D) > C19862T(ORF1b:A2132V) > C28969T > T23030C(S:F490P over existing S:F490S/T23031C)
**Query:** T23030C, C28969T, C19862T
**Earliest seq:** 2023-06-03 (EPI_ISL_17834630, South Korea)
**Latest seq:** 2023-06-15 (EPI_ISL_17969966, South Korea)
**Sampled Countries:** South Korea (3)

<details><summary>Genomes: </summary>
EPI_ISL_17834630, EPI_ISL_17932556, EPI_ISL_17969966
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_29ea9_a871d0.json?f_userOrOld=uploaded%20sample

view from XBB.1.5's T17124C polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/018147de-3eba-440f-879e-e665a17ae302)

details under ORF1a:L681F branch, yellow box are mutations similar to #366
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ee95fb2c-c843-4c8f-8d27-26ace5cc19d8)

**Trivia:**
- The parent ORF1a:L681F branch is more interesting than the proposal itself, having so many similarities with issue #366, could this be a recombinant of XBB.1.5* and XBB.1.16*? Or simply too homoplastic?
- Query: T17124C, C2306T, G27915T, -T10204C with XBB.1.5 lineage filter roughly catches this branch, about 114 seqs out of 623 seqs caught since May 1st. Most recent seqs are coming from South Korea and the USA.

**Comment by FedeGueli** [comment]
No new sequence closing htis one
