### ISSUE TITLE
FL.40 (XBB.1.9.1+ Orf1a_I3758V)  with ORF1a:L3116F (nsp4_L353F), ORF1b:T577A (nsp12_T586A), S:T19L and S:T478R (22 seqs, 4 countries, many with foreign travel history)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#377]
**Defining Mutations:** XBB.1.9.1 > A11537G(ORF1a:I3758V) > C27684T > C1912T, C9611T(ORF1a:L3116F), A15196G(ORF1b:T577A), A21617C(S:T19L _on top of existing S:T19I/C21618T_), C22995G(S:T478R _on top of existing S:T478K/C22995A_)
**Query:** C22995G, A15196G, A21617C
**Earliest seq:** 2023-04-17 (EPI_ISL_17818160, Yamalo-Nenets, Russia)
**Latest seq:** 2023-06-03 (EPI_ISL_17879194, Saint Petersburg, Russia)
**Sampled Countries:** Russia (10), China (1, Shanghai), Canada (1, Nova Scotia)

<details><summary>Genomes: </summary>
EPI_ISL_17618334, EPI_ISL_17634778, EPI_ISL_17716496, EPI_ISL_17818160, EPI_ISL_17818250, EPI_ISL_17818340, EPI_ISL_17831501, EPI_ISL_17831512, EPI_ISL_17831518, EPI_ISL_17831521, EPI_ISL_17831537, EPI_ISL_17879194
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13159_adce20.json?f_userOrOld=uploaded%20sample&showBranchLabels=all

view from XBB.1.9.1 polytomy with filter of codon 19, 478 of S gene
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f6065f5c-b52e-4486-afda-fb5a00e8f6a2)

details on ORF1a:I3758V branch, with interesting sibing to this mini-saltation
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2468a035-1470-4a1a-bd64-76dca3fb07d0)

**Trivia:**
- Sibling branch (T25150C, T29092C) to this mini saltation is quite interesting too, not only attempting to get S:F490P multiple times, but there's one sub-branch with S:Y200C also, probably a recombinant with XBB.1.22.1 involved.
- Most seqs from parent ORF1a:I3758V branch comes from Russia, with 5-8% local prevalence, but too little (and maybe a little bit delayed) seqs to confirm this.
![intl](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/272ee15d-c54f-4bf6-9890-76b2356e70dc)

**Comment by FedeGueli** [comment]
Although it is not represented in the Gisaid database these last findings suggest it is widespread in many undersampled area.
I suggest to propose it clarifying very well why we are proposing it and which countries has been sampled or imported from. thank you.

**Comment by FedeGueli** [comment]
Propose it-

**Comment by FedeGueli** [comment]
parental lineage with Orf1a_I3758V designated FL.40
