### ISSUE TITLE
XBB.1.5(S:T883i) with S:L517i, S:E554V, S:V642G (11 seqs, Dominican Republic, Spain)

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#379]
GISAID Query: Spike_l517i, spike_e554v ( or A3063C, A23223T thx to the tree published by @nkrmnzr

Earliest sequence: June 9 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f70a_b1d160.json

![Screenshot_20230709_155413_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/fe64c38e-0d4c-4728-ad6c-ca377965e7f0)

Discussion: 
Not used to seeing that many mutations on that side of the spike on XBB, and this one appears to make a reasonable portion of the sequences in Dominican Republic, even though they have some very fit lineages there.   
Additionally, one of the 10 sequences has S:556K.
Waiting to see if it spreads to other countries.   

Parental of #503

**Comment by FedeGueli** [comment]
last one came from Spain

**Comment by FedeGueli** [comment]
clsoing this one.
