### ISSUE TITLE
XBB.1* Sublineage with S:L335S, S:R403K, S:S486P, ORF1a:T403I, ORF1b:S2212I (11 seq, 4 continents, May 16, 1 seq from Republic of Congo,Brazzaville)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#38]
### **Description**
**Sub-lineage of:** XBB.1* (Possibly XBB.1.28, but I'm not certain)
**Earliest sequence:** 2023-3-27, France — EPI_ISL_17480623
**Most recent sequence:** 2023-4-24, France
**Countries circulating:** France (2), China (1), USA (1)
**Number of Sequences:** 4
**GISAID AA Query:** Spike_L335S, Spike_F486P, Spike_R403K
**GISAID Nucleotide Query:** G22770A, T22566C, T23018C
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of XBB.1:**
**Spike:** L335S, R403K, S486P
**ORF1a:** T403I (NSP2_T223I)
**ORF1b:** S2212I (NSP15_S161I)
**Nucleotide:** C1473T, G20102T, G22770A, T22566C, T23018C

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1_L335S_R403K_S486P_4seq.json  
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33738461/236979137-65024cd5-2181-45c8-a524-9dd4dc8dd912.png">

 
**Evidence**
There are only four sequences at this point, but they are spread across three continents, with sequences from China, USA, and France. Short description of additional mutations on each sub-branch:
 
• USA sequence—S:G476S, ORF1b:V1402I (NSP13_V479I) + synonymous nuc mutations G12331A, C17850T, C25276T, and C29416G
 
• France sequence 1 — synonymous nuc mutations G12331A, C17850T, C25276T, and C29416G
 
• France sequence 2—ORF6:L35H, ORF1a:R24C, ORF1a:A117T, ORF1a:E1293D, ORF1a:P1497T
 
• China sequence—S:K478R, ORF1a:L397F, ORF1b:I829V, ORF1b:Y1200H plus synonymous nuc mutations C17850T, C25276T, and C29416G

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17480623, EPI_ISL_17593232, EPI_ISL_17615418, EPI_ISL_17618380
</details>

**Comment by krosa1910** [comment]
If the sequences each have very distinct mutations， could that simply be a layout of distinct branches instead of sharing a common ancestor？

**Comment by ryhisner** [comment]
@krosa1910, I think the likelihood of ORF1a:T403I, ORF1b:S2212S, S:L335S, and S:R403K all appearing together independently in different XBB.1* sequences is vanishingly small. ORF1b:S2212I has only been in 138 other sequences over the past 6 months, and S:L335S is even rarer, only occurring 30 times over the past 6 months.

**Comment by ryhisner** [comment]
After three sequences were uploaded today, this one is up to eight sequences. There has now been one sequence from England (poor coverage w/ artifactual reversions) and sequences from three US states (New York, Pennsylvania, New Jersey). All three US sequences also have S:G476S. 
<img width="1455" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/247f2d4b-e092-47d5-bba5-f15d57e8718e">

**Comment by FedeGueli** [comment]
I think this could be transferred to the main pango proposals github page due:
1) convergent mutations
2) diversity shown with a tendency to accumulate more rbd mutations some already known to confer some potential advantage
3) quite wide geographical spread.

@ryhisner please fix you the timing for transfer (do you want to wait it reaches 10,15,20 seqs? )

**Comment by ryhisner** [comment]
@FedeGueli, given how geographically widespread this one is, I'd say it's worth transferring to the main page when it reaches 10 sequences. I don't know exactly how to transfer it to the main page, however.

**Comment by FedeGueli** [comment]
> @FedeGueli, given how geographically widespread this one is, I'd say it's worth transferring to the main page when it reaches 10 sequences. I don't know exactly how to transfer it to the main page, however.

@ryhisner just copy and paste redoing the tree (only time absorbing thing but necessary to give an up to date tree to the proposal. Thank you!

Now Usher clearly branches it under the XBB.1.28 tree so this is XBB.1.28 

![Schermata 2023-05-14 alle 11 20 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7b9e6cff-c659-406c-9ab8-8a8413c08aab)

It has to be noticed that two seqs further acquired S:T478R
![Schermata 2023-05-14 alle 11 21 50](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0f8e2dd3-c56e-4668-bb4d-1c6ff48115ce)

**Comment by FedeGueli** [comment]
This went to 10 with two new samples coming in from France and England .
@ryhisner i urge you to re propose it in the main Pango page.

**Comment by HynnSpylor** [comment]
One more seq from Congo

**Comment by FedeGueli** [comment]
> One more seq from Congo. 4 continents now

good catch did u fiond it with the alternative query: C1473T, G20102T  , T22566C ?

**Comment by FedeGueli** [comment]
Proposed here: https://github.com/cov-lineages/pango-designation/issues/1997
