### ISSUE TITLE
Still circulating CM.10+S:A688V (38 seqs, 6 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#382]
CM.10+A20355G,C7765T+C23625T(S:A688V)

GISAID query: C23625T,A20355G,C7765T
No. of seqs: 36(Germany 1 Japan 3 New Zealand 1 Philippines 4 South Korea 1 Indonesia 26)

First: EPI_ISL_17859261, Philippines, 2022-11-12
Latest:EPI_ISL_17835849, Indonesia, 2023-5-28

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_290b6_bff720.json?label=id:node_7175975)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e71d8893-e698-4623-88ca-65e42244c3e6)

**Comment by FedeGueli** [comment]
noticed this one too CM.10 (S:478T) had a good resilience in the las months but worth highlighting no sequence of this one in June and also no BA.2.3.20 in the little batch from Philippines uploaded today.

**Comment by aviczhl2** [comment]
> noticed this one too CM.10 (S:478T) had a good resilience in the las months but worth highlighting no sequence of this one in June and also no BA.2.3.20 in the little batch from Philippines uploaded today.

It is mainly circulating in Indonesia now, and Indonesia only uploads 2 seqs collected in June.

**Comment by FedeGueli** [comment]
> > noticed this one too CM.10 (S:478T) had a good resilience in the las months but worth highlighting no sequence of this one in June and also no BA.2.3.20 in the little batch from Philippines uploaded today.
> 
> It is mainly circulating in Indonesia now, and up to now Indonesia only uploads 2 seqs collected in June.

yes still if something circulates to certain levels there then we see in Singapore very soon.

**Comment by FedeGueli** [comment]
It likely didnt make it through EG.5.1 Era
