### ISSUE TITLE
HN.3 with S:253G (54) and 9 with S:P621S

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#383]
_Original proposal now designated HN.3; please skip below to see its sublineage proposed_

***************************************************
**_Original Proposal:_**
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/2e41d1ac-95a5-4bce-8001-52b57f7cd698)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_155ee_c1cd40.json?c=gt-S_494&f_userOrOld=uploaded%20sample
EPI_ISL_17955845 EPI_ISL_17955806 EPI_ISL_17955780
first seq: 2023-06-12
most recent: 2023-06-16
gisaid query: T23042C, G20060T, C22995G (edited : @fearuncle on Gisaid you have to use the WT as start so it is C22995 not A22995)
On https://cov-spectrum.org/collections/177 it will be the first level 6 lineage
**This has been designated HN.3**

********************
**New proposal**:

HN.3>  **ORF1a:G345C** (G1298T) > **S:D253G** (A22320G) 

Gisaid query: **G1298T,A22320G,T23042C**

Tree:
![Schermata 2023-10-17 alle 11 25 11](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a424d52a-68af-4fbb-b4bb-b2f68f34dd4d)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38d01_e52310.json?label=id:node_3393054

Countries : 4

Samples: 46
EPI_ISL_18104484, EPI_ISL_18162736, EPI_ISL_18165599,
EPI_ISL_18261311, EPI_ISL_18261351, EPI_ISL_18265077,
EPI_ISL_18278033, EPI_ISL_18281903, EPI_ISL_18282698,
EPI_ISL_18305109, EPI_ISL_18305602, EPI_ISL_18306310-18306311,
EPI_ISL_18308830, EPI_ISL_18309796, EPI_ISL_18316947,
EPI_ISL_18317279, EPI_ISL_18322589, EPI_ISL_18322598,
EPI_ISL_18333191, EPI_ISL_18333239, EPI_ISL_18333261,
EPI_ISL_18333595, EPI_ISL_18333602, EPI_ISL_18333649,
EPI_ISL_18339157-18339158, EPI_ISL_18340012, EPI_ISL_18340288,
EPI_ISL_18340402, EPI_ISL_18344517, EPI_ISL_18358312,
EPI_ISL_18358429, EPI_ISL_18359241, EPI_ISL_18361082,
EPI_ISL_18363844, EPI_ISL_18363959, EPI_ISL_18368449,
EPI_ISL_18368696, EPI_ISL_18369429, EPI_ISL_18369666,
EPI_ISL_18372322, EPI_ISL_18379561, EPI_ISL_18384102,
EPI_ISL_18384890, EPI_ISL_18389064

**Comment by FedeGueli** [comment]
still 3

**Comment by Fearuncle** [comment]
there is a lineage of fl.1.5.1 with s:554k

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/fab18f73-8419-4470-a056-08d285e2c3a0)

**Comment by FedeGueli** [comment]
2 samples from airport surveillance with travel history from Rep.Dominicana

**Comment by plomano** [comment]
456L, 478R, 494P is quite the combo. This one seems like it could have horsepower. In terms of pure immune evasion it would likely surpass 455F/456L/478R.

**Comment by FedeGueli** [comment]
growth tracking: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T23042C%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&

**Comment by Fearuncle** [comment]
new branch with s:253G 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/e0015f24-656b-4b04-87d9-09006b57e1e5)

**Comment by FedeGueli** [comment]
Tracker:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T23042C%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Please propose it including the growth advantage tracker i posted above.

**Comment by Fearuncle** [comment]
reopening this issue due to the low number of sequences and there is sequence with S:P621S

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T23042C%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@Fearuncle when you change the title of the proposal you should update the proposal to be the same , otherwise it becomes a mess. i spotted that it is not updated and now i m editing to follow the headline.
