### ISSUE TITLE
EG.5.1 with s:K458R in hawaii (6 seqs)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#384]
Combination 456L and a mutation at 458 is interesting. In the curious case of ba.1.23, which is thought to be originated from transmission between immunocomprised patients, 458M preceded 455W, then 458M was swapped out for 456L, and then returned in one longterm patient after 100 days resulting in W455 L456 M458. Now in this case it is 458R, but my personal theory is that these residues are very interlinked. Example if you look at how many F455 L456 is rising up in example dv.7.1, a non xbb lineage. And some rarer W455 L456 popping up in eg.5.1, but its to be seen how effective that is. See #295 

Query: C19524T, A22935G, G21718T

Anyways, here is the usher tree, it seems to split off from a regular C19542T branch of eg
5.1:
![Screenshot_20230710_164709_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/00ed3eff-b3cc-4613-bad5-38034809be50)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4e9e6_c18fd0.json

**Comment by FedeGueli** [comment]
closing this one for the moment.
