### ISSUE TITLE
Very recent CH.1.1.11 sublineage with S:L212S and S:R408N circulating in Australian Capital Territory (12)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#386]
i was monitoring for a while this sublineage cause S:L212S was one of the last mutations popping up in BA.2 before being replaced by BA.4/5 and it was clearly beneficial.
But now it is clear there is a sublineage with multiple AA changes acquired one after the other that is now circulating in Act Australia, so worth monitoring it here.
CH.1.1.11 tree:
![Schermata 2023-07-10 alle 23 37 51](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/600b7b26-64b5-40ce-8b2c-274bbbd75186)

The lineage here proposed popped up in an undesignated CH.1.1.11 branch with Orf1a:N4315H
![Schermata 2023-07-10 alle 23 36 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a74cb599-1993-40e6-a008-2e5cafebe272)
then gained S:L212S and orf1b:R2613H
![Schermata 2023-07-10 alle 23 38 34](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/aa6cf222-7f58-464a-8854-2fd2f48e73c2)
then Orf1a:H13R and then Orf1a:P1921L, Orf1a:Q2840R, S:R408N and ORF7a:T28I
![Schermata 2023-07-10 alle 23 41 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/641992de-92f9-4674-bf8a-2fb089b0b159)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_2caf7_c71d10.json?c=gt-S_212&label=id:node_7335250

Defining mutations:
CH.1.1.11 >> > **Orf1a:N4315H** (A13208C= NSP10_N62H) > C10507T, T17136C, **Orf1b:R2613H** (G21305A = NSP16_R216H) , **S:L212S** (T22197C), A23899G > **Orf1a:H13R** (A303G = NSP3_H13R)) > Orf1a:P1921L (C6027T = NSP3_P1103L) , Orf1a:Q2840R (A8784G = NSp4_Q77R), S:R408N (G22785A), Orf7a:T28I (C27476T) 

Gisaid Query: A8784G,C6027T,G21305A

Samples: 9
first:
hCoV-19/Australia/NSW-ICPMR-45440/2023 | Original | EPI_ISL_17561597 | 2023-04-19
Last:
hCoV-19/Australia/ACT12377/2023 | Original | EPI_ISL_17975439 | 2023-06-28

**Comment by Mydtlwn** [comment]
There seems to be some mistake in the title

**Comment by FedeGueli** [comment]
thx

**Comment by krosa1910** [comment]
I think this indicate some convergence to XBC( or whatever BA.2 parent of it)?
![191961561-f7e923a6-8663-477f-aa68-e6e67c064890](https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/7a4e07c6-7c3b-482f-835d-8049b13dfdc4)

Australia is the home of XBC, which happened to acquire S: P209L, L212S, D215H in its recombination. I also used to search S:212S in other lineages, although my interest was in XBB*.

**Comment by FedeGueli** [comment]
Sampled also in WA

**Comment by FedeGueli** [comment]
closing it,
