### ISSUE TITLE
FL.5 sublineage with defining BA.2 Orf1a:S135R mutated to Orf1a:R135K apparently faster than parental lineage- 105 seqs

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#39]
I would highlight that a sublineage of FL.5 has a mutation in one of longstanding BA.2 defining mutations outside the spike, it got **S:R135K** with a 2nd nuc mutation after the first: T670G then G669A ,

While we (cc  @c19850727 and @JosetteSchoenma ) noticed for a while that first BA.1/BA.2 recombinants tended to remove the first part of Orf1a from BA.2 and there were one of the first big likely but unproven recombinant BA.2.23 that had it reverted to S

it is the first time i notice such a big sublineage with a mutation there since BA.2/4/5 dominance

And interestingly it seems to be faster than parental lineages (FL.5 and FL.5+A29020G):
![Schermata 2023-05-09 alle 11 00 07](https://user-images.githubusercontent.com/87669813/237047491-70a9c778-cf3a-48e2-bc16-b6a0d13a0db8.png)
![Schermata 2023-05-09 alle 11 00 28](https://user-images.githubusercontent.com/87669813/237047599-366d5c43-168a-43c2-b376-d712adf37438.png)

The trend in accumulating more rapidly sequences seems clear when it has this kind of shape and covspectrum estimates it between 10-30%

Tree
![Schermata 2023-05-09 alle 10 55 08](https://user-images.githubusercontent.com/87669813/237046193-4efd2808-0cd8-4a86-a0e8-6ee048cf548f.png)
![Schermata 2023-05-09 alle 10 54 27](https://user-images.githubusercontent.com/87669813/237046011-79676bd9-3662-4d12-aceb-c3b2138adfe7.png)
![Schermata 2023-05-09 alle 10 55 36](https://user-images.githubusercontent.com/87669813/237046284-99f9245c-6695-48ba-94d0-8e6be6879ea3.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice19_genome_321f5_88f7d0.json?label=id:node_5879591

Gisaid query: G669A ,T670G, C29358T,A29020G got just 83 samples , maybe for the 2 nuc mutation??

**Comment by AnonymousUserUse** [comment]
@FedeGueli Could you please use small letters for the label, e.g. non-spike mutations or Non-spike mutations? In order to be consistent with other labels and have a better overview.

**Comment by FedeGueli** [comment]
Usher now shows 105 sequences while my query finds just 92

![Schermata 2023-05-17 alle 20 57 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/724a8387-43f0-4cf5-844c-bce1e0d6eda2)
T670G

**Comment by FedeGueli** [comment]
100 seqs with G669A ,T670G, C29358T,A29020G.

Interesting but slow closing this for now.
