### ISSUE TITLE
EG.5.1 got S:F157L and growing rapidly (26 seqs - 8 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#394]
I want to thank @krosa1910 who turned the spotlight on S:F157 again L in #274 .
I independently found a very recent EG.5.1 sublineage with S:F157L looking at GBW sequences on Gisaid ( US airport surveillance sequences)

Tree:
![Schermata 2023-07-12 alle 01 26 48](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/efba5ebd-8df6-457d-936a-7094f24c7e52)
![Schermata 2023-07-12 alle 01 27 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d858e756-de3b-46d7-b60a-2d9ac2cc1f3f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_283eb_de3bd0.json?label=id:node_6677659

Defining mutations:
EG.5.1 >> > Orf1a:S1857L (C5835T), S:F157L (C22033A) 

Gisaid query: C22033A,C5835T,G21718T,A18492G

Samples: 18
First: 
hCoV-19/England/PHEC-YYE4TUM/2023 | Original | EPI_ISL_17803964 | 2023-05-27
Last: hCoV-19/USA/FL-CDC-LC1045195/2023 | Original | EPI_ISL_17979092 | 2023-06-21

IDs: EPI_ISL_17803964, EPI_ISL_17818492, EPI_ISL_17838394,
EPI_ISL_17885526, EPI_ISL_17885589, EPI_ISL_17926207,
EPI_ISL_17949508, EPI_ISL_17951685, EPI_ISL_17952407,
EPI_ISL_17952448, EPI_ISL_17956602, EPI_ISL_17960141,
EPI_ISL_17971804, EPI_ISL_17971842, EPI_ISL_17972327,
EPI_ISL_17974744, EPI_ISL_17975303, EPI_ISL_17979092,

Countries: 6 
![Schermata 2023-07-12 alle 01 32 02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7ce78fa2-ec37-4fca-b8e2-f71b6f7d34a4)

**Comment by FedeGueli** [comment]
Ping @corneliusroemer i suggest direct designation of this one.

**Comment by krosa1910** [comment]
Would make a lot of sense for this to be fast. It is EG.5.1, and S:157L is the only BA.2.75* early mutation (that XBB* did not got due to it recom nature) that both showed up multiple times and seemed to show significant growth among XBB*.
<img width="908" alt="061D7D5C-AFBF-4619-8BE5-5D9518265D8E" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/45791d8d-c46d-46a3-a34a-e3506227cf96">

**Comment by FedeGueli** [comment]
One of the three new sequences came from a traveller from Italy

**Comment by FedeGueli** [comment]
ping @corneliusroemer

**Comment by FedeGueli** [comment]
Designated EG.5.1.6 from https://github.com/cov-lineages/pango-designation/commit/a65b3221da89eca922fc3ea3e1941c2b7d01f83b

**Comment by AngieHinrichs** [comment]
Thanks @FedeGueli!  Next time perhaps you can just add the milestone, and then let @aviczhl2 run the automated milestone update, and then you won't need to do the manual edit & pull request?
