### ISSUE TITLE
XBB.1.5+Orf1a:P2287S+S:N185D(16 seqs, Canada) and its potential recombinant with GK.1 (9 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#396]
XBB.1.5+C4586T,T16974C,C7124T(Orf1a:P2287S),A22115G(S:N185D)

GISAID query: T16974C,A22115G,-C23673T
No. of seqs: 16(Canada)
First: EPI_ISL_17590678, 2023-4-17
Latest: EPI_ISL_17701147, 2023-5-10

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f152_e51990.json?c=gt-S_185&label=id:node_6926286&showBranchLabels=all)

Most samples gets S:S940F additionally.

![屏幕截图 2023-07-12 152110](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f5f0bdc8-4097-4525-8e23-c00f2db32c69)

GK.1+T16974C,A22115G(S:N185D)

GISAID query: T16974C,A22115G,C23673T

No. of seqs: 9(Dominician Rep 1 France 2 Spain 2 Brazil 1 Canada 3)
First: EPI_ISL_17948645, Spain, 2023-5-17
Latest: EPI_ISL_17976067, Dominician Rep, 2023-6-27

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_23b5d_e49c60.json?branchLabel=Spike%20mutations&label=id:node_6921738&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6a562773-ddd9-4e0b-9bea-795942c1ae4a)

I suppose it is a recombinant, because they have the common T16974C, which is rare with S:N185D samples(only appears in these 2 lineages).  Also both GK.1 and the proposed XBB.1.5 branch don't have additional mutations between 16974 and 22115, so it's possible to be a recombinant. 

Also its pattern satisfies a pattern that it emerges in some undersampled areas, and outputs early the weak version of XBB.1.5+S:N185D to Canada only and lately the powerful recombinant (S:185D, with additional S:455,456,704 from GK.1) to multiple countries.

Breakpoint shall be between 12468 and 16973, and breakpoint 2 between 22116 and 22623, as GK.1 has G12467T and C22624T.

**Comment by FedeGueli** [comment]
Good catch i think it is a legit recombinant. 
![Schermata 2023-07-12 alle 13 13 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b50aff30-65a6-4919-8ef3-d9ba14fc4197)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=T16974C%2CA22115G%2CC23673T&nucMutations1=T16974C%2CA22115G%2CC23673C&nextcladePangoLineage2=GK.1*&nextcladePangoLineage3=XBB.1.5*&analysisMode=CompareEquals&

**Comment by FedeGueli** [comment]
Ping @corneliusroemer

**Comment by oobb45729** [comment]
ORF1a:P2287S is also in Delta(21J) and Lambda.

**Comment by FedeGueli** [comment]
> ORF1a:P2287S is also in Delta(21J) and Lambda.

That corresponds to NSP3_P1469S
Moderately beneficial in the Bloom/Neher calculator.
![Schermata 2023-07-12 alle 23 35 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c171b413-3c27-48e1-973a-821ba74155be)

**Comment by aviczhl2** [comment]
I'll propose it in main thread.

**Comment by FedeGueli** [comment]
GK.1.2 https://github.com/cov-lineages/pango-designation/commit/7afb37ca3526a5b03b8cfb64f4e748c4b3cc2fbb
