### ISSUE TITLE
XBB.1.16/XBC.1.3 Recombinant, Australia (3 seq, July 12)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#400]
### **Description**
**Sub-lineage of:** XBB.1.16/XBC.1.3 Recombinant
**Earliest sequence:** 2023-6-13, EPI_ISL_17975402
**Most recent sequence:** 2023-7-4, EPI_ISL_17975448
**Countries circulating:** Australia (3) — Australian Capital Territory (2), New South Wales (1)
**Number of Sequences:** 3
**GISAID AA Query:** Not possible
**GISAID Nucleotide Query:** A27898C, G28378A, A28447G
**CovSpectrum Query:** [3-of: A27898C, G28378A, A28447G]
**Breakpoints:**
First Breakpoint: 5584-6195
Second Breakpoint: 27898-28247

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBC.1.6_XBB.1.16_Recombinant.json?c=gt-nuc_28447&label=id:node_5181426
<img width="1374" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/35238d6f-303a-450e-af3b-06e7f9a9406b">

**Evidence**
This sandwich recombinant takes the first part of ORF1a, the last part of ORF8, and all of N/ORF9b from XBB.1.16* and the rest of the genome from XBC.1.6*. It also possesses ORF9b:R32H (G28378A), which is only found in 13 XBB.1.16* sequences. However, these 13 sequences are scattered about the Usher tree, and none are from Australia, so it's difficult to find the exact source of the XBB.1.16* portion of this recombinant.
 
The two genes in which I believe many XBB* lineages have a large advantage over XBC* lineages are
N and ORF9b. In N, XBB*, like every other non-Deltacron lineage, has the triple-nucleotide mutation of N:R203K, G204R. This creates a novel TRS that has been confirmed to create a new protein called N*, which enhances innate immune evasion. It was found to cause increased viral loads and greater disease severity in an early study published in Nature. [ https://www.nature.com/articles/s41467-022-28287-8](https://www.nature.com/articles/s41467-022-28287-8)
<img width="1420" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/59e7bf32-fe06-49f3-9a91-cd3f0fbd0eac">
 
This recombinant also picks up the three-AA deletion in N that's been near-universal since Omicron's emergence—N:30-32del.
<img width="836" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2f4dfcb7-2339-4872-9fc8-017cf5c9d846">
 
XBB.1.16* has ORF9b:I5T, which has conferred a clear growth advantage in numerous lineages over the past two years, as well as ORF9b:N55S, whose effect is less clear.
<img width="1508" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1249fd27-37e9-4dba-a3ef-358c369c8d04">
 
I suspect XBC's best chance at staying alive on the global scene in the face of competition from the various XBB + S486P lineages is to purloin N/ORF9b through recombination, and this has now happened several times in Australia. I believe this is the first such recombinant to have more than two sequences, but I expect we'll see others before long.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17924212, EPI_ISL_17975402, EPI_ISL_17975448
</details>

**Comment by FedeGueli** [comment]
Hi @ryhisner all of the sudden XBC.1.3 seems to have get high prevalences in NZL, WA and also a good 5% overall in Australia in July ( taking it with all the caveats of the batch uploading of certain Australian states) . So the recombination event coul be easily expalin if it there were a surge of prevalence locally with XBB.1.16 being imported from abroad.

**Comment by FedeGueli** [comment]
I make this dormient until something new will pop up

**Comment by FedeGueli** [comment]
Sorry i have cosed this one too early! now Josette re analyzed it again and proposed it  in #992
