### ISSUE TITLE
XBB.1.5 Sublineage with S:V36I, S:P272H, S:Q836K, N:I292T, ORF1b:M2322I (Puerto Rico, USA, Uk, 45 seq, Sept 9)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#403]
### **Description**
**Sub-lineage of:** XBB.1.5
**Earliest sequence:** 2023-4-21, Puerto Rico, EPI_ISL_17700246
**Most recent sequence:** 2023-6-27, USA, Florida, EPI_ISL_17979245
**Countries circulating:** Puerto Rico (16), USA (9)
**Number of Sequences:** 25
**GISAID AA Query:** Spike_V36I, Spike_P272H, N_I292T
**GISAID Nucleotide Query:** G21668A, C22377A, T29148C
**CovSpectrum Query:** Nextcladepangolineage: XBB.1.5* & [3-of: G20433A, G21668A, C22377A, C24068A, T29148C]
**Substitutions on top of XBB.1.5:**
**Spike:** V36I, P272H, Q836K
**N:** I292T
**ORF1b:** M2322I
**Nucleotide:** G20433A, G21668A, C22377A, C24068A, T29148C
 
**Phylogenetic Order of Mutations:** G21668A (S:V36I) **→** C24068A (S:Q836K) **→** G20433A (ORF1b:M2322I), T29148C (N:I292T) **→** C22377A (S:P272H)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5_V36I_P272H_Q836K__N-I292T__ORF1b-M2322I.json
 
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/25c71110-be76-4cef-80a7-0d6d16fa377f">

**Evidence**
An earlier study found S:P272L to be a T-cell-escape mutation, so it seems likely S:P272H is one as well. S:Q836K is in an interesting region of S2 and seems likely to be consequential in some way. https://www.cell.com/cell/pdf/S0092-8674(22)00849-2.pdf

This lineage makes up about 2% of sequences from Puerto Rico collected since May 15, and has been detected in five US states (Connecticut, Florida, Mississippi, New Jersey, New York).
 
XBB.1.5 seems like a dying lineage, so this one will probably die with it, but it seems worth noting nonetheless.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17700246, EPI_ISL_17700255, EPI_ISL_17700262, EPI_ISL_17810315, EPI_ISL_17821251, EPI_ISL_17830891, EPI_ISL_17830947, EPI_ISL_17830953, EPI_ISL_17830956, EPI_ISL_17831082, EPI_ISL_17853080, EPI_ISL_17853153, EPI_ISL_17853307, EPI_ISL_17856365, EPI_ISL_17885206, EPI_ISL_17885222, EPI_ISL_17885226, EPI_ISL_17953730, EPI_ISL_17955545, EPI_ISL_17965558, EPI_ISL_17965563, EPI_ISL_17965596, EPI_ISL_17965601, EPI_ISL_17979117, EPI_ISL_17979245
</details>

**Comment by FedeGueli** [comment]
it seems expanding again after a slight slowdown. better to keep this tracked

**Comment by FedeGueli** [comment]
Also samples from July so ongoing circulation.

**Comment by FedeGueli** [comment]
Only 3 samples from August closing it
