### ISSUE TITLE
Some branches under XBB.1.5+Orf8:Q18* (S:1101Y:157 seqs, S:307I, 201 seqs, S:1078S, 185 seqs, S:157L, 36 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#404]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/cd470dc7-bdca-4f98-8935-ba07abe7b7f1)
I find XBB.1.5+Orf8:Q18* has a steady growth advantage against XBB.1.5, which is quite interesting as this mutation seems useless after G8*. It has 1800+seqs so the result seems valid.

However it is highly convergent and appears on various XBB* branches so will cause trouble if designated directly.

I check the branch (XBB.1.5 with T17124C but not T10204C)+Orf8:Q18*(C27945T) and find some interesting large sub-branches.

Branch 1:
XBB.1.5+Orf8:Q18*+C17550T+T378C(Orf1a:V38A)+C24863T(S:H1101Y)

GISAID query: C17550T,T378C,C24863T,C27945T
No. of seqs: 148(Japan, South Korea,USA)
First: EPI_ISL_17373762, South Korea, 2023-3-12
Latest: EPI_ISL_17969486, South Korea, 2023-6-16

Branch 2:
XBB.1.5+Orf8:Q18*+C3876T(Orf1a:A1204V)+C22482T(S:T307I)

GISAID query:C3876T,C22482T,C27945T
No. of seqs: 190(Australia, Canada, Chile, Israel, USA,Germany)
First:EPI_ISL_16414033, 2022-12-26, Chile
Latest: EPI_ISL_17971906, 2023-6-28, USA from Germany

Branch 3:
XBB.1.5+Orf8:Q18*+G24794T(S:1078S)

GISAID query: G24794T,C27945T,T17124C
No. of seqs: 176(South Korea, USA, Belgium)
First: EPI_ISL_16849523, 2022-12-24, USA
Latest: EPI_ISL_17956587, 2023-6-13, USA

Branch 4:
XBB.1.5+Orf8:Q18*+C17550T+C11580A(Orf1a:T3772N, NSP6 T183N)+ G13958A(Orf1b:R164H), S:F157L(C22033A)

GISAID query: C22033A,G13958A,C27945T
No. of seqs: 29(South Korea)
First: EPI_ISL_17691281, 2023-4-28
Latest: EPI_ISL_17969849, 2023-6-15

The whole picture looks like this.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice66_genome_23b5d_e49d90.json?c=gt-S_157,1101,307,1078)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/156779ba-13fe-4269-9454-883490bdb3ca)

**Comment by aviczhl2** [comment]
The S:157L branch is detected in Japan, outside SK.

**Comment by FedeGueli** [comment]
They seem all quite slow, but still  interesting to keep track of them

**Comment by FedeGueli** [comment]
I think the only one worth monitoring is branch 4. So i m closing this one as a whole but if branch 4 reaches 50 please repropose it or ping me to reedit the issue and opening it again.
