### ISSUE TITLE
FR.1+7-nuc/7-aa saltation in China(10 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#405]
FR.1+C16175A, G942A, C1223T, C2040T, C10277T, C28312T, C29268T

Orf1a: R226K, L320F, T592I, L3338F
Orf1b: T903N
N:T332I
Orf9b: P10F

GISAID query:  G942A, C1223T, C2040T
No. of seqs: 10, Fujian, China
First: EPI_ISL_17802004, 2023-6-3
Latest: EPI_ISL_17850162, 2023-6-5
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_e565_fa8750.json?label=id:node_3142238)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3dfd4611-0f8c-4302-92fa-a7a0abe8ec3a)

**Comment by FedeGueli** [comment]
Interesting to see how the orf9b mutations of BQ works on the BN backbone , after popping up multiple times in the xbb tree.

**Comment by aviczhl2** [comment]
No further seqs.

**Comment by FedeGueli** [comment]
> No further seqs.

Thx
