### ISSUE TITLE
XBB.1.5 / BQ.1.24 recombinant in South Korea  (14)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#409]
There is a  new recombinant between XBB.1.5 and  BQ.1 i found in South Korea. It took everything from E ahead from BQ.1 the rest is XBB.1.5 

I have no time to go in depth in this moment
but main points here:
BP: between 23403-25416
Private mutations: G960A (**Orf1a:R232H**), C8140T, T10204C, T12340C,T14799CC17156T= **Orf1b: T1230I**,G27666T = **Orf7a:E91D**
 
Tree:
![Schermata 2023-07-14 alle 11 44 21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e089864f-cc64-4454-a213-aeaf8c27ef3c)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_26f7d_10efc0.json?c=gt-ORF7a_91&label=id:node_6832724

Query: C8140T, T10204C, T12340C, G26529A

Samples : 10
First: EPI_ISL_17604457
Last: EPI_ISL_17984468

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c063f11f-1010-4746-96e5-7a90665c6513)

There's a South Korean XBB.1.5 branch with G960A , C8140T, T10204C, T12340C,T14799C, C17156T  

It has 48 seqs. 

So this branch recombines with BQ. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32e4_14c050.json?branchLabel=nuc%20mutations&f_country=SouthKorea&label=id:node_6818824)

**Comment by FedeGueli** [comment]
Thx @aviczhl2 i have seen that the query without m:D3N gave back 50+ sequences. . thx a lot for looking into this.

**Comment by Over-There-Is** [comment]
BQ.1.24+G27666T 693 seq in Korea

**Comment by FedeGueli** [comment]
thx @Over-There-Is changed the title following your findings.

**Comment by FedeGueli** [comment]
last samples from SK and GD

**Comment by Over-There-Is** [comment]
Detected by Shenzhen Customs, but it did not tell where this sequence import from.

**Comment by FedeGueli** [comment]
Thx @Over-There-Is

**Comment by FedeGueli** [comment]
one week and i ll close this.

**Comment by FedeGueli** [comment]
closing it
