### ISSUE TITLE
XBB.2.3+Orf1a:A583V,Orf1a:L3829F, S:478R,S:L8F,S:Y796H, S:V1122L,S:C1243F in England (3 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#411]
XBB.2.3+orf1a:A583V(C2013T),Orf1a:L3829F(C11750T),S:K478R(A22995G)+T11158C,G21586T(S:L8F),T23948C(S:Y796H), G24926T(S:V1122L), G25290T(S:C1243F)

Though it is placed under XBB.2.3.8 and has the XBB.2.3.8 defining Orf1a:L3829F,S:K478R Orf1a:A583V, it lacks C16389T.

Both Orf1a:L3829F,S:K478R are highly convergent and orf1a:A583V is moderately convergent, this lineage may be a side branch instead of a sub-branch of XBB.2.3.8. 

GISAID query: Spike_L8F,Spike_T478R,Spike_C1243F
No. of seqs: 3(England)

EPI_ISL_17813153, 2023-6-2
EPI_ISL_17838174, 2023-6-6
EPI_ISL_17838182, 2023-6-12

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_128e5_19be40.json?label=id:node_3082641)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f333071f-46cc-4d26-bece-9fc0ad2d3a89)

**Comment by FedeGueli** [comment]
Quite puzzling that reversion i looked into it without arriving to any clear conclusion. :
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AC1243F%2CS%3AL8F%2CS%3A478R&nextcladePangoLineage1=XBB.2.3.8*&analysisMode=CompareEquals&
![Schermata 2023-07-23 alle 00 42 09](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8d369cbc-ccea-4476-9da6-7cc5a581761e)

**Comment by aviczhl2** [comment]
> Quite puzzling that reversion i looked into it without arriving to any clear conclusion. :I still suspect a recombination with something but XBB.1.5.12 that has the same nucleotide mut on the donor side (T11158C ) has too mutations around it to be a good candidate, and so other XBB.2.3.8 sublineages never sequenced with that nuc (even if there is a branch opre xbb.2.3.8 that could hint that a homologous recombination theorically could have happened but no sign of it. 

May a saltation after a XBB.2.3.11/XBB.2.3.8 recombination?

**Comment by FedeGueli** [comment]
> > Quite puzzling that reversion i looked into it without arriving to any clear conclusion. :I still suspect a recombination with something but XBB.1.5.12 that has the same nucleotide mut on the donor side (T11158C ) has too mutations around it to be a good candidate, and so other XBB.2.3.8 sublineages never sequenced with that nuc (even if there is a branch opre xbb.2.3.8 that could hint that a homologous recombination theorically could have happened but no sign of it.
> 
> May a saltation after a XBB.2.3.11/XBB.2.3.8 recombination?

Maybe

**Comment by aviczhl2** [comment]
No further seqs.
