### ISSUE TITLE
BQ.1.2.2 with 5 spike mutations(K182E, P251L, V486A, E554K, S494P) 5 seq.

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#412]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/513a3f76-66f0-4671-a456-775f2380d195)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_cc5a_1f7f60.json?c=gt-S_554&label=id:node_8061610
first seq: 2023-06-15
most recent: 2023-06-29
G26951C, C28163A, G19129A, G23222A
EPI_ISL_17971795 EPI_ISL_17971878 EPI_ISL_17971857 EPI_ISL_17851464 EPI_ISL_17851591

**Comment by FedeGueli** [comment]
Already proposed in Pango.
