### ISSUE TITLE
XBB.1.16.7(S:T732I) with Orf1a:Y1090H,Orf1b:K82R,S:Q675H (7 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#413]
XBB.1.16.7+T3533C(Orf1a:Y1090H),T17154C+A13712G(Orf1b:K82R)+G23587C(S:Q675H)

GISAID query: A13712G,G23587C,T3533C
No. of seqs: 4( Laos 1 Xinjiang 1 Jiangsu 1 Taiwan 1)

First: EPI_ISL_17836267, 2023-5-23, Xinjiang
Latest: EPI_ISL_17984639, 2023-6-15, Taiwan

New, convergent and geographically distributed.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_128e5_19be40.json)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f7271490-752a-4b4e-9b68-4c6d2d34efc5)

**Comment by aviczhl2** [comment]
+2 from Guizhou

**Comment by FedeGueli** [comment]
closing it for now
