### ISSUE TITLE
XBB.1.9.1 small saltation with S:K478R, S:A520S and other 2 non-Spike aa mutations (4 seqs in Berlin, Germany)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#417]
Defining mutations: 
XBB.1.9.1>C28846T>G2174A (ORF1a:E637K)>G12071A (ORF1a:D3936N), C20368T, A22995G (S:K478R), G23120T (S:A520S), T25510C (ORF3a:S40P),C28948T
GISAID query: G5720A, C28846T, G2174A, G23120T
Earliest seq: 2023-06-15 (Germany, EPI_ISL_17988384)
Most recent seq: 2023-06-22 (Germany, EPI_ISL_17988381)
Countries detected: Germany (4)

Usher Tree: 
<img width="716" alt="屏幕截图 2023-07-16 014910" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/aa236553-a117-42a5-a0ac-dbd8facd58f9">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3fe5b_2d79b0.json

This branch is neighbored with FL.15 (with S:F456L). As the ID of these samples are neighbored and concentrated in Berlin, I presume that it is a single infection chain. 
 

Genomes:  
EPI_ISL_17988380-17988381, EPI_ISL_17988383-17988384

**Comment by FedeGueli** [comment]
No update closing it.
