### ISSUE TITLE
XBB.1.5.13 with ORF1a:A690V (>500 seq. mainly Chile and USA)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#418]
ORF1a:A690V is in both EG.5 and XBC.1.6. I searched the mutation and found this lineage. It was at about 10% in Chile for a while.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.13*%26ORF1a%3AA690V&
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3725d_304410.json?label=id:node_7041775
USHER put this lineage directly under XBB.1. I don't know what's happening here.

**Comment by FedeGueli** [comment]
It seems a flip flop branch of XBB.1.5 misplaced to XBB.1 cc @angiehinrichs

**Comment by FedeGueli** [comment]
![Schermata 2023-07-18 alle 14 55 29](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e9a86126-99a8-44f7-a66d-e3b0d144f5b0)
found this xbb.1.16 one casually with Orf1a:A690V 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice25_genome_test_984d_62b0e0.json?label=id:node_6629963 maybe you are interested in.

**Comment by FedeGueli** [comment]
> > It seems a flip flop branch of XBB.1.5 misplaced to XBB.1 cc @AngieHinrichs
> 
> Yes, thanks @FedeGueli, I will add that to the list for the next round of fixes.

Thank you!

**Comment by AngieHinrichs** [comment]
In XBB.1.5.13 as it should be in 2023-07-19 tree.

**Comment by FedeGueli** [comment]
please transfer to pango. thank you.
