### ISSUE TITLE
XBB.1.16.18(+Orf1a:G519S) with S:Q675H in China(18 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#421]
XBB.1.16+G27509T(Orf7a:T39I)+G1820A(Orf1a:G519S)+G23587T(S:Q675H)

GISAID query: C27509T,G1820A,G23587T
No. of seqs: 15( Fujian 3 Guangdong 5 Hong Kong 1 Taiwan 1 Shanghai 5)

First seq: EPI_ISL_17584665, Guangdong, 2023-4-19
Latest: EPI_ISL_17956749, Shanghai, 2023-6-21

This is the second XBB.1.16+S:Q675H branch in China. This one achieves S:Q675H through different way (23587T compared with 23587C) as in #413 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice25_genome_2cfe6_2c2e80.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d73437fd-4f28-461f-8fa0-fcfaba0094dd)

**Comment by FedeGueli** [comment]
This should be now a sub branch of XBB.1.16.18 but i am not sure i want to check further on Usher in a couple of days.

**Comment by FedeGueli** [comment]
Slow closing it for now.
