### ISSUE TITLE
Possible EG.5.1.1 and FY.3.1 recombinant (4 seqs in China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#426]
GISAID query: G5720A, C6541T, A22161G, T22191C
Earliest seq: 2023-06-17 (Sichuan Province, China- EPI_ISL_17988941)
Latest seq: 2023-06-19 (Sichuan Province, China- EPI_ISL_17988939)

Usher Tree (with several reversions which are likely artefacts)
<img width="702" alt="屏幕截图 2023-07-18 025802" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/62cd4283-62b6-4c99-a84e-c7bdce1c1694">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_311ec_415990.json

Description:

I found 2 seqs of EG.5.1.1 with S:Y200C and S:I210T from Sichuan Province, China, which are defining mutations of FY.3.1.
<img width="626" alt="屏幕截图 2023-07-18 025507" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/b8274e86-b452-4201-8679-06e5a6042533">

Genes except Spike are very likely from EG.5.1.1. For Spike mutation, G21718T (S:Q52H) and a silent mutation C22480T are for EG.5.1, while A21995G (S:Y200C), T22191C (S:I210T) and a silent nuc mutation C23191T are from FY.3.1. Besides, both the 2 seqs don't get S:F456L from EG.5.1.1. 
<img width="674" alt="屏幕截图 2023-07-18 025549" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d29f5d28-4090-4925-99c5-d3f7d9d99d63">
<img width="665" alt="屏幕截图 2023-07-18 023422" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/108da995-739d-41e1-86b1-a0fc0d3324a7">

It is my first proposal for possible recombinant, hence the description is incomplete. Could we have a discussion?

Genomes:
EPI_ISL_17988939, EPI_ISL_17988941

**Comment by aviczhl2** [comment]
Breakpoint between S:52 and S:200. 

However given its lost of S:456L I guess it will not compete against EG.5.1.1

**Comment by FedeGueli** [comment]
I am not convnced it is one recombinant cause one of the two sequences in the part of genome ahead of the spike has two private mutations belongng to EG.5.1.1 while the other has not them so likely they are two distinct recombinants, while the S:F456L absence to me is not real cause there are also the reversion from 440 to 460 , likely they are base calling of wt nucleotide.

Evidences:
![Schermata 2023-07-18 alle 08 15 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b5463fb1-db86-48d2-ab69-a5518e811d9a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_311ec_415990.json?c=gt-nuc_23191,25572,27507&label=id:node_5183185
![Schermata 2023-07-18 alle 08 16 29](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9d029afc-57db-4a45-8c03-63014fd89fcf)
mutations listed as EG.5.1.1 : C2334T,G5720A,C6541T,C9693T,C12789T,G13627A,A16878T,A18492G,G21718T,C22480T,T22930A,**C25572T,A27507C**,C29625T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=FY.3.1*&aaMutations1=Orf1b%3AD54N&nextcladePangoLineage1=EG.5.1*&analysisMode=CompareEquals&

**Comment by aviczhl2** [comment]
> while the S:F456L absence to me is not real cause there are also the reversion from 440 to 460 , likely they are base calling of wt nucleotide.

Yeah we cannot conclude from the seq only. But for the recombinant, the breakpoint is before S:200. Unless there's a second breakpoint before S:456 it shall be FY.3.1-spike which does not have 456L.

**Comment by HynnSpylor** [comment]
One more seq updated (also from Sichuan Province, China)

**Comment by FedeGueli** [comment]
To me this is not real, one out of three lacks the FY.3.1 defining.

![Schermata 2023-07-28 alle 23 02 05](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/eef86e13-db6d-47dc-b091-f4a1893ddad1)

One out of three lacks C23191T defining of FY.3 
![Schermata 2023-07-28 alle 23 03 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b7f9efae-e3bd-4780-9d0a-40acfa8bfa52)
![Schermata 2023-07-28 alle 23 05 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a9c7aef0-b934-469d-83f1-32e6a86a8180)


All of them have C22480T that is defining of EG.5.1 but then they all lacks T22930A
![Schermata 2023-07-28 alle 23 06 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e915ad98-2540-4d3b-a67f-0a40f7c3ebe2)
![Schermata 2023-07-28 alle 23 08 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/689cf9c8-1ad0-46b1-9907-6ae7f26bbc01)

So given this pattern it is very unlikely it is real or we should imagine multiple rbd breakpoints.

tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1c76d_42acf0.json?c=gt-nuc_22480&f_userOrOld=uploaded%20sample&label=id:node_10642006

So i propose to close this down.

cc @angiehinrichs @corneliusroemer if you have time to take a look.

reference: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=FY.3.1*&aaMutations1=Orf1b%3AD54N&nextcladePangoLineage1=EG.5.1*&analysisMode=CompareEquals&
https://nextstrain.org/staging/nextclade/sars-cov-2/21L?branchLabel=aa&c=gt-nuc_22480&label=spike_mutations:F456L

**Comment by FedeGueli** [comment]
This doesnt seem spreading further.
