### ISSUE TITLE
XBB.2.3.3 with S:T478R  (35 Thailand, China, South Korea, Australia )

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#429]
XBB.2.3.3 recently acquired S:T478R as several siblings of it.

Tree:
![Schermata 2023-07-18 alle 08 27 05](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/64a741e5-4f75-4e16-8d1e-2282f9805b5f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d276_62a560.json?c=userOrOld&label=id:node_7069562

Defining mutations: XBB.2.3.3 >> C19884T, C13138T> A11794G, S:T478R (A22995G)

Gisaid query: C19884T, C13138T,A11794G

Samples: 16
First: 
hCoV-19/Thailand/TROPMED-0179/2023 | Original | EPI_ISL_17952206 | 2023-04-20
Last:
hCoV-19/Thailand/NIC_UDN_6946/2023 | Original | EPI_ISL_17980180 | 2023-07-04

IDs:
EPI_ISL_17622144, EPI_ISL_17624077, EPI_ISL_17683098,
EPI_ISL_17692219, EPI_ISL_17696820, EPI_ISL_17816161,
EPI_ISL_17835426, EPI_ISL_17952206, EPI_ISL_17956877,
EPI_ISL_17980180, EPI_ISL_17984544, EPI_ISL_17984546,
EPI_ISL_17987920, EPI_ISL_17994632, EPI_ISL_17994656,
EPI_ISL_17994683

Countries:
![Schermata 2023-07-18 alle 08 32 03](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/18cbab39-eacd-47e0-81b5-fd0d22dc21d7)

**Comment by FedeGueli** [comment]
jumpt to 20 seqs. around 5% of recent samples from Thailand

**Comment by FedeGueli** [comment]
cc @corneliusroemer

**Comment by FedeGueli** [comment]
+ 9 : S.Korea, Thailand , Haute Garonne, Alberta, Dublin  , Texas

**Comment by FedeGueli** [comment]
Spain , NYC, Wales and two gbw samples (likely one patient from Uk) this is to keep monitored.

**Comment by aviczhl2** [comment]
Of course. 

Emerging lineage with high growth advantage, global spread and known beneficial mutation.  I can't think of a reason not to propose this.

**Comment by FedeGueli** [comment]
proposed

**Comment by FedeGueli** [comment]
Designated GJ.5 and GJ.5.1 via https://github.com/cov-lineages/pango-designation/commit/897f423b48cc98132cf611f0e4b0e95cc960c32a and https://github.com/cov-lineages/pango-designation/commit/712224206fb032c45ba4e1b4f6ee33c80662a396 see issue on Pango for 255F
