### ISSUE TITLE
FP.1 with ORF8 truncation restored

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#43]
Here's a subbranch of FP.1 (actually the largest one) that gained A27917T, which changes the ORF8:8 stop codon (TGA) to Cysteine (TGT), thus functionally restores the truncated ORF8.

Currently 19 sequences, all from Singapore.

**Genomes:**
EPI_ISL_17496258, EPI_ISL_17496426, EPI_ISL_17496431, EPI_ISL_17539578, EPI_ISL_17539635, EPI_ISL_17539700, EPI_ISL_17539706, EPI_ISL_17539754, EPI_ISL_17596135, EPI_ISL_17596157, EPI_ISL_17596192, EPI_ISL_17596273, EPI_ISL_17596276, EPI_ISL_17631440, EPI_ISL_17631527, EPI_ISL_17631583, EPI_ISL_17631591, EPI_ISL_17631614

**Usher tree:**
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/0b3e1c3c-c67f-4446-9e48-94ddc2425931)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_138bf_cf9440.json?c=gt-nuc_27917&label=id:node_5897136

It'll be interesting to monitor if restoration of ORF8 will confer any growth (dis)advantage over stock FP.1.

**Comment by FedeGueli** [comment]
Please propose in the main page  . very interesting mutations right to be checked beyond the variant spottimg community.

**Comment by JosetteSchoenma** [comment]
Maybe this one explains the growth of XBB.1.11 in Singapore?
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/0198ba7d-e4cf-492b-80d2-649ff1115f28)

This query might be helpful. C13968A, C9487T
It counts 18. It misses EPI_ISL_17539578 which misses C9487T, but adds a bad Indian sequence, so it should be okay to monitor the count.

@c19850727 I count 18 EPI_ISL instead of 19.

**Comment by c19850727** [comment]
Yes @JosetteSchoenma I double checked. It should be 18. Thanks!

**Comment by FedeGueli** [comment]
Now proposed in https://github.com/cov-lineages/pango-designation/issues/1993

**Comment by AnonymousUserUse** [comment]
Does this lineage have SGTF?

**Comment by FedeGueli** [comment]
> Does this lineage have SGTF?

yes FP.1 has 69/70del
