### ISSUE TITLE
XBB.1.5 with ORF1b:I1569V (nsp14_I45V) and S:T478R (55 seqs, USA, Canada, Spain, Sweden)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#430]
**Defining Mutations:** On top of XBB.1.5's [T17124C > T23018C] > C19524T > A11782G > A18172G(ORF1b:I1569V), C22995G(**S:T478R**), T26301C
**Query:** `A18172G, C22995G, T26301C`
**Earliest seq:** 2023-05-02 (`EPI_ISL_17693922`, Florida, USA)
**Latest seq:** 2023-06-29 (`EPI_ISL_17990501`, Québec, Canada)
**Sampled Countries:** USA (12), Canada(5)

<details><summary>Genomes: </summary>

`EPI_ISL_17674333, EPI_ISL_17693922, EPI_ISL_17707877, EPI_ISL_17727017, EPI_ISL_17767522, EPI_ISL_17771553, EPI_ISL_17797773, EPI_ISL_17853127, EPI_ISL_17854077, EPI_ISL_17856173, EPI_ISL_17856311, EPI_ISL_17856521, EPI_ISL_17950925-17950926, EPI_ISL_17979233, EPI_ISL_17986337, EPI_ISL_17990501`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26875_630360.json?f_userOrOld=uploaded%20sample

view from XBB.1.5 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3efda682-d930-4b27-a361-de9d9f0078c7)

`C19524T` branch diversity
![diver](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/66ee64ca-6910-48fa-8462-7a8123b042af)

**Trivia:**
- Recognized as XBB.1.5.28 by Nextclade
- One sequence got further `S:R408N` and `S:K444R`: `USA/IL-CDC-LC1045725/2023|EPI_ISL_17979233|2023-06-27`

**Comment by FedeGueli** [comment]
It appears to be fast.

**Comment by FedeGueli** [comment]
+ 3 from US.

**Comment by FedeGueli** [comment]
Still very far from leaders: https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A18172G%2CC22995G%2CT26301C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
closing this for now.
