### ISSUE TITLE
FL.2 with  S:T385I, S:L441R and S:F490P and multiple AA mutations outside the spike (19 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#431]
**FL.2** with ORF1b:T1019I (nsp13_T96I), ORF1b:S2339F (nsp15_S288F), ORF1a:D1127N (nsp3_D309N), **S:T385I**, ORF1a:G1119S (nsp3_G301S), **S:L441R** and **S:F490P**

**Defining Mutations:** FL.2 > C16523T(**ORF1b:T1019I**) > C9166T, C13019T > C20483T(**ORF1b:S2339F**), C22663T > G376A > G3644A(**ORF1a:D1127N**) > C22716T(**S:T385I**) > G3620A(**ORF1a:G1119S**), T22884G(**S:L441R**), T23030C(**S:F490P** over existing S:F490S/T23031C)
**Query:** G3620A, T23030C, T22884G, 18
**Earliest seq:** 2023-06-11 (EPI_ISL_17871943, Québec, Canada)
**Latest seq:** 2023-07-04 (EPI_ISL_17990438, Québec, Canada)
**Sampled Countries:** Canada (All Québec)

<details><summary>Genomes: </summary>
EPI_ISL_17871943, EPI_ISL_17959286, EPI_ISL_17959299, EPI_ISL_17959351, EPI_ISL_17959364, EPI_ISL_17959377, EPI_ISL_17990408, EPI_ISL_17990435, EPI_ISL_17990438-17990439, EPI_ISL_17990457, EPI_ISL_17990494, EPI_ISL_17990510-17990511, EPI_ISL_17990519, EPI_ISL_17990536, EPI_ISL_17990543, EPI_ISL_17990557
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d3e7_63c700.json?label=id:node_6720489

view from FL.2 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/38cafa3a-ad44-41e9-b79d-76e81b11b2a4)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/53a2de52-a756-4bb7-b099-d97e66e0d461)

**Trivia:**
- F375S_Reversion on its sub-branch didn't show up in Nextclade
![375](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/07b1506e-f7f5-44ce-9967-6bdb31e8e86b)
- Interesting to see N440K+L441R, that's a lot of positive charge.
![441](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/70e58af6-59c7-4b9e-9ece-1cb2298ca516)
- So far only sampled in Québec, so this could be a targeted batch.

**Comment by FedeGueli** [comment]
![Schermata 2023-07-18 alle 11 24 16](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0d00117a-61c1-48e8-a22a-4b8fde46bb0c)
![Schermata 2023-07-18 alle 11 26 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4d152f86-e5b3-4726-a609-4b9cdb3ef41f)
![Schermata 2023-07-18 alle 11 26 36](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a2dc0889-f7f7-4d57-ae07-6850da6d770e)

It seems this could have increased binding while leikely has reduced spike expression

**Comment by FedeGueli** [comment]
It seems fast but for Canadian clusters is better to wait a bit more.

**Comment by FedeGueli** [comment]
closing this for now
