### ISSUE TITLE
FP.4+Orf7a:L9M+S:F456L in China( 13 seqs,2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#435]
FP.4+Orf7a:L9M(C27418A)+G2875A,C20457T,T22928C(S:F456L)

GISAID query:G2875A,C20457T,T22928C
No. of seqs: 9 (Yunnan,Sichuan, Shanghai)

First seq: EPI_ISL_17547586, Yunnan, 2023-4-12
Latest: EPI_ISL_17994460, Shanghai, 2023-6-28

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice34_genome_167ed_64b2b0.json?label=id:node_6740118)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/02a517eb-d34c-4cee-8dbc-f7a42c72b8c0)

**Comment by FedeGueli** [comment]
it seems slow.

**Comment by FedeGueli** [comment]
One more recent sample (end of June) came from Shanghai

**Comment by aviczhl2** [comment]
13, Slovenia
