### ISSUE TITLE
HE.1 sublineage with ORF1a:V710I (209 seqs Puerto Rico/USA)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#436]
Sub-lineage of: HE.1 (XBB.1.18.1.1.1.1) 
Substitution on top of HE.1: ORF1a:V710I (G2393A)
Earliest sequence: 2023-5-03, Puerto Rico — EPI_ISL_17713905
Most recent sequence: 2023-7-20, Wisconsin — EPI_ISL_18090064
Countries circulating: Puerto Rico (194), USA (4)
Number of sequences: 198
GISAID nucleotide query: G2393A,T23018C,G23426A,C28057T
CovSpectrum query: [FE.1.1.1* (Nextclade) + S:V622I, ORF8:A55V, ORF1a:V710I](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AV622I%2CORF8%3AA55V%2CORF1a%3AV710I&nextcladePangoLineage=FE.1.1.1*&)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_275ed_d48f90.json?label=id:node_6835066

![Screenshot 2023-08-04 at 14-58-03 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_275ed_d48f90 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/12881cbd-54fc-4ea0-9121-3fad20885c01)

```{r, echo=FALSE}
EPI_ISL_18059509,EPI_ISL_18060005,EPI_ISL_18060014,EPI_ISL_18060015,EPI_ISL_18060016,EPI_ISL_18060017,EPI_ISL_18060024,EPI_ISL_18059974,EPI_ISL_18059975,EPI_ISL_18059985,EPI_ISL_18059986,EPI_ISL_18059987,EPI_ISL_18059988,EPI_ISL_18059989,EPI_ISL_18043079,EPI_ISL_18043054,EPI_ISL_18043058,EPI_ISL_18043067,EPI_ISL_18043068,EPI_ISL_18043069,EPI_ISL_18043070,EPI_ISL_18043071,EPI_ISL_18043072,EPI_ISL_18043073,EPI_ISL_18043074,EPI_ISL_18043075,EPI_ISL_18043076,EPI_ISL_18043077,EPI_ISL_18043078,EPI_ISL_18043153,EPI_ISL_17998443,EPI_ISL_18043149,EPI_ISL_18043150,EPI_ISL_18043099,EPI_ISL_18043100,EPI_ISL_18043101,EPI_ISL_18043102,EPI_ISL_18043103,EPI_ISL_18043104,EPI_ISL_18043105,EPI_ISL_18043111,EPI_ISL_18043112,EPI_ISL_18043113,EPI_ISL_18043114,EPI_ISL_18043115,EPI_ISL_18043147,EPI_ISL_18043148,EPI_ISL_18043151,EPI_ISL_18043157,EPI_ISL_18043158,EPI_ISL_18043159,EPI_ISL_18043160,EPI_ISL_18043161,EPI_ISL_18043162,EPI_ISL_18043163,EPI_ISL_18043164,EPI_ISL_18007762,EPI_ISL_17976402,EPI_ISL_18007678,EPI_ISL_18007625,EPI_ISL_18007626,EPI_ISL_18007634,EPI_ISL_17982666,EPI_ISL_17982667,EPI_ISL_17982646,EPI_ISL_17982647,EPI_ISL_17982648,EPI_ISL_17982649,EPI_ISL_17982650,EPI_ISL_17982664,EPI_ISL_18007652,EPI_ISL_17982645,EPI_ISL_17982656,EPI_ISL_17982623,EPI_ISL_17982626,EPI_ISL_17982627,EPI_ISL_17982628,EPI_ISL_17982629,EPI_ISL_17982630,EPI_ISL_17982631,EPI_ISL_17982632,EPI_ISL_17982633,EPI_ISL_17982634,EPI_ISL_17982635,EPI_ISL_17982636,EPI_ISL_17982637,EPI_ISL_17982638,EPI_ISL_17982643,EPI_ISL_17885282,EPI_ISL_17982613,EPI_ISL_17885177,EPI_ISL_17885178,EPI_ISL_17885180,EPI_ISL_17885169,EPI_ISL_17885170,EPI_ISL_17885202,EPI_ISL_17885158,EPI_ISL_17885159,EPI_ISL_17885171,EPI_ISL_17885172,EPI_ISL_17885173,EPI_ISL_17885148,EPI_ISL_17831578,EPI_ISL_17810314,EPI_ISL_17810311,EPI_ISL_17830885,EPI_ISL_17830886,EPI_ISL_17831083,EPI_ISL_17831092,EPI_ISL_17831093,EPI_ISL_17831094,EPI_ISL_17831095,EPI_ISL_1783109,EPI_ISL_17831097,EPI_ISL_17831074,EPI_ISL_17831075,EPI_ISL_17831076,EPI_ISL_17831077,EPI_ISL_17831078,EPI_ISL_17831079,EPI_ISL_17831081,EPI_ISL_17831052,EPI_ISL_17831053,EPI_ISL_17831054,EPI_ISL_17831055,EPI_ISL_17831056,EPI_ISL_17831059,EPI_ISL_17831060,EPI_ISL_17831061,EPI_ISL_17831062,EPI_ISL_17831063,EPI_ISL_17831064,EPI_ISL_17831065,EPI_ISL_17831066,EPI_ISL_17805712,EPI_ISL_17805676,EPI_ISL_17805682,EPI_ISL_17805683,EPI_ISL_17805684,EPI_ISL_17805685,EPI_ISL_17805686,EPI_ISL_17805687,EPI_ISL_17805688,EPI_ISL_17805689,EPI_ISL_17805690,EPI_ISL_17805691,EPI_ISL_17805692,EPI_ISL_17805693,EPI_ISL_17805694,EPI_ISL_17805695,EPI_ISL_17805696,EPI_ISL_17805697,EPI_ISL_17805698,EPI_ISL_17805702,EPI_ISL_17805651,EPI_ISL_17805652,EPI_ISL_17805653,EPI_ISL_17805654,EPI_ISL_17805655,EPI_ISL_17805656,EPI_ISL_17805669,EPI_ISL_17805670,EPI_ISL_17805671,EPI_ISL_17805672,EPI_ISL_17805673,EPI_ISL_17805674,EPI_ISL_17777804,EPI_ISL_17777813,EPI_ISL_17777814,EPI_ISL_17777805,EPI_ISL_17777806,EPI_ISL_17777807,EPI_ISL_17965576,EPI_ISL_17777772,EPI_ISL_17777773,EPI_ISL_17777774,EPI_ISL_17777775,EPI_ISL_17777776,EPI_ISL_17777777,EPI_ISL_17777778,EPI_ISL_17777779,EPI_ISL_17777780,EPI_ISL_17737307,EPI_ISL_17737291,EPI_ISL_17737294,EPI_ISL_17713905
```

An additional sublineage of this branch is worth monitoring which consists of 13 seqs (11 from PR and 2 from NY/NJ USA) with ORF1a:D2026G (A6342G) + ORF1a:T4302I (C13170T) + ORF1a:S2900L (C8964T) + **ORF9b:S10F (C28311T, C28312T)**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_275ed_d48f90.json?c=gt-nuc_6342,13170,8964,28311,28312&label=id:node_6835067&tl=pango_lineage_usher

![Screenshot 2023-08-04 at 15-11-05 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_275ed_d48f90 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/bad6b767-5000-483f-90da-8e9048033545)

**Comment by FedeGueli** [comment]
One more sequence from NYC but it seems slow.

**Comment by arodzh-sudo** [comment]
Considering editing this to focus the main branch with ORF1a:V710I (G2393A) and keep monitoring the additional mutations, specially ORF9b:S10F (C28311T, C28312T).

**Comment by FedeGueli** [comment]
> Considering editing this to focus the main branch with ORF1a:V710I (G2393A) and keep monitoring the additional mutations, specially ORF9b:S10F (C28311T, C28312T).

Likely worth monotoring the parental branch

**Comment by FedeGueli** [comment]
closing this for now
