### ISSUE TITLE
XBB.2.3.2 + ORF1a:L293I + ORF1a:P4197S + S:K147N + ORF8:T26I (42 seqs in 8 countries)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#438]
Sub-lineage of: XBB.2.3.2
Substitution on top of XBB.2.3.2: ORF1a:L293I (C1142A), ORF1a:P4197S (C12854T), S:K147N (A22003T), ORF8:T26I (C27970T)
Earliest sequence: 2023-5-11, USA, North Carolina — EPI_ISL_17853014
Most recent sequence: 2023-7-17, Germany — EPI_ISL_18050097
Countries circulating: USA (17), Spain (13), France (5), Japan (2), Puerto Rico (2), Germany (1), Canada (1), UK (1)
Number of sequences: 42
GISAID nucleotide query: C1142A,C12854T,A22003T,C27970T
CovSpectrum query: [XBB.2.3.2* (Nextclade) + ORF1a:L293I, ORF1a:P4197S, S:K147N, ORF8:T26I**](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AL293I%2CORF1a%3AP4197S%2CS%3AK147N%2CORF8%3AT26I&nextcladePangoLineage=xbb.2.3.2*&)

```{r, echo=FALSE}
EPI_ISL_17853014,EPI_ISL_17768942,EPI_ISL_17852577,EPI_ISL_17717513,EPI_ISL_17821259,EPI_ISL_17847968,EPI_ISL_17885598,EPI_ISL_17847923,EPI_ISL_1796501,EPI_ISL_17982655,EPI_ISL_17810179,EPI_ISL_17958259,EPI_ISL_17958260,EPI_ISL_17958263,EPI_ISL_17958264,EPI_ISL_17958265,EPI_ISL_17982677,EPI_ISL_1797232,EPI_ISL_17979090,EPI_ISL_17990082,EPI_ISL_17986670,EPI_ISL_17996336,EPI_ISL_17994111
```

[https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_82d8_6dc8b0.json?f_userOrOld=uploaded%20sample&label=id:node_7075979](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_82d8_6dc8b0.json?f_userOrOld=uploaded%20sample&label=id:node_7075979)

![Screenshot 2023-07-18 at 15-02-08 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_82d8_6dc8b0 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/0b7061e8-419c-4e50-b912-3651d9453474)

**Relative growth advantage** 
![Screenshot 2023-07-18 at 15-00-43 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/bcfb2d51-3f0f-4d32-9085-71ff3d74ffb4)

**Mutations over time**
![Screenshot 2023-07-18 at 15-03-26 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/652e09e1-43c5-49ae-a4e9-1f74133fa77f)

**Comment by arodzh-sudo** [comment]
10 additional sequences from Spain

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by FedeGueli** [comment]
> 10 additional sequences from Spain

i have proposed separately case they all have S:I714V, at the start i didnt recognize it was the same lineage proposed here. Well, so if this will be designated and this spanish branch will go up growing it could be proposed then on the main page. thx.

**Comment by FedeGueli** [comment]
Designated HH.5 (Sorry for the delay)
