### ISSUE TITLE
XBB.2.3.3 sublineage with S:E183K and ORF1b:P1727S (40 seqs mainly in Australia and New Zealand), then further get S:K444R (18)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#439]
Defining mutations:
XBB.2.3.3>C19884T>C18646T (ORF1b:P1727S), S:E183K (G22109A), then further>S:K444R (A22893G)
GISAID query: C19884T, C18646T, C22109A (Further query: A22893G)
Earliest seq: 2023-04-20 (New Zealand, EPI_ISL_17740481)
Most recent seq: 2023-07-07 (Singapore, EPI_ISL_17996625)
Countries detected: Australia (14), New Zealand (10), Singapore (1)

Usher Tree:
<img width="905" alt="屏幕截图 2023-07-19 170459" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/a79671d6-1452-429b-a5bd-8c4916c547ba">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_869e_7a48a0.json?c=gt-S_183

Description:
S:Q183E is the one defining mutation of XBB* lineages, and this sublineage further get S:E183K from acidic aa (E) to basic aa (K). 
Notice that 17 of the 25 seqs further get S:K444R, which emerged in Australia, is another attempt for XBB* to get site S:444 mutation.

Genomes:
EPI_ISL_17739019, EPI_ISL_17739423, EPI_ISL_17739875, EPI_ISL_17740172, EPI_ISL_17740325, EPI_ISL_17740481,
EPI_ISL_17816244, EPI_ISL_17961837, EPI_ISL_17961990, EPI_ISL_17962577, EPI_ISL_17962800, EPI_ISL_17996625,
EPI_ISL_17999588, EPI_ISL_17999614, EPI_ISL_17999642, EPI_ISL_17999682, EPI_ISL_17999695, EPI_ISL_17999774,
EPI_ISL_17999780, EPI_ISL_17999784-17999785, EPI_ISL_17999927, EPI_ISL_17999936, EPI_ISL_17999939, EPI_ISL_17999943,

**Comment by FedeGueli** [comment]
2 New Zealand samples uploaded in July.

**Comment by FedeGueli** [comment]
> One of the latest seqs `Australia/WA15110/2023|EPI_ISL_18127961|2023-07-31` is a saltation from WA that got `S:S494P` https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice27_genome_2e171_7751c0.json?c=gt-S_183,444,494&label=id:node_7361235

This saltation is to me 100% MOV, @ryhisner did u spot this one too??

**Comment by ryhisner** [comment]
I had not, Fede, but you're 100% correct. Definitely a MOV branch!

**Comment by FedeGueli** [comment]
this appears to be the 10% of samples in Auckland in August. i think it is around 7%  cause on Gisaid is still pending the batch of 30% share of XBC.

**Comment by FedeGueli** [comment]
If it starts spreading beyond Oceania we will propose it. pls keep it checked .

**Comment by FedeGueli** [comment]
It seems slow lets wait the next batch from NZL and then closing it.

**Comment by HynnSpylor** [comment]
It has been designated as GJ.7

**Comment by FedeGueli** [comment]
Designated GJ.7 from https://github.com/cov-lineages/pango-designation/commit/d6cfeab5ab7dacd26487abef766ab37f68647005
