### ISSUE TITLE
XBL.3 branch with S:I726V have emerged in Asia -49 seqs as 04Jun

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#44]
There may be a sub branch of XBL.3 that is growing faster than sibling lineages in southern and eastern asia.

It is defined by some nuc mutations plus a spike mutation at residue S:726 

S:I726V happened just 600+ times in the course of the pandemic with the biggest lineage being a B.1.1.7 from germany with less than 100 sequences.

Although successful mutations from 700-to 730 are frequent as A701V or N703I in XBC or S:A706V in XAY or S:I714V  in DV.4

Tree:
![Schermata 2023-05-11 alle 17 43 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e4837640-a7f2-465c-9248-55988b82740e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d12b_d01f80.json?c=gt-S_726&label=id:node_6032759

Defining mutations:
XBL.3 >> C11824T > G14400T > C17766T > S:I726V (A23738G)

Gisaid query: C11824T , G14400T , C17766T ,A23738G 

Samples: 24
EPI_ISL_16975245, EPI_ISL_17359407, EPI_ISL_17388689,
EPI_ISL_17388866, EPI_ISL_17432297, EPI_ISL_17432961,
EPI_ISL_17474470, EPI_ISL_17495865, EPI_ISL_17513938,
EPI_ISL_17527172, EPI_ISL_17539132, EPI_ISL_17539822,
EPI_ISL_17547355-17547356, EPI_ISL_17563988, EPI_ISL_17596177,
EPI_ISL_17596418, EPI_ISL_17596699, EPI_ISL_17631338,
EPI_ISL_17631406, EPI_ISL_17631455, EPI_ISL_17631471,
EPI_ISL_17631496, EPI_ISL_17631530

**Comment by FedeGueli** [comment]
7 more samples 4 from Singapore 2 with travel history (Thailand and Malaysia) 1 from Australia and 2 from US both travel related one of the two from Japan. I will propose it once reached 50seqs ( cc @corneliusroemer)

**Comment by FedeGueli** [comment]
36 seqs last ones from Taiwan , Singapore South Korea Georgia (Us)

**Comment by Over-There-Is** [comment]
Malaysia+1, Taiwan+1

**Comment by Over-There-Is** [comment]
Malaysia+1, Taiwan+1

**Comment by FedeGueli** [comment]
thx @Over-There-Is a batch uploaded today from Singapore seems faster than i thought. Which threeshold we can set for this one to be proposed? 100?

**Comment by Over-There-Is** [comment]
Thailand +2. Since I am an amateur, I don't know which threshold is reasonable.

**Comment by FedeGueli** [comment]
@corneliusroemer ping maybe worth a designation when you.will look at xbl tree

**Comment by FedeGueli** [comment]
Designated XBL.3.1 via https://github.com/cov-lineages/pango-designation/commit/aecb12c70558119c3dfbee19b3d9b4f849a9df53
