### ISSUE TITLE
Very long saltation of FU.1(#2037+28-nuc/18-aa) in Japan (3 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#441]
[#2037](https://github.com/cov-lineages/pango-designation/issues/2037)
 +G10364A(Orf1a:V3367I)+G28447A(Orf9b:55,rev)
+

C2627T, G3482A, G4136A, G5567A, T6294C, T7378C, G10051A, G11128A, G19072A, G21210A, C22993T, C24054T, G24928A, G26107A, A27347G, G28122A, C28348T, C28507T, C11833T, T14094C, C25521T, G28086A, C29675T, del425_427

ORF1a | V54del,L788F, G1073R, V1291I, V1768I, I2010T, M3621I
Orf1b | D2269N, M2581I
S | A831V
ORF3a | E239K
ORF6 | Y49C
ORF8 | G77S,A65T
Orf9b | A22V,A75V

GISAID query: C25521T, G28086A, C29675T
No. of seqs: 3(Japan)
EPI_ISL_17980375-17980377, Japan, 2023-6-22
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_125f1_8c08f0.json?label=id:node_6637868&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6b8d970c-be57-411b-a744-2683f5eb79c6)

**Comment by ryhisner** [comment]
Yeah, I've got this on my list of molnupiravir sequences. It's a really clear example of a MOV lineage, with 100% transitions and 46% G->A. All three sequences are identical and collected on the same day. No metadata. 
<img width="1176" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f0c649f8-e0ac-4f49-9208-026a21f0d1b2">

**Comment by FedeGueli** [comment]
It doesnt seem spreading luckily closing for noe.
