### ISSUE TITLE
EG.5.2 with ORF1a:P748L, ORF1a:S1905F, ORF1b:P976S, and S:L455F (7-10 seq. Canada)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#443]
**EDITED on 25/07**

**Defining mutations** : EG.5.2 >> G2086A, **Orf1a:P748L** /C2508T), **ORF1a:S1905F** (C5979T), C6472T, T12244C, A14142G, C15699T, **ORF1b:P976S** (C16393T) , C20325T, **S:L455F** (G22927T)
**New query**: G2086A, C2508T, C5979T (edited) or T12244C, A14142G, C15699T
**New tree**: (edited)
![Schermata 2023-07-25 alle 14 17 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a6253c50-2b1b-4338-908c-9a10ec0093a7)
![Schermata 2023-07-25 alle 14 20 19](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/cf69c68b-4552-4c0d-9080-0cca6dad9f88)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_41326_fbadf0.json?c=gt-S_455&label=id:node_6703338

Samples 10 on Usher 7 on Gisaid as 25/07/2023

**************************

**Original issue** :
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AEG.5.2*%26S%3AL455F&
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/8987673e-fa90-4ba2-9e6d-e3293f148834)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36ff6_97a510.json?f_userOrOld=uploaded%20sample&label=id:node_6688322

**Comment by FedeGueli** [comment]
This has grown to 7 seqs, all from Canada. Please propose it.

**Comment by FedeGueli** [comment]
ping @corneliusroemer
