### ISSUE TITLE
New XBB.1.9.1+S:478R,688V saltation(6-nuc/6-aa) (14 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#444]
XBB.1.9.1+
A28704G,C1758T, C23625T, C28005T, A22995G, C28201T

ORF1a | A498V
S | K478R, A688V
ORF8 | P38S, S103L
N | D144G

usher assigns it on XBB.1.9.1+C28201T+A22995G branch, however, as both A22995G and C28201T are quite convergent, it's better treat them as part of the saltation.

GISAID query: A28704G,C1758T, C23625T
No. of seqs: 5(Australia 2 USA 3(2 from South Africa, 1 airport))

First: EPI_ISL_17950386, USA from South Africa, 2023-6-21
Latest: EPI_ISL_17999798, Australia, 2023-7-6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34dae_984d10.json?label=id:node_10568193)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/bc1b37f7-fd62-4706-bb24-8a06e292851f)

**Edited : showing advantage over top lineages: **
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=EG.5.1*&nucMutations1=A28704G%2CC1758T%2CC23625T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Last samples from WA and Sa Australia. Please propose it when reaches 20 (if @corneliusroemer doesnt spot it before)

**Comment by FedeGueli** [comment]
I think it has slowed down lets monitor here for abit more

**Comment by FedeGueli** [comment]
Closing this one for now.

**Comment by FedeGueli** [comment]
Parental lineage with Orf8:S:103L got designated FL.35 via https://github.com/cov-lineages/pango-designation/commit/3ddfc810a6a2903d70f42ff6645c412d00a9b927
