### ISSUE TITLE
EG.2+S:Q675H(42 seqs, 7 countries) with a further sublineage with S:F490P (19 seqs, mainly Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#445]
EG.2+G4561A,G23587C(S:Q675H)

GISAID query: G4561A,G23587C,C22995G
No. of seqs:30( Indonesia 2 Japan 14 New Zealand 4 China 1 South Korea 4 (1 from USA) USA 3(1 from Japan))

First: EPI_ISL_17664308, Indonesia, 2023-4-17
Latest: EPI_ISL_17999344, Japan, 2023-6-27

Another S:Q675H lineage after S:478R. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2979_988ad0.json?f_userOrOld=uploaded%20sample&label=id:node_6699086)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/22838e55-b4de-470d-9b31-c11afe7f6041)
*********************

EDITED
Possible sublineage of interest with S:F490P
EG.2 >> S:Q675H > C24748T > A5725G >Orf1a:A2554V (C7926T), A10132T, T10135A >S:F490P (T23030C)
Gisaid query: T23030C,C7926T, T10135A
Samples: 14
tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_1de74_fdc20.json?c=userOrOld&label=id:node_6725008
![Schermata 2023-07-26 alle 13 23 22](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/78c90770-d638-46ea-9b80-6265ce99ce24)

**Comment by aviczhl2** [comment]
@FedeGueli It shouldn't have the S:613 label. You can create an S:675 label.

**Comment by FedeGueli** [comment]
Interestingly a sub branch of it has S:F490P and seems spreading in japan:
![Schermata 2023-07-26 alle 13 21 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/81c05308-42b2-4f51-8b0b-3342bce795a3)
counting 13 samples.

**Comment by FedeGueli** [comment]
@ryhisner i found this very close double synonymous mutation in the sublineage with S:F490P : A10132T, T10135A could be of any relevance?

**Comment by aviczhl2** [comment]
41, UK

**Comment by FedeGueli** [comment]
Designated EG.2.5 via https://github.com/cov-lineages/pango-designation/commit/b375fca919450f297cfd79de816c66d1919327a2
