### ISSUE TITLE
BQ.1.2 singlet with 26 aa changes over BQ.1.2 in Finland

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#448]
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/db63dae2-237f-4783-bfbc-3e33747d3164)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3AT859N%26S%3AP681H%26S%3AI666V&
I found this thing when searching S:T859N. S:T859N is one of convergent mutations in lineages prior to Omicron. However, although the mutation still happens at times in Omicrons, it wasn't generally associated with chronic infections, until recently. It also showed up in a BA.2.9 strain in Sweden.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3AI68T%26S%3AH954D&

**Comment by FedeGueli** [comment]
Please let me know if some new sample pops up closing it a the moment,
