### ISSUE TITLE
Potential FU.1(#2037) / BA.5* recombinant in China (2 seq)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#449]
Query: A460G, G19711A, T23018G

FU.1+A460G+G19711A(Orf1b:V2082I) with BA.5* RBD
Breakpoint: 22664\~22895, 23031\~23202

FU.1> A460G> G19711A(Orf1b:V2082I)> C22895Grev(S:P445Vrev), C22896Trev(S:P445Vrev), A22898Grev(S:S446Grev), T22917G(S:L452R), G22942Trev(S:K460Nrev), G22995Arev(Spike:R478Krev), C23018G(S:P486V), C23019Trev(S:P486V), C23031Trev(S:S490Frev)

Beijing/BJCDC-1446/2023|EPI_ISL_18009716|2023-05-01
Beijing/BJCDC-1461/2023|EPI_ISL_18009731|2023-05-01

**Comment by Over-There-Is** [comment]
The BA.5* donor can be BA.5.1.32, BF.7.14* or BA.5.2.48*/49*/50, or any other still circulating 22B in China.

**Comment by FedeGueli** [comment]
likely this has died off.
