### ISSUE TITLE
XBB.1.5 sublineage with S:K462R and 2 ORF mutation (21 seqs- Peru, Japan and USA)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#45]
Defining mutations: XBB.1.5>G15649A (ORF1b:V728I), G22947A (S:K462R), C27925T (ORF8:T11I, but with the ORF8:G8* ahead), C835T, C4391A
GISAID query: Spike_K462R, C835T, C4391A ( Edited :or A22947G,C835T, C4391A)
Earliest seq: 2023-03-18 (Peru, EPI_ISL_17616713)
Most recent seq: 2023-04-18 (Japan, EPI_ISL_17631142)
Countries detected: Peru (11), USA (2), Japan (1)

Ushe Tree:
![QQ截图20230512094903](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/c215bb85-4839-4613-987a-022703e46750)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_20296_d99d10.json
The S:K462R is quite rare (even all S:K462 mutations), with only about 110 high quality seqs. It emerged in some small branches of BA.1*, BA.2.38 and BA.2.76.  Escape calculator shows the maximum potential in RBD region for XBB in site 462.  
![QQ截图20230512094509](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/554d9fbf-261f-4f19-a27f-99db98e81780)

https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/
Genomes:
EPI_ISL_17351703, EPI_ISL_17521421, EPI_ISL_17616713, EPI_ISL_17631142, EPI_ISL_17634855, EPI_ISL_17634870,
EPI_ISL_17634978, EPI_ISL_17634987, EPI_ISL_17635028, EPI_ISL_17635059-17635060, EPI_ISL_17635066, EPI_ISL_17639854,
EPI_ISL_17639868

**Comment by FedeGueli** [comment]
I would propose it in the main page. New potentisl interesting rbd mutation and geographical spread.

**Comment by FedeGueli** [comment]
@HynnSpylor now 21!! Lets go with a proposal!
