### ISSUE TITLE
XBB.2.3.6 with ORF1a:R4017K (nsp8_R75K), ORF1a:S3099L (nsp4_S336L) and S:N388K (33 seqs, Japan), follows a sub-lineage with S:Y453H (4 seqs, Japan) 

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#450]
**Defining Mutations:** _On top of XBB.2.3.6's [T22843C > C7105T > C1063T]_ > G12315A(ORF1a:R4017K) > G26834T > C9561T(ORF1a:S3099L) > T22726A(S:N388K)
**Query:** C9561T, T22726A
**Earliest seq:** 2023-05-15 (EPI_ISL_17881889, Tokyo, Japan)
**Latest seq:** 2023-07-03 (EPI_ISL_17994250, Kumamoto, Japan)
**Sampled Countries:** Japan (10), USA (3, Virginia, Travel history to Japan)

<details><summary>Genomes: </summary>
EPI_ISL_17881889, EPI_ISL_17884007, EPI_ISL_17960078, EPI_ISL_17971830, EPI_ISL_17971864, EPI_ISL_17971891, EPI_ISL_17973271, EPI_ISL_17985853, EPI_ISL_17994250, EPI_ISL_17996449, EPI_ISL_17996453, EPI_ISL_18006463, EPI_ISL_18006974
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_5ff1_be5620.json?f_userOrOld=uploaded%20sample

view from XBB.2.3 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5d022865-a74b-4588-92d5-426e4885c22c)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3696e75b-4033-4a71-bb41-42f7635daa42)

**Trivia:**
- No idea what S:N388K does, it seems to be deleterious by all predictions, but all those calculators are made on XBB.1.5 backbone, maybe slightly different on XBB.2*? Or simply a super-spreader event?

**Comment by ryhisner** [comment]
There are now three sequences in this lineage with S:Y453H from Japan, a very interesting development. Two from Chiba, one from Tokyo. EPI_ISL_18044092, EPI_ISL_18065162, EPI_ISL_18065176

**Comment by FedeGueli** [comment]
propose it when reaches 35, please.

**Comment by FedeGueli** [comment]
6 + from jap

**Comment by FedeGueli** [comment]
Designated GM.3.1 via https://github.com/cov-lineages/pango-designation/commit/56e3ad0411769d342772935635f611dfaa29da79
