### ISSUE TITLE
XBC.1.6.3 may have acquired S:N460H in the US (6)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#452]
I noticed three sequences of XB.1.6.3 with S:N460H in United states coming from California and Florida, despite being just three samples the shape of the tree suggests me that this could be larger than we think, not sure how fast or fit it will be but nice to check that together here.

XBC.1.6.3 TREE:
![Schermata 2023-07-22 alle 18 20 11](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/05fea2a5-54ae-4718-bd25-923f77704a9e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26756_bf86b0.json?c=userOrOld&label=id:node_6219245

Defining mutations:
XBC.1.6.3 >> > Orf1a:T1597I (C5055T = NSP3_T779I) > Orf1a:A2123V (C6633T = NSP3_A1305V) > T16242A, C22120T > S:N460H( A22940C)

Gisaid query: T16242A, C22120T , A22940C

Samples:
EPI_ISL_17865743, EPI_ISL_18008786, EPI_ISL_18011212

**Comment by HynnSpylor** [comment]
3 more seqs updated today (all from CA, US)

**Comment by FedeGueli** [comment]
Thx @HynnSpylor this starts to be interesting

**Comment by FedeGueli** [comment]
I want to flag to @corneliusroemer @thomaspeacock that this has been already sampled in Wales too:


Wales/CLIMB-CM7YJT4J/2023|2023-07-18
Wales/CLIMB-CM7Y8C6S/2023|2023-07-17
![Schermata 2023-08-08 alle 01 50 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0bbfb8e4-3036-4182-a6d1-11ceeb1b85d8)
