### ISSUE TITLE
Multiple XBB.1.5 branches with S:V1122M and S:T478R : 1 designated/1 dead /1 proposed/ Branch 4 with additonal S:L552I (11 seqs - Mexico, US, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#453]
<a name="task_header"></a>
```[tasklist]
### Multiple XBB.1.5 branches with S:V1122M and S:T478R
- [x] [Branch 1](#branch_1): Designated as **HY.1 (XBB.1.5.100.1)** via [cov-lineages/pango-designation@`8fceb45`](https://github.com/cov-lineages/pango-designation/commit/8fceb45347ce4d0d8cbf5fe603b02528278592ac) `XBB.1.5 [T17124C > T23018C]` > _A21137G(ORF1b:K2557R)_ > `G24926A(S:V1122M)` > _G21137A_Reversion(ORF1b:R2557K_Reversion)_ > `C22995G(S:T478R)`
- [ ] [Branch 2](#branch_2): `XBB.1.5.100` > `C8986T` > `A3662G(ORF1a:S1133G)` > `C1973T` > `T104C` > `C22995G(S:T478R)` [Query: `C8986T, A3662G, C22995G`, 15 seqs, 09/21]
- [ ] [Branch 3](#branch_3): Transferred to cov-lineages/pango-designation#2153 `XBB.1.5 [T17124C > T23018C]` > `C26111T(ORF3a:P240L)` > `G24926A(S:V1122M)` > `A9562G` > `A20898G, 22995G(S:T478R)`
- [ ] [Branch 4](#branch_4): `XBB.1.5.100` > `C1609T, C23216A(S:L552I)` > `A15583G(ORF1b:I706V), C22995G(S:T478R), C28677T(N:T135I)` [Query: `C22995G, C23216A, G24926A`, 19, 10/09]
```

<a name="branch_1"></a>
### Branch 1

<details><summary>Designated as HY.1 (XBB.1.5.100.1) :</summary>

_Designated as **HY.1 (XBB.1.5.100.1)** via cov-lineages/pango-designation@8fceb45 , as parent lineage up to `S:V1122M` designated as **XBB.1.5.100** via cov-lineages/pango-designation@6655aae_

**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > _A21137G(ORF1b:K2557R)_ > `G24926A(S:V1122M)` > _G21137A_Reversion(ORF1b:R2557K_Reversion)_ > `C22995G(S:T478R)`
**Query:** `T17124C, G24926A, C22995G, -C8986T, -C26111T, -T10609C, -C1609T`
**Earliest seq:** 2023-03-27 (`EPI_ISL_17591252`, Mexico City)
**Latest seq:** 2023-07-03 (`EPI_ISL_17994146`, Mexico City)
**Sampled Countries:** USA(19), Mexico (9), Spain (5), UK (2, England), Canada (1), Italy (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17591252, EPI_ISL_17642837-17642838, EPI_ISL_17651068, EPI_ISL_17688114, EPI_ISL_17700054, EPI_ISL_17705946-17705947, EPI_ISL_17707003, EPI_ISL_17760254, EPI_ISL_17760270, EPI_ISL_17768538, EPI_ISL_17768593, EPI_ISL_17785462, EPI_ISL_17786061, EPI_ISL_17787186, EPI_ISL_17819943, EPI_ISL_17842444, EPI_ISL_17842450-17842451, EPI_ISL_17842457, EPI_ISL_17851550, EPI_ISL_17853929, EPI_ISL_17854430, EPI_ISL_17854704, EPI_ISL_17974951, EPI_ISL_17989840, EPI_ISL_17990077, EPI_ISL_17990100, EPI_ISL_17990120, EPI_ISL_17994146, EPI_ISL_17997966, EPI_ISL_18009010, EPI_ISL_18011914, EPI_ISL_18011920, EPI_ISL_18011923, EPI_ISL_18011975`

</details>

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2

**Defining Mutations:** `XBB.1.5.100` > `C8986T` > `A3662G(ORF1a:S1133G)` > `C1973T` > `T104C` > `C22995G(S:T478R)`
**Query:** `C8986T, A3662G, C22995G`
**Earliest seq:** 2023-05-09 (`EPI_ISL_17854937`, Texas, USA)
**Latest seq:** 2023-06-17 (`EPI_ISL_17982531`, Guatemala)
**Sampled Countries:** Guatemala(4), USA (3, California, Texas, New Mexico), Colombia (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17744488, EPI_ISL_17768107, EPI_ISL_17854937, EPI_ISL_17855916, EPI_ISL_17954098, EPI_ISL_17954537, EPI_ISL_17973071, EPI_ISL_17982531`

</details>

[Back to Tasklist](#task_header)

---

**UShER:**
view from `ORF1b:K2557R` flip-flop branch
![branches](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/18285747-73d9-4f82-8bba-d42c2f69d014)

Branch 1:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f988_c05d60.json?f_userOrOld=uploaded%20sample&label=id:node_6932995
![branch1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f4c9ea65-f793-4f3a-a3ff-6a82e9e5a1f1)

Branch 2:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a6ad_c00ac0.json?f_userOrOld=uploaded%20sample&label=id:node_6932886
![branch 2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/60da7af5-313e-4f5b-81e6-dc3e35f18974)

[Back to Tasklist](#task_header)

---

(07/29: adding branch 3 that almost doubled in 10 days)

<a name="branch_3"></a>
### Branch 3

<details><summary>Transferred to main repository: </summary>

_Transferred to cov-lineages/pango-designation#2153_

**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `C26111T(ORF3a:P240L)` > `G24926A(S:V1122M)` > `A9562G` > `A20898G, 22995G(S:T478R)`
**Query:** `C26111T, A20898G, 22995G`
**Earliest seq:** 2023-04-28 (`EPI_ISL_17707100`, California, USA)
**Latest seq:** 2023-07-13 (`EPI_ISL_18036951`, California, USA, with travel history to: Mexico)
**Sampled Countries:** USA (29), Canada (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17707100, EPI_ISL_17744399, EPI_ISL_17767971, EPI_ISL_17788420, EPI_ISL_17788778, EPI_ISL_17788998, EPI_ISL_17789103, EPI_ISL_17852118, EPI_ISL_17852638, EPI_ISL_17856294, EPI_ISL_17856633, EPI_ISL_17950491, EPI_ISL_17950750, EPI_ISL_17950759, EPI_ISL_17955500, EPI_ISL_17971792, EPI_ISL_17971814, EPI_ISL_17972481, EPI_ISL_17986607, EPI_ISL_17997501, EPI_ISL_18036951, EPI_ISL_18037574-18037575, EPI_ISL_18037666, EPI_ISL_18039763, EPI_ISL_18045316, EPI_ISL_18045335, EPI_ISL_18045578, EPI_ISL_18046071, EPI_ISL_18046136`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ac00_4e3ca0.json?f_userOrOld=uploaded%20sample&label=id:node_6969332

diversity from `ORF3a:P240L` branch
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5173d73f-dd80-4a16-93c3-4f5845371a87)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_4"></a>
### Branch 4

**Defining Mutations:** `XBB.1.5.100` > `C1609T, C23216A(S:L552I)` > `A15583G(ORF1b:I706V), C22995G(S:478R), C28677T(N:T135I)`
**Query:** `C22995G, C23216A, G24926A`
**Earliest seq:** 2023-06-20 (EPI_ISL_18011975, Yucatan, Mexico)
**Latest seq:** 2023-07-31 (EPI_ISL_18121068, Oregon, USA)
**Sampled Countries:** Mexico (3), USA (2)

<details><summary>Genomes: </summary>

`EPI_ISL_18011975, EPI_ISL_18121068, EPI_ISL_18136911, EPI_ISL_18137357, EPI_ISL_18137430`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24e14_9e5960.json?c=gt-S_478&label=id:node_7332817
![Branch4](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4949c252-6e93-410e-a930-ce018c854204)

[Back to Tasklist](#task_header)

---

**Trivia:**
- Branch 1 & 2 are on flip-flop branches, featuring `ORF1b:K2557R/A21137G`
- These branches are assigned as `XBB.1.5.28` (`S:T478R` directly on `XBB.1.5` polytomy) by GISAID and Nextclade
- Need to check if these are actually `XBB.1.5.28` sub-branches misplaced right on `XBB.1.5`'s polytomy caused by potential drop-out.
- Branch 3 got further `S:F456L`, no wonder it is _that fast_. Query: `C26111T, A20898G, 22995G, T22928C`

**Comment by FedeGueli** [comment]
cc @angiehinrinchs  i dont think the mutation/reversion is real here : XBB.1.5 [T17124C > T23018C] > A21137G(ORF1b:K2557R) > G24926A(S:V1122M ) > G21137A_Reversion(ORF1b:R2557K_Reversoin) > C22995G(S:T478R) what do you think?

( cc @NkRMnZr your query for variant 1 gives me 71 , correct?)

**Comment by FedeGueli** [comment]
@angiehinrinchs could you take  a look at this flip flop branch. I dont exclude recombination between undesignated sublineages of XBB.1.5 circulating in Mexico.


@NkRMnZr please propose in the pango page the branch 3.

**Comment by FedeGueli** [comment]
Branch 1 designated: HY.1 via https://github.com/cov-lineages/pango-designation/commit/8fceb45347ce4d0d8cbf5fe603b02528278592ac

**Comment by FedeGueli** [comment]
Please keep branch 2 monitored. If it grows remember to repropose it as XBB.1.5.100 plus S:K478R. thx for your work 
@NkRMnZr

**Comment by FedeGueli** [comment]
branch 2 now 10.

**Comment by FedeGueli** [comment]
Branch 4 now went to 8 i think we should monitor it could be n0t slow. reopening this for a while : @NkRMnZr

**Comment by FedeGueli** [comment]
Still too slow. iw ould close this one for now. : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C22995G%2CC23216A%2CG24926A&analysisMode=CompareToBaseline&
