### ISSUE TITLE
XBB.1.19.1 (S:E554K) plus N:P80S with S:T478I S:L455F , S:F456L UAE, Australia 2 sequences

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#454]
I just spotted an XBB.1.19.1 with S:T478I, S:L455F, S:F456L 
two sequences clustering together one from China early in May and one recent in Australia
tree:
![Schermata 2023-07-23 alle 12 53 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fc893d21-3a02-4546-9ab5-c35b48d94cd8)
![Schermata 2023-07-23 alle 12 52 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/dbf63f30-7e14-48d6-b9d4-5588329a1f32)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38d35_d05ce0.json?label=id:node_6620656

Defining mutations:
XBB.1.19.1 (S:E554K) : > N:P80S (C28511T) > Orf1a:S302F (C1170T) > Orf1a:P2079Q (C6501A), C12473T, Orf1a:P4220L(C12924T), S:K478I (A22995T), C24034T, T24046C, T28723C > S:L455F (G22927T), S:F456L (T22928C)  

Samples:  2
EPI_ISL_17645716, EPI_ISL_17999822

Gisaid : T28723C,G22927T,T22928C,C12473T

I was looking at the new Tyler Starr fitness Binding/Expression calculator:  S:T478I while clearly reducing ACE2 binding (less than 478R) it increases [RBD expression](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/).
![Schermata 2023-07-23 alle 13 44 28](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0cd956de-4bbe-4e21-a3f5-5cd1036bd913)

**Comment by Over-There-Is** [comment]
Imported from UAE

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230504-476/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 35; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-05-01"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in The United Arab Emirates"

**Comment by FedeGueli** [comment]
thx @Over-There-Is

**Comment by FedeGueli** [comment]
already proposed in #61

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a7fa_fc5a90.json?label=id:node_6625137

**Comment by FedeGueli** [comment]
Designated GW.5

**Comment by HynnSpylor** [comment]
Today Pakistan updates several seqs, including XBB.1.19.1+K478I only and one GW.5
Maybe it first acquired K478I then got S:L455F+F456L

**Comment by oobb45729** [comment]
> 

Those sequences lack coverage at S:455-456. I assume they all have the double mutations.

**Comment by oobb45729** [comment]
> Today Pakistan updates several seqs, including 7 XBB.1.19.1+K478I only and 2 GW.5 it probably originated in Pakistan, and first acquired K478I then got S:L455F+F456L
> 
> (Maybe GW.5 should broaden the definition as XBB.1.19.1+K478I, and current GW.5 should be GW.5.1?)

Those sequences lack coverage at S:455-456. I assume that they all have the double mutations.

**Comment by FedeGueli** [comment]
@corneliusroemer spotted the Pakistan origin of it. @oobb45729 i suggest to open a "Broadening GW.5 " proposal on the main repo tagging both Cornelius and @angiehinrichs

**Comment by corneliusroemer** [comment]
Why broadening? We don't really rename after such a long time.

Also as @oobb45729 points out, no evidence that they don't have FLip due to Ns.
