### ISSUE TITLE
XBB.1.5.32 with S:T883I (380 seqs, mainly in Canada, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#458]
**Defining Mutations:** XBB.1.5.32 > C24210T(**S:T883I**)
**Query:** T10204C, C8733T, C24210T
**Earliest seq:** 2023-01-26 (EPI_ISL_16980967, Manitoba, Canada)
**Latest seq:** 2023-07-11 (EPI_ISL_18011219, California, USA)
**Sampled Countries:** Canada (317), USA (33), South Korea (8), Australia (3), India (2), Denmark (1), Japan (1), Luxembourg (1)

<details><summary>Genomes: </summary>
EPI_ISL_16980967, EPI_ISL_16980974, EPI_ISL_16989419, EPI_ISL_16989597, EPI_ISL_17019047, EPI_ISL_17068032-17068033, EPI_ISL_17102180, EPI_ISL_17103808, EPI_ISL_17185845, EPI_ISL_17190080, EPI_ISL_17191921, EPI_ISL_17191928, EPI_ISL_17191931, EPI_ISL_17191939, EPI_ISL_17191942, EPI_ISL_17191957-17191958, EPI_ISL_17191992, EPI_ISL_17191997-17191998, EPI_ISL_17192007, EPI_ISL_17192034, EPI_ISL_17192621, EPI_ISL_17211782, EPI_ISL_17226555, EPI_ISL_17226572, EPI_ISL_17266535, EPI_ISL_17269868, EPI_ISL_17271040, EPI_ISL_17271044-17271045, EPI_ISL_17271060, EPI_ISL_17271253, EPI_ISL_17276967, EPI_ISL_17276984, EPI_ISL_17277004, EPI_ISL_17277006-17277007, EPI_ISL_17306619, EPI_ISL_17324164, EPI_ISL_17324182, EPI_ISL_17333147, EPI_ISL_17333625, EPI_ISL_17350230, EPI_ISL_17350291, EPI_ISL_17370205, EPI_ISL_17370257, EPI_ISL_17370517, EPI_ISL_17385888, EPI_ISL_17385903, EPI_ISL_17412545, EPI_ISL_17412762, EPI_ISL_17412771-17412772, EPI_ISL_17412801, EPI_ISL_17412808-17412810, EPI_ISL_17412919, EPI_ISL_17412921, EPI_ISL_17412924, EPI_ISL_17412926, EPI_ISL_17413115, EPI_ISL_17413127, EPI_ISL_17413133-17413134, EPI_ISL_17413141, EPI_ISL_17413163, EPI_ISL_17413184, EPI_ISL_17413186, EPI_ISL_17413644, EPI_ISL_17413652-17413655, EPI_ISL_17413657, EPI_ISL_17413659-17413660, EPI_ISL_17413662-17413664, EPI_ISL_17413682, EPI_ISL_17413962, EPI_ISL_17413970, EPI_ISL_17414001, EPI_ISL_17414012, EPI_ISL_17414091, EPI_ISL_17442362, EPI_ISL_17461803, EPI_ISL_17461806, EPI_ISL_17461808, EPI_ISL_17461900, EPI_ISL_17461930, EPI_ISL_17461932, EPI_ISL_17461938-17461939, EPI_ISL_17461942, EPI_ISL_17461951, EPI_ISL_17462001, EPI_ISL_17462107, EPI_ISL_17462223, EPI_ISL_17462232, EPI_ISL_17465575, EPI_ISL_17465647, EPI_ISL_17471348, EPI_ISL_17478089, EPI_ISL_17486762, EPI_ISL_17490701, EPI_ISL_17495736, EPI_ISL_17497664, EPI_ISL_17499799, EPI_ISL_17502431, EPI_ISL_17504691, EPI_ISL_17504698, EPI_ISL_17504768, EPI_ISL_17504841, EPI_ISL_17504849, EPI_ISL_17510333, EPI_ISL_17510336, EPI_ISL_17510338, EPI_ISL_17510362, EPI_ISL_17510377-17510378, EPI_ISL_17510380, EPI_ISL_17510384, EPI_ISL_17510405, EPI_ISL_17510423, EPI_ISL_17510441, EPI_ISL_17510468-17510470, EPI_ISL_17510472, EPI_ISL_17510474-17510476, EPI_ISL_17510485, EPI_ISL_17510783, EPI_ISL_17536994, EPI_ISL_17546830, EPI_ISL_17552121, EPI_ISL_17552448, EPI_ISL_17552462, EPI_ISL_17552583, EPI_ISL_17583036, EPI_ISL_17583047, EPI_ISL_17583064, EPI_ISL_17583070, EPI_ISL_17583076, EPI_ISL_17583097-17583098, EPI_ISL_17583107, EPI_ISL_17583110, EPI_ISL_17583117, EPI_ISL_17583136-17583137, EPI_ISL_17583662, EPI_ISL_17587215, EPI_ISL_17593673, EPI_ISL_17595267, EPI_ISL_17595891, EPI_ISL_17595904, EPI_ISL_17595910, EPI_ISL_17595918, EPI_ISL_17595942-17595943, EPI_ISL_17595945, EPI_ISL_17595959, EPI_ISL_17604013, EPI_ISL_17604386, EPI_ISL_17604403, EPI_ISL_17605489-17605490, EPI_ISL_17605498, EPI_ISL_17605530, EPI_ISL_17605568, EPI_ISL_17605765, EPI_ISL_17611723, EPI_ISL_17611746, EPI_ISL_17611817, EPI_ISL_17615726, EPI_ISL_17617586, EPI_ISL_17625145, EPI_ISL_17626137, EPI_ISL_17630532, EPI_ISL_17635238-17635239, EPI_ISL_17635254-17635255, EPI_ISL_17635257, EPI_ISL_17635262-17635263, EPI_ISL_17636953, EPI_ISL_17641170, EPI_ISL_17641402, EPI_ISL_17641626, EPI_ISL_17643882, EPI_ISL_17644013, EPI_ISL_17644072, EPI_ISL_17644588, EPI_ISL_17644705, EPI_ISL_17644913, EPI_ISL_17645056, EPI_ISL_17645140, EPI_ISL_17645172, EPI_ISL_17648349, EPI_ISL_17659426, EPI_ISL_17659434-17659435, EPI_ISL_17659437-17659440, EPI_ISL_17659445, EPI_ISL_17659475-17659481, EPI_ISL_17659608, EPI_ISL_17659611, EPI_ISL_17659631, EPI_ISL_17659797, EPI_ISL_17659889-17659890, EPI_ISL_17659898-17659899, EPI_ISL_17659975-17659981, EPI_ISL_17659984, EPI_ISL_17659987, EPI_ISL_17660055, EPI_ISL_17660076, EPI_ISL_17660081, EPI_ISL_17660094, EPI_ISL_17660130, EPI_ISL_17660155, EPI_ISL_17660175, EPI_ISL_17660178, EPI_ISL_17660181, EPI_ISL_17660187, EPI_ISL_17660191, EPI_ISL_17660269, EPI_ISL_17661351, EPI_ISL_17662236, EPI_ISL_17672101, EPI_ISL_17672163, EPI_ISL_17675242, EPI_ISL_17682163, EPI_ISL_17682168, EPI_ISL_17682240, EPI_ISL_17682254, EPI_ISL_17682263, EPI_ISL_17682268, EPI_ISL_17682332, EPI_ISL_17682335-17682337, EPI_ISL_17682341, EPI_ISL_17686649, EPI_ISL_17686651, EPI_ISL_17686656, EPI_ISL_17686658, EPI_ISL_17686662, EPI_ISL_17686669, EPI_ISL_17686675, EPI_ISL_17686679, EPI_ISL_17686686, EPI_ISL_17686698, EPI_ISL_17686715, EPI_ISL_17686717, EPI_ISL_17686720-17686721, EPI_ISL_17686725-17686726, EPI_ISL_17686728, EPI_ISL_17686750, EPI_ISL_17686763, EPI_ISL_17686771, EPI_ISL_17686775, EPI_ISL_17686777, EPI_ISL_17686780, EPI_ISL_17686782, EPI_ISL_17686805, EPI_ISL_17686807-17686808, EPI_ISL_17687706, EPI_ISL_17687742, EPI_ISL_17691204, EPI_ISL_17706751, EPI_ISL_17706753, EPI_ISL_17707890, EPI_ISL_17707963, EPI_ISL_17707966, EPI_ISL_17711621, EPI_ISL_17723532, EPI_ISL_17727209, EPI_ISL_17732341, EPI_ISL_17732363, EPI_ISL_17735428, EPI_ISL_17740774, EPI_ISL_17740954, EPI_ISL_17743597, EPI_ISL_17743602-17743603, EPI_ISL_17743610, EPI_ISL_17743614-17743615, EPI_ISL_17743620-17743621, EPI_ISL_17743626-17743627, EPI_ISL_17743648, EPI_ISL_17743658, EPI_ISL_17761060, EPI_ISL_17761103, EPI_ISL_17761111, EPI_ISL_17761193, EPI_ISL_17761233, EPI_ISL_17761246, EPI_ISL_17769095, EPI_ISL_17779205, EPI_ISL_17779637, EPI_ISL_17782717, EPI_ISL_17782806, EPI_ISL_17782887, EPI_ISL_17782959, EPI_ISL_17782979, EPI_ISL_17783059, EPI_ISL_17783080, EPI_ISL_17783206, EPI_ISL_17789289, EPI_ISL_17798811, EPI_ISL_17798891, EPI_ISL_17798899, EPI_ISL_17798906, EPI_ISL_17799014, EPI_ISL_17799054, EPI_ISL_17799076, EPI_ISL_17799392, EPI_ISL_17821362, EPI_ISL_17821827, EPI_ISL_17852341, EPI_ISL_17854532, EPI_ISL_17856418, EPI_ISL_17856709, EPI_ISL_17857014, EPI_ISL_17857024, EPI_ISL_17859926, EPI_ISL_17859930, EPI_ISL_17859938, EPI_ISL_17859941, EPI_ISL_17952402, EPI_ISL_17961074, EPI_ISL_17971428, EPI_ISL_17971552, EPI_ISL_17986873, EPI_ISL_18005607, EPI_ISL_18011219
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10a44_d23ab0.json?f_userOrOld=uploaded%20sample

![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c814e0c0-37df-4ba0-9b70-6ff012d3a644)

**Trivia:**
- Some of the undesignated hiatus branch, 88 out of 366 collected Since May 1st, but only 9 collected since June 1st. Out of those recent samples, there's one emerging branch of S:K478E, and another with S:E619Q.

**Comment by FedeGueli** [comment]
Although well defined at least in Canada it cannot compete with fast coming lineages: https://cov-spectrum.org/explore/Canada/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T10204C%2CC8733T%2CC24210T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
> 08-26, 5 seqs from Canada and USA `EPI_ISL_18120108, EPI_ISL_18120762, EPI_ISL_18120846, EPI_ISL_18133653, EPI_ISL_18133692`

Thanks @NkRMnZr fro tracking it, time to close it cause one lineage with 300seqs growing just of half a dozen every two weeks means it is disappearing. Although in a perfect system this would have been designated before being our time resources and efforts necesiraly limited i think better to focus on growing lineages. (Although i love personally to have the tree described as better as possible. Thx
