### ISSUE TITLE
FK.1.1.2 with S:A684V (32 seqs, Australia)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#459]
**Defining Mutations:** FK.1.1.2 > A28154T > C23613T (**S:A684V**)
**Query:** C23613T, A28154T, T23071G
**Earliest seq:** 2023-05-07 (EPI_ISL_17662942, South Australia)
**Latest seq:** 2023-07-05 (EPI_ISL_17999365, South Australia)
**Sampled Countries:** Australia (32, SA/30, Victoria/2)

<details><summary>Genomes: </summary>
EPI_ISL_17662942, EPI_ISL_17703912, EPI_ISL_17703923, EPI_ISL_17793456, EPI_ISL_17793464, EPI_ISL_17793523, EPI_ISL_17793534, EPI_ISL_17793593, EPI_ISL_17793613, EPI_ISL_17793768, EPI_ISL_17793833, EPI_ISL_17802450, EPI_ISL_17822449, EPI_ISL_17849437, EPI_ISL_17849542, EPI_ISL_17849554, EPI_ISL_17849608, EPI_ISL_17849633, EPI_ISL_17849643, EPI_ISL_17849646, EPI_ISL_17849655, EPI_ISL_17849702, EPI_ISL_17849720, EPI_ISL_17999365, EPI_ISL_17999981-17999982, EPI_ISL_18000023, EPI_ISL_18000041, EPI_ISL_18000097-18000098, EPI_ISL_18000210, EPI_ISL_18000213
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f6da_d30410.json?f_userOrOld=uploaded%20sample&label=id:node_7388027
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b7f2d40f-6452-4948-b717-f867555543b7)

**Trivia:**
- Be aware of FK.1.1.2's T23071G branch, it is a S:V503 silent mutation, close to predicted hot spot H505, also may be something close to V503E or G504S/D that may be bad for certain potential antibody, according to Cao et al., 2022 https://doi.org/10.1016/j.celrep.2022.111845

**Comment by FedeGueli** [comment]
it seems slow ,no recent smaples closing for now
