### ISSUE TITLE
Saltation of BQ.1.1.40 with S:C15R, S:W64R, S:D428H(?), S:N481S, S:S494P, S:I670M, S:D1139Y and other 16 non-Spike mutation (2 seqs in Ontario, Canada)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#468]
defining mutations: BQ.1.1.40>C1441T, C23191T, G25690T(ORF3:G200C)>saltation branch 
***NOTICE THAT IT IS NEIGHBORED WITH ANOTHER BQ.1.1.40 SALTATION BRANCH** (https://github.com/sars-cov-2-variants/lineage-proposals/issues/132)

Substitutions in saltation:
nuc: C335T, T4369C, C4763T, G7988A, C10279T, C11249T, C11681G, T11879C, T13705G, C13957T, T15167C, G15822A, C16915T, C17285T, A18982T, T21605C, T21752C, A23004G, T23042C, A23572G, G24977T, G25912T, T26149C, A27562G, G28209T, G28560A
ORF1ab: R24C, A2575T, H1500Y, R3662C, L3806V, L4481V, R4565C, L4968S, M5186I, S5674L, M6240L
S: C15R, W64R, D428H (1 seq is missing), N481S, S494P, I670M, D1139Y
ORF3a: G174C, S253P
ORF7a: T57A
ORF8: E106*
N: G96D
<img width="637" alt="屏幕截图 2023-07-25 111601" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/9ba4d09a-1692-4502-97fc-930c0e7f6b95">

**Shared with the neighbored saltation branch: S:D1139Y, ORF1ab:R24C, ORF1ab:M6240L**

Deletions:
<img width="248" alt="屏幕截图 2023-07-25 111815" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/56db9962-13a8-47ae-9a5c-fb581e6b0706">

GISAID query: T4369C, C4763T, G7988A

Usher Tree: (Blue for the past saltation, yellow for the current saltation)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12bb4_f3c5d0.json?c=gt-S_64,385
<img width="907" alt="屏幕截图 2023-07-25 112325" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/c04c9a7c-4271-40e1-94b3-0324dc09b731">

It should be highly concerned that it neighbored with another BQ.1.1.40 saltaiton branch, but they share a little mutations. Although it is very likely another nursing home outbreak (despite the 2 samples are submitted from different labs), it also should be watched.

Genomes:
EPI_ISL_17996897, EPI_ISL_18030536

**Comment by Over-There-Is** [comment]
Also Y144-(?)

**Comment by FedeGueli** [comment]
Saw this one two, thanks for proposing!

**Comment by FedeGueli** [comment]
Wondering if the source of both lineages is a single person, that would be a bit worrisome

**Comment by FedeGueli** [comment]
No new sample closing for now.
