### ISSUE TITLE
GW.1 sublineage with Orf3a:D27Y circulating in Canada (78 seq, 5 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#469]
GW.1> C4586T> C2416T, T13064C, G25471T(Orf3a:D27Y)
Query: C2416T, T13064C, G25471T

Earliest Sequence: 06-04 England, United Kingdom EPI_ISL_18007108
Latest Sequence: 08-14, England, United Kingdom EPI_ISL_18209227

Regions Detected: **Canada** 71(Ontario 59, BC 12), **United Kingdom** 4(England), **USA** 2(New Jersey, 1 from **Netherlands**, 1 airport screening), **South Korea** 1

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_303b8_577d40.json?label=id:node_10281855
![2023-08-20 (3)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/93a80fde-40f6-4fee-aec4-91d1382a0d6f)

<details><summary>Sequences</summary>

EPI_ISL_17814668, EPI_ISL_17814702, EPI_ISL_17814704-17814705,
EPI_ISL_17814811-17814812, EPI_ISL_17814814, EPI_ISL_17814836-17814837,
EPI_ISL_17838809, EPI_ISL_17849059, EPI_ISL_17849070,
EPI_ISL_17849094, EPI_ISL_17849096, EPI_ISL_17849098,
EPI_ISL_17849103-17849107, EPI_ISL_17849121, EPI_ISL_17849161,
EPI_ISL_17849193-17849197, EPI_ISL_17851463, EPI_ISL_17851469,
EPI_ISL_17960554, EPI_ISL_17960587, EPI_ISL_17960644,
EPI_ISL_17960683, EPI_ISL_17960685, EPI_ISL_17970343,
EPI_ISL_17977841-17977844, EPI_ISL_17977854-17977857, EPI_ISL_17993979,
EPI_ISL_17993988-17993990, EPI_ISL_17994005, EPI_ISL_17994013,
EPI_ISL_17994019, EPI_ISL_17994021-17994024, EPI_ISL_17994027,
EPI_ISL_17994046, EPI_ISL_17994095-17994096, EPI_ISL_17994119,
EPI_ISL_18007108, EPI_ISL_18030472-18030473, EPI_ISL_18030558,
EPI_ISL_18045193, EPI_ISL_18045259, EPI_ISL_18045264,
EPI_ISL_18057738, EPI_ISL_18081761, EPI_ISL_18081763,
EPI_ISL_18112229, EPI_ISL_18129056, EPI_ISL_18129058,
EPI_ISL_18129069, EPI_ISL_18129127, EPI_ISL_18129147,
EPI_ISL_18129150, EPI_ISL_18161435, EPI_ISL_18209227

</details>

**Comment by FedeGueli** [comment]
Still i think it is mostly a cluster. please when an issue got 5 or more updates if you can re publish the tree. Its shape could be a key here to understand what is going on.

**Comment by Over-There-Is** [comment]
> Still i think it is mostly a cluster. please when an issue got 5 or more updates if you can re publish the tree. Its shape could be a key here to understand what is going on.

The json file is updating when new sequences appear, although I did not update the image, you can also view the latest version via the link. And I just update the image right now.

**Comment by FedeGueli** [comment]
> > Still i think it is mostly a cluster. please when an issue got 5 or more updates if you can re publish the tree. Its shape could be a key here to understand what is going on.
> 
> The json file is updating when new sequences appear, although I did not update the image, you can also view the latest version via the link. And I just update the image right now.

Cool thank you i didnt know

**Comment by Over-There-Is** [comment]
It seems that there are still some COGUK sequences did not uploaded to GISAID.

**Comment by FedeGueli** [comment]
too few recent samples.
