### ISSUE TITLE
XBB.1.5 with P681R in canada (20 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#47]
This one is different from the xbb.1.34 which has p681r and n:a50v. Gisaid query: A10804G,T17124C, C23604G  (edited)

Even for 18 sequences, i think there is some diversity in aa mutations.
![Screenshot_20230512_151912_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/7afe6437-f89e-4349-ae11-91527a1ddc6d)

![Screenshot_20230512_151316_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/5d28708d-9cdf-43d9-99db-4e490592fa72)

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3e48b_e3b380.json?f_userOrOld=uploaded%20sample

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A681r&nucMutations=a10804g

**Comment by FedeGueli** [comment]
Agree this seems interesting all recent samples although Canada usually did targeted sequencing.
the top branch has 
T28318C = ORF9b:L12S and then S:Q677H that makes the FCS : SYQTHTKSRRRARSVASQSI (cc @thomaspeacock)

while the bottom branch shows Orf3a:T229I that was defining in BN.1

**Comment by BorisUitham** [comment]
Yes it's all quebec too. So for the moment its a very localized cluster

**Comment by FedeGueli** [comment]
Still slow .

**Comment by FedeGueli** [comment]
Closing this one.
