### ISSUE TITLE
Sibling lineage of XBB.1.5.59 with F456L and Orf1a:T654A spreading in South Korea and South America (52)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#471]
In the same tree of XBB.1.5.59 and XCF now is clearly visible  a new XBB.1.5 sublineage with S:F456L

Gisaid query: A2225G,C5512T, C17439T, A29700G
finds : **22** samples
from 7 countries mainly **South Korea**

<Details>
<summary>
Samples:
</summary>
EPI_ISL_17768046, EPI_ISL_17779305, EPI_ISL_17780614,
EPI_ISL_17816933, EPI_ISL_17853017, EPI_ISL_17853114,
EPI_ISL_17954142, EPI_ISL_17960522, EPI_ISL_17969427,
EPI_ISL_17969448, EPI_ISL_17979152, EPI_ISL_18010883,
EPI_ISL_18011000, EPI_ISL_18031207-18031210, EPI_ISL_18031547-18031551,

</details>

Defining mutations:
**XBB.1.5 >> S:F456L (T22928C) > Orf1a:T654A (A2225G), C5512T, C17439T, A29700G**

Tree:
![Schermata 2023-07-25 alle 17 06 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ed42745a-84fd-4c3f-a4d4-06e867420e77)

![Schermata 2023-07-25 alle 17 05 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4c1a51be-ffeb-487d-a5df-0ab19a82fb85)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1484c_fe4450.json?c=gt-ORF1ab_654&label=id:node_7003423

Note that Usher misclassify it as XBB.1.5.59 while it is missing the defining mutation of XBB.1.5.59
![Schermata 2023-07-25 alle 17 07 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a5c6a30b-e79c-423a-9e16-0f02bafac492)

Growth comparison: 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A2225G%2CC5512T%2CC17439T%2CA29700G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Interestingly there was a sublineage of XBB.1.5.86 circulating n SOuth korea with Orf1a:T654A we cant exclude the lineage proposed here comes from a recombination between XBB.1.5.59 and XBB.1.5.86
![Schermata 2023-07-25 alle 17 11 34](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b8ece2ac-3b29-4f11-935d-26e25b5f936a)

But unlikely looking at this:

https://cov-spectrum.org/explore/South%20Korea/AllSamples/Past6M/variants?aaMutations=Orf1a%3AT654A%2CS%3Af456L&aaMutations1=orf1a%3AT654A&nextcladePangoLineage1=XBB.1.5.86*&nextcladePangoLineage2=XBB.1.5.59*&analysisMode=CompareEquals&
![Schermata 2023-07-25 alle 17 14 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4a91f67b-0b89-484d-b1ce-b16e01090de1)

**Comment by FedeGueli** [comment]
Although slow last samples came from Costarica and from Germany via GBW US Surveillance)

**Comment by FedeGueli** [comment]
New samples from Colombia, Ecuador and Utah

**Comment by FedeGueli** [comment]
Last samples came from Spain, Canada, Trinidad and US

**Comment by FedeGueli** [comment]
It doest seem slow now: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A2225G%2CC5512T%2CC17439T%2CA29700G&analysisMode=CompareToBaseline&

cc @ryhisner @hynnspylor @aviczhl2 @Nkrmnzr @over-there-is should i propose this?

**Comment by ryhisner** [comment]
It seems geographically widespread enough to justify a proposal to me. I say go for it. 

A29700G has always intrigued me. It seems to show up a lot in interesting sequences, but it's not an a particularly interesting position and doesn't seem like it should have any real function. According to this depiction of the secondary RNA structure of the 3' UTR, it switches one pair from an A-T bond to a G-T bond, which shouldn't make much difference. However, maybe it allows a slight shift into a more favorable conformation?
<img width="1507" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cc4f16ec-3e9e-47a9-9c2b-5fa8a2ee6e23">

**Comment by FedeGueli** [comment]
Thx @ryhisner proposed

**Comment by aviczhl2** [comment]
Designated XBB.1.5.110
