### ISSUE TITLE
HN.1 (FL.1.5.1 + S:A67S) with 4 further NTD mutations: I68V, E156Q, M177V, N185G (6 seqs)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#477]
Only 2 sequences so far, but interesting in the amount of mutations in the NTD region, as well as inheriting 456l+478r from its ancestor. One seq is from dominican republic (5/7), where hn.1 and fl.1.5.1 are already establishing dominance, but recently another sample has been uploaded from florida (12/7). This is indicated as baseline surveillance rather than airport screening. Of course both are in the carribean region so the spread might not be too interesting, but for such mutated lineage it might be worth monitoring.

Note that all these NTD mutations are relatively rare: 67s (9k), 177v (5k), 68v (1.5k), 156q (1.1k), 185g (4, of which these 2 are half)

Gisaid query: a21764g, g22028c, a22091g, a22115g, a22116g 

![hn 1 1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/8484c5d2-987b-41ae-b36b-1c9fb01a71d7)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2b6ca_3d520.json?c=gt-S_156

**Comment by FedeGueli** [comment]
@BorisUitham could you add a nucleotides query for this one?

**Comment by BorisUitham** [comment]
Sure: for the ntd muts its g21671t, a21764g, g22028c, a22091g, a22115g, a22116g.
Ill add it in main post, there are probably more succint queries but thisll manage

**Comment by FedeGueli** [comment]
it doesnt seem super fast  hopefully,

**Comment by BorisUitham** [comment]
I think this can stay closed because i highly highly doubt this is relevant but I'm quite surprised to see a fifth sequence submitted yesterday, 4 months after the previously found sequence in new jersey:
EPI_ISL_18779138
Collected just before christmas, 12-20!
Both NJ sequences aren't very related to eachother and branch off of S:N1023S which it shares with a dominican republic sequence, but not the NY sequence. This latest one also adds S:T572I.

Boggles my mind how this one was still alive. Perhaps its a long term infection that passed on to someone else because I can't imagine this having a lot of community transmission.

**Comment by FedeGueli** [comment]
i have put it under monitoring. thank you!

**Comment by FedeGueli** [comment]
I see 6 samples now the last collected in 2024

**Comment by BorisUitham** [comment]
Very mysterious this sudden reappearance in NJ of a seemingly unfit sublineage in the JN.1-dominant era! This one adds N:S193N and N:P365L. Also i had a typo in my previous comment, its S:T573I instead of S:T572I
