### ISSUE TITLE
EG.1.6 (XBB.1.9.2 + S:Q613H, N:L219F) Sublineage with S:V642del, ORF3a:V244F, ORF9b:R47P, ORF1a:P4211Q, ORF1b:A576V (78 seqs)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#478]
### **Description**
**Sub-lineage of:** EG.1.6 (XBB.1.9.2.1.6 = XBB.1.9.2 + S:Q613H, N:L219F, G26235T)
**Earliest sequence:** 2023-4-25, South Korea, EPI_ISL_17677447
**2nd-Earliest sequence:** 2023-5-21, South Korea, EPI_ISL_17762019
**Most recent sequence:** 2023-7-11, South Korea — EPI_ISL_18039153, EPI_ISL_18039165
**Countries circulating:** South Korea (25), Finland (1)
**Number of Sequences:** 26
**GISAID AA Query:** Spike_Q613H, Spike_V642del, NS3_V244F
**GISAID Nucleotide Query:**
**CovSpectrum Query:** Nextcladepangolineage:EG.1.6* & S:V642- & ORF3a:V244F
### **Substitutions on top of EG.1.6:**
**ORF3a:** V244F
**ORF9b:** R47P
**ORF1a:** P4211Q
**ORF1b:** A576V
**Nucleotide:** G28423C
**Deletions on top of EG.1.6:**
**AA Deletions:** S:V642del
**Nucleotide Deletions:** ∆23486-23488
 
**Phylogenetic Order of Mutations:** G28423C (ORF9b:R47P) **→** C12897A (ORF1a:P4211Q) **→** C4021T (syn), C15194T (ORF1b:A576V), G26122T (ORF3a:V244F)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.1.6_V642del_26seq.json?c=gt-ORF3a_244&label=id:node_2965810
<img width="1489" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/38048c7a-a020-44e0-a02d-777325063d03">

**Evidence**
There have been a scattering of sequences with deletions around S:642, but this is one of the only ones to reach a decent size. The sequence from Finland is actually the basal sequence for this lineage, so though 25/26 sequences are from South Korea, it's possible it originated in an undersequenced country elsewhere.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17677447, EPI_ISL_17762019, EPI_ISL_17806994-17806999, EPI_ISL_17807988, EPI_ISL_17816391-17816392, EPI_ISL_17816614, EPI_ISL_17932496, EPI_ISL_17966736, EPI_ISL_17969825, EPI_ISL_17969947, EPI_ISL_17970084, EPI_ISL_17970128, EPI_ISL_17974482, EPI_ISL_17983541-17983542, EPI_ISL_17983702, EPI_ISL_17983704, EPI_ISL_18038698, EPI_ISL_18039153, EPI_ISL_18039165
</details>

**Comment by FedeGueli** [comment]
New samples from S.Korea collected in July

**Comment by FedeGueli** [comment]
This kept on  spreading at low levels  in South Korea. Now it is over 60 sequences : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16d5a_b89a20.json?label=id:node_6981940

**Comment by FedeGueli** [comment]
78 Japan and South Korea no chance to compete with HK.3 & co  

closing it now.
