### ISSUE TITLE
XBC.1.6+Orf1b:R712C+Orf7a:Q90* (67 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#479]
XBC.1.6+C12733T+C1594T+C15601T(Orf1b:R712C)+C27661T(Orf7a:Q90*)

GISAID query: C15601T, C27661T
No. of seqs: 67(Australia)

First: EPI_ISL_17398369, 2023-3-24
Latest: EPI_ISL_18000304,2023-7-2

Propose this as Orf7a:Q90* truncation is seen again.  It also appears in XBB.2.3 #328 in Bangladesh.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice97_genome_3cc08_10790.json?label=id:node_6227529)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/17e77830-6f1d-472e-9a3b-d5333cfd0b03)

**Comment by FedeGueli** [comment]
thx @aviczhl2 i have seen multiple times this one but i got confused with the other XBC.1.6.2 with orf7a truncated proposed by @krosa1910 as it was tracked as branch in https://github.com/cov-lineages/pango-designation/issues/2057 Luckily you were there to spot !

**Comment by FedeGueli** [comment]
still no sequences outside SA

**Comment by aviczhl2** [comment]
No seqs since proposal.
