### ISSUE TITLE
XBB.1.5.38 (i666v) with s:t478r (europe, n. america, 43 sequences)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#48]
I was just monitoring this for a while but there is a new subbranch in kalmar, sweden that is currently clustering so i'm just putting this here to keep a further eye on it.

The overall branch including swedish currently has a 63% advantage over xbb.1.5.38. Theres currently too few swedish sequences to accurately get a growth advantage out of that. It says 131 (42-219) over xbb.1.5.38 but thats probably an overestimation due to clustering

The swedish branch has orf8:i9t (which is probably useless because of the 8 truncation) and n:p279l

Query: spike_f486p, spike_i666v, spike_t478r

![Screenshot_20230512_155023_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/d09a527e-b979-4871-be16-4b2b68401a7b)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_7fff_e43cd0.json?f_userOrOld=uploaded%20sample&showBranchLabels=all

Overall:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A478r&nextcladePangoLineage=xbb.1.5.38*&aaMutations1=s%3A521s&nextcladePangoLineage1=xbb.1.16*&

Swedish branch:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A478r%2Cn%3A279l&nextcladePangoLineage=xbb.1.5.38*&aaMutations1=s%3A521s&nextcladePangoLineage1=xbb.1.16*&

**Comment by FedeGueli** [comment]
@ryhisner @thomaspeacock Orf8.

**Comment by BorisUitham** [comment]
There has not been any uploads from kalmar, sweden since 05-04 so it is difficult to tell if that branch is spreading or not. Indeed 4 new sequences from other branches though.

**Comment by BorisUitham** [comment]
By the way, here is orf8:8* vs orf8:8* + orf8:i9t:
https://cov-spectrum.org/explore/World/AllSamples/from%3D2022-09-01%26to%3D2023-05-11/variants?aaMutations=orf8%3A8*&aaMutations1=orf8%3A9t%2Corf8%3A8*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated GG.1
