### ISSUE TITLE
FL.2/EU.1.1 large recombinant buried in FL.2 tree  (65 seqs China, Chile, Us)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#486]
I think i discovered a quite big recombinant hidden in the FL.2 tree:

![Schermata 2023-07-26 alle 14 37 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8a0ca9ed-ee3a-4d1d-9197-99471760dcdd)
As you can see it got reverted FL.2 defining (T4579A) and XBB.1.9*  defining (Orf1a:G1819S = G5720A) 
while getting C920T  defining of XBB.1.5.26/EU.1/EU.1.1  family:
![Schermata 2023-07-26 alle 14 38 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/34e33517-7f7c-408c-936e-c5c13ab76938)
![Schermata 2023-07-26 alle 15 10 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f85e0389-08e9-4da8-b0bd-18b821258d89)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4057d_fa010.json?branchLabel=back-mutations&c=gt-nuc_920&label=id:node_6766989

Evidences:
![Schermata 2023-07-26 alle 15 14 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fa4a0f81-1163-436b-82d4-7f9a0971e5d2)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=EU.1.1*&nextcladePangoLineage1=FL.2*&analysisMode=CompareEquals&

Breakpoint somewhere between 5721 and 11955 ( everything before 5721 is from EU.1.1* and everything after 11955 is from FL.2)

Gisaid query: C23191T,C920T,C29353T

<Details>
<Summary> Samples: </summary>
EPI_ISL_1429670, EPI_ISL_10080731, EPI_ISL_17625321,
EPI_ISL_17625509, EPI_ISL_17684020, EPI_ISL_17684353-17684354,
EPI_ISL_17696752, EPI_ISL_17714403, EPI_ISL_17718392,
EPI_ISL_17725054, EPI_ISL_17725327, EPI_ISL_17729840,
EPI_ISL_17770210, EPI_ISL_17775339, EPI_ISL_17775490,
EPI_ISL_17778727, EPI_ISL_17783630, EPI_ISL_17794134,
EPI_ISL_17794175, EPI_ISL_17794199, EPI_ISL_17794782,
EPI_ISL_17795171, EPI_ISL_17795739, EPI_ISL_17801764,
EPI_ISL_17808240, EPI_ISL_17808258, EPI_ISL_17808282,
EPI_ISL_17811258, EPI_ISL_17818495, EPI_ISL_17818502,
EPI_ISL_17830428, EPI_ISL_17831623-17831637, EPI_ISL_17850878,
EPI_ISL_17850912-17850914, EPI_ISL_17955971, EPI_ISL_17999059,
EPI_ISL_17999196, EPI_ISL_18006101, EPI_ISL_18034317,
EPI_ISL_18035574, EPI_ISL_18036169

</details>

Countries: 3 China, Chile, US
![Schermata 2023-07-26 alle 15 15 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/02bc949f-af3f-4882-9cc8-4ad4b9212f2c)

**Comment by aviczhl2** [comment]
I guess Cornelius will once again designate this as a normal branch instead of recombinant branch.

**Comment by FedeGueli** [comment]
> I guess Cornelius will once again designate this as a normal branch instead of recombinant branch.

No i dont think so here is quite clear recombination event

**Comment by FedeGueli** [comment]
4: 3 from different regions in China (Gansu, Hubei) and 1 from California

**Comment by FedeGueli** [comment]
This is quite interesting and still circulating in China.

**Comment by FedeGueli** [comment]
I ll close this one no samples from august still.
