### ISSUE TITLE
FY.4 sublineage with S:L212S in a branch with Orf1b:V2287I  (17) recently spreading in Japan 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#487]
I noticed an international spread branch of FY.4 defined by Orf1b:V2287I that has further acquired S:L212S.
S:L212S has been quite homoplasic at the end of original BA.2 era conferring some slight advantage.
As noticed by @hynnspylor XBB.1.22.1 has an apparent propension to acquire further S1 mutations so it is not surprising to see S:L212S appearing here.

Defining mutations:
FY.4 >> C7417T, ORF1b:V2287I (G20326A) > ORF1a:Y2171F (A6777T) > ORF3a:S177I (G25922T) > N:A218T (G28925A) > S:L212S (T22197C) 

Gisaid query : G20326A,T22197C, G28925A

Samples: 8 all from july 2023
3 of them are related to Japan but i suspect that the samples related Japan could be up to 6 or 7
cause 5 out of 8 samples are from airport surveillance in US ( three different states) 
First: 
hCoV-19/USA/DC-DFS-PHL-09818/2023 | Original | EPI_ISL_18011708 | 2023-06-14
Last:
hCoV-19/USA/CA-GBW-H10-012-6784/2023 | Original | EPI_ISL_18036887 | 2023-07-15

<Details>
<Summary> EPI_ISLs </summary>
EPI_ISL_17986666, EPI_ISL_18010943, EPI_ISL_18011708,
EPI_ISL_18013336, EPI_ISL_18036876, EPI_ISL_18036887,
EPI_ISL_18036950, EPI_ISL_18036959
 
</Details>

Tree:
![Schermata 2023-07-26 alle 17 05 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d7af63bc-bd61-4dd7-9349-21e61db98a6c)

![Schermata 2023-07-26 alle 17 06 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3237377f-9995-4e24-9349-d095aecc57cb)
![Schermata 2023-07-26 alle 17 06 37](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/235cc3b1-d4a6-459c-8af4-aa3ad7043332)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c339_12b1b0.json?label=id:node_10617443

**Comment by HynnSpylor** [comment]
3 more seqs updated. 1 from South Korea and 2 from US International Airport (1 seq shows the travel history from Japan)

**Comment by HynnSpylor** [comment]
2 more seqs from Japan

**Comment by FedeGueli** [comment]
> 2 more seqs from Japan

thx it is really super fast apparently

**Comment by ryhisner** [comment]
All the US sequences are either labeled as travel from Japan or else are in regions or cities that are major travel hubs. This must be spreading faster than we realize in Japan or we would not be seeing so many travel-related cases. I bet we see a big upload of these from Japan very soon.

**Comment by FedeGueli** [comment]
> All the US sequences are either labeled as travel from Japan or else are in regions or cities that are major travel hubs. This must be spreading faster than we realize in Japan or we would not be seeing so many travel-related cases. I bet we see a big upload of these from Japan very soon.

Agree, its doubling time is already very high.

Cc @corneliusroemer @thomaspeacock @angiehinrichs please take a look

**Comment by FedeGueli** [comment]
two more samples from Virginia

**Comment by HynnSpylor** [comment]
2 more seqs from Japan
I suggest it can be proposed in main page

**Comment by FedeGueli** [comment]
Yes def one of the fastest at the moment.

**Comment by FedeGueli** [comment]
FY.4.2 designated
