### ISSUE TITLE
XBB.1.16.6 (456-478)  + ORF1a:G268R (107 seqs, USA/Puerto Rico/Canada/South Korea/Sweden)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#488]
Sub-lineage of: XBB.1.16.6
Substitution on top of XBB.1.16.6: ORF1a:G268R (G1067A)
Earliest sequence: 2023-5-5, Puerto Rico — EPI_ISL_17737300
Most recent sequence: 2023-8-1, Canada — EPI_ISL_18076502
Countries circulating: Puerto Rico (34), USA (29), Canada (4), Sweden (1), South Korea (1)
Number of sequences: 69
GISAID nucleotide query: A12397G,G1067A,T22930A
CovSpectrum query: [XBB.1.16.6* (Nextclade) + ORF1a:G268R](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3Ag268r&nextcladePangoLineage=xbb.1.16.6*&)

This lineage constitutes around 68% of XBB.1.16.6 detected in Puerto Rico.

```{r, echo=FALSE}
EPI_ISL_17737300,EPI_ISL_17831589,EPI_ISL_17831590,EPI_ISL_17885200,EPI_ISL_17885218,EPI_ISL_17955916,EPI_ISL_17965545,EPI_ISL_17976398,EPI_ISL_17982616,EPI_ISL_17982660,EPI_ISL_17987279,EPI_ISL_17987280,EPI_ISL_18007683,EPI_ISL_18007740,EPI_ISL_18007757,EPI_ISL_18011181,EPI_ISL_18012180,EPI_ISL_18012182,EPI_ISL_18022460,EPI_ISL_18022834,EPI_ISL_18031646,EPI_ISL_18037715,EPI_ISL_18043011,EPI_ISL_18043014,EPI_ISL_18043028,EPI_ISL_18043039,EPI_ISL_18043043,EPI_ISL_18043122,EPI_ISL_18043156,EPI_ISL_18043183,EPI_ISL_18049290,EPI_ISL_18053320,EPI_ISL_18053996,EPI_ISL_18055150,EPI_ISL_18057246,EPI_ISL_18057353,EPI_ISL_18057792,EPI_ISL_18057879,EPI_ISL_18058025,EPI_ISL_18059984,EPI_ISL_18059993,EPI_ISL_18059996,EPI_ISL_18060013,EPI_ISL_18060029,EPI_ISL_18060032,EPI_ISL_18060036,EPI_ISL_18060662,EPI_ISL_18065611,EPI_ISL_18069135,EPI_ISL_18072545,EPI_ISL_18072573,EPI_ISL_18076438,EPI_ISL_18076502,EPI_ISL_18077423,EPI_ISL_18079062,EPI_ISL_18079969,EPI_ISL_18080251,EPI_ISL_18080770,EPI_ISL_18080773,EPI_ISL_18080949,EPI_ISL_18081426

```

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_97ad_15ab00.json?branchLabel=Spike%20mutations&label=id:node_6677304&showBranchLabels=all

![Screenshot 2023-07-26 at 14-16-09 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_97ad_15ab00 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/5cc90f19-6ded-4d9f-bdd5-9baea4cb48ab)

A few sequences have acquire a Spike mutation at S:L176V (C22088G) and the combination of S:V308L (G22484T) + S:K1086I (A24819T)
![Screenshot 2023-07-26 at 14-15-00 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ subtreeAuspice1_genome_97ad_15ab00 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/36845fcc-3a55-4ca3-a064-696061d90977)

[Relative growth advantage ](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3Ag268r&nextcladePangoLineage=xbb.1.16.6*&)
![Screenshot 2023-07-26 at 14-52-28 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/be3e8ee5-b187-4045-9f18-91f0e8871edb)

**Comment by FedeGueli** [comment]
This is quite surprisingly showing an advantage over EG.5.1.1 :
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A12397G%2CG1067A%2CT22930A&analysisMode=CompareToBaseline&

To me this should be proposed even if its profile doesnt point to any special profile.

**Comment by FedeGueli** [comment]
Please while proposing it  highlight briefly that this proposal comes from Puerto Rico Public Health Laboratory.

**Comment by FedeGueli** [comment]
I suggest in the headline to recall the main spike mutations or combination of them
