### ISSUE TITLE
Another (?) XBB.1.11 lineage acquired S:F486P, with ORF1a:S2103F/nsp3_S1285F (22 seqs, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#489]
**Defining Mutations:** XBB.1.11 > C3241T > C29095T > C2536T, C6573T(ORF1a:S2103F), C15045T > C6997T, T23018C(S:F486P)
**Query:** C3241T, C6573T, C6997T, T23018C
**Earliest seq:** 2023-04-06 (EPI_ISL_17780640, Hanoi, Vietnam)
**Latest seq:** 2023-07-06 (EPI_ISL_18041466, Miyazaki, Japan)
**Sampled Countries:** South Korea (7), Japan (6), China (5, Sichuan/2, Anhui/1, Shanghai/1, Yunnan/1), Austria (1), Israel (1), Spain (1), Vietnam (1)

<details><summary>Genomes: </summary>
EPI_ISL_17554729, EPI_ISL_17558200, EPI_ISL_17618864, EPI_ISL_17633003, EPI_ISL_17650861, EPI_ISL_17690500, EPI_ISL_17691135, EPI_ISL_17691275, EPI_ISL_17718440, EPI_ISL_17730411, EPI_ISL_17730517, EPI_ISL_17736084, EPI_ISL_17780640, EPI_ISL_17785360, EPI_ISL_17883071, EPI_ISL_17883192, EPI_ISL_17958600, EPI_ISL_17959662, EPI_ISL_17969972, EPI_ISL_18041261, EPI_ISL_18041459, EPI_ISL_18041466
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a92e_1e8cd0.json?f_userOrOld=uploaded%20sample&label=id:node_6779293

view from XBB.1.11 polytomy with nuc 2536 filter, upper hightlight branch is FP.4, lower is this proposal
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e6e588af-1c11-4595-92bc-f41c5c99ce42)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6529151e-3c43-452b-b4ec-c70ae62c39da)

**Trivia:**
- Need help to identify if it really is the sibling branch to cov-lineages/pango-designation#1490 that also acquired S:F486P, it shares the homoplastic C3241T, C2536T (and of course T23018C) with FP.4 (XBB.1.11.1.4), but they seems to be on different phylogenetic paths. Could this be a subset of FP.4 simply misplaced due to certain samples with dropout, or something new?
- I've checked there's no SGTF like FP.1 so far.

**Comment by AngieHinrichs** [comment]
> but in my view they are kept divided just by two/three sequences: EPI_ISL_17719711,EPI_ISL_17481626,EPI_ISL_17427836.

Yep, I'll prune those, re-optimize (which should put the branch in FP.4) and then let them be added back.  Thanks!

**Comment by FedeGueli** [comment]
> > but in my view they are kept divided just by two/three sequences: EPI_ISL_17719711,EPI_ISL_17481626,EPI_ISL_17427836.
> 
> Yep, I'll prune those, re-optimize (which should put the branch in FP.4) and then let them be added back. Thanks!

Thanks!

**Comment by FedeGueli** [comment]
@NkRMnZr please recheck this one in some days. if it have been merged back in FP.4 please close this one.

**Comment by FedeGueli** [comment]
Thank you @NkRMnZr for checking! Thx @AngieHinrichs for fixing it!
