### ISSUE TITLE
FY.3 (XBB.1.22.1.3) sublineage with S:I210T (T22191C) emerged in China (27seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#49]
Defining mutations: FY.3>C23191T>C5544T(ORF1a:T1760I), T22191C (S:I210T)
GISAID query: Spike_Y200C, Spike_I210T, T28297C
Earliest seq: 2023-04-18 (Jiangsu Province, China, EPI_ISL_17637401)
Most recent seq: 2023-05-04 (Shanghai Municipality, EPI_ISL_17645765)
Countries detected: China (18, Shanghai Municipality 9, Hubei Province 6, Jiangsu Province 3)

Usher Tree:
![QQ截图20230513003851](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/e39f00d1-b0cd-4313-a401-0a21e433244b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a05a_e4a810.json
Based on FY.3 (XBB.1.22.1+ORF1a:E750K) which is highly concentrated in China, a branch with S:I210T emerged recently. S:I210T was mainly in B.1.619* (once popular in South Korea) and B.1.640.1 lineages. 
Genomes:
EPI_ISL_17619115, EPI_ISL_17619169, EPI_ISL_17625260,
EPI_ISL_17625280, EPI_ISL_17625311, EPI_ISL_17625409,
EPI_ISL_17625551, EPI_ISL_17625563, EPI_ISL_17637397,
EPI_ISL_17637401, EPI_ISL_17637426, EPI_ISL_17645438,
EPI_ISL_17645454, EPI_ISL_17645740, EPI_ISL_17645764-17645765,
EPI_ISL_17645806, EPI_ISL_17646194

**Comment by aviczhl2** [comment]
One of them has S:69-,70-( 17625280), while the other 17 doesn't.

**Comment by Memorablea** [comment]
21 sequences 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_33b84_1cab90.json?f_userOrOld=uploaded%20sample&label=id:node_3573490
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/9d3b366f-2722-42c7-b1a3-745f74128bed)

**Comment by HynnSpylor** [comment]
28 seqs now

**Comment by HynnSpylor** [comment]
27 seqs now （6 updated today, Hube Province)
