### ISSUE TITLE
XBB.1.16 mini-saltation with ORF1a:I2903T, ORF1b:M2269I, S:D936V and ORF8:H17R (24 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#490]
**Defining Mutations:** `XBB.1.16` > `C18060T` > `C27600T` > `T8973C(ORF1a:I2903T/nsp4_I140T)`, `G20274T(ORF1b:M2269I/nsp15_M218I)`, `A24369T(S:D936V)`, `A27943G(ORF8:H17R)`
**Query:** `G20274T, A24369T, A27943G`
**Earliest seq:** 2023-05-04 (`EPI_ISL_17881765`, Kanagawa, Japan)
**Latest seq:** 2023-06-29 (`EPI_ISL_18033637`, Dublin, Ireland)
**Sampled Countries:** Canada (5, Québec), USA (3, California, Florida, Texas), Japan (2), Ireland (1), Israel (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17803797, EPI_ISL_17881765, EPI_ISL_17950770, EPI_ISL_17959376, EPI_ISL_17990397, EPI_ISL_17990497, EPI_ISL_17990506, EPI_ISL_17990555, EPI_ISL_17998482, EPI_ISL_17998500, EPI_ISL_18008372, EPI_ISL_18033637`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41f28_1f90c0.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0ee77f6f-95e0-4c9b-8dea-7aadc5f005ca)

**Trivia:**
- `S:936V` is predicted to be slightly deleterious (`936H` is predicted to be most fit by a huge margin), however, this mini-saltation lineage has not only spread to multiple countries, but also got futher step mini-saltation, for example `Japan/PG-545412/2023|EPI_ISL_18008372|2023-06-26` with S:Q690R and ORF7a:Q94*

**Comment by FedeGueli** [comment]
cant compete: https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G20274T%2CA24369T%2CA27943G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
too slow to be worth tracking it.
