### ISSUE TITLE
FK.1.2.1 with S:T286I (70 seqs, mainly in Finland, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#491]
**Defining Mutations:** `FK.1.2.1 > C22419T(S:T286I)`
**Query:** `C2937T, C22419T`
**Earliest seq:** 2023-03-17 (`EPI_ISL_17325808`, Galway, Ireland)
**Latest seq:** 2023-07-10 (`EPI_ISL_18013159`, Copenhagen, Denmark)
**Sampled Countries:** Finland (58), UK (3, England/2, Northern Ireland/1), Australia (1, SA), Denmark (1), France (1), Germany (1), Ireland (1), Luxembourg (1), USA (1, Washington)

<details><summary>Genomes: </summary>

`EPI_ISL_17325808, EPI_ISL_17519901, EPI_ISL_17540420, EPI_ISL_17540471, EPI_ISL_17540477, EPI_ISL_17540482-17540483, EPI_ISL_17540494, EPI_ISL_17540498, EPI_ISL_17540504-17540506, EPI_ISL_17540509, EPI_ISL_17598021-17598022, EPI_ISL_17598029, EPI_ISL_17598033, EPI_ISL_17598035, EPI_ISL_17598043, EPI_ISL_17598053, EPI_ISL_17598075, EPI_ISL_17598081, EPI_ISL_17598083-17598084, EPI_ISL_17598092, EPI_ISL_17598102, EPI_ISL_17598569, EPI_ISL_17633052, EPI_ISL_17661552, EPI_ISL_17661558, EPI_ISL_17661560-17661561, EPI_ISL_17661567, EPI_ISL_17661589, EPI_ISL_17661641, EPI_ISL_17679966, EPI_ISL_17699076, EPI_ISL_17699078, EPI_ISL_17699114, EPI_ISL_17699116, EPI_ISL_17763092, EPI_ISL_17763251, EPI_ISL_17763268, EPI_ISL_17763286, EPI_ISL_17763313, EPI_ISL_17763329, EPI_ISL_17763386, EPI_ISL_17763388, EPI_ISL_17763402, EPI_ISL_17763408, EPI_ISL_17763411, EPI_ISL_17820794, EPI_ISL_17833562, EPI_ISL_17849617, EPI_ISL_17974295, EPI_ISL_17974336, EPI_ISL_17974392-17974393, EPI_ISL_17974476, EPI_ISL_17974550, EPI_ISL_17974556, EPI_ISL_17977330, EPI_ISL_17994704, EPI_ISL_17994709, EPI_ISL_17994761, EPI_ISL_17994763, EPI_ISL_17994813, EPI_ISL_18013159`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f955_2051c0.json?f_userOrOld=uploaded%20sample
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ac9f04a4-abf3-415d-9463-50c11bdd759d)

**Trivia:**
- `S:T286I` is predicted to be deleterious, could this be some superspreader event?
![intl](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/05ed5826-b0ca-4675-9f4c-67c33b7bd5a5)

**Comment by FedeGueli** [comment]
slow in comparison to EG.5 but worth monitoring it cause it is still around.

**Comment by FedeGueli** [comment]
Closing this for now.
