### ISSUE TITLE
BA.2.9 saltation with N:D63E, S:R346T, M:I161F, S:I68T, S:L216F, S:N440R, S:K444R, S:Q954D and S:V1189A (4 seqs, Sweden)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#492]
**Defining Mutations:** BA.2.9 [C2790T > C22792T > C25624T(ORF3a:H78Y)] > `C28462A(N:D63E)` > `C9857T, A13131G(ORF1a:Q4289R/nsp10_Q36R), G22599C(S:R346T), A27003T(M:I161F)` > `G434A(ORF1a:E57K/nsp1_E57K), C583T, C4234T, A10630G, T10885C, C11036G(ORF1a:L3591V/nsp6_L22V), G12569A(ORF1a:V4102I/nsp8_V160I), G13385A(ORF1a:G4374S/nsp10_G121S), C14120A(ORF1b:P218Q/nsp12_P227Q), T21765C(S:I68T), C22208T(S:L216F), A22881G(S:N440R), A22893G(S:K444R), C23029T, C24422G(S:Q954D), T25128C(S:V1189A)`

**Query:** `A22881G,C24422G,T25128C`
**Earliest seq:** 2023-05-09 (`EPI_ISL_17710673`, Halland, Sweden)
**Latest seq:** 2023-07-06 (`EPI_ISL_18010720`, Halland, Sweden)
**Sampled Countries:** Sweden(3)

<details><summary>Genomes: </summary>
`EPI_ISL_17710673, EPI_ISL_17830762, EPI_ISL_18010720`
</details>

**Saltation Profile:**
Mutations on nearest branch:

```
nuc	unique	G434A, C4234T, A10630G, T10885C, C11036G, G12569A, C14120A, C22208T, A22881G, A22893G, C24422G, T25128C
nuc	homoplasies	C583T, G13385A, T21765C, C23029T
ORF1ab	unique	E57K, L3591V, V4102I, P4619Q
ORF1ab	homoplasies	G4374S
S	unique	L216F, K440R, K444R, H954D, V1189A
S	homoplasies	I68T
```
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6ca0e038-eca0-48ba-9381-ebe8688793d6)

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_50a4_223cb0.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/da596a0b-6237-47d1-85a6-1ba298f8e90b)

**Trivia:**
- UShER placed this on `G22775A/S:D405N` flip-flop branch, if neglect this, this lineage should fit the definition of `BA.2.9`.
- Could these sequences be from single chronically infected patient?
- This lineage modifed 2 spike mutations introduced from `BA.2`: `N440K>R` and `Q954H>D`

**Comment by FedeGueli** [comment]
Yeah we spotted this too. i think it is a single chronic infection.

**Comment by silcn** [comment]
S:Q954D (really S:H954D) is extremely rare, only 9 sequences in the whole pandemic - a BA.1.1 in early 2022, a 5-sequence branch of XBB.1.5.43 from Australia earlier this year, and these three. H954 isn't fixed, it changes to Y, R or L from time to time, but it really doesn't like to revert, and D954 has been pretty heavily selected against so far.

**Comment by FedeGueli** [comment]
no new seqs
