### ISSUE TITLE
XBB.1 saltation with ORF1a:G2814S (nsp4_G51S), S:R403K, S:L461I, S:N556S and ORF7a:P34L (5 seqs, China, India, Sweden, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#493]
**Defining Mutations:** XBB.1 [G27915T/ORF8:G8*] > `T4579A` > `G6850A, G8705A(ORF1a:G2814S), C11455T, T18351C, G22770A(S:R403K), C22943A(S:L461I), C23086T, A23229G(S:N556S), C27494T(ORF7a:P34L)`
**Query:** `G22770A, C22943A, A23229G`
**Earliest seq:** 2023-05-21 (`EPI_ISL_17770005`, Shanghai, China, with travel history to: Ethiopia)
**Latest seq:** 2023-06-28 (`EPI_ISL_18034530`, Guangdong, China with unknown travel history)
**Sampled Countries:** China (2, Shanghai, Guangdong), India (1, Hyderabad)

<details><summary>Genomes: </summary>
`EPI_ISL_17770005, EPI_ISL_18034530, EPI_ISL_18042397`
</details>

**Saltation Profile:**
mutation on nearest branch:

```
nuc	unique	G6850A, G8705A, T18351C, C22943A, A23229G, C27494T
nuc	homoplasies	C11455T, G22770A, C23086T
ORF1ab	unique	G2814S
S	unique	L461I, N556S
S	homoplasies	R403K
ORF7a	unique	P34L
```
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3b77cb12-7404-4ef6-ba27-ad4cfcb24a34)

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d68f_242ba0.json?f_userOrOld=uploaded%20sample
![R403K](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/eee8e9df-35fc-4b6c-a9ac-be4bb241dcfd)

**Trivia:**
- 2 Chinese sequences are associated with travel history

<details><summary>Shanghai/SCDC-HG0523-1064/2023|EPI_ISL_17770005|2023-05-21</summary>

```
FEATURES             Location/Qualifiers
     source          1..29792
                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230523-1064/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 55; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-05-21"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Ethiopia"
```

</details>

- `Guangdong/GDCDC_GZHG_1246/2023|EPI_ISL_18034530|2023-06-28` is sampled by Guangzhou Customs without metadata showing exact travel history.
- `S:L461I` only sampled about 400 times during the whole pandemic, and is not predicted to have any significant impact on immune escape, nor binding affinity, nor fitness; `S:N556S` is about the same rarity, and is predicted to be slightly deleterious.

**Comment by aviczhl2** [comment]
This doesn't have 486P

**Comment by FedeGueli** [comment]
> No seqs incoming, tracking it privately

one more from Sweden EPI_ISL_18099936

**Comment by FedeGueli** [comment]
closing this for now, nothing happened. in more than one month.

**Comment by Over-There-Is** [comment]
45 now, including 7 submitted by Ethiopia

**Comment by xz-keg** [comment]
Yeah a lot of old seqs of this branch are submitted recently.
