### ISSUE TITLE
EG.1.3 saltation with S:A222V, S:D253Y and 3 non-Spike aa mutations in Sweden (19 seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#494]
Defining mutations:
EG.1.3>G1914A (ORF1a:R550H = NSP2_R370H), T6394A (ORF1a:D2043E = NSP3_D1225E), G15372A, C18508T (ORF1b:L1681F = NSP14_L157F), C22227T (S:A222V), C22264T, G22319T (S:D253Y) (edited)

GISAID query: T6394A, G15372T, C22227T, G22319T
Earliest seq: 2023-06-09 (Sweden, EPI_ISL_17804180)
Most recent seq: 2023-07-13 (Sweden, EPI_ISL_17990584)
Countries detected: Sweden (13)

Usher Tree:
<img width="899" alt="屏幕截图 2023-07-27 194106" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/e0ffb12a-4ad3-44a6-a721-2dd068e909cd">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18115_248fd0.json
S:A222V was popular in B.1.177, some Delta (B.1.617.2*) lineages and nowadays in XBC* lineages. S:D253Y is another attempt for site S:D253 (S:D253G in XBB.2*)

Genomes:
EPI_ISL_17804180, EPI_ISL_17950806, EPI_ISL_17950816-17950817, EPI_ISL_17950821, EPI_ISL_17950842, EPI_ISL_17969285,
EPI_ISL_17990578, EPI_ISL_17990584, EPI_ISL_17990662, EPI_ISL_17990672, EPI_ISL_18008250, EPI_ISL_18010813,

**Comment by FedeGueli** [comment]
Jumped to 19, it could be a swedish cluster but better to propose it
