### ISSUE TITLE
Multiple XBB.1.5.51 branches with S:T478R (99/19/2)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#495]
```[tasklist]
### Multiple XBB.1.5.51 branches with S:T478R
- [ ] Branch 1: Transferred to cov-lineages/pango-designation#2186 XBB.1.5.51 > C22995G(**S:T478R**)
- [ ] Branch 2: XBB.1.5.51 > A3379G > C1875T(ORF1a:A537V), C14529T, C22498T, C22995G(**S:T478R**), C27600T [Query:`C14529T, C22498T, C22995G`, 22 seqs, 09/01]
- [ ] Branch 3: XBB.1.5.51 > A3379G > T14658A > T26430C > C9559T > C22995G(**S:T478R**) [Query: `A3379G, C22995G, T26430C`, 2 seqs, 07/18]
- [ ] _Further step_ with **S:F456L** from **Branch 1**: XBB.1.5.51 > C22995G(**S:T478R**) > A28025G > A507G(ORF1a:H81R) > C28507T(ORF9b:A75V) > G10523C(ORF1a:V3420L), A19134G, C21597A(**S:S12Y**), T22928C(**S:F456L**), C27920T [Query: `C21597A, T22928C, C27920T`, 4 seqs, 07/10]
- [ ] _Further step_ with **S:Q613H** from **Branch 2**: XBB.1.5.51 > A3379G > C1875T(ORF1a:A537V), C14529T, C22498T, C22995G(**S:T478R**), C27600T > T6274C, C11094T(ORF1a:A3610V), C11824T, T12175C, C13957T(ORF1b:R164C), C21855T(**S:S98F**), G23401T(**S:Q613H**) [Query: `T12175C, C21855T, G23401T`, 9 seqs, 09/01]
```

#### Branch 1:

<details><summary>Transferred</summary>

_Transferred to cov-lineages/pango-designation#2186_

**Defining Mutations:** `XBB.1.5.51` > `C22995G(S:T478R)`
**Query:** `A9291C, C25553T, C22995G, -T19209G, -A3379G`
**Earliest seq:** 2023-01-24 (`EPI_ISL_16892598`, South Carolina, USA)
**Latest seq:** 2023-07-08 (`EPI_ISL_18008689`, Oregon, USA)
**Sampled Countries:** USA (48), Spain (12), Mexico (7), Austria (4), France (3), Germany (3), Netherlands (2), Belgium (1), Chile (1), India (1), Ireland (1), Peru (1), Sweden (1), UK (1, England)

<details><summary>Genomes: </summary>

`EPI_ISL_16892598, EPI_ISL_16944857, EPI_ISL_16945621, EPI_ISL_16992959, EPI_ISL_17127174, EPI_ISL_17170239, EPI_ISL_17201936, EPI_ISL_17250533, EPI_ISL_17278361, EPI_ISL_17279062, EPI_ISL_17384922, EPI_ISL_17384974, EPI_ISL_17411502, EPI_ISL_17412225, EPI_ISL_17417735, EPI_ISL_17417866, EPI_ISL_17430300, EPI_ISL_17446687, EPI_ISL_17465568, EPI_ISL_17467427, EPI_ISL_17471954, EPI_ISL_17476429, EPI_ISL_17477756, EPI_ISL_17497548, EPI_ISL_17519071, EPI_ISL_17546901, EPI_ISL_17554337, EPI_ISL_17588627, EPI_ISL_17591119, EPI_ISL_17591193, EPI_ISL_17591344, EPI_ISL_17597795, EPI_ISL_17612881, EPI_ISL_17651419, EPI_ISL_17664377, EPI_ISL_17664408, EPI_ISL_17664436, EPI_ISL_17665628-17665629, EPI_ISL_17667805, EPI_ISL_17712119, EPI_ISL_17723015, EPI_ISL_17765412, EPI_ISL_17782135, EPI_ISL_17785442, EPI_ISL_17788559, EPI_ISL_17791848, EPI_ISL_17791890, EPI_ISL_17797810, EPI_ISL_17805062, EPI_ISL_17814403, EPI_ISL_17833149, EPI_ISL_17839169, EPI_ISL_17842452, EPI_ISL_17844518, EPI_ISL_17845937, EPI_ISL_17853478, EPI_ISL_17861254, EPI_ISL_17880945, EPI_ISL_17880985, EPI_ISL_17881020, EPI_ISL_17885008, EPI_ISL_17950861, EPI_ISL_17950930, EPI_ISL_17956100, EPI_ISL_17956377, EPI_ISL_17966204, EPI_ISL_17971535, EPI_ISL_17971542, EPI_ISL_17972220, EPI_ISL_17976115, EPI_ISL_17976128, EPI_ISL_17976408, EPI_ISL_17976649, EPI_ISL_17976744, EPI_ISL_17978844, EPI_ISL_17987408, EPI_ISL_17990370, EPI_ISL_17997687, EPI_ISL_17997727, EPI_ISL_18008689, EPI_ISL_18011891, EPI_ISL_18026796, EPI_ISL_18038146, EPI_ISL_18042399`

</details>

</details>

---

#### Branch 2

**Defining Mutations:** `XBB.1.5.51` > `A3379G` > `C1875T(ORF1a:A537V), C14529T, C22498T, C22995G(S:T478R), C27600T`
**Query:** `C14529T, C22498T, C22995G`
**Earliest seq:** 2023-03-07 (`EPI_ISL_17249468`, Maryland, USA)
**Latest seq:** 2023-07-04 (`EPI_ISL_17997281`, Hongkong, China)
**Sampled Countries:** USA (8, many with travel history to: Ghana), Ireland (3), Bulgaria (1), China (1, Hongkong), Finland (1), Germany (1), UK (1, England)

<details><summary>Genomes: </summary>

`EPI_ISL_17249468, EPI_ISL_17428406, EPI_ISL_17428527, EPI_ISL_17468642, EPI_ISL_17669173, EPI_ISL_17716722, EPI_ISL_17716765, EPI_ISL_17716835, EPI_ISL_17812678, EPI_ISL_17820969, EPI_ISL_17958969-17958970, EPI_ISL_17960218, EPI_ISL_17974335, EPI_ISL_17997281, EPI_ISL_18033613`

</details>

---

#### Branch 3

**Defining Mutations:** Branch 3: `XBB.1.5.51` > `A3379G` > `T14658A `> `T26430C` > `C9559T `> `C22995G(S:T478R)`
**Query:** `A3379G, C22995G, T26430C`
**Earliest seq:** 2023-06-08 (`EPI_ISL_17954550`, Guatemala)
**Latest seq:** 2023-07-11 (`EPI_ISL_17996882`, Ontario, Canada)
**Sampled Countries:** Guatemala (1), Canada (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17954550, EPI_ISL_17996882`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1dc96_24c530.json?c=gt-nuc_3379&f_userOrOld=uploaded%20sample

view from XBB.1.5.51 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/16abedb0-7584-4a42-91c2-cecf757ce26c)

<details><summary>details for Branch 1</summary>

![branch 1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ec3df1cf-7342-4a94-b4c1-0a3f4752f5a8)

</details>

<details><summary>details for Branch 2 & 3</summary>

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_304a6_256a90.json?c=gt-S_478,613&f_userOrOld=uploaded%20sample
![branch2+3](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7ec81500-6155-4c23-a5bc-39a3e5700510)

</details>

**Comment by FedeGueli** [comment]
Very good catch

**Comment by FedeGueli** [comment]
Please propose branch 1 on the main pango page.
