### ISSUE TITLE
Potential UShER misplacement, or a XBB.1.5* × XBB.1.9.2* recombinant with 4 consecutive nsp14 private mutations (238 seqs, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#496]
**Defining Mutations:** XBB.1.9.2 > T11956C_reversion > A16878T_reversion > A27507C_reversion > ORF1b:D1914E(T19209G), ORF1b:R1915G(A19210G, A19212G), ORF1b:Y1916C(A19214G), ORF1b:P1917H(C19217A) > T16878A_reversion, C27507A_reversion > A5720G_reversion(ORF1a:S1819G_reversion), T12789C_reversion(ORF1a:I4175T_reversion) > C28297T_reversion(ORF9b:T5I_reversion) > T17124C

(edited from orf1a>orf1b)

**Query:** T19209G, A19210G, A19212G, A19214G, C19217A, T17124C, T23018C, -G15957T, -G1466A, -C2695T
**Earliest seq:** Canada/QC-L00571143001/2022|EPI_ISL_16489940|2022-12-27
**Latest seq:** Spain/MD-H12O_296/2023|EPI_ISL_17811470|2023-06-04
**Sampled Countries:** Canada (148), USA (54), Colombia (14), France (8), Spain (7), South Africa (2), Netherlands (1), Philippines (1)

<details><summary>Genomes: </summary>
EPI_ISL_16489940, EPI_ISL_16489952, EPI_ISL_16541374, EPI_ISL_16663872, EPI_ISL_16732094, EPI_ISL_16732097, EPI_ISL_16732100, EPI_ISL_16732107, EPI_ISL_16732109, EPI_ISL_16732161, EPI_ISL_16732182, EPI_ISL_16732215, EPI_ISL_16818549, EPI_ISL_16837884, EPI_ISL_16837888, EPI_ISL_16837900, EPI_ISL_16837915, EPI_ISL_16870789, EPI_ISL_16919585, EPI_ISL_16986131, EPI_ISL_16986136-16986140, EPI_ISL_16986143, EPI_ISL_16986148, EPI_ISL_16986151, EPI_ISL_16986159-16986160, EPI_ISL_16986163-16986165, EPI_ISL_16986169, EPI_ISL_16986171-16986172, EPI_ISL_16986174, EPI_ISL_16986187, EPI_ISL_16986204-16986205, EPI_ISL_16986207, EPI_ISL_16986210, EPI_ISL_16986214, EPI_ISL_16986216, EPI_ISL_16986228, EPI_ISL_16986231, EPI_ISL_16986990-16986991, EPI_ISL_16986993, EPI_ISL_16986997, EPI_ISL_16986999, EPI_ISL_16987020, EPI_ISL_17034774, EPI_ISL_17034779, EPI_ISL_17034781, EPI_ISL_17034784, EPI_ISL_17034790, EPI_ISL_17034793, EPI_ISL_17034806-17034807, EPI_ISL_17034814, EPI_ISL_17034816, EPI_ISL_17035051, EPI_ISL_17035208, EPI_ISL_17035226, EPI_ISL_17035230, EPI_ISL_17035267, EPI_ISL_17035278, EPI_ISL_17085888, EPI_ISL_17085891, EPI_ISL_17085907, EPI_ISL_17085918, EPI_ISL_17180673, EPI_ISL_17180721, EPI_ISL_17180916, EPI_ISL_17180947, EPI_ISL_17181072, EPI_ISL_17181114, EPI_ISL_17181126, EPI_ISL_17181209, EPI_ISL_17181372, EPI_ISL_17182104, EPI_ISL_17195638, EPI_ISL_17195641, EPI_ISL_17195673, EPI_ISL_17195687, EPI_ISL_17195718, EPI_ISL_17195734, EPI_ISL_17195739, EPI_ISL_17195754, EPI_ISL_17270277, EPI_ISL_17270279, EPI_ISL_17270282, EPI_ISL_17270285, EPI_ISL_17270296, EPI_ISL_17270298-17270301, EPI_ISL_17270310-17270311, EPI_ISL_17305115, EPI_ISL_17305128, EPI_ISL_17321741, EPI_ISL_17321743, EPI_ISL_17321781, EPI_ISL_17358307, EPI_ISL_17390273, EPI_ISL_17398449, EPI_ISL_17398456, EPI_ISL_17398459, EPI_ISL_17437763, EPI_ISL_17437776, EPI_ISL_17437797, EPI_ISL_17437800, EPI_ISL_17437806, EPI_ISL_17437812, EPI_ISL_17437928, EPI_ISL_17438003, EPI_ISL_17438069, EPI_ISL_17438121, EPI_ISL_17438127, EPI_ISL_17438132, EPI_ISL_17438187, EPI_ISL_17443372, EPI_ISL_17464853, EPI_ISL_17497788, EPI_ISL_17497792, EPI_ISL_17497797, EPI_ISL_17506781, EPI_ISL_17523119, EPI_ISL_17523186, EPI_ISL_17523224, EPI_ISL_17523263, EPI_ISL_17523332, EPI_ISL_17523378, EPI_ISL_17523390, EPI_ISL_17523505, EPI_ISL_17523580, EPI_ISL_17523647, EPI_ISL_17523651, EPI_ISL_17523655, EPI_ISL_17523789, EPI_ISL_17523806, EPI_ISL_17523887, EPI_ISL_17523890, EPI_ISL_17523929, EPI_ISL_17523944, EPI_ISL_17523950, EPI_ISL_17550169, EPI_ISL_17550171, EPI_ISL_17550179, EPI_ISL_17550185, EPI_ISL_17550189, EPI_ISL_17587418-17587419, EPI_ISL_17587425, EPI_ISL_17587430, EPI_ISL_17587434, EPI_ISL_17587440, EPI_ISL_17587445, EPI_ISL_17587477, EPI_ISL_17587489, EPI_ISL_17587494, EPI_ISL_17587496-17587497, EPI_ISL_17587499, EPI_ISL_17587502, EPI_ISL_17587505, EPI_ISL_17587532, EPI_ISL_17587534, EPI_ISL_17588379, EPI_ISL_17588468, EPI_ISL_17611488, EPI_ISL_17611494, EPI_ISL_17611499, EPI_ISL_17611529-17611530, EPI_ISL_17611536, EPI_ISL_17611577, EPI_ISL_17611601-17611602, EPI_ISL_17611611, EPI_ISL_17611627, EPI_ISL_17611636, EPI_ISL_17611650, EPI_ISL_17611657, EPI_ISL_17611664, EPI_ISL_17611697, EPI_ISL_17611702, EPI_ISL_17611708, EPI_ISL_17611711, EPI_ISL_17611713, EPI_ISL_17611726, EPI_ISL_17611731, EPI_ISL_17611736, EPI_ISL_17611748, EPI_ISL_17611761, EPI_ISL_17611811, EPI_ISL_17611817, EPI_ISL_17611819, EPI_ISL_17641685, EPI_ISL_17641691, EPI_ISL_17641719, EPI_ISL_17641756-17641757, EPI_ISL_17641781, EPI_ISL_17641783, EPI_ISL_17641785-17641786, EPI_ISL_17641788, EPI_ISL_17641791, EPI_ISL_17652664-17652665, EPI_ISL_17652676, EPI_ISL_17652699, EPI_ISL_17652704-17652705, EPI_ISL_17687442, EPI_ISL_17687451, EPI_ISL_17717609, EPI_ISL_17717611, EPI_ISL_17717625, EPI_ISL_17717629, EPI_ISL_17722863, EPI_ISL_17763736, EPI_ISL_17775778, EPI_ISL_17776130, EPI_ISL_17777747, EPI_ISL_17810263, EPI_ISL_17811465, EPI_ISL_17811470, EPI_ISL_17978191, EPI_ISL_17978259, EPI_ISL_18012304
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40afb_25ffd0.json?f_userOrOld=uploaded%20sample

view from XBB.1.9.2 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/87991bf0-cf40-4620-aed4-61b650a436d4)

**Trivia:**
- Need help identifying if this is not a placement error, and the 4 consecutive nsp14 mutations are real.
- If it is really a recombinant between XBB.1.5* and XBB.1.9.2*, it drops G5720A(ORF1a:G1819S), C12789T(ORF1a:T4175I), A16878T, A27507C, T28297C(ORF9b:I5T) from XBB.1.9.2 and gained XBB.1.5's hallmark T17124C, with private mutations: ORF1b:D1914E(T19209G), ORF1b:R1915G(A19210G, A19212G), ORF1b:Y1916C(A19214G), ORF1b:P1917H(C19217A)
![weird](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/619bf5b8-5c28-4849-b7d9-5679cc8214e3) (edited a>b)
- By the way, XBB.1.9.2 now seems misplaced under XBB.1.9.1's C11956T

**Comment by FedeGueli** [comment]
@ryhisner is this real?

**Comment by aviczhl2** [comment]
what happens around 19209-19217?

**Comment by aviczhl2** [comment]
I searched for T19209G,A19210G,A19212G,A19214G,C19217A, and found 9065 seqs on GISAID. Seems quite common?

**Comment by ryhisner** [comment]
This is a common sequencing artifact. It used to appear in about half of all Russian sequences, as well as many others.

**Comment by aviczhl2** [comment]
> This is a common sequencing artifact. It used to appear in about half of all Russian sequences, as well as many others.
> 
> I think most labs fixed whatever issue was causing this problem, but not all apparently.

@AngieHinrichs  maybe we shall mask out 19209-19217?

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs maybe we shall mask out 19209-19217? I find this one has already caused a few flip-flop reversion branches, as it containes a lot of "common” mutations.

That's a lot of bases to mask, although since they're not in Spike, maybe it's not as big of a loss to lose visibility on them?  

I have excluded 250 sequences with spurious mutations in that range so far, because they were causing trouble for lineages -- I will take a look at these and probably exclude some more.  Somewhere in BA.5 there is a really large branch of almost entirely Russian sequences with that pattern -- I ended up not excluding those because the problem seemed pretty much confined to Russian sequences at that point.  But if it continues to cause trouble and if nobody cares much about mutations in that range, I would consider masking.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs
