### ISSUE TITLE
XBB.1.5's T22873C (S:N437N) branch (187 seqs, mainly in China, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#498]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `T22873C` (ignored `nuc 26822 C/T` flip-flop)
**Query:** `T17124C, T23018C, T22873C, -C27643T, -G1820A, -T20479C, -T3547C, -T10204C, -A2948G`
**Earliest seq:** 2023-02-03 (`EPI_ISL_17222355`, Michigan, USA)
**Latest seq:** 2023-06-24 (`EPI_ISL_17988894`, Sichuan, China)
**Sampled Countries:** China (149, Gansu/68, Xinjiang/20, Shanghai/14, Yunnan/8, Hubei/7, Qinghai/7, Guangdong/6, Shanxi/4, Sichuan/4, Jiangsu/3, Jiangxi/2, Henan/2, Anhui/1, Beijing/1, Fujian/1, Heilongjiang/1), USA (14, California/9, NJ/3, Michigan/1, NY/1), Australia (1, Vic), Austria (1), Japan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17222355, EPI_ISL_17239032, EPI_ISL_17420058, EPI_ISL_17420171, EPI_ISL_17420655, EPI_ISL_17467508, EPI_ISL_17467620, EPI_ISL_17467728, EPI_ISL_17467876, EPI_ISL_17529495, EPI_ISL_17545649, EPI_ISL_17584969, EPI_ISL_17618686, EPI_ISL_17619251, EPI_ISL_17625277, EPI_ISL_17625437, EPI_ISL_17625443, EPI_ISL_17625476, EPI_ISL_17625490, EPI_ISL_17625534, EPI_ISL_17638121, EPI_ISL_17645400, EPI_ISL_17645771, EPI_ISL_17652397, EPI_ISL_17652401, EPI_ISL_17671964, EPI_ISL_17683990, EPI_ISL_17684068, EPI_ISL_17684235-17684237, EPI_ISL_17684261, EPI_ISL_17684347, EPI_ISL_17684408, EPI_ISL_17684477, EPI_ISL_17684480, EPI_ISL_17684486, EPI_ISL_17696905, EPI_ISL_17697676, EPI_ISL_17697904, EPI_ISL_17698335, EPI_ISL_17703998, EPI_ISL_17704063, EPI_ISL_17704065, EPI_ISL_17704238, EPI_ISL_17714313, EPI_ISL_17714420, EPI_ISL_17718363, EPI_ISL_17725355, EPI_ISL_17729979, EPI_ISL_17730018, EPI_ISL_17744617, EPI_ISL_17744621-17744623, EPI_ISL_17744627, EPI_ISL_17744777, EPI_ISL_17770089, EPI_ISL_17770407, EPI_ISL_17770409, EPI_ISL_17775138, EPI_ISL_17775143, EPI_ISL_17775203, EPI_ISL_17775205, EPI_ISL_17775249, EPI_ISL_17775318, EPI_ISL_17775323, EPI_ISL_17775355, EPI_ISL_17775492, EPI_ISL_17775562, EPI_ISL_17775578, EPI_ISL_17775595, EPI_ISL_17775636, EPI_ISL_17775661, EPI_ISL_17775670, EPI_ISL_17778559, EPI_ISL_17778580-17778583, EPI_ISL_17778586-17778588, EPI_ISL_17778591, EPI_ISL_17778612, EPI_ISL_17778652, EPI_ISL_17778692, EPI_ISL_17778764, EPI_ISL_17783569-17783573, EPI_ISL_17783577, EPI_ISL_17783579, EPI_ISL_17784865, EPI_ISL_17785321, EPI_ISL_17794680, EPI_ISL_17794717, EPI_ISL_17795024, EPI_ISL_17795680, EPI_ISL_17795723, EPI_ISL_17822900, EPI_ISL_17830291, EPI_ISL_17830307, EPI_ISL_17836326-17836327, EPI_ISL_17836416, EPI_ISL_17836750, EPI_ISL_17836982, EPI_ISL_17837043-17837044, EPI_ISL_17837052, EPI_ISL_17837057, EPI_ISL_17850310, EPI_ISL_17855156, EPI_ISL_17855470, EPI_ISL_17856130, EPI_ISL_17856382, EPI_ISL_17951246, EPI_ISL_17951251, EPI_ISL_17951262, EPI_ISL_17956962, EPI_ISL_17957171, EPI_ISL_17966420, EPI_ISL_17978590, EPI_ISL_17980912, EPI_ISL_17987602, EPI_ISL_17988147, EPI_ISL_17988894, EPI_ISL_17994624, EPI_ISL_17998769, EPI_ISL_17998773, EPI_ISL_17998780, EPI_ISL_17998782, EPI_ISL_17998785-17998786, EPI_ISL_17998797, EPI_ISL_17998801, EPI_ISL_17998805, EPI_ISL_17998807, EPI_ISL_17998816-17998817, EPI_ISL_17998822, EPI_ISL_17998824-17998825, EPI_ISL_17998830-17998831, EPI_ISL_17998834, EPI_ISL_17998843, EPI_ISL_17998845, EPI_ISL_17998850, EPI_ISL_17998857, EPI_ISL_17998860, EPI_ISL_17998878, EPI_ISL_17998883, EPI_ISL_17998918, EPI_ISL_18009940, EPI_ISL_18012340-18012341, EPI_ISL_18034004, EPI_ISL_18034761, EPI_ISL_18035182, EPI_ISL_18036009, EPI_ISL_18040204, EPI_ISL_18040206`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43c0d_335130.json?f_userOrOld=uploaded%20sample&label=id:node_7002582
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b84ce894-a400-4304-8ab7-583593345ab4)

**Trivia:**
- Proposed lineage sits on `nuc 26822 C/T` flip-flop branch, follows `XBB.1.5 [T17124C > T23018C]` > `C26822T` > `T22873C` > `T26822C_reversion`
- The query is a bit rough, and may contain other XBB.1.5's T22873C branches here and there, tried my best to filter them out.
- `T22873C` (`S:N437` silent mutation) branch itself doesn't make significant impact elsewhere until it finds foothold in China, especially in certain latent sample submission areas.
- It quickly accumulated spike mutations like `K356N`, `A701V`, `T883I` etc.
- There's also another branch follows `XBB.1.5 [T17124C > T23018C]` > `C27643T(ORF7a:P84S)` > `T22873C`, could they be the same lineage split by some dropout issues? QC looks good though.
![qc](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/61d89855-384c-467d-be7a-40f62ea1a74d)

<details><summary>Genomes for C27643T(ORF7a:P84S) > T22873C branch, query: T17124C, T23018C, T22873C, C27643T</summary>

`EPI_ISL_17645800, EPI_ISL_17652406, EPI_ISL_17684476, EPI_ISL_17684479, EPI_ISL_17684489, EPI_ISL_17704054-17704055, EPI_ISL_17704060, EPI_ISL_17704066, EPI_ISL_17744628, EPI_ISL_17744631, EPI_ISL_17775164, EPI_ISL_17775304, EPI_ISL_17778578, EPI_ISL_17836341, EPI_ISL_17836978, EPI_ISL_17836980, EPI_ISL_17836984, EPI_ISL_17951253, EPI_ISL_18040209, EPI_ISL_18040211`

</details>

**Comment by FedeGueli** [comment]
S:N437N , maybe we can propose the upper branch with NSP6 mutation?

**Comment by FedeGueli** [comment]
So you can make a proposal of parental with three main branches NSP6, T883I and 356N. please do.

**Comment by FedeGueli** [comment]
Has been this proposed then?
