### ISSUE TITLE
FU.1 with A460G 516 seq. mostly China mostly Shanghai ( >18% prevalence in Shanghai)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#50]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b10ea47e-29a2-4ecc-bef6-0c1cef41ea77)
first sequenced: 3-30-23
Most recent Sequence: 4-26-23
 

EDITED by mod.:  Gisaid query A460G,T12730A, T3802C.

**Comment by FedeGueli** [comment]
Can you estimate local prevalence in Shanghai after 1st of April or provide a gisaid query please?

**Comment by Fearuncle** [comment]
11.9%

**Comment by FedeGueli** [comment]
I think it could be more than 13% actually. It is already at 200 seqs found with the query A460G,T12730A, T3802C on Gisaid. It represents 177 out of 1294 samples collected in Shanghai after 1st of April.

@corneliusroemer i suggest to directly designate it in the next systemic tree review of XBB.1.16 ( due to the fact it is not permitted to propose lineages with just nucletotide mutations.

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a94b76a4-c595-40f5-95c9-0015c363acc7)
there is a growing mutation
ORF1ab:M1588V(A5027G) 19 seq.

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/f2542d3c-b72e-48ff-a4c1-c6dd3e886105)

**Comment by FedeGueli** [comment]
Consider that some sequences could be duplicated  cause Usher pulls seqs from the chinese gen bank too and there are seqs also uploaded in Gisaid. i will look at the tree later to see if this is the case

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/3aa6556d-2c5b-4dfe-87e5-129cf04729f5)

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/391c65c7-aafd-464e-a3f6-39372b5e4a23)

**Comment by FedeGueli** [comment]
321 samples on Gisaid with A460G,T12730A, T3802C . Found also in travellers from Taiwan.

@corneliusroemer i suggest a direct designation of this one (missing an AA defining mutation)

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/f50ae383-e06a-4458-88f9-8e968197b06d)

**Comment by Over-There-Is** [comment]
Among 15 FU.1 sequences collected in Guangdong, 12 have A460G mutation. Additionally, Guangdong/GDCDC_JM_0092/2023|EPI_ISL_17698225|2023-05-10 (assigned by GISAID as XBB.1.9.1 and assigned by Nextclade as XBB.1.22) is probably a recombinant between FU.1+A460G and XBB.1.9.2*.

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/72c61ec5-c956-4d91-88fb-6e6ddabca4c0)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/d508e4c5-20a7-474c-b99a-3d0902a74816)
43 seq

**Comment by FedeGueli** [comment]
43? are u sure? or you mean new ones @Fearuncle

**Comment by Over-There-Is** [comment]
Exactly there are only 25 seq with A460G and Orf1a:V3367I right now, most of these are uploaded to both GISAID and GenBase and duplicated.

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b7233b7a-2e71-4aaa-8e9d-c533cc2c790e)
big upload

**Comment by Over-There-Is** [comment]
With Fede's query, only 516 is found.
1 seq in Jingzhou dropped 12730 out,
4 seq in Shanghai (all local), 1 seq in Wuxi, 1 seq in Changzhou and 1 seq in Fuzhou dropped 3802 out,
and 1 Shanghai local seq dropped out both.

**Comment by Over-There-Is** [comment]
> how do i navigate gisaid to get accurate numbers

Past `A460G,T12730A, T3802C` in GISAID's "Nucl Mutations" textbox.

**Comment by Over-There-Is** [comment]
NZ 2, China 4(Heilongjiang 3, Yunnan 1), S. Korea 1(from China), Australia 2 and Canada 1. 526 now.

**Comment by FedeGueli** [comment]
At this point please transfer this to the main page , it doesnt accomplish the pango criteria so maybe put it as possible systematic designation to describe the tree.
