### ISSUE TITLE
Brazilian XBB.1.18.1 sibling of FE.1 with T22930A for S:F456L  (7)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#500]
My attention was caught by a recent brazilian sample carrying S:V16F S:A344V, S:R403K and S:F456L (EPI_ISL_17879723) when i discovered that despite belonging to XBB.1.18.1 was not a FE.1 family but acquired S:F456L from the alternative route (as EG.5) from T22930A  and it belonged to a small lineage circulating in Brazil at least in three different states ( Sao Paulo, Minais Gerais and Pernambuco

**Tree:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_3e91f_388e50.json?c=userOrOld 
![Schermata 2023-07-28 alle 11 45 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b7a26ffe-1240-4a8f-8cd3-ad8838647559)
![Schermata 2023-07-28 alle 11 48 34](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/24fe6a46-bf66-40b7-b758-ef3f993f01ff)

**Defining mutations:**
XBB.1.18.1 >> Orf1a:H1141Y (C3686T),Orf1a:T2277I (C7095T), S:F456L (**T22930**A), Orf8:V81I (G28134A)

Gisaid query:
C3686T, C7095T, T22930A,  

Samples : 6 Brazil ( 3 Sao Paulo-Campinas- Santa BArbara d'Oeste/ 2 Minais Gerais-Belo Horizonte / 1 Pernambuco-Serra Talhada)
EPI_ISL_17614895, EPI_ISL_17717305, EPI_ISL_17838758,
EPI_ISL_17879723, EPI_ISL_17886055, EPI_ISL_17886071
First: hCoV-19/Brazil/SP-IAL-10512/2023 | Original | EPI_ISL_17614895 (Sao Paulo / Campinas)
Last: hCoV-19/Brazil/PE-LACENPE-261662325/2023 | Original | EPI_ISL_17879723 | 2023-06-05 (Pernambuco / SERRA TALHADA)

**Comment by FedeGueli** [comment]
One more sample from Sao Paulo (Santa Cruz de Rio Pardo)

**Comment by FedeGueli** [comment]
> Not sure if it's UShER (mis-)placement thing, there's another branch with `S:F456L` follows: XBB.1.18 > G5739A(ORF1a:S1825N), C23887T > C14425T, T22928C(**S:F456L**) Query: `C14425T, T22928C, C23887T` finds 81 as of July 27. https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c319_478470.json?f_userOrOld=uploaded%20sample
> 
> Right now _FE.1_ is placed as a sibling to _XBB.1.18.1_ rather than its descendant ![details](https://user-images.githubusercontent.com/125747944/259635436-54f2db0f-3a61-4ba0-8f6e-ee1f50bfb547.png)

Great catch to me it is an independent acquisition as you said likely also FE.1 is a sibling of XBB.1.18.1 and not a descendant.
So please propose the 80+ lineage,

cc @angiehinrichs @corneliusroemer could you take a look at these findings by @NkRMnZr

**Comment by AngieHinrichs** [comment]
Thanks for tagging me @FedeGueli.  Yes, T22928C looks a little messy in the XBB.1.18 branch, those may just be misplacements and I can try the usual prune / optimize / re-add trick to see if these branches can be joined:
* XBB.1.18 > T23018C (XBB.1.18.1) > T22928C (11 seqs)
* XBB.1.18 > T23018C (XBB.1.18.1) > G5739A,C23887T > C14425T,T22928C (81 seqs)
* XBB.1.18 > T26012G > A3662G > T23018C > T22928C (FE.1, 3952 seqs)

-- in particular, there are very few sequences putting T26012G and A3662G ahead of T23018C so I think FE.1 has a good chance of moving to XBB.1.18 and staying there.

**Comment by FedeGueli** [comment]
Absorbed by https://github.com/cov-lineages/pango-designation/issues/2225
