### ISSUE TITLE
XBB.1.5 with ORF1b:S2658Y (nsp16_S261Y), ORF1a:Q4385L (nsp10_Q132L), S:G181V and S:T323I (15 seqs, New Zealand, Japan, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#501]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `C21440A(ORF1b:S2658Y)` > `C11671T` > `A13419T(ORF1a:Q4385L)` > `G22104T(S:G181V)` > `C22530T(S:T323I), A27372T`
**Query:** `A13419T, G22104T, C22530T`
**Earliest seq:** 2023-05-10 (`EPI_ISL_17739559`, New Zealand)
**Latest seq:** 2023-07-02 (`EPI_ISL_18048116`, New Zealand)
**Sampled Countries:** New Zealand (5), Japan (1), USA (1, NY)

<details><summary>Genomes: </summary>

`EPI_ISL_17739559, EPI_ISL_17962355, EPI_ISL_17962407, EPI_ISL_17978799, EPI_ISL_17998559, EPI_ISL_18048114, EPI_ISL_18048116`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d98_3b63f0.json?c=gt-S_181,323&f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/914aed6c-147a-4dac-9bb7-ea931dc2edb3)

**Trivia:**
- Both `S:G181V` and `S:T323I` are expected to gain some growth advantage, the former is more often seen in `BA.5*` lineages (although `S:181A` is expected to be the most fit). However due to monthly sequence upload intervals, don't expect this to go fast unless it is caught by other countries.
- There are 3 seqs without `S:T323I` that sampled earlier in South America, query: `C11671T, A13419T, G22104T, -C22530T`

<details><summary>S:G181V only sequences without S:T323I: </summary>

`EPI_ISL_17789708, EPI_ISL_17795828, EPI_ISL_17989881`

</details>

**Comment by FedeGueli** [comment]
It cannot compete. lets wait next upload from NZl to close it: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A13419T%2CG22104T%2CC22530T&analysisMode=CompareToBaseline&
