### ISSUE TITLE
Another XBB.1.22.1 sublineage with ORF3a:T24N spreading internationally (120 seqs in 10 countries,  China, SK, Japan, US )

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#502]
Defining mutations:
XBB.1.22.1>C12068T, C25463A (ORF3a:T24N)

GISAID query: C25463A, A22161G, T28297C or (C12068T, C25463A by @Over-There-Is )
Earliest seq: 2023-04-10 (Austria, EPI_ISL_17497504)
Most recent seq: 2023-07-07 (South Korea, EPI_ISL_18047277)
Countries detected: China (40), South Korea (6), US (3), Japan (3), Singapore (2), Austria (2), Israel (1), Belgium (1), Russia (1) 

Usher Tree:
![屏幕截图 2023-07-28 225419](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/1d50ecae-6e15-445a-8098-fd3bf5a0c63b)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4351e_3d2a10.json

It is different from the main XBB.1.22.1* lineage (FY.3 with ORF1a:E750K) in China. It deserves for further watch despite not successful as FY.3*.

Genomes:
EPI_ISL_17497504, EPI_ISL_17618951, EPI_ISL_17652346, EPI_ISL_17652349, EPI_ISL_17678357, EPI_ISL_17725508, EPI_ISL_17770176, EPI_ISL_17774000, EPI_ISL_17775555, EPI_ISL_17775634, EPI_ISL_17776700, EPI_ISL_17778608, EPI_ISL_17785317, EPI_ISL_17790400, EPI_ISL_17790402, EPI_ISL_17795336, EPI_ISL_17803727, EPI_ISL_17808259, EPI_ISL_17808525, EPI_ISL_17811300, EPI_ISL_17819872,
EPI_ISL_17830401, EPI_ISL_17830441, EPI_ISL_17830454, EPI_ISL_17831499, EPI_ISL_17836675, EPI_ISL_17836848, EPI_ISL_17850412, EPI_ISL_17850838, EPI_ISL_17930422, EPI_ISL_17956899, EPI_ISL_17956914, EPI_ISL_17956981, EPI_ISL_17957067, EPI_ISL_17957140, EPI_ISL_17957153, EPI_ISL_17962818, EPI_ISL_17969771, EPI_ISL_17970056, EPI_ISL_17970058, EPI_ISL_17978675, EPI_ISL_17979681,
EPI_ISL_17979730, EPI_ISL_17982249, EPI_ISL_17987648, EPI_ISL_17987727, EPI_ISL_17994446, EPI_ISL_17994618, EPI_ISL_17998849, EPI_ISL_17998901, EPI_ISL_17998996, EPI_ISL_17999257, EPI_ISL_18009027, EPI_ISL_18033685, EPI_ISL_18034680, EPI_ISL_18040208, EPI_ISL_18046061, EPI_ISL_18047044, EPI_ISL_18047277

**Comment by FedeGueli** [comment]
![Schermata 2023-07-28 alle 20 55 34](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c47358cb-0332-41fa-8181-4ca01e2e8b67)
Ideally this is the 7th branch of XBB.1.22.1
![Schermata 2023-07-28 alle 20 58 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5fe80c8e-79f4-4bd3-8689-b
![Schermata 2023-07-28 alle 20 59 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c40b99ee-e32b-4810-8140-5995dde0721c)
21872273a1e)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=FY.1*&nextcladePangoLineage1=FY.2*&nextcladePangoLineage2=FY.3*&nextcladePangoLineage3=FY.4*&nextcladePangoLineage4=FY.5*&nucMutations5=C2037T&nextcladePangoLineage5=XBB.1.22.1*&aaMutations6=ORF3a%3AT24N&nextcladePangoLineage6=XBB.1.22.1*&analysisMode=CompareEquals&

**Comment by Over-There-Is** [comment]
/organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-HG20230614-2048/2023"
                     /isolation_source="Pharyngeal swab"
                     /host="Homo sapiens; Host_age: 58; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-06-13"
                     /note="Passage_details/history: Original;
                     Additional_host_information: Patient infected while
                     traveling in Thailand"
 10 countries

**Comment by FedeGueli** [comment]
This starts spreading internationally : lets count how many days it takes to reach 100 seqs

**Comment by Over-There-Is** [comment]
107 found with `C12068T, C25463A`. 1 FU.1 sequence is found with `C25463A, A22161G, T28297C` too.
And there is a branch with F157L reaching 5 sequences now.

**Comment by FedeGueli** [comment]
> 107 found with `C12068T, C25463A`. 1 FU.1 sequence is found with `C25463A, A22161G, T28297C` too. And there is a branch with F157L reaching 5 sequences now.

Not sure it is enough XBB.1.22.1 always lacks something to compete. lets see how this goes in the next month

**Comment by FedeGueli** [comment]
It seems to have slowed down closing it for now.
