### ISSUE TITLE
XBB.1.5 on T10204C with ORF1a:K1668R (nsp3_K850R = PLPro_K105R), S:T883I and S:L517I (94 seqs, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#503]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C > T10204C]` > `A5268G(ORF1a:K1668R)` > `C4331T, A26319G` > `C24210T(S:T883I)` > `C23111A(S:L517I)`
**Query:** `A5268G, C23111A, C24210T, T10204C`
**Earliest seq:** 2023-02-12 (`EPI_ISL_17025744`, Massachusetts, USA)
**Latest seq:** 2023-07-07 (`EPI_ISL_18047735`, Hyogo, Japan)
**Sampled Countries:** USA (25, California/4, New York/4, Texas/4, New Jersey/3, Wisconsin/3, North Carolina/2, Florida/1, Iowa/1, Massachusetts/1, Rhode Island/1, Washington/1), Canada (48, Ontario/34, Alberta/6, Saskatchewan/6, BC/2), Dominican Republic (12), Spain (6), Japan (5), Australia (2, Queensland, WA), Colombia (1), UK (1, Wales)

<details><summary>Genomes: </summary>

`EPI_ISL_17025744, EPI_ISL_17273636, EPI_ISL_17306927, EPI_ISL_17306929, EPI_ISL_17307173, EPI_ISL_17350287, EPI_ISL_17370482, EPI_ISL_17373442, EPI_ISL_17386107, EPI_ISL_17442001, EPI_ISL_17442235, EPI_ISL_17442319, EPI_ISL_17442353, EPI_ISL_17442512, EPI_ISL_17442684, EPI_ISL_17442812, EPI_ISL_17445000, EPI_ISL_17445005, EPI_ISL_17462529, EPI_ISL_17467979, EPI_ISL_17467987, EPI_ISL_17468024, EPI_ISL_17482721, EPI_ISL_17482746, EPI_ISL_17490704, EPI_ISL_17490744, EPI_ISL_17492219, EPI_ISL_17502383, EPI_ISL_17502391-17502392, EPI_ISL_17521450, EPI_ISL_17527474, EPI_ISL_17537704, EPI_ISL_17546778, EPI_ISL_17546783, EPI_ISL_17546798, EPI_ISL_17583062, EPI_ISL_17588126, EPI_ISL_17588142, EPI_ISL_17595226, EPI_ISL_17603848, EPI_ISL_17603904, EPI_ISL_17603987, EPI_ISL_17605402, EPI_ISL_17605686, EPI_ISL_17635249-17635250, EPI_ISL_17635258, EPI_ISL_17635273, EPI_ISL_17639618, EPI_ISL_17639661, EPI_ISL_17639668, EPI_ISL_17644443, EPI_ISL_17679020, EPI_ISL_17679254, EPI_ISL_17679523, EPI_ISL_17682278, EPI_ISL_17682280, EPI_ISL_17685908, EPI_ISL_17690061, EPI_ISL_17701411, EPI_ISL_17701675, EPI_ISL_17706204, EPI_ISL_17707986, EPI_ISL_17711684, EPI_ISL_17716671, EPI_ISL_17716715, EPI_ISL_17722744, EPI_ISL_17722882, EPI_ISL_17760322, EPI_ISL_17773289, EPI_ISL_17789389, EPI_ISL_17814714, EPI_ISL_17815379, EPI_ISL_17818992, EPI_ISL_17818994, EPI_ISL_17853199, EPI_ISL_17952067, EPI_ISL_17955792, EPI_ISL_17955799, EPI_ISL_17955824-17955825, EPI_ISL_17955855-17955858, EPI_ISL_17956238, EPI_ISL_17957490, EPI_ISL_17958995, EPI_ISL_17960580, EPI_ISL_17960625, EPI_ISL_17960630-17960631, EPI_ISL_17960645, EPI_ISL_17971305, EPI_ISL_17977867, EPI_ISL_18006509, EPI_ISL_18012968, EPI_ISL_18042106, EPI_ISL_18047735`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4117f_3d1bb0.json?f_userOrOld=uploaded%20sample

view from `T10204C > ORF1a:K1668R` branch, with `883`, `517`, `554`, `642` filters of S gene
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/25d8b6d4-7634-452b-b21c-a40a9eb41fe0)

**Trivia:**
- This seems to be the parent branch of #379 proposed by @Sinickle
- Since it has `T10204C`, it is not `XBB.1.5.4`, just another `XBB.1.5` with `S:T883I`

**Comment by FedeGueli** [comment]
It is slow but mutational profile has to be kept monitored.

**Comment by FedeGueli** [comment]
i found 91 of this one. still going .

**Comment by FedeGueli** [comment]
The NSP3 mutation should correspond to PLPro_K105R
