### ISSUE TITLE
GK.1 with s:478r, s:98f, orf1ab:2379v, resulting in 455f 456l 478r combo. 5 seqs  Brazilian travellers Canada

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#504]
Query: C21855T, G22927T, G12467T

The combo of 455f 456l + a 478 mutation, like 478r (in several yet undesignated xbb.1.16 and xbb.1.16.6) or 478i (in designated gw.5), is becoming more common lately. in this case, 98f might also add some very slight advantage as it is slowly becoming more common.

Sequences are from USA, but one is described as traveller from brazil, and I assume the other is as well. (Edit: the other one is a pooled sample, so probably same patient. Nonetheless, the combination of mutations is something to keep an eye on.)

![Screenshot 2023-07-28 184856](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/9f6ab348-86dd-4954-b4ba-c40f734efd91)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5a0c1_3f0920.json?f_userOrOld=uploaded%20sample

EPI_ISL_18049309, EPI_ISL_18049334

**Comment by FedeGueli** [comment]
Designated GK.1.4 via https://github.com/cov-lineages/pango-designation/commit/56f61984899d7f46f692dc39ae67f7b0f803584f
