### ISSUE TITLE
Eg.5.1.1 with s:d253g and orf1a:1923t (25 seqs, europe)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#505]
Query: T14988C, A23014T, G6032A, A22320G
Seqs are from 1x wales, 1x england, 2x spain, and 2 usa airport: 1traveller from france, the other unknown (but this is a pooled sample with same collection date, i presume same patient) 
Interesting because s:253g is the alternative to 252v in xbb.2.3, and here they are combined.

![Screenshot 2023-07-28 191006](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/17d1fa73-f857-4ac0-859d-23dad1672770)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_8f20_3f5b00.json?c=gt-S_253

EPI_ISL_17989851, EPI_ISL_18015591, EPI_ISL_18015753,
EPI_ISL_18015770, EPI_ISL_18036932

**Comment by BorisUitham** [comment]
from 5 seqs to 12 seqs in a week. adding sweden to list of countries

**Comment by aviczhl2** [comment]
25 seqs now.

**Comment by BorisUitham** [comment]
Thanks for notifying. Thats another doubling of sequences in about a week

**Comment by FedeGueli** [comment]
Propose it please.

**Comment by FedeGueli** [comment]
> T14988C, A23014T, G6032A, A22320G

Thank you very much

**Comment by BorisUitham** [comment]
Annnnd 35 now. Proposing on main page

**Comment by FedeGueli** [comment]
HK.6 now
