### ISSUE TITLE
New EG.2 (478R) branch(+8-nuc,4-aa) with S:494P (37 seqs, 6 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#506]
EG.2+T23449C+G27604A(Orf7a:V71I)+A2560G,C23185T+C22264T+C7728T,C17747T(Orf1a:S2488F, Orf1b: P1427L)+T23042C(S:494P)

GISAID query: T23042C,C22995G,C17747T

No. of seqs: 8 (USA 1 Japan 1 UK 6)

First : EPI_ISL_17884491, UK, 2023-6-10
Latest: EPI_ISL_18049209, USA, 2023-7-17

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19e64_480ea0.json?label=id:node_6738171)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ddf900dd-6b6e-4731-88ff-702d2204daf8)

**Comment by aviczhl2** [comment]
+1 Spain

**Comment by aviczhl2** [comment]
+1 Denmark

**Comment by FedeGueli** [comment]
EG.2 is showing a good fitness and interesting diversity in the recent weeks.

**Comment by aviczhl2** [comment]
24, Sweden

**Comment by FedeGueli** [comment]
It cannot compete in Uk: https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T23042C%2CC22995G%2CC17747T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
It still seems non competitive

**Comment by aviczhl2** [comment]
A huge upload from Sweden making it 37.

**Comment by FedeGueli** [comment]
still 37 closing this
