### ISSUE TITLE
XBB.1.5 with S:F456L (via T22930A) re-activated by follow up ORF1b:T2040I, ORF1aK1817N, ORF1b:L1504F, M:I8V and N:G124D (13 seqs, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#508]
**Defining Mutations for sleeper S:F456L lineage:** `XBB.1.5 [T17124C > T23018C]` > `C952T` > `T9352C, T22930A(S:F456L)`
**Defining Mutations for reactivated follow-up lineage:** `XBB.1.5 [T17124C > T23018C]` > `C952T` > `T9352C, T22930A(S:F456L)` > `T334C, C6187T, C19586T(ORF1b:T2040I/nsp14_T516I)` > `G5716T(ORF1aK1817N/nsp3_K999N), C17977T(ORF1b:L1504F/nsp13_L581F), A26544G(M:I8V), G28644A(N:G124D)`

**Query for parent S:F456L lineage:** `C952T, T9352C, T22930A`
**Query for follow-up S:F465L lineage:** `C952T, T22930A, A26544G`

**Earliest seq for reactivated follow-up lineage:** 2023-04-19 (`EPI_ISL_17862360`, California, USA)
**Latest seq for follow-up lineage:** 2023-07-08 (`EPI_ISL_18015576`, England, UK)

**Sampled Countries:** UK (3), Belgium (2), Canada (2), France (1), Ireland (1), USA (1)

<details><summary>Genomes for inactive parent S:F456L lineage: </summary>

**Earliest seq:** 2023-01-24 (`EPI_ISL_16938194`, Virginia, USA)
**Latest seq:** 2023-04-11 (`EPI_ISL_17588665`, Virginia, USA)

`EPI_ISL_16938194, EPI_ISL_16938198, EPI_ISL_17077389, EPI_ISL_17193251, EPI_ISL_17238135, EPI_ISL_17238520, EPI_ISL_17286859, EPI_ISL_17333259, EPI_ISL_17333320, EPI_ISL_17333861, EPI_ISL_17350168, EPI_ISL_17350170, EPI_ISL_17411533, EPI_ISL_17534618, EPI_ISL_17585601, EPI_ISL_17585640`

</details>

<details><summary>Genomes for follow-up lineage: </summary>

`EPI_ISL_17805433, EPI_ISL_17805435, EPI_ISL_17814614-17814615, EPI_ISL_17862360, EPI_ISL_17958959, EPI_ISL_17964421, EPI_ISL_18015576, EPI_ISL_18015672, EPI_ISL_18049017,`

plus one non-gisaid lineage: `Scotland/CLIMB-CM7YR1GJ/2023|2023-07-05`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3305a_4dd070.json?f_userOrOld=uploaded%20sample&label=id:node_7113225

view from `C952T` branch
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4f22c8f9-8bba-4bcb-965e-057804e036b3)

**Trivia:**
- A sleeper `XBB.1.5` + `S:F456L` lineage recently re-activated from hiatus.
- Previously sits on a skeptical `C21998A/S:Q146K` flip-flop branch of `XBB.1.5`, now that has been masked.

**Comment by FedeGueli** [comment]
Likely is worth ptoposing starting from the only circulating branch with Orf1a:K1817N ( =PLPro_K254N ) and M:I8V:
the last sequence without them ( just checked on Gisaid adding "-M_I8V to your query) is from April , so the rest of the lineage is non existent.
