### ISSUE TITLE
EG.1 (S:Q613H) + S:A222V(35seq)+S:K478R( 13  seq, England) 

### ISSUE THREAD

**Issue by DoropFan** [sars-cov-2-variants/lineage-proposals#509]
Description
Sub-lineage of:EG.1(XBB.1.9.2.1)
Earliest sequence:2023-04-20(United Kingdom)
Most recent sequence:2023-07-11(United Kingdom)
 Sequences:7
EG.1>C22227T(S:A222V)
.>C27603T
.>G16381A(ORF1b:V972I), G25855C(ORF3a:D155H)
.>G1820A(ORF1a:G519S), A22995G(S:K478R), G28875T(N:S201I)

UShER Tree
![EG1+A222Vp1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/118802079/ff7258d0-908b-4c57-bd2d-5d68496f22d9)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1cef9_501970.json?c=gt-S_222&label=id:node_6744978

 
CovSpectrum:ORF1b:V972I, S:A222V, S:K478R
GISAID:G1820A, C22227T, **C**22995G (edited)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AV972I%2CS%3AA222V%2CS%3AK478R&

Genomes
https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2023-01-23&dateTo=2023-07-22&aaMutations=ORF1b%3AV972I%2CS%3AA222V%2CS%3AK478R&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random
EPI_ISL_17989698
EPI_ISL_17606960
EPI_ISL_17960282
EPI_ISL_18015686
EPI_ISL_17989821
EPI_ISL_17960300
EPI_ISL_18015646

**Comment by aviczhl2** [comment]
The delta mutation S:A222V is becoming popular again these days.

**Comment by FedeGueli** [comment]
It seems slow closing for now
