### ISSUE TITLE
Saltation of XBB.1.5.14 with S:D427Y, S:I714V and S:I882V (7 seqs as of 2023-05-25, Sweden)

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#51]
Here's a small cluster (6 sequences) of XBB.1.5.14 from Sweden with 6 additional mutations on branch.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/ac4a8d33-1bae-4344-9dec-f83245dbb618)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9678_f47d20.json?c=userOrOld&label=id:node_6770709

**Amino changes on top of XBB.1.5.14**: ORF1b:F148S, S:D427Y, S:I714V, S:I882V, ORF8:P93T

**GISAID and Cov-spectrum query**: C556T, T13910C, A23702G, A24206G, C28170A

**Genomes**: EPI_ISL_17607810, EPI_ISL_17638676, EPI_ISL_17638689, EPI_ISL_17638691-17638693

**Comment by FedeGueli** [comment]
S:I714V did quite good in DV.4

**Comment by FedeGueli** [comment]
Closing this for now
