### ISSUE TITLE
XBB.8.2+16-nuc,9-aa containing S:521T,478R,178H, spotted by FedeGueli (2 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#510]
Side branch of #349 .

XBB.8.2+C6156T,C15925T(orf1b:L820F),A21081G,C25680T,G27467C(Orf7a:R25T)+C934T+C29149T+C23123A(S:P521T)
+A259G, T15735C, A17219G(Orf1b:D1251G), G22094C(S:178H), G26416T(E:V58F), C11750T(Orf1a:L3829F), A22995G(S:478R), G25471C(Orf3a:D21H)

GISAID query:G22094C,G26416T,T23018C
No. of seqs: 2( USA from Portugal)
EPI_ISL_17985500, 17985578, 2023-7-1

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e15d_6eea40.json?label=id:node_7129749)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1eab04fb-4e8f-4386-a479-3109285a7c07)

**Comment by FedeGueli** [comment]
Thx for proposing it

**Comment by aviczhl2** [comment]
> Thx for proposing it

The two actually from Portugal not USA. I guess it has the same origin as #349 before C29149T, but S:521T more likely belong to the saltation together with S:478R, 178H.

**Comment by aviczhl2** [comment]
No new seqs.
