### ISSUE TITLE
XBB.1.5.68 with ORF1a:F3486L (nsp5_F223L), ORF8:Q72L and S:T478R (101 seqs, mainly in the USA, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#514]
**Defining Mutations:** `XBB.1.5.68` > `T10721C(ORF1a:F3486L), A28108T(ORF8:Q72L)` > `C23266T` > `C22995G(S:T478R)`
**Query:** `T10721C, C23266T, C22995G`
**Earliest seq:** 2023-03-12 (`EPI_ISL_17279117`, Indiana, USA)
**Latest seq:** 2023-07-20 (`EPI_ISL_18044190`, Iceland)
**Sampled Countries:** USA (95, California/29, Illinois/27, Texas/11, Florida/10, Arizona/4, Indiana/3, Utah/3, New Jersey/2, Virginia/2, Minnesota/1, New York/1, Ohio/1, Oregon/1), Guatemala (2), Iceland (2), Austria (1), UK (1, England)

<details><summary>Genomes: </summary>

`EPI_ISL_17279117, EPI_ISL_17417915, EPI_ISL_17468371, EPI_ISL_17478017, EPI_ISL_17486435, EPI_ISL_17550882, EPI_ISL_17589154, EPI_ISL_17590290, EPI_ISL_17592996, EPI_ISL_17616812, EPI_ISL_17619069, EPI_ISL_17619206, EPI_ISL_17621009, EPI_ISL_17621066, EPI_ISL_17621086, EPI_ISL_17621377, EPI_ISL_17621571, EPI_ISL_17627541, EPI_ISL_17639840, EPI_ISL_17675967, EPI_ISL_17675979, EPI_ISL_17675983, EPI_ISL_17677413, EPI_ISL_17680543, EPI_ISL_17689947, EPI_ISL_17714891-17714892, EPI_ISL_17737638, EPI_ISL_17744106, EPI_ISL_17744481, EPI_ISL_17773905, EPI_ISL_17782104, EPI_ISL_17782147, EPI_ISL_17788479, EPI_ISL_17790001, EPI_ISL_17797801, EPI_ISL_17797808-17797809, EPI_ISL_17804386, EPI_ISL_17804388, EPI_ISL_17848360, EPI_ISL_17853173, EPI_ISL_17853641, EPI_ISL_17853663, EPI_ISL_17854030, EPI_ISL_17855303, EPI_ISL_17855368, EPI_ISL_17855937, EPI_ISL_17855955, EPI_ISL_17856419, EPI_ISL_17856635, EPI_ISL_17856754, EPI_ISL_17866015, EPI_ISL_17881130, EPI_ISL_17885505, EPI_ISL_17885529, EPI_ISL_17885531, EPI_ISL_17887124, EPI_ISL_17952345, EPI_ISL_17954563, EPI_ISL_17955608, EPI_ISL_17955991-17955992, EPI_ISL_17972238, EPI_ISL_17976043, EPI_ISL_17976726, EPI_ISL_17976918, EPI_ISL_17979250, EPI_ISL_17979321, EPI_ISL_17981074, EPI_ISL_17986275, EPI_ISL_17986355, EPI_ISL_17996249, EPI_ISL_17997612, EPI_ISL_17997648, EPI_ISL_17997670, EPI_ISL_17997946, EPI_ISL_17998081, EPI_ISL_17998101, EPI_ISL_17998117, EPI_ISL_17998122, EPI_ISL_17998593, EPI_ISL_18005380, EPI_ISL_18008760, EPI_ISL_18022437, EPI_ISL_18031768, EPI_ISL_18037707, EPI_ISL_18044178, EPI_ISL_18044190, EPI_ISL_18044381, EPI_ISL_18045040, EPI_ISL_18045045, EPI_ISL_18045311, EPI_ISL_18045630, EPI_ISL_18045671, EPI_ISL_18045876, EPI_ISL_18046128, EPI_ISL_18046155, EPI_ISL_18046287, EPI_ISL_18046492, EPI_ISL_18050175`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a07f_78e580.json?f_userOrOld=uploaded%20sample&label=id:node_7062490

view from XBB.1.5.68 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b6b522c4-6d2b-4bea-ad3a-b39ffb98879f)

details & diversity
![diversity](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8c04a31d-77f7-4914-b5ba-ce04385ced46)

**Comment by FedeGueli** [comment]
> 
> view from XBB.1.5.68 polytomy ![poly](https://user-images.githubusercontent.com/125747944/257197973-b6b522c4-6d2b-4bea-ad3a-b39ffb98879f.png)
> 
> details & diversity ![diversity](https://user-images.githubusercontent.com/125747944/257198015-8c04a31d-77f7-4914-b5ba-ce04385ced46.png)

>

In your tree there were also HZ.2 and HZ.3
