### ISSUE TITLE
EG.5.1 with ORF1a:P309Q (nsp2_P129Q), S:D1146A and S:T573I (40 seqs, mainly in Japan, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#515]
**Defining Mutations:** `EG.5.1` > `T15198A` > `C1191A(ORF1a:P309Q), A24999C(S:D1146A), A27642G, A28254Δ(ORF8:I121Δ)` > `C23280T(S:T573I)`
**Query:** `T15198A, C23280T, A24999C`
**Earliest seq:** 2023-06-22 (`EPI_ISL_17978793`, Kyoto, Japan)
**Latest seq:** 2023-07-24 (`EPI_ISL_18051719`, Yamaguchi, Japan)
**Sampled Countries:** Japan (11), USA (2, travel history to Japan)

<details><summary>Genomes: </summary>

`EPI_ISL_17978793, EPI_ISL_18006986, EPI_ISL_18010885, EPI_ISL_18011011, EPI_ISL_18013372, EPI_ISL_18040388, EPI_ISL_18040838, EPI_ISL_18047763, EPI_ISL_18051713, EPI_ISL_18051715-18051717, EPI_ISL_18051719`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1044b_79c040.json?f_userOrOld=uploaded%20sample

view from EG.5 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c4bbeeed-9a27-48fc-b124-470dd153a6a9)

details and diveristy from `T15198A` branch
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4454ccd6-5440-4ba1-8458-24cfd1626f71)

**Comment by FedeGueli** [comment]
Please propose it.
