### ISSUE TITLE
XBB.2.3.2 + Orf1a:E913D (NSP3_E95D), Orf1a:V2783I (NSP4_V20I) and Orf1b:T2453I (NSP3_T1635I) 53 seqs & its  S:69/70del sublineage  (7 seqs, Singapore , AUS-NSW )

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#52]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/105a8286-068a-4ff1-8df4-514bc3dabbc6)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2281_f4c5b0.json?c=userOrOld&label=id:node_6985420

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/1d693d10-1ab4-43fd-bbc3-518e13a3ef07)

4 sequences at the moment. 

2 Japan ex-Singapore and 2 Australia-NSW.

Besides S:69/70del and 3 ORF1ab changes, there are also 5 unique nuc mutations on branch: C763T, T3331C, T11791A, C17403T, G29383A
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/2df14ca5-a681-4677-b61f-bcd3b998208e)

**Comment by FedeGueli** [comment]
@c19850727 have you establish where the deletion happened in the tree? in the main node or with the 5 nuc saltation ?

**Comment by c19850727** [comment]
Hi @FedeGueli I forgot to mention the S:69/70del happened with the 5 nuc saltation.

Query: **T5680C, G8612A, G3004T, C20825T** with or without **del21767**.

**Comment by FedeGueli** [comment]
Thank you @c19850727 !

**Comment by FedeGueli** [comment]
Up to 7 today . 2 new local cases today in Singapore : a baby kid and an elderly. 

cc @c19850727 please keeps this checkedif it spreads further a proposal could be deserved.

**Comment by FedeGueli** [comment]
The broader lineage reached 50 while the 5 nuc lineage with 69/70del seems not growing at the moment.
![Schermata 2023-06-10 alle 14 05 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/eec589d3-17ae-4eb2-b89d-6a9285a38839)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3847f_4666a0.json?label=id:node_6931748

cc @c19850727 maybe i suggest to shift the proposal to the main branch , leaving the 5 nuc branch just as subproposal!
