### ISSUE TITLE
FL.2 with S:N641K (70 seqs, 14 countries) emerged likely in Eastern Africa and shows a lot of Spike diversity: three branches 259S/ 809T/ 471Q

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#520]
**Defining Mutations:** `FL.2` > `C25521T` > `T23485A(S:N641K), A29683T`
**Query:** `T23485A, C25521T`
**Earliest seq:** 2023-03-15 (`EPI_ISL_17363241`, England, UK)
**Latest seq:** 2023-07-13 (`EPI_ISL_18055042`, California, USA)
**Sampled Countries:** USA (19, California/13, Arizona/4, New York/2), Sweden (17), Canada (9, Ontario), UK (6, England/5, Scotland/1), France (2), Austria (1), China (1, Shanghai), Germany (1), India (1), Ireland (1), Israel (1), Italy (1), Japan (1), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17363241, EPI_ISL_17395881, EPI_ISL_17400810, EPI_ISL_17448553, EPI_ISL_17488308, EPI_ISL_17488334, EPI_ISL_17511907, EPI_ISL_17514054, EPI_ISL_17537803, EPI_ISL_17537913, EPI_ISL_17549297, EPI_ISL_17553672, EPI_ISL_17555869, EPI_ISL_17558172, EPI_ISL_17590487, EPI_ISL_17630281, EPI_ISL_17630455, EPI_ISL_17630478, EPI_ISL_17664440, EPI_ISL_17668930, EPI_ISL_17668978, EPI_ISL_17668999, EPI_ISL_17690272, EPI_ISL_17713615, EPI_ISL_17721736, EPI_ISL_17722643-17722644, EPI_ISL_17722718, EPI_ISL_17731144, EPI_ISL_17731521, EPI_ISL_17732731, EPI_ISL_17732763, EPI_ISL_17732771, EPI_ISL_17732773, EPI_ISL_17732812, EPI_ISL_17732815, EPI_ISL_17732819, EPI_ISL_17764343, EPI_ISL_17764728, EPI_ISL_17767911, EPI_ISL_17768311, EPI_ISL_17769714, EPI_ISL_17781527, EPI_ISL_17791659, EPI_ISL_17797041, EPI_ISL_17809292, EPI_ISL_17809729, EPI_ISL_17838302, EPI_ISL_17838841, EPI_ISL_17854148, EPI_ISL_17855011, EPI_ISL_17950471, EPI_ISL_17950512, EPI_ISL_17951643, EPI_ISL_17981065, EPI_ISL_18005336, EPI_ISL_18010050, EPI_ISL_18045881, EPI_ISL_18046161, EPI_ISL_18046249, EPI_ISL_18046277, EPI_ISL_18055042`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36e64_922b50.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/70630ebc-548e-4b65-9fb0-5c612e44a1d5)

**Trivia:**
- No idea what `S:N641K` does, but it does seems to have a lot of positive charge. Only sampled 170 times during the whole pandemic, about 1/3 is from this branch.
- Not a fast lineage, but got sampled here and there sparsely. 
- One of the most recent branch is the one with the most spike mutations, follows: `S:259S, E554A` and `K356N`, but there are also mutations like `S:P809T`, `E471Q` from other branches.

**Comment by FedeGueli** [comment]
Although this has no growth advantage: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=T23485A%2CC25521T&analysisMode=CompareToBaseline&

I think the reamrkable spike diversity shown in its tree strongly points to an undersampled circualtion somewhere.
EPI_ISL_17395881 collected in Japan back in April from a traveller coming from Somalia
and EPI_ISL_17537913 collected back in April from a traveller from Kenya could throw some light on that area.

So i think it should be proposed in the main page specifying these two seqeucnes and the spike diversity shown:
(three big branches each with  S:259S or S:P809T or S:E471Q

**Comment by thiolist** [comment]
**NkRMnZr** asked what S:N6411K does. One thing is that it adds a proteolytic cleavage site that is a target of the HAT (Human Airway Trypsin-like) protease, which could cleave the spike protein at this site. This would change the protein shape in the airway (nasal passage to lungs) without changing its shape elsewhere in the body (e.g. change transmissibility without affecting infectability of tissues outside of the airway).

**Comment by FedeGueli** [comment]
> **NkRMnZr** asked what S:N6411K does. One thing is that it adds a proteolytic cleavage site that is a target of the HAT (Human Airway Trypsin-like) protease, which could cleave the spike protein at this site. This would change the protein shape in the airway (nasal passage to lungs) without changing its shape elsewhere in the body (e.g. change transmissibility without affecting infectability of tissues outside of the airway).

References?

**Comment by FedeGueli** [comment]
> > **NkRMnZr** asked what S:N6411K does. One thing is that it adds a proteolytic cleavage site that is a target of the HAT (Human Airway Trypsin-like) protease, which could cleave the spike protein at this site. This would change the protein shape in the airway (nasal passage to lungs) without changing its shape elsewhere in the body (e.g. change transmissibility without affecting infectability of tissues outside of the airway).
> 
> Thanks! Any ref to the study?

@ryhisner pointed to this one: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9167920/

**Comment by ryhisner** [comment]
Thanks, Fede. However, I don't think that study says anything about S:N641K creating a HAT cleavage site. Instead, it claims—convincingly, I think—that a cleavage site already exists at S:Y636. 

This isn't to say that N641K couldn't create a HAT cleavage site (something I'm not familiar with at all), only that I don't see any support for that idea in this paper.

**Comment by FedeGueli** [comment]
Thx @ryhisner for clarifying!

**Comment by FedeGueli** [comment]
FL.2.6
