### ISSUE TITLE
HF.1 (XBB.1.16.13.1) Sublineage with S:H1101Y, S:D1163Y, N:A35T, ORF1a:T2121I, ORF1b:V1228L, ORF1b:A176V (22 seq, Aug 6)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#521]
### **Description**
**Sub-lineage of:** HF.1 (XBB.1.16.13.1)
**Earliest sequence:** 2023-7-4, USA, North Carolina, EPI_ISL_17996289
**Most recent sequence:** 2023-7-22, Canada, Ontario, EPI_ISL_18055273, EPI_ISL_18055274
**Countries circulating:** Canada (21), USA (1)
**Number of Sequences:** 22
**GISAID AA Query:** Spike_H1101Y, Spike_D1163Y, Spike_K304N
**GISAID Nucleotide Query:** C6627T, C24863T, G25049T (catch 1 old unrelated seq- EDITED)
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16* & G25049T & [3-of: C6627T, C7006T, C13994T, C24863T]
**Substitutions on top of HF.1:**
**Spike:** H1101Y, D1163Y
**N:** A35T
**ORF1a:** T2121I
**ORF1b:** A176V, V1228L
**Nucleotide:** C6627T, C7006T, C13994T, G17149T, C24863T, G25049T, G28376A
 
**Phylogenetic Order of Mutations:** G17149T, G28376A (ORF1b:V1228L, N:A35T) **→** C7006T, C13994T, C24863T (ORF1b:A176V, S:H1101Y) **→** C6627T (ORF1a:T2121I)**→** G25049T (S:D1163Y)
Note—20/22 sequences also have **→** C28290T (N:P6L/ORF9b:P3S)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/HF.1__XBB.1.16.13.1__H1101Y_D1163Y.json

<img width="1343" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cc1a05dc-5133-4cc4-822a-9b1a1fa5ed36">

<img width="1476" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a8ef8763-d90f-4c0c-a7bf-3e9753427b47">

**Evidence**
All sequences with very recent collection dates, and the sequence from North Carolina shows this is more than an outbreak in one facility in Canada. HF.1 is already quite a fast lineage, so this bears watching. Note that 20/22 sequences here also have N:P6L/ORF9b:P3S. I've noted before that ORF9b:P3S slightly improves the already impressive extended homology for a suboptimal ORF9b TRS.

<img width="1406" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1b093ef2-bee1-4ae5-9817-d6fba8df98b5">
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17996289, EPI_ISL_18030497-18030499, EPI_ISL_18030522, EPI_ISL_18030547-18030549, EPI_ISL_18055171, EPI_ISL_18055173, EPI_ISL_18055176-18055177, EPI_ISL_18055217, EPI_ISL_18055221-18055222, EPI_ISL_18055261, EPI_ISL_18055264-18055265, EPI_ISL_18055273-18055274, EPI_ISL_18055324, EPI_ISL_18055347
</details>

**Comment by FedeGueli** [comment]
it doesnt sem to have spread further closing this for now,

**Comment by FedeGueli** [comment]
Designated HF.1.1 the parental S:H1101Y i dont know ryan if you want to keep open the issue or u re satisfied this way.

**Comment by ryhisner** [comment]
There were a couple geographically distant sequences recently in the US (Arkansas and New York), but for the most part, this seems like a classic Canadian cluster. I'd leave closed, and if more pop up, we can always reopen.
