### ISSUE TITLE
FY.3.1 (XBB.1.22.1.3.1) sublineage with S:Q613H and S:D950N (10 seqs in Japan)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#522]
Defining mutations:
FY.3.1>G4109T (ORF1a:D1282Y)>C25669T (ORF3a:H93Y)>T17688C, G23401C (S:Q613H)

GISAID query: A22161G, G4109T, G23401C
Earliest seq: 2023-07-05 (Japan, EPI_ISL_18051378)
Most recent seq: 2023-07-12 (Japan, EPI_ISL_18051430)
Countries detected: Japan (7)

Usher Tree:
![QQ截图20230802001445](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7550148e-9af4-4f09-aefe-b3721f23f08c)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8bcf_92bee0.json?c=gt-S_613

S:Q613H is popular in FK.1 and EG.1 nowadays. All seqs are from Fukuoka, Japan and the IDs are consecutive, hence they may be two infection chains.

Genomes:
EPI_ISL_18051378-18051379, EPI_ISL_18051381, EPI_ISL_18051426-18051427, EPI_ISL_18051429-18051430

**Comment by HynnSpylor** [comment]
2 more seqs from Japan
and I omitted that they also get S:D950N (which emerged in Delta lineages)

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by FedeGueli** [comment]
It seems to have slowed down . lets track it till the end of this month.

**Comment by HynnSpylor** [comment]
1 more seq but still in Fukuoka, Japan. It really slowed down.

**Comment by FedeGueli** [comment]
Closing for now. ping me if it starts again to pop up.
