### ISSUE TITLE
XBB.1.16 with S:T883I (51 seqs, mainly in the USA, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#524]
**Defining Mutations:** `XBB.1.16` > `C7765T` > `C7081T, T22912C, C24210T(S:T883I)`
**Query:** `C7081T, T22912C, C24210T`
**Earliest seq:** 2023-04-11 (`EPI_ISL_17525649`, North Carolina, USA)
**Latest seq:** 2023-07-19 (`EPI_ISL_18057147`, Texas, USA)
**Sampled Countries:** USA (38), Canada (1, Ontario), Italy (1), Japan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17525649, EPI_ISL_17525653, EPI_ISL_17580927, EPI_ISL_17589257, EPI_ISL_17608715-17608716, EPI_ISL_17620963, EPI_ISL_17689591, EPI_ISL_17699852, EPI_ISL_17768926, EPI_ISL_17768931, EPI_ISL_17839152, EPI_ISL_17852630, EPI_ISL_17855235, EPI_ISL_17856548, EPI_ISL_17885534, EPI_ISL_17885539, EPI_ISL_17950863, EPI_ISL_17955602, EPI_ISL_17965292, EPI_ISL_17971800, EPI_ISL_17971852, EPI_ISL_17971860, EPI_ISL_17976377, EPI_ISL_17979510, EPI_ISL_17989089, EPI_ISL_17992048, EPI_ISL_17992050, EPI_ISL_17996883, EPI_ISL_18009155, EPI_ISL_18009373, EPI_ISL_18011186, EPI_ISL_18012980, EPI_ISL_18030614, EPI_ISL_18043548, EPI_ISL_18046044, EPI_ISL_18050179, EPI_ISL_18053813, EPI_ISL_18053828, EPI_ISL_18057147, EPI_ISL_18057699`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41d33_a2dde0.json?f_userOrOld=uploaded%20sample

view from `C7765T` polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8a350880-f751-4b29-858d-48316260d339)

details & diversity
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/52eb0ee6-0903-4000-b01c-252f8ec8443c)

**Trivia:**
- `C7765T` is one of the large undesignated XBB.1.16 branch, 172 out of 495 collected since June 1st (query: `A22101T, T28297C, C7765T`), there are also mutations like `S:E554Q` from neighbouring sub-branches (follows: `C7765T` > `T25779C` > `G23222C(S:E554Q)`, query: `C7765T, G23222C` only finds 4 at the moment, but there are many more non-GISAID sequences showed on UShER), proposed #554
- `T22912C` is `S:N450` silent mutation

**Comment by FedeGueli** [comment]
> * there are also mutations like `S:E554Q` from neighbouring sub-branches (follows: `C7765T` > `T25779C` > `G23222C(S:E554Q)`, query: `C7765T, G23222C` only finds 4 at the moment, but there are many more non-GISAID sequences showed on UShER)
>

@NkRMnZr i have checked this and i think it should be proposed immediately, it is now 9 on Gisaid  with **C7765T, G23222C,T25779C** but already 15 on Usher .
![Schermata 2023-08-09 alle 14 01 23](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b0030eb4-65d2-43d6-a750-62a857bc9627)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ed75_37ecc0.json?label=id:node_6738279

**Comment by FedeGueli** [comment]
> > i have checked this and i think it should be proposed immediately, it is now 9 on Gisaid with **C7765T, G23222C,T25779C** but already 15 on Usher .
> 
> How about turn this proposal into XBB.1.16 > C7765T lineage diversity tracker?

I prefer to get it separated if it is not too much work for you!

**Comment by FedeGueli** [comment]
although slower than dominant S:T883I is clearly beneficial and this will keep circualting for a while. XBB.1.16 has still a lot of the tree undesignated. Propose it and @corneliusroemer for sure when will have the time to screen xbb.1.16 will get it designated (if not overwhelmed by FLips and co): https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C7081T%2CT22912C%2CC24210T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
> Designated as XBB.1.16.29 via [cov-lineages/pango-designation@42e991c](https://github.com/cov-lineages/pango-designation/commit/42e991c)

thank you i hve missed the ghost commit!
