### ISSUE TITLE
New EG.5.1.1 sublineage with S:L455F ( 15 sequences Liaoning, Guangdong, Shanghai, Yunnan,South Korea,Japan, Singapore)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#525]
@borisuitham solicited me to monitor multiple emergences of S:L455F on EG.5.1.1 backbone 
so i did, findiing mutliple singlets traceable with the following query (maybe)
1) C17802T,C6781T, G22927C
2)  G22899T, G23624T,C8326T, G22927C
3) T6673C, A7150C, G19962A
which i will monitor privately

but one is already two sequences from two different regions so it si worth proposing it immediately:

Gisaid query:  , G22927T,C5031T
EG.5.1.1 >> C6541T > orf1a:T1589I (C5031T) > orf1a:T4249I C13011T, S:L455F (G22927T)

Sequences: 
EPI_ISL_18034950, (Guangdong) 
EPI_ISL_18049761 (Liaoning)

Tree:
![Schermata 2023-08-02 alle 12 44 16](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0b27cb4e-acb2-4d02-9d01-bf002ca9f25e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_90e8_a33420.json?c=gt-S_455&label=id:node_6755361

**Comment by aviczhl2** [comment]
8 seqs now

**Comment by FedeGueli** [comment]
> C13011T, G22927T,C5031T

Thank you i am retuning the query.

**Comment by FedeGueli** [comment]
3 more sequences of this one all from Shanghai all very recent

**Comment by aviczhl2** [comment]
+2 South Korea

**Comment by FedeGueli** [comment]
+2 Japan,Singapore (local case)

**Comment by FedeGueli** [comment]
@ryhisner @hynnspylor @avichzl2 @nkrmnzr i think all these EG.5.1* plus 455 should be transferred to Pango at 10seqs they clearly go and there is a need to distinguish them ( a taxonomy need more than epi but still, it was as 346 460+444 popped up even if the real competitive at the end have been 3-4-5 lineages i think is right to describe the tree. assuming Pirola not doing a BA.1 to everyone)

**Comment by aviczhl2** [comment]
I think all of these>10 branches(there are at least 5 of them now) shall be designated. Currently the only designated is HK.3, however non-HK.3 flips are nothing worse than HK.3 and all of them are growing fast.

**Comment by FedeGueli** [comment]
Thx @aviczhl2 i will propose it indeed.
