### ISSUE TITLE
FL.10 saltation with ORF1a:G4178S, ORF1b:N1382S, S:K356T, S:T523N, ORF3a:D27N, ORF7b:N38I, N:K373N, N:D415E (14 seqs, Canada and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#527]
**Defining Mutations:** `FL.10` > `C18888T` > `T11422C, G12797A(ORF1a:G4178S/nsp9_G38S), A17612G(ORF1b:N1382S/nsp13_N459S), A22629C(S:K356T), C23130A(S:T523N), G25471A(ORF3a:D27N), A27868T(ORF7b:N38I), G29392C(N:K373N), C29518A(N:D415E)`
**Query:** `A22629C, C23130A, G25471A`
**Earliest seq:** 2023-06-10 (`EPI_ISL_17821379`, Alberta, Canada)
**Latest seq:** 2023-07-20 (`EPI_ISL_18055211`, Ontario, Canada)
**Sampled Countries:** Canada (4, Ontario/3, Alberta/1), US (1, Washington)

<details><summary>Genomes: </summary>

`EPI_ISL_17821379, EPI_ISL_17994047, EPI_ISL_18030530, EPI_ISL_18040062, EPI_ISL_18055211`

</details>

**Saltation Profile:**

mutations on neatest neighboring branch:

```
nuc	unique	G12797A, A17612G, C23130A, G25471A, A27868T, G29392C, C29518A
nuc	homoplasies	T11422C, A22629C
ORF1ab	unique	G4178S, N5783S
S	unique	T523N
S	homoplasies	K356T
ORF3a	unique	D27N
ORF7b	unique	N38I
N	unique	K373N
N	homoplasies	D415E
```
details
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bfef02e2-f8f3-4746-8ad7-4750172770a6)

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3502e_a4dee0.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/85922154-d13c-4f95-a0e6-9890a5cd647d)

**Comment by FedeGueli** [comment]
Thx good catch, @ryhisner could you see some treatment related pattern here?  
And leaving mov aside, also that double C > A mutations seems interesting 
G12797A, A17612G, C23130A, G25471A, A27868T, G29392C, C29518A,T11422C, A22629C

**Comment by ryhisner** [comment]
Definitely not molnupiravir-related. 5/9 mutations on the saltation branch are transversions, which is much higher percentage than normal.

**Comment by FedeGueli** [comment]
One more from Canada, Alberta

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/commit/a397154801c054bea353ab455553242efd4bd0aa

designated FL.10.2
