### ISSUE TITLE
GL.1 with ORF1a:V2061I, ORF1a:I2138V, ORF1b:T284I, ORF1b:P976L, S:A222V, and S:E1144Q (2 seq. Portugal)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#529]
Portugal/PT48905/2023|EPI_ISL_18052412|2023-07-10
Portugal/PT48912/2023|EPI_ISL_18052419|2023-07-05
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/97815554-5514-40f4-a56a-3bd817026d6f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c91d_aa56e0.json?c=gt-S_1144&label=id:node_6264848
This is the first time we've seen S:A222V on XAY lineages.
S:E1144Q happens quite frequently (for a G to C change). It is in DU.1(BQ.1.1.2.1), which had some advantage over BQ.1.1. Besides S:E1144Q, DU.1 has S:Y144- and S:D253G over BQ.1.1, which are also in GL.1.
https://jbloomlab.github.io/SARS2-mut-fitness/S.html has S:E1144Q with fitness of 2.40.
![2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/d91757f0-dc00-4810-ba34-fecb99713931)
The 4 ORF1ab changes aren't rare either. All of them have fitness above 0 in https://jbloomlab.github.io/SARS2-mut-fitness/.
ORF1b:P976L is in B.1.427.

Gisaid query: C4321T, C4456T, G22820A,C22227T (edited)

**Comment by FedeGueli** [comment]
I think @ryhisner spotted this one too.
GL.1 seems circulating quite well in Portugal. Thx for proposing

**Comment by FedeGueli** [comment]
No new sequences closing it for now
