### ISSUE TITLE
Potential FY.6 (XBB.1.22.1.6) and XBB.1.5* (with T17124C) recombinant (62 seqs, mainly in Philippines and Japan, 10 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#530]
**Query:** `C2037T, T17124C, A22161G`
**Earliest seq:** 2023-03-29 (`EPI_ISL_17819055`, Davao, Philippines)
**Latest seq:** 2023-07-22 (`EPI_ISL_18051836`, Fukui, Japan)
**Sampled Countries:** Philippines (26), Japan (11), Australia (5), USA (4, California, 2 with travel history to Taiwan, China), China (3, Fujian/1, Guangdong/1, Shanghai/1), Singapore (2), Germany (1), South Korea (1)

**Recombinant Profile:** 
- Mutation gained on **FY.6**: `T17124C`
- Mutation lost on **FY.6**: `T2935C`
- XBB.1.5 could contributed between two breakpoints within `2037 (ORF1a:A591)` to `2935` and `17124` to `22161 (S:Y200)`, both 3' and 5' end are from **FY.6** donor. _OR_ as @FedeGueli [suggested](https://github.com/sars-cov-2-variants/lineage-proposals/issues/530#issuecomment-1663760049), there's one breakpoint possiblity that a XBB.1.5* with both `C2037T (ORF1a:A591V)` and  `T17124C` from 5' end, recombined XBB.1.22.1* from 3' end, breakpoint between `17124` to `22161 (S:Y200)`.

<details><summary>Genomes: </summary>

`EPI_ISL_17618343, EPI_ISL_17653060, EPI_ISL_17669269, EPI_ISL_17669271, EPI_ISL_17685392, EPI_ISL_17689338, EPI_ISL_17704344, EPI_ISL_17718856, EPI_ISL_17741717, EPI_ISL_17790405, EPI_ISL_17796559, EPI_ISL_17802590, EPI_ISL_17802872, EPI_ISL_17802904, EPI_ISL_17802906, EPI_ISL_17815658, EPI_ISL_17819033, EPI_ISL_17819038, EPI_ISL_17819054-17819055, EPI_ISL_17819063, EPI_ISL_17819083, EPI_ISL_17819200, EPI_ISL_17819204, EPI_ISL_17819213, EPI_ISL_17819223, EPI_ISL_17819229, EPI_ISL_17819258-17819259, EPI_ISL_17819306-17819309, EPI_ISL_17948680-17948681, EPI_ISL_17948686, EPI_ISL_17948729, EPI_ISL_17948865, EPI_ISL_17948878, EPI_ISL_17948922, EPI_ISL_17948933, EPI_ISL_17958377, EPI_ISL_17997390, EPI_ISL_18013358, EPI_ISL_18033978, EPI_ISL_18040384, EPI_ISL_18040386, EPI_ISL_18040442, EPI_ISL_18044090, EPI_ISL_18051833, EPI_ISL_18051836, EPI_ISL_18051926, EPI_ISL_18058420`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24076_b746d0.json?f_userOrOld=uploaded%20sample

UShER now placed it under FY.6
![placement](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/cd26893d-a57b-4224-9ec6-4d45c6d22f92)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/631d3b67-81b8-4bbc-a5bf-44659ed9964d)

**Trivia:**
- While checking recent uptick of `S:S939F` I discovered this branch now placed under **FY.6**, and soon realized there was once a placement problem #11 , if this is not the case recurring, it favors to be a recombinant of **FY.6** and **XBB.1.5*** with `T17124C`.

**Comment by FedeGueli** [comment]
It is also possible that Orf1a:A591V could be inherited from the XBB.1.5 side : 
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1a%3A591V&nextcladePangoLineage=XBB.1.5*&nextcladePangoLineage1=XBB.1.22.1*&
and then Usher placing it in FY.6 for that reason.

**Comment by FedeGueli** [comment]
> > It is also possible that Orf1a:A591V could be inherited from the XBB.1.5 side : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1a%3A591V&nextcladePangoLineage=XBB.1.5*&nextcladePangoLineage1=XBB.1.22.1*& and then Usher placing it in FY.6 for that reason.
> 
> but that will miss `ORF9b:I5T (T28297C)`, [try this](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1a%3A591V&nucMutations=T28297C&nextcladePangoLineage=XBB.1.5*&nextcladePangoLineage1=XBB.1.22.1*&analysisMode=CompareEquals)

No i was meaning a recombinant with XBB.1.5 plus orf1a:A591V that got from 0 to 17125 from XBB.1.5 then xbb.1.22.1  (generic not FY.6)

**Comment by FedeGueli** [comment]
Now it is even more clearer the recombination:
![Schermata 2023-08-13 alle 17 52 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f8c65753-a161-4a9e-8d50-b69ac8d1495f)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1a%3A591V&nextcladePangoLineage=XBB.1.5*&nextcladePangoLineage1=FY.6*&nucMutations2=C2037T%2CT17124C%2CA22161G&analysisMode=CompareEquals&

it likely took the orf1ab from XBB.1.5 + orf1a:A591V and then from NTD ahead from FY.6.


Please propose it.
