### ISSUE TITLE
XBB.1.5.10 + S:R646S (9 seqs Puerto Rico)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#532]
Sub-lineage of: XBB.1.5.10
Substitution on top of XBB.1.5.10: S:R646S (C23498A)
Earliest sequence: 2023-05-31, Puerto Rico — EPI_ISL_17885195
Most recent sequence: 2023-07-21, Puerto Rico — EPI_ISL_18107263
Countries circulating: Puerto Rico (9)
Number of sequences: 8
GISAID nucleotide query: T22928C,C23498A
CovSpectrum query: [XBB.1.5.10* (Nextclade) + C23498A](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C23498A&nextcladePangoLineage=xbb.1.5.10*&)

Worth monitoring since XBB.1.5.10 is most prevalent in Puerto Rico.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2eaa8_ba0a90.json?branchLabel=Spike%20mutations&label=id:node_6859551

![Screenshot 2023-08-03 at 08-54-13 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ singleSubtreeAuspice_genome_2eaa8_ba0a90 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/5ebc2bcd-e93b-45ca-a09e-8db95a199926)

**Comment by FedeGueli** [comment]
no new sequence closing it for now
