### ISSUE TITLE
XBB.2.3/XBB.1.16 recombinant, USA (29 seq, Sept 4)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#535]
I don't want to spend as much time as I usually do on this one, but here are the basics. 

**GISAID IDs**: EPI_ISL_18012194, EPI_ISL_18012785, EPI_ISL_18061007
**Location**—USA (2 from Iowa, 1 from Delaware)
**Collection Dates**: July 6, 10, 19

**Breakpoint**: Between S:521 and ORF7a:13 (23123-27430)

Mutations not found in any canonical XBB.2.3 or XBB.1.16 lineages: 
**Nucleotide**—T6394C, G8863T, T14305C, G18636A, T18882C, ∆22190-22192, C27684T, C27513T, T28034C
**AA**—S:I210del, ORF1b:Y280H

There have been 10 XBB.2.3 sequences from Bangladesh with S:I210del, T6394C, and T18882C so that's probably where the XBB.2.3 portion originated, though XBB.2.3 sequences with those three mutations have since been detected in other countries. 

Gisaid query : T6394C, G8863T, T14305C (edited)

Tree: (edited):
![Schermata 2023-08-04 alle 00 31 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f01de9de-af73-4669-ab2e-9c79f9dbb990)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c0f1_c2a7a0.json?label=id:node_7178370

Rapid picture: (edited)
 
![Schermata 2023-09-05 alle 02 17 48](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3e566888-e957-4c28-93ba-acb44de89b3d)

**Comment by FedeGueli** [comment]
Thx Ryan i ve edited the missing parts. It is cool cause it is de facto a XBB.2.3 with Orf8:8stop!

**Comment by aviczhl2** [comment]
The XBB.2.3 comes from #328

**Comment by ryhisner** [comment]
This looked dead for a bit, but three more sequences popped up from Texas in the last few days with collection dates of July 26, August 2, and August 6. EPI_ISL_18098772, EPI_ISL_18099225, EPI_ISL_18107710

**Comment by ryhisner** [comment]
This has doubled from ~15 to about ~30 sequences in the past week. I have no idea why. There is not one particularly branch that has taken off or anything. Still a really scattered lineage. 
<img width="1464" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a72f9f71-9293-4889-8ce7-516220d1357a">

**Comment by FedeGueli** [comment]
i was checking this jsut now and i saw ur comment . to be proposed with a certain urgence it is fast. dunno why.

**Comment by FedeGueli** [comment]
But if we think twice it is xbb.2.3 + all the stuff of XBB.1.16 so it shouldnt surprise us..

**Comment by FedeGueli** [comment]
Now proposed : https://github.com/cov-lineages/pango-designation/issues/2260#issuecomment-1705620693

**Comment by FedeGueli** [comment]
Designated HCW
