### ISSUE TITLE
FL.3.3 with S:M1229T, S:F186L , S:E583D and  further mini-saltation with S:T573I (12 seqs, Wales)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#541]
**Defining Mutations for main proposal:** `FL.3.3` > `T25248C(S:M1229T)` > `C21928T, T22118C(S:F186L), G23311T(S:E583D)`
**Query:** `C21928T, T22118C, G23311T`

_Defining Mutations for further mini-saltation with **S:T573I**_: >> `A11782G, G12892A, T22777C, C23280T(S:T573I), C25378T`
**Query:** `T22118C, C23280T, G23311`

**Earliest seq:** 2023-02-18 (`EPI_ISL_17095054`, England, UK)
**Latest seq:** 2023-07-11 (`EPI_ISL_18052687`, Wales, UK)
**Sampled Countries:** UK (12, England/9, Wales/3), Spain (1), USA (1, New York)

<details><summary>Genomes</summary>

`EPI_ISL_17095054, EPI_ISL_17153951, EPI_ISL_17257145, EPI_ISL_17257163, EPI_ISL_17257283, EPI_ISL_17274004, EPI_ISL_17381780, EPI_ISL_17381822, EPI_ISL_17427173, EPI_ISL_17429793, EPI_ISL_17542319, EPI_ISL_17730147, EPI_ISL_18052687, EPI_ISL_18052692`

</details>

<details><summary>non-GISAID genomes</summary>

```
Wales/CLIMB-CM7YGD18/2023|2023-07-17
Wales/CLIMB-CM7YJ8UF/2023|2023-07-17
Wales/CLIMB-CM7YK5CH/2023|2023-07-17
Wales/CLIMB-CM7Y8MR3/2023|2023-07-17
Wales/CLIMB-CM7YRQ7K/2023|2023-07-17
```
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18314_cd18c0.json?f_userOrOld=uploaded%20sample&label=id:node_6813070
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ba884560-2de6-4767-bd26-2d0798012997)

**Trivia:**
- A spike mutation fiesta.
- Most of the sequences probably have extra deletions like `ORF1a:82-86del` and `ORF7a:97-101del`
![deletions](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0fb84c08-2043-49b5-a91e-0c351dc6a464)

**Comment by FedeGueli** [comment]
The parental lineage is dead. While the welsh sublineage appears to be superfast we should track it very closely, although Wales used to do targeting sequencing so it could be nothing.
Still very interestin to see a 4 Spike mutations lineage without any in the RBD

**Comment by FedeGueli** [comment]
> no new seqs

ty!
