### ISSUE TITLE
XBC.1.3 with orf7a frameshifted ( a sort of SARS COV 2 Lite version referring to accessory proteins truncations/expression ablated) with prevalence in NZL(7 %) and Australia (1%) in october  (942 seqs) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#542]
CC @corneliusroemer 
take a look at this please cause it seems gaining high prevalence in NZL : 
References: 
https://twitter.com/RhysTWhite/status/1687292350077509633
https://www.esr.cri.nz/assets/CGID_40_Report.pdf
And i personally checked to be around 10% of sequences in WA,Australia in July (27/268)

Proposal (**Edited** after @ryhisner ongoing review)

**NEW QUERY:   A3063T,C12786T  ( **I have understood my previous query missed half of the lineage 22-08)**
Tree:
![Schermata 2023-08-04 alle 12 40 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1ec3e19f-a6ef-4c30-b164-c82c7564e2d4)
![Schermata 2023-08-04 alle 12 41 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c2c82012-722d-4ed4-809d-4bba9c388fea)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_14c24_ccfd60.json?c=gt-ORF1ab_933&label=id:node_6267951

Defining mutations:
XBC.1.3 (C25614T) >>ORF1b:S759N (G15743A) > C6145T > ORF1a:T4174I (C12786T) > ORF1a:Q455K (C1628A) > ORF3a:D173G (A25910G)> ORF1a:V2061A (T6447C) > **Orf1a::E933V** (A3063T) 

Note that NSP3_E115V is [predicted](https://jbloomlab.github.io/SARS2-mut-fitness/nsp3.html) to be deleterious: 
![Schermata 2023-08-04 alle 12 49 53](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c88c71db-bf00-4ec0-af6c-113bb542c4bb)

EDITED (all CREDITS to RYAN @ryhisner)
Nextclading it most of the recent sequences have another frameshift in addition to the one at Orf7b defining of all XBC lineages, while the frameshift in Orf8 is likely an artifact coming from the 119-120 deletion that all XBC have (credit : @ryhisner)

Orf7a Orf7b Orf8 
![Schermata 2023-08-04 alle 13 01 53](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/43e86284-9cf4-475d-9085-adb7958805f7)

Orf7a:
![Schermata 2023-08-04 alle 13 02 42](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a55c9b02-7d3e-4ed0-973a-886cee20966d)

![Schermata 2023-08-04 alle 13 03 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9ef35749-8501-4bfc-8a06-6fMc8860b8883)

This would come in addition to the Mutations described by @ryhisner that ablates the expression of Orf8 and to the frameshift that creates a brande new Orf7b in all XBC

Samples: 215 
<Details>
<Summary>
Epi_ISLs
</Summary>
 EPI_ISL_16947476-16947477, EPI_ISL_17150345, EPI_ISL_17229036-17229037,
EPI_ISL_17243731, EPI_ISL_17244429, EPI_ISL_17280579,
EPI_ISL_17280677, EPI_ISL_17324264, EPI_ISL_17374642,
EPI_ISL_17374702, EPI_ISL_17374779, EPI_ISL_17396529,
EPI_ISL_17398429, EPI_ISL_17408745, EPI_ISL_17408753,
EPI_ISL_17408786, EPI_ISL_17409026, EPI_ISL_17463288,
EPI_ISL_17463298, EPI_ISL_17463301, EPI_ISL_17463427,
EPI_ISL_17463478, EPI_ISL_17468444, EPI_ISL_17527367,
EPI_ISL_17527433, EPI_ISL_17561363, EPI_ISL_17561455,
EPI_ISL_17561505, EPI_ISL_17606420, EPI_ISL_17606448,
EPI_ISL_17606549, EPI_ISL_17606593, EPI_ISL_17606609,
EPI_ISL_17624144, EPI_ISL_17656325, EPI_ISL_17656492,
EPI_ISL_17656945, EPI_ISL_17657022, EPI_ISL_17660912-17660913,
EPI_ISL_17660921-17660922, EPI_ISL_17660953, EPI_ISL_17661132,
EPI_ISL_17661143, EPI_ISL_17661153, EPI_ISL_17661178,
EPI_ISL_17661199, EPI_ISL_17661208, EPI_ISL_17661399,
EPI_ISL_17663031, EPI_ISL_17696601, EPI_ISL_17696625,
EPI_ISL_17696724, EPI_ISL_17703804, EPI_ISL_17703812,
EPI_ISL_17703902, EPI_ISL_17703913, EPI_ISL_17718746,
EPI_ISL_17718755, EPI_ISL_17724287, EPI_ISL_17724307,
EPI_ISL_17724310-17724311, EPI_ISL_17742560, EPI_ISL_17761978,
EPI_ISL_17765664, EPI_ISL_17765723, EPI_ISL_17765725-17765727,
EPI_ISL_17780049, EPI_ISL_17780061, EPI_ISL_17780068,
EPI_ISL_17790945, EPI_ISL_17790993, EPI_ISL_17791008,
EPI_ISL_17791011, EPI_ISL_17791015, EPI_ISL_17791021,
EPI_ISL_17791032, EPI_ISL_17793415, EPI_ISL_17793510,
EPI_ISL_17793635, EPI_ISL_17793647, EPI_ISL_17793655,
EPI_ISL_17793709, EPI_ISL_17793730, EPI_ISL_17793757,
EPI_ISL_17793775, EPI_ISL_17793808, EPI_ISL_17793871,
EPI_ISL_17802092, EPI_ISL_17802214, EPI_ISL_17802320-17802321,
EPI_ISL_17802342, EPI_ISL_17802434, EPI_ISL_17802447,
EPI_ISL_17802654, EPI_ISL_17802901, EPI_ISL_17802960,
EPI_ISL_17803004, EPI_ISL_17803216, EPI_ISL_17803247,
EPI_ISL_17803257, EPI_ISL_17822210, EPI_ISL_17822278,
EPI_ISL_17822307, EPI_ISL_17822446, EPI_ISL_17822460,
EPI_ISL_17822475, EPI_ISL_17822606, EPI_ISL_17822737,
EPI_ISL_17822745, EPI_ISL_17823433, EPI_ISL_17823735,
EPI_ISL_17824333, EPI_ISL_17824368, EPI_ISL_17832463,
EPI_ISL_17849398, EPI_ISL_17849448, EPI_ISL_17849458,
EPI_ISL_17849636, EPI_ISL_17849644, EPI_ISL_17865694,
EPI_ISL_17957288, EPI_ISL_17961814, EPI_ISL_17962327,
EPI_ISL_17966998, EPI_ISL_17985016, EPI_ISL_17985039,
EPI_ISL_17997017, EPI_ISL_17999352-17999353, EPI_ISL_17999477,
EPI_ISL_17999496, EPI_ISL_17999509, EPI_ISL_17999559,
EPI_ISL_17999572-17999573, EPI_ISL_17999606, EPI_ISL_17999611,
EPI_ISL_17999613, EPI_ISL_17999615, EPI_ISL_17999644,
EPI_ISL_17999658, EPI_ISL_17999668, EPI_ISL_17999733-17999734,
EPI_ISL_17999752, EPI_ISL_17999781, EPI_ISL_17999786,
EPI_ISL_17999799, EPI_ISL_17999817-17999818, EPI_ISL_17999821,
EPI_ISL_17999828, EPI_ISL_17999838-17999839, EPI_ISL_17999841,
EPI_ISL_17999843, EPI_ISL_17999869, EPI_ISL_17999895,
EPI_ISL_17999940, EPI_ISL_17999965, EPI_ISL_17999978,
EPI_ISL_18000013, EPI_ISL_18000030, EPI_ISL_18000077,
EPI_ISL_18000232, EPI_ISL_18000242, EPI_ISL_18000261,
EPI_ISL_18012204, EPI_ISL_18012234-18012236, EPI_ISL_18047818-18047821,
EPI_ISL_18047823, EPI_ISL_18047833, EPI_ISL_18047838,
EPI_ISL_18047842, EPI_ISL_18047879, EPI_ISL_18047881,
EPI_ISL_18047904, EPI_ISL_18047911, EPI_ISL_18047948,
EPI_ISL_18047979, EPI_ISL_18048200, EPI_ISL_18048619-18048621,
EPI_ISL_18048626, EPI_ISL_18053228-18053229, EPI_ISL_18060318,
EPI_ISL_18060323, EPI_ISL_18060325-18060326, EPI_ISL_18060332,
EPI_ISL_18060363-18060364, EPI_ISL_18060367, EPI_ISL_18060370,
EPI_ISL_18060375, EPI_ISL_18060384, EPI_ISL_18060396,
EPI_ISL_18060424, EPI_ISL_18060429, EPI_ISL_18060447,
</details>

**Comment by FedeGueli** [comment]
@ryhisner i ve assigned this to you, could you help when you have some spared time?? please!

**Comment by ryhisner** [comment]
I've looked at the deletion, which according to NextClade are ∆27565-27581. There are no new nucleotide mutations in ORF7a that I can see in these sequences. The 17-nucleotide deletion causes a frameshift that leads to a stop codon after the production of just five more AA, which I believe would be CFCLS.

<img width="1503" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2ad10570-9f82-481b-94a8-a95a7ba9adcb">

**Comment by FedeGueli** [comment]
> I've looked at the deletion, which according to NextClade are ∆27565-27581. There are no new nucleotide mutations in ORF7a that I can see in these sequences. The 17-nucleotide deletion causes a frameshift that leads to a stop codon after the production of just five more AA, which I believe would be CFCLS.
> 
> <img alt="image" width="1503" src="https://user-images.githubusercontent.com/33738461/258427743-2ad10570-9f82-481b-94a8-a95a7ba9adcb.png">

Thank you very much @ryhisner just to understand better:
we will have a classical XBC.1.3 until Orf7a:T57 then new 58C 59F 60C 61L 62S , so Orf7a should be 62AA long then it should be still there the shortes Orf7b with 34AA and then Orf8 with ablated expression by 27890 mutation and (orf8:K2T too messing the signal peptide , right?) then a inframe deletion at the end of orf8:119-120 with the delta deletion of 28271 that overexpresses ORf9b .
Is my description correct???

Took together all these changes brings this XBC.1.3 sublineage very far from WT and everything else circulating.


Back to Orf7a to Cisteine so close could have some effect ? maybe @thomaspeacock could look into.

**Comment by corneliusroemer** [comment]
Looks mostly like founder to me, this just happens to be the XBC.1(.3) that grew big and made it in AUS/NZ - let's see

**Comment by ryhisner** [comment]
That sounds like a great summary of the situation to me, Fede!

**Comment by FedeGueli** [comment]
> Looks mostly like founder to me, this just happens to be the XBC.1(.3) that grew big and made it in AUS/NZ - let's see

yeah let see consider there are two regions WA and NZL  where it apparently gained significant prevalence in the meanwhile other lineages were circualting. But some Australian states as WA and SA and NZL hardly are reproducible examples elsewhere still something to watch closely.

**Comment by FedeGueli** [comment]
224 as today. In Western Australia seems hanging around 10% but without clear trend up hopefully.

**Comment by FedeGueli** [comment]
Big upload from Tasmania today: looking at samples from July it was  the most sequenced with 11 out f 68 samples at pair with GL.1!! Not one but two deltacrons leading while EG.5.1 family stopped at 8 seqs. 

So this Sars Cov Lite version seems very efficient to gain rapidly a good share at least in Oceania scoring at 30% in Nzl 15% in Tasmania 10% in Western Australia

**Comment by FedeGueli** [comment]
it now represents 24 samples out of 387 nationally in Australia after July 25. @corneliusroemer

**Comment by oobb45729** [comment]
nuc:C25614T is also in AY.4.2. It introduces an early stop codon on ORF3d-2 (and ORF3d).

**Comment by FedeGueli** [comment]
> nuc:C25614T is also in AY.4.2. It introduces an early stop codon on ORF3d-2 (and ORF3d).

Thank you!

**Comment by FedeGueli** [comment]
I have found a more efficient query. i am re estimating prevalences now:
State/ June/July/ August
Oceania/ 2%/ 6% / 8%
Australia/ >2%/ 6%/ 8%
NSW/ 0,3%/ 4% / 7%
QLD 2,5%/ 3% / 9%
TAS  9% / 19%  / 10%
WA 7% / 11% / 19%
NZL 0,3% / 6%

Ping @corneliusroemer this kind of pattern to me could not be explained with founder effect

**Comment by FedeGueli** [comment]
Last samples from WA, Tas and Japan

**Comment by FedeGueli** [comment]
prevalence around 5% now.

**Comment by FedeGueli** [comment]
first data from September it seems stable below 10% in Australia

**Comment by FedeGueli** [comment]
729 as today. @ryhisner noticed something further in this sublineage.

**Comment by FedeGueli** [comment]
This is still close to 10% in Australia.

**Comment by FedeGueli** [comment]
@corneliusroemer i suggest to designate it: very big and circulating since months at >5% in Oceania and an unique shifts in accessory proteins

**Comment by FedeGueli** [comment]
only 3 samples from November closing it now.

**Comment by FedeGueli** [comment]
Designated XBC.1.3.1 via https://github.com/cov-lineages/pango-designation/commit/f3e9fb3155eef8b8475c76cc62a9040fdb352981
