### ISSUE TITLE
XBB.1.5.37 with ORF1a:V2130I, ORF1a:L2095I and S:F456L (83 seqs, mainly in France, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#543]
**Defining Mutations:** `XBB.1.5.37` > `G6653A(ORF1a:V2130I/nsp3_V1312I)` > `C6548A(ORF1a:L2095I/nsp3_L1277I), T22928C(S:F456L)`
**Query:** `C6548A, T22928C, A24696G`
**Earliest seq:** 2023-03-20 (`EPI_ISL_17383802`, Amiens, France)
**Latest seq:** 2023-07-25 (`EPI_ISL_18059108`, Dublin, Ireland)
**Sampled Countries:** France (32), USA (8, Texas/2, Virginia/2, Hawaii/1, New York/1, Oklahoma/1, Utah/1), Belgium (1), Canada (1, Ontario), Ireland (1), Italy (1), Switzerland (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17383802, EPI_ISL_17640570, EPI_ISL_17676172, EPI_ISL_17677207, EPI_ISL_17677346, EPI_ISL_17705187, EPI_ISL_17705221, EPI_ISL_17705276, EPI_ISL_17713816, EPI_ISL_17715889, EPI_ISL_17716690, EPI_ISL_17716748, EPI_ISL_17732256-17732257, EPI_ISL_17732266-17732267, EPI_ISL_17769466, EPI_ISL_17781531, EPI_ISL_17831259, EPI_ISL_17831359, EPI_ISL_17971755, EPI_ISL_17974732, EPI_ISL_17974770-17974771, EPI_ISL_17974787, EPI_ISL_17975754, EPI_ISL_17976193, EPI_ISL_17976199, EPI_ISL_17979228, EPI_ISL_17994050, EPI_ISL_18010120, EPI_ISL_18015508, EPI_ISL_18026667, EPI_ISL_18026677, EPI_ISL_18026719-18026720, EPI_ISL_18032361, EPI_ISL_18049060, EPI_ISL_18057185, EPI_ISL_18057348, EPI_ISL_18057690, EPI_ISL_18057849, EPI_ISL_18059108, EPI_ISL_18060578, EPI_ISL_18064762`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_194c_cec2c0.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/11d49b98-c3cd-44b3-8428-d9be10aedad3)

**Trivia:**
- There's only a few sequences from `G6653A(ORF1a:V2130I)` branch withouth `A24696G(S:K1045R)`, need help to figure out if this branch is misplaced **XBB.1.5.37** (**XBB.1.5** on `T10204C` with `S:K1045R`).

**Comment by FedeGueli** [comment]
@angiehinrichs also this one as suggested by the author could be just a misplacement of XBB.1.5.37

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs also this one as suggested by the author could be just a misplacement of XBB.1.5.37

Yep, the sequences have been moved to XBB.1.5.37 in the 2023-08-17 tree.

**Comment by FedeGueli** [comment]
Please propose it
