### ISSUE TITLE
XBB.1.5 with ORF8:I47V and S:F456L (117 seqs, mainly in Spain, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#544]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `A21366T` > `C6268T` > `C29119A` > _`A28032G(ORF8:I47V)`_ > `T22928C(S:F456L)`
**Query:** `C6268T, A21366T, T22928C, -A17799G`
**Earliest seq:** 2023-03-03 (`EPI_ISL_17482561`, Granada, Andalusia, Spain)
**Latest seq:** 2023-07-20 (`EPI_ISL_18044763`, Isere, Auvergne-Rhone-Alpes, France)
**Sampled Countries:** Spain (71), USA (6, California/2/ex. Mexico; New York/2/ex. Italy; Delaware/1; Massachusetts/1), Austria (5), France (3)

<details><summary>Genomes: </summary>

`EPI_ISL_17482561, EPI_ISL_17678943, EPI_ISL_17678953, EPI_ISL_17678956-17678957, EPI_ISL_17679065, EPI_ISL_17679082, EPI_ISL_17679149, EPI_ISL_17679153, EPI_ISL_17679159, EPI_ISL_17679168, EPI_ISL_17679171, EPI_ISL_17679259, EPI_ISL_17679278-17679282, EPI_ISL_17679286-17679290, EPI_ISL_17679626, EPI_ISL_17734964, EPI_ISL_17734967, EPI_ISL_17768521, EPI_ISL_17768655, EPI_ISL_17777136, EPI_ISL_17780240, EPI_ISL_17780242-17780243, EPI_ISL_17780704, EPI_ISL_17780717, EPI_ISL_17780929, EPI_ISL_17782437, EPI_ISL_17782553, EPI_ISL_17782555, EPI_ISL_17782600, EPI_ISL_17787138, EPI_ISL_17787184, EPI_ISL_17795955, EPI_ISL_17797658, EPI_ISL_17817656, EPI_ISL_17817827, EPI_ISL_17817842, EPI_ISL_17830600, EPI_ISL_17833506, EPI_ISL_17878362, EPI_ISL_17881269, EPI_ISL_17948501, EPI_ISL_17948521, EPI_ISL_17948561-17948562, EPI_ISL_17948579, EPI_ISL_17948588, EPI_ISL_17948661, EPI_ISL_17949008, EPI_ISL_17949030, EPI_ISL_17949033, EPI_ISL_17949096, EPI_ISL_17949322, EPI_ISL_17949395-17949396, EPI_ISL_17949583-17949584, EPI_ISL_17949611, EPI_ISL_17949972, EPI_ISL_17973561, EPI_ISL_17974798, EPI_ISL_17976571, EPI_ISL_17989173, EPI_ISL_17989180, EPI_ISL_17989973, EPI_ISL_17990075, EPI_ISL_17990079, EPI_ISL_17990086, EPI_ISL_17990123, EPI_ISL_18042102, EPI_ISL_18042238, EPI_ISL_18042286, EPI_ISL_18042311, EPI_ISL_18042318, EPI_ISL_18044763, EPI_ISL_18058870-18058871`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e5fa_cf3f60.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8f9fdc27-6b4a-406a-87ea-d8bc7b3e8ed5)

**Comment by FedeGueli** [comment]
from June.lets see if it manages to accumulate recent samples-

**Comment by FedeGueli** [comment]
More it cant compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C6268T%2CA21366T%2CT22928C&analysisMode=CompareToBaseline&
