### ISSUE TITLE
EG.6.1 Sublineage with S:L242I, S:A484K, ORF1a: P1786L, ORF1b:R1576K (10 seq, 8 countries, Sept 4)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#546]
### **Description**
**Sub-lineage of:** EG.6.1 (XBB.1.9.2.6.1 = EG.6 + S:F456L)
**Earliest sequence:** 2023-7-7, Spain — EPI_ISL_17995565
**Most recent sequence:** 2023-7-24, USA travel from Croatia — EPI_ISL_18067206
**Countries circulating:** Spain (1), Portugal (1), USA/Croatia (1)
**Number of Sequences:** 3
**GISAID AA Query:** Spike_E484K, Spike_F486P, Spike_L242I
**GISAID Nucleotide Query:** (C22286A, G23012A, -A23013C, -A22812C, -G25563T — The previous search missed a couple, but this one catches them all)  
**CovSpectrum Query:** Nextcladepangolineage:EG.6.1* & S:E484K
**Substitutions on top of EG.6.1:**
**Spike:** L242I, E484K
**ORF1a:** P1786L
**ORF1b:** R1576K
**Nucleotide:** C5622T, G18194A, C22286A, G23012A, C23013A, C27881T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.6.1_L242I_E484K.json?c=gt-S_484&label=id:node_2995026

<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/890162bc-680c-41bc-a99b-ef0a8014b1ad">

 
**Evidence**
Speaks for itself. S:A484K is a 2-nucleotide mutation. Three sequences from three countries, one of them a travel sequence from a country with not much recent sequencing. The most recent sequence from Croatia was collected on May 16. 
 
Note that there are four sequences listed on GISAID, but one of them is a pooled sample from Ginkgo Bozoworks, so it's a duplicate of the travel sequence.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17995565, EPI_ISL_18052373, EPI_ISL_18067206
</details>

**Comment by ryhisner** [comment]
This one's obviously no growing too fast, but the geographic spread is intriguing. We've now seen sequences from Croatia, Portugal, Spain, South Korea, and USA.

**Comment by FedeGueli** [comment]
I think it is worth a proposal @ryhisner the coming back of S:E484K should be well clear to everyone being a known antigenic site versus 1-2 wave immunity.

**Comment by FedeGueli** [comment]
@ryhisner ORF1a: P1786L should be PLPro_P223L not finding a lot about it tough.

**Comment by ryhisner** [comment]
11 sequences now on GISAID, but two are pooled samples from Ginkgo. There's an individual sequence paired with one of the pooled samples, but the latest pooled sample does not have a corresponding individual sequence. HOPefully, we eventually get an individual sequence for that one so we can find out what country the traveler came from. 

Also, one is a spike-only sequence from South Korea.

**Comment by FedeGueli** [comment]
Please ryan keep the number shown by Gisaid.  no need to specify in the headline (but very good to do in the proposal/comment) the fact one or two are duplicates! so a rapid check could go without more work.

**Comment by FedeGueli** [comment]
> Please ryan keep the number shown by Gisaid. no need to specify in the headline (but very good to do in the proposal/comment) the fact one or two are duplicates! so a rapid check could go without more work.

Scratch this i messed things up.

I edited the nuc query cause it doesnt work : this the new one: C5622T, G18194A, C27881T

**Comment by FedeGueli** [comment]
Propose when reaches 10.

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by ryhisner** [comment]
Done. https://github.com/cov-lineages/pango-designation/issues/2257

**Comment by FedeGueli** [comment]
Thank you

**Comment by FedeGueli** [comment]
Designated EG.6.1.1 via https://github.com/cov-lineages/pango-designation/commit/ab56ccdfc268869c158495ed61ee5809810212bc
