### ISSUE TITLE
Saltation of AY.25 with S:L455F,S:F456L,S:E484A,S:T859N and other mutations.(4 sequences,USA)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#55]
Description 
Sub-lineage of:AY.25
Earliest sequence:2022-9-24,USA,EPI_ISL_15306067
Latest sequences:2023-3-28,USA,EPI_ISL_17651803
Countries:USA（4）
Number of Sequences:4
Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3eebc_3bff0.json?f_userOrOld=uploaded%20sample&label=id:node_4765623
![IMG_0319](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/a9d8b864-7265-44dc-b502-d0f7847622dc)
![IMG_0320](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/e9282593-f08f-4d88-bb4e-6a3c46b93310)

Sequences:
EPI_ISL_15306067
EPI_ISL_17037388
EPI_ISL_17222365
EPI_ISL_17651803

**Comment by FedeGueli** [comment]
This should be  a chronic infection and it has been tracked by @ryhisner since it was two. 
Until we have no evidence that it has transmitted we will leave this closed. Thx for finding it.

**Comment by Outpfmance** [comment]
@FedeGueli I don't think this is a chronic infection in the same patient, let's wait and see more sequences.

**Comment by ryhisner** [comment]
@Outpfmance, do you have any reason to think these sequences are from different patients? There's no metadata, but this sort of pattern is typical of repeated sequences from the same chronically infected patient. I would be very surprised if these sequences are from different individuals.

**Comment by krosa1910** [comment]
Well,I mentioned about this in my previous observation of the "swap mutation of L455F/F456L" as following:
"want to say something more about the nature of this weird "swap".
This is definitely not one of the very popular double mutation series. Rising only 105 times within the entire pandemic/over 15 million seqs. 30 of those are from this year out of half a million seqs.
However, only 16 of those are within the XBB family that seemed to dominate our world now. 11 are in family 1( some pre-486P XBB, https://github.com/cov-lineages/pango-designation/issues/1681 ) and 5 in this nomination.
What else got those? 1 BN.1.3.X, 1 BA.1, 1 BA.4.6, 3 BA.5.2.1, 1 BA.5.1, 4 BQ.1.1* and 2 AY, yes Delta. Many of those are variants that have long gone to grave.
What's shared between those non XBB variants that got this combo? All but one got L452R, hallmark Delta mutation。
And these Delta are probably the most modern Delta I have ever seen. The earlier one even got S:477N, classic BA.2 move.

@FedeGueli Would you like to comment more about how this could be related to cryptics?".
But I don't think this would ever spread, as it was only spotted few times, and also people working in wastewater monitoring did not see sign of this in the shed.
