### ISSUE TITLE
Another (?) XBB.1.5 with S:K1045R (42 seqs, mainly in Japan, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#553]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C > T10204C]` > `C20946T` > `C25836T, A28768G` > `A24696G(S:K1045R)`
**Query:** `A24696G, C25836T, A28768G`
**Earliest seq:** 2023-04-25 (`EPI_ISL_17880687`, Hyogo, Japan)
**Latest seq:** 2023-07-25 (`EPI_ISL_18060552`, Tokyo, Japan)
**Sampled Countries:** Japan (29), USA (2; California, New York), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17780114, EPI_ISL_17880687, EPI_ISL_17880718, EPI_ISL_17882965, EPI_ISL_17884050, EPI_ISL_17884058, EPI_ISL_17884076, EPI_ISL_17884106, EPI_ISL_17884108, EPI_ISL_17884113, EPI_ISL_17884119, EPI_ISL_17884149, EPI_ISL_17941090, EPI_ISL_17949815, EPI_ISL_17963190, EPI_ISL_17973279, EPI_ISL_17973294, EPI_ISL_17979899, EPI_ISL_17982042, EPI_ISL_17996463, EPI_ISL_18000419, EPI_ISL_18000461, EPI_ISL_18006540, EPI_ISL_18043229, EPI_ISL_18050890, EPI_ISL_18051348, EPI_ISL_18053885, EPI_ISL_18060552, EPI_ISL_18064902, EPI_ISL_18067240, EPI_ISL_18067279, EPI_ISL_18067303`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18056_e4ab20.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5a295a73-48b5-4ac0-b6ef-54ad8ab87c4a)

**Trivia:**
- Please check if this proposal and #543 belong to XBB.1.5.37 that potentially got misplaced.
- 2 airport screening seqs from _Ginkgo Bioworks_ (with travel history to Japan) possiblely cause split of branches due to Ns

```
CA-GBW-H20-322-4944/2023|EPI_ISL_17838436|2023-06-11
CA-GBW-H10-013-4482/2023|EPI_ISL_17985492|2023-07-03
```
![Ns](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/362f30a9-39a7-4366-81b6-ce378c087a77)

**Comment by FedeGueli** [comment]
cc @angiehinrichs

**Comment by AngieHinrichs** [comment]
Yep, unfortunately these got snagged on a different little branch (C25836T) in the 2023-08-17 tree so I will have to try again later.

**Comment by FedeGueli** [comment]
Too few recent samples closing it.
