### ISSUE TITLE
XBB.1.16 Sublineage with S:F186S, S:E554Q, S:N556K, ORF1a:P286S (11 seq, 2 continents, Sept 7)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#555]
### **Description**
**Sub-lineage of:** XBB.1.16
**Earliest sequence:** 2023-6-13, France, Grand Est, Colmar — EPI_ISL_17837367
**Most recent sequence:** 2023-7-24, France, Occitanie, Haute Garonne — EPI_ISL_18070166
**Countries circulating:** Japan (4), France (2)
**Number of Sequences:** 6
**GISAID AA Query:** Spike_E554Q, Spike_N556K
**GISAID Nucleotide Query:** C26894T, T5335C, A29110T, T22119C, G4504A
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16* & C23230A & [3-of: C1121T, G4504A, T5335C, T22119C, G23222C, C26894T, A29110T]
**Substitutions on top of XBB.1.16:**
**Spike:** F186S, E554Q, N556K
**ORF1a:** P286S
**Nucleotide:** C1121T, G4504A, T5335C, T22119C, G23222C, C23230A, C26894T, A29110T
 
 
**Phylogenetic Order of Mutations:** C26894T **→** T5335C, A29110T **→** T22119C (S:F186S) **→** C1121T, G23222C (ORF1a:P286S, S:E554Q) **→** G4504A, C23230A (S:N556K) **→**

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16_F186S_E554Q_N556K.json
 
<img width="1319" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6499a01d-17fc-450a-9b26-db95f774e2c7">

**Evidence**
This has appeared on opposite sides of the world in short succession. A different branch of XBB.1.16 with S:E554Q was also noticed just today by @NkRMnZr, in issue #554.

Something isn't entirely right with the Usher Tree since ORF1b:R2613C (C21304T) appears and is almost immediately reverted. Not a big deal, and if this lineage grows, the tree might sort itself out. 

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17837367, EPI_ISL_18056109, EPI_ISL_18056364, EPI_ISL_18056383, EPI_ISL_18056386, EPI_ISL_18070166
</details>

**Comment by FedeGueli** [comment]
> 
> Something isn't entirely right with the Usher Tree since ORF1b:R2613C (C21304T) appears and is almost immediately reverted. Not a big deal, and if this lineage grows, the tree might sort itself out.
> 

cc @angiehinrichs

**Comment by AngieHinrichs** [comment]
21304 stuff cleaned up in the 2023-08-17 tree (on dev.usher.bio now, on usher.bio in a bit over 4 hours), thanks @ryhisner and @FedeGueli.

**Comment by FedeGueli** [comment]
so now we have 7 :
![Schermata 2023-08-18 alle 14 38 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/71264ecb-77af-4652-86f9-a538257886f5)

![Schermata 2023-08-18 alle 14 37 47](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1a0d7f89-065a-4aab-ae09-3eb76d2ec557)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_407ca_f65960.json?label=id:node_6826265

**Comment by FedeGueli** [comment]
It seems slow @ryhisner closing for now.
