### ISSUE TITLE
FE.1.1 (XBB.1.18.1.1.1) with S:E554K (47 seqs, mainly in Brazil, 6 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#556]
**Defining Mutations:** `FE.1.1` > `G23222A(S:E554K), A23233G`
**Query:** `G23222A, A23233G, A8001G`
**Earliest seq:** 2023-04-09 (`EPI_ISL_18043094`, Aracaju, Sergipe, Brazil)
**Latest seq:** 2023-07-18 (`EPI_ISL_18054028`, Afonso Claudio, Espirito Santo, Brazil)
**Sampled Countries:** Brazil (16), Luxembourg (3), Mexico (2), France (1), USA (1, New Jersey)

<details><summary>Genomes: </summary>

`EPI_ISL_17710208, EPI_ISL_17734501-17734502, EPI_ISL_17771913, EPI_ISL_17792515, EPI_ISL_17813601, EPI_ISL_17814902, EPI_ISL_17832079, EPI_ISL_17960998, EPI_ISL_17961011, EPI_ISL_17975041, EPI_ISL_17975113, EPI_ISL_17990624, EPI_ISL_18022412, EPI_ISL_18043094, EPI_ISL_18054028, EPI_ISL_18058116, EPI_ISL_18058118-18058119, EPI_ISL_18058124, EPI_ISL_18058948, EPI_ISL_18067133, EPI_ISL_18069203`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_641a_e68a80.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2b1bde79-0ec0-4d0d-8470-802cac7f5562)

**Trivia:**
- Almost doubled in a week, but many of recent uploaded samples are not-so-recent, so hard to tell how fast it is.
- It now sits on a flip-flop _S:H505Y_reversion_ sub-branch of **FE.1** on UShER, it doesn't seems to be real though.
- `A23233G` is `S:K557` silent mutation

**Comment by FedeGueli** [comment]
Likely not fast but interesting to track 456 554 combo. even if XBB.1.18 is not the fastest backbone to be tested with

**Comment by FedeGueli** [comment]
HArd to tell if it sseems slow due sequencing intensity or whatever else. It is starting accumulating samples from abroad.

**Comment by FedeGueli** [comment]
For me this is slow. but apparently covspectrum dont see it as slow.

**Comment by FedeGueli** [comment]
Please propose it. not a lot of sequences but the fact it popped up in 3 different american states meand it should be quite prevalent in Brazil

**Comment by FedeGueli** [comment]
thank you
