### ISSUE TITLE
FE.1.2 with ORF1a:S2083I, ORF1b:A2143S, ORF1a:V228I, S:A93S and S:E484T (14 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#557]
**Defining Mutations:** `FE.1.2` > `G6513T(ORF1a:S2083I/nsp3_S1265I)` > `G19894T(ORF1b:A2143S/nsp15_A92S)` > `C7420T` > `G947A(ORF1a:V228I/nsp2_V48I), G21839T(S:A93S) > G23012A(S:E484T, over existing A23013C/S:E484A)`
**Query:** `G21839T,G23012A,G947A`
**Earliest seq:** 2023-06-05 (`EPI_ISL_17955881`, Houston, Texas, USA)
**Latest seq:** 2023-07-21 (`EPI_ISL_18057214`, Houston, Texas, USA)
**Sampled Countries:** USA (8, Texas)

<details><summary>Genomes: </summary>

`EPI_ISL_17955590, EPI_ISL_17955754, EPI_ISL_17955881, EPI_ISL_18057157, EPI_ISL_18057214, EPI_ISL_18057442, EPI_ISL_18057611, EPI_ISL_18057633`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d6b5_e6c0c0.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7c39ebc0-d7df-427f-bf1e-a31814ab9dcb)

**Trivia:**
- Recently `S:E484A>X` got an uptick, that's a worrying trend. 
- Should any of these `E484A>X` still be called _**GRA** clade_ by GISAID? I've got the question since **BA.2.3.20** emerged.
![484t](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/493c776d-6b73-455e-a498-2707b9a9af37)

**Comment by FedeGueli** [comment]
Thx . i dont know anything about gisaid clades . maybe @corneliusroemer could answer?

**Comment by FedeGueli** [comment]
![Schermata 2023-09-02 alle 23 57 32](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/26705b97-41f2-472a-b440-2be90db09d1c)
it seems not able to compete:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G21839T%2CG23012A%2CG947A&analysisMode=CompareToBaseline&

Lets track it for a while being a 484

**Comment by FedeGueli** [comment]
No new seqs closing it.
