### ISSUE TITLE
DV.7.1 with ORF1a:K3353R (>80 seq. Mainly Israel and Spain)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#559]
It seems that this DV.7.1 sublineage with a Beta-defining mutation ORF1a:K3353R has taken root in Israel.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ADV.7*%26%21S%3AL455L%26%21S%3AF456F%26ORF1a%3AK3353R&
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/3d8ca443-9ee3-4aba-a264-0f7db5246730)
![2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/022ed91e-9aa1-4ec2-b3bf-e3da898280bf)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39903_eb3cc0.json?c=gt-ORF1ab_3353&label=id:node_7476474

Nuc Query: A10323G,G22927T,G25606A finds 77 as September 1.

**Comment by FedeGueli** [comment]
sorry @oobb45729 i missed your updates of this one without the proper label. . Consider that Orf1a:K3353R is very homoplasic. I prefer to wait a bit to evaluate how it co ares with the other newcoming lineages. i saw @aviczhl2 found a new sublineage of it. We will monitor both together

**Comment by FedeGueli** [comment]
Thank you
