### ISSUE TITLE
Potential XBB.1.5 recombinant neighboring to XBW and XCD also gained S:T478I (25~30 seqs, mainly in Israel, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#560]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C > T10204C]` > `[C27382G_rev > T27383A_rev > C27384T_rev] / ORF6:L61D_reversion` > `G27382C/ins_27384C(ORF6:D61H)` > `C657T(ORF1a:A131V)` > `G6713T(ORF1a:V2150F)` > `C7488T(ORF1a:T2408I) > C22995T(S:T478I)`

**Query:** `G6713T, C7488T, C22995T`
**Earliest seq:** 2023-06-01 (`EPI_ISL_17803715`, Israel)
**Latest seq:** 2023-07-26 (`EPI_ISL_18062642`, Israel)
**Sampled Countries:** Israel (6)

<details><summary>Genomes: </summary>

`EPI_ISL_17803706, EPI_ISL_17803715, EPI_ISL_18012543, EPI_ISL_18050870, EPI_ISL_18062641-18062642`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_159f5_f62db0.json?f_userOrOld=uploaded%20sample

placement on UShER tree, neighboring to XBW and XCD
![israel](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/82f8bbad-0947-4d50-85f1-79dd12cd7829)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/de12f2a7-c5b8-4c82-89bc-e8ce4dd25cbc)

**Trivia:**
- Tracked this a bit since the discovery of _XCD_, it went silent for a while then popped up every week with 1 or 2 seqs recently.
- Not entirely sure if this is a recombinant, for it only partly drops `ORF6:D61L(G27382C, A27383T, T27384C)` introduced from **BA.2**, turns it into `ORF6:D61H(G27382C)` through a cytosine insersion at `nuc 27382`. And I have no idea what the other donor could be.
- There's also a neighbour `USA/FL-CDC-LC1045449/2023|EPI_ISL_17979086|2023-06-21` branching from `G6713T(ORF1a:V2150F)` follows `C27382G_rev(ORF6:H61D_rev)` > `C18828T, A19459G(ORF1b:I1998V), T22913C(S:Y451H)` > `T22304C(S:Y248H), C22995T(S:T478I), C26058T, C29510A_rev(N:R413S_rev)` that also got `S:T478I`, but that's only a singlet at the moment.

**Comment by FedeGueli** [comment]
@ryhisner @JosetteSchoenma @c19850727 could you take  a look please?

I am not sure it is a recombinant. If it is a R. it should have got just Orf6 from a BA.5 lineage

btw great catch @NkRMnZr

**Comment by FedeGueli** [comment]
cc @shay671 this is in Israel.

**Comment by ryhisner** [comment]
It seems really unlikely that 2/3 nucleotides in ORF6:61 would revert but not the third one. Also, Israel uploads a lot of low-quality sequences, and there's a ton of missing coverage in all these. I really don't think this is a recombinant.

**Comment by FedeGueli** [comment]
> After checking with potential gaps/insersions, the cause of `ORF6:D61H` could be a cytosine insersion at `nuc 27384` ![INS](https://user-images.githubusercontent.com/125747944/260299021-74eb3ac4-85fa-49c0-874a-e5391c6e937e.png) ![d61h](https://user-images.githubusercontent.com/125747944/260299028-db1bb3a0-e4b1-4ba2-ace1-4585d5a32b37.png)
>

cc @ryhisner 


thx @NkRMnZr

**Comment by ryhisner** [comment]
I don't think a cytosine insertion can explain D61H, regardless of whether you start with D61L or D61. An insertion of C at 27384 (which always means _after_ 27384) would get rid of the stop codon but wouldn't affect D61. In fact, any 1-nucleotide insertion here would destroy the stop codon. I think the ins27384C is just a misinterpretation by NextClade of what is likely a bad sequence. 
<img width="1483" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d5b490f6-5397-4592-9000-9565c5713365">

**Comment by FedeGueli** [comment]
> no new seqs for 2 weeks

Thx

**Comment by FedeGueli** [comment]
Thank you for still tracking it.

**Comment by FedeGueli** [comment]
It seems flateening its growth lets see

**Comment by FedeGueli** [comment]
Still circualting at low levels in Israel wondering if it is not from some neighbouring country

**Comment by FedeGueli** [comment]
label here more a question than a definition.

**Comment by FedeGueli** [comment]
Still very little spread closing it for now
