### ISSUE TITLE
EG.13 (ORF1a:K798N = NSP2_K618N) plus S:T478R, followed by S:A647S, ORF3a:G44R, ORF3a: V256I (16 seqs, UK)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#561]
**Defining Mutations:** `EG.13 (XBB.1.9.2 + ORF1a:K798N) > `C22995G(S:T478R)` > `C13551A, G23501T(S:A647S), G25522A(ORF3a:G44R), G26158A(ORF3a: V256I), G27420T`
**Query:** `C22995G, G23501T, G25522A`
**Earliest seq:** 2023-06-05 (`EPI_ISL_17813136`, England, UK)
**Latest seq:** 2023-07-19 (`EPI_ISL_18066805`, England, UK)
**Sampled Countries:** UK (12, England)

<details><summary>Genomes: </summary>

`EPI_ISL_17813136, EPI_ISL_18015605, EPI_ISL_18015615, EPI_ISL_18015621, EPI_ISL_18052532, EPI_ISL_18052541, EPI_ISL_18052618-18052619, EPI_ISL_18066802, EPI_ISL_18066805, EPI_ISL_18066808, EPI_ISL_18066811`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ae50_e8f1a0.json?f_userOrOld=uploaded%20sample

view from `G2659T/ORF1a:K798N` branch
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/83c20acc-d5a3-4a67-9c56-72ab1af0513f)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/27351474-9193-418b-83ed-732c3745316e)

**Trivia:**
- `XBB.1.9.2`'s `G2659T(ORF1a:K798N)` branch first noticed by @FedeGueli from cov-lineages/pango-designation#1708 , suprisingly not designated since yet grew to a large cluster with at least 1k seqs (Query: `G2659T, A16878T, A27507C`).

<details><summary>A view of G2659T/ORF1a:K798N branch filtered by seqs collected from June 1st, excluding seqs from this proposal</summary>

![G2659T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ebdd6f6e-0e73-46c1-b730-5058486b2ef5)
</details>

- `S:A647S` only sampled about 6.7k times during the whole pandemic, is predected to be somewhat beneficial on XBB.1.5 backbone
![647](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f830acac-5de3-4de8-9f45-5b63b316f74a)

- Most of the sequences at the moment falls under further `G4357A, C12974T, C24809T(S:H1083Y), C25572T` sub-branch, maybe it should be proposed up till there?

**Comment by FedeGueli** [comment]
I think youn proposed it from the right starting point reprsenting the spread in Uk and an apparent boost.

Very ood catch it seems fast.

**Comment by FedeGueli** [comment]
A lot of samples in the uk database are duplicated on Usher , i hope it will become cleare then  : https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3824_8ff8e0.json?label=id:node_6784856

**Comment by Over-There-Is** [comment]
Parental branch is designated as EG.13 now.

**Comment by FedeGueli** [comment]
> Parental branch is designated as EG.13 now.

Thank you corrected the title now

**Comment by FedeGueli** [comment]
Tracker: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C22995G%2CG23501T%2CG25522A&analysisMode=CompareToBaseline&

To me it is slower than observed lets see how it goes.

**Comment by FedeGueli** [comment]
Closing this for now
