### ISSUE TITLE
EG.5.1.1 + S:R190K (31seqs Uk / Ireland)

### ISSUE THREAD

**Issue by olias120676** [sars-cov-2-variants/lineage-proposals#564]
Earliest sequence is July 11th, the others are all from the past 2 weeks. Looks like it might be a circulating sublineage rather than the usual sequencing clusters I see in the UK, worth keeping an eye out for it popping up elsewhere.

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_33221_e3e00.json?c=userOrOld&label=id:node_6774376

![Screenshot 2023-08-07 140108](https://github.com/sars-cov-2-variants/lineage-proposals/assets/24962257/4b88ea13-046f-44c9-bf3a-914e00027181)

GISAID query: C6541T,G13627A,G22131A

**Comment by FedeGueli** [comment]
Welcome here @olias120676 !

**Comment by HynnSpylor** [comment]
it reaches 31. It can be proposed to main page if reaches 50 or emerges outside England.

**Comment by FedeGueli** [comment]
Pls @olias120676 propose it.
