### ISSUE TITLE
Dave McNally: FL.1.5.1 lineage with S:T618I emerging in Uk (12seqs) 3 countries- US,Uk, Chn

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#567]
Full credit to @olias120676 and his tool : https://ukcovid.xyz/spike-combo.php?type=multi&mincount=2
tracking spike mutations in Uk sequences.

Defining mutations:
FL.1.5.1 > Orf1a:R287S (G1126T), Orf1A: A2248T (G7007A),Orf1B:H1087Y (C16726T), S:T618I (C23415T), C24418T

Gisaid query: G1126T, G7007A, C16726T

Samples : Only **ONE** on Gisaid 
hCoV-19/Shanghai/SCDC-XG06-9865/2023 **EPI_ISL_17987790**)
England/CLIMB-CM7YRIFF/2023\|2023-07-28
England/CLIMB-CM7YKIKZ/2023\|2023-07-26
England/CLIMB-CM7Y884Y/2023\|2023-07-31
England/CLIMB-CM7YJOTJ/2023\|2023-07-31

Tree: (by @olias120676)
![Schermata 2023-08-08 alle 01 04 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0ee1f343-b440-49b1-b4e9-5d94f6407c60)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3772d_10ac90.json?c=gt-S_618&label=id:node_6806320

**Comment by FedeGueli** [comment]
+1 EPI_ISL_18074476 from Shanghai

**Comment by aviczhl2** [comment]
10 seqs now. 4 CLIMB seqs not on GISAID. 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/59963797-cb1b-4f75-9366-5c27f1d9c534)

**Comment by FedeGueli** [comment]
8 now on Gisaid
