### ISSUE TITLE
XBB.1.9.2 plus S:R403K and S:A344T (25 seqs as 20/07/2023)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#57]
Another xbb.1.9.2 sublineage carrying S:R403K popped up recently. It counts now 5 seqs in three countries:

Tree:
![Schermata 2023-05-14 alle 11 02 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ad6c6bbd-1bae-4d5d-ae30-7b09c7ce900d)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_4065_81c20.json?label=id:node_6731876

Defining mutations:
XBB.1.9.2:  C29347T >**Orf1a:T1474I**  (C4686T) >  C13767T, **Orf1b:N969S** (A16373G), **S:A344T** (G22592A), **S:R403K** (G22770A)

Gisaid query:  A16373G,G22770A,C13767T, G22592A  finds 4 : 
EPI_ISL_17621123, EPI_ISL_17621413, EPI_ISL_17637838,
EPI_ISL_17640614

**Comment by FedeGueli** [comment]
One more added from Kansas

**Comment by FedeGueli** [comment]
The new sequence came from England has S:A344V 
![Schermata 2023-05-26 alle 23 31 54](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fd41e43b-b726-4e00-a805-33b41652e81e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_26c4_11ec70.json?c=userOrOld&label=id:node_10192008

**Comment by FedeGueli** [comment]
It seems too slow to be worth  tracking it

**Comment by Sinickle** [comment]
New sequence came up with R357i
EPI_ISL_17742312
Scotland, collected 5/11.

**Comment by Sinickle** [comment]
Spain and England have each had a sequence with S494P (5/30, 5/28)

**Comment by FedeGueli** [comment]
I reopen this one. the tree is interesting likely not that fast but better monitor for a while again:
![Schermata 2023-06-16 alle 13 21 09](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b2c3e962-7690-48d1-91d3-d10fb3d24abf)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice13_genome_test_160cc_c40750.json?label=id:node_10289736

Thx @Sinickle !

**Comment by FedeGueli** [comment]
really to slow to keep this open.

**Comment by HynnSpylor** [comment]
Today the sibling lineage (S:A344V branch) updates 5 seqs (total 10)
I’d like to propose a new issue

**Comment by FedeGueli** [comment]
> Today the sibling lineage (S:A344V branch) updates 5 seqs (total 10) I’d like to propose a new issue

Yes please.

**Comment by FedeGueli** [comment]
@corneliusroemer this reached 25 in the new great! tree  by @angiehinrinchs new query : A16373G,G22770A,C13767T, G22592A
