### ISSUE TITLE
FL.20.2 (S:Q52H,S:F456L, S:T478R with  S:L452M (20 seqs, Canada and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#571]
**Phylogenetic Order**: FL.20.2 >  C22916A(**S:L452M**)

**Query**: `C1912T, T19755C, C22916A`

**Samples:** 17

<details><summary>Genomes: </summary>

` EPI_ISL_18113760, EPI_ISL_18143431, EPI_ISL_18264251,
EPI_ISL_18276516, EPI_ISL_18341484, EPI_ISL_18351809,
EPI_ISL_18374961, EPI_ISL_18423631, EPI_ISL_18423808,
EPI_ISL_18424227, EPI_ISL_18431706, EPI_ISL_18431711,
EPI_ISL_18437053-18437054, EPI_ISL_18452509, EPI_ISL_18452512,
EPI_ISL_18453451`</details>

<details><summary>UShER: </summary>

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice62_genome_d661_392d90.json?label=id:node_3358083
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3ba25a0e-f291-44a8-9d3a-5b35a7cb581d)

</details>

************************
**Original proposal that led to FL.20.2 designation:** 
**Defining Mutations:** _FL.20_ > `T19755C` > `C22995G`(**S:T478R**)
**Query:** `T19755C, C22995G, C25714T`
**Earliest seq:** 2023-06-27 (EPI_ISL_18043018, Puerto Rico)
**Latest seq:** 2023-07-22 (EPI_ISL_18057005, New York, travel history to: UK)
**Sampled Countries:** USA (4)

<details><summary>Genomes: </summary>

`EPI_ISL_18037722, EPI_ISL_18043018, EPI_ISL_18054080, EPI_ISL_18057005`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2173a_18ac70.json?f_userOrOld=uploaded%20sample
![FL20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2e37ecbc-0268-4c17-bf76-48363154eb6b)

**Trivia:**
- `FL.20`, an `EG.5.1` _impersonator_ on `XBB.1.9.1` backbone, not only gained `S:L455W` (designated as `FL.20.1`), also picking up `S:T478R`.

**Comment by FedeGueli** [comment]
NY NJ and Switzerland the last samples. Last doubling was quite fast lets see how does it take to reach 25.

**Comment by FedeGueli** [comment]
Please propose it although FL.20 is not fast ad its cousin impersonator EG.5.1

**Comment by FedeGueli** [comment]
> T19755C, C22916A, C22995G, C25714T

Please propose in a separate issue

**Comment by FedeGueli** [comment]
or resume this one changing it into FL.20.2 +452M

**Comment by FedeGueli** [comment]
+2 US

**Comment by FedeGueli** [comment]
20 one only sample from November closing it for now.
