### ISSUE TITLE
XBB.1.5.28 (478R) with ORF3a:F79S, ORF1a:L198I (nsp2_L18I) and S:F456L (6 seqs, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#572]
**Defining Mutations:** `XBB.1.5.28` > `T25628C(ORF3a:F79S)` > `C857A(ORF1a:L198I)` > `T22928C(S:F456L)`
**Query:** `C857A, T22928C, T25628C`
**Earliest seq:** 2023-07-22 (`EPI_ISL_18056974`, Virginia, travel history: Spain)
**Latest seq:** 2023-07-28 (`EPI_ISL_18072798`, Madrid, Spain)
**Sampled Countries:** USA (2), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18056964, EPI_ISL_18056974, EPI_ISL_18072798`

</details>

<details><summary>non-GISAID Genomes: </summary>

`England/CLIMB-CM7YK4F8/2023|2023-07-24`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2760_19ca80.json?c=gt-S_456&f_userOrOld=uploaded%20sample
![456](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8c7a3e28-3417-454a-95b7-9eaf761e2655)

**Comment by FedeGueli** [comment]
Good catch it is a 456-478 combo as FL.1.5.1

**Comment by FedeGueli** [comment]
5th sequence of the 456L branch from England.

**Comment by FedeGueli** [comment]
closing this for now.
