### ISSUE TITLE
FE.1.1.3 saltation with S:L455F, S:L513I and ORF1a:L1182R (2 seqs in Shanghai, China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#573]
Defining mutations:
FE.1.1.3>T3810G (ORF1a:L1182R), G22927T (S:L455F), C23099A (S:L513I) 
GISAID query: A24775G, G22927T, T3810G
Earliest seq: 2023-07-20 (Shanghai Municipality, China- EPI_ISL_18074819)
Most recent seq: 2023-07-23 (Shanghai Municipality, China- EPI_ISL_18074389)
Countries detected: China (2) 

Usher Tree:
<img width="715" alt="屏幕截图 2023-08-08 190104" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/92a22dfa-8068-41e2-ba36-d87363d8964b">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_183e5_201520.json?c=gt-S_455,513&label=id:node_6855775

S:L455F+S:F456L "Exchange" Combo has been more popular recently. Now the FE.1.1.3 sublineage (already got S:F456L) also shows the mutations, with another RBD mutation S:L513I (which is very rare).

Genomes:
EPI_ISL_18074389, EPI_ISL_18074819

**Comment by HynnSpylor** [comment]
65 seqs now

**Comment by FedeGueli** [comment]
No more samples closing it for now.
