### ISSUE TITLE
EG.5.1.1+S:P1263L (21+4+1*9)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#576]
EG.5.1.1+C25350T(S:P1263L)

GISAID query: C25350T,C6541T,T23018C,-16242(edited)
No. of seqs: 6(China 4 Israel 1 Singapore 1)

First:EPI_ISL_18036357, Guangdong, 2023-6-6
Latest: EPI_ISL_18050851, Israel, 2023-7-19

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d416_260150.json?branchLabel=Spike%20mutations&label=id:node_6776259&showBranchLabels=all)

usher places it with S:Y144F/ A21993T branch, however the seqs don't have this mutation. XBB* shall have S:Y144del/del21992_21994. Seems to be a new bug of usher. 
@AngieHinrichs

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2264843d-65ee-4e12-8d42-75b4f34f28cd)

**Comment by FedeGueli** [comment]
cc @angiehincrichs pls could u help?

**Comment by aviczhl2** [comment]
+1 South Korea

**Comment by aviczhl2** [comment]
16, Japan

**Comment by FedeGueli** [comment]
It doesnt seem especially fast https://cov-spectrum.org/explore/Asia/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C25350T%2CC6541T%2CT23018C&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
24, Canada

**Comment by aviczhl2** [comment]
27, USA

**Comment by FedeGueli** [comment]
Still far feom leaders : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C25350T%2CC6541T%2CT23018C&analysisMode=CompareToBaseline&

**Comment by AngieHinrichs** [comment]
> XBB* shall have S:Y144del/del21992_21994.

Good point, thanks. Also, the deletion can also be mapped to 21991-21993 depending on the alignment tool.  Bases 21994 and 21995 are already masked in XBB due to past problems mentioned in issues #1882, #1503, #1999, and #1918.  I will mask bases 21991-21993 in XBB and that should take care of this as of the 2023-10-03 tree.

**Comment by aviczhl2** [comment]
Like other EG.5.1.1 branches, this one diverges now. 

Branch 1: Proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/934, 28 seqs

Branch 2: main branch, 21 seqs

Branch 3: EG.5.1.1+Orf1a:G2509D,Orf1a:D935N, Orf3a:S26L, S:P1263L   C25350T,C6541T,T23018C,G7791A, 4 seqs

And 9 singlets.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2f36b_36cff0.json?f_userOrOld=uploaded%20sample&label=id:node_3430540)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9b084667-941d-48d9-b516-e7806ebaa659)

**Comment by FedeGueli** [comment]
> Like other EG.5.1.1 branches with convergent S, this one diverges now after the fix of S:144 by @AngieHinrichs
> 
> Branch 1: Proposed in #934, 28 seqs
> 
> Branch 2: main branch, 21 seqs
> 
> Branch 3: EG.5.1.1+Orf1a:G2509D,Orf1a:D935N, Orf3a:S26L, S:P1263L C25350T,C6541T,T23018C,G7791A, 4 seqs
> 
> And 9 singlets, one is under HK.3, the other 8 are under undesignated EG.5.1.1 branches.
> 
> [usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2f36b_36cff0.json?f_userOrOld=uploaded%20sample&label=id:node_3430540) ![image](https://user-images.githubusercontent.com/10445944/273492069-9b084667-941d-48d9-b516-e7806ebaa659.png)
> 
> Given there are already 20000+ samples under EG.5.1.1 with vast large undesignated branches, any mutation with some levels of convergence may become messsy. (already seen in S:455, S:1162 and S:14)
> 
> Suggest to start making systemic designation for EG.5.1.1 to make things clearer. @corneliusroemer

Sincerely at this point i will wait for HK.3 to become dominant and then designate just if something remains alive. the advantage of HK.3like is huge and very few things compete with them mostly very similar to it plus a dozen more of different spike combinations. I think in November we will have a complete different scenario.

**Comment by aviczhl2** [comment]
Total=39 now

**Comment by FedeGueli** [comment]
Closing for now too far: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C25350T%2CC6541T%2CT23018C%2C16242T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Branch 3 parental lineage designated HK.29
