### ISSUE TITLE
Another FL.15+Orf1a:G400V+S:Q14H (21 seqs, 2 countries, 2 with S:L455F)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#578]
FL.15+G1464T(Orf1a:G400V)+C12890T+C29236T,C1684T,C11747T,G21604T(S:Q14H)

GISAID query: C29236T,C1684T,C11747T
No. of seqs: 6(China(Xinjiang, Yunnan, Shanghai, Liaoning,Gansu))
First: EPI_ISL_17836269. Xinjiang, 2023-5-25
Latest: EPI_ISL_18060799,Shanghai, 2023-7-21

This one is a little different from #547
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice28_genome_3d416_2601d0.json?label=id:node_6755576)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/96c6d7e6-99fd-48b4-a2bf-00f58e4da925)

EDITED:
QUery for the FLip sublineage : C29236T,C1684T,C11747T,G22927T,
Samples 2 
ID: EPI_ISL_18133811, EPI_ISL_18138215

**Comment by aviczhl2** [comment]
Also in today's Hubei batch

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
2 of the seqs also have S:L455F

**Comment by FedeGueli** [comment]
Please propose it once it reaches 20 as parental lineage or 5 as FLip lineage.

**Comment by FedeGueli** [comment]
Designated FL.15.2 via https://github.com/cov-lineages/pango-designation/commit/81a254acab70b66c7a4f7c24f840f226aeef3ec2#commitcomment-128527167
