### ISSUE TITLE
very new HK.3 (EG.5.1.1.3) sublineage with S:F157L, S:Q146K (?) and ORF1a:T4129I (13 seqs in Hubei Province, China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#580]
Defining mutations:
HK.3>C12651T (ORF1a:T4129I),  C21998A (S:Q146K? it should be treated cautionlly),  C22033A (S:F157L)
GISAID query: G5720A, C12651T, C22033A
Earliest seq: 2023-07-31 (Hubei Province, China- EPI_ISL_18078259)
Most recent seq: 2023-08-03 (Hubei Province, China- EPI_ISL_18078269)
Countries detected: China (7)

Usher Tree:
<img width="902" alt="屏幕截图 2023-08-09 200616" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/603d2d49-a007-4af6-8f27-f3208779926e">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31305_37fe00.json

Another branch with S:F157L (which has emerged in EG.5.1.6 lineages). HK.3 is one of lineages with L455F-F456L "exchange" Combo mutations, and this branch (with S:F157L) popped up very recently (in last 10 days). Rapid view may be needed.

Genomes:
EPI_ISL_18078259, EPI_ISL_18078261-18078262, EPI_ISL_18078265-18078266, EPI_ISL_18078268-18078269

**Comment by Mydtlwn** [comment]
I would like to add an "EG.5.1" Lable.

**Comment by Mydtlwn** [comment]
Label

**Comment by FedeGueli** [comment]
Propose it directly.thx for spotting. HK.3 with a doubling close to 10 days seems the fastest around with at least  not local only spread.

**Comment by HynnSpylor** [comment]
6 more seqs from Hubei Province, China
I'll propose it in main page

**Comment by FedeGueli** [comment]
Designated HK.3.1 via https://github.com/cov-lineages/pango-designation/commit/2d2cdd668e05e9ae1a6ca247d1e9833f1155e24e
