### ISSUE TITLE
FL.15 with ORF1a:G400V (nsp2_G220V), ORF1b:A1895V (nsp14_A371V) and S:A344S (25 seqs, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#581]
**Defining Mutations:** `FL.15` > `G1464T(ORF1a:G400V)` > `C12890T` > `C7735T` > `C19151T(ORF1b:A1895V)` > `G22592T(S:A344S)`
**Query:** `C7735T, C19151T, G22592T`
**Earliest seq:** 2023-07-24 (`EPI_ISL_18055384`, Ontario, Canada)
**Latest seq:** 2023-07-28 (`EPI_ISL_18076492`, Ontario, Canada)
**Sampled Countries:** 24 (Canada)

<details><summary>Genomes: </summary>

`EPI_ISL_18055363-18055364, EPI_ISL_18055370-18055371, EPI_ISL_18055384-18055385, EPI_ISL_18055387-18055391, EPI_ISL_18055394, EPI_ISL_18055410, EPI_ISL_18076405-18076408, EPI_ISL_18076410, EPI_ISL_18076437, EPI_ISL_18076459, EPI_ISL_18076474, EPI_ISL_18076492, EPI_ISL_18076494, EPI_ISL_18076496`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ec91_39a9a0.json?f_userOrOld=uploaded%20sample
![diver](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/dfbe4251-7b67-42db-8b76-3a99b2778aeb)

**Trivia:**
- Doubling in a week, but they are all from Ontario, Canada, either a super-spreader event, or targeted sample?
- No possibly `A344X` correlated `R403K` seen in **EG.9.1** or **EG.10**, yet. And `A344S` expected to be slightly beneficial to `A344T` in terms of fitness, binding affinity and expression by tiny little bit.

**Comment by FedeGueli** [comment]
It is likely the usual canadian cluster thing.

**Comment by alex-m-a** [comment]
I can confirm that this is a known cluster within a healthcare facility.

**Comment by FedeGueli** [comment]
> I can confirm that this is a known cluster within a healthcare facility.

Thank you very much. closing it . Please let us know if you see it start spreading in the pop.
