### ISSUE TITLE
XBB.1.5.16 with ORF1a:T592I, ORF1a:V2203I, ORF1a:I2229V and S:F456L (35 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#582]
**Defining Mutations:** `XBB.1.5.16` > `C2040T(ORF1a:T592I/nsp2_T412I)` > `G6872A(ORF1a:V2203I/nsp3_V1385I)`, `A6950G(ORF1a:I2229V/nsp3_I1411V)` > `T16548C, T22928C(S:F456L)`
**Query:** `C2040T, T16548C, T22928C`
**Earliest seq:** 2023-04-02 (`EPI_ISL_17523596`, Houston, Texas, USA)
**Latest seq:** 2023-07-23 (`EPI_ISL_18075248`, Albany, New York, USA)
**Sampled Countries:** USA (29; New York/8 with ex. France; Michigan/5; California/3, with ex. Japan; Texas/3; Arizona/2; Ohio/2; Delaware/1; Illinois/1; Maryland/1; Minnesota/1; New Jersey/1; Nevada/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17523596, EPI_ISL_17685734, EPI_ISL_17690278, EPI_ISL_17700408, EPI_ISL_17716703, EPI_ISL_17763587, EPI_ISL_17768613, EPI_ISL_17768659, EPI_ISL_17768662, EPI_ISL_17815204, EPI_ISL_17815208-17815209, EPI_ISL_17839195, EPI_ISL_17853380, EPI_ISL_17950920, EPI_ISL_17950986, EPI_ISL_17976617, EPI_ISL_17976899, EPI_ISL_17979155, EPI_ISL_17986707, EPI_ISL_17998588, EPI_ISL_18039614, EPI_ISL_18054076, EPI_ISL_18054660, EPI_ISL_18064438, EPI_ISL_18071304, EPI_ISL_18075248, EPI_ISL_18075274, EPI_ISL_18075276`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36d2f_3b1dd0.json?f_userOrOld=uploaded%20sample&label=id:node_7149808
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4bf5c99b-8f43-4984-9716-e0209389a64f)

**Comment by FedeGueli** [comment]
Cant compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C2040T%2CT16548C%2CT22928C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
One more from Texas

**Comment by FedeGueli** [comment]
Very few sequences in august i m closing it now.
