### ISSUE TITLE
XBB.1.5 with ORF1a:P2046L (nsp3_P1228L) and S:F456L (53 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#583]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C > T10204C]` > `C26753T` > `C1555T, C6402T(ORF1a:P2046L), T22930A(S:F456L)`
**Query:** `C1555T, C6402T, T22930A`
**Earliest seq:** 2023-02-16 (`EPI_ISL_17161699`, California, USA)
**Latest seq:** 2023-07-30 (`EPI_ISL_18073915`, Oregon, USA)
**Sampled Countries:** USA (44; California/37; New Mexico/2; New York/2; Oregon/2; Arizona/1), China (1, Shanghai, Ex. USA)

<details><summary>Genomes: </summary>

`EPI_ISL_17161699, EPI_ISL_17225939, EPI_ISL_17321249, EPI_ISL_17333535, EPI_ISL_17384364, EPI_ISL_17525875, EPI_ISL_17535089, EPI_ISL_17546554, EPI_ISL_17546559, EPI_ISL_17582170, EPI_ISL_17619210, EPI_ISL_17642805, EPI_ISL_17642904, EPI_ISL_17643502, EPI_ISL_17688916, EPI_ISL_17688963, EPI_ISL_17706098, EPI_ISL_17733361, EPI_ISL_17831709, EPI_ISL_17853527, EPI_ISL_17854992, EPI_ISL_17860866, EPI_ISL_17860987, EPI_ISL_17861079, EPI_ISL_17861307, EPI_ISL_17862237, EPI_ISL_17862389, EPI_ISL_17862626, EPI_ISL_17971885, EPI_ISL_17971932, EPI_ISL_17987454, EPI_ISL_17997653, EPI_ISL_17997680, EPI_ISL_17997684, EPI_ISL_17997873, EPI_ISL_17998609, EPI_ISL_18008913, EPI_ISL_18050249, EPI_ISL_18073907, EPI_ISL_18073915, EPI_ISL_18079473, EPI_ISL_18079475-18079476, EPI_ISL_18079544, EPI_ISL_18079965`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18870_3bf640.json?f_userOrOld=uploaded%20sample&label=id:node_6915398
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/24102cf3-24a7-41e2-8f77-e2eb1f7d918a)

**Comment by FedeGueli** [comment]
cant compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C1555T%2CC6402T%2CT22930A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@NkRMnZr no new mutation adding to the defining ones right?

**Comment by FedeGueli** [comment]
Still only 5 samples from July. still worth monitoring until the end of the month to look if could resist to the impact of fast variants coming

**Comment by FedeGueli** [comment]
-26%
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C1555T%2CC6402T%2CT22930A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
closing this one.
