### ISSUE TITLE
EG.5.1.1+Orf1a:Q991R, S:A262T in Israel (106 seqs, 12 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#588]
EG.5.1.1+C11779T+A3237G(Orf1a:Q991R),G22346A(S:A262T)

GISAID query: C11779T,A3237G,G22346A,C6541T
No. of seqs: 11(Israel)

First: EPI_ISL_17953564, 2023-6-25
Latest: EPI_ISL_18050836, 2023-7-21

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_5077_51e870.json?label=id:node_6788170)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/659386dc-23b4-4437-a725-0eacceb7e903)

**Comment by aviczhl2** [comment]
+3 USA, 1 Germany

**Comment by aviczhl2** [comment]
25, Spain

**Comment by aviczhl2** [comment]
35, Luxemburg

**Comment by aviczhl2** [comment]
52,Netherlands

**Comment by FedeGueli** [comment]
Still far from FLip : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C11779T%2CA3237G%2CG22346A%2CC6541T&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
76, Greece, Ireland,UK

**Comment by FedeGueli** [comment]
Adding a tracker:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C11779T%2CA3237G%2CG22346A%2CC6541T&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
95, Slovenia, Singapore,

**Comment by aviczhl2** [comment]
106, Belgium

**Comment by aviczhl2** [comment]
Designated HK.15 @FedeGueli

**Comment by FedeGueli** [comment]
Designated HK.15 via https://github.com/cov-lineages/pango-designation/commit/04f540f9fba134e7b2985e3d94f4ef2b1caf268d
