### ISSUE TITLE
EG.5.1.6 sublineage with S:N211I (73 seqs in 7 countries, mostly in Ireland)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#589]
Defining mutations:
EG.5.1.6>C1684T, A22194T (S:N211I)
GISAID query: C1684T, C5835T, A22194T, C22033A
Earliest seq: 2023-07-13 (Ireland- EPI_ISL_18033615)
Most recent seq: 2023-08-02 (Ireland- EPI_ISL_18092164)
Countries detected: Ireland (11), US (1), UK (1, detected from US International Airport), Spain (1), China (1)

Usher Tree:
<img width="717" alt="屏幕截图 2023-08-11 114918" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7c43f69f-e1cf-493a-a3e4-212aa660a03b">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ee4d_5adb70.json?c=gt-S_211

EG.5.1.6 (with S:F157L) is one of rapidly increasing lineages. Now the branch with S:N211I has shown international transmission, and a rapid view may be needed.

I'll propose it in main page when it reaches 20.

Genomes:
EPI_ISL_18033615, EPI_ISL_18056978, EPI_ISL_18056987, EPI_ISL_18060774, EPI_ISL_18072782, EPI_ISL_18092133,
EPI_ISL_18092139-18092140, EPI_ISL_18092143, EPI_ISL_18092145-18092146, EPI_ISL_18092153, EPI_ISL_18092162, EPI_ISL_18092164-18092165,

**Comment by FedeGueli** [comment]
Great catch Hynn, EG.5.1.6 seems to be a great backbone  .
Interestingly one branch of it got orf1a:Q556R similar to the K defining of BA.5.3.1/BE.1/BQ family

**Comment by HynnSpylor** [comment]
2 more seqs from Spain

**Comment by HynnSpylor** [comment]
3 more seqs from Ireland

**Comment by FedeGueli** [comment]
20 please go!

**Comment by FedeGueli** [comment]
It slowed a lot. lets keep it here for now.
