### ISSUE TITLE
Multiple lineages with S:N481K  (updated 09/07)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#59]
```[tasklist]
### Multiple Lineages with S:N481K
- [x] Branch 1: FL.1 > G25186T(S:Q1208H) > T23005A(S:N481K), Designated as FL.1.6
- [ ] Branch 2: FL.1.4 > T23005A(S:N481K) [G25186T, T23005A, C23664T, C22995G, 7 seqs]
- [ ] Branch 3: FL.1.1 > T23005A(S:N481K) [A21371C, T23005A, C23664T, C11956T, 14 seqs]
- [ ] Branch 4: FL.11 > T23005A(S:N481K) [23005A, C9073T, T28297C, 27 seqs]
- [ ] Branch 5: XBB.1.9.1 > C539T(ORF1a:L92F) > C10977T(ORF1a:A3571V), T23005G(S:N481K) [C10977T, T23005G, 25 seqs]
- [ ] Branch 6: XBB.1.5.30 > T27614C(ORF7a:V74A) > C24358A > C17010T, G25437T(ORF3a:L15F) > T23005A(S:N481K) [T27614C, T23005A, 43 seqs]
```

see https://github.com/sars-cov-2-variants/lineage-proposals/issues/59#issuecomment-1577848491 for tracking details, thanks to @FedeGueli 

---

### Branch 1: FL.1 + S:Q1208H + S:N481K

<details><summary>Designated as FL.1.6 </summary>

**Defining Mutations:** FL.1 >> G25186T(S:Q1208H) >>T23005A(S:N481K)
**Query:** G25186T, T23005A, C23664T, -C22995G [10 seqs]
**Earliest seq:** 2023-04-03 (Brunei, EPI_ISL_17503927)
**Most recent seq:** 2023-05-03 (Shanghai, EPI_ISL_17645760)
**Countries detected:** South Korea (3), USA (2), Brunei (1), China (1)
**Genome:** EPI_ISL_17503927, EPI_ISL_17645760(C_AA014208.1), EPI_ISL_17537890, EPI_ISL_17677732, EPI_ISL_17677733, EPI_ISL_17690534, EPI_ISL_17706795

![FL 1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/61b011a5-3def-4d92-8251-296fbb595c9b)

</details>

### Branch 2: FL.1.4 > S:N481K

There is another subtree that also got T23005A(S:N481K) under C22995G(S:T478R) sub-branch, which is proposed by @HynnSpylor at  https://github.com/cov-lineages/pango-designation/issues/1985 (which is designated FL.1.4 on 23-05-24)

**Query:** G25186T, T23005A, C23664T, C22995G [5 Seqs]
**Countries detected:** Vietnam (1), USA (2), Singapore (1), Canada (1)
**Genome:** EPI_ISL_17595484, EPI_ISL_17614077, EPI_ISL_17595399, EPI_ISL_17670170, EPI_ISL_17701244

---

### Branch 3: FL.1.1 + S:N481K

**Defining Mutations:** FL.1.1 [A21371C(ORF1b:Q2635P)]>T23005A(S:N481K)
**Query:** A21371C, T23005A, C23664T, C11956T [11 Seqs]
**Earliest seq:** 2023-03-22 (EPI_ISL_17588026, USA)
**Most recent seq:** 2023-05-23 (EPI_ISL_17776857, Scotland)
**Countries detected:** USA (7), UK (4, Scotland)
**Genome:** EPI_ISL_17524181(OQ852226.1), EPI_ISL_17462785(OQ802638.1), EPI_ISL_17588012(OQ909937.1), EPI_ISL_17588026(OQ909952.1), EPI_ISL_17462476(OQ802329.1), EPI_ISL_17589492(OQ893714.1), EPI_ISL_17680758, EPI_ISL_17776849, EPI_ISL_17776854, EPI_ISL_17776856, EPI_ISL_17776857

![FL 1 1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6ed1a644-705e-4b34-a3d3-447dfbd638b7)

---

all branches above on downsample UShER Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_411d5_200740.json?c=gt-S_481
![Subtree](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/910b6937-894a-423c-8f57-307ee3402941)

---

### Branch 4: FL.11 + S:N481K
spotted by @FedeGueli 

**Defining Mutations:** FL.11 > T23005A(S:N481K)
**Query:** 23005A, C9073T, T28297C [20 seqs]
**Earliest seq:** 2023-04-13 (EPI_ISL_17537280, Canada)
**Most recent seq:** 2023-05-15
**Sampled Countries:** Canada (8, All Ontario), USA (5, All New York), Austria (3), France (3), Denmark (1)
<details><summary>Genomes: </summary>
EPI_ISL_17537280, EPI_ISL_17537702, EPI_ISL_17566036, EPI_ISL_17630242, EPI_ISL_17639076, EPI_ISL_17677166, EPI_ISL_17689470, EPI_ISL_17689471, EPI_ISL_17689503, EPI_ISL_17701158, EPI_ISL_17701160, EPI_ISL_17701234, EPI_ISL_17701329, EPI_ISL_17701330, EPI_ISL_17715278, EPI_ISL_17715542, EPI_ISL_17717554, EPI_ISL_17732179, EPI_ISL_17761749, 

USA/NY-PRL-230518_81A07/2023|OR026434.1|2023-05-15
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice27_genome_3238d_d9c830.json?label=id:node_6696050 ![Schermata 2023-06-05 alle 12 06 27](https://user-images.githubusercontent.com/87669813/243321743-bf352560-43ad-444f-8e4c-7dcc4ed49449.png)

---

### Branch 5: XBB.1.9.1 + ORF1a:L92F + ORF1a:A3571V + S:N481K

**Defining Mutations:** XBB.1.9.1 >  C539T(ORF1a:L92F) > C10977T(ORF1a:A3571V), T23005G(S:N481K) >
**Query:** C10977T, T23005G [23 seqs]
**Earliest seq:** 2023-03-09 (EPI_ISL_17257316, England)
**Most recent seq:** 2023-05-20
**Sampled Countries:** UK (11, England/10, Wales/1), USA (4, New Jersey/2, Virginia/2), Australia (4, NSW/3, Queensland/1), France (2), Germany (1), Isreal (1)
<details><summary>Genomes: </summary>
EPI_ISL_17257316, EPI_ISL_17257427, EPI_ISL_17358849, EPI_ISL_17381703, EPI_ISL_17469179, EPI_ISL_17483831, EPI_ISL_17549063, EPI_ISL_17549345, EPI_ISL_17584830, EPI_ISL_17621541, EPI_ISL_17621661, EPI_ISL_17666291, EPI_ISL_17667353, EPI_ISL_17710103, EPI_ISL_17731145, EPI_ISL_17731207, EPI_ISL_17744118, EPI_ISL_17744131, EPI_ISL_17762558, EPI_ISL_17762716, EPI_ISL_17358999, EPI_ISL_17408925, EPI_ISL_17528907
</details>

**UShER:**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a646_fd8580.json?c=userOrOld&f_userOrOld=uploaded%20sample

---

### Branch 6: XBB.1.5.30 + ORF7a:V74A + ORF3a:L15F + S:N481K

**Defining Mutations:** T27614C(ORF7a:V74A) > C24358A > C17010T, G25437T(ORF3a:L15F) > T23005A(S:N481K) >
**Query:** T27614C, T23005A [37 seqs]
**Earliest seq:** 2023-03-30 (EPI_ISL_17454852, Canada/NL)
**Most recent seq:** 2023-05-23
**Sampled Countries:** Canada (32, All NL), Australia (5, all NSW)
<details><summary>Genomes: </summary>
EPI_ISL_17454852, EPI_ISL_17516681, EPI_ISL_17516683, EPI_ISL_17516686, EPI_ISL_17516687, EPI_ISL_17516688, EPI_ISL_17516691, EPI_ISL_17516693, EPI_ISL_17516694, EPI_ISL_17553032, EPI_ISL_17561711, EPI_ISL_17561712, EPI_ISL_17561713, EPI_ISL_17561714, EPI_ISL_17561716, EPI_ISL_17561717, EPI_ISL_17612684, EPI_ISL_17651739, EPI_ISL_17651741, EPI_ISL_17651743, EPI_ISL_17651744, EPI_ISL_17651745, EPI_ISL_17651746, EPI_ISL_17651749, EPI_ISL_17651750, EPI_ISL_17651760, EPI_ISL_17651762, EPI_ISL_17683318, EPI_ISL_17683705, EPI_ISL_17718231, EPI_ISL_17718242, EPI_ISL_17718245, EPI_ISL_17718250, EPI_ISL_17718255, EPI_ISL_17767518, EPI_ISL_17767529

EPI_ISL_17741892
</details>

**UShER:**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41eec_fdc310.json?c=userOrOld&f_userOrOld=uploaded%20sample

---

K is predicted to be the most fit mutation on residue 481 of S:
![481K Fitness](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/834d43c2-9a9b-496d-a32b-88d37a07887b)

**Comment by FedeGueli** [comment]
I see 11/11/ 8 as count today.
@NkRMnZr could you check the second branch query? i modified a bit cause it ave 98 seqs at first chance.

**Comment by FedeGueli** [comment]
Thx i suspected that!

**Comment by FedeGueli** [comment]
They seems slow (unsurprising cause N481K popped up multiple times without any advantage as today. Lets wait a couple more of week if they dont grow significatively we will close (better not to waste time in monitoring slow things)

**Comment by FedeGueli** [comment]
> 2 more seqs from England on Branch 1 EPI_ISL_17736728, EPI_ISL_17736792
> 
> I'll close this issue next week if it doesn't grow any faster.

Agree likely just lin 1 worth to be monitored on its own. so or you re edit this one or you can open a new one just for lineage one.

**Comment by FedeGueli** [comment]
FL.11 + S:N481K  20seqs  Gisaid: 23005A, C9073T,  T28297C
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice27_genome_3238d_d9c830.json?label=id:node_6696050
![Schermata 2023-06-05 alle 12 06 27](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bf352560-43ad-444f-8e4c-7dcc4ed49449)

**Comment by FedeGueli** [comment]
@NkRMnZr very little new sequences i am tempted to close this one, but if you will find some of these growing please ping me.

**Comment by HynnSpylor** [comment]
Branch 6 has been designated as HM.1 (XBB.1.5.30.1)

**Comment by Over-There-Is** [comment]
@FedeGueli I think FL.1.6 should also be added to the milestone.
