### ISSUE TITLE
FY.3.1 sublineage with S:E183K (11 seqs in US and Italy)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#591]
Defining mutations:
FY.3.1>G4109T (ORF1a:D1282Y)>C27509T (ORF7a:T39I)>C8481T (ORF1a:P2739L)>C21952T, G22109A (S:E183K)
GISAID query: C21952T, C22109A, A22161G
Earliest seq: 2023-07-05 (US- EPI_ISL_18022790)
Most recent seq: 2023-07-30 (Italy- EPI_ISL_18064404)
Countries detected: US (4), Italy (1)
Usher Tree:
<img width="918" alt="屏幕截图 2023-08-11 234056" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/f641f097-df1a-4b40-a2d0-3e2ad36e2755">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a8cd_652b70.json?c=gt-S_183&label=id:node_6862691

S:Q183E is one of XBB* defining mutations. Now some lineages have shown the further mutation S:E183K

Genomes:
EPI_ISL_18022790, EPI_ISL_18064404, EPI_ISL_18072610, EPI_ISL_18090088, EPI_ISL_18090101

**Comment by FedeGueli** [comment]
it seems very slow.

**Comment by FedeGueli** [comment]
one more but still closing this
