### ISSUE TITLE
EG.6.1 (S:F456L) sublineage with ORF1a:2977K and ORF1a:I4308T first detected in California, USA (279 GISAID seqs as of 2023-09-08; 5 countries)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#599]
There may be a EG.6.1 sublineage with ORF1a:T2977K (C9195A; NSP4:T214K) and ORF1a:I4308T (T13188C; NSP10:I55T) first detected in USA.

This is a sibling lineage to the one described in https://github.com/sars-cov-2-variants/lineage-proposals/issues/306 since both share ORF1a:T2977K.

As of 2023-08-12, Cov-Spectrum reports 82 good-quality (95 total) EG.6.1+ORF1a:2977K+ORF1a:4308T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AEG.6.1+%26+ORF1a%3AT2977K+%26+ORF1a%3AI4308T&nextcladeQcOverallScoreTo=29&

GISAID shows 100 sequences

In the USA, this lineage is showing a 17% growth advantage (confidence interval 6% to 28%) over its parent half-FLip lineage EG.6.1. Relative to all lineages, this lineage shows a 43% growth advantage (confidence interval 36% to 51%) in the USA for a growth rate confidence interval that today would place it between the 10th and 11th fastest designated lineages in the USA.

This lineage has been reported in 8 states of the USA from the southwest to the northeast, and it has been reported from at least 2 additional countries.

As of 2023-08-12, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_EG 6 1_ORF1a_2977K+ORF1a_4308T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/26e5a0f6-ae9e-4263-ae0c-810ff276846a)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_EG.6.1%2BORF1a_2977K%2BORF1a_4308T.json?c=gt-ORF1ab_4308&label=id%3Anode_6815717

GISAID query: C1684T, T22928C, C9195A, T13188C

First GISAID sequence: California, USA 2023-05-21 

Most Recent GISAID sequence: Arizona, USA 2023-07-31

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum UShER output files for these sequences is available at [Support_EG.6.1+ORF1a_2977K+ORF1a_4308T.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12328410/Support_EG.6.1%2BORF1a_2977K%2BORF1a_4308T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-EG.6.1+ORF1a_2977K+ORF1a_4308T.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12328411/gisaid-epi-isl-EG.6.1%2BORF1a_2977K%2BORF1a_4308T.txt)

**Comment by FedeGueli** [comment]
As its sibling it doesnt show an advantage over EG.5.1.1 , lets wait mid month if it reaches 400 maybe it is worth a designation.

**Comment by alurqu** [comment]
This lineage is growing but only slowly, so I'm closing this proposal.
