### ISSUE TITLE
Suggestions on tags

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#60]
Suggest to broaden 'non-spike mutations' tag into the following:
'nsp mutations' (for orf1ab/nsp1-16)
'accessory gene mutations' (for orf3a, 6, 7ab, 8, 9b, 10, co-related with 'truncated' tag)
'envelope mutations'
'membrane mutations'
'nucleocapsid mutations'
'synonymous mutations'
and 'non-coding IGS/TRS mutations'

broaden 'spike mutations' into the following:
'NTD mutations'
'RBD mutations', ~~merge S:356, S:403, S:456, S:478, S:486 here,~~ co-related with 'convergent evolution' tag
'FCS mutations'
and
'S2 subunit mutations'

rename 'SGTF' to 'potential target failure' since it could occur on only S gene, but also N gene and ORF1ab gene

splitting 'New mutations' into the following:
'Emerging mutations' 
and 'Re-emerging mutations' for those appeared in the past but went silent for a while.

And, maybe there's no need for word like 'mutations' in tags after all.

**Comment by FedeGueli** [comment]
Thank you.
The tags should be used then to sistematically check a category, example: i want check all the S:F456L carrying lineages so i will query for S:F456L on the search tab and find all of them in a row.
In fact they have not the goal to be exhaustive on the proposed lineage . But ok lets open a discussion and see.
