### ISSUE TITLE
EG.5.1.3/XBB.1.16.19 recombinant in USA (16 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#600]
I find a grouped EG.5.1/XBB.1.16 recombinant with 7 seqs under a sub-tree full of EG.5.1*/XBB.1.16* recombinants.

mutations on top of EG.5.1: T2334C(rev), A5720G(rev), T5422C, C7044A, T9693C(rev), C22570T, C27507A(rev), G27065A, A28182G, A28447G, T29625C(rev) C29386T

XBB.1.16---EG.5.1.3---XBB.1.16
Breakpoint 1: between 9694 and 11749
Breakpoint 2: between 22996 and 27064

Private mutations: T5422C, C7044A(Orf1a:P2260H), G27065A,A28182G(Orf8:S97G)

Usher places it under EG.5.1.1 but it has all 3 EG.5.1.1 defining mutations reverted so it shall be EG.5.1.

It has one of the EG.5.1.3 defining mutations (C22570T) and the other defining mutation for EG.5.1.3(C1889T) is on XBB.1.16 part. So the EG.5.1-side donor is likely EG.5.1.3.

This one is basically EG.5.1-spike with XBB.1.16-Orf9b.

GISAID query: C22570T, G27065A,A28182G
No. of seqs: 7(USA-CA,NY,UT,TX)

FIrst: EPI_ISL_18095385, Utah, 2023-7-12
Latest: EPI_ISL_18081455, California, 2023-7-26

 Besides the sub-tree it belongs to is full of other EG.5.1/XBB.1.16 recombinant singlets.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_728a_849b50.json?branchLabel=nuc%20mutations&c=gt-nuc_28182&showBranchLabels=all)

Edited: clearer link for the tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3688_88b700.json?f_userOrOld=uploaded%20sample&label=id:node_6789374

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b77fa949-85f1-4888-97db-7c83dcfe3abf)

Resulting in this overall picture:
![Schermata 2023-08-13 alle 10 09 46](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d204eca3-c702-43e6-81d9-e0d5a5c0f89b)

**Comment by FedeGueli** [comment]
I have identified the [XBB.1.16 in XBB.1.16+Orf1a:P2260H+ G27065A](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AP2260H&nucMutations=G27065A&nextcladePangoLineage=XBB.1.16.19&) circulating in California/Hawaii recently.
![Schermata 2023-08-13 alle 10 02 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1ed02ac1-e459-4871-a112-fd91fb7135b7)

So looking at the [Vienn diagram](https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-07-01%26to%3D2023-08-06/variants?nucMutations=C22570T%2CG27065A%2CA28182G&nextcladePangoLineage1=EG.5.1.3*&aaMutations2=ORF1a%3AP2260H&nucMutations2=G27065A&nextcladePangoLineage2=XBB.1.16.19*&analysisMode=CompareEquals&) Breakpoint are correct. thank you:
![Schermata 2023-08-13 alle 10 06 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2d191d3e-ef85-4bd1-9da6-50f34cd972c9)
![Schermata 2023-08-13 alle 10 06 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2fea7fbf-af19-4018-9601-21e75a3b2feb)

![Schermata 2023-08-13 alle 10 06 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d069c3ea-7964-403e-b310-24e173aaebf9)
![Schermata 2023-08-13 alle 10 06 40](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3233f513-80c1-42c4-bdec-f6735165f4d6)

**Comment by FedeGueli** [comment]
cc @corneliusroemer misplaces this as XBB.1.42

**Comment by aviczhl2** [comment]
+1 NJ, 5 states now

**Comment by FedeGueli** [comment]
Propose it when it reaches 15 ( if in one7two weeks from now)

**Comment by aviczhl2** [comment]
+3 Alaska, 6 states now,

**Comment by aviczhl2** [comment]
+1 Indiana, 7 states now.

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
It is spreading pls go on proposing it!

**Comment by FedeGueli** [comment]
Designated XCV via https://github.com/cov-lineages/pango-designation/commit/396563328e3a8d292687b97591148b7d08ceffba
