### ISSUE TITLE
Multiple EG.5.1.1+S:Q14R branches (x - 81-45-29, total=904）

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#601]
I don't think a proper query can be made to exclude everything else, given the fact that new separate lineages are popping up from time to time. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0bcfeadd-2d85-45ab-9237-f28012a0729b) 
_Proposal (edited by mod)_

_Branch 1_ ( Proposed in https://github.com/cov-lineages/pango-designation/issues/2252) CLOSED
EG.5.1.1+S:Q14R, X(about 500) seqs,
A21603G,C25572T,T23018C,-29386

_Branch 2_  proposed in https://github.com/cov-lineages/pango-designation/issues/2387
Designated HK.3.13
HK.3+C14889T+S:Q14R , **61 Seqs**
A21603G,C6541T,T23018C, C14889T,, China,Singapore, USA
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d64655e9-ceeb-4a55-8eee-3a376d122d91)

_Branch 3_ proposed in https://github.com/cov-lineages/pango-designation/issues/2436
HK.13.1+S:Q14R, **81 seqs** , 12/29
A21603G,C6541T,T23018C, A24604G, Hong Kong, Singapore, Hubei

_Branch 4_
HK.12+S:Q14R Orf1b:K2085E, **45 seqs** , 12/29
A21603G,C6541T,T23018C, A22629C, China, Singapore, Australia

_Branch 5_ dead
EG.5.1.1+Orf1a:T1589I+S:L455F+N:T24I+S:Q14R
A21603G,C6541T,T23018C, C5031T, G22927T, **20 seqs**, Canada

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b9165287-c19a-447d-9abb-bdaa5899148c)

_Branch 6_ Designated HK.32
EG.5.1.1+Orf1a:S2193F+S:Q14R, **28 seqs**, 12/03
A21603G,C6541T,T23018C, C6843T, China, Australia,Canada
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a3df2c24-065f-4c34-8881-ae2007b6da79) 

_Other Branches_

EG.5.1.1+Orf1a:V2116L+V121I,N:G19R,S:Q14R, 11 seqs
A21603G,C6541T,T23018C, G6611T, China, Singapore, Ireland

EG.5.1.1+S:P1263L+Orf1a:E2070D,Q14R, 17 seqs
A21603G,C6541T,T23018C, C25350T,Hubei

HK.13.2+S:Q14R, 29 seqs
A21603G,C6541T,T23018C, T23953A, Hubei, Sichuan

EG.5.1.1+C21742T+S:Q14R, 13 seqs
A21603G,C6541T,T23018C,C21742T, France, Australia, Peru， Belgium, UK

EG.5.1.1+A8443G+S:Q14R, 7 seqs
A21603G,C6541T,T23018C, A8443G, Shanghai, Xinjiang

EG.5.1.1+Orf1b:I1539T+S:Q14R, 7 seqs
A21603G,C6541T,T23018C, T18083C, Sichuan, Canada

An EG.5.1.1/BA.5 recombinant, 3 seqs
A21603G,C6541T,T23018C, G1886C, Shanghai (this one has 405A so likely recomb with BA.5* on 5'-side)

**Comment by FedeGueli** [comment]
All the samples are very recent please propose it.

**Comment by aviczhl2** [comment]
> All the samples are very recent please propose it.

Sorry My bad. It seems that this one is quite convergent like S:L455F and has become various different lineages. I'll change my title.

**Comment by FedeGueli** [comment]
Thank you @aviczhl2 very weird such a convergence! cc @ryhisner did u know anything on S:14 ?? Asking you cause i know you went deep on 9-13-16 mutations

**Comment by aviczhl2** [comment]
> Thank you @aviczhl2 very weird such a convergence! cc @ryhisner did u know anything on S:14 ?? Asking you cause i know you went deep on 9-13-16 mutations

Maybe due to the high population of China. If sth. appears at say 1/10^8 rate, it will happen 14 times in China but only 1 time in Japan.

**Comment by ryhisner** [comment]
> Thank you @aviczhl2 very weird such a convergence! cc @ryhisner did u know anything on S:14 ?? Asking you cause i know you went deep on 9-13-16 mutations

I don't know what's going on with S:Q14. There have also been a ton of S:Q14H and S:Q14K mutations, so it seems to want to go to a positive charge there. No idea why that would be. 

The S:14 mutation trend is driven almost entirely by China, so I feel pretty certain that the very different infection history has created a population immunity environment that strongly favors S:Q14 mutations. 
<img width="1415" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2f5704a9-a589-4b75-90e3-047f4b94838f">

**Comment by FedeGueli** [comment]
Thx @ryhisner

**Comment by aviczhl2** [comment]
We get 9 more seqs in 2 days, 17+4+2*3+1*7 now.

**Comment by FedeGueli** [comment]
ok lets start to propose them once they reach 20. ok?

**Comment by aviczhl2** [comment]
> ok lets start to propose them once they reach 20. ok?

Is it better to give up the main branch and only treat those with at least one additional mutation other than S:Q14R as a separate lineage?

**Comment by FedeGueli** [comment]
@aviczhl2 propose each of them separately when they reach 20 . so lets start with the main one.

**Comment by aviczhl2** [comment]
It seems that branch 1 already reaches 25, but there may be more separate branches.

**Comment by aviczhl2** [comment]
@FedeGueli 
EG.5.1.1 baseline: 22480T,19720A

This branch is weird, we have 3 seqs of S:Q14R on a branch, with

22480C+19720A
22480C+19720G
22480T+19720G

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/36e6cfdb-1557-4922-847e-73957f1b8a65)

**Comment by FedeGueli** [comment]
> @FedeGueli EG.5.1.1 baseline: 22480T,19720A
> 
> There is a weird branch that cannot be queried by any GISAID queries.
> 
> We have 3 seqs of S:Q14R on a branch, with
> 
> 22480C+19720A 22480C+19720G 22480T+19720G
> 
> ![image](https://user-images.githubusercontent.com/10445944/265248498-36e6cfdb-1557-4922-847e-73957f1b8a65.png)

Crazy! maybe @corneliusroemer @angiehinrichs could help?

**Comment by aviczhl2** [comment]
Total of the whole is 44 now. I'm trying to clear up current branches.

**Comment by ryhisner** [comment]
> @FedeGueli EG.5.1.1 baseline: 22480T,19720A
> 
> There is a weird branch that cannot be queried by any GISAID queries.
> 
> We have 3 seqs of S:Q14R on a branch, with
> 
> 22480C+19720A 22480C+19720G 22480T+19720G
> 
> ![image](https://user-images.githubusercontent.com/10445944/265248498-36e6cfdb-1557-4922-847e-73957f1b8a65.png)

This is a branch with an alleged reversion at 22480 (T22480C). The Washington, USA, sequence has no coverage at 22480, so it almost certainly doesn't belong in this branch. Most likely, the entire T22480C "reversion" branch is an artifact. As usual with these sort of branches, it's full of C22480T "unreversions." 

<img width="1497" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/fea3dc90-4d56-402f-9f01-b5d215aebc24">

The Shanghai sequence and Hubei sequence clearly are related, but they probably have no connection whatsoever to any of the other sequences in this branch.

**Comment by aviczhl2** [comment]
> 

Thanks! So this shall be part of the main branch, so the main branch actually has 24 confirmed seqs.

**Comment by aviczhl2** [comment]
Total 50 now. Will review this when total=100.

**Comment by aviczhl2** [comment]
Total 65 now.

**Comment by aviczhl2** [comment]
Total 79 now

**Comment by aviczhl2** [comment]
Total=107 now. Shall start a second investigation on this.

**Comment by aviczhl2** [comment]
@FedeGueli  Total 25 branches now, the main branch 65 seqs with 57 on main branch and some others misplaced on other branches with artefact/flip-flop reversions.  But number of branches is high.

**Comment by FedeGueli** [comment]
Crazy thank you for your work

**Comment by aviczhl2** [comment]
Total=164 now

**Comment by aviczhl2** [comment]
Total=185 now

**Comment by aviczhl2** [comment]
Total=227 now

**Comment by aviczhl2** [comment]
Analyse it again, the main branch has 113 seqs and there are a lot of new branches including an EG.5.1.1/BA.5 recomb now.

**Comment by FedeGueli** [comment]
>EG.5.1.1+S:L455F(G22927C)+C13378T,A24604G,S:Q14R, 4 seqs
A21603G,C6541T,T23018C, A24604G, Hong Kong, Singapore, Hubei
>

this one is a subbranch of HK.13.1

**Comment by FedeGueli** [comment]
>EG.5.1.1+S:L455F(G22927C)+S:F797L,D1153H,Q14R, 4 seqs
A21603G,C6541T,T23018C, T23953A, Hubei, Sichuan
>
This is a subbranch of HK.13

**Comment by FedeGueli** [comment]
Betond the main branches they other doesnt seem growing especially fast.

**Comment by FedeGueli** [comment]
Closing it as completed.

**Comment by FedeGueli** [comment]
If any of this will get Flip or other mutations to restore their fitness please ping me i will reopen it.

**Comment by Over-There-Is** [comment]
HK.3>C14889T>S:Q14R C6541T, C14889T, A21603G is 57 now.

**Comment by FedeGueli** [comment]
> A21603G,C6541T,T23018C, C14889T

éPlease propose it @aviczhl2

**Comment by FedeGueli** [comment]
These 3 lineages are the ones to watch and propose once 50 So i will shuffle the proposal putting them on the top. 
the rest is near dead, almost.

HK.13.1+S:Q14R, 42 seqs
A21603G,C6541T,T23018C, A24604G, Hong Kong, Singapore, Hubei

EG.5.1.1+S:Q14R,K356T, Orf1b:K2085E, 36 seqs
A21603G,C6541T,T23018C, A22629C, China, Singapore, Australia

HK.3+C14889T+S:Q14R
A21603G,C6541T,T23018C, C14889T, 56 seqs, China,Singapore, USA

**Comment by FedeGueli** [comment]
I have updated and reorganized the issue to track it at the est for a while more. reopening.

**Comment by FedeGueli** [comment]
Branch 2 has a 15/20%prevalence in Henan China in November worth proposing it.

**Comment by FedeGueli** [comment]
> Branch 2 has a 15/20%prevalence in Henan China in November worth proposing it.

already proposed : https://github.com/cov-lineages/pango-designation/issues/2387

**Comment by aviczhl2** [comment]
Branch 6 designated HK.32.  
Why start from branch 6?

**Comment by aviczhl2** [comment]
Branch 2 designated HK.3.13

**Comment by FedeGueli** [comment]
HK.3.13 via https://github.com/cov-lineages/pango-designation/commit/b1f5bb0f8ac43fbf64a98b2af357bfe23d134614

**Comment by FedeGueli** [comment]
HK.32 via https://github.com/cov-lineages/pango-designation/commit/fde1fd9c60a1c3070815c89476c3af4cc9efc2f8

**Comment by FedeGueli** [comment]
> A21603G,C6541T,T23018C, A24604G

let s see if some more recent samples will come , only 4 in November.

**Comment by ryhisner** [comment]
A unique HK.3 popped up today in Henan, China with S:Q14R, S:C15R, and S:P479R. EPI_ISL_18700325
The S:S375F that appears in the Usher Tree is actually a synonymous mutation in the third nucleotide of S:V367 (C22663T). For reasons I've never quite understood, almost any mutation that occurs between ~365-377 is registered by Usher as an S:S375F reversion. @AngieHinrichs, do you know why this is?
<img width="1426" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cfd12bd9-b2a3-4e87-9c99-1dcf160c1d32">

**Comment by FedeGueli** [comment]
> Branch 3 is 81 now.

Propose it please.

**Comment by ryhisner** [comment]
A second HK.3 sequence with S:Q14R, S:C15R, and S:P479R showed up today. Both collected on December 15 from Henan, China, but from different cities—Zhoukou and Xuchang.
EPI_ISL_18700325, EPI_ISL_18703895

**Comment by FedeGueli** [comment]
> A second HK.3 sequence with S:Q14R, S:C15R, and S:P479R showed up today. Both collected on December 15 from Henan, China, but from different cities—Zhoukou and Xuchang. EPI_ISL_18700325, EPI_ISL_18703895

better to propose it in a separate issue

**Comment by FedeGueli** [comment]
Thx for proposing Branch 3. I m closing this one.
i suggest @aviczhl2 to monitor these two : 
HK.13.2+S:Q14R, 29 seqs
A21603G,C6541T,T23018C, T23953A, Hubei, Sichuan

EG.5.1.1+C21742T+S:Q14R, 13 seqs
A21603G,C6541T,T23018C,C21742T, France, Australia, Peru， Belgium, UK 

Pleas ping if they keep on circulating.

@ryhisner i would monitor your S:C15R sublineage.

**Comment by AngieHinrichs** [comment]
> The S:S375F that appears in the Usher Tree is actually a synonymous mutation in the third nucleotide of S:V367 (C22663T). For reasons I've never quite understood, almost any mutation that occurs between ~365-377 is registered by Usher as an S:S375F reversion. @AngieHinrichs, do you know why this is?

That's very strange, I suspect it's something about the aligner that I use in usher.bio (blat).  FWIW branch-specific masking removes the reversion (T22686C) from the XBB branch because there seemed to be a lot of false reversions.  After the sequences have been added to the tree (aligned to reference by a different tool, mafft) and branch-specific masking has been applied, they do not appear to have the reversion -- and they do show the synonymous C22663T:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/lineage-proposals-601.json?c=gt-S_375&gmax=25384&gmin=21563&label=id:node_3527624
<img width="994" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/186983/a37ee220-5087-4f02-949a-9d2d51a7c83d">

That Nextstrain view is from pasting the ID EPI_ISL_18700325 into usher.bio with a subtree size of 500.  When I upload fasta for EPI_ISL_18700325 instead, now I see that blat gets the reversion T22686C instead of C22663T (and also gets a mutation at branch-specific-masked site 221 -- usher.bio can't do branch-specific masking):
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/lineage-proposals-601-fasta.json?c=userOrOld&label=id:node_3527624
<img width="994" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/186983/62fa59bd-d15d-4bea-859f-a4ae84fa9fbf">

So, drilling down to the sequence, here is how I would align the region in question, and it looks like mafft does this too:
```
22222222222222222222222222222222222222222222222222
22222222222222222222222222222222222222222222222222
66666666666666666666666666666666666666666666666777
55555556666666666777777777788888888889999999999000
34567890123456789012345678901234567890123456789012

ATTATTCTGTCCTATATAATTCCGCATCATTTTCCACTTTTAAGTGTTAT  ref
          ||         |    |      | |             
ATTATTCTGTTATATATAATTTCGCACCATTTTTCGCTTTTAAGTGTTAT  Henan/ZKCDC-129/2023
```
But blat does something that surprises me: it completely skips over some bases from both sequences (xxx's below), and introduces multiple gaps so that it ends up with no mismatches .  I guess it really does not like all those mismatches!
```
22222222222222222222222222222---222222222222222222222
22222222222222222222222222222---222222222222222222222
66666666666666666666666666666---666666666666666666777
55555556666666666777777777788---888888889999999999000
34567890123456789012345678901---234567890123456789012

ATTATTCTGTCCTATATAATTCCGCATCA---TTTTCCACTTTTAAGTGTTAT  ref
                  xxxxxxxxxxx        xx
ATTATTCTGT--TATATATAATTTCGCACCATTTTTCG-CTTTTAAGTGTTAT  Henan/ZKCDC-129/2023
```
Since blat has found a (dubious IMO) way to avoid all mismatches in that region (perhaps by seeding the alignment with perfectly matching 11mers), it ends up asserting that 22686 has reverted to reference.

Well Ryan, your powers of observation are legendary, thanks for pointing out that weird pattern!  I guess I need to find a different aligner to use in usher.bio given the level of divergence we're seeing these days.

**Comment by aviczhl2** [comment]
ATTATTCTGTCCTATATAATTCCGCATCA---TTTTCCACTTTTAAGTGTTAT  ref
                  xxxxxxxxxxx        xx
ATTATTCTGT--TATATATAATTTCGCACCATTTTTCG-CTTTTAAGTGTTAT  Henan/ZKCDC-129/2023

It seems that it is C22663T, C22664A, C22674T, T22679C, C22686T, A22688G. 

C22664A, C22674T, T22679C, C22686T, A22688G are already presented in XBB so the mutation here is only C22663T?

**Comment by aviczhl2** [comment]
> Since blat has found a (dubious IMO) way to avoid all mismatches in that region (perhaps by seeding the alignment with perfectly matching 11mers), it ends up asserting that 22686 has reverted to reference.

Maybe a 2-step process is better? First compare with original to decide its general belonging (BA.2, BA.5, XBB, BA.2.86, etc), then compare with the branch-specific reference for more accurate mutation profile?

**Comment by FedeGueli** [comment]
> ATTATTCTGTCCTATATAATTCCGCATCA---TTTTCCACTTTTAAGTGTTAT ref xxxxxxxxxxx xx ATTATTCTGT--TATATATAATTTCGCACCATTTTTCG-CTTTTAAGTGTTAT Henan/ZKCDC-129/2023
> 
> It seems that it is C22663T, C22664A, C22674T, T22679C, C22686T, A22688G.
> 
> C22664A, C22674T, T22679C, C22686T, A22688G are already presented in XBB so the mutation here is only C22663T?

i never dig into this but using Dave McNally tool that detects spike mutations in UK Climb database i met S:V367I more than one time and then it never showed up  in Usher.

**Comment by AngieHinrichs** [comment]
> C22664A, C22674T, T22679C, C22686T, A22688G are already presented in XBB so the mutation here is only C22663T?

Yes, the first step when you upload a sequence to usher.bio is alignment to the reference ([NC_045512](https://www.ncbi.nlm.nih.gov/nuccore/NC_045512)) so that we can use reference coordinates like 22664 and so on, and so that we know what mutations the sequence has.  Before alignment, we know nothing about the sequence.  When we know that we're dealing with an XBB sequence, then yes we expect 5 of those 6 mutations so only C22663T is new.  But if the alignment tool tells us that we have some weird indels instead of single-nucleotide changes, then we need a more appropriate alignment tool.
