### ISSUE TITLE
Potential XBB.2.3* and XBB.1.5* recombinant (23 seqs, mainly in Spain, 3 countries), further gained S:F456L (7 seqs, Spain and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#604]
**Defining Mutations:** `XBB.2.3` > ~~T28297C(ORF9b:I5T)~~ > _T29706G_reversion_ > _T27431C_rev(ORF7a:V13A_reversion)_, `G27915T(ORF8:G8*)` > `T3797C(ORF1a:F1178L)` > _C28297T_reversion(ORF9b:T5I_reversion)_

**Recominant Profile:**
- Donor A: **XBB.2.3**, from 5' End to Breakpoint
- Donor B: Unsure, could be any XBB.1 + `ORF8:G8*`, without `ORF9:I5T`, most likely **XBB.1.5**
- Breakpoint: Between `nuc 23123/S:521` to `nuc 27431/ORF7a:13`
- Private mutation: `ORF1a:F1178L/nsp3_F360L/T3797C`, that's before the potential breakpoint.

**Query:** `T3797C, G6536A, G27915T, -T28297C`
**Query for further S:F456L branch:** `T5965C, T22930A, C26873T`

**Earliest seq:** 2023-03-30 (`EPI_ISL_17440750`, Basque, Spain)
**Latest seq:** 2023-07-24 (`OR398253.1`, New York, USA)
**Sampled Countries:** Spain (14), USA (2)

<details><summary>Genomes: </summary>

`EPI_ISL_17440750, EPI_ISL_17690211, EPI_ISL_17690239, EPI_ISL_17699380-17699381, EPI_ISL_17766844, EPI_ISL_17963579, EPI_ISL_17964301, EPI_ISL_18015491, EPI_ISL_18022804, EPI_ISL_18072010, EPI_ISL_18072208, EPI_ISL_18075214, EPI_ISL_18075246, EPI_ISL_18095937`
</details>

<details><summary>non-GISAID Genomes: </summary>

`USA/NY-PRL-230728_81E11/2023|OR398253.1|2023-07-24`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16480_9275b0.json?f_userOrOld=uploaded%20sample
![Branch 1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/135e4513-1fb2-40b8-9c1b-d32f71355b1c)

**Trivia:**
- Branch 1 got further `S:F456L`, not sure if that's convergent or from a different recombinant event. Unsure about the other donor either.
- It happens to be neighbouring to #535 on phylogenetic tree, ie. happens to have similar breakpoint sites but with a different donor.

**Comment by FedeGueli** [comment]
great catch thx for your work. Lets see if it spread further.

Rapid identikit of the 456L carrying one:
![Schermata 2023-08-14 alle 01 29 17](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/83f804b6-be53-45f6-bd00-55913fa6e87c)
