### ISSUE TITLE
EU.1.1 with ORF1a:H2092Y (nsp3_H1274Y), N:M322I, ORF1a:M2796V (nsp4_M33V) and S:S494P (19 seqs, France, Belgium)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#608]
**Defining Mutations:** `EU.1.1 (XBB.1.5.26.1.1)` > `T19809C` > `G991A` > `C6539T(ORF1a:H2092Y), G29239T(N:M322I)` > `A8651G(ORF1a:M2796V), C16111T, T23042C(S:S494P)`
**Query:** `A8651G, C16111T, T23042C`
**Earliest seq:** 2023-07-10 (EPI_ISL_18048997, Occitanie, France)
**Latest seq:** 2023-07-24 (EPI_ISL_18094671, Nouvelle-Aquitaine, France)
**Sampled Countries:** France (12: Occitanie/8; Nouvelle-Aquitaine/2; Provence/1; Auvergne-Rhône-Alpes/1)

<details><summary>Genomes: </summary>

`EPI_ISL_18048997, EPI_ISL_18056682, EPI_ISL_18070083-18070084, EPI_ISL_18070092, EPI_ISL_18070118, EPI_ISL_18070126, EPI_ISL_18070128, EPI_ISL_18070144, EPI_ISL_18070163, EPI_ISL_18094633, EPI_ISL_18094671`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4372c_a03260.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2af65667-0235-43c9-b33c-d217e4f082b2)

**Comment by FedeGueli** [comment]
It cant co mpete: https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A8651G%2CC16111T%2CT23042C&analysisMode=CompareToBaseline&
