### ISSUE TITLE
Potential GM.2 and FP.1 recombinant (28 seqs, 4 countries) further gained S:S494P (17 seqs, 4 countries) with a singlet got extra S:K444T

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#609]
**Defining Mutations:** `GM.2` > _T7105C_rev_ > _T4234C_rev_, `C6312T(ORF1a:T2016I)`, _A6536G_rev(ORF1a:S2091G_rev)_, `A6616G`
**Query:** `C6312T, A6616G, G22103C`

**Query** for further `S:S494P` sub-branch: `C6312T, G22103C, T23042C`
**Query** for further `S:S494P` + `S:K444T` sub-branch: `C6312T, G22103C, A22893C`

**Recombinant Profile:** 
- Donor A: GM.2 (XBB.2.3.6.1), from 5' End to 1st breakpoint, from 2nd breakpoint to 3' End
- Donor B: FP.1 (XBB.1.11.1.1), betewen 2 breakpoints
- Breakpoint 1: from `nuc 1063` to `nuc 4234`
- Breakpoint 2: from `nuc 7105` to `nuc 16342/ORF1ab_5360`

**Earliest seq:** 2023-04-17 (`EPI_ISL_17596226`, Singapore)
**Latest seq:** 2023-07-26 (`EPI_ISL_18097192`, Hongkong, China)
**Sampled Countries:** Singapore (15), China (1, HK), USA (1, CA)

<details><summary>Genomes: </summary>

`EPI_ISL_17596117, EPI_ISL_17596163, EPI_ISL_17596226, EPI_ISL_17670383, EPI_ISL_17670456, EPI_ISL_17670533, EPI_ISL_17670567, EPI_ISL_17694782, EPI_ISL_17724538, EPI_ISL_17724540, EPI_ISL_17724543, EPI_ISL_17724558, EPI_ISL_17724566, EPI_ISL_17790782, EPI_ISL_17790799, EPI_ISL_17866083, EPI_ISL_18097192`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a781_a3b060.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1da33f54-3e52-48ed-af32-40dae73f1013)

**Trivia:**
- The recombinant itself is nothing spectacular, except for being placed on UShER tree as the _largest sub-branch_ of GM.2 right now.
- It soon gained `S:S494P` then the latest sequence `Hong_Kong/VB23126930/2023|EPI_ISL_18097192|2023-07-26` gained another RBD Level `S:K444T` that are missing from XBB* backbone, so I'll leave it here to monitor for a while.

**Comment by FedeGueli** [comment]
Please propose it.

**Comment by corneliusroemer** [comment]
Great work - just independently came to the same conclusion that this is a GM.2 with a little bit of FP.1 (sandwich) when seeing all the CAN-ON-PHL sequences.

**Comment by FedeGueli** [comment]
@NkRMnZr the sublineage with S:F494P has reached 36 
showing this advzantage versus dominant lineages: https://cov-spectrum.org/explore/World/AllSamples/from%3D2023-05-29%26to%3D2023-08-31/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C6312T%2CG22103C%2CT23042C&analysisMode=CompareToBaseline& 

I urge you to propose it separately.

**Comment by FedeGueli** [comment]
XCJ
