### ISSUE TITLE
XBB.1.19.1 with ORF1a:S302F, ORF1a:P2079Q, ORF1a:P4220L, S:L455F, S:F456L, S:K478I, N:P80S (5 seq. China ex UAE, Australia, Canada, US)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#61]
**EDITED**

Defining mutations:
XBB.1.19.1 (S:E554K) : > N:P80S (C28511T) > Orf1a:S302F (C1170T) > Orf1a:P2079Q (C6501A), C12473T, Orf1a:P4220L(C12924T), S:K478I (A22995T), C24034T, T24046C, T28723C > S:L455F (G22927T), S:F456L (T22928C)
Query : T28723C,G22927T,T22928C,C12473T (Edited)
Tree:
![Schermata 2023-07-25 alle 14 54 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e239c367-35ca-4c3d-8ff8-300225a6482b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a7fa_fc5a90.json?label=id:node_6625137

Samples:
hCoV-19/Canada/ON-PHL-23-26905/2023\|EPI_ISL_18030523\|2023-07-15
hCoV-19/USA/NJ-CDC-QDX82431222/2023\|EPI_ISL_18022751\|2023-07-05
USA/NY-PRL-230711_81B06/2023\|OR342426.1\|2023-07-08
hCoV-19/Australia/WA14482/2023\|EPI_ISL_17999822\|2023-07-07
hCoV-19/Shanghai/SCDC-HG0504-476/2023\|EPI_ISL_17645716\|2023-05-01

*******************************

**ORIGINAL ISSUE**:
C_AA014164 or/and EPI_ISL_17645716 (I don't know whether they are the same or not).

https://cov-spectrum.org/explore/China/AllSamples/Past6M/variants?variantQuery=S%3A455F%26S%3A456L%26S%3A478I&
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41985_2764a0.json?c=gt-S_455&label=id:node_6687574
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/8d15d82a-3f17-4ce2-8206-5c22f568f519)

edited: Spike_T478I,Spike_L455F

**Comment by FedeGueli** [comment]
Thanks for highlighting, here it is possible to highlight also singlets , i ask just the knindness of track them in the first two weeks after the first "proposal" if no new sequence has come into the game please close this kind of issue by yourself. 

So for this one i fix closing date for 1st of June if no sequence has been uploaded before. 

Ok?

**Comment by oobb45729** [comment]
No problem.

**Comment by oobb45729** [comment]
Considering how relatively new XBB.1.19.1 is in China, this strain likely did not originate in China. I wonder where it comes from.

**Comment by aviczhl2** [comment]
> Considering how relatively new XBB.1.19.1 is in China, this strain likely did not originate in China. I wonder where it comes from.

XBB* has been circulating in China for a very long time, it is just not sequenced due to CCDC's low sequencing density. 

Especially in some areas like Beijing, where zero sequences have been uploaded in the recent month. 

We already have long Chinese XBB saltations like https://github.com/sars-cov-2-variants/lineage-proposals/issues/16

**Comment by oobb45729** [comment]
https://ngdc.cncb.ac.cn/genbase/search/gb/C_AA014164.1?lang=en
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/3beac5af-bba4-4261-903e-63bd5d8a7a5e)
So it's from UAE, where no sequences was uploaded recently.

**Comment by FedeGueli** [comment]
rapid qury to check this:   N_P80S,N_T379I. i think it has not spread. but still wait for exp date.

**Comment by HynnSpylor** [comment]
Now Australia updated another sample without ORF1a:H1160Y and N:T379I
<img width="713" alt="屏幕截图 2023-07-19 203918" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/457411e7-c29d-4bf8-be26-d20a2ae2105a">

**Comment by FedeGueli** [comment]
New query: Spike_T478I,Spike_L455F

**Comment by FedeGueli** [comment]
Two more sequences of this one one  from New Jersey and another from Canada. Please propose it @oobb45729

**Comment by FedeGueli** [comment]
Another one from NYC not yet on Gisaid 5 in total. Ping @corneliusroemer i suggest direct designation of this one first time we see 455-456-554

**Comment by FedeGueli** [comment]
Designated GW.5 via https://github.com/cov-lineages/pango-designation/commit/166dd7494a8bf79105a7e58a54449813863dd044
