### ISSUE TITLE
EG.5.1.3 + ORF1a:V274L (62) in 7 countries a branch with 5 orf1ab mutations (S7090C, D7091R, V7092S, L7093V, V7094L) 6 seqs

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#610]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/bdb7969b-9eb0-414e-85a2-e844db8c41c6)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/07fc1ac9-b4ad-4b48-97f0-c4ff09fe9374)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16ac4_a73430.json?c=gt-ORF1ab_274&label=id:node_6794309
EPI_ISL_18049050 EPI_ISL_18070106 EPI_ISL_18070057 EPI_ISL_18070164 EPI_ISL_18070116 EPI_ISL_17962976 EPI_ISL_17987378 EPI_ISL_18094318 EPI_ISL_18049049 EPI_ISL_18037739 OR399383.1 EPI_ISL_18092159 EPI_ISL_17962997 EPI_ISL_18044679 EPI_ISL_18070029 EPI_ISL_18070062 EPI_ISL_18070135 EPI_ISL_17976795 EPI_ISL_18070132 EPI_ISL_17987377 EPI_ISL_18070113 EPI_ISL_18048987 EPI_ISL_18070070 EPI_ISL_18070043 EPI_ISL_18092161 EPI_ISL_18092134 EPI_ISL_18070162 EPI_ISL_18070167 EPI_ISL_18070034 
first seq: 2023-06-21
most recent: 2023-08-07
gisaid query: G1085T, G15451A, C1889T

**Comment by Mydtlwn** [comment]
![Uploading Screenshot_20230815_083921_com.tencent.mtt.png…]()

**Comment by Mydtlwn** [comment]
![Uploading Screenshot_20230815_083921_com.tencent.mtt.png…]()

**Comment by Fearuncle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a466c622-4089-46a0-b5a7-561ea24eefa7)

**Comment by FedeGueli** [comment]
@ryhisner could u give a look at these clustered mutations at the end of orf1b please?

**Comment by aviczhl2** [comment]
Do those clustered orf1b ones really belong to Orf1a:V274L?

**Comment by FedeGueli** [comment]
> Could it be a recominant (with some non-B.1.1.529 lineage)? It has `T28271A_reversion` right before long branch of multiple ORF1ab aa change, which potentially upregulate expression of ORF9b.

28271 is for you @ryhisner

**Comment by ryhisner** [comment]
The ORF1b cluster looks like it's almost certainly an artifact. The BLAST nucleotide alignment tool won't even try to align that part of the genome with the reference sequence, and Nextclade shows a complex mix of NNN's, insertions, frameshifts, and deletions. 
<img width="299" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0776f239-3055-4b71-8196-49e9b43a94aa">
.

The coverage on the sequences is not good, and there are a lot of mixed nucleotides. 

.
<img width="911" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/82a73244-a63e-4bab-88d8-27a71a0a58b8">
.

There are also an extraordinary number of "reversions," almost certainly all artifactual, including T28271A.


.
<img width="1392" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d4f65a40-b16f-4e02-890c-0a8377de7236">

**Comment by FedeGueli** [comment]
Closing this for now.

**Comment by FedeGueli** [comment]
> The ORF1b cluster looks like it's almost certainly an artifact. The BLAST nucleotide alignment tool won't even try to align that part of the genome with the reference sequence, and Nextclade shows a complex mix of NNN's, insertions, frameshifts, and deletions. <img alt="image" width="299" src="https://user-images.githubusercontent.com/33738461/263093795-0776f239-3055-4b71-8196-49e9b43a94aa.png"> .
> 
> The coverage on the sequences is not good, and there are a lot of mixed nucleotides.
> 
> . <img alt="image" width="911" src="https://user-images.githubusercontent.com/33738461/263094047-82a73244-a63e-4bab-88d8-27a71a0a58b8.png"> .
> 
> There are also an extraordinary number of "reversions," almost certainly all artifactual, including T28271A.
> 
> . <img alt="image" width="1392" src="https://user-images.githubusercontent.com/33738461/263094799-d4f65a40-b16f-4e02-890c-0a8377de7236.png">

Thank you Ryan
