### ISSUE TITLE
NEW FL.1.5 (S:F456L) sublineage with S:481K, S:681R (7) popped up in Uk with a sublineage with S:490P (4)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#614]
Thanks to Dave McNAlly [tool](https://ukcovid.xyz/spike-combo.php?type=multi&mincount=2)
i have been able to identify a FL.1.5 (456L) sublineage of interest not yet on Gisaid.
It has gained first S:481K and S:H681R and then S:F490P plus multiple AA mutations outside the spike.

Tree:
![Schermata 2023-08-15 alle 19 32 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/35c1dd33-cc3b-4d31-b032-ad9b5cb97797)
![Schermata 2023-08-15 alle 19 32 40](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/28b9b780-6cfd-418e-b528-b0920862852e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16506_bb5ea0.json?c=gt-S_481&label=id:node_6825265

Defining mutations:
FL.1.5 (S:F456L) > T23245C > S:N481K (T23005A), S:P681R (A23604G) 
then its sublineage > Orf1a:S723F (C2433T), Orf1a:T4129I (C12651T), S:F490P (T23030C), C26586T

Samples: 6 ( from 3 countries)
USA/NJ-PHEL-V23013054/2023\|OR387029.1\|2023-07-21
France/BRE-IPP16220/2023\|EPI_ISL_18031855\|2023-06-26
England/CLIMB-CM7YJ5Q8/2023\|2023-08-03
England/CLIMB-CM7YGOIF/2023\|2023-07-31
England/CLIMB-CM7YG5DS/2023\|2023-08-03
England/CLIMB-CM7YFJ1W/2023\|2023-08-03

Gisaid query: T23245C ,T23005A
for now it finds just the samples not from UK (2)

**Comment by c19850727** [comment]
One more sequence. EPI_ISL_18114969 from Denmark.

**Comment by FedeGueli** [comment]
> One more sequence. EPI_ISL_18114969 from Denmark.

Has it 490P.too?

**Comment by FedeGueli** [comment]
Now all 7 on Gisaid.

**Comment by FedeGueli** [comment]
Designated FL.1.5.2
