### ISSUE TITLE
FL.4 + S:V1264L, ORF1b:T310I(20seq Spain) + S:S494P(6seq)

### ISSUE THREAD

**Issue by DoropFan** [sars-cov-2-variants/lineage-proposals#616]
Sub-lineage of:FL.4(XBB.1.9.1.4)
Earliest sequence:2023-05-02(Spain)
Most recent sequence:2023-07-20(Spain)
Countries circulating:Spain(19)
Sequences:19

UShER Tree
FL.4>A28615G>G24586A>
C14396T(ORF1b:T310I), G25352T(S:V1264L), T28022C
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25c5e_c1c730.json?c=country&label=id:node_6838322
![FL4+V1264L+S494Pp1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/118802079/52c5c141-3694-4be2-b011-6f3199cebe21)

. + S:S494P
.>T5731C, G2351T(ORF1a:G696C), A28254-(ORF8:I121-)>
G4656A(ORF1a:R1464Q),T23042C(S:S494P),C24058G

CovSpectrum:S:V1264L, ORF1b:T310I
GISAID:C14396T, G25352T
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AV1264L%2CORF1b%3AT310I&nucMutations=G24586A&

Genomes
https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?dateFrom=2023-02-13&dateTo=2023-08-09&aaMutations=S%3AV1264L%2CORF1b%3AT310I&nucMutations=G24586A&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&orderBy=random
EPI_ISL_17985222
EPI_ISL_18008620
EPI_ISL_17638573
EPI_ISL_17949812
EPI_ISL_17985219
EPI_ISL_17838499
EPI_ISL_17680208
EPI_ISL_17726436
EPI_ISL_18008603
EPI_ISL_17812468
EPI_ISL_17980538
EPI_ISL_17985202
EPI_ISL_18044145
EPI_ISL_18056893
EPI_ISL_18044143
EPI_ISL_18044144
EPI_ISL_18044146
EPI_ISL_18044154
EPI_ISL_18044156

**Comment by FedeGueli** [comment]
Closing this for now
