### ISSUE TITLE
FL.21 (or XBB.1.9.1) sublineage with Orf7a:T14I, Orf8:C90S(91 seq, 6 countries) then S:F456L(75 seq, 4 countries) and further S:K478R, P1143S(6 seq, Texas)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#617]
Query: C9166T, A10564T(Edited)
Query for F456L sequences: C9166T, A10564T, T22928C
Query for K478R, P1143S sequences: C9166T, A10564T, C24989T

FL.21> T2845C, C4543T, C9166T, A16431G, C27434T(Orf7a:T14I), T28161A(~Orf8:C90S~)
Or XBB.1.9.1> C27434T(Orf7a:T14I)> T2845C, C4543T, C9166T, A10564T, A16431G, T28161A(~Orf8:C90S~)
Then> C5144T> T22928C(S:F456L)
Then> G15380A(Orf1b:S638N)> A22995G(S:K478R), C24989T(S:P1143S)

Earliest sequence: 04-22 Virginia, USA EPI_ISL_17593231
Earliest sequence with F456L: 06-23 Louisiana, USA EPI_ISL_18053704
Earliest sequence with K478R, P1143S: 08-23 Texas, USA EPI_ISL_18267510
Latest sequences: 09-28 Minnesota, USA EPI_ISL_18389869
\*A sequence from Tennesse was assigned as collected on 01-24, but according to phylogenic tree, its collecting date is probably mislabeled.

Regions detected: **US** 8+**63**(**Texas** 5+**48**, **California** 1+**2**, **Pennsylvania 2**, **Tennesse** 1+**1**, **Virginia** 1+**1**, **Connecticut 1**, **Illinois 1**, **Louisiana 1**, **Minnesota 1**, **Nebraska 1**, **New Jersey 1**, **New York 1**, **North Carolina 1**, **Wisconsin 1**), Spain 3( Andalucia 1, Castilla y Leon 1, Murcia 1), **Japan 3**(**Hokkaido 2**, **Osaka 1**), **Australia 1**(**WA**), **Canada 1**(**Ontario**), UK 1(England)
The number of sequences with F456L is bolded.

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_1644e_1aac30.json?label=id:node_6918650
![2023-09-14 (3)](https://github.com/cov-lineages/pango-designation/assets/38100637/bbb4bfe3-562a-4f9e-bf3e-02493d55e29c)

<details><summary>Sequences:</summary>

EPI_ISL_17593231, EPI_ISL_17806562, EPI_ISL_17808967,
EPI_ISL_17855155, EPI_ISL_17955566, EPI_ISL_17955640,
EPI_ISL_18053704, EPI_ISL_18057201, EPI_ISL_18057212,
EPI_ISL_18069723, EPI_ISL_18072239, EPI_ISL_18076295,
EPI_ISL_18080870, EPI_ISL_18090095, EPI_ISL_18104390,
EPI_ISL_18107733, EPI_ISL_18118197, EPI_ISL_18119619,
EPI_ISL_18119678, EPI_ISL_18119696, EPI_ISL_18119716,
EPI_ISL_18119739, EPI_ISL_18119791, EPI_ISL_18163828,
EPI_ISL_18163946, EPI_ISL_18163973, EPI_ISL_18164002,
EPI_ISL_18164401, EPI_ISL_18164596, EPI_ISL_18210849,
EPI_ISL_18212504, EPI_ISL_18222756, EPI_ISL_18233897,
EPI_ISL_18241729, EPI_ISL_18256236, EPI_ISL_18256260,
EPI_ISL_18256388, EPI_ISL_18264671, EPI_ISL_18266867,
EPI_ISL_18267510, EPI_ISL_18275701, EPI_ISL_18275792,
EPI_ISL_18291668, EPI_ISL_18291720, EPI_ISL_18291727,
EPI_ISL_18308516, EPI_ISL_18310995, EPI_ISL_18316927,
EPI_ISL_18316958, EPI_ISL_18320643, EPI_ISL_18321866,
EPI_ISL_18322215, EPI_ISL_18322228, EPI_ISL_18322313,
EPI_ISL_18322323, EPI_ISL_18322499, EPI_ISL_18322624,
EPI_ISL_18322629, EPI_ISL_18322643, EPI_ISL_18322788,
EPI_ISL_18329058, EPI_ISL_18329074, EPI_ISL_18329594,
EPI_ISL_18329698, EPI_ISL_18340963, EPI_ISL_18341138,
EPI_ISL_18341264, EPI_ISL_18341310, EPI_ISL_18341329,
EPI_ISL_18341359, EPI_ISL_18341361, EPI_ISL_18341369,
EPI_ISL_18341421, EPI_ISL_18342840, EPI_ISL_18344259,
EPI_ISL_18345266, EPI_ISL_18352402, EPI_ISL_18369287,
EPI_ISL_18373125, EPI_ISL_18374778, EPI_ISL_18380359,
EPI_ISL_18380414, EPI_ISL_18380416, EPI_ISL_18386274,
EPI_ISL_18389869
</details>

**Comment by FedeGueli** [comment]
Thx! worth monitoring it closely it resembles the FL.1.5 spike ( didnt look in depth so maybe i m wrong)

**Comment by Over-There-Is** [comment]
> Thx! worth monitoring it closely it resembles the FL.1.5 spike ( didnt look in depth so maybe i m wrong)

It does not have FL.1's A701V mutation.

**Comment by FedeGueli** [comment]
This is going quite well please propose just the 456L branch onve it hits 25 ( i think it will be soon)

**Comment by Over-There-Is** [comment]
Both XBB.1.9.1> C27434T(Orf7a:T14I) and original FL.21 without extra mutation have not been found in USA. But it seems C27434T is much homoplastic, samples with C27434T from several XBB lineages can be found with `A405G, C27434T`. And FL.21 and this sublineage are the only two(one?) lineages with A10564T since 2023-02.

**Comment by Over-There-Is** [comment]
USA/TX-TAMGHRC-SHS_98064/2023 T4543Crev, C5144Y, T22928N
It should be under the C5144T branch, but I don't know whether it have F456L.

**Comment by FedeGueli** [comment]
> Both XBB.1.9.1> C27434T(Orf7a:T14I) and original FL.21 without extra mutation have not been found in USA. But it seems C27434T is much homoplastic, samples with C27434T from several XBB lineages can be found with `A405G, C27434T`. And FL.21 and this sublineage are the only two(one?) lineages with A10564T since 2023-02. So this sublineage is more likely to be a descendant of FL.21. #Tree Unclear#

@angiehinrichs please could you take a look?

**Comment by FedeGueli** [comment]
> > Thx! worth monitoring it closely it resembles the FL.1.5 spike ( didnt look in depth so maybe i m wrong)
> 
> It does not have FL.1's A701V mutation.

**Comment by Over-There-Is** [comment]
There are plenty of sequences with C27434T, including non-XBB.1.9.1 variants.

**Comment by Over-There-Is** [comment]
> This is going quite well please propose just the 456L branch onve it hits 25 ( i think it will be soon)

26 now, transferred to the main page.

**Comment by AngieHinrichs** [comment]
> > Both XBB.1.9.1> C27434T(Orf7a:T14I) and original FL.21 without extra mutation have not been found in USA. But it seems C27434T is much homoplastic, samples with C27434T from several XBB lineages can be found with A405G, C27434T. And FL.21 and this sublineage are the only two(one?) lineages with A10564T since 2023-02. So this sublineage is more likely to be a descendant of FL.21. #Tree Unclear#
> 
> @AngieHinrichs please could you take a look?

Interesting -- it looks separate to me, but I can't tell whether it's homoplasy or recombination or what.  ?

**Comment by Over-There-Is** [comment]
S:F168Y 4seq

**Comment by FedeGueli** [comment]
Hence the 478R branch is dead the 456L lineage cant compete closing it

**Comment by Over-There-Is** [comment]
11-24 Hokkaido

**Comment by FedeGueli** [comment]
Wow it is stille around!  too slow to reopen it tough

**Comment by Over-There-Is** [comment]
Japan/PG-587309/2023|EPI_ISL_18740786|2023-12-23 Kanagawa, Japan

**Comment by FedeGueli** [comment]
> C9166T, A10564T, T22928C

Thx for tracking this one. which is your query for 456L? i would exclude 478R from the proposal tough cause likely comopletely dead
