### ISSUE TITLE
XBB.1.5 with ORF1a:K2143R (nsp3_K1325R), ORF7a:S81L, and S:T478R (60 seqs, USA, UK, Netherlands, Jamaica where it represents 20% of samples after July 1)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#618]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `A6693G(ORF1a:K2143R)` > `C27635T(ORF7a:S81L)` > `C22995G(**S:T478R**)`
**Query:** `A6693G, C22995G, C27635T`
**Earliest seq:** 2023-03-15 (`EPI_ISL_17304959`, Houston, Texas, USA)
**Latest seq:** 2023-08-01 (`EPI_ISL_18098838`, Houston, Texas, USA)
**Sampled Countries:** USA (33: Texas/14; New York/9; Colorado/3; Florida/3; California/1; Georgia/1, ex: Jamaica; Maryland/1; Pennsylvania/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17304959, EPI_ISL_17486005, EPI_ISL_17535216, EPI_ISL_17621352, EPI_ISL_17763795, EPI_ISL_17852435, EPI_ISL_17852922, EPI_ISL_17854238, EPI_ISL_17955508, EPI_ISL_17955515, EPI_ISL_17955595, EPI_ISL_17955646, EPI_ISL_17955715, EPI_ISL_17955719, EPI_ISL_17955929, EPI_ISL_17955952, EPI_ISL_17955985, EPI_ISL_17971859, EPI_ISL_17986385, EPI_ISL_17992027-17992028, EPI_ISL_17992034-17992035, EPI_ISL_18053937, EPI_ISL_18054683, EPI_ISL_18057598, EPI_ISL_18090205, EPI_ISL_18093371, EPI_ISL_18093580, EPI_ISL_18093725, EPI_ISL_18098838, EPI_ISL_18098989, EPI_ISL_18099255`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1116f_c81980.json?f_userOrOld=uploaded%20sample&label=id:node_7116487
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/3386ec99-187d-4568-85ea-184a3aab5988)

**Comment by FedeGueli** [comment]
Growth tracker: https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A6693G%2CC22995G%2CC27635T&analysisMode=CompareToBaseline& 

it cant compete.

**Comment by FedeGueli** [comment]
Cant copete closing it : https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A6693G%2CC22995G%2CC27635T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
monitor it for a bit further it is around 20% of Jamaican samples.

**Comment by FedeGueli** [comment]
Too slow to track further.
