### ISSUE TITLE
XBB.1.5 (or XBB.1.5.49) with ORF1b:T17I (nsp12_T26I), S:T478R, ORF3a:T89I and ORF3a:D222Y (33 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#619]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `C13517T(ORF1b:T17I)` > `T6886C, C29272T, A29687G` > `A4987G` > **_`T10204C`_** > `C22995G(S:T478R), C25658T(ORF3a:T89I), G26056T(ORF3a:D222Y)`
**Query:** `C22995G, C25658T, G26056T`
**Earliest seq:** 2023-03-26 (`EPI_ISL_17477445`, Texas, USA)
**Latest seq:** 2023-08-03 (`EPI_ISL_18098719`, Texas, USA)
**Sampled Countries:** USA (11: Texas/8; California/3), Guatemala (4), Mexico (2), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17477445, EPI_ISL_17486466, EPI_ISL_17486557, EPI_ISL_17655243, EPI_ISL_17744474, EPI_ISL_17789161, EPI_ISL_17789225, EPI_ISL_17833814, EPI_ISL_17853520, EPI_ISL_17954110, EPI_ISL_17954612, EPI_ISL_18010405, EPI_ISL_18070977, EPI_ISL_18098604, EPI_ISL_18098641, EPI_ISL_18098719, EPI_ISL_18098799, EPI_ISL_18099267`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d30b_c875e0.json?f_userOrOld=uploaded%20sample&label=id:node_7146279
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/45201fc1-906c-4ad3-b696-b3c60c5f3dff)

**UShER:**
- Identified by GISAID/nextclade as XBB.1.5.49, probably due to `T6886C` and `T10204C`. Need help to check if this is another sub-branch of XBB.1.5.49 with `S:T478R` misplaced with some drop-out cluster. Previously stated in #451 [comment](https://github.com/sars-cov-2-variants/lineage-proposals/issues/451#issuecomment-1671161285) , recently add up a few more sequences.

**Comment by FedeGueli** [comment]
Very wierd what is hapening in XBB.1.5.49 and 478R.

**Comment by AngieHinrichs** [comment]
Yep, probably, I'll add it to the list for the next round of fixing, thanks @NkRMnZr.

**Comment by FedeGueli** [comment]
i leave this open fro a whilel with the assumption it is circulating in mexico/guatemala undersampled are.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs can you check if this is another misplaced XBB.1.5.49 branch?

It has T6886C, but also other credible mutations first... homoplasy/recombination??

**Comment by FedeGueli** [comment]
Hard it could compete anymore: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C22995G%2CC25658T%2CG26056T&analysisMode=CompareToBaseline& but still the MExico +478R thing is to be tracked.

**Comment by FedeGueli** [comment]
Just two samples in september closing this
