### ISSUE TITLE
XBB.1.5 (T10204C) with ORF1a:A4357V (nsp10_A104V), ORF1a:T1001I (nsp3_T183I) and S:T478R (29 seqs, 7 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#620]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C > T10204C]` > `C13335T(ORF1a:A4357V)` > `C3253T, C3267T(ORF1a:T1001I), C8290T, A14373G, C19524T, C22995G(**S:T478R**), C28732T`
**Query:** `C3267T, C22995G, C28732T`
**Earliest seq:** 2023-05-16 (`EPI_ISL_17716833`, `IAD`, Virginia, USA, unknown travel history)
**Latest seq:** 2023-08-05 (`EPI_ISL_18094995`, New York, USA)
**Sampled Countries:** USA (4: CA; NY; TX; VA), Mexico (3), Canada (2), China (1, Guangdong, unknown travel history), Greece (1), Mauritius(1)

<details><summary>Genomes: </summary>

`EPI_ISL_17716833, EPI_ISL_17763791, EPI_ISL_17832094, EPI_ISL_17994140, EPI_ISL_18036615, EPI_ISL_18053149, EPI_ISL_18074077, EPI_ISL_18079593, EPI_ISL_18094995, EPI_ISL_18096568, EPI_ISL_18103782, EPI_ISL_18105008`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32c8b_c92330.json?f_userOrOld=uploaded%20sample&label=id:node_6963910
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6197d759-c01d-42dd-8b6a-588f3569d1c8)

**Comment by FedeGueli** [comment]
This belongs to that weird lineages with very few sequences and multiple continents already reached.. lets see if the lae July trend of increased circualtion keeps on showing up.

**Comment by FedeGueli** [comment]
Slow but likely circulating in Mexico,
