### ISSUE TITLE
XBB.1.5 (pre-T17124C) with ORF1a:T4129I and S:T573I (65 seqs, mainly in USA, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#621]
**Defining Mutations:** `XBB.1.5 [pre-T17124C]` > `C12651T(ORF1a:T4129I)` > `A5116G` > `C23280T(**S:T573I**)`
**Query:** `A5116G, C12651T, C23280T`
**Earliest seq:** 2023-03-28 (`EPI_ISL_17412081`, California, USA)
**Latest seq:** 2023-07-28 (`EPI_ISL_18078835`, Arizona, USA)
**Sampled Countries:** USA (56: California/49; Arizona/4; Colorado/1; New Mexico/1; Nevada/1), Spain (2, Canary Islands), Japan (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17412081, EPI_ISL_17486904, EPI_ISL_17582593, EPI_ISL_17694105, EPI_ISL_17767930, EPI_ISL_17783184-17783185, EPI_ISL_17783441, EPI_ISL_17791528, EPI_ISL_17815322, EPI_ISL_17854153, EPI_ISL_17856443, EPI_ISL_17856775, EPI_ISL_17887178, EPI_ISL_17951107, EPI_ISL_17965297-17965300, EPI_ISL_17965688, EPI_ISL_17976661, EPI_ISL_17977777, EPI_ISL_17981054, EPI_ISL_17986245, EPI_ISL_17997618, EPI_ISL_17997626, EPI_ISL_17997628, EPI_ISL_17997634, EPI_ISL_17997641, EPI_ISL_17997981, EPI_ISL_17997983, EPI_ISL_17997985, EPI_ISL_17997988, EPI_ISL_17997991, EPI_ISL_18043211, EPI_ISL_18045413, EPI_ISL_18046102, EPI_ISL_18046135, EPI_ISL_18050227-18050228, EPI_ISL_18050241, EPI_ISL_18078835, EPI_ISL_18079296, EPI_ISL_18079450, EPI_ISL_18079462, EPI_ISL_18079480, EPI_ISL_18079543, EPI_ISL_18079590, EPI_ISL_18079809, EPI_ISL_18079892, EPI_ISL_18080010, EPI_ISL_18080631, EPI_ISL_18080758, EPI_ISL_18081422, EPI_ISL_18093562, EPI_ISL_18105265-18105267, EPI_ISL_18106318`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41f46_c9a1c0.json?f_userOrOld=uploaded%20sample&label=id:node_6874732

- view from `ORF1a:T4129I` branch
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/914d07b5-7007-4e87-9ab0-eb8633912bb7)

- details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/07dc29e1-e010-4bc0-b97a-91efacd2b2be)

**Trivia:**
- At the moment, all XBB.1.5 `pre-T17124C` has been misplaced under `XBB.1.22` > `C28297T_reversion (ORF9b:T5I_reversion)`

**Comment by FedeGueli** [comment]
Interesting but it will have hard life from now ahead: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A5116G%2CC12651T%2CC23280T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=A5116G%2CC12651T%2CC23280T&analysisMode=CompareToBaseline& 

closing this for now.
