### ISSUE TITLE
XBB.1.5.10 with S:S939F and ORF1b:S1985L then mini-saltation with 3 ORF1ab aa mutations and S:Q675H (40 seqs, Canada and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#622]
**Defining Mutations:** `XBB.1.5.10` > `C24378T(S:S939F)` > `C19421T(ORF1b:S1985L/nsp14_S461L)` > `T10192C` > `T5619C(ORF1a:I1785T/nsp3_I967T), C7299T(ORF1a:A2345V/nsp3_A1527V), C17036T(ORF1b:A1190V/nsp13_A267V), C19983T, G23587C(S:Q675H)`
**Query:** `C18395T, G23587C, C24378T`
**Earliest seq:** 2023-05-28 (`EPI_ISL_17971455`, North Carolina, USA)
**Latest seq:** 2023-08-11 (`EPI_ISL_18124363`, Ontario, Canada)
**Sampled Countries:** Canada (24, Ontario), USA (5: North Carolina/2; New Jersey/1; New York/1; Puerto Rico/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17854356, EPI_ISL_17971455, EPI_ISL_17971474, EPI_ISL_17986247, EPI_ISL_18090727, EPI_ISL_18105035, EPI_ISL_18105094-18105097, EPI_ISL_18105099, EPI_ISL_18105128, EPI_ISL_18105156-18105163, EPI_ISL_18105174-18105175, EPI_ISL_18124288, EPI_ISL_18124361, EPI_ISL_18124363, EPI_ISL_18124387, EPI_ISL_18124399-18124400, EPI_ISL_18124402`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17d98_b260c0.json?label=id:node_7203061
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ead94b5e-8a44-48c4-9625-4a3df3a2da9c)

**Trivia:**
- Could be just Canadian batch thing, or boosted by a sub-branch with `S:Q675H`.

**Comment by FedeGueli** [comment]
i ve noticed too the further branch with 675. lets see if it is not the usual canadian cluster.

**Comment by FedeGueli** [comment]
Please restrict the proposal to the S:Q675H branch that seems growing faster (although could be the usual canadian effect)-

**Comment by FedeGueli** [comment]
likely the usual canadian cluster who fools us everytime.
