### ISSUE TITLE
HR.1 (XBB.1.5.77.1 with S:478R) sublineage with S:K304N (250 seqs in 13 countries ) 20% prevalence in Costa Rica

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#623]
Defining mutations:
HR.1>C27005T>G9203A (ORF1a:D2980N)>T15717C>C27881T>A22474C (S:K304N)
GISAID query: T15717C, A22474C,A29147G
Earliest seq: 2023-07-05 (US- EPI_ISL_18022790)
Most recent seq: 2023-07-30 (Italy- EPI_ISL_18064404)
Countries detected: Canada (6), Australia (5), US (3) 

Usher Tree:
<img width="704" alt="屏幕截图 2023-08-16 184838" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/6b77cdd4-dd39-42c8-9110-85608cabcd72">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15c02_ca7580.json?c=gt-S_304

S:K304N is popular in HF.1 (XBB.1.16.13.1) recently. 

Genomes:
EPI_ISL_18037184, EPI_ISL_18057049, EPI_ISL_18057638, EPI_ISL_18060341, EPI_ISL_18060349, EPI_ISL_18060390,
EPI_ISL_18060426, EPI_ISL_18073945, EPI_ISL_18093873, EPI_ISL_18098935, EPI_ISL_18105091, EPI_ISL_18105138,
EPI_ISL_18105141, EPI_ISL_18105198

**Comment by FedeGueli** [comment]
This likely is circulating somewhere. it is doubling very fast and  it is already spread in 3 continents ( assuming your Italy sample from Usher) . It could be COlombia where XBB.1.5.77 was very high or Costarica where likely HR.1 emerged.
Still the combo 478+304N seems going well. lets see

**Comment by ryhisner** [comment]
I would propose the wider ORF1a:D2980N / NSP4_D217N branch. It's bigger and has been growing for a much longer period of time, and D2980N is a significant mutation often seen in chronic-infection sequences. This lineage is probably going nowhere if it doesn't add F456L or FLip, but if it picks up FLip, look out. It seems to combine a lot of non-spike mutations that are probably modestly beneficial. 
<img width="1452" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/4f3cc83a-f899-432c-a28a-2352de73a986">

**Comment by FedeGueli** [comment]
@HynnSpylor what about proposing in the main page with the split between parent and sublineage of interest as proposed by @ryhisner ?

**Comment by HynnSpylor** [comment]
Agree @FedeGueli 
I suggest @ryhisner to propose the whole branch in main page and cite it when mention the S:K304N sublineage

**Comment by FedeGueli** [comment]
pls @ryhisner go!

**Comment by FedeGueli** [comment]
i see 32 now with 304N  doubling in line with dominant lineages. @ryhisner would you like to propose it?

**Comment by ryhisner** [comment]
No, I'm really pressed for time right now. One of you guys should propose it.

**Comment by FedeGueli** [comment]
Lets wait a bit more i suspect it is slowing down.

**Comment by FedeGueli** [comment]
Thi went back to some speed expanding geographically and numerically. Propose in the main page and let @corneliusroemer decide about it.

**Comment by FedeGueli** [comment]
This is not slow, please propose it :https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T15717C%2CA22474C%2CA29147G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@HynnSpylor

**Comment by FedeGueli** [comment]
@HynnSpylor now 240 please propose it!

**Comment by FedeGueli** [comment]
This has reached 20% in Costa Rica recently please propose it.

**Comment by FedeGueli** [comment]
BTW tree showing itneresting further spike diversity with 780D 716I 259I  https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_58755_1df950.json?label=id:node_3907699 cc @corneliusroemer

**Comment by HynnSpylor** [comment]
Thx @FedeGueli! I'm back now and will propose it on main page

**Comment by FedeGueli** [comment]
Designated HR.1.1 via https://github.com/cov-lineages/pango-designation/commit/8844830153e19a226146bc70f9c7d63808ae8f37
