### ISSUE TITLE
XBB.1.5.70 with ORF1a:A876S (nsp3_A58S) and S:A475V (14 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#624]
**Defining Mutations:** `XBB.1.5.70` > `G2891T(ORF1a:A876S), C12469T` > `C22986T`(**S:A475V**)
**Query:** `C12469T, C22986T`
**Earliest seq:** 2023-07-11 (`EPI_ISL_18069791`, California, USA)
**Latest seq:** 2023-08-02 (`EPI_ISL_18104829`, Illinois, USA)
**Sampled Countries:** USA (14: New York/7, 2 ex. Czech; California/3; Illinois/2; North Carolina/1; Rhode Island/1)

<details><summary>Genomes: </summary>

`EPI_ISL_18049215, EPI_ISL_18049325, EPI_ISL_18049939, EPI_ISL_18057888, EPI_ISL_18057920, EPI_ISL_18057997, EPI_ISL_18065604, EPI_ISL_18069791, EPI_ISL_18069862, EPI_ISL_18072270, EPI_ISL_18080146, EPI_ISL_18080799, EPI_ISL_18104464, EPI_ISL_18104829`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_95cd_ca7be0.json?f_userOrOld=uploaded%20sample&label=id:node_7086216

view from XBB.1.5.70 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/83c42ec7-dcb2-4150-a071-20c01643cc18)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d552b4b0-2c76-411c-b0f6-bf0e3f453884)

**Trivia:**
- `S:A475V` is expected by Bloom et al. to be moderate costly at fitness and binding affinity, but can provide some kind of immune escape.
![475](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e4056907-06ea-4928-87cf-228b7e489625)
- The XBB.1.5.70 (flip mutation combo) _impersonator_ proposed cov-lineages/pango-designation#2071 also got `S:A475V`, coincidence or some kind of new pattern?

**Comment by FedeGueli** [comment]
Did u check this is not GK.3.1?

**Comment by FedeGueli** [comment]
No bad!
