### ISSUE TITLE
EG.2 (478R) with N:T24I and S:Q52H (19 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#625]
**Defining Mutations:** `EG.2` > `C28344T`(**N:T24I**) > `A17757G` > `G21718T`(**S:Q52H**)
**Query:** `A17757G, G21718T, C28344T`
**Earliest seq:** 2023-05-07 (`EPI_ISL_17729528`, East Kalimantan, Indonesia)
**Latest seq:** 2023-07-31 (`EPI_ISL_18094727`, Dordogne, France)
**Sampled Countries:** Canada (4), France (4), Brunei (2), Malaysia (2), Indonesia (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17729528, EPI_ISL_17736251, EPI_ISL_17814617, EPI_ISL_17856269, EPI_ISL_17856341, EPI_ISL_17884326, EPI_ISL_18005417, EPI_ISL_18037465, EPI_ISL_18037471, EPI_ISL_18076116, EPI_ISL_18094727, EPI_ISL_18100721, EPI_ISL_18100738`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2abae_cb9510.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2581ccac-8b58-4199-9c3e-e54dbd14b76d)

**Trivia:**
- `S:Q52H` seems to be a proven winner on EG.5.1, but how does it work with `S:T478R` (EG.2)?

**Comment by FedeGueli** [comment]
to me this is slow. lets see
