### ISSUE TITLE
XBB.1.9.1 with N:P122S and S:T76I (30 seqs, mainly in Japan, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#626]
**Defining Mutations:** `XBB.1.9.1` > `C28637T`(**N:P122S**) > `C11020T` > `T29131C` > `C21789T`(**S:T76I**)
**Query:** `C11020T, C21789T, C28637T`
**Earliest seq:** 2023-06-01 (`EPI_ISL_17952661`, Hiroshima, Japan)
**Latest seq:** 2023-07-21 (`EPI_ISL_18101037`, Kagoshima, Japan)
**Sampled Countries:** Japan (24), USA (2, California, ex. Japan), China (1, Shanghai, ex. Japan)

<details><summary>Genomes: </summary>

`EPI_ISL_17950309, EPI_ISL_17950372, EPI_ISL_17952661, EPI_ISL_17952663, EPI_ISL_17956852, EPI_ISL_17978057, EPI_ISL_17978796, EPI_ISL_17979662, EPI_ISL_17980747, EPI_ISL_17982136, EPI_ISL_17996455, EPI_ISL_18000614, EPI_ISL_18006556, EPI_ISL_18040754, EPI_ISL_18040801, EPI_ISL_18051328, EPI_ISL_18051992, EPI_ISL_18065192, EPI_ISL_18071779, EPI_ISL_18100464, EPI_ISL_18100890, EPI_ISL_18101002, EPI_ISL_18101037, EPI_ISL_18101050, EPI_ISL_18101139, EPI_ISL_18101159, EPI_ISL_18101166`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36d69_cbf9e0.json?f_userOrOld=uploaded%20sample&label=id:node_6774421
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/07e4c1cf-9cf6-4126-9d92-c457729cfb4d)

**Trivia:**
- `S:T76I` is the definition of `BA.5.5` and `HU.2 (XBB.1.22.2.2)`

**Comment by FedeGueli** [comment]
It cant compete : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C11020T%2CC21789T%2CC28637T&analysisMode=CompareToBaseline& 
i am closing it.
