### ISSUE TITLE
FE.1.1 with S:L455F (7 seqs, China, UK)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#627]
**Defining Mutations:** `FE.1.1` > `G22927T`(S:L455F)
**Query:** `T4579A, G22927T, C28093T, -A2109G, -A24775G`
**Earliest seq:** 2023-06-26 (`EPI_ISL_18105360`, Jiangsu, China)
**Latest seq:** 2023-07-31 (`EPI_ISL_18097768`, England, UK)
**Sampled Countries:** China, UK

<details><summary>Genomes: </summary>

`EPI_ISL_18097768, EPI_ISL_18105360`
</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_39d9c_741890.json?label=id:node_3541731
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/51c06d89-e83f-4e77-9ca3-258494c63891)

**Comment by FedeGueli** [comment]
+1 Uk

**Comment by FedeGueli** [comment]
I think this has few chance to survive. lets close it
