### ISSUE TITLE
FL.1.5.1 x BQ.1.2.2 Recombinant, 6 seqs, Nigeria and US-TX

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#630]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/a43e4d64-9f5d-482c-82cc-66ae7445d46b)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f3b7_e4b1b0.json?c=gt-ORF8_90&label=id:node_6930474

**Query**: G3242A, C28163A
**Earliest sequence**: EPI_ISL_18110467, 2023-07-20, Nigeria
**Most recent sequence**: EPI_ISL_18098706, 2023-08-04, US-TX

Breakpoint is likely somewhere between nuc 23665 (spike 701) and 25415 (ORF3a 8). Everything upstream is from a FL.1.5.1 donor, and everything from 25416 to 3' is from BQ.1.2.2 donor.

**Unique AA changes from BQ.1.2.2**: ORF3:255/258del, ORF8:C90stop

**Sequences**: EPI_ISL_18098706, EPI_ISL_18110467, EPI_ISL_18110470

**EDITED** i (F) add a rapid portrait of this recombinant
![Schermata 2023-08-23 alle 16 12 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f8725a4f-12b7-4580-a1e1-df8174ea740f)

**Comment by FedeGueli** [comment]
Great catch Saka it is a FL.1.5 spike (with Orf1b:2557) that got rid of E:11 Orf6:61 putative attenuating mutations and orf8:8* but orf8 expression is severely ablated by 27889 . and also truncated by orf8:90* .

So coming from an undersampled area is something to track  closely i think it should be proposed if reaches 10 in the next two weeks.

**Comment by FedeGueli** [comment]
designated XCK via https://github.com/cov-lineages/pango-designation/commit/474997486d4668327e987801711728e0b901bd43
