### ISSUE TITLE
HK.1+Orf1a:V2019I+S:T307I,L455F (41 seqs, 5 countries 4% in NZL 4% Xinjiang)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#631]
HK.1+G6320A(Orf1a:V2019I)+C11704T,C22482T,G22927C(S:T307I,L455F)

GISAID query: C11704T,C22482T,G22927C
No. of seqs: 2(Xinjiang)
EPI_ISL_18108848, 2023-7-4
EPI_ISL_18108876,2023-7-18

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e562_e63370.json?branchLabel=Spike%20mutations&label=id:node_10742083&showBranchLabels=all)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c59cf7ee-8967-4b38-9142-5dd2ace7200b)

**Comment by FedeGueli** [comment]
Thx

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by aviczhl2** [comment]
+2 New Zealand

**Comment by aviczhl2** [comment]
+1 UK-CLIMB seq

**Comment by FedeGueli** [comment]
New batch from New Zealand where it appears to be at 3%

**Comment by FedeGueli** [comment]
new upload from XInjiang

**Comment by aviczhl2** [comment]
> new upload from XInjiang

7/101=7%

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by aviczhl2** [comment]
11/255 in the recent New Zealand batch.

**Comment by FedeGueli** [comment]
Thank you for tracking propose it.

**Comment by FedeGueli** [comment]
Designated HK.1.2 from https://github.com/cov-lineages/pango-designation/commit/2ee937ccb13e3ee615171bdf04dde0ebf453807a
