### ISSUE TITLE
New EG.5+Orf1a:Q990R,Orf1b:S2212I, S:Q14K,A522P in China(21 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#632]
EG.5+A3234G, G20102T, A20532G, G23126C,T9622C, C21602A (Orf1a:Q990R,Orf1b:S2212I, S:Q14K,A522P)

GISAID query:G23126C,C21602A,A20532G
No. of seqs:10 (9 Shanghai, 1 USA)
First: EPI_ISL_17994570, Shanghai, 2023-7-5
Latest: EPI_ISL_18108392, Shanghai, 2023-8-2

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41dcf_e7d5b0.json?label=id:node_6902427)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/69df9a85-a645-4744-bb2d-7fa2fd61488b)

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by FedeGueli** [comment]
Please propose it
