### ISSUE TITLE
HS.1 (XBB.1.5.95+S:T478R) with S:F456L (17 seqs, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#633]
**Defining Mutations:** `HS.1` > `T10084A` > `C6628T` > `C10252T, T22928C(S:F456L), G28077T(ORF8:V62L)`
**Query:** `C10252T, T22928C, G28077T`
**Earliest seq:** 2023-05-30 (`EPI_ISL_17985957`, Puerto Rico)
**Latest seq:** 2023-08-04 (`EPI_ISL_18110544`, Mississippi)
**Sampled Countries:** USA(14: Texas/7; Mississippi/5; Puerto Rico/2)

<details><summary>Genomes: </summary>

`EPI_ISL_17856278, EPI_ISL_17985957, EPI_ISL_18057331, EPI_ISL_18057336, EPI_ISL_18057506, EPI_ISL_18059619, EPI_ISL_18099024, EPI_ISL_18099037, EPI_ISL_18104808, EPI_ISL_18104885, EPI_ISL_18107764, EPI_ISL_18110481, EPI_ISL_18110498, EPI_ISL_18110544`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33897_e8b110.json?c=gt-S_456&label=id:node_7236260
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/49b2565c-9cf4-45b9-bdd2-78049a83bc91)

**Trivia:**
- `HS.1` now sits on `nuc 15888 C/T` flip-flop branches of `XBB.1.5.95` which is omitted in defining mutations listed above.

**Comment by FedeGueli** [comment]
Please propose it when it reaches 25

**Comment by FedeGueli** [comment]
Designated HS.1.1 via https://github.com/cov-lineages/pango-designation/commit/acf9ccca72216e7d139f97b73f1a895e13070595
