### ISSUE TITLE
AY.122 Saltation Lineage, 14 spike mutations (2 seq, different patients, Russia, Aug 17)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#634]
**Description**
**Sub-lineage of:** AY.122
**Earliest sequence:** 2023-7-5, Russia, Primorsky Krai, Vladivostok — EPI_ISL_18111021       
**Most recent sequence:** 2023-7-13, Russia, Primorsky Krai, Vladivostok — EPI_ISL_18111020
**Countries circulating:** Russia (2)
**Number of Sequences:** 2
**GISAID AA Query:** NSP9_T24N, NSP10_C103G, NSP12_D879G
**GISAID Nucleotide Query:** A5181C, T11543C, C12141T, C12756A, T13331G
**CovSpectrum Query:** Nextcladepangolineage:AY.122 & S:F486A & S:K417N
**Substitutions/Deletions on top of AY.122:**
**Spike:** P25L, H66Y, ∆243-244, ∆A372, K417N. S477N, K478T (R), E484Q, F486A (2-nuc), N501T, G885A, S939F, G946R, H1101Q
**N:** P13L
**ORF3a:** L65P, W131L, G172C, Q213K
**ORF7a:** A82V (Reversion)
**ORF8:** I9V, Q18*
**ORF9b:** P10S
**ORF1a:** E102K, N267S, T1322I, D1639A, A2139V, F3760L, T3959I, T4164N, C4356G
**ORF1b:** D870G, Q2070R, A2480S
**Nucleotide Substitutions:** G569A, A1065G, G1408A, C4230T, A5181C, C6681T, T11543C, C12141T, C12756A, T13331G, A16076G, A19676G, A20832T, G20905T, C21636T, C21758T, G22813T, G22992A, A22995C (Reversion), G23012C, T23018G, T23019C, A23064C, C24378T, G24398C, C24865G, T25586C, G25784T, A25755T, G25906T, C26029A, C27638T (Reversion), A27918G, C27945T, C28311T
**Nucleotide Deletions:** ∆22289-22294, ∆22674-22676

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/AY.122__Russia__2_seq_2023-7-13.json?c=gt-S_478&label=id:node_10741278 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/AY.122__Russia__2_seq_2023-7-13.json 
 
<img width="1337" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/835c1e7f-a7db-4766-92c5-7652fe829c9d">

**Evidence**
The metadata indicate these sequences come from two different patients, one of whom was hospitalized. Both are from Vladivostok, Russia. They differ by several mutations, though some of these differences could be due to lack of coverage. 

EPI_ISL_18111020 is about 4% NNN's and, in addition to the shared mutations listed above, has S:G885A, M:L29F, ORF1a:G2207C, and ORF1a:N3168D (G6884T, A9767G, G24216C, C26607T).

EPI_ISL_18111021 is about 8.5% NNN's and, in addition to the shared mutations listed above, has S:143-144del, S:Q484R, S:D936H (∆22289-22294, A23013G, G24368C).

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18111020, EPI_ISL_18111021
</details>

**Comment by ryhisner** [comment]
This may not be relevant at all, but Vladivostok is very close to North Korea. 
<img width="1042" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/08b56af9-5d68-4412-bbe0-71977bc23ed2">

**Comment by HynnSpylor** [comment]
Ah I also notice it!
the connection between NK and Russia is also limited. Maybe we can also track the seqs from Northeastern China

**Comment by aviczhl2** [comment]
> Ah I also notice it! the connection between NK and Russia is also limited. Maybe we can also track the seqs from Northeastern China

Unfortunately, the last Jilin seq was sequenced in 2023-3-21. About half a year without any seqs.

**Comment by Over-There-Is** [comment]
Jewish Autonomous Oblast and Amur Oblast seem stopped sequencing, and Amur Oblast and Khabarovsk Krai did not upload sequences in this batch. In this batch, 5 sequences from Primorsky Krai are uploaded, all of them are from Vladivostok and 2 of them are collected in July, and both these 2 are AY.122.

**Comment by MCB6** [comment]
The RII team hopes to sequence additional samples from Vladivostok in the next 10 to 15 days. It's just hard to procure enough samples for a batch size commensurate with the sequencer capacity.

**Comment by ryhisner** [comment]
Thank you for the information @MCB6! Very much appreciated.

**Comment by georgimarinov** [comment]
That's a lot of S2 mutations in an interesting region. One has to wonder what effect those have...

**Comment by FedeGueli** [comment]
We were lucky it seems dead.

**Comment by MCB6** [comment]
The finally posted 47 September-October genomes from Vladivostok, Russia. No AY.122's phew
<img width="537" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/93294184/0875038d-c200-4ec1-84e3-ca7c718085be">
