### ISSUE TITLE
HW.1 (XBC.1.6.3.1) sublineage with S:N417S (6 seqs in SA, Australia)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#636]
Defining mutations:
HW.1>C29445T (N:T391I)>A2176G>T13333C>C13499T (ORF1b:T11I), A22812G (S:N417S), T24634A
GISAID query: T13333C, A22812G, T24634A
Earliest seq: 2023-07-19 (SA, Australia- EPI_ISL_18109334)
Most recent seq: 2023-08-02 (SA, Australia- EPI_ISL_18109532)
Countries detected: Australia (6)

Usher Tree:
<img width="903" alt="屏幕截图 2023-08-18 140242" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/82efd98d-e6ad-4f84-a0d8-8c9a9453a9cd">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_352de_f071f0.json?c=gt-S_417

Another choice for S:K417. now almost seqs are K417N and K417T once emerged in Gamma and some BA.2 lineages (as BA.2.18, BA.2.38). However, the S:K417S is relatively rare. 

XBC.1.6.3 is still circulating and evolving. It can be tracked for a time.

Genomes:
EPI_ISL_18109314-18109315, EPI_ISL_18109334, EPI_ISL_18109338, EPI_ISL_18109526, EPI_ISL_18109532

**Comment by FedeGueli** [comment]
Good catch 417S was in EK.1 i think a xbb.1.5 from.Austria that didnt take off after a fast start

**Comment by FedeGueli** [comment]
no new seqs closing this for now.
