### ISSUE TITLE
Sublineage of FY.6 or Recombinant mentioned in pango #2191 with S:ins247SLQGN (35 seqs mainly in Japan)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#637]
Defining mutations:
FY.6> C2935T>T17124C (Maybe Recombinant in https://github.com/cov-lineages/pango-designation/issues/2191) >T11269C>G25699A (ORF3a:A103T)>C9693T (ORF1a:A3143V)  (Usher does not show the insertion)
GISAID query: ins22303T, A22161G, T28297C
Earliest seq: 2023-07-05 (Japan- EPI_ISL_18040442)
Most recent seq: 2023-08-04 (Japan- EPI_ISL_18111918)
Countries detected: Japan (6)

Usher Tree:
<img width="718" alt="屏幕截图 2023-08-18 180849" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/b92d9e8e-ec77-4c28-ba3e-0e2d38548f72">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_348fe_f40e30.json?c=gt-nuc_9693

An interesting insertion on NTD. It has circulated in Japan for a month.
<img width="271" alt="屏幕截图 2023-08-18 181033" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/c9544b95-fb1f-4466-9a8e-7d71eee6a000">

Genomes:
EPI_ISL_18040442, EPI_ISL_18081996, EPI_ISL_18082406, EPI_ISL_18097510, EPI_ISL_18100685, EPI_ISL_18111918,

**Comment by ryhisner** [comment]
I saw a few of these last week, and was surprised to see that one of the insertions had already acquired a mutation. Instead of ins247_SLQGN, it has ins247_SFQGN, if I remember right. 
It looks like there are now two sequences with SFQGN, one from Gunma and one from Kumamoto. EPI_ISL_18081996, EPI_ISL_18111918

**Comment by FedeGueli** [comment]
> I saw a few of these last week, and was surprised to see that one of the insertions had already acquired a mutation. Instead of ins247_SLQGN, it has ins247_SFQGN, if I remember right. It looks like there are now two sequences with SFQGN, one from Gunma and one from Kumamoto. EPI_ISL_18081996, EPI_ISL_18111918

Oh is this that one? good catch

**Comment by FedeGueli** [comment]
In the meanwhile this went to 12. all from Jap

**Comment by FedeGueli** [comment]
27 now propose it once it gets to 50

**Comment by FedeGueli** [comment]
I think as all the other XBB.1.22.1 at the moment it cnnot compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=A22161G%2CT28297C&aaInsertions1=ins_S%3A246%3ASLQGN&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
closing it for now
