### ISSUE TITLE
FL.13+Orf1a:P1659L (=PLPro_P96L) +S:K182E+S:F456L(16 seqs, 7 countries) with a sub-branch of interest with S:Q14H, S:E484K (10 Seqs-6 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#638]
FL.13+C5241T(Orf1a:P1659L)+A22106G(S:K182E)+C12499T+T22928C(S:F456L)

GISAID query: C12499T,T22928C,C5241T
No. of seqs: 6(Pakistan 1 China 5)

First: EPI_ISL_17690187, Pakistan, 2023-5-10
Latest: EPI_ISL_18111165, China, 2023-8-4

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice26_genome_3ff57_f45550.json?label=id:node_6869894)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/08c0bfed-b180-4e63-8303-053a12ed5a47)

*******************

**With a further saltation sublineage of potential interest:** (Spotted by @HynnSpylor and @NkRMnZr )
**Defining mutations:**
FL.13 >C5241T(Orf1a:P1659L)>A22106G(S:K182E)>C12499T>T22928C(S:F456L)>G3994T, A15489G > T3160C, G8027C (Orf1a:V2588L), T11522G (Orf1a:F3753V), A15847T (Orf1b:T794S),  G21604C (S:Q14H), G23012A (S:A484K)
**Tree:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5c98f_64a240.json?label=id:node_3319680
![Schermata 2023-10-11 alle 09 11 45](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/13cd6336-1fc9-4ff5-bfb9-82ebbc5b5d4f)

**Query**:T3160C, G8027C, T11522G

**Samples** : 8
EPI_ISL_18128337, EPI_ISL_18263831-18263832, EPI_ISL_18266417,
EPI_ISL_18324791, EPI_ISL_18355852, EPI_ISL_18366733,
EPI_ISL_18366783

**Countries**: England, US, Qatar, Singapore and Georgia

**Comment by aviczhl2** [comment]
+1 Qatar

**Comment by FedeGueli** [comment]
Also considering N:N140Y is beneficial this has to be watched closely. 
![Schermata 2023-08-25 alle 15 17 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/5ddc5bc6-d354-47df-8e6c-3354b34570fe)

**Comment by FedeGueli** [comment]
SLow closing it.

**Comment by HynnSpylor** [comment]
It has a new small saltation branch (with S:Q14H and S:E484K). 
I suggest to reopen it.

**Comment by aviczhl2** [comment]
New countries are USA,Australia, UK and Singapore

**Comment by FedeGueli** [comment]
Thank you missed it , reopened now.

**Comment by FedeGueli** [comment]
i am looking at the tree: being the lower branch all old sequences i think  it is worth to rearrange the proposal to highlight the new Q14/484 branch:
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5c98f_64a240.json?label=id:node_3319680
![Schermata 2023-10-11 alle 09 11 45](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/13cd6336-1fc9-4ff5-bfb9-82ebbc5b5d4f)
Query:T3160C, G8027C, T11522G
Samples : 8
EPI_ISL_18128337, EPI_ISL_18263831-18263832, EPI_ISL_18266417,
EPI_ISL_18324791, EPI_ISL_18355852, EPI_ISL_18366733,
EPI_ISL_18366783

Defining mutations:
FL.13 >C5241T(Orf1a:P1659L)>A22106G(S:K182E)>C12499T>T22928C(S:F456L)>G3994T, A15489G > T3160C, G8027C (Orf1a:V2588L), T11522G (Orf1a:F3753V), A15847T (Orf1b:T794S),  G21604C (S:Q14H), G23012A (S:A484K)

**Comment by FedeGueli** [comment]
Sub branch with 484K 2new sampled from israel new country

**Comment by aviczhl2** [comment]
Designated FL.13.4 and FL.13.4.1 @FedeGueli

**Comment by FedeGueli** [comment]
FL.13.4 via https://github.com/cov-lineages/pango-designation/commit/735356192b05b865bcbe7eb3c14cfd39637820f0 
FL.13.4.1 via https://github.com/cov-lineages/pango-designation/commit/d917828e408e9b83785f4e14cd46fca139c0a8c5

**Comment by Sinickle** [comment]
30/44 seqs uploaded by Qatar today are FL.13.4.1.

**Comment by FedeGueli** [comment]
> 30/44 seqs uploaded by Qatar today are FL.13.4.1.

Thank you for highlighting

**Comment by FedeGueli** [comment]
32/40 from october in Qatar!

**Comment by HynnSpylor** [comment]
Yes the share of FL.13.4.1 in Qatar is 80% 
* Notice that 5 of them get S:K478R and 2 get S:E554K

**Comment by aviczhl2** [comment]
> Yes the share of FL.13.4.1 in Qatar is 80%
> 
> * Notice that 5 of them get S:K478R and 2 get S:E554K

Please make new proposals.
