### ISSUE TITLE
The subfamily of FY.3 (XBB. 1.22.1.3) and ORF1ab: E3764G (A11556G =  NSP6_E195G) appears in China (72seqs)

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#64]
Hello everyone, this is my first article here.

Sub-lineage of:XBB.1.22.1.3 with ORF1ab: E3764G (A11556G) = NSP6_E195G
Earliest sequence:2023-03-31
Most recent sequence:2023-05-04
Countries circulating:China（,Hubei 44, Henan 3,Sichuan 1,Shanghai 1, Anhui 1）
GISAID Search： G2513A,C23191T,A11556G

sequence：EPI_ISL_17652363，EPI_ISL_17645500，EPI_ISL_17645475，EPI_ISL_17645474，EPI_ISL_17645465，EPI_ISL_17645449，EPI_ISL_17645441，EPI_ISL_17645433，EPI_ISL_17625392，EPI_ISL_17625374，EPI_ISL_17625364，EPI_ISL_17625345，EPI_ISL_17625330，EPI_ISL_17625308，EPI_ISL_17625289，EPI_ISL_17625288，EPI_ISL_17625287，EPI_ISL_17625282，EPI_ISL_17625271，EPI_ISL_17625270，EPI_ISL_17625263，EPI_ISL_17615025，EPI_ISL_17615020，EPI_ISL_17615013，EPI_ISL_17615000，EPI_ISL_17614998，EPI_ISL_17614996，EPI_ISL_17614995，EPI_ISL_17614993，EPI_ISL_17614990，EPI_ISL_17614982，EPI_ISL_17614981，EPI_ISL_17614978，EPI_ISL_17545759，EPI_ISL_17545753，EPI_ISL_17545732，EPI_ISL_17545718，EPI_ISL_17545717，EPI_ISL_17545710，EPI_ISL_17545698，EPI_ISL_17545692，EPI_ISL_17545691，EPI_ISL_17545687，EPI_ISL_17545671，EPI_ISL_17545653，EPI_ISL_17545645，EPI_ISL_17545641，EPI_ISL_17511956，EPI_ISL_17501449，EPI_ISL_17485743

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/a41aa11d-7b7c-4e1a-999c-1972230464f2)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_17d08_316c40.json?f_userOrOld=uploaded%20sample

EDITED: showing the exact Usher tree for this one:
![Schermata 2023-05-16 alle 12 46 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d3ec181d-d815-4807-8772-a81e2c8ebdc1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a843_35e4d0.json?c=gt-nuc_11556&label=id:node_6743888

**Comment by FedeGueli** [comment]
@zach-hensel please do you think  NSP6_E195G could be relevant?

**Comment by Memorablea** [comment]
I found that there have been 18 more sequences from multiple regions in Hubei since May 12th.

Latest Tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_36813_4dc120.json?label=id:node_3576971
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/acac4844-200c-4493-98f7-c3da7940638e)

**Comment by Memorablea** [comment]
One sequence from Sichuan and three sequences from Hubei on May 18.

I will move this issue to the Pango designation in due course.

**Comment by FedeGueli** [comment]
I suggest to change the tree you published here and there it doesnt make understand the lineage.

**Comment by Memorablea** [comment]
> EDITED: showing the exact Usher tree for this one: ![Schermata 2023-05-16 alle 12 46 24](https://user-images.githubusercontent.com/87669813/238619956-d3ec181d-d815-4807-8772-a81e2c8ebdc1.png) https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a843_35e4d0.json?c=gt-nuc_11556&label=id:node_6743888

I'm so sorry. Excuse me, should it be changed to the evolutionary tree above?

**Comment by Memorablea** [comment]
> I suggest to change the tree you published here and there it doesnt make understand the lineage.

Thank you very much for raising this question, and I will revise it now.

**Comment by FedeGueli** [comment]
I mean the tree should show the nodes , each with its mutation/s. In the way it is showed now it seems it got all mutations in a row like we see in the downsampled trees

**Comment by Memorablea** [comment]
> I mean the tree should show the nodes , each with its mutation/s. In the way it is showed now it seems it got all mutations in a row like we see in the downsampled trees

I understand. I just updated the tree, thank you!
