### ISSUE TITLE
2 GW.5 (XBB.1.19.1.5) branches-Branch A with S:A845V, (7 seqs , 3 countries) / Saltation Branch B with S:D215H, (10 seqs, 6 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#640]
Defining mutations:
Branch A:
GW.5>T20310C, C28519T>C745T, C24096T (S:A845V)
GISAID query: C6501A, T24046C, C24096T
Earliest seq: 2023-07-05 (New Jersey, US- EPI_ISL_18022751)
Most recent seq: 2023-08-01 (England, UK- EPI_ISL_18112255)
Countries detected: UK (3), US (2)

Branch B:
GW.5>A28768G>G25839T (ORF3a:W149C)>A5709T (ORF1a:E1815V), A12631G, T13270C, G22205C (S:D215H), A26108G (ORF3a:E239G),  C27513T, G28541T (N:A90S)
GISAID query: A5709T, A12631G, T22928C
Earliest seq: 2023-08-03 (Michigan, US- EPI_ISL_18113418)
Most recent seq: 2023-08-05 (Michigan, US- EPI_ISL_18113425)
Countries detected: US (2)

Usher Tree: (Branch A in blue and Branch B in yellow)
<img width="702" alt="屏幕截图 2023-08-19 003742" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7f483caa-e2ac-40ba-9131-c3749b3e8b61">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d886_f99500.json?c=gt-S_215,845

GW.5 is a saltation branch with S:L455F+S:F456L Combo and S:K478I. Branch B is a further saltation with S:D215H, which emerged in XBB.1.17.1 and XBC* lineages, and considered to improve fitness.

Genomes:
Branch A:
EPI_ISL_18022751, EPI_ISL_18097908-18097909, EPI_ISL_18104498, EPI_ISL_18112255
Branch B:
EPI_ISL_18113418, EPI_ISL_18113425

**Comment by FedeGueli** [comment]
A lot of known faces in the branch 2 i will take a closer look later

**Comment by aviczhl2** [comment]
G28541T is also Orf9b:E86D

**Comment by aviczhl2** [comment]
+2 Spain for branch 2

**Comment by FedeGueli** [comment]
branch 1 : +1 dk

**Comment by HynnSpylor** [comment]
Now the parent lineage of Branch B is designated as GW.5.1

**Comment by FedeGueli** [comment]
They appear to be slow i suggest you to close this one next week if nothing changes. GW.5 is a fast growing lineage not seeing any contribution from them.

**Comment by FedeGueli** [comment]
Closing them although maybe being circulating somewhere
