### ISSUE TITLE
GK.1.1 sublineage with ORF7b:A15S first collected in Pernambuco, Brazil (226 GISAID seqs as of 2023-10-07, 16 countries)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#641]
There may be a GK.1.1 sublineage with ORF7b:A15S (G27798T) first collected in Pernambuco, Brazil.

As of 2023-08-18, Cov-Spectrum reports 23 good-quality (24 total) GK.1.1+ORF7b:15S sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AGK.1.1+%26+ORF7b%3AA15S&nextcladeQcOverallScoreTo=29&

The growth advantage shows as high globally, but it is difficult to determine in the most common country (Ireland) since all GK.1.1 reported from Ireland have ORF7b:A15S. However, it may be significant that this lineage has already been detected in 5 countries on 3 continents. Additionally, the Bloom and Neher data at https://jbloomlab.github.io/SARS2-mut-fitness/ORF7b.html suggests that ORF7b:A15S confers a fitness advantage. Examination of the fitness from Bloom and Neher by clade (https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) shows that an advantage from ORF7b:A15S is consistent across all clades.

As of 2023-08-18, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_GK 1 1+ORF7b_15S](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/b7543973-0964-4362-aefa-d1ab152f6c7b)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_GK.1.1%2BORF7b_15S.json?c=gt-ORF7b_15&label=id%3Anode_7190991

GISAID query: C23673T, C23280T, C26735T, G27798T

First GISAID sequence: Pernambuco, Brazil 2023-06-01 

Most Recent GISAID sequence: Dublin, Ireland 2023-08-08

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-GK.1.1+ORF7b_15S.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12384437/Support-GK.1.1%2BORF7b_15S.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-GK.1.1+ORF7b_15S.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12384436/gisaid-epi-isl-GK.1.1%2BORF7b_15S.txt)

Edit: Correct First and Most Recent GenBank to GISAID.

**Comment by FedeGueli** [comment]
ABout GK tree unrelated to this issue (sorry @alurqu if i use this one) i would ask some calrification from @angiehinrichs: i noticed that there is an Usher branch close to  XBB.1.5.70 named XBB.1.5.17124 which gained 455-456-511 as GK.2 but lacks all the nucs leading to GK.2 is that real ? is a recombinant?:
![Schermata 2023-08-19 alle 10 25 36](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/76543995-7c8a-44ce-a6bd-4494e0fd1394)
![Schermata 2023-08-19 alle 10 26 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d3a2aead-0f2d-454f-a3d8-211ef4b1d38e)
Interestingly it has S:P1162S as the other quite growing XBB.1.5 455-456 still undesignated proposed in pango .
Thanks for your help.

**Comment by AngieHinrichs** [comment]
> Usher branch close to XBB.1.5.70 named XBB.1.5.17124

XBB.1.5_17124 is just a new label for an old node formerly labeled XBB.1.5 (even though it includes T17124C which is in most but not all XBB.1.5 seqs).  The new label was recently introduced to address an annoying branch move that must have happened during a recent reoptimization.  

<details>
  <summary>Longer explanation</summary>

It is just the part of XBB.1.5 that includes T17124C (most of XBB.1.5).  The part of XBB.1.5 that has only T23018C and not T17124C used to be on this path with a reversion on 17124:
`XBB.1 > G27915T > T17124C > T23018C > C17124T`
The XBB.1.5_17124 label was not necessary back then.  XBB.1.5 was annotated on the node with 23018, and sequences with 23018 but without 17124 were on the child node with the reversion.

It would be preferable to have G27915T > T23018C > T17124C, with XBB.1.5 annotated on the T23018C.  But unfortunately during some recent daily build's matOptimize run, the branch was instead moved to a different reversion path:
`XBB.1 > G27915T > T28297C > T23018C > C28297T`
-- as a child of XBB.1.22!  🙁  So XBB.1.5 sequences without T17124C started to appear to be XBB.1.22 (but with a reversion on one of XBB.1.22's two defining mutations), not good at all.  I moved the XBB.1.5 label to the new reversion path and added the label XBB.1.5 on the old T17124C > T23018C node where XBB.1.5 used to be annotated.

I've had on my to-do list for months to make a utility that will detect grandparent-reversion nodes like this and fix them (i.e. if we see `... > X > Y > revX`, move `revX` to `... > Y`).  Will have to bump up its priority.  It should also fix the bad placement of XBB.1.9.2 as a child-with-reversion of XBB.1.9.1, and at least one mess in BA.2.75.3 (BM) sublineages.

</details>

> branch ... which gained 455-456-511 as GK.2 but lacks all the nucs leading to GK.2 is that real ? is a recombinant?:

It is placed pretty close to XBB.1.5.70.  In the 2023-08-20 tree, after the part of XBB.1.5 with T17124C, XBB.1.5.70 and that branch have 6 mutations in common:
`C27059T > C28005T > T22928C > G22927T > C22624T > A25045G`
But then while XBB.1.5.70 has these 4:
`C1973T > T8737C > C7564T,G12467T`
that branch has 5 different mutations:
`C15755G,G23093A,C23741T > C7417T,C25046T`

Meanwhile GK.2 has all of the XBB.1.5.70 mutations plus these:
`C23741T > T2824C,G23093A`
so GK.2 has two additional mutations in common with that branch (G23093A,C23741T)... but still GK.2 has 5 mutations that don't appear in that branch (XBB.1.5.70's C1973T > T8737C > C7564T,G12467T, T2824C), and GK.2 doesn't have 3 mutations seen in that branch (C15755G, C7417T, C25046T).

So it's just another little undesignated branch in XBB.1.5 -- in the part of XBB.1.5 that has the new annoying label.  Who knows whether it's recombination or an interesting convergent appearance of Spike mutations (although there's no reason to expect a synonymous mutation like C23741T to convergently appear).

**Comment by FedeGueli** [comment]
156 as today

**Comment by FedeGueli** [comment]
Adding a tracker: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C23673T%2CC23280T%2CC26735T%2CG27798T&analysisMode=CompareToBaseline&

**Comment by alurqu** [comment]
UShER shows this as the second-largest GK.1.1 branch with a different geographic distribution from the largest GK.1.1 branch that has A23014G,

**Comment by FedeGueli** [comment]
It cannot compete : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C23673T%2CC23280T%2CC26735T%2CG27798T&analysisMode=CompareToBaseline&
@corneliusroemer if you have the need to describe further GK.1.1 this is a good candidate but in my view GK is too slow to survive without 475V
