### ISSUE TITLE
XBB.1.16.14 sublineage with ORF1a:T568I first detected in California, USA (106 GISAID seqs as of 2023-10-07; USA, Canada, Australia, Spain)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#642]
There may be a XBB.1.16.14 sublineage with ORF1a:T568I (C1968T; NSP2:T388I) first detected in California, USA.

As of 2023-08-18, Cov-Spectrum reports 23 good-quality (29 total) XBB.1.16.14+ORF1a:568I sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.1.16.14+%26+ORF1a%3AT568I&nextcladeQcOverallScoreTo=29&

The growth advantage shows as high globally, but the counts are still low, so the growth advantage may be overestimated. Most of the sequences are in the USA where the early XBB.1.16.14 did not have ORF1a:T568I but where the mutation has become more common recently in XBB.1.16.14. There is also spread to 4 countries on 3 continents. Additionally, the Bloom and Neher data at https://jbloomlab.github.io/SARS2-mut-fitness/nsp2.html suggests that NSP2:T388I confers a fitness advantage. Examination of the fitness from Bloom and Neher by clade (https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) shows that an advantage from NSP2:T388I is consistent across all clades except for a near-neutral effect in clade 20A.

As of 2023-08-18, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 1 16 14+ORF1a_568I](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/ff634c90-efb1-49b2-85f9-94a1cf329032)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_XBB.1.16.14%2BORF1a_568I.json?c=gt-ORF1ab_568&label=id%3Anode_6814865

GISAID query: T22917A, G11926A, C14898T, C1968T

First GISAID sequence: California, USA 2023-07-03

Most Recent GISAID sequence: Washington, USA 2023-08-08

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-XBB.1.16.14+ORF1a_568I.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12384603/Support-XBB.1.16.14%2BORF1a_568I.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.1.16.14+ORF1a_568I.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12384604/gisaid-epi-isl-XBB.1.16.14%2BORF1a_568I.txt)

**Comment by FedeGueli** [comment]
This is quite far from fastest lineages: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T22917A%2CG11926A%2CC14898T%2CC1968T&analysisMode=CompareToBaseline&

**Comment by alurqu** [comment]
This is growing but only slowly. Given that it is now quite far from the fastest lineages, I'll close this issue since this lineage is unlikely to receive a designation.
