### ISSUE TITLE
FU.1/EG.5.1.1 recombinant with additional S:Q14H in Shanghai (3 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#647]
EG.5.1.1+
2334C, 5720G, 6541C, 27507A, 29625C (rev)
A460G,T3802C,A28447G, C29386T (from FU.1+A460G branch)
C1059T,C3619T,G20663A,G21604A (private mutations, Orf1a:T265I, Orf1b:S2399N, S:Q14H)

This one gets S:Q14H via G21604A not HK.2's G21604T

FU.1---EG.5.1.1----FU.1

Breakpoint 1: Between 6542 and 9692
Breakpoint 2: Between  25573 and 27506

This one is basically HK.2-Spike+XBB.1.16-Orf9b

GISAID query: A460G,C1059T,C3619T,T3802C,C25572T
No. of seqs: 2(Shanghai)
EPI_ISL_18074516, 2023-7-5
EPI_ISL_18114800, 2023-8-7

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_3f35c_cd5f0.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9015be5a-d9b1-45e0-8b70-5007c2bf342a)

**Comment by FedeGueli** [comment]
Thank you

**Comment by aviczhl2** [comment]
There is a 3rd seq, reopen.
