### ISSUE TITLE
FL.13.1+7-nuc,5-aa including  S:L455F,F456L (13  seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#649]
FL.13.1+A2611G,C13011T(Orf1a:T4249I)+G10658A(Orf1a:V3465I)+G25337T(S:D1259Y)+T22702C,G22927T,T22928C(S:L455F,F456L)

GISAID query:G22927T,T22928C,G25337T
No. of seqs: 2(Shanghai 1(from South Korea) South Korea 1)

EPI_ISL_18047533, South Korea, 2023-7-8
EPI_ISL_18114830, Shanghai, 2023-8-11

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice25_genome_3f35c_cd630.json?label=id:node_6871669)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e8e30564-4872-47b1-a299-6c2ccff86f3f)

**Comment by Over-There-Is** [comment]
The Shanghai sequence is imported from South Korea.

**Comment by aviczhl2** [comment]
> The Shanghai sequence is imported from South Korea.

Is there a quick way to link GISAID seqs to GenBase metadata?

**Comment by HynnSpylor** [comment]
2 more seqs from South Korea

**Comment by FedeGueli** [comment]
i think this one should have been mentioned somewhere by @borisuitham when it was a singlet. Not able to find where.

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by FedeGueli** [comment]
It doesnt appear fast. lets wait a bit more.

**Comment by FedeGueli** [comment]
I think we can close this one.

**Comment by FedeGueli** [comment]
last one came from Colombia do u want it to be reopened? not sure if worth.

**Comment by aviczhl2** [comment]
12 now. Please reopen.

**Comment by FedeGueli** [comment]
Closing it for now
