### ISSUE TITLE
BQ.1.2.2 (BQ.1.2 + K147E, ∆186-187, N188Y, R346T, V445A) Sublineage w/ S:A484K, S:V486A, ORF7a:∆71-82, + 4x ORF1ab

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#650]
### **Description—First sequence spotted by @c19850727 (Sakaguchi Hitoshi) and @hynnspylor ([here](https://github.com/cov-lineages/pango-designation/issues/2068#issuecomment-1680316776))  **
**Sub-lineage of:** BQ.1.2.2
**Earliest sequence:** 2023-7-24, USA, Delaware — EPI_ISL_18115437, EPI_ISL_18115438
**Most recent sequence:** 2023-8-2, Finland — EPI_ISL_18106489
**Countries circulating:** USA (2), Finland (1)
**Number of Sequences:** 3
**GISAID AA Query:** Spike_E484K, Spike_F486A
**GISAID Nucleotide Query:** G8368A, A17824G
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions/Deletions on top of BQ.1.2.2**
**Spike:** A484K, V486A
**ORF7a:** ∆71-82 (frameshift)
**ORF1a** L580F, L730F
**ORF1b:** V464F, T1453A
**Nucleotide:** C2003T, C2453T, G8368A, G14857T, A17824G, T23011A, G23012A, C23013A (reversion), T23019C, A25983G
**Nucleotide Deletions:** ∆27605-27639

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BQ.1.2.2_A484K_V486A.json?c=gt-S_484&label=id:node_3628803
 
<img width="1380" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e764d598-cada-4100-a463-e6f4f7bfed88">

**Evidence**
BQ.1.2.2 already possessed an interesting spike profile, with spike mutations K147E, ∆186-187, N188Y, R346T, and V445A. These three have added the 2-nucleotide A484K as well as V486A. The two sequences from the USA both seem to have great coverage throughout the whole genome, whereas the one from Finland is missing quite a bit of coverage. It's hard to know for certain if the additional mutations in the two US sequences—S:T547I, S:V1228L, ORF1a:T708I, ORF1b:A2222V (nucleotides C2388T, C20132T, C20719T, C23202T, C23557T, G25244T)—are truly absent from the Finnish sequence or if they were just not picked up in sequencing.

Notably, this branch features three consecutive nucleotide mutations, all to A—T23011A, G23012A, C23013A. The mutations relative to BA.2 at S:484 and 486 are pictured below.
<img width="1198" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/44f4cb94-8858-459b-a730-56973aeb2f45">

In the two sequences from the US state of Delaware, there's also a very odd synonymous mutation C23557T, which is adjacent to the A23558G mutation that forms S:I666V. Peculiarly, according to the study "Rampant C→U Hypermutation in the Genomes of SARS-CoV-2 and Other Coronaviruses: Causes and Consequences for Their Short- and Long-Term Evolutionary Trajectories" by P. Simmonds, the nucleotide context in which C23557T occurs is easily the *least* favorable one for C->T mutations. 
<img width="1501" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1693c166-12c7-4fd7-bfa5-2c00cc5acb17">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18115437, EPI_ISL_18115438, EPI_ISL_18106489
</details>

**Comment by FedeGueli** [comment]
@ryhisner edited to credit hynnspylor who independently discovered it at the same time with Saka here : https://github.com/cov-lineages/pango-designation/issues/2068#issuecomment-1680316776

**Comment by FedeGueli** [comment]
Please propose in the main page if reaches 5 and add one more country.

**Comment by Sinickle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/479c56db-2201-49c7-a95a-c8e2b117a358)

Not sure if S:V486A will have some sort of epistatic effect, but S:A484K looks like a definite win for BQ.1

**Comment by Over-There-Is** [comment]
> **Substitutions/Deletions on top of XBB.1.5:**

**Comment by FedeGueli** [comment]
@Over-There-Is now corrected

**Comment by FedeGueli** [comment]
Designated JH.2 via https://github.com/cov-lineages/pango-designation/commit/9043731f6746aade7f24fddc96892b661bf06797
