### ISSUE TITLE
EG.5.1.6 + ORF8:R115C (115) mostly USA ~ 2.7% in Texas in the past 21 days

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#653]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/430e9aef-3814-41df-9182-7c504b367aac)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/369c9500-6c1d-440b-beea-8e85a03a4a55)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fdfb_198e90.json?c=gt-ORF8_115&label=id:node_6904445
first seq: 2023-06-11
Most Recent: 2023-08-06
OR440547.1 EPI_ISL_18098708 OR395511.1 OR460044.1 EPI_ISL_18098806 EPI_ISL_18099295 EPI_ISL_18046470 EPI_ISL_18098578 EPI_ISL_17818492 EPI_ISL_17838394 OR268410.1 OR226172.1 OR343083.1 EPI_ISL_18098882 OR366817.1 EPI_ISL_18098694 EPI_ISL_18066998 EPI_ISL_18101345 EPI_ISL_18098704 EPI_ISL_18099140 EPI_ISL_18095003 OR388015.1 EPI_ISL_18099124 EPI_ISL_18098722 EPI_ISL_18099249 EPI_ISL_18099160 EPI_ISL_18099179 EPI_ISL_18099120 OR439978.1 EPI_ISL_18099151 EPI_ISL_18081472 OR428864.1 EPI_ISL_18099155 EPI_ISL_18098759 EPI_ISL_18098662 EPI_ISL_17960141

Gisaid query: C28236T,C5835T (Edited)

**Comment by FedeGueli** [comment]
This is growing similar to its sibling HV.1 please propose it:
https://cov-spectrum.org/explore/United%20States/AllSamples/Past6M/variants?nextcladePangoLineage=HV.1*&nucMutations1=C28236T%2CC5835T&analysisMode=CompareToBaseline&
