### ISSUE TITLE
Multiple CH.1.1* Lineages with S:R403K [13 (+12)/8]

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#655]
```[tasklist]
### Multiple CH.1.1* Lineages with `S:R403K`
- [ ] Branch 1: CH.1.1.1 [C25721T(ORF3a:A110V) > T4402A] > G15025T(ORF1b:A520S) > G11527A > G22770A(**S:R403K**) [Query: `T4402A, G11527A, G22770A`, 13 (+12), 09/18]
- [ ] Branch 2: CH.1.1 [C21811T > C193T] > G16537A(ORF1b:D1024N), T16599C > A2043G(ORF1a:N593S), C4754T(ORF1a:P1497S), C8637T(ORF1a:T2791I), A24727G > C25587A > G7059A(ORF1a:G2265D), G21668A(**S:V36I**), G22770A(**S:R403K**) [Query: `A2043G, G16537A, G21668A`, 8, 09/19]
```

### Branch 1

_Once [mentioned in Comment](https://github.com/cov-lineages/pango-designation/issues/1960#issuecomment-1664074230) of `S:R403K` lineage tracker from main repo cov-lineages/pango-designation#1960_

**Defining Mutations:** `CH.1.1.1 [C25721T(ORF3a:A110V) > T4402A]` > `G15025T(ORF1b:A520S)` > `G11527A` > `G22770A(S:R403K)`
**Query:** `T4402A, G11527A, G22770A` (only catches 10 but there are many more non-GISAID or dropout sequences)
**Earliest seq:** 2023-03-13 (`EPI_ISL_17299227`, England)
**Latest seq:** 2023-08-07 (`CLIMB-CM7YGNXU`, England)
**Sampled Countries:** UK (19: England/16; Northern Ireland/1; Scotland/1; Wales/1), China (1, Shanghai, ex. UK)

<details><summary>Genomes: </summary>

```
England/BRBR-32710401/2023|EPI_ISL_17350880|2023-03-24
England/BRBR-3271043E/2023|EPI_ISL_17350860|2023-03-24
England/CLIMB-CM7YF5FS/2023|EPI_ISL_17989737|2023-06-30
England/CLIMB-CM7YGNXU/2023|EPI_ISL_18130679|2023-08-07
England/CLIMB-CM7YKN7I/2023|EPI_ISL_18015636|2023-07-09
England/CLIMB-CM7YKY1W/2023|EPI_ISL_17989777|2023-06-07
England/CLIMB-CM7YRU96/2023|EPI_ISL_18015564|2023-07-01
England/PHEC-YYE3BW5/2023|EPI_ISL_17721627|2023-05-04
England/PHEC-YYE5Q8F/2023|EPI_ISL_17838261|2023-06-05
England/PHEC-YYE5QM7/2023|EPI_ISL_17838270|2023-05-30
England/PHEC-YYEZIM6/2023|EPI_ISL_17666189|2023-05-05
England/PHEP-YYGOY4R/2023|EPI_ISL_17299227|2023-03-13
England/PHEP-YYGTBIM/2023|EPI_ISL_17400899|2023-03-18
England/PHEP-YYGTBWP/2023|EPI_ISL_17400910|2023-03-18
Northern_Ireland/NIRE-022098/2023|EPI_ISL_17964390|2023-06-02
Scotland/SCOT-31431/2023|EPI_ISL_17884623|2023-06-09
Shanghai/SCDC-HG0801-2878/2023|EPI_ISL_18105623|2023-07-31
Wales/CLIMB-CM7Y8R7B/2023|EPI_ISL_18098198|2023-07-26
```

</details>

<details><summary>non-GISAID Genomes: </summary>

```
England/PHEC-YYE4ZIB/2023|OY290526.1|2023-06-01
England/CLIMB-CM7Y8XS3/2023|2023-07-26
```

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_cd61_1e6670.json?c=gt-S_403&label=id:node_7650732
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/31450afa-8605-4d64-9546-ef696c15b29a)

**Trivia:**
- It probably have `ORF1a:82-86 deletion` too. Sequence from Shanghai Customs also have that deletion so it could be real.
![deletion](https://github.com/cov-lineages/pango-designation/assets/125747944/96c0ea76-668b-4fc6-9cff-172cac066aba)
- There are a few seqs from neighbouring branches also have `S:R403K`, these may be from the proposed branch too (not counted):
```
Austria/AGES-1139469/2023|EPI_ISL_17826788|2023-06-05
England/PHEC-YYE4SNJ/2023|OY291433.1|2023-06-05
```

---

### Branch 2

**Defining Mutations:** `CH.1.1 [C21811T > C193T]` > `G16537A(ORF1b:D1024N_nsp13_D101N), T16599C` > `A2043G(ORF1a:N593S/nsp2_N413S), C4754T(ORF1a:P1497S/nsp3_P679S), C8637T(ORF1a:T2791I/nsp4_T28I), A24727G` > `C25587A` > `G7059A(ORF1a:G2265D/nsp3_G1447D), G21668A(S:V36I), G22770A(S:R403K)`
**Query:** `A2043G, G16537A, G21668A`
**Earliest seq:** 2023-02-10 (`EPI_ISL_17978223`, Eastern Cape, South Africa)
**Latest seq:** 2023-07-04 (`EPI_ISL_18125236`, Eastern Cape, South Africa)
**Sampled Countries:** South Africa (7)

<details><summary>Genomes: </summary>

`EPI_ISL_17358567, EPI_ISL_17859330, EPI_ISL_17978223, EPI_ISL_18125226-18125227, EPI_ISL_18125236, EPI_ISL_18125240`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_1b23a_59e0e0.json?c=gt-S_403&label=id:node_7637426
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/18cae920-64be-4470-ab65-0f81978cce47)

**Trivia:**
- It also have `ORF1a:82-86` deletion.

**Comment by FedeGueli** [comment]
Thx for proposing likely slow but worth tracking for a bit.

**Comment by FedeGueli** [comment]
Very slow.

**Comment by FedeGueli** [comment]
Closing them

**Comment by FedeGueli** [comment]
> Branch 1 now has 14 that can be found by query, and 20 more with potential `R403K` dropout, with one of the latest sequence `England/CLIMB-CM7YMEY1/2023|EPI_ISL_18497165|2023-10-09` that has got extra `S:T478N`
> 
> Genomes:
> UShER:

Thx! luckily they arent so recent!

**Comment by aviczhl2** [comment]
Branch 1: +1, 12-5.

it seems that most seqs have G22770R instead of G22770T. Suggest to use C22458T,G25483T,G22770 for the S:T299I branch and gets 27 seqs

**Comment by FedeGueli** [comment]
B2 +1 uk
