### ISSUE TITLE
XBB.2.3.3 Sublineage w/new S2' FCS—S:N450D, S:K478R, S:P812R, S:V1264L + 4x ORF1ab (6 countries, 48 seq, Jan 21)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#656]
### **Description**
**Sub-lineage of:** XBB.2.3.3
**Earliest sequence:** 2023-7-30, Netherlands, Noord-Brabant — EPI_ISL_18098305
**Most recent sequence:** 2023-8-13, Netherlands, Noord-Holland — EPI_ISL_18115963
**Countries circulating:** Netherlands (2)
**Number of Sequences:** 2
**GISAID AA Query:** Spike_P812R, Spike_P521S
**GISAID Nucleotide Query:** G3620A, A6326G
**CovSpectrum Query:** Nextcladepangolineage:XBB.2.3.3* & S:P812R
**Substitutions on top of XBB.2.3.3:**
**Spike:** N450D, K478R, P812R, V1264L
**ORF1a:** T224I, G1119S, T2021A
**ORF1b:** G977C
**Nucleotide:** C936T, G3620A, A6326G, A13021G, C15540T, G16396T, A17622G, A22910G, A22995G, T23830C, C23997G, G25352C, C26936T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/XBB.2.3.3_N450D_K478R_P812R_V1264L.json?c=gt-S_812&gmax=25384&gmin=21563&label=id:node_4102599

<img width="1482" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a626df87-649f-4da0-a9ae-f899a51983b8">

 
**Evidence**
XBB.2.3* lineages has curiously been much slower than XBB.1*+S:S486P lineages to pick up advantageous spike mutations, particularly S:F456L (in 0.69% of XBB.2.3* in the past 3 months compared to 18.7% of XBB.1*+S:F486P) and L455F-F456L (1067 sequences of XBB.1*+S:F486P w/Flip compared to zero XBB.2.3*). S:N450D has been extremely rare in both, however, appearing in just 51 sequences in the past three months.
 
But the most interesting aspect of this 2-sequence (so far) saltation branch of XBB.2.3.3 is the presence of S:P812R, which @ThomasPeacock informed us creates a new furin-cleavage site (FCS) at the S2' location. See his explanation  at Pango Github issue #1627 here:[ https://github.com/cov-lineages/pango-designation/issues/1627](https://github.com/cov-lineages/pango-designation/issues/1627) .
 
This lineage also has S:K478R, which has proven to confer a growth advantage in XBB lineages, and S:V1264L, which has proven to be an advantageous mutation in the past, and which has a solid fitness advantage according to the Bloom Lab amino-acid fitness calculator.

<img width="692" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/bbb2a1d1-8a94-4206-9538-19d0922b69b0">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18098305, EPI_ISL_18115963, EPI_ISL_18130456,
EPI_ISL_18136960, EPI_ISL_18136963, EPI_ISL_18286700,
EPI_ISL_18299958, EPI_ISL_18331374, EPI_ISL_18392989,
EPI_ISL_18393096, EPI_ISL_18393098, EPI_ISL_18398856,
EPI_ISL_18398858, EPI_ISL_18403515, EPI_ISL_18403933,
EPI_ISL_18419955, EPI_ISL_18421656, EPI_ISL_18441622,
EPI_ISL_18444758, EPI_ISL_18444761-18444762, EPI_ISL_18444840,
EPI_ISL_18446173, EPI_ISL_18467510-18467513, EPI_ISL_18467516-18467517,
EPI_ISL_18467525, EPI_ISL_18467588, EPI_ISL_18471202,
EPI_ISL_18520168, EPI_ISL_18535805, EPI_ISL_18536101,
EPI_ISL_18584927, EPI_ISL_18584952, EPI_ISL_18640365,
EPI_ISL_18674275, EPI_ISL_18674905, EPI_ISL_18674917,
EPI_ISL_18694629, EPI_ISL_18701935, EPI_ISL_18712638,
EPI_ISL_18754699, EPI_ISL_18754879, EPI_ISL_18763381,
</details>

**Comment by FedeGueli** [comment]
@ryhisner consider that there is also GJ.1.2.1 (same XBB.2.3.3 family) that has as defining mutation S:N450D and further acquired S:T478R  so  leaving out the S2 interesting mutations , this notably converges toward its "sibling"

**Comment by oobb45729** [comment]
Maybe it can be explained by my conjecture that losing ORF8 trades innate immune evasion capability for infectiousness.
 https://github.com/cov-lineages/pango-designation/issues/1451

>Could it mean that mutations like ORF8:G8* or C27889T work better when the spike is highly antibody-evasive that it can tolerate the ORF8 loss? Maybe this is the reason why ORF8:G8* is doing well on XBB. Could it also mean that if the spike is no longer so antibody-evasive, the ORF8 loss becomes detrimental to the virus? Could this be the reason that the vaccines did a much better job limiting the spread of Alpha (with ORF8:Q27*) than Delta?

BA.5 also faded quite fast when the spike is no longer so antibody-evasive. Maybe for lineages without a full ORF8, they need antibody-evasive mutations more to keep up, but XBB.2.3 has a full ORF8, so it doesn't need S:F456L that much?

**Comment by oobb45729** [comment]
Maybe it can be explained by my conjecture about that losing ORF8 trades innate immune evasion capability for infectiousness.
 https://github.com/cov-lineages/pango-designation/issues/1451

>Could it mean that mutations like ORF8:G8* or C27889T work better when the spike is highly antibody-evasive that it can tolerate the ORF8 loss? Maybe this is the reason why ORF8:G8* is doing well on XBB. Could it also mean that if the spike is no longer so antibody-evasive, the ORF8 loss becomes detrimental to the virus? Could this be the reason that the vaccines did a much better job limiting the spread of Alpha (with ORF8:Q27*) than Delta?

BA.5 also faded quite fast when the spike is no longer so antibody-evasive. Maybe for lineages without a full ORF8, they need antibody-evasive mutations more to keep up, but XBB.2.3 has a full ORF8, so it doesn't need S:F456L that much?

**Comment by ryhisner** [comment]
This one tripled from two to six sequences in the past two days.

**Comment by FedeGueli** [comment]
weirdly the AA query (6) gives one more seq than the nuc query (5) G3620A, A6326G , anyway it seems doubling fast.

**Comment by JosetteSchoenma** [comment]
Yes @FedeGueli The sixth one misses G3620A and has an N at A6326G. They all have A17622G, if you would like to add it, but query Spike_P812R, Spike_P521S does the job.
Thanks, @ryhisner. The majority of recent Dutch XBB.2.3 have S:478R, from several different sublineages.
EPI_ISL_18137115
EPI_ISL_18136963
EPI_ISL_18136960
EPI_ISL_18130456
EPI_ISL_18115963
EPI_ISL_18098305
New tree, including those EPI_ISL numbers and the dates.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/3509ae95-3cac-4321-ab34-6cde6cc4a31e)

**Comment by FedeGueli** [comment]
Yes def the Combo 478-521 works well (also on XBB.1.16 backbone)  , likely if XBB.2.3 would have got it before it could be in a leading position now.

**Comment by FedeGueli** [comment]
Thx @JosetteSchoenma

**Comment by FedeGueli** [comment]
it unbelievably seems slow. or this new fcs thing makes the virus super mild or slow it toward lower fitness  !

**Comment by JosetteSchoenma** [comment]
Reasonably big upload today from the Netherlands. No new ones.

**Comment by FedeGueli** [comment]
Closing this for now @ryhisner ping me if something changes!

**Comment by ryhisner** [comment]
Probably still a dead lineage, but two showed up in Scotland today with collection dates of Sept 25-26, and there are three more on the Usher tree with October collection dates that haven't been uploaded to GISAID yet. EPI_ISL_18393096, EPI_ISL_18393098

<img width="1504" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2259f6fc-d492-45a5-9762-d643d9f5c010">

**Comment by JosetteSchoenma** [comment]
And apparently there was a Dutch one in between, so 12 in totaal now then.

**Comment by ryhisner** [comment]
Credit to @JosetteSchoenma for spotting a recent surge in this one, which is now >32 sequences. (There are at least some on the Usher tree but not on GISAID, but the fat that many of the samples occur on the Usher tree three separate times makes it hard to count them.) The most recent sequences have mostly been from Scotland, with one from Belgium and a coupe from the Netherlands. One also showed up on the West Coast of the USA in the state of Washington. 
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f4dabdbd-ce5f-43f0-a2cc-790e770a4b4d">

**Comment by FedeGueli** [comment]
+1 Anhui

**Comment by FedeGueli** [comment]
One only sample in November closing it

**Comment by FedeGueli** [comment]
38 now last 2 from Slovakia

**Comment by FedeGueli** [comment]
44 sequences and after only two sequences in november showed up in 4 samples in December mostly from Netherlands. Reopening for a whilel

**Comment by FedeGueli** [comment]
New tree: 
<img width="1170" alt="Screenshot 2024-01-02 alle 07 36 33" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d1e5d688-1887-44aa-914e-d38a7b1aa03f">
[2023-12-25](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_af14_3509a0.json?f_userOrOld=uploaded%20sample&label=id:node_4064340)

cc @ryhisner one curious thing here is that the brach that survived and it is circulatingin NDL and Uk is defined by two silent mutations in the RBD:
T22925C > S:L455L
A23092T > S:V510V 
<img width="1156" alt="Screenshot 2024-01-02 alle 07 39 19" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/040dc70d-9849-4786-be05-0a849f03a510">

What this could mean?

**Comment by FedeGueli** [comment]
48. now. most of the recent samples in the branch with silent spike substitutions: T22925C

**Comment by FedeGueli** [comment]
Please propose on the main repo!
