### ISSUE TITLE
EG.5.1 sublineage with S:D420N (3 seqs in Japan and HI, US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#658]
Defining mutations:
EG.5.1>A22531G>A14469C>G22820A (S:D420N), T28217C, A29700G
GISAID query: A14469C, G22820A, A22531G
Earliest seq: 2023-07-16 (HI, US- EPI_ISL_18077335)
Most recent seq: 2023-07-31 (Japan- EPI_ISL_18116076)
Countries detected: Japan (2), US (1)

Usher Tree:
<img width="905" alt="屏幕截图 2023-08-21 152235" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/51bc09c9-ed89-441f-aab8-9f963291f6a4">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ee58_30f1a0.json?c=gt-S_420

S:D420N has shown certain success in GL.1 (XAY.1.1.1.1). It may be a potential mutation by Cao et al. (2023) (despite the research is based on XBB.1.5 RBD)
![242475671-37a803cb-8e10-4247-be15-cc84a3049fdd](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/8ce38277-0490-424d-8bc8-f1d318d0cab9)

Genomes:
EPI_ISL_18077335, EPI_ISL_18106324, EPI_ISL_18116076

**Comment by FedeGueli** [comment]
closing it
