### ISSUE TITLE
XBB.1.11.1 (S:S486P) Sublineage with S:K478R (87 seq, May 20)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#66]
**Description**
**Sub-lineage of:** XBB.1.11.1
**Earliest sequence:** 2023-2-2, Indonesia — EPI_ISL_17012209
**Most recent sequence:** 2023-5-2, Indonesia — EPI_ISL_17655098
**Countries circulating:** Indonesia (29), Malaysia (7), England (3) South Korea (1), Australia (1), Spain (1), Japan (1)
**Number of Sequences:** 43
**GISAID Nucleotide Query:** C13968A, G16377A, C22995G, T23018C
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.11.1* & S:K478R
**Substitutions on top of XBB.1.11.1:**
**Spike:** K478R
**Nucleotide:** A22995G

**USHER Tree** (The tree below excludes several sequences with multiple artifactual reversions, so all the longer branches below consist of real mutations.)
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.11.1_(S486P)_K478R.json?c=gt-S_478&label=id:node_3679455
<img width="1493" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/89b372d0-3c35-461d-a5af-b8701ccf3de1">

**Evidence**
This lineages seems to be most in Indonesia, a country of about 275 million people from which we don't get very many sequences. It is also prominent in Malaysia. The base lineage can't be growing particularly fast or it would be more widespread internationally by now, but there's a great deal of diversity here, including a sizable branch with S:F186S and four additional AA mutations. This branch includes the most recently collected sequence (May 2) and first appeared on March 10 in Indonesia.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17012209, EPI_ISL_17164850, EPI_ISL_17324410, EPI_ISL_17389516, EPI_ISL_17389654, EPI_ISL_17389725, EPI_ISL_17416998, EPI_ISL_17469966, EPI_ISL_17470009, EPI_ISL_17470016-17470017, EPI_ISL_17470030, EPI_ISL_17518081, EPI_ISL_17542013, EPI_ISL_17546410, EPI_ISL_17546448, EPI_ISL_17551332, EPI_ISL_17551361, EPI_ISL_17551494, EPI_ISL_17551532, EPI_ISL_17554737, EPI_ISL_17558668, EPI_ISL_17612344-17612345, EPI_ISL_17612347, EPI_ISL_17612354, EPI_ISL_17612366, EPI_ISL_17612373-17612374, EPI_ISL_17622306, EPI_ISL_17622322, EPI_ISL_17622348, EPI_ISL_17622363, EPI_ISL_17630635, EPI_ISL_17630702, EPI_ISL_17652467, EPI_ISL_17654916, EPI_ISL_17654975, EPI_ISL_17654978, EPI_ISL_17655098, EPI_ISL_17655949, EPI_ISL_17656892, EPI_ISL_17664323
</details>

**Comment by HynnSpylor** [comment]
Maybe the Usher tree is the reorganizing of #31

**Comment by FedeGueli** [comment]
> Maybe the Usher tree is the reorganization of #31

The branch on the top is the saltation proposed in #31 lemm re check what happened.

cc @angiehinrichs Usher seems to have re sorted this tree in the opposite direction could you take a look

**Comment by FedeGueli** [comment]
@corneliusroemer @angiehinrichs could you please take a look at this one? it was proposed before but USher at that time had S:F186S as main node, then with new sequences of this one with S:K478R accumulating fastly now it broaden the lineage making it start from S:K478R and showing just a branch of it with S:F186S.


Once resolved the tree i think it should be proposed.

**Comment by AngieHinrichs** [comment]
(looking at the 2023-05-18 tree) The saltation branch from #31 has been moved to a separate branch of XBB.1.11.1 starting with ORF1a:V3078I (G9497A) > S:F186S (T22119C); this is just the branch with S:K478R (A22995G) and these seuqences:

Indonesia/JK-NIHRD-W01459/2023|EPI_ISL_17546448|2023-03-31
Indonesia/JK-NIHRD-W01136/2023|EPI_ISL_17551532|2023-03-31
Indonesia/JK-GSILab-1151115/2023|EPI_ISL_17664323|2023-04-19
Indonesia/JK-NIHRD-W01577/2023|EPI_ISL_17518081|2023-04-12
Indonesia/YO-BBTKLPP-C285-S78B3/2023|EPI_ISL_17654916|2023-04-28
Oman/5237649/2023|EPI_ISL_17550381|2023-03-19
SouthKorea/KDCA231306/2023|EPI_ISL_17554737|2023-04-17
Japan/PG-472308/2023|EPI_ISL_17558668|2023-03-31
Malaysia/C19UMB3912/2023|EPI_ISL_17671125|2023-04-12
Malaysia/C19UMB3887/2023|EPI_ISL_17671106|2023-03-30
England/PHEC-YYEU7WM/2023|2023-04-11
England/PHEC-YYEOQSH/2023|2023-03-25
England/QEUH-326EF4B1/2023|OX450101.1|2023-02-28
Australia/VIC83584/2023|EPI_ISL_17656892|2023-04-25
Spain/GA-CHOP-52075926/2023|EPI_ISL_17652467|2023-04-04
Indonesia/JK-CW62-4290/2023|EPI_ISL_17630702|2023-04-03
Indonesia/JK-GS-GSILab-1149437/2023|EPI_ISL_17389725|2023-03-18
Indonesia/JK-GS-GSILab-1149435/2023|EPI_ISL_17389654|2023-03-18
Malaysia/UNIMAS-GHML2130/2023|EPI_ISL_17612373|2023-02-20
Malaysia/UNIMAS-B19277/2023|EPI_ISL_17612344|2023-03-16
Indonesia/JT-Labkes-WGS-23-067/2023|EPI_ISL_17664301|2023-05-01
Indonesia/JK-CW62-3857/2023|EPI_ISL_17012209|2023-02-02
Malaysia/UNIMAS-B19318/2023|EPI_ISL_17612366|2023-04-01

**Comment by FedeGueli** [comment]
thx @AngieHinrichs ! Now everything makes sense. @ryhisner please go on proposing it in the main page.

**Comment by FedeGueli** [comment]
87 seqs @ryhisner did you propose this one then??

**Comment by FedeGueli** [comment]
> Not yet, @FedeGueli. I'll copy and paste this to the main page today though.

Have you checked the tree?? i think the saltation sublineage is not more present and i proposed it separately

**Comment by FedeGueli** [comment]
FP.3
