### ISSUE TITLE
EG.5.1.5 with S:N354K and N:P151S ( 23, Spain, Denmark)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#660]
Defining mutations:
EG.5.1.5 >> T451G > C5878T, T19224C > C9979T, S:N354K (C22624A), N:P151S (C28724T )

Gisaid: C9979T, C22624A,C5878T

Samples: 4 (Spain- 2 regions)
hCoV-19/Spain/AS-HUCA-232345960/2023\|EPI_ISL_18112354\|2023-07-25
hCoV-19/Spain/MD-HGUGM-7539975/2023\|EPI_ISL_18118444\|2023-08-08
hCoV-19/Spain/MD-HGUGM-7539825/2023\|EPI_ISL_18118447\|2023-08-07
hCoV-19/Spain/MD-HGUGM-7539968/2023\|EPI_ISL_18118464\|2023-08-08

Tree:
![Schermata 2023-08-21 alle 16 07 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/88afed99-e673-41b8-9a20-10697f0ac952)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1817_36d850.json?label=id:node_6902677

**Comment by HynnSpylor** [comment]
12 seqs now

**Comment by FedeGueli** [comment]
Catalunya, Canary Isl. , Denmark the last ones 20 now
