### ISSUE TITLE
GA.4 (XBB.1.17.1.4) saltation branch with S:H245Y, S:K478R, S:E554K, S:S704L and N:A208V (5 seqs in US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#661]
Defining mutations:
GA.4>C23673T (S:S704L)>T5290C, C22295T (S:H245Y), A22995G (S:K478R), G23222A (S:E554K), C28896T (N:A208V)
GISAID query: C1670T, A3503G, C22295T, G23222A
Earliest seq: 2023-07-07 (US- EPI_ISL_17996097)
Most recent seq: 2023-08-11 (US- EPI_ISL_18119380)
Countries detected: US (5)

Usher Tree:
<img width="907" alt="屏幕截图 2023-08-21 232346" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/4de4d33e-d8ca-4282-ac31-6adf1bc4dcbe">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_179a2_374c40.json?c=gt-S_245

A Saltation branch for GA.4 (XBB.1.17.1.4, XBB.1.17 sublineage with S:K356T, ORF1a:N1080D and ORF1a:S2553F). S:K478R is popular since XBB.1.16*, and S:E554K also increases recently.

Genomes:
EPI_ISL_17996097, EPI_ISL_17996116, EPI_ISL_18113409, EPI_ISL_18119372, EPI_ISL_18119380

**Comment by aviczhl2** [comment]
Designated GA.4.1

**Comment by FedeGueli** [comment]
Designated GA.4.1
