### ISSUE TITLE
FY.4.1.1 + S:D1139H (51) seq

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#662]
_Gisaid query: G29212A,G24977C
Countries:Usa
Defining FY.4.1.1 >G29212A > C18744T > S:D1139H (G24977C)_  (all edited)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1cca93e2-c38f-4e8d-b672-f4e0a93cc82a)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/415df7f6-fbe3-46cd-ac89-4c9c9d860efa)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ecc6_3cae80.json?c=gt-S_1139&label=id:node_6979613
First Seq: 2023-05-17
Most Recent: 2023-08-05
OR365567.1 OR365554.1 OR447450.1 EPI_ISL_18098637 EPI_ISL_18057101 OR252223.1 EPI_ISL_18099109 EPI_ISL_18098898 EPI_ISL_18098879 EPI_ISL_18057299 EPI_ISL_18099094 EPI_ISL_18057211 EPI_ISL_18098892 EPI_ISL_18098892 EPI_ISL_18098579 EPI_ISL_18098884 OR440128.1 EPI_ISL_18099239 EPI_ISL_18057253 EPI_ISL_18057564

**Comment by FedeGueli** [comment]
Spotted it too, thx for proposing. it seems going well. just edited a bit the proposal
