### ISSUE TITLE
FY.3.1 with ORF1a:I1990V (nsp3_I1172V) and S:Q493L (22 seqs, China, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#665]
**Defining Mutations:** `FY.3.1` > `A6233G(ORF1a:I1990V)` > `A23040T(S:Q493L)`
**Query:** `G4109T, A6233G, A23040T`
**Earliest seq:** 2023-05-03 (`EPI_ISL_18013093`, Wuhu, Anhui, China)
**Latest seq:** 2023-08-08 (`EPI_ISL_18119352`, New York, USA)
**Sampled Countries:** China (11: Anhui/4; Shanghai/3; Guangdong/2; Jiangsu/1; Sichuan/1), USA (2: NY)

<details><summary>Genomes: </summary>

`EPI_ISL_17725309, EPI_ISL_17956841, EPI_ISL_17988946, EPI_ISL_18013093-18013094, EPI_ISL_18013101, EPI_ISL_18034237, EPI_ISL_18037320, EPI_ISL_18074554, EPI_ISL_18105333, EPI_ISL_18108264, EPI_ISL_18119352, EPI_ISL_18121857`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28bae_490cd0.json?f_userOrOld=uploaded%20sample&label=id:node_6986308
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a4beba87-eea6-4005-af01-2508b054ffbe)

**Comment by FedeGueli** [comment]
It seems going and 493 is a key mutation for many aspects of this virus, lets show it to @corneliusroemer and he will weigh it then

**Comment by FedeGueli** [comment]
Thank you
