### ISSUE TITLE
CK.1.1 sublineage with S:V1264L (110 seqs mainly in Japan, still circulating even shows growth advantage) 

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#666]
Defining mutations:
CK.1.1>C26907T>A27753C>G25352T (S:V1264L)
GISAID query: A24129G, G25352T, A27753C
Earliest seq: 2023-02-24 (Japan- EPI_ISL_17265415)
Most recent seq: 2023-08-03 (Japan- EPI_ISL_18122853)
Countries detected: Japan (94), South Korea (1)

Usher Tree:
<img width="707" alt="屏幕截图 2023-08-22 225307" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/b898ae2e-40a7-4b83-8948-dcdde649ee45">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3140c_4c9ea0.json?c=gt-S_1264

In recent 3 months, almost (~95%) CK.1.1 seqs got S:V1264L. It seems very strange that an old BA.5* lineage can still circulate in Japan- Even it shows a 42% growth advantage:
<img width="686" alt="屏幕截图 2023-08-22 225739" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d4680b23-55b2-4117-b6b9-ed8c67707ca3">

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AV1264L&nextcladePangoLineage=CK.1.1*&
And it becomes the second biggest BA.5* lineages in past 3 months:
<img width="698" alt="屏幕截图 2023-08-22 223530" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/8c5edb12-5230-4193-8250-811c08c1bf62">

If we carefully analyze the Usher Tree, the ORF8:P38S may be another key mutations- the branch has increased and circulated since Jun 2023. 5 seqs further get S:L176F.
<img width="911" alt="屏幕截图 2023-08-22 225436" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/014c1147-d531-42f2-ae6b-8820278fed65">

Despite it can not compete with XBB* outside Japan, it still deserves a further tracking.

Genomes:
EPI_ISL_17265415, EPI_ISL_17280829, EPI_ISL_17281014, EPI_ISL_17281546, EPI_ISL_17295219, EPI_ISL_17295221,
EPI_ISL_17387955, EPI_ISL_17388093, EPI_ISL_17388167, EPI_ISL_17463107, EPI_ISL_17495667, EPI_ISL_17495682,
EPI_ISL_17540021, EPI_ISL_17540023, EPI_ISL_17540025-17540027, EPI_ISL_17540176, EPI_ISL_17558606, EPI_ISL_17629485,
EPI_ISL_17630994, EPI_ISL_17631063, EPI_ISL_17631079, EPI_ISL_17637599-17637600, EPI_ISL_17652270, EPI_ISL_17880076,
EPI_ISL_17881491, EPI_ISL_17881691, EPI_ISL_17882706, EPI_ISL_17882776, EPI_ISL_17883773, EPI_ISL_17952860,
EPI_ISL_17973117, EPI_ISL_17973136, EPI_ISL_17980792, EPI_ISL_17982143, EPI_ISL_17985835, EPI_ISL_18006526,
EPI_ISL_18006568-18006569, EPI_ISL_18007023, EPI_ISL_18013331, EPI_ISL_18013347, EPI_ISL_18033119, EPI_ISL_18044112,
EPI_ISL_18051431, EPI_ISL_18051668, EPI_ISL_18051720, EPI_ISL_18056120, EPI_ISL_18060297, EPI_ISL_18060307,
EPI_ISL_18064876, EPI_ISL_18065198, EPI_ISL_18065265, EPI_ISL_18065270, EPI_ISL_18065290-18065291, EPI_ISL_18065909,
EPI_ISL_18066504, EPI_ISL_18067291, EPI_ISL_18067296, EPI_ISL_18067316, EPI_ISL_18071617, EPI_ISL_18082342,
EPI_ISL_18082733, EPI_ISL_18082764, EPI_ISL_18082768, EPI_ISL_18082773, EPI_ISL_18097036, EPI_ISL_18097142,
EPI_ISL_18097384, EPI_ISL_18097395, EPI_ISL_18097408, EPI_ISL_18097447, EPI_ISL_18106312, EPI_ISL_18106326-18106331,
EPI_ISL_18106335, EPI_ISL_18106337-18106339, EPI_ISL_18118051, EPI_ISL_18122670, EPI_ISL_18122733, EPI_ISL_18122817,
EPI_ISL_18122853, EPI_ISL_18122908, EPI_ISL_18122931, EPI_ISL_18122965, EPI_ISL_18122986

**Comment by aviczhl2** [comment]
Worth noting that this lineage has S:144-

**Comment by aviczhl2** [comment]
Worth noting that this lineage also has S:144-.

**Comment by FedeGueli** [comment]
I ve noticed this too last week i got fooled thinking it was CK.1.1.1 , wrong!. Thx for proposing it. It has to say that the most of BA.5 family circulating lineages are in Japan . I dont know why if an island effect or just the fact the BQ wave finished here later than in other parts of the world.

**Comment by HynnSpylor** [comment]
3 more seqs from Japan
BA.5* still persists in Japan may be related to the NPI (e.g. high proportion of wearing mask), then the BA.5* antibodies may be a relatively low coverage and can still circulate.

**Comment by aviczhl2** [comment]
> 3 more seqs from Japan (latest for 2023-08-06) BA.5* still persists in Japan may be related to the NPI (e.g. high proportion of wearing mask), then the BA.5* antibodies may be a relatively low coverage and BA.5* lineages can still circulate.)

This shall not be blamed to masks and "lack of BA.5 infections". Japan already had two huge BA.5* waves. If lack of BA.5 infection causes BA.5 to spread India where BA.5 never spreaded largely there shall face a large BA.5 wave.

**Comment by HynnSpylor** [comment]
110 seqs now and it emerges in US
