### ISSUE TITLE
XBB.2.3.11 sublineage with M:A104V, ORF1a:A181T, ORF3a:G172C, G14268A, and C25701T first detected in France (106 GISAID seqs as of 2023-08-22; Europe, North America, Asia)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#668]
There may be a XBB.2.3.11 sublineage with M:A104V (C26833T), ORF1a:A181T (G806A; NSP2:A1T), ORF3a:G172C (G25906T), G14268A, and C25701T first detected in France. This lineage also appears to have a G->C nucleotide mutation just after the 28362-28370 deletion in ORF9 which may impact ORF9b:V30.

There may be cause to consider designation of one or more intermediate lineages between the parent XBB.2.3.11 lineage and the lineage proposed here.

As of 2023-08-22, Cov-Spectrum reports 60 good-quality (69 total) XBB.2.3.11+M:104V+ORF1a:181T+ORF3a:172C+14268A+25701T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.2.3.11+%26+M%3AA104V+%26+ORF1a%3AA181T+%26+ORF3a%3AG172C+%26+G14268A+%26+C25701T&nextcladeQcOverallScoreTo=29&

There is too little data to reliably determine the growth rate of this lineage in the country (France) where it is most common, but this lineage may be growing fairly rapidly. It has been detected in 12 countries on 3 continents, and as of 2023-08-22 there are significantly more sequences in GISAID than in CoV-Spectrum where data was last updated on 2023-08-19. Possible impacts of non-synonymous mutations on viral relative fitness are discussed below.

As of 2023-08-22, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 2 3 11+M_104V+ORF1a_181T+ORF3a_172C+14286A+25701T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/9783c604-d46a-4be2-aa55-451cca3d3119)

To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_XBB.2.3.11%2BM_104V%2BORF1a_181T%2BORF3a_172C%2B14286A%2B25701T.json?c=gt-ORF3a_172&label=id%3Anode_7356980

GISAID query: C26833T, G806A, G25906T, G14268A, C25701T

First GISAID sequence: Ile-de-France, France 2023-05-22 

Most Recent GISAID sequence: Ontario, Canada 2023-08-14

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-XBB.2.3.11+M_104V+ORF1a_181T+ORF3a_172C+14286A+25701T.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12414236/Support-XBB.2.3.11%2BM_104V%2BORF1a_181T%2BORF3a_172C%2B14286A%2B25701T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.2.3.11+M_104V+ORF1a_181T+ORF3a_172C+14268A+25701T.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12414239/gisaid-epi-isl-XBB.2.3.11%2BM_104V%2BORF1a_181T%2BORF3a_172C%2B14268A%2B25701T.txt)

Potential effects of the non-synonymous mutations on viral relative fitness
-------------------------------------------------------------------------------------------------

Now to consider the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations in their order on the UShER tree:

For M:A104V,

clade,gene,aa_mutation,delta_fitness
20A,M,A104V,-1.3216
20B,M,A104V,0.096687
20C,M,A104V,-0.75338
20E,M,A104V,-0.1322
20G,M,A104V,-0.31455
20I,M,A104V,0.075529
21C,M,A104V,-0.16369
21I,M,A104V,-1.5489
21J,M,A104V,-1.5756
21K,M,A104V,-0.012062
21L,M,A104V,-0.034943
22A,M,A104V,0.1043
22B,M,A104V,-0.0039761
22C,M,A104V,0.0066427
22D,M,A104V,0.13321
22E,M,A104V,-0.45698
22F,M,A104V,0.51454
23A,M,A104V,0.59722

M:A104V exhibits sign epistatis between clades with a positive delta_fitness in the XBB clades for which data is available 22F and 23A.

For ORF1a:A181T (NSP2:A1T),

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,A181T,0.4541
20B,ORF1ab,A181T,-0.12603
20C,ORF1ab,A181T,0.69026
20E,ORF1ab,A181T,-1.4323
20G,ORF1ab,A181T,-0.71803
20I,ORF1ab,A181T,0.64
21C,ORF1ab,A181T,-0.048028
21I,ORF1ab,A181T,0.075645
21J,ORF1ab,A181T,0.20418
21K,ORF1ab,A181T,0.74246
21L,ORF1ab,A181T,0.70443
22A,ORF1ab,A181T,-0.27274
22B,ORF1ab,A181T,0.29769
22C,ORF1ab,A181T,0.30749
22D,ORF1ab,A181T,0.92246
22E,ORF1ab,A181T,-0.34493
22F,ORF1ab,A181T,-0.30134
23A,ORF1ab,A181T,0.11896

ORF1a:A181T also exhibits sign epistatus between clades with weakly mixed delta_fitness in the XBB clades 22F and 23A.

For ORF3a:G172C,

clade,gene,aa_mutation,delta_fitness
20A,ORF3a,G172C,0.87255
20B,ORF3a,G172C,1.3092
20C,ORF3a,G172C,0.99406
20E,ORF3a,G172C,0.58623
20I,ORF3a,G172C,1.1417
21C,ORF3a,G172C,1.007
21I,ORF3a,G172C,0.53968
21J,ORF3a,G172C,1.0177
21K,ORF3a,G172C,1.3135
21L,ORF3a,G172C,0.67395
22A,ORF3a,G172C,0.94976
22B,ORF3a,G172C,0.88703
22C,ORF3a,G172C,-0.30292
22D,ORF3a,G172C,0.51675
22E,ORF3a,G172C,0.50294
22F,ORF3a,G172C,1.5038
23A,ORF3a,G172C,0.36773

ORF3a:G172C provides positive delta_fitness to varying degrees, except in Clade 22C (BA.2.12.1) including a decently strong positive delta_fitness in Clade 22F (parental XBB).

Considering the fitness effects of the non-synonymous mutations, this lineage could plausibly have a growth advantage especially if the advantage from ORF3a:G172C holds in the not-yet-measured Clade 23E (XBB.2.3).

**Comment by alurqu** [comment]
It may be just an oddity, but I just realized that all of the (first 9) BA.2.86 sequences have M:A104V.

Until recently, the only lineage with M:A104V at >= 50% prevalence appears to have been BQ.1.32.

**Comment by FedeGueli** [comment]
GS.4 via https://github.com/cov-lineages/pango-designation/commit/3760d6c5452a7ac689732c489f8a8ccd1c189b0b

**Comment by alurqu** [comment]
ORF3a:G172C to a sublineage with S:N185D also designated as GS.4.1. I would have made a designation node at https://github.com/cov-lineages/pango-designation/commit/5dde128ae6d61a3b6f10277dc227f63906f7a7e3 due to the branching from that point, but oh well.

**Comment by MCB6** [comment]
It appears to have reached domination in Ukraine.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/93294184/bac34c82-a80c-47c7-8454-b0c3d62d79f7)

**Comment by FedeGueli** [comment]
> It appears to have reached domination in Ukraine. ![image](https://user-images.githubusercontent.com/93294184/284029615-bac34c82-a80c-47c7-8454-b0c3d62d79f7.png)

Thx another country after India and Philippines with XBB.2.3 on the lead.
