### ISSUE TITLE
GK.1.1 (XBB.1.5.70 + S:T573I, S704L) Sublineage with S:K356T (11 seq, 8 countries / Nov 29)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#671]
### **Description**
**Sub-lineage of:** GK.1.1 (XBB.1.5.70.1.1)
**Earliest sequence:** 2023-7-25, Switzerland – EPI_ISL_181229953
**Most recent sequence:** 2023-7-27, Switzerland – EPI_ISL_18129925
**Countries circulating:** Switzerland (2)
**Number of Sequences:** 2
**GISAID Nucleotide Query:** G376T, G1820A, A22629C
**CovSpectrum Query:** Nextcladepangolineage:GK.1.1* & A22629C & [3-of: G376T, G1820A, A2254G, G12442A, A20814G, G28048T]
**Substitutions on top of GK.1.1:**
**Spike:** K356T
**ORF1a:** E37D, G519S
**ORF8:** R52I
**Nucleotide:** G376T, G1820A, A2254G, G12442A, A20814G, A22629C, G28048T
 
**Phylogenetic Order of Mutations:** G12442A  **→**  G376T, A2254G, A20814G, G28048T (ORF1a:E37D, ORF8:R52I)  **→**  G1820A (ORF1a:G519S)  **→**  A22629C (S:K356T)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/GK.1.1_K356T.json?c=gt-S_356&label=id:node_7205217

<img width="1300" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/87e2a8b6-1264-475c-9a5a-76dd7921d642">

**Evidence**
With L455F, F456L, and now K356T, this looks like it could be the most immune-evasive RBD on an XBB* lineage yet. S:K356T adds a glycan and is a sotrovimab (Xevudy) escape mutation. Not much more to add really. Only detected in Switzerland so far, so there's a good chance it will fizzle and die. 

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18129925, EPI_ISL_18129953
</details>

**Comment by aviczhl2** [comment]
Shall be T573I

**Comment by krosa1910** [comment]
Shall be 573I, still this is very similar to the XBB.1.5.44 I proposed month ago (572I+356T).

**Comment by FedeGueli** [comment]
third from Germany

**Comment by FedeGueli** [comment]
Super slow closing it.

**Comment by FedeGueli** [comment]
5 now but collected last time in mid september.

**Comment by FedeGueli** [comment]
10

**Comment by FedeGueli** [comment]
4 last seqs from 4 different countries , reopening for a while to monitor it.
