### ISSUE TITLE
Triple spike mutations S:K182E,S:V551I,S:E554K for a saltation XBB.1.16 sublineage emerging in MH, India (12 seqs , 2 countries)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#672]
I was monitoring this for a while with the wrong query so i didnt realize it was growing .

Defining mutations:
XBB.1.16 >> > C29386T > A25410G > Orf1a:P748L (T2242C),Orf1a:E972K (C2508T), G3179A, S:K182E (A22106G), S:V551I (G23213A), S:E554K (G23222A)

Tree:
![Schermata 2023-08-24 alle 16 48 14](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/afb66891-1717-45c3-9808-2a5f0cc7a25e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19e92_768140.json?c=gt-S_182,551,554&label=id:node_6839462

Gisaid query: T2242C, G3179A,A25410G

Samples: 10 from MH, India (9) , Penn.,Us (1)
First  from MH collected on 2023-04-28
Last from MH collected on 2023-08-12
EPI_ISL_17686342, EPI_ISL_17978171, EPI_ISL_18094379,
EPI_ISL_18094384-18094385, EPI_ISL_18120269, EPI_ISL_18120320,
EPI_ISL_18121354, EPI_ISL_18128324-18128325

**Comment by FedeGueli** [comment]
2 earlier samples  collected from Gujarat. 

@ryhisner @ryhisner @aviczhl2 @nkrmnzr @Sinickle  this represent around 5% of recent (from july ahead) samples from India maybe worthto move it to main page?
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ddef_9bebd0.json?label=id:node_10773846
![Schermata 2023-08-26 alle 11 01 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/42a04c54-b89a-4529-8418-381884dc41b5)

**Comment by aviczhl2** [comment]
8/116 of India's seqs from 2023-7-1. Yes it is taking some share. (mostly MH)

**Comment by HynnSpylor** [comment]
Yes it has notable advantage.

**Comment by FedeGueli** [comment]
Thank you for your kind answers i will try tomorrow .

**Comment by ryhisner** [comment]
I agree with the others. There are >1 billion people in India, so anything that makes up >5% of sequences there and has spread internationally deserves a proposal.

**Comment by FedeGueli** [comment]
Thx everyone proposed in the main page.

**Comment by FedeGueli** [comment]
Deignated XBB.1.16.24 via https://github.com/cov-lineages/pango-designation/commit/68ae5bfcd50c2eed683568680fbdef2f8ddb011b
