### ISSUE TITLE
XBC.1.3 (a sublineage of #542) with S:R346S (45 seqs, mainly in Australia, +1 Denmark)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#673]
**Defining Mutations:** `XBC.1.3` > `G15743A(ORF1b:S759N)` > `C6145T` > `C12786T(ORF1a:T4174I)` > `C1628A(ORF1a:Q455K)` > _A25910G(ORF3a:D173G)_ > `T6447C(ORF1a:V2061A)` > `A3063T(ORF1a:E933V)` > _G25910A_rev(ORF3a:G173D_rev)_ > `A460G, A22600T`(**S:R346S**)

_or_ #542 > _G25910A_rev(ORF3a:G173D_rev)_ > `A460G, A22600T`(**S:R346S**)

**Query:** `C6145T, G15743A, A22600T`
**Earliest seq:** 2023-06-21 (`EPI_ISL_17999688`, Western Australia)
**Latest seq:** 2023-08-14 (`EPI_ISL_18127948`, Western Australia)
**Sampled Countries:** Australia (9: WA/8; QLD/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17999688, EPI_ISL_17999786, EPI_ISL_18077570, EPI_ISL_18118094, EPI_ISL_18118098, EPI_ISL_18118114, EPI_ISL_18127903, EPI_ISL_18127914, EPI_ISL_18127948`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e91f_77f350.json?c=gt-nuc_22600,25910&f_userOrOld=uploaded%20sample&label=id:node_6405132

view from XBC.1.3 polytomy with filter of `nuc 22600/Spike_346` and `nuc 25910/ORF3a_173`
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f5c7cb0e-d62d-4d2e-8b34-2b2f4e3407d0)

details, there's `ORF3a:D173G` flip-flop here and there
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/47e1f225-fcc3-4669-b739-63653a97ccfd)

**Comment by FedeGueli** [comment]
11 now. too slow to count. XBC.1.3 uses other strategies to go on spreading.

**Comment by FedeGueli** [comment]
please propose it.

**Comment by FedeGueli** [comment]
Designated KD.1 via https://github.com/cov-lineages/pango-designation/commit/b81fd891f05cc3f2568cb9e9828f88350028af78#commitcomment-133981259
