### ISSUE TITLE
XBB.2.3.3 Sublineage with S:F456L, M:G6S, ORF1a:T891I, ORF1a:Y1814C (+ S:S494P branch) (7 seq, 4 countries, Sept.23)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#675]
### **Description**
**Sub-lineage of:** XBB.2.3.3
**Earliest sequence:** 2023-7-31, India, Maharashtra — EPI_ISL_18120271, EPI_ISL_18120272
**Most recent sequence:** 2023-8-8, Singapore (local case) — EPI_ISL_18127408
**Countries circulating:** India (2), Singapore (1)
**Number of Sequences:** 3
**GISAID Nucleotide Query:** C2937T, A5706G, G6536A
**CovSpectrum Query:** Nextcladepangolineage:XBB.2.3* & [3-of: C2937T, A5706G, T22930A, G26538A]
**Substitutions on top of XBB.2.3.3:**
**Spike:** F456L
**M:** G6S
**ORF1a:** T891I, Y1814C
**Nucleotide:** C2937T, A5706G, T22930A, G26538A
 
**Phylogenetic Order of Mutations:** A5706G (ORF1a:Y1814C) **→** C2937T, T22930A, G26538A (ORF1a:T891I, S:F456L, M:G6S)
**Further Mutations in S:S494P Branch:**  **→** T17863C, T23042C, G29711C (ORF1b:Y1466H/NSP13_Y543H, S:S494P, 5' UTR)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.2.3.3_F456L_M-G6S_ORF1a-T891I_ORF1a-Y1814C.json?c=gt-nuc_26538&label=id:node_7360913

<img width="1364" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/147fb814-1c5e-4e13-930d-b1ad1e2930ee">
 

**Evidence**
There are only three sequences here, but the two in Maharashtra may represent a much larger number present in that region, which has a population of over 110 million. The sequence in Singapore indicates that it is likely at least somewhat widespread in Maharashtra and perhaps other regions of India. There have only been 97 legible sequences from all of India with collection dates of July 1 or later and just 38 since July 30, so these two Indian sequences make up a substantial proportion of recent Indian sequences.
 
M:G6S is present in a number of divergent sequences. I believe this region of spike projects outside of the virion, so mutations from M:2-20 or so are probably antigenic mutations.
 
The Indian branch also has S:S494P, ORF1b:Y1466H/NSP13_Y543H, and a 5' UTR mutation with G27911C.
 
You can see that below this branch, there is another fascinating branch with S:N87K, S:L452Q, and S:K478N with two sequences. One is from several months ago, but another was collected July 31 and has several additional mutations, including S:A397V and an apparent 10-nucleotide enlargement of the standard BA.2* s2m deletion—∆29725-29760 instead of the usual ∆29734-29759. With just one recent sequence, it's not deserving of even a pre-proposal, but it bears watching.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18120271, EPI_ISL_18120272, EPI_ISL_18127408
</details>

**Comment by FedeGueli** [comment]
I just noticed this is sibling lineage of https://github.com/sars-cov-2-variants/lineage-proposals/issues/739

**Comment by FedeGueli** [comment]
It doesnt seem fast but was sampled in two more countries Denmark and Netherlands
