### ISSUE TITLE
GK.3+S:T572I in USA( 27 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#677]
GK.3+C26801T+C21306T+C23277T,C4189T(S:T572I)

GISAID query: C26801T,C21306T,C23277T,C4189T,G2891T
No. of seqs: 10(USA, 7 states)

First: EPI_ISL_18081333, Michigan, 2023-7-13
Latest: EPI_ISL_18133573, Arizona, 2023-8-16

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_972e_81ab40.json?label=id:node_7209127)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b4f85637-be5d-4275-b73f-85a721cd3ced)

**Comment by aviczhl2** [comment]
19, Canada.

**Comment by FedeGueli** [comment]
Propose it once 25 thank you.

**Comment by FedeGueli** [comment]
+2 Oregon, Arizona
