### ISSUE TITLE
EG.5.1.1 sublineage with S:L452R ( 9 seqs in China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#678]
Defining mutations:
EG.5.1.1>C11779T>T22917G (S:L452R)
GISAID query: C11779T, G13627A, T22917G
Earliest seq: 2023-06-08 (Shanghai Municipality, China- EPI_ISL_17836953)
Most recent seq: 2023-07-31 (Sichuan Province, China- EPI_ISL_18134006)
Countries detected: China (6)

Usher Tree:
![QQ截图20230825135025](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/743c564b-8f62-4d32-884d-833643355a26)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_addc_83eb80.json?c=gt-S_452
S:L452R is popular for a long time. In neighbored branch, it is also found in EG.5.1.6.1 (HV.1)

Genomes:
EPI_ISL_17836953, EPI_ISL_18060842, EPI_ISL_18108671, EPI_ISL_18133981-18133982, EPI_ISL_18134006

**Comment by FedeGueli** [comment]
great catch lets see how it goes in comparison to HV.1

**Comment by FedeGueli** [comment]
it seems slow! but still circualting likely in area not well sampled in China

**Comment by FedeGueli** [comment]
closing it for now
