### ISSUE TITLE
JD.1.1 (S:A475V + FLip proposed in #2174) Sublineage with S:S446I (8 seq, Aug 25)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#679]
**Description**
**Sub-lineage of:** JD.1 (XBB.1.5.102 + FLip) + S:A475V (Proposed in [#2174](https://github.com/cov-lineages/pango-designation/issues/2174))
**Earliest sequence:** 2023-7-25, Spain, Extremadura —EPI_ISL_18072815, EPI_ISL_18072823, EPI_ISL_18072824
**Most recent sequence:** 2023-8-21, Spain, Basque Country — EPI_ISL_18134783
**Countries circulating:** Spain (8)
**Number of Sequences:** 8
**GISAID Nucleotide Query:** C19185T, C11681T, C14189T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.5* & [3-of: C19185T, C11681T, C14189T]
**Substitutions on top of XBB.1.5:**
**Spike:** S446I, A475V
**ORF8:** A65V
**ORF1b:** A241V (NSP12_A250V)
**Nucleotide:** C11681T, C14189T, G22899T, C19185T, C22986T, C28087T,
 
**Phylogenetic Order of Mutations:** C14189T (ORF1b:A241V/NSP12_A250V)  **→**  C28087T (ORF8:A65V)  **→**    C19185T, C22986T (S:A475V)  **→**  C11681T, G22899T (S:S446I)  

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/JD.1_A475V_S446I.json?c=gt-nuc_11681&label=id:node_7177834 
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/121df5c0-509e-47d7-8580-d53297ad5d3e">

**Evidence**
The S:A475V branch of JD.1 has already been noted by @FedeGueli here[ https://github.com/cov-lineages/pango-designation/issues/2071#issuecomment-1683487985](https://github.com/cov-lineages/pango-designation/issues/2071#issuecomment-1683487985) and by @oobb45729 here[ https://github.com/sars-cov-2-variants/lineage-proposals/issues/643](https://github.com/sars-cov-2-variants/lineage-proposals/issues/643) .

I assume that one will soon be designated, if it hasn't been already been. The S:S446I branch is a little less apparent, primarily because half the sequences have no coverage in the entire RBD. I suppose it's possible that these sequences lack S:S446I, but I doubt it. Luckily, they all share the synonymous mutation C11681T, which is not shared by any other sequences in this lineage. Every sequence with C11681T that has RBD coverage also has S:S446I, hence my assumption that the ones with no coverage also have it. (Note also that the majority of the sequences here allegedly have an ORF8:V65A "reversion," but this is almost certainly a sequencing artifact.)

It seems possible that the combination of FLip (S:L455F, F456L) somehow makes S:S446I more favorable. The S446I-L455F-F456L combination has now appeared independently at least four times: in this lineage, in a very recent GK.1 sequence from Brazil (EPI_ISL_18113536), in a DV.7.1 (EPI_ISL_18078439), and in an EG.5.1.1 sequence from Sichuan, China (EPI_ISL_18012368). Apart from the EG.5.1 singlet from China (which was collected July 5), the collection dates for all of these are either late July or August, so this could be the early stages of an emerging trend.

<img width="957" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6bcf8a6e-be07-45ea-aecb-ae150dd2f387">
  
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18072815, EPI_ISL_18072818, EPI_ISL_18072823, EPI_ISL_18072824, EPI_ISL_18119237, EPI_ISL_18119241, EPI_ISL_18134783,EPI_ISL_18134811
</details>

**Comment by FedeGueli** [comment]
Hy @ryhisner thx for proposing it , i made minor updates cause it is a sublieage of your https://github.com/cov-lineages/pango-designation/issues/2174 !

**Comment by FedeGueli** [comment]
Parental now designated JD.1.1

**Comment by FedeGueli** [comment]
no new sequences added closing for now

**Comment by FedeGueli** [comment]
+1 Spain
