### ISSUE TITLE
FL.2 (XBB.1.9.1.2) sublineage with S:141-144del (86 seqs in China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#68]
Defining mutations: FL.2>C29353T>C23191T>del21983-21991 (S:141-143del) (Usher can not show, but both the 4-aa del and Y144del only are on the branch).
GISAID query: C23191T, C29353T, Spike_G142del
Earliest seq: 2023-04-17 (Qinghai Province, China, EPI_ISL_17584972)
Most recent seq: 2023-05-03 (Heilongjiang Province, China, EPI_ISL_17645644)
Countries detected: China (27, Qinghai Province 23, Shanghai Municipality 1, Jiangsu Province 1, Gansu Province 1, Heilongjiang Province 1)

Usher Tree (Red points are S:141-144del, and the branch also has some S:Y144del only)

 
![QQ截图20230517223852](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/ea91c123-df74-4789-a44a-a4f6e0fe8407)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9956_4d1660.json

A very strange 4-aa deletion at site S:141-144, despite the S:Y144del is very common. I also note some other scattered seqs in Europe with S:141-144del (not on this branch).  
![QQ截图20230517215204](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/8ea211e0-22fe-4f0a-a054-afc1deb4f5be)

I'd like to ask for help to confirm whether they are artefacts. @corneliusroemer @FedeGueli

Genomes:
EPI_ISL_17584972, EPI_ISL_17618328, EPI_ISL_17618672, EPI_ISL_17637386, EPI_ISL_17645644, EPI_ISL_17652400, 
EPI_ISL_17652408-17652410, EPI_ISL_17652413, EPI_ISL_17652416-17652417, EPI_ISL_17652419, EPI_ISL_17652422-17652423, EPI_ISL_17652426, EPI_ISL_17652428, EPI_ISL_17652430-17652431, EPI_ISL_17652434, EPI_ISL_17672068, EPI_ISL_17672070, EPI_ISL_17672072-17672076,

**Comment by FedeGueli** [comment]
29 as today. Slow.

**Comment by HynnSpylor** [comment]
Now Qinghai Province updated 21 seqs. But it seems highly concentrated in Qinghai.

**Comment by HynnSpylor** [comment]
65 seqs now, and it is still highly concentrated in Qinghai Province (like BA.5.2.49*）

**Comment by Over-There-Is** [comment]
81 now

**Comment by FedeGueli** [comment]
no new seq from Qinqhai. lets wait the next upload from there. it seems very slow anyway

**Comment by Over-There-Is** [comment]
83 now

**Comment by Over-There-Is** [comment]
85

**Comment by FedeGueli** [comment]
closing for now.
