### ISSUE TITLE
XBB.1.5 with ORF1b:V222I (nsp13_V231I), S:E554K, S:G184V, S:Q607K and S:T478R (20 seqs, South Africa, Turkey ,Spain, India, Ireland, Germany, UK, Netherlands, Sweden)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#680]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `G14131A(ORF1b:V222I)` > `C7609T, G23222A(S:E554K)` > `T5065C` > `G7936T, G22113T(S:G184V), C23381A(S:Q607K)` > `C22995G(S:T478R)`
**Query:** `T5065C, G7936T, C22995G`
**Earliest seq:** 2023-06-13 (`EPI_ISL_17964551`, Bavaria, Germany)
**Latest seq:** 2023-07-29 (`EPI_ISL_18118301`, Castilla y León, Spain)
**Sampled Countries:** Spain (3), India (2), Germany (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17964551, EPI_ISL_18052815, EPI_ISL_18118257, EPI_ISL_18118301, EPI_ISL_18118320, EPI_ISL_18120266`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_190d6_87d5c0.json?c=gt-S_554,607,478&label=id:node_7318321

view from `ORF1b:V222I` branch
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1424d8f1-bbdc-400b-846e-fdc15574920d)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b96cb857-46d6-4de4-875d-e1a1d0dcb848)

**Trivia:**
- This one with many spike mutations is jumping fast from the tracking list, but too early and too few seqs to tell.
- Some of the samples don't seem to have good QC.

**Comment by FedeGueli** [comment]
just saw the indian sample too. it is hard to tell but maybe circualting much mre than waht we see from nmbr of sequence.

**Comment by FedeGueli** [comment]
Once reached 10 you can propose it. Please specifiy that is likely coming from india .

**Comment by FedeGueli** [comment]
It slowed down, keeping it open due the fact it could be more spread in an undersampled area. SO please dont propose it even it reaches 10.

**Comment by FedeGueli** [comment]
> no more sequences

thank you for tracking. i am planning a big closing day when Hk.3 reaches 25% but everything is too slow to compete also in the short term is good to be closed if it has no special mutations or combo.

**Comment by FedeGueli** [comment]
Slow but worth tracking it.

**Comment by FedeGueli** [comment]
+1 Turkey. reopening for a short while

**Comment by FedeGueli** [comment]
+1 South Africa

**Comment by FedeGueli** [comment]
20 now but all oldies, closing it
