### ISSUE TITLE
Two FL.16 (S:215V)+S:F456L branches (32 seqs and 54 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#681]
Branch 1: FL.16+T22928C(S:F456L)

GISAID query: A22206T,T22928C,C3511T,-10003,-3177
No. of seqs: 9(Japan 6 China 2 USA 1 )

First: EPI_ISL_18012994, Japan ,2023-6-29
Latest: EPI_ISL_18123207, Japan, 2023-8-14

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice28_genome_233ee_870400.json?branchLabel=none&gt=S.456L&label=id:node_10765742)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ccfe7f32-b45c-4004-97fb-f6959ccffee4)

Branch 2: FL.16+C29530T+T10003G,C10798T,T22928C(S:F456L)
No. of seqs: 4(UK 3 Spain 1)
One UK seq not on GISAID

GISAID query: A22206T,T22928C,C3511T,T10003G

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice28_genome_233ee_870400.json?branchLabel=none&label=id:node_6897622)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/59847190-4c96-4a1d-9f75-80ca973804d9)

**Comment by aviczhl2** [comment]
Branch 2 USA+2
Branch 1 +5 Japan,China

**Comment by aviczhl2** [comment]
Branch 2 Canada+3

**Comment by aviczhl2** [comment]
There seems to be a Canadian cluster for branch 2, making it 39.

**Comment by FedeGueli** [comment]
re put it under close monitoring to watch as it will evolve

**Comment by FedeGueli** [comment]
Branch 1 slow
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=A22206T%2CT22928C%2CC3511T%2C3177C%2C10003T&analysisMode=CompareToBaseline&

Branch 2 reached 48 (not just Canada): https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=A22206T%2CT22928C%2CC3511T%2CT10003G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
few recent samples closing it
