### ISSUE TITLE
EG.5.1 Sublineage w/new S2' FCS—S:P812R, ORF3a:A98V, ORF1a:F2334L, ORF1b:S997L (Denmark, 6 seq, Sept 09)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#682]
### **Description**
**Sub-lineage of:** EG.5.1
**Earliest sequence:** 2023-7-31 — EPI_ISL_18130335, EPI_ISL_18130353
**Most recent sequence:** 2023-8-7 — EPI_ISL_18130314, EPI_ISL_18135305, EPI_ISL_18135340
**Countries circulating:** Denmark (5)
**Number of Sequences:** 5
**GISAID Nucleotide Query:** C15763T, C16457T, C23997G
**CovSpectrum Query:** Nextcladepangolineage:
**Substitutions on top of EG.5.1:**
**Spike:** P812R
**ORF3a:** A98V
**ORF1a:** F2334L
**ORF1b:** S997L
**Nucleotide:** T7265C, C15763T, C16457T, C23997G, C25685T
 
**Phylogenetic Order of Mutations:** T7265C, C25685T (ORF3a:A98V, ORF1a:F2334L)  **→**   C16457T (ORF1b:S997L)  **→**  C15763T, C23997G (S:P812R)  

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.5.1_P812R__S2'_FCS.json?c=gt-nuc_23997&label=id:node_6908166

<img width="1267" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/424de450-2ec4-4595-8143-17704421fdd8">

**Evidence**
This is the second multiple-sequence, S:P812R lineage in the past week to emerge from Europe. As I understand it, S:P812R often emerges in cell culture studies, but it has been quite rare in circulating lineages. As stated previously, @ThomasPeacock explained to use that S:P812R creates a new furin-cleavage site (FCS) but at the S2' location in spike instead of the S1/S2 spot. See his explanation at Pango Github issue #1627 here:[ https://github.com/cov-lineages/pango-designation/issues/1627](https://github.com/cov-lineages/pango-designation/issues/1627) . In that issue, the only heretofore known S:P812R lineage with significant circulation was designated.
 
Do recent XBB lineages perhaps create a spike environment more favorable to S:P812R and the novel FCS it creates? Or perhaps there is something about the current level and type of population immunity that favors S:P812R? Too soon to tell, really. This could be a random blip. But the independent evolution of S:P812R in two unrelated XBB* lineages (the other being XBB.2.3.3) is certainly unexpected.
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18130314, EPI_ISL_18130335, EPI_ISL_18130353, EPI_ISL_18135305, EPI_ISL_18135340
</details>

**Comment by FedeGueli** [comment]
It seems super slow! (or super mild ?) closing for now

**Comment by ryhisner** [comment]
Yeah, agree. Weird how two lineages with P812R popped up all at once, then almost instantly disappeared.
