### ISSUE TITLE
HV.1 sublineage with ORF1a:T4083M first detected in California, USA (52 GISAID seqs as of 2023-08-30; USA, Canada, China, Ecuador)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#683]
There may be a HV.1 sublineage with ORF1a:T4083M (C12513T; NSP8:T141M) first detected in Arizona, USA.

As of 2023-08-25, Cov-Spectrum reports 21 good-quality (22 total) HV.1+ORF1a:4083M sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AHV.1+%26+ORF1a%3AT4083M&nextcladeQcOverallScoreTo=29&

There are not yet enough sequences to reliably estimate a growth advantage, but this lineage is a sublineage of a fast parent lineage, has spread to 3 countries on 2 continents including 2 non-adjacent Canadian provinces and 17 American states, has additional sequences appearing in GISAID, and it has an additional mutation ORF1a:T4083M (aka NSP8:T141M) that Bloom and Neher's estimates show as providing a growth advantage in all clades.

As of 2023-08-25, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_HV 1+ORF1a_4083M](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/8c665d9f-52d5-4e1e-956a-a4e18b497599)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_HV.1%2BORF1a_4083M.json?c=gt-ORF1ab_4083&label=id%3Anode_6908889

GISAID query: Spike_F486P, Spike_F456L, Spike_Q52H, Spike_F157L, NSP3_S1039L, Spike_L452R, NSP8_T141M
Nucleotides only Query:  C12513T,C22033A, C5835T (Edited)

First GISAID sequence: California, USA 2023-07-24 

Most Recent GISAID sequence: North Carolina, USA 2023-08-15

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-HV.1+ORF1a_4083M.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12441769/Support-HV.1%2BORF1a_4083M.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-HV.1+ORF1a_4083M.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12441771/gisaid-epi-isl-HV.1%2BORF1a_4083M.txt)

Potential effects of the non-synonymous mutation on viral relative fitness
-------------------------------------------------------------------------------------------------

Now to consider the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations in their order on the UShER tree:

For ORF1a:T4083M,

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,T4083M,1.3672
20B,ORF1ab,T4083M,1.2216
20C,ORF1ab,T4083M,1.308
20E,ORF1ab,T4083M,1.2706
20G,ORF1ab,T4083M,1.5972
20I,ORF1ab,T4083M,0.97347
21C,ORF1ab,T4083M,1.6464
21I,ORF1ab,T4083M,1.2674
21J,ORF1ab,T4083M,1.3126
21K,ORF1ab,T4083M,1.1227
21L,ORF1ab,T4083M,0.62093
22A,ORF1ab,T4083M,0.57972
22B,ORF1ab,T4083M,0.98779
22C,ORF1ab,T4083M,0.64668
22D,ORF1ab,T4083M,0.27632
22E,ORF1ab,T4083M,0.82636
22F,ORF1ab,T4083M,1.0486
23A,ORF1ab,T4083M,0.63056

**Comment by FedeGueli** [comment]
Orf1a:T4083M was also in some AY.4 sublineages very homoplasic on that backbone.

**Comment by FedeGueli** [comment]
![Schermata 2023-08-25 alle 22 11 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/45cdf50b-c822-4437-8c11-63158c463c81)
I looked back at 2021 it seems it gave a substantial advantage over Delta baseline (in the pic is Denmark)

**Comment by FedeGueli** [comment]
Already up to 43 multiple american states and Ontario

**Comment by FedeGueli** [comment]
49 now. @alurqu i urge you to propose it.

**Comment by jasondorjeshort** [comment]
The recent growth of HV.1 is as out-of-the-blue as it is rapid.  While it's not certain that this is real, attention needs to be given not just to its descendants but to any other S:452R sequences popping up.

XBB+S:452R has never been competitive before, and now it's outgrowing everything else by 30-50% a week on quite limited sampling.  This lineage is also unusual in that it seemingly originates in a country with good sequencing, giving a very good view of its growth.  At 99 US sequences the lineage is not quite in range of reliable models, yet it models as becoming the most numerous US lineage within about 3 weeks with roughly weekly doubling.  It could be driven by substantial immune escape, unlike other currently fast-growing lineages.  But all that makes no sense given that other XBB+452R lineages have appeared and simply not grown.

HV.1*+ORF1a:T4083M is 0.6% of all US sequences in the most recent cov-spectrum interval.

![United States-log-fit](https://github.com/sars-cov-2-variants/lineage-proposals/assets/17172327/630fa428-1848-444a-b50d-362b2370a950)
