### ISSUE TITLE
FY.4.1.2 sublineage with S:G184S (21 seqs in Us, UK and Denmark)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#684]
Defining mutations:
FY.4.1>C9042T (ORF1a:S2926F)>A21137G (ORF1b:K2557R), C23638T, T24091C>G22112A (S:G184S)
GISAID query: G22112A, T22913C, T24091C 
Earliest seq: 2023-07-14 (England, UK- EPI_ISL_18056718)
Most recent seq: 2023-08-07 (Denmark, EPI_ISL_18135292) / 2023-08-14 (Wales, UK-CLIMB-CM7Y844F/2023)
Countries detected: UK (4), Denmark (1) on GISAID, Notice that Genbank shows 1 more seq in Wales, UK 

Usher Tree:
![QQ截图20230826005625](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/a9679a72-c7ec-4a18-a168-af93c933324a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d2ed_8a4d60.json?c=gt-S_184
S:G184S was very scattered in many lineages with low proportion.  It may slightly increase the fitness. 
![QQ截图20230826005939](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/745c975b-c15c-461a-925e-badb50a0f95b)

Genomes:
EPI_ISL_18056718, EPI_ISL_18072086, EPI_ISL_18094258, EPI_ISL_18130672, EPI_ISL_18135292

**Comment by FedeGueli** [comment]
+ 3 Uk

**Comment by Over-There-Is** [comment]
Parental branch has been designated as FY.4.1.2.

**Comment by FedeGueli** [comment]
Some recent samples from England

**Comment by FedeGueli** [comment]
No chance to compete :https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G22112A%2CT22913C%2CT24091C&analysisMode=CompareToBaseline&
