### ISSUE TITLE
XBB.1.16 with S:L455F and S:F456L (5 seqs, China)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#686]
**Defining Mutations:** `XBB.1.16` > `G22927T(S:L455F), T22928C(S:F456L)`
**Query:** `G22927T, T22928C, T28297C, C29386T, -T4491A, -T9622C`
**Earliest seq:** 2023-07-03 (`EPI_ISL_18037229`, Guangdong, China)
**Latest seq:** 2023-08 (`EPI_ISL_18133903`, Anhui, China)
**Sampled Countries:** China (5: Anhui/4; Guangdong/1)

<details><summary>Genomes: </summary>

`EPI_ISL_18037229, EPI_ISL_18133816, EPI_ISL_18133848, EPI_ISL_18133872, EPI_ISL_18133903`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_720f_8de2d0.json?label=id:node_10765450
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/efd4d9f3-3b77-4bff-83ec-a35e70ff807f)

**Comment by FedeGueli** [comment]
Already proposed by @avichz2l one minute before you!

**Comment by FedeGueli** [comment]
You all are wonderful really.
