### ISSUE TITLE
XBB.1.16.21 sublineage with ORF1a:G963D first detected in Utrecht, Netherlands (73 GISAID seqs as of 2023-09-23; UK, Switzerland, USA, Canada, Belgium, Netherlands, Italy, Germany, Ireland, Portugal)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#688]
There may be a XBB.1.16.21 sublineage with ORF1a:G963D (G3153A; NSP3:G145D) first detected in Utrecht, Netherlands.

As of 2023-08-25, Cov-Spectrum reports 23 good-quality (24 total) XBB.1.16.21+ORF1a:963D sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.1.16.21+%26+ORF1a%3AG963D&nextcladeQcOverallScoreTo=29&

This one may or may not grow significantly. XBB.1.16.21 is a relatively slow sublineage of XBB.1.16. And ORF1a:G963D is inconsistent between clades on whether it helps or hurts viral fitness (see Bloom and Neher fitness estimates by clade below.  However, this lineage has grown by 33% from 24 to 32 in GISAID in the August 23, 24, and 25 submissions, and this lineage has been detected in 7 countries on two continents, so it may indeed have significant growth capability.

As of 2023-08-25, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 1 16 21+ORF1a_963D](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/0cef64b0-98b5-433b-a427-35aa7ef6191a)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_XBB.1.16.21%2BORF1a_963D.json?c=gt-ORF1ab_963&label=id%3Anode_6823993

GISAID query: Spike_E180V, Spike_T478R, Spike_F486P, NSP6_L260F, NSP14_D222Y, NSP8_V130I, NSP3_G145D

First GISAID sequence: Utrecht, Netherlands 2023-07-14 

Most Recent GISAID sequence: Ontario, Canada 2023-08-16

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-XBB.1.16.21+ORF1a_963D.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12444564/Support-XBB.1.16.21%2BORF1a_963D.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl+XBB.1.16.21+ORF1a_963D.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12444566/gisaid-epi-isl%2BXBB.1.16.21%2BORF1a_963D.txt)

Potential effects of the non-synonymous mutation on viral relative fitness
-------------------------------------------------------------------------------------------------

Now to consider the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations in their order on the UShER tree:

For ORF1a:G963D,

clade,gene,aa_mutation,delta_fitness
20A,ORF1ab,G963D,-0.84518
20B,ORF1ab,G963D,0.21044
20C,ORF1ab,G963D,-0.40835
20E,ORF1ab,G963D,-1.4323
20G,ORF1ab,G963D,-1.8166
20I,ORF1ab,G963D,0.19531
21C,ORF1ab,G963D,0.4628
21I,ORF1ab,G963D,-0.37634
21J,ORF1ab,G963D,-0.040515
21K,ORF1ab,G963D,0.29048
21L,ORF1ab,G963D,0.64288
22A,ORF1ab,G963D,0.51572
22B,ORF1ab,G963D,0.50179
22C,ORF1ab,G963D,0.47454
22D,ORF1ab,G963D,0.30342
22E,ORF1ab,G963D,0.89183
22F,ORF1ab,G963D,-0.30134
23A,ORF1ab,G963D,0.11896

ORF1a:G963D appears to be associated with a significant sign epistatis effect (reference Nielsen et al, “Host heterogeneity and epistasis explain punctuated evolution of SARS-CoV-2”, PLOS Computational Biology, https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010896) between clades with Bloom and Neher delta_fitness values ranging from a negative -1.82 in clade 20G to a fairly positive +0.89 in clade 22E. The closer clades to this lineage for which estimates are available, 22F and 23A, show mixed but weak effects for this mutation. It is possible although definitely uncertain that ORF1a:G963D might be associated with a viral fitness advantage in XBB.1.16's clade 22B. So for this lineage, the Bloom and Neher analysis is inconclusive with the available data.

**Comment by alurqu** [comment]
This may be fizzling out. If it doesn't grow more soon then closure as not planned may be merited.

**Comment by FedeGueli** [comment]
73 now but only 4 samples in september i m closing it.
