### ISSUE TITLE
Multiple XBB.1.16* with S:A352S (51 seqs, 14 countries / 42 seqs, 6 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#69]
```[tasklist]
### Multiple XBB.1.16* lineages with S:A352S
- [ ] Branch 1: XBB.1.16 > G22616T(S:A352S) [Query: `G22616T, T28297C, C29386T, -C23202T`, 58 seqs, 09/08]
- [ ] Branch 2: XBB.1.16.1 > G22616T(S:A352S) [Query: `G22616T, T28297C, C29386T, C23202T`, 68 seqs, 09/06]
```

### Branch 1

**Defining mutations:** XBB.1.16 > G22616T(S:A352S)
**Refined Query:** G22616T, T28297C, C29386T, -C23202T [to distinguish it from branch 2]
**Earliest seq:** 2023-03-04 (EPI_ISL_17764209, India)
**Latest seq:** 2023-05-19 (EPI_ISL_17771615, Canada)
**Countries:** Portugal (8), USA (6, Illinois/4, Indiana/1, NY/1), India (5), Japan (3), Canada (3, Ontario/2, Quebec/1), Australia (2, All NSW), France (1), Netherlands (1), Austria (1), New Zealand (1)

<details><summary> Genomes:</summary>
EPI_ISL_17358828, EPI_ISL_17360839, EPI_ISL_17373663, EPI_ISL_17387466, EPI_ISL_17428466, EPI_ISL_17442151, EPI_ISL_17447387, EPI_ISL_17477993, EPI_ISL_17478058, EPI_ISL_17490966, EPI_ISL_17561072, EPI_ISL_17586774, EPI_ISL_17589218, EPI_ISL_17592354, EPI_ISL_17601994, EPI_ISL_17606287, EPI_ISL_17616771, EPI_ISL_17634158, EPI_ISL_17639531, EPI_ISL_17652780, EPI_ISL_17654487, EPI_ISL_17655479, EPI_ISL_17657648, EPI_ISL_17720077, EPI_ISL_17720078, EPI_ISL_17720079, EPI_ISL_17720080, EPI_ISL_17720144, EPI_ISL_17720247, EPI_ISL_17739134, EPI_ISL_17771615
</details>

![XBB 1 16+S_A352S](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bdf6522d-ecd3-4bfb-bb81-c11e10a2ba20)

---

### Branch 2

**Defining mutations:** XBB.1.16.1 > G22616T(S:A352S) >
**Refined Query:** G22616T, T28297C, C29386T, C23202T [to distinguish it from branch 1]
**Earliest seq:** 2023-04-07 (EPI_ISL_17489933, Virginia, USA)
**Latest seq:** 2023-05-24 (EPI_ISL_17764507, Canada)
**Countries:** USA (7), Canada (2), India (1)

<details><summary>Genomes: </summary>
EPI_ISL_17464021, EPI_ISL_17489933, EPI_ISL_17490000, EPI_ISL_17593317, EPI_ISL_17639409, EPI_ISL_17653208, EPI_ISL_17689550, EPI_ISL_17763812, EPI_ISL_17764284, EPI_ISL_17764507
</details>

![XBB 1 16 1+S_A352S](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/519652ca-3e32-4e65-a15c-3603831400e7)

---

**UShER:**

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a125_15e1e0.json?f_userOrOld=uploaded%20sample

overview

![XBB 1 16 Polytomy](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1c0ea5c0-3c9d-4b28-a50a-49659d4fe0ad)

**Comment by FedeGueli** [comment]
i think you could propose this one once it reaches 50.

**Comment by FedeGueli** [comment]
branch 1 is slow, Branch 2 is more interesting.
