### ISSUE TITLE
Two branches of EG.5.1.1+S:G184V(9 seqs and 4 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#690]
Branch 1: EG.5.1.1+S:G184V(G22113T)

GISAID query: G22113T,G13627A,T23018C,-1946,-7164
No. of seqs: 6( China 5 Singapore 1 )

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d76b_9ce160.json?f_userOrOld=uploaded%20sample&label=id:node_6916003)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c55e5569-934d-4717-ac0f-15125cc55df6)

Branch 2: EG.5.1.1+C11779T+G1946A(Orf1a:V561I),T20613C,G22113T(S:G184V)

GISAID query: G22113T,G13627A,T23018C,G1946A
No. of seqs: 3(Yunnan)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1d76b_9ce160.json?f_userOrOld=uploaded%20sample&label=id:node_6919709)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/7bedeb8c-2f48-4c19-b5eb-7aa576c6cbfc)

**Comment by FedeGueli** [comment]
closing it for now.
