### ISSUE TITLE
XBB.1.5 on T10204C with S:T478N (40 seqs, Mexico and USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#691]
**Defining Mutations:** XBB.1.5 [T17124C > T23018C > T10204C] > `T2428C, A22996C(S:T478N), T27182C`
**Query:** `T2428C, A22996C, T27182C`
**Earliest seq:** 2023-05-12 (`EPI_ISL_17853464`, California, USA)
**Latest seq:** 2023-08-07 (`EPI_ISL_18126205`, Nevada, USA)
**Sampled Countries:** USA (7), Mexico (5)

<details><summary>Genomes: </summary>

`EPI_ISL_17842437, EPI_ISL_17853464, EPI_ISL_17861526, EPI_ISL_17959731, EPI_ISL_18011978, EPI_ISL_18077019, EPI_ISL_18098874, EPI_ISL_18104305, EPI_ISL_18121694, EPI_ISL_18126205, EPI_ISL_18137367, EPI_ISL_18137469`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1cfa5_9f0cb0.json?label=id:node_7046670
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4f2ea405-e6e3-444c-a182-fdf5cf1d3a5f)

**Comment by FedeGueli** [comment]
note  that Mexico was the first place in the world to have sustained circualtion of 478K with B.1.1.519 early in 2021 . So this could explain why we are seeing so many lineages popping up there with S:t478R

**Comment by FedeGueli** [comment]
This is doing pretty well.
lets ping me when it reaches 50, if there are the conditions we will propose it

**Comment by FedeGueli** [comment]
tracker : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T2428C%2CA22996C%2CT27182C&analysisMode=CompareToBaseline&

It is in the middle between EG.5.1 and HK.3

**Comment by FedeGueli** [comment]
Just one sample from Spetember closing it for now.
