### ISSUE TITLE
FL.13 with ORF1a:T1000I (nsp3_T182I), ORF1a:L2527M (nsp3_L1709M) and S:F456L (34 seqs, mainly in Chile - 5% prevalence, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#692]
**Defining Mutations:** `FL.13` > `C27297T` > `C3264T(ORF1a:T1000I), A3754G, T4507C` > `C7844A(ORF1a:L2527M), T21976C, T22928C(S:F456L), C23929T`
**Query:** `C3264T, G4354A, T22928C`
**Earliest seq:** 2023-07-26 (`EPI_ISL_18137360`, Hidalgo, Mexico)
**Latest seq:** 2023-08-15 (`EPI_ISL_18124553`, Ontario, Canada)
**Sampled Countries:** Canada (5, Ontario), Mexico (1), Singapore (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18124416-18124417, EPI_ISL_18124484, EPI_ISL_18124486, EPI_ISL_18124553, EPI_ISL_18127460, EPI_ISL_18137360`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice65_genome_8efa_9dfcf0.json?c=gt-S_456&label=id:node_6883987
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/81c2767c-1b76-422c-afea-dec3bf678bc6)

**Comment by FedeGueli** [comment]
adding a growth  tracker : [C3264T, G4354A, T22928C](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C3264T%2CG4354A%2CT22928C&analysisMode=CompareToBaseline&)

**Comment by FedeGueli** [comment]
this seems to have a 5% of prevalence recently in Chile.

**Comment by FedeGueli** [comment]
Designated FL.13.5 via https://github.com/cov-lineages/pango-designation/commit/73069dfdb871ec433dcca6eb316c567f12ab6a91
