### ISSUE TITLE
XBB.1.5 (on T10204C) with S:Q1201K, S:V70F, deletion/frameshift around S:183-185 (S:Q183del, S:G184E S:N185D) and S:F456L (14 seqs, USA, Mexico, Australia, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#693]
**Defining Mutations:** `XBB.1.5 [T17124C > T23018C]` > `C25163A(S:Q1201K)` > `C25162A` > **`T10204C`** > `T3520A, G21770T(S:V70F), T22928C(S:F456L)`
**Query:** `T3520A, G21770T, T22928C`
**Earliest seq:** 2023-06-30 (`EPI_ISL_18120766`, California, USA)
**Latest seq:** 2023-08-04 (`EPI_ISL_18098800`, Texas, USA)
**Sampled Countries:** USA (8: Texas/4; Arizona/1; California/1; Florida/1; Louisiana/1), Mexico (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18037725, EPI_ISL_18057193, EPI_ISL_18057605, EPI_ISL_18057616, EPI_ISL_18098800, EPI_ISL_18104608, EPI_ISL_18120766, EPI_ISL_18133696, EPI_ISL_18137440`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_13191_9fe3d0.json?c=gt-nuc_10204,22928&label=id:node_7204018
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8f941f87-de1e-4e1f-bb1d-3246a797a9d4)

**Trivia:**

- The tree is quite messy again, this time probably due to a deletion around S:183-185 causing frameshit, nextclade think it's S:Q183Δ, S:G184E and S:N185D. This is not the 1st case of deletion around that area, one other example being #592.
![deletion](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/05daeb08-d52b-40a0-b167-509ae7ac649a)

- UShER puts `T10204C` after some changes around S:1200-1201, one silent and one aa change, that could be some kind of mis-placement (or another cause of it).
![1200](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8d7876dc-f0f1-4cb0-893a-d16cd8be8b3b)

**Comment by FedeGueli** [comment]
Very interesting lineage for mutations, deletions and also that double nuc spike mutation. cc @ryhisner if you have a time this could be interesting.

**Comment by ryhisner** [comment]
The 2-nuc change at S:1200-1201 has occurred again and again, and Marc Johnson has even noticed it in several cryptic wastewater lineages. Like many multi-nuc mutations, it's TRS related. 
<img width="1457" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/218e6230-1422-4f79-a135-50f951e88e30">
.

In BA.2.3.20, there were even a handful of sequences that went the whole distance to get the ideal TRS sequence, though this is far less common than the S:Q1201K version. 
<img width="1506" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/174f86ff-a5b1-47ef-89ae-545b07692851">

**Comment by ryhisner** [comment]
Definitely an interesting lineage though. Are deletions in the N4 NTD loop coming into favor? N4 is the only NTD loop that has so far not seen many deletions, but the fitness landscape is constantly changing, and there are at least three lineages now with deletions in N4. 

I wonder if this one might me fairly prominent in Mexico or other Central American countries from which we've had almost no sequencing in the past two months.

**Comment by FedeGueli** [comment]
Thank you very much @ryhisner

**Comment by FedeGueli** [comment]
it seems slow. waiting a week more befoe closing.
