### ISSUE TITLE
EG.5.1.1 sublineage with S:E654Q (9 seqs in China and US) 

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#694]
Defining mutations:
EG.5.1.1>C6541T>T13438G, A18399G, G23522C (S:E654Q), C25075T
GISAID query: G13627A, A18399G, G23522C
Earliest seq: 2023-07-06 (Shanghai Municipality, China- EPI_ISL_17994408)
Most recent seq: 2023-08-11 (Shanghai Municipality, China- EPI_ISL_18114828)
Countries detected: China (6, including Shanghai 5 and Yunnan 1), US (1) 

Usher Tree:
![QQ截图20230827002215](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/ee4bfe2e-b1ab-4677-b4e5-60c8e311807d)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12cc_9c27a0.json

S:E654Q may effectively improves the fitness
![QQ截图20230827002228](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/3a40aaac-8e25-4e05-bfba-6de71f399e3c)

Genomes:
EPI_ISL_17994408, EPI_ISL_18103543, EPI_ISL_18111220, EPI_ISL_18114728, EPI_ISL_18114828, EPI_ISL_18138096, EPI_ISL_18138278

**Comment by FedeGueli** [comment]
I ve propsed one with the same mutation on an EG.1 backbone and it did nothing, let see if in a fast backbone could help. thx

**Comment by FedeGueli** [comment]
Closing it-
