### ISSUE TITLE
EG.6.1 (S:F456L) sublineage with ORF1b:D1183G and ORF1b:P218S after T6547C first detected in Pennsylvania, USA (157 GISAID seqs as of 2023-09-29; Canada, USA, UK, France)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#696]
There may be a EG.6.1 sublineage with ORF1b:D1183G (A17015G; NSP13:D260G; ORF1ab:D5584G) and ORF1b:P218S (C14119T; NSP12:P226S; ORF1ab:P4619S) after T6547C first detected in Pennsylvania, USA.

Note that this lineage has two potentially-significant sublineages defined by ORF1a:T2274I and by S:C1236F.

As of 2023-08-26, Cov-Spectrum reports 42 good-quality (44 total) EG.6.1+ORF1b:1183G+ORF1b:218S+6547C sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AEG.6.1+%26+ORF1b%3AD1183G+%26+ORF1b%3AP218S+%26+T6547C&nextcladeQcOverallScoreTo=29&

There are not enough sequences of this lineage in a single country to obtain a reliable growth estimate; however, it has been detected in 4 countries on 3 continents. Notably, the analysis of the Bloom and Neher non-synonymous mutation fitness effects suggests that these mutations should have decreased the viral fitness, but ORF1b:P218S does show possible positive sign-change epistatis in the XBB clades 22F and 23A. So perhaps this lineage could compete due to epistatic effects.

As of 2023-08-26, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_EG 6 1+ORF1b_1183G+ORF1b_218S+6547C](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/32394386-c055-4f7b-aff3-5a15d7cdda6f)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_EG.6.1%2BORF1b_1183G%2BORF1b_218S%2B6547C.json?c=gt-nuc_14119&label=id%3Anode_6943480

GISAID query: C1684T, T22928C, T6547C, A17015G, C14119T

First GISAID sequence: Pennsylvania, USA 2023-06-24 

Most Recent GISAID sequence: Ontario, Canada 2023-08-15

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-EG.6.1+ORF1b_1183G+ORF1b_218S+6547C.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12446877/Support-EG.6.1%2BORF1b_1183G%2BORF1b_218S%2B6547C.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at
[gisaid-epi-isl+EG.6.1+ORF1b_1183G+ORF1b_218S+6547C.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12446872/gisaid-epi-isl%2BEG.6.1%2BORF1b_1183G%2BORF1b_218S%2B6547C.txt)

Potential effects of the non-synonymous mutations on viral relative fitness
-------------------------------------------------------------------------------------------------

Now to consider the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations in their order on the UShER tree:

For ORF1b:D1183G (aka NSP13:D260G),

20A,ORF1ab,D5584G,-1.3038
20B,ORF1ab,D5584G,-0.064288
20C,ORF1ab,D5584G,-0.95299
20E,ORF1ab,D5584G,-1.0363
20G,ORF1ab,D5584G,-0.054993
20I,ORF1ab,D5584G,-0.75916
21I,ORF1ab,D5584G,-1.7323
21J,ORF1ab,D5584G,-0.43178
21K,ORF1ab,D5584G,-1.9659
21L,ORF1ab,D5584G,-0.84675
22A,ORF1ab,D5584G,-1.2084
22B,ORF1ab,D5584G,-1.6409
22C,ORF1ab,D5584G,-1.518
22D,ORF1ab,D5584G,-0.9299
22E,ORF1ab,D5584G,-0.64157
22F,ORF1ab,D5584G,-0.87999
23A,ORF1ab,D5584G,-1.7492

ORF1b:D1153G decreases viral fitness in most clades, but it is very near neutral in clades 20B and 20G. This mutation would be expected to decrease viral fitness and decrease the lineage growth rate. However, the impact of this mutation has varied between clades so perhaps epistatic effects can make it neutral or even positive for viral fitness.

For ORF1b:P218S (aka NSP12:P226S),

20A,ORF1ab,P4619S,-0.13202
20B,ORF1ab,P4619S,-0.077666
20C,ORF1ab,P4619S,0.0087582
20E,ORF1ab,P4619S,-0.007034
20G,ORF1ab,P4619S,-0.58282
20I,ORF1ab,P4619S,-0.5493
21C,ORF1ab,P4619S,-0.16369
21I,ORF1ab,P4619S,-0.6616
21J,ORF1ab,P4619S,-0.40198
21K,ORF1ab,P4619S,-0.11538
21L,ORF1ab,P4619S,-0.55667
22A,ORF1ab,P4619S,-0.6333
22B,ORF1ab,P4619S,-0.25758
22C,ORF1ab,P4619S,-0.31613
22D,ORF1ab,P4619S,-0.8223
22E,ORF1ab,P4619S,0.41485
22F,ORF1ab,P4619S,0.51454
23A,ORF1ab,P4619S,0.45151

ORF1b:P218S has decreased viral fitness in many clades but it has been associated with a close-to-neutral effect in others. More notably, in clades 22E (BQ.1) and more importantly 22F (XBB) and 23A (XBB.1.5), this mutation has been associated with a somewhat-positive change to viral fitness. This mutation does appear to be associated with epistatic effects that can change it from a negative to a positive fitness effect.

**Comment by FedeGueli** [comment]
67n in gisaid now

**Comment by FedeGueli** [comment]
124 now

**Comment by FedeGueli** [comment]
138 now.

Adding a tracker

**Comment by FedeGueli** [comment]
It cannot compete vs HK.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C1684T%2CT22928C%2CT6547C%2CA17015G%2CC14119T&analysisMode=CompareToBaseline&

**Comment by alurqu** [comment]
Given that this lineage cannot compete, I am closing this proposal.
