### ISSUE TITLE
DV.7.1 with ORF1a:A4162V and ORF10:M1V (123 seq) 8 countries 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#697]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/96cf7d9a-26d4-45ef-958f-b85cfc62b0bb)
tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b7e0_a89230.json?c=gt-ORF10_1&label=id:node_7667037
gisaid query: T22928C, A29558G, G22927T
OY719336.1 EPI_ISL_18112414 EPI_ISL_18124929 EPI_ISL_18113218 EPI_ISL_18118666 EPI_ISL_18109063 EPI_ISL_18094921 EPI_ISL_18049132 OY640191.1 EPI_ISL_18120519 EPI_ISL_18111793 EPI_ISL_18131645 EPI_ISL_18110624 EPI_ISL_18092147 EPI_ISL_18076194 EPI_ISL_18113226 EPI_ISL_18078439 EPI_ISL_18106886EPI_ISL_18076193 OR415343.1 EPI_ISL_18049130 EPI_ISL_18092156 EPI_ISL_18081536 OR465352.1 EPI_ISL_18094905 OY541330.1 EPI_ISL_18110627 EPI_ISL_18113968 EPI_ISL_18118665 EPI_ISL_18118667 OY725081.1 OY719466.1 EPI_ISL_18124220 OY640947.1 EPI_ISL_18123386 EPI_ISL_18094333 EPI_ISL_18110631 EPI_ISL_18118669 EPI_ISL_18113228 OY723610.1 EPI_ISL_18115954 EPI_ISL_18118442 EPI_ISL_18118664 EPI_ISL_18092171 EPI_ISL_18119312 EPI_ISL_18119243 EPI_ISL_18092154 EPI_ISL_18110641 EPI_ISL_18092158 EPI_ISL_18118670 OR415344.1 EPI_ISL_18106726 EPI_ISL_18118681 EPI_ISL_17949279 OR415424.1 EPI_ISL_18092157 EPI_ISL_18106861 OY724882.1 EPI_ISL_18110630 EPI_ISL_18094935 EPI_ISL_18106902 EPI_ISL_17953153 EPI_ISL_18113219 EPI_ISL_18110626

**Comment by FedeGueli** [comment]
Please propose it. In the title and in the proposal please specify that 30 sequences are only on Climb (maybe try the double count Gisaid/Usher)
