### ISSUE TITLE
XBC.1.6 x FL.1.5 recombinant (9 seqs, US-CA, NY, UT, NV)

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#698]
**Query**: G3606T, C5184T, A6806G
**Earliest sequence**: 2023-06-25 (US-CA)
**Most recent sequence**: 2023-08-02 (US-CA)

Breakpoint is between nuc 5721 and 6805 at NSP3. Everything upstream is from a XBC.1.6 donor and everything downstream is from a FL.1.5 donor.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/f7130d67-10c2-4961-893e-54bb53ba75b8)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fd5a_aa0a90.json?c=userOrOld&label=id:node_6951467

**Genomes**:
EPI_ISL_18030638, EPI_ISL_18045883, EPI_ISL_18046190, EPI_ISL_18064766, EPI_ISL_18104442, EPI_ISL_18108122, EPI_ISL_18114027, EPI_ISL_18133665, EPI_ISL_18133672

**Comment by Over-There-Is** [comment]
But I think the breakpoint is between 5184 to 5584. They all have C5184T from XBC.1.6 and A5720G from FL.1.5, but not A5584G.

**Comment by Over-There-Is** [comment]
FL.1.5> T23245C> A6806G(Orf1a:T2181A), T10839C(Orf1a:L3525S), C27741T> C24023T
Then recombined with XBC.1.6+C4586T

There are 2 branches of XBC.1.6* with C4586T:
XBC.1.6> C10537T> C23996A(S:P821T)> C4586T(11 seq, 7 in US)
or XBC.1.6.3> A476G(Orf1a:A476G)> A11047G> C4586T, A29752T(8 seq, 0 in US, and the recombinant does not have A476G, so the XBC.1.6 donor is improbably this branch)

Private mutations: G18651T(Orf1b:E1728D), C18788T(Orf1b:T1774I)

**Comment by FedeGueli** [comment]
This is the rapid picture of this recomb
![Schermata 2023-08-27 alle 16 55 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/68624586-8195-4a46-8724-68ac1b7afeab)

**Comment by FedeGueli** [comment]
1 month without new samples collected , luckily it is not fast. waiting a bit more before closing.

**Comment by FedeGueli** [comment]
Closing this one for now
