### ISSUE TITLE
ORF7b/ORF8 Discussion (transferred from main page issue #1999)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#70]
_I didn't want to bog down the issue on the recent XBB.1* saltation lineage https://github.com/cov-lineages/pango-designation/issues/1999(/url) in Guatemala with a prolonged discussion of multi-nuc mutations at the end of ORF7b and their relation to ORF8, so I've coied and pasted my first comment on the subject and screenshots of replies from @oobb45729 and @FedeGueli below, so if anyone wants to discuss further, we can do so here._ 

The triple-nuc ORF7b:A43L (which consists of C27881T, G27882C, & C27883T) is definitely real, but I don't think this lineage actually has it. One of the three nucleotides (C27881T) is actually in ORF7b:42 and is synonymous. Like the multiple-nucleotide mutations at the end of ORF8, which are much more common than the ORF7b 3-nuc mutations, this is a transcription-regulation sequence (TRS) phenomenon. These three nucleotide mutations create extended homology for the ORF8 TRS, which means they create a sequence that more closely resembles the TRS-L at the beginning of the genome. The more closely a TRS-B for a given sgRNA resembles the TRS-L, the more likely it is to be transcribed, so extended homology for a given TRS-B should increase the expression of the sgRNA downstream of it. 

<img width="1373" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/7ab34639-b412-4a11-a4e4-bdec4932e422">

There have been multiple forms of this ORF7b mutation. Some only have C27881T & G27882C and result in ORF7b:A43P. A common one is three nucleotide mutations accompanied by a two-nucleotide deletion. 
<img width="1400" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/c013b819-7078-45f0-ba7f-60fa7ecae50d">

A four-nucleotide mutation form that forms 5/8 of a second, novel ORF8 TRS upstream of the main one, and which also has four nucleotides of extended homology. 
<img width="1506" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/d4372fc7-b6a6-475c-9d18-04c2fb1a0832">

XBB.1 lineages have ORF8:G8*, and it seems extremely unlikely that the function of these multi-nuc ORF7b mutations is to make more 7-amino-acid peptides consisting of the first seven AA in ORF8. My only hypothesis is that this extended homology causes the RdRp to skip to the TRS-L more frequently at this spot, meaning that it's free to find another genome and start scanning again. (The RdRp scans "backwards.") This would increase the expression and the amount of cellular resources available for N and ORF9b, since they are the only sgRNAs up stream of this TRS-B and are therefore not directly affected by its more frequent diversion of the RdRp. This hypothesis also fits well with the extremely common acquisition of extended homology for the N/ORF9b TRS-B, which has independently evolved many thousands of times, and which appears to confer a small growth advantage in whatever lineage acquires it (though this small growth advantage has always been overwhelmed by larger, more dramatic changes in the variant landscape, obscuring its effect within a given lineage). 

The most extreme version of this ORF7b TRS thing involves five nucleotide mutations and a two-nucleotide insertion. In reality, I'm pretty certain most (but not all) of these TRS-enhancing, multi-nuc mutations occur through recombination with the TRS-L, though I don't know the detailed mechanism by which this happens. The complicated insertions, substitutions, and deletions that show up in sequencing are just the simplest way for the algorithms to make sense of the change, since they aren't wired to label anything as happening due to recombination. 
<img width="1490" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/52b1bf2e-e417-4d05-8dcf-25b2d177e364">

<img width="1356" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a0b25e9c-4d98-4d89-9f42-f145db4e39b6">

<img width="1267" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9f28db03-c518-490e-a4dd-1a941c7c2861">

<img width="1259" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/3981a715-b00c-4532-8cbc-05eb1d499fb1">

**Comment by aviczhl2** [comment]
There seems to be Orf8:F120V,I121L combo convergence lineages everywhere in XBB*, which causes lots of flip-flop reversion branches as X+Orf8:F120V,I121L=X+A+Orf8:F120V,I121L+(-A)       , so X+Orf8:F120V,I121L is easily attached to X+A+Orf8:F120V,I121L+(-A) on usher as it is 1 distance from X+A+Orf8:F120V,I121L but 2 distance from X.
