### ISSUE TITLE
GK.2.1/XBB.1.5 recombinant with additional S:P1162S (31 seqs, 9 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#700]
XBB.1.5(with 17124 but without 10204)+C27059T+C28005T(Orf8:P38S), T22928C(S:F456L),G22927T(S:L455F),C22624T,A25045G
+C15755G(Orf1b:S763C),G23093A,C23741T(S:V511I),C7417T,C25046T(S:P1162S)

Compared with GK.2.1 it lacks C1973T, T2824C, C7564T, T8737C, and G12467T, but have additional C7417T and C25046T.

Shall be GK.2.1/XBB.1.5 recombinant. Breakpoint between 12468 and 15754.

GISAID query: C7417T,C25046T,C15755G
No. of seqs: 20(Canary Islands 2 UK 5 Spain 2 Switzerland 2 USA 1 South Korea 1 Norway 1 Ireland 1 Israel 1 Italy 4 )

First: EPI_ISL_18119219, Italy, 2023-5-18
Latest: EPI_ISL_18130290, Switzerland, 2023-8-10

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12ccb_a97c40.json?branchLabel=Spike%20mutations&label=id:node_7215657&showBranchLabels=all)

  
![Schermata 2023-08-27 alle 09 41 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fba0b9fa-22dd-4cbe-a4d2-128f3c9dab6a)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a0ec4f0f-f572-4948-81a2-b53160b867cf)

The French seq is a recombinant with XBB.1.9*, so not included.

**Comment by FedeGueli** [comment]
thx @aviczhl2 i have added a bigger picture of the tree to make it clearer. It is XBB.1.5.70 + 511I. Wonder if it could be a recombination with XBB.1.5.71 or JD.1?  
Now i m going later i will check.

cc @angiehinrichs if you could take a look at the tree it is seems legit but it could have both mutations from JD.1.2 or XBB.1.5.71 so i supsect that something could have happened.

**Comment by aviczhl2** [comment]
> thx @aviczhl2 i have added a bigger picture of the tree to make it clearer. It is XBB.1.5.70 + 511I. Wonder if it could be a recombination with XBB.1.5.71 or JD.1? Now i m going later i will check.
> 
> cc @AngieHinrichs if you could take a look at the tree it is seems legit but it could have both mutations from JD.1.2 or XBB.1.5.71 so i supsect that something could have happened.

>XBB.1.5.70	S:L455F, S:F456L (T22928C), ORF1a:A4068S, Brazil, from #1982

It doesn't have Orf1a:A4068S. 
Do you find any recombinant potentials？Outside the XBB.1.5.70 branch it also has C15755G(Orf1b:S763C),G23093A,C23741T(S:V511I),C7417T,C25046T(S:P1162S)

**Comment by FedeGueli** [comment]
![Schermata 2023-08-27 alle 14 44 19](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/09ae3abf-82fa-4979-b286-4ba7cb9cef26)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.1.5*&nextcladePangoLineage1=GK.2*&nucMutations2=C7417T%2CC25046T%2CC15755G&analysisMode=CompareEquals&

Thx for the analysis @aviczhl2 i rechecked and didnt find any other easy explanation for this. adding labels now.

**Comment by AngieHinrichs** [comment]
> So now I guess it is GK.2.1/XBB.1.5 recombinant. 

Yes, that's what it looks like to me too.  And if you move back one node, to include France/GES-IPP16300/2023, then there is no need to require C7417T and C25046T, it still has C15755G (ORF1b:S763C), G23093A (S:V511I) and C23741T.

**Comment by FedeGueli** [comment]
> > So now I guess it is GK.2.1/XBB.1.5 recombinant.
> 
> Yes, that's what it looks like to me too. And if you move back one node, to include France/GES-IPP16300/2023, then there is no need to require C7417T and C25046T, it still has C15755G (ORF1b:S763C), G23093A (S:V511I) and C23741T.

Thank you Angie ! So (now it is already 21 with last sample coming from Spain) i think you can propose it in the main page once reached 25

**Comment by aviczhl2** [comment]
> > So now I guess it is GK.2.1/XBB.1.5 recombinant.
> 
> Yes, that's what it looks like to me too. And if you move back one node, to include France/GES-IPP16300/2023, then there is no need to require C7417T and C25046T, it still has C15755G (ORF1b:S763C), G23093A (S:V511I) and C23741T.

The French node is an independent recombinant of XBB.1.9* and isn't belonging to this lineage.

**Comment by aviczhl2** [comment]
I realized that there are 6 Scotland seq and 3 England seqs not on GISAID. The actual number of seqs shall be 31.

**Comment by FedeGueli** [comment]
Perfect so please propose it

**Comment by FedeGueli** [comment]
Designated XCL via https://github.com/cov-lineages/pango-designation/commit/40b2d678c6899d43fc4ae4c536660efc5033e566
