### ISSUE TITLE
GL.1 sublineage with  S:Y144del , ORF1:KSF141-143del and ORF3a:D155H (59 seq. Mainly Tasmania, Australia- 40% prevalence in August 2023)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#701]
Defining mutations: GL.1 then S:Y144- then nuc:C5239T then ORF1:KSF141-143del+nuc:C2788T+ORF3a:D155H(G25855C).
Gisaid query: C5239T,C2788T, G25855C (Edited)
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/5ba5ef5f-af94-4152-9bd8-a3772321ce19)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39b95_ae74a0.json?c=gt-ORF3a_155&label=id:node_6402106
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF3a%3AD155H&
ORF1:KSF141-143del (the same deletion as BA.4) has already occurred on GL.1* three times independently.
It first appeared on the Austrian branch (without S:Y144-).
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF6%3AE46G&
Then it appeared on this one.
Then it appeared on the Canary Islands branch nuc:C8293T > ORF1a:E2089D(G6532T) > ORF1a:G7S(G284A)+ORF1:KSF141-143del.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AGL.1*%26ORF1a%3AG7S&

Prevalence in Tasmania:
July: 9/66
August: 20/47

**Comment by FedeGueli** [comment]
You ve read in my mind!! ;)

**Comment by FedeGueli** [comment]
Please propose it . Remember to emphatize the S:Y144- mutation in the titel cause it could explain the further fitenss gained there by this lineag.

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/Australia/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C5239T%2CC2788T%2CG25855C&analysisMode=CompareToBaseline&
Still unclear that the advantage is real being the lower CI negative, bt still it gained so fast a high prevalence there that deserves a proposal

**Comment by FedeGueli** [comment]
+ 2 victoria.

**Comment by FedeGueli** [comment]
51 now

**Comment by FedeGueli** [comment]
It has slowed down . I m closing for now. if you notice some new trend please ping me.

**Comment by FedeGueli** [comment]
@oobb45729 worth noticing that we have just 4 recent samples related to Vietnam one of the four is a GL.1 collected in Singapore belonging to the C5239T branch  https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_d532_690080.json?c=userOrOld&label=id:node_11067935
![Schermata 2023-11-04 alle 19 47 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ea1e0a53-cf62-42c0-a227-f83a6f48e804)

**Comment by FedeGueli** [comment]
BTW the whole S:144del branch reached 213 on Usher
203 on Gisaid with del21992_21994,C5239T,G22820A
![Schermata 2023-11-04 alle 19 53 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/bbc79185-5bde-4262-ad46-f9a77ca25df4)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_d532_690080.json?c=userOrOld&label=id:node_2826475
maybe you can propose it starting with the deletion instead of this subbranch that stopped circulating?

**Comment by FedeGueli** [comment]
but still it could not compete:https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C5239T%2CG22820A&analysisMode=CompareToBaseline&
