### ISSUE TITLE
BF.7.3 singlet saltation with 20 Spike aa mutations and 6 non-Spike mutations (2023-08-02 in Netherlands)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#702]
It is a singlet seq, but the mutations are interesting and we can have a track. (QUERY: A1668G, C4893T, C9559T - edited by f)

From root of BF.7.3 (BF.7+S:K182E)
AA mutations:
S: P9L, T29I, D142C, L212I, T299I, R357K, V367L, R403K, G446S, Y473F, K478R, V483G, A484V, V486F (reversion), S494P, T500A, D574N, S640P, S659T, A701V
ORF1ab: K468R, T1543I, T2283I, S2900L, A4357V
E: V62F (common in Delta)
![QQ截图20230827155349](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/a28b7f4c-81ff-4b55-9e3d-4f184f050fbb)

Also notice that S:229-289 are missing.
![QQ截图20230827160355](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/56f699f2-732a-4729-aa33-00e6c4b36e10)

Deletions (show Spike only):
S: Y144-, N211-, V620-, P621-
![QQ截图20230827160344](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/c7a13962-dcc0-4c29-b8e3-f72b19f0dd74)

Usher shows the neighbored branches/seqs were active in Sep2022-Nov2022.
![QQ截图20230827160030](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/839bce40-0df3-46bc-9a66-bd941f0411ee)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1b90b_a9d530.json

Metadata shows the patient age is 23. If the second seq (from different patient) shows we could concern it.

Genomes:
EPI_ISL_18136968

**Comment by FedeGueli** [comment]
thank you this was spotted by @JosetteSchoenma a couple of days ago. very bad one. likely chronic infection, hopefully.

**Comment by silcn** [comment]
S:D142C is a very rare 2-nuc mutation. S:A484V is accomplished by GCA -> GTT, meaning that A23014T was silent whether or not it came first (unless it went 484A -> 484E -> 484D -> 484V).

I think there may be a signal for molnupiravir but only outside the spike? @ryhisner

**Comment by ryhisner** [comment]
> S:D142C is a very rare 2-nuc mutation. S:A484V is accomplished by GCA -> GTT, meaning that A23014T was silent whether or not it came first (unless it went 484A -> 484E -> 484D -> 484V).
> 
> I think there may be a signal for molnupiravir but only outside the spike? @ryhisner

The most distinctive molnupiravir mutation is G->A, and there is only one G->A mutation outside of spike, so I think MOV is unlikely here. In our paper on molnupiravir sequences, @theosanderson discovered than MOV-induced mutations favor distinct nucleotide contexts. So he created an awesome new tool that assists in identifying possible MOV sequences by analyzing the nuc contexts. I ran this sequence's mutations through the tool as a check, and it confirms that MOV probably not a factor here. Results below.

<img width="1511" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1dff0fe4-c02d-475a-b07a-6cced2893f2d">


.
I had the exact same thought about the 484 progression. A->T mutations don't happen willy-nilly, so it seemed really unlikely to me that A23014T happened by coincidence. 484D is extremely rare, but it's shown up in numerous extreme chronics, and multiple studies have shown it confers the ability to enter cells independently of ACE2. 

<img width="1145" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/63992bf4-2138-47d7-af1b-676eac7bca36">

.

I checked A23014T on Cov-Spectrum, and as I expected, it has basically been basically nonexistent throughout almost the entire pandemic. However, it was recently acquired by HK.6, a fast-growing sublineage of EG.5.1.1 that has S:D253G. Most likely just a weird coincidence as it's hard for me to think of any reason this synonymous mutation would be any more favorable now than in any previous time period. 
<img width="1246" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/79142f86-810b-4810-8078-f2069809bfc2">
<img width="1493" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d76184bf-8b7e-4f6a-9104-2edd68aa616e">

**Comment by ryhisner** [comment]
> S:D142C is a very rare 2-nuc mutation. S:A484V is accomplished by GCA -> GTT, meaning that A23014T was silent whether or not it came first (unless it went 484A -> 484E -> 484D -> 484V).
> 
> I think there may be a signal for molnupiravir but only outside the spike? @ryhisner

I suspect D142C might form a disulfide bond with C136. Normally, there's a C15-C136 disulfide bond in spike, but P9L alters the signal peptide, removing C15. https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1011308
<img width="1208" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/19a5cfc0-4bd9-4d6b-a75a-defc79294049">


But as I understand it, unpaired cysteine residues tend to be destabilizing. It seems that sequences with destabilizing mutations—such as large NTD deletions—are rarely successful at transmitting. Though P9L is very common in chronic-infection sequences, there are only two instances I know of in which it has transmitted: a BA.1 lineage in the US in early 2022 (when near-total lack of infection-preventing immunity likely allowed even weak versions of BA.1 to transmit) and C.1.2. But C.1.2 had C136F in addition to P9L—so it got rid of the unpaired cysteine. 

It's pretty common to see either the loss of an unpaired cysteine or the addition of a cysteine to replace C15 to form a new disulfide bond. One example noted by Veesler et al. was Epsilon, or B.1.429, which had a different peptide-signal-shifting mutation (S13I) along with W152C, which formed a new disulfide bond. 
<img width="1407" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e318cb50-c337-46c5-bb2b-e0067b43fe09">

It's not uncommon to see similar examples in chronic-infection sequences. I've seen S:W64C and S:W152C paired together numerous times with either P9L, C15F, or ∆C15; and two EG.5.1.1 sequences collected in August in China have both P9L and C136F, for example.

**Comment by silcn** [comment]
> I suspect D142C might form a disulfide bond with C136. Normally, there's a C15-C136 disulfide bond in spike, but P9L alters the signal peptide, removing C15. https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1011308 <img alt="image" width="1208" src="https://user-images.githubusercontent.com/33738461/263547228-19a5cfc0-4bd9-4d6b-a75a-defc79294049.png">

I think you're right here. S:142C is a 2-nuc mutation from BA.2 (or Delta) but only a 1-nuc mutation from WT, Alpha etc. Looking at the sequences that had it, a decent proportion of them have signal-peptide altering mutations: 25% have S:S13I (most of these are not B.1.427 or B.1.429), then there are a few S:P9L, S:P9S, S:C15F. There are also a few sequences with rather unusual mutations that introduce another cysteine, namely S:R214C, S:W258C or S:G261C - presumably some or all of these form a new disulfide bond with 142C in addition to the 15-136 bond.

**Comment by krosa1910** [comment]
Well, it seemed that those mutations such as R357K and Y473F are not random, but some of the strongest escape site mutaitions. According to this new jbloom study, I suppose that this variant to be paid more attention to, as it could foreshadow some of the extreme attempts for the virus to escape XBB-elicited antibodies.
<img width="707" alt="29D19882923C2DBC197D6F453DB2895D" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/6e5b8bc4-11f7-4f7a-ba00-602b5df05ec6">
<img width="612" alt="3452D63D-62F7-4285-A31E-9101F5CB3AB6" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/1216c58b-b45f-4dc9-b5ee-f613cf327c33">

**Comment by FedeGueli** [comment]
@HynnSpylor i added a query to be easy to track after what noticed @krosa1910 i think a reinforced tracking on it is worth.

**Comment by JosetteSchoenma** [comment]
Thanks, @FedeGueli . I will keep an eye on it as well.

**Comment by silcn** [comment]
> Well, it seemed that those mutations such as R357K and Y473F are not random, but some of the strongest escape site mutaitions. According to this new jbloom study, I suppose that this variant to be paid more attention to, as it could foreshadow some of the extreme attempts for the virus to escape XBB-elicited antibodies.

Interesting that these XBB-escape mutations appeared on a BA.5 background. Perhaps the individual was coinfected with XBB?

**Comment by FedeGueli** [comment]
Closing this for now
