### ISSUE TITLE
XBB.1.16.6 (S:F456L) sublineage with ORF3a:H78Y and C29627T first detected in Wisconsin, USA (225 GISAID seqs as of 2023-10-07; USA, Canada, Ireland, UK, France, Germany, China, South Korea, Denmark, Spain, Sweden, Australia, Colombia, Israel, Portugal, traveler from Netherlands)

### ISSUE THREAD

**Issue by alurqu** [sars-cov-2-variants/lineage-proposals#705]
There may be a XBB.1.16.6 sublineage with ORF3a:H78Y (C25624T) and C29627T (putative ORF10:R24C) first detected in Wisconsin, USA.

As of 2023-08-27, Cov-Spectrum reports 28 good-quality (31 total) XBB.1.16.6+ORF3a:78Y+29627T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.1.16.6+%26+ORF3a%3AH78Y+%26+C29627T&nextcladeQcOverallScoreTo=29&

The are not enough samples of this lineage in any one country to obtain a reliable growth estimate relative to its parental lineage; however, this lineage has already been detected in 8 countries from 3 continents plus a traveller from an additional country.  Additionally, checking the Bloom and Neher viral fitness impact estimates for both mutations indicates a good potential for an increase in viral fitness relative to the parental lineage.

As of 2023-08-27, UShER shows all of the CoV-Spectrum samples are on a single subtree with evidence of additional branching:
![UShER_CoV-Spectrum_XBB 1 16 6+ORF3a:78Y+29627T](https://github.com/sars-cov-2-variants/lineage-proposals/assets/88959107/a0c227a6-3c84-4e60-9b0e-26073d4bf8fb)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/08/subtreeAuspice1_genome_CoV-Spectrum_XBB.1.16.6%2BORF3a_78Y%2B29627T.json?c=gt-ORF3a_78&label=id%3Anode_6865060

GISAID query: Spike_E180V, Spike_T478R, Spike_F486P, NSP6_L260F, NSP14_D222Y, Spike_F456L, NS3_H78Y

First GISAID sequence: Wisconsin, USA 2023-06-04

Most Recent GISAID sequence: Limerick, Ireland 2023-08-21

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum-derived UShER output files for these sequences is available at [Support-XBB.1.16.6+ORF3a_H78Y+29627T.zip](https://github.com/sars-cov-2-variants/lineage-proposals/files/12449617/Support-XBB.1.16.6%2BORF3a_H78Y%2B29627T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-XBB.1.16.6+ORF3a_78Y+29627T.txt](https://github.com/sars-cov-2-variants/lineage-proposals/files/12449614/gisaid-epi-isl-XBB.1.16.6%2BORF3a_78Y%2B29627T.txt)

Potential effects of the non-synonymous mutations on viral relative fitness
-------------------------------------------------------------------------------------------------

Now to consider the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of the fitness effects of the non-synonymous mutations:

For ORF3a:H78Y,

clade,gene,aa_mutation,delta_fitness
20A,ORF3a,H78Y,1.3276
20B,ORF3a,H78Y,1.3205
20C,ORF3a,H78Y,1.1074
20E,ORF3a,H78Y,1.13
20G,ORF3a,H78Y,1.487
20I,ORF3a,H78Y,1.4793
21C,ORF3a,H78Y,1.1356
21I,ORF3a,H78Y,1.5225
21J,ORF3a,H78Y,1.6939
21K,ORF3a,H78Y,1.1148
21L,ORF3a,H78Y,1.9934
22A,ORF3a,H78Y,1.0463
22B,ORF3a,H78Y,0.75496
22C,ORF3a,H78Y,1.0088
22D,ORF3a,H78Y,0.70376
22E,ORF3a,H78Y,1.0423
22F,ORF3a,H78Y,1.2922
23A,ORF3a,H78Y,0.81014

ORF3a:H78Y is associated with a significant increase in viral fitness in all clades although slightly less so in related clade 23A. This mutation could be reasonably associated with a growth advantage for this lineage over its parental lineage XBB.1.16.6.

For ORF10:R24C,

clade,gene,aa_mutation,delta_fitness
20A,ORF10,R24C,1.3072
20B,ORF10,R24C,0.72796
20C,ORF10,R24C,1.2325
20E,ORF10,R24C,0.82331
20G,ORF10,R24C,0.70238
20I,ORF10,R24C,0.83227
21C,ORF10,R24C,1.0064
21I,ORF10,R24C,1.2326
21J,ORF10,R24C,1.0285
21K,ORF10,R24C,1.1839
21L,ORF10,R24C,1.2002
22A,ORF10,R24C,1.3126
22B,ORF10,R24C,1.2658
22C,ORF10,R24C,1.5145
22D,ORF10,R24C,1.4601
22E,ORF10,R24C,0.91838
22F,ORF10,R24C,0.9002
23A,ORF10,R24C,1.0944

Actual production of ORF10 is disputed; however, Bloom and Neher provide estimates for the mutation ORF10:R24C, and this mutation is associated with a positive impact on viral fitness in all clades. This mutation may also somehow support an increased growth rate for this lineage versus its parental lineage XBB.1.16.6.

**Comment by FedeGueli** [comment]
Orf3a:H78Y was the defining mutation of BA.2.9 one of the first big sublineage of BA.2 that appeared very soon and it had been identified and discussed already in early January 2022

**Comment by oobb45729** [comment]
ORF3a:H78Y is problematic. I recall that there were reversions ORF3a:Y78H in the BA.2.9 tree.
Also, this weird surge of ORF3a:H78Y in Germany earlier does not look real to me.
https://cov-spectrum.org/explore/Germany/AllSamples/from%3D2022-12-01%26to%3D2023-06-01/variants?variantQuery=ORF3a%3AH78Y&

**Comment by FedeGueli** [comment]
this seems to have a huge advantage over parental lineage: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.1.16*&aaMutations1=S%3AE180V&nucMutations1=C25624T%2CC29627T&analysisMode=CompareToBaseline&

**Comment by alurqu** [comment]
This lineage appears to be growing more slowly than several other XBB.1.16.6 sublineages, so I'll close this proposal as not planned.
