### ISSUE TITLE
 XBB.1.16.20 wih Orf1a:Q556K and S:T573I in Japan (82 seqs, 5 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#706]
XBB.1.16.20+G23611T+C1931A(Orf1a:Q556K)+T12388C,T13210C, T21369C, C23280T(S:T573I)

GISAID query: T12388C,T13210C,C23280T
No. of seqs: 26(Thailand 1 USA 3(1 from Japan) Japan 22)

First: EPI_ISL_17980729, 2023-6-19, Japan
Latest: EPI_ISL_18123116, 2023-8-14, Japan

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice36_genome_1bf0b_c15d10.json?label=id:node_6824890)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/558f0891-9cac-423d-b574-cd610a029f37)

**Comment by aviczhl2** [comment]
70, Germany

**Comment by FedeGueli** [comment]
It cannot compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T12388C%2CT13210C%2CC23280T&analysisMode=CompareToBaseline&

Did you check if any recombination qith BQ.1 involved?

**Comment by FedeGueli** [comment]
scratch that A405G missing

**Comment by FedeGueli** [comment]
It cannot compete also in Japan wherre it is mostly circualting: https://cov-spectrum.org/explore/Japan/AllSamples/Past3M/variants?aaMutations=S%3AQ52H%2CS%3AL455F&nucMutations1=T12388C%2CT13210C%2CC23280T&analysisMode=CompareToBaseline&
