### ISSUE TITLE
FL.7 with ORF1a:S443F (nsp2_S263F) and S:H69, V70 deletion (36 seqs, mainly in USA, 6 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#707]
**Defining Mutations:** `FL.7` > `T2911G` > `C1593T(ORF1a:S443F), del21767_21772(Spike_H69del, Spike_V70del)`
**Query:** `C1593T, T2911G, C21714T` (alt: `G5720A, C11956T, C21714T, del21767_21772`)
**Earliest seq:** 2023-04-23 (`EPI_ISL_17646656`, Campania, Italy)
**Latest seq:** 2023-08-09 (`EPI_ISL_18119825`, Texas, USA)
**Sampled Countries:** USA (26: Texas/22; California/1; Florida/1; New Jersey/1; Puerto Rico/1), Switzerland (2), Dominican Republic (2), Italy (1), South Korea (1), Sweden (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17646656, EPI_ISL_17655864, EPI_ISL_17818485, EPI_ISL_17818897, EPI_ISL_17955568, EPI_ISL_17955743, EPI_ISL_17955771, EPI_ISL_18034145, EPI_ISL_18057111, EPI_ISL_18057229, EPI_ISL_18057250, EPI_ISL_18057289, EPI_ISL_18057352, EPI_ISL_18057360, EPI_ISL_18057387, EPI_ISL_18057395, EPI_ISL_18057472, EPI_ISL_18057503, EPI_ISL_18057513, EPI_ISL_18057534, EPI_ISL_18057573, EPI_ISL_18067369, EPI_ISL_18098919, EPI_ISL_18099059, EPI_ISL_18099308, EPI_ISL_18104675, EPI_ISL_18107319, EPI_ISL_18109994, EPI_ISL_18110989, EPI_ISL_18119759, EPI_ISL_18119765, EPI_ISL_18119825, EPI_ISL_18121458`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23c48_c66ed0.json?c=gt-nuc_1593&label=id:node_6914647

view from FL.7 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/72fd00ad-4407-459b-a689-b08cebe38041)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/fc4b8d0c-301f-4cd4-8fcb-34a2172adf51)

**Trivia:**
- Be careful using _**SGTF only**_ to filter BA.2.86, cause there are quite a few XBBs with it.
![deletion](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/14a2d00e-d5e5-4af8-8c05-bce0816d7546)
![del](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bc9f9239-8d70-41f7-a864-513aaeed798a)

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/North%20America/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C1593T%2CT2911G%2CC21714T&analysisMode=CompareToBaseline& 

sorry i missed this one. it cannot compete.
