### ISSUE TITLE
FL.2.3 / GJ.1* recombinant (2 seq, South Korea)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#708]
South Korea/KDCA257224/2023|EPI_ISL_18117763|2023-07-28
South Korea/KDCA258396/2023|EPI_ISL_18140176|2023-08-02

Query: T4579A, C12225T, G28209C

Breakpoint: 17615~19884

Mutations based on XBB+T23018C:
C2003T, T4579A(FL.2), G5720A(XBB.1.9), C11956T(XBB.1.9.1), C12225T, C12789T(XBB.1.9/23/42), A17615G(FL.2.3) / C19884T(GJ.1/2/3), A22108T(XBB.2.3.3), A22320G(XBB.2), C23123T(XBB.2.3), T27322C, C27431T(XBB.2.3), C27498G, G28209C(GJ.1), G29706T(XBB.2.3)

Extra Mutations: C2003T(Orf1a:L580F), C12225T(Orf1a:A3987V) / T27322C(Orf6:S41P), C27498G(Orf7a:C35W)

C12225T is inherited from FL.2.3> G28980T(N:G236V)> G28279T(N:V236F)> C12225T(Orf1a:A3987V) branch.
There is also 1 sequence with C2003T under this branch, but it seems unrelated.
There are also 2 GJ.1.2 sequences with T27322C, but they are on two different branch and having low quality, so I think they are unrelated.

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json?label=id:node_10778514
![2023-08-28 (5)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/4083c8ad-44d6-41b5-9204-e14588c049ca)

**Comment by FedeGueli** [comment]
Thank you @Over-There-Is quite clear recomb. It is a GJ that has got the T4579A that has been discussed in other issues as  TRS related. So it could have been a good catch for GJ that is already quite fast intrinsically.

**Comment by FedeGueli** [comment]
No more sequence closing it for now
