### ISSUE TITLE
EG.5.1 sublineage with S:P486H (3 seqs from US international Airport with Japan travel history)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#709]
Defining mutations:
EG.5.1> G26051T (ORF3a:S220I)>G9269A (ORF1a:G3002S)>C5467T, A9368G (ORF1a:I3035V), C23019A (S:P486H), C28603T

GISAID query: G9269A, A9368G, T23019A
Earliest seq: 2023-08-15 (US International Airport, with Japan travel history- EPI_ISL_18138469)
Most recent seq: 2023-08-15 (US International Airport, with Japan travel history- EPI_ISL_18138557)
Countries detected: Japan (3, detected from US International Airport)

Usher Tree:
![QQ截图20230828200130](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/76f05ae2-bf2d-4f1c-9297-7b70f1bd3dbb)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bf7a_c6c050.json?c=gt-S_486

The S:P486H is corresponding to C23019A. 486H shows the higher fitness than 486P (Bloom and Neher, 2023), However, the expected count is very low.  We can track the new choice for site S:486.
![QQ截图20230828200158](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/30f19d22-4016-47fb-9dd5-99a6fa2fa220)

![QQ截图20230828200023](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/104441aa-f7a0-4f19-913b-21be23cd632b)

Genomes:
EPI_ISL_18138469, EPI_ISL_18138532, EPI_ISL_18138557

**Comment by FedeGueli** [comment]
on XBB.1.5 backbbone Tyler Starr found it could be deleterious: 
![Schermata 2023-08-28 alle 15 46 05](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4e607e8f-74fa-49d2-994c-5c935561b840)

**Comment by alurqu** [comment]
From the clade-specific Bloom and Neher estimates (from https://github.com/jbloomlab/SARS2-mut-fitness/blob/main/results/aa_fitness/aamut_fitness_by_clade.csv) of non-synonymous mutation fitness effects, there is only an entry for S:486H in clade 23A (XBB.1.5):

clade,gene,aa_mutation,delta_fitness
23A,S,P486H,0.63407

S:P486H could plausibly increase overall viral fitness in other XBB+S:486P clades such as EG.5.1's clade 23F.

**Comment by FedeGueli** [comment]
Closing this for now.
