### ISSUE TITLE
xbc.1.6.3 with ORF1a:T1597I  and ORF1a:A2123V (183 seq.) mostly australia

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#71]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/027101a4-0704-4e62-88fa-c7619cc6dd3b)
first seq. 3-26
most recent 5-9
C13297T, C28791T, C5055T

**Comment by FedeGueli** [comment]
It is the main branch of XBC.1.6.3 could have some advantage although not totally clear as today. Lets wait until the end of the month to have a clearer picture.

**Comment by FedeGueli** [comment]
I think if it has any the one to monitor is the Orf1a:A2123V is 80% of the proposed brnach and the one growing.

**Comment by FedeGueli** [comment]
Please propose this one.

**Comment by FedeGueli** [comment]
Designated HW.1
