### ISSUE TITLE
New EG.5.1.4 sublineage with S:V483I (England, 51 samples UK, as 20/10)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#710]
thx to Dave McNally [tool ](https://ukcovid.xyz/spike-combo.php?type=single&mincount=2)

i spotted a new very  recent sublineage of EG.5.1.4 with a potential mutation of interest S:V483I 
![Schermata 2023-08-28 alle 14 22 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b2c62896-4938-4c3d-a7c1-f6a5e89c9dce)

(**EDITED**)Looking at the new data coming from [J.Bloom](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/summary_overlaid.html)
![Schermata 2023-09-04 alle 00 13 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e71b265e-609a-464c-a76d-812a0793bb71)

Samples
EPI_ISL_18216158, EPI_ISL_18216304, EPI_ISL_18216306,
EPI_ISL_18227081, EPI_ISL_18227104, EPI_ISL_18227314,
EPI_ISL_18227316, EPI_ISL_18227319-18227321, EPI_ISL_18227323-18227325,
EPI_ISL_18227354, EPI_ISL_18227369, EPI_ISL_18227375,
EPI_ISL_18227377-18227378

Tree:
![Schermata 2023-08-28 alle 14 16 09](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1e477769-b0dc-45e2-b5c3-b067d961472d)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_11460_c8eb70.json?c=gt-S_483&label=id:node_6930888

Defining mutations:
EG.5.1.4 >> **Orf3a:P240L** (C26111T) > T9115C > **ORF1a:R1170H** (G3774A), S:V483I  ( G23009A)

Gisaid query: G23009A,G3774A

**Comment by aviczhl2** [comment]
It seems that this tool is based on covspectrum? So I guess it is easy to expand to global mutations?

**Comment by FedeGueli** [comment]
@aviczhl2 it is based on Climb uk database where the UK sequences are placed before they were ready (QC checks) to be uploaded to Gisaid. SO it is not reproducibile cause Gisaid doesnt allow direct unlimited access to their databases while instead releasing each 2-3-4 days an  API then used by CovSpectrum or other scientists to do their analysis.  
you can propose to enhance covspectrum with one more tool like this one on  https://github.com/GenSpectrum/LAPIS/issues opening an issue there.

**Comment by aviczhl2** [comment]
> while instead releasing each 2-3-4 days an API

How to access to such API? Maybe I can develop a tool myself(with 2-3-4 day delay).

**Comment by FedeGueli** [comment]
> > while instead releasing each 2-3-4 days an API
> 
> How to access to such API? Maybe I can develop a tool myself(with 2-3-4 day delay).

@corneliusroemer @tomwenseleers could you help?

**Comment by FedeGueli** [comment]
This jumped to 13 all ENgland none still on Gisaid:
![Schermata 2023-09-04 alle 00 08 31](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/04595666-40ef-4d24-8933-06f41c1359da)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_41aed_502fc0.json?c=gt-S_483&gmax=25384&gmin=21563&label=id:node_6938128

@corneliusroemer please take a look:
From the [new data ](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/summary_overlaid.html)by J.Bloom it seems quite advantageous to gain S:V4831I
![Schermata 2023-09-04 alle 00 09 56](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/76d6d1ab-e2ac-4c56-b1fa-7071df03bb11)

There are 0 samples on Gisaid:
England/CLIMB-CM7YGJSW/2023\|2023-08-21
England/CLIMB-CM7YEI3F/2023\|2023-08-19
England/CLIMB-CM7YJQA4/2023\|2023-08-19
England/CLIMB-CM7YFWSI/2023\|2023-08-21
England/CLIMB-CM7YKGGZ/2023\|2023-08-24
England/CLIMB-CM7YKXEZ/2023\|2023-08-24
England/CLIMB-CM7YGFKO/2023\|2023-08-24
England/CLIMB-CM7YKOT9/2023\|2023-08-23
England/CLIMB-CM7YENF8/2023\|2023-08-23
England/CLIMB-CM7YJ9JM/2023\|2023-08-23
England/CLIMB-CM7YFY64/2023\|2023-08-23
England/CLIMB-CM7YF3NC/2023\|2023-08-23
England/CLIMB-CM7YE4T4/2023\|2023-08-23

**Comment by FedeGueli** [comment]
Sorry using Usher.dev i find already 18 of this sublineage,
![Schermata 2023-09-04 alle 00 41 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/136c88bc-cce1-491f-a9d9-5f5c18332e61)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1b127_50a1d0.json?c=gt-S_483&gmax=25384&gmin=21563&label=id:node_6937949

**Comment by FedeGueli** [comment]
I ma trnasferring it to the main repo.

**Comment by FedeGueli** [comment]
Transferred to https://github.com/cov-lineages/pango-designation/issues/2254

**Comment by aviczhl2** [comment]
> Sorry using Usher.dev i find already 18 of this sublineage, ![Schermata 2023-09-04 alle 00 41 15](https://user-images.githubusercontent.com/87669813/265292248-136c88bc-cce1-491f-a9d9-5f5c18332e61.png) https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1b127_50a1d0.json?c=gt-S_483&gmax=25384&gmin=21563&label=id:node_6937949

What is usher.dev?

**Comment by FedeGueli** [comment]
> > Sorry using Usher.dev i find already 18 of this sublineage, ![Schermata 2023-09-04 alle 00 41 15](https://user-images.githubusercontent.com/87669813/265292248-136c88bc-cce1-491f-a9d9-5f5c18332e61.png) https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1b127_50a1d0.json?c=gt-S_483&gmax=25384&gmin=21563&label=id:node_6937949
> 
> What is usher.dev?

https://genome-test.gi.ucsc.edu/cgi-bin/hgPhyloPlace

**Comment by aviczhl2** [comment]
What's the difference between usher.dev and main usher? More updated with seqs? Is the algorithm different?

**Comment by FedeGueli** [comment]
> What's the difference between usher.dev and main usher? More updated with seqs? Is the algorithm different?

Usher dev  shows sequences before the manual annotations the team of Usher does every evening (!!) so it precedes of just some hours Usher.bio not a big difference. but @angiehinrichs could answer better than me for sure ;)

**Comment by FedeGueli** [comment]
Refused from the main page i keep it monitored here.

**Comment by FedeGueli** [comment]
All the samples are now on Gisaid: EPI_ISL_18216158, EPI_ISL_18216304, EPI_ISL_18216306,
EPI_ISL_18227081, EPI_ISL_18227104, EPI_ISL_18227314,
EPI_ISL_18227316, EPI_ISL_18227319-18227321, EPI_ISL_18227323-18227325,
EPI_ISL_18227354, EPI_ISL_18227369, EPI_ISL_18227375,
EPI_ISL_18227377-18227378

**Comment by HynnSpylor** [comment]
24 seqs now and it rapidly increases in England
I suggest to propose it in main page if reaches 30

**Comment by FedeGueli** [comment]
> 24 seqs now and it rapidly increases in England I suggest to propose it in main page if reaches 30

Thank you @HynnSpylor i already proposed it and was refused, i am waiting for samples outside Uk.
Anyway i ping @corneliusroemer he could decide to review it earlier

**Comment by FedeGueli** [comment]
Still unsure if it could compete or not with Hk.3 but definetely not slow:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G23009A%2CG3774A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Out competed : https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G23009A%2CG3774A&analysisMode=CompareToBaseline&
