### ISSUE TITLE
Another XBB.2.3 and XBB.1.5 recombinant, with S:T732I (44 seqs, 6 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#711]
_different recombinant to #604_

**Defining Mutations:** `XBB.2.3` > _T27431C_reversion(ORF7a:V13A_reversion)_ > _T29706G_reversion_ > `A13187G(ORF1a:I4308V/nsp10_I55V), C22388T, C23757T(S:T732I)` > `G6536A(ORF1a:G2091S)` > `G27915T(ORF8:G8*)`

**Recombinant Profile:**
- Donor A: XBB.2.3, upstream from 5' end to breakpoint
- Breakpoint: Between `nuc 23123/spike_521` to `nuc 27431/ORF7a_13`
- Donor B: Any XBB.1* with `ORF8:G8*` and without `ORF9:I5T`, most likely XBB.1.5, downsteram of breakpoint to 3' end.
- Private mutations: `ORF1a:I4308V`, `C22388T`, `S:T732I`

**Query:** `G6536A, C23757T, G27915T` or `A13187G, C22388T, C23757T` if considering potential `ORF1a:G2091S` dropout (thanx Fede)
**Earliest seq:** 2023-06-30 (`EPI_ISL_18080753`, California, USA)
**Latest seq:** 2023-08-21 (`EPI_ISL_18136401`, Liège, Belgium)
**Sampled Countries:** USA (12, Many with foreign travel history), Guatemala (9), Belgium (1), Mexico (1), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18011156, EPI_ISL_18023025, EPI_ISL_18037651, EPI_ISL_18080753, EPI_ISL_18081441, EPI_ISL_18090453, EPI_ISL_18094952, EPI_ISL_18094954, EPI_ISL_18099404, EPI_ISL_18099406, EPI_ISL_18099422, EPI_ISL_18099424, EPI_ISL_18102662, EPI_ISL_18102696, EPI_ISL_18104413, EPI_ISL_18118410, EPI_ISL_18136401, EPI_ISL_18137317, EPI_ISL_18138518, EPI_ISL_18139698, EPI_ISL_18139701, EPI_ISL_18139731, EPI_ISL_18139754, EPI_ISL_18139756`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f67e_ca71c0.json?label=id:node_7356271
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/876abbe6-e091-4885-9a6b-f9fe3f4b568e)

**Comment by FedeGueli** [comment]
Good spot: i think A13187G, C22388T, C23757T is a better query and finds 29 samples.  i am checking it . ah okit is just a little broader but being all the samples added from Guatemala it makes sense it is the same recombinant

**Comment by FedeGueli** [comment]
It seems circualting in Belgium and Germany. not especially fast but worth tracking.

**Comment by FedeGueli** [comment]
Please propose it
