### ISSUE TITLE
XBB.1.16 with S:P251S (40 seqs, mainly in Thailand, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#712]
**Defining Mutations:** `XBB.1.16` > `C22313T(S:P251S)`
**Query:** `C11956T, T12730A, C22313T, -C2470T, -A2969G, -T3561C, -T4129C, -T15825A, -T27173C`, check `exclude low coverage seqs`
**Earliest seq:** 2023-04-18 (`EPI_ISL_17623937`, Khon Kaen, Thailand)
**Latest seq:** 2023-08-22 (`EPI_ISL_18141220`, Singapore)
**Sampled Countries:** Thailand (16), Japan (6), Singapore (5), China (3: Guangdong/2; Taiwan/1), USA (3: Michigan/2; Washington/1), South Korea (2), Denmark (1), Laos (1), Malaysia (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17602976, EPI_ISL_17622239, EPI_ISL_17622248, EPI_ISL_17623935-17623937, EPI_ISL_17661735, EPI_ISL_17661800, EPI_ISL_17677518, EPI_ISL_17709555, EPI_ISL_17724443, EPI_ISL_17774495, EPI_ISL_17790877, EPI_ISL_17791607, EPI_ISL_17816321, EPI_ISL_17816353, EPI_ISL_17855498, EPI_ISL_17855977, EPI_ISL_17883903, EPI_ISL_17979697, EPI_ISL_17994662, EPI_ISL_17994664, EPI_ISL_18031860, EPI_ISL_18035065, EPI_ISL_18035517, EPI_ISL_18042066, EPI_ISL_18052054, EPI_ISL_18066316, EPI_ISL_18077776, EPI_ISL_18081881, EPI_ISL_18094941, EPI_ISL_18101217, EPI_ISL_18103691, EPI_ISL_18116011, EPI_ISL_18134247, EPI_ISL_18141131, EPI_ISL_18141153, EPI_ISL_18141220`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_394b4_cc2df0.json?f_userOrOld=uploaded%20sample
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4ba814a3-889a-47bc-a463-d782fc8f09fe)

**Trivia:**
- Not a fast one, but very resilient (?) _or_ not enough coverage of it.
![intl](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/12cbdb7c-988b-4164-8271-23118c744bfa)

- `S:P251S` close to XBB.1's defining `S:G252V` and XBB.2's `S:D253G`, wondering if it will do something.
![251+252](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d826297c-a464-4cb5-b3a8-25a5067468c3)

**Comment by FedeGueli** [comment]
Very interesting! thx is there a shorter query possible also if it gets some trash in?

**Comment by FedeGueli** [comment]
Looks like it cant compete but lets track it for some time: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=C11956T%2CT12730A%2CC22313T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Thx!
