### ISSUE TITLE
EG.1 with ORF1a:G379R (nsp3_G1007R) and S:L452R (50 seqs, mainly South Korea, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#713]
**Defining Mutations:** `EG.1` > `C21306T` > `G1400A(ORF1a:G379R)` > `T22917G(S:L452R), C29218T`
**Query:** `G1400A, C21306T, T22917G`
**Earliest seq:** 2023-05-30 (`EPI_ISL_17927651`, South Korea)
**Latest seq:** 2023-08-07 (`EPI_ISL_18134244`, Taiwan, China with travel history to South Korea)
**Sampled Countries:** South Korea (44), China (1, ex. South Korea)

<details><summary>Genomes: </summary>

`EPI_ISL_17835109, EPI_ISL_17835518, EPI_ISL_17927651, EPI_ISL_17927653-17927654, EPI_ISL_17930639, EPI_ISL_17970523, EPI_ISL_18030840, EPI_ISL_18031123, EPI_ISL_18031405, EPI_ISL_18031924, EPI_ISL_18038893, EPI_ISL_18039139, EPI_ISL_18039142, EPI_ISL_18046758, EPI_ISL_18046799, EPI_ISL_18047378, EPI_ISL_18047420, EPI_ISL_18047452, EPI_ISL_18047694, EPI_ISL_18067746, EPI_ISL_18067752, EPI_ISL_18067802, EPI_ISL_18068044, EPI_ISL_18068048, EPI_ISL_18068161, EPI_ISL_18068279, EPI_ISL_18111501, EPI_ISL_18116372, EPI_ISL_18116717, EPI_ISL_18116947, EPI_ISL_18117940, EPI_ISL_18117987, EPI_ISL_18117998, EPI_ISL_18134244, EPI_ISL_18139900, EPI_ISL_18139903, EPI_ISL_18140041, EPI_ISL_18140304, EPI_ISL_18140327-18140330, EPI_ISL_18140363, EPI_ISL_18140612`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a96a_ceae00.json?f_userOrOld=uploaded%20sample&label=id:node_6963318
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/df33bc40-2ea4-4a35-8d5d-c3963b6b1de3)

**Comment by FedeGueli** [comment]
Did you mention this one before weeks ago? i have like a feeling we already saw this one when very small. anyway great catch very interesting to see 452 +613 combo that we observed quite successful in CH.1.1 if it will be the same on XBB.1 backbone.

**Comment by FedeGueli** [comment]
It is going please propose it

**Comment by FedeGueli** [comment]
Thank you.
