### ISSUE TITLE
XBB.1.16* x CH.1.1.1* x XBB.1.16* recombinant, singlet, with S:444T,446S,452R,455F, 456L,478R Denmark

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#718]
I am to pre-propose a singlet recombinant based on its potentially concerning mutation profile at Spike S1.

EPI_ISL_18159982 collected on 2023-08-07 and uploaded on 2023-08-29 from Denmark.

It looks to me like a XBB.1.16* x CH.1.1.1* x XBB.1.16 recombinant with 3 breakpoints at NSP3, NSP12/NSP14, and Spike RBD respectively.

**from 5' to 3857**: CH.1.1.1* (probably DV.7.1 as it has C2227T)
**from 3927 to 14856**: XBB.1.16*
**from 18583 to 22917**: CH.1.1.1*
**from 22995 to 3'**: XBB.1.16*

Thus it has a RBD mutation profile of: **(K444T, G446S, L452R)** from CH.1.1.1*, **(T478R, F486P, F490S)** from XBB.1.16*, and **(L455F, F456L, N460K)** from either donors. 

It also has its NTD from CH.1.1.1*, as well as **ORF1a:L3829F, ORF9b:I5T** and **ORF9b:N55S** from XBB.1.16*.

Other interesting mutations are **ORF1a:141/143del (nuc 686/694del)** and **ORF8:66/67del+ORF8:K68E (nuc 28090/28095 del)** if they're not artefactual.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/726872b3-8e66-4e12-9dac-caecc8cca2d8)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/362c6abe-65b1-4819-8a5b-4b442fc5dc82)

**Query**: C2227T, C10645T, C11750T

**Comment by FedeGueli** [comment]
to me likely it took FLip 455-456 from DV.7.1

**Comment by FedeGueli** [comment]
cc @thomasppeacock @angiehinrichs @corneliusroemer worth a look if it starts growing.

**Comment by FedeGueli** [comment]
no new samples coming of this one, luckily

**Comment by FedeGueli** [comment]
it remained a singlet.
