### ISSUE TITLE
XBB.1.9.1 with S:V6L and S:E554Q (48 seqs, 9 countries) with further sublineage got S:F456L (22 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#719]
**Defining Mutations:**  `XBB.1.9.1` > `C21952T` > `G21578C(S:V6L), G23222C(S:E554Q), C28657T` > `G7331A(ORF1a:V2356I/nsp3_V1538I)`
**Query:** `G21578C, C21952T, G23222C`

**Defining Mutations for Further S:F456L sub-branch:** _main proposal_ > `T13339C, C19961T(ORF1b:T2165M)` > `T22928C(S:F456L), C25572T`
**Query for further S:F456L:** `G7331A, T13339C, T22928C`

**Earliest seq:** 2023-04-30 (`EPI_ISL_17627824`, Washington, USA)
**Latest seq:** 2023-08-16 (`EPI_ISL_18144424`, New York, USA)
**Sampled Countries:** USA (16: NY/7; CA/4; NJ/1; TX/1; UT/1; WA/1), Australia (3), France (2), Canada (1), Greece (1), Ireland (1), Italy (1), Sweden (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17627824, EPI_ISL_17743571, EPI_ISL_17802036, EPI_ISL_17802259, EPI_ISL_17802866, EPI_ISL_17809594, EPI_ISL_17818647, EPI_ISL_17819979, EPI_ISL_17952310, EPI_ISL_17976781, EPI_ISL_18042611, EPI_ISL_18053301, EPI_ISL_18058566, EPI_ISL_18072721, EPI_ISL_18079428, EPI_ISL_18080087, EPI_ISL_18096113, EPI_ISL_18115323, EPI_ISL_18119324, EPI_ISL_18121778, EPI_ISL_18126492, EPI_ISL_18129811, EPI_ISL_18144424, EPI_ISL_18144990, EPI_ISL_18145277, EPI_ISL_18146903`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21ad6_f75b40.json?label=id:node_6924449
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/dcd0db1c-9e2d-45db-a071-0334a0487cc8)

**Comment by FedeGueli** [comment]
Thank you very good spot

**Comment by ryhisner** [comment]
Seven sequences from California today in the F456L branch, along with four from two days ago (Sept 12). One of the four from Sept 12 was a US sequence with travel from Peru, so this could be circulating there. 
EPI_ISL_18252054, EPI_ISL_18252688, EPI_ISL_18252710, EPI_ISL_18252809, EPI_ISL_18260388, EPI_ISL_18260548, EPI_ISL_18260652, EPI_ISL_18260811, EPI_ISL_18260833, EPI_ISL_18261260, EPI_ISL_18261327

**Comment by FedeGueli** [comment]
now 22 , it seems pretty fast . please propose when it reaches 50
