### ISSUE TITLE
XBB.2.3.15  [ORF1a:I4308V (nsp10_I55V)] with ORF1a:M3669I (nsp6_M100I) and S:T323I (62 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#722]
**Defining Mutations:** `XBB.2.3` > `A13187G(ORF1a:I4308V)` > `G11272T(ORF1a:M3669I), C22530T(S:T323I)`
**Query:** `G11272T, A13187G, C22530T`
**Earliest seq:** 2023-06-20 (`EPI_ISL_17952263`, Arizona, USA)
**Latest seq:** 2023-08-16 (`EPI_ISL_18162845`, New Jersey, USA)
**Sampled Countries:** USA (25: CA/14; TX/4; NJ/3; AZ/2; NV/1; NY/1), Guatemala (4), Canada (3: ON/2; AB/1)

<details><summary>Genomes: </summary>

`EPI_ISL_17952263, EPI_ISL_18038125, EPI_ISL_18045676, EPI_ISL_18045918, EPI_ISL_18062539, EPI_ISL_18069595, EPI_ISL_18072544, EPI_ISL_18072550, EPI_ISL_18080828, EPI_ISL_18081484, EPI_ISL_18098781, EPI_ISL_18098973, EPI_ISL_18099421, EPI_ISL_18104565, EPI_ISL_18105243, EPI_ISL_18119806, EPI_ISL_18119822, EPI_ISL_18122247, EPI_ISL_18124435, EPI_ISL_18124514, EPI_ISL_18126244, EPI_ISL_18144756, EPI_ISL_18144841, EPI_ISL_18144861, EPI_ISL_18144878, EPI_ISL_18145021, EPI_ISL_18162749-18162750, EPI_ISL_18162845, EPI_ISL_18163531, EPI_ISL_18163551-18163552`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1303f_f8f520.json?label=id:node_7380459

view from `ORF1a:I4308V` branch, neighbouring to #607 and recombinant #711
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6cc77db3-6c72-47b8-baa1-7a6388420fb5)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1c395930-a634-4202-97a0-c17cca016d93)

**Comment by FedeGueli** [comment]
It seems quite fast lets see

**Comment by FedeGueli** [comment]
tracker: https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?aaMutations=Orf1b%3AD54N&nucMutations1=G11272T%2CA13187G%2CC22530T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
Parental lineage described by you here Designated XBB.2.3.15 via https://github.com/cov-lineages/pango-designation/commit/2fe3c52fddddab7c851aa717dce3fb3fc3fb4ae4
