### ISSUE TITLE
XCH.1/XBB.1.16.15 recombinant(3 seqs, Canada)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#724]
XBB.1.16+

Nt | C900T, C6336T, T10756C,G12038A, T14067C, A16856G,T17124C,T18703G(rev), T22101A(rev),C22624T, G22927T, T22928C, G22995A(rev)C23280T, C23673T, G25947C, C26907T, C27741T

ORF1a | S212L, S2024L, V3925I
Orf1b | D1130G, Y1746D(rev)
S | V180E(rev), L455F, F456L, R478K(rev), T573I, S704L
ORF3a | Q185H

From XBB.1.16.15: T10756C, T14067C
Branch specific mutations:  C900T,C6336T, G12038A 
From XCH.1:
A16856G, T17124C, T18703G(rev), T22101A(rev),C22624T, G22927T, T22928C, G22995A(rev)C23280T, C23673T,G25947C,C26907T,C27741T

XBB.1.16.15--XCH.1--XBB.1.16.15
Breakpoint 1: Between 14068 and 16855
Breakpoint 2: Between 28292 and 28446

GISAID query: C900T,C6336T,G12038A,C27741T
No. of seqs: 2(Canada)
EPI_ISL_18147637, 2023-8-19
EPI_ISL_18147057, 2023-8-21

This one is basically XCH.1-Spike+Orf1a:L3829F, Orf9b:N55S from XBB.1.16, plus 3 additional private Orf1a mutations.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice21_genome_1e55f_6ce0.json?label=id:node_6817414)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/425cc4de-c683-44c3-800b-e6542c042627)

Rapid picture of this:
![Schermata 2023-08-31 alle 11 06 14](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/1d9b6b0e-3cbe-42fd-9ce3-b24736ac65ca)

**Comment by FedeGueli** [comment]
Hi ! i ve proposed it already :https://github.com/sars-cov-2-variants/lineage-proposals/issues/717 why do you think it was XCH the parental lineage?

**Comment by FedeGueli** [comment]
You got it right! thank you:
closing mine and taking your open : 
![Schermata 2023-08-31 alle 09 40 46](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fbe1f4f3-528d-4fc2-a1ab-2a79b1fda667)
![Schermata 2023-08-31 alle 09 40 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ecef6cdd-8034-45c6-b8eb-86aa3c09b4f8)

**Comment by aviczhl2** [comment]
> Hi ! i ve proposed it already :#717 why do you think it was XCH the parental lineage?

Sorry I didn't notice that as I only searched for XCH and XBB.1.16.15 and got no previous repos. Sometimes the same thing can be described in very different forms.

**Comment by FedeGueli** [comment]
> > Hi ! i ve proposed it already :#717 why do you think it was XCH the parental lineage?
> 
> Sorry I didn't notice that as I only searched for XCH and XBB.1.16.15 and got no previous repos. Sometimes the same thing can be described in very different forms.
> 
> This one has Orf1b: D1130G and Orf3a:Q185H, both are XCH defining mutations.

Thank you no no it was me wasnt thinking to XCH  , i ve added a nextclade rapid overview of the lineage that i think it is always helpful to evaluate recombs!

**Comment by aviczhl2** [comment]
+1 Belgium +1 Norway

**Comment by FedeGueli** [comment]
Please propose when it reaches 10

**Comment by aviczhl2** [comment]
@FedeGueli 

The Belgium and Norway seqs are not recombinants. They are XBB.1.16.15-side donator of this. I've changed my query to better fit on the proposed recombinant only.

**Comment by FedeGueli** [comment]
> @FedeGueli
> 
> The Belgium and Norway seqs are not recombinants. They are XBB.1.16.15-side donator of this. I've changed my query to better fit on the proposed recombinant only.

Thank you,

**Comment by FedeGueli** [comment]
maybe a third from Croatia today ushering it...

**Comment by FedeGueli** [comment]
Just two . it seems slow.

**Comment by aviczhl2** [comment]
Still at 2. 

But its XBB.1.16.15 donor grows from 0 to 8 during this period. (C900T,C6336T,G12038A,-27741）

**Comment by aviczhl2** [comment]
+1, reopen

**Comment by FedeGueli** [comment]
Thank you!! reappearing after such a Hyatus!
