### ISSUE TITLE
Fl.1.5.1 with orf3a:T24I issue #522 with ORF1a:P193S and S:95N and S:157L (1) In canada

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#727]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/1efc27e6-eb86-489a-8078-083a072feac0)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_259c_a5d00.json?c=gt-S_157&label=id:node_6981724
EPI_ISL_18150951
sequenced on 2023-08-19
gisaid Query: T14814C, C21036T

**Comment by FedeGueli** [comment]
Thank you for spotting please tag me if it comes to two.
