### ISSUE TITLE
NEW EG.5.1.1 sublineage with S:455F (11) in 3 countries 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#728]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/d49daa04-1054-462c-b059-fa8767d8bf6d)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10907_dfe80.json?c=gt-S_455&label=id:node_6947519
First Seq: 2023-07-15
Most Recent: 2023-08-18
Defining Mutations:
ORF1a:P80S,  ORF1a:L3930F, ORF1b:P1570S, S:L455F
Gisaid Query: C503T, A8116G, C18175T
EPI_ISL_18147293 EPI_ISL_18065046 EPI_ISL_18125017 EPI_ISL_18124879 EPI_ISL_18147263 EPI_ISL_18060497 EPI_ISL_18141863 EPI_ISL_18124861 EPI_ISL_18139669 EPI_ISL_18130075 EPI_ISL_18147248

**Comment by FedeGueli** [comment]
Thank you for spotting already proposed https://github.com/cov-lineages/pango-designation/issues/2229.

I suggest to check the multiple lineages issue tracked in a superlative way by @nkmnzr
