### ISSUE TITLE
HK.3+S:Q14K(11 seq, 2 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#730]
HK.3> C853T> C21602A(S:Q14K)
Query: C853T, C21602A

Earliest Sequence: 08-10 Shanghai, China EPI_ISL_18138275
Latest Sequence: 08-22 Yunnan, China EPI_ISL_18241517
Detected Regions: **China** 9+1(Shanghai 4, Hubei 4, Yunnan 1; Taiwan 1[From Hong Kong]), **Luxembourg** 1.

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?label=id:node_6951915
![2023-09-06](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/568b7d35-1944-49af-8694-9cc4135e8884)

<details><summary>Sequences:</summary>

EPI_ISL_18138275, EPI_ISL_18146044, EPI_ISL_18208487,
EPI_ISL_18208572, EPI_ISL_18208585, EPI_ISL_18217166,
EPI_ISL_18217168, EPI_ISL_18217170, EPI_ISL_18217866,
EPI_ISL_18220655, EPI_ISL_18241517

</details>

1 sequence with C853T reported by Amoy, Fujian, imported from Macao.

**Comment by Over-There-Is** [comment]
Huanggang, Hubei+3
Taiwan+1, from Hong Kong.
Almost all of the sequences in this batch from Taiwan have S:N417Krev artefact.

**Comment by Over-There-Is** [comment]
Luxembourg+1

**Comment by Over-There-Is** [comment]
1 more Chinese province: Yunnan

**Comment by FedeGueli** [comment]
Designated HK.3.2 via https://github.com/cov-lineages/pango-designation/commit/24cc70f23561835ed1456869d0f19c21c7569875

**Comment by Over-There-Is** [comment]
I did not notice that Canada/ON-KHS-05850-v1/2023|EPI_ISL_18222018|2023-08-30 has an N on 21602. And there is a sequence on the same branch has Canada/ON-KHS-05850-v1/2023|EPI_ISL_18222018|2023-08-30. It means, not only China and Luxembourg, HK.3.2 has spread to Canada before designating.
![2023-09-13 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/602da5f5-2163-46fc-81c5-6ac77f3db618)
![2023-09-13 (2)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/eda9170f-722a-46e8-b67f-fb8e5e54aec2)
@AngieHinrichs

**Comment by AngieHinrichs** [comment]
Thanks @Over-There-Is, I think this is fixed now (Canada/ON-KHS-05850-v1/2023|EPI_ISL_18222018|2023-08-30 is in HK.3.2).

**Comment by Over-There-Is** [comment]
Q677H 4seq Ontario, Canada
G184A 3 seq Shanghai, China

**Comment by Over-There-Is** [comment]
R214H, I1221T 4 seq, 5 countries (Singapore, US [Washington, from Japan], China [HK], Australia [WA])

**Comment by FedeGueli** [comment]
> R214H, I1221T 5 seq, 6 countries (Singapore, US [Washington, from Japan], China [HK], Australia [WA], UK [England])

feel free to open an issue for each of this lineages or to open a spike diversity issue where you can track HK.3.2 spike diversity (mutation, query count) until something shows some solid growth

**Comment by Over-There-Is** [comment]
L822F 16seq UK

**Comment by Over-There-Is** [comment]
![2023-10-24 (7)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/b5c1d814-7d51-4541-ad72-3b2ce37c52fa)
EPI_ISL_18362064 has no coverage on 337
