### ISSUE TITLE
XBB.2.3 sublineage with S:E654K and possible S:K478T reversion (25 seqs in India and US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#731]
Defining mutations:
XBB.2.3> C5622T (ORF1a:P1786L)> C7303A> C10776T (ORF1a:P3504L), C22624T, G23522A (S:E654K)
GISAID query: C7303A, C10776T, G23522A
Earliest seq: 2023-06-20 (Maharashtra, India- EPI_ISL_18052802)
Most recent seq: 2023-08-24 (Maharashtra, India- EPI_ISL_18209977)
Countries detected: India (24, including 1 detected in US International Airport), US (1)

Usher Tree:
![QQ截图20230901220922](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7ecc80bc-2781-4856-ab39-082229e40751)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10b57_1ed5f0.json?c=gt-S_654

It is a branch with S:G184V ( proposed but undesignated in https://github.com/cov-lineages/pango-designation/issues/1945/EDITED)  but without another defining mutation of XBB.2.3.2 (ORF1a:R2159W), hence it is not classified as XBB.2.3.2

Another notable feature is the almost seqs are possible S:K478T reversion. If we show the S:478 on neighbored branches, the other branch are not the concentrative reversion. Moreover, if we query the other samples updated in the same batch on GISAID, the samples outside the branch are all showing the S:T478X mutation. Therefore, I suggest the reversion is possibly true instead of artefacts. 
![QQ截图20230901221055](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/201f75ae-0906-465a-aa3c-f63f63eee6ef)

*The branch accounts for >30% of samples updated in India today, and over half of them are collected in last 10 days.

Genomes:
EPI_ISL_18052798, EPI_ISL_18052802, EPI_ISL_18120273, EPI_ISL_18120276, EPI_ISL_18125007, EPI_ISL_18126472,
EPI_ISL_18209930-18209931, EPI_ISL_18209936, EPI_ISL_18209945, EPI_ISL_18209947-18209948, EPI_ISL_18209950-18209951, EPI_ISL_18209954, EPI_ISL_18209959, EPI_ISL_18209961, EPI_ISL_18209967, EPI_ISL_18209969, EPI_ISL_18209973, 
EPI_ISL_18209976-18209977, EPI_ISL_18209980-18209981, EPI_ISL_18209983

**Comment by FedeGueli** [comment]
Thx for proposing also @ryhisner noticed it. 
S:T478T is a trend i was trying to tracking and does not surprise me that is now blooming out. thank you.

**Comment by FedeGueli** [comment]
That branch is a long time pending proposal by @aviczhl2 https://github.com/cov-lineages/pango-designation/issues/1945

cc @corneliusroemer could you take  a look an undesignated branch is giving birth to fast (apparently) lineages.

**Comment by FedeGueli** [comment]
Being at 35% in MH and already went from 1 to 25 in one month in a very low sequencing area. i think it is better to propose directly. great spot @HynnSpylor and @ryhisner

**Comment by HynnSpylor** [comment]
Thx @FedeGueli!

**Comment by FedeGueli** [comment]
44 seqs now. it slowed down but it was found in 2 more countries i think it is worth a proposal once it has reached 50.

It has to be noticed that Orf1a:P1786L is NSP3_P968L > PLPro_P223L

**Comment by FedeGueli** [comment]
Designated JY.1 via https://github.com/cov-lineages/pango-designation/commit/e4f431ba40282c47792704bc8668006671467cd7
