### ISSUE TITLE
#559(DV.7.1)+S:K679R(14 seqs, Spain, Switzerland, Iceland, France Canada)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#732]
#559 +S:K679R(A23598G)

GISAID query: A23598G,A10323G,G22927T
No. of seqs: 10(Spain 9 Iceland 1)

First: EPI_ISL_18112358, Spain, 2023-7-26
Latest: EPI_ISL_18209613, Spain, 2023-8-24

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_29b71_280d30.json?label=id:node_7685523)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6bc87a6f-22a9-44ad-b769-3f168b69b31d)

**Comment by FedeGueli** [comment]
Now also Switzerland 12 tot.

**Comment by FedeGueli** [comment]
+2 Fra  Can

**Comment by FedeGueli** [comment]
> There's also FK.1.1* with S:N679R, what's happening on CH.1.1*

i think we already tracked one 679R in CH.1.1 backbone months ago (likely in the main page)

**Comment by aviczhl2** [comment]
Designated DV.7.1.1
