### ISSUE TITLE
XBB.1.22.1 (sub-lineage of #2053 / S:Q675K) with S:T385A and S:D1118Y (16 seqs, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#733]
**Defining Mutations:** `XBB.1.22.1` > `C925A(ORF1a:D220E), G2265A(ORF1a:C667Y), C23585A(S:Q675K)` > `C10615T` > `C19884T` > `C10456T, A22715G(S:T385A), G24914T(S:D1118Y)` > `C1913T(ORF1a:R550C), C3540T(ORF1a:A1092V)`
**Query:** `A22715G, C23585A`
**Earliest seq:** 2023-07-27 (`EPI_ISL_18094197`, England)
**Latest seq:** 2023-08-16 (`EPI_ISL_18209599`, Spain)
**Sampled Countries:** Spain (7), UK (5: England/3; Scotland/2), Belgium (2), Portugal (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17859769, EPI_ISL_18094197, EPI_ISL_18094204, EPI_ISL_18118892, EPI_ISL_18119257, EPI_ISL_18119260, EPI_ISL_18142239, EPI_ISL_18167983, EPI_ISL_18168151, EPI_ISL_18209594-18209599`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f346_2d4210.json?c=gt-S_385&gmax=25384&gmin=21563&label=id:node_6881038

view from XBB.1.22.1 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1c0f9a89-5939-4d70-9259-fba2717e0315)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7c937edc-04ba-4894-957a-a7995207cc64)

**Trivia:**
- Another emerging branch of undesignated niché `S:Q675K` sub-lineage of XBB.1.22.1, proposed by @HynnSpylor at cov-lineages/pango-designation#2053 , after some `S:R408X` branches earlier tracked #296 and #410 , this sub-lineage kept popping up some surprises.
- `S:T385A` is quite rare, only sampled 210-ish times during the whole pandemic. But a recent uptick of mutations around `Spike_38X` loop is awared.

**Comment by FedeGueli** [comment]
XBB.1.22 is really a prolific lineage in terms of spike mutations. Lets see if it manages to regain that bit of speed it always lacked till now.

**Comment by FedeGueli** [comment]
+1 Israel

**Comment by FedeGueli** [comment]
No new sequences closing it
