### ISSUE TITLE
GF.1* (XBB.1.5.24.1, #2086) and EG.5.1* recombinant (5 seqs, China and Sweden) with 1 singlet got further S:L455F (Sweden)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#734]
**Defining Mutations:** **GF.1 (XBB.1.5.24.1)** > `A8197G` > `G18105T(ORF1b:Q1546H/nsp14_G22H)` > `G15908A (ORF1b:G814D/nsp12_G823D)` > `A9153G(ORF1a:Q2963R)` > `T28297C(ORF9b:I5T)` > `A27507C` > `T2372C, C22480T, T22930A(S:F456L)`, _T23805A_revsersion(S:V748E_reversion)_, `C29625T(ORF10:S23F)`
**Query:** `A9153G, G15908A, C22480T`

**Recombinant Profile:** 
- **Donor A**: **GF.1** (XBB.1.5.24.1) with `ORF1b:G814D/G15908A`, `ORF1b:Q1546H/G18105T`, proposed as cov-lineages/pango-designation#2086 , and extra `ORF1a:Q2963R/A9153G` (largest sub-branch of that proposal), upstream from 5' end to breakpoint
- **Donor B**: **EG.5.1** (XBB.1.9.2.5.1), downstream from breakpoint to 3' end; Probably **NOT** EG.5.1.1 for the recombinant doesn't have `C25572T` after breakpoint
- Breakpoint: between `nuc 21718/spike_52` to `nuc 22480/spike_306`
- Private mutation: `T2372C`

**Earliest seq:** 2023-07-13 (EPI_ISL_18074915, Yunnan, China)
**Latest seq:** 2023-08-17 (EPI_ISL_18162572, Skåne, Sweden, with extra `S:L455F`)
**Sampled Countries:** China (3: Hubei; Shanghai; Yunnan), Sweden (2)

<details><summary>Genomes: </summary>

`EPI_ISL_18060792, EPI_ISL_18074915, EPI_ISL_18078307, EPI_ISL_18147779, EPI_ISL_18162572`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d704_2fa1a0.json?label=id:node_6892754
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d9c27a67-702a-404c-b1b3-46b8ffe4942e)

**Comment by aviczhl2** [comment]
#725

**Comment by aviczhl2** [comment]
> > #725
> > 4/5 has C25572T, weird as this recombinant has a private mutation 2372 indicating they are of the same source.
> 
> @aviczhl2
> 
> Ah, didn't see your proposal. I put this up [in the comment about weeks ago](https://github.com/cov-lineages/pango-designation/issues/2086#issuecomment-1625601127) but didn't make proper issue about it, I'll leave this to you then.
> 
> And yes, 4/5 has `C25572T` so the one without it could be dropout? BTW there's only one with _Flip_ atm

Yeah, only one with Flip.
