### ISSUE TITLE
DV.7.1+S:K478R, Orf1a_V1143F=nsp3_V325F 9 seqs in  England, Spain and Netherland as of 10-10

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#737]
Descendent of DV.7.1 (judged from flip+S:L858I +CH*)
Mutations on top of that: 
C10228T ( small, 6 seq branch)+ T20833C, A29172T (N:H300L)
C10615T, A22995G (S:K478R)
Inquiry of this lineage:Spike_L455F,L858I,T478R  
Nucleotides query:  T4036A,C10228T,22995G,C19017T (edited again)
Sequence 1/First  is  EPI_ISL_18107088 from Luxemburg in 23-07-10
Sequence 2/Second is  EPI_ISL_18209326 from England in 23-08-12
Downsampled tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2d0a4_3efad0.json?f_userOrOld=uploaded%20sample
DV.7.1 tree: (edited)
![Schermata 2023-09-03 alle 08 57 20](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/26f92da1-e137-4dab-ad19-dbcf9c4e502e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e8a5_42dff0.json?c=gt-S_478&label=id:node_7689922
![Schermata 2023-09-03 alle 08 57 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a96f9d2d-ef4f-4b1e-b05f-69d2203ba8cd)

It is rather rare that CH* got S:T478R mutation, and it is interesting when the second sequence is in a foreign country (although it's probably also because Luxemberg is so small)

**Comment by FedeGueli** [comment]
Thank you @krosa1910 very good spot.

**Comment by krosa1910** [comment]
Grow to 4 seemingly, spread to Spain.

**Comment by krosa1910** [comment]
<img width="1012" alt="Screenshot 2023-09-07 at 5 43 53 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/ea0a7734-e575-453d-b6a2-dbf9e88ff5c7">
The latest 3 seem to form a branch with the mutation orf1a:V1143F=nsp3_V325F, and it is predicted to be positive and showed up in a weird long past mutant B.1.1.433, which created a temporary spread in Denmark back in 2020 winter.

**Comment by FedeGueli** [comment]
thank you please propose it when it reaches 10

**Comment by krosa1910** [comment]
Spain and Scotland have some new updates. 
Also, the earliest Luxemburg sequence is excluded.

**Comment by FedeGueli** [comment]
Better keeping it track here for a while. It didnt take off while it could and now it is likely too late.

**Comment by krosa1910** [comment]
> Better keeping it track here for a while. It didnt take off while it could and now it is likely too late.

Agree, now it seem nowhere to compete with stronger variants like HK.3* or BA.2.86.1, I don't even mention JN.1. I guess DV.7.1 lost its window to gain more privilege position in Europe as a whole, and could only remain their as a "normal FLip". with low frequency, just like CH.1* in 2022 winter.

**Comment by FedeGueli** [comment]
It didnt be successful
