### ISSUE TITLE
XBB.2.3.2 with S:S98F, S:V622F and ORF1a:P2950H (14 seqs, Canada-MB)

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#74]
Uploaded on 2023-05-19, and collected between 2023-04-24 and 2023-05-05.

**Mutation on branch**: G2731A, C9114A (ORF1a:P2950H), C21855T (S:S98F), G23426T (S:V622F)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/e7e018e6-1510-4b04-9bc4-3cc105cf4e50)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25adc_86a510.json?c=userOrOld&label=id:node_10180096

**Genomes**: EPI_ISL_17686770, EPI_ISL_17686772-17686774, EPI_ISL_17686776, EPI_ISL_17686787-17686788, EPI_ISL_17686790-17686791, EPI_ISL_17686797, EPI_ISL_17686799, EPI_ISL_17686803

Edited: Gisaid query:  C9114A,G2731A, C21855T, G23426T

**Comment by FedeGueli** [comment]
no new seqs. Last week for this one to pop up again before closing it.

**Comment by FedeGueli** [comment]
2 sequences uploaded after June 1 always from Canada. I

**Comment by FedeGueli** [comment]
i m closing this for now
