### ISSUE TITLE
XBB.2.3.11 saltation with ORF1a:G989S (nsp3_G171S), ORF1b:A1131V (nsp13_A208V), S:A262D, S:Q675H and S:A701V (14 seqs, England, Sweden) with a recent sublineage with S:E554K (3 Seqs, Uk)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#743]
**Defining Mutations:** `XBB.2.3.11` > `T352C, T1606C, G3230A(ORF1a:G989S), C16859T(ORF1b:A1131V), C22347A(S:A262D), G23587C(S:Q675H), C23664T(S:A701V), C27630A, T28007C`
**Query:** `C4234T, T1606C, C16859T`
**Earliest seq:** 2023-07-03 (`EPI_ISL_18078369`, England)
**Latest seq:** 2023-08-17 (`EPI_ISL_18209267`, England)
**Sampled Countries:** UK (8: England)

<details><summary>Genomes: </summary>

`EPI_ISL_18066833, EPI_ISL_18078369, EPI_ISL_18130698, EPI_ISL_18130771-18130773, EPI_ISL_18209267, EPI_ISL_18209283`
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25432_497e30.json?f_userOrOld=uploaded%20sample

view from XBB.2.3.11 polytomy
![poly](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/86794477-283d-4cae-939e-c63e13ac79f3)

details
![detials](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a245e897-7a52-494b-b0d5-33180e679173)

**Further sublineage with S:E554K** 
Defining: #743> C10969T, T13668C > C11962A, T14409C, S:E554K (G23222A), C28256T
Query:   T1606C, C16859T,G23222A
Samples 3:
EPI_ISL_18467085, EPI_ISL_18499772, EPI_ISL_18514526
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ccbc_8a27e0.json?label=id:node_4017690
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/49f4959c-f86a-43c8-832d-7d4a9da8fb5b)

**Comment by FedeGueli** [comment]
9 England

**Comment by FedeGueli** [comment]
it was likely just  a cluster closing it.

**Comment by FedeGueli** [comment]
Noticed those ones too, i didnt recall it was already proposed. so i reopen it , if all the recent october(November seuqences are from that branch please change the issue in a proposal of that heavy mutated  branch: have you a query for it?

**Comment by FedeGueli** [comment]
Ok @NkRMnZr to save your time i ve dited the proposal on my own. thank you for spotting.

**Comment by FedeGueli** [comment]
closing it only one from november
