### ISSUE TITLE
EG.5.1.1/XBB.1.16 recombinant with additional 5-nuc,4-aa including S:F157L (13 seqs, 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#745]
EG.5.1.1+
A1982G,C10408T,C22033A,C27507A(rev),C28000T, A28182G, A28447G,C29386T,T29625C(rev)

EG.5.1.1--XBB.1.16
breakpoint between 25573 and 27506

Private mutations: C10408T,C28000T(Orf8:P36L)

GISAID query: C28000T,C25572T,-27507,G13627A(edited)
No. of seqs: 3(China 1 Japan 1 USA 1)

First: EPI_ISL_18105530, China, 2023-8-1
Latest: EPI_ISL_18144757, USA, 2023-8-16

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3fc6c_4c3120.json?c=gt-S_157)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1bef6eb2-35f1-4afa-b492-ad58ee3e9e4a)

Rapid picture of this recombinant (edited)
![Schermata 2023-09-03 alle 23 52 14](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ac027cdf-81f1-457a-8ac7-15c606e8df95)

**Comment by FedeGueli** [comment]
Good catch and apparently good recombinant.

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by aviczhl2** [comment]
+2 New Zealand

**Comment by FedeGueli** [comment]
It seems slow

**Comment by aviczhl2** [comment]
> It seems slow

This one seems to be circulating at some undersampled regions, and exporting to different countries from time to time

**Comment by FedeGueli** [comment]
> > It seems slow
> 
> This one seems to be circulating at some undersampled regions, and exporting to different countries from time to time

Yes likely added the label.

**Comment by aviczhl2** [comment]
9, Israel

**Comment by FedeGueli** [comment]
It doensnt seem fit enough to circulate. closing for now . Ping to @corneliusroemer for recombinant search

**Comment by aviczhl2** [comment]
+1 USA from Sweden

**Comment by FedeGueli** [comment]
Having added a new recent sample from a new country i ve reopened it to keep it tracked.

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
Thank you for the new query still it struggles to grow significantly closing it for now

**Comment by aviczhl2** [comment]
+4 Sweden
