### ISSUE TITLE
Another FL.15+S:L455F branch(15 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#747]
FL.15+C5161T+A18222G+A13303G,C21812T+T15357G,G22927T(S:L455F)

Edited: different from https://github.com/sars-cov-2-variants/lineage-proposals/issues/646

GISAID query: T15357G,G22927T
No. of seqs: 4(South Korea 2 Taiwan 1(from Malaysia) Shanghai 1)

First: EPI_ISL_18164770, Taiwan from Malaysia, 2023-8-1
Latest: EPI_ISL_18114867, Shanghai, 2023-8-13

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice13_genome_23286_566030.json?c=gt-S_455)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6ef0beea-b383-4a6c-9214-320a075f4184)

**Comment by FedeGueli** [comment]
I mentioned the other to make understandable the titletrack.

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by aviczhl2** [comment]
+1 Canada

**Comment by aviczhl2** [comment]
+1 Singapore

**Comment by aviczhl2** [comment]
+1 USA

**Comment by FedeGueli** [comment]
Slowly starting to circulate.

**Comment by FedeGueli** [comment]
just three samples in October closing it
