### ISSUE TITLE
BQ.1.2 saltation with S:R214C, S:G504D, S:Y796C, S:141-144del, S:373-374del and 17 other non-Spike aa mutations (2 seqs in Israel)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#748]
Defining mutations:
BQ.1.2>C683T>C1091T (ORF1a:P276S), C25658T (ORF3a:T89I)>saltation branch

AA mutations (from clades.nextstrain)

Spike:
Shared: R214C, F375P, A376L, G504D, Y796C (S:D796Y→Y796C)
For earlier seq: E748Q
For later seq: S408R (rev), S:H1101D

ORF1ab: 
Shared: L681F, T812A, D1323N, T1638N, P1640S, T3058I, L4715P

E:
shared: T30I

M:
shared: N3I, G6S, G78S, S94R

N:
shared: P122S, N140T, T325I

ORF6a: 
for later seq: D61H

ORF7a: 
for later seq: A50S

ORF10:
for later seq: V6I

AA deletions (show Spike only):
del24-26, del69-70, del141-144, del 373-374

![QQ截图20230904211605](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/ec182d81-5c8e-43fc-838b-91b38641bc79)

![QQ截图20230904222402](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/b17b2963-5bb5-4c7e-bd4f-124bfbe06fc0)

(why there is del373-374 instead of del375-376?)

GISAID query: C683T, C22202T, A23949G

Earliest seq: 2023-07-09 (Israel- EPI_ISL_18012526)
Most recent seq: 2023-08-20 (Israel- EPI_ISL_18215482)
Countries detected: Israel (2)

Usher Tree:
![QQ截图20230904221506](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/408f2b34-1397-4aa8-9a02-4cc6f46613ae)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_44b9_5942d0.json

Usher also shows that the other neighbored seqs are all in Israel (in Oct2022-Nov2022), so the origin is quite clear. However, the 2 samples have certain differences and without detail Metadata information. It needs to be confirmed whether it is from one chronic patient or 2 individuals.

Genomes:
EPI_ISL_18012526, EPI_ISL_18215482

**Comment by ryhisner** [comment]
I feel pretty sure this is a chronically infected individual, but I've asked a researcher from Israel to look into this to be sure. When/if I hear back, I'll post an update here.

**Comment by silcn** [comment]
Yeah, E:T30I usually means it's a chronic case. The only designated lineage ever to have it is B.1.616, and I believe that's the only variant ever identified to have switched to primarily infecting the LRT. As a result, not only was it possibly more virulent than even Delta, but it was also very difficult to detect with nasopharyngeal swabs, which one would expect might have given it a huge advantage in winter 2020/21 when people were still regularly testing - and yet it never spread far.
I don't think the mutations responsible for the tropism shift were ever identified but E:T30I has to be a possibility.

**Comment by FedeGueli** [comment]
Closing this
