### ISSUE TITLE
XBB.1.16 Cluster with ∆69-70 (7 seq, Sweden)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#749]
**Description**
**Sub-lineage of:** XBB.1.16
**Earliest sequence:** 2023-8-18, Sweden, EPI_ISL_18147745
**Most recent sequence:** 2023-8-26, Sweden, EPI_ISL_18216652
**Countries circulating:** Sweden (6)
**Number of Sequences:** 6
**GISAID AA Query:** Spike_E1202Q, Spike_T883I, Spike_H69del
**GISAID Nucleotide Query:** A19002G, G3431A, G25166C
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.16* & A19002G & G3431A & G25166C
**Substitutions/Deletions on top of XBB.1.16:**
**Spike:** ∆69-70, T883I, E1202Q
**N:** R204Q
**ORF3a:** T34M
**ORF1a:** V1056M, N1081S
**ORF9b:** R32L
**Nucleotide:** G3431A, A3507G, A19002G, ∆21765-21770, C24210T, G25166C, C25493T, G28378T, G28884A
 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16_69-70del.json
<img width="1493" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/65aec9da-9120-4435-b6f7-4a467f35027c">

**Evidence**
These are all from Orebro, Sweden, so there's a good chance this is a local cluster that will disappear and never be seen again. Still, it's interesting to see a ∆69-70 cluster emerge at the same time as another ∆69-70 lineage (BA.2.86), perhaps portending yet another swing of the enigmatic ∆69-70 pendulum. 
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18147745, EPI_ISL_18216642, EPI_ISL_18216645-18216646, EPI_ISL_18216648, EPI_ISL_18216652
</details>

**Comment by FedeGueli** [comment]
one more from Sweden

**Comment by FedeGueli** [comment]
It seems slow likely just a cluster?

**Comment by FedeGueli** [comment]
Too slow.
