### ISSUE TITLE
Another DV.7.1+S:K679R(8 seqs, UK)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#750]
#697+A24373G+C26022A(Orf3a:D210E)+T3204C(Orf1a:L980S)+A23598G(S:K679R)

GISAID query: A23598G,T3204C
No, of seqs: 7(UK)
6 on GISAID, 1 not
First: EPI_ISL_18135072, 2023-8-2
Latest: CLIMB_CM7Y8M8N, 2023-8-18

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1548b_69a6a0.json?label=id:node_7691741)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/bc47b08e-3cba-4bcc-979f-df61d2694082)

The other DV.7.1 +679R is https://github.com/sars-cov-2-variants/lineage-proposals/issues/732 (Edited)

**Comment by FedeGueli** [comment]
FCS+Flanking residues : SYQTQTRSHRRARSVASQA

**Comment by FedeGueli** [comment]
Ty
