### ISSUE TITLE
XBB.1.17.1 Sublineage with S:N148T, S:∆177-181, S:Q218R, S:S494P, S:P521S, E:S68F, ORF1a:E622G, ORF1a:T1429I, ORF1b:G1568C (11 seq, France, Uk, NY , Quebec Sept 29)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#755]
### **Description**
**Sub-lineage of:** XBB.1.17.1
**Earliest sequence:** 2023-8-21, France, Ile-de-France, Bobigny, — EPI_ISL_18221906, EPI_ISL_18221907
**Most recent sequence:** 2023-8-21, France, Ile-de-France, Bobigny — EPI_ISL_18221906, EPI_ISL_18221907
**Countries circulating:** France (2)
**Number of Sequences:** 2
**GISAID AA Query:** NSP14_G44C, E_S68F, Spike_Q218R
**Alternative Query** :  A22215G, T25902A,T23042C (4/4) or C8140T, C9298T, C26447T  (3/4)**(EDITED)**
**GISAID Nucleotide Query:** T12655C, A22215G, T25902A (2/4)
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.17.1* & [2-of: T12655C, A22215G, T25902A]
**Substitutions/Deletions on top of XBB.1.17.1:**
**Spike:** N148T, ∆177-181, Q218R, S494P, P521S
**N:**
**ORF1a:**E622G, T1422I (NSP2_E442G, NSP3_T611I)
**ORF1b:** G1568C (NSP14_G44C)
**Nucleotide:** A2130G, C4511T, C8140T, C9298T, T12655C, G18169T, ∆22091-22105, A22005C, A22215G, T23042C, C23123T, T25902A, C26447T
 
**Phylogenetic Order of Mutations:** A2130G, C4511T (ORF1a:E622G, ORF1a: T1429I) **→** C23123T (S:P521S) **→** A22005C, T23042C (S:N148T, S:S494P) **→** C8140T, C9298T, T12655C, G18169T, ∆22091-22105, A22215G, T25902A, C26447T

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.17.1__N148T_177-181del_Q218R_S494P_P521S.json?c=gt-S_218&gmax=25384&gmin=21563&label=id:node_7051983
<img width="1403" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d67b34ca-5ace-453d-9d1d-611c6e07eddb">

 
**Evidence**
This lineage consists, so far, of only two sequences from separate hospitalized patients in France, both collected on August 21. I'm posting it here because XBB.1.17.1 seems likely to have originated in western Africa and is presumably still most common there. We get so few sequences from that region that it's impossible to know what is circulating in recent weeks. These two identical sequences have a large number of mutations, particularly in spike, so I think it's conceivable it evolved in a stepwise manner through fairly wide circulation in some part of Africa. Most likely it will disappear soon, but it seems worth tracking to me, particularly with its very unusual (perhaps unique) deletion in the N4 NTD loop (S:∆177-181).
 
<img width="1467" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7082b77a-a179-4479-ab9d-2e7cd341f2ab">

 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18221906, EPI_ISL_18221907
</details>

**Comment by HynnSpylor** [comment]
2 more seqs (France+1 Scotland, UK+1)

**Comment by FedeGueli** [comment]
> NSP14_G44C, E_S68F, Spike_Q218R

which query are you using?

**Comment by FedeGueli** [comment]
C8140T, C9298T, C26447T finds 3

**Comment by FedeGueli** [comment]
This jumped to 10 reaching also Quebec and NY and one new region in France.

**Comment by FedeGueli** [comment]
one more from England

**Comment by FedeGueli** [comment]
Designated GA.7.1 via https://github.com/cov-lineages/pango-designation/commit/d00ef95a0a984ca112bd02877afc8cf9d56cbb75
