### ISSUE TITLE
monitor: BA.2.86 with ORF7a:E22D(G27459T) (21 seqs）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#756]
only have 3 seqs on GISAID,from Canada and South Africa.Slow, so monitoring.

**EPI_ISL ID** ：EPI_ISL_18125259, EPI_ISL_18164467, EPI_ISL_18168185

https://nextstrain.org/groups/neherlab/ncov/BA.2.86
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/9f6fab68-b85f-4ad1-8ac5-299878d7eb4f)

**Comment by Over-There-Is** [comment]
North West, South Africa +1

**Comment by Memorablea** [comment]
8

**Comment by Memorablea** [comment]
18 now .It's like this. It's like this. Due to the relatively small number of BA.2.86, the growth of this branch is very slow. And most of them are South African sequences.cc @FedeGueli

**Comment by Memorablea** [comment]
21

**Comment by FedeGueli** [comment]
Designated BA.2.86.2 via https://github.com/cov-lineages/pango-designation/commit/fb96d0a2615265f16525fe555106273f12c53bca

**Comment by Memorablea** [comment]
thx

**Comment by Memorablea** [comment]
> Designated BA.2.86.2 via [cov-lineages/pango-designation@fb96d0a](https://github.com/cov-lineages/pango-designation/commit/fb96d0a2615265f16525fe555106273f12c53bca)

@FedeGueli Hello, I have discovered a new cluster. BA. 2.86.1 and S: T299I, but I am unable to raise an issue. Can you help me?

**Comment by FedeGueli** [comment]
> > Designated BA.2.86.2 via [cov-lineages/pango-designation@fb96d0a](https://github.com/cov-lineages/pango-designation/commit/fb96d0a2615265f16525fe555106273f12c53bca)
> 
> @FedeGueli Hello, I have discovered a new cluster. BA. 2.86.1 and S: T299I, but I am unable to raise an issue. Can you help me?

For sure. why are you unable? technical issue or the tree is unclear?

i suggest to ceck the Cornelius? BA.2.86 tree here: https://nextstrain.org/groups/neherlab/ncov/BA.2.86?c=gt-S_157&gmax=25384&gmin=21563

**Comment by Memorablea** [comment]
> > > Designated BA.2.86.2 via [cov-lineages/pango-designation@fb96d0a](https://github.com/cov-lineages/pango-designation/commit/fb96d0a2615265f16525fe555106273f12c53bca)
> > 
> > 
> > @FedeGueli Hello, I have discovered a new cluster. BA. 2.86.1 and S: T299I, but I am unable to raise an issue. Can you help me?
> 
> For sure. why are you unable? technical issue or the tree is unclear?
> 
> i suggest to ceck the Cornelius? BA.2.86 tree here: https://nextstrain.org/groups/neherlab/ncov/BA.2.86?c=gt-S_157&gmax=25384&gmin=21563

It's like this, there's a problem with my network and I can't log in to GISAID.

**Comment by FedeGueli** [comment]
> > > > Designated BA.2.86.2 via [cov-lineages/pango-designation@fb96d0a](https://github.com/cov-lineages/pango-designation/commit/fb96d0a2615265f16525fe555106273f12c53bca)
> > > 
> > > 
> > > @FedeGueli Hello, I have discovered a new cluster. BA. 2.86.1 and S: T299I, but I am unable to raise an issue. Can you help me?
> > 
> > 
> > For sure. why are you unable? technical issue or the tree is unclear?
> > i suggest to ceck the Cornelius? BA.2.86 tree here: https://nextstrain.org/groups/neherlab/ncov/BA.2.86?c=gt-S_157&gmax=25384&gmin=21563
> 
> It's like this, there's a problem with my network and I can't log in to GISAID.

Ok i am sorry to hear. Hope you will resolve soon. To me 299I is not super urgent so if you can resolve it you will propose it when you can rejoin Gisaid. Alternatively you can put together a proposal using Covspectrum
