### ISSUE TITLE
BA.2 single saltation with >20 Spike aa mutations (2023-08-24 in Canada)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#757]
It is a singlet seq, but the mutations are interesting and we can have a track. 

Definition mutations:
BA.2>C9803T>C19186T>C4832T>saltation branch

AA mutations:

ORF1a: V38A, S166G, E256D, Q362R, S771G, K1281R, T1543I, K1795Q, P2046L, N2155S, A2355S, D3936N, Q3966R

ORF1b: R340K, G662S, A2143V

S: W152R, F157S, K187E, G257D, D339H, R346T, A348P, V395L, R403K, L452R, N460K, N477D, G482A, A484E (rev), G496S, H505Y (rev), A570V, N606D, I651V, Q675H, A942S, Q1113K, G1219C

E: I9T (rev)

M: A2V, E12D, I52L

ORF6a: L61F

ORF7a: N43S

ORF7b: D8E

ORF8a: G96S, V117G

N: T271I
![QQ截图20230906221805](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/05ffb54c-031c-427d-a18c-a7ac2d11c1d6)

Deletions (Spike only):
del24-26

Insertion (Spike only):
ins212AG
![QQ截图20230906221640](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/aeb0d078-f34e-422e-b8bd-19822f1398ca)

GISAID query: G23048A, C23271T, A23378G

Usher Tree:
![QQ截图20230906221537](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/79bf1912-0d01-4393-87f4-d9b35b03f934)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4f00_87dc80.json

The neighbored samples were collected in North America (US/Canada) during Mar-May 2022. So the origin is quite clear.

It shares some Spike mutations to BA.2.86 (F157S, D339H, R403K, A570V) but there are more differences. I hope that it is just one case.

Genomes:
EPI_ISL_18224410

**Comment by FedeGueli** [comment]
Closing this for now luckily
