### ISSUE TITLE
EG.5.1 with orf1b:D54N in china and canada(97 sequences)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#76]
71 china, 2 usa, 1 canada, 1 singapore
Query: G13627A, G21718T

I assume this is mostly a founder effect since there are no other eg.5.1 in china. But the speed at which it is spreading is impressive. Same for some other new branches from china, perhaps there is increased sequencing intensity lately. But this will probably become the dominant eg.5.1 branch in china so even with those biases i think its still good to keep this in mind. There are 45 with orf1b:d54n, and only 2 without in china

![Screenshot_20230520_115844_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/83e88212-24ae-4871-b5bd-ac67801367dd)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1c541_899350.json?f_userOrOld=uploaded%20sample

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1b%3A54n&nextcladePangoLineage=eg.5.1*&

**Comment by FedeGueli** [comment]
It seems to have a prevalence between 1-2% in some chinese region , something to monitor.

**Comment by BorisUitham** [comment]
1 sequence in singapore airport surveillance traveller from china

**Comment by BorisUitham** [comment]
68 now. Still most from china. @FedeGueli do you think i should move this to main page? It is growing quite quickly

**Comment by BorisUitham** [comment]
2 new ones in california making it the first usa sequences

**Comment by BorisUitham** [comment]
up to 97 now after may 25 uploads

**Comment by BorisUitham** [comment]
https://github.com/cov-lineages/pango-designation/issues/2020

**Comment by FedeGueli** [comment]
> 68 now. Still most from china. @FedeGueli do you think i should move this to main page? It is growing quite quickly

Sorry i havent seen you request while i was well aware this was growing.

As advice to everyone i think for non spike mutations they will be better tracked here, fron where i can ping @corneliusroemer when something has establishef some sort of advantage, beyond this point this surely deserves a designation if it shows same dynamics elsewhere outside China

**Comment by BorisUitham** [comment]
@FedeGueli Oops, sorry I should have waited for your reply then

**Comment by FedeGueli** [comment]
No worries at all it is already 100 seqs.
My fear is that we cant keep proposals around 50-60 in the main page they will be overlooked due time constraints. (Consider that i m not aware on any direct public/international funding keeping this thing going, if there are some the fact they are used to keep world updated is a choice/effort of the scientists on the Pango Committee)
