### ISSUE TITLE
DV.7.1 (CH.1.1.1.7.1) sublineage on the proposed #2258 branch with S:G485R (30 seqs in France and US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#760]
**Note this is a sublineage of https://github.com/cov-lineages/pango-designation/issues/2258** (_Edited)_

Defining mutations:
DV.7.1>A29558G (ORF10:M1V)>C12750T (ORF1a:A4162V)>A24373G>C7002T (ORF1a:S2246L)>G23015C (S:G485R)
GISAID query: A24373G, G23015C, A29558G
Earliest seq: 2023-07-24 (CA, US- EPI_ISL_18113968)
Most recent seq: 2023-08-28 (France- EPI_ISL_18229637)
Countries detected: France (10), US (1)

Usher Tree:
![QQ截图20230907015955](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/0c3ad797-c042-4f93-8172-e3e474aa236d)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7645_8bc340.json?c=gt-S_485

Between the two popular mutation sites 484/486, S:G485X also has relatively low but stable proportion. 
DV.7.1 rises as an "old CH* lineages" due to the flip mutations L455F-F456L. The branch with S:G485R seems growing fast in France. 

Genomes:
EPI_ISL_18113968, EPI_ISL_18215231, EPI_ISL_18215406, EPI_ISL_18221563, EPI_ISL_18221567, EPI_ISL_18228745,
EPI_ISL_18228907, EPI_ISL_18228914, EPI_ISL_18229248, EPI_ISL_18229319, EPI_ISL_18229637

**Comment by FedeGueli** [comment]
Already 6 different regions in France. Very interesting one.

**Comment by FedeGueli** [comment]
More samples from France now in 9 different regions of France.

although not able to compete with HK.3 it is very interesting and worth tracking it further.
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=A24373G%2CG23015C%2CA29558G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
ping @corneliusroemer interesting spike diversity here for DV.7.1

**Comment by FedeGueli** [comment]
5 more from France

**Comment by FedeGueli** [comment]
30

**Comment by aviczhl2** [comment]
Designated JV.1 @FedeGueli

**Comment by FedeGueli** [comment]
Designated JV.1 via https://github.com/cov-lineages/pango-designation/commit/3ab2f9cb67f8f529d6f9754e5a510c2cc7197823
