### ISSUE TITLE
HK.3 with Orf3a:L52I (see discussion on Branch18 issue #537), 150 seqs  with a sublineage of interest with S:475V (3 , Finland )

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#763]
**NEW EDITION: now this branch is placed on the HK.3 tree thx @nkrmnzr for the heads up**

tree: 
![Schermata 2023-09-07 alle 15 22 52](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/77c11772-b2a1-427b-979b-b69f7ca641fa)

![Schermata 2023-09-07 alle 15 22 03](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ea36ce00-942a-4160-a452-4440ab360987)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5fcf4_9ccf00.json?label=id:node_6947521

**Original proposal (Edited)**

Mutations on top of EG.5.1.1*: S:455F. Additionally T14988C and C25546A (Orf3a: L52I)

Gisaid for the whole branch: C25546A,T14988C,-C22264T,G22927T (**EDITED**)
Gisaid Inquiry for FLip+ S:A475V :  C22986T, C25546A  ,G22927T (**EDiTED)**

AA Query: Spike_Q52H,L455F + C25546A

Sequences: 14
earliest EPI_ISL_18166706 Finland 2023-08-11
latest EPI_ISL_18228379 FInland 2023-08-27
all: EPI_ISL_18151177, EPI_ISL_18164063, EPI_ISL_18164451,
EPI_ISL_18166655, EPI_ISL_18166671-18166674, EPI_ISL_18166706,
EPI_ISL_18209707, EPI_ISL_18210958, EPI_ISL_18224587-18224588,
EPI_ISL_18228379

USher Tree:(**EDITED**)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5fcf4_9ccf00.json?branchLabel=back-mutations&label=id:node_6947521
![Schermata 2023-09-07 alle 15 27 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b2e20b54-ac25-4def-b7ed-ddae6d3f708e)

******************************
**Trees by the author**
Whole Tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_7cab_996000.json?f_userOrOld=uploaded%20sample&label=id:node_6947533

Branch just add Spike_A475V before the search for main branch
a much too broad search that illustrated all S:A475 sequences since June
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3589d_98e340.json?f_userOrOld=uploaded%20sample&gt=S.456L

a smaller one to focus on this branch
 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3f95f_991da0.json?label=id:node_10811723

**Comment from the author:**
If #537 does contain this , then I would look for propose the branch with S:A475V instead, which I believe is not mentioned in issue #643. Yet both of them are pretty new and fast so it could be that we did not find it last week.
 I think Ryan mentioned the triple combo in issue 643 three weeks ago, not likely this one as it is submitted only 7 days earlier but I don't know.
Anyway this is interesting mutation.

**Comment by krosa1910** [comment]
Finland submitted 276 sequences since 08-11, 54 are EG.5.1 type (using S:Q52H), 10 have S:L455F, and 7 is listed here. So I have reason to suggest that it is at least locally dominant in Finland. The global spread to three other countries demonstrate its ability to travel afar, so it would be a rather major EG.5.1+S:455F lineage.

**Comment by FedeGueli** [comment]
+1 from England (new country) it seems extremely track @nkrmnzr please add to the tracklist of #537

**Comment by FedeGueli** [comment]
@angiehinrichs this lineage is on a reversion branch C22264C . likely as suggested by @nkrmnzr once resolved the reversion it will be placed as HK.3 sublineage  ( likely HK.3 is also a collector of everything with G22927T stemming out from the politomy more than one monophyletic lineage, as we saw with XBB.2.3 478R before) Could you take a look?

**Comment by krosa1910** [comment]
Large uploads from Switzerland(new country), increasing count to 24 now.

**Comment by AngieHinrichs** [comment]
The 22264 reversion is stubborn and not fixed in the 2023-09-15 tree as I had hoped (instead, it now has all of HK.3), but I hope it will be fixed in the 2023-09-16 tree tomorrow.

**Comment by krosa1910** [comment]
It went to France and Italy, increased to 30 seqs.
If it could got to a new continent this week, then I would consider proposing it in the main repo.

**Comment by FedeGueli** [comment]
> It went to France and Italy, increased to 30 seqs. If it could got to a new continent this week, then I would consider proposing it in the main repo.

I suggest to wait here

**Comment by krosa1910** [comment]
> I suggest to wait here


OK, still, detected in Australia. I would wait for your advice to decide whether post it or not.

**Comment by FedeGueli** [comment]
Thank you.

**Comment by FedeGueli** [comment]
C25546A,T14988C,-C22264T,G22927T finds 64 not sure if it has any advantage over parental lineage if any it is small.
To me there is little chance this will be designated. Decide you if keeping this open or track it privately for some more time.

**Comment by krosa1910** [comment]
> C25546A,T14988C,-C22264T,G22927T finds 64 not sure if it has any advantage over parental lineage if any it is small. To me there is little chance this will be designated. Decide you if keeping this open or track it privately for some more time.

I would check my issues and close everything that is not significantly faster than its parent.

**Comment by oobb45729** [comment]
One more with S:A475V.

**Comment by FedeGueli** [comment]
Thx @oobb45729 , @krosa1910 maybe you convert this in a direct hk.3+475V proposal

**Comment by krosa1910** [comment]
The thing grows to 150 seqs recently? About 80% of sequences are submitted these three weeks.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_24d38_a0cac0.json?f_userOrOld=uploaded%20sample
<img width="1199" alt="Screenshot 2023-10-13 at 11 39 04 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/ed2f8b9f-5569-4147-bc80-243979eeef7f">

**Comment by FedeGueli** [comment]
yes i monitoring it too.

**Comment by krosa1910** [comment]
Pretty wild, now 185 seqs on Gisaid using the edited search.
The A475V however is limited in Finland and does not seem to express international spread.

**Comment by FedeGueli** [comment]
Propose it in the main repo highlighting in the headline and in the proposal the small 475V branch

**Comment by krosa1910** [comment]
Transferred to Issue 2343 in main repo

**Comment by FedeGueli** [comment]
Designated HK.3.11 via https://github.com/cov-lineages/pango-designation/commit/738adab884bcae6fecd3cf0dce7cb7aa4a6c4a88

**Comment by FedeGueli** [comment]
HK.26.1 is the sublineage of this with S:A475V
https://github.com/cov-lineages/pango-designation/commits/master
