### ISSUE TITLE
XBB.1.5.63 or XBB.1.17.1/HK.8 Recombinant (37 seqs, 9 countries , mostly Russia)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#766]
HK.8+C344T,C346T, T2334C(rev)

The T2334C rev makes me think of recombinants.

And find a French XBB.1.5.63 branch with C344T, C346T. 

There's another XBB.1.17.1 branch with C344T, C346T, it also has 76 and 78 mutations, but 76 and 78 may be artefacts. So also possible, 

There may be other possible donors, but currently according to GISAID seqs it is only XBB.1.5.63.

XBB.1.5.63 or XBB.1.17.1--HK.8
Breakpoint between 2335 and 5719.

GISAID query: C344T,C346T,G22927T
No. of seqs: 2(1 China 1 Canada)

EPI_ISL_18166398, China, 2023-8-11
EPI_ISL_18076513, Canada, 2023-7-30

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_132ec_a83d20.json?c=gt-nuc_344,346&gmax=1346&label=id:node_6955929)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/59d95edb-3b13-4bb0-a821-69d41b1efbba)

[usher for XBB.1.5.63 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_302d6_a8efa0.json?branchLabel=nuc%20mutations&c=gt-nuc_344,346&gmax=1344)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/fcbb291d-f571-4efd-bb7f-16f83b85ca8d)

**Comment by FedeGueli** [comment]
any new sample popped up in a long time closing it for now

**Comment by aviczhl2** [comment]
+3 Russia

**Comment by aviczhl2** [comment]
Long time without seqs again. But that's due to Russia not submitting seqs since 10-21. Wait for the next Russian batch.

**Comment by FedeGueli** [comment]
Thx, when emerging from undersmpled areas lineages are kept open for a longer period!

**Comment by aviczhl2** [comment]
4 more in the recent Russian batch.

**Comment by aviczhl2** [comment]
+1 Denmark

**Comment by aviczhl2** [comment]
+2 USA,  TX/CA

**Comment by aviczhl2** [comment]
+2 Lithuania

**Comment by FedeGueli** [comment]
+1 Denmark

**Comment by aviczhl2** [comment]
+1 Sweden
+1 China from Russia

**Comment by FedeGueli** [comment]
Lets wait the next batch from Russia. If present in numbers please propose , if absent pls close it.

**Comment by aviczhl2** [comment]
+1 Greece

**Comment by FedeGueli** [comment]
Lets wait for Russia

**Comment by aviczhl2** [comment]
+1 Finland

**Comment by FedeGueli** [comment]
closing for now, please reopen if some greek or russian batch with this will be uploaded.
