### ISSUE TITLE
BA.2.86 Monitor:BA.2.86.1 with ORF1a:Y621C （A2127G）( 53 seqs）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#767]
We have found a significant growth advantage in BA.2.86.1, which is the largest of this branch with 35 sequences currently distributed in five countries.I think he has a great advantage in growth.

GISAID seach ：A2127G
**EPI_ISL ID** :EPI_ISL_18147545, EPI_ISL_18147559, EPI_ISL_18147561,
EPI_ISL_18168405, EPI_ISL_18168588, EPI_ISL_18213025,
EPI_ISL_18226750, EPI_ISL_18229665, EPI_ISL_18232952,
EPI_ISL_18237517-18237540, EPI_ISL_18237542-18237543

USHER tree
（I will replace the tree after @corneliusroemer 's tree is updated to address the issue of tree retention）
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_ba94_b24eb0.json?label=id:node_5366242
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/98f4e7f6-f059-4465-b4cd-9f1215ab2d2b)

**Comment by FedeGueli** [comment]
I would have waited a bit more in proposing this one, not sure if @corneliusroemer has willing to subdivide already the whole thing in absence of spike mutations.
But now let that open and lets wait for thoughts from Cornelius

**Comment by Memorablea** [comment]
> I would have waited a bit more in proposing this one, not sure if @corneliusroemer has willing to subdivide already the whole thing in absence of spike mutations. But now let that open and lets wait for thoughts from Cornelius

I saw him growing and accounting for a quarter, so he transferred. So let's reopen it and use it as surveillance here

**Comment by Memorablea** [comment]
45

**Comment by Memorablea** [comment]
53

**Comment by Memorablea** [comment]
57

**Comment by Memorablea** [comment]
78

**Comment by FedeGueli** [comment]
Designated JN.2 via https://github.com/cov-lineages/pango-designation/commit/62ee71fda492d8305882f8a8611804094501d7f2
