### ISSUE TITLE
GS.4 sublineage with S:Q218H, 46 samples 6 countries (40 on Usher) ( with a further sublineage defined by S:R190S convergent with GS.3) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#768]
Tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_327b0_b06720.json?c=country&label=id:node_7400995
![Schermata 2023-09-08 alle 17 20 21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ecbf105e-449c-4d78-a47d-47ebec7ed0e1)

![Schermata 2023-09-08 alle 17 19 54](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4d5c11b4-3c8e-4d0b-8929-b47abadc2ee3)

Defining mutations:
**GS.4 (before Orf1a:A181T)  >> Orf1a:T1822I (C5730T) ,T7549C, S:Q218H (G22216T)**

Note that Orf1a:T1822I is a known marker for chronically infected patient ( cc @ryhisner) it corresponds to NSP3_T1004I = PLPro_T259I .

Gisaid query: T7549C, G22216T  ,C5730T

Samples 29:
EPI_ISL_18109722, EPI_ISL_18123357-18123360, EPI_ISL_18123763,
EPI_ISL_18127692, EPI_ISL_18130718, EPI_ISL_18142486,
EPI_ISL_18147725, EPI_ISL_18147734, EPI_ISL_18147746,
EPI_ISL_18158418, EPI_ISL_18158969, EPI_ISL_18159097,
EPI_ISL_18215849-18215850, EPI_ISL_18215853-18215854, EPI_ISL_18215860-18215863,
EPI_ISL_18215870, EPI_ISL_18215874, EPI_ISL_18220196-18220197,
EPI_ISL_18220203, EPI_ISL_18221583

Countries: France, Belgium , England, Sweden, Norway, Denmark.
Interestingly the shape of the tree makes me think everywhere it landed it gave birth to cluster of relvant dimension.
Not sure if this could point to increased severity aka overrepresentation in Hospitalized which are the most of the samples sequenced or what else

**Comment by FedeGueli** [comment]
ping @corneliusroemer

**Comment by ryhisner** [comment]
M:A104V is also found in BA.2.86 and, like ORF1a:T1822I, shows up from time to time in chronic-infection sequences as well.
