### ISSUE TITLE
JC.5 sublineage with S:Y421F and S:Q779K (2 seqs in France)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#769]
Defining mutations:
JC.5 [= XBB.1.41.1>C364T>C3924T (ORF1a:P1220L), C18555T>C29171T (N:H300Y)]>A2480G (ORF1a:I769V)>T10414C, A22824T (S:Y421F), C23897A (S:Q779K), C29769T
GISAID query: T10414C, A22824T, C23897A
Earliest seq: 2023-08-28 (France- EPI_ISL_18237364)
Most recent seq: 2023-08-28 (France- EPI_ISL_18237365)
Countries detected: France (2)

Usher Tree:
![QQ截图20230909002620](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/e04f0101-bfb3-46ad-af4f-4ace134ca93e)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_106a3_adbb00.json?c=gt-S_421

XBB.1.41.1 (mainly with S:L335S, S:R403K and S:K478R) has circulated in Europe for several months. S:Y421F is a very rare mutation which only less than 150 valid samples, mainly once in AY.25.1 lineage. 

Genomes:
EPI_ISL_18237364-18237365

**Comment by FedeGueli** [comment]
Parental is now JC.5 i ve edited proposal and headline consequently

**Comment by FedeGueli** [comment]
I dont think it is still circulating
