### ISSUE TITLE
XBB.1.16 ( Pango #1920 sublineage)  with ORF9b:T5A and ORF9b:T24S (13 seqs, Canada-QC)

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#77]
This cluster obtained 2 ORF9b changes in a stepwise manner, including a 2-nuc mutation that further changed ORF9b:5T into ORF9b:5A.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/22ba9566-1b85-4ff1-88b4-0980ea41ddab)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bb1b_8c4a30.json?c=userOrOld&label=id:node_8419324

**changes on top of XBB.1.16**: **A28353T (N:27I / ORF9b:T24S)** > C13548T > **A27142G (M:N207S)** > T26418C > **G3485A (ORF1a:A1074T)** > G12355A, C14184T, **G20491T (ORF1b:V2342L)**, **A28296G (N:N8S / ORF9b:T5A)**

**Query**: G12355A, C14184T, G20491T, A28296G

**Genomes**: EPI_ISL_17611679, EPI_ISL_17641177, EPI_ISL_17641668, EPI_ISL_17641734-17641735, EPI_ISL_17641803, EPI_ISL_17641810-17641811, EPI_ISL_17687659, EPI_ISL_17687689, EPI_ISL_17687696, EPI_ISL_17688223-17688224

**Comment by FedeGueli** [comment]
It has a change on the key extra spike residue at this moment. @c19850727 propose it if it reaches 20.

**Comment by FedeGueli** [comment]
This has gone stale so likely T>A at Orf9b:5  wasnt beneficial!
