### ISSUE TITLE
EG.5.2 sublineage with S:K679R (sibling of EG.5.2.1, 26 seqs, 13 countries) and its 2 recombinants with XBB.1.9* (14 seq, 4 countries / 21 seq, 6 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#770]
Credit to @NkRMnZr

## EG.5.2+S:K679R
EG.5.2> A6729G(Orf1a:N2155S)> C11518T> C3602T(Orf1a:H1113Y)> A25744G(Orf3a:I118V, shared with EG.5.2.1)> A23598G(S:K679R)
Query: A6729G, A23598G
Earliest sequence: 05-12 Noord Holland, Netherlands EPI_ISL_17787266
Latest sequence: 09-23 Basque, Spain EPI_ISL_18366383
Regions detected: Spain 6(Catalunya 2, Balearic Islands 1, Basque 1, Canary Islands 1, Castilla y León 1), UK 4(Scotland 3, England 1), Belgium 2(Londerzeel 1, Gingeleon 1), Austria 1(Wien), Denmark 1, Luxembourg 1, Netherlands 1(Noord Holland), Portugal 1, Sweden 1(Kalmar);
Israel 2, South Korea 2, Georgia 1(Tbilisi);
Peru 3(Lima)

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20424_7b8a0.json
![2023-09-28 (10)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/dead2ce5-4c4e-46d4-ba6e-ab3f1ca80f50)

And its C583T, T16905C branch (3 seq, 3 countries) recombines with two different XBB.1.9* donors and forms two different recombinants.

Sequences:
EPI_ISL_17787266, EPI_ISL_17827046, EPI_ISL_17960339,
EPI_ISL_18042094, EPI_ISL_18052049, EPI_ISL_18052445,
EPI_ISL_18096783, EPI_ISL_18134870, EPI_ISL_18147777,
EPI_ISL_18167899, EPI_ISL_18168067, EPI_ISL_18209149,
EPI_ISL_18214053, EPI_ISL_18226771, EPI_ISL_18273765,
EPI_ISL_18286676, EPI_ISL_18293080, EPI_ISL_18322861,
EPI_ISL_18337011, EPI_ISL_18337025, EPI_ISL_18366383,
EPI_ISL_18370626, EPI_ISL_18370924, EPI_ISL_18379250,
EPI_ISL_18385349, EPI_ISL_18414631

## Recombinant 1:
XBB.1.9* / EG.5.2 / XBB.1.9*
Query: 4060, 4086, C11518T or C11518T, G27390C or A23598G, G27390C

Earliest sequence: 07-24 Iceland EPI_ISL_18094123
Latest sequence: 08-28 California, US EPI_ISL_18267315
Regions detected: US 10(California), Iceland 2, France 1(Nouvelle-Aquitaine), UK 1(England)

Breakpoint 1: 6729\~9693
Breakpoint 2: 28754\~29625
EG.5.2> *A6729G*> C11518T> *C3602T*> A25744G(Orf3a:I118V, shared with EG.5.2.1)> A23598G(S:K679R)> *C583T*, T16905C> A79G, *T583Crev*, T2334Crev(Orf1a:V690Arev), *T3602Crev*, A4060C, T4086C(Orf1a:I1274T), C5152Trev, *G6729Arev*, G27390C, T29625Crev(Orf10:F23Srev)

Since it has G5720A and G6729Arev, the other one donor should be an XBB.1.9*.
Any 2 of A79G, A4060C, T4086C, G27390C gives no sequence except this recombinant.
A79G, G5720A, -16905 gives no sequence.
A4060C, G5720A, -16905 gives 1 sequence, a French FL.8 with several mutations between 5' to 5720, and its 405 is reversed.
T4086C, G5720A, -16905 gives 3 sequences, 1 is an Indian low-quality sequence, and 2 are American FL.4> A28615G> A6646G> T4086C.
G27390C, G5720A, -16905 gives 23 sequences, but most of they are too messy, and 27390 is on the upstream of 28754, it seems impossible to inherit 27390 from the XBB.1.9* donor.
And this recombinant is also possible to be more complex and twisted? But in this case, the non-EG.5.2 donor could be from the other strains.

Sequences:
EPI_ISL_18094123, EPI_ISL_18094138, EPI_ISL_18118869,
EPI_ISL_18121231, EPI_ISL_18121255, EPI_ISL_18144691,
EPI_ISL_18215145, EPI_ISL_18222944, EPI_ISL_18267315,
EPI_ISL_18267640, EPI_ISL_18270057, EPI_ISL_18270377,
EPI_ISL_18317736, EPI_ISL_18347338

## Recombinant 2:
XBB.1.9.1 / EG.5.2
Query: T4690C, A23598G

Earliest sequence: 08-21 Denmark EPI_ISL_18210614
Latest sequence: 09-29 New York, US EPI_ISL_18394164
Regions detected:  Italy 8(Sicily 4, Apulia 3, Veneto 1), US 8(NY 4, California 2, Minnesota 2),Canada 2(BC 1, Ontario 1), Denmark 1, France 1(ARA), Greece 1(Central Greece)

Breakpoint: 6729\~9693
EG.5.2> *A6729G*> C11518T> *C3602T*> A25744G(Orf3a:I118V, shared with EG.5.2.1)> A23598G(S:K679R)> *C583T*, T16905C> **C547T**, *T583Crev*, C1758T(Orf1a:A498V, Private), T2334Crev(Orf1a:V690Arev), *T3602Crev*, **T4579A**, **T4690C**, **T4930C**, C5152Trev, *G6729Arev*
The donor should be from XBB.1.9.1> C29614T> **C547T**> T15309C> **T4690C**, **T4930C**, G10540T, C26054T branch. (2 seq, and 1 seq has further **T4579A**.)

Sequences: 
EPI_ISL_18210080, EPI_ISL_18210109, EPI_ISL_18210181,
EPI_ISL_18210614, EPI_ISL_18218428, EPI_ISL_18300257,
EPI_ISL_18314673, EPI_ISL_18330426, EPI_ISL_18344025,
EPI_ISL_18357726, EPI_ISL_18363919, EPI_ISL_18364276,
EPI_ISL_18368928, EPI_ISL_18389364, EPI_ISL_18394164,
EPI_ISL_18404126, EPI_ISL_18419443, EPI_ISL_18419447,
EPI_ISL_18419462, EPI_ISL_18419489, EPI_ISL_18422941

**Comment by FedeGueli** [comment]
is it the EG.5.2 + 679R sonor proposed yet?

**Comment by Over-There-Is** [comment]
> is it the EG.5.2 + 679R sonor proposed yet?

not proposed yet.

**Comment by FedeGueli** [comment]
I suggest to propose it  having recombined two times means it has some ability in coinfect (679R)  or prevalence somewhere

**Comment by FedeGueli** [comment]
Query for it : A23598G,A25744G,  -A4060C , -C547T 
 
Defining : 
EG.5.2 (S:F456L) > ORF1a:N2155S (A6729G) > C11518T > ORF1a:H1113Y (C3602T) >Orf3a:I118V (A25744G) > S:N>K679R (A23598G)

17 samples
EPI_ISL_10729647, EPI_ISL_17787266, EPI_ISL_17827046,
EPI_ISL_17960339, EPI_ISL_18042094, EPI_ISL_18052049,
EPI_ISL_18052445, EPI_ISL_18094138, EPI_ISL_18096783,
EPI_ISL_18121255, EPI_ISL_18134870, EPI_ISL_18147777,
EPI_ISL_18167899, EPI_ISL_18168067, EPI_ISL_18209149,
EPI_ISL_18214053, EPI_ISL_18226771


 
 


--

**Comment by Over-There-Is** [comment]
> A23598G(S:K679R)> _C583T_, T16905C

Two sequences of recombinant 1 have M on 4060, so -G27390C would be better.

**Comment by FedeGueli** [comment]
+4 lineage 1

**Comment by Over-There-Is** [comment]
Sorry for forgetting tracking this issue.

**Comment by Over-There-Is** [comment]
Lineage 2 also has a new sequence.

**Comment by Over-There-Is** [comment]
Common query for the EG.5.2 donor and both recombinant: `C11518T, T16905C, A23598G`

**Comment by Over-There-Is** [comment]
2 of recombinant 1 have P445S. Artefact?

**Comment by FedeGueli** [comment]
Only Recombinant 2 is fast the other two very slow.

**Comment by Over-There-Is** [comment]
Branch 2 is also in France now.

**Comment by FedeGueli** [comment]
Please propose branch 2 it seems fast
![Schermata 2023-10-23 alle 23 18 43](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/eddef56d-ad10-4376-8b26-8d74635df064)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1f872_6e1f90.json?label=id:node_3421384
![Schermata 2023-10-23 alle 23 21 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/25238b98-4b23-4d82-9970-870e3c88bc72)

**Comment by FedeGueli** [comment]
And then close this one.

**Comment by Over-There-Is** [comment]
EG.5.2.4 & XDG

**Comment by FedeGueli** [comment]
Designated EG.5.2.4 donor 
EG.5.2.4 è FL.37 >> XDG

via https://github.com/cov-lineages/pango-designation/commit/d7b0265b8f5d95db0be543300f7402653c1d7b09
