### ISSUE TITLE
EG.5.1/JD.1.1 recombinant( 9 seqs, 4 countries) 

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#772]
JD.1.1+
C2334T, C3622T, G5720A, T6896C(rev),C9693T, A11537G, C12789T,  T14085C(rev), T14189C(rev),C19185T

C2334T, G5720A,C9693T,,C12789T are from EG.5.1

Orf1a: A690V, G1819S, A3143V, I3758V, T4175I
Orf1b: V241A(rev)

C3622T,A11537G(Orf1a:I3758V) are from an European EG.5.1 branch. 

C19185T is JD.1.1 branch specific.

EG.5.1--JD.1.1
Breakpoint between 14190 and 14633

GISAID query: C3622T,A11537G,C19185T
No. of seqs: 3(France 2 Denmark 1)

EPI_ISL_18210617,Denmark, 2023-8-21
EPI_ISL_18237406,18239722, France, 2023-8-28

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_19eb6_bef6f0.json?label=id:node_10820329)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/fcb8ca09-de80-4cf5-bf2f-bb88deabdc8a)

[usher for EG.5.1-side donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice10_genome_19eb6_bef700.json?gt=nuc.3622T&label=id:node_6948762)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e6e9da9d-e49c-491a-b813-de1305151bad)

**Edited** from the EG.5.1 donor ie gets a NSP6 mutation: **Orf1a:I3758V** = NSP6_I189V
EDITED: Rapid picture of this recombinant:
![Schermata 2023-09-10 alle 07 29 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ee7cc221-f011-4a60-8584-634d06ba3cf4)

**Comment by FedeGueli** [comment]
Please add AA changes.

**Comment by FedeGueli** [comment]
This has S:A475V too.

**Comment by aviczhl2** [comment]
> This has S:A475V too.

Yeah, this is JD.1.1 spike.

**Comment by FedeGueli** [comment]
no new samples piling on

**Comment by aviczhl2** [comment]
+1 UK-CLIMB seq

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by LilKitt** [comment]
I was unsure of this sequence, until the new ones were uploaded. Seems very fit.

**Comment by FedeGueli** [comment]
This grew to 19 maybe worth a designation too cc @corneliusroemer

**Comment by FedeGueli** [comment]
@aviczhl2 please propose when it reaches 25

**Comment by FedeGueli** [comment]
scratch that already designated better sleeping too much new things today!

**Comment by FedeGueli** [comment]
XCP
