### ISSUE TITLE
EG.5.1 with S:S98F, S:Q146K, S:F157L, ORF3a:L53F, ORF1b:P2256S (12 countries, 95 seq, Nov 29)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#774]
**Description**
**Sub-lineage of:** EG.5.1
**Earliest sequence:** 2023-7-31, USA, New York — EPI_ISL_18121316
**Most recent sequence:** 2023-8-30, England — EPI_ISL_18227352
**Countries circulating:** England (5), USA-Hawaii (3), Portugal (2), USA-New York (1), France (1), Northern Ireland (1)
**Number of Sequences:** 13 (Three not on GISAID as of 2023-9-9)
**GISAID AA Query:** Spike_S98F, Spike_F157L, Spike_F456L
**GISAID Nucleotide Query:** C25549T, C20233T, A18492G
**CovSpectrum Query:** Nextcladepangolineage: EG.5.1* & [4-of: T8234C, C8650T, C21998A, C20233T, C21855T, C22033A, C25549T]
**Substitutions on top of EG.5.1:**
**Spike:** S98F, Q146K, F157L
**ORF1b:** P2256
**Nucleotide:** T8234C, C8650T, C21998A, C20233T, C21855T, C22033A, C25549T
 
**Phylogenetic Order of Mutations:** T8234C, C8650T  **→→**  C25549T (ORF3a:L53F)  **→→**  C20233T, C21855T, C21998A, C22033A (S:S98F, S:Q146K, S:F157L, ORF1b:P2256S)  

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.5.1_S98F_Q146K_F157L.json?c=gt-nuc_20233&gmax=21233&gmin=19233&label=id:node_6947965
<img width="1409" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/82bd360f-cc8a-40bf-a208-a748083524b5">

**Notes**
The five most recent mutations in this lineage are all non-synonymous, suggesting some positive selection is at work. Geographic spread, stretching from Hawaii to New York to Portugal, France, England, and Northern Ireland is fairly impressive.
 
Probably destined to die out soon if it doesn't add L455F, so likely not even worth proposing, but I'm tired and needed something mindless to do this morning.
 
 
**Genomes**
**Not yet on GISAID:**
Northern_Ireland/CLIMB-CM7YEA7R/2023|OY727084.1|2023-08-06 (Has S:N481Y)
England/CLIMB-CM7YRSYW/2023|2023-08-29
England/CLIMB-CM7YFOND/2023|2023-08-29
 
<details>
<summary>Genomes</summary>
EPI_ISL_18121316, EPI_ISL_18130033, EPI_ISL_18141939, EPI_ISL_18142258, EPI_ISL_18227352, EPI_ISL_18227433, EPI_ISL_18227443, EPI_ISL_18237450, EPI_ISL_18241265, EPI_ISL_18241343
</details>

**Comment by FedeGueli** [comment]
it looks fast.

**Comment by FedeGueli** [comment]
It is fast please propose it-

**Comment by FedeGueli** [comment]
It seems able to compete with fastest flip. please propose it : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C25549T%2CC20233T%2CA18492G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
it is still faster than most of EG.5.1 without Flip

**Comment by FedeGueli** [comment]
Only few samples from November closing it
