### ISSUE TITLE
FL.1.5.1 with ORF3a:A99V - 121 seqs (73 on Gisaid) in 11 countries 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#775]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/e182985a-9a94-4aae-8d35-13b276c4c92d)
Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26d47_cc0ff0.json?label=id:node_6999315
First Seq: 2023-07-25
Most Recent: 2023-09-04
Gisaid Query: C25688T, G20060T, C22995G (Edited @Fearuncle remember to use the WT nucleotide as start)
England/CLIMB-CM7YR5KM/2023 England/CLIMB-CM7YJBGI/2023 England/CLIMB-CM7YFFN7/2023 England/CLIMB-CM7YK6F8/2023 England/CLIMB-CM7YJNWA/2023 England/CLIMB-CM7YRZMU/2023 England/CLIMB-CM7YJJK4/2023 EPI_ISL_18135373 EPI_ISL_18161108 Scotland/CLIMB-CM7YM8T7/2023 Scotland/CLIMB-CM7YKK6U/2023 Wales/CLIMB-CM7YER9A/2023 EPI_ISL_18220540 Wales/CLIMB-CM7YGHKX/2023 OY726222.1 Wales/CLIMB-CM7YRA3J/2023 England/CLIMB-CM7YEP88/2023 OY725026.1 OY723468.1 England/CLIMB-CM7YMSFM/2023 England/CLIMB-CM7YENWY/2023 EPI_ISL_18228777 EPI_ISL_18228779 EPI_ISL_18228780 EPI_ISL_18228781 EPI_ISL_18228778 England/CLIMB-CM7YMTCU/2023 England/CLIMB-CM7YM18J/2023 England/CLIMB-CM7YFGDJ/2023 EPI_ISL_18105829 Scotland/CLIMB-CM7YMDKM/2023 Scotland/CLIMB-CM7YJ5OB/2023 England/CLIMB-CM7YK88W/2023 Scotland/CLIMB-CM7YRMOW/2023 EPI_ISL_18168643 EPI_ISL_18168637 England/CLIMB-CM7YMP3A/2023 EPI_ISL_18134865 England/CLIMB-CM7YKRWE/2023 EPI_ISL_18130877 EPI_ISL_18229520 EPI_ISL_18228975 England/CLIMB-CM7YJYHK/2023 OY724165.1 EPI_ISL_18229521

**Comment by FedeGueli** [comment]
it could have some advantage on its parental lineage.: https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?nextcladePangoLineage=FL.1.5.1*&nucMutations1=C25688T%2CG20060T%2CA22995G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
50 on Gisaid and counting them alone it is doubling in 9 days way faster than parental lineage ping @corneliusroemer 
in fact its disadvantage vs HK.3 is not that clear:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C25688T%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
on gisaid there are 73

**Comment by FedeGueli** [comment]
it is a fast one: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C25688T%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Propose it even if i m not sure Cornelius this kind of lineage.
its growth advantage over parental seem real even if the lowest CI has the same growth advantage,
this usually points toward that there is something else at work not intrinsic advantage
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=FL.1.5.1*&nucMutations1=C25688T%2CG20060T%2CC22995G&analysisMode=CompareToBaseline&
