### ISSUE TITLE
GL.1+S:Y144- sublineage with S:T307I (16+2? seq. Portugal, USA, UK)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#776]
Defining mutations: GL.1 then S:Y144- then nuc:C5239T then nuc:T4114G then S:T307I(C22482T)
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/465b49fc-38dd-4f1f-b212-6133791e7293)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2338d_cd9620.json?c=gt-S_307&gmax=25384&gmin=21563&label=id:node_6405171
Portugal/PT48929/2023|EPI_ISL_18052436|2023-07-07 lacks coverage at S:307 so it likely has S:T307I too and the two branches likely belong to the same lineage.

Possible query: C22482T, T4114G,C5239T finds 10 one from Uk too.

**Comment by oobb45729** [comment]
This is the second time that an XAY lineage gained S:T307I. The first time is on an XAY.1.1.1+ORF1a:P1640S subbranch with S:T307I and ORF3a:P240S, which probably is the most interesting subbranch of XAY.1.1.1+ORF1a:P1640S. There are sequences with S:D420N, S:T430I, or S:N460K on that branch
https://open.cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1%26S%3AT307I&

**Comment by FedeGueli** [comment]
![Schermata 2023-09-09 alle 23 26 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3c84c3a1-e80f-440e-80af-7878f6d81128)
@angiehinrichs this tree seems split in two artefactually! GL.1 + S:T307I

**Comment by FedeGueli** [comment]
> This is the second time that an XAY lineage gained S:T307I. The first time is on an XAY.1.1.1+ORF1a:P1640S subbranch with S:T307I and ORF3a:P240S, which probably is the most interesting subbranch of XAY.1.1.1+ORF1a:P1640S. There are sequences with S:D420N, S:T430I, or S:N460K on that branch https://open.cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXAY.1.1.1%26S%3AT307I&

That branch with Orf1a:P1640S is now GL.3

**Comment by FedeGueli** [comment]
It seems too slow to be worth tracking it publicly.
