### ISSUE TITLE
EG.5.1.1/XBB.1.16.6 Recombinant (US, Spain, England, 15 seq, Oct 20)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#777]
### **Description**
**Recombinant of:**  EG.5.1.1 / XBB.1.16.6
**Breakpoint:** 14856-16878 (Before 14856 = EG.5.1.1, After 16878 = XBB.1.16.6)
**Earliest sequence:** 2023-8-17, Spain, Basque Country — EPI_ISL_18241651
**Most recent sequence:** 2023-8-29, England — EPI_ISL_18237603
**Countries circulating:** England (4), Spain (1)
**Number of Sequences:** 5
**GISAID Nucleotide Query:** C1875T, T17454A
**CovSpectrum Query:** [2-of: G393A, C1875T, T17454A]
**(possible) Private Substitutions:**
**ORF1a:** R43H, A537V
**Nucleotide:** G393A, C1875T, T17454A

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.16.6_EG.5.1.1_Recomb.json?c=gt-nuc_17454&gmax=18454&gmin=16454&label=id:node_6821120 
<img width="1423" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c8ad413c-e3b5-432a-ad6f-b444a001d5cc">

 
**Notes**
None for now.
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18227047, EPI_ISL_18227118, EPI_ISL_18227645,
EPI_ISL_18237603, EPI_ISL_18241651
</details>

**Comment by FedeGueli** [comment]
10 now sampled in California too.

**Comment by FedeGueli** [comment]
it seems slowing down

**Comment by aviczhl2** [comment]
23 now
