### ISSUE TITLE
Divergent AY.25.1.2 - Possible Single-Patient Chronic Infection (Trinidad & Tobago, 2 seq, Sept 9)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#778]
Two recently collected AY.25.1.2 sequences from Trinidad & Tobago, both with lots of missing coverage. The first sequence has no metadata, so it is not possible to know for certain if both sequences come from the same patient or not. There is one aspect of these sequences that suggests they could be from different patients: the first sequence has a 31-nucleotide deletion in ORF8, but the second sequence only has the usual Delta six-nucleotide deletion (ORF8:∆119-120). 

Deletions don't disappear like that in normal lineages. However, if this is a chronic patient, they could have multiple coexisting intrahost variants, some with the larger ORF8 deletion and some without it, and in that case, it's perfectly possible for a deletion to disappear due to being outcompeted by an intrahost variant that lacks the deletion. It's also possible the deletion in the first sequence was an artifact, though there's nothing in particular to suggest that it is. 

The missing coverage is more extensive than what's indicated. For example, sequence two has missing coverage indicated for 631-676, yet it has clearly artifactual reversions at S:614 and S:681, so the true missing coverage extends well beyond the bounds that are described.

If you combine the coverage from the two sequences, you can get a fuller picture of this branch. For example, sequence two lacks coverage at S:45-111—likely a wider interval in reality—so in all likelihood it has the same mutations sequence 1 had in this region, i.e. S:P26S, S:H66Y, and S:A67G.

Short summaries of both sequences below.

**Usher Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/AY.25.1.2__Trinidad_Tobago__2_seq.json?c=gt-S_453&gmax=25384&gmin=21563&label=id:node_1284201
<img width="1508" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/85887524-2ec0-4129-b652-097ccd4ad6d8">

### **Sequence 1**
**Collection Date**: 2023-7-17, Trinidad & Tobago — 
**GISAID ID**: EPI_ISL_18116176 
**Private Mutations**
<img width="1503" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9223c944-eca3-493f-9fb1-2aaa0cc0d2a7">

**Missing Coverage and Unknown AAs**
<img width="1499" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/004c641b-de31-49e5-8c88-ddc184b17a54">

### **Sequence 2**
**Collection Date**: 2023-8-1
**GISAID ID**: EPI_ISL_18241719 
**Private Mutations** 
<img width="1504" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/43a0d1bb-1084-42b5-9123-175e94c8f7c1">

**Missing Coverage and Unknown AAs**
<img width="1466" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/475b1b7f-6fd7-48bf-9124-d61826a833b7">

Potential query: A14771G,C27945T (**EDITED**)

**Comment by HynnSpylor** [comment]
Yeah I also notice it.
A strange thing is seq 1 missed lots of "key mutations" shown in seq 2 (including K356, K378, P499, Y508 S704 etc.)

![QQ截图20230910095723](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/6605b00c-783a-4f39-860c-c24933703ad8)

**Comment by krosa1910** [comment]
It reminded me about the AY.25 I discovered in Michigan this Spring when searching for S:L455F+F456L, now commonly known as the flip. It got S:P499R.
499 seem to be a certain popular spot in cryptic Deltas, although the commoner form is 499R, but 499L appeared more in other lineages, so possibly it is fitter?
<img width="1437" alt="Screenshot 2023-09-09 at 11 18 40 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/106a9137-3cf4-4817-9411-632b3be6829b">
<img width="1091" alt="Screenshot 2023-09-09 at 11 20 48 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/352bf71a-e6b1-4a9a-9f5e-707ff21566b6">

**Comment by FedeGueli** [comment]
No new sample came luckily closing it
