### ISSUE TITLE
XBB.1.5.102+14-nuc,5-aa including S:E554K,N450D,F456L(2 seqs,Spain)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#779]
XBB.1.5.102+G4255A+C20629T(Orf1b:H2388Y)+G1820A(Orf1a:G519S)+C27513T+C14178T,T22510C,G23222A(S:E554K)+T15717G,C12484T, G25297A, C26882T+A22910G, T22928C, C29095T(S:N450D,F456L)

GISAID query: A22910G, T22928C, C29095T
No. of seqs: 2(Spain)

EPI_ISL_18112409, 2023-8-14
EPI_ISL_18147173, 2023-8-22

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_24b95_d33460.json?branchLabel=Spike%20mutations&label=id:node_7219688&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e018b18b-c74d-47cc-93e4-5855438c8685)

**Comment by FedeGueli** [comment]
no new seq i suspect it is slow.
