### ISSUE TITLE
Weird Singlet of BA.4.6? that got Flip

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#780]
Singlet ID: EPI_ISL_18129944, Switzerland 2023-08-08
Analysis of it
<img width="1091" alt="Screenshot 2023-09-10 at 1 03 59 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/0cfc3e9e-bf60-4ebb-80c9-e6d84bb6ac6e">
I found this when searching a Flip search that I tried to remove the largest ones (EG, GK, JD and DV).
Its mutations are just similar to common cryptics. S:346T and S:493Q rev are the commonest, yet the others are less common weirder. I think BA.2.83 may have some similarity to it (S:27S, S:G252D, S:V1264L etc.) But in general it is just weird.

**Comment by krosa1910** [comment]
My fault it seemed that it is a doublet instead of a singlet. (My time filter just ignoring the older one)
The earlier sequence is EPI_ISL_17831941 Swiss 2023-06-08, so 2 months earlier, and while two sequences have similarity, they also differ in a lot of places. Since the latter one has more mutations, I do incline to believe it is a single chronically infected patient

<img width="1671" alt="Screenshot 2023-09-10 at 1 12 10 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/5779ed2f-faf9-4167-b312-4c64f71e04ba">

**Comment by FedeGueli** [comment]
duplicate #703

**Comment by FedeGueli** [comment]
@krosa1910 see #703
