### ISSUE TITLE
XBB.2.3 is finally getting "flip" (2 US singlet of XBB.2.3+flip)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#782]
Search Intended for this collection by author: Spike_L455F,F456L under G6536A,C23123T
Singlet 1: EPI_ISL_18222150 US-NJ 2023-08-21
This one is weird because it is placed under a very long, but largely syn mutation branch with A1230G, T9931C, T11656C, C17010T, T21728C, C22210T, C26124T. It is understandable that C-T transition is very common, yet still strange to me.
The branch could be searched with  A1230G,T9931C,C17010T on Gisaid.
Inquiry for the singlet (if it develops): A1230G,T9931C,C17010T,G22927T
It is classified as XBB.2.3.11 descendent( GS.4),  I won't question this, yet XBB.2.3.11 looks to me as a rubbish bin of all XBB.2.3+S:K478R that is not classified otherwise, and this sequence does not have S:K478R (or have it reversed, or have bad sequencing quality)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_256a5_d55b40.json?label=id:node_7411817
![Schermata 2023-09-10 alle 08 39 03](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f1b01c32-2bb3-48b7-a99f-34b4d4578830)
Tree to show its relations and mutations of single 1

*******************************

Singlet 2: EPI_ISL_18225087 US-AZ 2023-08-24
It is classified as XBB.2.3.2, being placed on G23417A/S:E619K branch 
the branch could go by inquiry: G23417A,G6536A,C7162T
similarly inquiry for the singlet: G23417A,G6536A,C7162T,G22927T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a5b2_d640f0.json?c=userOrOld&label=id:node_7393193
![Schermata 2023-09-10 alle 08 38 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f183bf58-c0d2-496f-883f-a8ac8fab1559)
Tree to show its relations and mutations of singlet 2 ( **it has also S:E619K - EIDTED**)

Yes, that is what it is, it is less a formal issue, more as something I noted special about XBB.2.3*
As @ryhisner have spotted, XBB.2.3* seemed to pick a distinct route of evolution. Yet at the same time, Flip is some mutation that not only appeared in the fastest XBB clans, but also somewhere else such as DV.7.1, or some other individual saltations. So I wanted to see if Flip could grow in XBB.2.3*.

**Comment by FedeGueli** [comment]
Singlet 1 is a GBW second sample (H20) it pairs with the other ust below in the tree which has not 455-456 and has 478
hCoV-19/USA/NJ-GBW-H10-016-3783/2023 EPI_ISL_18147045. 
So it could be contamination to me.

**Comment by FedeGueli** [comment]
> Yes, that is what it is, it is less a formal issue, more as something I noted special about XBB.2.3*
> As @ryhisner have spotted, XBB.2.3* seemed to pick a distinct route of evolution. Yet at the same time, Flip is some mutation that not only appeared in the fastest XBB clans, but also somewhere else such as DV.7.1, or some other individual saltations. So I wanted to see if Flip could grow in XBB.2.3*.

No worry everyone choose her/his style , one thing i m reushering SINGLET 2 cause you have put the same tree of SINGLET 1

**Comment by FedeGueli** [comment]
they remained singlets apparently.

**Comment by krosa1910** [comment]
This is very slow, I guess that XBB.2.3* is not that compatible with FLip.
