### ISSUE TITLE
Potential XBB.1.16.2 and FL.1.6 Recombinant (3 seqs, South Korea)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#783]
**Defining Mutations:** **XBB.1.16.2** > _G9190C (GY.5)_ > `T2575A, C7124T(ORF1a:P2287S)` > `C6445T, G6618T(ORF1a:G2118V)` > `A27853T(ORF7a:E33V)` > _G22995A_reversion(S:R478K_reversion)_ > `G2095A, C3634T`, _C9190G_reversion_, `C10714T`, _G14856A_reversion_, `G18538T(ORF1b:V1691L)`, _T18703G_reversion(ORF1b:Y1746D_reversion)_, `C19834T(ORF1b:L2123F)`, _T22101A_reversion(S:V180E_reversion)_, `T23005A(S:N481K), C23664T(S:A701V)`

**Recombinant Profile:**
- **Donor A**: Despite the lineage is located under a **GY.5 (XBB.1.16.2.5)** branch, it has **GY.5** defining `G9190C` reversed, considering that would add even more breakpoints for a sandwich recombinant, it's safe to say the donor is **XBB.1.16.2**, upstream from 5' to 1st breakpoint; downstream from 2nd breakpoint to 3' end.
- **Donor B**: **FL.1.6 (XBB.1.9.1.1.6)**, and more specific, `FL.1.6` > `G18538T(ORF1b:V1691L)` > `C5822T(ORF1a:L1853F), C19834T(ORF1b:L2123F)`, closely related to `South_Korea/KDCA235236/2023|EPI_ISL_17690534|2023-04-25`, between two breakpoints.

<details><summary>potential Donor B</summary>

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_27ec1_d8abe0.json?c=gt-nuc_18538,19834&gmax=20834&gmin=17538&label=id:node_6999268
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5954aedc-7151-494c-9a16-7724ef979ef1)
</details>

- **1st Breakpoint**: between `nuc 12970/ORF1a_4235` to `nuc 14856/ORF1b_463`
- **2nd Breakpoint**: between `nuc 23664/spike_701` to `nuc 25186/spike_1208`

**Query:** `C19834T, T23005A, A27853T`
**Earliest seq:** 2023-07-21 (`EPI_ISL_18111674`, South Korea)
**Latest seq:** 2023-08-15 (`EPI_ISL_18236820`, South Korea)
**Sampled Countries:** South Korea (3)

<details><summary>Genomes: </summary>

`EPI_ISL_18111674, EPI_ISL_18213925, EPI_ISL_18236820`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27ec1_d8abe0.json?f_userOrOld=uploaded%20sample&label=id:node_6871748
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/afe4e9ff-9a89-4308-9259-1880ab42d2c9)

**Comment by FedeGueli** [comment]
![Schermata 2023-09-12 alle 00 27 05](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/adf722e5-b47a-400d-bf43-9636bc725907)
 it does like this way

**Comment by FedeGueli** [comment]
quite old samples likely slow
