### ISSUE TITLE
GE.1 with 6 aa mutations (24) in 8 USA states 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#785]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a122d155-a1d2-4716-8a1e-b21b02712bab)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3258e_dff860.json?c=gt-nuc_4021&gmax=5021&gmin=3021&label=id:node_7416608
Gisaid Query: C335A, T27876G
Defining Mutations: ORF7b: C41G, H42L, A43L and ORF1ab: T1597I, T6889M, R24S
First Seq: 2023-04-10
Most Recent: 2023-08-26
OQ860513.1 OQ893033.1 OQ930360.1 OR418782.1 OR399319.1 OR150499.1 OR487440.1 OR460065.1 OR346514.1 OR516162.1 OR516508.1 EPI_ISL_18228543 EPI_ISL_18137914 OR480829.1 EPI_ISL_18231334 OR465600.1 OR476907.1 OR465601.1

**Comment by FedeGueli** [comment]
@ryhisner again the orf7b:31-43 thing

**Comment by ryhisner** [comment]
There are two sequences collected in April in this branch, and it's remained mostly confined to the US South, with a few sequences along the East Coast, so I think it's pretty slow. 

This set of mutations creates a ton of extended homology for the ORF8 TRS, which would be expected to increase transcription of ORF8. XBB.2.3 lineages clearly employ a different strategy than XBB.1 with regard to ORF8 and ORF9b, so this seems to be a sort of extension of the pro-ORF8 strategy of XBB.2.3. 

Here's a picture of what this set of mutations/insertion creates. 
<img width="1503" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/26b67004-bdd1-4f1c-a8ec-c9181a3a52a6">

**Comment by FedeGueli** [comment]
Thank you Ryan

**Comment by FedeGueli** [comment]
29 now. keep it checked cause although slow showed up in different countries so maybe it has an undersampled reservoir.
