### ISSUE TITLE
FY.5 + S:T572I small saltation branch with S:M153I, S:F186S and S:S247N (21 seqs in 7 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#790]
Defining mutations:
FY.5>C23277T (S:T572I)>T26921C>C5312A (ORF1a:L1683I)>A610T, G13313A(ORF1a:V4350I), C21057T, G22021T(S:M153I), T22119C (S:F186S), G22302A (S:S247N)
GISAID query: A610T, G13313A, G22021T
Earliest seq: 2023-08-25 (UK- EPI_ISL_18227258)
Most recent seq: 2023-09-06 (Singapore- EPI_ISL_18243568)
Countries detected: Singapore (2), UK (1)

Usher Tree:
![QQ截图20230911201235](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/3c900dc8-8492-4169-884d-a147ebbad106)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8765_ef5960.json?c=gt-S_186

A small and very new saltation branch with international transmission. Despite acquired 3 NTD aa mutations, this branch (even nearly the whole FY* lineages) still lack S:F456L. 

One seq gets S:K969N rev but probably artefact.

Genomes:
EPI_ISL_18227258, EPI_ISL_18243506, EPI_ISL_18243568

**Comment by HynnSpylor** [comment]
one more in Virginia, US but it seems slow.

**Comment by FedeGueli** [comment]
Lets wait a bit more. For sure XBB.1.22.1 backbone is apparently the slowest of the last spring swarm , still fascinating that it could pick updifferent spike mutations than other lineages without restoring competitivity

**Comment by Sinickle** [comment]
7 seqs now I believe

**Comment by FedeGueli** [comment]
This seems going i m adding S:t572I to the title, l

**Comment by FedeGueli** [comment]
@angiehinrichs could you take a look at FY.5 tree please? S:T572I seems highly homoplasic in it. to me is real and no misplacement.
![Schermata 2023-10-01 alle 10 18 32](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/325a2430-739d-43f3-81d4-12ebd33846af)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2df58_9105f0.json?c=userOrOld&label=id:node_3489440

**Comment by HynnSpylor** [comment]
@FedeGueli Not only in FY.5 but also in several FY* lineages

**Comment by HynnSpylor** [comment]
9 seqs now（England+1/Israel+1）

**Comment by FedeGueli** [comment]
This seems going very good. lets see if it goes on.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs could you take a look at FY.5 tree please? S:T572I seems highly homoplasic in it. to me is real and no misplacement.

Yes, it's strange that it would appear in 3 different sub-branches, but it looks pretty coherent as far as the tree is concerned.

> @FedeGueli S:T572I is not only in FY.5* but also common in other FY* lineages

It's one of the defining mutations of FY.1.2.  It has a couple small branches in FY.3.1 but they stayed small.

**Comment by FedeGueli** [comment]
+1 Malaysia, England only 10 with the query

**Comment by FedeGueli** [comment]
it is spreading fast propose it when it reaches 25 if keeps this pace.

**Comment by HynnSpylor** [comment]
21 seqs now 
I'll propose it in main page if reaches 30

**Comment by FedeGueli** [comment]
@HynnSpylor two samples from Uk have further acquired 284I and 704L: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_9cf3_2de560.json?label=id:node_3214588
![Schermata 2023-11-02 alle 00 27 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c59ced99-0201-44b9-b7a9-7e5d742fc43d)
