### ISSUE TITLE
HK.3.1 + ORF1a:G49C, N:V270L 255 seq.

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#791]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/60f57765-946d-41a4-9fbe-31b359f4957e)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e03a_fafc40.json?c=gt-N_270&gmax=29533&gmin=28274&label=id:node_6962742
gisaid query: G410T, T11269C
first seq: 2023-08-14
most recent: 2023-08-27
EPI_ISL_18220240 EPI_ISL_18220237 EPI_ISL_18229712 EPI_ISL_18141234 EPI_ISL_18238183 EPI_ISL_18215934

**Comment by Fearuncle** [comment]
18 seq. from Sweden with S:681R

**Comment by FedeGueli** [comment]
It will hardly compete vs JN.1 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=G410T%2CT11269C&analysisMode=CompareToBaseline& still it is faster than parent https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3.1*&nucMutations1=G410T%2CT11269C&analysisMode=CompareToBaseline&

cc @corneliusroemer

**Comment by FedeGueli** [comment]
Please propose it..
