### ISSUE TITLE
HK.3 (EG.5.1.1.3) sublineage with S:L8F and S:N481K (4 seqs in Sichuan, China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#792]
Defining mutations:
HK.3>A7210G, C19572T>G21586C (S:L8F), T23005A (S:N481K), C29067T (N:T265I)
GISAID query: A7210G, G21586C, T23005A
Earliest seq: 2023-08-18 (Sichuan, China- EPI_ISL_18246367)
Most recent seq: 2023-08-22 (Sichuan, China- EPI_ISL_18246364)
Countries detected: China (3)

Usher Tree:
![QQ截图20230912102847](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/fbdae3ae-c806-40bf-b6a1-8bfe41f14462)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_300f_fbe840.json?c=gt-S_481

S:N481K has popped up recently, especially in BA.2.86* lineages. As the one of biggest Flip-lineages, HK.3 is also concerned, and we can track it for a time.

*Also notice that Sichuan Province is the first place to identify EG.5.1* lineages in China, and now more than half of samples get S:L455F-F456L flip

Genomes:
EPI_ISL_18246364, EPI_ISL_18246366, EPI_ISL_18246367

**Comment by FedeGueli** [comment]
> _Also notice that Sichuan Province is the first place to identify EG.5.1_ lineages in China, and now more than half of samples get S:L455F-F456L flip

Impressive.

**Comment by FedeGueli** [comment]
no recent sequence from this closing it for now. (i suspect Hk.3 is better in its original way than with spike mutations but too soon to say)
