### ISSUE TITLE
Two EG.5.1.1+Flip+S:V171I branches (29 and 4 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#793]
HK.3+S:V171I(G22073A)

GISAID query: G22927T,G22073A,-G21604T
No. of seqs: 6(Singapore 5 China 1)

First: EPI_ISL_18145963, Yunnan, 2023-8-14
Latest: EPI_ISL_18243561, Singapore, 2023-9-6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f46b_fcc720.json?f_userOrOld=uploaded%20sample&label=id:node_10825412)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3793fc85-7aaf-481f-8e9b-6ca8b78601c8)

HK.2+S:L455F(G22927T)(Branch 23,#537)+A7088T, T18648C, A22310C,G22073A(Orf1a:N2275Y, S:T250P,V171I)

GISAID query: G22927T,G22073A,G21604T
No. of seqs: 2(Shanghai)
EPI_ISL_18232598,18232599, 2023-8-22/23
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1f46b_fcc720.json?label=id:node_6957220)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/29b22c46-404d-456d-ad38-c32ed6b2d55d)

S:V171I is a new mutation but happens independently in two EG.5.1.1+Flip branches.

**Comment by FedeGueli** [comment]
The 2nd one is Branch 23 of #537 but good to trck the mutation specifically so may i ask you to call it HK.2 Branch 23 ?

**Comment by aviczhl2** [comment]
> The 2nd one is Branch 23 of #537 but good to track the mutation specifically so may i ask you to call it HK.2 Branch 23 ?

Yeah of course. 

Since both S:Q14H and S:L455F are highly convergent it is hard to distinguish whether it's HK.2+L455F or HK.3+Q14H.

**Comment by FedeGueli** [comment]
Branch 1 went to 12 with the last batch from Singapore

**Comment by FedeGueli** [comment]
Branch 1 went to 14 Samples from Canada and Shanghai

**Comment by FedeGueli** [comment]
S:V171I is an light escape mutation from a new class of ABs recovered by Liu from  Beta serum, they block the binding with a different mechanism interacting with SD.1 (residues 522/577/583) in the spike and Ntd (residues 100-126-170/176)
https://www.biorxiv.org/content/10.1101/2023.04.08.536123v1.full.pdf
![Schermata 2023-09-29 alle 09 55 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/75ca4d5b-8af6-4fef-91a8-a16fd76c254e)

**Comment by FedeGueli** [comment]
@aviczhl2 since branch 2 is branch 23 in #537 here i would focus on Branch 1 that seems growing. please re edit the proposal

**Comment by aviczhl2** [comment]
> @aviczhl2 since branch 2 is branch 23 in #537 here i would focus on Branch 1 that seems growing. please re edit the proposal

It is sub-branch of that branch, not the whole branch.

**Comment by FedeGueli** [comment]
> > @aviczhl2 since branch 2 is branch 23 in #537 here i would focus on Branch 1 that seems growing. please re edit the proposal
> 
> It is sub-branch of that branch, not the whole branch.

Yeah once fixed the Y144F bug we will see where it is really. 
Please re edit the proposal focusing on branch 1 mentioniing branch 2 with the query as sublineage of #23 and its potential misplacement

**Comment by aviczhl2** [comment]
Branch 1 designated HK.3.7 @FedeGueli , and branch 2 seems stopped growing, so close it.

**Comment by FedeGueli** [comment]
Designated HK.3.7 via https://github.com/cov-lineages/pango-designation/commit/e0fe839746d96bbf4c1866d90c9bef3c0adfc9a4

**Comment by FedeGueli** [comment]
> Branch 1 designated HK.3.7 @FedeGueli , and branch 2 seems stopped growing, so close it.

Thank you agree for closing.
