### ISSUE TITLE
EG.5.1.1+Orf1a:K129R,Orf1b:E867D, S:A222S(9 seqs, Japan) 

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#795]
EG.5.1.1+C11779T+A651G, G16068T, G22226T(Orf1a:K129R,Orf1b:E867D, S:A222S)

GISAID query:A651G,C11779T,G22226T
No. of seqs: 9(Japan)

EPI_ISL_18096913-18096919,18096921,2023-7-28
EPI_ISL_18096924, 2023-7-31

Propose it because it has S:222 mutation and also it recombines with XBB.1.5.70.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10128_fee6d0.json?label=id:node_6962572)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/886b4b5f-0a77-4ef7-aa53-76c30844001f)

**Comment by FedeGueli** [comment]
Very weird it seems a cluster too on month earlier than the cluster of its recombinant in Italy. A lot of bits missing in its spread.

**Comment by aviczhl2** [comment]
> Very weird it seems a cluster too on month earlier than the cluster of its recombinant in Italy. A lot of bits missing in its spread.

This is the only Orf1a:K129R+EG.5.1 seq on GISAID. It is possible that the real donor is elsewhere but based on current evidence this is the most likely.

**Comment by aviczhl2** [comment]
> Very weird it seems a cluster too on month earlier than the cluster of its recombinant in Italy. A lot of bits missing in its spread.

#724 is another example whose donor and recombinant are found in different countries.

**Comment by FedeGueli** [comment]
> > Very weird it seems a cluster too on month earlier than the cluster of its recombinant in Italy. A lot of bits missing in its spread.
> 
> #724 is another example whose donor and recombinant are found in different distant countries.

I was not dubious on that, just noting we lost the track of it and it popped up as recombinant with a south american flip lineage in Italy .

**Comment by aviczhl2** [comment]
> I was not dubious on that, just noting we lost the track of it and it popped up as recombinant with a south american flip lineage in Italy .

Haha, we have planes that can carry viruses across continents in hours.

**Comment by FedeGueli** [comment]
closing it for now.
