### ISSUE TITLE
XBB.1.5.70/EG.5.1.1 recombinant in Italy(11 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#796]
XBB.1.5.70+A651G,C8841T,C12469T,C14396T,C18807T,T28005C(rev), T28297C, C29625T

Orf1a:K129R,T2859I
Orf1b:T310I
Orf8:S38P(rev)
Orf9b:I5T
Orf10:S23F

EG.5.1.1 is from #795, XBB.1.5.70 is a sibling branch of https://github.com/cov-lineages/pango-designation/issues/2276
EG.5.1.1--XBB.1.5.70--EG.5.1.1
Breakpoint 1 between 652 and 2333
Breakpoint 2 between 27508 and 28004

A651G,T28005C(rev), T28297C, C29625T are from EG.5.1.1(#795)
C8841T,C12469T,C14396T,C18807T are from XBB.1.5.70-branch.

This is another XBB.1.5.70+Orf9b:I5T recombinant( apart from XCH), so deserves attention.

GISAID query: A651G,C29625T,C8841T
No. of seqs: 9(Italy)
EPI_ISL_18226627,18226629,18226636,18226639,18226640,18226642,18226643,18226650, 2023-8-29

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2db1e_e69c90.json?label=id:node_7252040)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6e27cc38-2f16-4c40-acd7-8fd8f5879f72)

**Comment by FedeGueli** [comment]
I think it is just a cluster lets wait next two weeks and see.

**Comment by FedeGueli** [comment]
11 all collected the same day all from Emilia Romagna

**Comment by FedeGueli** [comment]
no new sequence coming from this.
