### ISSUE TITLE
Potential XBB.2.3.8* and EG.5* Recombinant (12 seqs, South Australia)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#797]
**Query:** `C4993T, C15279T, T22930A`
**Earliest seq:** 2023-08-20 (`EPI_ISL_18225485`, South Australia)
**Latest seq:** 2023-08-29 (`EPI_ISL_18246784`, South Australia)
**Sampled Countries:** Australia (7, SA)

**Recombinant Profile:** 
- **Nearest Phylogenetic Branch**: **XBB.2.3.8** > `T18921C` > _C26684T_ > `C15240T` > `C4993T` > _C29200T_ > `C15279T`, _T23449C_ > `C3768T(ORF1a:T1168I), C14925T`
- **Mutations on Nearest Phylogenetic Branch**:
```
nuc	unique	A2039G, C23449T, T26684C, G27084T, A27507C, T29200C
nuc	homoplasies	C1403T, C3429T, T22930A, G22995A, T23123C, T27431C, G27915T, T28297C, C29625T, T29706G
nuc	reversionsToRoot	T23123C, C23449T, T26684C, T27431C, T29200C, T29706G
S	homoplasies	F456L, R478K, S521P
S	reversionsToRoot	S521P
M	unique	A188S
ORF7a	homoplasies	V13A
ORF7a	reversionsToRoot	V13A
ORF8	homoplasies	G8*
ORF10	homoplasies	S23F
ORF1ab	unique	T592A
ORF1ab	homoplasies	P380S, T1055I
```
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/dabfe36a-3e61-4dca-b2ee-a759a0404145)

- **Donor A**: XBB.2.3.8* with `ORF1a:T1168I(C3768T)`, `C4993T`, `C14925T`, `C15240T`, `C15279T`, `T18921C`, upstream from 5' end to breakpoint
- **Donor B**: EG.5*, downstream from breakpoint to 3' end
- Breakpoint: Between `nuc 22480/spike_306` and `nuc 22930/spike_456`
- Private Mutations: `ORF1a:P380S(C1403T)`, `ORF1a:T592A(A2039G)`, `ORF1a:T1055I(C3429T)`, `M:A188S(G27084T)`

<details><summary>Genomes: </summary>

`EPI_ISL_18225485, EPI_ISL_18225503, EPI_ISL_18225518, EPI_ISL_18246744, EPI_ISL_18246752-18246753, EPI_ISL_18246784`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice39_genome_145c_13da0.json?branchLabel=back-mutations&label=id:node_7410192
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/318e36e0-a5d9-41f6-9a2a-d3d9a401968e)

**Trivia:**
- This recombinant traded `S:Q52H` and `S:T478R` for `S:F456L`, probably not a good bargain and hopefully not going anywhere.
- The other donor is unlikely the more popolar EG.5.1.1, or EG.5.2, for it doesn't have `C25572T` nor `C28754T/N:161F` after breakpoint, despite we can find a triplet of EG.5.1.1 with `M:A188S(G27084T)`, but those seqs also have `M:T9A(A26547G)`, so they are likely unrelated.

**Comment by FedeGueli** [comment]
It gave away also S:P521S but got the XBB.2.3 reversion of Orf1b:S959S together with the loss of Orf8  and the acquisition of Orf9b:I5T i am not sure it will be slow!

**Comment by FedeGueli** [comment]
no further spread

**Comment by FedeGueli** [comment]
It is likely dead closing it for now. Ping @corneliusroemer for his recombinant list.

**Comment by FedeGueli** [comment]
confirmed dead off
