### ISSUE TITLE
BE.13 (= BA.5.3.1 +S:346T +S:T478R)  + S:T747I sublineage still circulating in South Africa (134 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#80]
BA.5.3.1 has been very successful in South Africa since its emergence being one of the first lineage gaining there S:R346T in multiple sublineage and managing in that way to resist to BA.5.2/BF/BA.2.75 variant soup earlier last autumn. 
Then it has been blown away before by BQ.1* and then by XBB.1.5 but very interestingly it managed to survive and went on evolving gaining in a branch S:R346T and S:K478R and being caught and designated by @corneliusroemer in March 2023.

Since one branch of it further gained S:T747I and was still sampled in April.

So i propose it to keep track of this neverlasting evolution route.

Defining mutation: BE.13 >>C27393T >> S:T747I (C23802T) 

C27393T is right in the TRS of Orf7a cc @ryhisner (My guess it worsens it but i m a rookie!)
![Schermata 2023-05-21 alle 12 13 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/84947d00-0ca6-49e4-805f-db280cede9a1)

Tree:
![Schermata 2023-05-21 alle 12 20 35](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/dcfc252a-c71e-4573-8b70-f5283fa7ee4b)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice53_genome_330ab_87b310.json?label=id:node_6302368

Gisaid query: C23802T, C27393T,T2665C

**Comment by ryhisner** [comment]
Nice spot on that C27393T, Fede! It's actually imposes a double-hit to ORF7a—not only does it spoil the TRS, going from the ideal AAACGAAC to the suboptimal AAACGAAT, it also seriously impairs the Kozac sequence for the ORF7a start codon, going from the best -1 residue (C) to the worst (T). I have to imagine this comes pretty close to zeroing out ORF7a expression.
<img width="1268" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/27646a9e-cd9a-4c74-aa65-78b70689bb79">

**Comment by FedeGueli** [comment]
Thx @ryhisner !

**Comment by HynnSpylor** [comment]
I have watched it for a long time. recently it slowly spreads in England and France and half of them with S:F157L

**Comment by FedeGueli** [comment]
last one  from Michigan

**Comment by FedeGueli** [comment]
135 and goodbye to this one.
