### ISSUE TITLE
Another EG.5.1.1+S:L452R (20 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#800]
EG.5.1.1+C28292A(N:Q7K)+T22917G(S:L452R)

GISAID query: C28292A,T22917G,G13627A
No. of seqs: 8(Singapore 7(all local) China 1)

First: EPI_ISL_18146022, China, 2023-8-15
Latest: EPI_ISL_18243495, Singapore, 2023-9-5

The 1st one is https://github.com/sars-cov-2-variants/lineage-proposals/issues/678 circulating in low-sampled provinces of China.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_18256_129d90.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c9300f95-d991-48f3-8f54-d840c6658ae0)

**Comment by FedeGueli** [comment]
it seems fast lets see when it grows.

**Comment by FedeGueli** [comment]
18 now all Singapore+Hubei

**Comment by FedeGueli** [comment]
@ryhisner this has C28292A T28297C in Orf9b could do something to the secondary TRS you spotted back in July/August??

**Comment by FedeGueli** [comment]
propose it when it reaches 20.

**Comment by FedeGueli** [comment]
Designated HK.18 via https://github.com/cov-lineages/pango-designation/commit/1bf9c67c15e270cc4d909eaaed5cb54be7ef8ad0
