### ISSUE TITLE
GP.1(CH.1.1+S:Q52H)+5-nuc,5-aa including S:F456L(10 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#801]
GP.1+C560T(orf1a:R99C)+T25496C(Orf3a:I35T)+G14653T(Orf1b:V396F)+C26833T,T22928C(S:F456L,M:A104V)

GISAID query: T22928C,C26833T,T25496C
No. of seqs:5(Italy 3 Canada 1 Spain 1)
First: EPI_ISL_17790062, Italy, 2023-5-5
Latest: EPI_ISL_18224401, Canada, 2023-8-24

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_18256_129da0.json?label=id:node_7682644)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3670e2d7-b7e7-440c-af23-42556ccb02f8)

**Comment by FedeGueli** [comment]
This branch of GP.1 has the brand new orf7b spotted by @ryhisner due to del27795_27796

**Comment by aviczhl2** [comment]
> This branch of GP.1 has the brand new orf7b spotted by @ryhisner due to del27795_27796

According to GISAID, it seems complex. One seq has del27995_27996, One seq has del27888_27888, one seq has del27499_27501, and the other two doesn't have Orf7b deletions.

Do they all have del27995_27996 and other forms are just artefacts?

**Comment by FedeGueli** [comment]
The spanish sample at the top looks like a recombinant with SOme XBB.1/orf8:8stop/orf9b:I5T sublineage carrying Orf7a:G26S, G27915T, orf9b:I5T (T28297C) but i dint find any with the same deletion of it at Orf7a:S36- (del27499_27501) . To be noticed that this sample has not the Orf7b frameshifting deletion confirming it is recombiantion.

**Comment by FedeGueli** [comment]
AH thx @aviczhl2 three samples out of 5 have no coverage in orf7a/Orf7b:=rf8

**Comment by FedeGueli** [comment]
wow all of them but Italy from Tigem Campania has N:A211S , so maybe the spanish plus the three without orf7a coverage are a different lineage?
![Schermata 2023-09-13 alle 12 11 07](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/dc392280-ba3d-4692-90a7-05d7beb7acab)

**Comment by aviczhl2** [comment]
> wow all of them but Italy from Tigem Campania has N:A211S , so maybe the spanish plus the three without orf7a coverage are a different lineage? ![Schermata 2023-09-13 alle 12 11 07](https://user-images.githubusercontent.com/87669813/267617503-dc392280-ba3d-4692-90a7-05d7beb7acab.png)

Does all GP.1 have that unique orf7b? Recombination of something?(XBB.2.3 for those with Orf8 and XBB.1.9 for the one with Orf8:G8* and T28297C?)

**Comment by FedeGueli** [comment]
> > wow all of them but Italy from Tigem Campania has N:A211S , so maybe the spanish plus the three without orf7a coverage are a different lineage? ![Schermata 2023-09-13 alle 12 11 07](https://user-images.githubusercontent.com/87669813/267617503-dc392280-ba3d-4692-90a7-05d7beb7acab.png)
> 
> Does all GP.1 have that unique orf7b? Recombination of something?(XBB.2.3/DV.7.1? for those with Orf8 and XBB.1.9 for the one with Orf8:G8* and T28297C?)

Most of them or several of them at least. In italy all of them,

**Comment by aviczhl2** [comment]
But N:A211S is not common among XBB*s. Hard to think that this specific branch recombines with multiple different XBBs while all of them having N:A211S

**Comment by aviczhl2** [comment]
> AH thx @aviczhl2 three samples out of 5 have no coverage in orf7a/Orf7b:=rf8 ![Schermata 2023-09-13 alle 12 08 51](https://user-images.githubusercontent.com/87669813/267616880-b36a63ce-8f85-4508-a628-4baeee58512f.png)

Oh. So 4 are real GP.1(1 with GP.1-specific Orf7b and 3 w/o coverage) while the Spanish one is(sandwich) recombinant of XBB.1.9/16/22?

**Comment by FedeGueli** [comment]
> > AH thx @aviczhl2 three samples out of 5 have no coverage in orf7a/Orf7b:=rf8 ![Schermata 2023-09-13 alle 12 08 51](https://user-images.githubusercontent.com/87669813/267616880-b36a63ce-8f85-4508-a628-4baeee58512f.png)
> 
> Oh. So 4 are real GP.1(1 with GP.1-specific Orf7b and 3 w/o coverage) while the Spanish one is(sandwich) recombinant of XBB.1.9/16/22?

Yes exactly , i am not sure about the ones without orf7a -orf7b coverage if they are recombinants too, but unluckily.

**Comment by aviczhl2** [comment]
2 more from Spain, EPI_ISL_18264891,18264895
However both of them have their Orf7b masked

**Comment by aviczhl2** [comment]
+1 Italy EPI_ISL_18272792

But this one also has Orf7b masked.

**Comment by aviczhl2** [comment]
+1 Canada, EPI_ISL_18305352, del27388_27388 and 27389N

**Comment by aviczhl2** [comment]
+1 Israel

**Comment by ryhisner** [comment]
I think there's a decent chance this one—or at least 8/10 of them—had something similar to the GW.5.1.1 ORF7a-ORF7b-ORF8 deletion. Seems to be a dead lineage, so probably not worth investing the time necessary to investigate it properly. But I think such deletions are much more common than we'd ever suspected.

**Comment by aviczhl2** [comment]
> I think there's a decent chance this one—or at least 8/10 of them—had something similar to the GW.5.1.1 ORF7a-ORF7b-ORF8 deletion. Seems to be a dead lineage, so probably not worth investing the time necessary to investigate it properly. But I think such deletions are much more common than we'd ever suspected.

Thanks. This explains why the Orf7b of this lineage look so different from other GP.1s.

**Comment by FedeGueli** [comment]
ah thanks @ryhisner @aviczhl2 and me discussed the orf7b of this lineage multiple times without reaching a clear picture!  i was thinking no coverage there while likely it was the deletion you found!
