### ISSUE TITLE
HV.1+Orf1a:T1589I (NSP3_T771I = PLPro_T26I ) 326 seqs, 17 countries

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#802]
I just noticed that like EG.5.1.1, there is also a sizeable HV.1+Orf1a:T1589I branch.

Convergent evolution or recombination? It is possible that this is HV.1/EG.5.1.1+Orf1a:T1589I recombination if we put the breakpoint between 5032 and 6540.

HV.1+C5031T(Orf1a:T1589I)

GISAID query: T22917G,C5031T,C5835T,C22033A
No. of seqs: 23( USA 22(NY,NJ,MA,AZ, Puerto Rico, CO,CA,HI,NC,FL,RI,TX,SC, 13 regions), Canada 1)

First: EPI_ISL_18060690, USA-CA, 2023-7-18
Latest: EPI_ISL_18235179, USA-NJ, 2023-8-28

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_18256_129d90.json?label=id:node_6952020)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/036453a9-814f-476a-a945-11c2063cc8bf)

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/d97669d9-da69-461b-8f3a-da36152535bd)

Proportion of C5031T only skyrockets recently. (Due to the two separate EG.5.1*+C5031T branches?)

**Comment by FedeGueli** [comment]
Orf1a:T1589I is NSP3_T771I = PLPro_T26I

**Comment by aviczhl2** [comment]
34, UK

**Comment by FedeGueli** [comment]
This seems slower than parental HV.1: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HV.1*&nucMutations1=T22917G%2CC5031T%2CC5835T%2CC22033A&analysisMode=CompareToBaseline&

88seqs now

**Comment by aviczhl2** [comment]
104, New Zealand

**Comment by aviczhl2** [comment]
132, Norway

**Comment by aviczhl2** [comment]
158, Sweden

**Comment by FedeGueli** [comment]
> It doesnt seem faster than parent :https://cov-spectrum.org/explore/North%20America/AllSamples/Past2M/variants?nextcladePangoLineage=HV.1*&nucMutations1=T22917G%2CC5031T%2CC5835T%2CC22033A&analysisMode=CompareToBaseline&

it is further slowing down.

**Comment by aviczhl2** [comment]
218, Italy, france

**Comment by aviczhl2** [comment]
258, Israel, Australia, Belgium,

**Comment by aviczhl2** [comment]
291, Spain, Austria, China, Greece,

**Comment by FedeGueli** [comment]
still i find it slower than parental.

**Comment by aviczhl2** [comment]
326, Japan, Denmark

**Comment by FedeGueli** [comment]
Please propose it.
