### ISSUE TITLE
HK.6/XBB.1.16 recombinant(30 seqs, 4 countries, Uk)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#803]
HK.6+A28447G(Orf9b:55),C29386T,T29625C(Orf10:23 rev)

HK.6--XBB.1.16
Breakpoint between 27508 and 28446

GISAID query: C29386T,A22320G,G13627A
No. of seqs: 9(UK 8 Austria 1)

8 on GISAID, 1 CLIMB seq without C29386T(but still having A28447G and 29625 rev, guess it actually belongs to this)

First: EPI_ISL_18106623, UK, 2023-7-22
Latest: EPI_ISL_18248591, UK, 2023-8-29

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8795_16a820.json?label=id:node_6958435)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a6e6e0e1-6a63-4630-9c18-8a4f93dbd68d)

**Comment by aviczhl2** [comment]
21, Canada

**Comment by aviczhl2** [comment]
+1 Luxembourg

**Comment by FedeGueli** [comment]
too slow closing it
