### ISSUE TITLE
GY.1 (XBB.1.16.2) with S:F456L then S:L455F (23 seqs, China, France, Denmark, USA, Canada, UK)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#804]
**Defining Mutations:** **GY.1** > `T22928C(S:F456L)` > `C19380T, G22927T(S:L455F)`
**Query:** `C3042A, G12467T, G22927T`
**Earliest seq:** 2023-08-19 (`EPI_ISL_18246357`, Sichuan)
**Latest seq:** 2023-08-28 (`EPI_ISL_18254262`, Hubei)
**Sampled Countries:** China (2)

<details><summary>Genomes: </summary>

`EPI_ISL_18246357, EPI_ISL_18254262`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice5_genome_test_5f584_906570.json?label=id:node_10990590
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/2ecbf7e4-2684-4cf0-9ba9-4a67cf824b77)

**Comment by FedeGueli** [comment]
2 more from Uk not yet on Gisaid.

**Comment by FedeGueli** [comment]
Clearly growing please propose it.

**Comment by FedeGueli** [comment]
This is doubling very fast (taking into account a canadian cluster) please propose it. @NkRMnZr

**Comment by FedeGueli** [comment]
thank you

**Comment by FedeGueli** [comment]
Desingnated GY.1.1 plus GY.1.1.1  with 475V described while transferred to the main repo.

via https://github.com/cov-lineages/pango-designation/commit/66cc3dba48226d02a200a1855d7cb351c8e4b1cc
and https://github.com/cov-lineages/pango-designation/commit/8e1a2dadf01956af0263f80ba6d86a510104bae2
