### ISSUE TITLE
XBB.1.9.1 saltation with 6 spike mutations (S:76I, 190S, 356T, 572I, 899S, 1070T) UK, US, Den(12)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#805]
Spotted using [Dave McNally tool 
](https://ukcovid.xyz/spike-combo.php?type=multi&mincount=2)

Defining mutations: 
XBB.1.9.1 > > **Orf1a: V3925I** ( G12038A = NSP7_V66I) > **S:R190S** (G22132T), **S:K356T** (A22629C), **S:T572I** (C23277T), **S:A899S** (G24257T)> **Orf1a:N1076D** (A3491G = NSP3_N258D), C9532T, T16776C, C21054T, **S:T76I** (C21789T), C23707T, **S:A1070T** (G24770A)

Tree:
![Schermata 2023-09-13 alle 13 22 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a5834467-0bd7-4d68-9ad0-6b3ea5d7dcd3)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_130c_19a650.json?label=id:node_7002353

Gisaid query : C23277T, G24257T,G22132T, A22629C

Actually it finds 5 samples on Gisaid ,
one of them (EPI_ISL_18239057) lacks S:T76I,S:A1070T and was sampled from a traveller entering US from Netherlands but it has no coverage at 1070 

Samples:
EPI_ISL_18244522, EPI_ISL_18244529 (Firs collected in England on 26/08/2023) , EPI_ISL_18248577,
EPI_ISL_18248583

**Comment by oobb45729** [comment]
3 N-glycan changes on this one, gaining N354 and N188 but losing N74.

**Comment by FedeGueli** [comment]
> 3 N-glycan changes on this one, gaining N354 and N188 but losing N74.

Tgank you! I didnt notice this

**Comment by krosa1910** [comment]
> 3 N-glycan changes on this one, gaining N354 and N188 but losing N74.

Is that from the the N-X(not P)-S/T/C rule? Just wonder how credible it is.

**Comment by krosa1910** [comment]
Also that is another one with K356T, T572I. I still miss those from my first designated lineage of XBB.1.5.44*
I think we have the most information on K356T. According to Cao that seems a very risky trade, pumping up great escape at E1-E3 sites ( have no ideas what they are exactly though), but at the risk of losing so much infectivity (Maybe that is why BN* are being comparatively unsuccessful up to now). 
Maybe 356T flip is what we are afraid of?
![F43yQfLakAAzZCE](https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/3830330e-d1c4-4553-bc05-0067a1aeb032)
![F44DoNubAAAII7q-1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/de1e0e5e-de91-41ef-ac24-8678f53c4b4b)

**Comment by olias120676** [comment]
There is a new one in the UK data, not on GISAID yet, sample date of 2023-09-06

The previous 4 from the UK could be in some way linked but this one looks fairly distinct. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_805a_2f5090.json?c=userOrOld&label=id:node_10870200
![Screenshot 2023-09-14 132556](https://github.com/sars-cov-2-variants/lineage-proposals/assets/24962257/5975d85a-45f2-4923-8b2d-18b2f2e2f93a)

**Comment by oobb45729** [comment]
> > 3 N-glycan changes on this one, gaining N354 and N188 but losing N74.
> 
> Is that from the the N-X(not P)-S/T/C rule? Just wonder how credible it is.

S:R190S is also in Gamma, and we know that Gamma has the N188-glycan.

**Comment by FedeGueli** [comment]
Now found also in Us and Denmark.

**Comment by FedeGueli** [comment]
ping @corneliusroemer this seems going.

**Comment by FedeGueli** [comment]
12 now both from England

**Comment by corneliusroemer** [comment]
Yeah just found this independently. I did a deep dive to see if this might be a recombinant, but couldn't find anything. Sure, the Spike could be from HC.2 but there's not much evidence this isn't just convergence.

**Comment by FedeGueli** [comment]
> Yeah just found this independently. I did a deep dive to see if this might be a recombinant, but couldn't find anything. Sure, the Spike could be from HC.2 but there's not much evidence this isn't just convergence.

Thx.. yeah me too searched without results
