### ISSUE TITLE
BA.5 saltation (~17 spike mutations) 2 patients. (5 seqs, Brazil)

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#807]
GISAID query: T19896C, C21178T
This does capture 1 seq (the earliest seq) that is prior to the chronic patient's sequences and is therefore boring. 

Seq 1 belongs to a chronic patient. I'm highlighting their most recent sequence, and the sequence that was found in a separate patient. 
Seq1: EPI_ISL_18253248. July 7. 
Seq2: EPI_ISL_18253249. July 28. 

Shared spike mutations: 
17-18Del, C136F, 143-145del, 211del, L212i, i231T, W258C, D339H, R346i, V445A, G446S, F486A, A570T, D936G, P1143S

Seq1 spike mutations:
142-153del, R403K, L452Q

Seq2 spike mutations:
L452K, G885V

[Everything outside of the red box is patient/seq 1. Red box is patient 2. ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37e9b_1ce7a0.json?label=id:node_9264121&s=Brazil/RJ-FIOCRUZ-24746/2022%7CEPI_ISL_16411269%7C2022-12-02)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/a2ad36db-ee64-420e-b56b-7c9f41e80de1)

Thoughts:

EDIT: Thanks Josette 
**Both** patients are hospitalized. Seq 1 appears to be from a patient who has been sequenced continuously. Their sequences are.. 

EPI_ISL_18253248 July 7
EPI_ISL_18095961 March 26
EPI_ISL_16967081 January 2
EPI_ISL_16411269 December 2

The March and December sequences both show the patient was hospitalized. 
Possibly this patient infected patient 2, who was also in the hospital, due to an unrelated hospitalization?

**Comment by JosetteSchoenma** [comment]
@Sinickle They both say hospitalized, but the location seems different.

Same region, different city? Or same city, different neighborhood ? I don't know how that works in Rio de Janeiro.

**Comment by JosetteSchoenma** [comment]
@Sinickle There is another one, probably from the same patient as the ..48 one. EPI_ISL_18095961

**Comment by ryhisner** [comment]
A few very interesting things I noticed about these two BA.5 sequences:

• Both have the T27889C reversion. C27889T, present in all BA.5, ruined the TRS for ORF8, resulting in almost no ORF8 expression in BA.5 lineages. If this is not an artifact, it essentially represents the reacquisition of ORF8.

• Both have s2m mutations. Both sequences have C29762T, and sequence 1 has an additional two nucleotides deleted—∆29760-29761—adding to the standard BA.2/4/5 ∆29734-29759. s2m deletions and mutations have been common in extremely divergent chronic-infection sequences and even more common in the cryptic wastewater variants. Its function is unknown.

• Both have the ORF9b:G16D reversion. This mutation was always silent in N. 

• Both share ORF1b:P1000L/NSP13_P77L. This mutation was universal in Delta and is found in both XAY and XBC, but it has been extremely rare in Omicron. 

• Both have ORF1b:T1050I/NSP13_T127I. Initially, some BA.5.2 lineages had ORF1b:T1050N and some did not, but the ones with ORF1b:T1050N had a distinct growth advantage over those without it, and BA.5.2 + ORF1b:T1050N went on to become world dominant. Bafflingly, ORF1b:T1050N was never picked up by other BA.5 lineages—or any other lineage at all, for that matter. For reasons that remain utterly mysterious, it conferred a growth advantage to BA.5.2 but no other lineages—not even BA.5.2.1.
