### ISSUE TITLE
GS.4 (S:T478R) + ORF1a:K322R (9) + S:76I (7) + FLip (1)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#808]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/d26bc1bd-c2b6-4348-9199-022fa53e4b61)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/98d23e84-3015-427f-981a-904b31229fab)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26686_214b20.json?c=gt-nuc_1230&gmax=2230&gmin=230&label=id:node_7416069
gisaid query: A1230G, T9931C, T11656C
first Seq: 2023-08-21
Most Recent: 2023-08-23
EPI_ISL_18221912 EPI_ISL_18229142 EPI_ISL_18220528 EPI_ISL_18222150 EPI_ISL_18147045

**Comment by FedeGueli** [comment]
This is a FLipper + 521S , being caught by international airport surveillance i bet it is alreaady spreading quite well. GS.4 seems one of the fittest XBB.2.3 in the very last month.
