### ISSUE TITLE
XBB.1.9.1 with s:d614a (11 seq, pakistan france china scotland malaysia)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#81]
D614A is very very rare, only 41 sequences. 9 of them are in this recent tiny branch. 
First seq: 2023-03-10
Recent seq: 2023-04-13
Query: A23403C, C12789T

![Screenshot_20230521_114914_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/1aafedbc-c699-486f-9cf9-eb150be526d4)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2f254_a11950.json?c=gt-S_614&f_userOrOld=uploaded%20sample

**Comment by FedeGueli** [comment]
Interestingly (cc @ryhisner @thomaspeacock @c19850727 ) there is a sub branch of this that has Orf8:*8**R** 
G27915T >> T27915C and it has also reverted one of the two Orf1a defining of XBB.1.9.1. , from Pakistan.

![Schermata 2023-05-22 alle 00 07 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9015ea6f-26ff-4388-9db7-72a43494e78b)

**Comment by aviczhl2** [comment]
This was proposed in  https://github.com/cov-lineages/pango-designation/issues/1852

**Comment by FedeGueli** [comment]
Better tracking this here.

**Comment by BorisUitham** [comment]
Ah thanks @aviczhl2 , I didnt see that proposal

**Comment by BorisUitham** [comment]
There is also a sequence in malaysia now

**Comment by FedeGueli** [comment]
one more from Scotland

**Comment by BorisUitham** [comment]
Super slow. I'll give it 2 more weeks until I close, mostly because the mutation is so interesting otherwise I would close it much sooner

**Comment by FedeGueli** [comment]
closing this for now if it someting new pops up please ping me
