### ISSUE TITLE
 EG.5.1.3/DV.7.1 recombinant and its further recombinant with XBB.1.9.2 that may be dropped out by usher(2 seq and 16 seqs )

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#811]
I find a EG.5.1.3/DV.7.1 recombinant that usher registers with too many reversions and may be dropped out. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6b11ecf6-200e-4cd7-ac77-41b85ff903e5)

EG.5.1.3--DV.7.1
Breakpoint: Between 18584 and 19325

Extra mutations: C1684T,C7051T,C20320T,T24073C

Orf1b:H2285Y

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C24134A%2CC7051T%2CC1889T&nextcladePangoLineage1=EG.5.1.3*&nextcladePangoLineage2=DV.7.1*&analysisMode=CompareEquals&

C1684T,C7051T from an EG.5.1.3-branch.

C20320T,T24073C are private

Some DV.7.1 branches have C20320T however they have additional mutations after that so not possible.

Query: C24134A,C7051T,C1889T

The branch include 2 recombs:

(this one with additional C29546T, private, no DV.7.1 has this)
EG.5.1.3--DV.7.1
For EPI_ISL_18254485(France), C24134A,C7051T,C1889T,C29546T

(this one with additional A27507C, T28297C, G27915T(Orf9b:I5T, Orf8:G8*), indicating 2nd breakpoint between 26276 and 27506
EG.5.1.3--DV.7.1--XBB.1.9.2? (Not EG.5.1.3 for not having C29625T)
3-seq branch: C24134A,C7051T,C1889T,A27507C  (USA, Switzerland)

So EG.5.1.3 recombs with DV.7.1 and get recomb 1, while recomb 1 recombs with another XBB.1.9.2 and gets recomb 2?

If that's 1 seq I'll view it as artefact, however now we have 4 seqs from 3 countries.

EG.5.1.3-side donor:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/491c36d2-e6b8-4c4d-9759-0adcf9c47f74)

Current usher

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bdbe_841b00.json)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8a4cd24b-a794-4f03-91ee-6b61a2a518f7)

**Comment by AngieHinrichs** [comment]
Added to list, should be added when 2023-09-14 build is done, thanks.

**Comment by aviczhl2** [comment]
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_150f6_28b580.json?f_userOrOld=uploaded%20sample&label=id:node_10918298)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0ccda7f6-bf86-49a1-a71a-7eeccb734ae1)

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2, I added EPI_ISL_18284092 to the list so it should be added in the 2023-09-28 build, sorry about the delay.  EPI_ISL_18254485 is being added to the tree daily, but then removed by our filter of max 20 private mutations on a singleton sequence.  When EPI_ISL_18284092 is added, then EPI_ISL_18254485 will no longer be a singleton with all those mutations and the two sequences should be retained in the 2023-09-28 tree.

**Comment by aviczhl2** [comment]
@AngieHinrichs  A 3rd one appears, EPI_ISL_18316684, seems to be the same recomb of EPI_ISL_18284092.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/bb10a3f1-0b25-4773-a0e0-9c2c086452dd)

**Comment by AngieHinrichs** [comment]
OK, added, should be in the 2023-09-29 build.  I don't see EPI_ISL_18284092 in the 2023-09-28 build (on dev.usher.bio) as expected; I will try to figure out what happened there.

**Comment by aviczhl2** [comment]
@AngieHinrichs  There's one more from Switzerland. EPI_ISL_18327700

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/bd764637-11ba-4a72-89c6-99f65b4e93de)

**Comment by aviczhl2** [comment]
@FedeGueli @ryhisner @NkRMnZr @krosa1910 @HynnSpylor  please help me on this. Seems extremely complex.

**Comment by FedeGueli** [comment]
> @FedeGueli @ryhisner @NkRMnZr @krosa1910 @HynnSpylor please help me on this. Seems extremely complex.

For sure inwill look at it tomorrow

**Comment by AngieHinrichs** [comment]
Added, thanks.

**Comment by FedeGueli** [comment]
It is looks like a XCM-alike sandwich recombinant between EG.5.1.3/DV.7.1 ( and the french sample could be a further recombination or a recombinant itself parent of this recombinant)

to me it could be (please check):
from **Eg.5.1.3**:
C1889T,C2334T,G5720A,C9693T,C12789T,T16342C,A16878T,A18492G,A27507C,G27915T,T28297C
 
from **DV.7.1**: A19886G,A20741G,T22016C,C22033A,A22115G,A22190G,T22200G,G22331A,A22893C,T22917G,G22927T,T22928C,C24134A,T24991A,G25606A,C25721T,T25959C  
and C20320T [sublineage](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22031_93d580.json?f_userOrOld=uploaded%20sample&label=id:node_4403696) of DV.7.1 (10 seqs)
![Schermata 2023-10-01 alle 11 35 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0896fe3e-26e7-40bf-bc1b-b1033d396335)

**Private mutations**: 
C44T,C835T,C1684T,C7051T ,T24073C


So it would be 

1-18429 EG.5.13 
18430-19885 Breakpoint 1
19886-25959: DV.7.1
25960-27506 : Breakpoint 2
27507- 3' end: EG.5.1.3

**Comment by aviczhl2** [comment]
> So it would be
> 
> 1-18429 EG.5.13 18430-19885 Breakpoint 1 19886-25959: DV.7.1 25960-27506 : Breakpoint 2 27507- 3' end: EG.5.1.3

How about 29625 missing?

**Comment by FedeGueli** [comment]
> 27849

yeah it could be also this one as donor

**Comment by aviczhl2** [comment]
> > 27849
> 
> yeah it could be also this one as donor: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3e515_96edd0.json?c=userOrOld&label=id:node_10941447 (link edited)

But it also doesn't have 28695?

**Comment by FedeGueli** [comment]
> > > 27849
> > 
> > 
> > yeah it could be also this one as donor: https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3e515_96edd0.json?c=userOrOld&label=id:node_10941447 (link edited)
> 
> But it also doesn't have 28695?

it is dv.7.1

**Comment by FedeGueli** [comment]
So concluding:
 it could be a EG.5.1.3 with a dv.7.1/xbb.1.9 recombinant 
or a "EG.5.1.3/XBB.1.9 recombinant"sandwich recombinant with DV.7.1

**Comment by aviczhl2** [comment]
> So concluding: it could be a EG.5.1.3 with a dv.7.1/xbb.1.9 recombinant or a "EG.5.1.3/XBB.1.9 recombinant"sandwich recombinant with DV.7.1

Yeah so we agree. EG.5.1.3/DV.7.1/XBB.1.9.2 but not EG.5(for having 27507 but not 29625) triple recomb.

**Comment by FedeGueli** [comment]
> > So concluding: it could be a EG.5.1.3 with a dv.7.1/xbb.1.9 recombinant or a "EG.5.1.3/XBB.1.9 recombinant"sandwich recombinant with DV.7.1
> 
> Yeah so we agree. EG.5.1.3/DV.7.1/XBB.1.9.2 but not EG.5(for having 27507 and 28297 but not 29625) triple recomb. Amazing isn't it?

xbb.19 could it be also xbb.1.9.1 i think

**Comment by FedeGueli** [comment]
What we dont know if it was a single triple recomb or more parsimoniously a recombinant that then recombined again.

**Comment by FedeGueli** [comment]
So last take . EG.5.1.3>DV.7.1+20320T > XBB.1.9.1 ( or recombinatn with the 3'end recombined with XBB.1.9.1

**Comment by FedeGueli** [comment]
Deleted the last ones they have 27507 so def XBB.1.9.2 excluding EG.5.1

**Comment by Over-There-Is** [comment]
EG.5.1.3 / DV.7.1 / EG.5.1.3 / DV.7.1?

**Comment by aviczhl2** [comment]
> EG.5.1.3 / DV.7.1 / EG.5.1.3 / DV.7.1?

This may be another possibility. However the other 3 seqs don't share the 29546 with the French EG.5.1.3/DV.7.1 seq.

**Comment by Over-There-Is** [comment]
Two Independent recombinant?

**Comment by aviczhl2** [comment]
> Two Independent recombinant?

They share T24073C that does not present in any DV.7.1 samples so likely closely related.

**Comment by FedeGueli** [comment]
i have 7 today with the query : C24134A,C7051T,C1889T

**Comment by FedeGueli** [comment]
New tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4a481_c0e6d0.json?label=id:node_4964878
![Schermata 2023-10-03 alle 14 53 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/26cd7bd0-cf28-4b4c-8ff1-2ec1cf875fdc)

PING : @corneliusroemer super fast spread in different countries i suggest direct designation once reached 10.

**Comment by AngieHinrichs** [comment]
> New tree:

Thanks, all 7 seqs should make it into the 2023-10-23 build.

**Comment by aviczhl2** [comment]
> i have 7 (new countries: Denmark, England) today with the query : C24134A,C7051T,C1889T (ushering it) (confirmed)

Yeah,still 1 for the French EG.5.1.3/DV.7.1 and 6 for the further recomb of XBB.1.9.2

**Comment by aviczhl2** [comment]
+1 Germany EPI_ISL_18343383 @AngieHinrichs 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/7e7f504f-cc19-4933-b522-ca2d54ba4f51)

**Comment by AngieHinrichs** [comment]
Added, thanks.

**Comment by FedeGueli** [comment]
+1 austria

**Comment by aviczhl2** [comment]
EPI_ISL_18354524 @AngieHinrichs

**Comment by FedeGueli** [comment]
10 (+1 Dk)  EPI_ISL_18360399

**Comment by AngieHinrichs** [comment]
Added, thanks.

**Comment by aviczhl2** [comment]
+1 Netherlands EPI_ISL_18363256 @AngieHinrichs 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0ec4d029-5936-4fa4-ba95-45e2645e738d)

**Comment by aviczhl2** [comment]
The new Netherlands seq has del27623_27639. Orf7b frameshift?

**Comment by AngieHinrichs** [comment]
> +1 Netherlands EPI_ISL_18363256 @AngieHinrichs

Added, thanks.

**Comment by aviczhl2** [comment]
+2 Germany 
EPI_ISL_18373930, 18373939

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a4a01733-f12b-431b-9d12-02e85ab901ed)

[new usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28311_6b2010.json?label=id:node_4771553)

**Comment by AngieHinrichs** [comment]
Added, thanks.

**Comment by FedeGueli** [comment]
> The new Netherlands seq has del27623_27639. Orf7b frameshift?

Thx @aviczhl2 sorry i forgot to answer it seems a Orf7a:77-82 out of frame deletion giving a  frameshift with an early stopcodon TAA at Orf7a:84 so it should have a 38AA shorter Orf7a 
![Schermata 2023-10-12 alle 01 33 11](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c4c70c48-1c3d-4232-9c84-8fdaf34cad63)

**Comment by aviczhl2** [comment]
@AngieHinrichs  4 four seqs. 

EPI_ISL_18388280
EPI_ISL_18385324
EPI_ISL_18384901
EPI_ISL_18384897

**Comment by aviczhl2** [comment]
@AngieHinrichs one more from Belgium
EPI_ISL_18385476

**Comment by FedeGueli** [comment]
Flying.

**Comment by corneliusroemer** [comment]
I've had reviewing recombinant proposals on my todo list for a while - just came across this one independently as a red XCM.

I agree that this is an JG.4(EG.5.1.3)-DV.7.1-JG.4(EG.5.1.3) recombinant with

**Comment by aviczhl2** [comment]
> I've had reviewing recombinant proposals on my todo list for a while - just came across this one independently as a red XCM.
> 
> I agree that this is an JG.4(EG.5.1.3)-DV.7.1-JG.4(EG.5.1.3) recombinant

This one doesn't have C29625T which appears in EG.5.1, and there are 2 seqs with DV.7.1's orf8/orf9b.

**Comment by JosetteSchoenma** [comment]
XCT

**Comment by FedeGueli** [comment]
Designated XCT

**Comment by aviczhl2** [comment]
It seems that currently the parental recomb (without G8*, C27507A and T28297C) is designated as XCT? 

https://nextstrain.org/staging/nextclade/sars-cov-2

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/b32de4b6-84fb-4ce4-bc8e-3d4ad41f62e6)

**Comment by FedeGueli** [comment]
> It seems that currently the parental recomb (without G8*, C27507A and T28297C) is designated as XCT?
> 
> https://nextstrain.org/staging/nextclade/sars-cov-2
> 
> ![image](https://user-images.githubusercontent.com/10445944/275483350-b32de4b6-84fb-4ce4-bc8e-3d4ad41f62e6.png)

only that one? does the designation misses the real XCT? in the other case it catches all i would not make a difference cc @corneliusroemer what do you think?

**Comment by aviczhl2** [comment]
> only that one? does the designation misses the real XCT? in the other case it catches all i would not make a difference cc @corneliusroemer what do you think?

I'm not sure, but the 2 recombs shall not be under one name. Either give both a designation, this may create a recomb with only 2 seqs but helpful for explanation. Or remove seqs of the parental recomb from XCT and to clarify the children recomb is XCT.

**Comment by aviczhl2** [comment]
@AngieHinrichs new XCT(children recomb) seqs, 

EPI_ISL_18395595, EPI_ISL_18392290, EPI_ISL_18391834, EPI_ISL_18381777,EPI_ISL_18391799

**Comment by aviczhl2** [comment]
@AngieHinrichs  7 more today, all children. 

EPI_ISL_18403312, EPI_ISL_18403342, EPI_ISL_18403373-18403374,
EPI_ISL_18405163, EPI_ISL_18406342, EPI_ISL_18406427,

**Comment by JosetteSchoenma** [comment]
2 more from NSW. EPI_ISL_18411444 and EPI_ISL_18411775

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2 and @JosetteSchoenma, I added those IDs to my file.  In the future would it be too much trouble for you to add sequences to https://github.com/sars-cov-2-variants/lineage-proposals/blob/main/recombinants.tsv ?

**Comment by aviczhl2** [comment]
> Thanks @aviczhl2 and @JosetteSchoenma, I added those IDs to my file. In the future would it be too much trouble for you to add sequences to https://github.com/sars-cov-2-variants/lineage-proposals/blob/main/recombinants.tsv ?

That's for undesignated lineages. 

Will it cause conflict for designated lineages as they may also appear elsewhere with different labels? 

recombinants.tsv also has a function for manual search of currently proposed recombs I think it shouldn't be too big (keep it <1000 
seqs). Designated lineages may grow to very large and if there's too many seqs inside we cannot manual search. 

What's your suggestion?

**Comment by AngieHinrichs** [comment]
OK, I misunderstood the purpose of recombinants.tsv, thanks for clarifying that.  

Perhaps there could be a separate file just for IDs of sequences that should be exempted from the too-many-reversions filter?  Like #991, but just a file of IDs.

**Comment by aviczhl2** [comment]
> OK, I misunderstood the purpose of recombinants.tsv, thanks for clarifying that.
> 
> Perhaps there could be a separate file just for IDs of sequences that should be exempted from the too-many-reversions filter? Like #991, but just a file of IDs.

Maybe I shall create one to include those seqs as well as XCT before they are not removed by usher.  

BTW: Is XCM still being filtered out? When can usher automatically recognize a lineage and stop removing its seqs?

**Comment by AngieHinrichs** [comment]
> Maybe I shall create one to include those seqs as well as XCT before they are not removed by usher.

That would be extremely helpful!

> BTW: Is XCM still being filtered out?

Most XCM should not be filtered out as far as I can tell.  The 2023-10-23 tree has 72 sequences placed in XCM even though my local file that exempts sequences from too-many-reversion filtering has only 7 IDs (none in recombinants.tsv).  They are right on the edge of filtering, with 5 reversions relative to placement in the nextclade tree version 2023-09-21T12:00:00Z.  Any sequence with one or more extra reversions could be filtered.


>  When can usher automatically recognize a lineage and stop removing its seqs?

When these things happen:
1. There is a nextclade sars-cov-2 data release
2. I re-run nextclade with the latest data on all sequences

**Comment by aviczhl2** [comment]
> 1. There is a nextclade sars-cov-2 data release
> 2. I re-run nextclade with the latest data on all sequences

By nextclade data release, do you mean https://nextstrain.org/staging/nextclade/sars-cov-2 ?

I see XCT is already there?

**Comment by AngieHinrichs** [comment]
I believe https://nextstrain.org/staging/nextclade/sars-cov-2 is Cornelius's nightly build -- it's pre-release.  By release I mean official releases like https://github.com/nextstrain/nextclade_data/releases/ .  When there is a new release, I can download the new release data files and then re-run nextclade on all sequences.  

My nightly build runs the latest downloaded release on all new sequences, which doesn't take much time -- but re-running nextclade every night on all pre-existing sequences would take a lot more time.

**Comment by aviczhl2** [comment]
> I believe https://nextstrain.org/staging/nextclade/sars-cov-2 is Cornelius's nightly build -- it's pre-release. By release I mean official releases like https://github.com/nextstrain/nextclade_data/releases/ . When there is a new release, I can download the new release data files and then re-run nextclade on all sequences.
> 
> My nightly build runs the latest downloaded release on all new sequences, which doesn't take much time -- but re-running nextclade every night on all pre-existing sequences would take a lot more time.

I see. So whatsoever designated lineages will be included eventually when nextclade performs a formal release every month?

**Comment by AngieHinrichs** [comment]
> I see. So whatsoever designated lineages will be included eventually when nextclade performs a formal release every month?

Yes.

**Comment by aviczhl2** [comment]
1 more for the parental recomb. EPI_ISL_18494770

**Comment by aviczhl2** [comment]
1 more for the parental recomb EPI_ISL_18518466
