### ISSUE TITLE
GK.2+S:K356T 8 Seqs in UK and US

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#813]
Mutations on top of GK.2: G16236A->A22629C (S:K356T)
Gisaid Inquiry: A22629C,G16236A,G23093A
Sequences: EPI_ISL_18161462, EPI_ISL_18209224, EPI_ISL_18227154,
EPI_ISL_18227161, EPI_ISL_18247664, EPI_ISL_18248767,
EPI_ISL_18248772
Earliest: EPI_ISL_18227161 2023-08-04, England
Latest: EPI_ISL_18248772 2023-09-02, England
Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24e0_2890a0.json
<img width="731" alt="5C16F4E9-D54D-4AAF-8AA7-AFA6C3F0BBDF" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/19651c3e-75fe-4593-bae7-631191343122">
The top tree there 

Note: I was replying to Fed in #805 about probably K356T being more useful in Flip context, so I searched for this.
Not to say it is particularly fast, as a month after initial spread with 7 seqs is not some amazing performance with "flip". But still an interesting variant to track.

**Comment by krosa1910** [comment]
@FedeGueli May I get TeFlon for this combo？

**Comment by FedeGueli** [comment]
One more seq

**Comment by FedeGueli** [comment]
Designated GK.2.3
