### ISSUE TITLE
GK.2.1 with S:T478R ('FLippeR', 14 seqs, UK, Italy)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#817]
**Defining Mutations:** **GK.2.1** (XBB.1.5.70.2.1) > `T8119G, C22995G(S:T478R)`
**Query:** `T8119G, C15755G, C22995G`
**Earliest seq:** 2023-09-03 (`EPI_ISL_18258122`, England)
**Latest seq:** 2023-09-05 (`EPI_ISL_18258127`, England)
**Sampled Countries:** UK (4, EN)

<details><summary>Genomes: </summary>

`EPI_ISL_18258121-18258122, EPI_ISL_18258127, EPI_ISL_18258133`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_54ef7_3fd720.json?label=id:node_10878760
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/59ea5dd0-58e9-4b89-b040-8b5f96d4f6e7)

**Comment by krosa1910** [comment]
I agree FLip is good as a pun, yet FLippeR is less original, and sounds less impressive.

**Comment by FedeGueli** [comment]
It seems slow but worth tracking it for one month from nw before closing.

**Comment by FedeGueli** [comment]
closing it for now
