### ISSUE TITLE
FL.2.3 sublineage with S:L455F, F456L (3 seq, 2 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#818]
Subbranch of https://github.com/sars-cov-2-variants/lineage-proposals/issues/526#issuecomment-1712438500 branch A

Query: G28839T, G22927T,-C7765T (edited by FedeGueli)
FL.2.3> G28839T(N:R189L)> T22928C(S:F456L)> T12670C, G22927T(S:L455F), T27288C, C29769T

Earliest sequence: 08-23 Deyang, Sichuan, China EPI_ISL_18261463
Latest sequence: 09-19 Jincheng, Shanxi, China EPI_ISL_18401824

Sequences:
USA/WA-GBW-H10-016-4168/2023|EPI_ISL_18239091|2023-08-31
Sichuan/DYCDC-0164/2023|EPI_ISL_18261463|2023-08-23
Shanxi/JCCDC-JCCX0494/2023|EPI_ISL_18401824|2023-09-19

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json?label=id:node_6795306
![2023-09-16 (2)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/99cec70b-a5c6-4e01-a82c-6475f0abfe69)

**Comment by Over-There-Is** [comment]
It is possible to be originated in Guangdong. Expect the next batch of sequences.

**Comment by Over-There-Is** [comment]
> +1 Israel

It has not any one of T4579A, T12670C, A17615G, T27288C or C29769T, so I don't think it's related.

**Comment by FedeGueli** [comment]
thx i ve edited the query in: G28839T, G22927T,-C7765T

**Comment by Over-There-Is** [comment]
+1
