### ISSUE TITLE
XBB.1.16.2 with S:L84I, ORF1ab:A4068S in China (81 seq)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#82]
Earliest sequence: 2023-04-26
Recent sequence: 2023-05-08
GISAID query: G12467T, C21812A

While S:L84I has popped up throughout the pandemic especially in ba.5 lineages, orf1ab:a4068s (NSP8_A126S EDITED) is very recently getting traction, mostly in xbb.1.5 so far but also bq* and ch*.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G12467T%2CC21812A&

![xbb1162](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/89d1ad1e-0dba-44a2-afb7-f51b6c59b8c0)

 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5aaf7_a8ff90.json?f_userOrOld=uploaded%20sample&label=id:node_8433596

**Comment by BorisUitham** [comment]
1 from Taiwan

**Comment by BorisUitham** [comment]
This one also doesnt turn out to be very fast. I'll wait until it reaches 100 sequences before assessing this again.

**Comment by FedeGueli** [comment]
@BorisUitham i m propsoing a bub branch with 456L

**Comment by BorisUitham** [comment]
@FedeGueli i havent seen that, go ahead and propose it!

**Comment by BorisUitham** [comment]
Proposed at https://github.com/cov-lineages/pango-designation/issues/2066

**Comment by FedeGueli** [comment]
Designated GY.1
