### ISSUE TITLE
GN.1.1 (S:F456L) recombinant with an Orf9b:I5T carrying lineage  (Defining of XBB.1.5.73 T28271C>T reverted and T28297C added) 17 seqs

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#820]
Mutations on top of GN.1.1 (XBB.1.5.73.1.1) : C9430T, G12268A, G17679A (step 1)-> C28271T (reversion), T28297C(step 2)
Gisaid Inquiry: G25445T,T28297C,C18395T
Sequences: EPI_ISL_18104153, EPI_ISL_18147604, EPI_ISL_18213009,
EPI_ISL_18232593, EPI_ISL_18232870, EPI_ISL_18251318,
EPI_ISL_18251337
Earliest: EPI_ISL_18104153 07-25, US, TX
Latest: EPI_ISL_18251318 09-05, Canada
7 seqs with 3 countries would be not bad
Usher Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38a9f_4a6bc0.json?c=userOrOld
<img width="1387" alt="Screenshot 2023-09-15 at 2 54 26 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/a9ea51f2-4f99-477d-b44a-e93fc6d27eee">
Step 1 and Step 2 would be obvious here.

Note: I said that I want to discover a recombinant. It seemed my last proposal #819 was a stepwise saltation that gained T28297C, so I tried another branch of T17124C+T28297C search.

**Comment by FedeGueli** [comment]
Good spot @krosa1910 . @ryhisner is the man who spotted and understood the importance of A28271T first.
Ryan so you remember XBB.1.5.73 the lineage with 28271 mutated to C? Now it is reverted via recomb to T!! if you want to take a look please!

**Comment by ryhisner** [comment]
Coming back home to 28271T! You love to see it. This will definitely be an interesting one to watch.

**Comment by FedeGueli** [comment]
+ 2 still Ontario and Texas

**Comment by FedeGueli** [comment]
one more from TX

**Comment by krosa1910** [comment]
2 more updated from TX.
Judging from the metadata this could very likely be a family cluster

**Comment by krosa1910** [comment]
Update in Canada (although it look like a classical Canadian cluster)

**Comment by FedeGueli** [comment]
17 now

**Comment by FedeGueli** [comment]
no recent sample closing it
