### ISSUE TITLE
Another GK.2 (XBB.1.5.70.2) sublineage with S:K356T (on T10204C branch, 11 seqs in NY, US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#823]
Defining mutations:
GK.2>T10204C>C21781T>A22629C (S:K356T) 
GISAID query: C21781T, A22629C, G23093A
Earliest seq: 2023-09-03 (NY, US- EPI_ISL_18269252)
Most recent seq: 2023-09-09 (NY, US- EPI_ISL_18269255)
Countries detected: US (3)
Usher Tree:
![QQ截图20230916173417](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/00b7a025-04c5-4d7c-9c2d-7e750e5ef8fa)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30986_55c500.json?c=gt-S_356

Another convergent branch of GK.2+S:K356T (the first one on G16236A branch is proposed in #813). S:K356T is a popular mutation with increased escape effect.

Genomes:
EPI_ISL_18265096, EPI_ISL_18269252, EPI_ISL_18269255

**Comment by FedeGueli** [comment]
+1 NY

**Comment by FedeGueli** [comment]
11 now
