### ISSUE TITLE
New Recombinant of GK.1/XBB.1.16(24 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#824]
XBB.1.5.70+
C12253A, C17010T,C23673T(S:S704L), G25045A(rev), T27059C(rev),A27669G,T28005C(Orf8:38 rev),T28297C(Orf9b:5),A28447G(Orf9b:55), A29221G,T29386C

C23673T from GK.1
C12253A, C17010T from an American GK.1 branch
G25045A(rev), T27059C(rev),A27669G,T28005C(Orf8:38 rev),T28297C(Orf9b:5),A28447G(Orf9b:55), A29221G,T29386C from an American XBB.1.16 branch

GK.1--XBB.1.16
Breakpoint between 23674 and 25044

Like XCH, this one is Flip+704+Orf9b:I5T, so may have good advantage.

GISAID query: C12253A,A27669G,A29221G
No. of seqs: 5 (USA 3 Sweden 2)

First: EPI_ISL_18270019, USA, 2023-7-31
Latest: EPI_ISL_18258632, Sweden, 2023-9-7

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26622_653430.json?c=gt-nuc_29221&gmin=28221&label=id:node_7272167)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1b578ae0-e5e3-4919-9b37-9616ac4f155f)

[usher for XBB.1.16 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4538_656dd0.json?label=id:node_6834992)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/7d582fae-11bb-416b-82e1-8f98f33c5b7e)

[usher for GK.1 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_26622_653430.json?branchLabel=nuc%20mutations)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3346e5b7-b57d-4879-892b-9651d2397ecc)

Rapid overview : (edited) _S:V689I not defining but acquired further._
![Schermata 2023-10-06 alle 22 50 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fdf9898f-2903-4338-b32f-f7195becaf93)

**Comment by aviczhl2** [comment]
+1 Italy

**Comment by FedeGueli** [comment]
Propose once it reaches 20

**Comment by FedeGueli** [comment]
5 seqs from Sweden have S:S689I in the FCS too

**Comment by aviczhl2** [comment]
12/137=9% from the latest Swedish batch.

**Comment by FedeGueli** [comment]
Designated XCS
