### ISSUE TITLE
HN.1 + ORF1a:I1367V and S:E554D (77) represents 2.1% of cases in Sweden

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#825]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/4a468adb-e837-4aea-8881-c80bc4177a98)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43e49_67b9f0.json?c=gt-S_554&label=id:node_7025026
First Seq: 2023-07-05
Most Recent: 2023-09-04
Gisaid Query: G23224T, A4364G, G21761T or (A4364G,G23224T)

EPI_ISL_18221141 EPI_ISL_18010404 England/CLIMB-CM7YF69G/2023 EPI_ISL_18221155 EPI_ISL_18098555 EPI_ISL_18214173 EPI_ISL_18214204 EPI_ISL_18221744 EPI_ISL_18221750 EPI_ISL_18248333 EPI_ISL_18215059 EPI_ISL_18258620 EPI_ISL_18258619 EPI_ISL_18258623 EPI_ISL_18258622 EPI_ISL_18258625 EPI_ISL_18258624 EPI_ISL_18258626 EPI_ISL_18258628 EPI_ISL_18258630 EPI_ISL_18258629 EPI_ISL_18258631 EPI_ISL_18258621 EPI_ISL_18258627 EPI_ISL_18258617 EPI_ISL_18258618

**Comment by FedeGueli** [comment]
The Us airport sample is from a traveller coming from Italy

**Comment by FedeGueli** [comment]
it seems fast.

**Comment by FedeGueli** [comment]
one sample only in october also prevalene in Sweden went down to 0,%

**Comment by FedeGueli** [comment]
Thank you
