### ISSUE TITLE
EG.6.1 with S:V705I (71 seqs, mainly in Israel, 10 countries), a singlet with further S:L455F and S:S494P

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#826]
**Defining Mutations:** **EG.6.1** > `C18570T` > `G23675A(S:V705I)`
**Query:** `C1684T, C18570T, G23675A`  or "C18570T, G23675A ,T27346C,C17766T,C1684T" (edited)
**Earliest seq:** 2023-06-21 (`EPI_ISL_17881223`, Vienna, Austria)
**Latest seq:** 2023-09-01 (`EPI_ISL_18246928`, Israel)
**Sampled Countries:** Israel (30), USA (4: NJ/3; CA/1), Austria (1), Romania (1), Spain (1), Sweden (1), UK (1: EN)

<details><summary>Genomes: </summary>

`EPI_ISL_17881223, EPI_ISL_18012493, EPI_ISL_18012553, EPI_ISL_18012571, EPI_ISL_18062670, EPI_ISL_18096812, EPI_ISL_18096882, EPI_ISL_18099933, EPI_ISL_18104599, EPI_ISL_18115872, EPI_ISL_18142615, EPI_ISL_18162893, EPI_ISL_18213446, EPI_ISL_18213482, EPI_ISL_18213494, EPI_ISL_18213509, EPI_ISL_18213519, EPI_ISL_18213522, EPI_ISL_18215380, EPI_ISL_18215489, EPI_ISL_18215493, EPI_ISL_18215506, EPI_ISL_18215519, EPI_ISL_18215523-18215524, EPI_ISL_18215535, EPI_ISL_18215542, EPI_ISL_18226787, EPI_ISL_18234037, EPI_ISL_18246918, EPI_ISL_18246928, EPI_ISL_18246937, EPI_ISL_18246943, EPI_ISL_18246978, EPI_ISL_18254738, EPI_ISL_18255326, EPI_ISL_18255377, EPI_ISL_18266240, EPI_ISL_18270125`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_15a94_6ae660.json?f_userOrOld=uploaded%20sample&label=id:node_7016264
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5c988ddb-dc1a-41c6-bef7-bd7643f26df1)

**Trivia:**

- `S:V705I` is much less popolar than mutations on adjacent codons (Like 701V, 703I, 704L, 706V etc), only sampled about 900 times during the whole pandemic, on par with another mutations on same codon 705F

**Comment by FedeGueli** [comment]
Thank you added a more precise query even if those crazy tunisian samples are hard to disappear.

**Comment by FedeGueli** [comment]
adding a tracker : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C18570T%2CG23675A%2CT27346C%2CC17766T%2CC1684T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated EG.6.1.2 via https://github.com/cov-lineages/pango-designation/commit/4f9712c41470021e362d8b8f2997465bdb80675a
