### ISSUE TITLE
XBB.1.9.1 and UShER misplacement featuring S:T478R with a Georgian sublineage of ORF1b:A1377V/nsp13_A454V (113 seqs, 8 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#828]
**Defining Mutations:** **XBB.1.9.1** > `C22995G(S:T478R)` > `C17597T(ORF1b:A1377V)`
**Query:** `G5720A, C11956T, C17597T, C22995G, -C4345T`
**Earliest seq:** 2023-04-03 (`EPI_ISL_18042884`, Greece)
**Latest seq:** 2023-09-05 (`EPI_ISL_18263886`, Georgia)
**Sampled Countries:** Georgia (102), Greece (4), France (2), Israel (2), China (1: SH), Slovenia (1), Sweden (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17850012, EPI_ISL_17876313, EPI_ISL_17876324, EPI_ISL_17876327, EPI_ISL_17876329, EPI_ISL_17885323, EPI_ISL_17885329, EPI_ISL_17885334, EPI_ISL_17885345-17885347, EPI_ISL_17885355, EPI_ISL_17885362, EPI_ISL_17885381, EPI_ISL_18042884, EPI_ISL_18072154, EPI_ISL_18072156, EPI_ISL_18072168, EPI_ISL_18072172, EPI_ISL_18072175, EPI_ISL_18072177, EPI_ISL_18072180-18072184, EPI_ISL_18072187-18072193, EPI_ISL_18072195, EPI_ISL_18096165, EPI_ISL_18096199, EPI_ISL_18096297, EPI_ISL_18161218, EPI_ISL_18208424, EPI_ISL_18215477, EPI_ISL_18246917, EPI_ISL_18249805, EPI_ISL_18258751, EPI_ISL_18263771-18263782, EPI_ISL_18263784-18263787, EPI_ISL_18263790-18263791, EPI_ISL_18263793-18263798, EPI_ISL_18263800-18263801, EPI_ISL_18263807, EPI_ISL_18263809, EPI_ISL_18263816-18263817, EPI_ISL_18263819, EPI_ISL_18263823, EPI_ISL_18263825, EPI_ISL_18263827-18263830, EPI_ISL_18263833, EPI_ISL_18263835-18263838, EPI_ISL_18263841-18263843, EPI_ISL_18263845, EPI_ISL_18263847-18263850, EPI_ISL_18263853-18263858, EPI_ISL_18263861-18263862, EPI_ISL_18263864-18263867, EPI_ISL_18263869-18263871, EPI_ISL_18263875-18263878, EPI_ISL_18263886`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ad68_6d8da0.json?f_userOrOld=uploaded%20sample&label=id:node_6931616
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ec1bcc42-23c4-403b-bea8-485d77fbcde8)

**Trivia:**
- This branch seems to be split into 3 clusters of the tree, the major one is placed under `XBB.1.9.1 > S:T478R`, for some reason right now UShER places both XBB.1.9.1 and XBB.1.9.2 under `C11956T` (the latter via a T11956C_reversion), and the whole XBB.1.9.7 seems placed under `XBB.1.9.1 > S:T478R` as well, it could be served as a dump for all undesignated XBB.1.9* with `S:T478R` and `S:F486P`, the issue was ealier submitted at yatisht/usher#350

- Misplacement of `XBB.1.9.7` under `XBB.1.9.1 > S:T478R`
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/82595669-b502-463c-b15a-ba81a3c7b504)

- At that time that wasn't a big problem, but after a recent batch of Georgian samples, [it represents the dominant lineage out there](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AA1377V%2CS%3AT478R) 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b8b160e2-0a53-4a54-8037-49dd191ef875)

- There seems to be a `XBB.1.9.1 > C17597T(ORF1b:A1377V)` branch too, there's a proportion of this lineage placed under it too, follows `XBB.1.9.1 > C17597T(ORF1b:A1377V)` > `C21077T(ORF1b:T2537I)` > `C1929T(ORF1a:A555V), G8017T, C20178T, C29585T(ORF10:P10S)` > `C22995G(S:T478R), C27737T(ORF7a:T115I)`, where most Greek seqs are located.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_ad68_6d8da0.json?c=gt-nuc_21077,22995&gmax=23995&gmin=20077&label=id:node_7056247
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/86bd04bb-9dc4-4792-a3e7-0cde1a50a50e)

- The last proportion of this branch is located under an end-of-ORF1ab, probably-TRS-related series of mutations, that we have seen in many lineages, follows `XBB.1.9.1 > G21305A(ORF1b:R2613H/nsp16_R216H) > C21304A(ORF1b:R2613N/nsp16_R216N) > C21302T(ORF1b:P2612L/nsp16_P215L)` > `C14649T, A17013T, C17597T(ORF1b:A1377V), C18086T(ORF1b:T1540I), C22995G(S:T478R)`, only small numbers so it probably won't matter.

**Comment by FedeGueli** [comment]
The fact is even harder to fix cause there is a big XBB.1.9.1 + orf1b:A1377V sublineage (C17597T) undesignated with 333 sequences : 
![Schermata 2023-09-18 alle 11 18 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9fc8472b-a68d-4650-b980-c0577c2ebac1)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2fc27_814fc0.json?c=gt-S_478&f_userOrOld=uploaded%20sample&label=id:node_7056025

and as highlighted in the tree a small part of it got 478R too.

cc @angiehinrichs could you help here? ( it is the sam XBB.1.9.7 thing i highlighted you in another issue)

**Comment by AngieHinrichs** [comment]
I think I can get the A22995G > C17597T branch moved to C17597T, we'll find out in a couple days.
