### ISSUE TITLE
JG.3+Orf1a:S2556L,Orf3a:L140F,S:T307I(52 seqs, 9 countries )

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#829]
This is another EG.5.1--Flip--307 branch so deserves attention. Especially considering JG.3 is the fastest among all designated/undesignated lineages including BA.2.86 now.

JG.3+C7932T,C25810T(Orf1a:S2556L,Orf3a:L140F)+S:T307I(C22482T)

GISAID query: C7932T,C25810T,C22482T

No. of seq: 17(Denmark 7 Romania 1 USA 1 Austria 1 Germany 2 UK 5)

First: EPI_ISL_18210634, Denmark, 2023-8-21
Latest: EPI_ISL_18268898, Romania, 2023-9-12

usher and image copied from @FedeGueli. 4 hrs ago it was only 14.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3bc0f_6ca290.json?label=id:node_6988676)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/91998389-4907-4b20-9224-5a75720df2a2)

**Comment by FedeGueli** [comment]
Wow it is growing really fast. 

at 50 seqs propose it please-

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C7932T%2CC25810T%2CC22482T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@aviczhl2 i see already 53 sequences on usher please propose it:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice11_genome_test_21e4b_148160.json?c=userOrOld&label=id:node_6983031
![Schermata 2023-09-25 alle 13 29 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/6bd51ef7-8c46-4002-9b41-27f2f9206b66)

**Comment by aviczhl2** [comment]
> @aviczhl2 i see already 53 sequences on usher please propose it: https://nextstrain.org/fetch/genome-

A lot of the 53 are duplicates (CLIMB/Genbank duplicate I guess), the actual number is 41.

**Comment by FedeGueli** [comment]
you re right But ok propose it the same

**Comment by FedeGueli** [comment]
44 now propose it

**Comment by aviczhl2** [comment]
45 and Canada. Wait for 50. (Likely in 1 or 2 days)

**Comment by FedeGueli** [comment]
> 45 and Canada. Wait for 50. (Likely in 1 or 2 days)

Or hours ;)

**Comment by aviczhl2** [comment]
47, Sweden

**Comment by FedeGueli** [comment]
48, Greece

**Comment by FedeGueli** [comment]
Designated JG.3.1 via https://github.com/cov-lineages/pango-designation/commit/325315cebd6f5b8a6f49ea0e79d0cb057603b6ef
