### ISSUE TITLE
BA.2.86.1 sublineage with S:N477D (2 seqs in England, UK)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#833]
Defining mutations:
BA.2.86.1>T21610C>A22991G (S:N477D)

GISAID query: A6183G, C12815T, A22991G
Earliest seq: 2023-09-04 (England, UK- EPI_ISL_18262768)
Most recent seq: 2023-09-06 (England, UK-EPI_ISL_18273644)
Countries detected: UK (2)

Usher Tree:
<img width="578" alt="屏幕截图 2023-09-19 002818" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/d04d7da6-bf02-40a4-9c2d-47e76ee8da52">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_a06c_8729a0.json?c=gt-S_477

since S:S477N (nuc G22992A) emerged in BA.1 sublineage, it is stable in almost Omicron lineages (incluidng XBB*). Now we can track whether the 2-nuc mutations S:S477D will develop. 

Genomes:
EPI_ISL_18262768, EPI_ISL_18273644

**Comment by arodzh-sudo** [comment]
> GISAID query: A6183G, C12815T, A22991G Earliest seq: 2023-09-04 (England, UK- EPI_ISL_18262768) 
> Most recent seq: 2023-09-06 (**Puerto Rico**, USA, EPI_ISL_18273644) Countries detected: UK (2)
> Genomes: EPI_ISL_18262768, EPI_ISL_18273644

Puerto Rico is a typo, the accession ID corresponds to a UK sample.

**Comment by HynnSpylor** [comment]
Thx @arodzh-sudo it is my fault

**Comment by FedeGueli** [comment]
No new seq closing for now. ping me if something changes
