### ISSUE TITLE
Saltation XBB.1.5.32 with S:S31F, N148D, R190S, G257S, K440R S490P, A570V  and a double PLPro mutation- 3 sequences ( Illinois, NY) 

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#834]
Came up high in ACE2 binding score, due to 403K

Seems to be XBB.1.5.32 that has picked up some 11 Spike mutations (not sure about the reversions) - also has the 69/70del

<img width="1889" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/ba83d27d-191c-494f-9eb0-9207b9e8d158">

Baseline surveillance from 20yo female. Looks like a chronic spillover

Strain: hCoV-19/USA/NY-CDC-QDX84735142/2023
EPI_ISL: EPI_ISL_18276415

Slight convergence with BA.2.86:
- 69/70 deletion
- P1143L
- A570V
- R403K

**_EDITED ON October 22_** (credits to @Sinickle for pointing this):

Mutations shared by all thre sequences  : 
Orf1a:T1638I (PLPro_T75I)
Orf1a: I1714V (PLPro_I151V)
Spike:
S31F, N148D,R190S, G257S, K440R
S490P, A570V
ORF3a:H182Y
M:I82V
ORF8 :I74L

Query : C5178T, A5405G, C16848T (**_NEW_**) 
finds 3 : EPI_ISL_18276415, EPI_ISL_18359229, EPI_ISL_18414808,

Tree:
 https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3f7c0_4bd990.json?label=id:node_3568596
![Schermata 2023-10-22 alle 08 17 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/c78015fb-57e3-435d-9823-e84b029961cb)

**Comment by ryhisner** [comment]
Two interesting reversions here: S:I19T reestablishes the N17 glycan, which was lost with T19I, and S:S446G is a common reversion in BA.1 chronic-infection sequences. 

ORF1a:T1638I is the single most common non-spike mutation I see in chronic sequences. It's a change to the kind of hydrophobic residue SARS-CoV-1 has at that site (L), and which has been shown to increase the ability of the papain-like protease (PLpro) to cleave K48-linked ubiquitin chains. ORF1a:K1795Q, the 2nd-most common non-spike mutation in chronic sequences, has the same effect. 

<img width="1377" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ff7cb116-d9d3-412c-85ac-af6a1d5f3678">

P1143S/L seems to be increasingly common in these saltation variants. I know Jesse Bloom's lab has found mutations at this site to be extremely successful in cell culture experiments. P1162S/L is another fairly common one. S2 is pretty much a complete mystery at this point, so I don't think there's much hope of deciphering what effect these mutations have.

**Comment by krosa1910** [comment]
Ryan is such a genius, that I don't have much to say regarding this variant besides what he already concluded. I do know from Cao's research that K440R is providing medium-level escape, and since it is not a reversion probably it does not lose escape to older infection.
![FvNzg51aMAE0KFl](https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/a03005e7-7173-4fbb-8546-3f13e7a77c90)

**Comment by ryhisner** [comment]
Forgot to mention that S:R190S, which was in Gamma, also adds a glycan. So like BA.2.86, this one adds two glycans, though these are both fairly early in the NTD (N17, N188), whereas BA.2.86's glycans are later in the NTD & in the RBD (N245, N354). The N354 glycan seems to come at a pretty steep cost in terms of infectivity though.

**Comment by FedeGueli** [comment]
I ve added this specific query: T13339A,C16848T

**Comment by corneliusroemer** [comment]
Baseline surveillance is what makes me think this is not a chronic but community circulation, but I might be wrong. Speculation doesn't really matter, we will either see more of this or we won't. If we don't it doesn't matter.

**Comment by FedeGueli** [comment]
> Baseline surveillance is what makes me think this is not a chronic but community circulation, but I might be wrong. Speculation doesn't really matter, we will either see more of this or we won't. If we don't it doesn't matter.

Yes for sure thank you. it was for adding or not the single chronic infected patient label or not ;)

**Comment by ryhisner** [comment]
> Baseline surveillance is what makes me think this is not a chronic but community circulation, but I might be wrong. Speculation doesn't really matter, we will either see more of this or we won't. If we don't it doesn't matter.

I'm not sure if labels like baseline surveillance, random surveillance, or sentinel surveillance can ever really be trusted. All Canadian sequences say random surveillance, yet we know a lot of them are targeted at nursing home outbreaks. I see this with sequences from other countries as well. Sometimes repeated sequences that are obviously from the same patient will be labeled as random/baseline/sentinel surveillance.

**Comment by FedeGueli** [comment]
No new sample of this one closing it for now

**Comment by Sinickle** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/5f062e1f-3ad7-48b3-981b-edfa3bba2117)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8fd8_2ccf90.json

It's actually alive and spreading.

**Comment by FedeGueli** [comment]
Thx @Sinickle

**Comment by FedeGueli** [comment]
@angiehinrichs these two may be excluded by Usher:EPI_ISL_18359229, EPI_ISL_18414808

**Comment by FedeGueli** [comment]
I have re arranged the proposal and the headline , it has 7 shared spike mutations. 
and i have assignes to @ryhisner cause it has also a double PLpro mutation.
@Sinickle you are assigned too cause you spotted the fact it was spreading further.

**Comment by FedeGueli** [comment]
new query : C5178T, A5405G, C16848T

**Comment by FedeGueli** [comment]
Still just three closing it.
