### ISSUE TITLE
FU.2 with ORF1b:F2309L (nsp15_F258L, ORF8:A65V, ORF1a:L349F (nsp2_L169F) and S:E554K (206 seqs, mainly in Mexico and USA, 10 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#835]
**Defining Mutations:** **FU.2** > `C26750T` > `T20392C(ORF1b:F2309L)` > `T826C` > _`C28087T(ORF8:A65V)`_ > `G1312T(ORF1a:L349F), G23222A(S:E554K)`
**Query:** `T826C, G1312T, G23222A`
**Earliest seq:** 2023-07-03 (`EPI_ISL_18131853`, Nuevo León, Mexico)
**Latest seq:** 2023-09-02 (`EPI_ISL_18268315`, Shanghai Customs, China, with travel history to: Japan)
**Sampled Countries:** USA (35: TX/16; CA/8; CO/6; AZ/1; HI/1; IA/1; MA/1; NE/1), Mexico (11: NLE/8; CMX/1; COA/1; TAB/1), Canada (2: BC; QC), Austria (1), China (1: ex. Japan), Spain (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18114132, EPI_ISL_18119763, EPI_ISL_18121227, EPI_ISL_18121615, EPI_ISL_18131847, EPI_ISL_18131853-18131854, EPI_ISL_18131863, EPI_ISL_18131996, EPI_ISL_18134775, EPI_ISL_18137414, EPI_ISL_18163795, EPI_ISL_18163810, EPI_ISL_18163833, EPI_ISL_18163835, EPI_ISL_18177793, EPI_ISL_18210474, EPI_ISL_18213011, EPI_ISL_18222464, EPI_ISL_18223143, EPI_ISL_18223611, EPI_ISL_18223831, EPI_ISL_18223868, EPI_ISL_18223878, EPI_ISL_18224028, EPI_ISL_18224068, EPI_ISL_18225082, EPI_ISL_18225457, EPI_ISL_18229870, EPI_ISL_18237333, EPI_ISL_18240145, EPI_ISL_18247125, EPI_ISL_18252404, EPI_ISL_18253965, EPI_ISL_18253999-18254000, EPI_ISL_18254023, EPI_ISL_18254034, EPI_ISL_18264174, EPI_ISL_18264811, EPI_ISL_18265938, EPI_ISL_18267587, EPI_ISL_18267656, EPI_ISL_18268315, EPI_ISL_18276309, EPI_ISL_18276403, EPI_ISL_18279589, EPI_ISL_18279600, EPI_ISL_18279692-18279693, EPI_ISL_18279735`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_39d36_94f870.json?label=id:node_6890398

view from FU.2 polytomy
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/9f55772e-20cf-4615-bdb7-67890b6f5269)

details
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e8c9511c-cf84-45b9-bb9c-b8c116fefa29)

**Trivia:**
- `C26750T` seems to be the largest FU.2 branch by now, and it has many occurrence of `ORF8:A65V/C28087T` if compared to designated FU.2.1

<details><summary>Comparison of designated FU.2.1 and undesignated C26750T branch, with ORF8_65 genotype filter</summary>

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/43154810-d2cc-4e0a-9aa7-d70d6bd7a2fe)</details>

- `T20392C(ORF1b:F2309L) > T826C` is the largest sub-branch of `FU.2.1 > C26750T`, it already has some interesting sub-lineages, such as `S:F456L`, `S:A845S > S:A668S` etc.

**Comment by FedeGueli** [comment]
It is doubling under current leading lineages no chance vs HK.3 but still not slow at all:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T826C%2CG1312T%2CG23222A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
re Orf8:A65V has been already messy in the past (BA.2) . @angiehinrichs could you take  a look it seems it popped up independently 3 times in the same branch, although weird i didnt find a simply way to put them together cause they are divided by multiple sequences and different mutations. Thank you.

**Comment by AngieHinrichs** [comment]
Yeah, there are several occurrences and a lot of scattered reversions of C28087T (ORF8:A65V) in the branch FU.2 > C26750T,  here's a screenshot from taxonium coloring by that base (orange = C, green = T):
<img width="464" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/186983/56744ddb-f1ef-48e7-b93e-baa0565a47e8">
I will have to take a closer look later -- could be Ns and/or some kind of systematic error (indel? false reversions?).  28087 kinda rings a bell for flakiness.

**Comment by FedeGueli** [comment]
please ping me at 100.

**Comment by FedeGueli** [comment]
Thank you @NkRMnZr  i m nt convinced it could compete lets track it for a while more: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T826C%2CG1312T%2CG23222A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Only 4 samples from october lets wait the end of the month my impression for all these lineages their era is done.

**Comment by FedeGueli** [comment]
Lets wait for more Mexican samples before closing it.

**Comment by FedeGueli** [comment]
No future for it : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=T826C%2CG1312T%2CG23222A&nextcladePangoLineage1=JN.1*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
It is still circualting, likely at higher level in Mexico. Please propose although i dont think it will be in the fight with JN.1

**Comment by FedeGueli** [comment]
lets wait a bit  before proposing.

**Comment by FedeGueli** [comment]
Around 5% in mexico but still just samples from october

**Comment by FedeGueli** [comment]
Still better letting @corneliusroemer to know about it propose it and then we will see.

**Comment by FedeGueli** [comment]
> Still better letting @corneliusroemer to know about it propose it and then we will see.

Pls Propose this one.

**Comment by FedeGueli** [comment]
Thank you
