### ISSUE TITLE
XBB.1.9.1 with multiple ORF1ab aa mutations plus ORF3a:D27H, S:D80H, S:T478R and S:Q613H (23 seqs, 7 countries, 20% prevalence in Morocco)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#836]
**Defining Mutations:** XBB.1.9.1 > `G12769T, G15438T(ORF1b:M657I/nsp12_M666I)` > _`C28236T(ORF8:R115C)`_ > `C882T(ORF1a:A206V/nsp2_A26V)` > `G25471C(ORF3a:D27H)` > `C16575T, G21800C(S:D80H)` > `G2265A(ORF1a:C667Y/nsp2_C487Y), A3417G(ORF1a:K1051R/nsp3_K233R), C22995G(S:T478R), G23401T(S:Q613H)`
**Query:** `C882T, G21800C, G23401T`
**Earliest seq:** 2023-05-18 (`EPI_ISL_17982448`, Casablanca, Morocco)
**Latest seq:** 2023-09-07 (`EPI_ISL_18281683`, Scotland, UK)
**Sampled Countries:** USA (6: MA/2; CA/1, ME/1; NY/1; UT/1), Canada (5: ON/3; QC/2), Morocco (4), France (3), UK (2: EN; SC), Luxembourg (1), Switzerland (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17982448, EPI_ISL_18104108, EPI_ISL_18124437, EPI_ISL_18151239, EPI_ISL_18157411, EPI_ISL_18157493, EPI_ISL_18162623, EPI_ISL_18215828, EPI_ISL_18220526, EPI_ISL_18221626, EPI_ISL_18224391, EPI_ISL_18229409, EPI_ISL_18244941, EPI_ISL_18252315, EPI_ISL_18267376, EPI_ISL_18270987, EPI_ISL_18273598, EPI_ISL_18276048, EPI_ISL_18279408, EPI_ISL_18281683, EPI_ISL_18281816-18281817`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_430c1_9a5ea0.json?f_userOrOld=uploaded%20sample&label=id:node_6949080
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a241cfb6-5d9f-42fc-8fae-4776491b8b12)

**Trivia:**
- There are many variations found on `spike_80`, eg. _D80Y_, _D80G_, even _D80A_ (Beta/B.1.351), but `S:D80H` may be the rare one, only sampled about 620-ish times during the whole pandemic, probably due to the rare `G>C` SNP?
- `Luxembourg/LNS1781214/2023|EPI_ISL_18220526|2023-08-22` have Ns around `spike_478`, so that's probably a dropout

**Comment by FedeGueli** [comment]
I have the feeling that 478+613 is trending up as growth advantage.
I anectodically noticed that 613H seems going far better when a set mutation is proximal to the end , in that situation it pops up as helper to keep lineages, with that declining set of mutations, alive.

**Comment by FedeGueli** [comment]
+1

**Comment by FedeGueli** [comment]
fast: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C882T%2CG21800C%2CG23401T&analysisMode=CompareToBaseline&
