### ISSUE TITLE
BA.5.2 saltation lineage, Italy—5 sequences, ≥3 patients

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#837]
I'm not doing a big write up on this one because I want to confirm that the metadata is correct and that the three most recent sequences—uploaded today (Sept 19) but collected on June 12, July 17, and July 24—are really from separate patients. The metadata indicate separate patients, but incorrect metadata from Italy has previously indicated that long-branch sequences that were really from the same patient were from different patients. 

Campania, Italy, also has a habit of reverting to the reference genome wherever there is missing coverage, so there's some uncertainty about how much coverage these sequences have (they indicate 100%). 

**Usher Tree:**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2.6_Saltation_Lineage_Italy_Campania__5_seq.json?c=gt-nuc_4364&gmax=5364&gmin=3364&label=id:node_9841433 
<img width="1502" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6d1724a5-43a9-4cb8-b691-750b7cb4243f">

**Nucleotide Mutations from root to furthest sequence:**
C140T, C629T, T721C, G960T, T2698C, A4083G, A4359G, A4364C, C5142A, A5648C, T6562C, A6683G, G6734A, C6762T, C7162T, C8055T, G13459A, C14649T, G15451A, G21249T, T22074C, G22599C, A25338C, G25489T, G28560T, C29409T   

**Amino Acid Mutations from root to furthest two sequences:**
<img width="1331" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1ee352ce-c664-4df1-b602-a57334e923f6">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17434227, EPI_ISL_17592618, EPI_ISL_18281259, EPI_ISL_18281287, EPI_ISL_18281288
</details>

**Comment by FedeGueli** [comment]
I've aLready informed @agrimaldi

**Comment by agrimaldi93** [comment]
Hi everyone,
regarding the samples sequenced at tigem, they all have high coverage (>99.5% @ 100X).
I asked the metadata to the sample provider and actually it should be the same patient swabbed multiple times. I already asked GISAID to correct the data.
About the other sequences, I wrote to the corresponding centers that submitted them. I will update you asap

**Comment by FedeGueli** [comment]
No new sample came from this lineage/Chronic infection
