### ISSUE TITLE
HK.3+8-nuc,5-aa including S:E583Q(11 seqs, 5 countries, 1.5% Anhui)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#838]
HK.3+C3096T(Orf1a:S944L)+C4927T,G18985A,C26801T(Orf1b:V1840I)+C10789T+G6710A(Orf1a:V2149I)
+C28439T(N:L56F)+G23309C(S:E583Q)

GISAID query: G23309C,C28439T,G6710A
No. of seqs: 2(USA 1 (from Netherlands), China 1)
3 on GISAID, 1 GBW H10/20 Duplicate

EPI_ISL_18284110,18284111, USA from Netherlands, 2023-9-7 
EPI_ISL_18133879, Anhui, 2023-8

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_20ccc_a46890.json?c=gt-S_583&gmax=25384&gmin=21563&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a37f8ce6-dbf4-46e3-be09-28e0735345c1)

**Comment by FedeGueli** [comment]
No new sequence closing it for now. ping me if it re sarts growing

**Comment by FedeGueli** [comment]
11 just 3 in early october than nothing

**Comment by aviczhl2** [comment]
new countries are Poland and Japan.

**Comment by aviczhl2** [comment]
> 11 just 3 in early october than nothing

This one is 2/121 in Anhui 2023-9 seqs. Note that Anhui only uploads 16 seqs collected in October.

**Comment by FedeGueli** [comment]
> > 11 just 3 in early october than nothing
> 
> This one is 2/121 in Anhui 2023-9 seqs. Note that Anhui only uploads 16 seqs collected in October.
ok lets reopen for a while.

**Comment by FedeGueli** [comment]
no recent sample closing again.
