### ISSUE TITLE
EG.5.1.1 on C11779T branch with N:P67S, S:A684V and S:V1264L (52 seqs, 13 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#841]
**Defining Mutations:** EG.5.1.1 > `C11779T` > `C28472T(N:P67S)` > `T22654C, C23613T(S:A684V), G25352T(S:V1264L)`
**Query:** `C11779T, C23613T, C28472T`
**Earliest seq:** 2023-07-19 (`EPI_ISL_18097418`, Tokyo, Japan)
**Latest seq:** 2023-09-04 (`EPI_ISL_18280821`, Hénin-Beaumont, France)
**Sampled Countries:** UK (11: EN), Japan (5), Belgium (4), Luxembourg (3), Canada (2: AB; ON), Denmark (2), France (2), Australia (1: QLD), Israel (1), Italy (1), Netherlands (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18097418, EPI_ISL_18111981, EPI_ISL_18115866, EPI_ISL_18118922, EPI_ISL_18134861, EPI_ISL_18210174, EPI_ISL_18218219, EPI_ISL_18220539, EPI_ISL_18220593, EPI_ISL_18220687, EPI_ISL_18227139, EPI_ISL_18227146, EPI_ISL_18227149, EPI_ISL_18227666, EPI_ISL_18244230, EPI_ISL_18244483, EPI_ISL_18244485, EPI_ISL_18244488, EPI_ISL_18248291, EPI_ISL_18250236, EPI_ISL_18251133, EPI_ISL_18258879, EPI_ISL_18263932, EPI_ISL_18273782, EPI_ISL_18273898, EPI_ISL_18273904, EPI_ISL_18278614, EPI_ISL_18279160, EPI_ISL_18280010, EPI_ISL_18280044, EPI_ISL_18280402, EPI_ISL_18280783, EPI_ISL_18280821`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_426e6_a853a0.json?c=gt-S_684&gmax=25384&gmin=21563&label=id:node_6988088

view from EG.5.1.1's `C11779T` branch
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/bb7738fc-2967-4dee-b39f-770618825b52)

details
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ae0d3c53-46a0-4f33-ae7f-7145cf1df78a)

**Trivia:**
- 3 seqs from Luxembourg have Ns around `T22654C`, probably dropout
- 2 seqs from England does not appear on GISAID yet (of course not counted in query), has less than 70% coverage, may also have `G25352T/S:V1264L` dropout: `England/CLIMB-CM7YKGWD/2023|OY724913.1|2023-07-21` and `England/CLIMB-CM7YJKF8/2023|OY724948.1|2023-07-19`
- another sequence from England that also not on GISAID yet has potential `C28472T/N:P67S` dropout: `England/CLIMB-CM7YF578/2023|OY723927.1|2023-07-21`, so it is pending on the last remaining sequence `Japan/PG-551440/2023|EPI_ISL_18060252|2023-07-10` to judge whether it's a saltation or not.

**Comment by FedeGueli** [comment]
it seems faster than parental lineage.

**Comment by FedeGueli** [comment]
it seems quite fast. https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C11779T%2CC23613T%2CC28472T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Still no chance to comepte vs HK.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C11779T%2CC23613T%2CC28472T&analysisMode=CompareToBaseline&
