### ISSUE TITLE
FR.1.1 (BN.1.2.3.1.1) x EG.5.1.1* recombinant (6 seqs in Anhui and Shanghai, China-breakpoint between S:356 and S:368) 

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#842]
Description:
Recombinant of: FR.1.1 (BN.1.2.3.1.1) and EG.5.1.1* (XBB.1.9.2.5.1.1*)
Breakpoint: S:356-S:368 (nuc:22630-22663, Before = FR.1.1, After = EG.5.1.1*)
Earliest sequence: 2023-08-01 (Shanghai, China-EPI_ISL_18105656)
Most recent sequence: 2023-09-03 (Shanghai, China-EPI_ISL_18284946)
Countries circulating: China (3)
GISAID Nucleotide Query: T2372C, C21807A, C25572T, C29625T or 
( **_edited_**: T2372C, C21807A, C25572T, C29625T,-G2518A to exclude the Liaoning sample)
GISAID AA Query: Spike_P82H, Spike_K187E, Spike_F456L, Spike_F486P

Usher Tree:
![QQ截图20230920163314](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/ca0dc5c1-a885-42b8-9a3e-57daf0bc6abc)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_292e1_aab180.json?c=gt-S_456

a very clear recombinant that breakpoint is on Spike (S:S356-S:368). Seq 2 and Seq 3 may be from one patient, but Seq 1 is from different individual. It also gets a very rare Spike mutation S:P631S.
We can track it for a time.

Genomes:
EPI_ISL_18105656, EPI_ISL_18284946, EPI_ISL_18285002

Rapid AA changes picture:(**_EDITED_**)
![Schermata 2023-09-21 alle 13 05 01](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/9d32d0da-92a6-4b62-8e9d-b526c99d10c1)

**Comment by aviczhl2** [comment]
Shall be EG.5.1.1 as it has C25572T

**Comment by Over-There-Is** [comment]
Breakpoint: 22629(S:K356T)~22664(S:L368I)

Extra mutations: C1686T(Orf1a:A474V), C8782T, G8849A(Orf1a:V2862M), C14790T(Orf1a:N4060S), C21910T / T23332C, C23453T(S:P631S), C27635T(Orf7a:S81L), C28253T, A28254C(Orf8:I121L)

Shanghai/SCDC-HG0803-2915-2/2023|EPI_ISL_18105656|2023-08-01(Import from Indonesia)
Shanghai/SCDC-xh0906-10_S10/2023|EPI_ISL_18285002|2023-09-02
Shanghai/SCDC-XG09-13426/2023|EPI_ISL_18284946|2023-09-03

**Comment by krosa1910** [comment]
Have had some time discussing with HynnSpylor about this.
First, do agree that C25572T is trait of EG.5.1.1*, and could be used to determine its later parent here. Yet interestingly that is a shared defining mutation of EG.5.1.1* and all FR*. 
Second, I have attempted to use a more broad search to really investigate this potential FR.1.1 X XBB recombinant.
And this is what I did:
Gisaid Inquiry: 21807A,A22190G,C7318T,T23019C

5 seqs, including those 3 and 2 earlier sequences in another two provinces.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_29ba5_ab34b0.json?f_userOrOld=uploaded%20sample

The earliest seq from Xinjiang is the weirdest, as it somehow unlocked both S:486P and Orf8:8* and Orf9b:I5T, yet maintained the E:D72G mutation of BN.1.2*. I would consider it to be mostly a saltation , but it is mysterious at least.

Then comes the Liaoning Seq in June, it is mostly certainly another FR.1.1* X XBB recombinant, I am inclined to put a XBB.1.9.1* parent because it fits the traits.

For this branch of 3 seq in Shanghai, well, you comment.

<img width="1027" alt="Screenshot 2023-09-20 at 4 58 04 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/2db8fa4a-880b-4a5e-b556-94d693bd9257">

**Comment by Over-There-Is** [comment]
@FedeGueli K356T, P631S

**Comment by Over-There-Is** [comment]
@krosa1910 the Xinjiang sequence has Q613H, maybe related to XBB.1.42*.

**Comment by krosa1910** [comment]
> @krosa1910 the Xinjiang sequence has Q613H, maybe related to XBB.1.42*.
True, and I considered it to the the closest thing to the possible contributor of some weird mutations, but the backbone still seem pretty much FR.1.1 to me.

**Comment by FedeGueli** [comment]
> @FedeGueli K356T, P631S

Thank you

**Comment by HynnSpylor** [comment]
3 more seqs in Anhui Province, China
It has spread in Eastern China

**Comment by Over-There-Is** [comment]
Update:

Extra mutations\*:
C1686T(Orf1a:A474V), C8782T, G8849A(Orf1a:V2862M), C14790T(Orf1a:N4060S), C21910T / T23332C, C23453T(S:P631S), C27635T(Orf7a:S81L), C28253T

The Anhui Sequences have not A28254C(~Orf8:I121L~), so remove it.

Alternative query: `Spike_P82H, Spike_K356T, Spike_L368I`
Alternative query: `C1686T, T23332C`\*
\*Still not sure whether the upcoming sequence having these mutations.

**Comment by FedeGueli** [comment]
> C1686T, T23332C

Orf8:121 always problematic i wont exclude them for that.

**Comment by FedeGueli** [comment]
![Schermata 2023-09-21 alle 13 01 40](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/47015484-fd89-4b30-a16e-4ddf2c1cd353)
this the updated tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e322_c22460.json?label=id:node_10905287

**Comment by FedeGueli** [comment]
i have added T2372C, C21807A, C25572T, C29625T,-G2518A  a query to exclude the Liaoning sample.

**Comment by FedeGueli** [comment]
I was looking at S:P631S is predicted to be very good for binding:
by Bloom and Dadomaite
![Schermata 2023-09-21 alle 13 06 26](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/98860a82-97b8-4208-b350-2b0def3be25b)

**Comment by FedeGueli** [comment]
And guys this is interesting and "amazing" from an evolutionary point of view:
https://cov-spectrum.org/explore/World/AllSamples/from%3D2022-01-03%26to%3D2022-10-01/variants?nextcladePangoLineage=BA.2.75*&nextcladePangoLineage1=BJ.1*&nextcladePangoLineage2=XBB*&analysisMode=CompareEquals&
![Schermata 2023-09-21 alle 13 23 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/648f702f-1be1-4fab-9562-84c1a125e7a3)

It is like BA.2.75 took back its own part it has lost in XBB (except from 368-445) with in addition on both sides very good mutations  
Isn't it crazy?

**Comment by krosa1910** [comment]
What Fed says is definitely a genuine idea, I propose this graph to better understand what it could be looked like as a "insert stuff" BA.2.75 saltation.
<img width="974" alt="BD6684A6E8ED547A4F5D8802BB2D11F6" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/97a887c5-d3f6-4260-bafe-e76c6e6c94b7">
To summarize, from the FR.1.1* part it gained Orf1a:L293F=nsp2_L113F S: P82H, S:K187E S:R346T, S:K356T.
From the XBB-related saltations it gained S:L368I S:V445P, S:F456L, S:F486P, S:F490S, Orf8:G8*, Orf9b:I5T
From its own mutations it accumulated Orf1a:A474V=nsp2_A294V, Orf1a:V2862M=nsp4_V99M, Orf1a:A3901T=nsp7_A42T, S:P631S, Orf7a:S81L
Surprisingly, I don't find evidence for it inheriting anything more than the defining mutations of FR.1.1* or EG.5.1.1* parent. So its five extra mutations (plus a bunch of syn ones) are mostly or even entirely from its own? The fact that FR.1.1* and EG.5.1.1* aren't so old themselves mean that the saltations must be pretty fast.

**Comment by Over-There-Is** [comment]
\*Orf1a:A3901T is not obtained by all sequences.

**Comment by aviczhl2** [comment]
It doesn't take the key component of FR.1, the new Orf7b.

**Comment by FedeGueli** [comment]
XCN
