### ISSUE TITLE
FE.1.1.3 saltation singlet with S:K356T, R403K, Y453F, S490P, K537E, A688V, K1045R(Mianyang, Sichuan, China)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#844]
Sichuan/MYCDC-XGCX323/2023|EPI_ISL_18284777|2023-08-30
FE.1.1.3> C2040T(Orf1a:T592I), C2836T, C7843T, C7985A(Orf1a:Q2574K), A22629C(S:K356T), G22770A(S:R403K), A22920T(S:Y453F), T23030C(S:S490P), A23171G(S:K537E), C23625T(S:A688V), A24696G(S:K1045R), G26538A(M:G6S)
@FedeGueli

**Comment by Over-There-Is** [comment]
It seems all the FE.1.1.3 sequences should have G28371T(N:G30V), which is masked by Usher.
39% of FE.1.1 or 25% of FE.1.1* sequences have G28371T(N:G30V).
On GISAID, 73 FE.1.1.3 samples have G28371T(N:G30V), and 29 have not. 27 of these sequences have N around 28362~28370, and 1 is a potential recombinant with XBB.1.16.

**Comment by Over-There-Is** [comment]
None of FE.1.1.1*/2/4 have G28371T. It's believable that FE.1.1.3 is on the FE.1.1> G28371T branch.

**Comment by FedeGueli** [comment]
> None of FE.1.1.1*/2/4 have G28371T. It's believable that FE.1.1.3 is on the FE.1.1> G28371T branch. FE.1.1> G28371T(N:G30V)> A24775G

Is it silent in orf9b?

**Comment by Over-There-Is** [comment]
> > None of FE.1.1.1*/2/4 have G28371T. It's believable that FE.1.1.3 is on the FE.1.1> G28371T branch. FE.1.1> G28371T(N:G30V)> A24775G
> 
> Is it silent in orf9b?

Orf9b:V30L

**Comment by FedeGueli** [comment]
> > > None of FE.1.1.1*/2/4 have G28371T. It's believable that FE.1.1.3 is on the FE.1.1> G28371T branch. FE.1.1> G28371T(N:G30V)> A24775G
> > 
> > 
> > Is it silent in orf9b?
> 
> Orf9b:V30L

It could be the result of the deletion? @angiehinrichs

**Comment by FedeGueli** [comment]
> It seems all the FE.1.1.3 sequences should have G28371T(N:G30V), which is masked by Usher. 39% of FE.1.1 or 25% of FE.1.1* sequences have G28371T(N:G30V). On GISAID, 73 FE.1.1.3 samples have G28371T(N:G30V), and 29 have not. 27 of these sequences have N around 28362~28370, and 1 is a potential recombinant with XBB.1.16.

It should be N:G33V not? (Likely same due the deletion there) covspectrum sees it N:G33V

**Comment by Over-There-Is** [comment]
![2023-09-20 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/24aa563e-c307-44f2-a371-dc2ee300572a)
![2023-09-20 (2)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/680552ef-92eb-4a18-bea8-d9c919a5bed6)

**Comment by FedeGueli** [comment]
Ok yes N:S33V = N:G30V due the deletion

**Comment by FedeGueli** [comment]
> del28364_28372

Yeah the deletion is in all omicron.

**Comment by Over-There-Is** [comment]
> > del28364_28372
> 
> Yeah the deletion is in all omicron.

It is analyzed as del28362-28370 by Nextclade, and analyzed as del28363-28371 by Usher.
And Gisaid analyze it as A28363T and del28364_28372. But if there is a G28371T, it will be analyzed as del28361_28369, A28370G and G28371T.

**Comment by FedeGueli** [comment]
> > > del28364_28372
> > 
> > 
> > Yeah the deletion is in all omicron.
> 
> It is analyzed as del28362-28370 by Nextclade, and analyzed as del28363-28371 by Usher. And Gisaid analyze it as A28363T and del28364_28372. But if there is a G28371T, it will be analyzed as del28361_28369, A28370G and G28371T.

to me likely not real. we already saw that, i remember @Sinickle did a bit analysis one year ago.

cc @corneliusroemer what do you think.

**Comment by Over-There-Is** [comment]
There are 172 sequences with G28371T in China collected since 2023-06.
3 are BF.7.14*, 2 are EG.5.1.1, and each one for FY.3.1, XBB.1.16 and XBB.1.16.1. And the rest are all FE.1.1 or FE.1.1.3.
And there are 786 sequences with dropout, and 12531 sequences with neither G28371T nor dropout.
So, I do not think G28371T of FE.1.1 is artefactual.

**Comment by FedeGueli** [comment]
> There are 172 sequences with G28371T in China collected since 2023-06. 3 are BF.7.14*, 2 are EG.5.1.1, and each one for FY.3.1, XBB.1.16 and XBB.1.16.1. And the rest are all FE.1.1 or FE.1.1.3. And there are 786 sequences with dropout, and 12531 sequences with neither G28371T nor dropout. So, I do not think G28371T of FE.1.1 is artefactual.

it could be.

**Comment by FedeGueli** [comment]
No new sample of this closing for now
