### ISSUE TITLE
Potential CH.1.1 x XBB recombinant, or contamination/coinfection [1x South Africa]

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#845]
Noticed a weird South African sequence: `hCoV-19/South_Africa/CERI-KRISP-K058084/2023|EPI_ISL_18284171|2023-09-04`

This is the Spike:

S:A27S | S:V36I | S:V83A | S:H146Q | S:K147E | S:W152R
S:F157L | S:G181E | S:Q183E | S:I210V | S:G257S | S:D339H
S:R346T | S:L368I | S:R403K | S:K444T | S:V445P | S:G446S
S:L452R | S:N460K | S:K478R | S:F486P | S:F490S | S:R493Q
S:G1219V

It's a CH.1.1 on C193T, C21811T branch, with additional Spike mutations: V83A, H146Q, G181E, Q183E, L368I, V445P, K478R, S486P, F490S, G1219V

It's weird that it doesn't have any reversion, only additional mutations gained from some XBB, this means there would have to be many breakpoints.

<img width="956" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/d8f6a01b-15fd-43ca-9610-9369a8b8372e">

potential query: C4633T, T9262C,T16342C (EDITED)

tree: (edited)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4ec8f_c31e80.json?f_userOrOld=uploaded%20sample

![Schermata 2023-09-21 alle 14 09 27](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d3f93e06-a498-4d0a-a17a-9299dd93b61a)

**Comment by aviczhl2** [comment]
del509_523/Orf1a:82-86del

**Comment by corneliusroemer** [comment]
I've designated the parent branch of this sequence as CH.1.1.31 > JP.1 

(this looks rather like contamination to me, as there's no clear breakpoint so I'll close this for now)

But the parent branch is interesting as a South African CH.1.1

**Comment by corneliusroemer** [comment]
Likely artefact
