### ISSUE TITLE
 EG.5.1.3/XCH.1 recombinant that may be removed by usher(8 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#846]
@AngieHinrichs, there's an Australian EG.5.1.3/XCH.1 recomb that may be removed by usher by reversions, please put it on list. 

EPI_ISL_18285932

XBB.1.5+C1889T,G2144A,C2334T, G5720A,T6649C,C9693T,T10254C,C12789T, A16878T, A18492G，G18703T,C22624T,G22927T,T22928C,C23280T, C23673T,G25947C, C26907T,C27741T,T28297C, C28657T

Orf1a:R542C,V627I,A690V,G1819S,A3143V,L3330S,T4175I
Orf1b:D1746Y
S:L455F,F456L,T573I,S704L
Orf3a:Q185H
Orf8:P38S
Orf9b:I5T

C1889T, C2334T, G5720A,C9693T, C12789T, A16878T, A18492G from EG.5.1.3
G2144A,T6649C,T10254C,G18703T from where? seems private.  Is it related with XBB.1.16?

C22624T,G22927T,T22928C,C23280T, C23673T,G25947C, C26907T,C27741T,T28297C, C28657T from XCH.1

Try to make a query for this: G2144A,G18703T,C28657T

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1e3b6ba0-9eb9-449b-808b-102c3059c03c)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31dc_b64320.json?f_userOrOld=uploaded%20sample&label=id:node_10899994)

**Comment by AngieHinrichs** [comment]
Added to list.  It should appear in 2023-09-21 tree.  Thanks!

**Comment by aviczhl2** [comment]
@AngieHinrichs @FedeGueli  There's one more of this. EPI_ISL_18324408

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3863206a-5a97-4a5e-abea-d27bf0d4ef0a)

**Comment by aviczhl2** [comment]
There is a 3rd one EPI_ISL_18324447 @FedeGueli @AngieHinrichs @corneliusroemer

**Comment by FedeGueli** [comment]
Sorry i was thinking it was just an usher issue.
So this is Flip and has 3 lineages as parental, right?

**Comment by aviczhl2** [comment]
> Sorry i was thinking it was just an usher issue. So this is Flip and has 3 lineages as parental, right?

Yeah, Flip+573+704+Orf9b:I5T, following XCH.1 but has the Orf1ab part replaced to something new. (EG.5.1.3+some private?)

**Comment by AngieHinrichs** [comment]
Added, thanks, should be in 2023-10-03.

**Comment by aviczhl2** [comment]
There is a 4th one @AngieHinrichs  EPI_ISL_18352383

**Comment by AngieHinrichs** [comment]
Added, thanks.  (BTW 2023-10-06 run has not started yet because 2023-10-05 run is hanging!  I think it's the first time that usher-sampled has gone off into deadlock or infinite loop land like this.  @yceh I sent you a message in Slack; if you have time to look into it, that would be super helpful.]

**Comment by FedeGueli** [comment]
no recent sample . closing it , ping for @corneliusroemer

**Comment by aviczhl2** [comment]
+1 USA +1 Switzerland

**Comment by FedeGueli** [comment]
Still not very recent please reopen it if some sample come from late Nov.December.

**Comment by aviczhl2** [comment]
+1 Austria

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
Likely dying off.

**Comment by FedeGueli** [comment]
thx
