### ISSUE TITLE
FL.2.3.1(S:K356T)+S:S490P (7 seq, China, 2 provinces)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#848]
FL.2.3.1> T23030C(S:S490P)
Query: A11188G, T23030C

Earliest sequence: 07-24 Heilongjiang, China EPI_ISL_18245927
Latest sequence: 09-18 Heilongjiang, China EPI_ISL_18465150

Regions detected: Heilongjiang 6, Anhui 1

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json?label=id:node_10825430
![2023-09-21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/834f5a3d-eb86-4cd6-ad35-aefba2597e54)

Sequences: 
EPI_ISL_18245927, EPI_ISL_18246109, EPI_ISL_18246137,
EPI_ISL_18289781, EPI_ISL_18384441, EPI_ISL_18465076,
EPI_ISL_18465150

**Comment by FedeGueli** [comment]
No recent sample closing it

**Comment by Over-There-Is** [comment]
+1

**Comment by FedeGueli** [comment]
Thank you still october sample, nt being detected elsewhere i keep this closed for now thx

**Comment by FedeGueli** [comment]
saw the new samples too. happy tou keep this monitored.
