### ISSUE TITLE
GK.1.1+Orf8:Q72H+S:G946V(61 seqs, 4 countries, mainly Japan)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#849]
GK.1.1+C26735T+A23014G+G28109T(Orf8:Q72H)+C10138T+G24399T(S:G946V)

GISAID query: G24399T,C10138T,G28109T
No. of seqs:16(Japan 15 China 1)

First: EPI_ISL_18116172, Aichi,Japan, 2023-8-3
Latest: EPI_ISL_18284845,Shanghai,China, 2023-9-10

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ac75_bdf280.json?label=id:node_7279927)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2bbfd4ec-45c2-4928-afbd-c881851488a4)

**Comment by aviczhl2** [comment]
44, South Korea

**Comment by FedeGueli** [comment]
it cannot compete: https://cov-spectrum.org/explore/Japan/AllSamples/Past3M/variants?nextcladePangoLineage=Hk.3*&nucMutations1=G24399T%2CC10138T%2CG28109T&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
58, USA

**Comment by FedeGueli** [comment]
Still beyond the fastest lineage in Japan :https://cov-spectrum.org/explore/Japan/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G24399T%2CC10138T%2CG28109T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
no recent samples closing it
