### ISSUE TITLE
XBB.1.5.7 Sublineage with ORF3a:W193R, ORF3a:Q213K, ORF3a:T269M, ORF1a:T3224I, ORF1a:Q3826H, ORF1b:V464F, ORF1b:P970L, ORF1b:G1638S (17 seq, June 16)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#85]
Full credit to the eagle-eyed @FedeGueli for being the first to discover this fascinating lineage! (=just a random spot looking at samples related to philippines. thx Ryan fede)
**Description**
**Sub-lineage of:** XBB.1.5.7
**Earliest sequence:** 2023-4-16, England — EPI_ISL_17598626
**Most recent sequence:** 2023-5-11, England (not on GISAID) – England/PHEC-YYEAT63/2023|2023-05-11
**Countries circulating:** England (8), Switzerland (2), South Korea (2—travelers, detected in USA, California, Los Angeles), Philippines (1—traveler, detected in USA, California, Los Angeles)
**Number of Sequences:** 13
**GISAID AA Query:** NSP6_Q257H, NSP14_G114S, -Spike_V963stop
**GISAID Nucleotide Query:** T10531C, A20262G, G11743T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.5* & G11743T & C26029A & [3-of: C9936T, T10531C, G14857T, C16376T, G18379A, A20262G, T25969C, C26198T]
**Substitutions on top of XBB.1.5.7:**
**ORF3a:** W193R, Q213K, T269M
**ORF1a:** T3224I, Q3826H (NSP4_T461I, NSP6_Q257H)
**ORF1b:** V464F, P970L, G1638S (NSP12_V473F, NSP13_P47L, NSP14_G114S)
**Nucleotide:** C9936T, T10531C, G11743T, G14857T, C16376T, G18379A, A20262G, T25969C, C26029A, C26198T
 
**Phylogenetic Order of Mutations:** C26198T (ORF3a:T269M) **→** G14857T (ORF1b:V464F) **→** T10531C **→** C16376T (ORF1b:P970L) **→** A20262G **→** C9936T, G18379A, T25969C (ORF1a:T3224I, ORF1b:G1638S, ORF3a:W193R) **→** G11743T, C26029A (ORF1a:Q3826H, ORF3a:Q213K)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5.7_ORF3a_W193R_Q213K_T269M.json
 
<img width="1424" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/dea91680-fb51-450e-8da1-7fa315c29e0d">

**Evidence**
Three ORF3a mutations is a lot. ORF3a:Q213K is the most homoplasic ORF3a mutation of all, and ORF3a:T269M is up there as well. ORF3a:W193R is much less common. Half the sequences here register a mixed nucleotide at ORF3a:W193, and the two from Switzerland don't have it at all. Perhaps there's an issue with some technical detail of sequencing around this site, maybe something to do with primers.
 
Most intriguing here are the three travelers from Asia—two from South Korea and one from the Philippines—who were all sequenced on the same day (April 17) in the same city (Los Angeles, California, USA). The Philippines is a mystery zone due to its unique variant mix and the total lack of sequences from there in the last two months.
 
**Genomes** (three sequences from England not currently on GISAID)
<details>
<summary>Genomes</summary>
EPI_ISL_17560508, EPI_ISL_17560582, EPI_ISL_17560591, EPI_ISL_17598626, EPI_ISL_17622819, EPI_ISL_17622823, EPI_ISL_17622863, EPI_ISL_17657718, EPI_ISL_17657728, EPI_ISL_17666395
</details>

**Comment by FedeGueli** [comment]
Good you proposed this one! I noticed it too some time ago (maybe digging into Philippines related samples) but i didnt know it went on growing!

**Comment by FedeGueli** [comment]
Thx @ryhisner no need to credit me this way!

**Comment by FedeGueli** [comment]
Still 13 with  T10531C, A20262G, G11743T but i see two new uploaded from Uk.

**Comment by FedeGueli** [comment]
14 as today. one more from Switzerland

**Comment by FedeGueli** [comment]
Still 17 .
