### ISSUE TITLE
FL.1.5.1 (XBB.1.9.1.1.5.1) sublineage with S:145-146del and S:K147Q (57 seqs in 14 countries including Oman, Ukraine, Turkey)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#850]
Defining mutations:
FL1.5.1>G20060T (ORF1b:S2198I)>G28375A>G19962T>C1473T (ORF1a:), C5986T>21993-21998del (S:145-146del), A22001C (S:K147Q)

GISAID query: A22001C, T22928C, G28375A
Earliest seq: 2023-07-20 (Brunei- EPI_ISL_18100762)
Most recent seq: 2023-09-04 (Oman- EPI_ISL_18290982)
Countries detected: France (5), Oman (3), Saudi Arabia (2, detected in US International Airport), Brunei (2), Japan (1), Ireland (1)
Usher Tree: The branch is messy as Usher can't analyze the deletion branch. 
![QQ截图20230921231337](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/4d14f5fc-dad2-4017-bc5c-c3db4e95a03f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_208ab_c45d80.json?c=gt-S_147

The detail nuc and aa for S:144-147:
![QQ截图20230921231521](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/7bcb51b8-fe9d-43d6-a0ee-577e8636a5b6)

FL.1.5.1 (with S:F456L and S:K478R) is increasing recently. As almost XBB* follow the S:Y144del the 145-146del is relatively rare. We can track it for a time.

Genomes:
EPI_ISL_18070031, EPI_ISL_18070041, EPI_ISL_18094607, EPI_ISL_18094627, EPI_ISL_18100762-18100763, EPI_ISL_18124872,
EPI_ISL_18125021, EPI_ISL_18239747, EPI_ISL_18248313, EPI_ISL_18287341, EPI_ISL_18290977-18290978, EPI_ISL_18290982

**Comment by krosa1910** [comment]
Reminding me of Delta (that got deletion shortly after, in 156-157?)

**Comment by ryhisner** [comment]
I can't say for sure, but I suspect this is an artifact. For whatever reason, there are a lot of errors at 144-147. Sometimes ∆Y144 seems to disappear, other times it looks as if the deletion has expanded. I usually ignore anything that happens there unless there's a lot of other evidence that it's real, like if they all share a unique nucleotide mutation.

**Comment by FedeGueli** [comment]
@corneliusroemer do u think this is real?

still hard it will compete : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=Jn.1*&nucMutations1=A22001C%2CT22928C%2CG28375A&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Slowed down a lot closing it for now.
