### ISSUE TITLE
EG.5 + ORF1a:V274L, ORF1a:R542C, S:A701V, ORF1b:K2557R, ORF1a:T4129I (1)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#852]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/38f418e1-1dfb-4060-b20d-9540528af16c)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9df8_cf6100.json?c=gt-S_701
Sequenced in: 2023-09-06
gisaid query: T5254C, T15163C

EPI_ISL_18264343

**Comment by Fearuncle** [comment]
I'm thinking it's an EG.5.1.3 with ORF1a:V274L x FL.1.5.2 recombinant.

**Comment by Fearuncle** [comment]
but I'm not sure how to confirm or deny.

**Comment by FedeGueli** [comment]
@Fearuncle the simpliest way is to use this tool:https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=G1085T%2CC1889T%2CC12651T%2CC12970T&nucMutations1=C22570T%2CC1889T%2CG21718T%2CT22930A&nucMutations2=T23245C%2CT23005A&analysisMode=CompareEquals&
I have set your variant as first (G1085T, C1889T, C12651T,C12970T)
then EG.5.1.3 (C22570T, C1889T, G21718T, T22930A)
then FL.1.5.2 (T23245C, T23005A) 

as you can see it resembles a recombinant as you said the only thing that doenst bode well is S:A701V that seems to be between two EG.5.1.3 parts 
![Schermata 2023-09-22 alle 11 51 19](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/943885d6-bf27-41e7-b607-b5e03a438bae)

**Comment by FedeGueli** [comment]
no new sequence clsoing it
