### ISSUE TITLE
EG.5.1.1 sublineage with S:L455W and S:M740K (2 seqs in Anhui, China)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#853]
Defining mutations:
EG.5.1.1>T22926G (S:L455W), T23781A (S:M740K)
GISAID query: T22926G, T23781A
Earliest seq: 2023-08-20 (Anhui, China- EPI_ISL_18289801)
Most recent seq: 2023-08-21 (Anhui, China- EPI_ISL_18289811)
Countries detected: China (2)
Usher Tree:
![QQ截图20230922195616](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/e593ff4d-3e3d-486b-9f8a-8c2f0cefb59f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_abd3_d318e0.json?c=gt-S_455

S:Q52H+S:L455W+S:F456L has emerged in FL.20.1 lineage, it seems a convergent branch in EG.5.1*. If we only focus on site S:455, S:L455W may have higher escape potential than S:L455F (Cao et al. 2023), but when we consider the effect of S:F456L, S:L455F+S:F456L Flip seems more competitive. Moreover, the S:M740K may slightly increase the escape effect.
One seq further gets S:I692F. We can track it for a time.

![QQ截图20230922195011](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/f252865b-1461-4a38-b1e3-8ecf2bcadcae)
![QQ截图20230922194754](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/2a1a4a16-903b-4da6-a46d-e43e8b9365cd)

Genomes:
EPI_ISL_18289801, EPI_ISL_18289811

**Comment by FedeGueli** [comment]
Very good spot thank you.

**Comment by BorisUitham** [comment]
Interesting, fl.20* seemed comparetively slow to eg.5.1* even though it had the same spike, so im curious to see what the effects of different accessory mutations are.

**Comment by FedeGueli** [comment]
no new sample from this
