### ISSUE TITLE
XBC.1.3 with S:P681R(1 sequences,New Zeland)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#854]
This is another current popular XBC* subline, it did not get L452R like XBC.1.6*, but got P681R in a New Zealand sequence today, XBC* contains the NTD part of the Delta, it is possible that P681R will interact with the NTD on XBC* to achieve better results, this needs attention.
Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_33525_d93ed0.json?label=id:node_5392734
![IMG_1507](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/b717b712-6af1-45c3-8514-dc4d610d44e4)
GISAID query:Spike_L452M,Spike_P681R,M_L29F
Sequence (s):EPI_ ISL_18292554
Tips:In addition, recently, the XBC* series HW.1.1 (XBC.1.6.3.1.1) and XBC.1.3* have been sequentially measured in many countries and are growing, I think this can be paid attention to.

**Comment by FedeGueli** [comment]
No new sample here
