### ISSUE TITLE
XDE: Potential GW.5.1*/ FL.13.4 recombinant that gained ORF8:G8* and ORF9b:I5T (11 seqs, Pakistan, France, USA, Australia)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#855]
**Query:** `C7113T, G22927T, C29535T`
**Earliest seq:** 2023-09-14 (`EPI_ISL_18294822`, Islamabad)
**Latest seq:** 2023-09-17 (`EPI_ISL_18294827`, Islamabad)
**Sampled Countries:** Pakistan (4)

**Recombinant Profiles: (see at the bottom integrastion by @Over-There-Is )** 
- Placement on Phylogenetic Tree: `XBB.1.19.1` > _`C28511T(N:P80S)`_ > `C1170T(ORF1a:S302F)` > `C12473T, C12924T(ORF1a:P4220L), C22995T(S:T478I), C24034T` > `C2260T, C7113T(ORF1a:T2283I), G22927T(S:L455F), T22928C(S:F456L), G27915T(ORF8:G8*), T28297C(ORF9b:I5T)`, _`T28511C_reversion(N:S80P_reversion)`_, `C29535T`
- Donor A: **GW.5***, upstream from 5' end to breakpoint
- Donor B: Any **XBB.1*** with `ORF8:G8*` and `ORF9b:I5T`, downstream from breakpoint to 3' end.
- Breakpoint: Between `nuc_24034/spike_824` to `nuc_24046/spike_828`
- Private mutations: `C2260T`, `C7113T/ORF1a:T2283I`, `C29535T`
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/fa942c04-400f-4def-ab81-685750045312)

<details><summary>Genomes: </summary>

`EPI_ISL_18294822, EPI_ISL_18294824-18294825, EPI_ISL_18294827`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_8ef0_da1060.json?label=id:node_10906506

current placement, with `ORF8_G8` genotype filter
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1402140b-c895-4002-9c45-ac8392f129ae)

details
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/77002e16-b676-4f0c-a4d4-ecc21c930267)

**Trivia:**
- This looks like contaminated to me at first, however, after cheking that 3 seqs have Ns around `nuc_6501` but `EPI_ISL_18294827` does cover that and has `C6501A(ORF1a:P2079Q)`, it cannot be ruled out of a real recombinant.
- There's a sub-branch with `ORF1a:T2283I` follows: `GW.5` > `A28768G` > `G25839T(ORF3a:W149C)` > `C7113T(ORF1a:T2283I)` suits Donor A, but all seqs are from England.
- There's a `FL.13` sequence from that area suits Donor B with query: `G27915T, T28297C, C29535T, -C28511T`, `EPI_ISL_17690187` but that was collected months back.

**EDITED**:

**Further analysis by @Over-There-Is :**
_GW.5.1 / FL.13.4 Recombinant
GW.5.1> C7113T(Orf1a:T2283I)
FL.13.4> T19896C, C29535T>C2434T, A22893G(S:K444R), G23222A(S:E554K), A26612G
Breakpoint: 24034~24046_

**Comment by FedeGueli** [comment]
@NkRMnZr didnt we discussed this already somewhere?

**Comment by FedeGueli** [comment]
> @NkRMnZr didnt we discussed this already somewhere?

Oh no i was confounding with GN.1 that did the same!

**Comment by FedeGueli** [comment]
England has a quite big Pakistani community so the donor you found could be credible.

**Comment by FedeGueli** [comment]
still not spreading.

**Comment by aviczhl2** [comment]
+1 France, EPI_ISL_18387869

This one doesn't have C2260T, suggest to alter the query to C29535T,G22927T,C22995T

**Comment by aviczhl2** [comment]
+1 USA

**Comment by FedeGueli** [comment]
Query changed i see thank you.

**Comment by Over-There-Is** [comment]
GW.5.1 / FL.13.4 Recombinant
GW.5.1> C7113T(Orf1a:T2283I)
FL.13.4> T19896C, C29535T>C2434T, A22893G(S:K444R), G23222A(S:E554K), A26612G
Breakpoint: 24034~24046

**Comment by Over-There-Is** [comment]
Although GW.5.1> C7113T are collected in UK and US, GW.5.1 itself is circulating in Pakistan, as a Commonwealth, they are well communicating with UK.
FL.13.4> T19896C, C29535T>C2434T, A22893G(S:K444R), G23222A(S:E554K), A26612G is not found in Pakistan, but there is an FL.13.4> T19896C, C29535T sequence there, and seems exported to UK, Singapore and Netherlands. Singapore is a Commonwealth too.

**Comment by Over-There-Is** [comment]
![2023-10-25 (4)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/62b1341a-b98b-44fa-a87e-c7661a69932a)
Only 1 sequences dropped out 26612.

**Comment by FedeGueli** [comment]
> GW.5.1 / FL.13.4 Recombinant GW.5.1> **C7113T**(Orf1a:T2283I) FL.13.4> _T19896C,_ **C29535T**>_C2434T, A22893G(S:K444R), G23222A(S:E554K),_ **A26612G** Breakpoint: 24034~24046

Thank you great!

**Comment by FedeGueli** [comment]
@NkRMnZr i have integrasted your proposal with the new analysis by @Over-There-Is

**Comment by Over-There-Is** [comment]
GW.5.1> C7113T is not designated yet, so the asterisk is not necessary.

**Comment by corneliusroemer** [comment]
Found this one too :) @aviczhl2 I think it's missing from the recombinants.tsv

Here's a current Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25b86_94cbe0.json?label=id:node_3206142

<img width="1993" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/dc3e421f-5bad-4e7b-8648-f78b265cb20e">

**Comment by aviczhl2** [comment]
> Found this one too :) @aviczhl2 I think it's missing from the recombinants.tsv
> 
> Here's a current Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25b86_94cbe0.json?label=id:node_3206142
> 
> <img alt="image" width="1993" src="https://user-images.githubusercontent.com/25161793/278097724-dc3e421f-5bad-4e7b-8648-f78b265cb20e.png">

Already in. Will update whenever seqs of a lineage doubles. 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f5942f54-4d4e-4869-a586-7a864ea77b34)

**Comment by FedeGueli** [comment]
3 new samples from Pakistan 20% of September samples from there
ping @corneliusroemer

**Comment by FedeGueli** [comment]
Please propose it

**Comment by FedeGueli** [comment]
> Transferred to [cov-lineages/pango-designation#2352](https://github.com/cov-lineages/pango-designation/issues/2352)

Thank you

**Comment by FedeGueli** [comment]
Now designated XDE via https://github.com/cov-lineages/pango-designation/commit/1f6b1c15215b3623b9f7c544039ba7882d349405

**Comment by FedeGueli** [comment]
EPI_ISL_18690172 should be XDE but it is not caught by the query
