### ISSUE TITLE
BA.2.86.1 with S:G594S(21 sequences,Denmark)

### ISSUE THREAD

**Issue by Outpfmance** [sars-cov-2-variants/lineage-proposals#856]
This is a Danish branch of BA.2.86* that currently has 6 sequences and growing.
Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_f331_da5400.json?f_userOrOld=uploaded%20sample&label=id:node_5392903
![IMG_1513](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125484893/87f165c7-4506-422a-b037-98e1befc2ab3)

GISAID AA query:Spike_L452W,Spike_G594S  OR BY NUC: **_A4576T, T4579A,A7842G_** (EDITED)
Sequences:
EPI_ISL_18294614
EPI_ISL_18294554
EPI_ISL_18294508
EPI_ISL_18264053
EPI_ISL_18264030
EPI_ISL_18135401

**Comment by HynnSpylor** [comment]
Maybe it should be 6 seqs- the 6th one (actually the 1st one on date, collected in 2023-08-14) is EPI_ISL_18135401
The seq shows A6183R (R=A or G) also with S:G594S

**Comment by FedeGueli** [comment]
> Maybe it should be 6 seqs- the 6th one (actually the 1st one on date, collected in 2023-08-14) is EPI_ISL_18135401 The seq shows A6183R (R=A or G) also with S:G594S

A4576T, T4579A,A7842G finds all

**Comment by Outpfmance** [comment]
It has now been corrected.
Thanks @FedeGueli @HynnSpylor

**Comment by Sinickle** [comment]
S:594 is around 15Å from S:621 (based on some alpha fold file I have), which is also mutated in BA.2.86*. 
I believe that Yunlong Cao found S:621 to be possibly at least partially responsible for it spending more time in a spike-down conformation. 
Might make this mutation be a little less random than it would otherwise seem.

**Comment by FedeGueli** [comment]
14 Now

**Comment by Outpfmance** [comment]
It has 21 sequences now.

**Comment by FedeGueli** [comment]
Designated JN.7 via https://github.com/cov-lineages/pango-designation/commit/2020508a6d891ada24c3a8545e726676b9aba3d1
