### ISSUE TITLE
EY.1 Cluster in Canada with S:P251L [23 sequences]

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#86]
GISAID Query: Spike_F157L, Spike_Q613H, Spike_P251L
[CoV-Spec link](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A346T%2CS%3A144-%2CS%3A157L%2CS%3A613H%2CS%3A251L&nextcladePangoLineage=ey.1&nextcladePangoLineage1=ey.1&)

This cluster as of 5/21 has 20 sequences, 2 in the US and 20 in Canada. 

The cluster is believably a more fit BQ.1, but I think not enough to make a difference against the current most fit XBB* sublineages.   
It appears at the top of the growth advantage charts for BQ.1 at the moment, due to British Colombia recently uploading 18 sequences, likely indicating some sort of cluster event. 

Overall, this is BQ.1 with S:R346T, S:P251L, S:Y144-, S:F157L, S:Q613H. The additional mutations beyond EY.1 are 
ORF1a:T346I, S:P251L

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17bc7_adde70.json?f_userOrOld=uploaded%20sample

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/0bcd2e31-4133-4b6b-b620-905edf44feab)

**Comment by FedeGueli** [comment]
Canada is always tricky to assess growth rates but thx to track it here

**Comment by FedeGueli** [comment]
No new seq

**Comment by FedeGueli** [comment]
Still no new seqs . I think we canc lose it. @Sinickle please reopen or ping if something changes!
