### ISSUE TITLE
Potential Usher bug that places unrelated seqs to branches with mutations they don't have.

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#861]
@FedeGueli @AngieHinrichs

I find this problem especially severe in EG.5.1.1.

For example, there is an EG.5.1.1+C27059T+S:L455F branch with 6 seqs, however if you look at seqs it shows and verify them on GISAID, only one of them actually has C27059T. Most of them are actually pure HK.3. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_9b48_faa370.json?label=id:node_6962728)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/be391148-c3f5-4706-8ad0-d4c9765cbc69)

Same problem also appears in EG.5.1.1+S:Q14R branches,where 8 of the 63 seqs that should belong to the main branch are placed on branches with mutations they don't have. 

There's no 3rd shared mutation of these seqs.

**Comment by aviczhl2** [comment]
> Noticed this too when tracking FLip, a few branches will be pulled back to where they should belong to, but some are quite persistent with artifact; There're also some split into different parts on the tree, quite a few are homoplastic branches, or known issue associating with indel like at the end of ORF8 that caused F120V, I121L artifact

The Late Orf8 mutation is very common  but it is not artefact. @ryhisner analysed that.

**Comment by Over-There-Is** [comment]
> > Noticed this too when tracking FLip, a few branches will be pulled back to where they should belong to, but some are quite persistent with artifact; There're also some split into different parts on the tree, quite a few are homoplastic branches, or known issue associating with indel like at the end of ORF8 that caused F120V, I121L artifact
> 
> The Late Orf8 mutation is very common but it is not artefact. @ryhisner analysed that.

https://github.com/sars-cov-2-variants/lineage-proposals/issues/252#issuecomment-1659166297

**Comment by AngieHinrichs** [comment]
> For example, there is an EG.5.1.1+C27059T+S:L455F branch with 6 seqs, however if you look at seqs it shows and verify them on GISAID, only one of them actually has C27059T.

Do they have an 'N' or other ambiguous base at 27059?  If other mutations are shared then UShER may impute that they have mutations at 'N' bases.

**Comment by aviczhl2** [comment]
> Do they have an 'N' or other ambiguous base at 27059? If other mutations are shared then UShER may impute that they have mutations at 'N' bases.

There's no other shared mutations. The tree is simply EG.5.1.1+C27059T+G22927T.

Seems that these seqs have 27059N. But at that case shouldn't they be placed back to HK.3?

**Comment by AngieHinrichs** [comment]
Yes, if they're really EG>5.1.1 + G22927T + 27059N (no additional shared mutation), then I would expect them to be placed in HK.3 not + C27059T.  Can you send a list of the seqs that have 27059N?  I can try a prune & replace.

**Comment by aviczhl2** [comment]
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_30fa9_65b200.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/ca804c6c-569e-4f4c-bd19-b32a20f4a68a)

Everything else than the Shanghai seq don't have C27059T. @AngieHinrichs 

Also this seems to be a systemic problem that also appears on other mutation branches, better fix it on algorithm side.

**Comment by aviczhl2** [comment]
The bug still continues, #1018  is a sample.

**Comment by aviczhl2** [comment]
This bug still exists and lead to the mistaken designation of HK.32.

**Comment by corneliusroemer** [comment]
Thanks for tracking this @aviczhl2. Good to collect evidence for negative impact of the imputation issue. Once Usher has placed a sequence, it forgets about Ns forever. Would be really useful if Ns were at least reported, see my proposal here: https://github.com/yatisht/usher/issues/349

First step would not require changing any placement algorithm, just not throw away N information and surface in exports. Similarly, deletions could be highlighted in Nextstrain tree exports even if the core algorithm isn't changed at all.

**Comment by aviczhl2** [comment]
> I will try a prune & replace, but I agree it would be better to prevent these than to fix them after the fact. I wonder if there is a batching effect with usher-sampled. I will try to make a test case for debugging.

I guess cornelius's suggestion may be a good idea. Start from retaining the original info of nucs of seqs for positions with mutations, which won't consume too much memory but is helpful.

**Comment by FedeGueli** [comment]
> Thank you for tracking this @aviczhl2. I see that as the EG.5.1.1 > C27059T branch has grown, it has also accumulated a bunch of reversion on 27059: <img alt="image" width="475" src="https://private-user-images.githubusercontent.com/186983/286352679-900c8e3f-90aa-42d5-b857-b5f73cb7074a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTk3MjgsIm5iZiI6MTcwMzg5OTQyOCwicGF0aCI6Ii8xODY5ODMvMjg2MzUyNjc5LTkwMGM4ZTNmLTkwYWEtNDJkNS1iODU3LWI1ZjczY2I3MDc0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwMTIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2UzMjE3NjEwNzhmNmM3YzBiYzhhMzc3OWI2MjViZGY1MDI0NDc0ZjUyZTlmMDhkNTljZjBmZWQ2YjQwMTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tvh4YX_OjoCrjvkaWgSzGrImMQZITr9iFECYpVE7iOU">
> 
> I will try a prune & replace, but I agree it would be better to prevent these than to fix them after the fact. I wonder if there is a batching effect with usher-sampled. I will try to make a test case for debugging.

I don't know if already noted but the mutation is A27507C defining of XBB.1.9.2 that mutated to 27507T in 300 sequences of EG.5.1.1  scattered among multiple lineage: i re found this issue cause i found a fast growing lineage in Russia that nextclade reads as Hk.30 having T26609C together with S:t478R and was spotted by @NkRMnZr that raised multiple times the matter in the issue: https://github.com/sars-cov-2-variants/lineage-proposals/issues/787 just look at comments searching for Branch 5.   So are we sure is an Usher error and instead it is not a mutation occuring on the top of the defining of XBB.1.9.2 ? i noticed that when it appears the lineage is usually split in two : it happened with the retracted HK.32.1 and it happens also in the HK.30 +478R i mentioned above. Could be that there is a indel there maybe ? or that simply a part of sequences do base calling at that position?  On Gisaid searching correctly i found both A27507C and A27507T for the same lineage so they are been read by Gisaid and it is ot an usher issue but something different..

@AngieHinrichs hope you could take. a look..

Here the trees i have:
for branch 5 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/787:

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_a8b0_f6a560.json?c=gt-nuc_27507&gmax=28507&gmin=26507&label=id:node_3444228
<img width="1167" alt="Screenshot 2023-12-30 alle 02 33 46" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/938b2560-ceb6-4eb9-9fa3-893c8fcb0bd9">


Downsampled global tree:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_a8b0_f6a560.json?c=gt-nuc_27507&gmax=28507&gmin=26507&label=id:node_3418986
<img width="1169" alt="Screenshot 2023-12-30 alle 02 32 46" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/dc2aa601-a2a8-4d63-b23a-3574cab256b6">


cc @aviczhl2 @corneliusroemer @NkRMnZr

**Comment by FedeGueli** [comment]
to be clear:
All the EG.5.1.1 sequences with A27507C>T belong to this tree
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3b7da_f75010.json?label=id:node_3444384
<img width="1163" alt="Screenshot 2023-12-30 alle 02 44 28" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2eec360e-8892-4903-a1e3-8589bfadfb60">
you see Branch 5 from #787 on the top 
immediately below you see ex HK.32.1 retracted 
and then a few undesignated unproposed branches.
 the problem here is that the Branch 5 has also the defining of HK.30 and it should probably be under HK.30 if it would not be for 27507T.
