### ISSUE TITLE
Potential Recombinant XBB.1.16/FL.1.5.1  with S:K182Q, S:F456L, S:E554K, S:A701V and ORF9b:S63F plus 2 non-Spike aa mutations (49 seqs in 9 countries)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#862]
Edited proposal by moderator:
looking at mutations with the double reversion of Or9b:N55S>N and C29386T>C and the presence of S:F456L and S:A701V
i have identified a FL.1.5.1 potential donor with S:E554K circulating in Sweden and defined also by C28471T

[Donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d1b0_172c60.json?f_userOrOld=uploaded%20sample&label=id:node_7047610):
![Schermata 2023-09-25 alle 13 50 16](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a58e0957-e89f-4e77-a78e-bfc8a2b6246c) (Query for Donor:  G23222A, G20060T,C22995G)

[Recombinant ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34345_13aac0.json?c=gt-nuc_28471&gmax=29471&gmin=27471&label=id:node_6834000)(by @HynnSpylor ) :
![Schermata 2023-09-25 alle 13 51 02](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2c857fee-a50e-464e-936c-50d051fe00a6)

[Covspectrum comparison tool](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.1.16*&aaMutations1=S%3AE554K&nucMutations1=C28471T&nextcladePangoLineage1=FL.1.5.1*&analysisMode=CompareEquals&):
![Schermata 2023-09-25 alle 13 53 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b5f923d2-4f32-499f-8b76-47845d6abfa8)

So to me it is a 5' end to breakpoint between 22101 from XBB.1.16
Breakpoint between 22102 and 22927.
22928 to end :FL.1.5.1 (specific) donor mentioned above

**Original proposal:**
Defining mutations:
XBB.1.16>G28447A (ORF9b:S55N, rev)>T22928C (S:F456L), C23664T (S:A701V)>A1269G (ORF1a:D335G), T8908C, A13693G (ORF1b:T76A), A22106C (S:K182Q), G23222A (S:E554K), C28471T (ORF9b:S63F)
GISAID query: T8908C, A13693G, T22928C
Earliest seq: 2023-08-19 (Sweden- EPI_ISL_18162576)
Most recent seq: 2023-09-16 (Belgium- EPI_ISL_18299718)
Countries detected: Sweden (2), Belgium (2), Australia (1), Canada (1), Denmark (1)
Usher Tree:
![QQ截图20230925171143](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/9a7d70b1-8e47-45da-a2e5-9427b996cd66)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34345_13aac0.json?c=gt-S_182,554

Almost mutations are popular recently, as S:F456L is dominant, S:E554K and S:A701V are rising.  

Genomes:
EPI_ISL_18162576, EPI_ISL_18245773, EPI_ISL_18277744, EPI_ISL_18280036, EPI_ISL_18285529, EPI_ISL_18299718, EPI_ISL_18300721

**Comment by FedeGueli** [comment]
it is a recombinant with Fl.1.5.1 plus S:E554K 8circualting in gemany breakpoint between 22102 and 22927.

Tree:

**Comment by FedeGueli** [comment]
Very good spot @HynnSpylor i have re edited the proposal changing it to  recombinant . Added an intro explaining why i think it is a recomb and potential donor. let me know your thoughts

**Comment by FedeGueli** [comment]
Rapid overview of this recombinant:

![Schermata 2023-09-25 alle 14 07 45](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fb691d67-4c9d-4952-be45-a96d61ab9f8d)

**Comment by HynnSpylor** [comment]
Today GISAID updates 13 more seqs, including 12 in Canada (possible cluster infection) and 1 in Sweden.

**Comment by FedeGueli** [comment]
39!

**Comment by HynnSpylor** [comment]
49 seqs now and I'll propose it in main page

**Comment by FedeGueli** [comment]
> 49 seqs now and I'll propose it in main page

yes please!

**Comment by FedeGueli** [comment]
54

**Comment by JosetteSchoenma** [comment]
XDA @HynnSpylor Would you please add XDA to the title?

**Comment by FedeGueli** [comment]
Now 277 it is the fastest lineage over 200 seqeunces after JN.1 .
