### ISSUE TITLE
FY.1.2 sublineage with S:W64L (126 seqs in 14 countries) recent circulation in Australia

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#863]
Defining mutations:
FY.1.2>C5055T (ORF1a:T1597I)>C21910T>T13447A, G21753T (S:W64L)
GISAID query: T13447A, G21753T, A22161G
Earliest seq: 2023-06-12 (Spain- EPI_ISL_18264883)
Most recent seq: 2023-09-13 (England- EPI_ISL_18302425)
Countries detected: Spain (18), US (12, including Puerto Rico 1), UK (9), France (2), Luxemburg (1) 
Usher Tree:
![QQ截图20230925213037](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/629960ce-b948-4c05-bfad-61ca2981d2e4)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_24678_185080.json?c=gt-S_64

As most of FY* (XBB.1.22.1*) lineages are decreasing recently, this branch is still circulating in Europe and US with about 20% growth rate. We can track it for a time.

Genomes:
EPI_ISL_18059153, EPI_ISL_18093383, EPI_ISL_18095922, EPI_ISL_18109924, EPI_ISL_18109931, EPI_ISL_18120489,
EPI_ISL_18124899, EPI_ISL_18126586, EPI_ISL_18161520, EPI_ISL_18187741, EPI_ISL_18226500, EPI_ISL_18229386,
EPI_ISL_18235084, EPI_ISL_18237375, EPI_ISL_18247168, EPI_ISL_18247563, EPI_ISL_18247566, EPI_ISL_18247580,
EPI_ISL_18248320, EPI_ISL_18255450, EPI_ISL_18262914, EPI_ISL_18262919, EPI_ISL_18264883, EPI_ISL_18264888,
EPI_ISL_18264899, EPI_ISL_18265854, EPI_ISL_18274957, EPI_ISL_18274973, EPI_ISL_18274989-18274990, EPI_ISL_18275028,
EPI_ISL_18275030, EPI_ISL_18286593, EPI_ISL_18288606, EPI_ISL_18291960, EPI_ISL_18294751, EPI_ISL_18294976,
EPI_ISL_18302379, EPI_ISL_18302384, EPI_ISL_18302393, EPI_ISL_18302421, EPI_ISL_18302425

**Comment by FedeGueli** [comment]
S:64 was quite successful both in BA.2 and BA.5 , curious to see what could do here.

**Comment by HynnSpylor** [comment]
54 seqs now and it is one of the fastest FY* sublineage

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=T13447A%2CG21753T%2CA22161G&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
97 sequences with new countries as Ukraine, Australia, Belgium and others.
Still slow but it is circulating widely

**Comment by HynnSpylor** [comment]
128 seqs now and it seems still circulating in Australia.

**Comment by FedeGueli** [comment]
Reopening it to track the Australian development

**Comment by aviczhl2** [comment]
Designated FY.1.2.1
