### ISSUE TITLE
HK.3 + C27889T (Orf8 killer mutation present in all BA.5) with S:P174S escape mutation emerged recently in Singapore (72 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#865]
**Intro**
Here i want to propose a singaporean sublineage of HK.3 (note that HK.3 as a whole is approaching 50% of sequences in the last two weeks there) 
defined by S:P174S.

S:P174S is a known escape mutation for the broadly neutralizing ABs found and described by Liu et al in this[ paper](https://www.biorxiv.org/content/10.1101/2023.04.08.536123v1.full.pdf) that blocks ACE2 binding interacting with residues preceding the N4 loop in the NTD and with  loop 1 and 2 of SD.1

The authors provided a very useful heatmap that makes easy to track mutations escaping this AB:
![Schermata 2023-09-26 alle 11 48 43](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a3901676-1665-4366-be3f-5ebc2651af1b)

As could be seen S:P174 is a key residue and a mutation to S moderately escapes these group of ABs.

It has to be noted that this sublineage popped up in a Hk.3 + C27889T branch:
C27889T is the Orf8 killer mutation described first by @ryhisner ( if you want to comment please do!!)

**Proposal**
Defining mutations:
HK.3 > **C27889T** > C11008T > **Orf1a:E1210K** (G3893A = **NSP3_E392K**) , T18324C > **S:P174S** (C22082T)

Orf1a:E1210K is quite uncommon ( 2,5K sequences from the start of the pandemic) but predicted to be beneficial
![Schermata 2023-09-26 alle 11 56 33](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a7ecdeb1-9be8-4524-9f7f-64c083b90cf2)

Gisaid query : **G3893A , T18324C ,C22082T**

Samples : 16 (all from Singapore)
EPI_ISL_18243471, EPI_ISL_18243511, EPI_ISL_18243543,
EPI_ISL_18306935, EPI_ISL_18306939, EPI_ISL_18306971,
EPI_ISL_18306985, EPI_ISL_18306995, EPI_ISL_18307044,
EPI_ISL_18307078, EPI_ISL_18307086, EPI_ISL_18307116,
EPI_ISL_18307145, EPI_ISL_18307164, EPI_ISL_18307186,
EPI_ISL_18307198

Tree:
![Schermata 2023-09-26 alle 11 59 44](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e4f73aff-d8d2-4ca1-b2ff-f03922615ca8)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5f09e_2a7030.json?c=gt-S_174&label=id:node_6978180

**Comment by krosa1910** [comment]
There seems to be an S:S884F branch of it, I do not know S2 very well, but S:T883I emerged in a lot of variants, so maybe there is something there. Also the number have increased to 38.

**Comment by aviczhl2** [comment]
46 now.

**Comment by FedeGueli** [comment]
It seems very fast: ping @corneliusroemer new spike escape mutation rapidly spreading in Singapore , i suggest direct designation!

**Comment by FedeGueli** [comment]
This reached 7% in Singapore.  72 seqs ping @corneliusroemer

**Comment by FedeGueli** [comment]
![Schermata 2023-10-09 alle 13 56 35](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8aebd2b8-a0a6-43f3-aa10-93e70a262986)
also very credible advantage vs Hk.3 in Singapore

https://cov-spectrum.org/explore/Singapore/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G3893A%2CT18324C%2CC22082T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated HK.3.5 via https://github.com/cov-lineages/pango-designation/commit/c1e681c015a9ffbeb6e3893a7f5ff05fb5318643

**Comment by FedeGueli** [comment]
+1 Luxembourg +3 England not yet on Gisaid
![Schermata 2023-10-16 alle 12 44 50](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8b3ee98a-44bf-44a3-8f66-8a1661d396af)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3d7e4_d13970.json?c=country&label=id:node_3468951

@thomaspeacok @angiehinrichs @corneliusroemer i flag you HK.3.5 : it is showing a huge advantage on Collection42 , these exports may hint to something more real than what i initially thought ( the usual Sigaporean cluster).it is worth double-flagging it to be monitored closely.
