### ISSUE TITLE
HV.1 + ORF1a:T4083M (proposed on Pango #2228) with S:K444T (8 seqs, USA, Canada)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#866]
**Defining Mutations:** `HV.1 (EG.5.1.6.1)` + `C12513T(ORF1a:T4083M = nsp8_T141M)` = (https://github.com/cov-lineages/pango-designation/issues/2228)  >> `A22893C(**S:K444T**)`
**Query:** `C5835T, C12513T, A22893C`
**Earliest seq:** 2023-08-30 (`EPI_ISL_18276226`, New York, USA)
**Latest seq:** 2023-09-19 (`EPI_ISL_18305437`, Ontario, Canada)
**Sampled Countries:** USA (3: NY/2; NJ), Canada (2: ON)

<details><summary>Genomes: </summary>

`EPI_ISL_18276226, EPI_ISL_18276468, EPI_ISL_18300264, EPI_ISL_18304836, EPI_ISL_18305437`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_263e4_2c6610.json?f_userOrOld=uploaded%20sample&label=id:node_6956428
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/00533aaa-50a3-4c4c-912e-50d47f4c4536)

**Comment by FedeGueli** [comment]
Parental linegae already proposed in:https://github.com/cov-lineages/pango-designation/issues/2228

**Comment by Sinickle** [comment]
14 sequences now, and in more countries. This makes up the majority (~75%) of S:K444T XBB sequences since August 1. Given that K444T + L452R has been in major variants BQ.1. and CH.1.1, I feel like this is one to watch/makes sense to bring over to the main page!

**Comment by FedeGueli** [comment]
Agreed. @NkRMnZr propose this one please

**Comment by FedeGueli** [comment]
Designated HV.1.1 via https://github.com/cov-lineages/pango-designation/commit/c3904cae0095f69cec6d4d3f915b4fbdfc846478
