### ISSUE TITLE
HK.3.2 subbranch with Orf8:M1L(24 seq, 10 countries) most of them with S:N185D (22)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#867]
HK.3.2> C100T> G7290A(Orf1a:G2342E)> C1348T, T25496C(Orf3a:I35T), A27894T(Orf8:M1L)> C4543T, A22115G(S:N185D)
Query: C853T, C21602A, A27894T
Query for S:N185D branch: A22115G, A27894T

2 with further S:P621S

Earliest Sequence: 09-11 Xining, Qinghai, China EPI_ISL_18268266
Latest Sequence: 10-27 Västra Götalands, Sweden EPI_ISL_18484264
Regions Detected:
**France** 2(ARA 1, IDF 1), **Greece** 2(Peloponnesus 1, Western Greece 1), **Sweden** 2(Västra Götalands), **UK** 1(England);
**Canada** 3(Ontario 2, Alberta 1), **US** 3(Washington 2[from **Japan**], New Jersey 1);
**Australia** 5(NSW 3, SA 2), **New Zealand** 1(Auckland); 
**China** 4(Hong Kong 2, Hubei 1, Qinghai 1);

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_20684_763510.json?label=id:node_10923271
![2023-11-02 (2)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/d4f6f7a6-9fa0-4880-a6fc-6ca50b5860df)

<details><summary>Sequences:</summary>

EPI_ISL_18268266, EPI_ISL_18306770, EPI_ISL_18388903,
EPI_ISL_18394411, EPI_ISL_18412334, EPI_ISL_18441055,
EPI_ISL_18447191, EPI_ISL_18453668, EPI_ISL_18453678,
EPI_ISL_18455951, EPI_ISL_18459205, EPI_ISL_18461762,
EPI_ISL_18461777, EPI_ISL_18461976, EPI_ISL_18463892,
EPI_ISL_18463919, EPI_ISL_18471634, EPI_ISL_18472086,
EPI_ISL_18484253, EPI_ISL_18484264, EPI_ISL_18490880,
EPI_ISL_18490950, EPI_ISL_18497161
</details>

**Comment by FedeGueli** [comment]
thank you cc @ryhisner

**Comment by Over-There-Is** [comment]
The third sequence detected, from Jingmen, Hubei

**Comment by Over-There-Is** [comment]
Appears in USA now.

**Comment by Over-There-Is** [comment]
Hong Kong+1, 1 more district

**Comment by Over-There-Is** [comment]
France

**Comment by Over-There-Is** [comment]
HK.3.2> C100T> G7290A(Orf1a:G2342E) is found in Hubei.

**Comment by Over-There-Is** [comment]
Australia

**Comment by Over-There-Is** [comment]
Canada

**Comment by Over-There-Is** [comment]
NZ

**Comment by Over-There-Is** [comment]
US+2, from Japan, on N185D branch, P621S

**Comment by FedeGueli** [comment]
Please propose it when turns the 25 seqs point

**Comment by FedeGueli** [comment]
Is interesting that two of the fastest HK.3 sublineage went further destroying orf8 both this one and HK.3.5

**Comment by FedeGueli** [comment]
@Over-There-Is i would re arrange the proposal focusing on 185D branch cause the sequences without it are all old.

**Comment by Over-There-Is** [comment]
Ontario +2

**Comment by Over-There-Is** [comment]
Sweden+2

**Comment by Over-There-Is** [comment]
Greece+2

**Comment by Over-There-Is** [comment]
UK+1

**Comment by FedeGueli** [comment]
+1 US. not sure if it makes sense to keep the two separated the lineage could start from S:N185D to me. Please propose it

**Comment by FedeGueli** [comment]
Deignated HK.3.2.2 via https://github.com/cov-lineages/pango-designation/commit/a699198d41ab8151456c85f81f27dfd2888ca517
