### ISSUE TITLE
XCH + ORF3a:T175K + N:P6T and ORF9b:D2E (54)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#868]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/2f7e0690-ced2-48fc-abfb-05930e3ba27c)
Tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34629_392390.json?c=gt-N_6&label=id:node_7293545
Gisaid Query: C28289A, A16923C
first seq: 2023-06-09
most recent: 2023-09-14
EPI_ISL_18295004 EPI_ISL_18280448 EPI_ISL_18251785 EPI_ISL_18222145 OY731127.1 EPI_ISL_18252357 OR577060.1 EPI_ISL_18279526 EPI_ISL_18258609 EPI_ISL_18258613 OR540743.1 EPI_ISL_18144599 OR186894.1 England/CLIMB-CM7YMWKC/2023 EPI_ISL_18224093 EPI_ISL_18258646 EPI_ISL_18223713 OR563486.1 OR559401.1 EPI_ISL_18137041 EPI_ISL_18280508 OR569433.1 OR540744.1 EPI_ISL_18258612 EPI_ISL_18144512 EPI_ISL_18299452 OR465671.1 EPI_ISL_18271542 EPI_ISL_18258648 EPI_ISL_18229402 EPI_ISL_18258649 OR560367.1 EPI_ISL_18291057 OR516344.1 EPI_ISL_18223302 EPI_ISL_18251784 OR553317.1 EPI_ISL_18291042 EPI_ISL_18144865 EPI_ISL_18299404 EPI_ISL_18251786 OR469612.1 OR577117.1 EPI_ISL_18223724

**Comment by FedeGueli** [comment]
Already 24

**Comment by FedeGueli** [comment]
Adding a tracker: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C28289A%2CA16923C&analysisMode=CompareToBaseline&
early to say but it looks fast.

**Comment by FedeGueli** [comment]
28 now

**Comment by FedeGueli** [comment]
Please propose it. it is around 1% in NYC past two weeks
