### ISSUE TITLE
XCH.1 + ORF1a:D981Y (67 Seq.)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#869]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/690d194e-3fd8-48db-86bc-29f7d9aa8ff9)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28aa5_3a0ca0.json?c=country&label=id:node_7293768
Gisaid Query: G3206T, C23280T, G25045A, T25658C, T9952C or just: (G3206T,G9220A,C23280T **EDITED**)
First Seq: 2023-08-23
Most Recent: 2023-09-16

EPI_ISL_18279949 EPI_ISL_18295818 EPI_ISL_18280400 EPI_ISL_18277608 EPI_ISL_18294941 EPI_ISL_18294542 England/CLIMB-CM7YFOIE/2023 England/CLIMB-CM7YEKNF/2023

**Comment by FedeGueli** [comment]
i think G3206T,G9220A,C23280T works well too

**Comment by FedeGueli** [comment]
No chane to compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=JN.1*&nucMutations1=G3206T%2CG9220A%2CC23280T&analysisMode=CompareToBaseline&
