### ISSUE TITLE
JD.1.2+7-nuc,4-aa including S:E554Q  (50 seqs, 6 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#870]
JD.1.2+C13968T,C29367T(**N:P365L**)+C28087T(**Orf8:A65V**)+T6136C,T18435G,G23222C,C28657T(**S:E554Q**, **Orf1b:D1656E**)

GISAID query: T6136C,T18435G,G23222C
No. of seqs: 7(OH,FL,TX,Puerto Rico)

First: EPI_ISL_18119752, 2023-8-8
Latest: EPI_ISL_18309226, 2023-9-6

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice18_genome_f64b_3a0c80.json?label=id:node_7263279)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/16a3c259-2034-4252-99bc-3337e2bb0d30)

**Comment by aviczhl2** [comment]
Hi Fede, That's Orf1b not 1a.

**Comment by FedeGueli** [comment]
> Hi Fede, That's Orf1b not 1a.

ahha thank you very much!! what an epic fail from me! Sorry!

**Comment by krosa1910** [comment]
Now spread to Canada, and 11 seqs in total.
<img width="1442" alt="Screenshot 2023-10-04 at 6 27 35 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/a4ab5a14-34ed-4a94-8036-9e6a3f4b0d8d">

**Comment by FedeGueli** [comment]
19 batch from Canada

**Comment by aviczhl2** [comment]
30, Italy

**Comment by FedeGueli** [comment]
This seems fast propose it when it reaches 50

**Comment by aviczhl2** [comment]
32, Brazil

**Comment by FedeGueli** [comment]
This carries PLPro_D93E (NSP3_D838E)

**Comment by aviczhl2** [comment]
> This carries PLPro_D93E (NSP3_D838E)

Hi, Fede, again this is Orf1b not 1a.

**Comment by FedeGueli** [comment]
> > This carries PLPro_D93E (NSP3_D838E)
> 
> Hi, Fede, again this is Orf1b not 1a.

haha thank you! corrected

**Comment by aviczhl2** [comment]
44,Netherlands

**Comment by aviczhl2** [comment]
+1 Belgium

**Comment by FedeGueli** [comment]
JD.1.2.1 via https://github.com/cov-lineages/pango-designation/commit/31270ad0f1ecec38c8298a34c6dd1baa3bd0b440
