### ISSUE TITLE
A very long evolution branch of BA.5.5 in Alberta, Canada (8 seqs, very likely from one chronic patient)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#872]
**The basic nuc mutations of the Canadian branch (also the GISAID query):
C337T, C23447G (S:L629V)**

Earliest seq: 2022-08-29 (EPI_ISL_15278730)
Latest seq: 2023-09-06 (EPI_ISL_18311951)

The steps of evolution:

step 1: C22281T (S:T240I), G22317A (S:G252D), G22898A (S:G446D), G23009C (S:V483L), C23447G (S: L629V)

step 2: G22632A (S:R357K), A22905G (S:N448S), T22942G (S:N460K)

step 3: A5576G (ORF1a:M1771V), T7247C (ORF1a:F2328L), G8393A (ORF1aA2710T), C11020T, T11380C, T21789C (S:I76T rev), G22200A (S:G213E), T22281C (S:I240T rev), A22317G (S:D252G rev), G22770A (S:R403K), A22881G (S:K440R)

step 4: G22017T (S:W152L), C22314A (S:P251H),  C22458T (S:T299I), T22478C (S:F306L), T22896C (S:V445A), A22991G (S:N477D, 2-nuc), T23010G (S:L483R, 2-nuc), A28467G (N:K65R)

step 5: (for the latest seq): G22021A (S:M153I), A22578G (S:D339G rev), A22582C(S:E340D), G22599C (S:R346T), C22986T (S:A475V), G23010A (S:R483H, 2-nuc), G23018T (S:V486F rev), T23031C (S:F490S), A23598G (S:K679R), G25019T (S:D1153Y), C25418A (ORF3b:T9K)

The aa mutations of latest seq (show Spike only):
![QQ截图20230927194820](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/31939068-154f-4d06-8e0c-ae98482ec999)

The aa deletions and insertions of latest seq (show Spike only):
![QQ截图20230927195048](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/72fcda08-bc75-4d79-bcf0-d266f63bc3a5)
Usher Tree:
 
![QQ截图20230927193757](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/0a18c71c-ae33-4e77-b455-3ee7044a1b33)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c41d_392480.json?c=gt-S_483

It is very likely from one chronic patient, whose course of disease lasts more than one year (the first seq was collected in Aug 2022). 5 steps of saltation are observed, and most of aa mutations concentrate on Spike with several reversion. 
Interestingly, the site S: 483 occurs 3 changes: S: V483L (in step 1)→S: L483R (in step 3)→S: R483H (in step 5)

 I hope that it will be just one chronic.

Genomes for all the branch:
EPI_ISL_15278730, EPI_ISL_15598104, EPI_ISL_15667047, EPI_ISL_16706498, EPI_ISL_17022081, EPI_ISL_17152522, EPI_ISL_17370155, EPI_ISL_18311951

**Comment by FedeGueli** [comment]
Not circualting in general population
