### ISSUE TITLE
FL.1.5.1 sublineage with S:R190K (20 seqs in Canada and US)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#873]
Defining mutations:
FL.1.5.1>A26760T (M:I80F)>C9448A, G22131A (S:R190K)
GISAID query: C9448A, G22131A, A26760T
Earliest seq: 2023-09-03 (Alberta, Canada- EPI_ISL_18278517)
Most recent seq: 2023-09-13 (Alberta, Canada- EPI_ISL_18312202)
Countries detected: Canada (6), US (2)
Usher Tree:
![QQ截图20230927201705](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/cd7413e6-d8f1-4393-ba09-e714cb4144b3)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3e055_3d0530.json?c=gt-S_190

S:R190K is rising in some EG.5.1* sublineages. It may slightly increase the ACE2 binding. 
![QQ截图20230927202408](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/f8d005bf-72c6-4d4f-9c84-b7bf84ef1f69)

Genomes:
EPI_ISL_18278517-18278518, EPI_ISL_18309991, EPI_ISL_18310174, EPI_ISL_18311973, EPI_ISL_18311979, EPI_ISL_18312202,
EPI_ISL_18312282

**Comment by FedeGueli** [comment]
14 now, still mostly Canada . not slow, lets see if can spread further

**Comment by FedeGueli** [comment]
I think it was just a clsuterin Canada closing it.
