### ISSUE TITLE
Chronic Delta (AY.74 classified) with S:242-243del, S373P and N501Y

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#875]
Sequence:EPI_ISL_18151977
![41A028F5EAC8FFE09BF94EA7F257B085](https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/ecd74e6f-bea3-4bc1-be12-87c9a3310fb8)
I think this one is interesting because it got S:242-243del as in XBC*, S:S373P and S:N501Y are both very successful mutations of Omicron we understands. Not familiar with the rest though.

**Comment by krosa1910** [comment]
However, shouldn't it be placed under AY.4.2*? I remember AY.4.2* got S:Y145H and S:A222V. Exactly presented in this sequence.

**Comment by FedeGueli** [comment]
> However, shouldn't it be placed under AY.4.2*? I remember AY.4.2* got S:Y145H and S:A222V. Exactly presented in this sequence.

No Orf1a:A2529V so it is not AY.4

**Comment by FedeGueli** [comment]
Still a singlet closing it 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_8f7_24d210.json?f_userOrOld=uploaded%20sample
