### ISSUE TITLE
2 Weird Flip Sequences with C7051T and seemingly a lot of similar CT transitions

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#878]
Gisaid Inquiry: C7051T,C1889T,G22927T
Sequences: 

EPI_ISL_18316684  and EPI_ISL_18254485
<img width="1057" alt="Screenshot 2023-09-28 at 2 15 39 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/475b05c7-4cf0-4710-926e-8739624be5c3">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17718_5c18c0.json?f_userOrOld=uploaded%20sample

I was checking Flip as usual and I saw those two.
<img width="1051" alt="Screenshot 2023-09-28 at 2 16 29 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/d71123a2-0ee6-4060-a958-83e41b563f8d"> (Cov-spectrum only got to analyze the first, French sequence)

I thought it could be a recombination of EG.5.1.3*? with DV.7.1*? , if so the breakpoint could be between 18492  and 19886, before is EG.5.1.3*+C1684T+C7051T, and after is DV.7.1*+C20320T+T24073C, but both seems rare so I am not sure.

Don't even know if those are two related singlets or a true recombination, because the later one seems related to EG.5.1*

**Comment by FedeGueli** [comment]
Already proposed here:https://github.com/sars-cov-2-variants/lineage-proposals/issues/811
