### ISSUE TITLE
BA.2.75.2 saltation singlet with I19Trev, R190S, T240P, S446N, L452Q, V483F, P621T, I1172V (Yunnan, China)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#881]
BA.2.75.2> C7420T> A11789G(Orf1a:I3842V), G29648T(Orf10:D31Y)> G2075T(Orf1a:G604C), G2890T, C6578T(Orf1a:L2105F), C7299T(Orf1a:A2345V), C9661T, A9760G, G10310A(Orf1a:V3349I), C12459T(Orf1a:T4065I), T13069C, G16707A, T18609C, T21618Crev(S:I19Trev), C21691T, G22132T(S:R190S), A22280C(S:T240P), G22899A(S:S446N), T22917A(S:L452Q), G23009T(S:V483F), C23423A(S:P621T), A25076G(S:I1172V), T25502C(Orf3a:I37T), C25516T(Orf3a:P42S), T26494G, G26529T(M:D3Y), C27223G(Orf6:Q8E), C27707T(Orf7a:A105V), C29719T

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice116_genome_3ae21_680d10.json?label=id:node_7699346
![2023-09-29 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/5b699728-f4b5-4965-bf53-28d933ea6a9d)

Query: G2890T, C6578T (edited)

**Comment by ryhisner** [comment]
Notably, this one adds two glycans with the I19T reversion (restoring the N17 glycan lost with T19I) and R190S, a Gamma mutation that adds a glycan at N188.

**Comment by FedeGueli** [comment]
no new sample of this one
