### ISSUE TITLE
EG.5.1 (or EG.5.1.6) sublineage with 3-nuc Spike mutation S:V483K (23 seqs in Australia,New Zealand,USa Sweden)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#882]
Defining mutations:
EG.5.1/EG.5.1.6 (with S:F157L but without ORF1a:S1857L)>G5044A, C11653T, A27989T, C28462T (ORF9b:T60I)>C6539A (ORF1a:H2092N), **G23009A, T23010A, T23011A** (S:V483K, 3-nuc mutation)
GISAID query: G23009A, T23010A, T23011A, C28462T
Earliest seq: 2023-09-01 (Queensland, Australia- EPI_ISL_18278517)
Most recent seq: 2023-09-08 (Queensland, Australia EPI_ISL_18312202)
Countries detected: Australia (3)
Usher Tree:
![QQ截图20230930003537](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/2fe5c121-c1e3-4ec1-8e5d-810555d17351)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_89b6_644670.json?c=gt-S_483
S:V483 mutations are popular since BA.2.86* emerges S:V483del. Now the branch shows a 3-nuc mutation S:V483K, which is very rare and considered to improve both the escape potential and hACE2 binding.
![QQ截图20230930003609](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/bb07d6ba-4de2-4626-a1c4-a2a79dca0313)

![QQ截图20230930003254](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/5d4d188d-ad87-4ae2-90bd-f580780d92e2)

Due to the potential and the rare 3-nuc mutation, we can track it for a time despite the branch is small now.

Genomes:
EPI_ISL_18284552, EPI_ISL_18324540, EPI_ISL_18324573

**Comment by FedeGueli** [comment]
Great catch!

**Comment by HynnSpylor** [comment]
6 seqs now but still in Queensland, Australia

**Comment by FedeGueli** [comment]
+1 NSW

**Comment by HynnSpylor** [comment]
11 seqs now (Australia 10, New Zealand 1) and first detected outside Australia

**Comment by FedeGueli** [comment]
It doesnt seem fast luckily

**Comment by FedeGueli** [comment]
14 now but oldies. closing it

**Comment by FedeGueli** [comment]
likely dead now closing it
