### ISSUE TITLE
Subbranch of Issue #650 with S:V445P (This is my first time seeing this besides BJ.1* derivatives), 2 seqs in Virginia (likely Dullas Airport)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#884]
#650 is Ryan's branch describing a chronic BQ.1.2.2*, later named as JH.2* branch.
I was trying to look at V445P, L452 sequences, and this one comes into mind.
Gisaid Inquiry: A17824G,G22895C,C1931A
both sequences collected in  VA, US on 09-08, submitted at 09-19 (so likely Ryan did not check it these days)
They are mentioned with airport, but the two have distinct patient metadata, so I am not sure if it is the same patient being collected twice. ( From **CAMEROON**, edited)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_bcc_79d660.json?c=gt-nuc_22895,22896&f_userOrOld=uploaded%20sample&gmax=23895&gmin=1289&label=id:node_1689263

<img width="850" alt="7BB869ABDC6A1DEB3EA34160663BA042" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/d71b85b8-409e-47f2-bbe0-71253e0b896c">

I would like to monitor this one for its uniqueness of reaching rare S:V445P 2-nuc mutation.

**Comment by FedeGueli** [comment]
Gbw samples usually start with pooling sampling. So it is either contamination or the last show up of diversity in BQ.1.2.2

**Comment by krosa1910** [comment]
Not very fast as the possible origin is undersampled and the branch seems to discontinue, consider closing it if no new related sequence uploaded in the next week.

**Comment by FedeGueli** [comment]
many time from the last sample. closing it.
