### ISSUE TITLE
New GK.1.1/FU.1 recombinant(Flip+573+704+1266+Orf9b:5,55) in USA(20 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#885]
XBB.1.5.70+
C23280T(S:T573I),C23673T(S:S704L), A24373C,G25045A(rev),A25359G(S:K1266R),A26708G, T27059C(rev),T28005C(Orf8:38 rev),T28297C(Orf9b:I5T),A28447G(Orf9b:N55S), T29386C

C23280T,C23673T from GK.1.1
A24373C,G25045A(rev),A25359G(S:K1266R),A26708G, T27059C(rev),T28005C(Orf8:38 rev),T28297C(Orf9b:I5T),A28447G(Orf9b:N55S), T29386C from an American FU.1 branch

GK.1.1---FU.1
Breakpoint between 23674 and 24372

GISAID query: A24373C,A25359G,C23280T
No. of seqs: 5(USA-AK,NJ,VA,FL,WA)

First: EPI_ISL_18266013, FL, 2023-8-23
LAtest: EPI_ISL_18309323, VA airport, 2023-9-17

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3664_7a0610.json?label=id:node_3912612)

This is the lower branch, the upper branch is #824

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/9d9574b4-af75-4f9d-b0d5-7cdd56e585aa)

[usher for FU.1 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_b043_7a5050.json?branchLabel=nuc%20mutations&f_userOrOld=uploaded%20sample&label=id:node_3505140&showBranchLabels=all)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/80813b1c-2243-4193-afef-2c46682df4f0)

**Comment by FedeGueli** [comment]
Ping @corneliusroemer another recombinant that seems fast.

@aviczhl2 please propose it once it gets 20 seqs

**Comment by FedeGueli** [comment]
17 now

**Comment by ryhisner** [comment]
There are two sequences from this lineage today with a 4-AA insertion—S:214_ESGL or ins_22204GAGTCAGGCTTA. Both also have an extraordinarily rare synonymous nucleotide mutation, T2548G. It's only been in 10 sequences ever, the most recent being from February 2021. 
<img width="1266" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c753e3d3-3d21-4ea4-bbe7-66206069841a">

**Comment by corneliusroemer** [comment]
GK.1.1 donor is here:
<img width="2050" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/b2a8fcf7-27fe-4a65-ba58-e6141e3ff459">

**Comment by aviczhl2** [comment]
> GK.1.1 donor is here: <img alt="image" width="2000" src="https://user-images.githubusercontent.com/25161793/275321799-b2a8fcf7-27fe-4a65-ba58-e6141e3ff459.png">

Thanks. I missed an additional mutation of C13405T.

**Comment by corneliusroemer** [comment]
The parents are now designated as GK.1.1.1 and FU.1.1.1

**Comment by FedeGueli** [comment]
Designated XCR
