### ISSUE TITLE
EG.5.1.3/GK.4 or GK.3.1 recombinant(52H+Flip+475V) (11 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#887]
XBB.1.5+C1889T,C2334T, G5720A,C9693T, C12789T, A16878T, A18492G，G21718T,C22624T,G22927T,T22928C, C22986T, A25045G,C27059T,C28005T

Orf1a:R542C,A690V,G1819S,A3143V,T4175I
S:Q52H,L455F,F456L,A475V
Orf8:P38S

C1889T,C2334T, G5720A,C9693T, C12789T, A16878T, A18492G，G21718T from EG.5.1.3
C22624T,G22927T,T22928C, C22986T, A25045G,C27059T,C28005T from GK.4 or GK.3.1

EG.5.1.3--GK.4 or GK.3.1
Breakpoint between 21719 and 22569 (Breakpoint on S)

GISAID query: A25045G,G21718T,C22986T
No. of seqs: 5(France)

First: EPI_ISL_18294427, 2023-9-11
Latest: EPI_ISL_18327250, 2023-9-18

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_3664_7a0620.json?label=id:node_3917249)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8b7f325e-4eda-459d-8d31-d84151468e05)

Rapid overview (edited):
![Schermata 2023-10-04 alle 06 31 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/087850e0-2f73-4aa7-bbc4-abdfbd35a4cf)

**Comment by FedeGueli** [comment]
+1 Italy, new country

**Comment by aviczhl2** [comment]
Also in Spain now.

**Comment by FedeGueli** [comment]
Ping @corneliusroemer this is likely very fast. i suggest an eye from you on it.

**Comment by corneliusroemer** [comment]
Just found this one independently! Thanks for having investigated already. Will take a closer look at the new sequences that aren't in my Usher tree yet.

**Comment by aviczhl2** [comment]
+1 USA.

**Comment by JosetteSchoenma** [comment]
XCY
