### ISSUE TITLE
XBB.1.5* with S:456L and Orf1a:H417Y (61 seqs)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#89]
Mutation Added from XBB.1.5*
Unique (3):A3586G, T19305C, A21583G
Homosplasy(3): C1514T (for H417Y), C21145T (for L6961F), T22928C (for F456L)
Gisaid Inquiry:  C1514T, T22928,T17124C
Earliest Sequence:
EPI_ISL_16944696 2023-01-27 AZ,US
Latest Sequence:
EPI_ISL_17676323 2023-05-09 WA,US
Seq Collection:
EPI_ISL_16944696, EPI_ISL_17211884, EPI_ISL_17259116,
EPI_ISL_17334097, EPI_ISL_17393267, EPI_ISL_17428596,
EPI_ISL_17429646, EPI_ISL_17475171, EPI_ISL_17486634,
EPI_ISL_17526818, EPI_ISL_17534515, EPI_ISL_17550660,
EPI_ISL_17588573, EPI_ISL_17605770, EPI_ISL_17627548,
EPI_ISL_17627829, EPI_ISL_17627850-17627851, EPI_ISL_17627862,
EPI_ISL_17627864, EPI_ISL_17627871, EPI_ISL_17651000,
EPI_ISL_17653516, EPI_ISL_17669543, EPI_ISL_17669571,
EPI_ISL_17669573, EPI_ISL_17669793, EPI_ISL_17676323,
EPI_ISL_17676354, EPI_ISL_17676388-17676389, EPI_ISL_17676397,
EPI_ISL_17676404, EPI_ISL_17676407, EPI_ISL_17676414,
EPI_ISL_17676424, EPI_ISL_17676429, EPI_ISL_17688700,

DIstribution: 5AZ, 5CA, 1FL,1GA, 8IL,1UT, 17WA
USHER tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25bea_b89400.json?f_userOrOld=uploaded%20sample

S:F456L is considered by me to be the third most successful RBD mutation in XBB era, only after 486P and 478R. It has both appeared many times, and demonstrated growth over the 486P basis. 
I largely approached this variant by systematically removing large existing trees under the giant F456L tree. (namely FD.1.1*,FE.1*, XBB.1.5.10*,XBB.1.5.59*,EG.5*,XBB.1.16.6*, issue 1982 that just got to be XBB.1.5.70*, issue 1950 from EG family which I hope get designated some time, issue 1994 of FL family , issue 29 here about XBB.1.5.18*). This one is one of the largest structure that remains on the tree. 
I decided to propose this here because currently it stays within US, yet it got to several states and has decent number. If it successfully spread to other continents or reach an even higher number count I would consider moving it to the main repository.

**Comment by krosa1910** [comment]
This is not that fast compared to most S:456L variants, I would watch it next week, if it is unable to grow to around 50 seqs or to another region, then I don't think it should be of concerns among more prominent S:456L variants like EG.5 or XBB.1.16+456L

**Comment by FedeGueli** [comment]
This seems completely disppeared very weird. I close this up but please reopen it if something changes.

**Comment by FedeGueli** [comment]
Last tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_1ae76_373cd0.json?label=id:node_6712457

![Schermata 2023-06-22 alle 16 05 24](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2290acbe-d854-4ab1-b316-03ff3816bdc2)

**Comment by FedeGueli** [comment]
re checked it is totally stale. very weird.

**Comment by FedeGueli** [comment]
to me this is slowing down.

**Comment by FedeGueli** [comment]
closing for now.

**Comment by krosa1910** [comment]
It got spread to Texas and Spain, both new, yet I agree it is not noteworthy in an age dominated by S:456L
