### ISSUE TITLE
BA.2.86.1 + ORF1a:T2087I (57 in 8 countries) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#892]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/6367bae1-871c-4e0e-a0e2-797546ab3d70)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7f8_821710.json?c=gt-nuc_6525&gmax=7525&gmin=5525&label=id:node_4520472
first seq: 2023-08-13
Most Recent: 2023-09-11
gisaid query: C6525T, A6183G

EPI_ISL_18303660 EPI_ISL_18315514 OR560235.1 EPI_ISL_18315528 England/CLIMB-CM7Y8HO4/2023 EPI_ISL_18308751 EPI_ISL_18272718 EPI_ISL_18304552 EPI_ISL_18303875 England/CLIMB-CM7YR9N1/2023 EPI_ISL_18286791 EPI_ISL_18263606 EPI_ISL_18294082 EPI_ISL_18111770 EPI_ISL_18230297 EPI_ISL_18230298 OR598216.1 EPI_ISL_18262714 EPI_ISL_18303917 EPI_ISL_18308767 EPI_ISL_18303657 England/CLIMB-CM7Y8RUT/2023 EPI_ISL_18280677 EPI_ISL_18245024 OR569223.1 EPI_ISL_18303880 EPI_ISL_18290703 EPI_ISL_18304461 EPI_ISL_18272909 EPI_ISL_18290686 EPI_ISL_18293837

**Comment by FedeGueli** [comment]
Dsignated JN.3 via https://github.com/cov-lineages/pango-designation/commit/8424ad296ae6dd8e78a5ae3247a976eae8dce8dd
