### ISSUE TITLE
XBB.1.5 Saltation: S:∆138-144, N149K, ∆242-243, R403K, L452R, E583D, L611F, P621S, D1153Y; ORF9b:I5T; ORF1a: S1372A, L2234S, S4119A; ORF1b:D2179Y (4 seq, Italy, Germany Nov 21))

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#893]
**Description**
**Sub-lineage of:** XBB.1.5
**Earliest sequence:** 2023-8-23, Italy, Apulia — EPI_ISL_18209924
**Most recent sequence:** 2023-9-22, Italy, Abruzzo — EPI_ISL_18326806, EPI_ISL_18326807
**Countries circulating:** Italy (3)
**Number of Sequences:** 3
**GISAID AA Query:** NSP3_S554A, NSP8_S177A
**GISAID Nucleotide Query:** T4379G, T12620G
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.5* & [5-of: T4379G, T6966C, T12620G, A13938G, G16377A, G20002T, C22009A, G22770A, T22917G, G23311C, C23393T, C23423T, G25019T, T28297C]
**Substitutions/Deletions on top of XBB.1.5:**
**Spike:** ∆138-144, N149K, ∆242-243, R403K, L452R, E583D, L611F, P621S, D1153Y
**ORF9b: I5T**
**ORF1a:** S1372A, L2234S, S4119A (NSP3_S554A, NSP3_L1416S, NSP8_S177A)
**ORF1b:** D2179Y
**Nucleotide:** T4379G, T6966C, T12620G, A13938G, G16377A, G20002T, ∆21974-21994, C22009A, ∆22289-22294, G22770A, T22917G, G23311C, C23393T, C23423T, G25019T, T27504C, T28297C, A29694G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5_Saltation_Italy_3_seq.json?c=gt-nuc_4379&gmax=5379&gmin=3379&label=id:node_4039693

<img width="1305" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/34dab3ad-b411-46fc-8618-fea6fd56a168">

**Evidence**
These sequences come from different patients according to metadata. The first, collected August 23, is from Apulia, Italy, while the two most recent (collected Sept 22) are from Abruzzo, Italy. These regions are not far from each other but do not share a border. The Apulia sequence has no coverage from S:255-421, so I have assumed it has S:R403K like the other two sequences.
 
It’s rare to see lineages with large deletions in spike, like ∆138-144, transmit. I could be wrong, but I don’t think there’s ever been a designated lineage with ∆138-144 or ∆138-145, despite these being not uncommon in chronic-infection singlets. My guess is that such large deletions efficiently evade antibodies but are destabilizing, making them advantageous within a host but deleterious between hosts.

ORF1a:S1372A is convergent in chronics but otherwise very rare. ORF1a:S4119A is extremely rare, with just 159 sequences all time and 12 in 2023.
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18209924, EPI_ISL_18326806, EPI_ISL_18326807
</details>

**Comment by FedeGueli** [comment]
apparently dying off, lets track it for a bit more

**Comment by ryhisner** [comment]
New sequence just showed up from Germany, collected October 24. 
EPI_ISL_18525840

Nucleotide mutations on the German branch: A3069G, C3619T, C3587T, A25998G
AA mutations: ORF1a:D935G, ORF1a:H1108Y
<img width="1306" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f6042299-4a7e-4394-bbea-a72536481a33">

**Comment by FedeGueli** [comment]
Still 4 and no  new sequence i m closing it
