### ISSUE TITLE
XCM (XBB -> DV.7.1) with S:D215Y (2 seqs, Denmark)

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#894]
Query: Spike_V83A, Spike_V213G, Spike_D215Y
Collection dates: Both 9/18. 
Patient metadata unable to confirm they're different patients. 

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/4e3baedd-781a-42e3-96bc-a772ffa8d063)

This caught my eye since S:215 mutations are defining in two larger variants already, XBC and then FK.1, with FK.1 being a CH.1.1 derivative and therefore having some similarity to XCM.  
Although the proposed variant has S:D215Y, XBC has S:D215H, and FK.1 has S:D215G.

**Comment by FedeGueli** [comment]
It is also defining of XBB.1.17.1

**Comment by FedeGueli** [comment]
no sequence came from this closing for now
