### ISSUE TITLE
FL.1.5.1 + ORF9b:S50L, ORF1a:E2861D (54)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#895]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/45bede99-c518-4401-a47c-9f909a064539)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_62dd_8b4000.json?c=gt-nuc_8848&gmax=9848&gmin=7848&label=id:node_3627083

gisaid query: A8848C, C28432T

First Seq: 2023-08-09
Most Recent: 2023-09-19

OR598574.1 OR598489.1 OR603637.1 OR603845.1 OR598586.1 EPI_ISL_18303881 OR598287.1 EPI_ISL_18277996 OR564596.1 OR600044.1 EPI_ISL_18305560 EPI_ISL_18260398 OR495345.1 OR599866.1 OR600025.1 OR598577.1 OR599951.1 OR597971.1 EPI_ISL_18303796 OR603677.1 OR599706.1

**Comment by FedeGueli** [comment]
Thank you!
