### ISSUE TITLE
XBB.1.16 with S:K356T, already showing steps of S:F157S then S:F456L (7 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#897]
**Defining Mutations:** `XBB.1.16` > `T13518C` > `A22629C(S:K356T)`
**Query:** `T13518C, G18703T, A22629C`
**Earliest seq:** 2023-06-23 (`EPI_ISL_18036655`, Guangdong, China)
**Latest seq:** 2023-09-22 (`EPI_ISL_18330303`, Fujian, China)
**Sampled Countries:** China (3), USA (2: ex. China), New Zealand (1), South Korea (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18036655, EPI_ISL_18138500, EPI_ISL_18138509, EPI_ISL_18254277, EPI_ISL_18292130, EPI_ISL_18293504, EPI_ISL_18330303`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2df58_9105f0.json?f_userOrOld=uploaded%20sample&label=id:node_3489468
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/045edbdb-2309-4647-ab62-d222ebbaa712)

**Trivia:**
- The sequence from New Zealand has an insert of 3 nuc at the end of ORF8 so it's pulled under `XBB.1.16 > A28254C(S:I121L) > T28251C(S:F120L)` 
- There's also a side-branch follows `XBB.1.16 > T13518C > T17250G > T25251C(S:V1230A) > G3246A(ORF1a:S994N), C3736T, G23401T(S:Q613H), C23585A(S:Q675K)` quite recent as well

Query for the 456L branch: T13518C, G18703T, A22629C,C583T (Edited)

**Comment by FedeGueli** [comment]
No recent sample closing it
