### ISSUE TITLE
XBB.1.5.27 with S:S256L (58 seqs, 4 countries, mainly in the USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#90]
**Defining mutations:** _(On XBB.1.5.27's defining C22995G/S:T478R)_ > C22329T(S:S256L)
**Query:**  C22995G, C22329T, A3309G
**Earliest seq:** 2023-01-25 (Colorado, USA, EPI_ISL_16896184)
**Latest seq:** 2023-05-22 (Canada, EPI_ISL_17727024)
**Sampled in Countries:** USA (52), New Zealand (3), Canada (2), Japan (1)

<details><summary>GISAID Genomes: </summary>
EPI_ISL_16896184, EPI_ISL_17058945, EPI_ISL_17162463, EPI_ISL_17169891, EPI_ISL_17181335, EPI_ISL_17196749, EPI_ISL_17196756, EPI_ISL_17236731, EPI_ISL_17236737, EPI_ISL_17237829, EPI_ISL_17278347, EPI_ISL_17278774, EPI_ISL_17280909, EPI_ISL_17320946, EPI_ISL_17323673, EPI_ISL_17428855, EPI_ISL_17445172, EPI_ISL_17445286, EPI_ISL_17468523, EPI_ISL_17475142, EPI_ISL_17477711, EPI_ISL_17477974, EPI_ISL_17491692, EPI_ISL_17491693, EPI_ISL_17492231, EPI_ISL_17500364, EPI_ISL_17526886, EPI_ISL_17527211, EPI_ISL_17543651, EPI_ISL_17543823, EPI_ISL_17551656, EPI_ISL_17551657, EPI_ISL_17588202, EPI_ISL_17588501, EPI_ISL_17589298, EPI_ISL_17590310, EPI_ISL_17612017, EPI_ISL_17616806, EPI_ISL_17626616, EPI_ISL_17639624, EPI_ISL_17652746, EPI_ISL_17652846, EPI_ISL_17669810, EPI_ISL_17669811, EPI_ISL_17669880, EPI_ISL_17670037, EPI_ISL_17674301, EPI_ISL_17675229, EPI_ISL_17686050, EPI_ISL_17688676, EPI_ISL_17706774, EPI_ISL_17727024, EPI_ISL_17739840, EPI_ISL_17740066, EPI_ISL_17740181, EPI_ISL_17758368, EPI_ISL_17758399, EPI_ISL_17759677
</details>

<details><summary>GenBank Genomes: </summary>
USA/AZ00178199/2023|OQ821305.1|2023-03-26, 
USA/AZ00178514/2023|OQ815834.1|2023-04-05, 
USA/AZ00179141/2023|OQ872848.1|2023-04-17, 
USA/AZ00179486/2023|OQ926174.1|2023-04-23, 
USA/AZ-2023-0441/2023|OQ546152.1|2023-02-12, 
USA/AZ-2023-0609/2023|OQ597873.1|2023-03-01, 
USA/AZ-2023-0613/2023|OQ591762.1|2023-02-26, 
USA/AZ-2023-0678/2023|OQ708465.1|2023-03-05, 
USA/UT-IDEL-2023031636_2023/2023|OQ681113.1|2023-03-12, 
USA/UT-UPHL-230407446698/2023|OQ802989.1|2023-03-29, 
USA/UT-UPHL-230407906631/2023|OQ803167.1|2023-04-03
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8f37_170b00.json?f_userOrOld=uploaded%20sample

![XBB 1 5 27+S_S256L](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/71a866ce-7737-4674-b044-697621ce6205)

**Trivia:**
- There's another smaller branch goes with C7926T(ORF1a:A2554V), C25614T first, then C22329T(S:S256L), 3 seqs (EPI_ISL_17669880, EPI_ISL_17669810, EPI_ISL_17669811). However, I checked those 2 outlier seqs without S:S256L OQ892833.1 and OQ892776.1, those probably are dropouts. So if they are the same branch, there'll be at least extra 5 seqs.
![dropouts](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/eb26d2dc-149a-49b0-832d-7cdf4270ceb3)
- S:S256L is quite convergent, happens to be the definition of CM.9, BQ.1.8.1, FF.1 (BQ.1.8.2.1), BQ.1.1.31, XBB.1.24.3, XBC, etc. It appears on @FedeGueli 's XBB.1.5 spike diversity tracker cov-lineages/pango-designation#1510 too. There's another proposal #19 on XBB.1.9.1 as well.
- Somehow gisaid query doesn't catch all sequences, finds only 47. There can be found on UShER. All sequences listed above are imported from UShER/nextclade generated TSV, finds 58.
- There are quite a few sequences not on GISAID yet: OQ821305.1, OQ815834.1, OQ872848.1, OQ926174.1, OQ546152.1, OQ597873.1, OQ591762.1, OQ708465.1, OQ681113.1, OQ802989.1, OQ803167.1
- The ORF1a:A2554V > S:S256L branch probably caused by dropouts from: USA/UT-UPHL-230426999947/2023|OQ892833.1|2023-04-18, 
USA/UT-UPHL-230426756668/2023|OQ892776.1|2023-04-11

**Comment by FedeGueli** [comment]
41 as today it appears slow. If anything doesnt change it will be closed next week

**Comment by FedeGueli** [comment]
52 on Gisaid now with Canada, Arizona and Tennessee
