### ISSUE TITLE
FD.4 (XBB.1.5.15.4) mini-saltation with ORF1b:M2260V (nsp15_M209V), S:T478R, S:T883I, M:R146H and ORF9b:Q34L (35 seqs, mainly in USA, 2 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#900]
**Defining Mutations:** `FD.4 (XBB.1.5.15.4)` > `C11878A` > `C14877T, A15426G, A20245G(ORF1b:M2260V), G21204A, C24210T(S:T883I), T26897C, C27213T, A28384T(ORF9b:Q34L)` > `C22995G(S:T478R)` > `G26959A(M:R146H)`
**Query:** `C11878A, A15426G, C24210T`
**Earliest seq:** 2023-07-11 (`EPI_ISL_18045374`, California, USA)
**Latest seq:** 2023-09-02 (`EPI_ISL_18305989`, Utah, USA)
**Sampled Countries:** USA (26: CA/19; UT/5; HI/2), Mexico (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18045374, EPI_ISL_18081373, EPI_ISL_18114211, EPI_ISL_18125093, EPI_ISL_18137471, EPI_ISL_18144489, EPI_ISL_18144558, EPI_ISL_18145046, EPI_ISL_18145182, EPI_ISL_18145638, EPI_ISL_18145766, EPI_ISL_18222206, EPI_ISL_18225078, EPI_ISL_18240729, EPI_ISL_18240782, EPI_ISL_18241273, EPI_ISL_18260291, EPI_ISL_18260648, EPI_ISL_18279496, EPI_ISL_18305989, EPI_ISL_18311785, EPI_ISL_18311888, EPI_ISL_18316574, EPI_ISL_18318705, EPI_ISL_18319003, EPI_ISL_18319438, EPI_ISL_18319483`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1e2b1_931cc0.json?f_userOrOld=uploaded%20sample&label=id:node_3838256
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7c84f8a4-ad29-48d5-8c8e-a5f39ab4e445)

**Trivia:**
- 2 seqs `EPI_ISL_18144489` and `EPI_ISL_18145638` has dropout around `spike_478` or `membrane_146`, so this would be considered a 10-nuc mini-saltation
- Already has a singlet with `S:F456L`: `EPI_ISL_18279496`

**Comment by FedeGueli** [comment]
Very interesting tree thx for spotting.
Likely it cannot compete tough.

**Comment by FedeGueli** [comment]
No new submission in the last two weeks very weird.

**Comment by FedeGueli** [comment]
> C11878A, A15426G, C24210T

quite old ones , just two from october

**Comment by FedeGueli** [comment]
3 only samples from October . i would close it.
