### ISSUE TITLE
HP.1.1 (XBB.1.5.55.1.1) with S:E554K (37 seqs, mainly in Mexico and USA, 5 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#901]
_a follow-up to #277_

**Defining Mutations:** `HP.1.1` > `G23222A(S:E554K)`
**Query:** `C22995G, G23222A, C28310T`
**Earliest seq:** 2023-07-07 (`EPI_ISL_17996102`, `ATL` airport, Georgia, USA, with travel history to: Mexico)
**Latest seq:** 2023-09-12 (`EPI_ISL_18321989`, Texas, USA)
**Sampled Countries:** Mexico (18: CHH/5; CMX/3; MEX/2; PUE/2; TLA/2; VER/2; AGU/1; NLE/1), USA (16: CA/7; TX/6; GA/3, ex. Mexico), Canada (1: AB), Denmark (1), UK (1: EN)

<details><summary>Genomes: </summary>

`EPI_ISL_17996099, EPI_ISL_17996102, EPI_ISL_17996124, EPI_ISL_18011950, EPI_ISL_18103909, EPI_ISL_18137389, EPI_ISL_18143828, EPI_ISL_18164044, EPI_ISL_18164079, EPI_ISL_18222870, EPI_ISL_18225585, EPI_ISL_18225610, EPI_ISL_18227341, EPI_ISL_18252579, EPI_ISL_18256232, EPI_ISL_18264834, EPI_ISL_18278262, EPI_ISL_18279566-18279568, EPI_ISL_18279571-18279572, EPI_ISL_18279593, EPI_ISL_18279649, EPI_ISL_18279680, EPI_ISL_18279701, EPI_ISL_18285514, EPI_ISL_18296044, EPI_ISL_18296052, EPI_ISL_18296099, EPI_ISL_18296105, EPI_ISL_18299154, EPI_ISL_18299158, EPI_ISL_18316208, EPI_ISL_18320076, EPI_ISL_18321989, EPI_ISL_18329025`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3787d_941d10.json?f_userOrOld=uploaded%20sample&label=id:node_3868087
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/693daaf3-1abe-43fb-9120-d7eabb84a103)

**Comment by FedeGueli** [comment]
It cannot compete : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C22995G%2CG23222A%2CC28310T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Closing for now
