### ISSUE TITLE
FL.2.2.1 (S:T307I) with S:G75S and S:K356T=A22629C (convergent with FL.2.3.1*) - 14 seqs (Canada, Wales)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#903]
FL.2.2*[=XBB.1.9.1*+T4579A+T21988C, A29086G,A22995G=S:K478R]+C4633T, G21785A (S:G75S)+A6475T(Orf1a:E2070D), A8475G(Orf1a: N2737S), G17721T,A22629C(S:K356T), G29086A +(reversion?)
Gisaid Inquiry:G27915T,G21785A,A22629C or _A6475T, A8475G, G17721T_ (**EDITED** to exclude old unrelated samples)
Earliest Sequence (of Canadian Cluster): EPI_ISL_18251183, ON, Canada, 09-02
Latest Sequence (New Wales one): EPI_ISL_18326126, Wales, 09-15
usher
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice15_genome_8f88_9fab80.json?label=id:node_5408306

<img width="1446" alt="Screenshot 2023-10-01 at 7 14 30 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/b4e2c936-1197-4926-a703-0e7e821b224d">

<img width="1370" alt="Screenshot 2023-10-01 at 7 08 16 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/aeb7d263-c643-4556-9ad3-33161fdd2a70">
This is the tree indicating its convergence (I searched S:K356T in XBB.1*, and discover this close to FL.2.3.1* tree)

**Comment by FedeGueli** [comment]
Closing this it was a cluster

**Comment by krosa1910** [comment]
Yeah, the thing showed up as a classic Canadian cluster, but I would monitor it as it seems to show sequences outside the cluster.

**Comment by FedeGueli** [comment]
> Yeah, the thing showed up as a classic Canadian cluster, but I would monitor it as it seems to show sequences outside the cluster.

Thx! it seems slow anyway
