### ISSUE TITLE
EG.5.1.1+Orf1a:V3660M+S:F186S(59 seqs, 4 countries, 2% Singapore)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#905]
EG.5.1.1+C2644T+G11243A(Orf1a:V3660M)+C3457T, T16383A,C25614T+T22119C(S:F186S)

GISAID query: C3457T,T16383A,T22119C
No. of seqs: 17(Singapore 16 UK 1)

First: EPI_ISL_18141194, Singapore, 2023-8-22
Latest: EPI_ISL_18307148, Singapore, 2023-9-20

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice30_genome_11595_a1f2b0.json?label=id:node_3656666)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6475d46a-cb20-45bc-914c-cfd55ea58889)

**Comment by FedeGueli** [comment]
2% locally in Singapore.

**Comment by aviczhl2** [comment]
23, Israek

**Comment by aviczhl2** [comment]
37, USA

**Comment by FedeGueli** [comment]
It is still a mainly singaporean sublineage and it cannot compete vs FLip there: https://cov-spectrum.org/explore/Singapore/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C3457T%2CT16383A%2CT22119C&analysisMode=CompareToBaseline&

**Comment by aviczhl2** [comment]
9/443=2% in the most recent Singapore batch. 
Considering 40% are BA.2.86* and 45% are Flip.

**Comment by aviczhl2** [comment]
Close this one as its sub-branch proposed in 2396.

**Comment by aviczhl2** [comment]
HK.34
