### ISSUE TITLE
GK.7 (XBB.1.5.70+N:D3G) with S:S446T, S:I472V, ORF3a:V55A, ORF8:I9T  (3 seqs, Greece, Finland) 

### ISSUE THREAD

**Issue by c19850727** [sars-cov-2-variants/lineage-proposals#907]
EPI_ISL_18314973 and EPI_ISL_18315125, collected in early September and uploaded on Sept. 27th (a bit old).

These 2 sequences belong to an undesignated subbranch of XBB.1.5.70 with N:D3G (A28281G), and further obtained the following mutations in a stepwise manner:
ORF1b:Y280C, ORF3a:V55A, 
ORF1a:V28I,
nuc A10114G, C18306T, A19005G,
S:S446T, S:I472V, ORF8:I9T

Query: G22899C, A22976G, T27919C (edited)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/86835836/4c32c0dc-dc05-4543-b5ab-ed5deea9ead2)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_dd34_ab32a0.json?c=gt-nuc_27919&gmax=29271&gmin=27271&label=id:node_3911976

**Comment by FedeGueli** [comment]
N:D3G was alpha defining if i recall well

**Comment by c19850727** [comment]
Fede it's N:D3L, but D3G was quite common in AY.122.

**Comment by FedeGueli** [comment]
> Fede it's N:D3L, but D3G was quite common in AY.122.

Ah ok thank you!

**Comment by krosa1910** [comment]
472 is very close to reportedly strong escape site of 473 ,lesser extent 475. I wonder does it also enhance escape of this variant. And it seems marginally escaping at some cost of ACE binding.

**Comment by FedeGueli** [comment]
+1 Finland collected on 2023-09-25

**Comment by Over-There-Is** [comment]
It's sublineage of GK.7 now.

**Comment by FedeGueli** [comment]
Parental branch designated GK.7

**Comment by FedeGueli** [comment]
No new sequence from this branch
