### ISSUE TITLE
GA.4 (XBB.1.17.1.4) small saltation with S:F186L, S:L585F and ORF1b:E1184D (14 seqs in Greece and Romania)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#908]
Defining mutations:
GA.4>T3442C>T3055C, G8185A, G17019T (ORF1b:E1184D), T22118C (S:F186L), C23315T (S:L585F), G25009A, T26103C
GISAID query: C23315T, G25009A, T26103C
Earliest seq: 2023-08-08 (Greece- EPI_ISL_18314349)
Most recent seq: 2023-09-07 (Greece- EPI_ISL_18315044)
Countries detected: Greece (12), Romania (2)

Usher Tree: (Yellow for the issue, Blue for GA.4.1)
![QQ截图20231002222618](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/028364d2-9268-4c8c-a9fa-3e506b90a3a0)

The saltation branch is neighbored with GA.4.1 (another important saltation branch of GA.4). 

Genomes:
EPI_ISL_18281784-18281785, EPI_ISL_18314349, EPI_ISL_18314472, EPI_ISL_18314790, EPI_ISL_18314811-18314813, EPI_ISL_18314897,
EPI_ISL_18314922, EPI_ISL_18314942-18314943, EPI_ISL_18314965, EPI_ISL_18315044

**Comment by FedeGueli** [comment]
Designated GA.4.3 via https://github.com/cov-lineages/pango-designation/commit/516ee4a9b416a596be17b7a3a5fb284c26a15bd5
