### ISSUE TITLE
XBB.1.5.70+ORF6:E55Q sublineage with ORF1a:N1555S, ORF1a:I2010V, S:N185I, and S:A475V (7 seq. Canada, USA, UK)

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#909]
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3AXBB.1.5.70*%26S%3AA475V%26ORF6%3AE55Q&
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/92840011-0c38-4883-9305-985b2081778d)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3506c_b42400.json?c=gt-S_475&gmax=25384&gmin=21563&label=id:node_3910201

Defining mutations:(EDITED)
XBB.1.5.70> Orf6:E55Q (G27364C) > Orf1a:I2010V (A4929G), Orf1a:N1555S (A6293G), C13019T, S:N185I (A22116T), S:A475V (C22986T)
  

Gisaid Query: A4929G, C13019T,A6293G (EDITED)

**Comment by FedeGueli** [comment]
Thank you. is it a new one not tracked before in the multiple lineages issue? (i ve added query and defining table)

**Comment by aviczhl2** [comment]
Designated GK.8.1 @FedeGueli

**Comment by FedeGueli** [comment]
Parenatl is now GK.8 via https://github.com/cov-lineages/pango-designation/commit/af7f5c4d7af42a831238d97bc759fefc0c0765ba
