### ISSUE TITLE
BQ.1.1 saltation  with S:K187E, T299I, T444K (rev), N450K, S:f456L, K462E, A484P, P1263S  (2 seq., France)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#912]
Proposal for a sublineage of BQ.1.1 
Earliest sequence: 19.08.2023 (France)
Countries detected: France

Edit: Now with usher tree.

nuc	unique	A438G, C878A, T6163A, T8138C, T8156C, G12565T, G12569A, C12623T, C14877T, G15598A, A22121G, C22458T, C22893A, T22912G, A22946G, G23012C, G24781A, T24943C, C25349T, A27724G, G27890A, A29183G
nuc	homoplasies	C4084T, C11003T, C22295T, T22928C, T23948C, C25587T, C26408T
nuc	reversionsToRoot	C22893A
S	unique	K187E, T299I, T444K, N450K, K462E, A484P, P1263S
S	homoplasies	H245Y, F456L, Y796H
S	reversionsToRoot	T444K
E	homoplasies	S55F
ORF7a	unique	T111A
N	unique	I304V
ORF1ab	unique	K58R, L205I, S2625P, S2631P, Q4100H, V4102I, P4120S, V5112I
ORF1ab	homoplasies	D1966E, H3580Y

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/45bca312-1f63-4909-aeef-2b9c01cb66d6)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/d4feb733-204b-4b74-9972-2c29ebabb24f)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2c3f6_c1e0c0.json?c=userOrOld&label=id:node_5198564

EPI_ISL_18338143
EPI_ISL_18338144

Gisaid query: A438G, C878A, T6163A (Edited)

**Comment by HynnSpylor** [comment]
Oh @FedeGueli they also get S:F456L (the only branch of BQ* to get S:F456L in recent three months)

**Comment by FedeGueli** [comment]
> Oh @FedeGueli they also get S:F456L (the only branch of BQ* to get S:F456L in recent three months)
> 
> S:A484P is considered to increase hACE2 binding (Cao et al.2023) ![QQ截图20231008171312](https://user-images.githubusercontent.com/121703496/273438475-a7cf2378-d0d3-42c8-9909-81a148570490.png)

Thx!

**Comment by ryhisner** [comment]
S:T444K is one of three common spike reversions in BQ* chronic-infection sequences. The first listed below also appear sin non-BQ* BA.5 lineages, and the second frequently occurs in all Omicron chronic-infection sequences. No other lineage, to my knowledge, has ever been characterized by three repeated spike reversions in chronic-infection sequences. The three spike reversions are:

• S:T444K
• S:A484E
• S:V486F

The first couple times I saw each of these, I assumed they were artifacts, but by now it's clear that all three are definitely real.

**Comment by FedeGueli** [comment]
No new sequence came for a long bit. closing it now thx
