### ISSUE TITLE
EG.5.1.1 recomb involving S:I1114T(25 seqs, 8 countries, 23 with Flip)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#914]
EG.5.1.1+T29625C(Orf10:F23S rev)+C15981T,T24903C(S:I1114T)+C2650T.G22927T(S:L455F)

The T29625C rev is most likely through recomb with anything that is not EG.5.1.

This branch seems not mentioned in #537 so worth a proposal.

GISAID query: C15981T,T24903C
No. of seqs: 10(China 6 Sweden 3 Norway 1)

First: EPI_ISL_18111103, Yunnan, 2023-7-30
Latest: EPI_ISL_18337642, Norway, 2023-9-11

GISAID query with S:L455F: C15981T,T24903C,,G22927T

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice37_genome_2e8db_ccd2b0.json?label=id:node_3650323)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/71c7fac4-9864-4375-b6a9-51f06e9f6c69)

**Comment by aviczhl2** [comment]
14, France

**Comment by FedeGueli** [comment]
> 14, France

could you argument a bit on the recombinant thing ?

**Comment by aviczhl2** [comment]
+1 Malaysia

**Comment by aviczhl2** [comment]
25, Iceland, Switzerland, France, UK

**Comment by FedeGueli** [comment]
pls propose it

**Comment by FedeGueli** [comment]
Designated XDL
