### ISSUE TITLE
JD.1* sublineage with S:P809T, 14 seqs in Ireland, England,Canada,France, Sweden, Japan, Belgium and Spain at 12-03

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#917]
Mutations on top of JD.1*:C14189T+C28087T (Pre-JD.1.1* mutation shared)+G13379A (Largest sibling of JD.1.1*, JD.1.1* got S:A475V instead)+T8806C, G18105T, C23987A
Gisaid Inquiry: T8806C, G18105T, C23987A
EPI_ISL_18274447, EPI_ISL_18280755, EPI_ISL_18295751,
EPI_ISL_18314150, EPI_ISL_18314167, EPI_ISL_18337690,
EPI_ISL_18342329

Earliest: 09-01 EPI_ISL_18274447 Ireland
Latest: 09-15 EPI_ISL_18337690 England

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a5c5_de8350.json?label=id:node_5410566
<img width="1442" alt="Screenshot 2023-10-04 at 6 38 50 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/69ed60ac-c15d-4261-8fa2-cd7dd03c83f7">

**Comment by FedeGueli** [comment]
13 with 3 new countries
