### ISSUE TITLE
XBB.1.17.1+17-nuc,13-aa including S:455F,456L,478R, Orf9b:T95M (6 seqs, 2 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#919]
XBB.1.17.1+G20173A(Orf1b:V2236I)+G13822A(Orf1b:V119I)+
T1354C, A1367G, C2592T, T3906C, A19307G, C25156T, G26959A,C6573T, G22927T, T22928C, A22995G, G26828C, C26895T, G27561T, C28567T ( S:L455F,F456L,K478R, M:R146H,H125Y, Orf1a: I368V, A776V, F1214S, S2103F, Orf1b: 1947R, Orf9b: T95M)

GISAID query:  T1354C, C2592T, A19307G(edited) 
No. of seqs: 4(Canada)

First: EPI_ISL_18305185, Canada, 2023-9-15
Latest: EPI_ISL_18343759, Canada, 2023-9-25

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice38_genome_43ff_e0ac70.json)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/10b7eb34-4d90-4678-9809-f576ebcf01f9)

**Comment by HynnSpylor** [comment]
1 more seq in New York, US
but the GISAID query should be changed: T1354C, C2592T, A19307G

**Comment by FedeGueli** [comment]
> 1 more seq in New York, US but the GISAID query should be changed: T1354C, C2592T, A19307G

Thank you Hynn. this has to be monitored if went up grwoing we will propose in the main page. please update in the comment so i got the notifications.

**Comment by aviczhl2** [comment]
No new seqs

**Comment by aviczhl2** [comment]
There seems to be a French recomb of this one and XBB.2.3.19.

**Comment by aviczhl2** [comment]
Designated GA.10.1

**Comment by aviczhl2** [comment]
It seems that GA.10.1 is designated as this branch together with the new French recomb.
