### ISSUE TITLE
FL.4 (XBB.1.9.1.4) with S:L452R, ORF8:V81A (21 seqs, mainly Singapore, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#92]
**Defining mutations:** _(On top of FL.4's defining G16741T/ORF1b:V1092F)_ > A28615G > A19314T > C7945T > T22917G(S:L452R), T28135C(ORF8:V81A) >
**Query:** A19314T, C7945T, T22917G, T28297C
**Earliest seq:** 2023-04-04 (EPI_ISL_17496040, Singapore)
**Latest seq:** 2023-05-23 (EPI_ISL_17724768, Singapore)
**Sampled in Countries:** Singapore (9), USA (Texas, 1)
**Genomes:** EPI_ISL_17496040, EPI_ISL_17539825, EPI_ISL_17588652, EPI_ISL_17596115, EPI_ISL_17631575, EPI_ISL_17670250, EPI_ISL_17724767, EPI_ISL_17724768, EPI_ISL_17724780, EPI_ISL_17724786
**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4135d_5b3900.json?f_userOrOld=uploaded%20sample
Downsampled
![XBB 1 9 1 4+S_L452R](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d0fc7e24-c493-46e7-a4f7-3b648b24dfd8)
Detailed 
![XBB 1 9 1 4+S_L452R_Detailed](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/68477289-9e5e-4357-9162-380dff182cbf)

**Trivia:**
- T22917G(S:L452R) doens't seems to go well on XBBs+S:F486P so far, unlike the double nuc mutations C22916A & T22917G on XAY or XBC.1.6.
- There's another proposal by @FedeGueli on #53 , let's see how it does on multiple branches of XBB.1.9*.

**Comment by FedeGueli** [comment]
Found this one today me too. good catch. 

The Singaporean samples are all local cases (within different age groups)

**Comment by FedeGueli** [comment]
Lets keep this open for a while.

**Comment by FedeGueli** [comment]
Designated FL.4.7
