### ISSUE TITLE
XBB.1.16 with ORF1a:A3889T, S:F456L then saltation with ORF1a:G963D, ORF1a:K2045R, S:E554K and ORF3a:M260T (84 seqs, mainly in France, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#922]
**Defining Mutations:** `XBB.1.16` > `G11930A(ORF1a:A3889T/nsp7_A30T)` > `T22928C(S:F456L`) > `G3153A(ORF1a:G963D/nsp3_G145D), A6399G(ORF1a:K2045R/nsp3_K1227R), C7720T, T12673C, T19065G, C20133T, T20484C, C20628T, G23222A(S:E554K), T26171C(ORF3a:M260T), A28984G`
**Query:** `A6399G, G11930A, T22928C`
**Earliest seq:** 2023-08-07 (`EPI_ISL_18147969`, Bouches-du-Rhône, France)
**Latest seq:** 2023-09-20 (`EPI_ISL_18331883`, England, UK
**Sampled Countries:** France (48), UK (2: EN), Ireland (1), Israel (1), Switzerland (1), USA (1: NY)

<details><summary>Genomes: </summary>

`EPI_ISL_18147969, EPI_ISL_18215130-18215131, EPI_ISL_18221730, EPI_ISL_18228747, EPI_ISL_18228846, EPI_ISL_18228979, EPI_ISL_18229085, EPI_ISL_18229098, EPI_ISL_18229239, EPI_ISL_18229335, EPI_ISL_18229340, EPI_ISL_18229633, EPI_ISL_18229636, EPI_ISL_18229643, EPI_ISL_18258298, EPI_ISL_18258365, EPI_ISL_18258376, EPI_ISL_18258418, EPI_ISL_18258447, EPI_ISL_18258455, EPI_ISL_18258462, EPI_ISL_18258467, EPI_ISL_18258469, EPI_ISL_18258821, EPI_ISL_18273211, EPI_ISL_18280744, EPI_ISL_18280782, EPI_ISL_18295375, EPI_ISL_18295530, EPI_ISL_18295558, EPI_ISL_18295566, EPI_ISL_18295578, EPI_ISL_18295592, EPI_ISL_18295594, EPI_ISL_18295615, EPI_ISL_18300169, EPI_ISL_18309232, EPI_ISL_18313720, EPI_ISL_18314249, EPI_ISL_18322392, EPI_ISL_18326506, EPI_ISL_18326563, EPI_ISL_18326583, EPI_ISL_18326937, EPI_ISL_18326958, EPI_ISL_18327135, EPI_ISL_18327153, EPI_ISL_18327249, EPI_ISL_18327291, EPI_ISL_18327315, EPI_ISL_18327420, EPI_ISL_18331883, EPI_ISL_18332023`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35340_eb6250.json?f_userOrOld=uploaded%20sample&label=id:node_3791530
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/9d72b1d2-48b1-46cd-8734-b3e9f72e123b)

**Comment by FedeGueli** [comment]
please propose it : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=A6399G%2CG11930A%2CT22928C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated XBB.1.16.27 via https://github.com/cov-lineages/pango-designation/commit/f38283e4baec67257c3b3d3c04a9e9cfe3548859
