### ISSUE TITLE
EG.6.1* with S:K356T (Seemingly three branches tot 18 seqs) at 10-17

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#926]
Gisaid Inquiry: A22629C,T27346C,T22928C

**Tree 1**: 
6seqs in Isarel
Earliest:  EPI_ISL_18300214 09-14
Latest: EPI_ISL_18345598 09-28
Inquiry: A22629C,T27346C,T22928C,C2227T

**Tree 2**: 
6 seqs in US
Earliest: EPI_ISL_18279490 09-06, Utah, US
Latest: EPI_ISL_18351558 09-28, same place
Inquiry: A22629C,T27346C,T22928C,C9195A

**Singlet 1**:  
EPI_ISL_18301761 England, 09-12
Inquiry: A22629C,T27346C,T22928C,A20898G

Global downsampled Usher Tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2951e_f92d00.json?f_userOrOld=uploaded%20sample&label=id:node_1080018
--
<img width="1285" alt="Screenshot 2023-10-06 at 12 54 30 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/2661267b-3c60-4b71-9918-2e3d0ef87d7d">

**Comment by FedeGueli** [comment]
we will see if there is any advantage. thx for tracking them

**Comment by krosa1910** [comment]
Another sequence uploaded in Israel (lineage A), not sure if the upload there is impeded by the war

**Comment by FedeGueli** [comment]
No recent sample closing it
