### ISSUE TITLE
FL.1.5.1 with ORF8:T11I and S:L455F (4 seqs, Singapore)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#927]
**Defining Mutations:** `FL.1.5.1` > `C21036T` > `C920T, C27925T(ORF8:T11I), C29721T` > `C10156T` > `G22927T(S:L455F)`
**Query:** `C10156T, G20060T, G22927T`
**Earliest seq:** 2023-09-26 (`EPI_ISL_18355183`, Singapore)
**Latest seq:** 2023-09-27 (`EPI_ISL_18355185`, Singapore)
**Sampled Countries:** Singapore (3)

<details><summary>Genomes: </summary>

`EPI_ISL_18355183-18355185`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_379a6_19ef0.json?f_userOrOld=uploaded%20sample&label=id:node_11967904
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/69b13caf-2669-4fba-89e5-8fda88169d37)

**Comment by FedeGueli** [comment]
no new sequence closing it. let me know if new seqs will pop up
