### ISSUE TITLE
JJ.1+5-nuc,5-aa including Orf1a:T1589I and S:A475V (3 seqs, France)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#928]
JJ.1+C25624T(Orf3a:H78Y)+A4079C(Orf1a:S1272R)+C5031T, G21019A,C22986T(Orf1a:T1589I, S:A475V, Orf1b:A2518T)

GISAID query: C5031T, G21019A,C22986T
No. of seqs: 2(France)

EPI_ISL_18356935, EPI_ISL_18356959, 2023-9-18

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice53_genome_10c4_bf420.json?f_userOrOld=uploaded%20sample&label=id:node_11969070)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/5237e72b-385b-4172-8b6b-8f2e4aca8436)

**Comment by FedeGueli** [comment]
Convergence going on

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
Thank you
