### ISSUE TITLE
HW.1.1 (XBC.1.6.3.1.1) with ORF1b:I1822M (nsp14_I298M), ORF1a:T2152I (nsp3_T1334I) and S:Q613H (20 seqs, mostly in Ireland, Netherlands)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#930]
**Defining Mutations:** `HW.1.1` > `A18933G(ORF1b:I1822M)` > `T27384C` > `C6720T(ORF1a:T2152I), G23401T(S:Q613H)`
**Query:** `A18933G, A22940C, G23401T`
**Earliest seq:** 2023-09-24 (`EPI_ISL_18321572`, Dublin, Ireland)
**Latest seq:** 2023-10-04 (`EPI_ISL_18356737`, Dublin, Ireland)
**Sampled Countries:** Ireland (11)

<details><summary>Genomes: </summary>

`EPI_ISL_18321572, EPI_ISL_18356699, EPI_ISL_18356703, EPI_ISL_18356717, EPI_ISL_18356721, EPI_ISL_18356723, EPI_ISL_18356730, EPI_ISL_18356732-18356734, EPI_ISL_18356737`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2f4b7_176580.json?label=id:node_3330266
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d9ee21e4-1b86-48d7-99ad-a482b5edcedf)

**Trivia:**
- Looks like a care home cluster according to metadata; upstream to this chain probably related to `Ireland/D-BH-970074230/2023|EPI_ISL_18315276|2023-09-04`
- Most seqs have N at `nuc 15908`, except for one that has Ns elsewhere but an insertion `ins15909GAT/nsp12_ins823D`
![Ns](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/cae075f6-cee5-493b-aa02-6ed4b49fcd55)

**Comment by FedeGueli** [comment]
+1 NDL

**Comment by FedeGueli** [comment]
Looking at metadata it seems some sort of long term care outbreak .

**Comment by FedeGueli** [comment]
Thx still  i dont think it is fast

**Comment by FedeGueli** [comment]
Closing it now
