### ISSUE TITLE
Weird FLip Tree under HK* with S:G1267R (11 NZL,AUS, Singapore)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#931]
Inquiry: G25361A,A6438G
Mutations: Unsure because of S:257 rev? Orf1a:Q2058R, N:Q229R S:G1267R
Earliest: EPI_ISL_18347639 New Zealand 09-13
Latest  :EPI_ISL_18355046 Singapore 09-25
Usher: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2854d_1da010.json?f_userOrOld=uploaded%20sample
<img width="1028" alt="Screenshot 2023-10-07 at 6 25 42 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/56c29584-e135-4d6b-b8aa-8a1e3edb0c45">

<img width="1028" alt="Screenshot 2023-10-07 at 6 26 02 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/c2b9c829-c946-46c0-83b9-c16d6f79957a">

It is defined as HK.1* (HK*+S:G257V) yet the real S: 257 position is "unsure" to me.

**Comment by FedeGueli** [comment]
thank you for focusing on this. it is brnach 48 of #537
