### ISSUE TITLE
XBB.1.16.6 sublineage with S:T346I and S:K356T (4 seqs in US and Netherlands)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#932]
Defining mutations:
XBB.1.16.6>C29296T>G4255A, C22599T (S:T346I), A22629C (S:K356T), C28005T
GISAID query: G4255A, G22599T, A22629C
Earliest seq: 2023-09-04 (NY, US- EPI_ISL_18291036)
Most recent seq: 2023-09-22 (NY, US- EPI_ISL_18358831)
Countries detected: US (3), Netherlands (1)
Usher Tree:
![QQ截图20231009000435](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/715a8cc6-8005-4783-8ea6-1a6d97b25a10)

Another branch of S:K356T+S:F456L combo, with a further change on site S:346. 
Genomes:
EPI_ISL_18291036, EPI_ISL_18300048, EPI_ISL_18357012, EPI_ISL_18358831

**Comment by FedeGueli** [comment]
no new seqs closing it
