### ISSUE TITLE
EG.5.1.6 + ORF8:F120L, (ORF8:I121- or ORF8:F121L), and S:L452R (14) only in USA

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#933]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/6a674df5-84a1-4682-a51a-3b8506233194)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6013_35ebb0.json?c=gt-nuc_26409&gmax=27409&gmin=25409&label=id:node_3415763

First Seq: 2023-09-05
Most Recent: 2023-09-22

Gisaid Query: I'm unable to find the query

OR616446.1 OR623519.1 OR599260.1 OR623641.1 OR623691.1 OR618888.1 EPI_ISL_18341561 OR616443.1 OR603490.1 OR600039.1 OR569249.1 OR599600.1 OR599627.1 OR618767.1

**Comment by FedeGueli** [comment]
Thank you @Fearuncle this is just HV.1 misplaced due to a flip flop mutation
![Schermata 2023-10-09 alle 11 06 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/20e85adc-258d-4285-9eb8-7d7381c04e85)

cc @angiehinrichs
