### ISSUE TITLE
Potential recombination between XBB and XBC  (3. seq., Philippines, Singapore)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#935]
Proposal for a sublineage of XBB and XBC 
Earliest sequence: 04.09.2023 (Philippines)
Countries detected: Philippines; Singapore

nuc	unique	G7058A, G22577C, C22664A, G22895C, G22927A, T23042C, C25584T, A26275G, C26577G, G26709A, C26767T, G27915T, A29510C
nuc	homoplasies	T3478C, C4586T, A7766G, A10449C, T15030C, A17207G, A19890G, T21846C, A22116G, C22329T, G22599C, T22896C, G22898A, T22942G, T23018C, T23019C, T23031C, C23123A, C25416T, C26060T, C26270T, C26606T, C26858T, A27259C, G27382C, A27383T, T27384C, T28297C, G28376A, C29762T
nuc	reversionsToRoot	A10449C, T21846C, C26767T
S	unique	D339H, L368I, V445P, S494P
S	homoplasies	I95T, N185S, S256L, R346T, G446S, N460K, F486P, F490S, P521T
S	reversionsToRoot	I95T
ORF3a	homoplasies	T223I
E	unique	T11A
E	homoplasies	T9I
M	unique	Q19E, A63T, T82I
M	reversionsToRoot	T82I
ORF6	homoplasies	D61L
ORF8	unique	G8*
N	unique	S413R
N	homoplasies	A35T
ORF1ab	unique	G2265S
ORF1ab	homoplasies	I2501V, H3395P, Y5648C
ORF1ab	reversionsToRoot	H3395P

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/96e945d4-0158-4fa8-b9dc-fca89df154be)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/4fadda8b-a8a9-4981-9654-50e9dc16b921)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1d9a8_3dc3e0.json?f_userOrOld=uploaded%20sample

EPI_ISL_18342927
EPI_ISL_18361826
EPI_ISL_18361978

Gisaid query: G22927A, T23042C, C25584T

**Comment by FedeGueli** [comment]
I think there i third from Philippines EPI_ISL_18342927

**Comment by FedeGueli** [comment]
oh already modified thx

**Comment by HynnSpylor** [comment]
Yes the Usher and GISAID temporarily classified it as "B.1.1.529"
The breakpoint may be between S:256 and S:339 (Before =XBC, After= XBB) 
The XBB* part is likely from XBB.1.16.11* (with T28297C, G27915T, C23123A etc.)

**Comment by FedeGueli** [comment]
> Yes the Usher and GISAID temporarily classified it as "B.1.1.529" The breakpoint may be between S:256 and S:339 (Before =XBC, After= XBB) The XBB* part is likely from XBB.1.16.11* (with T28297C, G27915T, C23123A etc.)

misisng T478R tough. so maybe it got reverted :? Philippines has had already some lineages with reversion to T at 478

**Comment by corneliusroemer** [comment]
You guys are fast! Just came across this one independently. Looks pretty solid to me, given the fact it's two countries, they cluster well, there are clear private mutations etc.

**Comment by corneliusroemer** [comment]
XBC donor is a direct descendant of `Philippines/PH-PGCMIN3313/2023|EPI_ISL_17948931|2023-05-26` (XBC.1.7.1)

XBB part is likely FL.23.1 (has both 494P and 521T, was seen most commonly in Philippines and doesn't require any reversions)

=> designated XCU

**Comment by FedeGueli** [comment]
Designated XCU via https://github.com/cov-lineages/pango-designation/commit/4806a9be4ec527e46ed135192cde0f23861ccfc0

**Comment by FedeGueli** [comment]
> XBC donor is a direct descendant of `Philippines/PH-PGCMIN3313/2023|EPI_ISL_17948931|2023-05-26` (XBC.1.7.1)
> 
> XBB part is likely FL.23.2.1 (has both 494P and 521T, was seen most commonly in Philippines and doesn't require any reversions)
> 
> => designated XCU

Thx Cornelius great catches for donors.

**Comment by JosetteSchoenma** [comment]
XCU

**Comment by FedeGueli** [comment]
12 now but 3/36 in Philippines

**Comment by ryhisner** [comment]
8/17 sequences from the Philippines uploaded today—collection dates Nov 4 to Nov 14—are XCU.

**Comment by FedeGueli** [comment]
Thx @ryhisner for the head up it is growing  a lot. i found 20 samples seuqenced in or from philippines in November and the variant scenario is the following:
8 XCU
7 XBB.2.3.3/GJ/JE
3 JD.1.1 
1 JN.1 
1 HN.5
