### ISSUE TITLE
FL.1.5 with ORF1a:E553K (nsp2_E373K), ORF1a:E792K (nsp2_E612K), S:N164H and ORF9b:Q70L (30 seqs, mainly in UK, 10 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#937]
**Defining Mutations:** `FL.1.5` > `G1922A(ORF1a:E553K), C10789T` > `G2639A(ORF1a:E792K), A22052C(S:N164H), A28492T(ORF9b:Q70L)`
**Query:** `G1922A, C10789T, A22052C`
**Earliest seq:** 2023-07-18 (`EPI_ISL_18112105`, Baden-Württemberg, Germany)
**Latest seq:** 2023-09-18 (`EPI_ISL_18343084`, Veneto, Italy)
**Sampled Countries:** UK (13: EN/7; WS/4; SC/2), Canada (2: AB; SK), France (2), Germany (2), Italy (2), Ireland (1), Netherlands (1), Sweden (1), USA (1: UT)

<details><summary>Genomes: </summary>

`EPI_ISL_18097976, EPI_ISL_18112105, EPI_ISL_18118966, EPI_ISL_18137065, EPI_ISL_18142581, EPI_ISL_18209311, EPI_ISL_18216154, EPI_ISL_18221408, EPI_ISL_18234220, EPI_ISL_18250141, EPI_ISL_18268518, EPI_ISL_18274303, EPI_ISL_18278635, EPI_ISL_18279428, EPI_ISL_18281583, EPI_ISL_18294323, EPI_ISL_18302381, EPI_ISL_18302388, EPI_ISL_18302523, EPI_ISL_18302598, EPI_ISL_18302608, EPI_ISL_18314131, EPI_ISL_18327260, EPI_ISL_18332383, EPI_ISL_18343084`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3b169_4005d0.json?f_userOrOld=uploaded%20sample&label=id:node_3392443
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/062ee1b0-75c9-4df4-99b4-4fad2fc4a7f4)

**Trivia:**
- `S:N164H` is another rare mutation, only sampled about 630-ish times during the whole pandemic, much rarer than the `BA.2.3.20`counterpart `S:N164K`. Recent appearance happens on this lineage and [a majority of `EG.4.5`](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_389db_3ffb80.json?f_userOrOld=uploaded%20sample&label=id:node_3465160) , another example of FL*/EG* ~~_telekinesis_~~ convergence

<details><summary>view of EG.4.5 tree</summary>

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4bc614cb-8bfe-4592-bdf0-f7e52ffc5879)
</details>

**Comment by FedeGueli** [comment]
Interesting but very likely not fast enough :https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G1922A%2CC10789T%2CA22052C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
N164 mutated to K was in the BA.2.12.1 biggest sublineage and in BA.2.3.20

**Comment by FedeGueli** [comment]
3 samples only from october
