### ISSUE TITLE
HW.1.1 (XBC.1.6 + S:N460H) with S:A435S (7 seq, Australia, Hong Kong, Japan, South Korea)

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#938]
Query: Spike_R346S, Spike_A435S ( or  A11746G,G22865T Edited)
First collected on August 28, most recently on September 20 
[USHER LINK](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_506dc_5045b0.json?c=userOrOld&label=id:node_2823839)(edited)

I mostly think it's interesting because this is one of the more common spike mutations on HW.1.1 now, and in 3 countries, but it is pretty rare overall, and especially rare on XBB (less than half of S:A435S in the last 6 months is on XBB). 

I don't think it's likely this proposed variant will survive, but I'll move this to the main page if it's showing legitimate signs of growth.

**Comment by FedeGueli** [comment]
Slow closing it for now
