### ISSUE TITLE
FL.1.5.1 with ORF1a:A801V, ORF1a:A3837V, ORF1b:A1428V, ORF1b:S2338L, S:N188K, ORF9b:G31E (25 in France) 

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#939]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/7fc9b249-0c43-4bda-8370-10f61fb9872c)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_330fb_44bfa0.json?c=gt-nuc_17750&gmax=18750&gmin=16750&label=id:node_3385274
First Seq: 2023-09-10
Most Recent: 2023-09-27
Gisaid Query: C17750T, T22126G

EPI_ISL_18295425 EPI_ISL_18295424 EPI_ISL_18326630 EPI_ISL_18327040 EPI_ISL_18326615 EPI_ISL_18326659 EPI_ISL_18326519 EPI_ISL_18326676 EPI_ISL_18357144 EPI_ISL_18357135 EPI_ISL_18326500 EPI_ISL_18326495 EPI_ISL_18326547 EPI_ISL_18357519 EPI_ISL_18357143 EPI_ISL_18326644 EPI_ISL_18326520 EPI_ISL_18326453 EPI_ISL_18326646

**Comment by FedeGueli** [comment]
It maybe is a cluster, lets monitor closely how it evolves thx for spotting

**Comment by FedeGueli** [comment]
Slowed down closing it
