### ISSUE TITLE
Multiple XCH* Lineages with S:T478R

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#941]
<a name="task_header"></a>
```[tasklist]
### Multiple `XCH*` Lineages with `S:T478R`
- [ ] [Branch 1](#branch_1): **XCH.1** > C12710T, C22995G(**S:T478R**), C29284T [Query: `G9220A, C12710T, C22995G, -C151T`, 15 seqs, 12/22]
- [ ] [Branch 2](#branch_2): **XCH.1** > T23662C > C6285T(ORF1a:T2007I), A20916G, C22995G(**S:T478R**) [Query: `G9220A, C22995G, T23662C`, 4 seqs, 12/18], (former main proposal)
- [ ] [Branch 3](#branch_3): **XCH** > C25916A(ORF3a:T175K) > C29668T > G1235A(ORF1a:D324N) > C22995G(**S:T478R**) [Query: `G1235A, C22995G, C25916A`, 6 seqs, 12/20] 
```
- [Singlets](#singlets), [Doublets](#doublets) and [Triplets](#triplets)

<a name="branch_1"></a>
### Branch 1

**Defining Mutations:** `XCH.1` > `C12710T, C22995G(S:T478R), C29284T`
**Query:** `G9220A, C12710T, C22995G, -C151T`
**Earliest seq:** 2023-10-02 (`EPI_ISL_18425733`, Alberta, Canada)
**Latest seq:** 2023-10-20 (`EPI_ISL_18455861`, Alberta, Canada)
**Sampled Countries:** Canada (3: AB)

<details><summary>Genomes: </summary>

`EPI_ISL_18425733, EPI_ISL_18455861, EPI_ISL_18455937`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice3_genome_test_2c2dc_34ac70.json?label=id:node_11062811
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/58367f43-1703-406d-9a14-fd95ae57a524)

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2 (former proposal)

**Defining Mutations:** `XCH.1` > `T23662C(S:G700)` > `C6285T(ORF1a:T2007I), A20916G, C22995G(S:T478R)`
**Query:** `T9952C, C22995G, T23662C`
**Earliest seq:** 2023-09-06 (`EPI_ISL_18282450`, Maryland)
**Latest seq:** 2023-09-25 (`EPI_ISL_18369354`, Pennsylvania)
**Sampled Countries:** USA (2: MD; PA)

<details><summary>Genomes: </summary>

`EPI_ISL_18282450, EPI_ISL_18369354`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ce04_655500.json?label=id:node_3693791
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/8969bd4f-f6b4-4d6d-a9d3-3da99a13f540)

[Back to Tasklist](#task_header)

---

<a name="branch_3"></a>
### Branch 3

**Defining Mutations:** `XCH` > `C25916A(ORF3a:T175K)` > `C29668T` > `G1235A(ORF1a:D324N)` > `C22995G(S:T478R)`
**Query:** `G1235A, C22995G, C25916A`
**Earliest seq:** 2023-09-28 (`EPI_ISL_18408002`, California, USA)
**Latest seq:** 2023-11-20 (`EPI_ISL_18662775`, California, USA)
**Sampled Countries:** USA (5: CA), Canada (1: ON)

<details><summary>Genomes: </summary>

`EPI_ISL_18408002, EPI_ISL_18446610, EPI_ISL_18504833, EPI_ISL_18609448, EPI_ISL_18662775, EPI_ISL_18662777`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35810_3c6210.json?label=id:node_3704511
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a2cee0b3-5074-4ff8-8b53-c643f963c85e)

[Back to Tasklist](#task_header)

---

<a name="singlets"></a>
### Singlets

- `USA/WA-PHL-034985/2023|EPI_ISL_18524551|2023-11-07`
**XCH** > C26907T > G10523C(ORF1a:V3420L), C22995G(**S:T478R**), G29348T(N:A359S) [Query: `A2163C, C22995G, C26907T, -T9952C`, 11/20] ⚠ Lot of Ns, low coverage

- `Spain/MD-H12O_478/2023|EPI_ISL_18413101|2023-09-30`
**XCH.1** > G3206T(ORF1a:D981Y) > C2005T, C9693T(ORF1a:A3143V) > C27303T > T508C, C1441T, C16650T, A21137G(ORF1b:K2557R), C22995G(**S:T478R**) [Query: `C2005T, G3206T, C22995G`, 10/20]

- `Spain/AN-PMC-38341/2023|EPI_ISL_18468245|2023-10-10`
**XCH.1 (pre-G9220A)** > T10198C_rev, C22995G(**S:T478R**), T23662C(S:G700), G25567A(ORF3a:A59T), T27320C(ORF6:L40S) [Query: `T9952C, C22995G, C26907T, -G9220A`, 11/06] ⚠missing `G9220A` and `C10198T` probably due to dropout, if that is confirmed this should belong to **Branch 2**

[Back to Tasklist](#task_header)

<a name="doublets"></a>
### Doublets

[Back to Tasklist](#task_header)

<a name="triplets"></a>
### Triplets

[Back to Tasklist](#task_header)

**Comment by FedeGueli** [comment]
Thank you

**Comment by FedeGueli** [comment]
it seems likely that this has very low circulation and we are getting it only thanks to the efficiency of Canadian sequencing.

**Comment by FedeGueli** [comment]
None of the lineages proposed seems to have a chance closing it

**Comment by FedeGueli** [comment]
Pls propose b ranch 1 once reached 50 seqs (if this happens not too far in the next weeks.
