### ISSUE TITLE
EG.5.1.3 Sublineage with S:K440R (11 seq, Ireland, 2023-10-11)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#942]
**Description**
**Sub-lineage of:** EG.5.1.3
**Earliest sequence:** 2023-9-11, Ireland — EPI_ISL_18307533
**Most recent sequence:** 2023-9-30 – EPI_ISL_18371264
**Countries circulating:** Ireland (11)
**Number of Sequences:** 11
**GISAID Nucleotide Query:** C6151T, A22881G, C27005T 
**CovSpectrum Query:** Nextcladepangolineage:EG.5.1* & A22881G & [1-of: C6151T, C27005T]
**Substitutions on top of EG.5.1.3.:**
**Spike:** K440R
**Nucleotide:** C6151T, A22881G, C27005T

**Phylogenetic Order of Mutations:** C27005T   **→**   C6151T   **→**  A22881G 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.5.1.3_K440R.json?c=gt-S_440&gmax=25384&gmin=21563&label=id:node_3426479 
<img width="1455" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/33a8e4ce-b862-4e13-92f3-f513ccc7983d">

**Evidence**
S:K440R has been a very convergent mutation in chronic-infection sequences, but this is the first time I’ve ever seen one transmit multiple times. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18307533, EPI_ISL_18307542, EPI_ISL_18352506,
EPI_ISL_18352534, EPI_ISL_18371236, EPI_ISL_18371243,
EPI_ISL_18371245, EPI_ISL_18371248, EPI_ISL_18371249, EPI_ISL_18371252,
EPI_ISL_18371264
</details>

**Comment by FedeGueli** [comment]
No recent sample closing this one
