### ISSUE TITLE
XDF/XCM recombinant(3 seq, Germany, Puerto Rico, Canary Island)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#944]
@AngieHinrichs, there seems to be a new EG.5.1/XCM recomb with XCM Spike. Please add it into usher list. 

EPI_ISL_18373945 Germany

EPI_ISL_18406963 Puerto Rico

XCM+T331G(rev),C335T,C1387T,T3453C,T4234C(rev), T5730C(rev), G5720A, A6536G(rev), C9693T, A11782G, C12789T,C13560T(rev)

Orf1a:H22Q(rev),R24C,V1063A,G1819S,I1822T(rev),S2091G(rev),A3143V,T4175I

The Pureto Rico seq has Orf1a:1-288 masked. 

XDF --XCM
Breakpoint between 13561 and 16877

T331G(rev),C335T,T3453C,T4234C(rev), T5730C(rev), G5720A, A6536G(rev), C9693T, A11782G, C12789T,C13560T(rev) from a branch in XDF

C1387T is private.

GISAID query: C1387T,T3453C,A29558G
No. of seqs: 2(Germany, Puerto Rico)

EPI_ISL_18373945 Germany, 2023-9-14

EPI_ISL_18406963 Puerto Rico,2023-9-25

[updated usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/multi-recomb-0.json?label=id:node_11117183)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/0fd20b7e-9444-4adf-b558-11aaab0ef8e7)

**Comment by corneliusroemer** [comment]
A bit more analysis would be useful - I have no clue where the breakpoints of this would be, what the donors are etc

**Comment by aviczhl2** [comment]
> A bit more analysis would be useful - I have no clue where the breakpoints of this would be, what the donors are etc

Yeah will analyse them when a 2nd one appears. For the 1st one just posting here for @AngieHinrichs to keep it on the tree.

**Comment by FedeGueli** [comment]
> A bit more analysis would be useful - I have no clue where the breakpoints of this would be, what the donors are etc

yes this is just to track them and be sure not being invisible. be safe i will ping on everything that grows.

**Comment by corneliusroemer** [comment]
@aviczhl2 when I check whether a potential recombinant I spot has already been reported, it's very useful if the country/ies where the first samples were found is included in the issue title as well. Also, it's much easier to read strain names than epi isls, so if you could include the strain names as well, that would be super useful. Thanks!

**Comment by aviczhl2** [comment]
Reopen as there seems to be 2nd seq. EPI_ISL_18406963, analysing.

**Comment by aviczhl2** [comment]
It seems that 1st part is not purely EG.5.1 but also formed via some form of recomb. Though there's too many candidates here. 

 So we have ?--EG.5.1--XBB.2.3--DV.7.1   for this variant,  fantastic.

**Comment by FedeGueli** [comment]
Thank you i ve put it under monitoring.

**Comment by Over-There-Is** [comment]
Germany/BE-RKI-I-1137446/2023|EPI_ISL_18241633|2023-08-28 EG.10.1+C335T, del510_518 could be a good candidate

**Comment by Over-There-Is** [comment]
France/HDF-IPP15717/2023|EPI_ISL_17831422|2023-06-05 FW.2+C335T, del510_518
USA/OK-OKPHL-0027623/2023|EPI_ISL_18073387|2023-05-03 XBB.1.5+del510_518, C1387T
Canada/BC-BCCDC-640618/2023|EPI_ISL_18129124|2023-07-23 XBB.1.5+C335T, del510_518(USA/ID-USAFSAM-S20973/2023|EPI_ISL_16550312|2023-01-05, USA/WI-MCRI-013085/2023|EPI_ISL_17195575|2023-02-10, USA/MI-SHMSU-A05_I_0144_71/2023|EPI_ISL_18335297|2023-04-06)

**Comment by aviczhl2** [comment]
> France/HDF-IPP15717/2023|EPI_ISL_17831422|2023-06-05 FW.2+C335T, del510_518 USA/OK-OKPHL-0027623/2023|EPI_ISL_18073387|2023-05-03 XBB.1.5+del510_518, C1387T Canada/BC-BCCDC-640618/2023|EPI_ISL_18129124|2023-07-23 XBB.1.5+C335T, del510_518(USA/ID-USAFSAM-S20973/2023|EPI_ISL_16550312|2023-01-05, USA/WI-MCRI-013085/2023|EPI_ISL_17195575|2023-02-10, USA/MI-SHMSU-A05_I_0144_71/2023|EPI_ISL_18335297|2023-04-06)

Yeah many candidates for 2/3, but none has 3/3 so unable to  confirm.

**Comment by FedeGueli** [comment]
no new sequence closing it for now

**Comment by aviczhl2** [comment]
+7 from Spain and Germany

**Comment by aviczhl2** [comment]
The new seqs belong to a new recomb of this one and FL.20.1, this one is still 2 though.

**Comment by aviczhl2** [comment]
del509_517 doesn't appear in #1050, so it shall not be included in this lineage.

**Comment by aviczhl2** [comment]
Now the first part is limited to C335T and C1387T, however still cannot confirm. 
One branch of XBB.1.5 has both mutations but also having T1753C, so shall not be the donor.  This lineage shall get one from its XBB donor while privately acquired another.

**Comment by FedeGueli** [comment]
great team work @aviczhl2 @nkrmnzr @Over-There-Is

**Comment by FedeGueli** [comment]
Closing this for now.

**Comment by aviczhl2** [comment]
+1 Canary Island

**Comment by corneliusroemer** [comment]
If someone could write down a proper analysis of breakpoints of this one and evidence for having multiple donors, that would be great. In particular, we'd want to know how many private mutations and reversions are saved by assuming a new donor/breakpoint. Are we sure it's XCM that's a parent here? XCM is very rare, and very rare until recently. Would be quite unlikely to be a donor, especially in such a complex way. Are we missing something simpler?

**Comment by FedeGueli** [comment]
Private mutations should be: C335T,510-518del,,C1063T,C1387T,G2407A,T3453C,C8318A,A11782G,C21648T, 
yes it is from XCM having : T17661C,A18879G,A24373G,A29558G in common with it
BPI 
1-11783 : unknown
11784- 17760 : EG.5.1
17661 - end XCM

**Comment by aviczhl2** [comment]
> Private mutations should be: C335T,510-518del,,C1063T,C1387T,G2407A,T3453C,C8318A,A11782G,C21648T, yes it is from XCM having : T17661C,A18879G,A24373G,A29558G in common with it BPI 1-11783 : unknown 11784- 17760 : EG.5.1 17661 - end XCM

T3543C and A11782G comes from a particular EG.5.1 branch. The breakpoint 1 is between 2335 and 3542. 

5' recomb of EG.5.1 is very very common. There's even an XCR branch of this. https://github.com/sars-cov-2-variants/lineage-proposals/issues/1077

**Comment by FedeGueli** [comment]
> > Private mutations should be: C335T,510-518del,,C1063T,C1387T,G2407A,T3453C,C8318A,A11782G,C21648T, yes it is from XCM having : T17661C,A18879G,A24373G,A29558G in common with it BPI 1-11783 : unknown 11784- 17760 : EG.5.1 17661 - end XCM
> 
> T3543C and A11782G comes from a particular EG.5.1 branch. The breakpoint 1 is between 2335 and 3542.
> 
> 5' recomb of EG.5.1 and something else is very very common. There's even an XCR branch of this. #1077

I dont feel at 100% but could be this is a recomb with the usual hyper recombinant lineage? https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4807f_c98940.json?c=gt-nuc_3453&gmax=4543&gmin=2543&label=id:node_11117183



> Private mutations should be: C335T,510-518del,,C1063T,C1387T,G2407A,T3453C,C8318A,A11782G,C21648T, yes it is from XCM having : T17661C,A18879G,A24373G,A29558G in common with it BPI 1-11783 : unknown edited i found a XBB.1.9.1 with some of the private mutations of this recomb: it seems weird but it is the usual mother of recombinants: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3e315_ceac90.json?c=gt-nuc_3453&gmax=4453&gmin=2453&label=id:node_3368142 11784- 17760 : EG.5.1 17661 - end XCM

scratch this.

**Comment by aviczhl2** [comment]
> If someone could write down a proper analysis of breakpoints of this one and evidence for having multiple donors, that would be great. In particular, we'd want to know how many private mutations and reversions are saved by assuming a new donor/breakpoint. Are we sure it's XCM that's a parent here? XCM is very rare, and very rare until recently. Would be quite unlikely to be a donor, especially in such a complex way. Are we missing something simpler?

If we assume this is EG.5.1/XCM recomb then we have to put one of C335T,C1387T and T2334C(rev) to private mutations.  So we may save 2 mutations(including one reversion) but assuming a new donor at 5'.

**Comment by aviczhl2** [comment]
But, yeah it depends on how to view the chance of orf1a:690 reversion and 5' recomb events of EG.5.1.

**Comment by aviczhl2** [comment]
> If someone could write down a proper analysis of breakpoints of this one and evidence for having multiple donors, that would be great. In particular, we'd want to know how many private mutations and reversions are saved by assuming a new donor/breakpoint. Are we sure it's XCM that's a parent here? XCM is very rare, and very rare until recently. Would be quite unlikely to be a donor, especially in such a complex way. Are we missing something simpler?

For XCM donor I'm quite sure though. 

This one is exactly the same as XCM from 13561. It contains the XBB.2.3 part and the DV.7.1 part with the XCM-specific breakpoint, so cannot be something else.

**Comment by aviczhl2** [comment]
@FedeGueli  It turns out only the Germany seq has del510_518 and C21648T. These shall not belong to the whole recomb.

**Comment by FedeGueli** [comment]
> A11782G

Agree it is XCM 100% the EG.5.1 side is more messy and quite mysterious.

**Comment by FedeGueli** [comment]
> @FedeGueli It turns out only the Germany seq has del510_518, C1063T and C21648T. The new Canary Island seq confirms that by unmasking and not having del510_518 and C1063T. These shall not belong to the whole recomb.

Yeah thank you. there is something weird in the covspectrum comparison i m trying to understnad what is driving it not reliably.

**Comment by FedeGueli** [comment]
> > > @FedeGueli It turns out only the Germany seq has del510_518, C1063T and C21648T. The new Canary Island seq confirms that by unmasking and not having del510_518 and C1063T. These shall not belong to the whole recomb.
> > 
> > 
> > Yeah thank you. there is something weird in the covspectrum comparison i m trying to understnad what is driving it not reliably.
> 
> It shows everything with more than 50% prevalence. So everything appearing in 1/2 of the seqs will be shown.

ahah no no i flipped 3453 in 3543 thats fooled me! sorry ! as i sa i am not at 100%!

**Comment by FedeGueli** [comment]
Now it is quite clearer:
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?es%2FPast3M%2Fvariants%3FnextcladePangoLineage=HK.3*&nucMutations=C1387T%2CT3453C%2CA29558G&nextcladePangoLineage1=XCM*&nucMutations2=A11782G%2CT3453C&nextcladePangoLineage2=EG.5.1*&analysisMode=CompareEquals&
![Schermata 2023-11-21 alle 19 26 49](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7877a758-d916-41b7-9783-676125926ee8)

Recomb pvt: C1387T
common with EG.5.1 + T3453C : C335T,T3453C,G5720A,C9693T,A11782G,C12789T
common with XCM: T17661C,A18879G,C22033A,A22115G,A22190G,T22200G,G22331A,A22893C,T22917G,G22927T,T22928C,C24134A,A24373G,T24991A,G25606A,C25721T,T25959C,A29558G

**Comment by FedeGueli** [comment]
Please correct me if i messed up it again.
but it seems likely: the EG.5.1 donor was in germany already in mid september when XCM started to spread 
![Schermata 2023-11-21 alle 19 29 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/fa79792d-a4d3-4051-abf9-7d16d5cd22f3)

**Comment by FedeGueli** [comment]
I deleted the wrong message check only the last ones please

**Comment by aviczhl2** [comment]
> Please correct me if i messed up it again. but it seems likely: the EG.5.1 donor was in germany already in mid september when XCM started to spread ![Schermata 2023-11-21 alle 19 29 57](https://user-images.githubusercontent.com/87669813/284681017-fa79792d-a4d3-4051-abf9-7d16d5cd22f3.png)

I think this recomb likely formed at somewhere without sequencing with a low-level circulation. So it only outputs a little outside,

**Comment by FedeGueli** [comment]
> But, yeah it depends on how to view the chance of orf1a:690 reversion and potential 5' recomb events of EG.5.1.

They have been inherited by the EG.5.1. donor i am checking the tree.

**Comment by aviczhl2** [comment]
> > But, yeah it depends on how to view the chance of orf1a:690 reversion and potential 5' recomb events of EG.5.1.
> 
> They have been inherited by the EG.5.1. donor i am checking the tree.

Oh I realized. 

It is the largest branch in #1088 with additional C1387T !!!

**Comment by FedeGueli** [comment]
> > > But, yeah it depends on how to view the chance of orf1a:690 reversion and potential 5' recomb events of EG.5.1.
> > 
> > 
> > They have been inherited by the EG.5.1. donor i am checking the tree.
> 
> Oh I realized.
> 
> It is the largest branch in #1088 with additional C1387T !!!

wait wait this should be recombinant of two recombinant!??!???!?!?!??!?!

**Comment by aviczhl2** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/e54df4d8-b187-4c0b-a0fc-9d07f6470b40)

This looks more clear. 

The upper branch is XCV. The EG.5.1 donor is also a recomb branch and it shares the T2334C(rev) with XCV while having additional C335T.

**Comment by aviczhl2** [comment]
@corneliusroemer  I think after some discussion and analysing the newly-uploaded Canary Island seq this recomb is clearer. 

It is a recomb of #1088 (a newly-emerged XBB/EG.5.1.3 recomb) and XCM.

**Comment by FedeGueli** [comment]
> @corneliusroemer I think after some discussion and analysing the newly-uploaded Canary Island seq this recomb is clearer.
> 
> It is a recomb of #1088 (a newly-emerged XBB/EG.5.1.3 recomb) and XCM.
> 
> Final recomb tower.
> 
> ![image](https://user-images.githubusercontent.com/10445944/284687525-c2432415-7ed1-473f-8eb5-b4da8955b16e.png)

Great work ! I am amazed by this side of the tree went on recombining multiple times in so short times none of the lineage being widespread! Wondering if some Cruise ship involved or some sub-population . very weird.

**Comment by aviczhl2** [comment]
> Great work ! I am amazed by this side of the tree went on recombining multiple times in so short times none of the lineage being widespread! Wondering if some Cruise ship involved or some sub-population . very weird.

Actually it is a 2-step recomb like XCT. #1088 and XCM meets to form #944, while #944 and FL.20.1 meets to form #1050. 

I think the formation of #944 is quite normal, both #1088 and XCM are not small branches. 
The 2nd step may be involved on cruise ship or somewhere that enhances recombination like navy, as that specific small branch of  FL.20.1 forms multiple recombinants almost at the same time.

**Comment by corneliusroemer** [comment]
This one's still just 3 sequences, right? Bit small for designation, so holding off for now.

**Comment by aviczhl2** [comment]
This one is likely died off. Its children is growing though..
