### ISSUE TITLE
FL.1.5.1 with ORF1a:S1978F, S:G261S (34 seq) and a branch with 5 orf1ab mutations (L92I, D629N, Y5906C, V6385L, T4618M)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#946]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/713f1a9a-6595-40f6-97dc-0f80a8c43621)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/71a6aae0-1860-48c1-bc63-4dde113d226e)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6b3f_764bb0.json?c=gt-S_261&gmax=25384&gmin=21563&label=id:node_3387770

first seq: 2023-08-17
most recent: 2023-09-26

gisaid query: G22343A, C6198T, C29296T

EPI_ISL_18341510 OR560005.1 OR600145.1 EPI_ISL_18328567 OR643354.1 OR516218.1 EPI_ISL_18341596 EPI_ISL_18318145 OR603429.1 OR565183.1 OR564779.1 OR645994.1 OR642976.1 EPI_ISL_18349839 EPI_ISL_18349826 OR618621.1 OR618719.1

**Comment by FedeGueli** [comment]
huge CI in its growth advantage: https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G22343A%2CC6198T%2CC29296T&analysisMode=CompareToBaseline& i think it will slow down.
