### ISSUE TITLE
EG.5.1.3/GK.2.1 recombinant (Flip+511+Orf9b:5T) ( 6 seqs, Belgium/Spain)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#947]
XBB.1.5(with 17124 but without 10204)+

del686_694,C1889T, C2334T, C3589T, C5140T, G5720A, C7564T, T8737C, T8885C, T11187C,G12467T, C15755G, T22928C,G22927T,C22624T,G23093A,C23741T,A25045G,A27507C,A28032G,T28297C, C29625T,

Orf1a: del141_143, R542C,A690V,G1819S,L3641S,A4068V
Orf1b:S763C
S:L455F,F456L,V511I
Orf8:I47V
Orf9b:I5T
Orf10:S23F

C1889T, C2334T, G5720A,A27507C,T28297C, C29625T from EG.5.1.3
C7564T, T8737C, T11187C,G12467T, C15755G, T22928C,G22927T,C22624T,G23093A,C23741T,A25045G from GK.2.1

del686_694, C5140T,A28032G from European EG.5.1.3 branch
C3589T,T8885C are private.

EG.5.1.3--GK.2.1--EG.5.1.3
Breakpoint 1 between 5721 and 7563
Breakpoint 2 between 25046 and 27058

GISAID query: C1889T,T8885C(edited)
No of seqs: 4(Belgium 3 Spain 1)

First: EPI_ISL_18332325, Spain, 2023-9-20
Latest:EPI_ISL_18377400, Belgium, 2023-10-2

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ba42_89bfa0.json?label=id:node_10979380)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/1e79a634-673b-4500-a5a0-04d0741c3b20)

**Comment by aviczhl2** [comment]
One more appears and it does not have C829T.

**Comment by FedeGueli** [comment]
Thanks for the updated query

**Comment by FedeGueli** [comment]
It seems dying off. lets wait a bit more before closing it
