### ISSUE TITLE
Potential recombinant BA.4 dropout (13 seq., 6 countries)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#948]
Proposal for a sublineage 
Earliest sequence: 28.08.2023 (France)
Countries detected: Germany, Austria, Denmark, Netherlands, France, USA

nuc	unique	A16878T, A18492G, T24073C, C24134A, G25606A, T25959C, A27507C, G22927T, T22928C
nuc	homoplasies	C1684T, C1889T, C2334T, G5720A, C7051T, C9693T, C12789T, T16342C, A19886G, C20320T, C23031T, C25721T, T22917G, A405G, T15939C, A20741G, A22893C, C23018T, T28297C
nuc	reversionsToRoot	C23031T, C23018T
S	unique	L858I, L455F, F456L
S	homoplasies	L452R, S490F, K444T, P486S
S	reversionsToRoot	S490F
ORF3a	unique	A72T
ORF3a	homoplasies	A110V
ORF1ab	homoplasies	R542C, A690V, G1819S, A3143V, T4175I, S5360P, K6541R, H6686Y, K47R, Q6826R

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/bef5d66c-03e0-4e39-9fd1-2c938d511062)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/d2e65939-42ab-4a89-bce5-9dbdc047daad)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/9581f666-c8e8-43dd-a36d-32676143899d)

EPI_ISL_18284092
EPI_ISL_18385324
EPI_ISL_18384901
EPI_ISL_18373930
EPI_ISL_18354524
EPI_ISL_18337277
EPI_ISL_18337266
EPI_ISL_18384897
EPI_ISL_18373939
EPI_ISL_18363256
EPI_ISL_18343383
EPI_ISL_18360399
EPI_ISL_18254485

**Comment by FedeGueli** [comment]
it is #811
