### ISSUE TITLE
FL.1.5.1 + ORF3a:E241V (25 seqs Puerto Rico)

### ISSUE THREAD

**Issue by arodzh-sudo** [sars-cov-2-variants/lineage-proposals#949]
Sub-lineage of: FL.1.5.1
Substitution on top of FL.1.5.1: ORF3a:E241V (A26114T)
Earliest sequence: 2023-9-5, Puerto Rico — EPI_ISL_18386927
Most recent sequence: 2023-9-18, Puerto Rico — EPI_ISL_18379200
Countries circulating: Puerto Rico (25)
Number of sequences: 25
GISAID nucleotide query: C14220T,T23018C,A26114T
CovSpectrum query: [FL.1.5.1* (Nextclade) + C14220T, T23018C, A26114T](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C14220T%2CT23018C%2CA26114T&nextcladePangoLineage=fl.1.5.1*&)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3039c_99a150.json?label=id:node_3388331&showBranchLabels=all
![Screenshot 2023-10-13 at 15-55-24 Nextstrain _ fetch _ genome ucsc edu _ trash _ ct _ singleSubtreeAuspice_genome_3039c_99a150 json](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/d845b788-318d-4f71-9a42-c9cfef4b9559)

[High fitness amino acid mutation based on Blooms calculator](https://jbloomlab.github.io/SARS2-mut-fitness/ORF3a.html)
![orf3a241](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/13596e21-3d79-4dbc-96e0-1f57d86ed3aa)

[Relative growth advantage ](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=orf1a%3Ag268r&nextcladePangoLineage=xbb.1.16.6*&)
![Screenshot 2023-10-13 at 15-54-56 covSPECTRUM](https://github.com/sars-cov-2-variants/lineage-proposals/assets/54407020/282650ec-c4e6-4e9d-9ca6-c1fba68fded1)

**Comment by FedeGueli** [comment]
Thank you for proposing i doubt it could survive to new fast lineages which will dominate soon

**Comment by arodzh-sudo** [comment]
No new sequences, closing.
