### ISSUE TITLE
XBB.1.9.1 with S:F456L(T22928C) and S:Q52H (G21718C) and 2 orf muts in Spain, Canada, Puerto rico, Finland, France, Ireland, England , Japan (18 sequences)

### ISSUE THREAD

**Issue by BorisUitham** [sars-cov-2-variants/lineage-proposals#95]
Query: G21718C, T22928C, C25714T
Collected: 2023-04-29 and 2023-05-12

Normally I wouldn't make an issue with only 2 sequences, but since this is pretty much the xbb.1.9.1 equivalent of xbb.1.9.2's eg.5.1 which does have a large growth advantage i'm tracking it here already, since I do expect it to grow similarly. If it doesn't grow even though its very similar, I will close this issue.
Spikes are identical to eg.5.1, the difference is in a lot of the nucleotides before the spike. 
If you compare presence of accessory mutations, the difference with eg.5.1 is that this has:
Orf3a:L108F
Orf1a:I2010V

And eg.5.1* has
Orf1a:a690v
Orf1a:a3413v
Orf1b:d54n (in 36% sequences, see my other proposal)

![Screenshot_20230523_232319_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/61e66d02-09c0-4197-a77b-c3d1f2cf0537)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_63964_dc0270.json?c=gt-S_52

![Screenshot_20230524_095330_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/2ee95fdb-da14-449e-a4a8-2bae0464ba6f)
In the above image: top sequences are eg.5.1, bottom two are these xbb.1.9.1 sequences.

**Comment by carlottaolivero** [comment]
I don't know if this is the right place to write it but we have noticed that S:Q52H can derive both from G21718C and G21718T. We have seen both mutations in our wastewater samples.

**Comment by FedeGueli** [comment]
Many thx @carlottaolivero for noticing that ! i think G21718T is the S:Q52H of the fast EG.5.1 lineage so likely you are seeing that in your samples

**Comment by BorisUitham** [comment]
There is a third one now in finland, but not much more than this so i'll leave it closed unless theres more activity

**Comment by BorisUitham** [comment]
5 more sequences, total 8 now. Do you think its worth reopening @FedeGueli ?
1 more spain, 2 canada, 2 puerto rico.

Total:
3 spain
2 canada
2 puerto rico
1 finland

**Comment by BorisUitham** [comment]
Interesting mutation: the latest one from england has s:l455w

**Comment by oobb45729** [comment]
There are 2 sequences with S:L455W in England now.
![1](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/9c266daf-20be-4182-909a-17b77449d585)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28b37_5272a0.json?c=gt-S_455&label=id:node_6606314

**Comment by oobb45729** [comment]
I suspect that L455W might be more beneficial than L455F (with F456L).
The predictions from AlphaFold:
![2](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/20eafd91-b15b-410e-9a00-63051b18b1b2)
![3](https://github.com/sars-cov-2-variants/lineage-proposals/assets/115189228/c28ecc94-28ec-4b93-8ac2-10c694142eb6)
Comparing to F455, W455 forms a new hydrogen bond with F490(S490), so the structure may be more stable. The distance between W455 and Y489 seems to be closer. Plus, L455W may escape antibodies that target this part better.
![](https://user-images.githubusercontent.com/121703496/242475671-37a803cb-8e10-4247-be15-cc84a3049fdd.png)

The reason we've seen less L455W than L455F probably is that U->G is less likely to happen than G->U. There might be a cation-pi interaction between W455 and R493 which may be the reason we saw less L455W in Q493 variants than R493 variants (BA.1 and BA.2). However, with many circulating lineages with F456L now, L455W may become favored again.

**Comment by BorisUitham** [comment]
@oobb45729 thanks for the analysis! An increase in stability might open up the path towards more mutations. 


"In contrast, the mutation L455W which reduces ACE2 affinity in Wuhan-Hu-1 is affinityenhancing in Omicron RBDs. While L455W is accessible via single-nucleotide mutation from the position TTG codon present in Wuhan-Hu-1 and Omicron, mutations to site 455 have not yet been important in SARS-CoV-2 variant evolution (but see [29]). This may be because all such mutations previously decreased ACE2 affinity. But site 455 is variable across the broader evolution of SARS-related coronaviruses, e.g., Y455 in SARS-CoV-1 and W455 in RsSHC014 (SARS-CoV-2 numbering), and the epistatic shift that makes some mutations at this site favorable for ACE2 binding in Omicron suggests it could become relevant for future SARS-CoV-2 evolution." https://www.biorxiv.org/content/10.1101/2022.09.20.508745v1.full#ref-29

Also here a description of a couple ba.1.23 long term infections last year which eventually developed W455 L456
https://pubmed.ncbi.nlm.nih.gov/37270625/

**Comment by jbloom** [comment]
Yes, L455W is the most ACE2-affinity favorable mutation in the BA.2 RBD, which is currently the one closest to XBB for which we have deep mutational scanning data.

See image below, taken from [here](https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/)
<img width="781" alt="Screenshot 2023-06-23 at 8 53 33 AM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/1906801/2c342e2b-ed4a-4715-9f10-892c10d6f46a">

**Comment by oobb45729** [comment]
I think Q493R might the reason that L455W increases ACE2-affinity in BA.1 and BA.2.

**Comment by tylernstarr** [comment]
@oobb45729 interesting theory, and it tracks nicely with new data in BQ.1.1 and XBB.1.5 (reverts back to Q493), wehre L455W affinity-increasing effect goes away again!

We haven't put the data out yet though our repository and [the data](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/) are publicly accessible at this point. We have a bit more QC to do on the data, but the values shoudln't change too dramatically and adds additional context to this interesting observation. 

<img width="474" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/4729237/79f85c25-8c43-48c9-86e4-7a2cf1733691">

**Comment by oobb45729** [comment]
Thank you so much for the new data!
1. So F456L is no longer detrimental for ACE2-binding in BQ.1.1 and it increases ACE2-affinity for XBB.1.5! That explains a lot. The R493Q probably is responsible for this too. For the difference between XBB.1.5 and BQ.1.1, maybe it has something to do with F490S?
2. L513F indeed is no longer highly detrimental for XBB.1.5 and BQ.1.1, but why?
3. H505Y does not increases ACE2-affinity for XBB.1.5 and BQ.1.1 any more.
4. R403K increases ACE2-affinity moderately, so does S494P.
5. Y453F, certain Q493Xs, and certain N417Xs increases ACE2-affinity significantly as always.
6. L425R seems to be still available for XBB.1.5 to gain.
7. A484K is beneficial for BQ.1.1.
8. There is a relative big RBD-expression loss for N450D in BQ.1.1 but not in XBB.1.5. Maybe K444T is the reason.
9. 348 and 356 do not change much.
10. 478 is still mysterious.

**Comment by BorisUitham** [comment]
Indeed, thanks for the new data! I think then, without 493q that f456l would be required to open up mutations at 455 to become possible in xbb+486p lineages. You can see this with f455, green line is f455 without l456 (looks like green is increasing but thats just lowered sequencing): 
![Screenshot_20230624_144010_Chrome](https://github.com/sars-cov-2-variants/lineage-proposals/assets/119106095/677af4ce-8f32-43fb-926e-f08ac6eb14a4)

Whereas in the ba.1.23 it was possible for w455 to come first and then l456 to follow suit

**Comment by FedeGueli** [comment]
18 samples as today yesterday uploads from ireland and England , today one caught by US airport surveillance coming from Japan

**Comment by BorisUitham** [comment]
Thank you @FedeGueli , i will

**Comment by BorisUitham** [comment]
https://github.com/cov-lineages/pango-designation/issues/2072

**Comment by FedeGueli** [comment]
Designated FL.20
