### ISSUE TITLE
XBB.1.5.72/DV.7.1 recombinant in France that may be removed by usher(10 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#950]
DV.7.1+A405G, T1545C(rev),G1598A, T2227C(rev),G3164A, T3796C(rev),  A3857C(rev),T3927C(rev), A4036T(rev), A4402T(rev), T4586C(rev), C4633T, T5183C(rev), T7057G,G11609T, C12789T,A28676T, A28990G

Orf1a:K47R, V427A(rev),G445S, A967T, K1198Q(rev), L1221S(rev), S1640P(rev),V3782F,T4175I
N:T135A

A405G, T1545C(rev),G1598A, T2227C(rev), T3796C(rev),  A3857C(rev),T3927C(rev), A4036T(rev), A4402T(rev), T4586C(rev), T5183C(rev) from XBB.1.5.72
G3164A, A4633T from an XBB.1.5.72 branch
T7057G,G11609T, C12789T,A28676T from a DV.7.1 branch
A28990G is private

XBB.1.5.72--DV.7.1
Breakpoint between 5184 and 7056

GISAID query: G3164A,A28990G,A405G(edited)
No. of seqs: 5(France)

EPI_ISL_18388867-18388870, 2023-10-2
EPI_ISL_18386897, 2023-10-3

@AngieHinrichs, please add them to usher tree. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_3a165_9f1b40.json?label=id:node_10991841)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/bdb33c87-4ae2-4017-8094-c6adf22bf7fc)

[usher for XBB.1.5.72 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40002_9f3e90.json?branchLabel=nuc%20mutations&label=id:node_3593307)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/5da75767-f0ab-4377-8125-48ad380c2105)

**Comment by FedeGueli** [comment]
+1 France , it seems slow.
