### ISSUE TITLE
DV.7.1.5+S:M153I (68 seqs, 12 countries, 2.5% Finland)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#951]
DV.7.1+A28676G(N:T135A)+G22021T(S:M153I)

GISAID query: A28676G,G22021T
No. of seqs: 9(Spain 5 UK 1 Singapore 1 Portugal 1 Italy 1)

First:EPI_ISL_18168253, Spain, 2023-8-7
Latest: EPI_ISL_18373335, UK, 2023-9-28

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_3a165_9f1b40.json?label=id:node_4215282)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/f74b259a-a384-430c-aaed-a9bbe6a6839e)

**Comment by aviczhl2** [comment]
19,France

**Comment by aviczhl2** [comment]
27, Finland, Belgium

**Comment by FedeGueli** [comment]
This seems keeps circualting but not enough to be faster than parental lineage :https://github.com/sars-cov-2-variants/lineage-proposals/issues/951 lets keep it monitored for a while

**Comment by aviczhl2** [comment]
31, Croatia, China,

**Comment by FedeGueli** [comment]
Now it seems   faster than parental :https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?nextcladePangoLineage=DV.7.1.5*&nucMutations1=A28676G%2CG22021T&analysisMode=CompareToBaseline& lets monitor it for a while

**Comment by aviczhl2** [comment]
35, Germany

**Comment by FedeGueli** [comment]
1 sample only in November closing it

**Comment by FedeGueli** [comment]
49 i wrongoed the number of samples coming from November reopening it.

**Comment by aviczhl2** [comment]
51, Denmark

**Comment by aviczhl2** [comment]
15/657 in Finland 12/15 batch.

**Comment by FedeGueli** [comment]
Designated KG.1 via https://github.com/cov-lineages/pango-designation/commit/c77220a20e5c32414b66104501789e8577903d24
