### ISSUE TITLE
HK.3+Orf1a:E553G,S:T95I on C27889T branch(130 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#952]
HK.3+C27889T+C29167T+A1923G,C7093T,C21846T(Orf1a:E553G,S:T95I)

GISAID query:A1923G,C7093T,C21846T
No. of seqs: 6(South Korea 5 UK 1)

First:EPI_ISL_18355302, South Korea, 2023-9-13
Latest:EPI_ISL_18373369, UK, 2023-9-30

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3a165_9f1b30.json?label=id:node_3461713)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/91c272f4-819d-4ad2-b404-8b948dbb54ca)

EPI_ISL_18382636 shall belong to this branch but due to S:455,456 masked usher place it elsewhere.

**Comment by FedeGueli** [comment]
Edited the title. 
Ping @corneliusroemer i suggest to designate the 27889 branch for its relevance (shown in the real world by BA.5 and then described  by Ryan Hisner,Thomas Peacock et al in https://virological.org/t/repeated-loss-of-orf8-expression-in-circulating-sars-cov-2-lineages/931

**Comment by FedeGueli** [comment]
It seems slowing down, lets see how it ends

**Comment by aviczhl2** [comment]
17/887 in South Korean seqs from 10-15.

**Comment by FedeGueli** [comment]
no samples in November closing it

**Comment by aviczhl2** [comment]
61, Japan

**Comment by FedeGueli** [comment]
only 6 samples in November

**Comment by aviczhl2** [comment]
> only 6 samples in November

Yeah that's due to the delay of South Korea is usually longer than other countries. 

But this one is going down though. Only 1% now.

**Comment by FedeGueli** [comment]
yeah SK and Japan are slow from sampling/sequencing to upload but still if not popping up elsewhere usually it means it stays local.

**Comment by aviczhl2** [comment]
82, New Zealand

**Comment by FedeGueli** [comment]
> A1923G,C7093T,C21846T

and very recent

**Comment by FedeGueli** [comment]
One sample only from December, closing it

**Comment by FedeGueli** [comment]
128 now , 2 from January reopening it

**Comment by FedeGueli** [comment]
lets wait the next South Korean batch before closing it

**Comment by FedeGueli** [comment]
3 samples only from Janaury ahead closing it
