### ISSUE TITLE
EG.5.1.1/XBB.1.9.1 recombinant (15 seqs, 5 countries, 11 with Flip)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#953]
EG.5.1.1+A9641G,C11956T,A13627G(rev),A16474G,T16878A(rev),G18492A(rev)

Orf1a: I3126V
Orf1b: N54D(rev), S1003G

EG.5.1.1--XBB.1.9.1--EG.5.1.1
Breakpoint 1: between 9694 and 11955
Breakpoint 2: between 18493 and 21617

C11956T,A13627G(rev),T16878A(rev),G18492A(rev) from XBB.1.9.1
A9641G,A16474G are private mutations (likely the A9641G from a EG.5.1.1 branch and A16474G from a XBB.1.9.1 branch, but cannot identify to which branch, too many candidates)

GISAID query: A9641G,A16474G,T22930A
No. of seqs: 6(South Korea 4 China 1 New Zealand 1)

First: EPI_ISL_17972859, Liaoning, 2023-6-12
Latest:EPI_ISL_18347601, New Zealand, 2023-9-20

GISAID query for S:L455F branch: A9641G,A16474G,G22927T

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice49_genome_3a165_9f1bf0.json?label=id:node_3446508)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/3accaad4-9287-4f83-bb23-6e536d3d6bef)

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by aviczhl2** [comment]
+1 Japan

**Comment by FedeGueli** [comment]
no sample in December closing it.
