### ISSUE TITLE
Multiple BA.2.86* Lineages with S:A475X (5 branches)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#954]
<a name="task_header"></a>
```[tasklist]
### Multiple `BA.2.86*` Lineages with `S:A475V` or `S:A475S`
- [x] [Branch 1](#branch_1) Designated as **JN.10** via [cov-lineages/pango-designation@`0a75629`](https://github.com/cov-lineages/pango-designation/commit/0a75629f83ff54c756aa129e1aa74f18e01803d3) , phylogenetic order follows: **BA.2.86.1** > C12815T > T3565C > C22986T(**S:A475V**) [Query: `T3565C, C12815T, C22986T`]
- [x] [Branch 2](#branch_2) Designated as **JN.5.1** via [cov-lineages/pango-designation@`5186c33`](https://github.com/cov-lineages/pango-designation/commit/5186c33727df8117d3f3d75501bc0be4d348b0ea) , phylogenetic order follows: **JN.5 (N:T135I)** > C5806T > G4720A, G16416T > T2950A, G22985T(**S:A475S**), A28052G, C29541T [Query: `G4720A, G16416T, G22985T`] many with `S:S680F/C23601T`
- [ ] [Branch 3](#branch_3) **BA.2.86.1** [with C12815T] > A14397G > C22986T(**S:A475V**) [Query: A6183G, A14397G, C22986T, 46 seqs, 03/03] proposed in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1386
- [ ] [Branch 4](#branch_4) **JN.2** > G22985T(**S:A475S**) [Query: `A2127G, C12815T, G22985T, -G16221T, -A27107T`, 17 seqs, 03/03]
- [x] Designated **JN.4** via [cov-lineages/pango-designation@`8c291c7`](https://github.com/cov-lineages/pango-designation/commit/8c291c77c2451fdbd2c0e9a3ff6ce38ea734c66c) , proposed as #1009 by @HynnSpylor , phylogenetic order follows: `BA.2.86.1 (pre-C12815T)` > `C22986T(S:A475V)` , query: `A6183G, C22986T, -C12815T`
```
- [Singlets](#singlets), [Doublets](#doublets), [Triplets](#triplets), [Quadruplets](#quadruplets) and [Quintuplets](#quintuplets) ; Query for all `BA.2.86*` with `S:A475X` minus most of already designated ones: `spike_A475, A7842, C8293T, G8393A, -T2950A, -T3565C, -T3745C, -C5170T, -C6541T, -T10033C, -T10372C, -C13366T`, 293 seqs, 01/12]

<a name="branch_1"></a>
### Branch 1

<details><summary>Designated as JN.10</summary>

Designated as **JN.10** via cov-lineages/pango-designation@0a75629

**Defining Mutations:** `BA.2.86.1` > `C12815T` > `T3565C` > `C22986T(S:A475V)`
**Query:** `T3565C, C12815T, C22986T`
**Earliest seq:** 2023-09-17 (`EPI_ISL_18311030`, `SEA` airport, with travel history to: Spain)
**Latest seq:** 2023-09-30 (`EPI_ISL_18361497`, Galicia, Spain)
**Sampled Countries:** Spain (3), USA (2: ex. Spain)

<details><summary>Genomes: </summary>

`EPI_ISL_18311029-18311030, EPI_ISL_18361497, EPI_ISL_18388492, EPI_ISL_18388567`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice111_genome_bf96_a5c5f0.json?label=id:node_4338909
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/444e1f40-23ed-4f68-9fdf-8f3f2d4a7267)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2: Three sub-lineages follows `S:S221L/C22224T` , `S:S680F/C23601T` and `S:E780Q/G23900C` respectively

<details><summary>Designated as JN.5.1</summary>

Designated as **JN.5.1** via cov-lineages/pango-designation@5186c33

**Defining Mutations:** `JN.5` > `C5806T` > `G4720A, G16416T` > `T2950A, G22985T(S:A475S), A28052G, C29541T`
**Query:** `G4720A, G16416T, G22985T`
**Earliest seq:** 2023-10-19 (`EPI_ISL_18466912`, England, UK)
**Latest seq:** 2023-11-06 (`EPI_ISL_18499740`, England, UK)
**Sampled Countries:** UK (7: EN), Belgium (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18450459, EPI_ISL_18466912, EPI_ISL_18492464, EPI_ISL_18499728, EPI_ISL_18499734, EPI_ISL_18499736, EPI_ISL_18499740, EPI_ISL_18499746`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2a3c6_379270.json?label=id:node_4432643
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1ee85da3-4846-455f-b725-1d65ed144c9a)

</details>
---

<a name="branch_3"></a>
### Branch 3:  

**Defining Mutations:** `BA.2.86.1` [with C12815T] > `A14397G` > `C22986T(S:A475V)`
**Query:** `A6183G, A14397G, C22986T`
**Earliest seq:** 2023-10-28 (`EPI_ISL_18473823, England, UK)
**Latest seq:** 2023-12-19 (` EPI_ISL_18700444,Indonesia)
**Sampled Countries:** **UK** (3: EN), **USA** (3: IL/2; DE), **Malaysia** (2), **China** (1: ex. Malaysia) **Indonesia** (1) 

<details><summary>Genomes: </summary>

`EPI_ISL_18473823, EPI_ISL_18525476, EPI_ISL_18566205-18566206, EPI_ISL_18601884, EPI_ISL_18641580, EPI_ISL_18698127, EPI_ISL_18698131, EPI_ISL_18700444, EPI_ISL_18703833`</details>

**UShER:**
 https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_189ee_4a0320.json?label=id:node_6827454
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/cc054221-a4cf-4d83-b175-3f354e72beb2)

</details>
---

<a name="branch_4"></a>
### Branch 4:  

**Defining Mutations:** `JN.2` > `G22985T(S:A475S)`
**Query:** `A2127G, C12815T, G22985T, -G16221T, -A27107T`
**Earliest seq:** 2023-11-19 (`EPI_ISL_18547191`, Stockholm, Sweden)
**Latest seq:** 2023-12-30 (`EPI_ISL_18738130`, Ontario, Canada)
**Sampled Countries:** Sweden (5) Canada (3: ON/2; QC), China (1: ex. Canada)

<details><summary>Genomes: </summary>

`EPI_ISL_18547191, EPI_ISL_18582068, EPI_ISL_18642928, EPI_ISL_18642942, EPI_ISL_18703807, EPI_ISL_18738130, EPI_ISL_18741962, EPI_ISL_18754391, EPI_ISL_18754404`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_31dc6_4aafe0.json?label=id:node_6870660
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6a29e46f-cb31-4842-a796-3ce2afd9e122)

[Back to Tasklist](#task_header)

---

<a name="singlets"></a>
### Singlets

- `Sweden/M-SUS0022883/2023|EPI_ISL_18718382|2023-12-19`
**BA.2.86.1** [with C12815T] > C364T > C22993T(S:N477N) > C486T(ORF1a:S74L), A4372C, C9541T, C13536T, C21654T(**S:S31F**), C28102A(ORF8:P70H) > G20487T(ORF1b:K2340N), G22985T(**S:A475S**), C27476T(ORF7a:T28I) [Query: `A4372C, C9541T, G22985T`, 01/04] dead

- `Netherlands/LI-RIVM-133791/2023|EPI_ISL_18612450|2023-11-20`
**BA.2.86.1** [with C12815T] > C1326T(ORF1a:A354V) > G22985T(**S:A475S**) [Query: `C1326T, C12815T, G22985T`, 12/12] dead

- `Austria/AGES-1144169/2023|EPI_ISL_18704149|2023-12-13`
**BA.2.86.1** [with C12815T] > A3864C(ORF1a:E1200A), C5986T > T5614A, T14386G(ORF1b:L307V), C19983T, G22985T(**S:A475S**) [Query: `A3864C, C5986T, G22985T`, 12/30] dead

- `Denmark/DCGC-669708/2023|EPI_ISL_18744560|2023-12-11`
**BA.2.86.1** [with C12815T] > C7528T > G24872T(**S:V1104L**) > A8456G(ORF1a:S2731G), G24193T(S:L877L) > G3471A(ORF1a:G1069E), C18109T(ORF1b:P1548S), A26019G, T27645C > G22985T(**S:A475S**) [Query: `G3471A, C18109T, G22985T`, 01/11] dead

- `Ireland/KE-NVRL-GIRL00102673/2023|EPI_ISL_18635963|2023-11-22`
**BA.2.86.1** [with C12815T] > T11614C > C7086T(ORF1a:T2274I) > A9328G, C22986T(**S:A475V**), G25459T(ORF3a:A23S), G29513T(N:A414S) [Query: `C7086T, T11614C, C22986T`, 12/15] dead

- `Canary_Islands/CHUIMI-021437123508/2023|EPI_ISL_18546329|2023-11-10`
**BA.2.86.1** [with C12815T] > T11614C > G29449T > A6521C(ORF1a:I2086L) > C22986T(**S:A475V**) [Query: `A6521C, T11614C, C22986T`, 3seqs 02/10] dead

- `Austria/AGES-AZ-1670440/2023|EPI_ISL_18638439|2023-11-29`
**XBB.2.86.1** [with C12815T] > C15613T(ORF1b:H716Y) > C832T, G22985T(**S:A475S**) [Query: `C12815T, C15613T, G22985T`, 2seqs 02/10] dead

- `Germany/MV-RKI-I-1141703/2023|EPI_ISL_18661607|2023-12-05`
**BA.2.86.1** [with C12815T] > T19260C, G22985T(**S:A475S**), G28116A(ORF8:D75N) [Query: `C12815T, T19260C, G22985T`, 12/20]dead

- `England/CLIMB-CM7YGFKU/2023|EPI_ISL_18707988|2023-12-21`
**BA.2.86.1** [with C12815T] > C29445T(**N:T391I**) > C11681T, C22986T(**S:A475V**) [Query; `C11681T, C12815T, C22986T`, 15 02/10] dead

- `Spain/MC-HCUVA-70091274/2023|EPI_ISL_18702353|2023-11-24`
**JN.2** > A27107T > C3317T(ORF1a:P1018S), C5956T > G22985T(**S:A475S**), T28688C [Query: `C3317T, C5956T, G22985T`, 2 seqs 12/29]  dead

- `Sweden/N-2A779331523/2023|EPI_ISL_18587536|2023-11-14`
**JN.2** > G28378T(ORF9b:R32L) > C3117T(ORF1a:T951I) > C20404T(ORF1b:P2313S), C22986T(**S:A475V**), C26789T [Query: `A2127G, C3117T, C22986T`, 12/05] dead

- `France/PAC-HCL723001722701/2023|EPI_ISL_18677034|2023-12-02`
**JN.3** > C8991T(ORF1a:A2909V) > C3177T(ORF1a:P971L) > G22985T(**S:A475S**) [Query: `C3177T, C8991T, G22985T`, 12/22] dead

- `Austria/AGES-1143115/2023|EPI_ISL_18596869|2023-11-24`
**JN.3** > C11575T > T27794C > G25455T(ORF3a:K21N) > C1102T, C22986T(**S:A475V**) [Query: `C6525T, C11575T, C22986T`, 12/08]dead

- `France/HDF-IPP28021/2023|EPI_ISL_18577378|2023-11-20`
**JN.5** > A23566T(S:A688A) > C12897T(ORF1a:P4211L) > A8771G(ORF1a:T2836A), T17115C, G17790T(ORF1b:Q1441H), C26684T > **S:I19T_reversion**(rev_T21618C, A21619T) > A8206G, T9725C(ORF1a:Y3154H) > C22986T(**S:A475V**) [Query: `A8206G, T9725C, C22986T`, 12/04]dead

- `Japan/PG-587453/2023|EPI_ISL_18744462|2023-12-11`
**JN.5** > A23566T(S:A688A) > C12897T(ORF1a:P4211L) > C11564T(ORF1a:P3767S), G28476C(**N:R68P**) > C22986T(**S:A475V**) [Query: `C11564T, C12897T, C22986T`, 2 seqs 01/11] dead

[Back to Tasklist](#task_header)

<a name="doublets"></a>
### Doublets

- `USA/MD-MDH-9069/2023|EPI_ISL_18403841|2023-10-03` and `USA/VA-VTVAS3-GSC44565/2023|EPI_ISL_18636777|2023-11-29`
**BA.2.86.1** [pre-C12815T] > C12733T, C27503T(ORF7a:S37F) > G2305T(ORF1a:K680N), C22978T(S:I472I), C27143T > C22986T(**S:A475V**) [Query: `G2305T, C12733T, C22986T`, 7 seqs, 02/10] dead

- `Israel/SMC-7116374/2023|EPI_ISL_18706493|2023-12-18`
**JN.2** > G16221T > C11758A, C15738T, C22986T(**S:A475V**), C25460T(ORF3a:A23V), G29540A [Query: `A2127G, G16221T, C22986T`, 01/02]dead

- `Portugal/PT50123/2023|EPI_ISL_18521981|2023-10-29` and `Portugal/PT50186/2023|EPI_ISL_18642132|2023-11-22`
**JN.2** > G16221T > G28903A(**N:M210I**) > G22985T(**S:A475S**) [Query: `A2127G, G16221T, G22985T`, 2 seqs, 12/18]dead

- `Scotland/CLIMB-CM7YGPDB/2023|EPI_ISL_18421633|2023-10-10` and `Scotland/CLIMB-CM7YEKXX/2023|EPI_ISL_18705387|2023-12-18`
**JN.5** > C2668A, C6539T(ORF1a:H2092Y), G22985T(**S:A475S**) [Query: `C2668A, C12815T, G22985T`, 01/02]dead

- `England/CLIMB-CM7Y8NKN/2023|EPI_ISL_18673357|2023-12-11` and `England/CLIMB-CM7YFQMS/2023|EPI_ISL_18705242|2023-12-19`
**JN.6** > A1588G > C19269T > C22986T(**S:A475V**) [Query: `A1588G, C19269T, C22986T`, 2 seqs, 01/02]dead

- `Denmark/DCGC-662924/2023|EPI_ISL_18498727|2023-10-23` and `South_Korea/KDCA280446/2023|EPI_ISL_18751749|2023-12-14`
**JN.9** > G22985T(**S:A475S**) [Query: `C12815T, G22985T, G25249A`, 2 seqs, 01/12]dead

[Back to Tasklist](#task_header)

<a name="triplets"></a>
### Triplets

- `USA/WI-WSLH-2302219/2023|EPI_ISL_18643915|2023-10-22`; `USA/WI-WSLH-2302513/2023|EPI_ISL_18644191|2023-11-12` and `USA/WI-WSLH-2302596/2023|EPI_ISL_18644270|2023-11-19`
**BA.2.86.1** [with C12815T] > G7954T(ORF1a:Q2563H) > C5724T(ORF1a:T1820I), G22985T(**S:A475S**), C29370T(N:T366I) [Query: `G7954T, C12815T, G22985T`, 3 seqs, 12/18] dead

[Back to Tasklist](#task_header)

<a name="quadruplets"></a>
### Quadruplets

- `England/CLIMB-CM7YEKN5/2023|EPI_ISL_18652526|2023-12-10`; `England/CLIMB-CM7YGJUG/2023|EPI_ISL_18694712|2023-12-15`; `England/CLIMB-CM7YE1K1/2023|EPI_ISL_18694788|2023-12-19` and `England/CLIMB-CM7YEZPT/2023|EPI_ISL_18727455|2023-12-24`
**JN.3** > G28378T(ORF9b:R32L) > A27950G > C8481T(ORF1a:P2739L) > C1594T, C22986T(**S:A475V**) [Query: `C6525T, C8481T, C22986T`, 4 seqs, 01/08]dead

[Back to Tasklist](#task_header)

<a name="quintuplets"></a>
### Quintuplets

- `France/NAQ-HCL723001539201/2023|EPI_ISL_18568555|2023-11-13`; `France/NAQ-HCL723001540101/2023|EPI_ISL_18568563|2023-11-13`; `France/NAQ-HCL723001540301/2023|EPI_ISL_18568565|2023-11-13`; `Spain/GA-33335542/2023|EPI_ISL_18560724|2023-11-14` and `Switzerland/BS-UHB-USB-2009db68/2023|EPI_ISL_18639142|2023-11-15`
**BA.2.86.1** [with C12815T] > C22986T(**S:A475V**)

- `Sweden/Y-34975091/2023|EPI_ISL_18587025|2023-11-21`; `Sweden/Y-35043027/2023|EPI_ISL_18587040|2023-11-23`; `Sweden/M-SUS0022458/2023|EPI_ISL_18636570|2023-11-30`; `Sweden/M-SUS0022459/2023|EPI_ISL_18636571|2023-11-30` and `Sweden/D-6563059976/2023|EPI_ISL_18672391|2023-12-05`
**JN.2** > A18640G(ORF1a:I1725V) > A11559G(ORF1a:Y3765C) > C21846T(**S:T95I**), C22986T(**S:A475V**) [Query: `A11559G, A18640G, C22986T`, 19 seqs, 03/03]

[Back to Tasklist](#task_header)

**Comment by HynnSpylor** [comment]
+3 in Galicia, Spain

**Comment by Huachuan1120** [comment]
1 more from Spain,EPI_ISL_18445489

**Comment by Huachuan1120** [comment]
Spain+3, EPI_ISL_18453794, EPI_ISL_18453771, EPI_ISL_18453743

**Comment by Memorablea** [comment]
https://github.com/cov-lineages/pango-designation/commit/8c291c77c2451fdbd2c0e9a3ff6ce38ea734c66c ？

**Comment by FedeGueli** [comment]
> 11-14, 1 more from Seine-Saint-Denis `EPI_ISL_18499504`
> 
> Adding **Branch 2** from former triplet

thank you sorry didnt see the addendum

**Comment by BorisUitham** [comment]
Branch 2 with 475s due to a recent designation now exists on jn.5 (N:T135I)

**Comment by FedeGueli** [comment]
> Branch 2 with 475s due to a recent designation now exists on jn.5 (N:T135I)

corrected everywhere here

**Comment by FedeGueli** [comment]
B.1 +2

**Comment by FedeGueli** [comment]
Branch 1 designated JN.10 via https://github.com/cov-lineages/pango-designation/commit/0a75629f83ff54c756aa129e1aa74f18e01803d3

**Comment by FedeGueli** [comment]
Branch 2 designated JN.5.1

**Comment by aviczhl2** [comment]
Sweden/AB-01_SE100_23CS503266/2023|EPI_ISL_18547191|2023-11-19 and Canada/ON-PHL-23-44848/2023|EPI_ISL_18582068|2023-11-28  

This one is 4 now.

**Comment by Over-There-Is** [comment]
A14397G branch is 10 now, detected in Malaysia, Singapore and China.

**Comment by FedeGueli** [comment]
> * `England/CLIMB-CM7YJPWA/2023|EPI_ISL_18473823|2023-10-28`; `USA/IL-USAFSAM-S21652/2023|EPI_ISL_18566205|2023-11-01`; `USA/IL-USAFSAM-S21653/2023|EPI_ISL_18566206|2023-11-06`; `England/CLIMB-CM7YFA7T/2023|EPI_ISL_18525476|2023-11-13` and `USA/DE-CDC-LC1071357/2023|EPI_ISL_18601884|2023-11-20`
>   **BA.2.86.1** [with C12815T] > A14397G > C22986T(**S:A475V**) [Query: `A6183G, A14397G, C22986T`, 5 seqs, 12/08]

This is now 10 adding it as Branch 3

**Comment by FedeGueli** [comment]
Sweden/AB-01_SE100_23CS503266/2023|EPI_ISL_18547191|2023-11-19`; `Canada/ON-PHL-23-44848/2023|EPI_ISL_18582068|2023-11-28`; `Sweden/AB-01_SE100_23CS102741/2023|EPI_ISL_18642942|2023-12-07` and `Sweden/AB-01_SE100_23CS102715/2023|EPI_ISL_18642928|2023-12-09`
**JN.2** > G22985T(**S:A475S**) [Query: `A2127G, C12815T, G22985T, -G16221T`, 6 seqs, 01/02] now 6

**Comment by FedeGueli** [comment]
Branch 3 went to 37 (propose if it will reach 50)
Branch 4 went to 16
Several previous singlets/doublets/Triplets/Quintuplets are now dead and i ve flagged it to save your time.
While some of them are now grown to 10, not urgent or important but maybe they should be upgraded to branches if still circulating at the end of this month. thx @NkRMnZr

**Comment by FedeGueli** [comment]
> > Sweden/AB-01_SE100_23CS503266/2023|EPI_ISL_18547191|2023-11-19`; `Canada/ON-PHL-23-44848/2023|EPI_ISL_18582068|2023-11-28`; `Sweden/AB-01_SE100_23CS102741/2023|EPI_ISL_18642942|2023-12-07`and`Sweden/AB-01_SE100_23CS102715/2023|EPI_ISL_18642928|2023-12-09`**JN.2** > G22985T(**S:A475S**) [Query:`A2127G, C12815T, G22985T, -G16221T`, 6 seqs, 01/02]
> 
> now this reached 6 i would wait it reaches 10 to make it a branch

This is now 19 please make it a branch.

**Comment by FedeGueli** [comment]
> > > Sweden/AB-01_SE100_23CS503266/2023|EPI_ISL_18547191|2023-11-19`; `Canada/ON-PHL-23-44848/2023|EPI_ISL_18582068|2023-11-28`; `Sweden/AB-01_SE100_23CS102741/2023|EPI_ISL_18642942|2023-12-07`and`Sweden/AB-01_SE100_23CS102715/2023|EPI_ISL_18642928|2023-12-09`**JN.2** > G22985T(**S:A475S**) [Query:`A2127G, C12815T, G22985T, -G16221T`, 6 seqs, 01/02]
> > 
> > 
> > now this reached 6 i would wait it reaches 10 to make it a branch
> 
> This is now 19 please make it a branch. Brnach 3 now 46
