### ISSUE TITLE
(XCH + ORF3a:T175K + N:P6T +ORF9b:D2E proposed in #868) with ORF1b:P218L 20 only in NY

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#956]
Sublineage of https://github.com/sars-cov-2-variants/lineage-proposals/issues/868: (**EDITED**)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/b9fcf886-135e-438f-8212-49f172aefc17)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38d56_aedfb0.json?c=gt-nuc_14120&gmax=15120&gmin=13120&label=id:node_3708109

first seq: 2023-09-10
most recent: 2023-09-26

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/3d18278a-0990-49d0-a60b-362c0c956d6f)

gisaid query: C14120T, C28289A, A16923C

EPI_ISL_18364267 EPI_ISL_18364241 OR642911.1 EPI_ISL_18364212 OR650567.1 OR649745.1 OR649914.1 OR600123.1 EPI_ISL_18364264 OR662199.1 EPI_ISL_18364273 OR642897.1 EPI_ISL_18364282 OR649958.1 OR650662.1

**Comment by FedeGueli** [comment]
For the next time is suggest to integrate the original issue  with a new sublineage better than opening one new

**Comment by FedeGueli** [comment]
only 3 samples in October. closing it for now
