### ISSUE TITLE
HV.1 Spike Diversity Collection (UPDATED 2024-02-21)

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#957]
HV.1* is a mystery to me, so I would like to create this colleciton of its Spike Diversity to see if there is an underlying reason behind its success in North America.

Standardized way of this search: C5835T,T22917G,T22930A for HV.1* parent.
```[tasklist]
### Dead/Small/Proposed Observations
- [x] S:S12F Query(small,30 total):C21597T+Base neutral
- [x] dead S:K41E 7 seqs, Query: C12513T,A21683G Canada, Ontario
- [x] S:S94F 22 small (=4+2+1seqs Query1 Also with S:T284I): C21843T,C5835T,C22413T US,CT Dead Query2:C21843T,C5835T,C22413T US and Iceland
- [x] S:M177I 35small=9(A)+20(C)+6(T)seqs, complicated because any of G22093X (X=A,T,C) appear as S:M177I Query:G22093A,C5835T,G27915T/G22093C,C5835T,G27915T/G22093T,C5835T,G27915T. US,NY/ US and Canada/US,CA unworthy
- [x] Small S:G181V 24 seqs , Query: T22917G,C12513T,G22104T,G22895C US,CA+Utah
- [x] Small? S:N185S 44 seqs Query: A22116G,C5835T,T22917G US and Canada Revived?
- [x] Dead S:P217H 17 seqs Query: C5835T,C22212A US,DC
- [x] Designated **HV.1.7** S:S221L 47 (non monoph.)seqs Query1: C22224T,C5835T,T22917G,G701T Canada,AB Query2:C22224T,C5835T,T22917G,G1820A US,NY/MD plus one US,CA singlet
- [x] Designated S:K444T 31seqs, Query: C5835T,C12513T,A22893C Multiple Countries designated HV.1.1
- [x] Small? S:T470I 48seqs Query: T22917G,C3369T,C22971T US,CA and 1 US,FL singlet
- [x] **HV.1.3** S:Q493L 93 seqs Query: C5835T,A23040T,T22917G Multiple Countries
- [x] S:S514F 162 seqs, Query: C12513T,C23103T US, Canada and Australia designated HV.1.2
- [x] Small S:E554Q 24 seqs Query: G23222C,G19735T,G22895C US,NY+OH
- [x] Small S:P561S 5 seqs Query: T22917G,C5835T,C23243T US,IA
- [x] Small S:G/D614S 31 seqs Query: G23402A,C5835T,G27915T Spain proposed in #1061
- [x] Small S:P621S 33 seqs Query: C5835T,C23423T,G27915T US,CA/CT/NY unworthy
- [x] Designated **HV.1.6.1 S:S704L** 145 seqs Query: C23673T,C5835T,T22917G,G27915T US, Canada and France
- [x] Small S:A879T 19 seqs Query: G24197A,C5835T US and Canada unworthy
- [x] Small S:L938F 28 seqs Query: C24374T,T6673C US,HI/AZ unworthy
- [x] Small S:V963I 3 seqs Query: T712C,G24449A,G27915T US,MD/NY/VA
- [x] Designated **HV.1.4** S:A1078S 163 seqs Query: G24794T,C27945T,C22033A Multiple Countries 236
- [x] Designated **HV.1.5** S:L1265F 168 seqs Query: C25355T,T22917G,C5835T,T28297C US, Canada and Australia.
- [x] Designated **HV.1.8**S:T208M Query(142): C1093T, C1302T, C22185T growing
- [x] Designated **HV.1.9** S:N211I,T1117IQuery(65):C24912T,C22624T,A22194T,C14119T growing
```

```[tasklist]
### Past Watches (I JUST DELETED THE STILL WATCHING ONES)
- [x] Small? S:V16F Query(49): G21608T,T24829C descending
- [x] S:S31F Query(36):C29284T,C21654T,C5835T descending
- [x] S:H49Y Query(69):C21145T,C21707T,C5835T neutral
- [x] S:T95I Query(small,35 total):C21846T+Base growing
- [x] S:W152R Query (66): C18713T, T22016A,C5835T neutral
- [x] S:M153I Query(small,46 total):G22021T+Base growing
- [x] S:N185S Query(40):A24742G,A22116G descending
- [x] S:A222S Query(small,36 total):G22226T+Base neutral
- [x] S:V227I Query(103):C13378T,G22241A,G2494T growing
- [x] S:R357K Query(small,47 total):G22632A+Base growing
- [x] S:L/R452W Query(48,121 total):C15720T,C22916T,C5835T growing
- [x] S:T470I Query(small,40 total):C22971T+Base growing
- [x] (S:A1078S=HV.1.4*),S:F/S490P Query(31):T23030C,G24794T,C27945T neutral
- [x] S:T553I Query(small,32 total):C23220T+Base growing
- [x] S:T572I Query(small, 30total):C23277T+Base neutral
- [x] S:V642G Query(small,32 total):T23487G+Base neutral
- [x] S:V656I Query(64):A28877T,G28878C,G23528A,C5835T neutral
- [x] S:Q836L Query(82):C29364T,A24069T growing
- [x] S:G1124S Query(43): C2695T, G24932A, C25433T neutral
- [x] S:P1162L Query(small,80 total): C25047T+Base neutral
- [x] S:Q1208H Query(small,38 total): G25186T+Base neutral
- [x] S:K1245R Query(41):A25296G,T12574C growing
```

 Trees of current stuff

```[tasklist]
### Now Watching Trees
- [ ] S:S98F Polytomy- Query:C21855T+HV.1*=C5835T,T22917G,T22930A Count:(15;84)
- [ ] S:K147I,E619Q Single Branch- Query: A22002T,G23417C,-G26529A Count:(8;56)
- [ ] S:N148T Polytomy- Query: A22005C,T22930A,C5835T,T22917G Count: (18; 181) Main Branch Query:C10189T, A22005C,C10125T Count: (6;62)
- [ ] S:G184V Polytomy- Query: G22113T,T22930A,C5835T,T22917G Count: (20;101) Main Branch Query: G22113T,C23185T, A23539T Count: (12;68)
- [ ] S:G184S Polytomy- Query:G22112A,T22930A,C5835T,T22917G  Count: (10;19)
- [ ] S:S221L outside HV.1.7* Polytomy- Query:C22224T,T22930A,C5835T,T22917G,-T23198C Count: (6;62)
- [ ] S:D253E  Single Branch- Query: T22321G,T22930A,C5835T,T22917G Count: (7;114)
- [ ] S:T307I Polytomy- Query:C22482T,T22930A,C5835T,T22917G Count: (5;84)
- [ ] S:I410V,S:H1101Q- Single Branch Query:A22790G,C24865G,T22917G Count: (7;72)
- [ ] S:L455F Polytomy- Single Branch Query: G22927T,T22917G,C5835T,T22930A Count: (12;100) Main Branch Query: G22927T,T23198C,T22917G Count: (7;54)
- [ ] S:G482S Polytomy (mostly one branch)- Query:G23006A,T22917G,T22930A,C5835T Count: (31;66)) Main Branch Query:C13665T,G23006A,T22930A  Count: (29;52)
- [ ] S:T573I Polytomy (mostly two branches)- Query:C23280T,T22917G,C5835T,T22930A Count: (17;108) Main Branch Query 1: C23280T,T1834A,G18826A Count: (8;60)(Main Branch Query 2: C18713T, C23280T,T22930A,T22917G Count: (7;34)
- [ ] S:P681R Polytomy (seemingly three branches)- Query:-C21711T,C23604G,T22930A,C5835T,T22917G,-A22629C Count: (16;174) Main Branch Query 1: C23604G,T22930A,C22185T Count: (10;146) Main Branch Query 2: G12806A,C23604G,T22930A Count: (1;16) Main Branch Query 3: C23604G, C26456T,T22930A Count: (5;12)
- [ ] S:S939F Polytomy(mostly one branch)- Query: Count:-G22870A,C24378T,T22930A,C5835T,G22317T,T22917G (6,likely 7 with one wrong date; 75) Main Branch Query: C24337T, C24378T, C25075T,T22930A Count: (4,likely 5; 50)
- [ ] S:H1101Y Polytomy Query: C24863T,T22930A,C5835T,T22917G Count: (24;145) Main Branch Query: C24863T,T22930A,C5835T,T22917G,C23673T Count: (19; 85) Oh, it was already designated as KL.1.1
- [ ] S:Q1201K Polytomy Query: C25163A,T22930A,C5835T,T22917G Count: (7;95)
- [ ] S:V1264L Polytomy Query: G25352T,T22930A,C5835T,T22917G Count:  (10;240) Main Branch Query: G25352T,T22930A,C5835T,T22917G,A16140G Count: (4;206)
```
S:98F tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_17854_596060.json?f_userOrOld=uploaded%20sample&label=id:node_1022987
<img width="985" alt="Screenshot 2024-02-21 at 2 31 27 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/7661767e-835e-4289-9595-45f1b77ac2db">

S:K147I+S:E619Q tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_93d8_5992c0.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 2 33 53 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/4483b0fe-1a09-4142-8aa7-80529b37abcc">

S:N148 tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_b9a1_599cb0.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 2 40 33 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/449a07d5-71d8-4e41-b31e-e3fdcc1bae0e">

S:G184V tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1390a_59b6d0.json?f_userOrOld=uploaded%20sample&label=id:node_1035383
<img width="985" alt="Screenshot 2024-02-21 at 2 44 30 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/d549e0dd-8318-4385-b1f5-84b0d4147a55">

S:G184S tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3d18f_59c540.json?f_userOrOld=uploaded%20sample&label=id:node_1025408
<img width="985" alt="Screenshot 2024-02-21 at 2 48 25 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/15b7b2a7-ff43-40a8-a6cb-a6916a8b593b">

S:S221L tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_42cf9_59d7a0.json?f_userOrOld=uploaded%20sample&label=id:node_1025408
<img width="985" alt="Screenshot 2024-02-21 at 2 52 40 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/fe3cf36e-e0fd-4cf4-9821-531a09fbc53a">

S:D253E tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_20f8_59e350.json?f_userOrOld=uploaded%20sample&label=id:node_1025409
<img width="985" alt="Screenshot 2024-02-21 at 2 55 24 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/506ea691-a8cf-44bc-9c78-b01f2514df39">

S:T307I tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_a558_59f860.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 3 02 16 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/03b86dab-a159-4413-8475-46aab1f92432">

S:I410V+S:H1101Q tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_114a2_5a0b00.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 3 05 36 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/d3d4be5b-377c-47c8-8b8e-1aceb61220a2">

S:L455F tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_12c20_5a11b0.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 3 15 35 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/ca5a07a6-e6f6-4ec5-a873-fcd7075d08c7">

S:G482R tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_300bc_5a1450.json?f_userOrOld=uploaded%20sample&label=id:node_1025408
<img width="985" alt="Screenshot 2024-02-21 at 3 09 28 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/65161e18-e9f5-4769-b3fe-35cb8573e902">

S:T573I tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2530c_5a4ae0.json?f_userOrOld=uploaded%20sample&label=id:node_1027082
<img width="985" alt="Screenshot 2024-02-21 at 3 47 55 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/90d9b0d1-3b39-41c4-b52b-dfc27732bf79">

S:P681R tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1ba0_5ab050.json?f_userOrOld=uploaded%20sample&gt=nuc.22930A,S.356K&label=id:node_1022987
<img width="985" alt="Screenshot 2024-02-21 at 4 27 16 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/f7c562d6-0dcf-4504-a9f5-5af061c43ab2">

S:S939F tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_4c0f_5b47f0.json?f_userOrOld=uploaded%20sample&gt=S.252V
<img width="985" alt="Screenshot 2024-02-21 at 4 39 30 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/2adf1321-46fe-4c7a-aca6-39f2aed1fd7e">

S:H1101Y tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_cf1_5b8850.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 4 51 25 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/923ba3ec-7532-47a3-8f85-43e520cc8e6d">

S:Q1201K tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_d481_5bb670.json?f_userOrOld=uploaded%20sample&label=id:node_1025408
<img width="985" alt="Screenshot 2024-02-21 at 5 00 15 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/a4df1e31-cffa-46cc-9f65-b3e572cd4d13">

S:V1264L tree
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_e352_5bbdb0.json?f_userOrOld=uploaded%20sample
<img width="985" alt="Screenshot 2024-02-21 at 5 04 13 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/49a409b0-a942-42bf-b3b8-346252121173">

**Comment by FedeGueli** [comment]
Thank you great work.

**Comment by krosa1910** [comment]
K41E 4 to 6
S704L 21 to 26
V1264L  23 (22+1( to 37 (34+2+1)
V16F 9(8+1) to 11(10+1)
S94F 5(3+2) to 6 (4+2)
N148T 5 to 6
W152R 3 to 5
N185S 13 to 14
S221L 8(6+1+1) to 9(6+2+1)
I410V 9 to 10
L938F 3 to 4
S1265F 17 to 23
I would say S1265F is worthing a proposal, maybe also V1264L(with caution about Canadian cluster) and N185S

**Comment by FedeGueli** [comment]
Lets wait they hit 40 sequences before proposing them . Great work @krosa1910

**Comment by RajLABN** [comment]
HV.1 has picked S:494P too

**Comment by krosa1910** [comment]
Yeah, I would update that sometime this week, also L452W is deserving tracking.

**Comment by FedeGueli** [comment]
@krosa1910 please propose the S:704L branch and the S:514F branch and the S:V1264L branch

**Comment by FedeGueli** [comment]
Please propose also the S:S1265F and the S:A1078S. while keeping 493L and 1162S monitored. thank you.

**Comment by FedeGueli** [comment]
You can also on Pango a multiple issue saying these are the spike mutated branches of HV.1 if any of them has interest to be diesignated and etc etc

**Comment by FedeGueli** [comment]
ping @corneliusroemer please take a look there is some interesting spike diversity in HV.1 that grew over the 100 seqs.

**Comment by FedeGueli** [comment]
S:S514F has been designated HV.1.2 via https://github.com/cov-lineages/pango-designation/commit/471889e99d588b099d8e42f0326ad83e85b89b7c

**Comment by FedeGueli** [comment]
@corneliusroemer the author cannot connect in this moment to internet so i updatted the issue flagging the ones you may want to evaluate for designation.
S:704L S:1078S S:493L and S:1265F are already big enough to be designated. please when u save a minute to look at these ones.

**Comment by FedeGueli** [comment]
S:S1265F designated HV.1.5 via https://github.com/cov-lineages/pango-designation/commit/4813e2faaefbc14a99663c13f80940a4983deea1

**Comment by FedeGueli** [comment]
S:S221L designated HV.1.7 via https://github.com/cov-lineages/pango-designation/commit/57891f2789b2b72af6cd018ae98e43aa356e7410

**Comment by FedeGueli** [comment]
> > S:S1265F designated HV.1.5 via [cov-lineages/pango-designation@4813e2f](https://github.com/cov-lineages/pango-designation/commit/4813e2faaefbc14a99663c13f80940a4983deea1)
> 
> Should be `L1265F` not `S`

Thank you edited everywhere now.

**Comment by FedeGueli** [comment]
> > @corneliusroemer S:Q493L maybe deserves a designation. around 100 sequences and widespread
> 
> it has already been designated #924

Thank you missed that was the same here.

**Comment by krosa1910** [comment]
Will try to update this issue, as I think HV.1* is still not over yet.

**Comment by krosa1910** [comment]
HV.1* now is very big, at over 28k on Gisaid, yet it is starting to lose momentum, so something at levels of 3 seq seems less interesting now. Thus I decided to find some newer branches and replace old ones.
Basically, any old branch under 30 sequences/ about 0.1% total samples are shut, while I would open some new ones at 10+ seqs.
within part 1, K41E,E554Q are dead, K444T S514F, S704L are designated, G181A is small at 11 seqs, Q1208H is not much larger but above the threshold. But V1264L is highly convergent in other lineages so deserve proposal.
Part 2 is larger, I updated the V16F search to be more precise, now at 37. S98F is small at 20, S98 at 48, N148T at 284 is quite descent, W152R at 94 is OK, any M177I is not successful overall, N185S is dead, T208M seems good, P217H is dead, S221L designated. I410V/H1101Q good consider multiple S mutations. T470I, P561S dead, P621S, A879T and L938F small, V963I dead, G1124S at 44, P1162L and Q1201K both good and L1265F and Q493L designated.
So in total, I am watching Q1208H, V16F, S98F, W152R, I410V/H1101Q, G1124S, P1162L, Q1201K and I think V1264L and T208M could be proposed.

**Comment by FedeGueli** [comment]
> HV.1* now is very big, at over 28k on Gisaid, yet it is starting to lose momentum, so something at levels of 3 seq seems less interesting now. Thus I decided to find some newer branches and replace old ones. Basically, any old branch under 30 sequences/ about 0.1% total samples are shut, while I would open some new ones at 30+ seqs. So in total, I am watching Q1208H, V16F, S98F, W152R, I410V/H1101Q, G1124S, P1162L, Q1201K and I think V1264L and T208M could be proposed. Others are shut down as they doesn't seem to show dominance over parent given time like two months. I will now consider the following candidates (after bogging down some valid trees that is) Y49H, T95I, M153I,M153K G184V, V227I, D253E , L455F,T470I , T573I, E619Q, V642G, P681R, Q836L, S939F, H1101Y, Q1208H, K1245R, S12F S31F, N148Q, K150V, E154V, N185S, N211I, Also 478 and 554 are weird, and people could start investigating it if they want. While N450D and L455F seems to rise recently.

Thank you great update! please track 148T too!

**Comment by krosa1910** [comment]
I would like to open some new issues after this update is completed. Those with a single tree neutral or growing status and >100 seqs would be likely considered.

**Comment by FedeGueli** [comment]
Thanks @krosa1910 greeat work.
Please propose S:N148T and the S:t208M+681R one. thank you.

**Comment by FedeGueli** [comment]
S:L452W already proposed  in #1044

**Comment by krosa1910** [comment]
> Thanks @krosa1910 greeat work. Please propose S:N148T and the S:t208M+681R one. thank you.

N148T seems too sparse and can be only proposed in the multiple trees manner, T208M+681R seems good enough though.

**Comment by FedeGueli** [comment]
> > Thanks @krosa1910 greeat work. Please propose S:N148T and the S:t208M+681R one. thank you.
> 
> N148T seems too sparse and can be only proposed in the multiple trees manner, T208M+681R seems good enough though.

Thx if not monophyletic better wait! Thx

**Comment by FedeGueli** [comment]
> S:N211I, S:T1117I, New Zealand>

this has been designated HV.1.9

**Comment by FedeGueli** [comment]
> S:T573I https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_d962_fe34d0.json?f_userOrOld=uploaded%20sample <img alt="Screenshot 2023-12-30 at 4 31 26 AM" width="1250" src="https://private-user-images.githubusercontent.com/131021067/293453311-d03a9ba2-d398-4ae5-b469-a7ebe6cf6724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzU3MDUsIm5iZiI6MTcwNjEzNTQwNSwicGF0aCI6Ii8xMzEwMjEwNjcvMjkzNDUzMzExLWQwM2E5YmEyLWQzOTgtNGFlNS1iNDY5LWE3ZWJlNmNmNjcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQyMjMwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmQ4YzE4NDJhN2UyNmNlOGE4ZWMxZDBkZjY4ZmQxNmQzNzlkODk1ZjY4NmVhZGJjZTYzNGQ5MzJiNTY5ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4fQqekUC-Fv4sW4KFSv92278jGSSxSXrXHU9hCsP9lk">

This one with the query : C3924T, C12295A,C23280T counts 53, please propose it.

**Comment by krosa1910** [comment]
This update moves things with a 50+ seq monophyletic to the current observing mode and would propose them if seems to grow fast enough, while trees without 50 seq would be moved to the "dead/small" sector. Some new things could be proposed as I would search the HV.1* for every S mutation appearing within the last 30 days's sequences.

**Comment by FedeGueli** [comment]
Thanks @krosa1910

**Comment by FedeGueli** [comment]
Yesterday i proposed https://github.com/sars-cov-2-variants/lineage-proposals/issues/1338 335S 403K in Aus.

**Comment by FedeGueli** [comment]
> (Range:140-146)del is really weird. I have asked people things about it months ago yet I don't get a definitive answer so I would ignore them.

yes it is. the 144del makes a mess in reading the sequence in that part. For a long while i suspected that also S:N148T was affected by something similar.

**Comment by krosa1910** [comment]
A lot of E554X+HV.1*, maybe deserving a new issue (if not for the fact that HV.1* is now falling considerably, yet it is still like twice as large as BA.2.86* without L455S or thrice as large as JD.1.1*/JG.3*) If some more experienced individuals like NK can help me then probably I could sort it out.

**Comment by FedeGueli** [comment]
> A lot of E554X+HV.1*, maybe deserving a new issue (if not for the fact that HV.1* is now falling considerably, yet it is still like twice as large as BA.2.86* without L455S or thrice as large as JD.1.1*/JG.3*) If some more experienced individuals like @NkRMnZr NK can help me then probably I could sort it out.

good idea lets wait next week to see how it goes in January

**Comment by FedeGueli** [comment]
i ve checked growing lineages, it seems to me very hard times for all of them in January.

**Comment by FedeGueli** [comment]
There is a HV.1 Flip lineage not listed here that managed to criculate in January:
<img width="1144" alt="Screenshot 2024-02-16 alle 23 17 31" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3b9d3677-953a-41bf-ba0f-0c5e74d8eadb">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1bc88_fdd4c0.json?c=userOrOld&label=id:node_3597976

Defining mutations:
HV.1 > C10279T > Orf1a:A3688V (C11328T) > Orf1a:I1203T (T3873C), S:L455F (G22927T),N:G214S (G28913A)
Query:  T3873C,G28913A
Samples: 13 as of 16/02/2024

**Comment by krosa1910** [comment]
Yep, I think I give up this mega lineage collection now. This would really be the last update if not for something not miraculous. 
New Standard( >10seq from 01-01-2024, a arbitrary but self-explainatary threshold I chose for JN.1* total dominance)
or >5 seq from 01-01-2024 and >50seq overall)

**Comment by FedeGueli** [comment]
Agree thanks great work by now

**Comment by krosa1910** [comment]
NOW ABOUT 20 MUTATIONS REMAIN, I WILL SOON UPDATE ON THE QUERIES AND TREES FOR THEM.

**Comment by FedeGueli** [comment]
Thank you for your work here i m closing it now

**Comment by krosa1910** [comment]
> Thank you for your work here i m closing it now

Yeah, by a crude search XBB* total is only 893/27503, EG.5.1* is 513 and HV.1* is a mere 143, even lower than FLirt being 264. So I don't think this issue is very valuable now, I would turn my effort toward the Flirt one.
