### ISSUE TITLE
Another EG.5.1.3+S:704L(17 seqs, 7 countries)+S:455F(10 seqs, France,USA)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#960]
There seems to be a new branch on EG.5.1.3 different from JG.3 but also gets S:704L and then S:455F. 

EG.5.1.3+A4340G(Orf1a:I1359V)+A2163G(Orf1a:E633G)+C23673T(S:S704L)

GISAID query: A4340G,A2163G,C23673T
No. of seqs: 5(France 3 UK 1 South Korea 1)

First: EPI_ISL_18239694, South Korea, 2023-8-20
Latest: EPI_ISL_18362894, UK, 2023-9-27

GISAID query for S:L455F branch: A4340G,A2163G,C23673T,G22927T

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice53_genome_6edd_b510b0.json?label=id:node_3434550)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/c5338be5-8342-415a-ad88-2646ed98e86b)

**Comment by FedeGueli** [comment]
Interestingly there was a sibling singlet of this one with 455S that never took off : 
England/CLIMB-CM7YRMOM/2023|EPI_ISL_18227115|2023-08-22
EG.5.1.3 > A4340G(ORF1a:I1359V) > A2163G(ORF1a:E633G) > C23185T > T11932G, T14022C, T22926C(S:L455S) [Query: A2163G, A4340G, T22926C, 09/06 
( #537 )

**Comment by aviczhl2** [comment]
11, Finland, USA, Belgium ,Spain

**Comment by FedeGueli** [comment]
2 only samples from November closing it for now. Reopen if something changes.

**Comment by aviczhl2** [comment]
No new seqs

**Comment by FedeGueli** [comment]
Thx. a lot of things are dyiong off.
