### ISSUE TITLE
XBB.1.41.1 with ORF1a:V1056L(nsp3_V238L) and S:G339R (G>D>H>R) through A22578G_reversion (56 seqs, mainly in Greece, 9 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#961]
**Defining Mutations:** `XBB.1.41` > `C18877T` > `T1657C, G3431T(ORF1a:V1056L), A22578G_reversion(S:G339R)`
**Query:** `T1657C, G3431T, C18877T`
**Earliest seq:** 2023-07-16 (`EPI_ISL_18314292`, Attica, Greece)
**Latest seq:** 2023-10-02 (`EPI_ISL_18387126`, Auvergne-Rhône-Alpes, France, _OR_ `EPI_ISL_18356714`, Dublin, Ireland)
**Sampled Countries:** Greece (35), France (11), Finland (2), Israel (2), Italy (2), Denmark (1), Ireland (1), Sweden (1), UK (1: SC)

<details><summary>Genomes: </summary>

`EPI_ISL_18218408, EPI_ISL_18226767, EPI_ISL_18229415, EPI_ISL_18294252, EPI_ISL_18294254, EPI_ISL_18300223, EPI_ISL_18314292-18314294, EPI_ISL_18314343-18314344, EPI_ISL_18314347, EPI_ISL_18314361, EPI_ISL_18314398, EPI_ISL_18314402, EPI_ISL_18314405, EPI_ISL_18314418, EPI_ISL_18314430, EPI_ISL_18314442, EPI_ISL_18314495, EPI_ISL_18314620-18314621, EPI_ISL_18314663, EPI_ISL_18314674, EPI_ISL_18314682-18314683, EPI_ISL_18314779, EPI_ISL_18314781, EPI_ISL_18314786, EPI_ISL_18314793, EPI_ISL_18314798, EPI_ISL_18314836, EPI_ISL_18314934-18314936, EPI_ISL_18315038, EPI_ISL_18315062, EPI_ISL_18315076, EPI_ISL_18315174, EPI_ISL_18315180, EPI_ISL_18315185, EPI_ISL_18326463, EPI_ISL_18326511, EPI_ISL_18326582, EPI_ISL_18338154, EPI_ISL_18338536, EPI_ISL_18347850, EPI_ISL_18347853, EPI_ISL_18356714, EPI_ISL_18360405, EPI_ISL_18362853, EPI_ISL_18366842, EPI_ISL_18387090, EPI_ISL_18387126, EPI_ISL_18387163, EPI_ISL_18387514`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f816_ba9490.json?f_userOrOld=uploaded%20sample&label=id:node_3530104
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/29278dac-81c4-43a5-863c-a908fbbfa5c1)

**Trivia:**
- UShER seems to mask `spike_339`, as you can see multiple branches labeled with `S:H339R` only when you upload those sequences.
- This site seems heavily selected for, it is `S:G339D(G22578A)` introduced since `B.1.1.529`, then got further mutated into `S:G339H(G22577C, G22578A)` from `BA.2.75` (also on `BA.2.86`), which got inherited by `XBB`, and this lineage reverts `A22578G` to make it `S:G339R`, if not artifact, that's some 3-step mutations from G to D to H to R.
- `S:G339R` only has about 310 seqs on GISAID to date, this lineage represents 20% of them.
![G339R](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/0f5dfe7f-5dbc-4c04-b49b-20289a6cb93c)

**Comment by aviczhl2** [comment]
Designated JC.2 @FedeGueli

**Comment by FedeGueli** [comment]
Designated JC.2 via https://github.com/cov-lineages/pango-designation/commit/9b30a5096a3faa1691c8cabb28120b370946ce8e

(flash issue!)

**Comment by FedeGueli** [comment]
I was looking at this one for a second time some thoughts:
it is no more a local lineage and have spread in multiple countries
could be S:L335S to enable S:G339R ? 
Interesting the trend in positive charge from G to R at 339
