### ISSUE TITLE
XBB.1.16 with ORF1a:R135K (nsp1_R135K), S:N185D, ORF1a:A516V (nsp2_A336V), S:F490P and ORF7a:V93L (84 seqs, Canada, USA, Denmark)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#962]
**Defining Mutations:** `XBB.1.16` > `C5203T` > `G669A(ORF1a:R135K), A22115G(S:N185D)` > `C22432T(S:D290)` > `C10726A` > `C1812T(ORF1a:A516V)` > `T23030C(S:F490P)` > `G27670C(ORF7a:V93L)`
**Query:** `C1812T, C10726A, T23030C`
**Earliest seq:** 2023-07-14 (`EPI_ISL_18057566`, Texas, USA)
**Latest seq:** 2023-09-27 (`EPI_ISL_18383633`, Alberta, Canada)
**Sampled Countries:** USA (51: NY/30; OH/13; CA/4; NC/2; TX/2), Canada (27: AB/25; QC/2), Denmark (2)

<details><summary>Genomes: </summary>

`EPI_ISL_18057566, EPI_ISL_18113828, EPI_ISL_18115292, EPI_ISL_18126170, EPI_ISL_18126939, EPI_ISL_18126943, EPI_ISL_18126945, EPI_ISL_18147521, EPI_ISL_18147527, EPI_ISL_18153023, EPI_ISL_18157474, EPI_ISL_18216896, EPI_ISL_18216898, EPI_ISL_18247482, EPI_ISL_18247486, EPI_ISL_18247509, EPI_ISL_18247532, EPI_ISL_18247601, EPI_ISL_18247654, EPI_ISL_18247660, EPI_ISL_18247667, EPI_ISL_18252386, EPI_ISL_18253235, EPI_ISL_18256667, EPI_ISL_18256789, EPI_ISL_18256807-18256808, EPI_ISL_18261252, EPI_ISL_18275853, EPI_ISL_18276316, EPI_ISL_18282592, EPI_ISL_18288054, EPI_ISL_18288071, EPI_ISL_18288112, EPI_ISL_18288212, EPI_ISL_18294583, EPI_ISL_18294666, EPI_ISL_18303621, EPI_ISL_18303820, EPI_ISL_18309304, EPI_ISL_18309510, EPI_ISL_18309692, EPI_ISL_18312175, EPI_ISL_18312204, EPI_ISL_18316244, EPI_ISL_18317278, EPI_ISL_18333570, EPI_ISL_18333581, EPI_ISL_18341355, EPI_ISL_18346078-18346081, EPI_ISL_18346090, EPI_ISL_18346400-18346401, EPI_ISL_18346425, EPI_ISL_18346438, EPI_ISL_18358301, EPI_ISL_18359752, EPI_ISL_18359755, EPI_ISL_18359802, EPI_ISL_18368934, EPI_ISL_18374772, EPI_ISL_18375546, EPI_ISL_18375773, EPI_ISL_18383348-18383349, EPI_ISL_18383368, EPI_ISL_18383435, EPI_ISL_18383445, EPI_ISL_18383487, EPI_ISL_18383491, EPI_ISL_18383548, EPI_ISL_18383555, EPI_ISL_18383633, EPI_ISL_18389332, EPI_ISL_18389385, EPI_ISL_18389410, EPI_ISL_18389503`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_205dc_bb5b20.json?label=id:node_3231914
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/1ff22cf8-98ff-40a8-8248-166541a98e73)

**Comment by FedeGueli** [comment]
It is hard time to compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C1812T%2CC10726A%2CT23030C&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Just three samples from october
