### ISSUE TITLE
Canadian (Ontario) DV.7.1.4 with S:403K and S:L981I [13 seqs as of 2023-10-15]

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#963]
Came across this Canadian DV.7.1.4 with S:403K and S:L981I

Not ready for designation as it could just be a single outbreak - but worth tracking

<img width="2156" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/449b643e-e190-48e5-82d8-c44e075b82f9">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23891_c016e0.json?c=gt-S_403&gmax=25384&gmin=21563&label=id:node_4222092

**Comment by HynnSpylor** [comment]
Oh it has been proposed in #915

**Comment by corneliusroemer** [comment]
Duplicate
