### ISSUE TITLE
DV.7.1.2 + ORF1a:S2246L, ORF1a:A690V, S:V772I (24 in 4 countries)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#964]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/0c0e4f66-584a-4079-b972-39fbad9103a3)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3417c_c68e60.json?c=gt-S_772&gmax=25384&gmin=21563&label=id:node_4222561

First Seq: 2023-08-29
Most Recent: 2023-10-06

Gisaid Query: G23876A, C1063T, C7002T, C12750T

EPI_ISL_18387330 EPI_ISL_18228275 EPI_ISL_18377295 EPI_ISL_18377291 EPI_ISL_18326999 EPI_ISL_18263624 EPI_ISL_18387481 EPI_ISL_18387270 EPI_ISL_18387205 EPI_ISL_18314232 EPI_ISL_18295477 EPI_ISL_18295472 CLIMB-CM7YR8DQ WSI-3311353B CLIMB-CM7YK9AD EPI_ISL_18387181 OY742908.1 EPI_ISL_18380079 CLIMB-CM7YKJ5U EPI_ISL_18337605

**Comment by FedeGueli** [comment]
Already designated JV.2 via https://github.com/cov-lineages/pango-designation/commit/777ef39532d5038125822df850164f8307e41b12
