### ISSUE TITLE
FD.1.1 with ORF1b:H1807Y, S:F157L, N:T379I, N:H300Y, ORF1a:S2114F, S:L455W and N:E367G (20 seqs, Spain, UK)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#967]
**Defining Mutations:** `FD.1.1 (XBB.1.5.15.1.1)` > `C18886T(ORF1b:H1807Y/nsp14_H283Y)` > `C22033A(S:F157L)` > `A17817G` > `C29409T(N:T379I)` > `C29171T(N:H300Y)` > `C6606T(ORF1a:S2114F/nsp3_S1296F), T22926G(S:L455W), A29373G(N:E367G)`
**Query:** `A17817G, C22033A, T22926G`
**Earliest seq:** 2023-07-31 (`EPI_ISL_18112788`, Ribeira, Galicia, Spain)
**Latest seq:** 2023-09-06 (`EPI_ISL_18388510`, Vigo, Galicia, Spain)
**Sampled Countries:** Spain (3: GA/2; AN)

<details><summary>Genomes: </summary>

`EPI_ISL_18112788, EPI_ISL_18388510, EPI_ISL_18391250`</details>

**UShER:**
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_13b1d_d1dda0.json?label=id:node_3650863
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/06d6eaf4-9b84-4432-a627-877d2b330ddc)

**Comment by FedeGueli** [comment]
It looks superslow , thx for tracking.

**Comment by FedeGueli** [comment]
No recent samples tough

**Comment by FedeGueli** [comment]
> EPI_ISL_18453737

From mid september

**Comment by FedeGueli** [comment]
there should be two more smaples from Climb database according to Dave McNAlly tool

**Comment by FedeGueli** [comment]
I think this should be proposed once reaches 20

**Comment by FedeGueli** [comment]
> 11-06, 1 more from England `EPI_ISL_18466925`

Using the Dave McNally tool i see 10 sequences on CLimb Uk. please propose it i m trying to grab an usher for them

**Comment by FedeGueli** [comment]
19 now the batch from Uk just uploaded

**Comment by FedeGueli** [comment]
20! +1 from Spain please propose it
