### ISSUE TITLE
XDB: XBB.1.16.19 Mystery 3’-end Recombinant with novel suboptimal TRS (T1834A, G1835A, G1836A = ORF1a:G524N) + ORF3a:H93Y, ORF1b:V1590I 

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#969]
### **Description**
**Sub-lineage of:** XBB.1.16.19
**Earliest sequence:** 2023-8-7, France — EPI_ISL_18215129, EPI_ISL_18215132, EPI_ISL_18228734
**Most recent sequence:** 2023-9-25, France — EPI_ISL_18387785
**Countries circulating:** France (29), Luxembourg (1), New Zealand (1)
**Number of Sequences:** 31
**GISAID Nucleotide Query:** (T1834A, G1835A, G1836A ) specific query for this : _G1835A, G1836A, T2935C (EDITED)_
**CovSpectrum Query:** Nextcladepangolineage:XBB.1* & [3-of: T1834A, G1835A, G1836A]
**Substitutions on top of XBB.1.16.19:**
**ORF3a:** H93Y
**ORF1a:** G524N
**ORF1b:** V1590I
**Nucleotide:** T1834A, G1835A, G1836A, T2935C, T6262C, G18235A, C25669T, C26885T

**Phylogenetic Order of Mutations:**  C26885T **→** T2935C, T6262C, G18235A, C25669T (ORF3a:H93Y, ORF1b:V1590I)   **→**   T18975C, G22225T   **→**   T1834A, G1835A, G1836A (ORF1a:G524N) 

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XCV_T1834A_G1835A_G1836A.json?c=gt-nuc_1834&gmax=2834&gmin=834&label=id:node_3313929 
<img width="1488" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e104bc19-0874-4d62-8249-50f34d183938">
 

**Evidence**
I’m not certain that this comes from a recombinant lineage, but there seem to be about 250 sequences of XBB.1.16.19 that lack A28447G and C29386T, both of which are in all other XBB.1.16* lineages. The country with the most is Indonesia, with 71 according to CovSpectrum. Perhaps it’s an artifact of some sort. If so, I’ll edit the title and the proposal. 

I keep track of novel TRS motifs that I come across & have seen over a hundred, but this one was new to me. Turns out there have been 13 previous sequences with this multi-nuc mutation, but the most recent was in September 2022. 

.
<img width="1504" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/7edefa73-37b8-4a1b-a42f-2e8ad849dc30">
.

Interestingly, one sequence has already picked up a 4th mutation—an A→C mutation no less—that adds to the extended homology. 

.
<img width="1367" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ac8869e3-5d40-4d32-8a6a-745f9f5cfa55">

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18215129, EPI_ISL_18215132, EPI_ISL_18228734,
EPI_ISL_18228858, EPI_ISL_18228861, EPI_ISL_18229524-18229525,
EPI_ISL_18231871, EPI_ISL_18258281, EPI_ISL_18258367,
EPI_ISL_18258374, EPI_ISL_18258383, EPI_ISL_18258448,
EPI_ISL_18258458, EPI_ISL_18258464, EPI_ISL_18258694,
EPI_ISL_18280724, EPI_ISL_18280832, EPI_ISL_18281000,
EPI_ISL_18287732, EPI_ISL_18287753, EPI_ISL_18313751,
EPI_ISL_18314177, EPI_ISL_18326552, EPI_ISL_18326864,
EPI_ISL_18326869, EPI_ISL_18357037, EPI_ISL_18357160,
EPI_ISL_18387693, EPI_ISL_18387785, EPI_ISL_18391674,
</details>

**Comment by FedeGueli** [comment]
Thx @ryhisner i ve edited the query in G1835A, G1836A, T2935C cause your one catches also old unrelated samples!

**Comment by FedeGueli** [comment]
It doesnt seem too slower than HK.3: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G1835A%2CG1836A%2CT2935C&analysisMode=CompareToBaseline&
and clearly faster than parent XBB.1.16* :https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.1.16*&nucMutations1=G1835A%2CG1836A%2CT2935C&analysisMode=CompareToBaseline&

Could this be a good catch for some recombinations??

**Comment by aviczhl2** [comment]
I looked at branches of this XBB.1.16.19-recomb, and no seqs with C26885T, C2878T or T10150C(3 largest sub-branch) appears together with both G15982A and (28447 or 29386). 

This means the recomb is likely real and these mutations are all gained after the recomb event.

**Comment by aviczhl2** [comment]
@corneliusroemer The root of this one is also a 200-sized recombinant despite Fede doesn't put a label.

**Comment by corneliusroemer** [comment]
Thanks I've seen this too - I agree double reversion makes this a likely a real recombinant so will designate

**Comment by FedeGueli** [comment]
Designated XDB via https://github.com/cov-lineages/pango-designation/commit/f1e5c7261d5f0344c7b4e647cac12554b00b2c29
