### ISSUE TITLE
FL.2.3 (XBB.1.9.1.2.3) with ORF1ab: K5784R and S: Q146K（198 seqs multiple countries）

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#97]
Sub-lineage of:FL.2
Earliest sequence:2023-04-07,Guangdong
Most recent sequence:2023-05-11,USA
Countries circulating:China 70, Ireland 1, England 1, United States 1
GISAID search：T4579A,A17615G,C21998A

sequence
<details><summary>Genomes:</summary>
EPI_ISL_17545640, EPI_ISL_17584630, EPI_ISL_17615002,EPI_ISL_17625276, EPI_ISL_17625305, EPI_ISL_17625315，EPI_ISL_17625360, EPI_ISL_17625389,EPI_ISL_17625431, EPI_ISL_17625499, EPI_ISL_17625567,EPI_ISL_17625585, EPI_ISL_17632975 ，EPI_ISL_17632976, EPI_ISL_17645472,EPI_ISL_17645513, EPI_ISL_17664527, EPI_ISL_17671914,EPI_ISL_17671919, EPI_ISL_17671944 ，EPI_ISL_17671945,EPI_ISL_17671949,EPI_ISL_17671951, EPI_ISL_17671956，EPI_ISL_17671957,EPI_ISL_17672024,EPI_ISL_17678284,EPI_ISL_17678372,EPI_ISL_17678427,EPI_ISL_17678450, EPI_ISL_17680003, EPI_ISL_17684000,EPI_ISL_17684191, EPI_ISL_17684329, EPI_ISL_17696835,EPI_ISL_17697630, EPI_ISL_17697636, EPI_ISL_17697691,EPI_ISL_17697695, EPI_ISL_17697698, EPI_ISL_17697760,EPI_ISL_17697763, EPI_ISL_17697767, EPI_ISL_17697786,
EPI_ISL_17697803, EPI_ISL_17697836, EPI_ISL_17697849-17697850,
EPI_ISL_17697880, EPI_ISL_17697883, EPI_ISL_17697914,
EPI_ISL_17698013, EPI_ISL_17698015, EPI_ISL_17698032,
EPI_ISL_17698034, EPI_ISL_17698046, EPI_ISL_17698073,
EPI_ISL_17698078, EPI_ISL_17698087, EPI_ISL_17698104,
EPI_ISL_17698123, EPI_ISL_17698226, EPI_ISL_17698233-17698234,
EPI_ISL_17698248, EPI_ISL_17698260, EPI_ISL_17698267,
EPI_ISL_17698275, EPI_ISL_17698284, EPI_ISL_17698292,
EPI_ISL_17700760, EPI_ISL_17703623, EPI_ISL_17703996
</details>

UShER Tree：
I directly referenced the UShER tree of @Over-There-Is because it seems to better reflect. I'm sorry for the error, but the UShER tree seems to be dirty.
https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_39469_cdac30.json
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/885706d1-5950-4cf6-be06-9c5d7a4b0516)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125779492/5b20c25e-e756-4a82-b2f2-21e2430797f6)

**Comment by JosetteSchoenma** [comment]
Thank you for making this issue. I was keeping an eye on this one as well, but I got a different and confusing Usher tree with a H146K reversion branch. Would you like to tell me how you made this your tree?

I used this query on GISAID. C11956T, C12789T, -T17124C, A17615G,  Spike_H146K plus -G27225a (78 samples) to exclude a branch of mostly samples from the USA, of which I am not sure whether Usher misplaced them.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/2b750952-e1b8-4f42-9846-78dfecffa9f4)
USA branch (XBB.1.9.1)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/5dcde463-6e62-46f8-a57a-0495c526738b)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/96422f34-eb99-4058-9ed0-4a82cabc42f5)

And I checked Guandong. It seems to have jumped to around 7% of the samples in week 16, but did not seem to grow after that. 6% in week 18.

**Comment by FedeGueli** [comment]
It has been already pre proposed here in #78 and theb transferred to Pango : https://github.com/cov-lineages/pango-designation/issues/2016

**Comment by FedeGueli** [comment]
Once the parental lineage got assigned then we can open #78
or this one.

**Comment by Memorablea** [comment]
> Once the parental lineage got assigned then we can open #78 or this one.

I understand, as I just said, there was an error in my screening, and I'm sorry. Next, let's wait for [#2016](https://github.com/cov-lineages/pango-designation/issues/2016)

**Comment by Over-There-Is** [comment]
It seems unreasonable that the earlier detected sequences are placed on the further place, so I downloaded the json file and edit it manually.

**Comment by Over-There-Is** [comment]
Hubei+2 Yunnan+1

**Comment by Over-There-Is** [comment]
Ohio, US+1

**Comment by Memorablea** [comment]
> Ohio, US+1

Thanks for your contribution, I'll change the title as the sequence grows.

**Comment by Over-There-Is** [comment]
South Korea 1, Singapore 1, Shanghai 4(1 from S. Korea, 1 from Vietnam, 1 from Thailand), Hubei 3, Shanxi 1. 88 seq now.
Not only China, US, UK, Ireland, Singapore, S. Korea, but also Vietnam, Thailand, and there was a sequence in Shanghai imported from UAE, totally 9 countries.

**Comment by Over-There-Is** [comment]
+1, Sichuan

**Comment by Over-There-Is** [comment]
Totally 89 now, but two of them also have N:R189L mutation. S:Q146K is more homoplastic than N:R189L, therefore I believe their gain N:R189L before S:Q146K.

**Comment by Over-There-Is** [comment]
California+1

**Comment by Over-There-Is** [comment]
Spain +1

**Comment by Over-There-Is** [comment]
Anhui +1

**Comment by Over-There-Is** [comment]
California +1, Shanghai +2(1 from Malaysia)

**Comment by Over-There-Is** [comment]
Xinjiang +1, 98 now

**Comment by Over-There-Is** [comment]
South Korea +1, from China

**Comment by FedeGueli** [comment]
Reopened this one. Be aware that in my opinion 146 is very tricky always. i dont see this one clearly faster than other sub-branches.

**Comment by FedeGueli** [comment]
![Schermata 2023-06-12 alle 19 24 55](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f6cd75ac-cba9-445a-ab88-de44092269c4)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3A1383R%2CN%3AG236V&aaMutations1=S%3A146K%2Corf1b%3A1383R&analysisMode=CompareToBaseline&

**Comment by Over-There-Is** [comment]
> ![Schermata 2023-06-12 alle 19 24 55](https://user-images.githubusercontent.com/87669813/245220077-f6cd75ac-cba9-445a-ab88-de44092269c4.png) https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3A1383R%2CN%3AG236V&aaMutations1=S%3A146K%2Corf1b%3A1383R&analysisMode=CompareToBaseline&

#127 is also Orf1b:K1383R+S:H146K.

**Comment by Memorablea** [comment]
I think we should keep turning it off

**Comment by Over-There-Is** [comment]
France +1

**Comment by Over-There-Is** [comment]
France +1

**Comment by Over-There-Is** [comment]
61 seqs from several provinces in China, 1 also have N:R189L (maybe convergent)

**Comment by FedeGueli** [comment]
175 as today

**Comment by Memorablea** [comment]
198 now

**Comment by FedeGueli** [comment]
@Memorablea please propose this one in the main page.

@NkRMnZr please propose the two branches you found with 456 and 490 in two separated issues. thank you

**Comment by Memorablea** [comment]
> @Memorablea please propose this one in the main page.

Home page? Do you mean sars-cov-2-variants or cov-lineages?

> @NkRMnZr please propose the two branches you found with 456 and 490 in two separated issues. thank you

And do you mean what NkRMnZr pointed out?

**Comment by FedeGueli** [comment]
> > @Memorablea please propose this one in the main page.
> 
> Home page? Do you mean sars-cov-2-variants or cov-lineages?
> 


The main page is the official pango page.

> > @NkRMnZr please propose the two branches you found with 456 and 490 in two separated issues. thank you
> 
> And do you mean what NkRMnZr pointed out?

Yes i mean he/she should propose them both , separately

**Comment by Memorablea** [comment]
转移至https://github.com/cov-lineages/pango-designation/issues/2078
