### ISSUE TITLE
HN.4  + S:Q14H (58)  and a branch with ORF1a:T333M (32)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#971]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/a91759c9-bb0d-4580-8552-250f1c9a8333)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ed8b_e03e60.json?c=gt-S_14&gmax=25384&gmin=21563&label=id:node_3391956

First Seq: 2023-08-18
Most Recent: 2023-10-02

Gisaid Query: G21604T, T1243C, C25710T

EPI_ISL_18376989 EPI_ISL_18387774 EPI_ISL_18326895 EPI_ISL_18387824 EPI_ISL_18376998 EPI_ISL_18327009 EPI_ISL_18280614 EPI_ISL_18370655 EPI_ISL_18370654 EPI_ISL_18377012 EPI_ISL_18263904 EPI_ISL_18374030 EPI_ISL_18376994 EPI_ISL_18263846 England/CLIMB-CM7YFWUT/2023 EPI_ISL_18376990 EPI_ISL_18376992 EPI_ISL_18376993 England/CLIMB-CM7YKI98/2023 EPI_ISL_18370619 England/CLIMB-CM7YK5UD/2023 EPI_ISL_18263882 EPI_ISL_18376988 EPI_ISL_18355189

**Comment by FedeGueli** [comment]
It appears fast: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=G21604T%2CT1243C%2CC25710T&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Designated HN.4.2 via https://github.com/cov-lineages/pango-designation/commit/9666613d7b2c2d694b1d02e286d08be07d10c060
