### ISSUE TITLE
Another EG.5.1/DV.7.1 recombinant that may be removed by usher(27 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#972]
There is another EG.5.1/DV.7.1 recombinant different from XCT.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/cd77db62-c540-4e7c-a8f8-6d7847836aba)

EG.5.1--DV.7.1
Breakpoint between 14125 and 15025. 

Additional mutations: del518_520, C1471T, C3397T, T14124A,C15924T, C29518T,T29793A

Orf1a: M85-

del518_520, C1471T,T14124A from a EG.5.1 branch having S:F186L
C15924T, C29518T, T29793A from a DV.7.1 branch

C3397T are private.

GISAID query:C3397T,T14124A,C15924T(edited)
No. of seqs: 4(Belgium 1 Canada 3)

EPI_ISL_18393248, Belgium, 2023-9-27
EPI_ISL_18395603,18395605-18395606, Canada, 2023-10-10

@AngieHinrichs, please add them to usher tree. 

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice26_genome_2a567_df9e60.json)

The top branch is XCT, the proposed is lower branch.

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/59d640d7-ff87-4455-afd2-7b1f0d3769de)

[usher for EG.5.1 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3caf1_e02570.json?c=gt-nuc_1471,14124&gmax=15124&gmin=471&label=id:node_3430751)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/223494f8-b727-40ec-8865-d9941ce82ba7)

[usher for DV.7.1 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_2a567_df9e00.json?c=gt-nuc_15924,29518,29793&gmin=14924&label=id:node_4223826)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2bca6833-490b-41ea-b807-6e5c1b562efa)

**Comment by FedeGueli** [comment]
+1 Belgium

**Comment by aviczhl2** [comment]
EPI_ISL_18406446
@AngieHinrichs

**Comment by aviczhl2** [comment]
+1 Switzerland without 12599, edit proposal.

**Comment by FedeGueli** [comment]
> +1 Switzerland without 12599, edit query.

thank you

**Comment by aviczhl2** [comment]
> +3 Canada
> 
> please propose once it reaches 25

Shall be +5, 2 of the seqs has 518 masked. altered query.

**Comment by FedeGueli** [comment]
Thx for the new query

**Comment by ryhisner** [comment]
Interesting that this one has T29793A. This is directly adjacent to the octanucleotide motif (ONM), whose purpose is unknown but which I believe is absolutely conserved in either all beta-coronaviruses or all coronaviruses. T29793A has only been in ~2200 sequences ever according to CovSpectrum, and I'd bet that a fair fraction of those are sequencing artifacts, which are pretty common in the 3' UTR. 

True to form, the ONM is virtually never mutated in SARS-CoV-2 genomes. It would be interesting to try to find which mutations in the ONM are real, if any, but it's a Herculean task to try to sort out real 3' UTR mutations from artifactual ones. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7766253/ 
<img width="1400" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cdf47c4e-6f87-484f-9351-b512f683465a">
<img width="1405" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e30a1a81-026b-4cf5-8d4b-bbae557d7682">

**Comment by aviczhl2** [comment]
+1 Italy
