### ISSUE TITLE
JF.1+Orf1a:H417Y, D4165G, S:Q14H misplaced on a XBB.1.16.6 branch (25 seqs , 7 countries, 22 with S:S810L, 4 with further S:S477K (WA))

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#976]
JF.1+C1514T, A12759G, G21604T,C28657T(Orf1a:H417Y, D4165G, S:Q14H)

GISAID query: A12759G,G21604T,G22927T
No. of seqs:8(USA 6(1 from France),Sweden 1 Canada 1)

First: EPI_ISL_18307795, USA, 2023-9-5
Latest: EPI_ISL_18368547, USA from France, 2023-9-29

usher misplaces on direct branch of XBB.1.16.6+G22927T, however most of the seqs do have C23986T, indicating they're actually JF.1.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice12_genome_2a567_df9e20.json?branchLabel=nuc%20mutations&label=id:node_3275226&showBranchLabels=all)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/6bbaba62-ca01-434c-b3b9-38f36eaa1a5c)

**Comment by aviczhl2** [comment]
18, UK, Australia

**Comment by FedeGueli** [comment]
There should be more samples on CLimb i saw this yesterday on the Dave McNally tool

**Comment by FedeGueli** [comment]
> usher misplaces on direct branch of XBB.1.16.6+G22927T, however most of the seqs do have C23986T, indicating they're actually JF.1.

cc @angiehinrichs.


Here the new USHer:
![Schermata 2023-11-02 alle 10 00 57](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/926492f4-dd54-45ef-972e-205c2fdd8ce3)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_3dfbb_3650a0.json?label=id:node_3283124

Note that all 4 WA samples have S:S477K 
there are two more british samples on Climb with a small saltation with M:S212N too.

**Comment by FedeGueli** [comment]
@aviczhl2 i have edited the headline , please propose it when reaches 25 and @angiehinrichs will have fixed the placement!

**Comment by AngieHinrichs** [comment]
I see there are a lot of scattered C23986T's in XBB.1.16.6, thanks for pointing that out.  I will try to get to that soon.

**Comment by aviczhl2** [comment]
+1 New Zealand
