### ISSUE TITLE
CH.1.1.12 Sublineage with S:S486P, S:P1162R (4/6), M:A2S, N:S327L, ORF7a:Q62*, ORF1a:S376L, ORF1a:R2860S, ORF1b:P1967S (2 continents, 6 seq, May 25)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#98]
### **Description**
**Sub-lineage of:** CH.1.1.12
**Earliest sequence:** 2023-3-10, Netherlands — EPI_ISL_17275580
**Most recent sequence:** 2023-5-11, Netherlands — EPI_ISL_17711057
**Countries circulating:** Netherlands (5), Japan (1)
**Number of Sequences:** 6
**GISAID AA Query:** Spike_F486P, Spike_P1162L, NS7a_Q62*
**GISAID Nucleotide Query:** A8845C, A23056G, T23018C
**CovSpectrum Query:** Nextcladepangolineage:CH.1.1* & [5-of: G1141A, C1392T, A8845C, C19366T, A23056G, T23018C, C25047G, G26526T, C27059T, C27577T, C29253T]
**Substitutions on top of CH.1.1.12:**
**Spike:** S486P, P1162R
**N:** S327L
**M:** A2S
**ORF1a:** S376L, R2860S (NSP2_S196L, NSP4_R97S)
**ORF1b:** P1967S (NSP14_P443S)
**Nucleotide:** G1141A, C1392T, A8845C, C19366T, A23056G, T23018C, C25047G, G26526T, C27059T, C27577T, C29253T
 
**Phylogenetic Order of Mutations:** G1141A (syn), A8845C (ORF1a:R2860S) **→** C1392T (ORF1a:S276L), C19366T ORF1b:P1967S, A23056G (syn), T23018C (S:S486P), G26526T (M:A2S), C27059T (syn), C27577T (ORF7a:Q62*), C29253T (N:S327L) 
 
+ **→** C25047G (S:P1162R)——4/6 sequences only

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/CH.1.1.12_S486P_ORRF7aSTOP_etc.json
<img width="1442" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/88f9a135-8d73-4ecc-95b2-922436ae590e">

**Evidence**
Just a few notes:
• Thus far, S:S486P has not performed well in CH.1.1* lineages, possibly because it is incompatible with S:K444T and/or S:L452R
• S:P1162R, which is in the four most recent sequences, is a C->G nucleotide mutation, the rarest type.
• N:S327L is a convergent mutation in chronic-infection/highly mutated sequences
• A23056G is a synonymous mutation in the crucial AA residue S:498. It opens up the possibility of Q498W which would have previously required two nucleotide changes. Furthermore, it only requires a C->T nuc mutation, by far the most common type. S:W498 is probably highly deleterious, so this likely doesn't matter much.
• ORF7a:Q62* is also in the saltation lineage XBB.1.33 (which has S:K964E, among other mutations).
 
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_17275580, EPI_ISL_17626499, EPI_ISL_17629782, EPI_ISL_17689073, EPI_ISL_17711038, EPI_ISL_17711057
</details>

**Comment by FedeGueli** [comment]
Still 6 seqs. it seems dying off lets wait one more week before closing it.

**Comment by FedeGueli** [comment]
Closing this for now.
