### ISSUE TITLE
HK.3+S:Q14H via G21604C (37 seqs, 16 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#980]
We already have HK.2.1 for EG.5.1.1+Q14H+L455F, but it is via G21604T, and now there's another branch under HK.3 with G21604C resulting in the same as HK.2.1.

HK.3+T22849C,A28877T,G28878C+G21604C(S:Q14H)

GISAID query:T22849C,G21604C,G22927T
No. of seqs: 5 (South Korea 2 Australia 1 China 2(Shanghai, Sichuan))

First: EPI_ISL_18284786, Sichuan, 2023-8-30
Latest: EPI_ISL_18360206, Shanghai, 2023-9-20

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_43608_f25620.json?label=id:node_3469881)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/75519092-2b85-4ab1-ab59-509a44b85648)

**Comment by FedeGueli** [comment]
Sorry i missed this one thanks,

**Comment by aviczhl2** [comment]
+1 Switzerland +1 Austria

**Comment by FedeGueli** [comment]
It doesnt seem fast

**Comment by aviczhl2** [comment]
+1 Denmark

**Comment by aviczhl2** [comment]
14, Norway, Canada

**Comment by aviczhl2** [comment]
New country of Italy

**Comment by aviczhl2** [comment]
19, Malaysia

**Comment by FedeGueli** [comment]
last sample from the first half of November, likely it was bigger than we saw but i think it is already calming down. lets see

**Comment by aviczhl2** [comment]
22, Singapore

**Comment by FedeGueli** [comment]
Slowed down a lot-

**Comment by aviczhl2** [comment]
+1 Spain

**Comment by aviczhl2** [comment]
31, Japan

**Comment by aviczhl2** [comment]
34, France

**Comment by aviczhl2** [comment]
+1 New Zealand

**Comment by FedeGueli** [comment]
> +1 New Zealand

also the only one samople from January lets see if it survives

**Comment by aviczhl2** [comment]
No new samples
