### ISSUE TITLE
FL.20 with ORF1a:N2628D (nsp3_N1810D), S:K356T and N:Q281L (10 seqs, Singapore)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#981]
**Defining Mutations:** `FL.20` > `A9052T` > `T29785C` > `C25692T` > `A23746T(S:P728)` > `A8147G(ORF1a:N2628D), C9778T, C15951T, A22629C(S:K356T), C28714A, A29115T(N:Q281L)`
**Query:** `A9052T, A22629C, T29785C`
**Earliest seq:** 2023-09-20 (`EPI_ISL_18373103`, Singapore)
**Latest seq:** 2023-10-09 (`EPI_ISL_18399133`, Singapore)
**Sampled Countries:** Singapore (8)

<details><summary>Genomes: </summary>

`EPI_ISL_18355664, EPI_ISL_18361876, EPI_ISL_18361938, EPI_ISL_18373103, EPI_ISL_18399126-18399127, EPI_ISL_18399131, EPI_ISL_18399133`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_4344a_f64c80.json?label=id:node_3344661
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ec84fc0d-a0a7-4a65-aea2-3592d050eda6)

**Comment by FedeGueli** [comment]
10 apparently slow closing it:
