### ISSUE TITLE
EG.5.1/XBB.1.5.70 recombinants, Belgium/France/Spain/Denmark (9 seqs)

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#984]
Came across some potential undesignated recombinants that share properties of both EG.5.1 and XBB.1.5.70

<img width="2191" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/7996a2b6-a1a8-478e-a6ac-c2e3c90d7d87">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_123b8_fc5810.json?label=id:node_3717968

```
hCoV-19/Belgium/UGent-1524/2023
hCoV-19/Denmark/DCGC-661082/2023
hCoV-19/Belgium/AZDelta-2340-02185/2023
hCoV-19/Belgium/AZDelta-2340-02136/2023
hCoV-19/Belgium/AZDelta-2339-05890/2023
hCoV-19/Spain/CT-HUVH-M26038/2023
hCoV-19/France/PAC-HCL723000936001/2023
```

GISAID Query: `T28297C, C29625T,C1889T, C2334T, G12467T`

Probably multiple recombinants, the top one is likely a single one (3x Belgium, 1x Spain) - if someone wants to do a breakpoint analysis, be my friend!

**Comment by aviczhl2** [comment]
The top one is #947

**Comment by aviczhl2** [comment]
> Thanks @aviczhl2! I wonder how we can make it easier to find recombinants that have already been analyzed.

It seems difficult. 

Firstly we shouldn't rely on fixed usher tree placements(eg under which variant) as they may change. As far as I know XCV experienced at least 2 placement changes, and other recombs also. 

Maybe we can use private mutations but it is not easy to figure out private mutations at the first glance too. 

There are some manual labels like mixBA1BA2postspike for past BA.1/BA.2 recombs on usher, is it easy to create such labels so that each recomb is tied to a label #n when proposed?

**Comment by aviczhl2** [comment]
Maybe we can maintain a google sheet for labels on usher tree. Everyone just add seq IDs to that sheet?

@AngieHinrichs, is it easy to process such a sheet automatically every day and assign labels to the correlating variants accordingly?

**Comment by corneliusroemer** [comment]
I think it would be best to keep it light for a start and not wire it into Usher (unless this is easy for Angie).

What we'd want is essentially something similar to `lineages.csv` but for not-yet-designated recombinants.

We could maintain it in this repo here and call it `recombinants.csv` and a simple format:

```
strain,issue_URL
```

I will create an example for the top cluster. This could then be easily searched by anyone using e.g. grep and a list of strain names to see if the recombinant has been proposed.

**Comment by corneliusroemer** [comment]
@aviczhl2 I've created a recombinants.tsv in the root of the repo

One can easily add the recombinants with the helper script `utils/add_to_recombinants.sh` with the tsv that one gets from Usher/Auspice through the "Download metadata interface"

**Comment by corneliusroemer** [comment]
@aviczhl2 I'll give you write access to the repo then you can add them directly!

**Comment by aviczhl2** [comment]
> @aviczhl2 I'll give you write access to the repo then you can add them directly!

Sure.

**Comment by corneliusroemer** [comment]
Yep great! For a start it's fine to just have the issue url as opposed to the exact branch number.

**Comment by FedeGueli** [comment]
> I'm start maintaining that .tsv now.
> 
> For this issue besides what proposed in #947 I'd like to separate the rest into 3 branches ,
> 
> Branch 1 for France/GES-IPP16300/2023|EPI_ISL_18076084|2023-07-10 Branch 2 for France/PAC-HCL723000936001/2023|EPI_ISL_18228989|2023-08-07 Branch 3 for Belgium/UGent-1524/2023|EPI_ISL_18403134|2023-10-01 and Denmark/DCGC-661082/2023|EPI_ISL_18377615|2023-09-25

thank you

**Comment by AngieHinrichs** [comment]
> See: https://github.com/sars-cov-2-variants/lineage-proposals/blob/main/recombinants.tsv

That is perfect!  I will start importing that into the build tomorrow (2023-10-19).  Thanks @corneliusroemer and @aviczhl2 !

**Comment by FedeGueli** [comment]
9 now with one sample uploaded today from Denmark.  it seems slow.

**Comment by aviczhl2** [comment]
The usher tree seems completely altered for the proposal and the 4 recombs seem separated apart now,

**Comment by FedeGueli** [comment]
> The usher tree seems completely altered for the proposal and the 4 recombs seem separated apart now,

closing it for now.

**Comment by FedeGueli** [comment]
the two usher are :
1
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_55db7_7be930.json?label=id:node_3604994
![Schermata 2023-11-29 alle 23 51 22](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/15baf7ce-673a-4f10-804e-96e3c04d3997)

2
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_55db7_7be930.json?f_userOrOld=uploaded%20sample&label=id:node_3721821
![Schermata 2023-11-29 alle 23 52 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3a0d6e92-8fca-4bef-9ecc-9711525bb8ff)
