### ISSUE TITLE
small saltation of BA.2.86.1 branch with S:N487T, ORF1a:P820L, ORF1a:A2593V, N:T379I (38 seqs in Denmark, Sweden and UK)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#985]
Spotted first by @ryhisner 

Defining mutations:
BA.2.86.1>C2724T (ORF1a:P820L), C8043T (ORF1a:A2593V), A23022C (S:N487T), C29407T (N:T379I)
GISAID query: C2724T, C8043T, A23022C

Earliest seq: 2023-10-02 (Denmark- EPI_ISL_18389245)
Most recent seq: 2023-10-05 (Sweden- EPI_ISL_18399505)
Countries detected: Denmark (2), Sweden (1)

Usher Tree:
![QQ截图20231018200818](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/61249146-ba12-4fac-ba6a-6b8e90bd16ac)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3fa35_fbe800.json

(*Actually, all the 3 seqs get S:N487T, but it is not shown on Sweden seq)

 
S:N487 is relatively less changed on RBD, Now these seqs show S:N481K-E484K-F486P-N487T. Despite it seems decreasing the fitness on XBB.1.5-like Spike, it is still hard to say how it works on BA.2.86. and we can track it for a time.

Genomes:
EPI_ISL_18389245, EPI_ISL_18389254, EPI_ISL_18399509,

**Comment by FedeGueli** [comment]
This was spotted and described by @ryhisner on the open discussion. I updated the proposal to credit him.
Thx for proposing

**Comment by FedeGueli** [comment]
+1 Denmark

**Comment by agamedilab** [comment]
18 seq (UK, Sweden, Denmark) as of 30.11.23. Subtree also carries S:N487T.

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/77b498c9-2d40-469d-ac37-da3ff67e0927)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d8bb_83cb30.json?c=userOrOld&label=id:node_4483555


EPI_ISL_18338879, EPI_ISL_18338901, EPI_ISL_18389245,
EPI_ISL_18389254, EPI_ISL_18399509, EPI_ISL_18442973,
EPI_ISL_18484291, EPI_ISL_18494473, EPI_ISL_18494574,
EPI_ISL_18494582, EPI_ISL_18518827, EPI_ISL_18552782,
EPI_ISL_18556684, EPI_ISL_18556720, EPI_ISL_18556846,
EPI_ISL_18556873, EPI_ISL_18556932, EPI_ISL_18556963

**Comment by FedeGueli** [comment]
+2 denmark

**Comment by FedeGueli** [comment]
25 now

**Comment by corneliusroemer** [comment]
It looks like 487T is an artefact, does it not? It appears all over the place in BA.2.86, but only in certain countries labs. It's in a very mutated region so not surprising if many pipelines mess this up - many pipelines still put reversions in all sorts of places and can't deal with short deletions after all.

We haven't seen 487T much during the pandemic, another reason this may well be artefactual. Sure, it can be real but at least some occurrences seem to be artefactual.

<img width="1629" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/fb9a6441-e4ad-4a04-97d2-5ded46b7d38a">

These are the mutations that cluster here compared to Wuhan-Hu-1
<img width="624" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/1c79a9a9-282f-4688-9012-74de0bda2cc6">

**Comment by FedeGueli** [comment]
> It looks like 487T is an artefact, does it not? It appears all over the place in BA.2.86, but only in certain countries labs. It's in a very mutated region so not surprising if many pipelines mess this up - many pipelines still put reversions in all sorts of places and can't deal with short deletions after all.
> 
> We haven't seen 487T much during the pandemic, another reason this may well be artefactual. Sure, it can be real but at least some occurrences seem to be artefactual.
> 
> <img alt="image" width="1629" src="https://private-user-images.githubusercontent.com/25161793/291935083-fb9a6441-e4ad-4a04-97d2-5ded46b7d38a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTQ4NzcsIm5iZiI6MTcwMzE1NDU3NywicGF0aCI6Ii8yNTE2MTc5My8yOTE5MzUwODMtZmI5YTY0NDEtZTRhZC00YTA0LTk3ZDItNWRlZDQ2YjdkMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwMjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTFiMDFjZmUyYzcwNDkzMTU0OGI0ZjM2OGRkNDhhNTgxMzhhY2I0NGViNzA1ZWVlOWJiYjkzZWQxYzVlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rW2uW1V3-HLzJhnCdKDmMsBLR6wqu65988xPXdlupC4">
> These are the mutations that cluster here compared to Wuhan-Hu-1 <img alt="image" width="624" src="https://private-user-images.githubusercontent.com/25161793/291935299-1c79a9a9-282f-4688-9012-74de0bda2cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTQ4NzcsIm5iZiI6MTcwMzE1NDU3NywicGF0aCI6Ii8yNTE2MTc5My8yOTE5MzUyOTktMWM3OWE5YTktMjgyZi00Njg4LTkwMTItNzRkZTBiZGEyY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwMjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MDNlMjJmNDVkN2U2YWRhOGVjOTJiMmE5MGMyYzIzMDk5OGNiMzFkYTk0OWU5MzJiNGY2MzhjNzIyMjRlMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QoHR0TdAmaWkIlOulVBH56Zev36uLtN47GtRatrxy5I">

same thought about it. still worth tracking a bit more to be sure.

**Comment by FedeGueli** [comment]
slow closing it
