### ISSUE TITLE
EG.5.1.1 Saltation: S:K356T, H681R, ORF3a:A72S, N:P365L, ORF1a:P309L, H1141Y, E2112D, V3751F (13 seq, Germany, Austria, USA, France , Italy)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#986]
_Spotted and proposed first by @corneliusroemer in https://github.com/cov-lineages/pango-designation/issues/2327#issuecomment-1820368895 (EDITED)_

### **Description**
**Sub-lineage of:** EG.5.1.1
**Earliest sequence:** 2023-9-28, USA (New Jersey) – EPI_ISL_18379617
**Most recent sequence:** 2023-10-6, Germany – EPI_ISL_18403336
**Countries circulating:** Austria (2—one a traveler to USA), Germany (1), USA (1)
**Number of Sequences:** 4
**GISAID Nucleotide Query:** T499A, T2633C, C4093A
**CovSpectrum Query:** Nextcladepangolineage:EG.5* & [-of:]
**Substitutions on top of EG.5.1.1.:**
**Spike:** K356T, H681R
**N:** P365L
**ORF3a:** A72S
**ORF1a:** P309L, H1141Y, E2112D, V3751F
**Nucleotide:** T499A, C1191T, T2633C, C3686T, C4093A, A6601C, G11516T, C13019T, A22629C, A23604G, G25606T, C26534T, A27107C, C27600T, C29367T

**Phylogenetic Order of Mutations:** All simultaneous (on one branch)

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.5.1.1_Saltation_K356T_H681R_etc.json?c=gt-nuc_499&gmax=1499&label=id:node_3451968 
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/EG.5.1.1_Saltation_K356T_H681R_etc.json  

<img width="1488" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d027a027-4596-406e-8e06-cce4806fe6dc">

**Evidence**
This is a 15-nucleotide, 8-AA saltation that likely arose in the Austria/Germany region, where very little sequencing is done these days. So this may be more widespread than it appears due to Austria/Germany being an undersequenced region. 

One of the four sequences is a Ginkgo Bozoworks sequence from a traveler from Austria. On the Usher tree, it appears as if it lacks two mutations the others have, but this is only due to the usual awful coverage from Ginkgo, one of the worst labs around, yet which somehow received the federal contract to do some of the most important sequencing of all (airport travel sequences in the US). 

This lineage also has the 3-nuc ORF9b/N TRS extended homology at the end of ORF8, and I think it's likely this was part of the saltation as well. This is a homoplasic mutation though, so Usher groups it with a few other small branches. 

.
<img width="1235" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/aabc8722-5bc2-4a62-8ca4-11c8b1a018d1">
.
.

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18379617, EPI_ISL_18385103, EPI_ISL_18400043, EPI_ISL_18403336
</details>

**Comment by FedeGueli** [comment]
Thx Ryan great catch! i have 5 sequences with the earliest being : 

hCoV-19/USA/NY-CDC-QDX85770892/2023 | Original | EPI_ISL_18379617 | 2023-09-28 | 2023-10-12

**Comment by oobb45729** [comment]
Any idea about what ORF1a:P309L/Q does?

**Comment by ryhisner** [comment]
> Any idea about what ORF1a:P309L/Q does?

Nope. I only have a vague idea of what NSP2 does—probably RNA binding and some sort of interaction with cell translational machinery, I guess? I usually get interested and start researching a protein when I see a mutation in it that appears over and over in chronic-infection sequences, and there just aren't any such mutations in NSP2.

**Comment by FedeGueli** [comment]
+1 Germany

**Comment by FedeGueli** [comment]
+2 NY +2 Germany

**Comment by FedeGueli** [comment]
I didnt notice that was spotted and proposed by @corneliusroemer first in https://github.com/cov-lineages/pango-designation/issues/2327#issuecomment-1820368895   , as he now closed his issue i will keep this one open for a while more.

**Comment by ryhisner** [comment]
Ha, I even commented on that one and apparently had completely forgotten about it three days later.

**Comment by FedeGueli** [comment]
Designated HK.25 via https://github.com/cov-lineages/pango-designation/commit/0c6878b08d611e523d3ca8ad0d664484a5f4a981
