### ISSUE TITLE
JN.1 + ORF6:P57L (C27371T) (38) and JN.1 + ORF1a:F499L (C1762A) (373) and JN.1 + ORF1a:T170I (T18453C)(74)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#987]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/fabddcd7-f87f-4843-8bd8-c0edcf843429)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2e2c9_28f70.json

gisaid query: T27810C, C18894T

First Seq: 2023-08-25
Most Recent: 2023-10-04

**Comment by FedeGueli** [comment]
Yeah the Orf6:P57L was mentioned by me in the open discussion, worth remembering Orf6:P57L was defining of a large undesignated BA.5.2.1 branch emerged in Africa and had in BF.15 its most interesting sublineage.

**Comment by RajLABN** [comment]
JN.1 + NSP2_F319L grows to 61

**Comment by Fearuncle** [comment]
@FedeGueli JN.1 + ORF1a:F499L passed 60 seq.

**Comment by FedeGueli** [comment]
Yes they are the two main branches of JN.1 i think @corneliusroemer is already aware of them

**Comment by Fearuncle** [comment]
13 with s:157f

**Comment by FedeGueli** [comment]
> 13 with s:157f

have you the IDs it is likely artefact reversion

**Comment by RajLABN** [comment]
JN.1 + NSP2 F319L grows to 117

**Comment by Fearuncle** [comment]
added JN.1 + ORF1a:T170I to the proposal

**Comment by FedeGueli** [comment]
Please propose in the main page as JN.1 Branches

**Comment by aviczhl2** [comment]
The Orf1a:F499L branch is designated JN.1.1

**Comment by FedeGueli** [comment]
Orf1a:F499L Designated JN.1.1 via https://github.com/cov-lineages/pango-designation/commit/ad909528afc624fb0cb4f3358da144f715cef61a

**Comment by FedeGueli** [comment]
JN.1 + ORF1a:T170I (T18453C) now Designated JN.1.4 via https://github.com/cov-lineages/pango-designation/commit/20ddbadddc4b7dfef0ec0819486d232acdacc3b8

**Comment by aviczhl2** [comment]
The Orf6:P57L branch is designated JN.1.44
