### ISSUE TITLE
FL.4 with ORF1a:P892S, ORF7a:H37Y, ORF1a:C316R, ORF1b:S775A, ORF1b:A1643V, ORF1b:P2256S and S:R403K (6 seqs, Sweden)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#988]
**Defining Mutations:** `FL.4` > `A28615G` > `C2939T(ORF1a:P892S/nsp3_P74S)` > `T3118C` > `T14127C` > `C27864T(ORF7a:H37Y)` > `T1211C(ORF1a:C316R/nsp2_C136R), C7006A, T15790G(ORF1b:S775A/nsp12_S784A), T18426C` > `C18395T(ORF1b:A1643V/nsp14_A119V)` > `C20233T(ORF1b:P2256S/nsp15_P205S), G22770A(S:R403K)`
**Query:** `C2939T, C7006A, G22770A`
**Earliest seq:** 2023-08-03 (`EPI_ISL_18147768`, Västmanland)
**Latest seq:** 2023-09-23 (`EPI_ISL_18399534`, Västmanland)
**Sampled Countries:** Sweden (6)

<details><summary>Genomes: </summary>

`EPI_ISL_18147768, EPI_ISL_18151525, EPI_ISL_18221518, EPI_ISL_18399523, EPI_ISL_18399534, EPI_ISL_18399564`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1677c_88c20.json?label=id:node_3383028
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/75f67f4a-3d4f-492a-8ddb-37e6f9588eac)

**Trivia:**
- Not a fast one, but it alreay has stepwise spike mutations like `A435S`, `A879S` then `F140L` and `P681R`, also picking up `BA.1`'s `M:D3G` Query for this branch: C17285T, G22865T, G24197T, C28610A (edited)

**Comment by FedeGueli** [comment]
Thank you lets keep tracked the sweden heavily mutated branch of it

**Comment by FedeGueli** [comment]
Thank you
