### ISSUE TITLE
xbb.1.9.2 with ORF1a:S302F, S:K478R, S:N185S (seq. 49)

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#99]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/e0f743cc-38dc-42af-a0eb-8af8e29f1fbe)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/0239c205-bd33-4fb8-a8a7-e12bc61c2163)

first seq. 04-05
most recently 05-09

**Edited:**

Tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1dc39_fdf6b0.json?c=gt-S_478&label=id:nod
![Schermata 2023-05-26 alle 00 24 49](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8babe2c8-b85d-4950-9e2d-0723242e1436)
e_6696064

Gisaid query:
C1170T,C2485T,A22116G

Def. Mutations 
XBB.1.9.2>>Orf1a:S302F  (C1170T)> S:T478R (C22995G) >C2485T>S:N185S (A22116G)

Samples:
EPI_ISL_17622304, EPI_ISL_17630680, EPI_ISL_17630691,
EPI_ISL_17651649, EPI_ISL_17654887, EPI_ISL_17654951,
EPI_ISL_17654985, EPI_ISL_17655076, EPI_ISL_17664321,
EPI_ISL_17670346, EPI_ISL_17681223, EPI_ISL_17681265,
EPI_ISL_17681324, EPI_ISL_17681414, EPI_ISL_17681423,
EPI_ISL_17681471, EPI_ISL_17681475, EPI_ISL_17681498,
EPI_ISL_17681518, EPI_ISL_17681527, EPI_ISL_17681573,
EPI_ISL_17686596, EPI_ISL_17696431, EPI_ISL_17704106,

**Comment by FedeGueli** [comment]
Please propose it once it reaches 50

**Comment by FedeGueli** [comment]
@Fearuncle i cant find the proposal for this one.

**Comment by FedeGueli** [comment]
Now 41.

**Comment by FedeGueli** [comment]
pls  propose it
