### ISSUE TITLE
BA.2.86 with S:H146Q, S:L368I, S:F490S, ORF8;G8* (5 seq. South Africa)

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#993]
Proposal for a sublineage of BA.2.86
Earliest sequence: 04.09.2023 (South Africa)
Countries detected: South Africa

Defining Mutations:
nuc	homoplasies	C11750T, G15451A, T15939C, T17859C, C22000A, C22664A, T23031C, G27915T
ORF1ab	homoplasies	L3829F, G5063S
S	homoplasies	H146Q, L368I, F490S
ORF8	homoplasies	G8*

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/a86c6969-9ebc-484b-bd6f-1868ffa5c5e4)

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/e00eb7e9-113f-4a12-ae4c-92b1ab317ef6)
![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/0151d92b-11c8-49ed-b6eb-7b2cd3a226cc)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d78_2818a0.json

EPI_ISL_18412368, EPI_ISL_18412371, EPI_ISL_18412386,
EPI_ISL_18412393, EPI_ISL_18412395

**Comment by Over-There-Is** [comment]
probably contaminated by XBB.1*

**Comment by HynnSpylor** [comment]
I noticed it before, and I suggest it is contaminated by XBB.1.41* seqs in the same patch -some XBB.1.41* also with C11750T
