### ISSUE TITLE
Potential FL.2.4 / EG.5.1.1+C11173T+S:L455F(Mainpage #2251) / FL.2.4 Sandwich (19 seq, 6 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#994]
_Credit: first spot by @JosetteSchoenma_  (**Edited**)

FL.2.4 / EG.5.1.1+C11173T+S:L455F / FL.2.4?

Query: T4579A, A7150C, C11173T (Edited)

Earliest Sequence: 09-09 Taiwan, China EPI_ISL_18427808
Latest Sequence: 01-03 Bayern, Germany EPI_ISL_18871228
Regions Detected: Australia 9(NSW 8, Victoria 1), China 4(Taiwan 3, Sichuan 1), Japan 3(Osaka 2, Hyogo 1), Germany 1(Bayern), New Zealand 1(Nelson Marlborough), South Korea 1

https://nextstrain.org/fetch/github.com/Over-There-Is/subtreeAuspice/raw/main/subtreeAuspice_genome_1e98b_4f17d0.json?label=id:node_11065235
![2024-01-10 (2)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/2cf54646-a2e9-470d-90f7-345ec8f41291)

Breakpoint 1: 4579\~6541
Breakpoint 2: 25572\~27507

XBB.1.9+S:S486P+
C21T, C673T, G1820A(Orf1a:G519S), A2109G(Orf1a:N615S), C3768T(Orf1a:T1168I), T4579A / C6541T, A7150C(Orf1a:L2295F), C9693T(Orf1a:A3143V), C11173T, G13627A(Orf1b:D54N), A16878T, A18492G, G21718T(S:Q52H), C22480T, G22927T(S:L455F), T22930A(S:F456L), C25572T / C28093T(~Orf8:S67F~)

FE.1.1 has not Orf9b:I5T but Orf1a:S1133G, so the T4579A, C28093T donor is probably not FE.1.1.

C21T, T4579A, C28093T are from FL.2.4
C9693T, G13627A, A16878T, A18492G, G21718T, C22480T, T22930A, C25572T are from EG.5.1.1
HK.3 has G22927T too, but A7150C, C11173T seems from cov-lineages/pango-designation#2251:
EG.5.1.1> C11173T> G22927T(S:L455F)> A7150C(Orf1a:L2295F), _G28212T(~Orf8:D107Y~)_ (3 seq, Qinghai 2, Shanghai 1)

C673T, G1820A, A2109G, C3768T seem private.
FL.2.4+G1820A 1seq, Saitama, Japan
FL.2.4+C3768T 1seq, ARA, France

<details><summary>Sequences:</summary>

EPI_ISL_18409297, EPI_ISL_18411535, EPI_ISL_18411563,
EPI_ISL_18411596, EPI_ISL_18427808, EPI_ISL_18458026,
EPI_ISL_18459886, EPI_ISL_18461779, EPI_ISL_18461896,
EPI_ISL_18461925, EPI_ISL_18513394, EPI_ISL_18536535,
EPI_ISL_18658095, EPI_ISL_18658110, EPI_ISL_18666582,
EPI_ISL_18667259, EPI_ISL_18686993, EPI_ISL_18725324,
EPI_ISL_18871228
</details>

**Comment by JosetteSchoenma** [comment]
New one from Taiwan. 
EPI_ISL_18427808
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/47123f99-a6fb-4974-9979-1a3acdb16e18)

**Comment by Over-There-Is** [comment]
C28093T dropped out, my query doesn't work.

**Comment by FedeGueli** [comment]
> T4579A, A7150C, C11173T

this one works:T4579A, A7150C, C11173T

**Comment by FedeGueli** [comment]
This has slowed down closing for now

**Comment by Over-There-Is** [comment]
Taiwan +1

**Comment by FedeGueli** [comment]
It seems to have some prevalence in taiwan better reopening it.

**Comment by Over-There-Is** [comment]
It's not the recombinant proposed

**Comment by Over-There-Is** [comment]
NZ

**Comment by Over-There-Is** [comment]
It seems T6541Crev is a common artefact in Taiwan.

**Comment by FedeGueli** [comment]
+ 3 australia

**Comment by FedeGueli** [comment]
![Schermata 2023-11-03 alle 09 52 13](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/3a9760b3-51a6-4267-8f3e-378ad8cec810)
https://genome-test.gi.ucsc.edu/cgi-bin/hgPhyloPlace
new tree

Nextclade: (considering that most of smaples have S:A1070T, & Orf8:E106Q )
![Schermata 2023-11-03 alle 09 55 11](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/8dd263b4-bdf7-4811-b9f7-6d6d6ef91448)

**Comment by FedeGueli** [comment]
It appears to have slowed down a lot

**Comment by Over-There-Is** [comment]
Another FL.2.4/EG.5.1.1+S:L455F/FL.2.4 appears.

**Comment by Over-There-Is** [comment]
TW

**Comment by Over-There-Is** [comment]
No sequence in latest batch from NZ and NSW.

**Comment by aviczhl2** [comment]
+3 Japan

**Comment by Over-There-Is** [comment]
Still circulating in Australia, not NSW but Victoria. And it also spreads to Japan. Reopen the issue to track it.

**Comment by Over-There-Is** [comment]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/570b8847-4dce-4c1e-bc29-2b080d5c69e0)
As I expected, Taiwan CDC's equipment is not able to detect 28093.

**Comment by ryhisner** [comment]
The branches on this one are super long. I have to think this is circulating widely in some region of China that has no sequencing. Or maybe some other country in East Asia with no sequencing. The whole branch sticks out like a sore thumb on the tree, and it's not because it's a recombinant. It's because of how long the branches are and its geographical spread. @corneliusroemer, may want to take a look at this and see what you think. JN.1 will probably wide it out, like every other XBB, but it's possible that China's unique immune history could allow something different to persist there even if it can't spread much beyond. 

<img width="1494" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2eb93c27-f5cd-493b-94a1-1db5c649f834">

**Comment by Over-There-Is** [comment]
> The branches on this one are super long. I have to think this is circulating widely in some region of China that has no sequencing. Or maybe some other country in East Asia with no sequencing. The whole branch sticks out like a sore thumb on the tree, and it's not because it's a recombinant. It's because of how long the branches are and its geographical spread. @corneliusroemer, may want to take a look at this and see what you think. JN.1 will probably wide it out, like every other XBB, but it's possible that China's unique immune history could allow something different to persist there even if it can't spread much beyond.
> 
> <img alt="image" width="1494" src="https://private-user-images.githubusercontent.com/33738461/295065686-2eb93c27-f5cd-493b-94a1-1db5c649f834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzI3NzAsIm5iZiI6MTcwNDgzMjQ3MCwicGF0aCI6Ii8zMzczODQ2MS8yOTUwNjU2ODYtMmViOTNjMjctZjVjZC00OTNiLTk0YTEtMWRiNWM2NDlmODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIwMzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZmYwMjE5YzM1ZjI1NTVlNjRjYzM5ODUwODc1ZjhhMzViN2M4ZmU3NTUyNGQ4OGJmYmYyNDg4NzIxMDAwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G_yQCFUQmu2RPnUfVvAPPBOwICbBzPS4ijf4rcJ8MMw">

F3753L branch is an unrelated recombinant. https://github.com/sars-cov-2-variants/lineage-proposals/issues/108#issuecomment-1812296237

**Comment by Over-There-Is** [comment]
sometimes several recombinants with similar breakpoint will be placed together and forms "recombinant island". Both the recombinant in this issue and that recombinant are FL.2.4/EG.5.1.1*/FL.2.4 with T4579A, C6541T and C28093T. But these 2 recombinants have different donors, so they are exactly unrelated.

**Comment by FedeGueli** [comment]
> sometimes several recombinants with similar breakpoint will be placed together and forms "recombinant island". Both the recombinant in this issue and that recombinant are FL.2.4/EG.5.1.1*/FL.2.4 with T4579A, C6541T and C28093T. But these 2 recombinants have different donors, so they are exactly unrelated.

great catch! thx.

**Comment by Over-There-Is** [comment]
Bayern

**Comment by FedeGueli** [comment]
> Bayern

and first from 2024

**Comment by FedeGueli** [comment]
Only one sample in early January closing it for now
