### ISSUE TITLE
Saltation branch of JC.2 (XBB.1.41.1+S:G339R) with S:T236S, S:K444N, S:P809L and ORF1a:I671L, N:G25C (5 seqs in NSW, Australia)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#995]
Defining mutations:
JC:2 [XBB.1.41.1>C18877T>T1657C, G3431T (ORF1a:V1056L)> A22578G (S:H339R)] > A2276C (ORF1a:I671L), T19335C, C22269G (S:T236S),  , G22894T (S:K444N), C23988T (S:P809L), G28346T (N:G25C)
GISAID query: C22269G, G22894T, C23988T
Earliest seq: 2023-09-29 (NSW, Australia- EPI_ISL_18411562)
Most recent seq: 2023-10-03 (NSW, Australia- EPI_ISL_18411748)
Countries detected: Australia (3)

Usher Tree:
![QQ截图20231021011844](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/085ee051-6f19-4a89-8b0c-2754cd8da722)

S:G339H is one of defining mutations of XBB*, and now some branches get further change. S:K444N is a "fitted" choice for S:444 as higher escape potential (Cao et al. 2023)
![QQ截图20231021013035](https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/beba6db6-5cf7-4d81-ab9d-10ad82d7aa04)

Genomes: 
EPI_ISL_18411562, EPI_ISL_18411569, EPI_ISL_18411748

**Comment by FedeGueli** [comment]
@HynnSpylor XBB.1.41.1 + 339R has been assigned alreaady as JC.2! spotted and designated same day ( @nkrmnzr)

**Comment by FedeGueli** [comment]
![Schermata 2023-10-21 alle 09 21 45](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f22a9149-03ae-4870-a7a8-d49e943bfbd8)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_278a7_37b870.json?c=gt-S_236,339,444,809&f_userOrOld=uploaded%20sample&gmax=25384&gmin=21563&label=id:node_3545063

**Comment by HynnSpylor** [comment]
2 more seqs in NSW, Australia

**Comment by FedeGueli** [comment]
No recent sample closing it.
