### ISSUE TITLE
HK.3.1/XBB.1.16.6 recombinant(17 seqs, 6 countries, 2 with S:L582H, 2 with S:S704L)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#997]
XBB.1.16.6 from 1 to 14856, HK.3.1 from 14857 to end.

Additional mutations: G29081T,A29700G 
N:T270I

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/8c23c5e1-359b-4568-86c4-02e6efd5a775)

Using the Slovenia seq as ref but it has S:455,456 masked so not exactly accurate. It is HK.3.1-Spike(Flip+52+157)

XBB.1.16.6--HK.3.1
Breakpoint between 14857 and 16877
 G29081T,A29700G  from an HK.3.1 branch

GISAID query: G29081T,C29625T,A14856G
No. of seqs: 3(France 2 Slovenia 1)

EPI_ISL_18396986, France, 2023-10-2
EPI_ISL_18412837, France, 2023-10-3
EPI_ISL_18402814, Slovenia, 2023-10-11

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice67_genome_a7d1_348e10.json?label=id:node_3224967)

![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/506bd61a-58f2-4f52-b760-dd0eb88b867e)

[usher for HK.3.1 donor](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_a7d1_348d10.json?c=gt-nuc_29081,29700&gmin=28081&label=id:node_3480133)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/42f411cb-3987-4233-97bc-235407ea120f)

**Comment by FedeGueli** [comment]
One month from last sample has been collected it seems slow

**Comment by aviczhl2** [comment]
+2 Italy

**Comment by aviczhl2** [comment]
+1 Denmark

**Comment by aviczhl2** [comment]
+1 Netherlands

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
While not fast in November it  expanded itself to new countries

**Comment by aviczhl2** [comment]
> While not fast in November it expanded itself to new countries

Seems it is getting S:S704L independently.

**Comment by corneliusroemer** [comment]
Just found this independently and it's not super small so I think it's worth designating as it is clearly a recombinant.

**Comment by corneliusroemer** [comment]
It's currently on quite a recombinant branch - but all the others are doublets or at most triplets
<img width="2244" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/dc2e1c00-4a31-4fdf-a8d2-d5e97c7d04aa">

**Comment by corneliusroemer** [comment]
XDJ
