### ISSUE TITLE
Deltacron  AY.122/BA.5.2 Recombinant with Delta NTD, BA.5 RBD, and Delta S2 (2, Russia)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#998]
**EPI_ISL_18416870**
**Country**: Russia
**Collection Date**: 2023-9-29

This sequence is most likely confined to one person and will never circulate, but I think it's worth as I believe it is the first Delta/Omicron recombinant to have the Delta S2 rather than the Omicron S2. I could be wrong about this, but I've ever seen an Omicron recombinant that didn't retain the Omicron S2. Before this sequence showed up, it appeared to me that the Omicron S2, for whatever reason, would inevitably be retained in any Omicron recombinant. 

It's hard to locate the sequence on the Usher tree, but it's the long branch at the very bottom.
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5_Delta_Complex_Recombinant__2023-9-29__EPI_ISL_18416870.json?c=gt-S_137&gmax=25384&gmin=21563 
<img width="1496" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f8ea951e-ca89-44b2-ba3d-028e079e7c8d">
.
Usher misses the deletions and therefore gets a couple things wrong, but below is its mutational summary for this sequence.
.
<img width="1497" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/c93482c8-6043-4d2a-89ef-77514cabd02e">

There appear to me to be four breakpoints, with both the 5' and 3' ends being BA.5—a double-decker sandwich recombinant, if you will. I'll look at synonymous mutations later and narrow down the breakpoints more if I can, but here's what it looks like now to me.

1-6402: **BA.5**
**Breakpoint 1**: ORF1a:2046-ORF1a:2287 (6402-7123)
7123-22034: **Delta**
**Breakpoint 2**: S:158-S:213 (22034-22199)
22200-23075: **BA.5**
**Breakpoint 3**: S:505-S:655 (23075-23524)
23525-24469: **Delta**
**Breakpoint 4**: S:969-S:1146 (24469-24999)
24999-end: **BA.5**

Some of the mutations pictured below may have been inherited (S:Q14H, ORF1b:H1550Y, and others), but this is my best guess as to the private AA mutations in this sequence. 
<img width="1480" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/456e44a3-7376-4bd7-a8d8-ecf647687ae9">
.

Delta's S2 and NTD are both thought to have contributed to its very high fusogenicity/syncytia formation, and therefore its disease severity, so this is an unpleasant surprise. Again, I think it's extremely unlikely this will ever circulate, but it seems, along with the Indonesian Delta from a few months ago, to prove that an Omicron-like RBD is compatible with a Delta NTD and S2, which ought to give us pause and banish the notion that SARS-CoV-2 variants will inevitably become ever-milder in the future.

Gisaid query: T493C, C10336T, C13680T, C14189T (Edited)

**Comment by FedeGueli** [comment]
Initially  I ve  found one that could have been the donor it is a AY.127.1 that circulated in Norway: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AP25S%2CS%3At859N%2COrf1b%3AH1550Y&nextcladePangoLineage=AY.127.1*&
Donor IDs:
EPI_ISL_8928329
EPI_ISL_7984436
EPI_ISL_7984437
EPI_ISL_8744598
Donor tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12f60_4daaa0.json?label=id:node_8607416
![Schermata 2023-10-22 alle 10 56 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b7611ac8-0998-4464-8139-4cc5c4aa251a)

Interesting the donor has S:K1205N G25177T  absent here so if in the recombinant that part has been sequenced it would confirm your BP at 24999 . cc @ryhisner 

**But the recombinant misses a lot of the silent mutations in Orf1b and Spikee that the donor has, so or it came from an sibling branch unsampled branch of it or it is not the donor-**

**Comment by Outpfmance** [comment]
EPI_ISL_18487014 Another sequence, same branch, different patient, Russian October 10 sample.

**Comment by Outpfmance** [comment]
EPI_ISL_18487014 Another sequence, same branch, different patient, Russian October 10 sample.

**Comment by Outpfmance** [comment]
EPI_ISL_18487014 Another sequence, same branch, different patient, Russian October 10 sample.

**Comment by pass-lin** [comment]
![89dca23319a8b2a08d6a8a38c5b144e](https://github.com/sars-cov-2-variants/lineage-proposals/assets/62837036/5b53663a-3c8d-4be7-b713-7d8c263dd6c3)
find second sequence

**Comment by Over-There-Is** [comment]
No additional mutation on the first sequence.

**Comment by FedeGueli** [comment]
Now we have a query: T493C, C10336T, C13680T, C14189T

**Comment by FedeGueli** [comment]
two different patients Mle 26 and female 32. cc @ryhisner

**Comment by Over-There-Is** [comment]
T21802G, C27513T

**Comment by Over-There-Is** [comment]
It is doubtless BA.5.2/21J recombinant.
21846 is provided by the Delta donor, but not mutated. So its Delta donor is probably not on S:T95I branch.
It has G22599C, the BA.5.2 donor could be assumed as BA.5.2.6 temporally.
And it also has C19983T and G20937T, and its 1048 and 25516 is covered by BA.5.2. So the Delta donor could be also assumed as AY.122.1. But it has no C23934T.

Breakpoints:
22B 6402\~7124 21J
21J 22034\~22200 22B
22B 23075\~23525 21J
21J 24469\~25000 22B

Mutations based on B.1:
T493C, T670G, C1627T, C1968T, C2790T, C3602T, G4184A, C4321T, C5869T, C7124T, C8389T, C8964T, C8986T, G9053T, C9967T, 	C10029T, C10336T, A11201G, A11332G, C13680T, C14189T, C14425A, G15451A, C15588T, C15960T, G16377A, C16466T, T16542C, A16638G, C18115T, T19074C, C19220T, T19893C, G19981A, C19983T, C20234T, G20274T, G20937T, G21604T, C21618G, C21627T, C21635T, T21802G, T21973G, G21987A, del22029-22034, del22190-22192, T22200G, del22287-22304, T22307A, G22578A, G22599C, C22674T, T22679C, C22686T, A22688G, G22775A, A22786C, G22813T, T22882G, T22896C, G22898A, T22917G, G22992A, C22995A, A23013T, T23018G, A23055G, A23063T, T23075C, C23248T, A23265G, T23434G, C23604G, C23939T, C24138A, G24410A, C25000T, del25456-25482, G26020T, C26060T, C26270T, G26529A, C26577G, G26709A, C27012T, C27513T, C27807T, C27889T, A27976G, A28271T, C28311T, A28330G, del28362-28370, G28881A, G28882A, G28883C, A29510C, del29734-29759

Mutations shared by both lineage:
C10029T(Orf1a:T3255I), G21987A(S:G142D), T22917G(S:L452R), C22995A(S:T478K)

Mutations from the BA.5.2.6-liked donor:
T670G(Orf1a:R135S), C1627T, C2790T(Orf1a:T842I), G4184A(Orf1a:G1307S), C4321T, T22200G(V213G), G22578A(S:G339D), **G22599C(S:R346T),** C22674T(S:S371F), T22679C(S:S373P), C22686T(S:S375F), A22688G(S:T376A), G22775A(S:D405N), A22786C(S:R408S), G22813T(S:K417N), T22882G(S:N440K), G22992A(S:S477N), T23018G(S:F486V), A23055G(S:Q498R), A23063T(S:N501Y), T23075C(S:Y505H), C26060T(Orf3a:T223I), C26270T(E:T9I), G26529A(M:D3N), C26577G(M:Q19E), G26709A(M:A63T), C27012T, C27513T, C27807T, C27889T, A28271T, C28311T(N:P13L, Orf9b:P10S), A28330G(Orf9b:D16G), del28362-28370(N:31-33del, Orf9b:27-29del), G28881A(N:R203K), G28882A(N:R203K), G28883C(N:G204R), A29510C(N:S413R), del29734-29759
Extra mutations in BA.5 sector:
T493C(Orf1a:T568I), C1968T, C3602T(Orf1a:H1113Y), C5869T, del22287-22304(S:del242-247, Y248H), T22307A(S:L249M), T22896C(S:V445A), G22898A(S:G446S), A23013T(S:E484V), del25456-25482(Orf3a:del22-30), T25584Crev, G26020T(Orf3a:D210Y), A27976G(Orf8:H28R) 

Mutations from the AY.122.1-liked donor:
C7124T(Orf1a:P2287S), C8986T, G9053T(Orf1a:V2930L), A11201G(Orf1a:T3646A), A11332G, G15451A(Orf1b:G662S), C16466T(Orf1b:P1000L), C19220T(Orf1b:A1918V), **C19983T, G20937T,** C21618G, G21987A(S:G142D), del22029-22034(S:del156-157, R158G), C23604G(S:P681R), G24410A(S:D950N) 
Extra mutations in 21J sector:
C8389T, C8964T(Orf1a:S2900L), C9967T, C10336T, C13680T, C14189T(Orf1b:A241V), C14408T(Orf1b:P314L), C14425A(Orf1b:L320I), C15588T, C15960T, G16377A, T16542C, A16638G, C18115T(Orf1b:C18115T), T19074C, T19893C, G19981A(Orf1b:V2172I), C20234T(Orf1b:P2256L), G20274T(Orf1b:M2260I), G21604T(S:Q14H), C21627T(S:T22I), C21635T(S:P25S), T21802G(S:D80E), T21973G(S:N137K), T23934Crev(S:I791Trev), C23939T(S:P793S), C24138A(S:T859N)

Mutations from unknown source:
del22190-22192(S:I210-), C23248T, A23265G(S:D568G), T23434G(S:I624M)

**Comment by Over-There-Is** [comment]
Shanxi/TYCDC300/2023|EPI_ISL_18495231|2023-06-23 FR.1/EG.5.1
Shanxi/TYCDC352/2023|EPI_ISL_18495283|2023-07-07 FY.3.2/EG.5.1
Shanxi/TYCDC350/2023|EPI_ISL_18495281|2023-07-07 XBB.1.42.2/EG.5.1
Gansu/QYCDC-693/2023|EPI_ISL_18495563|2023-06-23 FY.3.3/EG.5.1
Gansu/QYCDC-704/2023|EPI_ISL_18495569|2023-06-28 EG.5.1.1/FY.3
Gansu/QYCDC-696/2023|EPI_ISL_18495566|2023-06-27 EG.5.1.1/FL.2.3
Gansu/QYCDC-897/2023|EPI_ISL_18495577|2023-09-01 XBB.1.9.1/EG.5.1.1
Shanxi/TYCDC423/2023|EPI_ISL_18495354|2023-08-04 FU.1/?
some could be contamination, but I have no time to analyze right now.

**Comment by FedeGueli** [comment]
> Shanxi/TYCDC300/2023|EPI_ISL_18495231|2023-06-23 FR.1/EG.5.1 Shanxi/TYCDC352/2023|EPI_ISL_18495283|2023-07-07 FY.3.2/EG.5.1 Shanxi/TYCDC350/2023|EPI_ISL_18495281|2023-07-07 XBB.1.42.2/EG.5.1 Gansu/QYCDC-693/2023|EPI_ISL_18495563|2023-06-23 FY.3.3/EG.5.1 Gansu/QYCDC-704/2023|EPI_ISL_18495569|2023-06-28 EG.5.1.1/FY.3 Gansu/QYCDC-696/2023|EPI_ISL_18495566|2023-06-27 EG.5.1.1/FL.2.3 Gansu/QYCDC-897/2023|EPI_ISL_18495577|2023-09-01 XBB.1.9.1/EG.5.1.1 Shanxi/TYCDC423/2023|EPI_ISL_18495354|2023-08-04 FU.1/? some could be contamination, but I have no time to analyze right now.

wrong issue

**Comment by FedeGueli** [comment]
> It is doubtless BA.5.2/21J recombinant. 21846 is provided by the Delta donor, but not mutated. So its Delta donor is probably not on S:T95I branch. It has G22599C, the BA.5.2 donor could be assumed as BA.5.2.6 temporally. And it also has C19983T and G20937T, and its 1048 and 25516 is covered by BA.5.2. So the Delta donor could be also assumed as AY.122.1. But it has no C23934T.
> 
> Breakpoints: 22B 6402~7124 21J 21J 22034~22200 22B 22B 23075~23525 21J 21J 24469~25000 22B
> 
> Mutations based on B.1: T493C, T670G, C1627T, C1968T, C2790T, C3602T, G4184A, C4321T, C5869T, C7124T, C8389T, C8964T, C8986T, G9053T, C9967T, C10029T, C10336T, A11201G, A11332G, C13680T, C14189T, C14425A, G15451A, C15588T, C15960T, G16377A, C16466T, T16542C, A16638G, C18115T, T19074C, C19220T, T19893C, G19981A, C19983T, C20234T, G20274T, G20937T, G21604T, C21618G, C21627T, C21635T, T21802G, T21973G, G21987A, del22029-22034, del22190-22192, T22200G, del22287-22304, T22307A, G22578A, G22599C, C22674T, T22679C, C22686T, A22688G, G22775A, A22786C, G22813T, T22882G, T22896C, G22898A, T22917G, G22992A, C22995A, A23013T, T23018G, A23055G, A23063T, T23075C, C23248T, A23265G, T23434G, C23604G, C23939T, C24138A, G24410A, C25000T, del25456-25482, G26020T, C26060T, C26270T, G26529A, C26577G, G26709A, C27012T, C27513T, C27807T, C27889T, A27976G, A28271T, C28311T, A28330G, del28362-28370, G28881A, G28882A, G28883C, A29510C, del29734-29759
> 
> Mutations shared by both lineage: C10029T(Orf1a:T3255I), G21987A(S:G142D), T22917G(S:L452R), C22995A(S:T478K)
> 
> Mutations from the BA.5.2.6-liked donor: T670G(Orf1a:R135S), C1627T, C2790T(Orf1a:T842I), G4184A(Orf1a:G1307S), C4321T, T22200G(V213G), G22578A(S:G339D), **G22599C(S:R346T),** C22674T(S:S371F), T22679C(S:S373P), C22686T(S:S375F), A22688G(S:T376A), G22775A(S:D405N), A22786C(S:R408S), G22813T(S:K417N), T22882G(S:N440K), G22992A(S:S477N), T23018G(S:F486V), A23055G(S:Q498R), A23063T(S:N501Y), T23075C(S:Y505H), C26060T(Orf3a:T223I), C26270T(E:T9I), G26529A(M:D3N), C26577G(M:Q19E), G26709A(M:A63T), C27012T, C27513T, C27807T, C27889T, A28271T, C28311T(N:P13L, Orf9b:P10S), A28330G(Orf9b:D16G), del28362-28370(N:31-33del, Orf9b:27-29del), G28881A(N:R203K), G28882A(N:R203K), G28883C(N:G204R), A29510C(N:S413R), del29734-29759 Extra mutations in BA.5 sector: T493C(Orf1a:T568I), C1968T, C3602T(Orf1a:H1113Y), C5869T, del22287-22304(S:del242-247, Y248H), T22307A(S:L249M), T22896C(S:V445A), G22898A(S:G446S), A23013T(S:E484V), del25456-25482(Orf3a:del22-30), T25584Crev, G26020T(Orf3a:D210Y), A27976G(Orf8:H28R)
> 
> Mutations from the AY.122.1-liked donor: C7124T(Orf1a:P2287S), C8986T, G9053T(Orf1a:V2930L), A11201G(Orf1a:T3646A), A11332G, G15451A(Orf1b:G662S), C16466T(Orf1b:P1000L), C19220T(Orf1b:A1918V), **C19983T, G20937T,** C21618G, G21987A(S:G142D), del22029-22034(S:del156-157, R158G), C23604G(S:P681R), G24410A(S:D950N) Extra mutations in 21J sector: C8389T, C8964T(Orf1a:S2900L), C9967T, C10336T, C13680T, C14189T(Orf1b:A241V), C14408T(Orf1b:P314L), C14425A(Orf1b:L320I), C15588T, C15960T, G16377A, T16542C, A16638G, C18115T(Orf1b:C18115T), T19074C, T19893C, G19981A(Orf1b:V2172I), C20234T(Orf1b:P2256L), G20274T(Orf1b:M2260I), G21604T(S:Q14H), C21627T(S:T22I), C21635T(S:P25S), T21802G(S:D80E), T21973G(S:N137K), T23934Crev(S:I791Trev), C23939T(S:P793S), C24138A(S:T859N)
> 
> Mutations from unknown source: del22190-22192(S:I210-), C23248T, A23265G(S:D568G), T23434G(S:I624M)

great analysis thx

**Comment by Over-There-Is** [comment]
It's still not sure whether the Delta donor AY.122.1 or not, it's just an assumption. One of the definition mutations is reversed.(T23934Crev, S:I791Trev)

**Comment by FedeGueli** [comment]
> It's still not sure whether the Delta donor AY.122.1 or not, it's just an assumption. One of the definition mutations is reversed.(T23934Crev, S:I791Trev)

AY.122 has not 791 as def

**Comment by Over-There-Is** [comment]
I did not found that there are lots of AY.122+C19983T, G20937T without S:T791I yesterday. Of course, the donor could be it.

**Comment by Over-There-Is** [comment]
I suggest using C19983T, G20937T, C27012T, C27513T as query.

**Comment by Over-There-Is** [comment]
Another possibility: The BA.5.2 donor could be from C27012T, C27513T> T493C> G26020T(Orf3a:D210Y) branch, and S:R346T is convergent.

**Comment by FedeGueli** [comment]
Luckily we can close this one.

**Comment by Vnes97** [comment]
> I believe it is the first Delta/Omicron recombinant to have the Delta S2 rather than the Omicron S2

Just FYI, a Belgium Deltacron (EPI_ISL_15537619) in 2022 had a breakpoint just beside the FCS (Omicron S:N679K+ Delta S:P681R), and it carried the whole Delta S2.

**Comment by FedeGueli** [comment]
> > I believe it is the first Delta/Omicron recombinant to have the Delta S2 rather than the Omicron S2
> 
> Just FYI, a Belgium Deltacron (EPI_ISL_15537619) in 2022 had a breakpoint just beside the FCS (Omicron S:N679K+ Delta S:P681R), and it carried the whole Delta S2.

Thank you very much.
